### ISSUE TITLE
链接草料二维码官方数据库

### ISSUE THREAD

**Issue by Feis231** [jeecgboot/JimuReport#1002]
##### 错误日志&截图：
数据库连接失败：Could not connect to address=(host=127.0.0.1)(port=3306)(type=master) : (conn=122165) Access denied for user 'cli_49303652'@'172.17.0.1' (using password: YES) Current charset is UTF-8. If password has been set using other charset, consider using option 'passwordCharacterEncoding'

##### 重现步骤：
数据源新建，填入所有信息，无法连接。但是草料二维码只能提供 主机地址、端口、数据库、用户名、密码等信息。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
详细说明

**Comment by Feis231** [comment]
不会链接草料官方的数据库.........
