### ISSUE TITLE
报表角标显示异常

### ISSUE THREAD

**Issue by Yxw521** [jeecgboot/JimuReport#1004]
##### 问题描述：
125⁰₋₂℃；2h±0.5h
库里存的是上面的报表显示为(〖150〗_(-2)^0℃；2h±0.5h)

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/76502207/168961887-2c318880-bf4a-471b-80a5-e4f2e8cc78b2.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/169507077-0a069af5-3a24-470d-bccc-d298072b4f58.png)
我用你的数据未复现此问题
你可以在官网上做个示例，把示例id贴上来
