### ISSUE TITLE
关于数据字典多选值（比如0,2）报表回显时的问题

### ISSUE THREAD

**Issue by yijian0645** [jeecgboot/JimuReport#1005]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/14273752/169008670-a1b56945-a4b4-4681-ba37-10675ec2a716.png)

![image](https://user-images.githubusercontent.com/14273752/169008793-0391e0fe-a030-4530-8f33-9c81e7676259.png)

![image](https://user-images.githubusercontent.com/14273752/169008919-a0ede5c5-05a9-4a7f-a8df-1e86e9af8e9a.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
gitee 已收录 
关闭此问题

**Comment by ljl120** [comment]
这个是怎么解决的？我也遇到了
