### ISSUE TITLE
在预览界面使用PDF导出功能时报错

### ISSUE THREAD

**Issue by wu-jun-3** [jeecgboot/JimuReport#1007]
##### 问题描述：
在预览界面使用PDF导出功能时显示导出错误的提示

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/105835485/169199509-6133b92a-1b43-4aeb-a601-7496f5c34b62.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by wu-jun-3** [comment]
有可以设置导出类型的地方吗？PDF报错可能是因为表格中的数据太多了，如何直接将PDF导出在导出功能中移除并保留其他导出功能

**Comment by lvdandan16** [comment]
升级最新版本试一下
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.5.0-beta</version>
</dependency>
```
