### ISSUE TITLE
预览不显示工具栏

### ISSUE THREAD

**Issue by dewen2018** [jeecgboot/JimuReport#1010]
##### 错误日志&截图：

![6{G%~81P$JPMB (X26361W](https://user-images.githubusercontent.com/41216978/169437611-c9374ff3-11f0-4ca8-a264-75c7c2a92932.png)

##### 重现步骤：
自己通过设计的打印报表，SQL数据源

**Comment by lvdandan16** [comment]
参考文档：http://report.jeecg.com/2384071
看是不是把预览工具条关闭了

**Comment by dewen2018** [comment]
ou,yes,thank you!
