### ISSUE TITLE
同一报表中放置多个数据源表格，与图表混合排版时，数据表会部分被遮挡

### ISSUE THREAD

**Issue by raymondsstar** [jeecgboot/JimuReport#1013]
##### 版本号：

1.5.0-beta

##### 问题描述：

多个 API 数据源（数据表）与图表排版时，数据表会出现数据行部分缺失（不显示）的现象。

##### 错误日志&截图：

图1：设计时的情况

![1](https://user-images.githubusercontent.com/105854452/169726265-db533dd6-842b-456a-bcbd-cb8d78f74013.png)

图2：实际数据查询情况

![2](https://user-images.githubusercontent.com/105854452/169726279-9b652566-5dcb-4e5c-8c73-a2a24c807a6f.png)

##### 重现步骤：

按下列步骤可以必然重现：

1、创建两个 API 数据源（只测试过API数据源，未测试过 SQL 数据源），分别对应两张数据表。

2、在设计模板中加入 API 数据源1，往下隔开一个空行，再添加第二个 API数据源2。其中数据源1、数据源2的数据行需要足够多，例如：10行。

3、再往下隔开一个空行，添加柱状图，不需要指定数据源，按默认设置。

4、预览该模板，即可发现数据源1或数据源2对应的表格中缺失了某些行。

**Comment by raymondsstar** [comment]
补充：新发现的规律
当图表贴边时，不会有这个缺陷：
![3](https://user-images.githubusercontent.com/105854452/169735163-704b71f9-4d89-4abd-974a-a24594e57907.png)

当图表离边缘有一个单元格时，问题必然重现：
![4](https://user-images.githubusercontent.com/105854452/169735201-33e34ea5-594c-4d8e-a2bb-5581a823824e.png)

目前通过调整排版布局来规避这个缺陷

**Comment by lvdandan16** [comment]
收录ws

**Comment by lvdandan16** [comment]
请导出报表配置及数据，我们复现一下

**Comment by raymondsstar** [comment]
[jimu.zip](https://github.com/jeecgboot/JimuReport/files/8801702/jimu.zip)
报表定义见附件，全部使用 api 数据源。被覆盖导致表格缺失的数据源名称为 project_plan、project_key_task、project_hightlight_task，应该随便找些数据（数据行要足够多）就能复现。

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
