### ISSUE TITLE
竖列合并，集合的不合并

### ISSUE THREAD

**Issue by yufuxin01** [jeecgboot/JimuReport#1015]
##### 版本号：
1.4.1

##### 问题描述：
竖列合并，集合的不合并
##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/77772498/169731986-9bf0f2c5-43ab-4c19-a56c-0c5d9c4fbd81.png)
![image](https://user-images.githubusercontent.com/77772498/169732032-3d2b42f1-ae16-4fd1-b5cd-c2ef56a619b9.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请详细描述问题

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
