### ISSUE TITLE
Mongodb连接问题

### ISSUE THREAD

**Issue by roy-long** [jeecgboot/JimuReport#1016]
##### 问题描述：
           积木报表连接mongodb，单机模式可以连接，副本集连接不上

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/28853880/169931842-ba772570-fb23-4b06-b58f-258640a8ac83.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
数据集？
参考文档：http://report.jeecg.com/2426229

**Comment by roy-long** [comment]
抱歉，你可能没有明白我的意思，我意思是mongodb单机连接是没有问题的，但是mongodb的集群副本集连接是有问题的，是不是源码写死了指定类型为单机连接




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月27日(星期五) 晚上7:10
收件人: ***@***.***&gt;; 
抄送: "just ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/JimuReport] Mongodb连接问题 (Issue #1016)





 
数据集？
 参考文档：http://report.jeecg.com/2426229

**Comment by lvdandan16** [comment]
不支持
归集到：#138
