### ISSUE TITLE
关于查询日期显示到报表里面

### ISSUE THREAD

**Issue by ych6666** [jeecgboot/JimuReport#1017]
##### 版本号：
1.4.0

##### 问题描述：
怎么将查询日期显示到左下方

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/89495170/169941794-40a0166a-cf44-4c44-8a08-bcca6cb98c28.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by ych6666** [comment]
![image](https://user-images.githubusercontent.com/89495170/169951833-2a62354c-93b5-437f-95d4-9add27f1b3c7.png)
解决了，但是两个日期之间不能加任何修饰，比如文字、符号等

**Comment by lvdandan16** [comment]
参考文档：http://report.jeecg.com/2306130
