### ISSUE TITLE
内网无法访问百度统计，导致报表显示不出来

### ISSUE THREAD

**Issue by Zeno118** [jeecgboot/JimuReport#1018]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
如何重现呢

**Comment by oyrc** [comment]
我也是内网开发，我的解决办法是把依赖包解压并找到 **jimureport-spring-boot-starter-1.4.3\templates\jmreport\desreport\common\tj.ftl** 然后打开 注释掉<script></script>里面的内容。然后重新打包上传到公司的maven仓库即可。

**Comment by zhangdaiscott** [comment]
1.5.0已经修改，请确认
