### ISSUE TITLE
积木报表excel导出大数据报错

### ISSUE THREAD

**Issue by zttzhou** [jeecgboot/JimuReport#1020]
##### 版本号：

15.0beta
##### 错误日志&截图：
积木报表excel导出大数据报错,
{"success":false,"message":"鎿嶄綔澶辫触锛孒andler dispatch failed; nested exception is java.lang.OutOfMemoryError: GC overhead limit exceeded","code":500,"result":null,"timestamp":1653440936611}

##### 重现步骤：
报表数据量85000条，点击导出EXCEL导出文件中含报错信息，{"success":false,"message":"鎿嶄綔澶辫触锛孒andler dispatch failed; nested exception is java.lang.OutOfMemoryError: GC overhead limit exceeded","code":500,"result":null,"timestamp":1653440936611}

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by yufuxin01** [comment]
感觉这么大的数据量可以用easeExcel啥的

**Comment by lvdandan16** [comment]
收录 #138
