### ISSUE TITLE
打印设计：设计出来的报表预览和打印的时候无缘无故多出一行空白行

### ISSUE THREAD

**Issue by tb2888** [jeecgboot/JimuReport#1021]
##### 版本号：
1.4.0

##### 问题描述：
打印设计：设计出来的报表预览和打印的时候无缘无故多出一行空白行

##### 错误日志&截图：
打印设计时：
![image](https://user-images.githubusercontent.com/55084864/170228885-f4647be2-24fe-467c-89d4-f2cb20a95c07.png)
预览时：
![image](https://user-images.githubusercontent.com/55084864/170228751-7a83192a-849c-47b2-a8f9-96fb0f0814c7.png)
打印时：
![image](https://user-images.githubusercontent.com/55084864/170229038-67a02252-c507-4491-8fe5-395da86783c1.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by tb2888** [comment]
如图把#号换成$就可以了，怎么回事？拖过来默认又是#
![image](https://user-images.githubusercontent.com/55084864/170404699-67b2f9e9-cebb-4ad8-ba45-25f2742ca6cf.png)
![image](https://user-images.githubusercontent.com/55084864/170404742-a394c5a7-3d68-4044-b351-09ea35512fc0.png)
![image](https://user-images.githubusercontent.com/55084864/170404765-ade09b6c-2b10-46ab-87b4-a0b4c3138045.png)

**Comment by lvdandan16** [comment]
参考文档：http://report.jeecg.com/2233183
