### ISSUE TITLE
二维码布局打印时bug

### ISSUE THREAD

**Issue by yanwencheng** [jeecgboot/JimuReport#1023]
##### 版本号：
1.5.0

##### 问题描述：

二维码在报表浏览时布局位置正常，打印预览时发生位置bug
##### 错误日志&截图：

1、设计时
![image](https://user-images.githubusercontent.com/11845393/170638802-89e4432d-0bad-4b0d-a2f1-c2457135ea75.png)
2、报表预览时
![image](https://user-images.githubusercontent.com/11845393/170638605-811b9202-5df2-42c7-bbc6-d6090e250d3e.png)
3、打印预览时出现bug
![image](https://user-images.githubusercontent.com/11845393/170638702-abdc540c-3d2d-4cbf-9d9f-7e72f2560c1e.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by lvdandan16** [comment]
请导出报表配置及数据，我们复现一下
