### ISSUE TITLE
柱状图数字展示重叠

### ISSUE THREAD

**Issue by yufuxin01** [jeecgboot/JimuReport#1025]
##### 版本号：

1.4.1
##### 问题描述：
柱状图数字展示重叠，可以
![image](https://user-images.githubusercontent.com/77772498/170668616-e367844b-3cb5-4733-bc8a-7bc3ea931176.png)

竖着数字展示吗
![Uploading image.png…]()

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持
收录 ws

**Comment by yufuxin01** [comment]
可以让他竖着展示在柱状图里边

**Comment by yufuxin01** [comment]
也可以设置一下字体让他歪一下

**Comment by yufuxin01** [comment]
![image](https://user-images.githubusercontent.com/77772498/171607986-b46d9e53-5e52-4c3b-9526-84b5622f8d0f.png)

**Comment by 1298191366** [comment]
已修复，待新版本发布
