### ISSUE TITLE
sql数据集datetime类型数据，返回UTC时间格式没法进行日期格式化

### ISSUE THREAD

**Issue by sdmq** [jeecgboot/JimuReport#1028]
##### 版本号：
1.5.0
##### 问题描述：
sql数据集 datetime 类型数据返回数据  1988-12-15T00:00   数据格式T 没法进行数据格式化
![image](https://user-images.githubusercontent.com/6269663/170697673-f7b38600-03d5-42a5-b801-14b483210d0f.png)

##### 错误日志&截图：
直接在jeecg-boot在线演示中可以看到
http://api3.boot.jeecg.com/jmreport/view/1338769064067076098

##### 重现步骤：
直接在jeecg-boot低代码在线演示中可以看到
http://api3.boot.jeecg.com/jmreport/view/1338769064067076098
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by yufuxin01** [comment]
你在数据处理的时候给字符串转化一下，dateformat一下

**Comment by lvdandan16** [comment]
已修复，下个版本升级
