### ISSUE TITLE
Tomcat8.5部署启动时存在线程无法停止,导致实例停止,启动失败

### ISSUE THREAD

**Issue by Acechengui** [jeecgboot/JimuReport#1030]
##### 版本号：
1.5.0.beta  以及 1.5.0

##### 问题描述：

Tomcat8.5部署启动时存在线程无法停止,导致实例停止,启动失败;本地idea使用tomcat9启动无问题,切换至1.4.4.beta版本才恢复正常
##### 错误日志&截图：
![AXO4AOC%WF$CRZ@V@ (FOB8](https://user-images.githubusercontent.com/63096199/170819683-b0676c62-8ba0-46e1-93b0-64735aeabc82.png)
![`R_)$V1FC@BS$U%1F~@U%GR](https://user-images.githubusercontent.com/63096199/170819703-17de6e0d-6c86-46e7-bc46-4b7ffa11ef95.jpg)

##### 重现步骤：
普通的spring boot项目, version:2.4.5;
集成积木报表之后,打成war包使用tomcat8.5部署

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
请使用jar包启动

**Comment by tygithub1** [comment]
还有一种方法解决： 
war包解压后将项目的驱动依赖(/WEB-INFO/lib下的驱动包)移到tomcat的lib下
