### ISSUE TITLE
积木报表连接数据源成功，但是点击确认报错

### ISSUE THREAD

**Issue by sml-bun** [jeecgboot/JimuReport#1034]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/53103175/171080721-2ffc194a-b6cb-4580-aa26-69387e704166.png)
![image](https://user-images.githubusercontent.com/53103175/171080844-9301e0eb-bc45-4eec-b75d-dc9ef73baa9f.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
哪个版本？

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题

**Comment by sml-bun** [comment]
1.4.0




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月2日(星期四) 下午5:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 积木报表连接数据源成功，但是点击确认报错 (Issue #1034)





 
哪个版本？
