### ISSUE TITLE
sql 输入了公式后，报表查询不到数据，但是预览数据可以。输入公式后，数据集就成了一样的字段了。

### ISSUE THREAD

**Issue by XuNuoZ** [jeecgboot/jimureport#1036]
##### 错误日志&截图：
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/42367621/171382642-3b8c67d7-d88a-49ce-8bcc-312608645202.png">

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/42367621/171382874-796fd05d-4362-4a44-be8f-de78bc81f25c.png">

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/42367621/171382914-25b86ba9-adcb-4662-bc31-c0b6b1cb86dd.png">

##### 重现步骤： 配置数据集---输入包含公式的sql

```
select  mx.brand_no, mx.cell,mx.indate,b.cname,avg(mx.kl),avg(mx.praarea),
sum(mx.price_in),sum(mx.num_bs),sum(mx.price_ss *  mx.sale_num)
from cx_salemxz mx,cx_brand b
where mx.brand_no=b.no
group by  mx.brand_no, mx.cell,mx.indate,b.cname
order by sum(price_ss * sale_num) desc
```
sql解析正常，预览数据正常。但是制作报表的时候，包含公式的sql就查询不出来了。

<img width="990" alt="image" src="https://user-images.githubusercontent.com/42367621/171384084-38c448d0-42a8-4200-b176-f0c4cd02f666.png">
字段也变成 公式的名称了。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by yufuxin01** [comment]
你选择的是正常还是数字
![image](https://user-images.githubusercontent.com/77772498/171423867-6526a33a-79c2-47a0-8cbf-f8cd3376c44f.png)
![image](https://user-images.githubusercontent.com/77772498/171423903-8bc82f37-e63f-4e8e-b4c4-f2fbfc080de1.png)
这俩地方，或者你直接导出看看有没有数据，感觉会有

**Comment by XuNuoZ** [comment]
> 你选择的是正常还是数字
> ![肖像](https://user-images.githubusercontent.com/77772498/171423867-6526a33a-79c2-47a0-8cbf-f8cd3376c44f.png)
> ![肖像](https://user-images.githubusercontent.com/77772498/171423903-8bc82f37-e63f-4e8e-b4c4-f2fbfc080de1.png)
> 这两个地方，或者你直接导出看看有没有数据，感觉会有

我试过了，不行呢

**Comment by lvdandan16** [comment]
SQL中统计函数需指定别名
