### ISSUE TITLE
报表导出excel失败

### ISSUE THREAD

**Issue by ych6666** [jeecgboot/JimuReport#1039]
##### 版本号：
1.4.32

##### 问题描述：
报表导出excel失败

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/89495170/171549729-45287ec0-1dbb-421b-8f8e-69908a026a1d.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by ych6666** [comment]
换成最新版本还是不行，重启mysql。也不行

**Comment by ych6666** [comment]
解决了，使用root账户启动账户就行了。那其他账户怎么办啊，总不能赋予最高权吧

**Comment by lvdandan16** [comment]
报什么错

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
