### ISSUE TITLE
html打印背景图显示不出来

### ISSUE THREAD

**Issue by gogorufei** [jeecgboot/JimuReport#1040]
##### 版本号：
1.5.0

##### 问题描述：
报表预览界面-打印-html打印，背景图显示不出来

##### 错误日志&截图：

![问题1](https://user-images.githubusercontent.com/102220736/171588919-3288de2d-203b-4c79-9f6e-6c174886bba8.jpg)

##### 重现步骤：

例如发票的预览界面-打印-html打印
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
套打的背景不会显示，其他设置为背景图片的不受影响
