### ISSUE TITLE
SQL数据集的报表字段明细中设置了日期范围查询，不能以${}传参的形式，传回sql中

### ISSUE THREAD

**Issue by yzmking** [jeecgboot/JimuReport#1041]
##### 版本号：
1.4.0

##### 问题描述：
SQL数据集的报表字段明细中设置了日期范围查询，不能以${}传参的形式，传回sql中

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/44563730/171598437-537f64dc-56a1-42dc-8af5-e9b13564aa25.png)
![image](https://user-images.githubusercontent.com/44563730/171598490-4efaf0a1-1b09-4e4a-a660-a1d2a1df9dc4.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
使用问题：报表字段明细中可直接查询，${}是在报表参数中设置
参考文档 ：
http://report.jeecg.com/2373404
http://report.jeecg.com/2373405
