### ISSUE TITLE
第一个不保留两位小数，第二个保留两位小数

### ISSUE THREAD

**Issue by yufuxin01** [jeecgboot/JimuReport#1043]
##### 版本号：
1.4.1

##### 问题描述：
![1654173565(1)](https://user-images.githubusercontent.com/77772498/171631136-1a05fc6a-ccb7-48ef-ab83-bb949c59139f.jpg)

##### 错误日志&截图：
第一个不保留两位小数，第二个保留两位小数

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
不支持，如果是数据库你可以自行格式化，api，如果标题太长，1.5.0版本支持数值旋转
数据库sql格式化
![image](https://user-images.githubusercontent.com/30997828/175797980-22352f2e-2c13-46f8-be22-7b5ebe326278.png)

api返回有两位小数即可
![image](https://user-images.githubusercontent.com/30997828/175797958-981dba72-1471-4974-9ab0-f53a11022ba0.png)

![image](https://user-images.githubusercontent.com/30997828/175797813-f8daf897-8301-4a9c-853c-c464e3f4523e.png)
