### ISSUE TITLE
折柱图的柱子粗细修改没效果，但是我改两个柱子可以渲染柱子的粗细

### ISSUE THREAD

**Issue by yufuxin01** [jeecgboot/JimuReport#1045]
##### 版本号：

1.4.1
##### 问题描述：
折柱图的柱子粗细修改没效果，但是我改两个柱子可以渲染柱子的粗细
![image](https://user-images.githubusercontent.com/77772498/171829218-4517dda8-eb41-47b5-a523-48f34e8d4cf4.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
未复现此问题
升级最新版本试一下
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.5.0</version>
</dependency>
```
