### ISSUE TITLE
报表参数中怎么使用日期范围查询

### ISSUE THREAD

**Issue by yzmking** [jeecgboot/JimuReport#1046]
##### 版本号：
1.4.0

##### 问题描述：
报表参数中怎么使用日期范围查询    需要在sql里某个位置添加日期范围查询，不是在整个sql外添加

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/44563730/172083968-a9d3e175-c0a4-4833-a7ab-7ac01843372e.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
报表参数为占位符，不可设为范围查看，可使用报表字段
参考文档：http://report.jeecg.com/2394748

**Comment by yzmking** [comment]
报表字段不行，因为时间条件要加在图上的那个位置，而你们的报表字段默认是加在整个sql的最外层，不能满足需求




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月10日(星期五) 下午4:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 报表参数中怎么使用日期范围查询 (Issue #1046)





 
报表参数为占位符，不可设为范围查看，可使用报表字段
 参考文档：http://report.jeecg.com/2394748

**Comment by lvdandan16** [comment]
那就只能用占位符方式，不支持范围

**Comment by yzmking** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月10日(星期五) 下午4:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 报表参数中怎么使用日期范围查询 (Issue #1046)





 
那就只能用占位符方式，不支持范围
