### ISSUE TITLE
打印时不分页 By pageSize

### ISSUE THREAD

**Issue by wuzhiping** [jeecgboot/JimuReport#1047]
##### 问题描述：阜阳检票数查询的例子
                              预览时候可以按pageSize分页
                              打印时没有按pageSize分页

##### 错误日志&截图：
![d997c532-e2fc-47ff-9f66-8877fe7238e1](https://user-images.githubusercontent.com/9571573/172110680-dba447bc-d927-4ff3-86e2-3f6ee4ceeb87.png)
![a1df31b3-c856-4951-b220-b1a7a935dfbc](https://user-images.githubusercontent.com/9571573/172110707-47510f26-8d3d-419b-acb0-6c9062edae77.png)

##### 重现步骤：点击 示例：阜阳检票数查询
                              点击预览
                              点击canvas打印

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
打印不支持按预览分页打印
