### ISSUE TITLE
1.4.1升级1.5.0时 报错

### ISSUE THREAD

**Issue by yufuxin01** [jeecgboot/JimuReport#1048]
##### 版本号：

1.5.0 是需要自己解决吗？还是大佬给个方案
##### 问题描述：
1.4.1升级1.5.0时

 @Autowired
    private IJmReportExportPdf jmReportExportPdf;

    @PostMapping({"/exportPdfNew"})
    public Result<Object> c(HttpServletRequest var1, HttpServletResponse var2, @RequestBody JSONObject var3) {
        HashMap var4 = new HashMap(var1.getParameterMap());
        a.info("===========exportPdf 执行导出PDF action ==========");
        boolean var5 = var4.containsKey("token");
        if (var5) {
            var4.remove("token");
        }

        String var6 = var3.getString("excelConfigId");
        JSONObject var7 = var3.getJSONObject("queryParam");

        var7.put("printAll", true);
        Result var8 = this.jmReportDesignService.show(var6, var7.toJSONString(), (List)null);
        JimuReport var9 = (JimuReport)var8.getResult();
        String jsonStr = var9.getJsonStr();
        a.error(jsonStr);
        boolean replaceSpaces = var3.getBoolean("replaceSpaces");
        if (replaceSpaces) {
            jsonStr=jsonStr.replace("\" ","\"\u00a0");
//            jsonStr=jsonStr.replace("\"   ","\"\u00a0\u00a0\u00a0");
//            jsonStr=jsonStr.replace("\"  ","\"\u00a0\u00a0");
        }
        a.error("change:"+jsonStr);
        JSONObject jsonObject = JSONObject.parseObject(jsonStr);
        JSONObject printConfig = jsonObject.getJSONObject("printConfig");
//        printConfig.put("paper","A3");
//        printConfig.put("width",842);
//        printConfig.put("height",1190);
        JSONObject newPageSize = var3.getJSONObject("newPageSize");
        if (newPageSize != null) {
            printConfig.put("paper",newPageSize.get("paper"));
            printConfig.put("width",newPageSize.get("width"));
            printConfig.put("height",newPageSize.get("height"));
            jsonObject.put("printConfig",printConfig);
            var9.setJsonStr(jsonObject.toJSONString());
        }

        String var10 = var1.getParameter("dpi");

        float var11 = 96.0F;

        if (var10 != null) {
            var11 = Float.parseFloat(var10);
        }

        JSONArray var12 = var3.getJSONArray("base64Arry");
        Map var13 = this.jmReportExportPdf.exportPdf(var9, var12, var11);
        return Result.OK(var13);
    }

错误日志

***************************
APPLICATION FAILED TO START
***************************

Description:

Field jmReportExportPdf in com.example.controller.ControllerExportPdf required a bean of type 'org.jeecg.modules.jmreport.desreport.service.IJmReportExportPdf' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'org.jeecg.modules.jmreport.desreport.service.IJmReportExportPdf' in your configuration.

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
pdf导出接口已经取消了，不支持使用了
http://report.jeecg.com/2518262
