### ISSUE TITLE
导出PDF失败

### ISSUE THREAD

**Issue by yufuxin01** [jeecgboot/JimuReport#1049]
##### 版本号：

1.4.1
##### 问题描述：

导出PDF失败

![image](https://user-images.githubusercontent.com/77772498/172172009-3df4712b-a5dc-4613-9e46-eee8e070dc4a.png)

![image](https://user-images.githubusercontent.com/77772498/172172038-6f127ef6-fe59-4600-826b-1fdbfa35cabc.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
先升级版本试一下，如果还报错，把错误贴上来
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.5.0</version>
</dependency>
```
