### ISSUE TITLE
柱状图导出excel 报错，没有图片，只有文字

### ISSUE THREAD

**Issue by yufuxin01** [jeecgboot/JimuReport#1050]
##### 版本号：
1.4.1

##### 问题描述：
柱状图导出excel 报错，没有图片，只有文字
![image](https://user-images.githubusercontent.com/77772498/172172994-d2f77fdd-da8d-4242-a93b-4a16c63c1b31.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级版本
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.5.0</version>
</dependency>
```
