### ISSUE TITLE
下拉框，选中后下拉框没有数据，清空掉内容才会出现所有的数据

### ISSUE THREAD

**Issue by YBenX** [jeecgboot/JimuReport#1051]
##### 版本号：
1.5.0

##### 问题描述：
下拉框，选中后下拉框没有数据，清空掉内容才会出现所有的数据
![image](https://user-images.githubusercontent.com/3353434/172285596-6863c296-60b6-4e8d-860c-e42a7dbbff26.png)
![image](https://user-images.githubusercontent.com/3353434/172285655-a5c1be20-b413-42ac-bd6a-dd51f6a6f26e.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
设计如此，支持搜索，选中后，会作为条件查询，所以只查询出一条数据
