### ISSUE TITLE
点开钻取报表，可以让子报表生成为新的路由页签吗

### ISSUE THREAD

**Issue by yzmking** [jeecgboot/JimuReport#1052]
##### 版本号：
1.4.2

##### 问题描述：
点开钻取报表，可以让子报表生成为新的路由页签吗

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/44563730/172330487-a811a728-930a-4b14-a492-95ce10143d8d.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
归集到：#138
