### ISSUE TITLE
配置customPrePath参数后，接口/jmreport/excelQuery?XXX访问报400错误

### ISSUE THREAD

**Issue by zxy443716654** [jeecgboot/JimuReport#1054]
##### 版本号：
<groupId>org.jeecgframework.jimureport</groupId>
<artifactId>jimureport-spring-boot-starter</artifactId>
<version>1.5.0</version>

##### 问题描述：
springcloud微服务配置customPrePath参数后，静态资源访问正常，但是

##### 错误日志&截图：
![企业微信截图_1654595869311](https://user-images.githubusercontent.com/65385465/172352731-82f969ad-500f-4738-8f5f-2c1c8183a14b.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
