### ISSUE TITLE
柱状图数字显示可以用科学计数法吗

### ISSUE THREAD

**Issue by yufuxin01** [jeecgboot/JimuReport#1055]
##### 版本号：
1.4.1

##### 问题描述：
![image](https://user-images.githubusercontent.com/77772498/172398897-7d67a499-9cc2-4419-b756-5a354e40d770.png)
柱状图数字显示可以用科学计数法吗
显示成这样的
![image](https://user-images.githubusercontent.com/77772498/172399049-e11de81a-43a7-44bd-986b-c6a5af7dac7f.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by yufuxin01** [comment]
带着千分位的

**Comment by lvdandan16** [comment]
不支持
