### ISSUE TITLE
导出时怎么指定不导出某列

### ISSUE THREAD

**Issue by yzmking** [jeecgboot/JimuReport#1057]
##### 版本号：
1.4.2

##### 问题描述：
导出时怎么指定不导出某列，导出时不需要 ‘操作’ 这一列

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/44563730/172567570-8fb22cbd-78c2-44cb-bbbf-2342717e398f.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持

**Comment by yzmking** [comment]
好的谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月10日(星期五) 下午4:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 导出时怎么指定不导出某列 (Issue #1057)





 
不支持
