### ISSUE TITLE
积木报表求和之后再计算百分比,没有函数实现次功能

### ISSUE THREAD

**Issue by tianbb** [jeecgboot/JimuReport#1058]
##### 问题描述：
报表 有三列   10条数据,最底下 加了一行合计 使用DBSUM(A),DBSUM(B)  第三列合计 需要把前面两个相除..没发现函数可以实现此效果

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/33417115/172581826-17b8ad33-9fa2-41ca-b81a-8e1eb85bea07.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持
归集：#138

**Comment by zwdgit** [comment]
现在是否支持此功能
