### ISSUE TITLE
JS增强中的metaGet请求api接口的前缀能否使用yml的配置apiBasePath作为接口前缀或增加一个新的默认前缀配置

### ISSUE THREAD

**Issue by YBenX** [jeecgboot/JimuReport#1059]
##### 版本号：

1.5.0
##### 问题描述：
![T83EU3T})YX` XJJW436`H9](https://user-images.githubusercontent.com/3353434/172765759-78fc6996-8b40-4801-96ff-69f60270fd6e.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持
归集到 #138
