### ISSUE TITLE
项目不联网时，无法请求https://hm.baidu.com/hm.js，页面加载需要十几秒，特别慢

### ISSUE THREAD

**Issue by javayc** [jeecgboot/JimuReport#1061]
##### 错误日志&截图：
![0fa21f45c001e90e64b575be496462b](https://user-images.githubusercontent.com/23695331/172821083-ad090e5e-b163-406c-8b11-e4cb2f525531.jpg)
![b7a511c0962ccdba5542fe86e8debbe](https://user-images.githubusercontent.com/23695331/172821178-3c889c78-1e78-48aa-ade4-57628300231d.jpg)

##### 重现步骤：
本地不联网，启动工程（示例工程），预览报表，此时加载非常慢，f12查看网络请求，发现https://hm.baidu.com/hm.js需要联网请求，导致无法下载

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
已修复，下个版本升级
