### ISSUE TITLE
新建报表 白屏 加载，无法操作

### ISSUE THREAD

**Issue by capewang** [jeecgboot/JimuReport#1063]
##### 版本号：
04-18    1.5    离线版
##### 问题描述：
打开本地web管理网址后， 选择新建报表，一直白屏，在加载中

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/61097665/172833235-a8723736-4c55-4f80-8ec3-4df2616f877f.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
看报什么错，是不是接口不通

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
