### ISSUE TITLE
积木SDK安全扫面漏洞问题

### ISSUE THREAD

**Issue by Zoe-Zhu** [jeecgboot/JimuReport#1065]
##### 版本号：
1.5.0

##### 问题描述：
dependencyCehck 扫描出积木报表1.5.0版本的安全漏洞，有部分是否可以排除或修复？
![image](https://user-images.githubusercontent.com/22297885/172979272-7107db9c-352b-409b-b59f-760378d44cee.png)

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/22297885/172979280-8468c29b-3217-451d-9bb9-086d80bae2bd.png)

##### 重现步骤：
dependencyCheck 扫描安全漏洞

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws
