### ISSUE TITLE
我想知道如何根据用户获取其创建的报表

### ISSUE THREAD

**Issue by lijia150** [jeecgboot/JimuReport#1067]
##### 版本号：
1.5.0-beta

##### 问题描述：
我传入token可以获取到用户，请问我想在首页列表页面只想看到此用户创建的报表，请问如何操作？谢谢！

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
对接完token  开启saas模式
参考文档：http://report.jeecg.com/2302149
