### ISSUE TITLE
查询条件下拉框最右边增加一个清空功能

### ISSUE THREAD

**Issue by YBenX** [jeecgboot/JimuReport#1068]
##### 版本号：

1.5.0
##### 问题描述：
查询条件下拉框最右边增加一个清空功能，否则操作太不方便了，没法下拉显示其他项，每次都要手动清空
![image](https://user-images.githubusercontent.com/3353434/173276830-7c3e7698-e01e-4e75-9fc8-42706c71643a.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
