### ISSUE TITLE
折柱图的左Y轴和右Y轴的刻度比例尺如何能保持一致

### ISSUE THREAD

**Issue by Macaroms** [jeecgboot/JimuReport#1069]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/51771606/173297276-f118df12-d4dd-4f30-acb7-fcb78e7e6ad3.png)

##### 重现步骤：
创建一个折柱图，使用默认静态数据

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
你说的左Y轴和右Y轴的刻度比例尺如何能保持一致，指的是的是两边的刻度数值一致，还是指的是两边的刻度数量一致
