### ISSUE TITLE
1.4.1 可以支持PDF 导出时候设置PDF宽高，升了1.5.0这个功能就用不了，这个功能对项目作用很大，1.5.0没找到支持的接口

### ISSUE THREAD

**Issue by yufuxin01** [jeecgboot/JimuReport#1071]
##### 版本号：
1.4.1

##### 问题描述：
1.4.1 可以支持PDF 导出时候设置PDF宽高，升了1.5.0这个功能就用不了，这个功能对项目作用很大，1.5.0没找到支持的接口

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
1.5.0取消了接口
