### ISSUE TITLE
【pdf导出】为什么要取消pdf导出功能？这个对整个使用影响非常大！

### ISSUE THREAD

**Issue by Zoe-Zhu** [jeecgboot/JimuReport#1072]
##### 版本号：
1.5.0

##### 问题描述：
导出功能取消，导致无法正常使用积木的sdk

##### 错误日志&截图：
/jmreport/exportpdf 导出接口报404

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
1.5.0不再支持导出接口
