### ISSUE TITLE
无法获取AbstractFunction 中 call方法的env 的值

### ISSUE THREAD

**Issue by jsbzg** [jeecgboot/JimuReport#1074]
##### 版本号：
1.5.0-beta
##### 问题描述：
自定义DivFunction extends AbstractFunction，无法获取call方法中的Map<String, Object> env 内容为空。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jsbzg** [comment]
使用的是单元格表达式，但是无法获取获取单元格值

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
env里面本来就是空的，他是在arg1里面的，是通过`ExpressUtil.getArgString`进行获取,arg是你有多少位就需要配置几个，如

![image](https://user-images.githubusercontent.com/30997828/175798136-bd89e8d3-19b8-4515-9ff2-a64fc9b7f2ab.png)
![image](https://user-images.githubusercontent.com/30997828/175798230-96506a76-f628-4e71-aed9-f697345803a7.png)
