### ISSUE TITLE
报表创建完成后，在预览界面导出为excel后，报表中的样式丢失

### ISSUE THREAD

**Issue by xieza** [jeecgboot/JimuReport#1075]
##### 错误日志&截图：
预览界面：
![1655277106060](https://user-images.githubusercontent.com/30657799/173765343-46487b8d-13f1-4231-9f52-a606cf00fd67.png)
导出为excel：
![1655277172842](https://user-images.githubusercontent.com/30657799/173765515-cf63dc5f-0d00-41fd-a2cf-b184987449e2.png)

##### 重现步骤：
创建一个带有样式的报表，预览，导出为excel即可看到本问题

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
导出渲染样式数据量大时，会导致慢  1.5.0去掉了渲染样式

**Comment by guoai2015** [comment]
搞这么简单粗暴，想去掉就去掉了，好歹给个参数配置啊。
