### ISSUE TITLE
导出pdf内容消失

### ISSUE THREAD

**Issue by iu159** [jeecgboot/JimuReport#1076]
##### 问题描述：
导出pdf后选择框不见了，用的unicode编码实现的选择框

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/32712057/173790288-01ad6834-57d0-49b7-ae20-01416a295bcc.png)
![image](https://user-images.githubusercontent.com/32712057/173790372-3ebc29c1-276d-4586-8b5d-20cdb6498320.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
