### ISSUE TITLE
循环块遇上有合并单元格时，打印有问题

### ISSUE THREAD

**Issue by iGuozy** [jeecgboot/JimuReport#1077]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/48822119/173789702-28f58441-9243-4614-b527-13b5a121ab1c.png)
![image](https://user-images.githubusercontent.com/48822119/173792556-da6340d2-ecf2-4a66-a7ef-53818b79db70.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请导出报表配置及数据 或 在官网做示例，我们复现一下

**Comment by iGuozy** [comment]
我在积木报表的官网，增加了这个打印格式的示例，浏览地址是：
https://bootapi.jeecg.com/jmreport/shareView/698707311396737024

**Comment by iGuozy** [comment]
用Canvas打印，到第四页就会出现重复
![image](https://user-images.githubusercontent.com/48822119/174542707-4a93b4ff-f454-4e33-8a64-548d5af41f77.png)

**Comment by lvdandan16** [comment]
Canvas打印可能会有问题，后期可能会去掉，用html打印即可
html打印边框有问题，二维码没问题吧？

**Comment by iGuozy** [comment]
用html打印也会存在其他问题的。如：边框显示异常，纸张物料标签内容也会劈开两页显示。
但用canvas就不会，不过canvas打印存在合并单元格的二维码会重复显示。
![image](https://user-images.githubusercontent.com/48822119/174544753-2f9b1bcc-1bf7-44b3-a49b-083401d678b2.png)

**Comment by lvdandan16** [comment]
收录 ty

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
请使用html打印，https://bootapi.jeecg.com/jmreport/shareView/698707311396737024 
该实例打印测试没有出现描述的问题
