### ISSUE TITLE
分版不可用

### ISSUE THREAD

**Issue by liuxh530** [jeecgboot/JimuReport#1078]
##### 版本号：
1.5

##### 问题描述：
数据报表，右键无分版设置

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/107610042/174016771-7c56a2f3-9ef0-451c-99a0-7ba5de410a8f.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/174427643-1c6a956f-0f0b-4b98-b589-9592084a2dde.png)
滚动条下拉
