### ISSUE TITLE
判断条件吧字符串特殊处理导致报错了

### ISSUE THREAD

**Issue by yufuxin01** [jeecgboot/JimuReport#1079]
##### 版本号：
1.4.1

##### 问题描述：

判断条件吧字符串特殊处理导致报错了

全的文字
'CENTURY CONSTRUCTION GROUP CORP.'

条件判断
=(let code= string.contains('#{AO01.relastionship_mo}','TOTAL'); 
if(code){
   return  color('#{AO01.customer_name}','','#8EA9DB');
}else{
   return '#{AO01.customer_name}';
})

##### 错误日志&截图：

2022-06-16 16:28:34.941 ERROR 21980 --- [nio-8444-exec-1] o.jeecg.modules.jmreport.desreport.a.a   : Syntax error: missing '}' to close 'else' body at 76, lineNumber: 5, token : [type='variable',lexeme='CONSTRUCTION',index=76],
while parsing expression: `
let code= '0';
if(code== '1'){
   color('','','#8EA9DB');
}else{
   CENTURY CONSTRUCTION^^^
`

com.googlecode.aviator.exception.ExpressionSyntaxErrorException: Syntax error: missing '}' to close 'else' body at 76, lineNumber: 5, token : [type='variable',lexeme='CONSTRUCTION',index=76],
while parsing expression: `
let code= '0';
if(code== '1'){
   color('','','#8EA9DB');
}else{
   CENTURY CONSTRUCTION^^^
`
	at com.googlecode.aviator.parser.ExpressionParser.reportSyntaxError(ExpressionParser.java:1062) ~[aviator-5.2.6.jar:na]

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级版本试一下，此版本未复现问题
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.5.0</version>
</dependency>
```
