### ISSUE TITLE
导出excel无样式

### ISSUE THREAD

**Issue by 961109899** [jeecgboot/JimuReport#1080]
##### 版本号：

1.5.0

##### 问题描述：

设计好报表后，导出excel无样式

##### 错误日志&截图：

设计样式
[!
![1655385753006](https://user-images.githubusercontent.com/29458769/174081222-93c7c9eb-0577-4184-b34b-e3a3949617fb.png)
](url)

导出excel样式
[!
![1655386494658](https://user-images.githubusercontent.com/29458769/174081960-84c45dec-9b03-4815-8fc1-b8d2c65ab04f.png)
](url)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
导出样式渲染大数据时会导致慢，所以1.5.0去掉了导出样式
