### ISSUE TITLE
API数据集按要求返回格式 ,分页不生效

### ISSUE THREAD

**Issue by Acechengui** [jeecgboot/JimuReport#1082]
##### 版本号：
1.4.4

##### 问题描述：

API数据集按要求返回格式 ,分页不生效

##### 错误日志&截图：
![WWWF17PD S REZ3~JF}B@PQ](https://user-images.githubusercontent.com/63096199/174213343-c9fa4f67-9f62-407d-8c4e-262d60d96a70.jpg)
![G`G%OSF4R4(OA4@Z`6 }Y2J](https://user-images.githubusercontent.com/63096199/174213375-5029f62e-594c-4b7d-b87b-3dfa8d41aae5.jpg)
![5ZY{B{@UGIRZ RM{8_T86K4](https://user-images.githubusercontent.com/63096199/174213393-d74b8f7c-fd60-4908-b760-c09de19a00bc.jpg)

##### 重现步骤：
按照文档说明返回要求格式,并且设置了每页显示条数,请求方式为get;

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级最新版本试一下
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.5.0</version>
</dependency>
```

**Comment by Acechengui** [comment]
现在还不能升版本,1.5.0版本我提得另外一个issue还未解决(tomcat8.5环境线程报错无法启动)


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月18日(星期六) 下午3:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] API数据集按要求返回格式 ,分页不生效 (Issue #1082)





 
升级最新版本试一下
 <dependency&gt;     <groupId&gt;org.jeecgframework.jimureport</groupId&gt;     <artifactId&gt;jimureport-spring-boot-starter</artifactId&gt;     <version&gt;1.5.0</version&gt; </dependency&gt;

**Comment by lvdandan16** [comment]
1.5.0版本可使用jar方式，如果必须使用war包方式 请使用tomcat9
