### ISSUE TITLE
【SQL数据集】数据集渲染失败

### ISSUE THREAD

**Issue by Zoe-Zhu** [jeecgboot/JimuReport#1083]
##### 版本号：
1.4.4-beta

##### 问题描述：
数据库连接没有问题，数据集数据预览也有数据，但是模板拖拉拽之后，打开预览url没有数据，日志中的SQL拖出来执行，有数据

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/22297885/174215083-322d03af-8220-43e6-bcae-3dcb83b30db7.png)
![image](https://user-images.githubusercontent.com/22297885/174215370-87de704a-7c8c-49c9-bc5e-35564dafa769.png)
![image](https://user-images.githubusercontent.com/22297885/174215477-ff7acdc5-70ce-4a76-8c55-870c983919c3.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级最新版本试一下
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.5.0</version>
</dependency>
```

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
