### ISSUE TITLE
查询栏中配置的查询条件无法获取外部的传递的参数

### ISSUE THREAD

**Issue by whd120130** [jeecgboot/JimuReport#1084]
##### 重现步骤：
<img width="2034" alt="WX20220619-124253@2x" src="https://user-images.githubusercontent.com/26647586/174466177-a5223a0d-a166-4796-bd95-138d59b2b82c.png">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
