### ISSUE TITLE
预览报表，报表内容不能进行复制

### ISSUE THREAD

**Issue by Zeno118** [jeecgboot/JimuReport#1085]
##### 问题描述：预览报表，报表内容不能进行复制，后面版本能否升级可以复制（开发自行选择用户预览是否可复制内容）
                             不能复制用户体验很不友好

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
归集到：#138

**Comment by Zeno118** [comment]
我看里面写的已实现了，但是我用的1.5版本还是不能复制。
