### ISSUE TITLE
折线图存在显示数值问题

### ISSUE THREAD

**Issue by changyoutianxia** [jeecgboot/JimuReport#1086]
##### 版本号：
1.5.0

##### 问题描述：
折线图打开和关闭显示数值的时候会把坐标轴显示，就关闭不掉了

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/46896358/174695670-efd30c64-2e77-4c86-a988-84204885a785.png)

##### 重现步骤：
制作折线图打开关闭数值显示，可以复现

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
