### ISSUE TITLE
无法正常预览问题

### ISSUE THREAD

**Issue by OIOIIIIOIO** [jeecgboot/JimuReport#1088]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/60501406/174718819-c60b636c-27d0-4e70-8ba9-5088798bebbe.png)
![image](https://user-images.githubusercontent.com/60501406/174718905-7fa7d736-a560-4186-b2fa-b9e86590485f.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
看报什么错

**Comment by OIOIIIIOIO** [comment]
抱歉过这么久才回复，再次查看的时候预览功能能正常使用了，可能是项目服务器的问题导致的，如果又类似的情况发现我再记录下报错
