### ISSUE TITLE
钻取联动条件框取值问题

### ISSUE THREAD

**Issue by yzmking** [jeecgboot/JimuReport#1089]
##### 版本号：
1.4.2

##### 问题描述：
怎么判断参数是否为空，需求是，如果列表什么数据，侧不跳转

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/44563730/174762051-c6e04a14-2468-485c-9415-3c35005e78d4.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
已修复，下个版本升级

**Comment by 1298191366** [comment]
已修复，目前支持为空判断，需要注意的是当条件都不满足的时候钻取跳转到第一个
