### ISSUE TITLE
查询条件支持SQL字典类型ID当查询条件么

### ISSUE THREAD

**Issue by An0nymous0** [jeecgboot/JimuReport#1090]
##### 版本号：
1.4.3

##### 问题描述：
比如通过sql带出下拉查询条件是省（北京、上海、广州） 最终 sql查询条件是id 
select * from user where area_id='${area_id}'

**Comment by 1298191366** [comment]
你可以参考文档[配置sql语句](http://report.jeecg.com/2306128),将你的id配置成`value`,省为`text`
