### ISSUE TITLE
#{jianpiao.idx} 无法设置序号

### ISSUE THREAD

**Issue by as365** [jeecgboot/JimuReport#1091]
##### 问题描述：
#{jianpiao.idx} 无法设置序号

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/13197006/174929522-61ab0ad9-2171-46d0-ba49-c1ee08562b36.png)

##### 重现步骤：
https://bootapi.jeecg.com/jmreport/view/699410358112440320?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NTU4NzExNDIsInVzZXJuYW1lIjoib2hiYUs2UTdjRXNvRk92YU5yLW1IOHNBQlZldyJ9.VUuKTVSprVV8fLc4wQ51zz2gL9JjyCeLpQ__67c6vOQ

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档：
http://report.jeecg.com/2351380

**Comment by as365** [comment]
> 参考文档： http://report.jeecg.com/2351380

http://report.jeecg.com/2373085这个序号列idx是固定取值，当需要递增序号时必须使用#{ygxxtj.idx}，ygxxtj为数据集的key

这个序号列不能用了吗？

**Comment by lvdandan16** [comment]
这个是循环块的，你设置成循环块了吗

**Comment by as365** [comment]
> 这个是循环块的，你设置成循环块了吗

循环块是否没有开源？我本地部署的测试项目右键没有循环块菜单呢

**Comment by lvdandan16** [comment]
所有功能都开源，右键滚动条下拉

**Comment by lvdandan16** [comment]
所有功能都开源，右键滚动条下拉

**Comment by as365** [comment]
> 所有功能都开源，右键滚动条下拉

好的，看到了，谢谢啦
