### ISSUE TITLE
导出Excel的时候，数字没有设置为数字格式，而是文本格式，还需要手动转化，很不方便

### ISSUE THREAD

**Issue by xinxingzhao** [jeecgboot/JimuReport#1092]
##### 版本号：
1.5.0

##### 问题描述：
导出Excel的时候，数字没有设置为数字格式，而是文本格式，还需要手动转化，很不方便

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/13712791/174983893-846979a7-978c-419c-856e-1afbeb389b9c.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
