### ISSUE TITLE
钻取报表添加条件后点击进入超链接报错

### ISSUE THREAD

**Issue by yzmking** [jeecgboot/JimuReport#1093]
##### 版本号：
1.4.2

##### 问题描述：
钻取报表添加条件后点击进入超链接报错

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/44563730/174992731-37759bb3-4e9b-4cc4-894d-857c683806af.png)
![image](https://user-images.githubusercontent.com/44563730/174992913-af68bad6-ee6c-4eee-a766-4b913e4329eb.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
