### ISSUE TITLE
关于数据源接口功能的建议

### ISSUE THREAD

**Issue by leblog** [jeecgboot/JimuReport#1094]
##### 版本号：
1

##### 问题描述：
API 数据源能否加入请求头,请求体
希望可以在接口的请求上面加入请求头,丰富一下请求的方式比如增加put,delete 方式请求

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/56074493/174969033-9bba8429-58e7-4a98-afe7-894fbacd031e.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
归集到：#138
