### ISSUE TITLE
报表表达式不支持四则运算吗？

### ISSUE THREAD

**Issue by pystudy123** [jeecgboot/JimuReport#1095]
##### 版本号：
1.5.0

##### 问题描述：
四则运算，运算表达式不支持？

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/57655202/175041543-debd1c62-839c-4936-8881-ed5c4addb303.png)
![image](https://user-images.githubusercontent.com/57655202/175041637-3a35cc7e-88a5-4d94-b170-e5b82f9463c0.png)

**Comment by pystudy123** [comment]
逻辑运算好像也没有？

**Comment by lvdandan16** [comment]
请具体说明

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
