### ISSUE TITLE
交叉报表遇到的问题--一级表头与二级表头对应关系出错

### ISSUE THREAD

**Issue by Trust7X** [jeecgboot/JimuReport#1096]
版本号：1.5
问题描述：交叉报表展示时一级表头与二级表头对应关系不对，位置窜了。
截图：
![4E84603B-8131-4a56-9759-73C1B2890758](https://user-images.githubusercontent.com/107460469/175227271-e350ea58-07f9-41c0-b30c-23524974ef08.png)
![image](https://user-images.githubusercontent.com/107460469/175227321-a6f3519d-209a-4e89-83b0-6622e976c44a.png)
重现步骤：交叉报表的实现方式，我是根据官方提供的文档来做的。具体数据库数据格式在第二张截图中可以看到。

**Comment by Trust7X** [comment]
问题解决了，一级表头必须设置排序为默认！！！

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
已修复
