### ISSUE TITLE
怎么才能实现点击表头排序？

### ISSUE THREAD

**Issue by yongguang423** [jeecgboot/JimuReport#1097]
##### 版本号：
1.5.0

##### 问题描述：

通过点击表头，实现数据排序排序功能，最好是基于sql的排序，并且表头能显示排序箭头。这个效果能通过js增强实现吗？
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/6082894/175256401-f7a6b8d2-8657-453f-8cf7-2f89c64b8e5a.png)

**Comment by lvdandan16** [comment]
不支持
归集到：#138
