### ISSUE TITLE
交叉报表----固定列

### ISSUE THREAD

**Issue by Trust7X** [jeecgboot/JimuReport#1098]
##### 版本号：
1.5

##### 问题描述：
想在交叉报表的后面加一个固定列，不知道怎么实现。
![image](https://user-images.githubusercontent.com/107460469/175257326-4aff0dc5-910d-4c78-ba97-9328c61a9cfd.png)
![image](https://user-images.githubusercontent.com/107460469/175257376-e76c022b-b664-4fea-a4f7-d98b871b440e.png)
如果只是直接把备注列放到数据列后面会被覆盖
![image](https://user-images.githubusercontent.com/107460469/175257549-f3e9d814-bf0d-475b-8334-27c6e67f20dc.png)
![image](https://user-images.githubusercontent.com/107460469/175257573-aab5f3b7-2d84-4457-b8cc-f0ec4dd4b9f7.png)

**Comment by lvdandan16** [comment]
交叉报表，横向目前还不支持插入列
归集到：#138
