### ISSUE TITLE
图表的数值显示，会连轴名称一起显示

### ISSUE THREAD

**Issue by yangjunzhou861012** [jeecgboot/JimuReport#1100]
##### 版本号：
1.5.0

##### 问题描述：
当设计柱状图，折线图（其他图表也是一样），然后修改数值显示的属性，则这些柱状图，折线图，连轴名称字段也会一起显示，但是这样显示一是多余，二，是数据量稍微多一些，则容易糊在一起看不清，无法单独的只显示数值

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/18575974/175450394-b7a01020-9a39-4db1-b436-0076e5870071.png)

##### 重现步骤：
打开设计器
添加数据源
编辑sql数据集
拖入折线图（其他图表也是一样）
当刚拖入，还未修改数值设置属性的时候
![image](https://user-images.githubusercontent.com/18575974/175450164-e53d439f-b289-4a52-ab4e-23cbf79a0c5c.png)
当修改了设置设置显示的时候
轴名称就显示了出来，且无法设置只显示数值
![image](https://user-images.githubusercontent.com/18575974/175450416-ae8f2919-731a-4308-ab22-d4fb65315584.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
