### ISSUE TITLE
报表增加字体

### ISSUE THREAD

**Issue by liuxh530** [jeecgboot/JimuReport#1104]
##### 版本号：
1.5

##### 问题描述：
windows增加了一些特殊字体，但是报表设计的时候无法选择。

##### 错误日志&截图：
![微信图片_20220624212554](https://user-images.githubusercontent.com/107610042/175545430-beee5113-37b5-4c59-92bb-e2f2063da409.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by yufuxin01** [comment]
直接改源码，字体是写死的

**Comment by lvdandan16** [comment]
不支持
