### ISSUE TITLE
配置sqlserver数据源提示驱动类不存在

### ISSUE THREAD

**Issue by snpython** [jeecgboot/JimuReport#1105]
##### 版本号：
1.5

##### 问题描述：
配置sqlserver数据源提示驱动类不存在

##### 错误日志&截图：
![67CK 51E V%Y}_VZR`@}6{U](https://user-images.githubusercontent.com/67887626/175795586-3437e533-bcf1-4018-aadb-aee39a2bfe2e.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by snpython** [comment]
换了个jar包好了

**Comment by lvdandan16** [comment]
参考常见问题 43：http://report.jeecg.com/2087464
