### ISSUE TITLE
富文本粘贴了excl表格要怎么处理

### ISSUE THREAD

**Issue by jinwe888** [jeecgboot/JimuReport#1107]
##### 版本号：
 v1.5.0 

##### 问题描述：
富文本粘贴了excl表格，到积木这边设计打印时显示的是富文本的源码，这要怎么解决，谢谢

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持html标签
归集到：#138
