### ISSUE TITLE
横向分组数据丢失,只出现一个表头，剩下不出现，同样的数据新建报表就没事，克隆都会有问题

### ISSUE THREAD

**Issue by baiyixiangqin** [jeecgboot/JimuReport#1108]
##### 版本号：
1.5.0

##### 问题描述：
横向分组数据丢失,只出现一个表头，剩下不出现，同样的数据新建报表就没事，克隆都会有问题

##### 错误日志&截图：
![输入图片说明](https://images.gitee.com/uploads/images/2022/0622/174713_16e4ac8b_8250846.png "屏幕截图.png")
[横向分组表头显示问题.zip](https://github.com/jeecgboot/JimuReport/files/8998901/default.zip)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by baiyixiangqin** [comment]
在第二次保存的时候很容易出现这样的问题

**Comment by baiyixiangqin** [comment]
@lvdandan16  多次保存的时候就会出现这个问题

**Comment by lvdandan16** [comment]
> @lvdandan16 多次保存的时候就会出现这个问题

数据表及表结构没有

**Comment by baiyixiangqin** [comment]
@lvdandan16  我还需要给出数据和表结构？

**Comment by baiyixiangqin** [comment]
@lvdandan16  因为是SQL多表查询，表结构和表数据不太好给

**Comment by baiyixiangqin** [comment]
@lvdandan16  
![image](https://user-images.githubusercontent.com/102849584/181203333-3b895900-1008-40b7-b469-47bc17d75791.png)
小范围横向分组没事，做大报表就有问题

**Comment by baiyixiangqin** [comment]
@lvdandan16 
![image](https://user-images.githubusercontent.com/102849584/181206506-08760dd7-b128-4f08-b0cd-8fc8bfb5c18e.png)
这个截图和上面那截图出自同一个报表，同一个数据源，结果差异化太明细了

**Comment by lvdandan16** [comment]
> @lvdandan16 ![image](https://user-images.githubusercontent.com/102849584/181203333-3b895900-1008-40b7-b469-47bc17d75791.png) 小范围横向分组没事，做大报表就有问题
注意一下你的数据，是否都完整，最起码第一条必须要是完整的
http://report.jeecg.com/2119057

**Comment by baiyixiangqin** [comment]
@lvdandan16 为什么做一个简单测试的时候，我第一条也不是全部都有数据，横向分组的表头出现了，而做大报表的时候需要遵循这一条规则？

**Comment by baiyixiangqin** [comment]
@lvdandan16 应该是单元格问题，这是我测试的视频
[横向分组.zip](https://github.com/jeecgboot/JimuReport/files/9206897/default.zip)

**Comment by baiyixiangqin** [comment]
@lvdandan16  这是今天发现问题
[测试横向分组.zip](https://github.com/jeecgboot/JimuReport/files/9215667/default.zip)

**Comment by tygithub1** [comment]
> @lvdandan16 这是今天发现问题 [测试横向分组.zip](https://github.com/jeecgboot/JimuReport/files/9215667/default.zip)

你搞明白啥是横向分组了吗？ 按照你的涉及，表头是基于你的数据的，你设置查询条件，结果数据不一样，那展示的表头自然不一样

**Comment by baiyixiangqin** [comment]
@lvdandan16  您有仔细看过视频吗？的确按照我的设计，表头数据是基于我的数据的，但我的两个压缩视频是没有点击查询条件的，单元格依旧数据丢失，下面是数据是有，表头数据没有，我在视频充分演示这个bug，还做了我自己的解决方法，但我的这种方法治标不治本，最后希望您们真的看看这个视频，真的解决这个问题

**Comment by lvdandan16** [comment]
升级1.5.4试一下，第一条默认数据做了自动填充
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.5.4</version>
</dependency>
```
