### ISSUE TITLE
成功开启分页后，打印没有分页

### ISSUE THREAD

**Issue by LostDust** [jeecgboot/JimuReport#1112]
##### 版本号：
1.5.0

##### 问题描述：
在开启分页后，预览页面有分页效果，但打印没有分页
只有第一页与预览效果一致，其他页均没有表头

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/45227081/176572167-4522e80b-53c6-4747-9a94-005703df8691.png)
![image](https://user-images.githubusercontent.com/45227081/176572242-d633ce15-eb95-422c-a86a-66ce644c909a.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
打印是打印全部，目前没有分页
其他页表头暂不支持
