### ISSUE TITLE
积木传参可以使用逗号隔开的长字符串吗？

### ISSUE THREAD

**Issue by yuan19981112** [jeecgboot/JimuReport#1113]
##### 版本号：
1.3.795

##### 问题描述：

积木传参数可以使用逗号隔开的字符串吗？目的是传到SQL里，使字段可以 in （参数）进行查询
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参数为占位符，传入什么就是什么
如果想用in 可以使用字段查询
