### ISSUE TITLE
一个报表中存在多个（我是3个）分版时，除了第1个分版正常，其他的（第2、3）分版列表显示错乱；且多个分版均无法删除；

### ISSUE THREAD

**Issue by gang2113920** [jeecgboot/JimuReport#1114]
##### 版本号：
1.5.0

##### 问题描述：
一个报表中存在多个（我是3个）分版时，除了第1个分版正常，其他的（第2、3）分版列表显示错乱；且多个分版均无法删除；

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/10305840/176585641-ffe09cfe-b52f-45c4-9508-5608dcc8dede.png)
![image](https://user-images.githubusercontent.com/10305840/176585694-aa4d50eb-cde1-4135-bdc9-532df4e70ad3.png)

##### 重现步骤：
步骤演示：
![动画3](https://user-images.githubusercontent.com/10305840/176586902-73b16ac2-f3be-4c32-ae73-cb56e793a640.gif)

报表设计SQL脚本：
[report-export-mysql.zip](https://github.com/jeecgboot/JimuReport/files/9016171/report-export-mysql.zip)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
不支持
