### ISSUE TITLE
是否支持数据集查出所有数据，在积木报表里进行条件过滤条件然后汇总功能

### ISSUE THREAD

**Issue by dcces** [jeecgboot/JimuReport#1115]
##### 版本号：
1.5.0-beta

##### 问题描述：
是否支持数据集查出所有数据，在积木报表里进行条件过滤条件然后汇总功能
图1为数据库表结构
图2为报表SQL
图3为报表模板
目的：配置一条数据集，然后在报表模板中对数据集进行条件过滤然后进行汇总。
##### 错误日志&截图：
![图片](https://user-images.githubusercontent.com/26531895/176602740-e36bf47a-b59b-4c3c-8fca-4348497c7405.png)
![图片](https://user-images.githubusercontent.com/26531895/176603093-49dbd695-d3a4-4fec-9b14-cf203ad08b1d.png)
![Uploading 图片.png…]()

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
