### ISSUE TITLE
日期选择控件（yyyy-MM）不兼容火狐浏览器

### ISSUE THREAD

**Issue by lusl1991** [jeecgboot/JimuReport#1116]
##### 错误日志&截图：
火狐浏览器如下：
![7078bb4155d4210ab558650dcebc4a8](https://user-images.githubusercontent.com/28939880/176617074-ba2aa477-deef-4d70-bd3e-e27907ff32c0.png)
谷歌浏览器如下：
![image](https://user-images.githubusercontent.com/28939880/176617345-e96c8457-226f-4f88-9c08-6277c64195b7.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
未测出，本地浏览器版本105.0.3 (64 位)，积木报表版本号1.5.0
yyyy-MM 格式
![image](https://user-images.githubusercontent.com/30997828/196078825-4b50487a-6cee-4656-ba06-e856a2556c29.png)
yyyy格式
![image](https://user-images.githubusercontent.com/30997828/196079478-d4bb6411-c542-4b1e-99df-5b32df7bf2f2.png)

**Comment by simbaliao** [comment]
设置了默认值就能复现该问题
