### ISSUE TITLE
导出pdf不显示二维吗

### ISSUE THREAD

**Issue by yueshibing** [jeecgboot/JimuReport#1117]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by yueshibing** [comment]
> ##### 版本号：1.4.4-beta
> ##### 问题描述：按照设置的初始pdf，获取到文件的二维码吗？
> ##### 错误提示&截图：
> ##### 然后步骤：集成1.4.4-beta版本，新建报表，报表中添加二维码（吗？内容为固定数据或动态都行），后台显示调用jmreport/export pdf，下载pdf文件中，不二维码
> #### 提示（为了提高问题处理效率）：
> * 积木报表是免费报表，功能免费不开放；
> * 未按格式要求发帖，会被直接删掉；
> * 请针对报表问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作示例并提供ID；
> * 如果有不好的问题，请描述操作视频或详细的步骤；

**Comment by yueshibing** [comment]
因为jmreport/export方法在1.5.0版本删除，所以我用了1.4.4-beta版本，如果在新版本有完善的pdf导出接口，请告诉我接口地址，谢谢大佬

**Comment by lvdandan16** [comment]
新版导出接口已取消
