### ISSUE TITLE
堆叠柱形图为堆叠展示

### ISSUE THREAD

**Issue by Action45** [jeecgboot/JimuReport#1118]
##### 错误日志&截图：
1、添加图表选择堆叠柱形
![image](https://user-images.githubusercontent.com/87290598/176640969-5b8f1ebd-f1dc-4c6c-bf23-1fd50171c418.png)

2、配置数据集
![RHS_8GW7 MLH30B$%ECRJ8S](https://user-images.githubusercontent.com/87290598/176642564-05f68127-cb10-4323-a774-90bd7e3752b2.png)

3、点击运行后，图形为多柱，而非期望的堆叠柱
![~C}H0(}I`F{EV@M@X 1I0FL](https://user-images.githubusercontent.com/87290598/176642899-2232dd32-0662-4ea1-b63e-4efa9285263e.png)

回退至1.4版本也存在该问题
##### 重现步骤：
如上述

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
想要堆叠的系列需要配置到系列类型中，参考https://help.jeecg.com/jimureport/barChart/datasource.html#4%E7%89%B9%E5%88%AB%E9%85%8D%E7%BD%AE
