### ISSUE TITLE
数据报表合计行的完成率无法实现另2个合计数相除

### ISSUE THREAD

**Issue by jeffrey-liu-025** [jeecgboot/JimuReport#1120]
##### 版本号：
1.5.0

##### 问题描述：
数据报表合计行的完成率无法实现另2个合计数相除

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/58239741/176981255-78e781c7-ad88-48a6-8237-edfdfe2666ff.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
