### ISSUE TITLE
带搜索下拉选项 搜索值问题

### ISSUE THREAD

**Issue by shangbandaka** [jeecgboot/JimuReport#1122]
##### 版本号：
1.5.0

##### 问题描述：
带搜索下拉选项 搜索时需输入value才能查询到 实际应用text值搜索。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/108644965/177077389-703bcbe5-dd95-4c39-bd74-f3028d1726e9.png)
![image](https://user-images.githubusercontent.com/108644965/177077454-7608e260-253e-4294-84cf-09c595564c34.png)
![image](https://user-images.githubusercontent.com/108644965/177077484-d5275776-ae4c-4e4d-a852-34a2c822fc4b.png)

##### 重现步骤：
下拉搜索框中输入对应下拉text无法查询到 需输入对应隐藏value值。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by shangbandaka** [comment]
用的字典项的下拉  是我哪配置不对？？   其他人没用遇到吗
![image](https://user-images.githubusercontent.com/108644965/178226823-f05be906-0230-44b0-9438-91acc505da01.png)

**Comment by lvdandan16** [comment]
归集：#138
