### ISSUE TITLE
下拉树控件有没有类似isLeaf的属性

### ISSUE THREAD

**Issue by yzmking** [jeecgboot/JimuReport#1126]
##### 版本号：
1.4.2

##### 问题描述：
加载出来的树结构，不管有没有子级，前面都有三角形，要点击才知道有没有下级，使用体现不太友好， 下拉树控件有没有类似isLeaf的属性，可以提前告诉控件，有没有下级，从而不显示三角

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/44563730/177111494-d22bf943-9ccf-40d7-b5e7-13e2dba3cd08.png)
![image](https://user-images.githubusercontent.com/44563730/177111596-a7aae846-f8cd-4363-9b04-dd7964aea04c.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by joneyjay** [comment]
大佬您好 我刚入门这个方便请教个问题吗

**Comment by lvdandan16** [comment]
归集到：#138
