### ISSUE TITLE
小票打印纸张高度问题

### ISSUE THREAD

**Issue by yueshibing** [jeecgboot/JimuReport#1128]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/38520937/177244542-4a722e0f-3a91-4f15-8867-c79f13c99b32.png)
![image](https://user-images.githubusercontent.com/38520937/177244780-77ce06a6-a232-45f4-ba8c-d7171f125a8f.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
归集到：#138
