### ISSUE TITLE
查询条件下拉框最下边，“暂无更多数据”

### ISSUE THREAD

**Issue by kerasking** [jeecgboot/JimuReport#1131]
##### 版本号：
1.5.0

##### 问题描述：
查询条件下拉框最下边，能不能不显示  “暂无更多数据”

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/998105/177293865-4521efe0-9a01-4931-abb9-c4a425a8e66b.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
