### ISSUE TITLE
查询条件下拉框选择一项后其他项不显示

### ISSUE THREAD

**Issue by kerasking** [jeecgboot/JimuReport#1132]
##### 版本号：

1.5.0
##### 问题描述：

查询条件下拉框选择一项后再回去选就没有其他项了
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/998105/177294176-3c6d974d-8185-4934-bf27-c960d71195a8.png)
![image](https://user-images.githubusercontent.com/998105/177294216-c0b649da-c900-4506-a18f-b29cae0409f7.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
选中后再次点击，选中值会作为查询条件查询，显示全部，删掉选中即可
