### ISSUE TITLE
引入了图片导出excel和pdf超时

### ISSUE THREAD

**Issue by zjh915801913** [jeecgboot/JimuReport#1134]
##### 版本号：

1.4.2
##### 问题描述：
引入了图片导出excel和pdf超时

##### 错误日志&截图：
字段设置成图片了的
![image](https://user-images.githubusercontent.com/30255969/177454904-1de71995-02d8-4780-8b97-b7d6b9d377f8.png)
图片预览成功的
![image](https://user-images.githubusercontent.com/30255969/177454994-5848b15f-6ee7-4a23-bb7a-0d4ef1f4c6f2.png)
导出超时转圈圈
![image](https://user-images.githubusercontent.com/30255969/177455192-7c67dca9-2a36-443f-94bb-07cefac007e6.png)
![image](https://user-images.githubusercontent.com/30255969/177455148-cf7a5af6-51c3-4885-91bc-90d1ef5575b8.png)

**Comment by lvdandan16** [comment]
图片太大，超时了吧
