### ISSUE TITLE
集成进入项目后  项目基于 docker容器启动时报错

### ISSUE THREAD

**Issue by lijiahao0617** [jeecgboot/JimuReport#1135]
##### 版本号：
1.5.0

##### 问题描述：
集成进入项目后  项目基于 docker容器启动时报错

##### 错误日志&截图：
![RTX截图未命名](https://user-images.githubusercontent.com/27475786/177457282-b069af86-529d-41a3-ace6-8dcb262272e7.png)

##### 重现步骤：
集成进入项目后  项目基于 docker容器启动时报错
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
依赖没加载完吧
