### ISSUE TITLE
列数超过AX时后面的列无法全部显示

### ISSUE THREAD

**Issue by zhanghahahahahaha** [jeecgboot/JimuReport#1136]
##### 问题描述：
当报表的列很多，超过AX列时，编辑状态下，后面的列没办法显示

##### 错误日志&截图：

![微信图片_20220706133931](https://user-images.githubusercontent.com/108739923/177476811-ffaa38d9-85d6-43c1-afa0-ba01378e125c.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
常见问题 34：http://report.jeecg.com/2087464
