### ISSUE TITLE
过滤条件的值重复显示

### ISSUE THREAD

**Issue by zhanghahahahahaha** [jeecgboot/JimuReport#1137]
##### 版本号：
1.5.0

##### 问题描述：
将某个字段设置为查询条件，在查询栏发现下拉列表的值是重复的，想要的是每个值显示一次

##### 错误日志&截图：

![20220706134932](https://user-images.githubusercontent.com/108739923/177478644-cc42f38c-ee4c-401f-81ac-aebe863b022d.png)

![20220706134936](https://user-images.githubusercontent.com/108739923/177478623-900f9957-0c7e-4b7f-a075-e8c5e0ec6718.png)

##### 重现步骤：
在SQL数据集界面，将某个列的“查询”勾选上，“查询模式”选择下拉列表，在报表预览界面，查询栏显示的值是重复的

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
可使用SQL字典 手动去重
http://report.jeecg.com/2373407
