### ISSUE TITLE
官网上的报表，每页显示行数为什么不起作用？

### ISSUE THREAD

**Issue by wangbo930** [jeecgboot/JimuReport#1139]
##### 版本号：
https://bootapi.jeecg.com/jmreport/index/9d11a703bb1135aa4cbb4c5cb4540408?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NTcwOTk3NjMsInVzZXJuYW1lIjoiMTUzNTM1MTAwNzkifQ.uG8Naj2hoM90iwWxPIYPavaf8Du6l6LHsPg0PJMiJZY

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/56463890/177496736-48c6a990-aa67-44b5-94d4-4d2fe638163a.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by wangbo930** [comment]
好像通过API取的数据源都有这样的问题，我们在项目碰到的情况如下：
1、使用API作为数据源
2、显示数据可以，但最后一页总是个空表（页数只能为复数吗？）
3、导出EXCEL无数据！！！

**Comment by lvdandan16** [comment]
官网线上api示例未实现分页
api分页参考文档：http://report.jeecg.com/2020177
问题2、3未复现
