### ISSUE TITLE
使用场景问题

### ISSUE THREAD

**Issue by cocoamu** [jeecgboot/JimuReport#1140]
请教下 目前免费版能实现以下场景吗
我先在报表设计工具设计好数据源跟报表模板，在我的业务系统里面，比如有一个列表 有10条数据，10条里面的数据类型可能都不一样，每个类型可能都对应一种类型的报表，我选中3条  点击打印 可以调用报表的接口进行预览和打印  

目前看到的都是独立的报表工作台  我想怎么跟业务结合  后端调用接口就能实现打印 不用单独到报表工作台打印

报表本身的功能是能满足我的需求的  但问题在于部署上去这似乎是一个独立的站点  唯一跟业务有交集的就是数据源跟数据集   所有操作得到一个独立的页面进行  我希望的是在业务系统  选中业务数据  后端匹配到对应的报表模块跟数据源   可以快速打印  这个过程是不需要离开业务系统的

**Comment by lvdandan16** [comment]
不支持
