### ISSUE TITLE
Pdf导出接口方案

### ISSUE THREAD

**Issue by liuxh530** [jeecgboot/JimuReport#1141]
##### 版本号：
1.5

##### 问题描述：
单据增加自定义按钮，调用Pdf导出接口方案 ，报错

##### 错误日志&截图：
![QQ图片20220706182241](https://user-images.githubusercontent.com/107610042/177529301-10992b01-b9a0-4e32-943b-beaf9cda9fbe.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
pdf导出接口已取消
