### ISSUE TITLE
加个排序

### ISSUE THREAD

**Issue by yufuxin01** [jeecgboot/JimuReport#1142]
##### 版本号：
![image](https://user-images.githubusercontent.com/77772498/177580944-3af9e918-cfc7-41a7-828a-7809e5747d37.png)

##### 问题描述：
![image](https://user-images.githubusercontent.com/77772498/177580962-fdd7c78c-9a3e-4e98-9118-d23cddbd0763.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
归集到：#138
