### ISSUE TITLE
积木报表1.50集成进jeecgboot 404

### ISSUE THREAD

**Issue by dll233** [jeecgboot/JimuReport#1144]
##### 版本号：
积木报表1.50
jeecgboot最新版

##### 问题描述：
按照此教程执行四步 打开积木报表页面显示404 (http://report.jeecg.com/2078875)

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/49135636/177668527-233379fb-8074-4872-a2e8-1b30607c0f03.png)
但是jeecg本身是可以正常使用的，
![image](https://user-images.githubusercontent.com/49135636/177668694-5eb84e62-7eea-4b9d-aaf2-bed5b6f15df0.png)

##### 重现步骤：
http://report.jeecg.com/2078875 按照如上四步执行 积木页面404
将依赖加入“jeecg-boot/pom.xml”应该没有问题？打开IDEA外部库列表可以看到有2个积木的

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档：http://report.jeecg.com/2213269

**Comment by dll233** [comment]
已解决，感谢！
