### ISSUE TITLE
分组报表数据是有省市区县的，但格式会错乱

### ISSUE THREAD

**Issue by fchaoyu** [jeecgboot/JimuReport#1151]
##### 版本号：
1.4.2

##### 问题描述：
分组报表数据是有省市区县的，但格式会错乱

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/85933335/177932401-fa0e2d48-e0b9-4e88-9209-15fe6426ec7c.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级版本试一下，需配私服
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.5.1</version>
</dependency>
```
