### ISSUE TITLE
两个不同的数据集不能在同一个页面上显示吗？

### ISSUE THREAD

**Issue by kerasking** [jeecgboot/JimuReport#1153]
##### 版本号：
1.5.0

##### 问题描述：
两个不同的数据集不能在同一个页面上显示吗？
目前一个报表里加了两个API数据集， 第一条数据集能正常显示，第二条不显示，API数据是正常的

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
支持
看下你怎么设计的
