### ISSUE TITLE
使用 html 打印时，表格中设置的打印图片如果为带参数的 url 格式，打印时无法正常加载。

### ISSUE THREAD

**Issue by Starxy** [jeecgboot/JimuReport#1155]
##### 版本号：
1.5.0

##### 问题描述：
使用 html 打印时，表格中设置的打印图片如果为带参数的 url 格式，打印时无法正常加载。
带参数的url接口为业务接口，传参需要验证权限
经排查，打印时请求图片的url后面错误的拼接了?time=参数，导致url解析失败，应该改为&time=
使用canvas打印获取图片正常，但是canvas打印时存在模糊的情况

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/15205095/178217762-c25db17b-8417-4c54-9ad7-2516178bfd91.png)
![image](https://user-images.githubusercontent.com/15205095/178217841-279c559c-7b58-4182-a643-1470388c2c7a.png)
![image](https://user-images.githubusercontent.com/15205095/178216886-73c36f09-8d5e-4a2b-b452-d66383ba3ba9.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
已修复
