### ISSUE TITLE
api数据集预览页和打印页数据不对

### ISSUE THREAD

**Issue by 13192294603** [jeecgboot/JimuReport#1157]
##### 版本号：
1.5.0

##### 问题描述：
api数据集预览页和打印页数据不对
预览页数据和打印页的数据显示不全  预览页空白的数据在打印页可以显示  但部分预览页有的数据在打印页不显示

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/55734244/178427719-ea5568f5-8ccd-4c65-a6dd-f7bdb86c82d8.png)
![image](https://user-images.githubusercontent.com/55734244/178427954-0aa11d33-1311-4d1d-98f1-7914992564b7.png)
![image](https://user-images.githubusercontent.com/55734244/178429935-70546855-cd54-466f-be88-ffccf4576f90.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级1.5.2试一下，api重新解析一下
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.5.2</version>
</dependency>
```

**Comment by 13192294603** [comment]
已更新 api重新解析 无效 问题依旧存在。

**Comment by lvdandan16** [comment]
官网做个示例，复现你的问题，把报表id贴上来

**Comment by 13192294603** [comment]
703766371267452928




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月12日(星期二) 下午3:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] api数据集预览页和打印页数据不对 (Issue #1157)





 
官网做个示例，复现你的问题，把报表id贴上来

**Comment by lvdandan16** [comment]
? 积木官网并没有这个id

**Comment by 13192294603** [comment]
706740160351784960

**Comment by lvdandan16** [comment]
预览和打印都没数据？

**Comment by 13192294603** [comment]
官网实例那个没有写数据集 这边接口数据不开放&nbsp; 你们那边可以加下数据试试&nbsp; &nbsp;预览页和打印页都丢失了部分数据



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月12日(星期二) 下午3:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/JimuReport] api数据集预览页和打印页数据不对 (Issue #1157)





 
预览和打印都没数据？

**Comment by 13192294603** [comment]
好像是api数据集和sql数据集一起使用出现的问题
![image](https://user-images.githubusercontent.com/55734244/179180821-fee0a544-30ea-4c40-95d5-2059a4364f27.png)

**Comment by 13192294603** [comment]
参数问题

**Comment by 13192294603** [comment]
706740160351784960


大概数据如下







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月12日(星期二) 下午3:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/JimuReport] api数据集预览页和打印页数据不对 (Issue #1157)





 
? 积木官网并没有这个id
