### ISSUE TITLE
API数据集，AP解析时提示: 数据为空，报表字段明细会被清空！

### ISSUE THREAD

**Issue by Zeno118** [jeecgboot/JimuReport#1158]
##### 问题描述：API数据集取数据时，AP解析时提示: 数据为空，报表字段明细会被清空！
                             http://api.jeecg.com/mock/26/jihua
                            第一次可以，后面就不可以了，任何API数据集取数据是，API解析就提示: 数据为空，报表字段明细会被清空！获取不到数据。 直接在用网页输入时可以取到值

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Zeno118** [comment]
{
  "success": true,
  "message": "",
  "code": 200,
  "result": [],
  "timestamp": 1657684544971
} 
 API解析 里面的result是空的

**Comment by Zeno118** [comment]
14:27:59.483 [http-nio-8081-exec-92] ERROR o.j.m.j.d.util.e - [b,504] - GET 请求url=http://api.jeecg.com/mock/26/jihua?printAll=true&pageSize=10 , api调用专用 error: I/O error on GET request for "http://api.jeecg.com/mock/26/jihua": Connect to api.jeecg.com:80 [api.jeecg.com/82.156.197.104] failed: Connection refused: connect; nested exception is org.apache.http.conn.HttpHostConnectException: Connect to api.jeecg.com:80 [api.jeecg.com/82.156.197.104] failed: Connection refused: connect
以上是API解析错误日志:

**Comment by Zeno118** [comment]
用API数据集，开始几次是可以解析成功，后面就解析不成功，提示:数据为空，报表字段明细会被清空！ 等到第二天又可以解析几次成功，后面又解析不成功了。

**Comment by lvdandan16** [comment]
怎么复现此问题？可录个视频

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
