### ISSUE TITLE
websocket 问题

### ISSUE THREAD

**Issue by qdkysoft** [jeecgboot/JimuReport#1159]
##### 问题描述：
已经完成动作：
jeecgboot中按文档中写了“WebSocket服务端” 
接口地址：wss://www.****.com:**/jeecg-boot/bigscreenwebsocket/refreshChart
websocket改成了bigscreenwebsocket，（@ServerEndpoint("/bigscreenwebsocket/refreshChart/{chartId}")）
shiro也放行了。filterChainDefinitionMap.put("/bigscreenwebsocket/**", "anon");

没得到理想效果：
用普通网页测试websocket：wss://www.****.com:**/jeecg-boot/bigscreenwebsocket/refreshChart/***
服务器有反应，也能互相通讯
在www.jimureport.com中设置上，刷新，无效果，后台也无反应。
中间经过nginx代理（一度以为是nginx问题）但普通网页是正常的

##### 错误日志&截图：
![图片](https://user-images.githubusercontent.com/95299005/178690348-0bb58ca5-140a-48f1-baca-56c5529831bf.png)

![图片](https://user-images.githubusercontent.com/95299005/178690576-a543fe6b-83b7-4d18-83e2-178fe5f2433f.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档：http://report.jeecg.com/2306131
数据返回格式需与文档中一致
