### ISSUE TITLE
动态数据接口地址异常

### ISSUE THREAD

**Issue by fengyuan665** [jeecgboot/JimuReport#1162]
##### 版本号：
大屏报表

##### 问题描述：
大屏报表测试动态数据时 不管是get还是post方式，都显示接口数据异常

https://mp.18.show/xymmcat_yunapi/test

##### 错误日志&截图：
![图片](https://user-images.githubusercontent.com/109282714/179120158-2df31ab2-df53-4085-9f14-c939edddb685.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 1105570390** [comment]
我与遇到了同样的问题，首先是跨域问题，把你的接口做跨域处理，然后就是https访问http的问题，我之前接口是http的，改了这两样我的就可以访问了，你可以看看你的是不是跨域的问题，我测过你的给的接口，确实存在跨域问题，你在控制台输入下面字输入下面这些代码就知道了
`
var xhr = new XMLHttpRequest();
xhr.open('GET', 'https://mp.18.show/xymmcat_yunapi/test');
xhr.send(null);
xhr.onload = function(e) {
    var xhr = e.target;
    console.log(xhr.responseText);
}

`

**Comment by lvdandan16** [comment]
确认直接访问是否存在问题
