### ISSUE TITLE
分组聚合后排序错乱

### ISSUE THREAD

**Issue by zhanghahahahahaha** [jeecgboot/JimuReport#1163]
##### 版本号：
1.5.0

##### 问题描述：
两个问题：
1、
在取数SQL里对部门ID（设置了为数值）做了order by排序（排序第一位），显示列表时也的确是按照order by的顺序显示；但是将部门ID做聚合后，则顺序就乱了，不是按照1、2、3...，而是1、10、11、...20、21...这样的顺序，感觉是将ID强制作为文本来排序的。

2、
如果将多列分别聚合分组，前面列的排序选择默认，后面列的排序选择正序，实际结果还是前面的列一次做了排序，而不是按照后面选了正序的列进行排序。

##### 错误日志&截图：
第1个问题的截图：
列表时顺序是正常的：
![1](https://user-images.githubusercontent.com/108739923/179135648-f2cb3d65-d2e6-42f8-9548-8e523f471587.png)

分组后：
![2](https://user-images.githubusercontent.com/108739923/179135885-390481b2-b300-4f6c-8843-37ab2ab6fb42.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhanghahahahahaha** [comment]
官方最近怎么不来答复大家的issue了？

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
聚合排序的时候暂不支持配置数据类型是数值还是字符串
默认排序并不是不排序，也会排序

**Comment by syliang2020** [comment]
> 

1.5.版本，默认排序好像跟正序的效果一样
