### ISSUE TITLE
下拉框搜索输入值无法过滤

### ISSUE THREAD

**Issue by shangbandaka** [jeecgboot/JimuReport#1164]
##### 版本号：
1.5.0

##### 问题描述：
使用多选或单选下拉时 模糊查询无效

##### 错误日志&截图：
多选下拉 输入查询字符无任何效果
![1657872452266_9523E9E0-E2FC-4ede-BEA3-5AD3D9ECEC8E](https://user-images.githubusercontent.com/108644965/179181095-ca3d1bcb-0324-43b5-8f20-9783f6080f52.png)

单选下拉   输入字符后直接全部查询不到 怀疑是传输的是隐藏值而不是显示值
![1657872410279_4C03291F-C0C4-4c89-B7A7-5ED834118DAB](https://user-images.githubusercontent.com/108644965/179180985-e0d2ac7c-b01a-4244-bec5-dfccd72862e1.png)

![1657872376979_B29EA468-ED2E-43db-BB52-2F76CCEBBA33](https://user-images.githubusercontent.com/108644965/179180901-a37be101-4ce9-45cc-99f1-e0578896c922.png)

##### 重现步骤：
使用官方的查询条件示例：https://bootapi.jeecg.com/jmreport/view/590432931076722688
1多选下拉：打开查询栏，点击请选择职务下拉，在请输入查询条件中输入相应字符 ，下拉无任何反应，未按输入值过滤
2单选下拉：点击性别下拉，会弹出男女两个选项下拉 ，在输入框中输入男，所有数据都没了，怀疑是按隐藏值进行过滤

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
归集到：#138
