### ISSUE TITLE
积木能不能日期动态格式化

### ISSUE THREAD

**Issue by kerasking** [jeecgboot/JimuReport#1165]
##### 版本号：
1.5.0
##### 问题描述：
报表查询有个条件是下拉框，有日，月，年 这种选项，支持日期组件格式动态改变日期格式化吗？，比如我选择日的时候 yyyy-MM-dd，选择月的时候 yyyy-MM，选年 yyyy
想做的效果就是一个日期组件里按条件改变日期类型

##### 错误日志&截图：
日
![image](https://user-images.githubusercontent.com/998105/179240175-2ed7033d-baaa-474e-9a7f-5466469dc871.png)

月
![image](https://user-images.githubusercontent.com/998105/179240257-10e2f707-66f5-4947-9198-b5517d5d0971.png)

年
![image](https://user-images.githubusercontent.com/998105/179240332-dff7d2e9-ff04-4729-b9ac-a1f765242597.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by joneyjay** [comment]
设定区间值 给上当前时间 再做日期运算就可以动态了

**Comment by lvdandan16** [comment]
不支持
