### ISSUE TITLE
[功能咨询]请问是否支持在API请求时传入指定参数

### ISSUE THREAD

**Issue by dll233** [jeecgboot/JimuReport#1168]
##### 版本号：
积木1.5.0

##### 问题描述：
现有需求：打印订货单。
尝试的操作：①向积木报表传入一个参数（订货单id），②积木拿到id，通过api中配置好的id参数进行查询，③后端返回此订货单下商品列表，④积木并打印显示该列表

##### 我的问题：
我的问题：积木是否支持如上的操作？
参考此文档后`http://report.jeecg.com/2118420`，文档似乎没有指出这种情况下 积木如何接收id，即上述的①②之间步骤。
尝试的操作：直接将id参数拼接到 `http://localhost:8085/jmreport/view/707539717480706048?id=${id}`
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by dll233** [comment]
补充：如果有其他实现需求的方式，还望告知，谢谢：D

**Comment by dll233** [comment]
问题已经解决

**Comment by chency-jn** [comment]
> 

解决了？怎么解决的
