### ISSUE TITLE
除法问题

### ISSUE THREAD

**Issue by 13806110915** [jeecgboot/JimuReport#1170]
##### 版本号：
缺省。

##### 问题描述：
C3=3，D3=6
=C3/D3的结果为0，不是0.5
直接写=3/6，结果是0.5
##### 错误日志&截图：

![S834J8N_3{`MXR{}GPUVE{R](https://user-images.githubusercontent.com/43401399/179443655-9ad85a7b-4345-4916-ae40-a7163f8da43c.png)
![YJFBZW_X(I{G{@QZX04Z I](https://user-images.githubusercontent.com/43401399/179443693-8058848f-e784-49ea-84f2-aa1bd2a3b25a.png)

##### 重现步骤：
C3=3，D3=6
=C3/D3的结果为0，不是0.5
直接写=3/6，结果是0.5
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
=C3/D3  不支持单元格除法
