### ISSUE TITLE
图表绑定SQL数据集，运行报错

### ISSUE THREAD

**Issue by Action45** [jeecgboot/JimuReport#1171]
##### 问题描述：图表配置SQL数据集，点击运行报错

1、SQL数据集，数据预览是有数据的
![image](https://user-images.githubusercontent.com/87290598/179456526-20054260-ee1f-443e-b29d-f06354c3f764.png)
2、选择图表并配置该数据源
![image](https://user-images.githubusercontent.com/87290598/179457400-3f87cd00-342d-4915-83b3-b2de3a799f99.png)

点击运行后出现下图错误

##### 错误日志&截图：

/jmreport/qurestSql接口返回数据null 
![image](https://user-images.githubusercontent.com/87290598/179456328-9ba27a27-e948-4b34-8ae0-b19cb58f628b.png)

导致Console出错：
![image](https://user-images.githubusercontent.com/87290598/179456148-8063e89f-cc9e-4f59-9ded-9004a315bdbe.png)

##### 重现步骤：
如上。

报表SQL：
SELECT t.sDate ,t.energy_id ,t.energy_name ,t.num ,t.cost FROM (
select '2022-03' as sDate,	354538254603264 as energy_id,	'消防水' as energy_name, 	24.00 as num, 	26.00 as cost 
union
select '2022-03' as sDate,	354538328798208 as energy_id,	'自来水' as energy_name, 	20.00 as num, 	22.00 as cost 
union
select '2022-03' as sDate,	354721364814848 as energy_id,	'风电	' as energy_name, 12.00	 as num, 13.00	 as cost 
union
select '2022-04' as sDate,	354538254603264 as energy_id,	'消防水' as energy_name, 	24.00 as num, 	26.00 as cost 
union
select '2022-04' as sDate,	354538328798208 as energy_id,	'自来水' as energy_name, 	20.00 as num, 	22.00 as cost 
union
select '2022-04' as sDate,	354721364814848 as energy_id,	'风电	' as energy_name, 12.00	 as num, 13.00	 as cost 
union
select '2022-05' as sDate,	354538254603264 as energy_id,	'消防水' as energy_name, 	21.00 as num, 	55.11 as cost 
union
select '2022-06' as sDate,	354538254603264 as energy_id,	'消防水' as energy_name, 	67.00 as num, 	71.00 as cost 
) t 
WHERE t.sDate BETWEEN DATE_FORMAT(DATE_SUB('${statisticsDate}-01', INTERVAL 11 MONTH), '%Y-%m')
  AND '${statisticsDate}'

参数statisticsDate 默认上月 =dateStr('yyyy-MM', -1)
![image](https://user-images.githubusercontent.com/87290598/179457774-6eba6c7d-d059-43bf-a638-5d76bbe8acbd.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
