### ISSUE TITLE
API接口设置查询条件，例年份，表格展示时，表头某列，根据查询字段“年份”的取值，动态显示该列的列名称

### ISSUE THREAD

**Issue by C20190420** [jeecgboot/JimuReport#1172]
##### 版本号：
jimureport-spring-boot-starter  1.5.1

##### 问题描述：
API接口设置查询条件，例年份，表格展示时，表头某一列，根据查询字段“年份”的取值，动态显示该列的列名，是否支持？
即：如何在预览页面动态显示查询字段的取值

##### 错误日志&截图：
![1658131266742](https://user-images.githubusercontent.com/71625913/179468582-923ff4af-eb7f-4eca-9228-3c947977a185.png)
![Uploading 1658131310745.png…]()

##### 重现步骤：
1、新增一个API接口，设置某个字段为查询条件
2、设计报表，列固定，但是列名称从查询条件取值动态显示

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by C20190420** [comment]
已查到解决方案

**Comment by yujun666** [comment]
大哥咋解决的？ 有同样问题。
