### ISSUE TITLE
使用https时报错

### ISSUE THREAD

**Issue by yzmking** [jeecgboot/JimuReport#1175]
##### 版本号：
1.4.2

##### 问题描述：
使用https时，到show接口会报 “"api连接超时，请重试！” ，而当参数中有配置 字典api的时候，getQueryInfo接口会报connect timed out 错误

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/44563730/179644487-dc9c9528-63c2-4351-9952-c49d9549dc49.png)
![image](https://user-images.githubusercontent.com/44563730/179644636-7eb80211-429a-4b85-aeb0-5557325cb68f.png)
![1658194440069](https://user-images.githubusercontent.com/44563730/179645265-b4fd4ed3-b782-4811-bc8a-339148ae0a27.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by disabilites** [comment]
你好，请问找到解决办法了嘛？

**Comment by yzmking** [comment]
只是我们自己网路配置有问题而且，不是项目的问题

**Comment by disabilites** [comment]
> 只是我们自己网路配置有问题而且，不是项目的问题

好的，谢谢。

**Comment by disabilites** [comment]
请问下，你使用nginx代理后端接口的嘛

**Comment by yzmking** [comment]
对的

**Comment by disabilites** [comment]
可以给我看下怎么配的嘛，我也是用nginx代理的，但唯独/jireport/show接口一直请求报错

**Comment by yzmking** [comment]
我这边还没有成功，因为配置网路还没有弄好，到时候确定可以没有问题后再发给你

**Comment by disabilites** [comment]
> 我这边还没有成功，因为配置网路还没有弄好，到时候确定可以没有问题后再发给你

好的，十分感谢

**Comment by yzmking** [comment]
我这边还没有成功，因为配置网路还没有弄好，到时候确定可以没有问题后再发给你

**Comment by yzmking** [comment]
> > 我这边还没有成功，因为配置网路还没有弄好，到时候确定可以没有问题后再发给你
> 
> 好的，十分感谢

你们也是用https吗？你们服务器能  telnet 通https的那个IP 端口吗，我们的情况就是telnet不通，所以访问不到，我们现在就直接用 http:127.0.0.1:项目端口  这样绕过ngnix，直接访问项目，这样是可以的

**Comment by disabilites** [comment]
> 对，ping都不通的话，是访问不了，那 改成A服务器的IP+端口 可以的话就先用着，如果你不想在报表中写死 IP 也可以再项目配置文件配置IP和端口， ![image](https://user-images.githubusercontent.com/44563730/179924818-bf407edc-4fd7-4f8d-b7c9-e32cca9f9167.png) 然后用 #{api_base_path} 代替 {{ domainURL }}

好的，不过修改apiBasePath每次还得重新打包，也不是很方便。
我是直接在数据库里修改api地址，不用在设计器里一个个点开修改。

**Comment by yzmking** [comment]
> > 对，ping都不通的话，是访问不了，那 改成A服务器的IP+端口 可以的话就先用着，如果你不想在报表中写死 IP 也可以再项目配置文件配置IP和端口， ![image](https://user-images.githubusercontent.com/44563730/179924818-bf407edc-4fd7-4f8d-b7c9-e32cca9f9167.png) 然后用 #{api_base_path} 代替 {{ domainURL }}
> 
> 好的，不过修改apiBasePath每次还得重新打包，也不是很方便。 我是直接在数据库里修改api地址，不用在设计器里一个个点开修改。

ok
