### ISSUE TITLE
SQL数据库call 存储过程参数如果不设置默认值，报表预览报错。

### ISSUE THREAD

**Issue by guyust** [jeecgboot/JimuReport#1177]
##### 版本号：
1.5.2

##### 问题描述：
设置虚拟默认值，报错信息如下：
CallableStatementCallback; SQL [{CALL procProjectLearnDetail('1', '1' ,'1')}]; ResultSet is from UPDATE. No Data.; nested exception is java.sql.SQLException: ResultSet is from UPDATE. No Data

不设置默认值，报错信息如下：
 CallableStatementCallback; uncategorized SQLException for SQL [{CALL procProjectLearnDetail('', '' ,'')}]; SQL state [HY000]; error code [1366]; Incorrect integer value: '' for column 'coursetype' at row 1; nested exception is java.sql.SQLException: Incorrect integer value: '' for column 'coursetype' at row 1

但是同样的参数，如最后一张图的配置，使用sql查询就一切正常。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/37604738/180639735-d9ff9743-4fac-4b62-9b36-ca332ddd4d8e.png)
![image](https://user-images.githubusercontent.com/37604738/180639757-f6687a3f-b9a2-4e9f-883e-4237c84d92f3.png)
![image](https://user-images.githubusercontent.com/37604738/180639771-b4078cb9-5c00-4786-8763-71e97568a4dc.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by guyust** [comment]
不设置参数默认值，预览效果如下。
![image](https://user-images.githubusercontent.com/37604738/180639809-e8d2f797-a13e-44d2-9194-53e8f7c65c85.png)

使用sql查询，其他参数设置，js增强配置一样。预览效果如下：
![image](https://user-images.githubusercontent.com/37604738/180639828-ecbed4e5-60c1-4a17-bda4-82ed134ee085.png)

上面两张图的差异就是第一个使用了存储过程，第二张正常使用sql。

建议优化为，使用存储过程时，报表加载时，不要默认进行参训操作。待用户选择完查询参数，点击查询按钮再触发查询操作。这样就可以解决问题。

**Comment by joneyjay** [comment]
@guyust 大佬您好 我想向您请教个调用存储过程的问题

**Comment by guyust** [comment]
> 

什么问题？

**Comment by joneyjay** [comment]
@guyust 现在调用没问题了 就是这个api数据源分页有问题 我勾选了分页没效果

**Comment by lvdandan16** [comment]
存储过程不支持分页

**Comment by spinechooo** [comment]
大佬 你解决这个问题了吗

**Comment by joneyjay** [comment]
@spinechooo 什么问题
