### ISSUE TITLE
根据条件修改单元格字体

### ISSUE THREAD

**Issue by zhanghahahahahaha** [jeecgboot/JimuReport#1178]
##### 版本号：
1.5.2

##### 问题描述：
除了通过if和color来改变单元格字体颜色和背景颜色，还有没有办法修改单元格字体为粗体和改变字体大小？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by joneyjay** [comment]
@zhanghahahahahaha 
大佬您好 我想请教你个问题

**Comment by zhanghahahahahaha** [comment]
> @zhanghahahahahaha 大佬您好 我想请教你个问题

what？我也是在给官方提issue。
把你的问题说出来吧，看能不能一起探讨

**Comment by lvdandan16** [comment]
不支持修改单元格字体为粗体和改变字体大小
