### ISSUE TITLE
横向分组出现数据出不来，第一种情况：多次点击保存，第二种情况：SQL数据集  第三种情况：修改报表名称后保存

### ISSUE THREAD

**Issue by baiyixiangqin** [jeecgboot/JimuReport#1179]
##### 版本号：

1.5.2
##### 问题描述：
1.多次保存会出现这个问题
2.点击数据集管理会出现这个问题（没有修改任何值）
3.修改报表名称

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/102849584/180697535-9092a430-c8f6-4595-812c-2af5a113d4d1.png)

##### 重现步骤：
[横向分组表头显示问题.zip](https://github.com/jeecgboot/JimuReport/files/9177959/default.zip)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by joneyjay** [comment]
大佬您好 方便向您请教个例子吗

**Comment by baiyixiangqin** [comment]
@joneyjay 这个称呼不敢不敢，相互解决，相互探讨而已

**Comment by joneyjay** [comment]
@baiyixiangqin 我想问一下自定义下拉树这个方法咋用，我有点不太会用官方例子，方便加一下qq吗大佬

**Comment by baiyixiangqin** [comment]
@baiyixiangqin  这个问题刚好遇见过，自定义下拉树还是有些问题的，会无限循环套循环，所以我就没在使用了

**Comment by joneyjay** [comment]
@baiyixiangqin 我看官方文档我不太会用 大佬方便截一下您的方法我理解一下吗 我看看能不能解决无线循环

**Comment by baiyixiangqin** [comment]
@joneyjay 
![image](https://user-images.githubusercontent.com/102849584/180724981-9ad31dcb-f210-44eb-8beb-457221a9071c.png)

**Comment by joneyjay** [comment]
@baiyixiangqin 谢谢大佬

**Comment by joneyjay** [comment]
大佬方便指点一下官方这个下拉树怎么用吗（方法写好了域名数据我查出来了 好像前端还是没办法用到） 有偿（我只能请您吃外卖）

**Comment by baiyixiangqin** [comment]
@joneyjay  有什么报错吗？

**Comment by baiyixiangqin** [comment]
@joneyjay  是不是有跨域问题？

**Comment by joneyjay** [comment]
不是的 应该是我方法不会用（我想只查当前列的自定义下拉单选怎么实现）

**Comment by baiyixiangqin** [comment]
@joneyjay  自定义下拉单选，在js增强使用

**Comment by joneyjay** [comment]
![image](https://user-images.githubusercontent.com/64302253/180754392-079b3fcb-aa89-419a-aa00-bcff9be32020.png)
我如果是这种参数类型的搜索条件没办法下拉单选吗

**Comment by baiyixiangqin** [comment]
@joneyjay 这种只能适用于下拉树的，不是自定义下拉单选

**Comment by joneyjay** [comment]
![image](https://user-images.githubusercontent.com/64302253/180754535-3d7ab58d-bb39-4330-8753-62e6917f8dd6.png)
我只想这样下拉单选一个值 选中后再进行传参搜索（应该怎么弄）

**Comment by baiyixiangqin** [comment]
http://report.jeecg.com/2373408

**Comment by joneyjay** [comment]
大佬如果我是参数类型是如何使用js增强
![image](https://user-images.githubusercontent.com/64302253/180901436-9fa34fd6-48fc-4f11-b252-e3d55ae1cff0.png)

**Comment by baiyixiangqin** [comment]
@joneyjay  
![Uploading image.png…]()

**Comment by baiyixiangqin** [comment]
@joneyjay  
![image](https://user-images.githubusercontent.com/102849584/180907088-9d665016-71d0-412c-98f5-47bee7a511ca.png)

**Comment by joneyjay** [comment]
![Uploading image.png…]()
@baiyixiangqin

**Comment by joneyjay** [comment]
![image](https://user-images.githubusercontent.com/64302253/180907489-236d2f6b-1fb6-4f9b-8de1-4819a6a4edcf.png)
@baiyixiangqin

**Comment by baiyixiangqin** [comment]
@joneyjay  编码名称给错了，在字段前，应该给的是com ，不是ioca

**Comment by joneyjay** [comment]
![image](https://user-images.githubusercontent.com/64302253/180907957-3a433c86-1215-4296-9612-55464acd0031.png)
![image](https://user-images.githubusercontent.com/64302253/180908007-7851b248-53e6-4a33-8852-20461d0be31c.png)

**Comment by joneyjay** [comment]
@baiyixiangqin 给com了也是不显示 后台报值为null

**Comment by joneyjay** [comment]
![image](https://user-images.githubusercontent.com/64302253/180908156-f97cfdd2-d743-4423-b8f9-0a36e0eae4ae.png)
后台报自定义路径值为null

**Comment by joneyjay** [comment]
![image](https://user-images.githubusercontent.com/64302253/180908248-29d70618-53c9-40e3-86a8-4d3306525409.png)
这是我接口的数据

**Comment by baiyixiangqin** [comment]
@joneyjay  ![image](https://user-images.githubusercontent.com/102849584/180908162-8dbce28e-f6bf-4369-a9dc-db63da46c33e.png)
这里不能这么给呀

**Comment by joneyjay** [comment]
@baiyixiangqin 官方文档不是这样给的吗
![image](https://user-images.githubusercontent.com/64302253/180908378-7683aed6-9504-4714-afd4-464099274bf9.png)

**Comment by baiyixiangqin** [comment]
@joneyjay  这里还是要发布到向上的地址

**Comment by joneyjay** [comment]
@baiyixiangqin 这样给了也是null值
![image](https://user-images.githubusercontent.com/64302253/180908777-2c02b605-5700-49ea-9c36-ccb21340e514.png)

**Comment by baiyixiangqin** [comment]
@joneyjay  你少了一个}

**Comment by joneyjay** [comment]
@baiyixiangqin 调好了 但是好像还是识别不到这个company
![image](https://user-images.githubusercontent.com/64302253/180910242-bd38c709-3f01-4b1b-826a-fd7fcf2bc1cb.png)
我下面这里读取值是不是有点问题
![image](https://user-images.githubusercontent.com/64302253/180910242-bd38c709-3f01-4b1b-826a-fd7fcf2bc1cb.png)

**Comment by joneyjay** [comment]
@baiyixiangqin 噢噢 识别到了 但是好像获取值还是获取不到
![image](https://user-images.githubusercontent.com/64302253/180910364-c8e3107b-bc80-4c41-a244-d0c7daae72ed.png)

**Comment by joneyjay** [comment]
是不是我获取值这里有点问题
![image](https://user-images.githubusercontent.com/64302253/180910429-f96838b4-8a72-421b-9cc5-33ce7d215240.png)

**Comment by baiyixiangqin** [comment]
@joneyjay  你要根据官方下拉单选走，
![image](https://user-images.githubusercontent.com/102849584/180910679-a65bca10-a9de-4e30-9ddd-741fd88c7b94.png)
命名也要一样

**Comment by joneyjay** [comment]
@baiyixiangqin 好的 我给到值了也可以下拉看到字段了
但是只能给字段进行JS增强吗，报表参数如何增强（就是不显示的字段，${参数}这种如何进行JS增强）
![image](https://user-images.githubusercontent.com/64302253/180915485-b545ba62-3926-414b-bd3b-f4674f423c4f.png)

**Comment by baiyixiangqin** [comment]
@joneyjay  不显示字段？我还是没明白

**Comment by joneyjay** [comment]
不是 就是我调用的是存储过程嘛 然后我sql是写了条件 条件不都是${}这样传参的吗，那我如何对这个参数进行增强

**Comment by baiyixiangqin** [comment]
@joneyjay  QQ给我

**Comment by joneyjay** [comment]
892419552
