### ISSUE TITLE
MongDB 数据源导出数据， 分页去掉了，导出excel只有100条数据

### ISSUE THREAD

**Issue by kerasking** [jeecgboot/JimuReport#1182]
##### 版本号：

1.5.2
##### 问题描述：

MongDB 数据源 导excel只能导出 100条数据
##### 错误日志&截图：

MongDB 数据源 导excel只能导出 100条数据

sql代码：
db.getCollection('report_day_gas').find({}，{ps_name:1,area_name:1,mp_name:1,data_time:1}).limit(5000);

导出excel 只有100 条数据。

![image](https://user-images.githubusercontent.com/998105/181199769-524164d3-08a2-4ab1-ae90-de953ba8678f.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by kerasking** [comment]
@zhangdaiscott @accpman @tygithub1 @lvdandan16 比较着急，帮忙看看

**Comment by lvdandan16** [comment]
收录 ws

**Comment by lvdandan16** [comment]
已修复
