### ISSUE TITLE
报表打印多出空白页问题

### ISSUE THREAD

**Issue by joker-zxs** [jeecgboot/JimuReport#1184]
##### 问题描述：
报表设计的时候不满一页,但是打印的时候多出来两页空白的纸张

##### 错误日志&截图：

![DR_5 MRX$8W0UI B2SYY_2P](https://user-images.githubusercontent.com/53653032/181668128-7a922da0-b17f-4d70-9dc1-9571a3abf0bd.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
后边是不是有多余的空白行，删除后边的整行试一下
