### ISSUE TITLE
api数据源，目前一个页面上显示最多行数是 2000行不到，再多就显示不出来了，这是做了限制吗？在那里设置这个值呢？

### ISSUE THREAD

**Issue by kerasking** [jeecgboot/JimuReport#1186]
##### 版本号：

1.5.2
##### 问题描述：

api数据源，目前一个页面上显示最多行数是 2000行不到，再多就显示不出来了，这是做了限制吗？在那里设置这个值呢？
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
预览界面吗？预览界面不分页的情况下是没有做限制的

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
