### ISSUE TITLE
api数据集调用接口返回xml 解析报错

### ISSUE THREAD

**Issue by gcm1314** [jeecgboot/JimuReport#1187]
##### 问题描述：
api数据集

springboot集成积木，报表调用restful接口,在postman上post请求测试返回正常的JSON格式；
积木报表api数据集设计，点击“api”解析报错

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/15045801/181716210-6c4a6e02-42ae-4185-9b39-410c79f25a9d.png)
![image](https://user-images.githubusercontent.com/15045801/181716282-52167ef4-833d-4999-af60-a7879fcdbce5.png)
![image](https://user-images.githubusercontent.com/15045801/181716322-8a3c6003-8049-40a6-97a7-5afa9dfc34b9.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档：http://report.jeecg.com/2020177
确认一下返回数据格式正确吗
