### ISSUE TITLE
api接口请求是否支持json格式的参数

### ISSUE THREAD

**Issue by chency-jn** [jeecgboot/JimuReport#1190]
##### 版本号：
1.5.2

##### 问题描述：
api接口数据时，因为业务数据参数较多，系统都是采用的json格式的参数对象，在设计报表时是否能够支持这种 json格式的参数呢？怎么使用呢？

##### 错误日志&截图：
![Xnip2022-08-04_11-16-24](https://user-images.githubusercontent.com/30253263/182755483-6d011d05-32a3-4834-b5f1-94c516b41625.jpg)

##### 重现步骤：
其他人有没有好的方案

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
