### ISSUE TITLE
堆叠柱状图、普通折柱图卡死

### ISSUE THREAD

**Issue by zhanghahahahahaha** [jeecgboot/JimuReport#1192]
##### 版本号：
1.5.2

##### 问题描述：

报表使用堆叠柱状图、或者普通折柱图后，在预览时页面一直加载不出来，中心蓝色圆点一直闪，日志也没有错误产生，
删除后，可以正常预览，是不是有什么bug？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
是不是数据没加载出来？可在官网上复现一下

**Comment by zhanghahahahahaha** [comment]
用默认的api是可以显示的，但是用SQL数据集就显示不出来，后台日志看到SQL也已经执行了，但是页面就是渲染不出来，等n分钟还是不行
