### ISSUE TITLE
上传excel js报错

### ISSUE THREAD

**Issue by weiqun6062415** [jeecgboot/JimuReport#1193]
##### 版本号：

1.5.2
##### 问题描述：

上传excel js报错
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/42401499/182792847-cd1a3117-6164-40f7-b899-5b92e877dd2d.png)

##### 重现步骤：
本地项目出现的

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
未复现此问题，可将excel上传上来，我们复现一下

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
