### ISSUE TITLE
查询设置默认时间，部署服务器报错，本地则不会报错

### ISSUE THREAD

**Issue by lyswco** [jeecgboot/JimuReport#1195]
##### 版本号：
1.5.2

##### 问题描述：
使用jeecg-boot里面集成的，积木报表更新到最新版本了，设置了时间查询，时间设置#{sysDate}，在本地测试不会报错，部署到服务器上则一直报错，去掉这个变量则正常，新旧版本都一样报错

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/17328717/182824883-28ab25ca-e3cd-41b1-8157-2e3f828a1665.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
未复现此问题，可确认本地和服务器上数据格式是一样的吗
