### ISSUE TITLE
导出excel

### ISSUE THREAD

**Issue by Andy199211** [jeecgboot/JimuReport#1196]
##### 版本号：

1.5.2
##### 问题描述：

设计的报表  有些地方没有单元格边框线，但是导出的有，而且还去不掉
##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/84311658/182978349-400736a9-6f75-4584-b7fb-fe32c360f350.png)

##### 重现步骤：
在单元个输入相关内容后，没有添加单元格边框，打印预览都没有问题，但是导出excel会多出来单元格边框线

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
归集：#138
