### ISSUE TITLE
API数据集无法进行横向分组

### ISSUE THREAD

**Issue by joneyjay** [jeecgboot/JimuReport#1199]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/64302253/183061007-b37e98f8-e05c-42ed-b651-3f6134a79e55.png)
![image](https://user-images.githubusercontent.com/64302253/183061204-3399b5a3-d405-4be0-a41a-78546ea8afe9.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
未复现此问题 这个示例就是用的api分组
https://cloud.jimureport.com/jmreport/view/590442764001693696
