### ISSUE TITLE
如何关闭后台日志？文档里没找到

### ISSUE THREAD

**Issue by yy35959199** [jeecgboot/JimuReport#1200]
##### 版本号：
1.4.32
SpringBoot 2.7

##### 问题描述：
每次查询时后台都会刷几百行日志，很快日志文件就几个G了

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/37442303/183284950-0cf7a0f6-9484-4315-af16-ad428bb6cab8.png)

请问如何配置来关闭后台日志打印？或者修改为debug才输出这些日志？

**Comment by lvdandan16** [comment]
积木报表不支持关闭日志
