### ISSUE TITLE
超链接报表钻取原始参数数据集传参不正确

### ISSUE THREAD

**Issue by Alocem** [jeecgboot/JimuReport#1204]
##### 版本号：
1.5.2

##### 问题描述：
为数字单元格添加超链接，原始参数从数据集获取，当单元格里的数字相同时，点击超链接跳转会带出第一次出现该数字的单元格里的参数，数字不同的单元格不会出现这个问题，希望即使点击相同数字的单元格也能取该行指定的参数值。

##### 错误日志&截图：
![11](https://user-images.githubusercontent.com/71489252/183556903-db99395e-78c1-47f0-828a-d2a6927530fd.png)
![22](https://user-images.githubusercontent.com/71489252/183556910-51a27d55-3f9b-457a-a358-b673bb7da6fd.png)
![33](https://user-images.githubusercontent.com/71489252/183556915-d59704d5-c70f-4f48-adca-36b787fb9741.png)
![44](https://user-images.githubusercontent.com/71489252/183556928-bedb7f48-212c-4d9f-b094-a1e1f0fcb416.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhanghahahahahaha** [comment]
试试：='施工队'

**Comment by Alocem** [comment]
> 尝试：='施工队'

传递的参数变成null了，而且 ='施工队' 在分组后取的值为null
![11](https://user-images.githubusercontent.com/71489252/183817352-407d3124-de83-4cc6-b455-16d84f723cef.png)

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
请查看http://report.jeecg.com/2427407#31__112 网络钻取配置->3.1字段配置中有说明点击的单元格值不允许重复（钻取一致），请参考表达式`自定义表达式配置`

**Comment by duanwenbing** [comment]
这个问题有解决没
