### ISSUE TITLE
修改单元格字体颜色

### ISSUE THREAD

**Issue by Alocem** [jeecgboot/JimuReport#1206]
##### 版本号：
1.5.2

##### 问题描述：
单元格内的文本支持两种字体颜色吗？类似Excel。

##### 错误日志&截图：
![1](https://user-images.githubusercontent.com/71489252/183801011-09d83c5f-384e-4363-af24-e405cde312e2.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
