### ISSUE TITLE
导出数据查询条件取值错误

### ISSUE THREAD

**Issue by Acechengui** [jeecgboot/JimuReport#1208]
##### 版本号：
1.5.2

##### 问题描述：
excel导出时,若配置了默认值,在预览界面更改查询值时,查询正常,但是导出依然取得是默认值,而不是取得我在查询输入框改的值

##### 错误日志&截图：

![3](https://user-images.githubusercontent.com/63096199/184077580-c5edf755-7619-47cf-beb8-73a79e71307e.png)
![2](https://user-images.githubusercontent.com/63096199/184077588-d39d9b11-f03e-4a2c-9b78-8c3df0d12660.png)
![1](https://user-images.githubusercontent.com/63096199/184077593-94a70575-df6e-4b2e-9055-dc876e025beb.png)

##### 重现步骤：
在官网可复现

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
