### ISSUE TITLE
下拉树组件不支持级联勾选/全选/取消权限，数据量大的时候希望还能提供查询功能，类似多选下拉框的搜索效果

### ISSUE THREAD

**Issue by chenhaoqiang** [jeecgboot/JimuReport#1209]
##### 版本号：
v1.5.2

##### 问题描述：
1. 下拉树组件不支持级联勾选/全选/取消权限
![image](https://user-images.githubusercontent.com/20062034/184089333-eb3132ce-38a2-4a84-8089-5431a95869e5.png)
2. 数据量大的时候希望还能提供查询功能，类似多选下拉框的搜索效果
![image](https://user-images.githubusercontent.com/20062034/184089385-15f84d58-cb4b-4f77-929b-6715c077383c.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持
归集到：#138
