### ISSUE TITLE
请问小计的合计列，合计是否改为其他文本？

### ISSUE THREAD

**Issue by Andy199211** [jeecgboot/JimuReport#1211]
##### 版本号：
1.5.2

##### 问题描述：
请问小计的合计列，合计是否改为其他文本？
是否可以和前一个单元格合并成一个单元？

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/84311658/184313746-0ac201ce-574c-4831-ad57-55b19a6b57c0.png)

##### 重现步骤：
1.所属种类 小计设置的分组依据设置为是；
2.本次付款金额的小计设置，聚合方式设置为求和；
3.自动出现合计列
问题：：
    现合计两个字想修改为其他文本是否可以设置？？
    合计行的序号列和收款单位列是否可以合并？？

**Comment by lvdandan16** [comment]
‘合计’两个字不支持修改
第二个问题没明白什么意思

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
