### ISSUE TITLE
图表背景图片显示失败

### ISSUE THREAD

**Issue by wengxingxia** [jeecgboot/JimuReport#1212]
##### 版本号：
1.5.0

##### 问题描述：
图表背景图片设置，图片上传成功，但是显示失败，前端图表背景图片的请求url不对。

##### 错误日志&截图：
jmsheet.js?v=1.0.7:2 Uncaught DOMException: Failed to execute 'createPattern' on 'CanvasRenderingContext2D': Source image is in the 'broken' state.

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
未复现此问题，确认一下你自己是用的哪种上传方式
