### ISSUE TITLE
循环块太坑人了

### ISSUE THREAD

**Issue by alanqwy** [jeecgboot/JimuReport#1214]
##### 问题描述：
单元格设置循环块,然后把单元剪切到其他单元格,复制其他内容到之前设置循环块的单元格,再剪切走
循环块将永远无法取消,是否可以增加 强制取消循环块的功能呢?

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/111260288/184696813-ffbc40b8-8343-4eca-af97-f0436f0a64f7.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
归集到：#138
