### ISSUE TITLE
springBoot项目使用的是PG数据库，积木报表初始化sql用的是mysql 要如何兼容

### ISSUE THREAD

**Issue by zhangxinyuan1** [jeecgboot/JimuReport#1216]
##### 版本号：
 <jimureport.version>1.5.2</jimureport.version>

##### 问题描述：
启动报错
DataSourceConfig.class]: Unsatisfied dependency expressed through method 'dataSource' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'basicDataSource' defined in class path resource [com/huaxincem/qc/common/config/DataSourceConfig.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.jdbc.DataSourceInitializerInvoker': Invocation of init method failed; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'dataSource': Requested bean is currently in creation: Is there an unresolvable circular reference?
08-17 08:48:36.517 INFO  restartedMain o.a.c.c.StandardService                  173: Stopping service [Tomcat]

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
url 配置有问题吧，截图看配置
