### ISSUE TITLE
动态合并格

### ISSUE THREAD

**Issue by Andy199211** [jeecgboot/JimuReport#1217]
##### 版本号：

1.5.2
##### 问题描述：
根据文档操作，右键为什么没有动态合并格的功能？

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/84311658/185021158-5edaf9c7-8ed1-4dba-8bfc-fa24f4f68cf1.png)

##### 重现步骤：

![%X33{RZGGTOMQ4T`2PYNGH5](https://user-images.githubusercontent.com/84311658/185021247-783a5972-c2ad-4611-986c-80aad0ebc3ae.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
滚动条下拉
