### ISSUE TITLE
源码不开放如何修改权限拦截？

### ISSUE THREAD

**Issue by zhangxinyuan1** [jeecgboot/JimuReport#1218]
##### 版本号：
 <jimureport.version>1.5.2</jimureport.version>

##### 问题描述：
 排除权限拦截
修改org.jeecg.config.shiro.ShiroConfig加入以下代码，这个应该是们封装的包，源码没开放如何排除权限拦截呢？？？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
org.jeecg.config.shiro.ShiroConfig 是jeecgboot项目的配置，只是参考

http://report.jeecg.com/2208864#Token_5
