### ISSUE TITLE
两个数据库一样的表，数据不同，当一个表的数据来展示，可以么？

### ISSUE THREAD

**Issue by hdmalzy** [jeecgboot/JimuReport#1219]
##### 版本号：
1.5.2

##### 问题描述：
我有两个数据库，两个库都有一个一样的表，但存的数据不同，报表需要把两个库的表的数据取出来，当一个表的数据来展示，支持么？怎么做？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
直接使用两个数据集，但是不支持两个数据在同一行显示
