### ISSUE TITLE
canvas打印一直转圈

### ISSUE THREAD

**Issue by Aftery** [jeecgboot/JimuReport#1220]
##### 版本号：
1.5.1

##### 问题描述：

当某个值设为图片，但是没有值得时候，canvas打印一直转圈
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/37588923/185360375-81caf24b-fd7e-4cae-925d-7694c73fb451.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by tygithub1** [comment]
请使用html打印
