### ISSUE TITLE
新建报表 和  自动保存报表 提示token校验失败，后台日志显示token为空

### ISSUE THREAD

**Issue by zhangxinyuan1** [jeecgboot/JimuReport#1221]
##### 版本号：
<jimureport.version>1.5.2</jimureport.version>
环境: springBoot集成

##### 问题描述：
1、定时保存报表提示token校验失败，后台看到token为空。
2、新建报表提示token为空，校验失败。

##### 错误日志&截图：
![图片](https://user-images.githubusercontent.com/39943076/185580432-6e94763e-f61e-4838-b432-3b3d9a2f23c1.png)
![图片](https://user-images.githubusercontent.com/39943076/185580564-7e4db238-efc0-4989-98d8-d835b0012ff6.png)

![图片](https://user-images.githubusercontent.com/39943076/185580209-4c1b8789-9e67-48be-acb4-4773519d7260.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档：http://report.jeecg.com/2208864
