### ISSUE TITLE
spring boot 项目集成报错

### ISSUE THREAD

**Issue by BruceWang91** [jeecgboot/JimuReport#1224]
##### 版本号：
1.5.2

##### 问题描述：
默认采用jdk动态代理，引入依赖后启动项目报错，已尝试过添加事务注解无效，请问有其他方式解决吗

##### 错误日志&截图：
Description:

The bean 'jimuReportServiceImpl' could not be injected as a 'org.jeecg.modules.jmreport.desreport.service.a.e' because it is a JDK dynamic proxy that implements:
	org.jeecg.modules.jmreport.desreport.service.IJimuReportService

Action:

Consider injecting the bean as one of its interfaces or forcing the use of CGLib-based proxies by setting proxyTargetClass=true on @EnableAsync and/or @EnableCaching.

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by BruceWang91** [comment]
补充下我使用datart项目集成

**Comment by lvdandan16** [comment]
jdk什么版本？datart项目未集成过，不确定是否完全兼容
