### ISSUE TITLE
报表支持目录检索吗(当报表内容很多时)

### ISSUE THREAD

**Issue by yangyz** [jeecgboot/JimuReport#1225]
##### 版本号：
1.5.2

##### 问题描述：
报表支持目录检索吗(当报表内容很多时)
比如：
![_K%2S9NK`TN7D)4P@5L}YUE](https://user-images.githubusercontent.com/6257884/185892588-7110587f-2f04-4688-8db6-54e0dc9dccac.png)
![image](https://user-images.githubusercontent.com/6257884/185892798-63d637c4-cabc-47f3-bac0-4f6fdce0c400.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
哪个功能检索？

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
