### ISSUE TITLE
查询栏如何用部门组件查询

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/JimuReport#1226]
##### 版本号：
v1.5.2 

##### 问题描述：
查询栏如果用部门组件查询，比如想查A公司下面的软件部，没有看到部门组件，后台是用 v3.4.1版本最新的

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/90361617/186340628-f181f44f-99ab-4d55-b219-ccbbc1ee273b.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
没有专门的部门组件，
如果显示部门树 可以使用下拉树  参考文档：http://report.jeecg.com/2388194
其他的 下拉单选、多选均可使用
