### ISSUE TITLE
Api数据集接口超时报错

### ISSUE THREAD

**Issue by zDream** [jeecgboot/JimuReport#1227]
##### 问题描述：用api数据集，当接口请求时长超过1秒就报错，怎么能设置访问接口时长？
![image](https://user-images.githubusercontent.com/16067566/186386092-d601b250-5d42-4285-baf0-e3259d8f8e82.png)
设置 connect-timeout 时长无效

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/16067566/186385994-77704b56-c4cc-4be2-b36d-6e8608966eee.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
超过1秒就报错，应该是接口的问题把

**Comment by zDream** [comment]
应该的，

**Comment by ywm12345** [comment]
> 超过1秒就报错，应该是接口的问题把

我在这个1.3.1-beta版本也设置了这个参数，好像不生效，当接口超时后，报表就会报连接超时
