### ISSUE TITLE
微信小程序iframe嵌入积木报表后超连接跳转失败

### ISSUE THREAD

**Issue by AXXZSTHL** [jeecgboot/JimuReport#1229]
##### 版本号：
jimureport-example-1.4.2

##### 问题描述：
报表配置的超连接跳转，但是把页面使用iframe方式嵌入到微信小程序中，点击超连接页面跳转失败，不知道是不是因为小程序不支持window.open导致的

##### 错误日志&截图：
暂无

##### 重现步骤：
小程序嵌入报表页面，

**Comment by lvdandan16** [comment]
积木报表暂不支持移动端
