### ISSUE TITLE
下拉树联动没有

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/JimuReport#1231]
##### 版本号：
1.4.32

##### 问题描述：
下拉树联动没有，想做一个打勾父类联动子类的，这好像不支持，并且不支持单选或多选的配置

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/90361617/186849076-515e1e02-8596-4a1e-8079-4ed5fa7b9d66.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
