### ISSUE TITLE
旧版本升级上来的，老版本好着

### ISSUE THREAD

**Issue by 15389181696** [jeecgboot/JimuReport#1232]
##### 版本号：
1.5.2

##### 问题描述：
freemarker.core.InvalidReferenceException: The following has evaluated to null or missing: ==> reportConfig [in template "jmreport/desreport/index.ftl" at line 13, column 33] ---- Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)?? ---- ---- FTL stack trace ("~" means nesting-related): - Failed at: ${reportConfig} [in template "jmreport/desreport/index.ftl" at line 13, column 31] ----
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/112158864/186876363-8dda9536-232d-4cfd-9dee-0722ed1dc06e.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
看看是不是fastjson版本不对，升级版本试一下
