### ISSUE TITLE
打印功能，设定明细行行数

### ISSUE THREAD

**Issue by fuermoqian** [jeecgboot/JimuReport#1233]
##### 版本号：
1.5.2

##### 问题描述：
使用积木报表打印出入库单，设定明细行的行数，比如实际数据有20行，设置每页只能打印10行，那么就分2页打印

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by fuermoqian** [comment]
请问现在是否有这个功能？

**Comment by lvdandan16** [comment]
不支持
