### ISSUE TITLE
系统集成时，跳转至报表时，能否直接传参

### ISSUE THREAD

**Issue by onepiecewyz** [jeecgboot/JimuReport#1234]
##### 版本号：
v1.5.0

##### 问题描述：
想将积木报表集成到其他系统，积木报表这边有一个个人简历打印页面，默认显示person=’张三‘的简历。现在希望从第三方系统通过url：http://127.0.0.1:8085/jmreport/index/723497428580757504?token=xxxx 跳转过来时，直接传递参数person=‘李四’，并显示李四的简历。目前没看到怎么传参，请教一下

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by onepiecewyz** [comment]
自己在技术文档里找到了，直接加参数即可http://127.0.0.1:8085/jmreport/index/723497428580757504?token=xxxx&person=xxx

**Comment by zhangxinyuan1** [comment]
@onepiecewyz jmreport/index  这个页面是能带上，如新建页面呢，又是一个新的URL 如何带参数呢？
