### ISSUE TITLE
新建报表页面和设计页面自动保存 无法获取Token

### ISSUE THREAD

**Issue by zhangxinyuan1** [jeecgboot/JimuReport#1236]
##### 版本号：
1.5.2

##### 问题描述：

以下两个页面进入无法获取token，要如何解决？
/jmreport/save
/jmreport/excelQueryName   
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档：http://report.jeecg.com/2208864
