### ISSUE TITLE
theme-color

### ISSUE THREAD

**Issue by zhangxinyuan1** [jeecgboot/JimuReport#1239]
##### 版本号：
1.5.2

##### 问题描述：
theme-color 主题背景颜色设置后为何不起作用？？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
报表没有这个功能

**Comment by zhangxinyuan1** [comment]
我看到很多报表设计器背景颜色可以使用二进制颜色码自定义，大多配置的是黑色背景，是否有此功能？
