### ISSUE TITLE
通过SQL数据集方式导出，使用Mysql 的 ORDER BY FIELD 不生效

### ISSUE THREAD

**Issue by sky-tujf** [jeecgboot/JimuReport#1241]
##### 版本号：

V1.5.2

##### 问题描述：

通过SQL数据集方式导出，使用Mysql 的 ORDER BY FIELD 不生效，同样的SQL在数据库中能正常按顺序查询，但导出发现顺序未按ORDER BY FIELD 排序导出

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
导出什么？

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
