### ISSUE TITLE
小计多了一行

### ISSUE THREAD

**Issue by xfeivip** [jeecgboot/JimuReport#1242]
##### 版本号：
1.5.2

##### 问题描述：
小计多了一行
两个分组小计，第二个小计多出来了一行

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/6063417/187577258-1c67c7b2-ab6d-4788-93a6-45c132ed603c.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
导出报表配置及数据，我们复现一下

**Comment by xfeivip** [comment]
> 
“进入设计页面，右键菜单：导出报表配置”，右键菜单没有导出报表配置
### 数据
`[
    {
        "searchStartDate": "2022-09-01",
        "total": 70,
        "customerAddressName": "武汉钢铁有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "#合计",
        "carNum": 1,
        "trainTypeName": "路运",
        "compName": "万年",
        "customerName": "武汉钢铁有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 70,
        "customerAddressName": "武汉钢铁有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "低灰烧结精煤",
        "carNum": 1,
        "trainTypeName": "路运",
        "compName": "万年",
        "customerName": "武汉钢铁有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 103.47999999999999,
        "customerAddressName": "山东兖矿国际焦化",
        "searchEndDate": "2022-09-01",
        "coalName": "#合计",
        "carNum": 3,
        "trainTypeName": "汽运",
        "compName": "九龙",
        "customerName": "山东兖矿国际焦化"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 103.47999999999999,
        "customerAddressName": "山东兖矿国际焦化",
        "searchEndDate": "2022-09-01",
        "coalName": "肥精煤",
        "carNum": 3,
        "trainTypeName": "汽运",
        "compName": "九龙",
        "customerName": "山东兖矿国际焦化"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 130.93,
        "customerAddressName": "武安市宝烨煤焦化工业有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "#合计",
        "carNum": 4,
        "trainTypeName": "汽运",
        "compName": "九龙",
        "customerName": "武安市宝烨煤焦化工业有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 130.93,
        "customerAddressName": "武安市宝烨煤焦化工业有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "肥精煤",
        "carNum": 4,
        "trainTypeName": "汽运",
        "compName": "九龙",
        "customerName": "武安市宝烨煤焦化工业有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 66.85,
        "customerAddressName": "河北华增达国际物流有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "#合计",
        "carNum": 2,
        "trainTypeName": "汽运",
        "compName": "九龙",
        "customerName": "河北华增达国际物流有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 66.85,
        "customerAddressName": "河北华增达国际物流有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "肥精煤",
        "carNum": 2,
        "trainTypeName": "汽运",
        "compName": "九龙",
        "customerName": "河北华增达国际物流有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 351.68,
        "customerAddressName": "冀中能源股份有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "#合计",
        "carNum": 11,
        "trainTypeName": "汽运",
        "compName": "大社矿",
        "customerName": "冀中能源股份有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 351.68,
        "customerAddressName": "冀中能源股份有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "原煤",
        "carNum": 11,
        "trainTypeName": "汽运",
        "compName": "大社矿",
        "customerName": "冀中能源股份有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 307.1,
        "customerAddressName": "河北旭阳能源有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "#合计",
        "carNum": 9,
        "trainTypeName": "汽运",
        "compName": "孙庄",
        "customerName": "旭阳营销有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 307.1,
        "customerAddressName": "河北旭阳能源有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "肥精煤",
        "carNum": 9,
        "trainTypeName": "汽运",
        "compName": "孙庄",
        "customerName": "旭阳营销有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 513.38,
        "customerAddressName": "河北峰煤焦化有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "#合计",
        "carNum": 18,
        "trainTypeName": "汽运",
        "compName": "孙庄",
        "customerName": "河北峰煤焦化有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 513.38,
        "customerAddressName": "河北峰煤焦化有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "肥精煤",
        "carNum": 18,
        "trainTypeName": "汽运",
        "compName": "孙庄",
        "customerName": "河北峰煤焦化有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 207.48000000000002,
        "customerAddressName": "河北旭阳能源有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "#合计",
        "carNum": 6,
        "trainTypeName": "汽运",
        "compName": "邯郸洗选厂",
        "customerName": "旭阳营销有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 207.48000000000002,
        "customerAddressName": "河北旭阳能源有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "焦精煤",
        "carNum": 6,
        "trainTypeName": "汽运",
        "compName": "邯郸洗选厂",
        "customerName": "旭阳营销有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 884.78,
        "customerAddressName": "河北峰煤焦化有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "#合计",
        "carNum": 28,
        "trainTypeName": "汽运",
        "compName": "邯郸洗选厂",
        "customerName": "河北峰煤焦化有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 884.78,
        "customerAddressName": "河北峰煤焦化有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "焦精煤",
        "carNum": 28,
        "trainTypeName": "汽运",
        "compName": "邯郸洗选厂",
        "customerName": "河北峰煤焦化有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 410.82,
        "customerAddressName": "邯郸市沐辰物流有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "#合计",
        "carNum": 13,
        "trainTypeName": "汽运",
        "compName": "邯郸洗选厂",
        "customerName": "邯郸市沐辰物流有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 410.82,
        "customerAddressName": "邯郸市沐辰物流有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "尾煤",
        "carNum": 13,
        "trainTypeName": "汽运",
        "compName": "邯郸洗选厂",
        "customerName": "邯郸市沐辰物流有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 134.3,
        "customerAddressName": "河北旭阳能源有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "#合计",
        "carNum": 4,
        "trainTypeName": "汽运",
        "compName": "马头洗选厂",
        "customerName": "旭阳营销有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 134.3,
        "customerAddressName": "河北旭阳能源有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "肥精煤",
        "carNum": 4,
        "trainTypeName": "汽运",
        "compName": "马头洗选厂",
        "customerName": "旭阳营销有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 134.04,
        "customerAddressName": "河北华增达国际物流有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "#合计",
        "carNum": 4,
        "trainTypeName": "汽运",
        "compName": "马头洗选厂",
        "customerName": "河北华增达国际物流有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 134.04,
        "customerAddressName": "河北华增达国际物流有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "焦精煤",
        "carNum": 4,
        "trainTypeName": "汽运",
        "compName": "马头洗选厂",
        "customerName": "河北华增达国际物流有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 172.18,
        "customerAddressName": "河北新兴能源科技股份有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "#合计",
        "carNum": 5,
        "trainTypeName": "汽运",
        "compName": "马头洗选厂",
        "customerName": "河北新兴能源科技股份有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 172.18,
        "customerAddressName": "河北新兴能源科技股份有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "肥精煤",
        "carNum": 5,
        "trainTypeName": "汽运",
        "compName": "马头洗选厂",
        "customerName": "河北新兴能源科技股份有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 542.76,
        "customerAddressName": "河南利源燃气有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "#合计",
        "carNum": 16,
        "trainTypeName": "汽运",
        "compName": "马头洗选厂",
        "customerName": "河南利源燃气有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 542.76,
        "customerAddressName": "河南利源燃气有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "肥精煤",
        "carNum": 16,
        "trainTypeName": "汽运",
        "compName": "马头洗选厂",
        "customerName": "河南利源燃气有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 98.82,
        "customerAddressName": "长治市上党区国义贸易有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "#合计",
        "carNum": 3,
        "trainTypeName": "汽运",
        "compName": "马头洗选厂",
        "customerName": "长治市上党区国义贸易有限公司"
    },
    {
        "searchStartDate": "2022-09-01",
        "total": 98.82,
        "customerAddressName": "长治市上党区国义贸易有限公司",
        "searchEndDate": "2022-09-01",
        "coalName": "焦精煤",
        "carNum": 3,
        "trainTypeName": "汽运",
        "compName": "马头洗选厂",
        "customerName": "长治市上党区国义贸易有限公司"
    }
]`
配置

**Comment by xfeivip** [comment]
[report-export-mysql (1).sql.zip](https://github.com/jeecgboot/JimuReport/files/9581825/report-export-mysql.1.sql.zip)

[data.json.zip](https://github.com/jeecgboot/JimuReport/files/9581857/data.json.zip)

**导出了报表配置和数据，请帮忙解决一下，万分感激**

> 导出报表配置及数据，我们复现一下

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
已修复，等新版发布
