### ISSUE TITLE
网关转发到积木报表部分接口报错

### ISSUE THREAD

**Issue by cocoamu** [jeecgboot/JimuReport#1243]
目前积木报表的端口是8080，网关的端口是9195 ，外面通过网关转发来访问报表8080
我在访问地址后面加了一个token，其他页面都正常，就预览访问会报500错误，网关的报错信息是
<img width="1774" alt="image" src="https://user-images.githubusercontent.com/11717549/187637762-27edaaf5-0987-4588-9e9f-363986341f2d.png">

猜测是因为这个接口的特殊传参导致url里面有特殊符号，问下这个该怎么处理，能否调整这个接口传参方式

**Comment by lvdandan16** [comment]
哪个版本？

**Comment by cocoamu** [comment]
> 哪个版本？

我现在是1.5.0-beta 但我试了最新版也是一样

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/194703386-c2347b9e-50f9-4146-b2a5-91173cfd70ea.png)
这个地方不对吧
