### ISSUE TITLE
Excel导出样式丢失改进

### ISSUE THREAD

**Issue by xinxingzhao** [jeecgboot/JimuReport#1244]
##### 问题描述：
查了一下文档，导出的Excel表格只能是单一的样式，实际应用过程中，需要保持相同样式的Excel表格导出，虽然PDF可以保持相同样式导出，但是如果需要导出后进行修正再使用的话，就需要保持原样式导出。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/13712791/187658364-f5dee5d9-3721-45c3-963e-0b707b5203bb.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
归集到：#138
