### ISSUE TITLE
交叉横向求和

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/JimuReport#1245]
##### 版本号：
 v1.5.2

##### 问题描述：
想最右边合计每个月的，这个怎么配置

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/90361617/187662607-09b150b2-96c8-49eb-9153-e9323d564831.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持
