### ISSUE TITLE
导出exel报表没有把样式一起导出

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/JimuReport#1248]
##### 版本号：
v1.5.2

##### 问题描述：
导出的时候标题颜色都没导出，已经设置export-excel-pattern: primary

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/90361617/187863845-e21e97f9-13be-41b2-8d9c-c995b6721e42.png)
![image](https://user-images.githubusercontent.com/90361617/187863962-8278a405-e0d2-4772-ab21-279b3c9e391b.png)
![image](https://user-images.githubusercontent.com/90361617/187864041-2fcec9df-a743-4347-804f-052011f0f2b1.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
1.5.0以后版本去掉了导出样式
