### ISSUE TITLE
参数用sql查询做字典，预览时数据不全

### ISSUE THREAD

**Issue by yujiangfan** [jeecgboot/JimuReport#1249]
##### 版本号：
1.4.2

##### 问题描述：
参数字典sql：select typeid as value,description as text from bas_bib_material where typeid <> '##' order by typeid
这个语句很简单，在数据库工具中查数据没问题，有38条数据
设置好后保存正常。但预览里下拉列表里只有10条数据，且排序没生效。
不止这一个，好几个都字典都有这个情况。

##### 错误日志&截图：
![QQ图片20220901185506](https://user-images.githubusercontent.com/34936549/187899116-189eac78-e3ee-43bd-9017-68c6db032727.jpg)
![D1)D4PVO`)KY(($E732DVE0](https://user-images.githubusercontent.com/34936549/187899156-cea80e03-d8d8-4365-a805-16d0b125f9c0.jpg)
![9P9 `QZ(XA $W7SM9ER7@LP](https://user-images.githubusercontent.com/34936549/187899226-6c8df51e-af41-4fac-97cd-3cb671d69f5d.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
字典默认只显示10条，数量大一次性加载卡，搜索会变化

**Comment by yujiangfan** [comment]
默认10条，有别的办法吗？总不能数据显示不完整吧
