### ISSUE TITLE
返回格式.

### ISSUE THREAD

**Issue by tzwhyqq** [jeecgboot/JimuReport#1250]
##### 版本号：
1.5.2

##### 问题描述：
api数据源返回格式.现在如果是主从表样式的报表一定要 写2个数据源. 这个好麻烦. 就不能接收对象吗. 这样有些api可以复用,要不然全部都要写一遍,太麻烦.   希望能接受这样 {data:[{name:"aaaaa",sex:"bbbb"},{name:"aaaaa",sex:"bbbb"}],item:{aa:!,bb:2}}  或者 按现在格式[{data:[{name:"aaaaa",sex:"bbbb"},{name:"aaaaa",sex:"bbbb"}],item:{aa:!,bb:2}}]

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你可以通过java数据源方式来实现

**Comment by zhangdaiscott** [comment]
咱无计划
