### ISSUE TITLE
electron集成了积木报表，横向数据太多，不显示横向滚动条

### ISSUE THREAD

**Issue by wang727179528** [jeecgboot/JimuReport#1253]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/48749289/188140168-a34bac7b-c450-4795-b45e-bcd564e01b62.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by pandawjw** [comment]
你好 请问 怎么解决的
