### ISSUE TITLE
时间控件是否可以支持只选择年或者月份

### ISSUE THREAD

**Issue by PengLiang-git** [jeecgboot/JimuReport#1255]
请问下，时间控件是否可以支持只选择年或者月份
我们有些报表是月度或者季度报表，所以时间查询想只选择到月份为止，而不让他继续选择精确到天，想问下这样怎么处理，需要加增强js代码吗？

**Comment by lvdandan16** [comment]
参考文档：
http://report.jeecg.com/2384073
