### ISSUE TITLE
图表配置无法正常保存的bug

### ISSUE THREAD

**Issue by Jalone5186** [jeecgboot/JimuReport#1256]
##### 版本号：
1.5.2

##### 问题描述：
选择SQL数据集的方式配置好图表的相关配置后，如果不选择一次定时刷新选项则无法保存成功。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/50126675/188407881-81b51d6f-5bd3-41a2-a39a-6a5ab2a1bc25.png)
![MYVWL9BQYYW4${JE9R@J}Y](https://user-images.githubusercontent.com/50126675/188407923-8b180ead-82da-4000-93e8-a9be83c992fd.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/194702351-f282d20e-a047-4f5f-a1b7-d701373048df.png)
需要点击运行后，再保存

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
需要点击一下运行按钮，数据才会加载，否则数据会加载不出来
