### ISSUE TITLE
配置查询超时时间不生效

### ISSUE THREAD

**Issue by Acechengui** [jeecgboot/JimuReport#1257]
##### 版本号：
1.5.2

##### 问题描述：
![image](https://user-images.githubusercontent.com/63096199/188411883-b585d2f4-172c-41cd-8524-d719e3a4fd8f.png)
![image](https://user-images.githubusercontent.com/63096199/188412121-b66bef2b-cb22-4629-b2f1-2205467cafb1.png)
按照文档均设置了超时时间,但是依然发现查询几分钟就会提示查询超时

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/63096199/188413011-d7c94b1e-bdfd-49f5-971d-91a93a0b397a.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
你这是SQL查询超时了，并不是接口访问超时吧

**Comment by Acechengui** [comment]
不可以配置吗？？？？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月8日(星期六) 晚上6:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/JimuReport] 配置查询超时时间不生效 (Issue #1257)





 
你这是SQL查询超时了，并不是接口访问超时吧

**Comment by Acechengui** [comment]
很多时候sql数据集也需要查询要几分钟时间，可不可以增加这一项配置，我们可以自定义超时时间

**Comment by lvdandan16** [comment]
目前不支持，归集到：#138
