### ISSUE TITLE
循环块内多行数据的问题

### ISSUE THREAD

**Issue by onepiecewyz** [jeecgboot/JimuReport#1258]
[#####](url) 版本号：
1.5.2

##### 问题描述：
在使用批量打印功能中，使用了循环块进行实现，循环打印的对象是一张表，表里有2类数据，一种是1行数据，一种是N条数据。目前是1行数据的在循环块内可以正常显示，N行数据的在循环块内无法显示。有试过主子报表来传参，调了很久都不行，请问应该怎么配置？或者是否目前版本不支持。

##### 错误日志&截图：
![QQ图片20220905180537](https://user-images.githubusercontent.com/21165646/188424178-d9d4e924-11a1-43e2-bdd1-ea41407b4cea.png)

**Comment by mayiB** [comment]
同问！遇到同样的问题，请求赐教

**Comment by lvdandan16** [comment]
循环块不支持主子表方式

**Comment by No996ICU** [comment]
> r

也遇到了同样的问题，类似的功能可以怎么来实现

**Comment by sanye8899** [comment]
同问

**Comment by sanye8899** [comment]
因长时间未回复，暂时关闭此问题
