### ISSUE TITLE
1.5.2图表的API数据集绑定时提示不支持get请求

### ISSUE THREAD

**Issue by rongyue11** [jeecgboot/JimuReport#1259]
##### 问题描述：图表的API数据集绑定时提示不支持get请求

截图:

![1662426006309](https://user-images.githubusercontent.com/112912434/188525628-c51136c1-e11f-44b5-8c98-e59b075303a5.jpg)

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/194696823-3298a17d-68da-4183-bb1f-a0d866bfad50.png)
未复现此问题，可在官网做个示例我们看一下
