### ISSUE TITLE
报表上的0导出excel后显示成0E-8

### ISSUE THREAD

**Issue by zhanghahahahahaha** [jeecgboot/JimuReport#1260]
##### 版本号：
1.5.2

##### 问题描述：
列在报表上的显示为0，但是导出excel后，就显示成0E-8，这个很影响使用
单元格设置的是数值格式

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/108739923/188534769-99d798b1-cfee-46a5-abd7-563e235ad9cc.png)

![image](https://user-images.githubusercontent.com/108739923/188534682-2524af37-c856-41ef-9a71-6131a1ea8f90.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
未复现此问题，怎么设计的，可导出报表配置，我们看一下

**Comment by lvdandan16** [comment]
Sqlserver数据库下是有这个问题，已修复，下个版本升级
不知道你这个是什么数据库，升级后可以先试一下
