### ISSUE TITLE
导出

### ISSUE THREAD

**Issue by hx1206** [jeecgboot/JimuReport#1261]
##### 问题描述：
1、导出项不支持控制（我想去掉导出execl项，不知道怎么去掉）；
2、不支持导出word；
3、导出execl样式被改变；

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by hx1206** [comment]
可以支持word导出吗？
怎么禁用导出excel？

**Comment by hx1206** [comment]
你们这个多久才能回复？

**Comment by HUGEWAVES** [comment]
> 可以支持word导出吗？ 怎么禁用导出excel？

同问。。。能不能导出word呢？

**Comment by lvdandan16** [comment]
1.不支持配置单独导出某一项，只可配置是否导出
2.不支持word导出
3.1.5.0以后，不支持导出execl的背景颜色
