### ISSUE TITLE
调用导出pdf接口问题？

### ISSUE THREAD

**Issue by JIangshaohao** [jeecgboot/JimuReport#1263]
##### 版本号：
1.5.2

##### 问题描述：

举个例子：
现在有一个界面，内容是一个表格数据，页面上面有个按钮，点击按钮，我要请求积木报表的接口，查看我选中数据的报表（例如柱形图，但是报表界面也是我自定义的（如图）），该怎么做。简单点来说，就是请求积木报表的接口，查看当前数据报表的样子。（用的是若依单体系统集成了JimuReport，不是jeecg）

同时，表格数据我还可以进行多选来查看报表，那么就需要循环（所以查看就是在一个界面中有两个柱形图（如图上：我选两条数据那么就循环成两个）），所以传参的话就是数组了

##### 截图：
![asf907145438](https://user-images.githubusercontent.com/93586311/188809620-deb247a9-0209-4bb7-b4d2-c53a8a536236.jpg)

![11120907145300](https://user-images.githubusercontent.com/93586311/188809750-152733ef-45fe-4818-8471-0d2383097a30.jpg)

**Comment by JIangshaohao** [comment]
同时，表格数据我还可以进行多选来查看报表，那么就需要循环（所以查看就是在一个界面中有两个柱形图），传参的话就是数组了

**Comment by lvdandan16** [comment]
不支持
