### ISSUE TITLE
横向分组合计问题

### ISSUE THREAD

**Issue by donganddong** [jeecgboot/JimuReport#1265]
##### 问题描述：横向分组合计无法计算
横向分组后无法显示或计算行尾合计，交叉表中经常用到的横竖的合计计算，只有纵向可以实现，横向无法实现。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持 横向合计

**Comment by donganddong** [comment]
邮件已收到，感谢你来信！
