### ISSUE TITLE
版本号：1.5.2 - 循环块设置 -  功能看不到了

### ISSUE THREAD

**Issue by fuermoqian** [jeecgboot/JimuReport#1266]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/34876749/188882552-4f0997a6-1829-4bd7-9a33-a435f63c8cd8.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by liyang1987jay** [comment]
![image](https://user-images.githubusercontent.com/4651483/190916194-5073b106-275e-4595-9a14-4d6b06f0e118.png)
你要选中行就能看到了

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/194697278-dd35e6bc-9629-4f3d-b07c-1cff8b9e0c73.png)
滚动条下拉
