### ISSUE TITLE
纵向分组小计一行如何填充颜色

### ISSUE THREAD

**Issue by zhangxinyuan1** [jeecgboot/JimuReport#1267]
##### 版本号：
1.5.2

##### 问题描述：
纵向分组小计 一行如何设置背景颜色

##### 错误日志&截图：
![图片](https://user-images.githubusercontent.com/39943076/189011977-542994d8-b880-43a3-9bbd-374725e49491.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
