### ISSUE TITLE
纵向合计无法对横向统计进行求和

### ISSUE THREAD

**Issue by zhangxinyuan1** [jeecgboot/JimuReport#1268]
##### 版本号：
1.5.2

##### 问题描述：
两个问题：
1、纵向分组合计 如何设置背景颜色
2、纵向合计 遇到横向统计 如何再进行纵向统计呢？ 右侧没有这一项

##### 错误日志&截图：
![图片](https://user-images.githubusercontent.com/39943076/189015385-d7011eb0-2525-452b-ae46-65a21c6427c1.png)
![图片](https://user-images.githubusercontent.com/39943076/189015655-240b01b1-a1bc-46cd-ae7c-72da827a3257.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
1.不支持
2.不支持
