### ISSUE TITLE
横向分组了后，在下面添加了两列，但是后面的没有展示出来

### ISSUE THREAD

**Issue by Dierzing** [jeecgboot/JimuReport#1269]
##### 错误日志&截图：
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/37360631/189017130-36a6dd11-c527-4c0e-a610-83a2c4e932ac.png">
<img width="840" alt="image" src="https://user-images.githubusercontent.com/37360631/189017169-b1bd0b89-75f1-4fbe-9f5a-0df41ad8a153.png">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
未复现此问题，可在官网复现问题，将报表id贴上来，我们看一下

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
