### ISSUE TITLE
有关积木大屏预览时鼠标手势问题

### ISSUE THREAD

**Issue by MartinZhums** [jeecgboot/JimuReport#1271]
##### 版本号：
1.5.2

##### 问题描述：
大屏预览时有关鼠标手势问题，超链接或可操作图表使用Hand手势，其他地方如边框，非超链接字是否可以设置成箭头，没有地方找到设置，图表中的组件，包括边框，鼠标移动上去还是显示Hand手势，是否可以显示成箭头?

##### 重现步骤：
鼠标在边框内和外滑动

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by MartinZhums** [comment]
重新发布

**Comment by lvdandan16** [comment]
不支持设置
