### ISSUE TITLE
积木报表文档中常见问题gitee链接访问404

### ISSUE THREAD

**Issue by whwtree** [jeecgboot/JimuReport#1273]
您好，积木报表文档中，常见问题gitee链接访问404，而且github上也没有对应issue，请问在哪可以查看链接内容呢？
例如：
问题： 日期默认查询，无法设置默认值为上月
链接：https://gitee.com/jeecg/JimuReport/issues/I4DQ3P
问题：打印多出一页空白纸张
参考：https://gitee.com/jeecg/JimuReport/issues/I4W4WB#note_9063628_link

**Comment by lvdandan16** [comment]
已重新整理文档，直接看文档即可，在文档中既有解决方案
http://report.jeecg.com/2483021
