### ISSUE TITLE
在积木报表首页，选择“视图”模式，报表的缩略图都是excel图标，而不是能看到报表内容的缩略图

### ISSUE THREAD

**Issue by zhanghahahahahaha** [jeecgboot/JimuReport#1275]
##### 问题描述：
在积木报表首页，选择“视图”模式，报表的缩略图都是excel图标，而不是能看到报表内容的缩略图，在QQ群有些人发的图片是可以显示每个报表缩略图的

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/108739923/189322421-1d8d5f91-fe7c-4371-ad45-8dc6779bc527.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持直接展示报表内容，可上传报表内容的封面图片

**Comment by zhanghahahahahaha** [comment]
> 

在哪里上传？

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/194699941-05661666-57d4-4d38-b057-3fd982a0d7a4.png)
先收藏模板，再上传封面
