### ISSUE TITLE
docker启动问题

### ISSUE THREAD

**Issue by LynnLLY** [jeecgboot/JimuReport#1276]
##### 版本号：
1.5.0

##### 问题描述：
我尝试在docker中启动jimu，但是遇到问题

##### 错误日志&截图：
<img width="1680" alt="CleanShot 2022-09-11 at 10 41 45@2x" src="https://user-images.githubusercontent.com/37694927/189509994-02b63ed3-ad68-41ee-9ab2-29f117017e38.png">

##### 重现步骤：
我根据网上解决办法尝试禁用jvm空闲调优参数-XX:IdleTuningMinIdleWaitTime=0，但是结果相同，没有解决问题

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by LynnLLY** [comment]
补充一下，我使用的spring-boot集成，自己打的docker镜像，没有使用官方的docker教程

**Comment by lvdandan16** [comment]
推荐使用官方教程
