### ISSUE TITLE
积木报表下载免安装版本，新建报表后页面打不开

### ISSUE THREAD

**Issue by Lee-2019** [jeecgboot/JimuReport#1277]
##### 版本号：
jimureport-quickstart-1.5-20220418

##### 问题描述：
积木报表下载免安装版本，新建报表后页面打不开，有一个圆圈一直在转。

##### 错误日志&截图：

<img width="958" alt="jimureporterror" src="https://user-images.githubusercontent.com/52067106/189514066-c907c3a6-2e92-4baa-866b-197f6a6253b9.png">

##### 重现步骤：
-在http://www.jimureport.com/download下载免安装版本
-解压缩jimureport-quickstart-1.5-20220418
-安装jdk1.8.0
-用MySQL Workbench打开jimureport.mysql5.7.create.sql
-修改 application.yml中的datasource url中的数据库名称以及password
-双击 start.bat 启动
-访问报表http://localhost:8085/jmreport/list
-点击新建报表

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
看具体报什么错

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
