### ISSUE TITLE
同一个报表中，使用两个api接口，分别计算对应列合计SUM有误

### ISSUE THREAD

**Issue by 793292556** [jeecgboot/JimuReport#1278]
##### 版本号：
1.5.2

##### 问题描述：
同一个报表中，使用两个api接口，分别计算对应列合计时，第二个SUM计算结果有误，把第一个SUM的数据累加上了

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/66394184/189794560-78f45d62-88c9-4ea6-91b4-f6b2eaa94471.png)
![image](https://user-images.githubusercontent.com/66394184/189794745-80114501-0351-474f-b711-e73c3da82f7b.png)

##### 重现步骤：
同一个报表中，使用两个api接口，分别计算对应列合计时，第二个SUM计算结果有误，把第一个SUM的数据累加上了

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
SUM计算列是计算整一列的数据，并不是按照数据源来计算的
