### ISSUE TITLE
参数in条件查询错误

### ISSUE THREAD

**Issue by dmarvin** [jeecgboot/JimuReport#1283]
##### 版本号：

1.5.2
##### 问题描述：
参数in条件时，字符串没加单引号

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/15043402/190381931-bb462d22-33c7-42e5-8d9d-8dc8399bb357.png)
![image](https://user-images.githubusercontent.com/15043402/190382043-da2c8902-2059-4d8c-a4e6-4052b27f9f1b.png)
![image](https://user-images.githubusercontent.com/15043402/190382107-26aa5067-2520-4b5d-af5a-ddf0c82d2586.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参数为占位符，传入什么就是什么
如果想用in 可以使用字段查询
