### ISSUE TITLE
微服务下静态资源访问不到

### ISSUE THREAD

**Issue by DaiisonGitHub** [jeecgboot/JimuReport#1284]
##### 问题描述：微服务网关访问静态资源无法访问，已经配置了
jeecg:  
  jmreport:
    customPrePath: /demo

##### 错误日志&截图：
![Uploading image.png…]()
![4F51B0EC46A0069F0C2274435B57E8D7](https://user-images.githubusercontent.com/34697450/190548657-10f966ef-f94a-4a29-9982-3075c83100ac.jpg)

**Comment by YIminta** [comment]
很明显你的url里面没有 /wns-sdk，应该是 :9000/wms-sdk/jmreport/desreport_/...省略了自己领悟

**Comment by DaiisonGitHub** [comment]
就是没有加/wms-sdk，看了https://github.com/jeecgboot/JimuReport/issues/1284#issuecomment-1248988277文档说，需要在yml里面添加，也添加了，还是不生效，静态文件还是加载不出来

**Comment by YIminta** [comment]
有没有配置过滤器？

**Comment by DaiisonGitHub** [comment]
.excludePathPatterns("/jmreport/**")//积木报表
<img width="1575" alt="image" src="https://user-images.githubusercontent.com/34697450/190590578-3b86e8a9-0b14-486e-8647-41fc7386563c.png">

**Comment by YIminta** [comment]
你这是网关，MCV请求过滤器有配置吗

**Comment by DaiisonGitHub** [comment]
> 你这是网关，MCV请求过滤器有配置吗

#JimuReport[minidao配置]
  #静态资源加载配置
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/public/


也配置了

**Comment by YIminta** [comment]
你最好是重写一个MvcConfig的那个接口，配置了mvc过滤器后，静态资源都没有放行，我现在也遇到了这个问题，默认全都返回true就是正常的

**Comment by DaiisonGitHub** [comment]
好的，我试试，感谢您的回复！

**Comment by YIminta** [comment]
感觉你应该配置这个  customPrePath: jimureport，然后还有问题应该是context-path没配置，参考https://blog.csdn.net/gududedabai/article/details/108095684?spm=1001.2101.3001.6661.1&utm_medium=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-108095684-blog-120460654.pc_relevant_default&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-108095684-blog-120460654.pc_relevant_default&utm_relevant_index=1
同时微服务下配置了context-path，还要改网关的参数不然直接访问就是404

**Comment by lvdandan16** [comment]
参考文档：http://report.jeecg.com/2506684
