### ISSUE TITLE
小数点问题

### ISSUE THREAD

**Issue by kongjingnan** [jeecgboot/JimuReport#1285]
##### 版本号：
1.5.0-beta

##### 问题描述：

mysql数据库存储的是整数，在积木界面上展示就会存在,00的问题，且在积木报表编辑SQL是语句也无效。
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by kongjingnan** [comment]
select  cast( 1  as decimal(9,2))
SELECT  0+cast(1 as char)  AS price 
这两条语句在navicate查出出来都是五小数点的处理方式，单是在积木的sql编辑器里，存在小数点，请问如何解决。

**Comment by lvdandan16** [comment]
可配置小数位数，设置为0即可
