### ISSUE TITLE
导出Excel与报表页查询条件不一致

### ISSUE THREAD

**Issue by ascevien** [jeecgboot/JimuReport#1286]
##### 问题描述：
导出Excel与查询条件不一致的问题。设置了默认值的条件，清除该条件值后查询，结果正常。但导出Excel的时候，仍传了该查询条件值。

##### 重现步骤：
1.设置一个叫“年份”查询条件，为时间类型，并设置默认值。
2.“年份”查询条件，默认值显示正常，清除该查询条件，点击“查询”结果正常（注意此时的结果）。
3.点击“导出”，选择Excel，查看导出的Excel结果，与报表查询页结果不一致。查看导出Excel执行的SQL，传入了“年份”查询条件值。

![image](https://user-images.githubusercontent.com/113666971/190579528-037d97d7-a557-4f99-997e-4f93840f99b7.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
