### ISSUE TITLE
导出excel样式改变了

### ISSUE THREAD

**Issue by dragonzoebai** [jeecgboot/JimuReport#1287]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/5774016/190594802-f20bab26-cd0b-4683-ab05-e64143f540be.png)

##### 重现步骤：
点击官方模板案例

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
1.5.0版本以后，不再导出excel样式
