### ISSUE TITLE
引入版本后为什么没引入成功

### ISSUE THREAD

**Issue by yuanzhaoh** [jeecgboot/JimuReport#1288]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/31821711/190597303-925900fb-dd74-49d8-9224-69fcd2f70b2d.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档：
http://report.jeecg.com/2302147
http://report.jeecg.com/2302148
