### ISSUE TITLE
柱状图能自定义填充图形么？

### ISSUE THREAD

**Issue by chengxucai** [jeecgboot/JimuReport#1289]
##### 版本号：
1.5.2

##### 问题描述：
![image](https://user-images.githubusercontent.com/36264031/190613655-3edd45c5-4151-4d40-8f4b-37a0011d52a8.png)
对于不同的柱状图，想填充不同的图形，例如直接访问填充斜线，邮件营销填充竖线，联盟广告填充横线

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
