### ISSUE TITLE
JimuReport积木报表设计打印模板是怎样获取到页码和总页数，需要打印出来

### ISSUE THREAD

**Issue by gaoyao8866** [jeecgboot/JimuReport#1290]
##### 错误日志&截图：
![页码](https://user-images.githubusercontent.com/31432797/190847123-25ccccc2-4791-4215-817c-aeb1dddfb5d4.jpg)

![页码](https://user-images.githubusercontent.com/31432797/190847163-74d0af7f-cbae-4cfa-ac6f-c7e9ea178ed2.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by gaoyao8866** [comment]
折中办法

**Comment by gaoyao8866** [comment]
已解决

**Comment by liu421** [comment]
请问这个您后面是怎么解决的？

**Comment by caitxj** [comment]
同上问，这个我看积木没有想过的api进行获取当前页码及总页码的操作
