### ISSUE TITLE
数据报表-使用dbsum对字段进行统计，当统计的字段过多时预览出错

### ISSUE THREAD

**Issue by Jsliufangyu** [jeecgboot/JimuReport#1293]
##### 版本号：

<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.5.2</version>
</dependency>

##### 问题描述：
使用dbsum对字段进行统计，当统计的字段过多时预览出错
[提供的文件.zip](https://github.com/jeecgboot/JimuReport/files/9595750/default.zip)

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/35021972/190938396-9baa9b19-20fb-4f95-9832-85e0e3b02f69.png)

![image](https://user-images.githubusercontent.com/35021972/190938413-5d6550ba-b441-4922-9b92-da49dbc26d1f.png)

![image](https://user-images.githubusercontent.com/35021972/190938447-aa247cdc-e9e8-4a9e-9630-1af5614d0e02.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by C20190420** [comment]
遇到了同样的问题，求解决办法

**Comment by hlniceguy** [comment]
+1

**Comment by lvdandan16** [comment]
收录 ws

**Comment by tygithub1** [comment]
已修复
