### ISSUE TITLE
能否支持view接口的post传参

### ISSUE THREAD

**Issue by Dili-gence** [jeecgboot/JimuReport#1294]
##### 版本号：
1.4.0-teta

##### 问题描述：
view请求是不想把参数拼接后面太长了

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/57351071/191161729-60e3416a-0c28-4270-a8e3-7b5a6d02f79f.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档：http://report.jeecg.com/2332212

**Comment by Dili-gence** [comment]
不是这种api请求集的那个post，是预览报表的那个请求，封装成post请求，这个内部调用的api请求集怎么回去展示报表请求post传递的参数呢

**Comment by Dili-gence** [comment]
也就是预览的地址想要是post请求方式，而不是在预览地址后面拼接参数

**Comment by Dili-gence** [comment]
预览地址的参数，可能不是报表自带的那种设置查询参数，想要的是那种，自己前端封装的参数

**Comment by lvdandan16** [comment]
不支持
