### ISSUE TITLE
Excel导出 报表包含图表不能导出图表

### ISSUE THREAD

**Issue by hezhaoliang** [jeecgboot/JimuReport#1295]
版本号：1.5.0

 问题描述：
Excel导出 报表包含图表不能导出图表

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/194701887-9a1e8944-cd75-488b-a382-5be5fbda9345.png)
看有没有报错，或者升级1.5.2试试，我这里是可以的
