### ISSUE TITLE
报表表头标题无法固定

### ISSUE THREAD

**Issue by qingzhaozhang** [jeecgboot/JimuReport#1298]
##### 版本号：
1.5.2

##### 问题描述：
报表表头无法固定，当鼠标滚动报表到页面底部时，看不到报表标题

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/19871734/191285479-e0acbd17-96fb-4a12-8c5d-3d6c49e3cbd9.png)

##### 重现步骤：
1、打开官方模板案例区域销售表，可以看到报表数据、标题栏

![image](https://user-images.githubusercontent.com/19871734/191285478-63278382-a9f9-4d37-bb43-929315c20b2e.png)

2、鼠标滚动到底部，标题栏没有固定，只能看到数据，看不清每列什么含义

![image](https://user-images.githubusercontent.com/19871734/191285477-5e952c09-dd96-487a-bc98-49a261e81ee4.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持固定表头
