### ISSUE TITLE
系统设置无边框,在预览的时候没有边框。但在导出的excel的时候确出现边框的，主要表现在单元框有值的时候。

### ISSUE THREAD

**Issue by guren1131** [jeecgboot/JimuReport#1300]
##### 版本号：
1.5.2

##### 问题描述：
系统设置无边框,在预览的时候没有边框。但在导出的excel的时候确出现边框的，主要表现在单元框有值的时候。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/32631049/191449037-db3e716a-b07e-45a1-9da8-3d77d06c310f.png)

![image](https://user-images.githubusercontent.com/32631049/191449815-75307bae-dd43-4d08-8aff-dffccd00a9d9.png)

##### 重现步骤：

在单元框有值的时候。
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
导出excel时有值的单元格，会默认加上边框

**Comment by guren1131** [comment]
建议可以根据系统边框有无设置来体现，不然在一些excel导出如一些单号 标题合并中会出现问题 标题前半段有边框 后半段没有边框，
![image](https://user-images.githubusercontent.com/32631049/196129293-99c56d76-a1a4-4d05-a1ef-fd7a47411b4a.png)
