### ISSUE TITLE
报表加载很慢

### ISSUE THREAD

**Issue by fangjin568** [jeecgboot/JimuReport#1301]
##### 版本号：
1.5.0

##### 问题描述：
通过容器部署或者jar部署，成功后，在页面访问加载在20秒左右才加载完成

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/54836751/191640390-625fdba9-277f-4ca4-9ddb-480566668527.png)

##### 重现步骤：
最开始是用的容器部署，后面感觉可能是服务器内存问题，换了大一点的内存服务器，用容器部署，或者jar部署都很慢

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
有报错信息吗

**Comment by mayiB** [comment]
遇到同样的问题，请问您是否解决了？

**Comment by fangjin568** [comment]
解决了，内网很慢因为一个js加载不出来，需要外网才可以，或者把那个js删掉

**Comment by fangjin568** [comment]
> 遇到同样的问题，请问您是否解决了？
代理成外网地址就可以很快或者把加载不出来的那个js删除掉

**Comment by hyzjz** [comment]
你好，这个js我怎么找不到呢，而且我其他内网的项目打开速度也不慢，不明白这是怎么回事

**Comment by hyzjz** [comment]
我新部署的那个强制刷新报表需要加载30秒了，求大神指导那个js在哪删除
