### ISSUE TITLE
如何将多行相同数据合并成一个标准单元格大小

### ISSUE THREAD

**Issue by lyfswns1106** [jeecgboot/JimuReport#1302]
##### 版本号：
1.5

##### 问题描述：
由于姓名那一列是动态查出来的，所以每一行的数据都是想同的，需要将相同的行合并成原先的一行大小，而不是动态合并成一大格

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/93788773/191673525-cb93748f-8ee9-4dfc-b543-e28aa59a7d79.png)

![image](https://user-images.githubusercontent.com/93788773/191673368-aa6996f3-8079-4222-8043-51d23596a1d7.png)

##### 重现步骤：
只需尝试将查出相同数据列设置成一个正常单元格大小就行

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
什么意思？是说第一行单元格太高了？

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
