### ISSUE TITLE
预览和实际打印不一致

### ISSUE THREAD

**Issue by gaoyao8866** [jeecgboot/JimuReport#1303]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/31432797/191682847-d2a0afb1-bcfd-4ab5-94d7-461d3018b301.png)

![image](https://user-images.githubusercontent.com/31432797/191683469-a0323945-dbc2-48fc-8a4c-d42f496e11b8.png)

打印效果：
![image](https://user-images.githubusercontent.com/31432797/191683688-c5ae8a62-1b56-4cf9-82b6-a0166af90fa9.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
打印暂不支持循环表头
