### ISSUE TITLE
单元格表达式SUM问题

### ISSUE THREAD

**Issue by zh1109334794** [jeecgboot/JimuReport#1304]
##### 错误日志&截图：
![1663833805857](https://user-images.githubusercontent.com/75262253/191692091-ab58798c-5334-466f-8f08-e809fdc3bd07.png)
![1663833913365](https://user-images.githubusercontent.com/75262253/191692391-a4d6af01-2b72-47fb-84b8-39086ae4d498.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持上方统计

**Comment by maokaogo** [comment]
> 不支持上方统计

可以支持吗，感觉这个上方统计功能还是挺实用的

**Comment by zh1109334794** [comment]
求支持
