### ISSUE TITLE
excel导出 单元格样式丢失

### ISSUE THREAD

**Issue by hezhaoliang** [jeecgboot/JimuReport#1306]
##### 错误日志&截图：
![微信图片_20220923101750](https://user-images.githubusercontent.com/17314818/191881367-25ee4517-1fd6-498d-aab9-e28391c7bd64.jpg)

![微信图片_20220923101950](https://user-images.githubusercontent.com/17314818/191881432-24060fde-c597-4834-aa77-2020c4b36017.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
1.5.0以后单元格样式不再导出
