### ISSUE TITLE
在不同运行环境下，图片路径配置时如何从上下文中获取到路径前缀

### ISSUE THREAD

**Issue by TOSHIBA4869** [jeecgboot/JimuReport#1307]
##### 版本号：
1.5.2

##### 问题描述：
在sql语句报表中根据不同的环境配置不同的图片路径前缀

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/28076006/191890498-2542ed3c-6412-4b52-82ee-4568f9b63f45.png)

##### 重现步骤：
不同运行环境下，如何从上下文中获取到图片路径的前缀

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
