### ISSUE TITLE
有默认查询条件数据报表翻页不能用问题

### ISSUE THREAD

**Issue by wassheima** [jeecgboot/JimuReport#1308]
##### 问题描述：
数据报表查询条件设置默认查询条件，如果首次查询没有数据，后续改用其他条件查询出数据后翻页功能不能用

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/114221186/191924427-1516ddcd-a1d5-4712-8954-3bdab50490b8.png)

![image](https://user-images.githubusercontent.com/114221186/191924894-8fb64776-cdbc-46c5-93f5-7cf4af21f3fc.png)

##### 重现步骤：
1、根据默认条件进行预览，没有数据
2、换另一个条件进行查询，有数据，此时翻页功能不能用
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
报表是如何设计的，用的SQL还是api？

**Comment by lvdandan16** [comment]
为复现此问题
因长时间未回复，暂时关闭此问题

**Comment by wassheima** [comment]
报表用的是SQL
