### ISSUE TITLE
1.5.2报表设计，报表参数，查询模式缺失，范围查询

### ISSUE THREAD

**Issue by LancCJ** [jeecgboot/JimuReport#1309]
##### 版本号：
1.5.2

##### 问题描述：
该版本在添加查询条件参数 日期类型 查询模式没有了范围查询的下拉，去哪里l？

##### 错误日志&截图：
<img width="1522" alt="iShot_2022-09-25_07 44 41" src="https://user-images.githubusercontent.com/2968042/192122479-b7f457a6-15bb-47fb-87ed-c24ec1501d2b.png">

##### 重现步骤：

正常操作即可，目前官网版本也是

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/194687448-9793fa7e-5505-46ad-8f72-86a4d1931e13.png)
有啊，没问题啊
