### ISSUE TITLE
报表单元格可以设置按内容扩大吗

### ISSUE THREAD

**Issue by hezhaoliang** [jeecgboot/JimuReport#1310]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
具体是什么需求，如果是内容较多，设置自动换行，可扩大单元格，其他情况不支持

**Comment by hezhaoliang** [comment]
比如像日期、时间这种比较固定长度的内容，想要一行显示完整，列宽能够自动根据内容扩大类似自适应。如果很长肯定不会去设置自适应

**Comment by Everything1sPossible** [comment]
老哥，列宽百分比自适应这块你有解决方案吗?
