### ISSUE TITLE
偶现首次请求报表样式错误，或报数组下标越界

### ISSUE THREAD

**Issue by wwssff** [jeecgboot/JimuReport#1312]
版本号：1.5.0

问题描述：
偶现首次请求报表或刷新报表后
1.样式错乱
2.报错数组下标越界
再次刷新后现实正常，（两种情况不同时出现，都为小概率偶现且刷新后正常显示）

截图&代码：
样式错乱时：
![image](https://user-images.githubusercontent.com/113870593/192426725-06a56a77-a06b-4988-9e19-8dc9a9aa82c3.png)
正常样式：
![image](https://user-images.githubusercontent.com/113870593/192426754-ca877ecf-f57f-44b6-bf9c-3cf304e71161.png)

数组越界后端报错
![image](https://user-images.githubusercontent.com/113870593/192704895-87409e3e-ce10-4093-a557-b6ec11f381cb.png)

**Comment by lvdandan16** [comment]
有横向分组时，需注意数据需完整
http://report.jeecg.com/2119057
