### ISSUE TITLE
多个列进行DBSUM的情况下，出现报错信息

### ISSUE THREAD

**Issue by hlniceguy** [jeecgboot/JimuReport#1314]
##### 版本号：
最新版本

##### 问题描述：
对8列以上的列进行求和时DBSUM，出现提示不存在列的错误

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/46768485/192947006-0c5a00c9-d406-4f7a-bac2-fcb6c6265b96.png)

![image](https://user-images.githubusercontent.com/46768485/192946811-ac12e6b2-1dbe-494c-ae12-f75494139b2b.png)

##### 重现步骤：
报表设计器地址：http://api3.boot.jeecg.com/jmreport/index/735334210288832512

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by lvdandan16** [comment]
已修复，下个版本升级
