### ISSUE TITLE
使用依赖引入积木报表，点击设计后修改内容进行保存报错

### ISSUE THREAD

**Issue by fhyxz001** [jeecgboot/JimuReport#1315]
##### 版本号：
1.5.2

##### 问题描述：
我在我的springBoot项目中引入了
```
<dependency>
            <groupId>org.jeecgframework.jimureport</groupId>
            <artifactId>jimureport-spring-boot-starter</artifactId>
            <version>1.5.2</version>
</dependency>
```
随后在进行试用中发现在保存的时候前端会在调用excelQueryName函数的时候将null转成空字符串传递给后端报错，经排查是dataList这个字段前端传的值为 dataList:"" 导致，如果是dataList:null 则正常。。
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/30167287/192952935-09a8733d-0224-4dad-933f-9e9d7d9ae2ad.png)

##### 重现步骤：
试用依赖引入，然后任意打开一个数据报表，点击设计，然后随便编辑一点东西，点击保存
![image](https://user-images.githubusercontent.com/30167287/192953200-45f7f775-4ba3-4672-a6e7-5ee3a01949ce.png)
就会出现这个问题

#### 临时解决方案：
我在 文件 jimureport-spring-boot-starter-1.5.2.jar 中 的
jimureport-spring-boot-starter-1.5.2\static\jmreport\desreport_\js\biz\design.js 中的excelQueryName方法加入了一个遍历转换，可以解决
![image](https://user-images.githubusercontent.com/30167287/192953606-b6501521-6276-4e35-88cf-21c445635867.png)

**Comment by lvdandan16** [comment]
是与你自己的项目有冲突吧，可以尝试一下我的demo，应该是没问题的
