### ISSUE TITLE
查询栏 下拉多选搜索无效

### ISSUE THREAD

**Issue by snkever** [jeecgboot/JimuReport#1316]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请图文并茂详细描述问题

**Comment by snkever** [comment]
![图片](https://user-images.githubusercontent.com/28818320/194702097-25013987-56d7-4598-9356-075fbe776e87.png)
多选下拉框里的搜索功能不能用

**Comment by lvdandan16** [comment]
SQL数据集还是API

**Comment by snkever** [comment]
用的API 数据字典

**Comment by lvdandan16** [comment]
api数据字典查询使用的value  用value值试一下可以查询吗

**Comment by snkever** [comment]
使用下拉多选text/value都不可以查询，使用下拉单选只能用value查询


| |
snkever
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年10月8日 18:09 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [jeecgboot/JimuReport] 查询栏 下拉多选搜索无效 (Issue #1316) |

api数据字典查询使用的value 用value值试一下可以查询吗

**Comment by lvdandan16** [comment]
截图看一下配置

**Comment by snkever** [comment]
| |
snkever
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年10月8日 18:17 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [jeecgboot/JimuReport] 查询栏 下拉多选搜索无效 (Issue #1316) |

截图看一下配置

**Comment by 1298191366** [comment]
已修复，待新版本发布

**Comment by mwqgithup** [comment]
从1.5.2升级到1.5.6版本后，点击报表报错： 签名校验失败,参数有误!  大师如何解决啊
