### ISSUE TITLE
查询栏选择字段筛选后，排序sql失效

### ISSUE THREAD

**Issue by overfly-panzn** [jeecgboot/JimuReport#1317]
##### 版本号：
v1.5

##### 问题描述：
查询栏选择字段筛选后，排序sql失效

##### 错误日志&截图：
原本sql：
SELECT t1.a, t1.b, t1.c FROM table_name t1 ORDER BY t1.a, t1.b
筛选后sql：
select * from (
SELECT t1.a, t1.b, t1.c FROM table_name t1 ORDER BY t1.a, t1.b
) WHERE jeecg_rp_temp  where 1=1  AND a= 'xxxx' 
##### 重现步骤：
查询栏选择字段筛选后，排序sql失效

**Comment by lvdandan16** [comment]
具体哪个版本？条件筛选怎么配置的，请图文并茂 详细描述
