### ISSUE TITLE
API自定义查询条件，API被调用多次

### ISSUE THREAD

**Issue by 23VingtTrois** [jeecgboot/JimuReport#1325]
##### 版本号：
1.5.2

##### 问题描述：
报表查询条件，自定义查询条件、API数据集，会调用多次API

##### 错误日志&截图：

![1665065659234](https://user-images.githubusercontent.com/61653732/194336213-5210cbd7-8fb6-4abc-9063-0d0f97a846bf.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by Wwwwwys** [comment]
1.5.4版本问题依然存在，编辑报表页面也多次调用自定义的api接口

**Comment by lsqGitHub716** [comment]
已修改
