### ISSUE TITLE
rtmp播放控件，没有文档中的视频类型属性

### ISSUE THREAD

**Issue by czcz1024** [jeecgboot/JimuReport#1328]
http://report.jeecg.com/2232386 文档中说明rtmp播放控件可以选择视频类型 rtmp hls等
但是我在网站尝试，
![图片](https://user-images.githubusercontent.com/2842888/194696782-3e6bdbce-fe82-48c0-9fa3-e5afa27719cf.png)
没有这个选项

**Comment by lvdandan16** [comment]
后来版本去掉了
