### ISSUE TITLE
权限控制自定义请求头无效

### ISSUE THREAD

**Issue by xal-hb** [jeecgboot/JimuReport#1329]
##### 版本号：
1.5.2

##### 问题描述：
文档中提到用户可自定义请求头，需要重写方法customApiHeader，但是重写了仍然走的是getToken-verifyToken的逻辑，在customApiHeader方法里打断点未进入

##### 重现步骤：
各版本均可复现

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
![image](https://user-images.githubusercontent.com/27989856/202976192-26a7c755-03bb-48fc-8dde-cb70a8abc60f.png)

该文档，明确说明了，api数据集调用api接口的时候，token的相关机制，和verifyToken没有关系，即使需要验证token也是你调用的那个请求对应的项目自己去校验
