### ISSUE TITLE
独立部署打开速度极慢，另外线上可否加打印纸张

### ISSUE THREAD

**Issue by mayiB** [jeecgboot/JimuReport#1330]
##### 版本号：
1.5.2

##### 问题描述：
独立打包成jar部署上自有服务器，访问和打开报表加载很慢，差不多10几秒才能打开；
因为需要自己设置打印纸张，所以才独立部署，可否在线上版本加上打印纸张，需求是 216mm*140mm

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
打印纸张可自定义设置
参考文档：http://report.jeecg.com/2141759
