### ISSUE TITLE
建多个横向动态列无法正常显示

### ISSUE THREAD

**Issue by SunAizheng** [jeecgboot/JimuReport#1331]
##### 版本号：
1.5.2

##### 问题描述：
建多个横向动态列无法正常显示，不同的会不显示，相同的表第一个表动态生成异常

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/103186192/194735221-82891994-5f0e-497f-a510-d229d3a1c0c9.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by C20190420** [comment]
同关注该问题，链接问题集#1341，请求是否是不支持同一张报表上存在两个横向动态分组的报表？

**Comment by lvdandan16** [comment]
同一个报表只支持一个数据集设置为横向分组
