### ISSUE TITLE
横纵组合分组，横向分组第一层级合并单元格，预览效果出问题 : 只有第一个单元格被合并

### ISSUE THREAD

**Issue by C20190420** [jeecgboot/JimuReport#1333]
##### 版本号：
1.5.2版本

##### 问题描述：
横纵组合分组，横向分组第一层级合并单元格，预览效果出问题 : 只有第一个单元格被合并

##### 错误日志&截图：

未合并单元格时效果：
 
![image](https://user-images.githubusercontent.com/71625913/194841695-9f24257c-aea4-4550-a265-1cbe4877fdf5.png)
![image](https://user-images.githubusercontent.com/71625913/194842047-78b28fc1-0d00-40d8-b49b-5ed9b7fe247f.png)

横向第一层级合并单元格后：
![image](https://user-images.githubusercontent.com/71625913/194841859-5d73a67d-4aba-42d2-b93f-160b4fea3aa2.png)
![image](https://user-images.githubusercontent.com/71625913/194841872-a2e15063-d0d6-4fd7-a4ed-093aa543e593.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
已修改
