### ISSUE TITLE
下拉多选存在重复数据

### ISSUE THREAD

**Issue by sparrow10211** [jeecgboot/JimuReport#1335]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/61782327/195038038-e2ca6d95-b015-4f35-8959-4347ad5a0052.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by sparrow10211** [comment]
由于我们存在大量此类型字段的筛选，因此选用字典做查询条件不现实。
所以想请教大佬们可否在源码查询条件那里distinct一下？

**Comment by lvdandan16** [comment]
用字典做查询条件，有分页条数限制实现不了吗
直接源码里distinct 会对排序有影响，所以现在去掉了默认distinct

**Comment by sparrow10211** [comment]
> 

因为我们的下拉查询需要支持门店or客户or产品等，这个数据量有几百甚至上千条，数据字典我们无法及时维护。

**Comment by sparrow10211** [comment]
> 

现在的排序也是有bug的。

**Comment by lvdandan16** [comment]
不需要配数据字段，sql字典  api都可以 参考文档http://report.jeecg.com/2373407

**Comment by sparrow10211** [comment]
> 不需要配数据字段，sql字典 api都可以 参考文档http://report.jeecg.com/2373407

我们的sql字典也需要带有数据源配置的报表参数，例如报表参数配置了一个“门店”参数且设置了一个“客户”的下拉多选查询条件，那此门店可以访问的查询也只能是本门店的客户。

**Comment by lvdandan16** [comment]
> 
那实现不了，字典不支持动态参数，目前只支持固定参数和系统变量

**Comment by sparrow10211** [comment]
> > 
> 
> 那实现不了，字典不支持动态参数，目前只支持固定参数和系统变量

那后续可否迭代实现呢？

**Comment by lvdandan16** [comment]
后续如果实现了，会在官网发布通知

**Comment by sparrow10211** [comment]
好的，谢谢
