### ISSUE TITLE
横向纵向均分组动态扩展，横向纵向均存在分组内小计，如何计算横向总计

### ISSUE THREAD

**Issue by C20190420** [jeecgboot/JimuReport#1337]
##### 版本号：
1.5.2

##### 问题描述：
1、横向纵向均分组动态扩展，横向纵向均存在分组内小计，如何计算横向总计
2、横向动态分组列后，增加固定列时，列样式展示存在问题

线上案例地址：https://cloud.jimureport.com/jmreport/index/740015078463852544?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjU1NTIxMjYsInVzZXJuYW1lIjoiMTg4MzIwNTAxOTAifQ.3jH152l2_bTCyvSMhNlMQlw8CgszCoA0ba_G0BS0tNI

##### 错误日志&截图：
问题1：
![1665543886723](https://user-images.githubusercontent.com/71625913/195240388-d761ec04-746e-4631-8918-748f6236e966.png)
![1665543919933](https://user-images.githubusercontent.com/71625913/195240436-28f7031d-9c31-4a66-9668-ece6c8be7843.png)

问题2：
![1665544006065](https://user-images.githubusercontent.com/71625913/195240627-368aad61-9283-492c-bc11-1865c0c0c102.png)
![1665544043622](https://user-images.githubusercontent.com/71625913/195240658-1c187666-3bfd-46f2-bbc2-8c20eaa8f979.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
横向扩展不支持再加固定列或合计
