### ISSUE TITLE
饼型图能否支持百分比？

### ISSUE THREAD

**Issue by zhoulinhui2018** [jeecgboot/JimuReport#1338]
##### 版本号：
v1.5.2

##### 问题描述：
目前最新版饼型图不支持百分比展示，请问后续能否支持饼状图自动展示百分比

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/200251236-4350978d-0023-4c98-89e4-86690c74ec99.png)

目前数值中是不支持百分比的，提示语中可配置百分比
