### ISSUE TITLE
表格中单元格设置百分比：遇到数值为0时，不显示的问题

### ISSUE THREAD

**Issue by snkever** [jeecgboot/JimuReport#1340]
##### 版本号：
1.52

##### 问题描述：

表格中单元格设置百分比：遇到数值为0时，不显示的问题
##### 错误日志&截图：
![图片](https://user-images.githubusercontent.com/28818320/195285363-fce1d222-fa28-4673-8455-6a5ecb8faf20.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
目前是这样设计的，为0时不显示数据
