### ISSUE TITLE
同一张报表，上下存在两个不同的横向动态分组报表，展示有问题

### ISSUE THREAD

**Issue by C20190420** [jeecgboot/JimuReport#1341]
##### 版本号：
1.5.2版本

##### 问题描述：
同一张报表，先制作一个横向动态分组表格，再下方再增加一个横向动态分组表格（使用另一个数据集），展示结果存在问题，是否不支持一张报表上存在两个分组报表

只有一张报表时：
![image](https://user-images.githubusercontent.com/71625913/195482754-395544e0-3b14-47f7-8813-152336a62e5e.png)
只有一张报表，页面预览正常
![image](https://user-images.githubusercontent.com/71625913/195482773-79158fbe-10d0-46b3-bccb-d1bb61eae5e0.png)

下方添加新的报表（也为横向动态分组）
情况一：新增数据集2（与数据集1为相同字段结构，仅数据集编码不同）
效果：上方原本展示正常的报表出问题，下方正常展示

情况二：新增数据集2（与数据集1为完全不同字段）
效果：预览页面直接展示空白，show方法返回null

##### 错误日志&截图：
以情况二为例截图：
![1665627232607](https://user-images.githubusercontent.com/71625913/195482974-41757982-522f-430a-8bc4-dca5904e8f1d.png)
![1665627246934](https://user-images.githubusercontent.com/71625913/195483004-5976e646-6ba6-4db8-8cdd-4acb99f94a03.png)

##### 重现步骤：
同一张报表
1、先制作一个横向动态分组表格
2、下方再增加一个横向动态分组表格（使用相同数据集或者不同数据集）

线上ID示例：https://cloud.jimureport.com/jmreport/view/740118354878353408?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjU2MzEyOTIsInVzZXJuYW1lIjoiMTg4MzIwNTAxOTAifQ._9U2YEmc81AaC_9tu8R59m7BTF-xDsl5hP-rJkvuFqU

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
同一个报表支持多个数据集，但是只支持一个数据集设置为横向分组
