### ISSUE TITLE
横向分组动态列，上层固定内容不能根据动态列自动扩展并合并单元格

### ISSUE THREAD

**Issue by C20190420** [jeecgboot/JimuReport#1342]
##### 版本号：
1.5.2版本

##### 问题描述：
横向分组动态列，只有下方固定行内容能动态扩展，上层固定内容不能根据动态列自动扩展并合并单元格

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/71625913/195485054-657ba8ea-9507-4176-a616-ea9adb1bf28a.png)
![image](https://user-images.githubusercontent.com/71625913/195485064-e7271ba0-acb0-4fbe-aa62-8506a634e842.png)

##### 重现步骤：
1、先制作一个横向分组动态列报表
2、横向分组动态列，上方添加固定行表头

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
这个问题不好解决，先归集至 #138

**Comment by wm204** [comment]
1.5.8版本这个解决了吗
