### ISSUE TITLE
docker启动的积木报表如何关闭F12输出的大面积console日志？

### ISSUE THREAD

**Issue by qifengzhang007** [jeecgboot/JimuReport#1343]
##### 版本号：
v1.5

##### 问题描述：
新设计了demo报表，打开F12的时候输出了大面积的console日志。
请问如何关闭这些？

##### 错误日志&截图：
![f12-console](https://www.ginskeleton.com/images/f12-console.jpg)

##### 重现步骤：
1.预览
2.F12

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持关闭
