### ISSUE TITLE
20221008新功能在哪个版本中升级了

### ISSUE THREAD

**Issue by heiManMao** [jeecgboot/JimuReport#1347]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
还未发布版本，测试中

**Comment by hezhaoliang** [comment]
预计什么时间发布呢

**Comment by hezhaoliang** [comment]
> 还未发布版本，测试中

预计什么时间发布呢

**Comment by lvdandan16** [comment]
下周会发，发布后会在官网发布升级通知
