### ISSUE TITLE
在线积木大屏的地图功能是否支持上传json文件

### ISSUE THREAD

**Issue by Lee-2019** [jeecgboot/JimuReport#1350]
##### 版本号：
在线积木大屏

##### 问题描述：
在线积木大屏的地图功能如何上传自定义json文件

##### 错误日志&截图：
1.离线地图和联网地图中均没找到上传地图json文件的入口；
2.使用自定义组件，在数据处理中输入json代码，也无法实现自定义地图

##### 重现步骤：
1.离线地图和联网地图中均没找到上传地图json文件的入口；
2.使用自定义组件，在数据处理中输入json代码，也无法实现自定义地图

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
