### ISSUE TITLE
报表导出PDF后，pdf里的图片丢失

### ISSUE THREAD

**Issue by zongxing** [jeecgboot/JimuReport#1353]
##### 版本号：
V1.5.2

##### 问题描述：
报表里上传的图片，在导出PDF时，图片丢失。
tip:导出图片，导出excel，导出pdf图片这3项是可以正常导出图片的。

##### 错误日志&截图：
查看过日志文件，没有错误日志。
下图是报表，左上角是图片：
![image](https://user-images.githubusercontent.com/18585413/196914978-ad1ff3d2-b1c1-4a84-b173-dc2fd9ac59fe.png)
下图是导出后的pdf文件：
![image](https://user-images.githubusercontent.com/18585413/196915148-3f556379-7d97-4b82-9e36-21e44b73dd36.png)

##### 重现步骤：
1：新建一个报表，上传一张图片
2：导出pdf格式的文件
以上步骤可以重现。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
未复现此问题，能否在官网做个示例，我们看一下？

**Comment by zongxing** [comment]
在官网做的一个示例，导出成pdf也出错


1：链接地址：
https://cloud.jimureport.com/jmreport/view/749798900025872384?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2Njc4ODQ3ODAsInVzZXJuYW1lIjoib2hiYUs2Y2RfWU9GSzZiZk9oZ2UyS0RXdGxhdyJ9.9QRvrNvk-z8cjpcmicfXGm3cpfkc0cbw5at7uplP8Mk
2：操作过程的视频
见附件：《积木报表导出pdf问题.mp4》


3：截图














&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月7日(星期一) 下午3:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 报表导出PDF后，pdf里的图片丢失 (Issue #1353)





 
未复现此问题，能否在官网做个示例，我们看一下？

**Comment by lvdandan16** [comment]
图片和文字不要放在一个单元格内

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
