### ISSUE TITLE
Echarts图表代码插入积木在线大屏的自定义组件，图表无法显示

### ISSUE THREAD

**Issue by Lee-2019** [jeecgboot/JimuReport#1354]
##### 版本号：
积木在线大屏

##### 问题描述：
Echarts图表代码插入积木在线大屏的自定义组件，图表无法显示

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/52067106/196918711-c5b26acb-5f6b-4350-bccc-851ecd4c8e32.png)

##### 重现步骤：
1.在Echarts中编辑代码，使用$.get同步获取api中的数据，代码如下：
function getData() {
  var res;
  $.ajaxSettings.async = false;
  $.get(
    'https://mock.mengxuegu.com/mock/634ead34369a770d74bbf781/ssb/test2',
    function (data) {
      res = data;
      $.ajaxSettings.async = true;
    }
  );
  return res;
}
option = {
  series: [
    {
      type: 'pie',
      data: getData()
    }
  ]
};
2.新建大屏，添加自定义组件，在数据值中粘贴上述代码后刷新；
3.图表无法显示。
注：当代码中的数据为静态数据时，图表可以正常显示；当代码中的数据使用$.get同步获取api中的数据时，图表无法显示。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持动态获取数据
