### ISSUE TITLE
对使用函数列使用分组，提示报错

### ISSUE THREAD

**Issue by yangyimin-wq** [jeecgboot/JimuReport#1361]
##### 版本号：
1.5.2

##### 问题描述：
对使用函数列使用分组，提示报错

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/59437168/197461689-5b4bc265-152a-46aa-aa02-718c71054762.png)

其中=quarter()是我自定义的一个计算函数
##### 重现步骤：
对某一列使用函数后，然后使用分组
提示
![image](https://user-images.githubusercontent.com/59437168/197462025-dc607895-82e8-4099-b6cb-9dcf0b0e5613.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持嵌套使用
