### ISSUE TITLE
1.5.4 当报表百分比数据为0时，无法显示为0%，会显示为空白

### ISSUE THREAD

**Issue by hongxin2** [jeecgboot/JimuReport#1362]
##### 问题描述：
1.5.4 当报表百分比数据为0时，无法显示为0%，会显示为空白

##### 错误日志&截图：
无错误日志，数据为0，格式选择百分比即可

##### 重现步骤：
1.5.4 当报表百分比数据为0时，无法显示为0%，会显示为空白

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
目前设计如此，为0时，不显示

**Comment by hongxin2** [comment]
@lvdandan16 这样的话整张表就很奇怪，就是表中间好几块是空白值，我还是直接用sql拼接字符串处理百分比好了
