### ISSUE TITLE
积木自带的无权限页,图标无法正常显示

### ISSUE THREAD

**Issue by Acechengui** [jeecgboot/JimuReport#1364]
##### 版本号：
1.5.4

##### 问题描述：
积木自带的无权限页,图标无法正常显示,
发现需要拼接前缀才能访问到图片

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/63096199/197673328-d76fa316-3279-43f0-bf22-db20d59a947a.png)
需要拼接前缀才能访问到图片,如图
![image](https://user-images.githubusercontent.com/63096199/197673469-218939e9-dab7-4be7-a853-f941e53025bf.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Acechengui** [comment]
11:13:15.888 [http-nio-9301-exec-5] INFO  o.j.m.j.d.a.a - [a,621] - freemarker base: 
11:13:15.888 [http-nio-9301-exec-5] INFO  o.j.m.j.d.a.a - [a,622] - freemarker customPrePath: /dev-api/jove-report

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
