### ISSUE TITLE
积木报表单个动态列如何求和

### ISSUE THREAD

**Issue by gitdpi** [jeecgboot/JimuReport#1365]
##### 版本号：
1.4.0-beta

##### 问题描述：
积木报表单个动态列如何求和

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/32302551/197673435-baacaeec-a3f9-4325-adf9-0052e01cf72d.png)
![image](https://user-images.githubusercontent.com/32302551/197673622-612853a3-4a34-41b9-9d80-5c260d4cf535.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
动态列不支持合计
