### ISSUE TITLE
预览/查看页面,普通输入框问题

### ISSUE THREAD

**Issue by Acechengui** [jeecgboot/JimuReport#1366]
##### 版本号：
1.5.4

##### 问题描述：
现在的普通输入流没有清空按钮,属于一个小细节的需求,望官方能加上,也不难,因为是elementui,加个属性就行~

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/63096199/197676786-c77c425b-70c3-4bf1-abeb-0871e41bf89f.png)
如图,加上clearable 

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
以支持，待新版本发布
