### ISSUE TITLE
积木带参数的api接口进行查询，页面无法显示结果

### ISSUE THREAD

**Issue by he365277** [jeecgboot/JimuReport#1369]
##### 错误日志&截图：

解析结果：
 {"0":{"cells":{"0":{"text":"学号"},"1":{"text":"姓名"},"2":{"text":"开始时间"}}},"1":{"cells":{"0":{"text":"17012101031"},"1":{"text":"任依果"},"2":{"text":"2022-10-21"}}},"len":22}
浏览器报错信息：
TypeError: Cannot read property 'data' of null
    at view.js?v=v=1.0.7:268
    at Object.success (manager.js?v=v=1.0.7:71)
    at request.js?v=v=1.0.7:73

##### 重现步骤：
带参数的api查询

**Comment by lvdandan16** [comment]
接口返回报错吗？

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
