### ISSUE TITLE
图片显示问题

### ISSUE THREAD

**Issue by hyh1688** [jeecgboot/JimuReport#1370]
##### 版本号：
  1.5.2

##### 问题描述：
  base64格式的图片不显示

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/5525918/197702765-1c14f192-b7b0-4b84-8149-1abe993e31a4.png)

##### 重现步骤：
略

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持base64格式的图片
