### ISSUE TITLE
数据库返回的是数组，怎么根据字典显示出值

### ISSUE THREAD

**Issue by Lam9547** [jeecgboot/JimuReport#1372]
##### 问题描述：

数据库返回的是数组，怎么根据字典显示出值
##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/107109710/197727398-63168786-8168-4fea-9688-f67f146a2b68.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/200262826-aea66a22-2de8-45ee-8ddc-94ded71f5927.png)

参考文档：http://report.jeecg.com/2083759#__70
