### ISSUE TITLE
报表编辑时最多显示到AX列

### ISSUE THREAD

**Issue by XTLidp** [jeecgboot/JimuReport#1373]
##### 版本号：
1.5.4

##### 问题描述：
报表新增时最多显示到AX列，但是通过新增列可以继续增加列。编辑时最多显示到AX列，后面的列无法显示，但是在预览或导出excel时可以显示AX列之后的列。

##### 错误日志&截图：

![编辑](https://user-images.githubusercontent.com/78455429/197733352-48b5e95a-9739-4d11-9241-276f38bc9708.jpg)
<img width="720" alt="预览" src="https://user-images.githubusercontent.com/78455429/197733633-f6694c32-6b9d-4d5d-b7d8-7a6fd0eec387.png">
<img width="665" alt="导出" src="https://user-images.githubusercontent.com/78455429/197733818-dc8475a2-6b00-4116-83fa-3da966e67001.png">

##### 重现步骤：
1、新增报表最多显示到AX列，通过新增列可以显示更多。
2、保存后编辑报表，最多显示到AX列，后面的列无法显示也就无法编辑了。
3、通过预览或导出可以显示添加的所有列。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
常见问题34：http://report.jeecg.com/2087464
