### ISSUE TITLE
报表API接口请求超时时长

### ISSUE THREAD

**Issue by ywm12345** [jeecgboot/JimuReport#1374]
##### 错误日志&截图：
![1666696810218_FCE4F3E4-481A-4ca3-81A7-0BE0972AC0A0](https://user-images.githubusercontent.com/85282624/197762718-01f1c5ac-6948-4f27-9389-b28455a43da0.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
可升级版本试一下
`
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.5.4</version>
</dependency>
`
