### ISSUE TITLE
导出excel后出现边框

### ISSUE THREAD

**Issue by Yxw521** [jeecgboot/JimuReport#1377]
##### 重现步骤：
![image](https://user-images.githubusercontent.com/76502207/197923861-c5039104-7428-488f-854f-bfc4fd1bd65b.png)
![image](https://user-images.githubusercontent.com/76502207/197923892-4f3cd36e-3d8f-492e-ace7-9eb44bf227eb.png)
![image](https://user-images.githubusercontent.com/76502207/197924181-7ebc0c9c-32c2-48e6-9a74-87fd4f9ca1d6.png)

**Comment by lvdandan16** [comment]
有数据的时候，导出默认会加上边框

**Comment by Yxw521** [comment]
有的时候是不想要的，有没有办法解决呢


鈊姷所属の
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月7日(星期一) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 导出excel后出现边框 (Issue #1377)





 
有数据的时候，导出默认会加上边框
