### ISSUE TITLE
页码显示问题

### ISSUE THREAD

**Issue by pengjunli** [jeecgboot/JimuReport#1378]
##### 版本号：
1.5.4

##### 问题描述：
没有页码显示，我看官网上有页码显示

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/38717534/198051529-68d708d2-f39c-4c76-8fc2-deae7b3c3dc7.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
打印报表的页面是没有的，可设置浏览器的页眉页脚，但是这样的话可能链接也会打印出来
