### ISSUE TITLE
分组情况下，显示数据不全问题

### ISSUE THREAD

**Issue by nageshui** [jeecgboot/JimuReport#1379]
##### 版本号：
1.5.3

##### 问题描述：
2列纵向分组，3行横向分组，1个动态列。表格显示缺少数据

##### 错误日志&截图：
<img width="641" alt="image" src="https://user-images.githubusercontent.com/6081582/198176983-02259e3b-7786-4ed7-9d89-2fff4c02f207.png">
<img width="853" alt="image" src="https://user-images.githubusercontent.com/6081582/198177114-437d0bb3-1af0-47e8-b6d2-4470a3d7262a.png">

console打印出来的数据：
解析后内容 {"0":{"cells":{"2":{"text":""}}},"1":{"cells":{"1":{"merge":[2,1],"style":1,"text":"操作员号","height":75},"3":{"completeBlankStatus":true,"rendered":"","merge":[0,3],"style":1,"text":"已对账","config":"","aggregate":"group","direction":"right"}}},"2":{"cells":{"3":{"completeBlankStatus":true,"rendered":"","merge":[0,1],"style":1,"text":"扫码","config":"","aggregate":"group","direction":"right"},"5":{"completeBlankStatus":true,"rendered":"","merge":[0,1],"style":1,"text":"银行卡","config":"","aggregate":"group","direction":"right"}}},"3":{"cells":{"3":{"completeBlankStatus":true,"rendered":"","style":1,"text":"挂号","config":"","direction":"right"},"4":{"completeBlankStatus":true,"rendered":"","style":1,"text":"缴费","config":"","direction":"right"},"5":{"completeBlankStatus":true,"rendered":"","style":1,"text":"挂号","config":"","direction":"right"},"6":{"completeBlankStatus":true,"rendered":"","style":1,"text":"缴费","config":"","direction":"right"}}},"4":{"cells":{"1":{"style":0,"text":"0062/张浩","aggregate":"group","cellIndex":"1","rowIndex":"7","merge":[3,0]},"2":{"rendered":"","style":0,"text":"1201VBIG","config":"","aggregate":"group"},"3":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"4.00","config":"","aggregate":"dynamic"},"4":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"","config":"","aggregate":"dynamic"},"5":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"","config":"","aggregate":"dynamic"},"6":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"","config":"","aggregate":"dynamic"},"7":{"rendered":"","text":"","config":""}}},"5":{"cells":{"2":{"rendered":"","style":0,"text":"1201VBIH","config":"","aggregate":"group"},"3":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"2.00","config":"","aggregate":"dynamic"},"4":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"","config":"","aggregate":"dynamic"},"5":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"","config":"","aggregate":"dynamic"},"6":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"","config":"","aggregate":"dynamic"},"7":{"rendered":"","text":"","config":""}}},"6":{"cells":{"2":{"rendered":"","style":0,"text":"1201VBIK","config":"","aggregate":"group"},"3":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"562.00","config":"","aggregate":"dynamic"},"4":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"","config":"","aggregate":"dynamic"},"5":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"","config":"","aggregate":"dynamic"},"6":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"","config":"","aggregate":"dynamic"},"7":{"rendered":"","text":"","config":""}}},"7":{"cells":{"2":{"rendered":"","style":0,"text":"1201VBIO","config":"","aggregate":"group"},"3":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"2.00","config":"","aggregate":"dynamic"},"4":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"","config":"","aggregate":"dynamic"},"5":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"","config":"","aggregate":"dynamic"},"6":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"","config":"","aggregate":"dynamic"},"7":{"rendered":"","text":"","config":""}}},"8":{"cells":{"1":{"style":0,"text":"0302/张赛茹","aggregate":"group","cellIndex":"1","rowIndex":"10","merge":[2,0]},"2":{"rendered":"","style":0,"text":"1201VBIH","config":"","aggregate":"group"},"3":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"-24.00","config":"","aggregate":"dynamic"},"4":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"","config":"","aggregate":"dynamic"},"5":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"","config":"","aggregate":"dynamic"},"6":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"","config":"","aggregate":"dynamic"},"7":{"rendered":"","text":"","config":""}}},"9":{"cells":{"2":{"rendered":"","style":0,"text":"1201VBIK","config":"","aggregate":"group"},"3":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"6.00","config":"","aggregate":"dynamic"},"4":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"","config":"","aggregate":"dynamic"},"5":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"","config":"","aggregate":"dynamic"},"6":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"","config":"","aggregate":"dynamic"},"7":{"rendered":"","text":"","config":""}}},"10":{"cells":{"2":{"rendered":"","style":0,"text":"1201VBIL","config":"","aggregate":"group"},"3":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"873.60","config":"","aggregate":"dynamic"},"4":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"","config":"","aggregate":"dynamic"},"5":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"","config":"","aggregate":"dynamic"},"6":{"completeBlankStatus":false,"rendered":"","display":"number","style":2,"text":"","config":"","aggregate":"dynamic"},"7":{"rendered":"","text":"","config":""}}},"11":{"cells":{"3":{"rendered":"","text":"","config":""},"4":{"rendered":"","text":"","config":""},"5":{"rendered":"","text":"","config":""},"6":{"rendered":"","text":"","config":""},"7":{"rendered":"","text":"","config":""},"8":{"$ref":"$.rows.11.cells.7"}}},"12":{"cells":{"3":{"rendered":"","text":"","config":""}}},"13":{"cells":{"4":{"rendered":"","text":"","config":""}}},"len":34}

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请把数据导出来，我们复现一下

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
