### ISSUE TITLE
堆叠柱形图设计和预览不一致

### ISSUE THREAD

**Issue by zhangdaiscott** [jeecgboot/JimuReport#1380]
##### 版本号：
1.5.2

##### 问题描述：
在设计堆叠柱形图的时候，设计页面显示的是同一柱体，但是预览页面就又分开了，只有开启刷新定时刷新才会显示到一起，但是字典数据不会带上

##### 截图&代码：
![输入图片说明](https://foruda.gitee.com/images/1663308143202924947/b06869a1_7550214.png "屏幕截图")
预览页面：
![输入图片说明](https://foruda.gitee.com/images/1663308292843175034/c9aa5dac_7550214.png "屏幕截图")
定时刷新后：
![输入图片说明](https://foruda.gitee.com/images/1663308248605561795/a56045ca_7550214.png "屏幕截图")

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by zhangdaiscott** [comment]
sq
