### ISSUE TITLE
希望支持存储过程情况下分页

### ISSUE THREAD

**Issue by hongxin2** [jeecgboot/JimuReport#1381]
##### 版本号：
1.5.4

##### 问题描述：
目前存储过程情况下无法进行分页，采用存储过程获取当前页码传参的方式，能够用正常获取当前页码，但前端缺无法进行翻页（翻页按钮为灰色），希望在存储过程情况下能过翻页

##### 错误日志&截图：
无

##### 重现步骤：
无

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
归集到：#138
