### ISSUE TITLE
yml中设置了项目前缀，分享链接地址有误

### ISSUE THREAD

**Issue by 617972800** [jeecgboot/JimuReport#1383]
##### 版本号：
1.5.4

##### 问题描述：
yml中设置了项目前缀，分享链接地址有误

##### 重现步骤：
yml中设置了项目前缀，如下
```
jeecg :
  jmreport:
    #自定义项目前缀
    customPrePath: demo
```

1. 第一次分享链接地址是正确的（http://127.0.0.1:8081/demo/jmreport/shareView/744788905193111552）；
2. 关闭分享页面后，再次查看分享链接地址显示为（http://127.0.0.1:8081/jmreport/shareView/744788905193111552）--是错误的，链接地址中少了“/demo”

期望：
链接地址正确显示

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
