### ISSUE TITLE
升级到1.5.4版本后,导出的excel没有背景颜色

### ISSUE THREAD

**Issue by taie-dev** [jeecgboot/JimuReport#1384]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/7703003/198210211-52bd87d6-ffea-40c3-8a39-43eecadbf7ac.png)
![image](https://user-images.githubusercontent.com/7703003/198210319-0ff89e52-4d7e-4f51-9707-d31ba0e85f9b.png)

**Comment by lvdandan16** [comment]
1.5.0以后版本去掉了导出excel样式
