### ISSUE TITLE
独立表格设置分版，内容自动换行还是会影响到其他表格

### ISSUE THREAD

**Issue by Lory996** [jeecgboot/JimuReport#1386]
##### 版本号：
1.4.2 - 1.5.2

##### 问题描述： 
独立表格设置分版，内容自动换行还是会影响到其他表格。

##### 错误日志&截图：
设计：
![image](https://user-images.githubusercontent.com/54149687/198223361-25a43da1-56fd-4850-b167-3e30d3e6c48f.png)

结果：
![image](https://user-images.githubusercontent.com/54149687/198223626-57447e4d-e8a9-4dd5-af2b-c95135ffbdfd.png)

##### 重现步骤：
左右两边是两个表格，对右边独立表格进行分版，其中有的内容使用自动换行会影响到左边表格。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Lory996** [comment]
Pdf导出接口方案 · JimuReport 积木报表 · 看云 http://report.jeecg.com/2373087
还有个问题是 pdf 导出接口 /jmreport/exportPdf 你们哪个版本删掉了，麻烦检查下是不是代码覆盖引起的。
确认影响版本：1.5.0-1.5.4  其他版本没看影不影响。

**Comment by Lory996** [comment]
从1.4.2升级至1.5.4
问题：可能因为内容有换行，导致整体高度发生问题，导出的PDF还是有各种问题。
升级前：
![DN{PRRN7 _R6GXE5U8M%`SD](https://user-images.githubusercontent.com/54149687/200239890-9860866f-2152-4057-8194-81e73f9ad4dc.png)

升级后：
![JT({9KJ__Z U%9GEFNK}S G](https://user-images.githubusercontent.com/54149687/200238304-6d253203-0865-4a00-815f-adb090c36e45.png)

表格断裂。
![image](https://user-images.githubusercontent.com/54149687/200240111-3c9302a8-5893-4857-8246-bbac3067b9bb.png)

**Comment by lvdandan16** [comment]
升级后，报表设计界面重新修改保存一下试试

**Comment by Lory996** [comment]
需要做什么操作？还是升级之后报表设计直接点保存就行了。

问题：分栏之后，打印凸出单元格
分栏之后列数是超了的，预览也凸出，所以对AB列设置了宽度0.01，预览是没问题了，但是打印和PDF之类的估计有问题。

设计：
![%3 1O)W}{ ~D(HPFLP7R8UD](https://user-images.githubusercontent.com/54149687/200451362-99aeb792-42cd-4cca-85d5-12d506b83d45.png)

结果：
![image](https://user-images.githubusercontent.com/54149687/200451667-8f81fe0f-1810-46c8-a6d7-26ba8961a797.png)

**Comment by lvdandan16** [comment]
不需要操作什么，随意拖动一下，直接保存接口

![image](https://user-images.githubusercontent.com/54099258/200487588-f82ab13c-bb69-4d0a-9379-6b1aef66ba48.png)

你这个分栏后，实际使用列数和你预留的列数保持一致，循环块内不需要已使用合并单元格
