### ISSUE TITLE
关于导出excel设置sheet最大值的问题

### ISSUE THREAD

**Issue by LiRuiBo001** [jeecgboot/JimuReport#1388]
##### 版本号：
1.4.4-beta

##### 问题描述：
导出excel时报表数据较大，分成每页只有10000条，如何设置最大值？
必须使用jeecg项目吗？不能在自己的springboot中配置吗？
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
导出sheet条数自定义参考文档：http://report.jeecg.com/2084047
是不是jeecg项目均可
