### ISSUE TITLE
【求教】报表能否实现Z字形数据展示？

### ISSUE THREAD

**Issue by antbuster** [jeecgboot/JimuReport#1390]
##### 版本号：
1.5.3

##### 问题描述：
报表能否实现Z字形数据展示？
**比如我有如下主从表：**
![image](https://user-images.githubusercontent.com/10290156/198496226-8f72c021-f581-4931-9004-6d5857ac1b24.png)
![image](https://user-images.githubusercontent.com/10290156/198496301-0e42638e-d8f7-43ce-a69a-c281b1ad3bea.png)

**想实现如下效果是否可行？**
![image](https://user-images.githubusercontent.com/10290156/198496806-098cf535-c139-4487-8f75-9f98e96d1426.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
