### ISSUE TITLE
分组跨页排序问题

### ISSUE THREAD

**Issue by speckle23** [jeecgboot/JimuReport#1391]
##### 版本号：
1.5.2

##### 问题描述：
分组时排序无法按照数据库查出的顺序输出，如第二页都是海西，第三页会先出现其他地区再出现海西,在分组排序那边设置也无法解决这个排序困扰。

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/54102334/198497723-188ab496-0df7-4b9f-a6a4-0ae87dee9744.png)

![image](https://user-images.githubusercontent.com/54102334/198497627-5625fe6a-e6e2-445e-9c7e-35974236805f.png)

预期第三页应该先展示海西再展示其他区域
##### 重现步骤：
需要有一定量的数据分组跨页时如果分组的字段输出不同信息就会出现这种情况

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级1.5.4版本试一下
`<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.5.4</version>
</dependency>
`

**Comment by speckle23** [comment]
升级到1.5.4依然存在这个问题

**Comment by lvdandan16** [comment]
分组排序不要选择，默认排序即可
