### ISSUE TITLE
希望作者抽空把 dockerhub 仓库的镜像更新到最新版，方便非java用户使用

### ISSUE THREAD

**Issue by qifengzhang007** [jeecgboot/JimuReport#1392]
##### 版本号：
hub.docker.com 仓库的镜像太仍然停留在v1.5.0 版本。

##### 问题描述：
积木报表在   hub.docker.com 仓库中的镜像仍然停留在 v1.5.0 版本，希望作者抽空能更新到最新版本(v1.5.4)，方便非java用户快速使用.

感谢！

##### 错误日志&截图：
暂无

##### 重现步骤：
暂无

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录

**Comment by 1298191366** [comment]
以上传1.5.4
[文档](http://report.jeecg.com/3007400)
只需要把版本号改成`1.5.4`即可
![image](https://user-images.githubusercontent.com/30997828/202612185-a316d2e1-cb61-4b01-a8fd-502a964edd60.png)
