### ISSUE TITLE
发布到生产环境后，其他的资源能加载出来 ，api.js 提示404 ，加载不到

### ISSUE THREAD

**Issue by guoxixijk** [jeecgboot/JimuReport#1393]
##### 错误日志&截图：
Z7C~$0}8P](https://user-images.githubusercontent.com/33819867/198524955-571720d5-3040-46b0-864b-e37eb67f5103.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档：http://report.jeecg.com/2506684
