### ISSUE TITLE
柱状图自定义配色失效

### ISSUE THREAD

**Issue by chengxucai** [jeecgboot/JimuReport#1394]
##### 版本号：
1.5.2

##### 问题描述：
柱状图自定义配色失效

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/36264031/198545053-c103249f-b9c9-4479-936b-b7dc684fa116.png)
![image](https://user-images.githubusercontent.com/36264031/198545174-8b830652-8819-47cb-a2c8-507a5126a9d9.png)
js中的颜色丢失
![image](https://user-images.githubusercontent.com/36264031/198545446-ffe30241-5acf-4287-9ccb-0038a7becd04.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
未复现此问题，可在官网做个示例复现一下

**Comment by chengxucai** [comment]
发现原因了，查询结果的顺序会影响柱状图的显示
