### ISSUE TITLE
报表页面展示和导出EXCEL样式不一致

### ISSUE THREAD

**Issue by 71907239** [jeecgboot/JimuReport#1396]
##### 版本号：
1.5.4

##### 问题描述：
报表预览页面没有单元格的边框，但是实际导出的EXCEL里面是有边框的，并且无法设置无边框清除掉

##### 错误日志&截图：
报表中没有显示边框
![image](https://user-images.githubusercontent.com/11450758/198883222-0caefa50-df53-405a-8a14-5b9aaad6e8a4.png)
报表预览界面没有边框
![image](https://user-images.githubusercontent.com/11450758/198883258-5d1346ae-2825-4fbe-9e6e-81f3d64f462d.png)
导出EXCEL是有边框的，并且无法去掉
![image](https://user-images.githubusercontent.com/11450758/198883288-ff74a59e-4661-436f-b714-caff95006807.png)

##### 重现步骤：
如果报表中被设置过边框，并且在报表中设置无边框后，虽然报表页面和预览页面没有显示了，但是导出EXCEL还是会有边框的，往往只有把这个单元格的行或者列都删除掉，才能去掉这个边框。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by Lory996** [comment]
这个问题我也有，Excel文件是用WPS打开的，设置export-excel-pattern: primary 也没效果。
报表设计：没有边框，而且左对齐
![image](https://user-images.githubusercontent.com/54149687/200814022-1f8e46e6-8b74-4ff2-9dc2-213f0c5f6d88.png)

![image](https://user-images.githubusercontent.com/54149687/200815989-66b1879f-2fff-4b80-b73b-131f6428bc07.png)

导出结果：有奇怪的边框，而且 好像用的还是默认样式，居中了
![image](https://user-images.githubusercontent.com/54149687/200814098-970dde1d-76d2-4085-af8b-cc3c3e5b014c.png)

![image](https://user-images.githubusercontent.com/54149687/200815894-d98ebf85-61cd-451a-9822-71427192974b.png)

**Comment by 1298191366** [comment]
下版本支持yml中配置多少行`excel-style-row`不设置样式，默认1000行，注意：样式多的话可能导致导出excel报错

**Comment by Lory996** [comment]
你这样加参数配置测试过因为中间有数据循环，行数其实不固定吗？
其实行下限边界不好确定，但是列边界是固定可以确定的，搞个配置列边界的参数来限制列样式边界。

你加这个配置参数其实意义不大，根本上也许还是你们代码哪有问题。
而且这种处理方案也不适合前面兄弟提的问题。

> 下版本支持yml中配置多少行`excel-style-row`不设置样式，默认1000行，注意：样式多的话可能导致导出excel报错

你这样加参数配置测试过因为中间有数据循环，行数其实不固定吗？
其实行下限边界不好确定，但是列边界是固定可以确定的，搞个配置列边界的参数来限制列样式边界。

你加这个配置参数其实意义不大，根本上也许还是你们代码哪有问题。
而且这种处理方案也不适合前面兄弟提的问题。

**Comment by Lory996** [comment]
> 下版本支持yml中配置多少行`excel-style-row`不设置样式，默认1000行，注意：样式多的话可能导致导出excel报错

你这样加参数配置测试过因为中间有数据循环，行数其实不固定吗？
其实行下限边界不好确定，但是列边界是固定可以确定的，搞个配置列边界的参数来限制列样式边界。

你加这个配置参数其实意义不大，根本上也许还是你们代码哪有问题。
而且这种处理方案也不适合前面兄弟提的问题。

**Comment by XTLidp** [comment]
1.5.6版本去掉了前几列的边框，L列之后的边框还带着。
这是1.5.6之前版本：
![image](https://user-images.githubusercontent.com/78455429/219537011-ab9f0dd8-544d-4205-8b3a-54b2b4766d3a.png)
这是1.5.6版本：
![image](https://user-images.githubusercontent.com/78455429/219537142-09cc8383-a91c-489d-8f4f-cbe4bbbb6f1b.png)
这是预览的效果：
![image](https://user-images.githubusercontent.com/78455429/219537334-b7ce11c3-81fd-4d59-90cb-c48897f0bda3.png)

**Comment by tennisdd** [comment]
我也遇到这个问题，1.4.32版本没有问题，升级到1.5.6就出现了，很奇怪
