### ISSUE TITLE
excel导出样式丢失

### ISSUE THREAD

**Issue by meepo8023** [jeecgboot/JimuReport#1398]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/88531867/198965327-9ef61d61-cae1-4892-a88f-6f1985ee7c26.png)
![image](https://user-images.githubusercontent.com/88531867/198965450-536f49c2-52cb-4fb2-98cc-40be37a91b6a.png)
![image](https://user-images.githubusercontent.com/88531867/198965420-5ad0ad61-e2e3-4b26-bf7e-0a515d2e5d2d.png)

##### 重现步骤：
表格行设置样式判断逻辑标色后，点击导出

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
1.5.0以后取消了excel导出样式
