### ISSUE TITLE
需求：API数据集支持嵌套

### ISSUE THREAD

**Issue by slhe08** [jeecgboot/JimuReport#1399]
##### 版本号：
1.5.4

##### 需求描述：
API数据集有2层嵌套的情况，报表设计时需要先遍历第一层，再遍历第二层

##### 效果图：
![image](https://user-images.githubusercontent.com/28702072/199138505-e5566244-7288-46c6-bd2f-1cf0a9e07807.png)

##### JSON数据：
[
{
  "corpName":"中国移动分公司",
  "payInfo": [
    {"month": "202210","insuType": "养老保险","atm": "1500"}, 
    {"month": "202209","insuType": "养老保险","atm": "1500"}, 
    {"month": "202208","insuType": "养老保险","atm": "1500"}, 
    {"month": "202207","insuType": "养老保险","atm": "1500"}
  ]
},
{
  "corpName":"龙江地产",
  "payInfo": [
    {"month": "202206","insuType": "养老保险","atm": "1200"}, 
    {"month": "202205","insuType": "养老保险","atm": "1200"}, 
    {"month": "202204","insuType": "养老保险","atm": "1200"}, 
    {"month": "202203","insuType": "养老保险","atm": "1200"}, 
    {"month": "202202","insuType": "养老保险","atm": "1200"}, 
    {"month": "202201","insuType": "养老保险","atm": "1200"}
  ]
}
]

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
嵌套不支持，返回数据处理可参考文档：http://report.jeecg.com/2293839
