### ISSUE TITLE
Api 自定义条件下拉数据

### ISSUE THREAD

**Issue by YeyuchenBa** [jeecgboot/JimuReport#1400]
##### 问题描述：这里能加条件筛选吗 不能加有什么方式筛选吗 看到 APi主可以条件筛选 查询条件可以吗
![ J(TO~UF1KXTIPR U1` A3GP](https://user-images.githubusercontent.com/117083299/198997776-6228fdf2-64d1-4570-af51-ea147fd912dd.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
字典筛选条件目前只支持固定值或系统上下文变量，不支持动态参数
参考文档：http://report.jeecg.com/2177487
