### ISSUE TITLE
无法调整打印区域边线

### ISSUE THREAD

**Issue by javeweb01** [jeecgboot/JimuReport#1402]
##### 版本号：
1.5.4

##### 问题描述：
无法调整打印区域边线

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/24342810/199158423-fcdd0f7e-4250-46e3-ac80-635460c39810.png)

**Comment by lvdandan16** [comment]
后续版本取消了设置，不在支持调整打印线，可通过打印设置调整打印纸张大小

**Comment by liyang1987jay** [comment]
A4都打印不全
