### ISSUE TITLE
字典形态多值下无法转成字典名称如（2,3）

### ISSUE THREAD

**Issue by ljl120** [jeecgboot/JimuReport#1403]
#1005 

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/200239541-49a20a61-2f71-4190-abc0-bbbb93c71baf.png)

参考文档：http://report.jeecg.com/2083759#__70
