### ISSUE TITLE
分享功能后台sql报错

### ISSUE THREAD

**Issue by alzerwv** [jeecgboot/JimuReport#1404]
##### 问题描述：
使用分享功能之后，报错。

##### 错误日志&截图：
![YZ36 BZG6GFQ6 L~7)H $UQ](https://user-images.githubusercontent.com/117156637/199191716-a07a2116-a6e3-4b75-ac73-5c94d65884ef.png)
![GHNF9CGT8_ZZV}2@@5$ (GC](https://user-images.githubusercontent.com/117156637/199191731-492a179f-8b5b-427f-87b9-fa9f99063172.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by alzerwv** [comment]
is there any one 救救me

**Comment by lvdandan16** [comment]
缺少升级SQL，官网升级日志中可查找：http://jimureport.com/doc/log
