### ISSUE TITLE
动态列表头居中显示

### ISSUE THREAD

**Issue by yangcoolq** [jeecgboot/JimuReport#1405]
##### 版本号：
1.5.2

##### 问题描述：
动态列报表，如何居中
![图片](https://user-images.githubusercontent.com/80020311/199216409-a7146e84-569b-4ebe-9c69-eb46bf1babf4.png)

##### 错误日志&截图：

无错误，就是显示不好看，达不到产品经理的最低要求
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持，调整起来有难度，归集到：#138
