### ISSUE TITLE
报表内多表格情况，在不知道表格行数的时候能不能配置表格独占一页

### ISSUE THREAD

**Issue by zhangsainan** [jeecgboot/JimuReport#1406]
##### 版本号：
1.5.4

##### 问题描述：
[报表内有多个表格，且表格多少行不知道，能不能单出配置独占一页，现在只能通过添加空白行处理]
添加空白行会导致预览空白行行高不可控，预览会多空白行
##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/45391789/199377718-47098a9e-de7f-4df2-a271-daed95970f55.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
