### ISSUE TITLE
通过接口导出excel如何自定义导出文件名称？

### ISSUE THREAD

**Issue by yangcoolq** [jeecgboot/JimuReport#1407]
##### 版本号：

1.5.2
##### 问题描述：

通过接口导出excel如何自定义导出文件名称？目前的技术文档没有说明如何传入文件名称，导出后的文件默认的命名是报表模板的名称
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持自定义导出文件名称
