### ISSUE TITLE
预览查询数据优化

### ISSUE THREAD

**Issue by speckle23** [jeecgboot/JimuReport#1409]
##### 版本号：
1.5.2

##### 问题描述：
可以支持预览跳转页面时不做查询数据,点击查询时才真正查询数据的设置吗？或如何设置才可以达到这样的效果

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
直接设置不支持，可以尝试添加查询条件默认值，默认条件查不出数据，修改条件重新查询后，显示数据
