### ISSUE TITLE
OOM:MetaSpace

### ISSUE THREAD

**Issue by bj-wangxing** [jeecgboot/JimuReport#1410]
##### 问题描述：
积木报表使用了 Aviator 作为表达式引擎，我看到在1.4.1 这个版本中
org.jeecg.modules.jmreprort.desreprt.express.b 这个类中的 出现了如下代码：
expression = e.compile(str);  这会造成 JVM ClassLoader 不断的加载类进入 MetaSpace
而这部分资源又不能被释放
 所以这行代码是否应改为 expression = e.compile(str,true);  将表达式解析放入缓存中；

JDK1.8 取消了 PermGen，引入了 MetaSpace，这行代码如果不改，在生成报表数据较多的时候会造成 OOM:MetaSpace

##### 错误日志&截图：
![微信图片_20221102163617](https://user-images.githubusercontent.com/45442343/199439954-c0ce154a-4b06-4e70-81a6-bf6fa8693231.png)

##### 重现步骤：
生成一张数据量比较大的报表

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
已修改
