### ISSUE TITLE
设计时没超出虚线,html打印时文字显示不全

### ISSUE THREAD

**Issue by 13759867353** [jeecgboot/JimuReport#1411]
##### 版本号：
1.5.2

##### 问题描述：
设计时没超出虚线,html打印时文字显示不全

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/117267741/199451841-2ea1d6d4-83bc-4cf0-96a8-67b31dbb9d23.png)
![image](https://user-images.githubusercontent.com/117267741/199451918-f986d363-7087-41aa-b87d-9b9a8caaf662.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by 13759867353** [comment]
> 收录 ty
导出pdf也有同样的样式问题
![image](https://user-images.githubusercontent.com/117267741/200529311-e7f453b6-c0d1-4cc0-bba8-0b7e6e0b2773.png)
![image](https://user-images.githubusercontent.com/117267741/200529352-24351af8-fc52-4a19-bbe8-3a4775f7ae54.png)

**Comment by lvdandan16** [comment]
> > 收录 ty
> > 导出pdf也有同样的样式问题
> > ![image](https://user-images.githubusercontent.com/117267741/200529311-e7f453b6-c0d1-4cc0-bba8-0b7e6e0b2773.png)
> > ![image](https://user-images.githubusercontent.com/117267741/200529352-24351af8-fc52-4a19-bbe8-3a4775f7ae54.png)

可以先试一下，右侧不要靠边界太近，留一点间距试试

**Comment by 13759867353** [comment]
> > > 收录 ty
> > > 导出pdf也有同样的样式问题
> > > ![image](https://user-images.githubusercontent.com/117267741/200529311-e7f453b6-c0d1-4cc0-bba8-0b7e6e0b2773.png)
> > > ![image](https://user-images.githubusercontent.com/117267741/200529352-24351af8-fc52-4a19-bbe8-3a4775f7ae54.png)
> 
> 可以先试一下，右侧不要靠边界太近，留一点间距试试

也不行的,你看看
![image](https://user-images.githubusercontent.com/117267741/200530688-cad37495-c451-4c36-92c2-8b71574bf4c4.png)
![image](https://user-images.githubusercontent.com/117267741/200530789-f75936c5-6462-44c5-b81d-9f8464579d2e.png)

**Comment by lvdandan16** [comment]
把您这个模板导出报表配置，发上来，我试一下，您这边也升级1.5.4版再试一下

**Comment by 13759867353** [comment]
> 把您这个模板导出报表配置，发上来，我试一下，您这边也升级1.5.4版再试一下

[新建文本文档 (3).txt](https://github.com/jeecgboot/JimuReport/files/9959921/3.txt)

**Comment by 13759867353** [comment]
1.5.4也不行

**Comment by lvdandan16** [comment]
> 1.5.4也不行

好的，已收录

**Comment by 13759867353** [comment]
> 

那个版本呢

**Comment by lvdandan16** [comment]
> > 
> 
> 那个版本呢

得下次发版了，发版的时候会在官网发布通知

**Comment by 13759867353** [comment]
> 

好的,感谢

**Comment by lvdandan16** [comment]
> > 
> 
> 好的,感谢
升级1.5.5  配置私服 
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.5.5</version>
</dependency>

**Comment by 13759867353** [comment]
> > > 
> > 
> > 
> > 好的,感谢
> > 升级1.5.5  配置私服
> 
> ```
> <dependency>
>   <groupId>org.jeecgframework.jimureport</groupId>
>   <artifactId>jimureport-spring-boot-starter</artifactId>
>   <version>1.5.5</version>
> </dependency>
> ```

私服怎么配置呢
