### ISSUE TITLE
横向扩展报表相关问题

### ISSUE THREAD

**Issue by wuhonglin520** [jeecgboot/JimuReport#1412]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/34824958/199642034-1a301d0b-af1e-4f15-8b59-53dda19f3ffb.png)

![image](https://user-images.githubusercontent.com/34824958/199642066-414d8379-c39d-4a12-bb62-97eb7c88c442.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持上方放动态列
