### ISSUE TITLE
jeecg-boot2.4.6集成积木报表1.4.2运行正常，积木报表升级到1.5.4之后，导致所有功能页面访问时都报SQL语法错误。

### ISSUE THREAD

**Issue by wfeng616** [jeecgboot/JimuReport#1413]
##### 版本号：
积木报表1.5.4

##### 问题描述：
1、从官网下载jeecg-boot-2.4.6代码，将积木报表的版本号改为1.5.4。
```
<!-- 积木报表 -->
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.5.4</version>
</dependency>
```

2、积木报表可以正常使用，但是会导致jeecg-boot-2.4.6项目中所有功能页面访问报错，错误信息如下：
`### Error querying database. Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') FROM sys_user WHERE del_flag = 0 AND (username <> '_reserve_user_external')' at line 1 ### The error may exist in org/jeecg/modules/system/mapper/SysUserMapper.java (best guess) ### The error may involve defaultParameterMap ### The error occurred while setting parameters ### SQL: SELECT COUNT() FROM sys_user WHERE del_flag = 0 AND (username <> ?) ### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') FROM sys_user WHERE del_flag = 0 AND (username <> '_reserve_user_external')' at line 1 ; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') FROM sys_user WHERE del_flag = 0 AND (username <> '_reserve_user_external')' at line 1`

3、如果把积木报表的版本号回退到1.4.2就没有问题。
```
<!-- 积木报表 -->
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.4.2</version>
</dependency>
```

##### 错误日志&截图：
1、jeecg-boot-2.4.6项目的所有功能页面都会报如下错误，下面以【系统管理->用户管理】为例：
`### Error querying database. Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') FROM sys_user WHERE del_flag = 0 AND (username <> '_reserve_user_external')' at line 1 ### The error may exist in org/jeecg/modules/system/mapper/SysUserMapper.java (best guess) ### The error may involve defaultParameterMap ### The error occurred while setting parameters ### SQL: SELECT COUNT() FROM sys_user WHERE del_flag = 0 AND (username <> ?) ### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') FROM sys_user WHERE del_flag = 0 AND (username <> '_reserve_user_external')' at line 1 ; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') FROM sys_user WHERE del_flag = 0 AND (username <> '_reserve_user_external')' at line 1`

![image](https://user-images.githubusercontent.com/6279180/199689431-2e72dee7-8759-445c-9f02-7ae5d22da84c.png)

##### 重现步骤：
1、上面的问题描述已经清楚写了重现步骤。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
看一下mysql版本，是不是有冲突，不一致

**Comment by wfeng616** [comment]
目前MySQL的版本号8.0.27，这个版本会有冲突吗？

**Comment by wfeng616** [comment]
> 看一下mysql版本，是不是有冲突，不一致
目前MySQL的版本号8.0.27，这个版本会有冲突吗？
