### ISSUE TITLE
列较多时，ax列后的内容无法展示

### ISSUE THREAD

**Issue by TheWind-s** [jeecgboot/JimuReport#1414]
##### 版本号：
1.5.0

##### 问题描述：
在报表设计页面往右拖只能到ax列，ax列之后的看不见，可以从其他地方复制到ax列之后，设计页面看不到无法编辑

##### 错误日志&截图：
 设计页截图
![image](https://user-images.githubusercontent.com/65717507/199724314-6eb012f6-89df-497e-bc31-ffc6fc92a5ea.png)
预览页截图
![image](https://user-images.githubusercontent.com/65717507/199724653-f001a153-fac7-426c-a4ad-bb5100849aca.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
修改列索引数：
![image](https://user-images.githubusercontent.com/54099258/200247444-a5b73243-4a50-496a-9947-69ff3cb45606.png)

参考文档：http://report.jeecg.com/2302149
