### ISSUE TITLE
报表工具条行数显示不正确

### ISSUE THREAD

**Issue by ylhy** [jeecgboot/JimuReport#1415]
##### 版本号：
http://jimureport.com/官网 在线使用 显示当前版本 v1.5.4 |

##### 问题描述：
在官网在线使用中新建报表 , 无论数据集有多少条数据, 工具条中始终显示"共10条"

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/33078383/199907891-3b5b6471-c067-4d0d-b572-b0779d1e7fc0.png)

##### 重现步骤：
新建报表, 然后预览

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
这是什么数据集？把官网报表的id贴上来，我们看一下

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
