### ISSUE TITLE
excel插入1行报错

### ISSUE THREAD

**Issue by xisong1588** [jeecgboot/JimuReport#1416]
##### 版本号：

1.5.2
##### 问题描述：

插入行数据后，预览会报错
##### 错误日志&截图：
<img width="803" alt="image" src="https://user-images.githubusercontent.com/11418454/199950405-1842f5ec-691c-4cbd-9923-ed69e85ee02e.png">

For input string: "NaN"

##### 重现步骤：
插入行数据后，预览会报错

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
看一下是不是插入的一行数据有空数据处理

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
