### ISSUE TITLE
三级联动自定义下拉框选项刷新失效

### ISSUE THREAD

**Issue by overfly-panzn** [jeecgboot/JimuReport#1417]
##### 版本号：
v1.5.4

##### 问题描述：
三级联动自定义查询，（如：省份-城市-区域），省份级选择了之后，城市中选项没有刷新；必须省份第二次选择后，城市中才会出现“第一次省份选择对应的城市”；省份第三次次选择后，城市中才会出现“第二次省份选择对应的城市”；依此类推。

##### 错误日志&截图：
省份第一次选择
![image](https://user-images.githubusercontent.com/85333919/200102529-fc3d0a20-6f4a-44e3-ba3c-0425ef67a39c.png)
省份第二次选择
![image](https://user-images.githubusercontent.com/85333919/200102556-2ba82e01-904d-4a65-a104-caa90559d3ba.png)

##### 重现步骤：
三级联动自定义查询（如：省份-城市-区域），省份级选择“江苏”，城市级无选项出现（正常情况下应该出现江苏的城市）；第二次省份级选择“安徽”，城市级选项出现了江苏的城市（正常情况下应该出现安徽的城市）。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
先看一下每次接口返回的数据对吗？

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
