### ISSUE TITLE
无法连接数据库

### ISSUE THREAD

**Issue by TactfulZ** [jeecgboot/JimuReport#1418]
##### 版本号：
1.5.4

##### 问题描述：
无法连接数据库

##### 错误日志&截图：
数据库连接失败：Could not connect to address=(host=127.0.0.1)(port=3306)(type=master) : (conn=24430314) Access denied for user 'root'@'172.17.0.1' (using password: YES) Current charset is UTF-8. If password has been set using other charset, consider using option 'passwordCharacterEncoding'

数据库连接失败：Could not connect to address=(host=127.0.0.1)(port=3306)(type=master) : (conn=24430146) Access denied for user 'root'@'172.17.0.1' (using password: YES)

![@4K_${E3KSGHIK8%OMYSWE6](https://user-images.githubusercontent.com/97019299/200170858-db51d2c4-1c8d-4989-bb11-2c13604d31f2.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 19373842811** [comment]
我也是这个问题，解决了吗楼主
