### ISSUE TITLE
能否把1.5.4的db脚本更新上

### ISSUE THREAD

**Issue by Boctopus** [jeecgboot/JimuReport#1419]
##### 版本号：
1.5.4

##### 问题描述：
能否把1.5.4的db脚本更新上

##### 错误日志&截图：
无

##### 重现步骤：
无

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by TactfulZ** [comment]
连接不上数据库的原因是因为脚本没更新吗

**Comment by lvdandan16** [comment]
1.5.4没有新增脚本
所有升级SQL脚本请查看官网：http://jimureport.com/doc/log
