### ISSUE TITLE
插入图片报错

### ISSUE THREAD

**Issue by wang727179528** [jeecgboot/JimuReport#1420]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/48749289/200213859-ea06d2e0-c33f-4ca7-b4e2-5ea3f65e0e67.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
报什么错？

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
