### ISSUE TITLE
分组排序不对

### ISSUE THREAD

**Issue by yangyimin-wq** [jeecgboot/JimuReport#1421]
##### 版本号：

1.5.4
##### 问题描述：

分组排序顺序不对
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/59437168/200251134-4d81da3d-7845-4594-b1ef-5162d7a959f8.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
使用默认排序即可，中文不支持排序
