### ISSUE TITLE
边框不一致，合并单元格对齐一直居中

### ISSUE THREAD

**Issue by lyswco** [jeecgboot/JimuReport#1422]
##### 版本号：
1.5.4

##### 问题描述：
1. 表格外的内容没设置边框，也会有边框出现；
2. 表格内个别单元格不设置边框，但是导出excel还是有边框；
3.  合并单元格内容设置了左对齐，上对齐，导出excel结果都是居中对齐；
4. 合并单元格内有多行内容，网页结果显示会重叠；

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/17328717/200330916-ba2552e0-cee5-4db5-9c02-d57dd7c17b12.png)
![image](https://user-images.githubusercontent.com/17328717/200331247-f4286c9e-7ca3-41e1-8d18-5185655abfca.png)
![image](https://user-images.githubusercontent.com/17328717/200331650-788ac11e-ba47-46ab-a632-56229c60cf58.png)
![image](https://user-images.githubusercontent.com/17328717/200332194-3a9449d3-90bb-4641-8d7f-4c3330f88ebf.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
问题1、2：只要表格有内容，导出excel时会自动添加边框，问题1表格外的内容没设置边框，可能是空字符串直接删除整行或整例即可
问题3：导出excel默认为居中
问题4：设置自动换行试一下
