### ISSUE TITLE
导出excel，设置了export-excel-pattern: primary，但是导出的excel设置的样式没起作用

### ISSUE THREAD

**Issue by wangyh198910** [jeecgboot/JimuReport#1424]
##### 版本号：
1.5.4

##### 问题描述：
代码中设置了导出excel为精致模式，但是导出来的excel样式全都丢失了

##### 错误日志&截图：
代码yml配置
<img width="485" alt="image" src="https://user-images.githubusercontent.com/21198489/200535330-d3660472-8c91-4037-a131-167c85228d94.png">
报表样式设置
<img width="688" alt="image" src="https://user-images.githubusercontent.com/21198489/200535424-90b28d0a-425e-4f80-9123-91f6e843bc4e.png">
导出的excel样式
<img width="519" alt="image" src="https://user-images.githubusercontent.com/21198489/200535532-8bef6266-df3f-464b-89e3-c68dd934e042.png">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
1.5.0版本以后，excel不再导出样式
