### ISSUE TITLE
打印设计模板，如何调整背景图位置及大小？

### ISSUE THREAD

**Issue by kanenhan** [jeecgboot/JimuReport#1425]
##### 版本号：
1.5.4

##### 问题描述：
打印设计模板，设置完背景图后，如何删除以及调整背景图位置？

##### 错误日志&截图：
找不到从哪儿里可以调整背景图

##### 重现步骤：
新建空设计模板
上传图片并设置为背景图
如何调整背景图位置及大小

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
再点击一次背景设置，可设置图片大小，取消背景设置
