### ISSUE TITLE
Excel导出执行两次查询sql

### ISSUE THREAD

**Issue by speckle23** [jeecgboot/JimuReport#1426]
##### 版本号：
1.5.4

##### 问题描述：
excle导出如果是分页会执行两次sql查询,造成效率缓慢，有什么办法设置只执行一次查询sql吗？毕竟excle导出是要导出所有符合查询条件的所有数据的

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
