### ISSUE TITLE
是否可以从SQL数据集中取数据作为下拉查询条件

### ISSUE THREAD

**Issue by su-qiu** [jeecgboot/JimuReport#1431]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
在报表字段明细中，直接设置查询条件，显示的下拉框即为数据集中的数据

**Comment by su-qiu** [comment]
> 在报表字段明细中，直接设置查询条件，显示的下拉框即为数据集中的数据
想用其他数据集作为下拉数据源可行吗
