### ISSUE TITLE
积木报表：打印模板->打印设置->打印回调函数：可以追加自定义参数吗？

### ISSUE THREAD

**Issue by wfeng616** [jeecgboot/JimuReport#1432]
##### 版本号：
1.5.4

##### 问题描述：
1、如下图所示：打印设置的回调函数可以追加自定义参数吗？
![image](https://user-images.githubusercontent.com/6279180/201316669-6cdfad62-861c-4dc6-9e3e-76fce419865f.png)

p1是传给打印模板的参数。
![image](https://user-images.githubusercontent.com/6279180/201317145-9ba73945-6312-415d-b88b-3407e14f4465.png)

##### 错误日志&截图：
参见问题描述。

##### 重现步骤：
参见问题描述。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持

**Comment by liyang1987jay** [comment]
我这个回调为啥不进入方法 呢
