### ISSUE TITLE
如果0则百分比格式化为空

### ISSUE THREAD

**Issue by dragonzoebai** [jeecgboot/JimuReport#1435]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/5774016/201621630-b901472d-9245-4e8f-865f-76ee2f9b8348.png)
![image](https://user-images.githubusercontent.com/5774016/201621726-38c0323e-454d-4198-b5c2-4f1d5580e207.png)
![image](https://user-images.githubusercontent.com/5774016/201621681-8073f959-ddb3-47e9-9fde-eec1149cc8ef.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
目前设计是这样的，0%不显示
