### ISSUE TITLE
动态分组报表，并发请求数据错乱

### ISSUE THREAD

**Issue by Seanchen201907** [jeecgboot/JimuReport#1436]
##### 版本号：
1.5.4

##### 问题描述：
报表显示数据错乱

##### 错误日志&截图：
报表设置方式如下图，这种设计报表又多个类似的
![image](https://user-images.githubusercontent.com/53468224/201807462-4fc87db7-73c0-4d5c-acd0-0d3d5cf12f4d.png)

##### 重现步骤：
1.设置了2个报表都(A,B)是动态分分组
2.同时请求2个报表的数据
3.**A报表的内容,标题，会变成B报表的内容和标题**
4.如果是单独请求不是同时请求，则A表和B表都能正常显示。怀疑是用了同一变量，但是线程不安全造成报表数据是同一个

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
一个报表中只支持有一个横向分组

**Comment by Seanchen201907** [comment]
> 
1个横向分组的限制场景太多了，很多报表都做不了，我尝试过了，当有多个横向分组的时候功能其实可以实现的，只是存在并发的问题，建议你们收录下这个问题，这样用户会更多
