### ISSUE TITLE
报表导出的效率很差

### ISSUE THREAD

**Issue by Seanchen201907** [jeecgboot/JimuReport#1437]
##### 版本号：
1.5.4

##### 问题描述：
在单元格较多的情况下，导出的效率很差

##### 错误日志&截图：
![微信截图_20221115100238](https://user-images.githubusercontent.com/53468224/201808309-43e96489-9c29-4a99-8275-d7f353a39d2c.png)

##### 重现步骤：
表头是动态的，格式如上面截图所示，当列数有300列的时候，导出EXCEL的时间大约为5分钟

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by zhangdaiscott** [comment]
升级到最新版，已经做了优化
