### ISSUE TITLE
超链接出现的问题:报表钻取

### ISSUE THREAD

**Issue by ZHANGzf75** [jeecgboot/JimuReport#1440]
##### 版本号：
1.5

##### 问题描述：
你好，我想问一下使用超链接报表钻去时，当前需要两个条件，1为当前地区的code值 2为当前地区对应的数据，使用超链接时会将这两个条件传值查询，但是 当条件2位相当时 code值需要的是不一致的但是他会传当前的第一个值，比如下图： 点击杭州市中的已书审数他会根据杭州的区划code和当前已书审数对应的值进行查询，但是如果需要点击温州市相应的数据时，当前已书审数值相同，就会传杭州的code值， 当点击宁波相同的数据时因为已书审数不相同，会传宁波的区划code值，这样相同数据时传的都是一致的code值
这个是有问题的吧，还是我那里出现了错误呢？ 可以麻烦您解答一下吗？ 我看开发文档中是没有这样的样例的
##### 错误日志&截图：
当前是设置的超链接：
![image](https://user-images.githubusercontent.com/115912095/201885872-f63cc44a-1e47-4b62-9bcd-7a56fef851d0.png)

##### 重现步骤：
![L QTM9DBJZAQ4N(EJ`66EE](https://user-images.githubusercontent.com/115912095/201887521-c2eb9fc5-d90e-46e5-a9f4-df5353fb015e.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by caiguanlin** [comment]
之前有遇到过，你试一下换成我这种方式看看行不行
![image](https://github.com/jeecgboot/JimuReport/assets/143568162/7d6773e5-73e8-4f8d-92d3-c5fd26e154f3)

**Comment by 1298191366** [comment]
已修复，待新版本发布。分组暂不支持
