### ISSUE TITLE
sql语句不支持union查询，建议优化

### ISSUE THREAD

**Issue by wuhonglin520** [jeecgboot/JimuReport#1442]
##### 错误日志&截图：
![1668587723788](https://user-images.githubusercontent.com/34824958/202130443-1539e50e-d829-4486-add7-a2c12b39d407.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by fhyxz001** [comment]
你好，我也是积木报表的使用者，我用的是1.5.2版本，请问您有遇到过提示函数参数替换，然后一直无法操作的问题吗

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/205222999-804b6dd7-98cd-4fba-94d1-7cf84bd52153.png)
未复现
