### ISSUE TITLE
横向扩展表头显示不正常了，之前还好好的

### ISSUE THREAD

**Issue by wuhonglin520** [jeecgboot/JimuReport#1443]
##### 问题描述：1.横向扩展表头显示不正常了，之前还好好的
2还有上次我提的横向扩展表头上面放动态数据报错，目前还没有解决。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/34824958/202132154-0c941ff4-f87b-4010-9e88-d95b84018910.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
问题1：导出报表配置及数据，我们复现一下
问题2：不支持
