### ISSUE TITLE
日报表日期错误

### ISSUE THREAD

**Issue by davidxie-star** [jeecgboot/JimuReport#1444]
##### 版本号：
1.5.4

##### 问题描述：
简单日报表，不如8号的，应该从0点-23点，但报表会出现9号的0点

##### 错误日志&截图：
![QQ截图20221116154331](https://user-images.githubusercontent.com/65750678/202118519-870ace6a-3be0-4eec-817e-e1d420a3bd09.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws
