### ISSUE TITLE
当没有数据时，有没有办法不显示某个数据块

### ISSUE THREAD

**Issue by qinfuji** [jeecgboot/JimuReport#1445]
##### 版本号：
1.5.0-bate

##### 问题描述：
当没有数据时，有没有办法不显示某个数据块

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/6016350/202608614-d4f4779a-de53-4e15-a259-f2650e7ab6ea.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
