### ISSUE TITLE
请问如何实现 横向柱状图?

### ISSUE THREAD

**Issue by luxiaojie** [jeecgboot/JimuReport#1446]
##### 版本号：
1.5.4

##### 问题描述：
请问如何实现 横向柱状图?
在示例模板里面有横向柱状图，但是在自己插入图表时只有纵向柱状图，请问如何插入横向柱状图呢？

##### 错误日志&截图：
![ETK6RDU8 DA44%C)9VOF9Q7](https://user-images.githubusercontent.com/1215314/202644695-5771025f-efa6-498a-b7e6-88e0fa3837fc.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
