### ISSUE TITLE
设置分版后页面遮挡

### ISSUE THREAD

**Issue by 2524956744** [jeecgboot/JimuReport#1447]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/56547165/202665431-80765a50-cee9-422a-9659-7de2e8f172e2.png)
![image](https://user-images.githubusercontent.com/56547165/202665474-513af6af-c91d-42b1-9f70-031aa5ca03e5.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID; 753506001105539072
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by 2524956744** [comment]
下个版本是否能解决

**Comment by zhangdaiscott** [comment]
分版功能不是循环块，分版是针对两个并排的报表，每个报表单独循环展示数据
