### ISSUE TITLE
编辑了内容，突然预览打开不了了，保错提示null

### ISSUE THREAD

**Issue by xisong1588** [jeecgboot/JimuReport#1449]
##### 版本号：
v1.5.4

##### 问题描述：
编辑了内容，突然预览打开不了了，保错提示null

##### 错误日志&截图：

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/11418454/202907958-609d1dae-05bf-4762-9a1c-8c71a429eee4.png">

##### 重现步骤：
编辑了内容后无法预览

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
关闭，重新打开试试
