### ISSUE TITLE
对交叉报表(横纵方向都扩展的报表)支持不友好

### ISSUE THREAD

**Issue by 17134934** [jeecgboot/JimuReport#145]
##### 版本号：
1.2.0

##### 问题描述：
设置横向纵向都能扩展的报表，预览时样式飞掉

##### 截图&代码：

![image](https://user-images.githubusercontent.com/81405104/112591736-c7235f00-8e3f-11eb-9d4e-dd37a5cc6304.png)
![image](https://user-images.githubusercontent.com/81405104/112591815-e91ce180-8e3f-11eb-914e-a7590e3568ef.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
报表分组后续会加大力度优化和改进

**Comment by zhangdaiscott** [comment]
暂不支持功能归集 #138

**Comment by zhangdaiscott** [comment]
样式飞了是什么意思？标题丢失吗

升级到版本1.3.63-beta , 要[配置私服](http://report.jeecg.com/2195924) ，看是否解决，无回复三天内关闭

```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.63-beta</version>
</dependency>
```
