### ISSUE TITLE
Excel导出后数字为0的表格显示类型不正确

### ISSUE THREAD

**Issue by KuXinZXT** [jeecgboot/JimuReport#1452]
##### 问题描述：
Excel导出后数字为0的表格显示类型不正确

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/48540143/203279104-4acf8fd5-ce41-4430-91a2-60f6d8a7e07f.png)

##### 重现步骤：
正常报表导出表格就可以复现

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
