### ISSUE TITLE
升级版本后手写分页失效

### ISSUE THREAD

**Issue by jujubetree** [jeecgboot/JimuReport#1453]
##### 版本号：
1.5.4

##### 问题描述：
1.3.7升级到1.5.4后，url后拼接'&pageSize=1'无效
url：http://localhost:8080/jeecg-boot/jmreport/view/752450087729451008?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjkxMjk4OTMsInVzZXJuYW1lIjoiYWRtaW4ifQ.M7LWKyeaXaY8tLwB4-qPNh5RGhUTHSanmYQGyVefLgc&pageSize=1
##### 错误日志&截图：
![微信截图_20221122232822](https://user-images.githubusercontent.com/49394098/203354035-d88c5075-9f4c-42b6-8337-986cb2e8003b.png)

![微信截图_20221122232831](https://user-images.githubusercontent.com/49394098/203354041-e7bb682f-5521-4d5e-aa59-1f4ef788195c.png)
第二张截图的访问没有携带参数
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by lsqGitHub716** [comment]
已修改
