### ISSUE TITLE
excel导出行高异常问题

### ISSUE THREAD

**Issue by sparrow10211** [jeecgboot/JimuReport#1456]
##### 错误日志&截图：
![9783a188a1626c2b0fd4483c2fd3d1d](https://user-images.githubusercontent.com/61782327/203486278-e46c1a59-5f44-427e-a5c9-d68539800bdc.png)

##### 重现步骤：
1、设置门店、账户类型为纵向分组
2、产品系列为横向分组
3、营业额为动态属性
4、导出excel

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by lsqGitHub716** [comment]
请在线上提供一个报表示例并提供ID给我们，方便复现问题
