### ISSUE TITLE
SQL数据集中的动态参数不起作用

### ISSUE THREAD

**Issue by fistlove159** [jeecgboot/JimuReport#1457]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/34266161/203487332-a0779f91-e983-4ddf-91a3-9514f7f24690.png)
![image](https://user-images.githubusercontent.com/34266161/203487458-b73d9472-83e9-432c-adef-69b27a204396.png)
![image](https://user-images.githubusercontent.com/34266161/203487602-51d10c05-c725-435b-a48b-45021a9e00ae.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ldd

**Comment by lvdandan16** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/54099258/543371df-a9f1-463b-860a-d8f6793fc24a)
未复现此问题，如果还有问题，可升级最新版试一下
