### ISSUE TITLE
报表中的图片地址访问时，跨域的问题如何解决？

### ISSUE THREAD

**Issue by qbsoft** [jeecgboot/JimuReport#1458]
##### 版本号：
1.5.4

##### 问题描述：
打印报表中需要显示javaBean返回的另一个系统上的存储的图片地址，但目前遇到了跨域访问的错误。
图片url放在浏览器里是可以预览出来的，但是放在积木报表里作为图片类型后，无法显示。

##### 错误日志&截图：
![5235755488e19902b1d1a172a771d67](https://user-images.githubusercontent.com/32183596/203512086-5c13bc22-351d-421c-ac20-9753fbe06de4.jpg)

##### 重现步骤：
![image](https://user-images.githubusercontent.com/32183596/203512854-8d16c24b-1313-416c-b6f2-1d9e37b1d85a.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
你自己的项目需要解决跨域问题
