### ISSUE TITLE
报表每页显示行数能否固定

### ISSUE THREAD

**Issue by songyongxiang** [jeecgboot/JimuReport#1460]
##### 问题描述：
上面一页显示9行，下面一页显示10行，能否固定行号，每页显示固定行数
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/47773068/203900358-e77c996c-af67-4530-9a84-445a70111a80.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
有自动换行情况下，是根据显示内容来的，固定不了
