### ISSUE TITLE
报表预览支持分页打印固定行数，但打印不支持

### ISSUE THREAD

**Issue by elanzyl** [jeecgboot/JimuReport#1461]
##### 版本号：
v1.5.4

##### 问题描述：
在针对针式打印机打印多联纸，每页能打印的行数有限，希望能够支持分页打印，每页打印固定行数。
当前情况是预览的时候能按需求预览，但调用打印功能时重新请求了接口，将所有数据都加载。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/49643288/203912173-212e8341-d3ad-4228-b20f-55f1ae8ffca6.png)
![image](https://user-images.githubusercontent.com/49643288/203912213-8422a813-9cff-44ba-984c-08107ebd056f.png)
![image](https://user-images.githubusercontent.com/49643288/203912249-6fee13fd-314b-486c-879d-a5bb5d1df782.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
打印是打印的全部，不支持固定行数
