### ISSUE TITLE
报表设计中，单元格右键菜单没有背景设置选项

### ISSUE THREAD

**Issue by ko6** [jeecgboot/JimuReport#1463]
##### 版本号：

1.5.4
##### 问题描述：

报表设计中，没有背景设置选项
##### 错误日志&截图：
自己部署的离线版本，官方自己的在线版本中均未找到此功能。
![image](https://user-images.githubusercontent.com/12150370/204068985-c99ae654-0c5b-4941-bc8e-ae4ce4eb503c.png)

官方自己的图片教程、视频教程中均有此功能。
![image](https://user-images.githubusercontent.com/12150370/204069008-011fa429-6ddb-4133-92c0-9a050d291b40.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/205230773-2b315604-da12-4b3b-aec0-4b0009ea63ef.png)
滚动条下拉
