### ISSUE TITLE
引入大屏开发时，新建大屏出线报错

### ISSUE THREAD

**Issue by 1319400800** [jeecgboot/JimuReport#1464]
##### 版本号：
jeecg-boot 2.3.0
jimureport-spring-boot-starter：1.5.4

##### 问题描述：
使用的时jeecg-boot集成的方式，打开/jmreport/list报表设计页面点击新建图形报表，在新的tag页面直接报错。

##### 错误日志&截图：
错误信息：freemarker.core.InvalidReferenceException: The following has evaluated to null or missing: ==> reportConfig [in template "jmreport/desreport/index.ftl" at line 13, column 33] ---- Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)?? ---- ---- FTL stack trace ("~" means nesting-related): - Failed at: ${reportConfig} [in template "jmreport/desreport/index.ftl" at line 13, column 31] ----
##### 重现步骤：
1访问：/jmreport/list
2选择左侧图形报表-》点击新建报表

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
fastjson版本不一致，改成一致的就可以了
