### ISSUE TITLE
数据报表查询条件设置默认查询条件(首次查询无数据)翻页功能不能用

### ISSUE THREAD

**Issue by wassheima** [jeecgboot/JimuReport#1465]
版本号：1.5.2
问题描述：
数据报表查询条件设置默认查询条件，**报表设计用的是sql**，如果首次查询没有数据，后续改用其他条件查询出数据后翻页功能不能用

错误日志&截图：
![image](https://user-images.githubusercontent.com/114221186/204179152-6e14f753-0fd4-4155-8d55-efcc0ca6f30f.png)

![image](https://user-images.githubusercontent.com/114221186/204179248-e9890623-be76-4a71-a184-d6ce5cc85c45.png)

重现步骤：
1、根据默认条件进行预览，没有数据
2、换另一个条件进行查询，有数据，此时翻页功能不能用

**Comment by lvdandan16** [comment]
升级1.5.5版本试一下
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.5.5</version>
</dependency>
```
