### ISSUE TITLE
多行文本如何设置行间距和字符间距

### ISSUE THREAD

**Issue by Kinspiration** [jeecgboot/JimuReport#1466]
##### 问题描述：

请问一个问题，我们有一段多行文本，想设置行间距，但是怎么设置好像都不起作用，能不能给说下具体的方法，非常感谢。
##### 错误日志&截图：
![ce5438e6ed5c1d2b808192bb15f76c4](https://user-images.githubusercontent.com/102337044/204217363-2481f96d-94fe-40dd-8f9d-0dd8327f9c83.png)

##### 重现步骤：
在报表中显示多行文本到一个格子里，

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
行间距不支持设置
