### ISSUE TITLE
报表设计器中数据列超过50列无法正常使用

### ISSUE THREAD

**Issue by duguike** [jeecgboot/JimuReport#1467]
##### 错误日志&截图：
![j1](https://user-images.githubusercontent.com/13192435/204248568-1a4c0464-c5ce-46a0-8584-5ba1a682157a.jpg)
![j2](https://user-images.githubusercontent.com/13192435/204248600-819af3a2-86e3-4d0c-a838-9497c84ac795.jpg)
![j3](https://user-images.githubusercontent.com/13192435/204248624-6636e015-ade3-4b2d-b8d6-805344c8aa24.png)

##### 重现步骤：
1、创建报表，添加大于50列信息
2、保存操作，提示保存成功
3、刷新当前设计页或者关闭重新进入，发现只会显示50列

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考常见问题34：http://report.jeecg.com/2087464
