### ISSUE TITLE
4联打印的时候，文字模糊

### ISSUE THREAD

**Issue by jacksonhou** [jeecgboot/JimuReport#1468]
##### 版本号：
<groupId>org.jeecgframework.jimureport</groupId>
<artifactId>jimureport-spring-boot-starter</artifactId>
<version>1.5.4</version>

##### 问题描述：
4联打印，文字模糊

##### 错误日志&截图：
![1669630399503](https://user-images.githubusercontent.com/4811022/204251943-9d239745-f503-4667-80e3-89800252a275.png)

##### 重现步骤：
4联打印的时候，文字模糊，导出excel打印没有问题，直接用A4纸打印也没问题

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
归集：#138
