### ISSUE TITLE
mongodb查询数据不全

### ISSUE THREAD

**Issue by ziyuliu1125900757** [jeecgboot/JimuReport#1470]
版本号：1.5.4

问题描述：
设置数据源来自mongodb时候，通过查询语句查询，实际应该大于101条数据，可是最后显示只有101条数据

错误日志&截图：

重现步骤：

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by Yuguangao** [comment]
请问你是如何连接mongodb的。 我连接数据库成功，但是不显示数据表

**Comment by lvdandan16** [comment]
@Yuguangao @ayururutia mongodb是nosql数据库，不显示数据库表直接写sql就可以
