### ISSUE TITLE
报表图片拉伸变形

### ISSUE THREAD

**Issue by TonyWang8904** [jeecgboot/JimuReport#1471]
##### 版本号：
1.5.4

##### 问题描述：
报表图片拉伸变形

##### 错误日志&截图：
<img width="104" alt="屏幕截图 2022-11-29 145245" src="https://user-images.githubusercontent.com/12045700/204459637-b6eebe99-3414-46cf-a470-ec30c8510640.png">

##### 重现步骤：
设置单元格属性为图片，图片为完整http地址，如http://ip:port/a.png这种
<img width="207" alt="屏幕截图 2022-11-29 145311" src="https://user-images.githubusercontent.com/12045700/204459667-6947b3e6-1297-471d-a46c-c89e0e540e3e.png">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
图片大小跟随单元格大小，也可右侧设置图片大小

**Comment by lvdandan16** [comment]
图片大小跟随单元格大小，也可右侧设置图片大小

**Comment by TonyWang8904** [comment]
> 图片大小跟随单元格大小，也可右侧设置图片大小

但是报表中图片不确定宽高比，可能会出现一列中既有横图也有竖图，无法做到自适应吗？
