### ISSUE TITLE
横向动态列分组，后统计分组内某一列数据总和

### ISSUE THREAD

**Issue by 775013453** [jeecgboot/JimuReport#1472]
##### 问题描述：
设计了横向动态列分组，需要横向统计分组内的某一列的的所有数据总和。
例子：按照商品分组后，每组商品有数量、金额，在横向分组末尾添加二列统计商品的总数量、商品的总金额

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
横向分组后合计暂不支持
