### ISSUE TITLE
主子表如何批量打印

### ISSUE THREAD

**Issue by liyang1987jay** [jeecgboot/JimuReport#1475]
##### 版本号：
1.5.4

##### 问题描述：

![image](https://user-images.githubusercontent.com/4651483/204547959-0322e6bb-85ac-4c19-9802-12ac9dc30ce5.png)
这种主子表，如何实现批量打印呢
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持

**Comment by No996ICU** [comment]
也遇到了同样的问题，如果不支持主子表的批量打印，类似的功能可怎么样来实现？
