### ISSUE TITLE
自定义横向分组数据超过8条时报错

### ISSUE THREAD

**Issue by zwdgit** [jeecgboot/JimuReport#1477]
##### 版本号：
1.5.4

##### 问题描述：
同样格式的数据，当数据量超过8条时会报错

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/28926324/204731160-10c16a2f-9142-49b2-8b75-0e7bf6af38bd.png)

##### 重现步骤：
报表配置：
[report-export-mysql.zip](https://github.com/jeecgboot/JimuReport/files/10120517/report-export-mysql.zip)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
数据表及数据也一块导出来

**Comment by zwdgit** [comment]
> 数据表及数据也一块导出来

[dcs_report_rhk_2.zip](https://github.com/jeecgboot/JimuReport/files/10138820/dcs_report_rhk_2.zip)

查 2022-11-29 的数据可以复现

**Comment by lvdandan16** [comment]
收录 ty

**Comment by lsqGitHub716** [comment]
已修改
