### ISSUE TITLE
报表SQL解析时无故报错

### ISSUE THREAD

**Issue by amwang6666** [jeecgboot/JimuReport#1479]
##### 错误日志&截图：
![1669819932598](https://user-images.githubusercontent.com/119473615/204829449-d91f81ee-7ddb-4169-a770-52fbf94c4882.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
SQL贴出来
