### ISSUE TITLE
打印设计中二维码打印不显示的问题

### ISSUE THREAD

**Issue by nebulae3971** [jeecgboot/JimuReport#1480]
##### 问题描述：
当采用单元格，拖字段，类型选择 二维码，通过html打印，不显示二维码。通过canvas打印可以。

当直接选二维码控件，放置单元格式，显示二维码，但不支持固定表头。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
未复现此问题，可在官网上做个示例，我们看一下
