### ISSUE TITLE
API数据集数据量大时列表无法显示数据

### ISSUE THREAD

**Issue by mhd0502** [jeecgboot/JimuReport#1481]
##### 版本号：
1.4.4-beta

##### 问题描述：
使用API数据集时数据量大的时候列表以及图标无数据

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级最新版本试一下
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.5.5</version>
</dependency>
```
