### ISSUE TITLE
导入报表sql，界面没有显示，控制台提示 json解析错误

### ISSUE THREAD

**Issue by catlvsuger** [jeecgboot/JimuReport#1482]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/39261781/204955897-0900ca8b-c204-4c87-a20d-ce2d071fcd2b.png)
![image](https://user-images.githubusercontent.com/39261781/204956382-72c8fdcc-35aa-4efa-873c-b23651936335.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Lory996** [comment]
> ##### 版本号：1.5.0
> ##### 问题描述：导入报表sql，界面没有显示,F12查看提示报错 json解析失败， 把sql中的 \n 全部删除，重新导入，界面可以显示
> ##### 错误日志&截图：
> ![image](https://user-images.githubusercontent.com/39261781/204955897-0900ca8b-c204-4c87-a20d-ce2d071fcd2b.png) ![image](https://user-images.githubusercontent.com/39261781/204956382-72c8fdcc-35aa-4efa-873c-b23651936335.png)
> 
> ##### 重现步骤：设计界面时添加换行
> #### 友情提示（为了提高issue处理效率）：
> * 积木报表是一款免费报表产品，功能免费源码不开放;
> * 未按格式要求发帖，会被直接删掉;
> * 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
> * 针对不好重现的问题，请录制操作视频或详细的重现步骤；

导出报表配置：对于换行符没有再做转义替换处理，执行sql的时候\n 需要替换为 \\n

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
升级到最新版试试

**Comment by lvdandan16** [comment]
\n 已处理  下个版本升级
