### ISSUE TITLE
选择单元格边框线粗细时出现乱码

### ISSUE THREAD

**Issue by amwang6666** [jeecgboot/JimuReport#1483]
##### 错误日志&截图：
![1669868244706](https://user-images.githubusercontent.com/119473615/204964681-297f3f1d-3a27-4941-84c9-d5876f5073b9.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by KateJun** [comment]
158版  还存在这个bug

**Comment by zhangdaiscott** [comment]
已处理，下个版本
