### ISSUE TITLE
api数据集，重新解析时最后一列 参数配置 的数据会被清除掉

### ISSUE THREAD

**Issue by catlvsuger** [jeecgboot/JimuReport#1485]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/39261781/205196420-757ccab3-02c9-4339-b8df-f730a6c5b18a.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by lvdandan16** [comment]
更新新版本试一下

**Comment by 1298191366** [comment]
已修复，待新版本发布
