### ISSUE TITLE
自行部署JimuReport没有用户登录验证？

### ISSUE THREAD

**Issue by lcb0913** [jeecgboot/JimuReport#1486]
##### 问题描述：按说明部署JimuReport，输入后台连接直接进入后台设计页面，没登录验证吗？用户访问报表是在同一个后台页面吗？也不用登录验证吗？
http://localhost:8085/jmreport/list

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/119642824/205215398-3dbfd860-f488-4027-89de-c8631394f2b3.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
默认没有登录，需要自己扩展
参考文档：http://report.jeecg.com/2208864
