### ISSUE TITLE
打成war包tomcat里访问404

### ISSUE THREAD

**Issue by ieayoio** [jeecgboot/JimuReport#1487]
##### 版本号：
jimureport-spring-boot-starter:1.5.4
springboot:2.6.11
Tomcat：9.0.69

##### 问题描述：
打成war包，放在tomcat里访问404，找了常见问题、官方文档和issues都没有解决

##### 错误日志&截图：
tomcat启动正常，无错误日志

##### 重现步骤：
1. 按照官方[springboot集成积木报表](http://report.jeecg.com/2391081)教程建立一个demo项目`jimu-demo`
2. 做了一些修改，maven finalName改为jmreport，jimureport-spring-boot-starter改为1.5.4，packaging改为war
3. maven打包jmreport.war，放入tomcat webapps目录，启动tomcat
4. 尝试可能的访问方式均显示404，例如：
```
http://127.0.0.1:8080/jmreport/
http://127.0.0.1:8080/jmreport/list
http://127.0.0.1:8080/jmreport/jmreport/list
```

<img width="902" alt="image" src="https://user-images.githubusercontent.com/7099604/205257898-69b15a6f-25e0-416a-ade8-c840030a5f17.png">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by ieayoio** [comment]
尝试增加`customPrePath`，依然显示404
```
jeecg :
  jmreport:
    customPrePath: /jmreport
```

**Comment by ieayoio** [comment]
已解决

**Comment by liqfj** [comment]
请问该问题如何解决的哇，感谢
