### ISSUE TITLE
API数据集不支持带有转义字符的数据

### ISSUE THREAD

**Issue by m1xui** [jeecgboot/JimuReport#1488]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/57282479/205429199-256f87e3-835a-4688-8150-92d4a5c4aa1d.png)

##### 重现步骤：
数据集：
![image](https://user-images.githubusercontent.com/57282479/205429104-667ca705-47ed-4a43-80fe-544ce64633ff.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
