### ISSUE TITLE
日期范围查询设置默认日期，传递到后端的参数date_end不是正常的字符串

### ISSUE THREAD

**Issue by No996ICU** [jeecgboot/JimuReport#1489]
##### 错误日志&截图：
前端通过js增强设置的默认值
![image](https://user-images.githubusercontent.com/100275832/205438635-f12920dd-73da-466e-8cf0-02791f180298.png)

后端接收到的参数值
![image](https://user-images.githubusercontent.com/100275832/205438677-56ef5818-6d05-4e4a-b41e-d994f3847d83.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
你应该是js增强里面的结束时间没有格式化导致的，修改你的js增强里面写法就可以
