### ISSUE TITLE
图片大小跟随单元格大小，也可右侧设置图片大小

### ISSUE THREAD

**Issue by TonyWang8904** [jeecgboot/JimuReport#1490]
图片大小跟随单元格大小，也可右侧设置图片大小

1.图片为自定义上传，可能为横图、竖图或者方图
2.图片列为分组，因此单元格大小不固定
3.右侧未找到设置图片大小的参数，只有设置单位格的参数

_Originally posted by @lvdandan16 in https://github.com/jeecgboot/JimuReport/issues/1471#issuecomment-1334829726_

**Comment by liaozhiyang** [comment]
插入的图片可改变尺寸，通过右侧填入的图片不可更改尺寸（跟随单元的大小）。

**Comment by liaozhiyang** [comment]
功能已添加，下一版本发布
