### ISSUE TITLE
建议清理下.git中的pack，挺好的项目让.git搞的非常臃肿。

### ISSUE THREAD

**Issue by mojitoming** [jeecgboot/JimuReport#1495]
##### 错误日志&截图：
<img width="486" alt="Xnip_2022-12-06_11-10-37" src="https://user-images.githubusercontent.com/16813446/205804120-14e8df4f-bf21-4ec2-a480-4c70cc3ed9d6.png">

**Comment by zhangdaiscott** [comment]
处理了，感谢
