### ISSUE TITLE
接口返回数据解析不了

### ISSUE THREAD

**Issue by yjohh** [jeecgboot/JimuReport#1497]
##### 问题描述：

![}B Y Y2Q_6``1XM4K@LCY_L](https://user-images.githubusercontent.com/39292376/206080655-a1deb13e-ca4a-49e4-90b6-704fbdf79f3f.jpg)
按照文档的数据格式返回，积木不能解析

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/39292376/206080738-dd16836a-aa4e-4057-8ece-3a14b842520d.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
给一个我们能用的外网 api地址贴上来，我们试一下
