### ISSUE TITLE
连接mongodb数据库不显示表

### ISSUE THREAD

**Issue by Yuguangao** [jeecgboot/JimuReport#1499]
##### 版本号：
v1.5.4

##### 问题描述：
连接mongodb数据库不显示表，测试连接数据库成功，不显示数据库表

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/94172410/206115833-b4483fca-e6b5-4d4d-b6c8-688def0f4dd7.png)
![image](https://user-images.githubusercontent.com/94172410/206115873-5367d335-5fd4-4325-b86a-38173c284127.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
没这做个功能，sql解析就好使的
