### ISSUE TITLE
请问下，下个版本是否可以考虑增加打印页码的设置及显示，以及打印预览页面能否居中问题

### ISSUE THREAD

**Issue by liu421** [jeecgboot/JimuReport#1500]
##### 版本号：
1.5.4

##### 问题描述：
是否可以考虑增加打印页码的设置及显示，以及打印预览页面能否居中问题。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
归集到 #138

**Comment by lvdandan16** [comment]
打印页码已支持 需升级最新版本 参考文档：https://help.jeecg.com/jimureport/7.pagenumset.html
