### ISSUE TITLE
积木报表html打印时，图片加载不全

### ISSUE THREAD

**Issue by lhhgh** [jeecgboot/JimuReport#1504]
##### 版本号：
1.5.4

##### 问题描述：
图片是存在华为云服务器上的，报表通过url能加载出来，预览也没问题，导出pdf也没问题。
但是点击html打印时，只能加载出来一部分图片。我测试的70条数据都加载不全。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/113173621/206334874-213d4217-85f8-435d-86c8-557510555b58.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by TonyWang8904** [comment]
咨询一下，这边图片存在拉伸变形的情况吗？没变形的话能不能截图看一下你怎么设计的

**Comment by lvdandan16** [comment]
> ![image](https://user-images.githubusercontent.com/113173621/206644358-b117fbe5-5d7b-4e14-81d7-e1bf4eefa5b4.png) 图片没有变形，图片地址是sql查出来的，没有特别的操作。

![image](https://user-images.githubusercontent.com/54099258/208817763-936ebca2-33cd-48c7-a3cd-dc20e368ff0d.png)
你这个高度够吗？

**Comment by zhangdaiscott** [comment]
- 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
