### ISSUE TITLE
分组排序不对

### ISSUE THREAD

**Issue by mhd0502** [jeecgboot/JimuReport#1509]
##### 版本号：
1.4.4-beta

##### 问题描述：
只要分组自己写的排序就全乱了，分组设置里面的排序方式已经改为默认了还是不行。API数据集和SQL数据集都是这种情况。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
更新新版本试一下
