### ISSUE TITLE
自动换行导致表格行错乱

### ISSUE THREAD

**Issue by speckle23** [jeecgboot/JimuReport#1510]
##### 版本号：
1.5.4

##### 问题描述：
表格设置自动换行，操作人员反映有出现行错乱现象，我自己本地是没有复现

##### 错误日志&截图：
![1670548482147](https://user-images.githubusercontent.com/54102334/206600984-6577505b-681f-4494-b957-1bdaf69f5477.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by liaozhiyang** [comment]
有重现的步骤吗？或者预览页面的地址？目前这样不好定位
