### ISSUE TITLE
新建设计报表页面，列有限制

### ISSUE THREAD

**Issue by Yuguangao** [jeecgboot/JimuReport#1511]
##### 版本号：

v1.5.5
##### 问题描述：
我需要设计的报表有60多列，而积木报表好像只支持大约50列，当我增加列设计保存后，可以正常预览。退出设计页面再进去，50列后面的不见了，导致50列以后不能二次编辑。
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/94172410/206612506-72d59f1d-ada0-4a86-9074-ccd90bd9d234.png)
如图所示，当我想二次编辑时，打开报表发现只显示到AX列，后面的列都不能操作了。而预览是正常的。
请问我如何才能操作50列以后的报表？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/jimureport/qa.html
34
