### ISSUE TITLE
模板设置无边框，导出Excel还是有边框

### ISSUE THREAD

**Issue by isxuduan** [jeecgboot/JimuReport#1512]
##### 问题描述：
《模板设置无边框，导出Excel还是有边框》预览也没有问题，导出excel有多余边框

##### 错误日志&截图：
![3A0613691D1BFC3AAC8014DD56C9D43B](https://user-images.githubusercontent.com/43172780/206615614-9c55c0da-06a2-4360-a864-45e9282ca9e8.jpg)

##### 重现步骤：
设计页面是去边框的，预览界面也没有边框 ，然后导出excel就有边框
![46C4FE638041AF21B93FDB62B17CE489](https://user-images.githubusercontent.com/43172780/206615640-20b97f08-4935-4013-b81f-207afd47601c.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by wangzhiyuan0011** [comment]
此版本导出Excel没有样式,和预览效果显示不同

**Comment by KateJun** [comment]
最新版 1。5。8 还存在这个问题

**Comment by lvdandan16** [comment]
收录 zy

**Comment by lvdandan16** [comment]
已修改，下个版本发布
