### ISSUE TITLE
SQL中条件表达式不生效，保存后重新进入表达式消失

### ISSUE THREAD

**Issue by TaoYangGItHub** [jeecgboot/JimuReport#1513]
##### 版本号：
1.5.4

##### 问题描述：
SQL中条件表达式不生效，保存后重新进入消失

##### 错误日志&截图：
![图片](https://user-images.githubusercontent.com/25076129/206621244-391099c2-5451-46d4-b989-7577cf8ddaba.png)

点击确定后重新进入条件表达式消失
![图片](https://user-images.githubusercontent.com/25076129/206621306-018ff177-d1d4-4f46-933c-4d41eefd7e85.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
未复现
