### ISSUE TITLE
超链接>报表钻取或者网络报表时，传的参数在目标报表中重置时不能清空

### ISSUE THREAD

**Issue by TaoYangGItHub** [jeecgboot/JimuReport#1514]
##### 版本号：
1.5.4

##### 问题描述：
在报表中设置了报表钻取，传递参数到其它报表。但是在其它报表重置查询条件时传递的参数没有清空，导致查询结果错误

##### 错误日志&截图：
1. 参数设置
![图片](https://user-images.githubusercontent.com/25076129/206622088-1b630a01-94cd-4778-9a41-057ab5e47e5e.png)
2. 跳转
![图片](https://user-images.githubusercontent.com/25076129/206622201-fa92dd6a-e4cb-4b06-abba-81abc5565d1d.png)
3.重置目标报表参数后查询 结果没变
![图片](https://user-images.githubusercontent.com/25076129/206622266-8964f8f9-24c6-40bb-85be-8f2b9888e060.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
手动删除 url链接的参数
