### ISSUE TITLE
导出excel时图表不显示

### ISSUE THREAD

**Issue by wym16** [jeecgboot/JimuReport#1515]
##### 错误日志&截图：
预览截图
![image](https://user-images.githubusercontent.com/20144556/206673458-3d72add3-ca57-4478-aa8a-f7c4a16fc7a1.png)
导出的excel截图
![image](https://user-images.githubusercontent.com/20144556/206673627-076e8ff7-8463-414f-99f3-04e6c6389bf1.png)

##### 重现步骤：
新建报表->增加柱状图以及折线图->数据类型为api动态数据->保存->预览->导出

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
未复现。api数据源和sql数据源都已测试，升级版本到1.6.1试一下
普通导出
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/3a932f41-a726-41be-b5d3-186389e30db9)
折叠导出
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/470a01c7-37ef-4532-8901-2400ba0deb5b)

```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.6.1</version>
</dependency>
```
