### ISSUE TITLE
javabean数据源如何统计所有分页的合计

### ISSUE THREAD

**Issue by a970772150** [jeecgboot/JimuReport#1516]
##### 版本号：
1.5.0

##### 问题描述：
请教一下，javabean数据源如何统计所有分页的合计，DBSUM函数没有生效

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by zhangdaiscott** [comment]
你可以单独弄两个数据集，一个提供列表数据，一个提供合计
