### ISSUE TITLE
单元格斜线打印问题

### ISSUE THREAD

**Issue by liu421** [jeecgboot/JimuReport#1518]
##### 版本号：
1.5.6

##### 问题描述：
当使用单元格斜线后，预览正常，但打印时，第一页只显示头部，剩下的都跑到第二页去了。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/80014877/206953515-c13e4f07-e800-4827-b7ad-a4918ff64e57.png)
![image](https://user-images.githubusercontent.com/80014877/206953552-e847e277-3e5e-4faf-801d-08908282858b.png)

如果去掉单元格斜线，则是正常的
![image](https://user-images.githubusercontent.com/80014877/206953625-9662d649-3c33-4433-8cbb-ceb8c7d8ea75.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by KateJun** [comment]
只要用了斜线， 打印就是这种情况， 不知道怎么处理， 你怎么解决的？

**Comment by KateJun** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/6227218/b37eedf9-696c-43df-81b6-3d635eb33319)

**Comment by zhangdaiscott** [comment]
已经处理了，下个版本发布
