### ISSUE TITLE
表格二维码，胡乱分页bug

### ISSUE THREAD

**Issue by KaherineZXL** [jeecgboot/JimuReport#1519]
##### 版本号：
1.5.1

##### 问题描述：
table 里面的数据有二维码时，打印的数据每一行都会分页
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级新版本试试
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.5.6</version>
</dependency>
```

**Comment by KaherineZXL** [comment]
我升级到最新的版本还是一样的问题，我在官网上设计了一个，也是同样的问题

**Comment by zhangdaiscott** [comment]
已经处理了，下个版本发布
