### ISSUE TITLE
导出excel的单元格不支持背景颜色？？

### ISSUE THREAD

**Issue by yangcoolq** [jeecgboot/JimuReport#1520]
##### 版本号：

1.5.2
##### 问题描述：

导出excel的单元格不支持背景颜色
##### 错误日志&截图：

页面如下：
![图片](https://user-images.githubusercontent.com/80020311/207288300-857e9bf6-969f-43e2-b9b2-f77f19fd4a7f.png)

导出如下：
![图片](https://user-images.githubusercontent.com/80020311/207288425-9fd1d607-b242-4f46-b630-0fc4e6483be0.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级新版本1.5.6
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.5.6</version>
</dependency>
```
