### ISSUE TITLE
关于数据解析的问题

### ISSUE THREAD

**Issue by hanpeiting1996** [jeecgboot/JimuReport#1521]
##### 问题描述：
-系统写的sql，在数据库是可以看到具体信息的，但是在报表工具解析成功后，下面的报表的字段明细就无法显示。
--这个有做过类似的报表之前可以解析出来，现在把之前的再次点击一次解析也无法显示出来了
现在导入新的没法生成，以前的报表也打不开了

##### 错误日志&截图：
![1670931855772](https://user-images.githubusercontent.com/118969528/207309414-adb13336-2e75-4c67-b369-79d4e2c5f755.png)

##### 重现步骤：
![image](https://user-images.githubusercontent.com/118969528/207309949-c58cd506-d2f9-4b87-a7be-9d58644c7719.png)
![image](https://user-images.githubusercontent.com/118969528/207310026-50019975-e2a1-4ce3-9fe7-c348d7b6b21e.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
