### ISSUE TITLE
报表PDF导出

### ISSUE THREAD

**Issue by wangzhiyuan0011** [jeecgboot/JimuReport#1524]
##### 问题描述：
1. 报表导出PDF,第二页是断开的，出现空白问题
2. 报表导出PDF图片,字段有重复显示问题，每页连接处数据残缺显示不全

##### 错误日志&截图：
![A@T53M1E BW{0LCL% Z13TR](https://user-images.githubusercontent.com/106571271/207791570-b378cb41-4c94-4921-8915-d06e5a4c8488.png)
![_1(44}6KW2VHEH7WXMMM_QK](https://user-images.githubusercontent.com/106571271/207791593-7cc21c22-1e65-43e6-a5d9-100d5ddbf616.png)
![M1@MU~9WOE$Y7CHX_QY( `R](https://user-images.githubusercontent.com/106571271/207791618-d0c19409-f4a0-4a7c-9540-bd722c30d775.png)
![FROS$7@QR24IVO{($3NXNG7](https://user-images.githubusercontent.com/106571271/207791629-2e2af8c6-7e5e-4af2-9d57-7ad76d20d75a.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
导出模板配置并提供数据，或者升级版本到1.6.1尝试一下
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.6.1</version>
</dependency>
```
