### ISSUE TITLE
报表导出Excel内容显示不全问题

### ISSUE THREAD

**Issue by wangzhiyuan0011** [jeecgboot/JimuReport#1525]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/106571271/207794055-90f5fb46-973f-4dbe-ad1b-5dc4418fcdc7.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
需要手动拖动，不自适应
