### ISSUE TITLE
报表sql查询出数据了，在报表里面却不显示，同一行，两个不同表的数据，却只显示一个表的数据。？？？

### ISSUE THREAD

**Issue by 455-dIAO** [jeecgboot/JimuReport#1527]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by IsLiving** [comment]
我也遇到过相同问题，看到你也在问，给你回复下吧 
并不支持两个数据源的数据配置到同一行上，这是官方文档给出的。
![image](https://user-images.githubusercontent.com/38464696/209773882-d8314ab3-ba65-4075-97ef-c5f096ad295a.png)
可以考虑下分版能否实现：http://report.jeecg.com/2373086
