### ISSUE TITLE
希望下拉树、自定义下拉框加级联能进行搜索

### ISSUE THREAD

**Issue by LK96963** [jeecgboot/JimuReport#1531]
##### 版本号：
1.4.2

##### 问题描述：
希望下拉树、自定义下拉框加级联能进行搜索。
级联自定义下拉框数据量大了会影响使用体验，半天找不到数据。但如果不加级联，用普通的下拉框，就需要客户自己筛选匹配方式，也影响体验。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/119652440/208219453-c48cac7d-602a-4f5a-9997-c514c8920a11.png)
![image](https://user-images.githubusercontent.com/119652440/208219618-7910a98b-7489-42e5-815d-fbd6f167542e.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级新版本，通过js增强可实现 
参考文档：https://help.jeecg.com/jimureport/query/jsEnhance.html

**Comment by BO-DI** [comment]
> 自定义下拉框加级联能进行搜索。
> 级联自定义下拉框数据量大了会影响使用体验，半天找不到数据。但如果不加级联，用普通的下拉框，就

请问，下拉树的查询项动态传参怎么处理的呢？
![7d22f6fab881f84066622f78bca53df5](https://github.com/user-attachments/assets/7188e9dc-0ec0-4cb6-b098-7d08e48d4ede)
