### ISSUE TITLE
若数据库服务器重启后,预览一直提示数据源错误

### ISSUE THREAD

**Issue by Acechengui** [jeecgboot/JimuReport#1532]
##### 版本号：
1.5.6

##### 问题描述：
若数据库服务器重启后,预览一直提示数据源错误,重启jar也不好说,除非在维护数据源那里新建一个一样的数据源才行,该问题从1.5.1版本
开始一直存在该问题,1.5.1以前版本没用过不知道,望官方大大能解决
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/63096199/208336807-b2bc19c3-2f6f-4808-88f0-34ded48c9a3e.png)

##### 重现步骤：
数据库停止一会儿再重启后,再访问预览报表页

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Acechengui** [comment]
sqlserver数据库

**Comment by zhangdaiscott** [comment]
编辑下数据源就好了

**Comment by Acechengui** [comment]
处理方案倒是知道这样处理，但是这很low，很麻烦，如果本身不受数据库重启影响，能连就是能连，而不是再编辑一次~









      发自我的企业微信         

 
 
 ----------回复的邮件信息----------
 ***@***.***&gt; 于2023年8月4日(周五) 下午4:51写道:

  

 
编辑下数据源就好了
