### ISSUE TITLE
报表code字段不断增加，等复制次数达到一定次数后，code长度超过数据库字段长度，导致无法复制

### ISSUE THREAD

**Issue by xjaltlgh** [jeecgboot/JimuReport#1533]
##### 版本号：
V1.5.6

##### 问题描述：

报表code字段不断增加，等复制次数达到一定次数后，code长度超过数据库字段长度，导致无法复制

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/30921368/208346833-37ee6728-d9b9-4b8e-89dd-cfe937666a09.png)

##### 重现步骤：
复制一个报表，修改报表名称（不要包含副本字段），继续复制，直到code长度超过数据库字段长度

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws
