### ISSUE TITLE
表格中的二维码打印时会独占一页，导致分页错乱

### ISSUE THREAD

**Issue by f1628162223** [jeecgboot/JimuReport#1534]
##### 版本号：
1.5.6

##### 问题描述：
表格中的二维码打印时会独占一页，分页错乱

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/55421213/208569528-ed8df2d6-3563-4564-aa4b-8dc05b1ba695.png)
![image](https://user-images.githubusercontent.com/55421213/208569578-8db6494c-fc9d-4dba-b4a0-b934320af872.png)

##### 重现步骤：
在文档上添加一个二维码 就会出现分页错乱，二维码独占一页

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
已经处理了，下个版本发布

**Comment by xiaojiang123123** [comment]
我把版本更新到1.6.1了，为什么还是有分页错乱这个问题

**Comment by zhangdaiscott** [comment]
如果还是有请提新issue，并附带测试例子
