### ISSUE TITLE
数据集二维码循环展示，打印出现分页

### ISSUE THREAD

**Issue by KaherineZXL** [jeecgboot/JimuReport#1535]
##### 错误日志&截图：

![) 5UIM~C{G04@ %F~CWK@Z4](https://user-images.githubusercontent.com/120431879/208593741-76c225c2-2b7f-4002-9010-59d0cb1d8e52.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by liaozhiyang** [comment]
已处理，下一个版本发布
