### ISSUE TITLE
excel导出后，附件内容只有一行报错

### ISSUE THREAD

**Issue by IsLiving** [jeecgboot/JimuReport#1536]
##### 版本号：
版本 1.5.6，起初在1.4.2上发现导出excel报错，将积木升级到1.5.6，问题仍然存在

##### 问题描述：
报表导出后的excel附件，打开后只有一行报错信息。

##### 错误日志&截图：
{"success":false,"message":"操作失败，Handler dispatch failed; nested exception is java.lang.InternalError: java.lang.reflect.InvocationTargetException","code":500,"result":null,"timestamp":1671512214317}
![image](https://user-images.githubusercontent.com/38464696/208593596-47cdf510-337d-4c65-ba94-0d7f2faf15b3.png)

##### 重现步骤：
公司里有三个环境，其中一个环境有此问题，导出的都是同一张报表

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
提供数据，我们看一下

**Comment by AllenFan4141** [comment]
想请问一下 我现在本机没有问题,放到服务器上就出现同样的问题,能提供下解决办法么
