### ISSUE TITLE
行数太少，设置行数不生效

### ISSUE THREAD

**Issue by zyexplorer** [jeecgboot/JimuReport#1537]
##### 版本号：
1.4.2
##### 问题描述：
表表行数最多只有100行，太少，设置了参数不起作用。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/48943780/208602666-2f98e1ca-0402-4e73-b402-759c9938682a.png)
![image](https://user-images.githubusercontent.com/48943780/208602942-3aef5a37-b1c4-4708-86a6-91dc6341ffc4.png)

##### 重现步骤：
修改配置参数：jeecg.jmreport.row=150  重启应用，访问ip:port/jmreport/list 查看总行数

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 zy

**Comment by zhangdaiscott** [comment]
没有这个属性，这是你自我创建的吧，后期待扩展

**Comment by XuXiaoDanGao** [comment]
这个问题解决了吗

**Comment by zyexplorer** [comment]
升级之后就可以添加行了
----- 原始邮件 -----
发件人：XuXiaoDanGao ***@***.***>
收件人：jeecgboot/JimuReport ***@***.***>
抄送人：ZY ***@***.***>,  Author ***@***.***>
主题：Re:_[jeecgboot/JimuReport]_行数太少，设置行数不生效_(Issue_#1537)
日期：2023年10月07日 17点14分


这个问题解决了吗
