### ISSUE TITLE
纵向分组排序，排序方式 设置为默认，没有按照源数据进行排序

### ISSUE THREAD

**Issue by xjaltlgh** [jeecgboot/JimuReport#1539]
##### 版本号：
1.5.6

##### 问题描述：
纵向分组排序，排序方式 设置为默认，没有按照源数据进行排序

##### 错误日志&截图：
两个设置的都是默认排序
![image](https://user-images.githubusercontent.com/30921368/208856812-ff3d1f8b-83c4-4f1b-84d5-b0708e578e02.png)

1月为第一个
![image](https://user-images.githubusercontent.com/30921368/208856688-28976520-bb59-4509-8f0e-6d0a5644e66d.png)

显示时，1月为第三个，顺序与源数据不一致
![image](https://user-images.githubusercontent.com/30921368/208857269-d57b7c02-bd93-486a-b7ef-bfb3f7bfb720.png)

##### 重现步骤：

此地址为复现的样例地址
https://cloud.jimureport.com/jmreport/view/759685530215862272

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录

**Comment by zhangdaiscott** [comment]
1.6.1+版本后，会支持文本排序
https://help.jeecg.com/jimureport/group/dataSort.html
