### ISSUE TITLE
系统在ie下运行，系统无法使用

### ISSUE THREAD

**Issue by RapidHorse** [jeecgboot/JimuReport#1540]
##### 问题描述：
在IE下运行，脚本报错，界面上出现程序标签

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/6520894/209051235-10c435b9-8d8f-4ed0-9ffb-9a226df2e8fb.png)
![image](https://user-images.githubusercontent.com/6520894/209051332-5beb39fb-0cca-4cf3-83a9-090e96970f8d.png)

##### 重现步骤：
在IE7-11下运行

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
我们只兼容最新版的浏览器，不兼容老IE
