### ISSUE TITLE
设置了套打图片无法取消或替换套打图片

### ISSUE THREAD

**Issue by gitdpi** [jeecgboot/JimuReport#1541]
##### 版本号：
1.5.6

##### 问题描述：
设置了套打图片后完全找不到取消或者更换套打图片的地方

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/32302551/209077736-1e033735-e0c9-4d70-847f-8d7e53cd4acd.png)

##### 重现步骤：
插入图片 -> 设为套打图片
然后想去掉套打图片，没找到怎么操作才行

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by gitdpi** [comment]
找到了，新版本右击表格默认加了滚动条了，往下一滑就有了，之前老版本没有滚动条以为只有那行功能没有找到。

**Comment by care98** [comment]
> 找到了，新版本右击表格默认加了滚动条了，往下一滑就有了，之前老版本没有滚动条以为只有那些功能。

您好 ，请教一下如何显示垂直滚动条呢？

**Comment by care98** [comment]
> 找到了，新版本右击表格默认加了滚动条了，往下一滑就有了，之前老版本没有滚动条以为只有那些功能。

您好，请教一下，数据报表本身是没有垂直滚动条也无法 通过ctrl a 全选吗？

**Comment by gitdpi** [comment]
我说的是最新版本报表设计页面的右击菜单的滚动条，不清楚你说的什么滚动条



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月8日(周三) 上午10:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [jeecgboot/JimuReport] 设置了套打图片无法取消或替换套打图片 (Issue #1541)




  
找到了，新版本右击表格默认加了滚动条了，往下一滑就有了，之前老版本没有滚动条以为只有那些功能。
  
您好 ，请教一下如何显示垂直滚动条呢？

**Comment by care98** [comment]
> 我说的是最新版本报表设计页面的右击菜单的滚动条，不清楚你说的什么滚动条

您好我意思是这里的滚动条如图
![image](https://user-images.githubusercontent.com/46066901/223613059-731c0f50-24dc-42b7-976f-77d0c9702450.png)

横向的滚动条是有的

类似wps表格这种垂直滚动条
![image](https://user-images.githubusercontent.com/46066901/223613167-05969d90-3e8f-491e-8118-4b6e5aefa1c9.png)

**Comment by gitdpi** [comment]
鼠标中键（滚轮）点按一下表格内松开，鼠标向右边移动，就可以看见了，鼠标中键（滚轮）再点按一下表格内松开
可能这个框架的默认宽度太宽了，看不到




NULL
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月8日(星期三) 中午11:35
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 设置了套打图片无法取消或替换套打图片 (Issue #1541)





  
我说的是最新版本报表设计页面的右击菜单的滚动条，不清楚你说的什么滚动条
  
您好我意思是这里的滚动条如图
 
 
横向的滚动条是有的
 
类似wps表格这种垂直滚动条

**Comment by care98** [comment]
> 鼠标中键（滚轮）点按一下表格内松开，鼠标向右边移动，就可以看见了，鼠标中键（滚轮）再点按一下表格内松开 可能这个框架的默认宽度太宽了，看不到 

非常感谢！！！这个问题我研究了好久一直很纳闷，确实没想到是这个原因。再次感谢！！！

那个，我还想请教一个问题，关于这个积木报表它无法ctrl a 全选吗

**Comment by gitdpi** [comment]
这我就不知道了，我也不行
&nbsp;


NULL
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月8日(星期三) 中午11:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [jeecgboot/JimuReport] 设置了套打图片无法取消或替换套打图片 (Issue #1541)





  
鼠标中键（滚轮）点按一下表格内松开，鼠标向右边移动，就可以看见了，鼠标中键（滚轮）再点按一下表格内松开 可能这个框架的默认宽度太宽了，看不到
  
非常感谢！！！这个问题我研究了好久一直很纳闷，确实没想到是这个原因。再次感谢！！！
 
那个，我还想请教一个问题，关于这个积木报表它无法ctrl a 全选吗

**Comment by care98** [comment]
> 这我就不知道了，我也不行 

好的 ，非常感谢！！！
