### ISSUE TITLE
sum函数放在数据的上方时，不起作用

### ISSUE THREAD

**Issue by yimimiyi** [jeecgboot/JimuReport#1544]
##### 版本号：
1.5.6

##### 问题描述：
sum函数放在数据的上方时，不起作用，结果为0

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/21001353/209148986-7108e334-286e-40d2-a4b8-127a85ecacc9.png)

##### 重现步骤：
将sum函数放于数据上方单元格，即可重现。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
sum不支持放上边，可以使用dbsum
