### ISSUE TITLE
concat和 string.substring连用时，sql解析报错

### ISSUE THREAD

**Issue by IsLiving** [jeecgboot/JimuReport#1545]
##### 版本号：
版本 1.5.6

##### 问题描述：
当我对一个字符串进行截取并和其他内容进行拼接时，“sql解析”功能报错，具体见截图

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/38464696/209297055-4269f47b-2c09-409c-83d2-3ec55c7dbecf.png)
![image](https://user-images.githubusercontent.com/38464696/209297075-632c64ca-45c4-4670-a78b-1ea902b0264b.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
截取并和其他内容进行拼接
是什么语法？
