### ISSUE TITLE
关于报表筛选的问题

### ISSUE THREAD

**Issue by hanpeiting1996** [jeecgboot/JimuReport#1546]
##### 问题描述：
在sql写入的时候，进行了排序和人员顺序排列，但是使用报表筛选，排序的顺序就发生了变化

##### 错误日志&截图：
![1671783228415](https://user-images.githubusercontent.com/118969528/209298701-d6667e4b-eebf-4068-adca-abb614c432a2.png)
![1671783228423](https://user-images.githubusercontent.com/118969528/209298716-77c2a5ce-097f-4566-9d0a-50b52af9b824.png)

##### 重现步骤：
筛选之前顺序是教师-行政.....，筛选之后顺序就被打乱了

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
把sql贴上来，我们看一下

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
