### ISSUE TITLE
0.01数据格式设置成百分比后数据无法显示

### ISSUE THREAD

**Issue by Hunter-han611** [jeecgboot/JimuReport#1547]
##### 版本号：
1.4.3

##### 问题描述：
0.01数据格式设置成百分比后数据无法在报表中显示

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/54894974/209534503-a20103e5-dcf6-4ae9-8cbb-94fe05a54d8c.png)
![image](https://user-images.githubusercontent.com/54894974/209534545-4a96f1a4-42a8-4538-9d46-d8bc96fc759e.png)

##### 重现步骤：
计算数据时，选择数据格式为百分比时无法显示，选择数值时正常。

**Comment by Hunter-han611** [comment]
> ##### 版本号：
> 1.4.3
> 
> ##### 问题描述：
> 0.01数据格式设置成百分比后数据无法在报表中显示
> 
> ##### 错误日志&截图：
> ![image](https://user-images.githubusercontent.com/54894974/209534503-a20103e5-dcf6-4ae9-8cbb-94fe05a54d8c.png) ![image](https://user-images.githubusercontent.com/54894974/209534545-4a96f1a4-42a8-4538-9d46-d8bc96fc759e.png)
> 
> ##### 重现步骤：
> 计算数据时，选择数据格式为百分比时无法显示，选择数值时正常。

**Comment by liaozhiyang** [comment]
能提供预览页面的地址嘛？

**Comment by zhangdaiscott** [comment]
sq

**Comment by mattmok** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/28980774/b28acae1-f635-4dec-9adc-79b0c7173484)
当设置为数值是显示，但设置为百分比时，不显示数据。
![image](https://github.com/jeecgboot/JimuReport/assets/28980774/12813264-1cec-484a-8dee-ff0e1c10235a)
