### ISSUE TITLE
折线图数据显示不全

### ISSUE THREAD

**Issue by zhanghahahahahaha** [jeecgboot/JimuReport#1550]
##### 版本号：
1.5.0

##### 问题描述：
折线图，在数据源SQL通过参数对数据时间范围进行筛选，
SELECT
	ymd 日期,count(*) cnt
FROM	table_name
WHERE ymd >= '${ymd_start}' and ymd <= '${ymd_end}'
group by ymd 
ORDER BY ymd 

数据库表最近几年每天都有数据的，当时间范围不大，比如一个月内，或者一个月多一点，则折线图可以显示全部数据，如果时间范围大了，比如两个月，则数据显示不全：

12月，可以全部显示
![image](https://user-images.githubusercontent.com/108739923/209747583-fcab7461-9f52-40e1-a2d2-fae53f6192ae.png)

11-12月，显示不全，而且折线图上最后一个点也只是12月20号的，如果时间单位为10-12月，则只能显示到11月的
![image](https://user-images.githubusercontent.com/108739923/209747703-04d0f552-41c5-4713-9bcc-161157be383b.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
你数据集是否设置了分页查询？

**Comment by zhanghahahahahaha** [comment]
> 的确设置了分页，取消分页后数据显示全了。
closed
