### ISSUE TITLE
报表设置了自动换行，但是导出的excel中，虽然自动换行了，但是行高没有变

### ISSUE THREAD

**Issue by wangyh198910** [jeecgboot/JimuReport#1551]
##### 版本号：
1.5.6

##### 问题描述：
我在报表中设置了自动换行，页面展示打印都没有问题，但是在导出的excel中，文字虽然换行了，但是行高没有变

##### 错误日志&截图：
报表设置：
![image](https://user-images.githubusercontent.com/21198489/209750592-12e71c15-46ae-4772-a0e1-a1b103271cac.png)
页面效果：
![image](https://user-images.githubusercontent.com/21198489/209750643-82eb54a3-5d57-48d4-a167-2c4fc21451ce.png)
导出Excel效果：
![image](https://user-images.githubusercontent.com/21198489/209750701-23c75148-7127-4967-843b-3978359d4ec8.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by tennisdd** [comment]
这个问题你是如何解决的？我需要根据EXCEL生成PDF，EXCEL中的内容不能有遮挡，否则生成的PDF内容就显示不全

**Comment by lvdandan16** [comment]
导出的excel 行高是不能自适应的，需要手动调整行高
