### ISSUE TITLE
报表查看时，数据量大，查看下方数据时，上方表头无法固定，无法确定数据属于哪列。（查看报表时，上方表头无法固定）

### ISSUE THREAD

**Issue by Hunter-han611** [jeecgboot/JimuReport#1552]
##### 版本号：
1.5.6

##### 问题描述：
查看报表时，上方表头无法固定
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/54894974/209751702-d5fe9c47-a961-46aa-bf6d-9af2078a659f.png)
![image](https://user-images.githubusercontent.com/54894974/209751828-f91357e6-9c25-46e6-95f7-674145df4020.png)

##### 重现步骤：
当报表数据量大时，下拉滚动条，上方表头滚动消失，无法确定当前数据属于哪类。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
归集 #138
