### ISSUE TITLE
导出pdf文件无固定打印表头表尾内容、无当前页总页数函数

### ISSUE THREAD

**Issue by lxridewind** [jeecgboot/JimuReport#1553]
##### 版本号：
1.5.6

##### 问题描述：
1、固定打印表头、固定打印表尾的内容，打印有效果，但是导出pdf文件则没有加上，感觉打印设置并未作用到导出过程
2、想在导出pdf文件尾部显示 "第n页/共m页" 这样的内容，但是缺少类似 当前页码、总页数的函数表达式

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/52850885/209766266-561839b1-fff5-4c1a-8662-122de9ff5789.png)

![image](https://user-images.githubusercontent.com/52850885/209766395-7bd5302e-204f-4adc-89ac-cf90850a16f4.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
目前只有打印支持，导出还没加
页码暂时不支持
