### ISSUE TITLE
当有多个数据源时，使用=SUM 对某个数据源的列进行求和时，得到的结果是多个数据源的和 

### ISSUE THREAD

**Issue by IsLiving** [jeecgboot/JimuReport#1554]
##### 版本号：
版本 1.5.6

##### 问题描述：
当有多个数据源时，使用=SUM 对某个数据源的列进行求和时，得到的结果是多个数据源的和 

##### 错误日志&截图：
这有两个内容部分的小计，但下方第二个小计，在报表预览页面上，获得的内容，更像是个总计，无法获得第二部分的小计。
![image](https://user-images.githubusercontent.com/38464696/209769679-2b131450-1f7e-45eb-b385-6d8cd4668ee5.png)
![image](https://user-images.githubusercontent.com/38464696/209769845-db615201-b2fe-4128-9f5f-61ff8d301554.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 zy

**Comment by lvdandan16** [comment]
sum是对整列求和，不支持分别小计，分别小计可参考分组小计
