### ISSUE TITLE
请问积木报表/jmreport/list下没有大屏设计器，该设计器是需要另外集成的吗

### ISSUE THREAD

**Issue by qq670176019** [jeecgboot/JimuReport#1557]
![image](https://user-images.githubusercontent.com/35839281/209791936-d0e849d7-3f68-4f6b-89c0-fbd2cc18a0dd.png)

官网上的示例里面，有大屏设计器；JeecgBoot里面有大屏设计器功能。

请问官方大佬：
1、积木报表中大屏设计器是单独集成进去的吗？
2、可以从JeecgBoot中分离出来自主集成进去吗？

谢谢！

**Comment by zhangdaiscott** [comment]
大屏只能在线用，不免费

**Comment by qq670176019** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件我已经收到，尽快给您回复。
