### ISSUE TITLE
自带的小计功能只能显示“合计”，不能自定义

### ISSUE THREAD

**Issue by jzha0927** [jeecgboot/JimuReport#1563]

**Comment by lvdandan16** [comment]
不支持自定义，归集

**Comment by jeecgos** [comment]
1.7.4+ 版本已支持 自定义小计文本功能。https://help.jeecg.com/jimureport/group/verticalSubtotal.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%88%86%E7%BB%84%E5%B0%8F%E8%AE%A1
