### ISSUE TITLE
希望实现预览时可编辑

### ISSUE THREAD

**Issue by h95-y09k21** [jeecgboot/JimuReport#1564]
##### 问题描述：
希望实现预览时可编辑，某些合同在生成时，部分字段需要自己填写，又不能把报表设计功能下放给他们，只能给他们预览的权限，所以希望实现预览报表时可以进行编辑。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
无此计划，本项目只用于报表，不做填报
