### ISSUE TITLE
1.5.6多租户不起作用

### ISSUE THREAD

**Issue by flysmallstrong** [jeecgboot/JimuReport#1566]
##### 版本号：
1.5.6

##### 问题描述：
我使用官方example
项目和数据库都是最新的,1.5.6版. 数据库表中有相应的tenant_id和type字段, JimuReportTokenService 中加入了getTenantId()
application.yml 中启用了  openTenant: true  以及 saas: true/false  (不确定saas的作用, 所以true和false都试过)
url header中,  租户key 与官网的不一致. 官网为tenantId,  而我的为JmReport-Tenant-Id
生成的sql的where条件中并没有生成 tenantId 条件

##### 错误日志&截图：
![图片](https://user-images.githubusercontent.com/36694291/210171676-c1d36337-8f31-46f2-a6d5-35ec3e0c7dd4.png)
![图片](https://user-images.githubusercontent.com/36694291/210171681-0e7452ff-38a4-4aee-a6e9-c08971638458.png)
![图片](https://user-images.githubusercontent.com/36694291/210171697-0d3c4ef1-64be-45e4-986d-d6e90d2e2c92.png)
![图片](https://user-images.githubusercontent.com/36694291/210171741-ccf95599-ed55-49ac-a9d6-3b4f8442ee6a.png)

page countsql===> SELECT count(0) FROM jimu_report jr WHERE 1 = 1 AND jr.TYPE = :jimuReport.type AND jr.DEL_FLAG = :jimuReport.delFlag AND jr.TEMPLATE = :jimuReport.template

page executeSql===> SELECT jr.ID,jr.NAME,jr.CODE,jr.TYPE,jr.template,jr.thumb FROM jimu_report jr WHERE 1=1 and jr.TYPE = :jimuReport.type and jr.DEL_FLAG = :jimuReport.delFlag and jr.TEMPLATE = :jimuReport.template ORDER BY jr.create_time DESC
 LIMIT 10 

##### 重现步骤：
使用的是firefox浏览器
url 为 http://localhost:8085/jmreport/list?tenantId=123&token=456

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zxs199414** [comment]
http://report.jeecg.com/2302149,看[yaml配置参数说明]，因为你没有开启多租户模式。

**Comment by xiaolaifeng** [comment]
openTenant: true表示多租户吧， 我开启也和楼主遇到的问题一样


#JimuReport[上传配置]
jeecg :
  jmreport:
   #只看自己创建数据 (报表、数据源、数据集、字典)
    saas: true
    #是否开启租户模式 Support By v1.5.5+   
    openTenant: true
    #是否 禁用导出PDF和图片的按钮 默认为false
    exportDisabled: false
    #是否自动保存
    autoSave: true
    #自动保存间隔时间毫秒
    interval: 20000
    # 列索引
    col: 100
    #自定义项目前缀
    customPrePath:
    # 自定义API接口的前缀 #{api_base_path}的值
    apiBasePath: http://localhost:8080/jeecg-boot
    #数据源标识
    datasource: master
    #预览分页自定义
    pageSize:
      - 10
      - 20
      - 30
      - 40
    #打印纸张自定义
    printPaper:
      - title: A5纸
        size:
          - 148
          - 210
      - title: B4纸
        size:
          - 250
          - 353
    #接口超时设置（毫秒）
    connect-timeout: 300000
    #Excel导出模式(fast/快、primary/精致模式，默认fast)
    export-excel-pattern: fast
    #Excel导出数据每个sheet的行数,每个sheet最大1048576行
    page-size-number: 10000
    #excel样式超过多少行显示默认样式（只在fast模式下有效）
    excel-style-row: 1000
    #设计页面表格的线是否显示 默认true
    line: true
    #sql数据源不写字典下拉框显示条数 版本1.4.2之后被放弃
    select-show-total: 10
    #是否启用签名校验,默认不开启，开启后会对执行sql的接口进行参数校验
    safeMode: true
    #预览页面的工具条 是否显示 默认true（3.1.0+版本（包含3.1.0）已移除）
    viewToolbar: true
  # local|minio|alioss
  uploadType: local
  # local
  path :
    #文件路径
    upload: D:\images
