### ISSUE TITLE
无法支持 url参数 动态切换，sql数据集的数据源

### ISSUE THREAD

**Issue by Rocky90883** [jeecgboot/JimuReport#1567]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/34960593/210243696-d7a1ab80-5954-40df-ab10-4d612893690a.png)

对于#{} ${} 或者新增其他标记，是否可提供  非sql注入的传参方式
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
报表参数需要设置默认值
