### ISSUE TITLE
报表文件导入生产环境

### ISSUE THREAD

**Issue by valinoment** [jeecgboot/JimuReport#1568]
##### 版本号：
1.5.0

##### 问题描述：
开发环境下设计好的报表文件能否导出，然后再导入，以达到先设计好报表再导入生产环境的目的？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
自己整理升级sql即可
