### ISSUE TITLE
不同db的数据集想联合在一起使用，该怎么做？

### ISSUE THREAD

**Issue by valinoment** [jeecgboot/JimuReport#1569]
##### 问题描述：
不同db的数据集想联合在一起使用，该怎么做？

比如，mysql下有个表存用户基础数据 user（userid，username）
mongodb下有个集合存用户登录历史 userlogin（time，userid，ip)

然后需要做个报表显示用户登录的历史数据（time，username，ip）,请问该如何操作？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你可以自己把数据处理好，再用积木报表展示
