### ISSUE TITLE
再次设计报表，点击报表保存图标按钮，出现json格式错误异常

### ISSUE THREAD

**Issue by github-sunxiaochen** [jeecgboot/JimuReport#1570]
##### 版本号：
1.5.6

##### 问题描述：
第一次创建报表是没有问题的，但是再次点击设计进入，点击保存按钮就会出现第二张图的错误，显示json的格式不正确。

最后一张截图，官网线上的测试是可以正常保存，另一个是本地的请求，显示两个时间格式不一样。不知道是不是这个原因

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/79350069/210323415-5f8c2264-8b5a-429e-8b23-41645684d068.png)
![image](https://user-images.githubusercontent.com/79350069/210323481-0f7e834b-95a5-4e23-862c-a9942c21628b.png)
![image](https://user-images.githubusercontent.com/79350069/210323813-f773f746-fdde-4457-927f-b84692e3f3e2.png)
![image](https://user-images.githubusercontent.com/79350069/210326222-8df15b29-d0bc-484d-8500-7ef6a0a9da95.png)

##### 重现步骤：
新建报表-数据集管理（新建sql）-选择一个数据库表，拖拽完成设计。返回报表设计界面，在新建的报表上选择设计，再次进入报表，点击报表的保存图标按钮，就会出现上述问题。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ldd

**Comment by lvdandan16** [comment]
未复现此问题
