### ISSUE TITLE
html打印带二维码的模板，二维码会占据一整页，把内容挤到下一页

### ISSUE THREAD

**Issue by Gigiwin** [jeecgboot/JimuReport#1572]
##### 版本号：
1.5.2

##### 问题描述：
打印设计模板带二维码的打印，选择“html打印”，浏览器（Google Chrome浏览器）出来的打印预览，分成了两页，二维码所在行占据了整整一页，内容都被挤到第二页了。
备注：1、之前设计的时候，用html打印出来的是正常的，不知道什么时候开始，预览就分页了。
2、不同电脑上同一个浏览器，浏览器打印预览出来的效果也不一样（有的分两页，有的是同一页），不知道什么原因。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/46088584/210678284-de02f1a7-1443-48b5-9298-9488bd1a666c.png)
![image](https://user-images.githubusercontent.com/46088584/210678168-fb6796cf-5eed-4e02-98df-f2802bd0b450.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Gigiwin** [comment]
已发现是谷歌浏览器版本的问题。升级到108版本的浏览器打印预览会出现这样的问题。
![image](https://user-images.githubusercontent.com/46088584/211476983-62661b20-bc99-484b-92c7-98a7aee32790.png)
<img width="529" alt="1673331836571" src="https://user-images.githubusercontent.com/46088584/211477082-7ae27dbc-01b5-4044-91f1-6f1ba6ec756f.png">

**Comment by KaherineZXL** [comment]
你好，我是谷歌111的版本也出现一样的问题，能问下谷歌哪个版本的打印是正常的吗
![image](https://user-images.githubusercontent.com/120431879/227400079-9d046ed5-55a0-4ca9-a6ce-81bb41f50c66.png)

**Comment by Gigiwin** [comment]
抱歉，我现在才看到你发给我的邮件。我这边了解到的是：浏览器内核版本高于108的都会出现这样的问题。另外，我有同事的电脑用的是以下的两种浏览器版本，打印是正常的：




积木报表目前还是没有处理这个问题。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月24日(星期五) 上午9:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] html打印带二维码的模板，二维码会占据一整页，把内容挤到下一页 (Issue #1572)





 
你好，我是谷歌111的版本也出现一样的问题，能问下谷歌哪个版本的打印是正常的吗

**Comment by zhangdaiscott** [comment]
已经处理了，下个版本发布
