### ISSUE TITLE
Excel导出当数值个位数时(0-9)会为文本格式

### ISSUE THREAD

**Issue by speckle23** [jeecgboot/JimuReport#1575]
##### 版本号：

1.5.6
##### 问题描述：
excel导出，当数值为个位整数时设置数值格式无效，其他数没有该问题

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/54102334/221069705-416c3c99-1584-428e-b5b0-15c1e05081e3.png)
注:如红框为个位整数，导出为文本格式；绿框为两位数导出为数值

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by speckle23** [comment]
单元格设置数值类型及字段设置都无法实现

**Comment by lvdandan16** [comment]
导出为字符串，不支持设置为数组

**Comment by 1298191366** [comment]
已修复，待新版本发布
