### ISSUE TITLE
怎么自定义API请求地址

### ISSUE THREAD

**Issue by hunk666** [jeecgboot/JimuReport#1576]
##### 问题描述：
请问怎么自定义API请求地址啊
![image](https://user-images.githubusercontent.com/68905085/210925441-a8b351e8-5bb1-42c0-ab1b-ecdf64709301.png)

我自定义了系统变量，但是报表里面取不到啊
![image](https://user-images.githubusercontent.com/68905085/210925549-a7afa960-503d-43fc-89e3-447eaf25372b.png)
![image](https://user-images.githubusercontent.com/68905085/210925568-26d59946-8442-46cb-8c72-05a0ab054511.png)
![image](https://user-images.githubusercontent.com/68905085/210925620-34e250e7-83ef-4e51-96c4-b126eae5def9.png)

**Comment by stevenzhao719** [comment]
请问解决了吗

**Comment by lvdandan16** [comment]
收录 ws

**Comment by zhangdaiscott** [comment]
用这个写法 `#{}`
