### ISSUE TITLE
自带的分页查询接口返回pageNo不对

### ISSUE THREAD

**Issue by hahaha11123** [jeecgboot/JimuReport#1578]
##### 问题描述：
报表设计-分页查询接口，返回pageNo错误，设置成了pageSize
Request URL: http://firefly.dahuatech.com/jmreport/excelQuery?pageNo=1&pageSize=10&reportType=datainfo&name=
返回结果：
{"success":true,"message":"","code":200,"result":{"pageNo":10,"pageSize":10,"total":4,"pages":1,"records":[]},"timestamp":1672995375533}
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 sq

**Comment by hahaha11123** [comment]
您的邮件已收到，谢谢！

**Comment by lsqGitHub716** [comment]
已修改
