### ISSUE TITLE
表格里，图片变形

### ISSUE THREAD

**Issue by 1600063003** [jeecgboot/JimuReport#1579]
##### 错误日志&截图：
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/20981426/210975569-52941362-5d63-460d-97dc-edc96761d0c2.png">

[report-export-mysql.sql.zip](https://github.com/jeecgboot/JimuReport/files/10359154/report-export-mysql.sql.zip)

##### 重现步骤：当表格的高度很高时，图片会撑的变形，期望图片高度能设置成height: auto;

http://localhost:8085/jmreport/view/760645615872897024?uClientId=huansi&uHdrId=53397328-ab91-483a-af93-782a987264dc

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 zy

**Comment by liaozhiyang** [comment]
右侧新增了一个图片设置功能可解决此问题，下一版本发布
