### ISSUE TITLE
请问动态属性如何与背景色修改共用

### ISSUE THREAD

**Issue by javawhb** [jeecgboot/JimuReport#1581]
##### 版本号：
1.5.4

##### 问题描述：
已经实现了按月动态显示数据，现在的需求是，如果偏差数据值小于0，单元格要标红告警，因为单元格的值已经是这种格式了#{tool.dynamic(deviation_ratio)}，所以现在不知道怎么和color共用。已经试过以下格式均不行：
#{tool.dynamic(case(tool.deviation_ratio < 0, color('#{tool.deviation_ratio}', '', 'red'),color('#{tool.deviation_ratio}', '', 'green')))}
=case(tool.deviation_ratio < 0, tool.dynamic(color('#{tool.deviation_ratio}', '', 'red')),tool.dynamic(color('#{tool.deviation_ratio}', '', 'green')))
#{tool.dynamic(color('#{deviation_ratio}', '', 'red'))}

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/19985809/211279530-7858aa95-3d51-444d-afa4-5014216c4fe5.png)
![image](https://user-images.githubusercontent.com/19985809/211279617-7f2f9063-a204-4dee-8c06-b5ab3e92ae21.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
归集到 #138
