### ISSUE TITLE
合并单元格之后添加图表，无法显示单元格边框

### ISSUE THREAD

**Issue by zhpingzi** [jeecgboot/JimuReport#1583]
##### 问题描述：
合并单元格并设置边框格式之后，添加图表，预览界面和导出的excel表格中都无法显示单元格的边框样式。
如果不合并单元格，只设置边框，预览界面是可以看见边框样式的

##### 错误日志&截图：
1.设计界面
![image](https://user-images.githubusercontent.com/82299489/211454172-539f73b8-dd9e-4dc4-95ef-ffd6f36ffe22.png)

2.预览界面
![image](https://user-images.githubusercontent.com/82299489/211454214-2cae47bc-040f-4562-bc57-7363c7167f84.png)

3.不合并单元格，只设置边框，预览界面
![image](https://user-images.githubusercontent.com/82299489/211454392-02abc9bb-1d8b-4bdf-88d8-a2545bfcf39f.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 zy

**Comment by liaozhiyang** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/8199499/fad98b7d-786f-4903-95ce-e5a95d3bcf20)
![image](https://github.com/jeecgboot/JimuReport/assets/8199499/535ba28d-e21f-4866-a2e9-bd61b74c460c)
新版无法复现，建议升级下版本。
