### ISSUE TITLE
项目部署后接口请求地址问题

### ISSUE THREAD

**Issue by TwentyNine-8** [jeecgboot/JimuReport#1584]
##### 版本号：
1.5.6

##### 问题描述：
项目集成后,点新建报错后发现请求接口的ip为服务器内网ip,想修改请求的ip地址,尝试了修改 jeecg.jmreport.apiBasePath 但是发现没有用,请问有什么办法可以解决吗

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by hunk666** [comment]
我也是这个问题，改不了请求接口地址

**Comment by zhangdaiscott** [comment]
怎么改的？详细说明

**Comment by lvdandan16** [comment]
收录 sq
