### ISSUE TITLE
分栏功能和分组功能组合使用时，后台会报NPT错误

### ISSUE THREAD

**Issue by phsy** [jeecgboot/JimuReport#1585]
##### 问题描述：
分栏功能和分组功能组合使用时，后台会报NPT错误

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/10345070/211504042-a1bee333-b001-472c-864d-2591632b70d9.png)

##### 重现步骤：
设置分栏，然后针对某个字段设置分组
官网示例
https://cloud.jimureport.com/jmreport/view/772697586829447168?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NzM0MDU3NTQsInVzZXJuYW1lIjoib2hiYUs2U1A1WU1pZC1UQVpmS0JMU3pwT3U1NCJ9.hzU7pHGXj080baJDlWHHKtg8sS0HTpyNsENJ7Mlz7Tw

**Comment by lvdandan16** [comment]
分栏分组功能不支持同时使用
