### ISSUE TITLE
请教一下，关于reportConfig的问题

### ISSUE THREAD

**Issue by daiw-hy** [jeecgboot/JimuReport#1586]
##### 版本号：jimureport 1.5.6
                          jeecg-boot 2.2.0

##### 问题描述：jeecg集成jimureport 的时候，到最后一步查询列表，复制模板，收藏等功能可以正常运行，但是预览和设计会报错
                              Failed at: ${reportConfig} [in template "jmreport/desreport/view.ftl" at line 45, column 20] ----

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/81909025/211755604-fb272214-d982-4575-bc9c-a7dbd0e95545.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 1198735966** [comment]
升级一下fastjosn 的版本，1.2.83以上试一下
