### ISSUE TITLE
报表SQL输入框没有像文档里那样自动调整高度

### ISSUE THREAD

**Issue by HDHXTM** [jeecgboot/JimuReport#1588]
##### 错误日志&截图：
本地环境：
![image](https://user-images.githubusercontent.com/74095069/211954097-bde4d104-4f53-4168-b1cd-a3510fa8b5ff.png)
官方文档：
![image](https://user-images.githubusercontent.com/74095069/211954211-87997b6f-038f-4f10-ab2f-c622eba13120.png)

**Comment by lvdandan16** [comment]
手动拖动输入框
