### ISSUE TITLE
图表的API数据集接口请求官网文档没写

### ISSUE THREAD

**Issue by GitHubFdd** [jeecgboot/JimuReport#1590]
##### 版本号：
V1.5.4 windows免安装版

##### 问题描述：
如截图所示意，我本地用node.js写了一个接口，使用积木报表的图表组件通过api数据集的接口请求访问，报错内容为“请返回正确的json数据”，然后我查阅官方文档并没有这一项的说明。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/117428642/212001859-65fbee12-faa2-405a-9fdc-d4ef58d76acf.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by GitHubFdd** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zhangdaiscott** [comment]
sq

**Comment by GitHubFdd** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 1298191366** [comment]
你的数据是api动态数据的时候用到的
参考文档：https://help.jeecg.com/jimureport/barChart/datasource.html#3%E5%8A%A8%E6%80%81api%E6%95%B0%E6%8D%AE-1
api接口请求需要自己封装echars配置及数据并返回，数据用options
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/9394ac3f-6a28-4793-a7ee-2bcd2bca0723)
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/4e86aab0-dedb-4cd2-a414-f03e89087f69)
