### ISSUE TITLE
根据动态列，自动进行单元格合并

### ISSUE THREAD

**Issue by chen01779451** [jeecgboot/JimuReport#1591]
##### 问题描述：动态列后，能否让标题行  根据动态列数 进行动态合并，
                             如：动态列有2列，那么标题行（或者是其他行） 可以自动合并2列
                             动态列数据有三列，那么标题行 合并3列

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
