### ISSUE TITLE
合并单元格后多行数据时，  行高异常

### ISSUE THREAD

**Issue by chen01779451** [jeecgboot/JimuReport#1593]
##### 问题描述：A1，A2，A3合并单元格，设置合并单元格自动换行，
                              设置第1、2、3行高度分别为25像素
                              在该单元格输入  多行文字后预览
                              发现第一行（A1）行与第2、3行，行高不一致

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请图文并茂
