### ISSUE TITLE
垂直居中后 样式上有所差异

### ISSUE THREAD

**Issue by chen01779451** [jeecgboot/JimuReport#1594]
##### 问题描述：单元格  设置了垂直居中，
                              但是总是感觉有偏差，或者靠上，或者靠下

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/47739705/212031237-c91fe0b3-6a2a-426e-a4ea-2f9a42702b06.png)
![image](https://user-images.githubusercontent.com/47739705/212031461-b227ecec-79ce-4c29-b2b5-64d9a07dca7b.png)
![image](https://user-images.githubusercontent.com/47739705/212032096-bffa856d-645c-4948-94c2-9eeff33145bc.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by liaozhiyang** [comment]
请问操作步骤是什么？设计器中只有自动换行，没复现此问题
