### ISSUE TITLE
当前页合计的值在打印时显示的是全量数据总和

### ISSUE THREAD

**Issue by phsy** [jeecgboot/JimuReport#1595]
##### 问题描述：
当前页合计功能页面显示正常，打印预览和打印时显示的是全部数据的合计

##### 错误日志&截图：
页面显示正常：
![image](https://user-images.githubusercontent.com/10345070/212032053-a0aa7cb0-78fc-456f-ace0-06b2eeffec92.png)
打印预览时显示错误，当前页合计的值和总数时一样的
![image](https://user-images.githubusercontent.com/10345070/212032222-e5e87b52-4c20-48a9-a7bf-95352c62a2d3.png)
生产环境打印效果（小计为当前页合计，总计为总数合计）
![image](https://user-images.githubusercontent.com/10345070/212033134-b5b79f0f-6d19-48ed-a799-fda5a5019146.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
在积木报表官网提供示例，我们看一下

**Comment by lvdandan16** [comment]
目前打印是不支持分页的，打印的是全部数据，所以会统计所有数据的值
