### ISSUE TITLE
浏览器打印总会多一页空白页

### ISSUE THREAD

**Issue by xingmyworld** [jeecgboot/JimuReport#1596]
##### 版本号：

1.5.6
##### 问题描述：
谷歌浏览器打印,会多一页空白页.  系统自带模板也是一样的

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/62834631/212219131-8b0bb026-a0ce-4e5e-bfda-d1346989e314.png)

##### 重现步骤：
用谷歌浏览器,预览-->打印

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by unbelievableTang** [comment]
这个问题解决了吗，我这边打印也莫名多一页空白页

**Comment by lvdandan16** [comment]
收录 ty

**Comment by zhangdaiscott** [comment]
已经处理了，下个版本发布
