### ISSUE TITLE
固定头第3页以上不打印等问题

### ISSUE THREAD

**Issue by xingmyworld** [jeecgboot/JimuReport#1597]
##### 版本号：
1.5.6

##### 问题描述：
1.固定头出现如下问题:
1)固定头第3页起就没不显示固定头
2)固定头的图片位置不对,跑到左上方. 另外图片也只打第一页,后面几页都不打
3)自动换行, 整个文本框换到下页去了,不合理.  自动换行的已设置对齐方式:垂直向上

##### 错误日志&截图：
图1: 打印文档
![1673576114554](https://user-images.githubusercontent.com/62834631/212221540-5aa1e582-b206-467c-a544-6622db88a4f5.png)

图2:设计文档
![1673575903279](https://user-images.githubusercontent.com/62834631/212221212-a68cf68b-f000-4e43-9047-097603ee2a41.png)

##### 重现步骤：
固定头部打3页以上

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
导出报表配置和数据贴上来，我们看一下

**Comment by liaozhiyang** [comment]
问题1和问题3现在线上已经解决，问题2固定表头的图目前不支持上传的图，你可以 选择单元格-->右侧面板选择图片类型-->填入图片地址，这种方式的图片支持固定表头
