### ISSUE TITLE
使用Api数据集方式，点击Api解析按钮报错

### ISSUE THREAD

**Issue by Lambert-ch** [jeecgboot/JimuReport#1598]
##### 版本号：
1.5.6

##### 问题描述：
使用Api数据集方式，点击Api解析按钮报错
![image](https://user-images.githubusercontent.com/77565700/212259131-88afc83b-3275-446a-9b82-f88d85fd12b3.png)

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/77565700/212259492-96138785-8d85-417b-9e85-220527562bc2.png)

##### 重现步骤：
点击api解析报错

原因是
/jmreport/executeSelectApi接口用post请求。前端：content-type格式为
![image](https://user-images.githubusercontent.com/77565700/212259954-472309d3-0c11-427a-8ef4-f21ec12f25ec.png)
接口
![image](https://user-images.githubusercontent.com/77565700/212259986-42920064-90d5-4a6f-a883-b1b1c8c4722d.png)
拿不到参数

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
api参数传值了吗
