### ISSUE TITLE
循环块中自动换行打印出现空白

### ISSUE THREAD

**Issue by Fancy128** [jeecgboot/JimuReport#1599]
##### 版本号：
1.5.6

##### 问题描述：
打印审批流程时，出现大段空白，数据没有换行也直接到了下一页

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/57052798/212269736-578af43a-3bf6-4f3a-8f74-7e052eccddb9.png)
![image](https://user-images.githubusercontent.com/57052798/212270264-9aa0feac-a23e-48b7-84cf-c34c6d7ff86e.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by liaozhiyang** [comment]
有更加具体操作步骤吗？或者能提供预览页面吗？仅凭上面这些信息不太好定位具体问题

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
