### ISSUE TITLE
api解析报表参数传时间默认值问题

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/JimuReport#1600]
##### 版本号：
1.5.6

##### 问题描述：
api解析想传时间默认值月份，比如2023-01，根据文档配置时间默认值为=dateStr('yyyy-MM', -1)，但是解析失败，后台跟踪传的是=dateStr('yyyy-MM', -1)字符串了

##### 错误日志&截图：
![3Z4WJY8V9JXAND%YGJ9 GVR](https://user-images.githubusercontent.com/90361617/212510966-894c6c5d-c203-46f6-8a57-99a1dd3fa709.png)
![~{$JD5{%LHMF0YG)AU)AG(1](https://user-images.githubusercontent.com/90361617/212511042-154fc2a1-f52b-485c-b3a7-78df72baa4e5.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
已修改
