### ISSUE TITLE
数据源用sqlServer，在预览页面有查询，查询中有中文，传给后端没有加N，查不到数据，

### ISSUE THREAD

**Issue by Ralap-li** [jeecgboot/JimuReport#1601]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/108796742/212582634-e9dc3c68-d1fd-4ea3-8eb0-75782f64c05d.png)
![image](https://user-images.githubusercontent.com/108796742/212582658-28af4f3a-31af-43b2-8b93-20344e3b5518.png)
![image](https://user-images.githubusercontent.com/108796742/212582687-984d8dcc-9995-459d-8e19-256ad796ba92.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by lsqGitHub716** [comment]
对于特殊情况，这边建议您使用[SQL条件表达式](https://help.jeecg.com/jimureport/query/sqlCondition.html)来实现您的功能
