### ISSUE TITLE
图表钻取，设置参数的时候，参数只能从图表分类和图表值两个选择吗？

### ISSUE THREAD

**Issue by donghbcn** [jeecgboot/JimuReport#1603]
##### 版本号：
1.5.4

##### 问题描述：
图表钻取，设置参数的时候，参数只能从图表分类和图表值两个选择吗？
比如要实现这样的需求，该如何实现？
报表A，饼图，分性别展示订单额，可以通过性别下钻到报表B
报表B，饼图，展示某个性别，分年龄段，展示订单额，点击年龄段，下钻到报表C
报表C，展示某个性别，某个年龄段的订单明细。报表C 需要两个参数，性别和年龄段。但是报表B 的饼图，下钻参数只有图表分类和图表值可供选择，在数据集中加了性别字段，参数也没有列出来。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/26576616/212583436-da5b8c8c-0305-4a54-a320-5cf920c7b7f2.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
目前图表的钻取只能获取你点击的图表所的配置数据（如下图），暂时还获取不到非图表上的其他数据
![image](https://github.com/jeecgboot/JimuReport/assets/65587928/c9f806db-b4db-488d-9802-73001c5eebcd)
