### ISSUE TITLE
报表钻取问题,跳转参数设置问题,条件不生效问题

### ISSUE THREAD

**Issue by TwentyNine-8** [jeecgboot/JimuReport#1604]
##### 版本号：
1.5.6

##### 问题描述：
1. 设置报表钻取时,例如在B列设置,跳转参数选择id,不生效,需要设置为具体列
2. 设置报表钻取条件不生效

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/59173584/212617815-d299e2d2-42d6-4baa-a3be-6772ae81dcc2.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版发布。
空数据用下图所示判断
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/6b97fa5d-b496-433b-becb-6f93adbc5581)
