### ISSUE TITLE
查询异常

### ISSUE THREAD

**Issue by Blank-GGW** [jeecgboot/JimuReport#1605]
##### 错误日志&截图：
日志：
![image](https://user-images.githubusercontent.com/112541486/212848205-4b610e50-ee3d-47a1-b617-05153b7015b5.png)
![image](https://user-images.githubusercontent.com/112541486/212848327-e34b31b7-1310-40e5-990e-768b10d12957.png)

##### 重现步骤：
1、链接sql server
2、编写sql语句
3、在sql解析完成后，在【报表明细字段】中选择一个有汉字的字段，并将此字段设为可查询的字段
4、将字段拉到表格中后，保存并进行预览
5、在查询条件中选择带有汉字的筛选条件
6、点击查询

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Blank-GGW** [comment]
![image](https://user-images.githubusercontent.com/112541486/212853211-7a4b1298-19c7-4629-a8dc-184742ac32b3.png)
使用sql查的时候是有数据的

**Comment by Blank-GGW** [comment]
> ##### 版本号：1.5.6
> ##### 问题描述：在链接到SQL Server时，如果查询条件中有汉字，将不会正常查询
> ##### 错误日志&截图：
> 日志： ![图像](https://user-images.githubusercontent.com/112541486/212848205-4b610e50-ee3d-47a1-b617-05153b7015b5.png) ![图像](https://user-images.githubusercontent.com/112541486/212848327-e34b31b7-1310-40e5-990e-768b10d12957.png)
> 
> ##### 重现步骤：
> 1、链接SQL Server 2、编写SQL语句 3、在sql解析完成后，在【报表明细字段】中选择一个有汉字的字段，并将此字段设为可查询的字段 4、将字段拉到表格中后，保存并进行预览 5、在查询条件中选择带有汉字的筛选条件 6、点击查询
> 
> #### 友情提示（为了提高issue处理效率）：
> * 积木报表是一款免费报表产品，功能免费源码不开放;
> * 未按格式要求发帖，会被直接删掉;
> * 请针对问题提供报表[设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
> * 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
设置SqlServer支持中文就行了
Chiness_PRC_CI_AS
https://zhuanlan.zhihu.com/p/162933497

或者你所有的查询SQL带着N
