### ISSUE TITLE
单元格自动合并问题（使用问题）

### ISSUE THREAD

**Issue by jiadejun521** [jeecgboot/JimuReport#1606]
##### 问题描述：
合并后的单元格不会随着纵向扩展，自动向下合并，也就是统计列随着公式列自动向下合并，这个该怎么设置

##### 错误日志&截图：
我的报表是这样的
![T9H{%TF7$ 0F`Y3$SA{KU3J](https://user-images.githubusercontent.com/43490975/213058012-aa848a24-5332-49ed-867b-eab12e4d414f.jpg)

预览是这样的
![0D%K8% _%PSGGR`Z8}`CJ7D](https://user-images.githubusercontent.com/43490975/213057885-c1b04519-60c2-4bbe-b087-c2ff5a110848.jpg)
我想让他变成这样的
![6(G_QBTFAORZKX)E2E6IVZ0](https://user-images.githubusercontent.com/43490975/213057916-cea2782f-f79a-48d7-a89e-77f7031ecc68.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档：https://help.jeecg.com/jimureport/base/dynamicMerge.html
