### ISSUE TITLE
大屏预览时提示接口异常

### ISSUE THREAD

**Issue by mgq880605** [jeecgboot/JimuReport#1608]
##### 问题描述：
大屏在数据源处添加接口地址，预览时偶发性提示接口异常，按F12查看，显示错误为：
Access to XMLHttpRequest at 'https://********/html/big_screen/okCount' from origin 'https://cloud.jimureport.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/123916589/215378327-ed6ed627-15fe-4e3f-bbd4-383c044471a2.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
接口问题，或网络问题吧，如果平时可以，只是偶尔有问题，有可能是偶尔网络慢吧
