### ISSUE TITLE
打印固定页尾，是否能够支持页码显示

### ISSUE THREAD

**Issue by wangyh198910** [jeecgboot/JimuReport#1609]
##### 版本号：
1.5.6

##### 问题描述：
在打印预览中，是否能够设置如图显示的内容，显示总页码与当前页码的数值？
![image](https://user-images.githubusercontent.com/21198489/215708393-c1c7dd6a-60f1-4a31-8d79-15198bc23528.png)
现在是这个样子的：
![image](https://user-images.githubusercontent.com/21198489/215708673-8b702967-6858-4af0-95ba-83c3ad289172.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
