### ISSUE TITLE
多数据集分版进行横向分组报错

### ISSUE THREAD

**Issue by gongrui218** [jeecgboot/JimuReport#1610]
##### 版本号：

1.5.2
##### 问题描述：

多数据集分版成多张表在一个报表里展示，除第一张表意外后续表进行横向分组报错
##### 错误日志&截图：
Index: 1, Size: 1
![5MRO{WQQZME ~E52KY70GTC](https://user-images.githubusercontent.com/43981702/215932396-6b27560a-dde0-492c-833d-c33495cd2176.png)
##### 重现步骤：
多数据集横向分组：
![image](https://user-images.githubusercontent.com/43981702/215932605-cbc737c9-fc7d-4531-ae70-d009f4358a75.png)
第二个数据集分版横向分组
![image](https://user-images.githubusercontent.com/43981702/215932888-8d36118f-d565-4df1-9286-1f0de4459654.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
一个报表中只支持一个横向分组
