### ISSUE TITLE
不能集成svg显示

### ISSUE THREAD

**Issue by a67757954** [jeecgboot/JimuReport#1612]
##### 问题描述：
我想在表格里面显示svg样式，

例如下图这样
![image](https://user-images.githubusercontent.com/45644866/216211695-8b7ce56a-6ab8-42ef-b97e-f1c7c0d729da.png)

帆软的代码如下
let (pathStr,IF($angle_one != "v" && $angle_two != "v",CONCATENATE("M600,0 L100,0 L",100 + 100 / tan(($angle_one / 180)* PI()),",100 L",600 - 100 / tan(($angle_two / 180)* PI()),",100 L600,0 z"), 		CONCATENATE( "M550,100 L150,100 L100,50 L150,0 L550,0 L600,50 z" )),TEXT,'<text x="350" y="50" style="font-size:60px;dominant-baseline:middle;text-anchor:middle;">' + $length + "=" + $count + " " + if($size_type == 0,'90°','45°') + "</text>", '<svg width="150" height="30" viewBox="100 0 600 100"><path stroke="black" stroke-width="3" fill="none" fill-rule="evenodd" fill-opacity="1" d="' + pathStr + '"></path>' + TEXT + '</svg>')

能不能类似的搞一下，因为我们有些需要显示svg图片

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持svg图片

**Comment by a67757954** [comment]
一句不支持就完了，以前还遇到问题去解决，现在你们团队怎么这样了呢？
