### ISSUE TITLE
部分报表调用导出pdf接口会报错

### ISSUE THREAD

**Issue by cocoamu** [jeecgboot/JimuReport#1613]
##### 版本号：
1.5.6

##### 问题描述：
部分报表调用导出pdf接口会报错

##### 错误日志&截图：

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/11717549/216250306-79c0b1d7-fd7a-4f18-8b11-22848c97d1e6.png">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
这不是文件没找到吗？
