### ISSUE TITLE
docker部署jimureport报错

### ISSUE THREAD

**Issue by zhanghahahahahaha** [jeecgboot/JimuReport#1614]
##### 问题描述：
按照官方提供的部署步骤 http://report.jeecg.com/2368854
在执行到第四步时报错
![image](https://user-images.githubusercontent.com/108739923/216259249-240ccba7-fa82-4511-a810-99e5984d6926.png)

##### 错误日志&截图：
报错截图：
![image](https://user-images.githubusercontent.com/108739923/216259334-e25ac8de-e866-4475-a2f9-6986966bcbae.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by JasonZhangNICE** [comment]
mark 同样的错误，请问后来是否解决？
