### ISSUE TITLE
PDF导出接口 jmreport/exportPdf 是否所有版本都已停用？

### ISSUE THREAD

**Issue by like-mc** [jeecgboot/JimuReport#1615]
##### 版本号：
1.4.4-beta、1.5.0、1.5.4三个版本

##### 问题描述：
PDF导出接口 jmreport/exportPdf 是否所有版本都已停用？包括1.4.4-beta版本

##### 错误日志&截图：
PDF导出接口 jmreport/exportPdf 是否所有版本都已停用？包括1.4.4-beta版本

##### 重现步骤：
PDF导出接口 jmreport/exportPdf 是否所有版本都已停用？包括1.4.4-beta版本

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
是的
