### ISSUE TITLE
报表钻取参数不传递

### ISSUE THREAD

**Issue by xiaoxiao-xx** [jeecgboot/JimuReport#1616]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/40261157/216281977-65a6212c-a0c8-4174-bebe-edc5dabfc759.png)
![image](https://user-images.githubusercontent.com/40261157/216282130-f8757c06-c91e-487a-b29b-7ad68d58595c.png)
![image](https://user-images.githubusercontent.com/40261157/216282210-e739b196-1d3d-4c19-b9ce-802745894d66.png)

##### 重现步骤：
1.单元格设置数值
2.超链接设置添加钻取报表
3.单元格其他设置，小数位2位

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布。分组暂不支持
