### ISSUE TITLE
SpringBoot按照官网集成后启动报错

### ISSUE THREAD

**Issue by shengxutan** [jeecgboot/JimuReport#1617]
##### 版本号：
1.5.6

##### 问题描述：

SpringBoot按照官网集成后启动报错，只引入了一个依赖，是否还需要引入其他依赖
                <dependency>
			<groupId>org.jeecgframework.jimureport</groupId>
			<artifactId>jimureport-spring-boot-starter</artifactId>
			<version>1.5.6</version>
		</dependency>
##### 错误日志&截图：

java.io.FileNotFoundException: class path resource [org/jeecgframework/minidao/aspect/EmptyInterceptor.class] cannot be opened because it does not exist
##### 重现步骤：

集成启动就报错
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档：https://help.jeecg.com/jimureport/projectJoin/springboot.html
