### ISSUE TITLE
在官网上看到积木是支持达梦数据库的，但是没有提供达梦的脚本，所以想确定一下通过mysql的数据库脚本转成达梦，程序上是否都能正常运行

### ISSUE THREAD

**Issue by xuechangjin** [jeecgboot/JimuReport#1618]
##### 版本号：

1.5.6

##### 问题描述：
在官网上看到积木是支持达梦数据库的，但是没有提供达梦的脚本，所以想确定一下通过mysql的数据库脚本转成达梦，程序上是否都能正常运行

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
应该可以，我们说的兼容是指，兼容达梦数据库作为数据源
