### ISSUE TITLE
保存CSS增强时报错

### ISSUE THREAD

**Issue by wangleigithub** [jeecgboot/JimuReport#1619]
##### 版本号：
1.4.0

##### 问题描述：
保存CSS增强时报错
![image](https://user-images.githubusercontent.com/755879/216506837-39676fc5-bfb9-4c2a-95c2-cc1a6a62037e.png)

##### 重现步骤：
1.从1.3.78升级到1.4.0
2.db使用oracle11

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级sql执行了吗，看后台有没有报错信息
