### ISSUE TITLE
官网创建的报表链接,删除后仍然可以访问,请问需要怎么删除

### ISSUE THREAD

**Issue by guozhengshun** [jeecgboot/JimuReport#1620]
##### 问题描述：https://bootapi.jeecg.com/jmreport/shareView/*************
在官网创建这样链接的报表,现在不使用了 删除掉了 但是链接还能访问,请问怎么删除

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
