### ISSUE TITLE
积木报表不支持交叉报表

### ISSUE THREAD

**Issue by zhouwanfeng** [jeecgboot/JimuReport#1622]
##### 版本号：
1.5.6

##### 问题描述：
本版本是否交叉报表？
1、培训视频中，交叉报表设计表头时，高级选型中 有 循环表头
2、1.5.6 版本 没有循环表头
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
支持
