### ISSUE TITLE
刚好一页的时候， 多出一个表头 表尾

### ISSUE THREAD

**Issue by yuzzzzzzzz** [jeecgboot/JimuReport#1624]
##### 版本号：

1.5.6
##### 问题描述：
打印的时候 固定表头 表尾，如果刚好一页的时候， 会多出一页表头 表尾。还有就是是否支持页内小计

##### 错误日志&截图：

![BT$4JCB(%M5PS3JJRCD}THJ](https://user-images.githubusercontent.com/124644743/217128327-1713fcdb-5beb-4462-806a-a3c6269c6fea.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by zhangdaiscott** [comment]
这是预览还是打印？
