### ISSUE TITLE
积木报表是否可以根据单元格内容设置背景色

### ISSUE THREAD

**Issue by Midimaster** [jeecgboot/JimuReport#1625]
##### 错误日志&截图：

<img width="814" alt="2d92066feceb43e2c2f0d07994751cb" src="https://user-images.githubusercontent.com/44290303/217208473-924f2110-66e0-463c-9cbc-1089fe70981b.png">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档：https://help.jeecg.com/jimureport/function/condition.html
