### ISSUE TITLE
提一个机制的问题，sql和查询条件是否同时执行

### ISSUE THREAD

**Issue by shenbushou** [jeecgboot/JimuReport#1626]
##### 版本号：
1.8 积木报表

##### 问题描述：

遇到一个问题，在数据库的数据量过大的时候，我给时间参数一个默认值，也无法查询出结果。
我想问，积木在执行查询sql时，是否将参数默认值传入sql后再执行。
还是先查询sql语句，再把查询条件作为筛选条件进行过滤。
如果是前者我不能理解为什么查不出数据，如果是后者我可以理解。

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
目前参数直接在sql拼接上了，你是怎么配置的，积木报表没有1.8版本号
设计页面：
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/4c3570b0-cf8d-45c7-a516-8a0a77167726)
预览页面
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/096a11cf-fafe-4150-ab3f-08906405eb69)

直接拼接sql查询
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/0c3beeb4-390c-4889-9de2-c975f2c2f5a0)
升级到1.6.1再试一下
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.6.1</version>
</dependency>
```
