### ISSUE TITLE
循环块打印内容出错

### ISSUE THREAD

**Issue by filicat** [jeecgboot/JimuReport#1627]
##### 版本号：
1.4.32

##### 问题描述：
我设计了一个循环块
![image](https://user-images.githubusercontent.com/43430296/217396292-04df6f0e-f614-47ed-96d8-e05e0a2cd097.png)
预览内容正常
![image](https://user-images.githubusercontent.com/43430296/217396440-88830640-f316-4b27-b6ec-eec7397c69f7.png)
但是用Canvas打印的时候，隔几页就会发现条形码的内容出错了

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/43430296/217397100-c796314a-7429-416f-8b4e-5271306c4d10.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级新版本看看是否还有这个问题

**Comment by filicat** [comment]
> 升级新版本看看是否还有这个问题

积木报表可以单独升级吗？

**Comment by filicat** [comment]
> 升级新版本看看是否还有这个问题

积木报表可以单独升级吗？就是不升级jeecgboot只升级积木报表

**Comment by lvdandan16** [comment]
可以，只升级积木报表即可
