### ISSUE TITLE
在设计报表使用数据图表设置为SQL数据集无法运行更新并保存

### ISSUE THREAD

**Issue by yoqu** [jeecgboot/JimuReport#1629]
##### 问题描述：
在新建积木报表时，默认添加图表是使用的静态数据源。
当JSON数据切换至SQL数据集，当SQL数据集返回空的时候，会无法运行图标，且保存时依然使用的是JSON数据

##### 错误日志&截图：
<img width="1621" alt="image" src="https://user-images.githubusercontent.com/10415165/217411603-3d09d161-21a4-4b7a-bd29-29649bbf13dc.png">

##### 重现步骤：
1. 添加图表。
2. 切换至SQL数据集。
3. 点击运行提示报错。
4. 点击保存按钮无法保存SQL数据集的配置。

解决办法：

<img width="782" alt="image" src="https://user-images.githubusercontent.com/10415165/217411900-cd3b5e09-c40c-4650-a39c-61f0338f9fc6.png">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录ws

**Comment by lsqGitHub716** [comment]
已修改
