### ISSUE TITLE
echarts 提示框的位置问题

### ISSUE THREAD

**Issue by chenfantech0815** [jeecgboot/JimuReport#1630]
##### 版本号：
V1.5.6

##### 问题描述：
echarts 提示框的显示位置再 靠页面上面时 将被遮住。 提示框 应该是根据 鼠标的位置 变换 提示框的显示位置。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/42404741/217740809-2798aabe-2384-4c7a-94fd-2009e7b320ca.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
已修改
