### ISSUE TITLE
参数的宽度怎么调整

### ISSUE THREAD

**Issue by chenfengZ** [jeecgboot/JimuReport#1631]
##### 版本号：
V1.5.6

##### 问题描述：
参数的宽度怎么调整，现在一行上的参数太多了，一行6个参数
##### 错误日志&截图：
![1675927171051](https://user-images.githubusercontent.com/32896911/217744197-e857e7b0-5565-4dac-9bcd-1f5bf3ba9222.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
已修改
