### ISSUE TITLE
积木报表垂直居中问题

### ISSUE THREAD

**Issue by Midimaster** [jeecgboot/JimuReport#1633]
##### 错误日志&截图：
<img width="662" alt="9b1e91331fda552052c0826567ff9a0" src="https://user-images.githubusercontent.com/44290303/217979182-9b87a29d-fc69-4b1e-b3fa-f969e3009d1c.png">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
有什么问题，没看出来？

**Comment by lsqGitHub716** [comment]
请详细截图描述一下你要实现的功能和复现步骤
