### ISSUE TITLE
希望增加一个api数据集刷新的

### ISSUE THREAD

**Issue by Yxw521** [jeecgboot/JimuReport#1634]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/76502207/217988983-4c1bf2d9-927a-477a-9f6f-9f7dcb60ffcb.png)
![image](https://user-images.githubusercontent.com/76502207/217989139-b84e2a4c-484a-4b8c-ab3b-3e0829d93b68.png)

##### 重现步骤：
希望列表和图表一样有个定时刷新的

**Comment by lvdandan16** [comment]
归集
