### ISSUE TITLE
设计器中，右击没有“循环块”选项

### ISSUE THREAD

**Issue by wenhao0514** [jeecgboot/JimuReport#1635]
##### 版本号：
1.5.6

##### 问题描述：
设计器中，右击没有“循环块”选项，是否有相关的开关还是需要怎么设置？

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/40976549/217989794-8cbef883-e322-42a5-92d6-311f174517b9.png)

##### 重现步骤：
1、新建设计器
2、固定部分行数据
3、选中行后，右击，没有出现“循环体”选项

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by kava-hchaojie** [comment]
同样，对着视频看了，摸索了半天，也没找到这个循环在哪里？坑~~

**Comment by LiLulin12** [comment]
条幅能滑动 , 向下滑就有了
