### ISSUE TITLE
关于报表页面展示与导出excel样式不一致问题的补充

### ISSUE THREAD

**Issue by XTLidp** [jeecgboot/JimuReport#1646]
##### 版本号：
1.5.6

##### 问题描述：
1.5.6版本去掉了导出excel前几列的边框，后面几列的边框还是存在。
##### 错误日志&截图：
1.5.4版本效果：
![image](https://user-images.githubusercontent.com/78455429/219540656-282002c4-fe96-4458-bbe4-d44a153b0cdc.png)
1.5.6版本效果：
![image](https://user-images.githubusercontent.com/78455429/219540802-e8eb1e55-ea17-48f7-a6f1-69ed5bd805cc.png)
预览效果：
![image](https://user-images.githubusercontent.com/78455429/219540978-74ae5380-6091-44a5-b9c9-dfeaed050228.png)

##### 重现步骤：
单元格有内容就会出现这个问题。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by AXXZSTHL** [comment]
我也遇到这个问题，之前用1.4版本的导出都是没问题，现在1.5版本后都有导出excel表格错乱的问题，很头疼啊

**Comment by 1298191366** [comment]
已修复，待新版本发布
