### ISSUE TITLE
重新设置循环块导致前端渲染不出来

### ISSUE THREAD

**Issue by 563427956** [jeecgboot/JimuReport#1648]
##### 错误日志&截图：
浏览器端请求:
![image](https://user-images.githubusercontent.com/53893965/219851096-5e87a8e8-f52b-4060-bde3-381668cecda9.png)
后端错误:
![image](https://user-images.githubusercontent.com/53893965/219851129-ff5f278e-339e-44d3-af6b-ad7bc69e70c5.png)

##### 重现步骤：
1.编辑页面取消循环块后保存
2.重新框选循环块设置后保存
3.预览无法渲染 , 后端报错

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；
[report-export-mysql.txt](https://github.com/jeecgboot/JimuReport/files/10773721/report-export-mysql.txt)

**Comment by 563427956** [comment]
更换了最新的1.5.6版本也是同样的问题

**Comment by unfairfair** [comment]
数据库中的模板json  清除下循环块后 重新设置下 试试。 
 表jimu_report 中字段json_str中将loopBlockList设置为空数组
   "loopBlockList":[]

**Comment by 563427956** [comment]
> 数据库中的模板json 清除下循环块后 重新设置下 试试。 表jimu_report 中字段json_str中将loopBlockList设置为空数组 "loopBlockList":[]
你好 , 按照你说的在数据库把 loopBlockList设置成空数组后 重新框选循环块, 结果是一样的 还是渲染不出来

**Comment by unfairfair** [comment]
之前我也遇到类似的情况，清空loopBlockList后再设置即可。

目前根据你的说的情况，我看了下反编译的源码 ，org.jeecg.modules.jmreport.desreport.render.a.a#a(com.alibaba.fastjson.JSONObject, com.alibaba.fastjson.JSONObject, int)

应该是 `loopBlockRows`没有值导致的。

![image](https://user-images.githubusercontent.com/25562282/220236543-ce1ec74b-5dae-4a8d-af5e-634dfbd7b540.png)

我使用的jimu 版本是 1.5.4，也许反编译出来的跟你的不一样。

你可以使用JD-GUI反编译查看后再定位试试。。

**Comment by lvdandan16** [comment]
重新设计一个看看可以吗
