### ISSUE TITLE
合并单元格并设置单元格格式为条形码或二维码时，在某些样式下无法导出pdf

### ISSUE THREAD

**Issue by unfairfair** [jeecgboot/JimuReport#1649]
##### 版本号：
1.5.4

##### 问题描述：
合并单元格并设置单元格格式为条形码或二维码时，在某些样式下无法导出pdf

##### 错误日志&截图：
可导出样式截图（单元格C3设置有值时）：
![image](https://user-images.githubusercontent.com/25562282/220005800-eb8360ab-61b4-433c-9032-5a919bf83d40.png)
导出样式预览及导出按钮：
![image](https://user-images.githubusercontent.com/25562282/220005969-b2e4eb55-b8e6-4e2b-9bb6-ceef25a300d8.png)

无法导出PDF时截图（单元格C3未设置值时）：
![image](https://user-images.githubusercontent.com/25562282/220006032-d3eb771e-5ac8-4d5d-87c6-d4ca073b951e.png)
导出样式预览及导出按钮：
![image](https://user-images.githubusercontent.com/25562282/220006221-0c59f8cb-0c45-4539-96ae-3f089d4675ae.png)

无法导出时后端报错信息：
![image](https://user-images.githubusercontent.com/25562282/220006295-d65ab3fb-33ad-4c23-b063-e5eb28d4d65f.png)

##### 重现步骤：
  同上一步骤中不设置C3单元格数值的场景

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Aggressive-head** [comment]
+1。有时合并的单元格中生成条码会导致导出PDF失败，有时在条码后一个单元格加上任意内容后又可以导出了。

**Comment by lvdandan16** [comment]
收录 ty
