### ISSUE TITLE
关于序号自增的疑问

### ISSUE THREAD

**Issue by liquanyou** [jeecgboot/JimuReport#1652]
##### 版本号：
1.5.2

##### 问题描述：

场景：目前支持的序号自增（行号函数row()）是当前页的行号，有什么方法能做到序号不受分页的限制一直累加，以解决当前此类需求问题

##### 错误日志&截图：
![1676950605318](https://user-images.githubusercontent.com/32211459/220241273-43c7e8cd-af6e-4065-a271-a5c9e00d1027.png)

##### 重现步骤：
1.创建一张报表（分页，每页10条或者其他）
2.使用行号函数 =row()
3.最大行号即是页数

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
使用表达式序号，就是每页显示序号，如果想分页增加，可以在sql中直接返回序号
