### ISSUE TITLE
添加数据源的过程中出现insert报错

### ISSUE THREAD

**Issue by happyuanhao** [jeecgboot/JimuReport#1653]
##### 版本号：
1.5.6

##### 问题描述：
我在添加数据源时，选择好需要用的数据后，进行确认操作时报错，插入错误，请官方帮助解决一下。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/25651702/220561652-96d8933e-0fb7-4ec9-b6f4-31a2b9119b6d.png)

##### 重现步骤：
我的项目是springboot2 集成积木报表来用，环境：idea+mysql驱动使用的是5.1.47  
操作步骤就是 访问 jmreport/list →创建新报表→添加mysql数据源→确认→报错 如上图所示 insert插入错误，

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
未复现此问题
