### ISSUE TITLE
打印设计

### ISSUE THREAD

**Issue by ricardoM8** [jeecgboot/JimuReport#1654]
##### 版本号：
1.5.4

##### 问题描述：
我要做一个收货单的打印，每页只打印五条数据，但是我点打印还是打印的全部

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/119491351/220583798-4a4fdddc-7cc3-4f85-947e-94c286150f5a.png)
![image](https://user-images.githubusercontent.com/119491351/220583969-ce9d30fe-f544-4ec0-8449-d4e34fe43b9b.png)
![image](https://user-images.githubusercontent.com/119491351/220584112-715d4785-efba-4fa3-9b27-3fdab2f54b60.png)

##### 重现步骤：
我用的sql数据集，页面上设置的分页，预览看的和实际打印的页面不一样

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
先升级到最新版看看

**Comment by lvdandan16** [comment]
打印不支持分页，打印时即打印全部数据
