### ISSUE TITLE
循环块中插入二维码打印异常分页

### ISSUE THREAD

**Issue by wangzhongkui** [jeecgboot/JimuReport#1655]
##### 版本号：
1.5.6

##### 问题描述：
报表打印设计中插入循环块，块中插入二维码。打印时会出现异常分页。条形码正常，文本正常。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/17774187/220795562-2fefd31b-6c04-465c-bcc2-b15ee85f8f55.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by wangzhongkui** [comment]
这个产品是不是要倒闭了，这么多iuse提问没有人回复。不开源圈用户，把用户当作测试牺牲品。

**Comment by KaherineZXL** [comment]
> 这个产品是不是要倒闭了，这么多iuse提问没有人回复。不开源圈用户，把用户当作测试牺牲品。

不知道呢，我过一段时间就来看看我的问题是否有回复，是否修复

**Comment by lvdandan16** [comment]
收录 ty

**Comment by lnmlnm** [comment]
其实不设循环块也这样

**Comment by liaozhiyang** [comment]
已解决，升级到最新版本。

**Comment by yangShengXin** [comment]
我也是这样，坑的一批啊
