### ISSUE TITLE
模板设计时设置好的字体, PDF导出无效

### ISSUE THREAD

**Issue by Jermy-Yao** [jeecgboot/JimuReport#1656]
##### 版本号：
1.5.6

##### 问题描述：
模板设计好的字体(楷体), PDF导出后, 字体设置无效

##### 错误日志&截图：
![WX20230227-111850](https://user-images.githubusercontent.com/17076914/221465152-b30fcb62-9c79-46ae-960c-d856226eb8d5.png)
![WX20230227-111915](https://user-images.githubusercontent.com/17076914/221465165-ac884381-0b6a-4e01-983b-a7e134e51c06.png)

##### 重现步骤：
1. 模板设计时, 设置为其他字体后保存; 
2. 导出PDF后, 字体设置无效;

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by ErosHel** [comment]
1.5.8依然是这样

**Comment by lvdandan16** [comment]
导出pdf默认宋体，不会按设计字体导出
