### ISSUE TITLE
“SQL解析” 空表时报500

### ISSUE THREAD

**Issue by dragonzoebai** [jeecgboot/JimuReport#1658]
##### 版本号：
1.5.4

##### 问题描述：
“SQL解析” 空表时报500

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/5774016/221768491-46215ee3-2c14-41c4-84f4-1c6661f806c0.png)

##### 重现步骤：
数据库中建一张空表，没有数据，在积木报表新建数据集时“SQL解析”报错

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版发布。您需要有数据，字段才会解析出来
