### ISSUE TITLE
Api返回结果里面有嵌套的集合怎么在报表中展示出来？

### ISSUE THREAD

**Issue by tb2888** [jeecgboot/JimuReport#1659]
##### 版本号：

1.5.6
##### 问题描述：

如图Api返回结果是集合，里面有嵌套的集合怎么在报表中展示出来？
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/55084864/222081067-401e2922-ca29-42f7-9b0e-7e5ae8eb2e10.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by tzwhyqq** [comment]
我以前问过，不支持，只能分开写2个接口一个主数据，一个明细。

**Comment by lvdandan16** [comment]
不支持嵌套集合
