### ISSUE TITLE
springboot 2.3.5-RELAESE 预览报表界面接口 jmreport/getQueryInfo 返回为空导致一直加载

### ISSUE THREAD

**Issue by RongLiXu** [jeecgboot/JimuReport#1660]
##### 版本号：
jimureport: v1.5.6
spring-boot-starter-parent: 2.3.5-RELAESE

##### 问题描述：
springboot 2.3.5 升级使用 jimu 1.5.6，在进入报表预览界面（http://[localhost:8081/[项目名称]/jmreport/view/784373301895954432?token=）一直加载中，查看浏览器控制台和网络，是因为接口jmreport/getQueryInfo 返回值为空

##### 错误日志&截图：
加载页面：
<img width="669" alt="image" src="https://user-images.githubusercontent.com/32008882/222410512-b521cbf1-eb1e-48c6-b704-7b2da56f37cc.png">
浏览器控制台：
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/32008882/222410396-acdad01f-177e-4795-986b-4270e4345c1d.png">
view.js：
<img width="658" alt="image" src="https://user-images.githubusercontent.com/32008882/222410776-6db4710b-6e5a-43c4-a02d-bf155edd15e3.png">
接口返回值：
<img width="776" alt="image" src="https://user-images.githubusercontent.com/32008882/222410931-466dd4b4-4303-4fb9-bdd8-06eaacaba60b.png">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by RongLiXu** [comment]
<img width="597" alt="image" src="https://user-images.githubusercontent.com/32008882/222620649-eb607e7e-d00a-4407-8008-694d1bc9211c.png">
回到一个正常可用的jimureport版本1.3.7时，查看区别，前端在此处对返回结果进行判断后在进行后续代码执行

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
