### ISSUE TITLE
官网的 报表设计器 设计只能 64行吗

### ISSUE THREAD

**Issue by WJME** [jeecgboot/JimuReport#1661]
报表设计器 设计只能 64行吗， 没有看到能在添加新行的地方

![image](https://user-images.githubusercontent.com/32950488/222626988-4a216be1-6c03-45ad-8655-5ef28d7cdb4a.png)

**Comment by care98** [comment]
![image](https://user-images.githubusercontent.com/46066901/223590282-e10c477b-c6dc-4e86-aae3-bd843f73b6cb.png)
右键插入行试试
