### ISSUE TITLE
导入图片，打印出现空白页问题

### ISSUE THREAD

**Issue by KaherineZXL** [jeecgboot/JimuReport#1662]
##### 版本号：

1.4.42  - 1.5.6
##### 问题描述：
页面通过工具栏导入图片的时候，打印预览会多出一行空白页。把图片拿掉就没有空白页
![image](https://user-images.githubusercontent.com/120431879/222647951-6df6bef9-5c88-4db5-95db-93291a743fa8.png)

##### 错误日志&截图：

没有图片上传的
![image](https://user-images.githubusercontent.com/120431879/222648113-3a58dc92-7fa4-40b8-bd6c-fb850cefa841.png)

![image](https://user-images.githubusercontent.com/120431879/222648204-a5c7e802-352b-41ca-a565-093860e15aa6.png)

有图片上传的
![image](https://user-images.githubusercontent.com/120431879/222648493-2b6b3798-308e-42ab-b3da-d204078a87be.png)

![image](https://user-images.githubusercontent.com/120431879/222648678-e95ed66b-94c0-41d0-8203-4a0bf5933ae1.png)

##### 重现步骤：
行数只有13行，不可能是因为空白行造成的
![image](https://user-images.githubusercontent.com/120431879/222647897-872b6ddc-0609-4e26-958b-feced30d27bf.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by zhangdaiscott** [comment]
已经处理了，下个版本发布
