### ISSUE TITLE
excel导出自定义背景色有问题

### ISSUE THREAD

**Issue by yangjunzhou861012** [jeecgboot/JimuReport#1664]
##### 版本号：
1.5.6

##### 问题描述：
当excel设置自定义的背景色，则excel导出的背景色会出现密密麻麻的小方格，导致字都看不清

##### 错误日志&截图：
自定义的背景色样式，背景色样式是（rgb(242, 249, 255)）：
![image](https://user-images.githubusercontent.com/18575974/223007901-dabcb329-07e6-42da-a0e8-7626f46d38db.png)
预览的样式：
![image](https://user-images.githubusercontent.com/18575974/223007963-dedd8acd-f3a5-461c-b263-e41e4f626b73.png)

导出后的excel样式：
![image](https://user-images.githubusercontent.com/18575974/223007587-c712c133-d263-4dda-9fb0-75fbea604b08.png)

##### 重现步骤：
步骤一：
点击新建报表
步骤二：
输入表头名称（随便输入几个字），然后设置
步骤三：
选中表头，然后点击填充颜色按钮，输入自定义颜色：rgb(242, 249, 255)
步骤四：
点击预览，然后点击excel，会发现excel的表头中填充颜色有问题，跟预览的不一致，会出现很多密密麻麻的小方格

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
导出不支持样式
