### ISSUE TITLE
积木报表功能

### ISSUE THREAD

**Issue by hfsunnyhy** [jeecgboot/JimuReport#1665]
##### 问题描述：能否满足如下功能：为实现各级用户宏观、统筹的管理需求，研发通用型统计报表组件，根据不同角色、不同工
程类型、不同需求进行灵活配置，满足用户对于多项运行管理情况、不同维度的查阅。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持，没有角色
