### ISSUE TITLE
查询下拉多选获取不到数据，后台报错

### ISSUE THREAD

**Issue by snkever** [jeecgboot/JimuReport#1666]
##### 版本号：
1.5.6

##### 问题描述：

查询下拉多选获取不到数据
##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/28818320/223068865-71e4c78c-d6f3-4e1d-bd9d-128024722fd5.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
接口问题吧
