### ISSUE TITLE
人民币金额转大写的时候；如果后缀金额为.78，转成大写为柒角柒分;以及.68，分也会转成七

### ISSUE THREAD

**Issue by lewskay** [jeecgboot/JimuReport#1673]
##### 版本号：
jimureport-spring-boot-starter 1.5.6

##### 问题描述：
人民币金额转大写的时候；如果后缀金额为.78，转成大写为柒角柒分

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/27395320/223625870-00fabc23-3d73-46a1-b540-d471d89aba67.png)
![image](https://user-images.githubusercontent.com/27395320/223625905-a5022364-0ff4-4cfa-9368-49d2f95dc8fb.png)

**Comment by NapChen** [comment]
后面加个单位更离谱，`=cnmoney(0.79,"bw")`会被转为`柒拾捌万玖仟玖佰玖拾玖元玖角玖分`

**Comment by lvdandan16** [comment]
收录 ws

**Comment by tygithub1** [comment]
小数请带上引号，直接写相当于是double类型了，精度控制不了
`=cnmoney('0.79',"bw")`
