### ISSUE TITLE
报表插入本地图片时图片上传请求头未带token

### ISSUE THREAD

**Issue by NapChen** [jeecgboot/JimuReport#1674]
##### 版本号：
1.5.6

##### 问题描述：
在报表中插入图片时，请求头未携带token，导致请求失败

##### 错误日志&截图：
![WX20230309-143200@2x](https://user-images.githubusercontent.com/19644794/223940327-2e1c3a8f-f0a6-4d2c-8bf3-12d6ed0bb921.png)
![WX20230309-143221@2x](https://user-images.githubusercontent.com/19644794/223940613-2351bbe8-16e1-4ef6-8d05-ab741ad53e56.png)

##### 重现步骤：
实现JmReportTokenServiceI接口，发起其他请求都携带了token头，上传文件时查看请求头发现没有token。

**Comment by lvdandan16** [comment]
收录 ws

**Comment by zhangdaiscott** [comment]
下个版本发布
