### ISSUE TITLE
积木报表制作的统计报表，如何实现列冻结和标题行冻结？

### ISSUE THREAD

**Issue by bhwhongwei** [jeecgboot/JimuReport#1675]
##### 版本号：
1.5.4

##### 问题描述：
如何实现统计报表列冻结和标题行冻结

##### 错误日志&截图：

![a6664e00a166ed84484d1db3b4b37b6](https://user-images.githubusercontent.com/127398704/224000277-49406ec0-afea-4745-b8b5-55bdd06b30e7.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by bhwhongwei** [comment]
技术大拿帮帮忙

**Comment by minitiger1974** [comment]
同问

**Comment by lvdandan16** [comment]
不支持
