### ISSUE TITLE
关于运行时修改API数据集的问题

### ISSUE THREAD

**Issue by mexhfl** [jeecgboot/JimuReport#1676]
##### 问题描述：

如果按格式转换器方式修改API数据解析规则，是不是每次新增一种解析规则，都需要改代码更新程序？
我这边的使用场景是，需要经常增加API数据集解析规则，如果能运行时增加解析规则就方便很多，是否有办法实现运行时修改API数据？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
目前只能通过这种方式来实现
