### ISSUE TITLE
关于API数据集解析问题

### ISSUE THREAD

**Issue by Barry-lyp** [jeecgboot/JimuReport#1678]
请问各位大佬，解析API数据集时，API接口的数据格式也都是和示例中一样的，但就是无法解析，API接口在浏览器是正常输出的。

浏览器中接口返回数据格式如下：
<img width="534" alt="image" src="https://user-images.githubusercontent.com/57979846/224262110-17571137-b4f3-43c1-8261-ae930d956772.png">

但是在API数据集中解析时，提示如下：
<img width="817" alt="image" src="https://user-images.githubusercontent.com/57979846/224262389-25119bfa-7b26-4a5c-a1e6-08c3874cb193.png">

控制台报错比较费解，如下：
![image](https://user-images.githubusercontent.com/57979846/224263486-d1ec4323-9a2f-4384-9e26-febad8006eff.png)

**Comment by Barry-lyp** [comment]
已经知道原因了，哈哈，不占用资源了，管了。

**Comment by 798076849** [comment]
你好，我和你有一样的问题，请问你怎么解决的

**Comment by Barry-lyp** [comment]
> 



> 你好，我和你有同样的问题，请问你怎么解决的

1、不要用localhost，如果有测试服务器可以用服务器iP去访问，或者使用内网穿透工具去生成一个网址。
2、创建一个自己的转换器类，实现ApiDataConvertAdapter接口(如果自己返回的参数与JEECG的不同的话)。
