### ISSUE TITLE
sql注入问题

### ISSUE THREAD

**Issue by 1010830256** [jeecgboot/JimuReport#1679]
##### 版本号：
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.5.6</version>
</dependency>

##### 问题描述：
存在sql注入风险

##### 错误日志&截图：
<img width="1465" alt="image" src="https://user-images.githubusercontent.com/32806860/224493775-90a7ea11-85fc-473d-bd54-5dc9c7f40c2b.png">

##### 重现步骤：
1. 填写sql的第一行打回车
2. 从第2行开始写update或者insert或者delete语句
3. 点击sql解析按钮
4. 虽然会报错，但是db已经执行了上述的sql注入

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by tygithub1** [comment]
已修改
