### ISSUE TITLE
交叉报表导出excel失败

### ISSUE THREAD

**Issue by qbsoft** [jeecgboot/JimuReport#1680]
##### 问题描述：
![image](https://user-images.githubusercontent.com/32183596/224596997-b13b6b99-de0b-4050-ab2f-6cdf96e578a3.png)

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/32183596/224596817-ece777d4-bb2d-4832-8ffe-68301d5df3d4.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
与 [#1696 ](https://github.com/jeecgboot/JimuReport/issues/1696)问题一样，关闭此问题
