### ISSUE TITLE
单元格表达式：多个 sum() 加减乘除不支持

### ISSUE THREAD

**Issue by xuanjinnan** [jeecgboot/JimuReport#1683]
##### 版本号：
<version>1.5.4</version>

##### 问题描述：
工作中汇总的值计算要用到除法，需要分子的和除以分母的和，不支持

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/39610746/224678458-a5733d0a-3655-4824-bcef-dd3f56cb9cef.png)
![image](https://user-images.githubusercontent.com/39610746/224678773-bb1d72bd-c9c0-47ad-b068-750f694b0014.png)
直接多个 sum 函数相加也是有问题，加的是第一行的数据
![image](https://user-images.githubusercontent.com/39610746/224679622-a3d2c191-0d48-4167-a580-3cfca763053a.png)
![image](https://user-images.githubusercontent.com/39610746/224680295-28653c9c-198b-4fcb-9edb-ae8137c0f355.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
