### ISSUE TITLE
同行不能显示两个数据集的数据吗？

### ISSUE THREAD

**Issue by happyuanhao** [jeecgboot/JimuReport#1684]
##### 版本号：
1.5.6

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/25651702/224881347-c6025c76-d348-48f6-9f3c-e62ec8d8a311.png)
![image](https://user-images.githubusercontent.com/25651702/224881378-d9f1e466-7a9e-4ae5-b335-ad626017ad05.png)
![image](https://user-images.githubusercontent.com/25651702/224881435-8371a2e9-5d84-4c52-87c8-464c90112485.png)
![image](https://user-images.githubusercontent.com/25651702/224881497-8490c82e-366a-48cb-b855-b5e2fc5d5315.png)

##### 重现步骤：

我添加了两个查询数据集，表格中需要在同一行显示两个数据集的相关信息，这两个数据集都是单条数据，在我把两个查询的字段放在同一行时，却只能显示其中一个数据集的数据，如上图所示，一个数据集是zh.xxx 一个 数据集是zl.xxxx 两个数据集无法同行显示，麻烦给回复一下 谢谢。
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持
