### ISSUE TITLE
图表钻取无法选择原始参数

### ISSUE THREAD

**Issue by gaojidong** [jeecgboot/JimuReport#1685]
##### 版本号：
1.5.6

##### 问题描述：
图表钻取不显示原始参数，api数据集

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/40835761/224961524-f51bdf9a-dfe6-4df7-bf63-fb884228ffbd.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
测试未复现您的问题，请尝试升级到最新版本后查看是否还存在问题![image](https://github.com/jeecgboot/JimuReport/assets/65587928/8f34ae16-b46b-4007-b4c0-bb6b7e742c2a)
