### ISSUE TITLE
excel导出失败

### ISSUE THREAD

**Issue by Lsatin** [jeecgboot/JimuReport#1688]
##### 版本号：
1.5.5

##### 问题描述：
打印设计 -> 导出 -> excel

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/34743318/225631978-97a5d899-c0fe-4ae7-82b8-d54b7ce13c1f.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Lsatin** [comment]
@zhangdaiscott

**Comment by lvdandan16** [comment]
升级autopoi包到4.1.2
