### ISSUE TITLE
缓存路由对积木报表不生效，切换tab之后，查询条件的值总是被重置为默认值

### ISSUE THREAD

**Issue by aidisheng** [jeecgboot/JimuReport#1689]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/34619741/225795577-484d1480-3836-4639-9459-055362e7c0ed.png)
![image](https://user-images.githubusercontent.com/34619741/225795615-c8584bee-c01e-4bf3-98fa-8a876ae79595.png)
![image](https://user-images.githubusercontent.com/34619741/225795642-8165b152-aa54-470f-a13e-dcb733cff7a3.png)
![image](https://user-images.githubusercontent.com/34619741/225795654-831331fd-3014-4455-a661-91bc3a4e3b8a.png)

##### 重现步骤：
1、给报表菜单设置缓存路由
2、访问报表功能，并修改查询条件为非默认值
3、访问其他功能，再切换回报表功能的标签
结果：报表功能的查询条件被重置为默认值，没有实现路由缓存保留查询条件的效果。

**Comment by lvdandan16** [comment]
目前是这样的
