### ISSUE TITLE
设计页面只能显示到AV列，后面其余列无法显示

### ISSUE THREAD

**Issue by abinnz** [jeecgboot/JimuReport#1690]
##### 版本号：
1.5.4

##### 问题描述：
上传excel超过AV列后，设计页面无法显示后面其余的列

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/13955662/225829756-ccfbba36-7bda-4da6-b71f-810fb2af3d3a.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 15518175448** [comment]
这个问题，你最后怎么处理的

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/jimureport/qa.html
34
