### ISSUE TITLE
在添加api数据集的过程中无故在api接口中莫名添加amp;字符，导致无法获取传参。

### ISSUE THREAD

**Issue by happyuanhao** [jeecgboot/JimuReport#1693]
##### 版本号：
1.5.6

##### 问题描述：
我在添加api数据集时，点击api解析，发现后台输出的api接口中的&字符后面莫名其妙的多出了**amp;** 这个字符导致我的参数无法接收到，从而导致json数据集无法获取到。

##### 错误日志&截图：
![8ccfb6bc16d0fbaf184a6022e8e2757](https://user-images.githubusercontent.com/25651702/225953331-cccc4506-336a-4592-af46-32c69b8ae65a.png)
![97073f8e018ac11b7fab2f718f0ac8c](https://user-images.githubusercontent.com/25651702/225953345-277089eb-a725-414b-9b97-fa6f9fc1774d.png)

##### 重现步骤：
第一张图是我的原始api接口，并且我通过postman进行了测试 是没问题的。
第二张图就是我点击api解析按钮后，后台输出的api接口中莫名其妙多出**amp；** 麻烦给解决一下谢谢。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by cjs3030** [comment]
我也遇到了，还有一个问题，不知道你遇到没，调用api接口时组装head头部(new HttpHeaders(); )会报Unable to evaluate the expression com.sun.jdi.VMMismatchException : instance of org.apache.tomcat.util.threads.TaskThread(name='http-nio-18080-exec-5', id=18808)，不知道这个有没有关系，导致获取业务JSON数据返回的数据格式和以前的不一样

**Comment by lvdandan16** [comment]
收录 ws

**Comment by happyuanhao** [comment]
此项问题 我已经解决，应该是项目自行转义的问题，请官方重点解决一下#1834 我所提出的问题 不管是在我个人项目中还是官网上的demo都存在这个问题，excel导出带不出在设计平台上保存的样式，我认为展示界面和导出的数据应该是 所见即所得的 这样带不出格式 导致我在生产实际应用中 无法给小数点补零 请官方重点看一下这个问题，谢谢。
