### ISSUE TITLE
点击新建报表没反应，前端报语法错误

### ISSUE THREAD

**Issue by li445970924** [jeecgboot/JimuReport#1694]
##### 版本号：
1.5.6

##### 问题描述：
点击新建报表没反应，前端报语法错误

##### 错误日志&截图：
![F 50P}@}(%M21J`27 7C2S9](https://user-images.githubusercontent.com/13675291/226235916-36b506da-7198-4f52-80cc-10b18e6763ec.png)

![W{NAZWY1K5~1_U4S`{XO FU](https://user-images.githubusercontent.com/13675291/226235961-671440dd-c50c-414d-8c52-2524218f0326.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
未复现此问题
