### ISSUE TITLE
excel交叉报表导出报错

### ISSUE THREAD

**Issue by cv-msan** [jeecgboot/JimuReport#1696]
##### 问题描述：
交叉报表导出excel时报错，去掉单元格斜线就可以正常导出

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/76542419/226285526-5f07fc9c-0900-4a42-9260-8a0dfc666465.png)
![image](https://user-images.githubusercontent.com/76542419/226285561-c2ed488b-28e5-44a0-8aa5-f3a3a2baaf43.png)
![image](https://user-images.githubusercontent.com/76542419/226285577-538591ae-ccd7-4872-99fa-c790ce598f00.png)

##### 重现步骤：
1.先做了一个交叉报表，然后做excel导出，然后前台显示导出失败，后台报错截图如上
2.去掉单元格斜线可以正常导出报表

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
