### ISSUE TITLE
系统上下文变量作用不稳定

### ISSUE THREAD

**Issue by hyzjz** [jeecgboot/JimuReport#1697]
##### 版本号：
1.5.0

##### 问题描述：
在报表设计中添加sql语句使用#{sysUserCode}，在设计器里预览没有问题，但是用我自己的系统登录后，无论用哪个账号登录，都会显示我在设计器里保存的用户名，如下图，图1中为语句示例，图2中为设计器中预览图片，图3为系统里查询报表展示。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/124112905/226504671-fa88733a-f16d-4a61-a3ac-75b21c4b4260.png)

##### 重现步骤：
![image](https://user-images.githubusercontent.com/124112905/226503978-c139f698-2fbc-4695-8968-4c6a9fa97015.png)
![1679365338529](https://user-images.githubusercontent.com/124112905/226504528-7584273e-3edf-41f2-9e97-0067774b346c.png)
![image](https://user-images.githubusercontent.com/124112905/226504607-33aa6e51-a060-4487-9d9f-d69b6a80c99f.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by zhangdaiscott** [comment]
这两个方法自定义了吗，自己加点输出日志，跟踪下

![image](https://github.com/jeecgboot/JimuReport/assets/3162115/beb6178f-be22-49c4-980e-82d726d03146)
