### ISSUE TITLE
表达式是否支持嵌套

### ISSUE THREAD

**Issue by hanfengcan** [jeecgboot/JimuReport#1698]
##### 问题描述：
我希望文本等于某个值的时候, 控制颜色。

输入以下公式的时候，执行报错：表达式渲染错误的单元格：K18,K19,K20,K21,K22
 
```
=color('#{tmp_report_data_income.biz_income}',case('#{tmp_report_data_income.biz_income}'=='非中石油','#AAA','#BBB'),'#171516')
```

##### 重现步骤：
使用demo里面的 实例:来源收入统计

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档：https://help.jeecg.com/jimureport/function/condition.html
