### ISSUE TITLE
积木报表循环块、分组问题

### ISSUE THREAD

**Issue by ys19950331** [jeecgboot/JimuReport#1699]
##### 版本号：

1.5.2
##### 问题描述：

图1是数据结构，图2是想实现的效果，请问各位大佬怎么实现，给点思路

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/44026939/226608920-9bef8822-895b-4e26-b9b3-0ea8ee5f3336.png)
![image](https://user-images.githubusercontent.com/44026939/226608994-eb6c6fe5-1d0a-40ac-951a-94336029357d.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lcpone** [comment]
问题解决没，我也遇到要实现这个效果的需求。

**Comment by lvdandan16** [comment]
这种分组方式不支持
