### ISSUE TITLE
一行只能有一个动态合并格 , 设置多个动态合并格只按照第一个的来合并

### ISSUE THREAD

**Issue by lzming9511** [jeecgboot/JimuReport#1706]
##### 版本号：

1.4.6
##### 问题描述：
一行只能有一个动态合并格 , 设置多个动态合并格只按照第一个的来合并

##### 错误日志&截图：
![微信截图_20230328094104](https://user-images.githubusercontent.com/26705045/228105012-61e29b91-2eb7-442f-ba68-b2f1e657456b.png)
![1679967814323](https://user-images.githubusercontent.com/26705045/228105102-c0770e6f-aa85-4546-8b1c-ee0e63ad6608.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
是1.5.6吗？ 没有1.4.6这个版本

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
