### ISSUE TITLE
前端预览表格报错

### ISSUE THREAD

**Issue by kukudehshuai** [jeecgboot/JimuReport#1707]
##### 版本号：
积木报表 版本1.5

##### 问题描述：
当我给表格添加样式后  大约8K条数据  前端报错 报表渲染不出来

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/73113771/228150032-75656dae-2a5a-49ba-9419-61ca98f9fc3a.png)
![image](https://user-images.githubusercontent.com/73113771/228150146-a4405d71-5960-41b8-8617-58794cd6df4e.png)

##### 重现步骤：
大约30个左右字段 ，当正常表格不加格式得时候 可以展现出来，当我在表格中填充颜色得时候 前端会报错卡死。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
报表数据分页查询试试
