### ISSUE TITLE
每次翻页都查询总数

### ISSUE THREAD

**Issue by kong6570** [jeecgboot/JimuReport#1708]
版本号：1.5.6

问题描述：
报表查询一个明细表，数据量比较大，直接在数据库执行翻页的sql，效率很快，但是实际操作翻页时间比较久，查询mysql的sql执行日志发现，每次翻页都会查询一次总数，猜测是这个问题导致的时间长的问题。是否可配置只查询一次总数

错误日志&截图：
![image](https://user-images.githubusercontent.com/7746804/228191069-729e6c3a-93ad-4413-9359-acc31a5d62ec.png)

友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by kong6570** [comment]
直接在数据集的报表sql外层包装select count(1) total  FROM ( ......) temp_count 
大数据量的报表会全表扫描，影响效率，建议可以调整下

**Comment by lvdandan16** [comment]
收录 ws

**Comment by lvdandan16** [comment]
归集 #138

**Comment by jeecgos** [comment]
已解决
