### ISSUE TITLE
在接入token的认证后，设计报表点击插入图片时并没有像其他接口一样带上token

### ISSUE THREAD

**Issue by LightInDark-s** [jeecgboot/JimuReport#1709]
##### 版本号：
1.5.6

##### 问题描述：
在接入token的认证后，设计报表点击插入图片时并没有像其他接口一样带上token

##### 错误日志&截图：
![1679996497955](https://user-images.githubusercontent.com/117820457/228196356-4685dfcf-c906-42a5-8508-8d1a9cdd2660.png)
![1679996507367](https://user-images.githubusercontent.com/117820457/228196385-3631672f-4752-4786-809a-1695d59102ff.png)

**Comment by lvdandan16** [comment]
收录 ws

**Comment by lvdandan16** [comment]
下个版本发布
