### ISSUE TITLE
导出excel，后缀多出.txt

### ISSUE THREAD

**Issue by yizhibaibai** [jeecgboot/JimuReport#1712]
##### 版本号：

1.5.6
##### 问题描述：
导出，文件后缀变成了xlsx.txt

##### 错误日志&截图：
![24%@8T}SVKG4K0HJLKA(SA7](https://user-images.githubusercontent.com/35802644/228734190-8bd1bc61-8a2a-4a0a-a679-cf1275b817db.png)
![~5EV_M}VHZ@T@V)HQZ3_335](https://user-images.githubusercontent.com/35802644/228734201-fc5c0355-1c1c-4400-9d14-70395aff0ce3.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
是导出的excel报错了吗

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
