### ISSUE TITLE
导出PDF失败

### ISSUE THREAD

**Issue by xiaoyurou** [jeecgboot/JimuReport#1713]
##### 版本号：
1.5.6

##### 问题描述：
导出pdf报错

##### 错误日志&截图：
2023-03-30 20:04:07.879 [http-nio-7001-exec-1] ERROR o.jeecg.common.exception.JeecgBootExceptionHandler:57 - Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: com.lowagie.text.Paragraph.add(Ljava/lang/String;)Z
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: com.lowagie.text.Paragraph.add(Ljava/lang/String;)Z
![image](https://user-images.githubusercontent.com/129394433/228832269-3c105694-8137-4614-87c5-90e5890870ff.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by unfairfair** [comment]
maven 依赖版本问题

**Comment by gitoftom** [comment]
这个解决了没有，我也遇到了，要引入什么版本才没问题？

**Comment by xiaoyurou** [comment]
com.lowagie.itext

**Comment by xiaoyurou** [comment]
> 这个解决了没有，我也遇到了，要引入什么版本才没问题？

我这边的是因为com.lowagie.itext版本冲突导致

**Comment by gitoftom** [comment]
引入openpdf依赖就没问题了        <dependency>
            <groupId>com.github.librepdf</groupId>
            <artifactId>openpdf</artifactId>
            <version>${openpdf.version}</version>
        </dependency>

**Comment by gitoftom** [comment]
1.3.27
