### ISSUE TITLE
时间默认值不回显到查询框

### ISSUE THREAD

**Issue by catlvsuger** [jeecgboot/JimuReport#1717]
##### 问题描述：时间默认值不回显到查询框
查询条件有值，点开时间查询框，也有选中，初始值不显示在查询框中

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/39261781/229662185-ffdb065c-cae4-4c2a-9134-cf7237247257.png)
![image](https://user-images.githubusercontent.com/39261781/229662267-3c8b3247-bd27-4de8-9a3c-70cf7c1449b7.png)
![image](https://user-images.githubusercontent.com/39261781/229662309-cf5e42ff-c085-4bef-adad-73904aa0f4a9.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by guozhiqiang-123** [comment]
查询模式设置为空就行

**Comment by 1298191366** [comment]
查询方式不用选择
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/381b90f2-190e-44eb-bbff-58d53e349f4d)

![image](https://github.com/jeecgboot/JimuReport/assets/30997828/413c93e2-8256-47e2-8e32-75cc0995c84c)
