### ISSUE TITLE
打印pdf中间空白，内容被分成两页

### ISSUE THREAD

**Issue by Mr-YW** [jeecgboot/JimuReport#1719]
##### 版本号：
1.5.6

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/75660892/230255674-e65383fc-74ce-4914-9b88-e8eaf54665ef.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
打印是根据纸张设置来的，你可以根据纸张设计报表
![image](https://github.com/jeecgboot/JimuReport/assets/3162115/ee16a78d-d269-4b62-819e-efc18547f2f2)
