### ISSUE TITLE
Unknown column 'PREVIEW_LOCK_STATUS' in 'field list'

### ISSUE THREAD

**Issue by cyangDrow** [jeecgboot/JimuReport#1723]
##### 问题描述：
在 ‘jimu_report_share’ 表中不存在 PREVIEW_LOCK_STATUS 字段，且sql脚本中貌似并没有提供此字段的更新

##### 重现步骤：
新增报表分享链接时会触发此问题。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
自己执行升级sql，不需要改
http://jimureport.com/doc/log
