### ISSUE TITLE
请问有没有办法支持MongoDb的aggregate 聚合查询？

### ISSUE THREAD

**Issue by Easzz** [jeecgboot/JimuReport#1725]
##### 版本号：
v1.5.6

##### 问题描述：
使用mongodb数据源，不支持aggregate 聚合查询

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/13145913/231319769-840c11a3-8362-42c8-81a3-c2b3f48629a3.png)

**Comment by lvdandan16** [comment]
暂不支持  归档

**Comment by jeecgos** [comment]
1.9.3版本 已支持使用sql语句对mongodb聚合查询
