### ISSUE TITLE
多个组件如何使用同一个接口返回的数据，只调用一次接口

### ISSUE THREAD

**Issue by clarkkentzh** [jeecgboot/JimuReport#1727]
##### 错误日志&截图：

![1681369260424](https://user-images.githubusercontent.com/26397435/231679354-1aca023d-c74b-4766-8031-054a32aad0fb.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zooooooooy** [comment]
可以用JS增强的方式配置多个文本框中的值
```
function init(){
// 加载第1个下拉框数据
$http.metaGet('http://localhost:8080/jeecg-boot/ces/ai/customSelect').then(res=>{
  let options =  res.data;
  this.updateSelectOptions('编码值', 'a属性', options);
  this.updateSelectOptions('编码值', 'b属性', options);
})
}
```

替换上述编码值，对不同属性值 进行设置

**Comment by lvdandan16** [comment]
不支持
