### ISSUE TITLE
开启租户模式后 报表名称重复问题

### ISSUE THREAD

**Issue by nidayang** [jeecgboot/JimuReport#1729]
##### 版本号：

V1.5.6

##### 问题描述：

兼容租户后，保存报表的时候显示名称重复，但是针对当前租户报表名称并没有重复。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
截图看下

**Comment by lvdandan16** [comment]
归档

**Comment by lvdandan16** [comment]
已修改  下个版本支持
