### ISSUE TITLE
接口响应时间大于5S，页面渲染不出来

### ISSUE THREAD

**Issue by yuxuanxinchen** [jeecgboot/JimuReport#1732]
##### 版本号：
1.5.4

##### 问题描述：
页面数据通过接口查询，接口返回较慢，平均时间大于5S，预览页面渲染数据有时候可以，有时候是空的，测试大于5S无法渲染出来数据，5S内可以渲染出来。可否有响应的配置能改变这个时间。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zooooooooy** [comment]
![image](https://user-images.githubusercontent.com/9649918/233242251-84754a60-a425-4331-ab63-27618aecac36.png)
这个配置可以修改接口响应时间。
