### ISSUE TITLE
首列或首行锁定

### ISSUE THREAD

**Issue by minitiger1974** [jeecgboot/JimuReport#1733]
##### 问题描述：

当行或列多的时候，能不能支持首列或首行锁定，这样横项或者纵向拖动时，锁定表头

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
暂时不支持
