### ISSUE TITLE
预览报表时，是否可以不直接查询

### ISSUE THREAD

**Issue by zooooooooy** [jeecgboot/JimuReport#1734]
### 版本号：
1.5.6

### 问题描述：
预览报表时，就会发起一次查询。
希望：预览报表时，不查询。手动点击查询按钮才进行查询

#### jar包版本号

```
<dependency>
	<groupId>org.jeecgframework.jimureport</groupId>
	<artifactId>jimureport-spring-boot-starter</artifactId>
	<version>1.5.6</version>
</dependency>
```

在未完成功能，已经有人提出同样的问题，是否有计划进行功能完善。或者提供相应的后门可以供我们操作。比如说JS增强来限制首次加载接口。

接口名称：jmreport/show

#### 建议
可以添加一个全局变量来控制是否首次预览时，加载后台的数据

#### 使用感受
积木报表使用起来非常方便，可定制化程度非常广，同步也会在项目中推广一下，让更多的需要报表的项目集成积木报表。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂时不支持，先归档

**Comment by lvdandan16** [comment]
已修复，下个版本支持

**Comment by breezeGit** [comment]
最新版本支持么？通过什么方式能限制首次进入页面不直接查询？

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/jimureport/query/jsEnhance.html#4%E8%AE%BE%E7%BD%AE%E9%A2%84%E8%A7%88%E4%B8%8D%E8%87%AA%E5%8A%A8%E5%8A%A0%E8%BD%BD%E6%95%B0%E6%8D%AE
