### ISSUE TITLE
报表sql，解析时，不支持大于小于号

### ISSUE THREAD

**Issue by wollior** [jeecgboot/JimuReport#1735]
##### 版本号：
1.5.6

##### 问题描述：
报表sql，解析时，不支持大于小于号

##### 错误日志&截图：
![UZ6UE4CV7DC 44LCLMJKG$K](https://user-images.githubusercontent.com/45417954/233590731-3ab61fad-e83d-4244-8958-d3a36c4a4526.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/54099258/a6117d2c-ed84-4478-bf21-ffd75ee7fdfc)
未复现此问题
