### ISSUE TITLE
图形报表-关系图不支持传参查询

### ISSUE THREAD

**Issue by jpf199** [jeecgboot/JimuReport#1736]
##### 版本号：
1.5.0-beta

##### 问题描述：
图形报表关系图-设置2个数据集，数据集中启用查询参数时，无法进行图表重新渲染，而是获取的jsonStr字段的默认值
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级新版本试试
