### ISSUE TITLE
打印设计，插入二维码或者插入图片后，打印时会多出一张空白页

### ISSUE THREAD

**Issue by zmwk** [jeecgboot/JimuReport#1737]
##### 问题描述：

在打印设计中，插入二维码或者插入图片后，打印时会多出一张空白页

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/44149252/233947622-fcddb382-9612-49f9-b3f8-2b7c5e9c1f5b.png)
![image](https://user-images.githubusercontent.com/44149252/233947759-20249e08-d5a2-4165-be3b-9baf4d3ca921.png)
![image](https://user-images.githubusercontent.com/44149252/233947917-b63ceeb2-170b-4303-9222-798e77bfe5f5.png)

##### 重现步骤：
只要插入二维码或者插入图片后，打印时就会多出一张空白页，把二维码或者图片删除后，打印就正常

**Comment by easonjim** [comment]
+1，请问这个问题解决了吗？

**Comment by easonjim** [comment]
@zhangdaiscott 请问这个问题如何解决了？

**Comment by lvdandan16** [comment]
收录 ty

**Comment by zhangshuai0220** [comment]
+1 同样遇到无法解决

**Comment by zhangdaiscott** [comment]
已经处理了，下个版本发布
