### ISSUE TITLE
预览报表，提示错误： for input string "isDrag"

### ISSUE THREAD

**Issue by xiaolaifeng** [jeecgboot/JimuReport#1739]
##### 问题描述：
复制数据报表模板， 点击设计后，预览，报错

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/7556508/234249242-6f105c72-1384-438d-a610-fb80d970383f.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by zhangdaiscott** [comment]
未重现
