### ISSUE TITLE
在ruoyi-vue-pro中积木报表API数据源无法获取数据的问题

### ISSUE THREAD

**Issue by stevenzhao719** [jeecgboot/JimuReport#1741]
##### 版本号：
积木报表 版本号 1.5.6
在[ruoyi-vue-pro](https://gitee.com/zhijiantianya/ruoyi-vue-pro) 1.7.1版本中使用的积木报表

##### 问题描述：
1.在配置打印模板时，新增API数据源如果使用id=${id},解析提示【数据为空，报表字段会被清除】
2.如果我将id写死比如id=1,可以成功解析出字段，但是当我在表格里面绑定的时候，值无法展示出来，都是空的。

##### 错误日志&截图：
没有错误日志

##### 重现步骤：
见版本号，和问题描述，步骤非常简单

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
ruoyi-vue-pro其他版本有这个问题吗
