### ISSUE TITLE
这个项目还有人维护么？为什么PREVIEW_LOCK_STATUS这个错误一直不改啊

### ISSUE THREAD

**Issue by ukhack** [jeecgboot/JimuReport#1742]
##### 版本号：
1.5.5

##### 问题描述：
报表点击分享会报错

##### 错误日志&截图：
bad SQL grammar；nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'PREVIEW_LOCK_STATUS' in 'field list'

##### 重现步骤：
git clone https://github.com/jeecgboot/JimuReport.git
将db文件执行，运行系统
demo报表直接点击分享

关联
#939
#941 
#1404
#1718 
#1722 
#1723

**Comment by zhangdaiscott** [comment]
http://jimureport.com/doc/log
