### ISSUE TITLE
右键分版消失了？

### ISSUE THREAD

**Issue by GFLEE** [jeecgboot/JimuReport#1744]
##### 版本号：
1.5.6

##### 问题描述：
右键分版消失了？

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/26864596/236151246-0b9843ce-7ca8-4d2e-8e93-60861c636f14.png)

##### 重现步骤：
右击，没有显示分版选项

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
滚动
