### ISSUE TITLE
jar包运行服务器上，访问url能出现页面，但控制台爆出caught ReferenceError: Vue is not defined  

### ISSUE THREAD

**Issue by tsvirs** [jeecgboot/JimuReport#1745]
##### 版本号：
 <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.1</version>
        <relativePath/> 
    </parent>
    <groupId>com.jimureport</groupId>
    <artifactId>demo</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>demo</name>
    <description>demo</description>
    <properties>
        
        <java.version>1.8</java.version>
        
        <postgresql.version>42.2.6</postgresql.version>
        <ojdbc6.version>11.2.0.3</ojdbc6.version>
        <sqljdbc4.version>4.0</sqljdbc4.version>
        <mysql-connector-java.version>5.1.14</mysql-connector-java.version>
        <minio.version>8.0.3</minio.version>
    </properties>

##### 问题描述：
jar包运行服务器上，访问url能出现页面，但控制台爆出caught ReferenceError: Vue is not defined  
本地正常。
##### 错误日志&截图：

<img width="1533" alt="image" src="https://user-images.githubusercontent.com/19851229/236157288-ad803fe6-84f8-4017-ba4d-13e74797a6b7.png">

##### 重现步骤：
访问项目：http://dev.ventilation.admin.ptteng.com/jmreport/list

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
影响使用吗

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题

**Comment by zpengc** [comment]
同样出现这个问题
