### ISSUE TITLE
自定义项目前缀  customPrePath 设置后不生效

### ISSUE THREAD

**Issue by atliwen** [jeecgboot/JimuReport#1746]
##### 版本号：
1.5.6

##### 问题描述：
自定义项目前缀  customPrePath 设置后不生效

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/10055836/236162044-01e6aa15-5e65-4dc1-bcbf-8b96619f8706.png)
![image](https://user-images.githubusercontent.com/10055836/236162182-f7b0a11d-15e7-42fb-bb41-f65fdf5157da.png)

##### 重现步骤：

确实读取到了配置设置，但是启动后却没变化

**Comment by lvdandan16** [comment]
收录 ws

**Comment by zhangdaiscott** [comment]
我们测试无问题，请提供详细重现步骤
