### ISSUE TITLE
报表数据超过1000多条时，导出失败

### ISSUE THREAD

**Issue by dinglingbo** [jeecgboot/JimuReport#1749]
##### 版本号：
1.5

##### 问题描述：
报表数据超过1000多条时，导出失败

##### 错误日志&截图：
![1683278422707](https://user-images.githubusercontent.com/51599298/236421296-08926143-d36f-4a64-8d12-ea37c4c141fd.png)

##### 重现步骤：
1、报表中单元格样式有数值，单元格宽度有大有小
2、查询至少2000条数据，然后点击导出

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by zhangdaiscott** [comment]
你是加样式了吧
