### ISSUE TITLE
是否支持手机端自适应展示

### ISSUE THREAD

**Issue by longlongwang88** [jeecgboot/JimuReport#1750]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持，针对手机端会出专门的仪表盘设计器
