### ISSUE TITLE
图表中无数据显示

### ISSUE THREAD

**Issue by charm-sign** [jeecgboot/JimuReport#1753]
##### 版本号：
1.4.32

##### 问题描述：
使用积木报表时数据库中数据量太大，导致数据还没返回,图表就渲染出来了,然后图表中无数据显示。sql已经不能再优化了。

##### 错误日志&截图：
![数据未返回，图表已渲染](https://user-images.githubusercontent.com/95025845/237051626-dca14766-e7ea-4be3-8381-1409e910c39d.png)

**Comment by lvdandan16** [comment]
设置分页展示数据
