### ISSUE TITLE
当前数据库脚本文件中jimu_report_share表缺失preview_lock_status字段

### ISSUE THREAD

**Issue by jxxglc** [jeecgboot/JimuReport#1760]
##### 版本号：
1.5.8

##### 问题描述：
当前版本代码里的数据库脚本缺失 jimu_report_share表的preview_lock_status字段。（该字段在1.4.4-beta版加上的），导致在分享报表勾选开启密码时后端报异常。

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/27805314/cb3e626b-7dac-47e3-8e28-463a2c01e574)
![image](https://github.com/jeecgboot/JimuReport/assets/27805314/7a5a3eae-44b1-41c6-abc8-9da7b80b7aba)

##### 重现步骤：
创建分享链接
![image](https://github.com/jeecgboot/JimuReport/assets/27805314/4ceeec41-1e7d-46a5-82d6-13328f618d1e)
后端报缺字段异常
![image](https://github.com/jeecgboot/JimuReport/assets/27805314/f8bb3311-a367-4793-96fc-5d1bff8a2489)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/jimureport/upgrade.html
2
