### ISSUE TITLE
设计报表时，添加一个图表，然后选中这个图表之后，无法取消选中状态

### ISSUE THREAD

**Issue by w2317q** [jeecgboot/JimuReport#1762]
##### 版本号：
1.5.8

##### 问题描述：
设计报表时，添加一个图表，然后选中这个图表之后，无法取消选中状态

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/25764968/fa9c9b9b-9025-431e-a07f-1fda5a7e0653)

##### 重现步骤：
设计报表时，添加一个图表，然后选中这个图表之后，无法取消选中状态

**Comment by zhangdaiscott** [comment]
不影响，你可以右键固定
