### ISSUE TITLE
如何迁移设计好的报表模板至新的环境

### ISSUE THREAD

**Issue by TonyWang8904** [jeecgboot/JimuReport#1763]
##### 版本号：
1.5.6

##### 问题描述：
在研发环境设计好一张报表模板，想直接将该报表迁移至运行环境，因为研发环境和运行环境的报表库有所区别，所以不能直接复制数据库，请问有什么比较好的方法吗？或者应该导出哪几张表的指定记录？

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/jimureport/issues.html
导出报表配置，或者手工整理升级sql
