### ISSUE TITLE
SQL解析之点击确定按钮无法保存的问题

### ISSUE THREAD

**Issue by dylvs** [jeecgboot/JimuReport#1764]
##### 问题描述：
springboot项目整合报表时加入jar包依赖之后，以数据列表为例。列表可以正常打开选择SQL语句报表的数据之后，SQL解析之后无法保存。后台报数据绑定的问题。
![image](https://github.com/jeecgboot/JimuReport/assets/133832509/9af89b7b-68c2-4da1-9943-7b58e5b0a549)

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/133832509/6edd62df-e47b-4c0f-b54b-b65f0dd31cd7)
ERROR org.apache.juli.logging.DirectJDKLog 175 log - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class java.io.PushbackInputStream and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.HashMap["exception"]->org.springframework.http.converter.HttpMessageNotReadableException["cause"]->com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException["location"]->com.fasterxml.jackson.core.JsonLocation["sourceRef"])

##### 重现步骤：
1.
![image](https://github.com/jeecgboot/JimuReport/assets/133832509/e7d0679c-1c32-4110-81aa-ae4120d95fa0)
2.
![image](https://github.com/jeecgboot/JimuReport/assets/133832509/0a860735-d000-45a5-9869-d89123110f3b)
3.
![image](https://github.com/jeecgboot/JimuReport/assets/133832509/0ecdadfa-a55f-4563-ba77-b9cae8ecb48c)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
测试demo没问题，你应该是依赖有冲突
