### ISSUE TITLE
是否有考虑支持Spring boot 3.0

### ISSUE THREAD

**Issue by pkaq** [jeecgboot/JimuReport#1765]
##### 版本号：
最新

##### 问题描述：

是否有考虑支持Spring boot 3.0
##### 错误日志&截图：

是否有考虑支持Spring boot 3.0
##### 重现步骤：
是否有考虑支持Spring boot 3.0

**Comment by zhangdaiscott** [comment]
后面会逐步升级，别着急

**Comment by pkaq** [comment]
那请问有时间表吗

**Comment by pkaq** [comment]
#138
