### ISSUE TITLE
图形报表设计页面怎么设置自适应，台式机和笔记本能自动适应

### ISSUE THREAD

**Issue by zhangfaming** [jeecgboot/JimuReport#1767]
##### 问题描述：
图形报表设计页面怎么设置自适应，台式机和笔记本能自动适应

比如： 台式机显示器分辨率比较高，笔记本比较低时， 做出来的图形报表就会出现滚动条，要左右或者上下拖动才能看

**Comment by lvdandan16** [comment]
暂不支持
