### ISSUE TITLE
积木报表等标题可以自定义吗？用了老板的资源替换方式，但是并没有生效

### ISSUE THREAD

**Issue by maderqia** [jeecgboot/JimuReport#1768]
##### 问题描述：
![image](https://github.com/jeecgboot/JimuReport/assets/102300058/62b3b974-7d8b-4146-8c24-bac6fcbbeae3)

积木报表等标题可以自定义吗？用了老板的资源替换方式，但是并没有生效
尝试了在maven依赖里修改了标题，和更换图标，以及resources下做静态资源都没生效

**Comment by zhangdaiscott** [comment]
不支持
