### ISSUE TITLE
查询出来符合条件的数据，能有选择性的导出么

### ISSUE THREAD

**Issue by aamhain001** [jeecgboot/JimuReport#1769]
##### 问题描述：查询出来符合条件的数据，能有选择性的导出么
比如第一次查询后，符合条件的结果有3条（ABC），然后选中一条A；第二次查询后，符合结果的有2条（DE），然后选择D。导出的表里面只包含AD，这种能实现么，谢谢大佬

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
