### ISSUE TITLE
springboot集成Jimurepot报错

### ISSUE THREAD

**Issue by shpilu** [jeecgboot/JimuReport#1770]
##### 版本号：
1.5.8

##### 问题描述：
按照官网的文档集成了Jimu，但编译报错，已知为了集成Jimu，代码修改如下
--- a/pom.xml
+++ b/pom.xml
@@ -75,6 +75,10 @@
 			<groupId>org.springframework.boot</groupId>
 			<artifactId>spring-boot-starter-web</artifactId>
 		</dependency>
+    <dependency>
+        <groupId>org.springframework.boot</groupId>
+        <artifactId>spring-boot-starter-freemarker</artifactId>
+    </dependency>
     <dependency>
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-starter-data-redis</artifactId>
@@ -247,6 +251,11 @@
       <artifactId>mysql-binlog-connector-java</artifactId>
       <version>0.25.0</version>
     </dependency>
+    <dependency>
+      <groupId>org.jeecgframework.jimureport</groupId>
+      <artifactId>jimureport-spring-boot-starter</artifactId>
+      <version>1.5.8</version>
+    </dependency>
   </dependencies>

 	<build>
diff --git a/src/main/java/com/gboot/GbootApplication.java b/src/main/java/com/gboot/GbootApplication.java
index 02b5914..74cc9e5 100644
--- a/src/main/java/com/gboot/GbootApplication.java
+++ b/src/main/java/com/gboot/GbootApplication.java
@@ -14,7 +14,7 @@ import org.springframework.scheduling.annotation.EnableScheduling;
 @EnableMBeanExport(registration = RegistrationPolicy.IGNORE_EXISTING)
 @Import(FdfsClientConfig.class)
 @MapperScan({"com.gboot.dbAccessor.tables.*.mapper","com.gboot.*.mapper","com.gboot.cadreSelect.*.mapper",
-  "com.gboot.*.db.*.mapper"})
+  "com.gboot.*.db.*.mapper", "org.jeecg.modules.jmreport"})
 public class GbootApplication {
 	public static void main(String[] args) {
 		SpringApplication.run(GbootApplication.class, args);
diff --git a/src/main/java/com/gboot/config/OauthResourceConfig.java b/src/main/java/com/gboot/config/OauthResourceConfig.java
index 85b08bd..125be88 100644
--- a/src/main/java/com/gboot/config/OauthResourceConfig.java
+++ b/src/main/java/com/gboot/config/OauthResourceConfig.java
@@ -59,6 +59,7 @@ public class OauthResourceConfig extends ResourceServerConfigurerAdapter {
                 .antMatchers("/documentinformation/callBackDocument/**").permitAll()
                 .antMatchers("/audit_rect/OALogin/oaUserInfo").permitAll()
                 .antMatchers("/audit_rect/OALogin/queryUserByCode").permitAll()
+                .antMatchers("/jmreport/**").permitAll()
                 .antMatchers("/**").authenticated()
                 .and().logout().logoutRequestMatcher(new AntPathRequestMatcher("/logout")).permitAll();
     }

##### 错误日志&截图：

2023‐05‐19 11:06:34.948 [main] [ERROR] [SpringApplication.java:824] [org.springframework.boot.SpringApplication] Application run failed
org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'a' for bean class [org.jeecg.modules.jmreport.desreport.b.a.a.a] conflicts with existing, non-compatible bean definition of same name and class [org.jeecg.modules.jmreport.common.constant.a]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.checkCandidate(ClassPathBeanDefinitionScanner.java:349)
	at org.mybatis.spring.mapper.ClassPathMapperScanner.checkCandidate(ClassPathMapperScanner.java:237)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:287)
	at org.mybatis.spring.mapper.ClassPathMapperScanner.doScan(ClassPathMapperScanner.java:168)
	at org.mybatis.spring.annotation.MapperScannerRegistrar.registerBeanDefinitions(MapperScannerRegistrar.java:123)
	at org.mybatis.spring.annotation.MapperScannerRegistrar.registerBeanDefinitions(MapperScannerRegistrar.java:72)
	at org.springframework.context.annotation.ImportBeanDefinitionRegistrar.registerBeanDefinitions(ImportBeanDefinitionRegistrar.java:86)
##### 重现步骤：
     参考代码diff

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
发截图，你这格式太乱，没发看

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭
