### ISSUE TITLE
单元格统计函数sum问题

### ISSUE THREAD

**Issue by sky199927** [jeecgboot/JimuReport#1773]
##### 版本号：
1.5.6
##### 问题描述：
两个纵向分组的合计中，如果第一个数据集的分局渲染超过下方的sum，那么就会把第一个数据集超过的部分统计合并进去。

##### 错误日志&截图：
![设计](https://github.com/jeecgboot/JimuReport/assets/84822807/cfa64f80-122b-403e-b4ba-e1918e99cbc9)
![结果](https://github.com/jeecgboot/JimuReport/assets/84822807/718b6932-fdce-490e-a7f5-785847f4310f)

##### 重现步骤：
SUM(D7)把上面的分组表格从第7列的数量也统计到了下面的合计。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by dylvs** [comment]
数据填充之后样式变了，这个里面应该使用的是=sum(表名别名.字段)/=dbsum(表名别名.字段)吧

**Comment by dylvs** [comment]
看着像是数据填充之后样式变了，除了第一个数据以外的其他数据集里面应该使用的是=sum(表名别名.字段)或者=dbsum(表名别名.字段)吧，可以试试看

**Comment by lvdandan16** [comment]
SUM(D7)是按列来计算的，只要是计算那一列的都会计算
