### ISSUE TITLE
下拉树数据源展示问题

### ISSUE THREAD

**Issue by dylvs** [jeecgboot/JimuReport#1775]
##### 问题描述：下拉树数据源展示只有一个父子关系，呈现多组错乱显示效果。另外配置的数据字典在查询栏会显示英文名称
![image](https://github.com/jeecgboot/JimuReport/assets/133832509/39aae423-e55b-4a9f-9ed1-06ac786bb9b2)

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/133832509/588477d8-9c1f-4720-89d3-9b26b1b9d9b0)
![image](https://github.com/jeecgboot/JimuReport/assets/133832509/c51c271d-e05b-433d-9de2-5570095245cb)

##### 重现步骤：
{'loadTree':'http:********/project/getDictTreeProj?dictCode=dict_proj'}
后台api接口返回的数据结构pid为空也会出现上述图片结果
[{"title":"华城荷坳发展有限公司","value":"2","pid":"0","id":"o_2"},{"title":"华城荷坳项目","value":"1","pid":"o_2","id":"p_1"}]

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by dylvs** [comment]
api接口需要初始化加载时带入pid参数，并且初始化时只展示一级数据进行过滤。因为折叠标签点击一下就需要调一次后台方法。此处应该可以优化，一次性查出所有JSON数据之后再就不需要频繁与后台方法进行交互。

**Comment by lvdandan16** [comment]
归档

**Comment by BO-DI** [comment]
> api接口需要初始化加载时带入pid参数，并且初始化时只展示一级数据进行过滤。因为折叠标签点击一下就需要调一次后台方法。此处应该可以优化，一次性查出所有JSON数据之后再就不需要频繁与后台方法进行交互。

请问，查询下拉树的参数配置，数据集用的api，我用固定值可以，动态参数怎么传呢
