### ISSUE TITLE
【求助】Aviator TRACE 日志如何关闭打印

### ISSUE THREAD

**Issue by catlvsuger** [jeecgboot/JimuReport#1776]
##### 错误日志&截图：数据量大的时候，[Aviator TRACE]打印非常多，如何不显示，日志级别设置没生效
![image](https://github.com/jeecgboot/JimuReport/assets/39261781/e2ddeed9-ae59-4e2a-a59e-c9aef4ec69f0)

![image](https://github.com/jeecgboot/JimuReport/assets/39261781/11875d59-0b5e-49ec-afb5-446208915e57)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
目前不支持设置
