### ISSUE TITLE
积木报表怎样和企业内部现有的系统集成？

### ISSUE THREAD

**Issue by yesay** [jeecgboot/JimuReport#1778]
##### 版本号：
1.5.6

##### 问题描述：
积木报表怎样和企业内部现有的系统集成？

##### 重现步骤：
积木报表怎样和企业内部现有的系统集成？

比如想把在积木报表中做好的报表集成企业到企业内部系统的页面，是通过分享报表链接的方式，还是需要 企业内部系统的前端调用积木报表后端项目的接口？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
分享链接即可
