### ISSUE TITLE
预览页面表头信息较多时报表右侧以及下方较大区域留白。表单信息较少时报表居左显示，

### ISSUE THREAD

**Issue by dylvs** [jeecgboot/JimuReport#1779]
##### 问题描述：
预览页面表头信息较多时报表右侧以及下方较大区域留白。留白可以去掉吗？较少时报表居左显示，可以调整为居中吗？求方案，谢谢

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/133832509/e1e7eef9-c256-4fb1-912d-146dc78f31b3)

![image](https://github.com/jeecgboot/JimuReport/assets/133832509/527a7cae-5113-43f2-9bc6-2214f4a6b2b8)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
目前就是居左的，不支持居中
