### ISSUE TITLE
请问api数据集如何进行post请求并传参？如何在修改请求header里的参数？

### ISSUE THREAD

**Issue by nonioniid** [jeecgboot/JimuReport#1780]
##### 版本号：
V1.5.8

##### 问题描述：
请问api数据集如何进行post请求并传参？如何在修改请求header里的参数？
官方文档里面只有get请求的示例，没有post相关的。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档：https://help.jeecg.com/jimureport/queryCriteria/apiInterface.html

**Comment by FGlai** [comment]
发个没用的地址出来干嘛。
