### ISSUE TITLE
分享数据报表报错

### ISSUE THREAD

**Issue by changankes** [jeecgboot/JimuReport#1782]
##### 版本号：
1.5
![image](https://github.com/jeecgboot/JimuReport/assets/57754826/aa4de375-cf1b-4e79-8cb0-c8d4a44067f5)

##### 问题描述：
分享数据报表报错。过期时间选择`1天`，是否开启密码选择`是`。
我的本地项目是从git上下载的zip压缩包，执行`jimureport-example/db/jimureport.mysql5.7.create.sql`脚本，初始化数据库。脚本里面`jimu_report_share`的建表语句好像缺少了**PREVIEW_LOCK_STATUS**字段。
![image](https://github.com/jeecgboot/JimuReport/assets/57754826/0063e041-806f-4897-84ea-d225bd6b3d70)

##### 错误日志&截图：
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [INSERT INTO jimu_report_share ( ID ,REPORT_ID ,PREVIEW_URL ,PREVIEW_LOCK ,LAST_UPDATE_TIME ,TERM_OF_VALIDITY ,STATUS ,PREVIEW_LOCK_STATUS ) values ( ? ,? ,? ,? ,? ,? ,? ,? )]; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'PREVIEW_LOCK_STATUS' in 'field list'

##### 重现步骤：
分享数据报表

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by johnnian** [comment]
我这边也是遇到同样的问题，使用的是Docker-compose安装，链接：http://report.jeecg.com/3007400

**Comment by lvdandan16** [comment]
参考升级sql日志：http://bi.qiaoqiaoyun.com/doc/log
