### ISSUE TITLE
若依分离版，添加数据源和保存报表报未知列名错误

### ISSUE THREAD

**Issue by lInsomnia** [jeecgboot/JimuReport#1783]
##### 错误日志&截图：PreparedStatementCallback; bad SQL grammar [INSERT INTO jimu_report_data_source ( ID ,NAME ,REPORT_ID ,CODE ,REMARK ,DB_TYPE ,DB_DRIVER ,DB_URL ,DB_USERNAME ,DB_PASSWORD ,CREATE_BY ,CREATE_TIME ,UPDATE_BY ,UPDATE_TIME ,CONNECT_TIMES ,TENANT_ID ,TYPE ) values ( ? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? )]; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'TENANT_ID' in 'field list'
![image](https://github.com/jeecgboot/JimuReport/assets/49468569/b0498977-958e-4ad5-bde8-a545f302075d)
![image](https://github.com/jeecgboot/JimuReport/assets/49468569/7fceadc8-c6c5-4237-b475-b1267ed5953b)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考升级sql：http://bi.qiaoqiaoyun.com/doc/log
