### ISSUE TITLE
在maven依赖中引用积木报表是否需要支付费用或者将自己项目开源？

### ISSUE THREAD

**Issue by namelessmyth** [jeecgboot/JimuReport#1784]
##### 版本号：
            <dependency>
                <groupId>org.jeecgframework.jimureport</groupId>
                <artifactId>jimureport-spring-boot-starter</artifactId>
                <version>1.5.8</version>
            </dependency>

##### 问题描述：
我在项目的maven依赖中引用了积木报表的依赖。不修改积木的源码，只是使用他开发业务报表。
我们的项目属于商用，功能上线之后，源代码会交付给客户。
请问像我们这种情况是否需要收费？或者是否需要把自己的项目开源？

##### 错误日志&截图：
无

##### 重现步骤：
无

**Comment by lvdandan16** [comment]
不收费，功能完全免费
