### ISSUE TITLE
1.5.6和1.5.8打印，请求官方支持，循环块打印功能

### ISSUE THREAD

**Issue by zhangpp2023** [jeecgboot/JimuReport#1785]
##### 错误日志&截图：

![微信图片_20230529151327](https://github.com/jeecgboot/JimuReport/assets/134915429/59f76c01-6c40-423d-af57-5ba5ef1b09f6)

备注：就是这个功能，目前块打印外层可以，但是这个块里面还有循环list，  也就是  item.list 这种套循环，请求支持；

##### 重现步骤：
    循环块打印，目前没发现bug

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；
![rrrrr](https://github.com/jeecgboot/JimuReport/assets/134915429/e91b876e-e624-4b99-807d-5d8cada4de6b)

**Comment by lvdandan16** [comment]
item.list 这种套循环  不支持
