### ISSUE TITLE
横向纵向组合分组排序错误

### ISSUE THREAD

**Issue by xiaobaiyis** [jeecgboot/JimuReport#1790]
##### 版本号：
1.5.6

##### 问题描述：
横向纵向组合分组时对中文字段列设置正序排序错误，设置分组后可以按照数据集的顺序直接排列出来吗，相同的Sql语句从数据库查出来的数据集顺序已经排好，却又在报表里再次排序，最终同样导致未按照指定排序规则排序，是否可以自己选择是否由分组中的排序规则排序

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/114853731/570e364c-14e0-43cf-8f57-c4b983f500bd)

##### 重现步骤：
![image](https://github.com/jeecgboot/JimuReport/assets/114853731/bd705ccc-16c1-49a2-927d-6ae4c83f560d)
下图是SQL查出来之后的排序
![image](https://github.com/jeecgboot/JimuReport/assets/114853731/5f147f88-097d-4484-bb3f-5398d22d2a12)
此图是经过报表中设置分组后再次排序
![image](https://github.com/jeecgboot/JimuReport/assets/114853731/5c5d7315-5c30-4c3b-b97d-5c1287f2766a)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
中文字段分组时不支持排序
