### ISSUE TITLE
打印时只有一张的内容，需要打印两张出来

### ISSUE THREAD

**Issue by tb2888** [jeecgboot/JimuReport#1792]
##### 版本号：
1.5.6

##### 问题描述：
如图，明明一张纸可以打印完，显示要2张纸，需要50张的话，显示51张纸，后面总有一页空白

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/55084864/9469345d-d698-4823-852c-e0cff3c0ec86)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
设计界面最后一页空白行删掉即可
