### ISSUE TITLE
主子表，主表循环不了

### ISSUE THREAD

**Issue by lcpone** [jeecgboot/JimuReport#1793]
##### 问题描述：
怎么能实现主表在页面上循环，想在一个页面上循环展示部门，每个部门下是用户列表，怎么实现

##### 错误日志&截图：
![~6HPY% S2EXEO5P1HQSMP}3](https://github.com/jeecgboot/JimuReport/assets/32187964/eaf1b384-cd79-4218-9b7e-9bfbed5cf4a8)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
主表不支持循环
