### ISSUE TITLE
没有循环代码块操作设置

### ISSUE THREAD

**Issue by dylvs** [jeecgboot/JimuReport#1796]
##### 问题描述：没有循环代码块操作设置，请问是那个版本有啊
![image](https://github.com/jeecgboot/JimuReport/assets/133832509/a8d47363-3a4b-47d6-853e-0ff89926e48e)

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/133832509/cf50a714-8f0a-4a6b-847a-cba6f754aa67)

##### 重现步骤：
![image](https://github.com/jeecgboot/JimuReport/assets/133832509/9d5dd5a3-17c0-496b-93ed-dbd887f0f7a2)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by KateJun** [comment]
旁边有个滚动条，

**Comment by dylvs** [comment]
> 旁边有个滚动条，

没太注意，关了issue又给开了。谢谢啦
