### ISSUE TITLE
单元格二维码打印页崩溃BUG

### ISSUE THREAD

**Issue by 15002035197** [jeecgboot/JimuReport#1799]
##### 错误日志&截图：

https://github.com/jeecgboot/JimuReport/assets/102869296/fb8e1e4e-c7ac-48e0-9f70-fe4224d0147a

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by lnmlnm** [comment]
我们也发现类似问题，二维码后有多余分页，很头疼。
奇怪的是有的机器上没事，有的机器上就不行。
firefox肯定没问题。
Edge、Chrome等看机器。

**Comment by zhangdaiscott** [comment]
已经处理了，下个版本发布
