### ISSUE TITLE
数据大屏设计时,表格同行区域同时存在表格跟图表时合成会错位

### ISSUE THREAD

**Issue by ForeachIn** [jeecgboot/JimuReport#1800]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/16876588/79ef8955-7af9-4a44-ad2c-a6e7cf593b41)
![image](https://github.com/jeecgboot/JimuReport/assets/16876588/33b0eaef-513f-4dfa-8311-c6464c77c4a3)

##### 重现步骤：
同行区域前半区域插入一张数据表格
后半区域插入一些图表
点击合成 预览时图表会错位到表格右下方展示

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by lvdandan16** [comment]
收录 zy

**Comment by 1298191366** [comment]
问题一未错位复现
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/4408151c-f6ee-4c9a-a288-527c1578093b)
需要和表格同一行，如果不在同一行会先循环列表在循环图表
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/4ea89efe-89a7-4bb3-a33a-bd4ba7a543c3)
