### ISSUE TITLE
导出excel无法打开

### ISSUE THREAD

**Issue by Ayat-l** [jeecgboot/JimuReport#1803]
##### 错误日志&截图：
![图片](https://github.com/jeecgboot/JimuReport/assets/76478281/2abb0b7a-d542-4ed3-97ef-fc37438abbc7)
导出时问题如下图示意:
![图片](https://github.com/jeecgboot/JimuReport/assets/76478281/f61439e8-dab7-4139-b8ed-f3cd7bcea2e8)

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
未复现

**Comment by 1298191366** [comment]
未复现，请提供报表sql
图一：企业实时报表
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/9be15250-9380-43f7-b81c-d47e2801e609)
图二：套打
