### ISSUE TITLE
查询优化建议

### ISSUE THREAD

**Issue by speckle23** [jeecgboot/JimuReport#1804]
##### 版本号：
1.5.6

##### 问题描述：
1.查询页面查询参数重置时，能不能优化成不直接就去触发查询？
2.查询页面点查询时可以塞入动态参数吗？区分第一次进入页面和点查询这两个动作

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持  归档
