### ISSUE TITLE
打印会莫名出现空白页

### ISSUE THREAD

**Issue by unbelievableTang** [jeecgboot/JimuReport#1807]
##### 版本号：
1.5.6

##### 问题描述：
为啥预览报表时明明没有数据，但打印报表一直有第二页空白页，哪位大佬解答下

##### 错误日志&截图：
![PLI7{@8P5KNS}}$MQO)SK3B](https://github.com/jeecgboot/JimuReport/assets/108724292/e2f03a91-1525-422e-8607-2d5dbf2281e4)

![T5E{@ TF9(L_@(LEPRT}R2](https://github.com/jeecgboot/JimuReport/assets/108724292/772473ed-dce9-4394-a1e0-7293f27f19b3)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/54099258/701496c9-82eb-46d7-af30-20227c0d8131)
设计页面下边空白行删掉
