### ISSUE TITLE
建议增加查询参数展示

### ISSUE THREAD

**Issue by dengyingfeng2022** [jeecgboot/JimuReport#1808]
##### 版本号：

1.5.8
##### 问题描述：
当我使用接口编制一个动态的报表时，我有两个查询参数 一个是查询月份，一个是产品名称，期望表头的表名展示为**2023-06A产品报表**时，感到很无力，因为我无法通过任何方式获取到查询参数，但是返回值中无法包含查询参数，因为查询月份是按月的，但返回数据是月的每一天，同样产品名称是一个类型，如查询A产品，会返回A-1，A-2，等等A相关的产品甚至部分产品名称完全不包含A相关信息，此时很无助。因为接口是三方提供的，不可能增加返回内容

##### 错误日志&截图：
非错误，知识期望增加这功能
##### 重现步骤：
谢谢

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持，先归档
