### ISSUE TITLE
单元格边框线条样式选择不了

### ISSUE THREAD

**Issue by KateJun** [jeecgboot/JimuReport#1810]
##### 版本号：

1.5.8
##### 错误日志&截图：
![Z`HKTC_{61IEO2VSCUAB586](https://github.com/jeecgboot/JimuReport/assets/6227218/101a8e1f-094f-42ac-a7ef-a5234e6354c0)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
修复
