### ISSUE TITLE
最新版本，数据源无法保存

### ISSUE THREAD

**Issue by 18621579069** [jeecgboot/JimuReport#1811]
##### 版本号：
  <dependency>
            <groupId>org.jeecgframework.jimureport</groupId>
            <artifactId>jimureport-spring-boot-starter</artifactId>
            <version>1.5.8</version>
  </dependency>

##### 问题描述：

后台增加数据源时，字段报错：表名：jimu_report_data_source 字段：DB_TYPE  部分代码显示 是TYPE 导致数据创建失败

##### 错误日志&截图：
<img width="1311" alt="图片" src="https://github.com/jeecgboot/JimuReport/assets/13254773/e7b632e4-bb2a-4ca1-847f-8187b1fef4e2">

##### 重现步骤：

每次点击增加数据源都会报错，建议最新版本优化

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 18621579069** [comment]
<img width="1247" alt="图片" src="https://github.com/jeecgboot/JimuReport/assets/13254773/521dd4b8-31ca-4ab3-8e08-2c158c686b84">

**Comment by unbelievableTang** [comment]
这个报错，表面上看是jimu_report_data_source表没有 TYPE 字段。

**Comment by 18621579069** [comment]
你好，现在修复了吗 ？最近需要用这个插件，方便更新后说下，我这边也更新。











在 2023-06-09 11:51:59，"devTom" ***@***.***> 写道：

这个报错，表面上看是jimu_report_data_source表没有 TYPE 字段。

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 18621579069** [comment]
现在处理了吗？可以更新使用吗？
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年06月16日 13:57 |
| 收件人 | jeecgboot/JimuReport ***@***.***> |
| 抄送人 | 18621579069 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [jeecgboot/JimuReport] 最新版本，数据源无法保存 (Issue #1811) |

收录 ws

**Comment by unbelievableTang** [comment]
我也是框架工具的使用者，勿回

**Comment by zhangdaiscott** [comment]
没有执行升级sql
http://jimureport.com/doc/log
