### ISSUE TITLE
能否依单元格内容值切换为超链接或纯文本?

### ISSUE THREAD

**Issue by tzengshinfu** [jeecgboot/JimuReport#1812]
##### 问题描述：
数据来源的會簽單單號字段内容值会有两种类型，
【会签单号】以及无单号则显示为”無會簽單”的文字(如截图)
请问有办法能达到有会签单号时显示为超链接，若是”無會簽單”则显示为纯文本避免用户误触？

(感谢jeecgboot团队提供这项优质报表产品，目前我们还在与相关竞品评估中，能以表达式函数客制各项功能诚为一大亮点👏)

##### 错误日志&截图：
![2023-06-09 08 33 56](https://github.com/jeecgboot/JimuReport/assets/2170033/4670c175-e56d-4172-be3c-c30a0612af96)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
目前不支持
