### ISSUE TITLE
导出的pdf格式有问题，页面出现大量留白

### ISSUE THREAD

**Issue by 9656cyhs** [jeecgboot/JimuReport#1813]
##### 版本号：
1.5.8版本

##### 问题描述：
导出的pdf格式有问题，页面出现大量留白

##### 错误日志&截图：
![屏幕截图 2023-06-09 150100](https://github.com/jeecgboot/JimuReport/assets/52615136/619eda49-01e2-4fae-8252-80bd15129c3c)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 2333paopao** [comment]
这个问题怎么解决的

**Comment by 9656cyhs** [comment]
> 

改源码了

**Comment by 2333paopao** [comment]
诚聘网络兼职工资日结!还不错详情请登陆招聘网站http://aqsvxceim.cn?6

**Comment by 2333paopao** [comment]
大佬，怎么改的

**Comment by 2333paopao** [comment]
谢谢大佬，这个是不是没有源码的话就没法改了

**Comment by 9656cyhs** [comment]
代码改动量比较少，可以直接拿字节码过来改

**Comment by 2333paopao** [comment]
大佬，请问是要改哪个文件

**Comment by 9656cyhs** [comment]
代码混淆了 没法说在哪个文件   可以debug跟一下

**Comment by 1298191366** [comment]
请把报表配置导出来一份我们参考一下，便于复现问题并解决

**Comment by 2333paopao** [comment]
诚聘网络兼职工资日结!还不错详情请登陆招聘网站http://aqsvxceim.cn?6
