### ISSUE TITLE
饼图数值显示问题

### ISSUE THREAD

**Issue by liushuang0904** [jeecgboot/JimuReport#1814]
##### 版本号：
1.5.6

##### 问题描述：
饼图在预览页面的数值显示多个一个字母n

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/12346627/634cf002-8790-4ad7-8d0a-ddd6ea1dc48c)
![image](https://github.com/jeecgboot/JimuReport/assets/12346627/1538e642-241d-4eb6-a5b4-649d2f898cdf)
![image](https://github.com/jeecgboot/JimuReport/assets/12346627/bbe4e863-196f-4f5a-a85f-867a48e71d68)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
已修改

**Comment by wm204** [comment]
这个数值和文本显示在同一行是怎么设置的啊
