### ISSUE TITLE
 一个表格中同时存在求和与求平均时，统计有误

### ISSUE THREAD

**Issue by dengyingfeng2022** [jeecgboot/JimuReport#1815]
##### 版本号：
1.58

##### 问题描述：
一个表格中同时存在求和与求平均时，放在后面一行的数据统计有误

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/105050463/a8f2417b-03d3-41ee-95d1-bea9549d924e)

![image](https://github.com/jeecgboot/JimuReport/assets/105050463/5f918f3e-1363-437d-baf8-cd38a39bd046)

##### 重现步骤：
合计是对的，但是求平均不对，多加了合计的那一行

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
输入的是C5 肯定会统计C5整一列
