### ISSUE TITLE
积木报表配置自定义函数选择SUM函数合计行之后，取值错误。

### ISSUE THREAD

**Issue by a1643977841** [jeecgboot/JimuReport#1816]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
积木报表配置自定义函数选择SUM函数合计行之后，取值错误。
实际取出来的是最后一图的数据

##### 截图&代码：
<img width="960" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/75775858/5edc78d1-3a86-455f-9f23-b12ad0cfbbe2">
<img width="883" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/75775858/f5c02341-2008-41ce-b644-467614df12aa">
<img width="553" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/75775858/65e2d1ca-eb50-4699-8052-73134af9d773">
<img width="888" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/75775858/fc6366db-91bd-43d3-a86b-b010675ba38b">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by zhangdaiscott** [comment]
你这个表达式是自己定义的吧，不支持

**Comment by a1643977841** [comment]
> 你这个表达式是自己定义的吧，不支持

SUM函数标准的可以支持，自定义的函数不支持的话，后期有计划支持吗

**Comment by zhangdaiscott** [comment]
后面会提供这机制
https://help.jeecg.com/jimureport/function/dynamiCell.html

**Comment by coolHao666** [comment]
我这还是不行呀？
![image](https://github.com/jeecgboot/JimuReport/assets/41717512/7d9f26e4-a50d-4ffd-aff4-28b1f068f92a)
![image](https://github.com/jeecgboot/JimuReport/assets/41717512/4073cea2-28f3-448c-8419-dac69bd1ee40)
1.6.4版本

**Comment by coolHao666** [comment]
是否有函数或者可以自定义函数来求一个动态列中不重复字符串个个数，用来解决账单表里面的人数合计问题
