### ISSUE TITLE
表格导出excel单元格数据不正确。

### ISSUE THREAD

**Issue by JxlWen** [jeecgboot/JimuReport#1818]
##### 版本号：
1.4.4

##### 问题描述：
表格数据导出excel后单元格数据不正确，此单元格数据为（23#），进行sql转换REPLACE(fault_position,'#','号门') as fault_position

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/50694382/6bf6acdf-04f9-48f8-b141-9f9a4f85ddc7)
![image](https://github.com/jeecgboot/JimuReport/assets/50694382/6ceedbda-d9aa-41b9-982c-2a45ecae9d7f)

##### 重现步骤：
数据源：SQL
SELECT id,line_name,line_number,REPLACE(fault_position,'#','号门') as fault_position,fault_type,create_by FROM operate_daily  A where A.repair_state = '1'  ORDER BY A.filling_time Desc 

预览，点击导出excel

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
未复现，请导出报表配置我们复现一下，或尝试升级版本`1.6.1`
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/0b650294-7af0-40ab-81c1-3691fbc12019)
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.6.1</version>
</dependency>
```
