### ISSUE TITLE
添加分组后导出报表相应时间过长

### ISSUE THREAD

**Issue by qiuzhaochuang** [jeecgboot/JimuReport#1819]
##### 版本号：
1.5.8

##### 问题描述：
导出150条数据，添加几个分组，需要30秒时间 ，响应时间太久

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/87967376/1b23333e-d946-4881-b7cc-1f0e36387d42)

##### 重现步骤：
150条数据，设置6个分组，基本多一个分组就多5秒

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by lvdandan16** [comment]
提供报表配置及数据sql  我们复现一下

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
