### ISSUE TITLE
能不能提供整条数据合并功能

### ISSUE THREAD

**Issue by MVWill** [jeecgboot/JimuReport#1821]
##### 错误日志&截图：类似这种
示例一：
姓名 | 科目 | 付款方式 | 实收金额 | 税额
张三 | 物业费 | 微信支付 | 100 | 10
张三 | 物业费 | 支付宝 | 50 | 5
 合并后
姓名 | 科目 | 付款方式 | 实收金额 | 税额
张三 | 物业费 | 微信支付,支付宝 | 150 | 15

示例二
姓名 | 科目 | 付款方式 | 实收金额 | 税额
张三 | 物业费 | 微信支付 | 100 | 10
张三 | 物业费 | 微信支付 | 50 | 5
 合并后
姓名 | 科目 | 付款方式 | 实收金额 | 税额
张三 | 物业费 | 微信支付 | 150 | 15

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持此种方式合并
