### ISSUE TITLE
并发导出不同模板时发生数组越界异常

### ISSUE THREAD

**Issue by unfairfair** [jeecgboot/JimuReport#1823]
##### 版本号：
1.5.4
1.5.8

##### 问题描述：
大量导出不同模板为PDF时发生异常，应该是并发问题，修改了模板json导致数组越界。

##### 错误日志&截图：
![企业微信截图_16867013091536](https://github.com/jeecgboot/JimuReport/assets/25562282/dc1667b9-c135-49fb-b150-413c9c82ac5e)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by zhangdaiscott** [comment]
请提供重现步骤
