### ISSUE TITLE
SQL数据源，页面预览数据没有渲染

### ISSUE THREAD

**Issue by CowBoy0909** [jeecgboot/JimuReport#1824]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/128303435/648994fa-08c4-43be-976c-9b1abf69a2e9)
![image](https://github.com/jeecgboot/JimuReport/assets/128303435/8b817430-f070-4188-8c34-41153dafde0d)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by CowBoy0909** [comment]
预览页面
![image](https://github.com/jeecgboot/JimuReport/assets/128303435/c19ebb1e-c7c9-4538-8853-f83473ea6bcd)

**Comment by lvdandan16** [comment]
对象使用$取值
