### ISSUE TITLE
希望条码内容和文字各自显示

### ISSUE THREAD

**Issue by vbwei** [jeecgboot/JimuReport#1825]
##### 问题描述：
用数据源替换文字内容后条码内容会相应变更
条码信息一般是给系统扫码用的，数据编号对于阅读并不方便
希望可以变更为各自显示而不是强制替换内容

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持
