### ISSUE TITLE
对比折线图保存失败

### ISSUE THREAD

**Issue by Lovedcc** [jeecgboot/JimuReport#1829]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/102033777/36340be1-bacc-409e-a822-ea10f5d8cf72)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
看后台报错信息

**Comment by Lovedcc** [comment]
感谢，之前没有注意到一个字段值太长了，已经解决了

**Comment by lvdandan16** [comment]
OK
