### ISSUE TITLE
版本升级后下拉单选功能失效

### ISSUE THREAD

**Issue by 15518175448** [jeecgboot/JimuReport#1830]
##### 问题描述：
在1.4.2版本中设置下拉单选后：比如该字段有"是"和"否"两种数据，那么下拉单选框只显示是、否
在升级到1.5.0后，下拉单选框显示"是是是是是否否否否......."
尝试升级到1.5.8后，下拉单选框没太大变化，在"是是是是是否否否否......."基础上新增查询功能
在新版本下除了数据字典外，如何实现1.4.2的这种功能？

##### 错误日志&截图：
1.4.2版本
![图片](https://github.com/jeecgboot/JimuReport/assets/84377642/f5ffc0d1-10c7-4bfa-9f27-ee0e12e79dd9)
1.5.0版本
![图片](https://github.com/jeecgboot/JimuReport/assets/84377642/7e44e759-0d35-4e92-8c41-4b9249ce7e0b)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档 5.2.通过SQL字典，字典code中直接输入sql语句：通过distinct查询下拉选项
https://help.jeecg.com/jimureport/query/controlDefaults.html

**Comment by 15518175448** [comment]
但是已经有大量报表采用1.4.2版本下拉框默认去重的方式，只能一个个通过SQL字典去调整嘛？
后续版本有希望能调整下拉框为1.4.2下拉框的默认去重方式嘛？
