### ISSUE TITLE
1.5.8版本，从1.5.0-beta升级过来的

### ISSUE THREAD

**Issue by xiaoxiaomeng1** [jeecgboot/JimuReport#1831]
##### 版本号：
1.5.8

##### 问题描述：
新增的报表保存不了

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/93893464/1c986eb8-48cb-4458-938e-408e55ef5296)

**Comment by xiaoxiaomeng1** [comment]
报表的内容什么也没有添加

**Comment by lvdandan16** [comment]
看后台报什么错，升级sql都添加了吗？

**Comment by zhangdaiscott** [comment]
http://jimureport.com/doc/log
