### ISSUE TITLE
打印莫名出现空白页(设计页面下边空白行已删掉)

### ISSUE THREAD

**Issue by unbelievableTang** [jeecgboot/JimuReport#1832]
##### 版本号：

1.5.6

##### 问题描述：
为啥预览报表时明明没有数据，但打印报表一直有第二页空白页，哪位大佬解答下？
@lvdandan16  之前按照您的描述的步骤，把下面的设计页面下边空白行删掉了，还是有多出来空白页的问题。

##### 错误日志&截图：
![1687316157739](https://github.com/jeecgboot/JimuReport/assets/108724292/de053435-66e5-4c7a-9156-0aa168323a7d)
![image](https://github.com/jeecgboot/JimuReport/assets/108724292/426091af-bd60-4ebe-b8b3-aceca6d44c74)

##### 重现步骤：
同 错误日志&截图 中的内容

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by CowBoy0909** [comment]
遇见相同的问题：
![image](https://github.com/jeecgboot/JimuReport/assets/128303435/6ded421f-d993-4c49-a546-6fa270ec3e99)
![image](https://github.com/jeecgboot/JimuReport/assets/128303435/c8137ec2-ee00-421f-850e-f8dce5afb2fe)

**Comment by lvdandan16** [comment]
就一行数据？

**Comment by unbelievableTang** [comment]
> 就一行数据？

![微信截图_20230625160126](https://github.com/jeecgboot/JimuReport/assets/108724292/e073ad45-bb9d-41d3-84d5-42ee66439ab4)
达到两页数据的时候也会多一页空白页。

**Comment by lvdandan16** [comment]
报表设计和数据导出一下，我们复现一下

**Comment by unbelievableTang** [comment]
> 报表设计和数据导出一下，我们复现一下

好的。数据可以导出，请问报表设计如何导出？

**Comment by lvdandan16** [comment]
设计界面，右键 最下方，导出报表配置

**Comment by unbelievableTang** [comment]
> 报表设计和数据导出一下，我们复现一下

[jimuData.zip](https://github.com/jeecgboot/JimuReport/files/11859165/jimuData.zip)
请查收

**Comment by unbelievableTang** [comment]
> 设计界面，右键 最下方，导出报表配置

你好，目前有解决方案吗

**Comment by tygithub1** [comment]
经测试，有图层图片时候打印不可控，将图片设置到单元格内即可
![image](https://github.com/jeecgboot/JimuReport/assets/27989856/dedfbad7-0b26-40ef-b944-21e6a4511a06)

**Comment by unbelievableTang** [comment]
> 经测试，有图层图片时候打印不可控，将图片设置到单元格内即可 ![image](https://user-images.githubusercontent.com/27989856/255881074-ca3cd5cc-da87-44b2-a042-85ee80d5922b.png)
@tygithub1 
我按照你的方法做了，发现还是会出现空白页

**Comment by tygithub1** [comment]
> > 经测试，有图层图片时候打印不可控，将图片设置到单元格内即可 ![image](https://user-images.githubusercontent.com/27989856/255881074-ca3cd5cc-da87-44b2-a042-85ee80d5922b.png)
> > @tygithub1
> > 我按照你的方法做了，发现还是会出现空白页

你没设置对

**Comment by unbelievableTang** [comment]
> > > 经测试，有图层图片时候打印不可控，将图片设置到单元格内即可 ![image](https://user-images.githubusercontent.com/27989856/255881074-ca3cd5cc-da87-44b2-a042-85ee80d5922b.png)
> > > @tygithub1
> > > 我按照你的方法做了，发现还是会出现空白页
> 
> 你没设置对

好的，感谢，我再研究下

**Comment by unbelievableTang** [comment]
> 经测试，有图层图片时候打印不可控，将图片设置到单元格内即可 ![image](https://user-images.githubusercontent.com/27989856/255881074-ca3cd5cc-da87-44b2-a042-85ee80d5922b.png)

能否通过本地路径获取图片

**Comment by liaozhiyang** [comment]
已处理，下一版本发布。
