### ISSUE TITLE
api数据集报表，用于数据范围控制的携带的限制条件无法传递给后端

### ISSUE THREAD

**Issue by PengLuo22** [jeecgboot/JimuReport#1833]
##### 版本号：
1.4.32

##### 问题描述：
我们把积木报表集成到了我司的SpringBoot系统上（以下简称大平台），业务流程是：1）点击大平台配置的积木菜单->2） 携带token和数据范围限制的条件到积木系统->3） 配置api数据集参数-> 4）携带限制条件和token访问我司的api获取报表数据。
现在的问题是第4步，携带的限制条件无法传递给后端，积木目前没有提供这个后端的拓展接口
##### 重现步骤：
api接口：http://xxx/api/level/getLevelList
Header: token={TOKEN}、orgId={ORG_ID}
其中orgId为限制条件

**Comment by lvdandan16** [comment]
不支持
