### ISSUE TITLE
不能添加图片

### ISSUE THREAD

**Issue by 949564353** [jeecgboot/JimuReport#1839]
##### 版本号：
1.5.8

##### 问题描述：
添加图片地址，图片未显示

##### 错误日志&截图：
<img width="1037" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/24226443/db087dc0-6610-469d-b7ae-09d98060bff2">
<img width="612" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/24226443/2fb201be-f3d1-48c0-80fd-48cd8da0d68b">

##### 重现步骤：
调用接口：https://api.jeecg.com/mock/26/tiaoma1
使用字段tp属性

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
图片是完整的路径吗
F12看看有没有错
