### ISSUE TITLE
在执行sql查询语句时，sum求和重复执行

### ISSUE THREAD

**Issue by Zz9810026** [jeecgboot/JimuReport#1840]
##### 版本号：
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.5.4</version>
</dependency>

##### 问题描述：
您好，在执行此条语句，每次统计sum求和时，有几个sum就会多执行几次query查询

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/138178791/3e9ad376-416b-48ea-8492-d7ab4d47a3b2)
<img width="742" alt="01eaeb4d6237038f7fec061d8198a7b" src="https://github.com/jeecgboot/JimuReport/assets/138178791/385ce482-15cc-4a64-b936-60a5e0d83391">

##### 重现步骤：
![image](https://github.com/jeecgboot/JimuReport/assets/138178791/fd5e7f4a-469c-4e55-b7e9-0e7560386642)

<img width="742" alt="01eaeb4d6237038f7fec061d8198a7b" src="https://github.com/jeecgboot/JimuReport/assets/138178791/0da89de2-6649-46f5-b74b-92fd9ca18993">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
未发现多次调用情况，请确认‘多执行几次query查询’ 是否因为sum导致
