### ISSUE TITLE
啥时候可以适配jdk17呢

### ISSUE THREAD

**Issue by afish177** [jeecgboot/JimuReport#1842]
##### 问题描述：

大佬 jeecg得 在线生成 大屏 积木报表 能否适配jdk17吗？ 能否发适配版本呢(目前在升级jdk17)
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by wangsongjiang** [comment]
同期待推出java17版

**Comment by Qiksy** [comment]
如果你们开放代码就好了，社区可以帮你们适配JDK17

希望官方早日支持JDK17+ 和 Spring boot 3

**Comment by zhangdaiscott** [comment]
制作了一个版本，试试
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot3-starter</artifactId>
  <version>1.6.6</version>
</dependency>
```
