### ISSUE TITLE
数据返回接口show，能否支持数据加密，然后返回密文

### ISSUE THREAD

**Issue by yasenagat** [jeecgboot/JimuReport#1844]
##### 版本号：
官网最新版本

##### 问题描述：

http://api3.boot.jeecg.com/jmreport/show

show接口 返回的response中的result能否返回密文

##### 错误日志&截图：
<img width="421" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/2101309/2cc06486-c290-4cef-8d37-77d9e2b46716">
<img width="674" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/2101309/043bc58e-6e7d-4cf1-8cc9-23d863d60c4c">

**Comment by zhangdaiscott** [comment]
暂无计划
