### ISSUE TITLE
如果报表列太多，在设计界面会不显示，但是预览是可以正常展示的

### ISSUE THREAD

**Issue by wangdong-0607** [jeecgboot/JimuReport#1845]
##### 版本号：
1.5.8

##### 问题描述：
如果报表列太多，在设计界面会不显示，但是预览是可以正常展示的

##### 错误日志&截图：

![图片](https://github.com/jeecgboot/JimuReport/assets/44137057/d6a8a8b3-f9c0-4574-9aec-f00f5c907d89)

##### 重现步骤：
添加很多列，超过AX列，然后保存后，重新从设计进来，列就丢失了，但是预览列还在
这个bug希望能尽快修复

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by wangdong-0607** [comment]
![图片](https://github.com/jeecgboot/JimuReport/assets/44137057/75335c5e-6c27-4cd9-bf76-e502440d7856)
这是预览效果

**Comment by zhangdaiscott** [comment]
手工设置下展示的x轴数量
https://help.jeecg.com/jimureport/config/yaml.html
![image](https://github.com/jeecgboot/JimuReport/assets/3162115/a8305911-1de1-44ce-be2d-4cae44a617e0)
