### ISSUE TITLE
sum函数计算有问题

### ISSUE THREAD

**Issue by Arlen-sc** [jeecgboot/JimuReport#1846]
##### 版本号：
1.5.8

##### 问题描述：
![image](https://github.com/jeecgboot/JimuReport/assets/52154292/99779086-e9d5-4228-905f-ff3a4f062111)

![image](https://github.com/jeecgboot/JimuReport/assets/52154292/9d6946e1-be01-4a89-9df0-a73c27ed7f0f)
![image](https://github.com/jeecgboot/JimuReport/assets/52154292/b005df31-45e0-496d-8ddd-3ad27dfb247c)

##### 重现步骤：
需要重现
可以联系我qq.504571990

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
麻烦做一个错误的示例，把链接地址发一下

**Comment by Arlen-sc** [comment]
我这边没有开放的链接，没搭建，你这边是否有环境，
我可以给模拟数据



***@***.***
 
发件人： lay
发送时间： 2023-08-17 12:44
收件人： jeecgboot/JimuReport
抄送： Arlen-sc; Author
主题： Re: [jeecgboot/JimuReport] sum函数计算有问题 (Issue #1846)
麻烦做一个错误的示例，把链接地址发一下

**Comment by lsqGitHub716** [comment]
那你去[积木报表]线上做一个例子吧( http://jimureport.com/login)

**Comment by lsqGitHub716** [comment]
你这边有做好的示例吗，在官网制作报表示例并提供报表ID，方便问题复现;

**Comment by Arlen-sc** [comment]
电脑坏了，还在维修，需要等待段时间



***@***.***
 
发件人： lay
发送时间： 2023-08-23 16:02
收件人： jeecgboot/JimuReport
抄送： Arlen-sc; Author
主题： Re: [jeecgboot/JimuReport] sum函数计算有问题 (Issue #1846)
你这边有做好的示例吗，在官网制作报表示例并提供报表ID，方便问题复现;

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此任务
