### ISSUE TITLE
积木报表打印

### ISSUE THREAD

**Issue by sizhujian** [jeecgboot/JimuReport#1849]
##### 版本号：

1.5.8
##### 问题描述：
在积木报表打印预览页面，展示的是6条/页，7条数据展示了两页，以及5条补空行，打印的时候，打印了7条数据以及5条空白行数据。想请问一下，积木报表的打印能否实现分页打印，7条数据，能否打印两页？

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/jimureport/report/printNew.html
看看是不是你想要的功能

**Comment by sizhujian** [comment]
我想要的功能是积木报表实现分页打印

**Comment by sizhujian** [comment]
目前来说项目的需求是需要每张单据都打印6条数据，超过6条换页打印，想问一下能不能实现
