### ISSUE TITLE
积木报表打印默认的页眉和页脚怎么设置

### ISSUE THREAD

**Issue by Jayson1998** [jeecgboot/JimuReport#1851]
##### 问题描述：
积木报表里面打印，出现默认的页眉和页脚，这个默认的页眉和页脚在哪可以自定义不用默认的或者去掉啊？

##### 错误日志&截图：
![Uploading [6$2J[W_E}XIVT`RZOMD(YY.png…]()

**Comment by peterjiang4991** [comment]
请问解决了么

**Comment by Jayson1998** [comment]
已解决



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月28日(星期四) 中午11:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/JimuReport] 积木报表打印默认的页眉和页脚怎么设置 (Issue #1851)





 
请问解决了么
