### ISSUE TITLE
采取本地存储文件时  图表设置背景，上传图片无法回显

### ISSUE THREAD

**Issue by bcsflilong** [jeecgboot/JimuReport#1855]
##### 问题描述：
采取本地存储文件时
图表设置背景，上传图片无法回显，图表展示时显示背景为黑色

##### 错误日志&截图：
问题初步判断问题在design.js  2386 行  chartBackgroundUploadSuccess 此方法执行设置path时 没有追加"/jmreport/img" 路径

`//图表背景图上传成功
            chartBackgroundUploadSuccess(res,chartBackground,callback){
                if(!res.success){
                    this.$Message.warning(res.message);
                }else{
                    let path = res.message
                    if(path.indexOf('http')<0){
                        if(path.indexOf('/')!=0){
                            path = '/' + path
                        }
						//add reason:本地文件需要添加路径 图片回显有问题
						path = "/jmreport/img" + path;
                    }
                    this.chartBackground['image'] = path
                    callback&&callback(path);
                    this.chartBackgroundChange(chartBackground);
                }
            },`
          

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
建议用mino或者阿里云
