### ISSUE TITLE
新部署的项目报表加载缓慢

### ISSUE THREAD

**Issue by hyzjz** [jeecgboot/JimuReport#1858]
##### 版本号：
1.5.0

##### 问题描述：
在内网新部署了一个项目，但报表加载缓慢，需要等待20多秒

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/124112905/a40e33be-c25f-4769-8a6b-fe4099299067)
![Uploading image.png…]()

##### 重现步骤：
已经部署了几家项目，有内网，有外网的，但这次的内网加载就很慢，其他项目都正常加载

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
F12看看

**Comment by hyzjz** [comment]
kosmer
***@***.***



&nbsp;你好，我们升级新版本后就可以正常加载了，谢谢您的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月19日(星期三) 中午12:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 新部署的项目报表加载缓慢 (Issue #1858)





 
F12看看

**Comment by zhangdaiscott** [comment]
已经优化，不分组件改成按需加载
