### ISSUE TITLE
使用官方文档自定义api接口数据格式转换器报错

### ISSUE THREAD

**Issue by 798076849** [jeecgboot/JimuReport#1861]
##### 错误日志&截图：
![)9QX5V9E) J0`9E9L88~A$7](https://github.com/jeecgboot/JimuReport/assets/130627334/196e60cc-e013-49c1-891d-0355842d5533)
![2_3`VNJJLZ`CB{YN)`08D Y](https://github.com/jeecgboot/JimuReport/assets/130627334/440153a9-bb77-4193-819a-2385e114a143)
![M5~%1CAPRFJEF@Z_%RHN5 S](https://github.com/jeecgboot/JimuReport/assets/130627334/3ced222f-ab99-4af4-ad94-abd0303f8342)
![image](https://github.com/jeecgboot/JimuReport/assets/130627334/817937a2-0d1b-4713-80f0-5c62a8211bb3)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参照文档：https://help.jeecg.com/jimureport/rumen/apiConver.html
