### ISSUE TITLE
打印预览各导出PDF时背景图片不能跨页显示

### ISSUE THREAD

**Issue by slhe08** [jeecgboot/JimuReport#1862]
##### 版本号：
1.5.8

##### 问题描述：
设置了背景图片，重复设置选择了“双向重复”，报表预览背景图片正常横向纵向重复显示，但是点击【打印】按钮，弹出的打印预览窗口，背景图片只在第一页显示

##### 错误日志&截图：
报表请见：
https://bootapi.jeecg.com/jmreport/shareView/838999694771572736

##### 重现步骤：
1、新建一个报表
2、报表内容跨两页显示
3、设置背景图片（大小200*200），重复设置为“双向重复”
4、点击报表【预览】，点击【打印】按钮弹出打印预览窗口

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 zy

**Comment by liaozhiyang** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/8199499/5e5a2e2e-20b7-47a8-93c6-c60d474c3a8d)
第二页底部需要内容，背景是根据内容高度来撑开的。内容到哪里，背景就到哪里。内容你可以给空
