### ISSUE TITLE
打印预览图片加载不全

### ISSUE THREAD

**Issue by lhhgh** [jeecgboot/JimuReport#1863]
##### 错误日志&截图：
报表预览：
![image](https://github.com/jeecgboot/JimuReport/assets/113173621/91c2d7c5-88ed-4e56-9282-b737daea025b)

打印预览：
![image](https://github.com/jeecgboot/JimuReport/assets/113173621/17d5c41d-ae40-4150-a50f-3ee00ba8ad55)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
是不是你这个图片有点大，html渲染慢导致

**Comment by lhhgh** [comment]
图片不大，都是从华为云直接获取的，可能是图片加载慢导致的。有没有方法能全部加载，慢点没事

**Comment by zhangdaiscott** [comment]
应该就是因为慢导致的
没一行都是不同的图片？

**Comment by lhhgh** [comment]
是的，每一行都是不一样的图片，有方法可以多加载一会吗？

**Comment by liaozhiyang** [comment]
图片是从设计器中上去的还是从数据源中获取的？有预览地址吗？代码有等待图片全部加载完再调出浏览器打印(失败也算，如果是http协议的图片会加载不出来)。

**Comment by liaozhiyang** [comment]
今天拿大量图片，再把浏览器的网速设成低速3G模式也没复现该问题。看能否提供更加详细的步骤或者给预览地址？

**Comment by lhhgh** [comment]
http://114.215.164.81:8080/jimu/jmreport/view/849497110231834624?token=48d70158-bafb-45a3-b12c-bb26dfad6b15
可以访问这个地址看下，打印时我这只有前一百多有图片

**Comment by liaozhiyang** [comment]
<img width="921" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/8199499/00d5f0b8-0b85-44cb-8942-abab7db73f5f">
已经修复，下一版本发布。你可以加上以上代码先解决这个问题

**Comment by zhangdaiscott** [comment]
1.6.1 版本修复

**Comment by lhhgh** [comment]
好的，非常感谢
