### ISSUE TITLE
横向分组使用#{数据集.customGroup(字段名)}右边的单元格不能渲染数据

### ISSUE THREAD

**Issue by 3apt1sm** [jeecgboot/JimuReport#1864]
##### 错误日志&截图：
1、横向分组
![image](https://github.com/jeecgboot/JimuReport/assets/125565421/e79d6170-37f3-43ed-b850-6de524cba7fe)
2、分组后的格式
![image](https://github.com/jeecgboot/JimuReport/assets/125565421/0bc68365-def0-46e9-8c14-e3295fbe99da)
3、分组后右侧输入任意值系统会报错
![image](https://github.com/jeecgboot/JimuReport/assets/125565421/b59e4ea0-7df0-41d6-9bcb-e17e324bae59)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lvdandan16** [comment]
数据集.customGroup(字段名)不支持动态分组，你这个地方应该使用数据集.groupRight()
参考文档：
动态横向分组：https://help.jeecg.com/jimureport/group/transverseDynamic.html
相邻合并：https://help.jeecg.com/jimureport/group/transverse.html
