### ISSUE TITLE
在W列之后添加compute计算函数导致整个报表都无法显示

### ISSUE THREAD

**Issue by JianYT** [jeecgboot/JimuReport#1866]
##### 版本号：
1.5.8

##### 问题描述：
在W列之后添加compute计算函数导致整个报表都无法显示

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/11935123/231f3e78-0bb5-4647-a5be-dcee25141faf)
![image](https://github.com/jeecgboot/JimuReport/assets/11935123/2ffdbeb9-db69-4ca3-ab51-25bd8e221c1b)
![image](https://github.com/jeecgboot/JimuReport/assets/11935123/cf6d855e-e528-4291-a35e-be64f54115fc)
![image](https://github.com/jeecgboot/JimuReport/assets/11935123/c38b2e2f-dc97-4a90-a0e7-0282e79b569d)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
请提供一个测试示例给我们，方便复现问题

**Comment by lsqGitHub716** [comment]
已修改
