### ISSUE TITLE
循环块中包含主子报表

### ISSUE THREAD

**Issue by xzcong** [jeecgboot/JimuReport#1869]
##### 版本号：
1.5.8

##### 问题描述：
问题描述请参考
[I4IRXU](https://gitee.com/jeecg/JimuReport/issues/I4IRXU)，请问这个问题可以解决一下？
推荐解决办法：https://gitee.com/jeecg/jeecg-boot/issues/I4CCNS 不适合，因为主表的数据是动态的
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by cgigo** [comment]
同问，这个问题困扰很久了

**Comment by zhangdaiscott** [comment]
不支持

**Comment by sanye8899** [comment]
同问，这个问题困扰很久了
