### ISSUE TITLE
日期控件

### ISSUE THREAD

**Issue by guozhiqiang-123** [jeecgboot/JimuReport#1871]
**版本号：1.5.8**

**问题描述：使用火狐浏览器时，年月日期框无法显示默认值且日期框显示异常，未设置默认值情况下，日期框正常使用；**

**错误日志&截图：**

![image](https://github.com/jeecgboot/JimuReport/assets/66155514/fa36dc68-34e9-4fe2-acde-c2c98e949c91)
![image](https://github.com/jeecgboot/JimuReport/assets/66155514/59040e3a-b341-4b7d-8002-c7c63eec423d)
![image](https://github.com/jeecgboot/JimuReport/assets/66155514/516ae487-de8a-49e9-8026-9100e1bfe22e)

**Comment by zhangdaiscott** [comment]
收录

**Comment by 1298191366** [comment]
已修复，待新版本发布
