### ISSUE TITLE
请问一下支持根据不同的列值动态排序吗，例如根据金额排序，或者根据订单时间排序，不是由数据源写死的那种动态排序

### ISSUE THREAD

**Issue by havetohuang** [jeecgboot/JimuReport#1873]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by havetohuang** [comment]
版本号：V1.59
问题描述：不知道是否支持根据不同的列动态排序
错误日志&截图：希望得到回答
重现步骤：谢谢各位工程师的免费使用

**Comment by zhangdaiscott** [comment]
no
