### ISSUE TITLE
如何注释打印台数据

### ISSUE THREAD

**Issue by lcy767** [jeecgboot/JimuReport#1876]
##### 问题描述：
如何能注释掉 ：console.log('数据对象',strObj)这行代码

##### 错误日志&截图：
![Uploading image.png…]()

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
收录

**Comment by imbigsnake** [comment]
为什么要注释掉？打印出来不挺好的吗

**Comment by lcy767** [comment]
> 收录
我是想知道如何去注释掉这行代码的办法。
