### ISSUE TITLE
在使用sql带参的时候报非法字符   使用Oracle数据库

### ISSUE THREAD

**Issue by Mryangkx** [jeecgboot/JimuReport#1880]
![1689904252122](https://github.com/jeecgboot/JimuReport/assets/75605416/49296eda-f0f3-42d2-9f54-84620ab49c88)
##### 错误日志&截图：
![1689904399478](https://github.com/jeecgboot/JimuReport/assets/75605416/4ecd93fd-fec1-484b-a2c6-e9444ae6de04)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；
/

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/3162115/0ed332d3-8be2-4b38-ac41-fbb4c04e257a)

这是什么意思？

**Comment by Mryangkx** [comment]
就是我是用sql带参数的方式  然后我在路径中传一个id的参数过来查不到数据  报错
 illegal identifier : &pos 1, line 1, column 2{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2ODk4NDU4MzYsInVzZXJuYW1lIjoiYWRtaW4ifQ.sACHZb52LYEFzVuCbkQ_LUFDbtrl2rvp5qLGQ_ehARg","id":"3D927D00512F4DC58567BCC3B5B409B0","pageNo":1,"pageSize":10,"jmViewFirstLoad":"1"}


写的时候我的sql是：select * from test where id='${id}'
但是解析完后保存确定后  报表sql就变成select * from test where id=&#39;${id}&#39;
使用mysql数据库 ''这个就保存确定后不会变还是''   但是oracle保存确定后就变成&#39;这个

**Comment by zhangdaiscott** [comment]
写的太乱，没明白

**Comment by Mryangkx** [comment]
就是使用sql带参出错&nbsp; &nbsp;你可以试下嘛&nbsp; 使用Oracle



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月21日(周五) 下午2:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/JimuReport] 在使用sql带参的时候报非法字符   使用Oracle数据库 (Issue #1880)




 
写的太乱，没明白

**Comment by Mryangkx** [comment]
a1481582028
***@***.***



&nbsp;
就是我是用sql带参数的方式&nbsp; &nbsp;报错信息如下
illegal identifier : &amp;pos 1, line 1, column 2{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2ODk4NDU4MzYsInVzZXJuYW1lIjoiYWRtaW4ifQ.sACHZb52LYEFzVuCbkQ_LUFDbtrl2rvp5qLGQ_ehARg","id":"3D927D00512F4DC58567BCC3B5B409B0","pageNo":1,"pageSize":10,"jmViewFirstLoad":"1"}



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月21日(星期五) 下午2:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 在使用sql带参的时候报非法字符   使用Oracle数据库 (Issue #1880)





 
写的太乱，没明白

**Comment by Mryangkx** [comment]
a1481582028
***@***.***



&nbsp;
预览的时候把参数加到路径中后就弹出下面的报错信息


illegal identifier : &amp;pos 1, line 1, column 2{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2ODk4NDU4MzYsInVzZXJuYW1lIjoiYWRtaW4ifQ.sACHZb52LYEFzVuCbkQ_LUFDbtrl2rvp5qLGQ_ehARg","id":"3D927D00512F4DC58567BCC3B5B409B0","pageNo":1,"pageSize":10,"jmViewFirstLoad":"1"}



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月21日(星期五) 下午2:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 在使用sql带参的时候报非法字符   使用Oracle数据库 (Issue #1880)





 
写的太乱，没明白

**Comment by Mryangkx** [comment]
a1481582028
***@***.***



&nbsp;
sql的单引号会变成网页的代表符号&nbsp; &amp;#39&nbsp; &nbsp; &nbsp;&amp;#39在网页中代表单引号


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月21日(星期五) 下午2:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 在使用sql带参的时候报非法字符   使用Oracle数据库 (Issue #1880)





 
写的太乱，没明白
