### ISSUE TITLE
数据报表-报表设计这一块，有些excel模板点击复制时提示权限不足，有些excel模板复制又没问题，要如何配置?

### ISSUE THREAD

**Issue by jiandandian-max** [jeecgboot/JimuReport#1882]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
按格式要求发issue
