### ISSUE TITLE
数据集未查询出数据，无法将数据集与报表绑定

### ISSUE THREAD

**Issue by xc925988564** [jeecgboot/JimuReport#1885]
##### 问题描述：
数据集未查询出数据，无法将数据集与报表绑定

##### 重现步骤：
创建数据集，sql查询数据为空，保存数据集，返回设计页面，拖出折线图设置绑定数据集，接口返回为null，js报错，无法保存成功，使用中很难发现是该问题影响的，建议优化查不出数据也可以保存配置，有数据了直接显示数据

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
查询不出数据，无法获取表字段，无法绑定，可以表中先插入一条数据，绑定后，数据再删除
