### ISSUE TITLE
报表钻取后 返回上一页发现 日期查询条件的日期变成上一天了

### ISSUE THREAD

**Issue by wenhongjun** [jeecgboot/JimuReport#1886]
##### 版本号：
1.5.9

##### 问题描述：
报表钻取到另一个报表后 返回上一页， 这个时间查询条件的日期少了一天，通过接口发现参数是对的就是显示有问题，日期变成前一天了

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/40422721/a67ee915-caae-47fd-bc51-c36fd0ea5f25)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
已修改
