### ISSUE TITLE
报表预览格式正常，导出后金额字段显示为多个0

### ISSUE THREAD

**Issue by yue1132** [jeecgboot/JimuReport#1887]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/3067644/2064b3bf-0715-402f-a47e-56a2e6f7d9fa)
![image](https://github.com/jeecgboot/JimuReport/assets/3067644/64792095-a510-4a8b-9941-67747e30af46)

##### 重现步骤：
金额字段为数字格式，值为null，预览导出出现后面多个0的格式。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
未复现，试一下设置小数位数看看是否生效，我测试数据库为空导出的就是空数据
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/7c1d90e4-0be2-48c8-be78-d3b633541fe7)
