### ISSUE TITLE
设计画面如何插入报表参数？

### ISSUE THREAD

**Issue by sunxfly** [jeecgboot/JimuReport#1888]
##### 版本号：
1.5.8

##### 问题描述：
设计页面单元格中，想插入“报表参数“数据的显示，应该怎么写？用${q}显示为空白。

##### 错误日志&截图：
报表参数设置：
![image](https://github.com/jeecgboot/JimuReport/assets/5136796/1f89e266-e3e9-4524-9d23-aede2fcd4752)
单元格中插入：
![image](https://github.com/jeecgboot/JimuReport/assets/5136796/ac045c19-36bb-472e-b7fc-0478df13763b)
预览显示：
![image](https://github.com/jeecgboot/JimuReport/assets/5136796/44ba8f90-9b34-4db7-a8d8-7e2c61a94345)

##### 重现步骤：
见上图。

**Comment by lvdandan16** [comment]
参考文档：https://help.jeecg.com/jimureport/summary/paramReport.html
