### ISSUE TITLE
你好，可以自定义导出excel后，把数值为文本类型的转换为数字字段吗？数值的文本字段涉及到计算会无法正常运算

### ISSUE THREAD

**Issue by cfy3133** [jeecgboot/JimuReport#1889]
##### 问题描述：
![1690507454795](https://github.com/jeecgboot/JimuReport/assets/43978367/f3f2efd5-2138-4170-8570-0ebc4bb1f1bb)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持，此处专门转为字符串的
