### ISSUE TITLE
引入的权限问题提问

### ISSUE THREAD

**Issue by anluster** [jeecgboot/JimuReport#1891]
##### 版本号：
v1.5.9

##### 问题描述：
我在个人项目（若依框架）里引入积木后，无法新建报表，也无法复制模板，是因为权限问题吗？请问需要怎么处理呢？
##### 错误日志&截图：
![%AT2R~`VQY5IL Y$11PBM0E](https://github.com/jeecgboot/JimuReport/assets/140869036/9695e46e-569c-493b-b483-9af7f981f857)

![`~R U90@YP}D01M69$YVMTX](https://github.com/jeecgboot/JimuReport/assets/140869036/6992e1cd-fd3d-4395-a049-1a427e62341a)

##### 重现步骤：
新建报表保存报错。
复制自带模板弹出没有权限。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
集成问题，自己看错误
