### ISSUE TITLE
页码显示有误

### ISSUE THREAD

**Issue by mylidong** [jeecgboot/JimuReport#1893]
##### 版本号：
最新版

##### 问题描述：
报表查看是url中加入 pageNo页码时如：  http://localhost:8085/jmreport/view/842265662076841984?pageNo=4
页面工具栏页码没变。

##### 错误日志&截图：
<img width="393" alt="1690795395076" src="https://github.com/jeecgboot/JimuReport/assets/57850334/5483770c-d8d1-499e-a1fd-0b2d7b61039c">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
已修改
