### ISSUE TITLE
配置报表到JeecgBoot菜单

### ISSUE THREAD

**Issue by moutianh** [jeecgboot/JimuReport#1894]
##### 版本号：
1.5.8

##### 问题描述：
报表集成到jeecgBoot菜单上如何实现页签切换时页面缓存,菜单管理里面设置了缓存路由但是不管用

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/112364684/9c7fbd40-cbfa-429e-b098-053b3bcd6653)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
报表肯定不支持缓存

**Comment by moutianh** [comment]
> 
切换页签的时候不能缓存么? 每次切换都要重新加载一下
