### ISSUE TITLE
自定义函数参数中有单元格取值和自定义参数时，单元格参数获取为空

### ISSUE THREAD

**Issue by yczxl** [jeecgboot/JimuReport#1895]
##### 版本号：
1.5.9

##### 问题描述：
自定义函数getIndexVal，在配置使用时，第一个参数是A1【取单元格的值】，第二个参数时字符串
- 配置为=getIndexVal(A1,'2023-07-31')，此时在代码中获取不到A1的值，排查为env中为空；
- 配置为=getIndexVal('test','2023-07-31')，就可以获取到第一个参数的值

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/12946794/235b20d4-79e4-4a3c-9168-9480d3333c39)

##### 重现步骤：
在自定义函数中参数设置从单元格取值，就可以复现

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
已修改

**Comment by yczxl** [comment]
经过同样的案例，在1.6.4版本中依然可以复现此问题。麻烦确认下此版本是都修复此问题
