### ISSUE TITLE
调用存储过程传入日期类型的参数时一直会报文字与格式不匹配，已经去除了单引号

### ISSUE THREAD

**Issue by Sgrvaries** [jeecgboot/JimuReport#1898]
##### 错误日志&截图：
<img width="1208" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/15855111/adddebf2-b1f3-427b-8c83-9c2196bfe7bc">
![WX20230802-110008@2x](https://github.com/jeecgboot/JimuReport/assets/15855111/e18dd446-a39e-4dd7-9d35-958a016e1859)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
报表参数是否有默认值

**Comment by 1298191366** [comment]
未复现，请提供报表配置和数据库数据，我们复现一下
存在游标
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/47bd1524-be1f-4314-9661-156d9838a3c7)
不存在游标
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/866cfc29-c2e0-4e10-b41f-1e65fe7b64e4)
