### ISSUE TITLE
API数据集返回为图片链接时，打印时会在后面默认加上time={时间戳}，请问如何删掉时间戳

### ISSUE THREAD

**Issue by P1casso** [jeecgboot/JimuReport#1899]
##### 问题描述：
API数据集返回为图片链接时，打印会在后面默认加上time={时间戳}，导致打印内容不正确，请问如何删掉时间戳
##### 错误日志&截图：
**我的API数据集是通过我的一个接口，返回对应的图片地址，预览的时候是正常的**

![image](https://github.com/jeecgboot/JimuReport/assets/60685688/0b65cab6-650c-41c5-8b22-da3f9202c246)

**API返回结果：**
![image](https://github.com/jeecgboot/JimuReport/assets/60685688/302561e8-ed86-494f-bb59-6dbccfaac107)

**预览：**
![image](https://github.com/jeecgboot/JimuReport/assets/60685688/3d2cda69-a0f5-4de3-8047-ded76da22362)

**打印的时候，系统会在接口上带上time=时间戳**
![image](https://github.com/jeecgboot/JimuReport/assets/60685688/d1a7e406-fefd-49af-974f-ace1a23dcdca)

_打印结果“：_
![image](https://github.com/jeecgboot/JimuReport/assets/60685688/b6c8e87e-4828-42e3-9b0b-cc1fea0bbae0)

**Comment by lvdandan16** [comment]
收录 zy

**Comment by lvdandan16** [comment]
未复现，可在[积木官网](http://bi.qiaoqiaoyun.com/)提供示例

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此任务
