### ISSUE TITLE
循环块分组

### ISSUE THREAD

**Issue by hellodajun** [jeecgboot/JimuReport#1900]
##### 版本号：
1.5.9

##### 问题描述：
<img width="423" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/1825773/9f0f6860-a06d-42f4-8dda-1532c1992bf6">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by hellodajun** [comment]
图上的效果，支持吗？

**Comment by lvdandan16** [comment]
图上效果不支持，目前分组小计支持如下方式：
参考文档https://help.jeecg.com/jimureport/group/verticalSubtotal.html
