### ISSUE TITLE
stv、case等表达式函数没有循环结果集计算

### ISSUE THREAD

**Issue by freewind1977** [jeecgboot/JimuReport#1901]
##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/26646785/4fe06fb1-c0af-4761-b2f5-97eca1e05d69)

上图使用stv表达式来转换E3列的数据值，下图为预览效果：
![image](https://github.com/jeecgboot/JimuReport/assets/26646785/bd3d5559-7bac-46c1-bc6f-20ab5f545196)
上图中，stv(E3)并没有循环数据，而是只用E3单元格的值来做的判断，尝试使用case、if都是一样的
但sum(D3,E3)是可以循环计算的，如下图：
![image](https://github.com/jeecgboot/JimuReport/assets/26646785/7feac703-e04e-4022-b6e3-3fd2eb11d18d)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
直接使用E3只取一个值，可以使用str(数据集.字段名称)
