### ISSUE TITLE
多租户 tenantid 已传，结果未区分

### ISSUE THREAD

**Issue by 510956114** [jeecgboot/JimuReport#1902]
##### 错误日志&截图：
![1691048383286](https://github.com/jeecgboot/JimuReport/assets/104486633/ee9d5769-2db2-457a-9a67-aa9130ec2de9)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
[配置文件中的openTenant属性是否为true ；[参考](https://x.topthink.com/preview/WPMeNm/config/yaml.html)
![image](https://github.com/jeecgboot/JimuReport/assets/65587928/6b49fe64-5794-44df-a215-d3cf0d695553)
