### ISSUE TITLE
api数据集字段与报表函数同时在表单一行时，函数不生效

### ISSUE THREAD

**Issue by Lruri74** [jeecgboot/JimuReport#1905]
##### 问题描述：
api数据集字段数据与报表函数同时存在表单同一行时，函数不生效

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/132562022/6ca6c93b-ee29-43c9-a5ec-c111857c7de5)

![image](https://github.com/jeecgboot/JimuReport/assets/132562022/59fe1546-2c63-42dc-bfa1-4e037e3f93c7)

##### 重现步骤：
1.集成api数据集
2.设计表格
3.拉取api字段
4.api统计字段与函数（例如：SUM）放在合计行
5.保存设计后点击预览：函数统计数据为0或空

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
#{字段}格式的表示需要循环处理，获取单一数据格式${字段}
