### ISSUE TITLE
报表下钻时如果有多个值一样时，只会选择第一个

### ISSUE THREAD

**Issue by yangqigit** [jeecgboot/JimuReport#1906]
##### 版本号：
1.5.0

##### 问题描述：
报表下钻时如果有多个值一样时，只会选择第一个

##### 错误日志&截图：
点击铜川的2 详单是宝鸡
![3](https://github.com/jeecgboot/JimuReport/assets/37768831/bdacd345-40de-4069-8aae-9bbeeb441316)

查看源码发现是直接用值比较的，源码要修改一下，这里需要选择这一行进行下钻

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by yangqigit** [comment]
查看源码发现是直接用值比较的，源码要修改一下，这里需要选择这一行进行下钻

**Comment by lvdandan16** [comment]
可以用自定义方式动态获取值，3.3自定义表达式配置B3列
https://help.jeecg.com/jimureport/linkage/reportDrilling.html
