### ISSUE TITLE
配置多个报表到JeecgBoot菜单且均配置为非外部方式，导致jeecgboot无响应

### ISSUE THREAD

**Issue by freewind1977** [jeecgboot/JimuReport#1907]
##### 版本号：
jeecgboot 2.4.5
jimureport 1.5.9

##### 问题描述：
将多个积木报表挂载到jeecgboot的菜单中，当打开方式设置为：非外部时，无法同时打开两个配置的报表/图表

##### 重现步骤：
1. 使用jimureport配置两个图表
2. 将两个图表按照官网的说明挂载到jeecgboot的菜单上，但打开方式为非外部；
3. 打开某一个配置的图表，显示正常，关闭jeecgboot选项卡（也就关闭图表），再打开另外一个图表，正常显示；
4. 打开某一个配置的图表，显示正常，此时不关闭这个图表，再打开另外一个图表，此时jeecgboot不会弹出新的页签，整个应用无响应；

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
你使用的vue2还是vue3？

**Comment by freewind1977** [comment]
我的jeecgboot是2.4.3和2.4.5的，是vue2

**Comment by lsqGitHub716** [comment]
vue2测试未复现你说的问题，请尝试排查一下是否有其他报错导致；
![test222](https://github.com/jeecgboot/JimuReport/assets/65587928/758ecbda-322c-479e-841c-e9b71dfa9ddd)
