### ISSUE TITLE
分组排序

### ISSUE THREAD

**Issue by syliang2020** [jeecgboot/JimuReport#1909]
##### 版本号：
                  <dependency>
			<groupId>org.jeecgframework.jimureport</groupId>
			<artifactId>jimureport-spring-boot-starter</artifactId>
			<version>1.5.8</version>
		</dependency>

##### 问题描述：
参照官网文档配置分组排序，文档地址https://help.jeecg.com/jimureport/group/dataSort.html，纵向分组默认排序并不能达到预期效果，（默认排序跟正序好像是一样的）
SQL数据集配置
![image](https://github.com/jeecgboot/JimuReport/assets/58301329/a6d3894b-2ec3-4211-8e9a-37ba7c8b30d8)
数据预览
![image](https://github.com/jeecgboot/JimuReport/assets/58301329/edac9850-8ea9-4103-a052-0839ad77faa7)
数据库执行语句结果集
![image](https://github.com/jeecgboot/JimuReport/assets/58301329/b825a572-dfc1-4b50-821b-441fa89653a2)
报表配置
![image](https://github.com/jeecgboot/JimuReport/assets/58301329/fc007786-be60-415c-9c4e-10ab7e33bb1c)
实际效果与预期结果不符，数据预览的顺序是对的，分组排序后顺序错乱
![image](https://github.com/jeecgboot/JimuReport/assets/58301329/8d9bece1-3fa6-479f-aa63-c52634629fe8)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
什么数据库

**Comment by syliang2020** [comment]
> 什么数据库

MYSQL8.0

**Comment by zhangdaiscott** [comment]
完整的数据贴一下，你的需求是按照什么排序

**Comment by syliang2020** [comment]
> 完整的数据贴一下，你的需求是按照什么排序

模拟数据
select * from (
select 7 as id ,'三年级' as grade_name ,'三年级二班' as class_name from dual union 
select 4 as id ,'二年级' as grade_name ,'二年级一班' as class_name from dual union 
select 5 as id ,'二年级' as grade_name ,'二年级二班' as class_name from dual union 
select 1 as id ,'一年级' as grade_name ,'一年级一班' as class_name from dual union 
select 9 as id ,'四年级' as grade_name ,'四年级二班' as class_name from dual union 
select 3 as id ,'一年级' as grade_name ,'一年级三班' as class_name from dual union 
select 8 as id ,'四年级' as grade_name ,'四年级一班' as class_name from dual union 
select 6 as id ,'三年级' as grade_name ,'三年级一班' as class_name from dual union 
select 2 as id ,'一年级' as grade_name ,'一年级二班' as class_name from dual union
select 10 as id ,'四年级' as grade_name ,'四年级三班' as class_name from dual 
) t order by t.id
报表配置
![image](https://github.com/jeecgboot/JimuReport/assets/58301329/4bbc7beb-1553-4780-b0f8-9b5718e98d0d)
实际效果
![image](https://github.com/jeecgboot/JimuReport/assets/58301329/a55331c5-3d9d-4be8-aef0-3b76701dadb8)

需要的排序效果按照，一年级、二年级、三年级、四年级 排序
参考的官网配置示例，https://help.jeecg.com/jimureport/group/dataSort.html

**Comment by lvdandan16** [comment]
收录   sq

**Comment by zhangdaiscott** [comment]
1.6.1+版本后，会支持文本排序
https://help.jeecg.com/jimureport/group/dataSort.html

**Comment by syliang2020** [comment]
> 1.6.1+版本后，会支持文本排序 https://help.jeecg.com/jimureport/group/dataSort.html

好的，谢谢
