### ISSUE TITLE
时间在苹果手机和Safari浏览器上现实NaN

### ISSUE THREAD

**Issue by windyfat** [jeecgboot/JimuReport#1912]
##### 版本号：
开源版本

##### 问题描述：
报表中的时间在苹果手机和Safari浏览器上面显示NaN，在Google浏览器正常

##### 错误日志&截图：
在Safari浏览器截图：
![image](https://github.com/jeecgboot/JimuReport/assets/33481024/04524ad3-d4c8-44aa-8220-fe53e9776543)
在Google浏览器截图：
![image](https://github.com/jeecgboot/JimuReport/assets/33481024/24bd712e-7fa3-4a16-840d-567c88cc7350)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
补充版本号
