### ISSUE TITLE
怎么根据分组后每个合计数量进行排序

### ISSUE THREAD

**Issue by qwerqwer1234234** [jeecgboot/JimuReport#1914]
##### 问题描述：
![image](https://github.com/jeecgboot/JimuReport/assets/100072068/dad8e77e-a260-49cd-b741-af3085fa04af)

怎么根据分组后每个合计数量进行排序

##### 错误日志&截图：

1##### 重现步骤：

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
