### ISSUE TITLE
横向动态列分组无法展示

### ISSUE THREAD

**Issue by notow666** [jeecgboot/JimuReport#1915]
##### 版本号：

1.6.0
##### 问题描述：
按照文档和示例设置最简单的横向动态列分组报表，动态列不展示数据

##### 错误日志&截图：

后台没有异常日志
##### 重现步骤：
这是我这边的报表设置截图：

![a23bb9db70bb2d2836cc8f8a1e90d809](https://github.com/jeecgboot/JimuReport/assets/33338046/e65b95da-ba97-48e0-a51a-2dae26f02667)
![1cead99fe7ed908a401082ddb0e60cef](https://github.com/jeecgboot/JimuReport/assets/33338046/c8d00651-b9d0-4f9e-aa75-674a8bbe964f)
![38bd005ef2b8e92e589cb9bad6a9c282](https://github.com/jeecgboot/JimuReport/assets/33338046/730dc300-dee9-4421-8f51-690be68395e3)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by notow666** [comment]
我在官网做了个示例，也是这样：
https://bootapi.jeecg.com/jmreport/index/849914460041990144

**Comment by zhangdaiscott** [comment]
你基于那个字段分组的配置都没有？怎么会好使

**Comment by notow666** [comment]
> 你说的这个基于某个字段分组的配置，是如图这里吗？我设置了也没用，有什么可参考的文档个示例吗？
![image](https://github.com/jeecgboot/JimuReport/assets/33338046/55402f85-3be3-48d6-9e54-9c06b1321bf4)
