### ISSUE TITLE
怎么分组小计后进行排序

### ISSUE THREAD

**Issue by qwerqwer1234234** [jeecgboot/JimuReport#1916]
##### 问题描述：

根据分组后合计大小对地区进行排序

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/100072068/76b94bb9-c372-42e2-9b18-33e066c6ebdf)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持
