### ISSUE TITLE
拼接?token=时请求报错400

### ISSUE THREAD

**Issue by qwerqwer1234234** [jeecgboot/JimuReport#1917]
##### 版本号：
1.5.9

##### 问题描述：
拼接?token=时请求报错400

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/100072068/3b203dc3-c08d-4d65-9b84-5058a02c8967)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
自己看下后台check逻辑
![image](https://github.com/jeecgboot/JimuReport/assets/3162115/a71caed9-b244-4973-9705-6edf29fa8904)
