### ISSUE TITLE
Tomcat 提示 积木报表开启了一个线程，无法关闭，最后导致内存泄漏  

### ISSUE THREAD

**Issue by zzl980114** [jeecgboot/JimuReport#1919]
##### 问题描述：
Tomcat 提示 积木报表开启了一个线程，无法关闭，最后导致内存泄漏  

##### 错误日志&截图：
![图片](https://github.com/jeecgboot/JimuReport/assets/124235418/e0cb7b91-3fa4-4adf-b148-ec191bf1cd76)

##### 重现步骤：
这个不太清楚，我就是打开了一个积木报表，然后关闭，当时没有报错，后来网站崩了，看tomcat日志发现的

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
版本号

**Comment by zhangdaiscott** [comment]
提供更详细的错误日志和报错代码行
