### ISSUE TITLE
版本1.6.0图表显示异常，数据已经提取，但部分内容未显示完全，呈现空白。

### ISSUE THREAD

**Issue by happyuanhao** [jeecgboot/JimuReport#1921]
##### 版本号：
1.6.0

##### 问题描述：

图表显示异常，部分内容未显示完全，但是点击打印却可以显示出来。
##### 错误日志&截图：
![1692000004351](https://github.com/jeecgboot/JimuReport/assets/25651702/b41e071c-7803-4cda-8f3b-45a9b0b3efaa)
![1692000221542](https://github.com/jeecgboot/JimuReport/assets/25651702/dd0341e8-a399-4671-ab5d-8bdff1e80826)
![1692000297526](https://github.com/jeecgboot/JimuReport/assets/25651702/0668cce9-e569-478d-9d08-376eb7c980e7)
![1692000443035](https://github.com/jeecgboot/JimuReport/assets/25651702/ecc82250-4f31-47da-b4b1-6f9489890e8a)

##### 重现步骤：

我的图表都是做好的，在1.56 1.58 1.59 显示都正常 在1.6.0上显示不全，但是点击图表空白部分能看部分数据。
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
线上提供例子

**Comment by happyuanhao** [comment]
如何线上提供例子呢？ 目前我使用的是api的形式从项目中提取的数据，然后显示在平台上 这个api接口 我无法在线上提供。 不是查库的方式，或者加微信我可以发个演示视频。

**Comment by happyuanhao** [comment]
你好 我提供导出报表配置那个sql可以吗

**Comment by happyuanhao** [comment]
放错图了 不好意思 这个图。
![1692001542529](https://github.com/jeecgboot/JimuReport/assets/25651702/50121f85-8a6f-481f-84e3-34942459560b)

**Comment by freewind1977** [comment]
与我遇到的问题一样，原因是你的数据中有0值，且单元格式的格式设置为"数值"就会有上面的问题 #1936

**Comment by happyuanhao** [comment]
我设置成正常格式 也不显示

**Comment by happyuanhao** [comment]
![1692350376356](https://github.com/jeecgboot/JimuReport/assets/25651702/342c3dec-c8ae-4fb4-b1d6-9bb868ca444d)
出现此问题 F12有报错。

**Comment by lvdandan16** [comment]
导出报表配置或者积木报表官网做例子就可以

**Comment by happyuanhao** [comment]
[report-export-mysql.txt](https://github.com/jeecgboot/JimuReport/files/12449181/report-export-mysql.txt)

**Comment by happyuanhao** [comment]
导出的报表配置为sql文件，把上条回复中后缀改为sql即可。

**Comment by liaozhiyang** [comment]
已经修复，下一版本发布。
你这个应该是数据中有0导致的，你数据格式别从顶部选，先从右边面板选择(数值)可以解决。
