### ISSUE TITLE
在积木报表中的查询条件，对应内容如何用sql定义数据内容？

### ISSUE THREAD

**Issue by NBmumu** [jeecgboot/JimuReport#1922]
##### 版本号：
1.5.6

##### 问题描述：
①报表的查询条件中，如何对查询字段进行自定义数据源？最好能用sql单独写那种，可以实现么？

②这个下拉数据如何进行去重？
非常感谢

##### 错误日志&截图：

<img width="882" alt="mmexport1692065733318" src="https://github.com/jeecgboot/JimuReport/assets/142280577/17a170e5-7405-4589-8929-51cdea47b8ea">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持sql

https://help.jeecg.com/jimureport/query/controlType.html
