### ISSUE TITLE
插入图表，绑定了数据，无法在图表展示

### ISSUE THREAD

**Issue by qwerqwer1234234** [jeecgboot/JimuReport#1923]
##### 问题描述：
插入图表，绑定了数据，无法在图表展示

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/100072068/74b99f95-0853-46a2-b170-57ca45f8b3ae)
![image](https://github.com/jeecgboot/JimuReport/assets/100072068/51a47528-4600-4e71-a20e-ba563f294479)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by qwerqwer1234234** [comment]
点保存和运行都不管用

**Comment by qwerqwer1234234** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/100072068/e0cf0a8c-04b3-48af-bd0d-8277929a458e)
刷新之后一直绑定静态数据源，

**Comment by zhangdaiscott** [comment]
不符合issue格式要求
