### ISSUE TITLE
插入图表无法选择sql数据集，选择后点击保存和运行都不生效

### ISSUE THREAD

**Issue by qwerqwer1234234** [jeecgboot/JimuReport#1925]
##### 版本号：
1.6.0

##### 问题描述：
插入图表无法选择sql数据集，选择后点击保存和运行都不生效

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/100072068/26328af7-adba-49ea-aede-f0bdd88f2a0a)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
未复现，请导出报表配置和数据我们复现一下
设计页面
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/acb6adc5-bad7-4053-803d-6ec7cba3d032)
预览页面
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/e2a957d5-810c-496d-a628-c6bcd57218d1)
