### ISSUE TITLE
打印时数据显示空白

### ISSUE THREAD

**Issue by Dy-yangming** [jeecgboot/JimuReport#1926]
##### 版本号：

1.6.0
##### 问题描述：

当数据集是调用存储过程，并且需要传参时。会出现点击打印按钮后，返回的数据集为空的情况。怀疑是参数值没有传到存储过程。
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/75370150/97bc07b7-5949-43bc-acd5-03e75b86f49a)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
导出报表配置或线上提供例子
