### ISSUE TITLE
如何实现二级循环

### ISSUE THREAD

**Issue by xiaojie515** [jeecgboot/JimuReport#1927]
##### 问题描述：
如何实现二级数组循环？

一场篮球比赛，现在要实现在一个报表内显示所有队伍信息和队伍运动员的信息，目前通过循环块能够实现显示队伍信息，但是无法显示运动员信息，运动员信息是在同一个数据源的二级数组内。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by xiaojie515** [comment]
根据“主子报表”手册 https://help.jeecg.com/jimureport/masterReport/apiData.html，我需要实现的功能是在一个页面显示所有的供货商信息及对应的订单详情，不知能否实现

**Comment by zhangdaiscott** [comment]
你应该把队伍和运动员整理成一个数据集，然后通过分组来实现

**Comment by xiaojie515** [comment]
> 你应该把队伍和运动员整理成一个数据集，然后通过分组来实现

目前队伍和运动员是在一个数据集里面，它的格式为
[
       {
       team_name:'队伍1',
       team_id:'',
       athlete_list:[
		   {id:1,name:'cc1'},
		   {id:2,name:'cc2'},
		   {id:3,name:'cc3'},
		]
       },
       {
       team_name:'队伍2',
       team_id:'',
       athlete_list:[
		   {id:1,name:'cc1'},
		   {id:2,name:'cc2'},
		   {id:3,name:'cc3'},
		]
       },
       {
       team_name:'队伍3',
       team_id:'',
       athlete_list:[
		   {id:1,name:'cc1'},
		   {id:2,name:'cc2'},
		   {id:3,name:'cc3'},
		]
       },
]


请问要怎么实现分组呢？
