### ISSUE TITLE
报表设置背景图片（双向重复），导出PDF时只显示一张被拉大了的图片（未双向重复）

### ISSUE THREAD

**Issue by slhe08** [jeecgboot/JimuReport#1929]
##### 版本号：
1.6.0

##### 问题描述：
报表设置了背景图片（自定义水印），且设置双向重复，但是导出的PDF中，每一页只显示一张图片，并未双向重复。
期望：导出的PDF中图片也双向重复

##### 错误日志&截图：
报表请见：
https://bootapi.jeecg.com/jmreport/shareView/838999694771572736

##### 重现步骤：
1、新建报表
2、设置背景图片（图片不大，设置为双向重复）
3、导出PDF

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
