### ISSUE TITLE
=SUM(E3) 之后怎么对这个单元格除以2

### ISSUE THREAD

**Issue by qwerqwer1234234** [jeecgboot/JimuReport#1930]
##### 版本号：

1.6.0
##### 问题描述：
=SUM(E3) 之后怎么对这个单元格除以2

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/100072068/80d385ab-15de-403c-bf4d-93aeebd76fe4)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
