### ISSUE TITLE
设计下钻的时候，能否支持直接传递页面本身具备的筛选条件

### ISSUE THREAD

**Issue by LhtLuo** [jeecgboot/JimuReport#1932]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
没这需求

**Comment by Wwwwwys** [comment]
我也是用类似方法，把所有查询的条件拼成一个json放到固定的单元格里，钻取的报表在解析参数，确实很麻烦
