### ISSUE TITLE
问题描述：积木报表不能自适应分辨率分辨率过低时显示不全

### ISSUE THREAD

**Issue by 2926184288** [jeecgboot/JimuReport#1933]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/93595345/d1bdc64a-4aa2-4c4c-9c59-b8ef3978e32f)

**Comment by zhangdaiscott** [comment]
上下滚动

**Comment by zhangdaiscott** [comment]
不可能做自适应
