### ISSUE TITLE
预览耗时较长，有办法加快渲染速度吗？

### ISSUE THREAD

**Issue by KateJun** [jeecgboot/JimuReport#1934]
##### 版本号：
1.5.8

##### 问题描述：
![image](https://github.com/jeecgboot/JimuReport/assets/6227218/9c322f48-95ea-4864-996c-81f865403b54)

##### 错误日志&截图：
10多秒才显示出来

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
数据大吗？

**Comment by zhangdaiscott** [comment]
10多秒应该是你的环境问题
