### ISSUE TITLE
case函数使用时的bug

### ISSUE THREAD

**Issue by pengjunli** [jeecgboot/JimuReport#1935]
##### 版本号：
1.5.9

##### 问题描述：
使用case函数时，如果是=case('1+1=2'!='','备注','')这样的，就会报java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/38717534/e40d7ff9-ce7c-452e-9877-f8e9a8d7e6e9)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
case表达式写法参考文档：https://help.jeecg.com/jimureport/function/condition.html

**Comment by pengjunli** [comment]
=case(strval('1+1=2')=='nil','','备注')，，请看下这个语句，写法没错啊，，但判断语句中如果是“1+1=2”这样的字符串就会报错。
