### ISSUE TITLE
从1.5.9升至1.6.1后，当单元格设置格式为数值是0值不显示，导致报表不完整

### ISSUE THREAD

**Issue by freewind1977** [jeecgboot/JimuReport#1936]
##### 版本号：
1.6.1

##### 问题描述：
当数据有0值返回，且在将该列的格式设置为数值时，报表显示不完整

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/26646785/450ee7b6-e9ac-4d29-ae74-1547b85aa48c)

##### 重现步骤：
1. 测试数据源语句：
```
select 1 as 'n1',0 as 'n2'
union
select 0 as 'n1',1 as 'n2'
union
select 1 as 'n1',1 as 'n2'
```
2.打开报表设置，并拖拽相应的列，如图
![image](https://github.com/jeecgboot/JimuReport/assets/26646785/e9a25a49-40de-4a51-a1ff-b5883fd96e9e)

此时四个单元格格式均为"正常"，可以看到数据可以正常显示，如下图：
![image](https://github.com/jeecgboot/JimuReport/assets/26646785/02d18f33-8603-4644-bff1-339385a098ca)
3. 将数据行的格式调整为"数值"后，报表显示不完整
![image](https://github.com/jeecgboot/JimuReport/assets/26646785/03934c49-53a8-49d4-8e92-008805d60e87)

显示效果：
![image](https://github.com/jeecgboot/JimuReport/assets/26646785/fd536b43-ec30-404e-a64b-6fe89e7bb203)

从有0的单元格之后的报表均没有正常显示

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 zy

**Comment by liaozhiyang** [comment]
已修复，下一版本修复。目前版本你通过右侧面板设置没问题，只是通过顶栏设置有问题
