### ISSUE TITLE
积木报表能否支持报表的自动导出，定时导出到固定的位置。

### ISSUE THREAD

**Issue by wml790116** [jeecgboot/JimuReport#1938]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
no

**Comment by jeecgos** [comment]
已支持，升级版本 v1.9.1+ date 20241202
参考文档：https://help.jimureport.com/exportJob?_highlight=%E5%AE%9A%E6%97%B6
