### ISSUE TITLE
积木报表跳过预览直接打印

### ISSUE THREAD

**Issue by yizhibaibai** [jeecgboot/JimuReport#1939]
##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/35802644/a1a28781-9e00-4a19-bd2a-e078d13408df)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by yizhibaibai** [comment]
![O}1P%CZS)I26DRKHSVF4OOS](https://github.com/jeecgboot/JimuReport/assets/35802644/daf2187a-ec4d-42da-a701-f340554f2296)

能跳过这个预览页面，直接到打印页面吗
![4@ 7CKSWCEP)V~GPXZ7FO](https://github.com/jeecgboot/JimuReport/assets/35802644/2c345528-cd5f-4bd3-983d-6ccd511c22dd)

有了解这个的吗？嫌步骤太繁琐，想省去第一步的预览，直接到打印预览。

**Comment by lvdandan16** [comment]
不支持直接打印，目前都需要预览后打印
