### ISSUE TITLE
单元格设置为数值类型,若为值0或者为空,控制台报错,且会导致数据显示不全

### ISSUE THREAD

**Issue by Acechengui** [jeecgboot/JimuReport#1940]
##### 版本号：
1.6.0

##### 问题描述：
数据明明有多条 显示却只显示一条,
单元格设置为数值类型,若为值0或者为空,控制台报错,且会导致数据显示不全,点导出正常没问题,取消设置单元格类型为数值类型,恢复正常,缩放浏览器也有这问题,查出来9条,放大浏览器比例就变成三条了,发现也是设置了单元格类型为数值问题

##### 错误日志&截图：
![@43WLH@_ KM03QB(KZJPEF5](https://github.com/jeecgboot/JimuReport/assets/63096199/f0c84256-64fa-494d-8d59-ebc8d7e15fab)

字符串"0"就执行不了indexOf,开发这里没注意js是弱类型的吧

##### 重现步骤：
查询返回的数据结果中,有些列是数值的字符串数据,可能有0的值,然后将对应单元格设置为数值类型

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请提供测试数据

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本修复。目前版本你通过右侧面板设置没问题，只是通过顶栏设置有问题
