### ISSUE TITLE
固定表头打印

### ISSUE THREAD

**Issue by Dy-yangming** [jeecgboot/JimuReport#1941]
##### 版本号：
1.6.0

##### 问题描述：
固定表头表尾打印时，表头设计的二维码在预览时显示，打印的时候不显示

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/75370150/9f439cd7-7013-41df-b20b-d6ada1f5e967)
![image](https://github.com/jeecgboot/JimuReport/assets/75370150/4e7778f6-d096-443f-b160-7ec31efd73cd)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Dy-yangming** [comment]
官方示例ID: 853419457878773760

**Comment by lvdandan16** [comment]
收录 zy

**Comment by lvdandan16** [comment]
已修改，下个版本发布
