### ISSUE TITLE
日期+时间类型数据，导出为pdf，格式不一致

### ISSUE THREAD

**Issue by hdongzs** [jeecgboot/JimuReport#1942]
##### 版本号：
1.5.6  以及 官网在线版本

##### 问题描述：
日期+时间的类型的数据，在预览时正常，点击值后会多出一个'.0';
导出为pdf也会多出
![1](https://github.com/jeecgboot/JimuReport/assets/104297618/414c03fe-01d2-477a-9633-9645017501dd)
![2](https://github.com/jeecgboot/JimuReport/assets/104297618/82b29d3b-6104-439d-ad5d-16aa5a92d877)

##### 错误日志&截图：
![3](https://github.com/jeecgboot/JimuReport/assets/104297618/b64487fa-e72e-44e2-8056-76b704d09efd)

##### 重现步骤：
查询条件示例；
修改出生日期，数据格式为日期+时间：
![image](https://github.com/jeecgboot/JimuReport/assets/104297618/905d6712-b5f7-4b8f-a470-aef7335f8a0e)
进行打印设置，A4横向打印；
预览；
导出为pdf;
pdf文件中的时间后多了'.0'

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
