### ISSUE TITLE
报表图片不显示

### ISSUE THREAD

**Issue by qiwuyun365** [jeecgboot/JimuReport#1943]
##### 版本号：
1.6.1

##### 问题描述：
报表图片不显示。预览的时候反而能显示。

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/114674825/7453ee15-5031-4ae3-b9ea-d367cacc7b8c)

##### 重现步骤：
数据循环出来图片，按图片格式显示的时候就出不来了，图片地址如下
https://huizhizao-1314830814.cos.ap-shanghai.myqcloud.com/huizhizao-1314830814/8ae4fe02d3f65d9bfbdc5746deb79fea0ae10c11d311a9305286cfee471e3d1c.png

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
F12看看提示什么

**Comment by KateJun** [comment]
兄弟，有可能是跨域问题吧？？
