### ISSUE TITLE
表单与预览不一致

### ISSUE THREAD

**Issue by liuhaia** [jeecgboot/JimuReport#1944]
##### 版本号：
1.6.1

##### 问题描述：
编辑报表的样式与预览的不一致

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/31206829/2d94e363-afdc-4ba1-8eb9-f7ad915b5d94)
![image](https://github.com/jeecgboot/JimuReport/assets/31206829/64fe72be-a103-4187-8575-f145118f5a28)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by liuhaia** [comment]
不知道是设置到什么地方了，突然就这样了

**Comment by liuhaia** [comment]
少了一截

**Comment by KateJun** [comment]
版本bug， 降回1.5.8

**Comment by lvdandan16** [comment]
导出报表配置及数据，我们重新一下

收录 zy

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/JimuReport/issues/1931
