### ISSUE TITLE
新版本并没有解决：纵向分组排序，排序方式 设置为默认，没有按照源数据进行排序

### ISSUE THREAD

**Issue by hechenjun** [jeecgboot/JimuReport#1945]
##### 版本号：
1.6.1

##### 问题描述：
纵向分组排序，排序方式 设置为默认，没有按照源数据进行排序

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持源数据排序，可以自定义文本排序

**Comment by hechenjun** [comment]
如果分组排序的内容不是固定的某些值，就用不了自定义文本排序了，想要按照源数据顺序排序有什么解决办法呢？
