### ISSUE TITLE
导出PDF 图像，表格跨页时，跨页内容不显示

### ISSUE THREAD

**Issue by panoliu** [jeecgboot/JimuReport#1946]
##### 版本号：
1.5.9

##### 问题描述：
预览时正常，但导出PDF 图像时，如果刚好碰到表格需要跨页显示，则只会显示一部分，余下跨页部分不显示

##### 错误日志&截图：
预览时正常：
<img width="785" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/46661640/8173e2d9-5e41-4163-8748-19d5528deef8">

但是用 “PDF图像”导出时，跨页后余下部分丢失
<img width="683" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/46661640/ddbacfff-2ba4-40c8-9767-971e7e2c1aee">

<img width="799" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/46661640/62809e24-d398-4a1c-a214-977fc22b611e">

##### 重现步骤：
多行表格，内容需跨页显示，选择PDF图像 导出

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by liaozhiyang** [comment]
无法重现，能把sql导出来吗？或者在官网上给个例子。

**Comment by panoliu** [comment]
> 无法重现，能把sql导出来吗？或者在官网上给个例子。

http://124.70.200.119:8080/jeecg-boot/jmreport/view/857550770154430464
您好，可以查看此报表，选择导出 PDF图像

**Comment by lvdandan16** [comment]
已修复，下个版本升级
