### ISSUE TITLE
打印设计，背景图打印菜单消失了

### ISSUE THREAD

**Issue by liuxiaokun** [jeecgboot/JimuReport#1947]
##### 版本号：

1.6.1
##### 问题描述：
在打印设计时，空白单元格右键菜单，已经找不到文档中的背景图设计，如果直接点击工具栏的图片上传，只可以设置为套打图片，也没有设置成背景图，且设置为套打图片后，没有菜单取消套打

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/5936920/54a4e2dd-aef9-4ce9-b67c-5f90c25b7cdf)

##### 重现步骤：

空白单元格，右键菜单
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/54099258/88b5c20d-b5a1-4fea-8e79-3113b32e5e69)
滚动条往下滑动

**Comment by liuxiaokun** [comment]
多谢
