### ISSUE TITLE
我的问题描述

### ISSUE THREAD

**Issue by hdthhh** [jeecgboot/JimuReport#1948]
##### 问题描述：
1.**打印时表单总会被放大！！！**导致预览的格式和打印的格式长的不一样，看在线演示时发现最新的演示是有html和canvas两种打印方式，但是我的版本有1.5.8和1.6.0，但只有一种打印方式，是只有1.6.1的版本才有两种打印方式吗，还是其他问题的原因？我看html好像会放大表单，canvas好像不会，但是如果客户看的话，他是不知道这两种有什么区别的，所以他很可能会选html，这样表单就会被放大，导致格式就会变了
2.打印清晰度  1和10 好像区别不大，肉眼看不出来什么区别
3.表达式上参数值是1和参数值是‘1’， 两种好像都会解析成数字
4.日期格式和其他格式能多加几种吗，如2018-01啥啥的
5.同时选中几行单元格，修改单元格高度，只会修改第一个选中的单元格，其他的单元格高度没改变，宽度也是同样的，改变不了

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by hdthhh** [comment]
6.打印的时候，有两个身份证，在同一列上，宽度都是一样的，身份证的位数也是一样的，但是设置了自动换行后，点击打印，第一行的身份证号在一行显示，没有换行，但是第二行的身份证号却换行了，最后一位身份证号在第二行换行了，不知道为什么？？？

**Comment by hdthhh** [comment]
能增加for函数吗

**Comment by lvdandan16** [comment]
请图文并茂，描述问题

**Comment by hdthhh** [comment]
涉及客户保密信息，不便，见谅

**Comment by hdthhh** [comment]
> 请图文并茂，描述问题

涉及客户保密信息，不便，见谅

**Comment by hdthhh** [comment]
这个没有解决吗
