### ISSUE TITLE
调用达梦数据库存储过程报错，提示Sql执行失败

### ISSUE THREAD

**Issue by Sgrvaries** [jeecgboot/JimuReport#1950]
##### 版本号：
1.5.9

##### 问题描述：
调用存储过程，入参为日期类型Date，出参为游标sys_refcursor,执行报错

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/15855111/e4fb31ec-5760-40b5-8963-45c7de507f9a)
<img width="1221" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/15855111/cd204161-8b79-4b84-8fe3-8aed686f6487">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by Sgrvaries** [comment]
create or replace procedure jmtest1(XM in DATE, outds out sys_refcursor) is
begin
  open outds for
  select '1' as id, '张三' as name from dual;
end;

**Comment by Sgrvaries** [comment]
现在只是写了一个很简单的测试demo来说明问题，真实业务有很多表关联，而后将数据塞进游标进行返回，并不是简单的查询而已，之所以用存储过程就是为了后期维护方便。

**Comment by Sgrvaries** [comment]
现在只是写了一个很简单的测试demo来说明问题，真实业务有很多表关联，而后将数据塞进游标进行返回，并不是简单的查询而已，之所以用存储过程就是为了后期维护方便。

**Comment by 1298191366** [comment]
我知道是demo,就是你用这种写法dm数据库能查询出来数据吗，通过CALL jmtest1(2023-12-09，?)，因为oracle数据库通过CALL能查询出来，复杂写法暂不支持

**Comment by lvdandan16** [comment]
归集到 #138
