### ISSUE TITLE
javabean数据集，查询的数据支持多租户吗

### ISSUE THREAD

**Issue by Ant-zbt** [jeecgboot/JimuReport#1953]
##### 版本号：
1.5.6

##### 问题描述：
javabean数据集，查询的数据支持多租户吗
openTenant:true，已开启多租户模式

##### 错误日志&截图：
<img width="898" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/47658509/dff4b7b6-731b-4f08-8426-7a7f8cf304b7">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持
