### ISSUE TITLE
想问问咱目前支不支持 单个报表导出sql 然后再别的环境再导入的操作

### ISSUE THREAD

**Issue by tengpeter** [jeecgboot/JimuReport#1954]
##### 版本号：
1.5.2

##### 问题描述：
想问问咱目前支不支持   单个报表导出sql  然后再别的环境再导入的操作

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
select * from jimu_report WHERE del_flag=0 and id = '753506001105539072';
SELECT * from jimu_report_db where jimu_report_id in (select id from jimu_report WHERE del_flag=0 and id = '753506001105539072');
SELECT * from jimu_report_db_field where jimu_report_db_id in (SELECT id from jimu_report_db where jimu_report_id in (select id from jimu_report WHERE del_flag=0 and id = '753506001105539072'));
SELECT * from jimu_report_db_param where jimu_report_head_id  in (SELECT id from jimu_report_db where jimu_report_id in (select id from jimu_report WHERE del_flag=0 and template=1));
SELECT * from jimu_report_data_source where report_id in (select id from jimu_report WHERE del_flag=0 and template=1);
SELECT * from jimu_report_link where report_id in (select id from jimu_report WHERE del_flag=0 and template=1);
