### ISSUE TITLE
SQL数据集查询条件下拉去重问题

### ISSUE THREAD

**Issue by dengyingfeng2022** [jeecgboot/JimuReport#1955]
##### 版本号：
1.5.8
##### 问题描述：
SQL 查询数据集时，用列作为查询条件时，由于返回值中此列的值存在重复，导致下拉选项也存在重复，期望去重，望指导。

##### 错误日志&截图：

![DB3F603F-E619-42d2-8FF3-AEA8C288BD53](https://github.com/jeecgboot/JimuReport/assets/105050463/9728e12a-0112-4b91-9af2-79a3faa55172)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by caiguanlin** [comment]
在报表参数对应参数的字典code中去写SQL并去重就可以达到你的效果，具体看官方文档，上面有，键别名要为text，值别名为value，否则不生效

**Comment by dengyingfeng2022** [comment]
感谢
