### ISSUE TITLE
打印回调接口没携带自定义的ApiHeader

### ISSUE THREAD

**Issue by slqzxl** [jeecgboot/JimuReport#1956]
##### 版本号：
1.6.0

##### 问题描述：
打印回调接口没携带自定义的ApiHeader,导致接口因权限问题无法调用
希望回调接口参数也能增加调用api方式传递的参数，这样方便知道哪个业务单据点击了打印

##### 错误日志&截图：
![无标题](https://github.com/jeecgboot/JimuReport/assets/102512326/6586739b-c048-4d14-98cb-a9965aa41afa)
![无标题2](https://github.com/jeecgboot/JimuReport/assets/102512326/b2535f0b-8488-48db-97f4-efda5cd1c9b5)

![22222](https://github.com/jeecgboot/JimuReport/assets/102512326/755da3d9-d1b0-4aab-a48a-0e43ceec67d3)
![3333](https://github.com/jeecgboot/JimuReport/assets/102512326/95074133-9330-40f7-bd77-d49bbe4b590a)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
归集 #138
