### ISSUE TITLE
二维码生成的容错级别

### ISSUE THREAD

**Issue by HhZzCcMm1** [jeecgboot/JimuReport#1957]
##### 版本号：
jimu报表1.6.1

##### 问题描述：
二维码长度溢出，造成二维码生成不了，改变二维码的correctLevel的值就能显示了，能否提供手动设置correctLevel的值

##### 错误日志&截图：
<img width="653" alt="51a92116a5dfef61185595c00e657a1" src="https://github.com/jeecgboot/JimuReport/assets/142368743/756b2bd2-1981-4ea7-be90-7784198ba403">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 zy

**Comment by lvdandan16** [comment]
已修复 下个版本升级
