### ISSUE TITLE
初始化jimureport数据库时，只能用mysql吗，是否可以直接把数据结果和数据放到kingbase数据库中

### ISSUE THREAD

**Issue by liuzhenhe-hub** [jeecgboot/JimuReport#1958]
##### 版本号：
1.6.1

##### 问题描述：
目前我们整个项目使用的是kingbase数据库，所以初始化时候也需要放在同一个库中；
官方给的初始化sql语句是mysql的，初始化的数据库是否只支持mysql，能否用其他数据库，比如kingbase；

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/55123456/8cc06d9f-0ee5-4a0b-9c29-3200ad6d3381)
将如上默认数据库连接修改为如下kingbase的
![image](https://github.com/jeecgboot/JimuReport/assets/55123456/5b100b7b-c8aa-4d8e-8550-a61788f78361)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
常规的数据库支持，kingbase不清楚
