### ISSUE TITLE
积木报表学生信息卡在打印预览时会出现多个学生信息与第一个学生信息的重复数据

### ISSUE THREAD

**Issue by zhoucod** [jeecgboot/JimuReport#1959]
##### 问题描述：
积木报表学生信息卡在打印预览时会出现多个学生信息与第1个学生的信息重复 与正常预览显示的不一致

##### 错误日志&截图：
图1：学生1信息正常
![image](https://github.com/jeecgboot/JimuReport/assets/143678029/870a06bd-3d84-46e7-ab0c-95c136d79340)
图2：学生2信息与学生1的信息重复
![image](https://github.com/jeecgboot/JimuReport/assets/143678029/ff9def3f-559b-479d-89cb-fcfb84c46154)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
最新版本号是多少

**Comment by zhoucod** [comment]
1.5.4

**Comment by zhangdaiscott** [comment]
先升级到最新

**Comment by zhoucod** [comment]
最新版本号是1.6.0吗

**Comment by zhoucod** [comment]
已经是最新版还是不可以

**Comment by lvdandan16** [comment]
请在积木官网做示例，我们复现

**Comment by zhoucod** [comment]
怎么弄呀

**Comment by lvdandan16** [comment]
积木官网注册做示例，把id贴上来就可以：http://www.jimureport.com/

**Comment by zhoucod** [comment]
在官网注册登录了之后具体是在报表示例里面贴吗 因为第一次反馈问题没有贴过麻烦可以说明一下吗 谢谢您

**Comment by lvdandan16** [comment]
做完示例，把报表id回复在这里就可以

**Comment by zhoucod** [comment]
官网报表示例 那里贴不了示例呀
