### ISSUE TITLE
分页打印时怎么打印当前页码和总页数

### ISSUE THREAD

**Issue by woniujjjjjjjjjjjj** [jeecgboot/JimuReport#1962]
##### 版本号：
1.5.9

##### 问题描述：
打印多页的时候我用${replaceParams.pageNo}获取的当前页码全都是1，没有获取到正确的页码

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/99636704/f174cc4b-c3f1-4fb3-b78c-6560478e1f1d)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 zy

**Comment by Lovedcc** [comment]
题主，可以请教一下打印多页的时候，每页表格下边都有的签名是怎么实现的吗

**Comment by liaozhiyang** [comment]
页码功能已添加，下一版本发布。

**Comment by liaozhiyang** [comment]
> 题主，可以请教一下打印多页的时候，每页表格下边都有的签名是怎么实现的吗
设计页面右键有个固定打印尾功能

**Comment by woniujjjjjjjjjjjj** [comment]
如果是分页查询的话可以不用设置固定打印表尾
&nbsp;


篮球火
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月14日(星期四) 中午11:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/JimuReport] 分页打印时怎么打印当前页码和总页数 (Issue #1962)





  
题主，可以请教一下打印多页的时候，每页表格下边都有的签名是怎么实现的吗
 设计页面右键有个固定打印尾功能
