### ISSUE TITLE
打印预览界面，点击“取消”按钮会出现界面一直加载的现象

### ISSUE THREAD

**Issue by hua350264633** [jeecgboot/JimuReport#1965]
##### 版本号：
1.6.1
##### 问题描述：
打印预览界面，点击“取消”按钮会出现界面一直加载的现象
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/32692650/66a22e00-e929-48e9-a1d4-9859da525d3c)
![image](https://github.com/jeecgboot/JimuReport/assets/32692650/52c2f7e7-ca4a-4aec-8f7b-8a916f517233)
##### 重现步骤：
设计报表>预览>打印>取消
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
已修改，下个版本发布
