### ISSUE TITLE
字符串函数=cnmoney有bug

### ISSUE THREAD

**Issue by your1986** [jeecgboot/JimuReport#1966]
##### 版本号：
1.5.4

##### 问题描述：
小写金额是 22.42，转大写后显示的是 贰拾贰元肆角壹分

##### 错误日志&截图：
![微信图片_20230901160947_1](https://github.com/jeecgboot/JimuReport/assets/86152114/aac14ccf-bde0-4bbd-b99a-84c5b94a4635)
![2](https://github.com/jeecgboot/JimuReport/assets/86152114/ae5e4e87-4f71-420a-ad50-8575c67592c3)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
请更新到最新版本，最新版本已修复过了
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.6.2-GA5</version>
</dependency>
```
