### ISSUE TITLE
使用API数据源无法获取数据

### ISSUE THREAD

**Issue by fistlove159** [jeecgboot/JimuReport#1967]
##### 版本号：
1.6.12

##### 问题描述：
使用API数据源，报表设计完成后，点击预览没有数据

##### 错误日志&截图：
1、API接口经测试能返回数据，如下图
![微信截图_20230902225938](https://github.com/jeecgboot/JimuReport/assets/34266161/43e5efd3-df23-4076-a952-540c6528889b)
2、后端接口：
![微信截图_20230902230106](https://github.com/jeecgboot/JimuReport/assets/34266161/c7dd4e0c-f8b3-4ad1-83d6-d7ece4c16729)

3、积木报表数据源：
![微信截图_20230902230259](https://github.com/jeecgboot/JimuReport/assets/34266161/a5ae527d-6b50-4a80-b909-d18db7504304)
![微信截图_20230902230643](https://github.com/jeecgboot/JimuReport/assets/34266161/eaa7da81-64a9-4083-8f03-4f28e85c3582)
4、报表编辑：
![微信截图_20230902230809](https://github.com/jeecgboot/JimuReport/assets/34266161/9b5b3f9a-efa9-4747-8ba4-7efeb209a73c)
5、报表预览：
![微信截图_20230902230942](https://github.com/jeecgboot/JimuReport/assets/34266161/6f729004-2518-45c0-bd80-25cd1f8bab54)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
看前后台报什么错

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此任务
