### ISSUE TITLE
定时下载报表

### ISSUE THREAD

**Issue by binli123-max** [jeecgboot/JimuReport#1968]
##### 版本号：
1.6.0

##### 问题描述：
我将积木报表集成到自己的springboot的项目中了，想要设置定时下载一些报表，目前找到的下载有前端手动导出报表，jimuReport有没有提供什么service层的方法调用获取流呢？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
