### ISSUE TITLE
Pdf导出接口方案何时开放？

### ISSUE THREAD

**Issue by fistlove159** [jeecgboot/JimuReport#1969]
##### 版本号：
1.6.12

##### 问题描述：
Pdf导出接口方案何时开放？
在项目中需要后台传参生成PDF格式存储，而不通过前端点击导出

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
