### ISSUE TITLE
保留数值格式导出的execl存在的问题。

### ISSUE THREAD

**Issue by happyuanhao** [jeecgboot/JimuReport#1971]
##### 版本号：

1.6.12
##### 问题描述：
首先感谢官方根据我的需求做出的报表格式导出execl补零的问题，但是在使用过程中发现，当数值为0.XX时，显示没问题，但是导出的就变成了.xx，内容如下。

##### 错误日志&截图：
<img width="1027" alt="微信图片_20230904160310" src="https://github.com/jeecgboot/JimuReport/assets/25651702/9f1dc508-be0a-4167-b4ba-0bbf1c9cf9f2">
<img width="927" alt="微信图片_20230904155713" src="https://github.com/jeecgboot/JimuReport/assets/25651702/c7f639a2-0bce-4cc5-a114-7c4c34cc959e">

##### 重现步骤：
在我使用了新增的所见即所得导出后，我发现execl导出的0.94变成了.94 前面的零不见了 这样显示肯定是不行的，这个问题能处理吗，使用的是数值格式保留两位小数时会出现这种情况。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
