### ISSUE TITLE
数值为0的单元格打印时变成空值.

### ISSUE THREAD

**Issue by anyonetff** [jeecgboot/JimuReport#1972]
##### 版本号：
1.6.12

##### 问题描述：
结果集数值为0的单元格，页面预览显示，导出均正常。但点击打印按钮，弹出的打印对话框可以看到，单元格则为空。

##### 错误日志&截图：
提取一个报表，可以看到有部分单元格数值为0
![图片](https://github.com/jeecgboot/JimuReport/assets/33112395/5b1334d4-ce72-4228-83dc-ca7d3ed2d266)
点击打印按钮，在打印预览界面可以看到单元格为“空”
![图片](https://github.com/jeecgboot/JimuReport/assets/33112395/9b572cff-6d56-4f77-8abe-49546fde678e)

##### 重现步骤：
1. 提取一个报表，可以看到有部分单元格数值为0
2. 点击打印按钮，在打印预览界面可以看到单元格为“空”
3. 实际发送到打印机，纸张显示结果也是“空”值

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 zy

**Comment by lvdandan16** [comment]
已修复，下个版本升级
