### ISSUE TITLE
打印设置页面底部内容固定

### ISSUE THREAD

**Issue by Lovedcc** [jeecgboot/JimuReport#1973]
##### 问题描述：1.在写表格的时候没有出现空行，但是一旦进入预览，就会出现一行空行将上下分隔开，如何解决？
![image](https://github.com/jeecgboot/JimuReport/assets/102033777/aa4f7425-3307-404d-a84d-3ad4072c4f81)
2.怎么实现打印时，每页的底部都固定上图的签字行呢？

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/102033777/02f9f3c0-a893-4fe3-911e-f16e77d88278)
![image](https://github.com/jeecgboot/JimuReport/assets/102033777/ffaf36c7-f3a8-402a-9436-8dc1e0abb220)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
1、1.3.78版本太老了，先升级新版本，看看还有没有问题
2、新版本打印时可设置固定表头表尾 参考链接：https://help.jeecg.com/jimureport/printNew/gaugeOutfit.html
