### ISSUE TITLE
报表钻取，参数传递不对。

### ISSUE THREAD

**Issue by liyuhui98** [jeecgboot/JimuReport#1974]
##### 版本号：
1.5.9
##### 问题描述：
报表钻取，参数传递不对。如下图，三个同名BOM，传递参数为设备型号，项目名称，客户名称。
点击图1中不同的BOM,结果入参 都是 同一个项目名称，客户名称 
##### 错误日志&截图：

![1693879574452](https://github.com/jeecgboot/JimuReport/assets/81678276/01ec2095-7bc8-4a47-86db-6d2462d4cffb)
![1693879715173](https://github.com/jeecgboot/JimuReport/assets/81678276/a9ece74e-403f-4f29-b23f-b221fe372c3a)

![1693879660938](https://github.com/jeecgboot/JimuReport/assets/81678276/e5015dcf-0f27-4d9e-8399-d57645e4ef42)

##### 重现步骤：
设置报表钻取，进行参数传递。 

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by xiaobaiyis** [comment]
遇到同款问题了 同值的时候只取第一条数据的参数

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布。分组暂不支持
