### ISSUE TITLE
mongodb数据源报表不能分页不能筛选

### ISSUE THREAD

**Issue by JoyenF** [jeecgboot/JimuReport#1975]
##### 版本号：
1.5.8 
1.6.0

##### 问题描述：
mongodb数据源 报表不能分页，
mongodb数据源 报表查询栏不能筛选

##### 错误日志&截图：
![Dingtalk_20230905110102](https://github.com/jeecgboot/JimuReport/assets/144082956/c51891c7-c7eb-46b9-8336-111b302894da)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持

**Comment by jeecgos** [comment]
1.9.3版本 已支持使用sql语句对mongodb分页和筛选查询
