### ISSUE TITLE
报表打印时显示总页数及当前页

### ISSUE THREAD

**Issue by liangGitHu** [jeecgboot/JimuReport#1976]
##### 版本号：
1.5.6

##### 问题描述：
关于报表打印的时候，会有多页的情况，我想在页脚配置“总共多少页，当前第几页”该怎么配置，有对应的变量赋值吗（因为列高度不确认，提前不知道最后会打印几页，只能打印的时候才能看到）

##### 错误日志&截图：
![1](https://github.com/jeecgboot/JimuReport/assets/25289627/77bcb746-9196-47d7-8557-43f8e94a835d)

##### 重现步骤：
![2](https://github.com/jeecgboot/JimuReport/assets/25289627/5f1f8036-2650-484c-b233-47a0345f3b6b)
![3](https://github.com/jeecgboot/JimuReport/assets/25289627/8bdba45b-2033-44ff-80e7-17c1eb25bd89)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 zy

**Comment by liaozhiyang** [comment]
页码功能已添加，下一版本发布
