### ISSUE TITLE
能否支持修改报表的封面图片和名称

### ISSUE THREAD

**Issue by MrZhaoFei** [jeecgboot/JimuReport#1978]
##### 版本号：
1.5.6

##### 问题描述：
1.能否支持修改报表的名称，封面图片？
2.报表名称太长之后显示不完整

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/20886201/dd1576a6-8b39-4f88-b308-7e6ce2960923)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/54099258/eb20e9e9-6d5d-4be3-9770-2d3f116a5db8)
收藏至模版，在模版案例中可以上传封面

**Comment by MrZhaoFei** [comment]
> ![图像](https://user-images.githubusercontent.com/54099258/265964248-eb20e9e9-6d5d-4be3-9770-2d3f116a5db8.png) 收藏至模版，在模版案例中可以上传封面

请问是哪个版本有收藏功能？通过maven集成使用1.6.1和1.6.2-bate版本都没有
