### ISSUE TITLE
报表钻取相同栏位值跳转参数错误

### ISSUE THREAD

**Issue by 544589199** [jeecgboot/JimuReport#1980]
##### 错误位置&截图：
<img width="1274" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/76895998/bafa44d8-304d-4f6e-8e24-481c39a38428">

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布。分组暂不支持
