### ISSUE TITLE
报表设计器中增加图表使用delete删除后不能撤回？

### ISSUE THREAD

**Issue by MrZhaoFei** [jeecgboot/JimuReport#1982]
##### 版本号：
1.6.1

##### 问题描述：
在设计器中添加了报表图形后，按键盘delete后，通过Ctrl+Z 或者顶部
撤回按钮不能撤回

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/20886201/84a2dd75-a935-4477-b60c-a79c923d93e5)

https://github.com/jeecgboot/JimuReport/assets/20886201/db943adb-03eb-42a7-8911-917c2d7cd041

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
