### ISSUE TITLE
关于ruoyi vue版集成积木报表

### ISSUE THREAD

**Issue by Miracle-ZT** [jeecgboot/JimuReport#1983]
##### 版本号：
jimureport: `1.6.1`
ruoyi-vue: `3.3.0`

##### 问题描述：
集成ruoyi-vue时，想要集成至tab栏中，但配置完要么点开会新建标签打开，要么就是产生页面嵌套，不能正常显示。
### 请问如何将积木报表的页面在ruoyi框架中打开？像这样：
![image](https://github.com/jeecgboot/JimuReport/assets/130826948/3afb4edb-5f2c-4103-b899-e4ec2ca3df26)

已按照官方文档进行操作，不确定是否有文档省略的某些步骤没有完成
暂未查询到有效的解决方法，烦请解答，感谢！！！(网图，侵删)

##### 错误日志&截图：
此为产生页面嵌套时
![3201a300e8528bcd0d3645d53add9a7d](https://github.com/jeecgboot/JimuReport/assets/130826948/7c4e87e5-8511-4a3a-85ff-45ba1956808b)
![6dfeaf4d24be6199d8573f65e289dc61](https://github.com/jeecgboot/JimuReport/assets/130826948/8518e55c-5ded-4af5-be44-17eebcbd2cb8)

当路由地址为完整路径时(如：`http://localhost:8086/jmreport/list`)，则会新建浏览器标签打开。

##### 重现步骤：
官方集成文档：http://report.jeecg.com/2302148
其中已完成至`7、启动项目访问`
若依中的菜单管理配置如上图

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
集成问题，需自行解决
