### ISSUE TITLE
字典code sql包含系统变量时，报表该列数据无法正常翻译为显示值

### ISSUE THREAD

**Issue by gxjljx** [jeecgboot/JimuReport#1984]
##### 版本号：
1.6.2-beta

##### 问题描述：
操作用户列使用了字典code，里面填的是sql，sql中包含了系统变量，如下：
select login_name as value, real_name as text
from sys_user
where tenant_id = '#{sysTenantId}'

在查询条件中，可以正常显示出下拉数据来的，但是在列的翻译显示值上没有正确翻译出来。
若把sql中的系统变量去掉，则列显示可以正常翻译出显示值

请支持下在翻译字典sql数据时，也可以支持系统变量传入

##### 错误日志&截图：
<img width="522" alt="jimu-bug" src="https://github.com/jeecgboot/JimuReport/assets/5818815/dfade4ea-5bd5-416c-885d-98754659cb70">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
