### ISSUE TITLE
Encountered unexpected token

### ISSUE THREAD

**Issue by gitReiki** [jeecgboot/JimuReport#1985]
##### 问题描述：
sql数据集配置时   数据预览能够预览

##### 错误日志&截图：
但做好报表保存后查看就报错

Encountered unexpected token: "(" "(" at line 4, column 4. Was expecting one of: "&" ")" "," "::" "<<" ">>" "ACTION" "ANY" "AS" "BYTE" "CASCADE" "CAST" "CHANGE" "CHAR" "CHARACTER" "COLLATE" "COLUMN" "COLUMNS" "COMMENT" "COMMIT" "CONNECT" "CYCLE" "DESC" "DESCRIBE" "DISABLE" "DIV" "DO" "DUPLICATE" "ENABLE" "END" "EXCEPT" "EXCLUDE" "EXTRACT" "FALSE" "FIRST" "FN" "FOLLOWING" "FOR" "FORMAT" "FROM" "GROUP" "HAVING" "INDEX" "INSERT" "INTERSECT" "INTERVAL" "INTO" "ISNULL" "KEY" "LAST" "MATERIALIZED" "MINUS" "NEXTVAL" "NO" "NOLOCK" "NULLS" "OF" "OPEN" "ORDER" "OVER" "PARTITION" "PATH" "PERCENT" "PRECISION" "PRIMARY" "PRIOR" "RANGE" "READ" "REPLACE" "ROW" "ROWS" "SCHEMA" "SEPARATOR" "SEQUENCE" "SESSION" "SIBLINGS" "SIZE" "START" "TABLE" "TEMP" "TEMPORARY" "TO" "TOP" "TRUE" "TRUNCATE" "TYPE" "UNION" "UNSIGNED" "VALIDATE" "VALUE" "VALUES" "VIEW" "WHERE" "WINDOW" "XML" "ZONE" "[" "^" "|"

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请图文并茂详细描述问题
