### ISSUE TITLE
横向动态分组的时候纵向的指标超过一个后出现错乱

### ISSUE THREAD

**Issue by 990289057** [jeecgboot/JimuReport#1988]
##### 版本号：
v1.6.2

##### 问题描述：
1.横向扩展两个字段，按账户和年份横向分组
2.纵向的指标一个字段的时候是正常的
3.纵向的指标如果是两个字段，第二个字段就开始出现分组错误，看起来是出现笛卡尔积的情况了。

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/144327586/b0707adc-10f1-4412-9510-68186bd86e4a)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lvdandan16** [comment]
表数据和报表设计也上传一下

**Comment by lsqGitHub716** [comment]
麻烦提供一下数据，请在设计页面右键菜单中导出报表配置，以及表数据，方便我们问题复现

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
