### ISSUE TITLE
版本1.6.1-带二维码打印分页错乱

### ISSUE THREAD

**Issue by xiaojiang123123** [jeecgboot/JimuReport#1991]
##### 版本号：

1.6.1
##### 问题描述：

把版本换成1.6.1后，带二维码打印还是会出现分页问题
##### 错误日志&截图：
<img width="874" alt="9d145e62dc0680a06e1c71435bb5d07" src="https://github.com/jeecgboot/JimuReport/assets/74350136/7f446cee-4c3a-4864-8236-206d12a805f0">

<img width="1279" alt="e5c2e1e67315bc3314daa51a216e6ce" src="https://github.com/jeecgboot/JimuReport/assets/74350136/6f4dff1b-77ef-4667-a477-30567d7bfc78">
<img width="874" alt="d9b447b7b7553cd6d0564f5b211a971" src="https://github.com/jeecgboot/JimuReport/assets/74350136/381df89f-0e65-4454-8de2-c4a17cf8c70c">
<img width="874" alt="a6a017f5936b2dcacfc5b4453e89c8a" src="https://github.com/jeecgboot/JimuReport/assets/74350136/d5ecd48f-44bb-4d1b-bfc3-0a6b17d88791">

##### 重现步骤：
我新建了一张单也无法实现在一页打印，也并没有超出打印范围

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by xiaojiang123123** [comment]
<img width="768" alt="企业微信截图_16941441945836" src="https://github.com/jeecgboot/JimuReport/assets/74350136/5d709120-f64f-4a32-975a-7f0c9f8d4ff5">
更新到1.6.1版本后后端报错
![image](https://github.com/jeecgboot/JimuReport/assets/74350136/26b352e8-862a-42b6-ba04-6d2fcddb8533)
请问是否是该错误引起的不生效，ke可否告知一下1.5.0（原版本）和1.6.1版本的数据库表结构的差异呢，谢谢！

**Comment by lvdandan16** [comment]
请在积木官网做个示例，我们看一下
