### ISSUE TITLE
版本16.1 循环块功能找不到

### ISSUE THREAD

**Issue by HanBYY** [jeecgboot/JimuReport#1992]
版本号：1.6.1

问题描述：循环块功能找不到

错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/50692422/1efaa71f-6fb2-4333-ba83-d0fca095a224)

重现步骤：
选定循环区域后，右键功能没有循环

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
滚动鼠标
