### ISSUE TITLE
如何删除设计页面右边空白列,目的是导出后excel右侧没有空白列

### ISSUE THREAD

**Issue by lwb69** [jeecgboot/JimuReport#1993]
##### 版本号：
1.6.1

##### 问题描述：
在报表设计页面删除了右边的空白列，保存后再打开又有空白列了，导出excel的时候右边也有空白列

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/67140264/ba5ca834-1a9c-40f3-9b43-ac1a16c15627)
![image](https://github.com/jeecgboot/JimuReport/assets/67140264/1538fe98-76f5-4be2-9d67-117917719327)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
直接选中删除
