### ISSUE TITLE
新增模块引入积木无法启动

### ISSUE THREAD

**Issue by joseofgit** [jeecgboot/JimuReport#1994]
积木 版本号：1.6.2-beta

问题描述：模块无法

 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/15164598/f47b6e2a-48b9-4e68-b5d5-b7b0e0d19a0f)

重现步骤：
![image](https://github.com/jeecgboot/JimuReport/assets/15164598/dc996560-4f8b-4e30-aada-ac7feb766e1d)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请详细描述功能

**Comment by zhangdaiscott** [comment]
集成问题，请自己解决
