### ISSUE TITLE
当接口返回数据量超过25M之后就会报JS错误：RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by hunk666** [jeecgboot/JimuReport#1995]
##### 问题描述：
当接口返回数据量超过25M之后就会报JS错误：RangeError: Maximum call stack size exceeded

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/68905085/d7000dc0-1fc0-4690-a65f-58ccf7c174df)
![image](https://github.com/jeecgboot/JimuReport/assets/68905085/97ca9585-f3e9-416c-9844-a2dfb7e98d70)

##### 重现步骤：
接口返回数据足够多，/jmreport/show接口返回数据超过25M以上的时候面报JS错误：
RangeError: Maximum call stack size exceeded
    at If (jmsheet.js?v=1.0.12:2)
    at t.Mf (jmsheet.js?v=1.0.12:2)
    at t.value (jmsheet.js?v=1.0.12:2)
    at t.value (jmsheet.js?v=1.0.12:2)
    at Object.view.viewReport (view.js?v=1.0.12:1141)
    at view.js?v=1.0.12:938
    at Object.success (manager.js?v=1.0.12:72)
    at request.js?v=1.0.12:160

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
为什么要那么多的数据量

**Comment by hunk666** [comment]
就是要查这么多啊  一年多的数据量全部展示出来
