### ISSUE TITLE
能否出个支持java17的版本，系统是java17用不了

### ISSUE THREAD

**Issue by wangsongjiang** [jeecgboot/JimuReport#1996]
##### 版本号：
1.6.1

##### 问题描述：
我的是java17的项目，报个面问题：Failed to introspect Class [org.jeecg.modules.jmreport.config.init.JimuReportConfiguration] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@63947c6b]
Caused by: java.lang.NoClassDefFoundError: javax/servlet/Filter

请求出个支持java17的版本，感谢！！！

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂时不考虑支持
