### ISSUE TITLE
导出带图形的报表配置sql再导入到另一个数据库，报表中的图形消失

### ISSUE THREAD

**Issue by lwb69** [jeecgboot/JimuReport#1997]
##### 版本号：
v1.6.1

##### 问题描述：
导出带图形的报表配置sql再导入到另一个数据库，报表中的图形消失

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
描述过于简单

**Comment by lwb69** [comment]
问题似乎出在导出sql的转义字符，将sql中的`\''`全部替换为`\"`，就能将图形导入了
![image](https://github.com/jeecgboot/JimuReport/assets/67140264/784e9cb4-2fc0-4e8c-b9c0-6fb486488a95)
------->
![image](https://github.com/jeecgboot/JimuReport/assets/67140264/a6c174bb-1e12-4cc2-b2c3-ce513d7fc189)

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
问题收录，正在优化调整导入方式
