### ISSUE TITLE
更新1.6.2-RC后报表出现sql报错。

### ISSUE THREAD

**Issue by happyuanhao** [jeecgboot/JimuReport#1998]
##### 版本号：
1.6.2-RC

##### 问题描述：

在之前的版本中，查询都是没有问题的，但在此次更新后出现了sql语句“请注意，SQL语法可能存在问题”的情况，我单独用postman或者网址去访问我的api，是没有问题的，我更新只是想使用我之前提出issue的部分，不想使用租户模式，因为我的模板只有我拥有操作权限，其他用户都不开放任何权限，我只想去解决补零及所见即所得excel的问题，请官方大佬解决一下，谢谢！！！！
 
 

##### 错误日志&截图：
![QQ图片20230911112213](https://github.com/jeecgboot/JimuReport/assets/25651702/00615b9c-eec7-4af1-b838-c531eb24c43a)
<img width="1256" alt="微信图片_20230911112135" src="https://github.com/jeecgboot/JimuReport/assets/25651702/d21edda9-abcb-46f2-bcdb-da00ef157aa7">
<img width="882" alt="微信图片_20230911112048" src="https://github.com/jeecgboot/JimuReport/assets/25651702/e45d5e55-a43b-4e80-af95-3787d2a75197">
##### 重现步骤：

具体步骤就是把新版本配置到pom中，我目前使用的Springboot，所以没有使用租户模式，就没有去配置yml，平台接入的是api接口，访问就会报错。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
截图看配置，你是配置的sql还是api

**Comment by happyuanhao** [comment]
<img width="1280" alt="微信图片_20230911112958" src="https://github.com/jeecgboot/JimuReport/assets/25651702/1d1aacd3-3ed5-4b1a-a70a-f2955f2e6068">
使用的多个api接口及sql组成的一个报表
<img width="267" alt="微信图片_20230911113158" src="https://github.com/jeecgboot/JimuReport/assets/25651702/6508c9b9-4e07-4657-9326-4c73e7e075cc">

**Comment by happyuanhao** [comment]
目前报错的位置是
Mybatisplus调用的GeteOne接口

**Comment by happyuanhao** [comment]
<img width="986" alt="微信图片_20230911113225" src="https://github.com/jeecgboot/JimuReport/assets/25651702/3061a11d-e023-4718-aaf6-684cf94d2e39">
这是访问sql

**Comment by happyuanhao** [comment]
<img width="987" alt="微信图片_20230911114401" src="https://github.com/jeecgboot/JimuReport/assets/25651702/96f252d0-3aa1-419f-938b-86f8b3ed045c">
 更改为1.6.12就不会报错，但是我之前提出的问题在这个版本存在问题。

**Comment by zhangdaiscott** [comment]
用这个试试
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.6.2-RC2</version>
</dependency>
```

**Comment by happyuanhao** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/25651702/5ad98f5c-4fae-44ad-9ff9-759d734dfb19)
还是不行，具体报错如上

**Comment by happyuanhao** [comment]
1.6.2-RC3已可以查询 ，但#1971的问题没解决，小数点整数位为0时导出的execl整数位不显示0
![0UXRC@MRS8O~SB `}F{4AO6](https://github.com/jeecgboot/JimuReport/assets/25651702/f9b977ec-b4d9-4741-a7d8-2a52df1df6f0)
![LFGZM@}~)35LQK (@WT71GU](https://github.com/jeecgboot/JimuReport/assets/25651702/9e6071f2-8421-4c24-b0a6-b36ecb6f34e5)
![image](https://github.com/jeecgboot/JimuReport/assets/25651702/703c9664-fa62-4e9a-9ea9-3e03d6105f0b)
