### ISSUE TITLE
动态属性值不显示数据

### ISSUE THREAD

**Issue by wangdongyuyuya** [jeecgboot/JimuReport#1999]
##### 问题描述：
根据一个字段分组后，动态属性值绑定的字段，在有多条不一样的分组字段数据中可以显示，一条时不显示。列如：查询的数据中有车次，实际值，按照车次分组，当查询出来的集合中的车次都为1时，动态属性的实际值不显示，当查询出来的集合中的车次有多个时（列如有4条为1车数据，4条为2车的数据）动态属性的实际值显示。具体操作请看截图。

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/40593825/67658bb2-bcf7-4228-9b7e-dd7de03d92a3)
![image](https://github.com/jeecgboot/JimuReport/assets/40593825/3d94986b-7780-4fc8-9057-3d9b0249990c)
![image](https://github.com/jeecgboot/JimuReport/assets/40593825/9c2468f5-70fb-4b0a-9aa0-21e3bbe20b5d)
![image](https://github.com/jeecgboot/JimuReport/assets/40593825/8252928e-67dd-4041-bd17-fb8b8b33240e)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请导出报表配置及数据，我们复现一下

**Comment by wangdongyuyuya** [comment]
[json数据.zip](https://github.com/jeecgboot/JimuReport/files/12618005/json.zip)
这个是配置和数据，模板是任务报表。

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
已修改

**Comment by wangdongyuyuya** [comment]
我怎么更新一下
