### ISSUE TITLE
除法运算显示Nan

### ISSUE THREAD

**Issue by zzlhr** [jeecgboot/JimuReport#2001]
##### 版本号：
1.6.2-beta

##### 问题描述：
=B1*B2
=B1/B2
这样写法显示结果NAN

##### 错误日志&截图：
<img width="1190" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/25954503/ece6ab45-92c2-49e4-8da5-423ddaa160e0">

<img width="1170" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/25954503/6fed4e9d-218b-43d0-8530-87b3b0cef4e4">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持此用法
