### ISSUE TITLE
1.6.1版本合并列或行带二维码打印报错

### ISSUE THREAD

**Issue by xiaojiang123123** [jeecgboot/JimuReport#2003]
##### 版本号：
1.6.1

##### 问题描述：
合并列或行带二维码打印报错For input string: "NaN"
VM1237 jmsheet.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'querySelector')
    at VM1237 jmsheet.js:2:1370254
    at Array.map (<anonymous>)
    at t.value (VM1237 jmsheet.js:2:1370229)
    at VM1237 jmsheet.js:2:1367565
    at Array.map (<anonymous>)
    at t.value (VM1237 jmsheet.js:2:1367065)
    at t.value (VM1237 jmsheet.js:2:1365261)
    at VM1237 jmsheet.js:2:1407390

##### 错误日志&截图：
VM1237 jmsheet.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'querySelector')
    at VM1237 jmsheet.js:2:1370254
    at Array.map (<anonymous>)
    at t.value (VM1237 jmsheet.js:2:1370229)
    at VM1237 jmsheet.js:2:1367565
    at Array.map (<anonymous>)
    at t.value (VM1237 jmsheet.js:2:1367065)
    at t.value (VM1237 jmsheet.js:2:1365261)
    at VM1237 jmsheet.js:2:1407390
 SQL脚本: 
[sql.zip](https://github.com/jeecgboot/JimuReport/files/12582109/sql.zip)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/54099258/f47c325c-99da-4a73-bdd1-1eae256b8e9a)
接口没有数据，复现不了

**Comment by xiaojiang123123** [comment]
数据就是一个普通的id:1632209100082023数字，类型为二维码




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月15日(星期五) 下午5:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 1.6.1版本合并列或行带二维码打印报错 (Issue #2003)





 

 接口没有数据，复现不了

**Comment by lvdandan16** [comment]
未复现，可正常打印
