### ISSUE TITLE
导出Excel时报错Method code too large!

### ISSUE THREAD

**Issue by luyizhilu** [jeecgboot/JimuReport#2004]
##### 问题描述：
导出Excel时报错Method code too large!，报错地方是引入的com.googlecode.aviator.jar包内判断方法是否大于64K

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/143050735/654a000d-6922-42c5-ac12-50ddce90219e)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
设置分页展示数据

**Comment by luyizhilu** [comment]
已排查定位，因列表有sum函数导致

**Comment by lvdandan16** [comment]
收录 ws

**Comment by lsqGitHub716** [comment]
提供一下报错的模版示例
