### ISSUE TITLE
跨站点脚本编制漏洞

### ISSUE THREAD

**Issue by gxggsggp** [jeecgboot/JimuReport#2005]
##### 错误日志&截图：
<img width="758" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/55690596/4aceb7f7-b740-4fdf-895c-967c26e15a8e">

##### 重现步骤：
jeecg-boot集成v1.6.1依赖，本地运行项目。AppScan扫描Web应用程序（积木模板预览地址）：http://localhost:9030/jeecg-boot/jmreport/view/691178166178467840

---
##### 重现步骤：
升级1.6.2-GA5。AppScan扫描Web应用程序（积木模板预览地址携带有效token）：http://localhost:9030/jeecg-boot/jmreport/view/740470174112911360?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2OTQ2NzEwODYsInVzZXJuYW1lIjoiY3NkeTAwMyJ9.5ebGnRR3ipsil5U6fXs2GdKHDsnMopV86LBgiqGXHZQ

**Comment by zhangdaiscott** [comment]
升级到1.6.2-GA3最新版，加了token限制

**Comment by gxggsggp** [comment]
升级到1.6.2-GA5，在token有效期内，扫描完整链接仍提示： 跨站点脚本编制

**Comment by zhangdaiscott** [comment]
已修复，下个版本发布
