### ISSUE TITLE
升级1.6.2-GA2后报表参数无法生效

### ISSUE THREAD

**Issue by Optimusruan** [jeecgboot/JimuReport#2007]
##### 版本号：
1.6.2-GA2

##### 问题描述：
从1.6.1升级到1.6.2-GA2后，报表参数报错

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/16751699/cf407997-4897-4c26-b540-fd3fbcaab682)

![image](https://github.com/jeecgboot/JimuReport/assets/16751699/09834d44-d80d-4856-8f32-5923713758ee)

##### 重现步骤：

升级后提示没有token，然后增加了JmReportTokenServiceI实现类，确实可以正常显示了，但是就是看起来参数没有赋值到sql

**Comment by zhangdaiscott** [comment]
升级1.6.2-GA5看看

**Comment by zhangdaiscott** [comment]
或者降低到老版本就好使？

**Comment by Optimusruan** [comment]
> 或者降低到老版本就好使？

1.6.1是正常的，另外尝试了升级GA5也是一样报错

**Comment by zhangdaiscott** [comment]
- 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Optimusruan** [comment]
[report-export-mysql.txt](https://github.com/jeecgboot/JimuReport/files/12592693/report-export-mysql.txt)

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
后续需要使用`${DaoFormat.concat(${参数名称},' 00:00:00')}；`来拼接参数

**Comment by Optimusruan** [comment]
阮才通已经收到您的邮件
