### ISSUE TITLE
报表导出普通excel，单元格为数值，小数位数设为2的，值为0时，预览为 0，导出结果为 .00

### ISSUE THREAD

**Issue by catlvsuger** [jeecgboot/JimuReport#2009]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/39261781/5cb0401c-a959-4986-bee5-27ce8331cdad)
![image](https://github.com/jeecgboot/JimuReport/assets/39261781/82b44bae-edd2-48a4-8ef2-5aaf81178ed9)
![image](https://github.com/jeecgboot/JimuReport/assets/39261781/dd0e393a-3558-4aef-84d1-2aa880271450)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by happyuanhao** [comment]
以及导出的报表值比如：0.120  导出的值就是.120  前面的零没有了
![image](https://github.com/jeecgboot/JimuReport/assets/25651702/96b71ef0-1123-4d18-b809-6a94beb499db)

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
