### ISSUE TITLE
javax.servlet.Filter无法转换为jakarta.servlet.Filter

### ISSUE THREAD

**Issue by zengzhuo** [jeecgboot/JimuReport#2011]
##### 版本号：
1.6.2-GA5

##### 问题描述：
集成springboot3.1.3版本时出现：java: 不兼容的类型: javax.servlet.Filter无法转换为jakarta.servlet.Filter

##### 错误日志&截图：
java: 不兼容的类型: javax.servlet.Filter无法转换为jakarta.servlet.Filter
##### 重现步骤：

只需引用springboot3.1.3版本启动就会出现该问题

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zengzhuo** [comment]
经过测试版本降到springboot2.7.15 及以下都可以，希望能对3.x版本做一下支持，谢谢

**Comment by zhangdaiscott** [comment]
短期内无计划升级

**Comment by zhangdaiscott** [comment]
制作了一个版本(springboot3.1.5+jdk17)，试试
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot3-starter</artifactId>
  <version>1.6.6</version>
</dependency>
```
