### ISSUE TITLE
API数据源，post请求后端无法接收到参数

### ISSUE THREAD

**Issue by qiuwenhu** [jeecgboot/JimuReport#2012]
##### 版本号：
1.6.2-GA

##### 问题描述：
API数据源，post请求后端无法接收到参数，之前成功过，但后面再解析就无法接收到参数了

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/111714892/8b4a2d45-4665-4ab7-96c8-912ccdcbfa29)
![image](https://github.com/jeecgboot/JimuReport/assets/111714892/322159e5-f593-4925-aa67-56dd9daafef6)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
post请求请使用RequestBody接收，RequestParam为get请求
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/ca0865c9-c1de-4fe7-9dce-17f74776fd2c)
如果还有问题请回复或升级版本试一下
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.6.2</version>
</dependency>
```

**Comment by qiuwenhu** [comment]
案列确实是用body接收的，我也确实成功过，但后续又无法接收，暂时没发现什么问题引起的该问题。后续有问题再提issue，感谢回复。
