### ISSUE TITLE
报表如何通过配置限制显示返回数据的条数或行数

### ISSUE THREAD

**Issue by cauchemar02** [jeecgboot/JimuReport#2013]
##### 错误日志&截图：
![mmexport1694761324427](https://github.com/jeecgboot/JimuReport/assets/122009614/558af459-b2b0-4e4b-babf-dbd7a45bf88c)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持

**Comment by cauchemar02** [comment]
那隐藏行支持吗？

**Comment by lvdandan16** [comment]
不支持，目前返回数据都会显示

**Comment by cauchemar02** [comment]
那打印格式可以修改吗？修改页边距等内容

**Comment by cauchemar02** [comment]
那打印格式可以修改吗？修改页边距等内容

**Comment by lvdandan16** [comment]
参考文档：https://help.jeecg.com/jimureport/print/rule.html
