### ISSUE TITLE
前后端分离系统的集成

### ISSUE THREAD

**Issue by hnsongbiao** [jeecgboot/JimuReport#2015]
##### 版本号：
1.6.2-GA5

##### 问题描述：
https://help.jeecg.com/jimureport/config/token.html

前后端分离系统，目前系统登录后调用后端接口都是通过header传递Token的方式，
不通过url传递token的方式可以支持吗？

另外报表配置为菜单时
前端组件：layouts/IframePageView 是必须的吗？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
支持
    /**
     * 发起请求接受请求需要在header里传token 此为token名
     */
    public static final String HEADER_TOKEN_KEY = "X-Access-Token";
