### ISSUE TITLE
界面报错：操作失败，MemberAccess implementation must be provided!

### ISSUE THREAD

**Issue by lyon1030** [jeecgboot/JimuReport#2016]
##### 版本号：
1.6.2-GA5

##### 问题描述：
接口 /jimureport/excelQuery   报错 MemberAccess implementation must be provided

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/128144990/c55b16f6-7677-4552-854a-26d392da0c92)
![image](https://github.com/jeecgboot/JimuReport/assets/128144990/9b64e456-b50b-4bff-a7b3-7fcc492748e2)

##### 重现步骤：
我用的springboot版本是2.1.6 
重现步骤 ：打开localhost:8080/jmreport/list 页面时，服务端接口 /jimureport/excelQuery   报错 MemberAccess implementation must be provided

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
那个功能操作?

**Comment by lyon1030** [comment]
> 那个功能操作?

进入页面jmreport/list就报错, 报错接口 jmreport/excelQuery
![95026A45-07E3-46d2-AE0D-1C02710F07CE](https://github.com/jeecgboot/JimuReport/assets/128144990/f27d526b-c9c7-4e7a-89fe-90003636a620)

**Comment by zhangdaiscott** [comment]
测试无问题，看看你项目是不是有minidao版本冲突

**Comment by lyon1030** [comment]
> 测试无问题，看看你项目是不是有minidao版本冲突

对springboot版本有要求吗  我的v：zjl908107968 希望交流一下

**Comment by zhangdaiscott** [comment]
升级版本号看看
<jimureport-spring-boot-starter.version>1.6.2</jimureport-spring-boot-starter.version>
	<minidao.version>1.9.4</minidao.version>
