### ISSUE TITLE
分版出现串行

### ISSUE THREAD

**Issue by xtxujin** [jeecgboot/JimuReport#2017]
##### 版本号：
1.6.2

##### 问题描述：
左侧为明细列表，右侧为固定显示信息。在右侧设为分版后，出现右侧的内容向上偏移了两行。详见图片。

##### 错误日志&截图：
![报表设计预览](https://github.com/jeecgboot/JimuReport/assets/145192816/aeeb4dbc-7b4b-4b1c-8446-88ff96bfc35f)

![报表实际应用显示](https://github.com/jeecgboot/JimuReport/assets/145192816/2cf79752-2f5c-4574-bb4d-7d5b9fb907d0)

##### 重现步骤：
左侧添加一个明细列表，右侧添加一个固定值显示（非明细列表）右侧设为分版。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
无回复关闭
