### ISSUE TITLE
数值0转成百分比就不展示了

### ISSUE THREAD

**Issue by dx0809** [jeecgboot/JimuReport#2018]
##### 错误日志&截图：
![1695018266109](https://github.com/jeecgboot/JimuReport/assets/35514496/66b112d8-3534-499b-b639-a5de693c9067)
![1695018280460](https://github.com/jeecgboot/JimuReport/assets/35514496/1c49f404-a23f-4eb8-8967-cb7b3b8920b4)
![1695018347335](https://github.com/jeecgboot/JimuReport/assets/35514496/2497e0ee-12b3-429c-b355-fd9d19803dfc)

##### 重现步骤：
sql数据集，返回的小数，设置成百分比展示后，0值的字段，有的展示空，有的展示0%。想要的效果是都展示0%。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by liaozhiyang** [comment]
已修复，下一版本更新。应该是数据返回的是0.0或者0.00导致的
