### ISSUE TITLE
怎么冻结表头

### ISSUE THREAD

**Issue by rw12306** [jeecgboot/JimuReport#2019]
##### 版本号：

1.6.2-GA5
##### 问题描述：
怎么冻结表头，比如现在查询出很多数据，往下滚动的时候，表头能看到。
目前没看到有冻结这个参数控制。
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/42023195/d5a32f37-a002-444b-9339-9a80e3fe5063)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
目前不支持
