### ISSUE TITLE
导出excel后样式出现问题

### ISSUE THREAD

**Issue by butOutOfMemory** [jeecgboot/JimuReport#2022]
##### 版本号：
1.6.1

##### 问题描述：
导出excel后，边框和配置/预览的不同
以下分别是配置页面，预览页面，excel页面

##### 错误日志&截图：
![1](https://github.com/jeecgboot/JimuReport/assets/48743827/c844ce38-aa11-4ec5-bf6c-af3348621a5d)
![2](https://github.com/jeecgboot/JimuReport/assets/48743827/854f798c-3ee6-444d-a571-769e4e459039)
![3](https://github.com/jeecgboot/JimuReport/assets/48743827/6646f0fc-646c-441f-afc7-bcb7f7bebd42)

##### 重现步骤：
有循环块，循环块内有合并单元格和边框线

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
升级到1.6.2看看

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
