### ISSUE TITLE
java.lang.NoSuchMethodError: com.lowagie.text.pdf.PdfPCell.setBackgroundColor

### ISSUE THREAD

**Issue by lianguooo** [jeecgboot/JimuReport#2023]
##### 版本号：
1.6.1

##### 问题描述：
预览后点击导出PDF时，后端报错

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/109119112/ba8fecc5-ca68-449d-b7f9-ad101049a489)

##### 重现步骤：
1、点击任一报表预览
2、点击导出PDF

**Comment by zhangdaiscott** [comment]
是不是依赖有冲突

**Comment by lianguooo** [comment]
> 是不是依赖有冲突

您好，1.6.1 版本内的依赖没看到冲突项
![image](https://github.com/jeecgboot/JimuReport/assets/109119112/ea7770e9-2bdd-4af7-98d0-309d65c7a938)
其他自己工程涉及到的PDF工具类如下：
<poi.version>4.1.2</poi.version>
<ooxml-schemas.version>1.4</ooxml-schemas.version>
<pdf-gae.version>2.0.2</pdf-gae.version>
<itextpdf.version>5.5.13</itextpdf.version>
<itext5.version>9.1.16</itext5.version>
<pdfbox.version>2.0.17</pdfbox.version>

**Comment by zhangdaiscott** [comment]
应该是有冲突，积木用的是openpdf
