### ISSUE TITLE
升级1.6.2-GA5后，设计报表，报错：缺失模板

### ISSUE THREAD

**Issue by liyuhui98** [jeecgboot/JimuReport#2026]
##### 版本号：
1.6.2-GA5
##### 问题描述：
升级1.6.2-GA5后，设计提示缺失模板。

freemarker.template.TemplateNotFoundException: Template not found for name "/jimu/jmreport/desreport/authority.ftl".
不确定是不是文件路径不对的问题，在升级之前版本为1.5.9，升级至1.6.2-GA5后出现报错
##### 错误日志&截图：
![图片](https://github.com/jeecgboot/JimuReport/assets/81678276/ebefd892-0795-41cd-801d-eecdde84f950)
![图片](https://github.com/jeecgboot/JimuReport/assets/81678276/48e377d2-ed85-4de3-a23a-e696ac6c9e1d)

![图片](https://github.com/jeecgboot/JimuReport/assets/81678276/7b07b2e5-3a20-41ad-93fb-0b2383efb191)
![图片](https://github.com/jeecgboot/JimuReport/assets/81678276/d7f8c6ad-3060-48ac-add4-a91365cf0504)

##### 重现步骤：
升级至1.6.2-GA5后。进行报表设计。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
怎么操作的？点击的那个功能，其他人没反馈类似问题

**Comment by zhangdaiscott** [comment]
无回复关闭
