### ISSUE TITLE
若依vue版集成之后看不到积木报表页面

### ISSUE THREAD

**Issue by happypWha** [jeecgboot/JimuReport#2027]
##### 版本号：
1.6.2

##### 问题描述：

若依vue版集成之后看不到积木报表页面
##### 错误日志&截图：
http://localhost:8848/jmreport/list 404

##### 重现步骤：
按照改文档进行集成的http://report.jeecg.com/2302148

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/jimureport/projectJoin/ruoyivue.html

**Comment by happypWha** [comment]
sql脚本从官网下载的不对啊，在哪里可以下载到正确的脚本啊

**Comment by happypWha** [comment]
<img width="717" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/18569566/a12b1bb2-953a-4ce6-974f-c3656cbec58f">
请问 这个token从哪里获取啊
