### ISSUE TITLE
图表跨页导出时无法显示，但偶尔跨页时也能导出。

### ISSUE THREAD

**Issue by qiuwenhu** [jeecgboot/JimuReport#2029]
##### 版本号：
1.6.2

##### 问题描述：

导出时图表无法显示，可能是图表跨页了？偶发性的bug
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/111714892/50ff06f5-cd02-4199-babe-079aab52c751)
![image](https://github.com/jeecgboot/JimuReport/assets/111714892/d07e5989-bc9f-47b0-84e0-44283cc4b295)
![image](https://github.com/jeecgboot/JimuReport/assets/111714892/cbcc337d-447e-4697-a88a-8b30d93e0fc7)

##### 重现步骤：
图表跨页导出时无法显示，但偶尔跨页时也能导出。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
导出多次未复现，请导出报表配置并提供数据，或者在线上做个例子，我们复现一下
设计器页面
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/18eada2c-d8c1-479b-8932-f2ccca8f3f5f)
预览页面
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/82f473c0-31ca-42bd-9950-66bb8788ec49)
导出excel
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/1c7aa10d-f949-448e-be22-b504024f0822)
