### ISSUE TITLE
升级 1.6.2-GA2 后，下拉树组件多选后参数传递到 sql 中 in 语句失效

### ISSUE THREAD

**Issue by BEshakalaka** [jeecgboot/JimuReport#2030]
##### 版本号：
1.6.2-GA2

##### 问题描述：
升级后，下拉树组件多选后参数传递到 sql 中 in 语句失效，导致查不出数据

##### 重现步骤：
![4335cd309e989e60f715da93b5a80013](https://github.com/jeecgboot/JimuReport/assets/30748862/b233d3ec-85b9-4fc2-8b65-b64c6b4d696b)

![8962d3134d228f9dc8c75ecefcb05fc3](https://github.com/jeecgboot/JimuReport/assets/30748862/2c6226ce-0bff-4874-9026-96278d7ab8e9)

![063cc9005a45434e56ee2322c29df39e](https://github.com/jeecgboot/JimuReport/assets/30748862/ba847be7-5680-487f-878c-fe23034fbd21)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
后续需要使用${DaoFormat.concat(${参数名称},' 00:00:00')}`；来拼接参数
