### ISSUE TITLE
 升级1.6.2 后老是提示  注意，值可能存在SQL注入风险

### ISSUE THREAD

**Issue by lijinlang** [jeecgboot/JimuReport#2032]
##### 问题描述：
 升级1.6.2 后老是提示  注意，值可能存在SQL注入风险，没升级前都是正常的，有点搞不懂了，这语句该怎么写才没有注入风险

##### 错误日志&截图：

![43](https://github.com/jeecgboot/JimuReport/assets/54636793/8d18ad1f-d676-428d-b8ca-e97ed3211813)

**Comment by zhangdaiscott** [comment]
sql贴一下

**Comment by lijinlang** [comment]
> sql贴一下 并提供建表SQL

select cid,cgoods,cgoodsname,famount,fmoney,cmemo from fy_bus_sales where mid='${id}'


建表语句，我用的是Sqlserver

CREATE TABLE [dbo].[fy_bus_sales] (
  [id] varchar(36) COLLATE Chinese_PRC_CI_AS  NOT NULL,
  [create_by] nvarchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
  [create_time] datetime  NULL,
  [update_by] nvarchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
  [update_time] datetime  NULL,
  [sys_org_code] nvarchar(64) COLLATE Chinese_PRC_CI_AS  NULL,
  [mid] nvarchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
  [cid] nvarchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
  [cgoods] nvarchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
  [cgoodsname] nvarchar(150) COLLATE Chinese_PRC_CI_AS  NULL,
  [famount] decimal(10,2)  NULL,
  [fmoney] decimal(10,2)  NULL,
  [fwriteoff] decimal(10,2)  NULL,
  [cmemo] nvarchar(300) COLLATE Chinese_PRC_CI_AS  NULL
)
GO

**Comment by zhangdaiscott** [comment]
测试无问题，看看后台日志提示的关键词是什么
![image](https://github.com/jeecgboot/JimuReport/assets/3162115/c985ad94-a009-4f96-a8b2-961be6e53188)

**Comment by lijinlang** [comment]
> 测试无问题，看看后台日志提示的关键词是什么 ![image](https://user-images.githubusercontent.com/3162115/270206966-c985ad94-a009-4f96-a8b2-961be6e53188.png)


我刚看过了是提示字段mid存在SQL注入关键词，这个字段名称都限制，我想应该跟注入关系不大吧

![微信图片_20230925100204](https://github.com/jeecgboot/JimuReport/assets/54636793/b43a95bb-54c1-4407-99d3-16a0891f6f6c)






> ##### 版本号：1.6.2
> ##### 问题描述：
> 升级1.6.2 后老是提示 注意，值可能存在SQL注入风险，没升级前都是正常的，有点搞不懂了，这语句该怎么写才没有注入风险
> 
> ##### 错误日志&截图：
> ![43](https://user-images.githubusercontent.com/54636793/270156492-8d18ad1f-d676-428d-b8ca-e97ed3211813.png)

**Comment by zhangdaiscott** [comment]
就是这个关键词导致的

**Comment by lijinlang** [comment]
那是要等更新了吗

**Comment by zhangdaiscott** [comment]
升级到
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.6.3</version>
</dependency>
```

**Comment by zhangdaiscott** [comment]
使用to_char函数导致的

**Comment by Userluckytian** [comment]
> 使用to_char函数导致的

是的，只是针对日期格式我们需要使用to_char函数。期望能帮忙解决下这个问题。

**Comment by zhangdaiscott** [comment]
下个版本处理
