### ISSUE TITLE
图表钻取时，无法把查询栏参数通过url带到被钻取的报表

### ISSUE THREAD

**Issue by luyizhilu** [jeecgboot/JimuReport#2033]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/143050735/d86ca4c9-5486-488f-970c-03b2ce8dcb49)
上图钻取到下图，查询栏的时间条件未带到被钻取的报表
![image](https://github.com/jeecgboot/JimuReport/assets/143050735/c280a8c7-b54b-45d2-b126-4923f5f7a29a)

##### 重现步骤：
第一张图根据时间查询后，点击第一张图表中的某个柱状，跳转到第二个报表

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
没这功能
