### ISSUE TITLE
使用免安装版本，但是执行sql会报错，数据库是server SQL 2022版本

### ISSUE THREAD

**Issue by LingXF00** [jeecgboot/JimuReport#2035]
##### 版本号：
JimuReport v1.6.2版本发布(绿色免安装版)

##### 问题描述：
使用免安装版本，但是执行sql会报错，数据库是server SQL 2022版本

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/145946127/2d77f6f8-9eaf-4b08-ad20-e65d0ca0f965)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
这是mysql的脚本，自己转下sqlserver
https://my.oschina.net/jeecg/blog/4905722
