### ISSUE TITLE
低代码开发模式设置为prod不生效

### ISSUE THREAD

**Issue by escapeSky** [jeecgboot/JimuReport#2036]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/16132851/6375cfec-da28-49c5-9c16-6cb2b120215d)

##### 重现步骤：
1.按照接口文档自定义了Token鉴权，实现了 JmReportTokenServiceI接口，并重写了getRoles方法
![image](https://github.com/jeecgboot/JimuReport/assets/16132851/a370c3a0-1e93-4832-8cac-3a10d3674dc0)

2.配置文件设置 lowCodeMode: prod
![image](https://github.com/jeecgboot/JimuReport/assets/16132851/6375cfec-da28-49c5-9c16-6cb2b120215d)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
怎么个不生效？

**Comment by escapeSky** [comment]
@zhangdaiscott 配置了lowCodeMode: prod，普通用户仍可以修改报表

**Comment by zhangdaiscott** [comment]
你确定你配置的对？

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/3162115/fe119aeb-f097-4d0f-bb75-86cbd32b316e)
![image](https://github.com/jeecgboot/JimuReport/assets/3162115/0a85857f-0840-4fb6-bbc4-802d8cd8f5c7)

**Comment by escapeSky** [comment]
已经找到原因了，配置没问题。由于项目中已经重写了WebMvcConfigurationSupport，积木报表的JimuLowCodeModeConfigurationme没有生效，导致JimuLowCodeModeInterceptor拦截器未注入失败，重新注入就好了
![image](https://github.com/jeecgboot/JimuReport/assets/16132851/9266af31-0e16-464a-bbdb-7ce477563eb5)
