### ISSUE TITLE
免安装版无法打开报表

### ISSUE THREAD

**Issue by LingXF00** [jeecgboot/JimuReport#2039]
##### 版本号：
JimuReport v1.6.2 免安装版

##### 问题描述：
免安装版无法打开报表

##### 错误日志&截图：
想本地安装积木报表，按照说明已经完成全部步骤，但是访问报表是i这样
![BFO(CYI)7PGN EO}83LLL 8](https://github.com/jeecgboot/JimuReport/assets/145946127/a37f28f3-b834-4fd1-8c0a-65be2492205b)
第三步数据库连接配置修改这两个地方不知是否正确：
![P@ UCNB~@JYLU%_(0HEEE9H](https://github.com/jeecgboot/JimuReport/assets/145946127/f40badfe-3d90-49cb-be2b-7469b8c09926)
数据库的内容已创建
![(_B6U02}ZQY ~($)P99{I`B](https://github.com/jeecgboot/JimuReport/assets/145946127/17e87fd6-29ab-442b-86cc-09f17b1c55a9)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你启动成功了吗
