### ISSUE TITLE
饼图图表数值设置显示控制的是分类

### ISSUE THREAD

**Issue by luyizhilu** [jeecgboot/JimuReport#2041]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/143050735/a85fae5f-113c-4171-898c-5fbf347d2084)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/54099258/b32ba2dd-977f-4963-b414-47a6b4e55d91)
升级新版本，支持设置显示数值

**Comment by wm204** [comment]
> ![image](https://github.com/jeecgboot/JimuReport/assets/54099258/b32ba2dd-977f-4963-b414-47a6b4e55d91) 升级新版本，支持设置显示数值

**Comment by wm204** [comment]
> ![image](https://github.com/jeecgboot/JimuReport/assets/54099258/b32ba2dd-977f-4963-b414-47a6b4e55d91) 升级新版本，支持设置显示数值

<img width="1381" height="678" alt="Image" src="https://github.com/user-attachments/assets/f42b1ad6-4e36-4138-bb54-1d7b031fdd2c" /> 请问一下这个数字是怎么设置的和文字在同一行展示的啊

**Comment by luyizhilu** [comment]
好的，感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2025年9月24日(星期三) 下午4:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/jimureport] 饼图图表数值设置显示控制的是分类 (Issue #2041)












wm204 left a comment (jeecgboot/jimureport#2041)
  
 升级新版本，支持设置显示数值
  
image.png (view on web) 请问一下这个数字是怎么设置的和文字在同一行展示的啊
