### ISSUE TITLE
【BUG】1.6.2 打印小纸张报表预留的右边距过大影响正常文本内容显示

### ISSUE THREAD

**Issue by TheShy-bit** [jeecgboot/JimuReport#2042]
##### 版本号：
1.6.2

##### 问题描述：
打印单长宽设置的很小的时候 打印出来的预留右边距不对（默认A4纸没问题）
##### 重现步骤：
设置打印长宽为 95mm * 75mm 内容为一整行的文本

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；
[report-export-mysql.txt](https://github.com/jeecgboot/JimuReport/files/12714003/report-export-mysql.txt)
![Snipaste_2023-09-25_18-24-37](https://github.com/jeecgboot/JimuReport/assets/57949618/e717fb5d-1501-4232-ac06-978404d9b955)

**Comment by TheShy-bit** [comment]
这里我写入了大量的文本内容【1111111】 很明显 打印显示的纸张右边距不对 （我再打印设置界面 设置的两个边距都从10 改成了0 ）

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
你这PDF导出吧？不是打印吧？

**Comment by 1298191366** [comment]
已修复，待新版本发布
