### ISSUE TITLE
横向动态列分组无法渲染数据，只展示字段名

### ISSUE THREAD

**Issue by pokerLife** [jeecgboot/JimuReport#2043]
##### 版本号：
1.6.1

##### 问题描述：
横向动态列分组渲染不正确

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/23650523/4942386a-53fb-4ccd-bf2c-64d123d46668)

##### 重现步骤：
步骤一：
JSON数据为官方示例，示例ID：1351426064915763200
![image](https://github.com/jeecgboot/JimuReport/assets/23650523/e70f6643-e10b-4dab-af62-9a413fa7e8c2)
步骤二：
按照官方文档进行报表设计
![image](https://github.com/jeecgboot/JimuReport/assets/23650523/38db6f6f-aef8-47e9-8eaf-4b4dc884b068)
步骤三：
预览时候只显示month，无法正确显示月份

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
sq

**Comment by pokerLife** [comment]
> sq

官方示例也没有SQL，我自己写了SQL还是显示这样，请问是哪里的问题呢
