### ISSUE TITLE
打印如何调起

### ISSUE THREAD

**Issue by Vieboo** [jeecgboot/JimuReport#2045]
##### 版本号：
1.6.2

##### 问题描述：
打印模板设计好以后如何在我的系统里嵌入打印功能，必须要打开那个预览页面以后点击上面的打印按钮才能打印吗？有没有不启动那个预览页面就直接能打印的方法。

##### 错误日志&截图：
无

##### 重现步骤：
打印

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
目前没有
