### ISSUE TITLE
图形报表（多个图表）怎么设计统一的时间筛选条件

### ISSUE THREAD

**Issue by jujubetree** [jeecgboot/JimuReport#2046]
##### 版本号：
3.4.4

##### 问题描述：
图形报表（多个图表）怎么设计统一的时间筛选条件

##### 错误日志&截图：
非错误，寻求技术支持。
![Dingtalk_20230928135210](https://github.com/jeecgboot/JimuReport/assets/49394098/179aeef7-e4cb-4c11-b188-d78a9217b93c)
需求：右上角需要一个时间选择器，选择时间后，相关图表数据查询渲染
如果只能在查询栏出现时间筛选条件的方式，能否同时影响多个图表

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档：https://help.jeecg.com/jimureport/query/commonExamples.html
