### ISSUE TITLE
some request is error,plese fix them

### ISSUE THREAD

**Issue by TianHuan-th** [jeecgboot/JimuReport#2047]
##### 错误日志&截图：
无
##### 重现步骤：
1.随意编写一个API数据集（返回内容包含一个电站名称）
2.在API返回的报表字段明细里，找到对应的电站名称，为其配置：
字段文本：电站；类型：数值类型；字典Code：单独写一个接口查询所有电站并返回text及value（问题就在这个接口的查询上，如果是域名会没反应，如果是端口+IP才会回显出正确的筛选条件）；查询：勾选上；查询模式：下拉多选

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;

  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
域名配置的对吗，正常使用域名访问，可以访问吗
