### ISSUE TITLE
积木报表保留三位小数导致预览页面展示乱行空白

### ISSUE THREAD

**Issue by lizhaopeng686** [jeecgboot/JimuReport#2048]
##### 版本号：
1.6.1

##### 问题描述：
积木报表保留三位小数导致预览页面展示乱行空白

##### 错误日志&截图：
数据展示（应该保留三位小数）
![image](https://github.com/jeecgboot/JimuReport/assets/77133705/b919c3e4-0c17-4bca-b8f0-d64b3c51205b)
（设置三位小数后出现预览页面展示乱行和空白）
![image](https://github.com/jeecgboot/JimuReport/assets/77133705/f4dcf39e-6856-46f1-aaa1-84f17286d81d)
![image](https://github.com/jeecgboot/JimuReport/assets/77133705/ee345388-554a-42a9-8d4f-2fa691f43f27)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请在积木官网做个示例，我们复现一下

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此任务
