### ISSUE TITLE
打印尾部会有空白页

### ISSUE THREAD

**Issue by CYDCM** [jeecgboot/JimuReport#2050]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/68319096/65201270-d315-4dce-9dfd-0ec10b875824)

##### 重现步骤：

1.自带模板《阜阳火车站检票数》961455b47c0b86dc961e90b5893bff05
2.打印

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请升级到1.6.4确认问题是否还存在

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
