### ISSUE TITLE
自动换行打印空白页

### ISSUE THREAD

**Issue by CYDCM** [jeecgboot/JimuReport#2051]
##### 错误日志&截图：
![1696480326605](https://github.com/jeecgboot/JimuReport/assets/68319096/f9f5bec5-9949-4b1e-b71c-51ff6eaa385d)

![1696480276815](https://github.com/jeecgboot/JimuReport/assets/68319096/fc380151-dae8-4e6e-85c1-e840da7152f1)

![1696480178397](https://github.com/jeecgboot/JimuReport/assets/68319096/2bb1459b-9cf7-46bd-b142-74c4337c3dff)

##### 重现步骤：
1.创建数据表
2.给一列内容设置比较长的数据
3.设定长数据为自动换行
4.打印该报表

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 zy

**Comment by zhangdaiscott** [comment]
请升级到1.6.4确认问题是否还存在

**Comment by liaozhiyang** [comment]
<img width="787" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/8199499/1b50238b-c3c8-4f2c-be47-a15fa832c67d">
文字内容的高度大于第一页剩余空间的高度吧？这种情况目前确实是存在。

**Comment by lvdandan16** [comment]
归集 #138

**Comment by liaozhiyang** [comment]
已解决，下一版本发布。
