### ISSUE TITLE
导出excel，小数点四舍五入了

### ISSUE THREAD

**Issue by catlvsuger** [jeecgboot/JimuReport#2052]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/39261781/c1120e14-951c-4462-b69d-67982c8e6e74)
![image](https://github.com/jeecgboot/JimuReport/assets/39261781/cf7b0674-decd-486f-85ba-3894b8cd903a)
![image](https://github.com/jeecgboot/JimuReport/assets/39261781/09a928b3-684b-4a24-8900-d9279e3da21d)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/54099258/1d5c80f6-bb12-43a9-a49d-7c6d0bfd352a)
未复现，请在[积木报表官网](http://www.jimureport.com/)做个示例，我们复现一下

**Comment by catlvsuger** [comment]
问题已解决，应该是其他单元格格式影响了
