### ISSUE TITLE
低代码开发模式下，字典code查询提示不允许使用在线配置

### ISSUE THREAD

**Issue by gxjljx** [jeecgboot/JimuReport#2053]
##### 版本号：
1.6.2

##### 问题描述：
低代码开发模式为发布模式下，普通用户没法在字典下拉查询条件中查询所有值，会提示不允许使用在线配置，报表刚打开时也会报同样错误

##### 错误日志&截图：
![dictcode](https://github.com/jeecgboot/JimuReport/assets/5818815/0d91df30-3862-4dda-9f56-5f3dde510133)
![dictCode1](https://github.com/jeecgboot/JimuReport/assets/5818815/3745d265-43c4-48c6-bb34-9da57b628c82)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by lsqGitHub716** [comment]
已修改
