### ISSUE TITLE
sql数据集SUM函数计算结果为0

### ISSUE THREAD

**Issue by yy879770988** [jeecgboot/JimuReport#2054]
##### 版本号：
1.5.7

##### 问题描述：
SUM函数放在数据行之上时始终为0，数据行之下则正常。

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/23287804/6e79e185-bdf5-422f-8eaf-3cbec3fb9475)
![image](https://github.com/jeecgboot/JimuReport/assets/23287804/03ee1a64-4ace-46d0-8ef5-ee24da4b2cd9)

##### 重现步骤：
1.集成sql数据集
2.设计报表

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
sum不支持放上边，可以使用dbsum
