### ISSUE TITLE
设置自动换行刷新页面问题

### ISSUE THREAD

**Issue by 2926184288** [jeecgboot/JimuReport#2055]
##### 问题描述：
文本设置自动换行文本数量过多时刷新页面会有空白断行
如图，会出现空白条的情况（比如请求数据、滚动条滑动时）
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/93595345/cae63f5f-6da8-4dfa-b7da-6d4e10cf7d65)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请在积木官网做个示例，我们复现一下

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
