### ISSUE TITLE
微服务下分库，报表查询当中很多业务表只含有ID值，需要根据ID值关联出明细作为同一行记录数据展示。

### ISSUE THREAD

**Issue by 7vqinqiwei** [jeecgboot/JimuReport#2056]
##### 问题描述：
微服务下分库，报表查询当中很多业务表只含有ID值，需要根据ID值关联出明细作为同一行记录数据展示。

##### 错误日志&截图：
如：
![image](https://github.com/jeecgboot/JimuReport/assets/29558605/9d057741-35d2-4dcd-93e6-b1d7fd7947f7)
就像很多业务表都含有用户ID，没有保留用户名称。报表查询只能用基础用户表数据来展示是一样的道理！
请问这种业务场景，该如何配置。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
`

**Comment by zhangdaiscott** [comment]
如果你的意思是你知道ID，但是数据在不同的数据库里，你不知道怎么查询的话。
那你应该把不同库的数据合并一下，放到es或者地方，实现汇总查询，至于其他思路可以自行百度
