### ISSUE TITLE
查询条件下拉数据重复，数据排序问题

### ISSUE THREAD

**Issue by lijinlang** [jeecgboot/JimuReport#2057]
##### 问题描述：
1、查询条件设置下拉后，数据都是重复的，不会去重
2、报表SQL中写了ORDER BY字段排序，解析后语句有问题，排序不起作用，数据排序还是乱了

##### 错误日志&截图：

条件下拉数据重复
![1](https://github.com/jeecgboot/JimuReport/assets/54636793/52868a2a-3a74-411d-9d7d-87ad126e97f8)
![2](https://github.com/jeecgboot/JimuReport/assets/54636793/67dc5189-6ae2-45b1-8e82-843ff14e494d)

数据排序问题
![3](https://github.com/jeecgboot/JimuReport/assets/54636793/625f3a53-ee82-4d09-aabf-ddbc8bdd6247)
![4](https://github.com/jeecgboot/JimuReport/assets/54636793/52f5b340-4f40-48eb-ab47-728c7539482b)
![5](https://github.com/jeecgboot/JimuReport/assets/54636793/71c0f0f9-781e-45ef-9ee7-4cdb96945737)
![6](https://github.com/jeecgboot/JimuReport/assets/54636793/b1939754-fd02-453f-88f3-022242d57524)

**Comment by lvdandan16** [comment]
1、下拉查询默认不会去重 需使用字典code自己写sql去重
2、收录ws

**Comment by 1298191366** [comment]
查询字段为条件时请使用`{'order':'升序或者降序'}`，注意，如果第一个字段是asc会先处理asc的，然后在处理desc
文档地址：https://help.jeecg.com/jimureport/dataSet/sql.html#5%E6%8E%92%E5%BA%8F
前台配置
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/3663c30e-761d-44f9-8a5b-bfeedcc98630)

后台sql
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/a8076446-bd80-404c-83ef-e7f24b7eebd6)
