### ISSUE TITLE
redis的KYES 命令被禁用导致报错，在无法修改redis的配置情况下，是否提供其它解决方案？

### ISSUE THREAD

**Issue by qiuwenhu** [jeecgboot/JimuReport#2059]
##### 版本号：
1.6.2

##### 问题描述：
刷新缓存，或配置字典时报错，导出也报错。
正式环境redis的KYES 命令被禁用导致报错，在无法修改redis的配置情况下，是否提供其它解决方案？

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/111714892/54df8bff-ee9b-47c6-95ba-1e369d136f19)

##### 重现步骤：
刷新缓存，或配置字典时报错，导出也报错，

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by zhangdaiscott** [comment]
没有
