### ISSUE TITLE
单元格上对数据集进行过滤，报错

### ISSUE THREAD

**Issue by 2636134561** [jeecgboot/JimuReport#2060]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/36060933/4475415b-29ec-4321-be85-922795b2c6d0)
![5%D8VP28HK`~~ZR9)X OPV7](https://github.com/jeecgboot/JimuReport/assets/36060933/f1580e7b-0b59-4e74-b596-1a521550834e)

##### 重现步骤：
数据源sql:
SELECT 
  guid,gate_id,direction,time_part,METER_READB,METER_READE,MONTH_QTY,YEAR_QTY 
FROM 
  S_SE_GRID_QTY
WHERE
  TO_CHAR(SE_MONTH,'yyyy-mm') = '${THEMONTH}'
AND
  PLANT_ID = '0105000020'

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 2636134561** [comment]
补充：
预览效果：![image](https://github.com/jeecgboot/JimuReport/assets/36060933/9d704797-7511-4aa4-903b-7d5539613a5d)

数据源预览效果：
![TT%OM5(@()Q89JLYH(WI`{7](https://github.com/jeecgboot/JimuReport/assets/36060933/d713ded5-5405-457f-8154-df9b2f7160fa)

**Comment by lvdandan16** [comment]
数据里边有空数据吗？

**Comment by 2636134561** [comment]
> 数据里边有空数据吗？

没有，如上图，数据源预览有6条数据，没有空数据

**Comment by 2636134561** [comment]
开发分析可能是，当结果集为多条数据时时，积木不支持在单元格上对数据集进行过滤，然后取出对应的单条数据，渲染到对应行中
![UXHILR7LHGE0 IJ~4EQI`TO](https://github.com/jeecgboot/JimuReport/assets/36060933/82d8407f-b38a-4d38-980a-fc4f941f8bb0)
请确认一下积木是否能支持在单元格上对有多条数据的结果集进行过滤

**Comment by lvdandan16** [comment]
收录 ws
