### ISSUE TITLE
PDF打印到第二页的时候，背景图片被第一页的文字覆盖

### ISSUE THREAD

**Issue by 89306681** [jeecgboot/JimuReport#2061]
##### 版本号：

最新版
##### 问题描述：

PDF打印到第二页的时候，背景图片被第一页的文字覆盖
##### 错误日志&截图：
<img width="337" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/67043809/cb50ce44-22c8-45bf-b3fe-28fea2217be9">

##### 重现步骤：
https://bootapi.jeecg.com/jmreport/index/872308460753342464

**Comment by lvdandan16** [comment]
收录 zy

**Comment by 1298191366** [comment]
已修复，待新版本发布
