### ISSUE TITLE
预览格式异常

### ISSUE THREAD

**Issue by wdwdwdd** [jeecgboot/JimuReport#2062]
##### 版本号：
1.6.3

##### 问题描述：
预览格式异常

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/51241520/56f306f4-e32b-4cb9-bbef-0a15938b82cb)
![image](https://github.com/jeecgboot/JimuReport/assets/51241520/dbbf029e-8acc-4f23-be57-d1e23b96544f)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
异常在哪？请详细说明

**Comment by wdwdwdd** [comment]
> 异常在哪？请详细说明

![image](https://github.com/jeecgboot/JimuReport/assets/51241520/6ea888e5-f32c-4b13-92a5-c7e83f93d808)
这个地方按照设计不应该有空出的地方，应为填满红框

**Comment by zhangdaiscott** [comment]
怎么设计的详细说明，发问题请考虑他人是否能分析准确
