### ISSUE TITLE
合计项，报 表达式处理出错，单元格

### ISSUE THREAD

**Issue by xdxycx** [jeecgboot/JimuReport#2063]
##### 版本号：
jimureport-example-1.6.jar

##### 问题描述：
数据报表，合计项,使用sum(I4)实现
2023-10-12 20:42:48.272 [http-nio-8085-exec-10] ERROR org.jeecg.modules.jmreport.desreport.express.a:334 - 表达式处理出错，单元格：I6004
##### 错误日志&截图：

![微信图片_20231013104359](https://github.com/jeecgboot/JimuReport/assets/4011625/18577eda-2bab-4b43-85b1-421f75574cf3)

##### 重现步骤：
多次查询就可以实现

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
数据有问题吧？这不提示哪个单元格有问题了吗

**Comment by xdxycx** [comment]
合计单元格出问题，使用sum(单元格)合计，数据没有问题，可能数据量有关系，数据少出错很少，数据量多出错。

**Comment by lvdandan16** [comment]
在积木官网做个例子，我们复现一下，没例子不好复现

**Comment by xdxycx** [comment]
只要行数大于4000或者5000就会发生这个问题，就是数据量大就会发生

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
