### ISSUE TITLE
对单元格进行纵向分组扩展，出现多余空白行

### ISSUE THREAD

**Issue by 2636134561** [jeecgboot/JimuReport#2065]
##### 错误日志&截图：
![Uploading L0OZ1FONGR[SP[PXTC)}`0K.png…]()
![image](https://github.com/jeecgboot/JimuReport/assets/36060933/0d86e010-eb13-4247-ba92-4ee5dc81a2ae)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 2636134561** [comment]
补充：单元格扩展，只展示了4条数据，且出现多余空白行
![L0OZ1FONGR SP PXTC)}`0K](https://github.com/jeecgboot/JimuReport/assets/36060933/8fa57d00-e365-4838-a640-1f69f3713775)

**Comment by lvdandan16** [comment]
请在积木官网做个例子，我们复现一下

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
