### ISSUE TITLE
js增强实现查询条件下拉框联动选择时存在问题

### ISSUE THREAD

**Issue by Unique-Dong** [jeecgboot/JimuReport#2066]
##### 错误日志&截图：
1、
![image](https://github.com/jeecgboot/JimuReport/assets/69563859/2c3f4c88-8bbd-49f9-b3da-4f0ee022870a)
![image](https://github.com/jeecgboot/JimuReport/assets/69563859/9f73b9f5-e3ce-4cc9-b211-6ab80f193abb)
![image](https://github.com/jeecgboot/JimuReport/assets/69563859/d1d65c44-7fbd-4f91-a0c1-20bd3568da6a)
![image](https://github.com/jeecgboot/JimuReport/assets/69563859/8096bb84-f5b1-450c-9ae6-aaa3632651c2)
![image](https://github.com/jeecgboot/JimuReport/assets/69563859/8a8c4f87-c81a-4898-a60f-74b25cd7147d)
![image](https://github.com/jeecgboot/JimuReport/assets/69563859/0a27309c-6ffd-46f9-beb6-06f76eea9e19)
2、
![image](https://github.com/jeecgboot/JimuReport/assets/69563859/d0394b70-1242-477f-a6c9-d61a7399e69e)

##### 重现步骤：
1、第一次加载后，第一次选择徽州银行，后台查询出手别为普委，但是查询条件手别未显示。然后第二次选择浦发银行，后台查询出手别为1，但是查询条件手别显示的是上一次的普委，最后第三次选择徽州银行，后台查询出手别为普委，但是查询条件手别显示的是上一次的1。
2、点击查询条件重置后，连第一个下拉框的值都没有了，就没法进行联动了。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by whatwhatw** [comment]
我也遇到了这个问题，请问有解决办法了吗

如图：第一级机构有两个选项，选择全部的时候可以查询到5个返回值，也在控制台打印了，但是药房的下拉没数据，
![13719c333ea7c445e81752541f136c72](https://github.com/jeecgboot/JimuReport/assets/154484667/2e0e4fa4-d9c8-4888-b9a1-924ac89b1e74)

选择演示机构的时候，后台返回长度为4的数据信息，但药房的下拉显示上次全部查询的数据。
![DDBB47A0-94A5-463b-AD43-B1BC9854E67A](https://github.com/jeecgboot/JimuReport/assets/154484667/117e3078-b144-4e1f-94e5-039558452664)

js 配置：
`function init(){
// 加载第1个下拉框数据
$http.metaGet('/jmreport/getOrgList').then(res=>{
  let options =  res.data;
console.log(options);
  this.updateSelectOptions('drug_acceptance', 'orgId', options)
})
// 监听第1个下拉框改变事件 加载第2个下拉框数据
this.onSearchFormChange('drug_acceptance', 'orgId', (value)=>{
    let params = {params: {pid: value}}
    $http.metaGet('/jmreport/getPharmacyByOrg', params ).then(res=>{
        let options =  res.data;
console.log(options);
        this.updateSelectOptions('drug_acceptance', 'deptId', options)
    })
})
}`

**Comment by yixuexing** [comment]
你好，请问$http.metaGet后面的url是什么，怎么获取
