### ISSUE TITLE
日期字段设置查询默认值为昨天日期时，设置yyyyMMdd格式，日期控件显示NaN

### ISSUE THREAD

**Issue by Unique-Dong** [jeecgboot/JimuReport#2067]
##### 问题描述：日期字段设置查询默认值为昨天日期时，设置yyyyMMdd格式，日期控件显示NaN。后来试了设置yyyy-MM-dd格式
反而是正常的，难道只支持yyyy-MM-dd格式？

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/69563859/9cdef0d7-b95b-4a10-a0a0-47901d0456d1)
![image](https://github.com/jeecgboot/JimuReport/assets/69563859/39b2dd88-27a8-4574-b29c-8acdf3a5d1db)
![image](https://github.com/jeecgboot/JimuReport/assets/69563859/d24103c5-64bd-4b4b-b476-521a5a33b788)
![image](https://github.com/jeecgboot/JimuReport/assets/69563859/d3a0a025-2790-4373-a3f0-fb81da8e83a5)

##### 重现步骤：
日期字段设置查询默认值为昨天日期时，设置yyyyMMdd格式，日期控件显示NaN。清空后正常选择就可以。后来试了设置yyyy-MM-dd格式反而是正常的，难道只支持yyyy-MM-dd格式？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Unique-Dong** [comment]
版本号 1.6.2

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
时间默认值只支持格式 `yyyy-MM-dd`和`yyyy-MM-dd HH:mm:ss`，其余格式暂不支持
参考文档：https://help.jeecg.com/jimureport/query/timeControlDefaultValue.html

**Comment by lvdandan16** [comment]
归集到 #138
