### ISSUE TITLE
导出失败

### ISSUE THREAD

**Issue by Luo09** [jeecgboot/JimuReport#2070]
##### 版本号：1.4.2
    <name>jimureport</name>
    <groupId>org.jeecg</groupId>
    <artifactId>jimureport</artifactId>
    <version>1.4.2</version>

##### 错误日志&截图：
java.lang.IllegalArgumentException: Invalid cell range, having lastRow < firstRow || lastCol < firstCol, had rows 2 >= 1 or cells 50 >= 54
![1697441662905](https://github.com/jeecgboot/JimuReport/assets/59717072/9bac1728-1ea6-4b40-a96a-2fde65b32b09)

![1697441809459](https://github.com/jeecgboot/JimuReport/assets/59717072/6ea3a570-f74a-480d-bfd5-2702304df0bc)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
遇到问题请先升级到最新版，再发帖

**Comment by wm204** [comment]
兄弟，这个最后怎么解决的
