### ISSUE TITLE
打印时添加页码

### ISSUE THREAD

**Issue by jewin** [jeecgboot/JimuReport#2073]
##### 版本号：
3.5.3

##### 问题描述：
报表打印时，如何为每一页添加对应的页码

##### 错误日志&截图：
无

##### 重现步骤：
无

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
积木报表升级到最新版就有这功能了

**Comment by caitxj** [comment]
> 积木报表升级到最新版就有这功能了

请问下，升级后，是有api或方法，可以直接在界面上获取并展示了？如: ${currentPage}, ${totalPage} 这种方式进行获取页码？
