### ISSUE TITLE
分版数据出现错位

### ISSUE THREAD

**Issue by Jsmin** [jeecgboot/JimuReport#2074]
##### 版本号：
1.6.4

##### 问题描述：
需要多数据集展示，分版数据错位

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/7332324/d7e26b34-e91e-44dc-925c-60c9254cd16b)

##### 重现步骤：
请查看预览地址:  https://bootapi.jeecg.com/jmreport/shareView/874077747297996800 

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by Jsmin** [comment]
> 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
分享预览地址为：https://bootapi.jeecg.com/jmreport/shareView/874077747297996800
ID:874077747297996800

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lvdandan16** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/54099258/3bb148ae-f911-4477-bd95-9fb0530308ef)
分版暂不支持，上方有表格
