### ISSUE TITLE
横向动态扩展后，扩展列后面的列不显示

### ISSUE THREAD

**Issue by 2636134561** [jeecgboot/JimuReport#2078]
##### 问题描述：
1.横向动态扩展后，扩展列后面的列不显示
2.横向扩展列后，表标题不能随着扩展列自动居中

##### 错误日志&截图：
无

##### 重现步骤：
如下图配置报表，预览即可重现（图片上传不上去）

报表配置sql:
[trade2.xlsx](https://github.com/jeecgboot/JimuReport/files/12923982/trade2.xlsx)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 2636134561** [comment]
图片传不上去。。。

**Comment by zhangdaiscott** [comment]
可以

**Comment by 2636134561** [comment]
> 可以
怎么进行设置

**Comment by 2636134561** [comment]
![Uploading 0VF1WE1SMGDG~`%D_U%WU8R.png…]()

**Comment by lvdandan16** [comment]
图片看不到

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
