### ISSUE TITLE
请自定义 JmReportTokenServiceI 的实现类，获取用户账号不允许为空！

### ISSUE THREAD

**Issue by hanfengcan** [jeecgboot/JimuReport#2079]
##### 版本号：
1.6.2

##### 问题描述：
从1.5.2升级到1.6.2后，访问jmreport/list提示，请自定义 JmReportTokenServiceI 的实现类，获取用户账号不允许为空！没有在文档看到与此相关的配置说明。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档：https://help.jeecg.com/jimureport/config/token.html
