### ISSUE TITLE
=row()行号顺序错乱

### ISSUE THREAD

**Issue by jwzjay** [jeecgboot/JimuReport#2080]
##### 错误日志&截图：
<img width="534" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/40534272/4586e678-d5df-4188-a282-9d7e1badc0d2">
![QQ20231018-1](https://github.com/jeecgboot/JimuReport/assets/40534272/df666820-4764-4dc5-a465-e9abecf27a36)

##### 重现步骤：
有横向分组（人员编号）和纵向分组（日期），为考勤数据

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jwzjay** [comment]
错乱照片为：
<img width="338" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/40534272/94810acb-0217-4cd4-b2fc-6d2e376547ea">

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
使用[模版](https://bootapi.jeecg.com/jmreport/shareView/1354358750907076608)测试没有复现你的问题，麻烦提供一下你的设计模版和模拟数据
![image](https://github.com/jeecgboot/JimuReport/assets/65587928/f55e7947-cd3d-411b-847c-99b28f388e69)

**Comment by jwzjay** [comment]
经过测试是因为在分组下的 动态属性里加了表达式导致的

=(let status= '#{shihua_api_1.dynamic(status)}';
if(status== '0'){
   return  '正常';
}elsif(status== '1'){
   return  color('年假','red','#ffff00');
}elsif(status== '2'){
   return  color('事假','red','#ffff00');
}elsif(status== '3'){
   return  color('病假','red','#ffff00');
}elsif(status== '4'){
   return  color('婚假','red','#ffff00');
}elsif(status== '5'){
   return  color('丧假','red','#ffff00');
}elsif(status== '6'){
   return  color('产假','red','#ffff00');
}elsif(status== '7'){
   return  color('护理假','red','#ffff00');
}elsif(status== '8'){
   return  color('探亲假','red','#ffff00');
}elsif(status== '9'){
   return  color('调休','red','#ffff00');
}elsif(status=='10'){
   return  color('公出','red','#ff9900');
}elsif(status=='20'){
   return  color('缺勤','red','#9fc5e8');
})

**Comment by lsqGitHub716** [comment]
测试动态属性里加表达式，也未复现，麻烦提供一下你的设计模版和模拟数据

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
