### ISSUE TITLE
分版之后导出Excel报空指针异常

### ISSUE THREAD

**Issue by hd0715** [jeecgboot/JimuReport#2081]
##### 版本号：
1.6.4

##### 问题描述：
不分版能正常导出，分版之后导出Excel时报空指针异常!，sql数据都有并且能展示。

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/83495935/61857bfe-ceda-4899-8c79-89a3ce7dfac3)
##### 重现步骤：
报表页面分页列表正常展示，工具栏点击导出excel时报错

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by hd0715** [comment]
[report-export-mysql.zip](https://github.com/jeecgboot/JimuReport/files/12988221/report-export-mysql.zip)

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
请提供一下表结构和测试数据，我复现一下

**Comment by hd0715** [comment]
收到 ！  
[Uploading kitchen_garbage_quality_log.zip…]()

**Comment by 1298191366** [comment]
> 收到 ！ Uploading kitchen_garbage_quality_log.zip…

你好，这个没有上传成功，需要你再上传一下

**Comment by hd0715** [comment]
[kitchen_garbage_quality_log.zip](https://github.com/jeecgboot/JimuReport/files/13173321/kitchen_garbage_quality_log.zip)

**Comment by 1298191366** [comment]
已修复，待新版本发布
