### ISSUE TITLE
纵向分组统计时，新增小计和合计时，最后合计的单元格的百分比怎么计算

### ISSUE THREAD

**Issue by lizhaopeng686** [jeecgboot/JimuReport#2082]
##### 版本号：
1.6.2
##### 问题描述：
1、在使用compute()内支持任意运算符计算时，如果除法为0，则为空
2、计算百分比时，怎么计算最后合计的单元格的百分比，如下图

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/77133705/69fcaf87-7e5b-40c3-854e-f748e9ee0037)
图1
![image](https://github.com/jeecgboot/JimuReport/assets/77133705/44812ba4-59f9-48df-ad87-9278c95ef818)
图2
![image](https://github.com/jeecgboot/JimuReport/assets/77133705/4a18587b-ea6e-4e87-bf50-09a2699acd1a)
图3
![image](https://github.com/jeecgboot/JimuReport/assets/77133705/5ad0d1ae-b039-42e5-b7b3-06f4ef89ab65)
图4

##### 重现步骤：
纵向分组统计时，新增小计和合计时，遇到的问题

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lizhaopeng686** [comment]
> 收录 sq

请问什么时候能解决，解决时提醒下可以吗？

**Comment by lsqGitHub716** [comment]
麻烦提供一下模版配置和数据，方便定位问题
