### ISSUE TITLE
分享链接创建失败

### ISSUE THREAD

**Issue by liukunyaya** [jeecgboot/JimuReport#2084]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/86349912/308a6964-6330-4dec-a43a-8a23db07a8cc)
![image](https://github.com/jeecgboot/JimuReport/assets/86349912/584077b4-77be-4fe5-b993-53f033b4a57e)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
后台报什么错
