### ISSUE TITLE
图片无法显示

### ISSUE THREAD

**Issue by A2324124** [jeecgboot/JimuReport#2087]
##### 版本号：
1.58

##### 问题描述：
前端图片url被拼接上了src="/jmreport/img/“https://zhcl-zskt.oss-cn-shanghai.aliyuncs.com/sign/2023/09/25/4d55d45346824a85a0b5308144ebafe1.png“" 额外的引号字符，导致预览失败

##### 错误日志&截图：
![1697769796414](https://github.com/jeecgboot/JimuReport/assets/148410067/0a9bf235-6622-4f97-aef2-efaaf0829385)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
怎么用的，详细说明

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
