### ISSUE TITLE
有问题需求帮助

### ISSUE THREAD

**Issue by MiaoWei814** [jeecgboot/JimuReport#2088]
##### 问题描述：
我发现我页面上访问不管有没有token依然可以访问,但是我在代码里实现了 JmReportTokenServiceI这个,并在idea里打了debug断点,发现都没有进去 所以我想寻求帮助, 自己也是迷茫了一个星期了 望回复

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
未按格式要求发帖，会被直接删掉
