### ISSUE TITLE
右侧求和，并合并单元格

### ISSUE THREAD

**Issue by Userluckytian** [jeecgboot/JimuReport#2089]
##### 版本号：
1.6.4

##### 问题描述：
是否可以实现 ： 右侧求和 并合并单元格的功能，具体效果如：https://github.com/youseries/ureport/issues/562#issuecomment-1204689561

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/66506773/528c70db-fb48-4e89-aa5e-1290f190917a)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
