### ISSUE TITLE
点击测试连接数据库一直提示需要角色权限

### ISSUE THREAD

**Issue by qwerqwer1234234** [jeecgboot/JimuReport#2091]
##### 版本号：
1.6.4

##### 问题描述：
点击测试连接数据库一直提示需要角色权限

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/100072068/ef1cf997-0f3d-4cca-9af9-3e45133f35a6)
![image](https://github.com/jeecgboot/JimuReport/assets/100072068/41c6ed4d-4df5-4b28-889c-c22a859e6ace)

##### 重现步骤：
![image](https://github.com/jeecgboot/JimuReport/assets/100072068/9a0e8942-00e9-496f-ace3-fdaefe785921)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
1、增加低代码开发模式配置 jeecg.jmreport.firewall.lowCodeMode： prod
  发布模式下会关闭所有报表设计相关接口，普通用户只能访问报表不能做任何报表修改，彻底解决被攻击风险
  为了便于线上报表临时维护，用户是“admin”，或者拥有角色 "admin"、"lowdeveloper" 的用户，可以拥有设计权限

https://help.jeecg.com/jimureport/prodSafe.html
