### ISSUE TITLE
多数据对比折线图异常

### ISSUE THREAD

**Issue by xiaoyaofawai** [jeecgboot/JimuReport#2092]
##### 问题描述：
多数据对比折线图异常,展示不了

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/12688996/acad8c1a-dfd1-4fe2-b213-2a0a24782e6a)

##### 重现步骤：
多数据对比折线图，选择SQL数据集，运行、预览都有问题

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
提供测试数据

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
