### ISSUE TITLE
报表配置导出没有导出数据源信息？

### ISSUE THREAD

**Issue by xi-xi-jun** [jeecgboot/JimuReport#2094]
##### 问题描述：
导出报表配置结构，也就是表jimu_report_data_source中的数据没有随着报表结构的导出。
查看导出的数据对比库发现，只涉及：
jimu_report、jimu_report_db、jimu_report_db_field、jimu_report_db_param、jimu_dict、jimu_dict_item

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/113566654/613b13e6-de9b-43e8-aabe-3420b9315dcc)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
是的，这个信息太敏感了
