### ISSUE TITLE
报表配置导入导出前后编码不一致

### ISSUE THREAD

**Issue by xi-xi-jun** [jeecgboot/JimuReport#2095]
##### 问题描述：
对比报表配置导入导出前后的编码发现不一致，如截图所示：

##### 错误日志&截图：
导出前原数据：
![image](https://github.com/jeecgboot/JimuReport/assets/113566654/c3d1e64f-78c2-4937-9b76-c919003e93c3)
导入后数据：
![image](https://github.com/jeecgboot/JimuReport/assets/113566654/0ce60ed9-bb1f-4650-aeb2-171c1d393027)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
说明，你倒错了

**Comment by zhangdaiscott** [comment]
数据集的code变了，不影响使用就没问题

**Comment by xi-xi-jun** [comment]
好吧，我还以这导出的Bug，原来是有意为之。不过如果报表里面配置了多个数据源，这样就有多个编码。在编辑界面涉及到的编码越多，导入之后就失去了原有的可读性了。

**Comment by zhangdaiscott** [comment]
导出、导入，支持生成新的报表，所以编码需要变。如果你是要覆盖功能，我们后期可以考虑加个导入模式

**Comment by xi-xi-jun** [comment]
我用示例进行补充，假设现在配置了两个数据源，两个数据源中的编码都会被重置。但此时，编辑界面的编码不会被重置。会导致预览界面为空。
![image](https://github.com/jeecgboot/JimuReport/assets/113566654/996c39c0-2e77-47b2-87d4-3f4f892cd27c)

**Comment by zhangdaiscott** [comment]
你的意思，报表里面的key   没变？

**Comment by xi-xi-jun** [comment]
是的，如果是一个数据集的话会变，多个的话就不变了。

**Comment by zhangdaiscott** [comment]
刚测，是变的

**Comment by xi-xi-jun** [comment]
非常感谢，我发现我的问题了
