### ISSUE TITLE
控制台输出太多

### ISSUE THREAD

**Issue by wuzhonghao1** [jeecgboot/JimuReport#2096]
##### 问题描述：
能不能提供一个参数来控制一下是否显示iframe引用时的控制台输出，有点影响开发人员进行调试，或者将积木报表的控制台输出console.group一下。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
版本号？

**Comment by wuzhonghao1** [comment]
1.4.2

**Comment by zhangdaiscott** [comment]
升级到最新版即可
