### ISSUE TITLE
行号优化问题

### ISSUE THREAD

**Issue by wenhongjun** [jeecgboot/JimuReport#2098]
##### 版本号：
1.6.4

##### 问题描述：

行号后一列设置了分组后行号不能跟着后面的分组内容来生成，希望能优化
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/40422721/27f05a90-fcb7-49d5-8f3a-51d23b3d6225)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 sq

**Comment by hoperunChen** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/13013558/d7dee930-f8c3-4d9c-8f3f-36a43c5717aa)
![image](https://github.com/jeecgboot/JimuReport/assets/13013558/750a116b-3e74-4451-bb0e-5106b698c627)
未复现该问题，烦请提供您的设计模版和模拟数据

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
