### ISSUE TITLE
积木报表不支持SpringBoot 3.x

### ISSUE THREAD

**Issue by alieismy** [jeecgboot/JimuReport#2099]
##### 错误日志&截图：
  - 在 SpringBoot 3.x环境集成积木报表1.6.4，会报错。

#### 友情提示（为了提高issue处理效率）：
  - 请问积木报表什么时候能支持SpringBoot 3.x，目前所用框架都是SpringBoot 3.x以上，麻烦给出一个时间周期，谢谢。

**Comment by zhangdaiscott** [comment]
规划中
