### ISSUE TITLE
jdk17 spring boot 2.7.3

### ISSUE THREAD

**Issue by larryyoung60** [jeecgboot/JimuReport#2100]
##### 版本号：

积木报表1.6.4
##### 问题描述：
请问积木表支持jdk17吗，我用的是jdk17 ,spring boot 2.7.3
获取数据都没有问题，保存数据提示成功但是没有保存到数据库
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/JimuReport/issues/2099

**Comment by lvdandan16** [comment]
jdk17不支持
