### ISSUE TITLE
单元格内容不能手动换行

### ISSUE THREAD

**Issue by liangGitHu** [jeecgboot/JimuReport#2102]
##### 版本号：
最新版

##### 问题描述：
报表的头信息列表字段需要可以手动换行调整格式，而不是自动换行

##### 错误日志&截图：
![ba4af00d_1212688](https://github.com/jeecgboot/JimuReport/assets/25289627/58964264-c135-4b7a-8987-439108d347b0)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
目前还不支持，归集到#138

**Comment by jeecgos** [comment]
已支持，

![Image](https://github.com/user-attachments/assets/8c0af23a-aa6a-43cd-a4ae-61e43cbb8379)
