### ISSUE TITLE
数据源加密

### ISSUE THREAD

**Issue by Yxw521** [jeecgboot/JimuReport#2103]
##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/76502207/d703027b-7f97-4b67-975e-8d84e0708571)

**Comment by zhangdaiscott** [comment]
你这个是编辑页面，密码肯定解密了，数据库里面密码是加密的

**Comment by Yxw521** [comment]
接口扫描会判断严重泄密，这个能优化下吗

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/jimureport/prodSafe.html
