### ISSUE TITLE
固定表头和首列这个能支持吗

### ISSUE THREAD

**Issue by rw12306** [jeecgboot/JimuReport#2104]
##### 问题描述：
固定表头和首列这个能支持吗？计划好久支持一下呢。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
预览页面不支持固定表头和首列
打印时支持固定表头表尾，仅限打印 参考文档：https://help.jeecg.com/jimureport/printNew/gaugeOutfit.html
