### ISSUE TITLE
使用compute后展示成科学计数法问题

### ISSUE THREAD

**Issue by dengyingfeng2022** [jeecgboot/JimuReport#2105]
##### 问题描述：
使用数据集的compute函数时若计算结果较大时，会被转成科学计数法，若单元格是数字格式就只会展示陈整数部分
如结果是1.27353E+7   就会直接展示成1  ，如果单元格是正常才会展示成1.27353E+7 ；请问是否可以不使用科学计数法直接展示成
12335300呢

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/105050463/d985399f-92a7-4ef8-a0ec-113493d215ad)
![image](https://github.com/jeecgboot/JimuReport/assets/105050463/05cef5c1-c969-4390-88c6-a0615a0d58ef)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by dengyingfeng2022** [comment]
版本V1.5.6

**Comment by zhangdaiscott** [comment]
遇到问题请先升级到最新版
