### ISSUE TITLE
sql server存储过程用报表字段明细的查询条件时保错

### ISSUE THREAD

**Issue by 12wmy** [jeecgboot/JimuReport#2106]
在积木报表中用存储过程出报表时，给字段添加查询条件后使用时报错
![微信图片_20231030174737](https://github.com/jeecgboot/JimuReport/assets/149373744/af529885-4152-424b-a08b-7dd6631e84d0)
![微信图片_20231030174743](https://github.com/jeecgboot/JimuReport/assets/149373744/9cc296e1-bbe9-45ca-bdf0-623a04230c6e)

**Comment by lvdandan16** [comment]
存储过程怎么写的，麻烦贴上来

**Comment by 12wmy** [comment]
USE [blueape-mes]
GO
/****** Object:  StoredProcedure [dbo].[BZ_ZLZB]    Script Date: 2023/10/30 9:30:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[BZ_ZLZB] 
          @DATE01 VARCHAR(10),
          @DATE02 VARCHAR(10),
		  @number varchar(50),
		  @inv varchar(50)
as
begin


  
 select *
 into #qc
 from BZ_QC
 where 质检日期>=@DATE01 and 质检日期<=@DATE02 and 成型工号 like '%'+isnull(@number,'')+'%' and 产品 like '%'+isnull(@inv,'')+'%'
 
 select *
 into #qx
 from BZ_QCQX
 where 质检日期>=@DATE01 and 质检日期<=@DATE02 and 成型工号 like '%'+isnull(@number,'')+'%' and 产品 like '%'+isnull(@inv,'')+'%'

 --drop table if exists #HZ
 select 产品,产品类别,颜色,窑炉,成型工号,'等级' 类型,'11'AS 等级ID,等级 等级缺陷,count(*) 数量
 into #HZ
 from #qc
 group by 产品,产品类别,颜色,窑炉,成型工号,等级,等级ID,产品类别
 union all
 select 产品,产品类别,颜色,窑炉,成型工号,'汇总' 类型,'0','成检总数' 等级缺陷,count(*) 数量
 from #qc
 group by 产品,产品类别,颜色,窑炉,成型工号,产品类别
 union all
 select 产品,产品类别,颜色,窑炉,成型工号,缺陷类别 类型,缺陷类别id,缺陷名称 等级缺陷,count(*) 数量
 from #qx
 group by 产品,产品类别,颜色,窑炉,成型工号,缺陷类别,缺陷名称,缺陷类别id,产品类别
 union all
 select 产品,产品类别,颜色,窑炉,成型工号,'汇总' 类型,'1','缺陷总数' 等级缺陷,count(*) 数量
 from #qx
 group by 产品,产品类别,颜色,窑炉,成型工号,产品类别
 union all
  select 产品,产品类别,颜色,窑炉,成型工号,缺陷类别 类型,'12','缺陷汇总' 等级缺陷,count(*) 数量
 from #qx
 group by 产品,产品类别,颜色,窑炉,成型工号,产品类别,	缺陷类别

 select #HZ.*,cjnum as cj from #hz
 inner join (
 select 产品,颜色,窑炉,成型工号,产品类别,count(*)cjnum
 from #qc
 group by 产品,颜色,窑炉,成型工号,产品类别
 )b on #HZ.产品=b.产品 and #HZ.成型工号=b.成型工号 and isnull(#hz.窑炉,'')=isnull(b.窑炉,'')
  order by  等级ID,等级缺陷,窑炉,产品,产品类别,成型工号
 end

**Comment by 12wmy** [comment]
USE [blueape-mes]
GO
/****** Object:  StoredProcedure [dbo].[BZ_ZLZB]    Script Date: 2023/10/30 9:30:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[BZ_ZLZB] 
          @DATE01 VARCHAR(10),
          @DATE02 VARCHAR(10)
	
as
begin


  
 select *
 into #qc
 from BZ_QC
 where 质检日期>=@DATE01 and 质检日期<=@DATE02
 
 select *
 into #qx
 from BZ_QCQX
 where 质检日期>=@DATE01 and 质检日期<=@DATE02 

 --drop table if exists #HZ
 select 产品,产品类别,颜色,窑炉,成型工号,'等级' 类型,'11'AS 等级ID,等级 等级缺陷,count(*) 数量
 into #HZ
 from #qc
 group by 产品,产品类别,颜色,窑炉,成型工号,等级,等级ID,产品类别
 union all
 select 产品,产品类别,颜色,窑炉,成型工号,'汇总' 类型,'0','成检总数' 等级缺陷,count(*) 数量
 from #qc
 group by 产品,产品类别,颜色,窑炉,成型工号,产品类别
 union all
 select 产品,产品类别,颜色,窑炉,成型工号,缺陷类别 类型,缺陷类别id,缺陷名称 等级缺陷,count(*) 数量
 from #qx
 group by 产品,产品类别,颜色,窑炉,成型工号,缺陷类别,缺陷名称,缺陷类别id,产品类别
 union all
 select 产品,产品类别,颜色,窑炉,成型工号,'汇总' 类型,'1','缺陷总数' 等级缺陷,count(*) 数量
 from #qx
 group by 产品,产品类别,颜色,窑炉,成型工号,产品类别
 union all
  select 产品,产品类别,颜色,窑炉,成型工号,缺陷类别 类型,'12','缺陷汇总' 等级缺陷,count(*) 数量
 from #qx
 group by 产品,产品类别,颜色,窑炉,成型工号,产品类别,	缺陷类别

 select #HZ.*,cjnum as cj from #hz
 inner join (
 select 产品,颜色,窑炉,成型工号,产品类别,count(*)cjnum
 from #qc
 group by 产品,颜色,窑炉,成型工号,产品类别
 )b on #HZ.产品=b.产品 and #HZ.成型工号=b.成型工号 and isnull(#hz.窑炉,'')=isnull(b.窑炉,'')
  order by  等级ID,等级缺陷,窑炉,产品,产品类别,成型工号
 end

**Comment by 12wmy** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/149373744/337ddb09-2eca-4e54-98bf-eba8b6741018)

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
目前不支持字段查询传参，支持报表参数传参的方式进行查询
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/f9321b26-be7c-4929-8e61-ed85ea994c2c)
