### ISSUE TITLE
存在sql注入

### ISSUE THREAD

**Issue by Yxw521** [jeecgboot/JimuReport#2108]
版本号：1.6.4

问题描述：
存在sql注入

错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/76502207/1ef97f27-fabd-40de-914b-8c716d937ec7)

**Comment by zhangdaiscott** [comment]
配置界面截图和完整的sql贴一下

**Comment by Yxw521** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/76502207/f241270b-2110-4965-b569-bc249b16153c)

**Comment by Yxw521** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/76502207/3125d317-6ee0-4315-a7b6-f422e08e48d6)

**Comment by zhangdaiscott** [comment]
去掉注释
![image](https://github.com/jeecgboot/JimuReport/assets/3162115/1df0c3c3-3c80-435d-ab9e-2bc25dcc2c1d)
