### ISSUE TITLE
积木报表后台数据源能独立于spring boot的数据源吗？

### ISSUE THREAD

**Issue by larryyoung60** [jeecgboot/JimuReport#2110]
##### 版本号：
1.6.4

##### 问题描述：
积木报表后台数据源配置和我的spring boot数据源配置冲突，我的spring boot 的数据源auto-commit=false而积木数据源配置auto-commit=true,所以问一下积木能单独配置其他的数据源吗？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/3162115/c2d5ad1b-3d3f-40a2-95a5-f09dfb662833)

https://help.jeecg.com/jimureport/config/yaml.html
