### ISSUE TITLE
集成后列表页面js404

### ISSUE THREAD

**Issue by wangrui-2020** [jeecgboot/JimuReport#2111]
##### 错误日志&截图：
![3511698738433_ pic](https://github.com/jeecgboot/JimuReport/assets/64881302/829d54c7-928a-49fe-ae35-1ccf732023ef)

##### 重现步骤：
按照快速集成后访问地址： {项目前缀}/jmreport/list 显示异常，前端js404

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
看文档，静态资源加载配置有问题
