### ISSUE TITLE
已有的项目集成进去无法启动

### ISSUE THREAD

**Issue by 3043871668** [jeecgboot/JimuReport#2112]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/73048063/59bdbc3a-ada0-45b3-ae7b-c2d51bdf9f7a)
![image](https://github.com/jeecgboot/JimuReport/assets/73048063/944f6b54-26f9-4e33-acd5-7aba40c08b29)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你的项目是什么架构，具体说明

**Comment by 3043871668** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月31日(星期二) 晚上6:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 已有的项目集成进去无法启动 (Issue #2112)





 
你的项目是什么架构，具体说明
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;










用的是spring boot架构
