### ISSUE TITLE
如何实现动态表名

### ISSUE THREAD

**Issue by xufuchaoxfc** [jeecgboot/JimuReport#2114]
##### 版本号：1.6.4
oracle 19c

##### 问题描述：

sql数据集
select F_Province 省份, count(*) 数量
from STO_SETTLEMENT_DETAILS_202310
group by F_Province

其中表 STO_SETTLEMENT_DETAILS_202310 应如何实现为动态表名

**Comment by zhangdaiscott** [comment]
不支持，你这种写法会有sql注入风险
