### ISSUE TITLE
多数据对比折线图问题

### ISSUE THREAD

**Issue by speckle23** [jeecgboot/JimuReport#2115]
##### 版本号：
1.5.6

##### 问题描述：
多数据对比折线图问题无法支持左右Y轴，导致若是不同数量级的数据无法对比，使用不便

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/54102334/940fbbb6-ff7d-4188-8a6b-5a030d264cfe)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持  收集到 #138

**Comment by jeecgos** [comment]
已支持
