### ISSUE TITLE
单元格表达式运算问题

### ISSUE THREAD

**Issue by speckle23** [jeecgboot/JimuReport#2116]
##### 版本号：
1.6.4

##### 问题描述：
除数为空或null时，也有值

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/54102334/feae14da-bf67-45b4-b76a-71385581f54b)
如表达式ysxbs/ysignedCount当ysxbs为空或null时该单元格计算结果是为0，预期是空
![image](https://github.com/jeecgboot/JimuReport/assets/54102334/835a08c3-5e9f-4c68-b752-41557f90fd95)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
目前就是这样设计的
