### ISSUE TITLE
代码报错

### ISSUE THREAD

**Issue by speckle23** [jeecgboot/JimuReport#2117]
##### 版本号：
1.6.4

##### 问题描述：
代码报错
![image](https://github.com/jeecgboot/JimuReport/assets/54102334/ec19bb6f-c0ef-4093-81d8-13829ecacb5b)

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/54102334/a5e8cbc5-d690-44ed-86f3-e9438f253cb0)
这个类的判断条件是不是有问题，但var0是""时会报错，不会进入到else

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请详细描述，什么功能？
或者在积木官网做个示例

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
