### ISSUE TITLE
积木报表无法新增报表

### ISSUE THREAD

**Issue by 3043871668** [jeecgboot/JimuReport#2119]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/73048063/a2d52253-07c0-4a47-ae07-45e2dec3e933)
![image](https://github.com/jeecgboot/JimuReport/assets/73048063/047c6d0e-f0e0-4ca6-a5b0-d8916c6a9d4f)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请升级新版本
