### ISSUE TITLE
spring boot 中的数据源hikari: auto-commit: false造成的积木报表不能保存

### ISSUE THREAD

**Issue by larryyoung60** [jeecgboot/JimuReport#2120]
##### 版本号：
1.6.4

##### 问题描述：
spring boot jpa 的数据源属性  hikari: auto-commit: false则 积木报表保存后提示成功但没有更新到数据库，如果设置为true则成功，但是spring boot 系统事务提交报错，要被折磨死了。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你为什么会出现这样的问题?

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
