### ISSUE TITLE
积木报表传参问题

### ISSUE THREAD

**Issue by zhuyn2015** [jeecgboot/JimuReport#2121]
![微信截图_20231102101942](https://github.com/jeecgboot/JimuReport/assets/11956900/a5788c1d-caa1-49ad-bbff-b7ac17d61caf)
##### 版本号：
v1.6.4

##### 问题描述：
配置了一个打印报表，通过url传参数时不生效。配置如下
sql数据源 配置报表sql: select  id,customer_name,customer_full_name,create_time,dept_id  from cp_customer where id=${id}
采用单数据模式，在参数id 增加默认值 2。
打印界面直接显示id,name几个数据。可以正常访问。只是分享的链接不能传参数。不知道原因。

##### 错误日志&截图：
分享链接http://localhost:8210/jmreport/shareView/879171820132679680?id=5 增加的参数依然显示的默认为2的数据
[http://zhi-xiang.oss-cn-qingdao.aliyuncs.com/唛头/微信截图_20231102102203.png]

##### 重现步骤：
![微信截图_20231102102030](https://github.com/jeecgboot/JimuReport/assets/11956900/12341647-f855-4e34-844d-baadaefb76f8)
![微信截图_20231102102059](https://github.com/jeecgboot/JimuReport/assets/11956900/a0614165-964b-45ca-8eb4-4f3c002590ed)
![微信截图_20231102102128](https://github.com/jeecgboot/JimuReport/assets/11956900/cb29a3dc-5ef5-4905-8382-7d0823ef0dcc)
![微信截图_20231102102203](https://github.com/jeecgboot/JimuReport/assets/11956900/8f926356-ae6a-402d-be15-ab1bbe2f8a84)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/54099258/c6533c65-7fc7-456d-a223-c2674e80a07a)
未复现此问题，可在积木官网做个示例，我们复现一下

**Comment by zhuyn2015** [comment]
预览地址:  https://bootapi.jeecg.com/jmreport/shareView/879148828992032768?id=370
这个是在官网上配的，帮忙看看也是同样的问题

**Comment by lvdandan16** [comment]
参考文档：
![Uploading image.png…]()

https://help.jeecg.com/jimureport/report/query.html
