### ISSUE TITLE
API数据集，多条数据情况下，预览时数据值 重复

### ISSUE THREAD

**Issue by localhosttomcat** [jeecgboot/JimuReport#2123]
##### 版本号：
官方demo教程下载

##### 问题描述：
API数据集，多条数据情况下，只显示了一条

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/33717569/b87949ff-59b0-4304-8ab1-04a28cc218f3)

![image](https://github.com/jeecgboot/JimuReport/assets/33717569/f6dbcffd-052d-4210-a19d-33f84547b2bb)

![image](https://github.com/jeecgboot/JimuReport/assets/33717569/0c898313-61ab-4f1e-9f72-a3545abd86cc)

##### 重现步骤：

1、新建报表
2、创建API数据集
3、设置模板 ${sm.XXX}
4、预览只有一条数据

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
数据集怎么配置的，截图说明

**Comment by lvdandan16** [comment]
多条数据使用#{}，并且如果是多条数据，此种设计需要使用循环块
