### ISSUE TITLE
导出pdf出现一页不会占满

### ISSUE THREAD

**Issue by LiuXiaoBo1701** [jeecgboot/JimuReport#2125]
##### 版本号：
1.6.4

##### 问题描述：
预览页面点击导出pdf出现一页不会占满

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/50015834/2d104a70-6550-4d95-b9a8-64009ae4bedb)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
提供下设计数据

**Comment by LiuXiaoBo1701** [comment]
设计页面
![image](https://github.com/jeecgboot/JimuReport/assets/50015834/ced60a29-effc-4a54-830b-3693451498a9)
数据
[data.json](https://github.com/jeecgboot/JimuReport/files/13255744/data.json)

**Comment by LiuXiaoBo1701** [comment]
还有一个问题就是咱们有没有导出pdf的接口，因为每次导出都是要先预览

**Comment by zhangdaiscott** [comment]
后面考虑出
