### ISSUE TITLE
最新版新建不了

### ISSUE THREAD

**Issue by 798076849** [jeecgboot/JimuReport#2126]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/130627334/bd62907b-e87e-4854-b378-dbe5793fffdd)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你需要集成权限
https://help.jeecg.com/jimureport/config/token.html
