### ISSUE TITLE
JimuReport 主数据源如何配置和使用？jimureport单独使用只保存报表

### ISSUE THREAD

**Issue by lqxmmmm** [jeecgboot/JimuReport#2129]
##### 问题描述：
JimuReport 主数据源如何配置和使用？jimureport单独使用只保存报表
spring:
  #数据库
  datasource:
    url: jdbc:mysql://localhost:3306/stone?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 12322321
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      #设置数据库超时时间
      connection-timeout: 100000
      #池中维护的最小连接数:5
      minimum-idle: 5
      #池中最大连接数
      maximum-pool-size: 15
      #连接最长闲置时间
      idle-timeout: 30000
      #池中连接最长生命周期
      max-lifetime: 30000

#持久层框架
minidao:
  base-package: org.jeecg.modules.jmreport.*
jeecg:
  minidao-datasource:
    jdbc-url: jdbc:mysql://localhost:3306/jimureport?autoReconnect=true&failOverReadOnly=false&maxReconnects=1000&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 12322321
    driver-class-name: com.mysql.cj.jdbc.Driver

##### 错误日志&截图：
直接输入SQL时，认的是jimureport，而不是 stone

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
什么意思

**Comment by lqxmmmm** [comment]
就是我想用SQL做数据集时，连接的是jdbc:mysql://localhost:3306/stone 这个数据源，:mysql://localhost:3306/jimureport 这个只做报表服务用

**Comment by lqxmmmm** [comment]
要如何配置这个主数据源？

**Comment by lvdandan16** [comment]
参考文档：https://help.jeecg.com/jimureport/rumen/sql.html

**Comment by zhangdaiscott** [comment]
通过这个参数来指定
![image](https://github.com/jeecgboot/JimuReport/assets/3162115/8af7d026-d9ff-4a36-93ad-5121c53fe549)
