### ISSUE TITLE
Could not initialize class org.jeecg.modules.jmreport.desreport.util.n

### ISSUE THREAD

**Issue by liuxin1221** [jeecgboot/JimuReport#2131]
##### 版本号：
        <dependency>
            <groupId>org.jeecgframework.jimureport</groupId>
            <artifactId>jimureport-spring-boot-starter</artifactId>
            <version>1.5.8</version>
        </dependency>

##### 问题描述：
请求api 报错java.lang.NoClassDefFoundError: Could not initialize class org.jeecg.modules.jmreport.desreport.util.n

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/52476412/9c993122-353a-44c5-8bfb-69d41c207d3c)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你的项目架构说明

**Comment by liuxin1221** [comment]
> 你的项目架构说明

springBoot  hibernate

**Comment by zhangdaiscott** [comment]
具体

**Comment by liuxin1221** [comment]
springBoot   springmvc    hibernate     sqlserver
