### ISSUE TITLE
关于积木报表嵌套循环打印，设置循环快，循环快内部查询数据的API数据源,没有查询数据并渲染

### ISSUE THREAD

**Issue by doolra** [jeecgboot/JimuReport#2133]
##### 问题描述：
关于积木报表嵌套循环打印，设置循环块，循环块内部查询列表数据的API数据源,没有查询数据并渲染

##### 错误日志&截图：
<img width="920" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/39663146/04ed4204-a164-4080-9557-8638cce2afe4">

<img width="1457" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/39663146/401e91f0-0a8e-4b28-bb05-34e2ec2125d1">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
循环块不支持主子表用法
