### ISSUE TITLE
从1.5.2升级1.6.4版本之后，数据字典code中使用数据集的值作为参数值，参数不生效

### ISSUE THREAD

**Issue by wuke001** [jeecgboot/JimuReport#2135]
##### 版本号：
1.6.4

##### 问题描述：
从1.5.2升级1.6.4版本之后，数据字典code中使用数据集的值作为参数值，参数不生效

##### 错误日志&截图：
无法查询到字典code中的sql对应的数据。原因是无法获取到${year__set_year}，year数据集中的set_year的值

##### 重现步骤：
数据字典code中的sql：
SELECT BATCH_ID AS "VALUE",BATCH_NAME AS "TEXT" FROM ISSUE_BATCH WHERE BATCH_YEAR='${year__set_year}' ORDER BY BATCH_ID

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
1.5.2应该也不支持吧，字典参数目前只支持系统变量参数

**Comment by wuke001** [comment]
1.5.2版本的字典code中的sql：SELECT BATCH_ID AS "VALUE",BATCH_NAME AS "TEXT" FROM ISSUE_BATCH WHERE BATCH_YEAR='${year__set_year}' ORDER BY BATCH_ID 。year数据集中的set_year字段是一个下拉单选的查询条件，这个数据字典的结果可以通过获取year数据集中的set_year条件选中的值，而动态改变。1.6.4就不支持了。

**Comment by zhangdaiscott** [comment]
发个新issue

**Comment by wuke001** [comment]
好的
