### ISSUE TITLE
报表纵向小计，预览打印时，第二页的第一列重复问题

### ISSUE THREAD

**Issue by Heidi669** [jeecgboot/JimuReport#2136]
版本号：1.6.4

问题描述：
 报表纵向分组小计，预览时，显示正确，但是点击打印，第二页的第一列就会重复显示

错误日志&截图：
正常预览显示：
![企业微信截图_16990026215375](https://github.com/jeecgboot/JimuReport/assets/38720981/3f52539b-fe44-4b45-a751-3a6d81397fa6)

点击打印：第二页第一列重复
![企业微信截图_169900168775](https://github.com/jeecgboot/JimuReport/assets/38720981/329242c3-efc3-4dae-bc52-8573e5536f87)

重现步骤：
1、设置分组
![image](https://github.com/jeecgboot/JimuReport/assets/38720981/e1003950-d9d6-49a2-8e12-730127ddb7f3)
2、求和

![企业微信截图_1699002867829](https://github.com/jeecgboot/JimuReport/assets/38720981/a7bb34d6-f8c0-4ba1-a61d-a98b5aa1e37a)

按照上述步骤之后，显示出来的效果，就是如此！

导出报表配置如下：
[盘点库房实时库存.json](https://github.com/jeecgboot/JimuReport/files/13263473/default.json)

**Comment by lvdandan16** [comment]
与#2124问题重复 https://github.com/jeecgboot/JimuReport/issues/2124
关闭此任务
