### ISSUE TITLE
分享功能报错jimu_report_share 这张表报错 提示preview_lock_status字段不存在

### ISSUE THREAD

**Issue by 1415181920** [jeecgboot/JimuReport#2137]
##### 版本号：

1.64
##### 问题描述：

分享功能报错jimu_report_share 这张表报错 提示preview_lock_status字段不存在
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/63941804/d9b1a8f9-6604-4637-afe2-6a60dbc50b05)
![image](https://github.com/jeecgboot/JimuReport/assets/63941804/ad7dae3d-085c-4b1b-9946-661c8540444d)
![image](https://github.com/jeecgboot/JimuReport/assets/63941804/0be6ac3e-d3d7-4434-ad46-0a14c884c8a0)
![image](https://github.com/jeecgboot/JimuReport/assets/63941804/6e171d1b-b727-4bad-adf0-f8774f90b05c)

##### 重现步骤：
点击分享按钮报错 数据库是否没更新

**Comment by lvdandan16** [comment]
升级SQL：http://bi.qiaoqiaoyun.com/doc/log
