### ISSUE TITLE
打印固定表头

### ISSUE THREAD

**Issue by qin-xing** [jeecgboot/JimuReport#2138]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/59475558/83434792-d1c3-4d24-9a87-2abc04e8a385)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
没加这功能

**Comment by lvdandan16** [comment]
鼠标下拉，目前固定表头表尾只支持打印
