### ISSUE TITLE
动态横向分组合计问题

### ISSUE THREAD

**Issue by superman4808** [jeecgboot/JimuReport#2139]
##### 版本号：
V1.6.4

##### 问题描述：
动态列最后放一个固定字段“合计”，需要对“合计”列求和，但最后合计的结果并非此列

##### 错误日志&截图：

![jm合计](https://github.com/jeecgboot/JimuReport/assets/121927607/ae5a25a9-64c9-42e9-b861-4b688e753de9)

##### 重现步骤：

![列和](https://github.com/jeecgboot/JimuReport/assets/121927607/b5df21f7-f03d-4c2d-94a6-f3ace1e681b1)

![列和后台](https://github.com/jeecgboot/JimuReport/assets/121927607/a5864bec-eeb1-4a9a-8005-f8f066a0a2f2)

导出报表配置：
[报表配置.zip](https://github.com/jeecgboot/JimuReport/files/13290979/default.zip)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
目前暂不支持横向分组合计
