### ISSUE TITLE
报表查询、上一页、下一页、打印、导出等等待时间较长

### ISSUE THREAD

**Issue by 18991391792** [jeecgboot/JimuReport#2141]
##### 版本号：
1.6.3

##### 问题描述：
报表查询、上一页、下一页、打印、导出 消耗时间都在8秒以上。

##### 错误日志&截图：
![2](https://github.com/jeecgboot/JimuReport/assets/54569940/1b57cf57-c8f8-4175-a65f-03047ac63eff)

![1](https://github.com/jeecgboot/JimuReport/assets/54569940/e78e132a-b0ae-488f-853e-5dfa3b31ad8d)
![image](https://github.com/jeecgboot/JimuReport/assets/54569940/e0a1d413-58dc-43b1-998d-4b7b0f1e2ff9)

##### 重现步骤：

我尝试超过了新建8次报表，数据集SQL也相对简单，都存在效率不高的情况。

感谢解答和解决。

**Comment by lvdandan16** [comment]
是你本地或者服务器问题吧，目前未发现消耗时间在8秒以上，或者可以在积木官网做个示例，我们复现一下

**Comment by 18991391792** [comment]
感谢回答。我是从这里下载的 Windows 免安装版本。
![image](https://github.com/jeecgboot/JimuReport/assets/54569940/6e89dbf1-68fa-40ac-bfcb-67fd09271bd3)
下载地址：
https://pan.baidu.com/s/1z9VmMz4HCc7GMVbzugetLQ?pwd=xafr#list/path=%2F
换了三台电脑都是一样的速度...
我在官网的示例上找到了和我做的相似的报表，展示格式如下：
![image](https://github.com/jeecgboot/JimuReport/assets/54569940/7fc20a79-d2fb-4495-9b0d-b656238c7046)
打开速度也要10秒钟了。

**Comment by zhangdaiscott** [comment]
看看是不是你数据库查询慢

**Comment by 18991391792** [comment]
一般为SQL问题
