### ISSUE TITLE
关于积木报表，list里面的对象的属性都是空值会报空指针，这个可以解决吗

### ISSUE THREAD

**Issue by doolra** [jeecgboot/JimuReport#2142]
##### 问题描述：
list里面的对象，对象的属性值都是空值，报空指针

##### 错误日志&截图：
<img width="1065" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/39663146/68ec8fea-5279-4703-a2b5-c648cbf8957d">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
什么功能和操作，请详细描述

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
