### ISSUE TITLE
打印预览的时候，多出表头

### ISSUE THREAD

**Issue by doolra** [jeecgboot/JimuReport#2143]
##### 问题描述：
固定表头，循环数据，分组，最后打印预览的时候多出一页表头，其实已经没有数据了，这是怎么回事呢

##### 错误日志&截图：
<img width="1013" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/39663146/5b3ee060-fb8c-469d-9005-74dfa227a213">
<img width="1029" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/39663146/49915a0c-6cb7-4b25-8707-0ae1b0f72d07">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请在积木官网做个示例，我们复现一下

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
