### ISSUE TITLE
表格插入图片时位置调整问题

### ISSUE THREAD

**Issue by shlshlshl** [jeecgboot/JimuReport#2145]
##### 版本号：
<dependency>
	<groupId>org.jeecgframework.jimureport</groupId>
	<artifactId>jimureport-spring-boot-starter</artifactId>
	<version>1.4.2</version>
</dependency>

##### 问题描述：
你好。我在单元格中插入图片时，使用图片偏移量设置位置使其居中。在使用html打印时与模版预览时的图片显示位置不一致。

##### 错误日志&截图：
预览时图片的位置在表格的居中位置：
![image](https://github.com/jeecgboot/JimuReport/assets/51730971/88918189-25f8-4508-90fd-bbb33df95188)

打印时，图片被默认偏移到了表格的最左边：
![image](https://github.com/jeecgboot/JimuReport/assets/51730971/a7978e4e-298c-4a05-99ea-7728b83cd856)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级新版本试一下

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
