### ISSUE TITLE
单元格出现负数时, 求和函数失效

### ISSUE THREAD

**Issue by ThisLoner** [jeecgboot/JimuReport#2146]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/40937634/fa7748eb-bdba-42e5-a4fa-34dfffd9b2b4)
![image](https://github.com/jeecgboot/JimuReport/assets/40937634/f35c659e-62e6-4562-b8cf-c0fe7123a6ff)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
问题未复现，你数据库数据是怎样的，后台有没有报错。请导出报表配置并提供数据
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/e8e9917a-67ce-43ff-b3bf-c312220a8c8d)
