### ISSUE TITLE
富文本显示问题

### ISSUE THREAD

**Issue by dreamascene** [jeecgboot/JimuReport#2150]
##### 版本号：
积木：1.6.4
数据库：人大金仓

##### 问题描述：
使用富文本类型显示时，文本格式出现错误。

##### 错误日志&截图：
下图为正常显示格式

![image](https://github.com/jeecgboot/JimuReport/assets/150433296/9673f6c0-f21a-4418-801a-3a2616b086b8)

下图为积木报表预览和打印的显示效果
![image](https://github.com/jeecgboot/JimuReport/assets/150433296/5c8fe64c-3216-4472-9f38-bf6bd083e555)

##### 重现步骤：
通过SQL数据集，实现富文本数据显示。（SQL数据集和API数据集获取数据都试了，格式不能正常显示）

数据库中数据格式：
<p style="text-align: center;"><span style="font-size: 18px;">关于805工房新增1个防爆摄像头的通知</span></p>
<p style="text-align: left;"><span style="font-size: 18px;">信息管理中心:</span></p>
<p style="text-align: left;">&nbsp;</p>
<p style="text-align: left;"><span style="font-size: 18px;">&nbsp; &nbsp; &nbsp; &nbsp; 为满足工艺科研项目 (XX自动称量项目) 研制要求，
公司决定为其在805工房安装1个防爆摄像头。现请你单位根据图纸为该项目配置1个摄像头，并于2023年10月15日前将询价结果和相关预算反馈至发展规划部</span></p>
<p style="text-align: left;">&nbsp;</p>
<p style="text-align: center;"><span style="font-size: 18px;">&nbsp; 发展规划部</span></p>
<p style="text-align: center;"><span style="font-size: 18px;">2023年10月19日</span></p>
<p style="text-align: center;">&nbsp;</p>

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by dreamascene** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/150433296/0edda7ce-3a35-4023-8086-519fb8c17a38)
shuj数据集中没有富文本类型

**Comment by zhangdaiscott** [comment]
下个版本
