### ISSUE TITLE
数据字典code中的SQL，使用数据集的值作为参数值，参数不生效

### ISSUE THREAD

**Issue by wuke001** [jeecgboot/JimuReport#2153]
##### 版本号：
1.6.4

##### 问题描述：
从1.5.2升级1.6.4版本之后，数据字典code中的SQL，使用数据集的值作为参数值，参数不生效

##### 重现步骤：
1.5.2版本的字典code中的sql为：SELECT BATCH_ID AS "VALUE",BATCH_NAME AS "TEXT" FROM ISSUE_BATCH WHERE BATCH_YEAR='${year__set_year}' ORDER BY BATCH_ID 。其中，year数据集中的set_year字段是一个下拉单选的查询条件，这个数据字典的结果可以通过获取year数据集中的set_year条件选中的值改变，而动态改变。1.6.4就不支持了。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 dd
