### ISSUE TITLE
apiBasePath:配置不生效

### ISSUE THREAD

**Issue by jin-770880** [jeecgboot/JimuReport#2155]
##### 问题描述：
项目配置：
#自定义项目前缀
    customPrePath: /group_8002
已生效，效果如下：http://localhost:8888/jeecg-boot/group_8002/jmreport/desreport_/cdn/iview/iview.css

# 自定义API接口的前缀 #{api_base_path}和#{domainURL}的值
    apiBasePath: http://localhost:8888/group_8002/jeecg-boot
未生效，结果如下：http://localhost:8888/jeecg-boot/jmreport/desreport_/cdn/iview/iview.css

##### 错误日志&截图：
http://localhost:8888/jeecg-boot/jmreport/desreport_/cdn/axios/qs.min.js
需要部署到生产环境，因为配置了nginx, 项目前缀需要在/jeecgboot之前携带/group_8002,才能正常访问
##### 重现步骤：
就是apiBasePath:配置不生效

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jin-770880** [comment]
初始化sql，jimu_report_share表缺少preview_lock_status字段

**Comment by lvdandan16** [comment]
参考升级sql：http://bi.qiaoqiaoyun.com/doc/log
