### ISSUE TITLE
多列分组聚合时，单元格排序和渲染都有错误

### ISSUE THREAD

**Issue by phsy** [jeecgboot/JimuReport#2158]
##### 版本号：
1.6.2

##### 问题描述：
同时设置多个连序列分组聚合，当设置图中班组列时，分组会出现错乱，而且数据的顺序也乱了
班组左侧的所有列都设置了分组，且按正序排列，班组这个列设置的也是分组和正序排列

##### 错误日志&截图：
不设置班组列为分组时：
![image](https://github.com/jeecgboot/JimuReport/assets/10345070/3ebfcadd-67dc-4ebc-a2bb-9d192d003cf0)

设置班组列为分组后：
![image](https://github.com/jeecgboot/JimuReport/assets/10345070/405c3b3f-ea47-4a01-86dd-0866022f9dbf)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请导出配置和数据或在积木官网做示例，我们复现一下
