### ISSUE TITLE
需求：增加一个颜色函数，当某个值大于或小于某个临界值时单元格改变字体和背景颜色

### ISSUE THREAD

**Issue by Jalone5186** [jeecgboot/JimuReport#2160]
##### 版本号：
1.6.4

##### 问题描述：
增加一个颜色函数，当某个值大于或小于某个临界值时单元格改变字体和背景颜色

##### 错误日志&截图：
<img width="990" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/50126675/ff24e104-6c7c-468e-9be3-ddc9dc13359c">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Jalone5186** [comment]
我来我试了一下通过case()函数可以实现，但是写起来比较麻烦，如下图：

**Comment by lvdandan16** [comment]
参考文档：https://help.jeecg.com/jimureport/function/condition.html
