### ISSUE TITLE
分组小计中，值为0时，小数位数没有了

### ISSUE THREAD

**Issue by phsy** [jeecgboot/JimuReport#2161]
##### 版本号：
1.6.2

##### 问题描述：
当设置为两位小数时，分组小计值为0时，显示的是0，而不是0.00

##### 错误日志&截图：
支付宝购票金额一栏已经设置了2位小数
![image](https://github.com/jeecgboot/JimuReport/assets/10345070/7b0f7c2e-5e88-4a8d-94d3-be72113e055f)

详细数据行已经是两位小数了，但是分组小计依然是0
![image](https://github.com/jeecgboot/JimuReport/assets/10345070/1deb28c6-9b71-4b50-b155-b7a4f47b2050)

所有的整数也都是这个现象：
![image](https://github.com/jeecgboot/JimuReport/assets/10345070/d5ebdd7a-6d5a-4c11-af3e-bbfc5318e6b5)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 cr

**Comment by lvdandan16** [comment]
已修复，下个版本升级
