### ISSUE TITLE
主子表循环，预览与打印，导出时子数据无法展示

### ISSUE THREAD

**Issue by bqrfkukpgy** [jeecgboot/JimuReport#2163]
##### 版本号：
1.6.4，1.5.6（可以全部版本都有这个问题）

##### 问题描述：
主子表，做循环时，主表数据无问题，能正常展示，但是子表数据，且无法展示，
查看接口发现，子表数据只查询了第一条主表的子数据

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/39266342/ef76830e-c72b-4f67-b0fa-914f3306c1ee)
![image](https://github.com/jeecgboot/JimuReport/assets/39266342/0ea47cf7-6a8f-477d-928a-7ffef5afe03c)
![image](https://github.com/jeecgboot/JimuReport/assets/39266342/b3738837-0e48-4e99-aed5-c4edeac48deb)

##### 重现步骤：
1.配置主子表模板（主表分页，明细表不分页）
2.配置整个模板循环
3.预览，打印，导出时，主表数据无问题，子表数据无法展示

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持主子表循环打印
