### ISSUE TITLE
Posgresql数据库， timestamp 字段 查询，提示timestamp without time zone >= character varying

### ISSUE THREAD

**Issue by jcenc** [jeecgboot/JimuReport#2166]
##### 错误日志&截图：
![Weixin Screenshot_20231117190644](https://github.com/jeecgboot/JimuReport/assets/79895629/e39795b5-0481-43e5-b55d-135f48290c13)

##### 重现步骤：
创建报表，sql 数据集，连接 Postgresql 数据库，设置 create_time 字段为查询条件，查询时报上面的异常

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
方便提供一个在线的报错的示例数据？便于测试

**Comment by lsqGitHub716** [comment]
已修改
