### ISSUE TITLE
无法通过散点图配制出四象限图（波士顿矩阵图）

### ISSUE THREAD

**Issue by Jalone5186** [jeecgboot/JimuReport#2167]
##### 版本号：
1.6.4

##### 问题描述：
无法通过散点图配制出四象限图（波士顿矩阵图）。可以在现有功能的基础上支持配制出X轴和Y轴的参考线（均值或固定某个值）然后隐藏X轴和Y轴的坐标就可以实现。参考线的样式最好能调整，带箭头等。效果如下截图：

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/50126675/1e5a2aa5-60a1-46c4-98e7-3b7b7c477ffc)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
