### ISSUE TITLE
能否将数字0替换成-输出

### ISSUE THREAD

**Issue by KIMLX** [jeecgboot/JimuReport#2168]
##### 版本号：
1.6.4

##### 问题描述：
能否将数字0替换成-输出

##### 错误日志&截图：
![Snipaste_2023-11-20_10-34-11](https://github.com/jeecgboot/JimuReport/assets/24363907/e0aa5ab6-c081-49e9-b6a8-6d1d469a72c3)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你可以自己写个表达式
