### ISSUE TITLE
多数据集查询为空

### ISSUE THREAD

**Issue by asasdddddsdo** [jeecgboot/JimuReport#2169]
##### 重现步骤：
1.创建两个sql数据集，分别为xzqh, qyxx
2.创建三个字段分别为：区划/区划名称和企业名称
3.其中区划名称的值为 =case('#{xzqh.xzqhdm}'=='#{qyxx.ssqx}','#{xzqh.xzqh}','0')
预览结果为0，再次尝试单独输出#{xzqh.xzqhdm}，结果为空，同一行内两个数据集，第二个数据集回显失败
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by asasdddddsdo** [comment]
截图如下：
![预览](https://github.com/jeecgboot/JimuReport/assets/28718456/67a3d060-c21a-4c35-8d08-12a91debe1bb)
![表格](https://github.com/jeecgboot/JimuReport/assets/28718456/d22ee979-23fb-4e81-bbce-69dc480b8003)
![单元格值](https://github.com/jeecgboot/JimuReport/assets/28718456/1565703c-b5c2-42c3-8948-8769a6bccda8)

**Comment by zhangdaiscott** [comment]
不支持这么组合用
