### ISSUE TITLE
能否支持不同租户的独立数据源？

### ISSUE THREAD

**Issue by eyuan** [jeecgboot/JimuReport#2171]
##### 版本号：
1.5.6

##### 问题描述：
我使用的是jeecgboot的多租户版本，并做了修改，当用户登录后，根据用户所属的租户，找到该租户配置的多数据源，然后后续操作使用该数据源，即jeecg默认的是使用租户id软隔离，我是借用jeecg的多数据源等功能改为不同数据库的硬隔离。
当前遇到个问题，求助：积木报表不设置数据源时，默认是该微服务的默认数据源。jeecg的积木默认集成在system模块/微服务下，使用的是system的主数据源，如何做到将当前用户tenantid所对应的数据源代替当前服务的主数据源来执行积木报表的数据集查询？

##### 错误日志&截图：
如下图所示：不选择数据源
![image](https://github.com/jeecgboot/JimuReport/assets/1910132/4734a52a-150c-4ccb-914f-e98ede918aa8)
执行查询后，在服务的主数据源中找不到表：
![image](https://github.com/jeecgboot/JimuReport/assets/1910132/a2c4c560-8212-4e7a-9c85-0bac53d895ab)
多数据源中配置了各租户的数据源
![image](https://github.com/jeecgboot/JimuReport/assets/1910132/0203eec6-f998-4e10-b70c-5d52aa5ba8ae)

**Comment by zhangdaiscott** [comment]
积木报表的数据源配置是自己的，不能用jeecg的
你可以开启saas
https://help.jeecg.com/jimureport/config/saas.html
