### ISSUE TITLE
旧版本的报表都打不开了，有什么办法能兼容或者把旧报表统一做下处理吗

### ISSUE THREAD

**Issue by eyuan** [jeecgboot/JimuReport#2172]
##### 版本号：
1.6.2GA5及以上版本

##### 问题描述：
升级后，原来的报表都打不开了

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/1910132/4a026955-22a5-4901-88b6-1a9752ec1988)

**Comment by zhangdaiscott** [comment]
所有的报表，还是那种类型
