### ISSUE TITLE
开发如何直接打印报表

### ISSUE THREAD

**Issue by xxhanlin888** [jeecgboot/JimuReport#2173]
##### 问题描述：
如果要实现把积木设计的报表嵌入到我的一个页面中，通过页面中的一个“打印”按钮直接打印到默认打印机上，这个功能如何实现呢？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by xxhanlin888** [comment]
qq:270019953@qq.com

**Comment by zhangdaiscott** [comment]
不支持
