### ISSUE TITLE
ruoyi集成不正常

### ISSUE THREAD

**Issue by suyang1023** [jeecgboot/JimuReport#2174]
##### 版本号：
1.6.4

##### 问题描述：
在我们的ruoyi项目中集成了积木报表，打开后显示异常，控制台报错“Uncaught SyntaxError: Unexcepted token .”，大佬能指示一下我错在哪里吗？

##### 错误日志&截图：
打开积木首页
![首页](https://github.com/jeecgboot/JimuReport/assets/11532782/2f798f59-40da-476c-86af-98b053fcb975)

控制台报错（ps: 我是内网截图，请求不了百度正常）
![2控制台报错](https://github.com/jeecgboot/JimuReport/assets/11532782/e930cd06-8c14-47fa-a33a-98887f47f1f6)

打开页面的network
![3network](https://github.com/jeecgboot/JimuReport/assets/11532782/b83f2093-f76b-473a-9828-7cdbd9a28874)

在浏览器请求积木的api，是通的
![4apirequest](https://github.com/jeecgboot/JimuReport/assets/11532782/a016df07-52a8-4ee7-9000-3a51b3f0584e)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
通过后台地址访问

**Comment by suyang1023** [comment]
通过后台地址访问是指什么地址？我用了ip, localhost, 127.0.0.1 访问都不行。我也重写JmReportTokenServiceI了。

![fangwen](https://github.com/jeecgboot/JimuReport/assets/11532782/2cf9c9fd-83b6-4097-b24e-f8798a19e219)

![截图](https://github.com/jeecgboot/JimuReport/assets/11532782/68d3e619-0a8e-46f8-a060-b73654fa4332)

**Comment by suyang1023** [comment]
最后发现是我内网的chrome浏览器版本太低的原因。
