### ISSUE TITLE
套打图片无法取消

### ISSUE THREAD

**Issue by zxzMrzxz** [jeecgboot/JimuReport#2175]
##### 版本号：
  <artifactId>jimureport-example</artifactId>
    <version>1.6</version>

##### 问题描述：
选择套打图片后，无法取消套打图片
##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/96802834/6989731a-4d1b-4cfa-8098-933a16512d43)

##### 重现步骤：
选择图片后右键误触，无法取消

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
zy

**Comment by zxzMrzxz** [comment]
请问有解决办法吗
