### ISSUE TITLE
提示 开启Saas模式下，保存数据集 不允许使用平台数据源（请配置数据源）

### ISSUE THREAD

**Issue by maxlkk** [jeecgboot/JimuReport#2178]
##### 问题描述：
新建报表-数据级管理-sql数据集  ，写好sql后 sql解析成功 点确定就会提示 开始Saas模式下。。。。
 为什么会提示 开启Saas模式，怎么触发的
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/50983296/21fd46f2-a17c-468f-8261-e65cf995b2b7)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
开启了saas模式，必须选择数据源
