### ISSUE TITLE
租户id获取不到

### ISSUE THREAD

**Issue by maxlkk** [jeecgboot/JimuReport#2180]
##### 问题描述：
yml中开启了租户隔离，url上拼接了tenantId，没有拼token，发起请求后后端JimuReportTokenService 无法从请求头中获取tenantId，但是有token。（之前有发起过拼接了token 没有拼tenantId的请求）
是什么原因导致

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/50983296/be6a9776-8266-46c9-8a7a-18ad8edbaba5)
![image](https://github.com/jeecgboot/JimuReport/assets/50983296/fa605788-5199-42f5-9283-ccd81d5a27ee)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
你可以通过`X-Tenant-Id`huoqu获取租户id，后续支持tenantId，如果获取不到请升级到最新版本
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/6bd42fb1-ef30-471c-a4bb-6593c2ec5472)
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.6.6</version>
</dependency>
```
