### ISSUE TITLE
图片不显示

### ISSUE THREAD

**Issue by gulanpeng** [jeecgboot/JimuReport#2181]
##### 版本号：
1.6.2-GA5

##### 问题描述：
图片不显示，

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/49330253/de49e04e-f287-4fe7-a704-750c94854446)

##### 重现步骤：无论是从数据源中取的还是直接上传的 都不显示

**Comment by zhangdaiscott** [comment]
上传这块怎么配置的，用的是阿里云还是minio?
