### ISSUE TITLE
操作问题

### ISSUE THREAD

**Issue by BI2414** [jeecgboot/JimuReport#2184]
##### 版本号：
1.5.4
##### 问题描述：
集成积木报表到自己的项目中，sql语句：
SELECT
	cc.title,
	sd.NAME major_name,
	cst.student_id student_num,
	cst.student_name,
	ccl.class_name,
	cca.audit_status,
	cc.apply_user_name 
FROM
	course_selection cse
	LEFT JOIN course_course cc ON cse.course_id = cc.id
	LEFT JOIN course_student cst ON cst.id = cse.student_id
	LEFT JOIN sys_dept sd ON cst.major_id = sd.dept_id
	LEFT JOIN course_class ccl ON ccl.class_id = cst.class_id
	LEFT JOIN course_course_addition cca ON cse.course_id = cca.course_id 
WHERE
	cse.`status` = 1 and 
  cst.major_id = ${majorId}
动态获取从url中的majorId，但是只有在第一次访问view的时候可以获取到majorId进行数据查询，后续页面上进行下一页和查询等操作获取不到majorid提示sql语句错误
##### 错误日志&截图：
![error1](https://github.com/jeecgboot/JimuReport/assets/85178236/29064c91-5c33-4a14-b21d-a5fdeb31f2b9)
![error2](https://github.com/jeecgboot/JimuReport/assets/85178236/3bc55d67-c577-483a-8379-6e9b1f8b9969)
![前端代码](https://github.com/jeecgboot/JimuReport/assets/85178236/adfbc82b-9bb5-4196-8905-9e5cf6d9a377)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请先升级到最新本
