### ISSUE TITLE
传了token还是报权限问题

### ISSUE THREAD

**Issue by hd0715** [jeecgboot/JimuReport#2187]
##### 版本号：
1.6.5

##### 问题描述：

传了token还是报权限问题
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/83495935/69056fd0-086c-40e5-a895-359b1199cf3d)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by luckymuye** [comment]
给你的JmReportTokenServiceI实现类加上这个试下
 `    @Override
    public String[] getRoles(String s) {
        return new String[]{"admin"};
    }`

**Comment by hd0715** [comment]
好的，已经ok了
