### ISSUE TITLE
系统想要集成积木打印功能

### ISSUE THREAD

**Issue by cloudwinter** [jeecgboot/JimuReport#2190]
##### 版本号：
最新版本

##### 问题描述：
自己的系统里面有入库单的打印需求，集成积木报表之后，配置入库单的模板，怎么从自己系统的入库单直接根据指定模板发起入库单的打印，不想每次都进入积木报表的页面再发起

##### 错误日志&截图：
无

##### 重现步骤：
无

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
目前只能先打开报表，才能打印
