### ISSUE TITLE
在doris中使用sql语句生成字段code，点击查询按钮后，会出现重复多次执行

### ISSUE THREAD

**Issue by RavenZdh** [jeecgboot/JimuReport#2192]
##### 版本号：
1.5

##### 问题描述：
使用doris数据库，在报表参数中，使用select语句的字典code生成查询下拉框。
在点击查询栏的查询按钮后，对应的报表参数code查询语句在doris会重复执行多次。
这个对现有报表影响还是很大的，我们不少报表有五六个使用sql的字典code，相当于每次查询时都会额外执行二三十次的SQL语句，对数据库影响较大。

##### 错误日志&截图：
相关报表配置：
![85fa00c89218970398618af3deeed8d](https://github.com/jeecgboot/JimuReport/assets/49672022/29c67a5c-9cff-4d1d-bfb6-afa0ea2eb8c0)
![ad5d3e11d74a3485349921d006a096b](https://github.com/jeecgboot/JimuReport/assets/49672022/a717a1e4-bd7a-45c6-8ab7-ff0da1deadb4)
报表前端：
![1700734909846](https://github.com/jeecgboot/JimuReport/assets/49672022/e0fa75ac-88d3-4a2e-b185-2d0945e9d57c)
doris日志：
![image](https://github.com/jeecgboot/JimuReport/assets/49672022/018e0a13-114f-4457-ac0d-182a97c8a473)

##### 重现步骤：
已经尝试在多个环境的jimu中验证，在点击查询栏按钮后，均会出现重复多次执行对应的字段code的sql的情况。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级最新版本试一下

**Comment by zhangdaiscott** [comment]
这个得你们自己分析了
