### ISSUE TITLE
查询控件下拉树自定义的token header未生效

### ISSUE THREAD

**Issue by yhan219** [jeecgboot/JimuReport#2193]
##### 版本号：

1.6.5
##### 问题描述：
重写了`JmReportTokenServiceI`，重新设置了token header为x-token
```
    @Override
    public HttpHeaders customApiHeader() {
        HttpHeaders httpHeaders = new HttpHeaders();
        httpHeaders.add("X-Token", TokenUtils.getToken(null));
        return httpHeaders;
    }
```
但是请求下拉树的时候，还是用的还是token

希望查询控件下拉树能支持传递token

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by lvdandan16** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/54099258/333cc12d-7b7f-40ba-9154-9b5e5458aa08)
目前token传参只支持这两种方式，其他的不支持
参考文档：https://help.jeecg.com/jimureport/config/token.html

**Comment by jeecgos** [comment]
2.1.2+版本已支持
