### ISSUE TITLE
多租户模式，报表名称的唯一性校验逻辑问题

### ISSUE THREAD

**Issue by Maoxfei** [jeecgboot/JimuReport#2194]
##### 版本号：
1.6.5

##### 问题描述：
租户A有一个报表名称为【出库单】，租户B创建报表时名称就不能为【出库单】，多租户模式的话，名称重复的校验也要加tenantId隔离吧？请问是尚未支持该数据隔离还是我未配置成功
补充：使用的是ruoyi-vue-pro 集成的方式
##### 错误日志&截图：
![1](https://github.com/jeecgboot/JimuReport/assets/16496235/5f6e3b55-bab9-4a4d-abb5-e08361b9aa95)
![2](https://github.com/jeecgboot/JimuReport/assets/16496235/73a1de04-5f1d-4b48-9052-3fbcdb5a5b6a)
![3](https://github.com/jeecgboot/JimuReport/assets/16496235/ede7923a-9eb0-48a8-afdf-0e5d4edca315)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by lsqGitHub716** [comment]
已修改
