### ISSUE TITLE
下拉树怎么设置为单选

### ISSUE THREAD

**Issue by yhan219** [jeecgboot/JimuReport#2195]
##### 版本号：

1.6.5
##### 问题描述：
自定义的下拉树想设置成单选的，需要怎么处理

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持

**Comment by BO-DI** [comment]
> 不支持

请问，1.9.1或者后续最新版本会支持吗？

**Comment by BO-DI** [comment]
> ##### 版本号：
> 1.6.5
> 
> ##### 问题描述：
> 自定义的下拉树想设置成单选的，需要怎么处理
> 
> ##### 错误日志&截图：
> ##### 重现步骤：
> #### 友情提示（为了提高issue处理效率）：
> * 积木报表是一款免费报表产品，功能免费源码不开放;
> * 未按格式要求发帖，会被直接删掉;
> * 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
> * 针对不好重现的问题，请录制操作视频或详细的重现步骤；

请问博主，后来有什么突破口吗，针对下拉树单选得情况？
