### ISSUE TITLE
查询数据分组排序后顺序不对

### ISSUE THREAD

**Issue by wangdongyuyuya** [jeecgboot/JimuReport#2196]
##### 问题描述：
查询的数据分组后排序不对，正常排序是从1到20排列下来，排序完的数据为 1，10，11，这种排列的，后台字段的数据类型为int类型，报表中设置了正序也不起作用

##### 错误日志&截图：
![Uploading 1700810796822.jpg…]()

#### 友情提示（为了提高issue处理效率）：
![mx](https://github.com/jeecgboot/JimuReport/assets/40593825/67a981d1-9a09-4f64-8258-868b1216b945)

  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/jimureport/group/dataSort.html
