### ISSUE TITLE
1.6.3 - SQL解析失败：请注意，值可能存在SQL注入风险!

### ISSUE THREAD

**Issue by kuailefeixiang** [jeecgboot/JimuReport#2198]
##### 问题描述：  
SQL解析失败：请注意，值可能存在SQL注入风险!--->select * from salsalesordermaster where uguid='${uguid}'

##### 错误日志&截图：
![QQ图片20231124160523](https://github.com/jeecgboot/JimuReport/assets/151910310/e73e8513-d71e-4948-a280-ba9aa0b4a36e)

![2](https://github.com/jeecgboot/JimuReport/assets/151910310/445569fa-6e57-424e-8c5e-c63110e7d8ca)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 z

**Comment by zhangdaiscott** [comment]
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.6.6</version>
</dependency>

**Comment by kuailefeixiang** [comment]
这意思是等着 1.6.6的升级版吗； 我是windows版本直接安装的； 修复后麻烦给个安装包。
