### ISSUE TITLE
能否把选择数值类型时的逗号去掉，或者做成可选择的？

### ISSUE THREAD

**Issue by happyuanhao** [jeecgboot/JimuReport#2199]
##### 版本号：

1.6.5
##### 问题描述：
我应用了咱们补零的这块的内容，所以给行参数设置了数值的格式，如果不设置数值格式，导出的execl就缺失了汇总合计的功能，但是在设置数值后，界面显示的数字就有了分隔符逗号，能否把逗号这个设置为可选的，或者去掉，因为我导出的execl中也不需要逗号分隔，在界面显示上都是逗号的分隔符，就看着很乱也不方便工作人员辨别逗号和小数点，希望官方能改进这一问题，谢谢！！！！

##### 错误日志&截图：
![1700821657727](https://github.com/jeecgboot/JimuReport/assets/25651702/dd0378cb-b760-47b6-bbc9-cb055ebc7dfa)

##### 重现步骤：
在积木报表编辑内选择数值，然后保留几位小数点

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by happyuanhao** [comment]
![1700821841080](https://github.com/jeecgboot/JimuReport/assets/25651702/1e9e3f0b-aef7-4386-9e3e-a960fa01b5a4)
![1700822023486](https://github.com/jeecgboot/JimuReport/assets/25651702/8cf34b41-ed9b-4867-aaa3-afb5cd3e124d)
![1700822150210](https://github.com/jeecgboot/JimuReport/assets/25651702/800092b5-2233-4531-9495-7ceec540ce97)

**Comment by lvdandan16** [comment]
目前不支持千分符设置为可选
