### ISSUE TITLE
无循环表头

### ISSUE THREAD

**Issue by SpringSea1201** [jeecgboot/JimuReport#2200]
##### 错误日志&截图：
![无循环表头](https://github.com/jeecgboot/JimuReport/assets/107163751/97cc4efa-a735-4545-9b82-29e3c1526d60)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
目前只有打印支持固定表头表尾，预览不支持循环表头
参考文档：https://help.jeecg.com/jimureport/printNew/gaugeOutfit.html
