### ISSUE TITLE
导出PDF时  系统报错  Trailing char < > at index 12: \opt\upload\ 

### ISSUE THREAD

**Issue by sanye8899** [jeecgboot/JimuReport#2201]
##### 问题描述：导出PDF时  系统报错
java.nio.file.InvalidPathException: Trailing char < > at index 12: \opt\upload\ 

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/105095249/2e2528e0-5a1d-444a-8e02-970bc5c93113)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by sanye8899** [comment]
已解决，是格式错误。

**Comment by liqinghe9** [comment]
> 已解决，是格式错误。

我把报表配置放到官方demo里没问题，但是本地就是不行，之前好好的，但是添加了背景和报表就不行了，去掉也不行
