### ISSUE TITLE
报表导出pdf，每一页都要显示的表头、表尾无法导出。

### ISSUE THREAD

**Issue by think9102** [jeecgboot/JimuReport#2202]
##### 版本号：
1.6.4

##### 问题描述：导出pdf的时候，表头、表尾没有办法导出。

比如很多情况下没有配置打印机，需要导出为pdf格式。
假定需要打印35人的信息，每一页10人，共4页，但是每一页都要展示表头表尾和表格的标题行。
现在发现预览打印可以。但是导出pdf后，表头表尾都无法每页展示。都没有了。

##### 错误日志&截图：
![导出pdf表头消失](https://github.com/jeecgboot/JimuReport/assets/55285286/a4611558-5171-4d3f-a118-77a7b63cd734)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by think9102** [comment]
> 导出pdf暂不支持固定表头表尾，目前只有打印支持 归集：#138

有导出支持的计划吗？还是有其他方法可以变通实现啊？现在很多情况下都需要导出来完成。配打印机的很少了。

**Comment by 1298191366** [comment]
目前导出pdf已经支持固定表头表尾，请升级到最新版本 `1.7.8`
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.7.8</version>
</dependency>
```
