### ISSUE TITLE
通过api解析查询到数据，分组后排序错乱，不是sql查询，1.5.2版本还没有问题，更新到最新版本后错乱。

### ISSUE THREAD

**Issue by wangdongyuyuya** [jeecgboot/JimuReport#2203]
##### 版本号：
1.6.3

##### 问题描述：
通过api解析查询到数据，分组后排序错乱，不是sql查询，1.5.2版本还没有问题，更新到最新版本后错乱。

##### 错误日志&截图：
![Uploading mx.jpg…]()

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 sq

**Comment by zhangdaiscott** [comment]
图列了

**Comment by lsqGitHub716** [comment]
麻烦提供一下你的模版配置或者错误截图信息

**Comment by wangdongyuyuya** [comment]
![Uploading sj.jpg…]()
正常排序1后面是2，现在1后面是10

**Comment by lsqGitHub716** [comment]
你上传的图片都看不了，你是怎么配置的

**Comment by wangdongyuyuya** [comment]
![1701756652205](https://github.com/jeecgboot/JimuReport/assets/40593825/114df94e-639f-4ce2-bb2b-e4f64eb3c8ce)

**Comment by lsqGitHub716** [comment]
好的，本地测试未复现，麻烦提供一下这个报表的配置以及接口返回的数据
![image](https://github.com/jeecgboot/JimuReport/assets/65587928/948ea7c6-52e6-4ad8-93af-f2b438052da7)

**Comment by wangdongyuyuya** [comment]
[任务报表.json](https://github.com/jeecgboot/JimuReport/files/13556631/default.json)
[数据.txt](https://github.com/jeecgboot/JimuReport/files/13556632/default.txt)

**Comment by lsqGitHub716** [comment]
已修改

**Comment by caiguanlin** [comment]
那个版本开始支持？

**Comment by SteadyArcticFox** [comment]
横向分组排序还是有问题，正序或者自定义都不行，已经是1.7.0了
![image](https://github.com/jeecgboot/JimuReport/assets/20089953/5218ef02-bb1d-4fc0-b307-1173e5a0028f)
![image](https://github.com/jeecgboot/JimuReport/assets/20089953/74da484a-27b8-4864-82c3-2890f5bfd469)
![image](https://github.com/jeecgboot/JimuReport/assets/20089953/1ed3a9e0-6eff-4a5f-8fd0-50ae8cd16f33)
