### ISSUE TITLE
升级成最新版本的报表后，原表名称中带master，无法使用报表

### ISSUE THREAD

**Issue by xdxycx** [jeecgboot/JimuReport#2204]
##### 问题描述：
升级成最新版本的报表后，原表名称中带master，无法使用报表

##### 错误日志&截图：
![微信图片_20231127101602](https://github.com/jeecgboot/JimuReport/assets/4011625/c9ae8b44-01b2-40ee-85e0-40ef4c8fa5bb)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请升级1.6.6版本
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.6.6</version>
</dependency>
