### ISSUE TITLE
1.6.1 到 1.6.5后页面预览访问报错NoSuchMethodError

### ISSUE THREAD

**Issue by hua350264633** [jeecgboot/JimuReport#2205]
##### 版本号：
1.6.5

##### 问题描述：
升级后访问预览页面报错：操作失败，Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: com.alibaba.fastjson.JSONObject.clone()Lcom/alibaba/fastjson/JSONObject;

##### 错误日志&截图：
![9H{)KW%XL _4Z(TWSMKCL L](https://github.com/jeecgboot/JimuReport/assets/32692650/f3f97596-2b16-418c-8834-8e7ef21c5e51)
##### 重现步骤：

随便访问哪个页面都会报错
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by hua350264633** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/32692650/5a26ecd1-7326-46f9-98a5-dde8dae6a0a9)

**Comment by lvdandan16** [comment]
fastjson是什么版本

**Comment by SleepyWiKi** [comment]
这个需要看下你项目的fastjson版本，把fastjson版本全局统一为1.2.78就可以解决了。

**Comment by hua350264633** [comment]
> 这个需要看下你项目的fastjson版本，把fastjson版本全局统一为1.2.78就可以解决了。
非常感谢，我目前的fastjson版本是1.2.75

**Comment by SleepyWiKi** [comment]
> > 这个需要看下你项目的fastjson版本，把fastjson版本全局统一为1.2.78就可以解决了。
> > 非常感谢，我目前的fastjson版本是1.2.75
老哥有没有遇到我新提的那个issue，全局拦截的问题；

**Comment by hua350264633** [comment]
> > > 这个需要看下你项目的fastjson版本，把fastjson版本全局统一为1.2.78就可以解决了。
> > > 非常感谢，我目前的fastjson版本是1.2.75
> > > 老哥还没有遇到我新提的那个问题，全局拦截的问题；

升级后还没测试呢，我们片区网络故障了，你那个问题我看了，没遇到过，你可以看一下[升级日志](http://jimureport.com/doc/log)里面有没有提到相关内容呢
