### ISSUE TITLE
偶发性BUG，相同的字段内容 放在某些单元格后就不会显示，放在其他格就能显示，全部重新做，一模一样的内容就能展示

### ISSUE THREAD

**Issue by dengyingfeng2022** [jeecgboot/JimuReport#2206]
##### 版本号：

1.6.5
##### 问题描述：
偶发性BUG，相同的字段内容 放在某些单元格后就不会显示，放在其他格就能显示，全部重新做，一模一样的内容就能展示

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/105050463/b91a291d-3bf0-4995-a949-d244f95a578b)
![image](https://github.com/jeecgboot/JimuReport/assets/105050463/4df5651c-a1fc-4317-a6bf-6fdd82fc674e)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请在积木官网做个示例，我们复现一下

**Comment by dengyingfeng2022** [comment]
这个是偶发的  我也不知道怎么操作可以稳定复现 但是我遇到过很多次了 我我怀疑是在一些单元格存入了错误的公式或者信息

**Comment by dengyingfeng2022** [comment]
已经稳定复现了，可能是一个兼容性BUG吧，情况是这样的：但API数据集只返回一条数据时，平常使用#{aa.abc}和${aa.abc}效果是一样的，但当一行的右侧有纵向合并的单元格时，使用了#{aa.abc}就必然导致合并单元格中的数据集元素不能展示，但是直接文本可以展示，解决方案当然也是很简单，对于返回一条数据的API不勾选数据集且使用${aa.abc}就能解决。看你们觉得是否有必要兼容一下吧@lvdandan16

**Comment by zhangdaiscott** [comment]
提供验证数据

**Comment by dengyingfeng2022** [comment]
API是内网的 外网无法访问        你可以写一个API数据集 只返回一条数据 然后勾选是否集合  然后在表格中做一个纵向合并的单元格 像这样
![image](https://github.com/jeecgboot/JimuReport/assets/105050463/7a53d51b-5619-4add-8da5-a2044efbc198)
