### ISSUE TITLE
公共页面，不需要鉴权和token，如何实现

### ISSUE THREAD

**Issue by 793292556** [jeecgboot/JimuReport#2207]
##### 版本号：

1.6.5
##### 问题描述：
我有一个公共页面，并不需要鉴权，只要地址就可以访问，如何放开限制，求解

##### 错误日志&截图：
{"code":500,"success":false,"message":"Token校验失败，无权限访问！","timestamp":1701065378413}

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/54099258/5a6312de-b970-4987-8012-33936deb9c58)

升级1.6.6版本
并且将yaml配置saasMode默认为空
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.6.6</version>
</dependency>
```
