### ISSUE TITLE
创建时间更新时间时间戳转换问题

### ISSUE THREAD

**Issue by dylvs** [jeecgboot/JimuReport#2208]
##### 版本号：
1.5.8

##### 问题描述：

整合sqlite数据库，报表保存后台打印时间转换的错误。
##### 错误日志&截图：
Unparseable date: "1701074953456" does not match (\p{Nd}++)\Q-\E(\p{Nd}++)\Q-\E(\p{Nd}++)\Q \E(\p{Nd}++)\Q:\E(\p{Nd}++)\Q:\E(\p{Nd}++)
![image](https://github.com/jeecgboot/JimuReport/assets/133832509/2b2a0a1e-db77-47ca-a6f4-148386cc88e7)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
没有兼容sqlite
