### ISSUE TITLE
积木报表的图表背景图上传后显示错误

### ISSUE THREAD

**Issue by suyang1023** [jeecgboot/JimuReport#2210]
##### 版本号：
<=1.6.5

##### 问题描述：
积木报表的图表背景图上传后显示错误
<img width="235" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/11532782/9644dfc6-a056-4626-b600-afe7d4c8d662">

##### 错误日志&截图：
图表背景上传后返回的图片地址是：http://localhost:8088/jimureport/bg1701076788103.png
应为 http://localhost:8088/jmreport/img/jimureport/bg1701076788103.png 才对
路径里少了 /jmreport/img
对应的js应该是 design.js，下图中少了 path = "/jmreport/img" + path;
![image](https://github.com/jeecgboot/JimuReport/assets/11532782/686ef55c-4737-4001-b3e2-2f3685dedec1)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
配置下上传云存储配置，可以用阿里云或者minio

**Comment by liqy00** [comment]
版本号：
版本1.7.8和版本1.8.0
问题描述：
文件上传到本地的应该怎么处理？或者怎么配置？
