### ISSUE TITLE
函数不能和文字进行组合了

### ISSUE THREAD

**Issue by Yxw521** [jeecgboot/JimuReport#2211]
##### 问题描述：
函数不能和文字进行组合了

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/76502207/2facf372-ee3b-4ae7-b005-34adff9f51a8)

##### 重现步骤：

1. 期望显示 ： 测试0
2. 实际显示  ：0

**Comment by hoperunChen** [comment]
已修复，待新版本发布
