### ISSUE TITLE
分组小计，字样消失

### ISSUE THREAD

**Issue by zimohj** [jeecgboot/JimuReport#2212]
##### 版本号：
1.6.5

##### 错误日志&截图：
[sssssss.json](https://github.com/jeecgboot/JimuReport/files/13483079/sssssss.json)
设置中间的数据作为分组依据，报表显示结果，但不显示小计字样
![image](https://github.com/jeecgboot/JimuReport/assets/142202507/b53d7c09-499b-4d83-9af6-fe07377af406)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zimohj** [comment]
补充报表预览图片
![image](https://github.com/jeecgboot/JimuReport/assets/142202507/a633e3c5-35bc-4e19-b928-2c7a484b7cd9)

**Comment by lvdandan16** [comment]
已修复，下个版本升级
