### ISSUE TITLE
MacOS系统中，使用官方springboot集成的代码在本地idea中运行，上传图片报错

### ISSUE THREAD

**Issue by Jalone5186** [jeecgboot/JimuReport#2213]
##### 版本号：
1.6.5

##### 问题描述：
MacOS系统中，使用官方springboot集成的代码在本地idea中运行，上传图片报错

##### 错误日志&截图：
<img width="1424" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/50126675/a47b3c95-f3d5-4da5-b141-df708053ea62">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Jalone5186** [comment]
前端图片也未显示出来，如图：
<img width="570" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/50126675/c40e53b9-e711-4f2d-981a-2e9d1764d7f1">

**Comment by zhangdaiscott** [comment]
使用云存储

**Comment by Jalone5186** [comment]
不能用云存储啊，是政府项目，需要本地部署，内网使用的。

**Comment by zhangdaiscott** [comment]
可以自己搭建minio
