### ISSUE TITLE
提示SQL注入风险，提示不准确导致SQL无法保存

### ISSUE THREAD

**Issue by Jalone5186** [jeecgboot/JimuReport#2214]
##### 版本号：
1.6.5

##### 问题描述：
提示SQL注入风险，提示不准确导致SQL无法保存

##### 错误日志&截图：
<img width="1244" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/50126675/da6b7b2d-bd86-46c0-a365-a70d7a3edefe">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
升级1.6.6

**Comment by Jalone5186** [comment]
pom文件中改成1.6.6的版本，无法下载到该版本的包

**Comment by SleepyWiKi** [comment]
你解决了吗，我也遇到了这个问题

**Comment by zhangdaiscott** [comment]
配置私服
升级1.6.6-beta
https://help.jeecg.com/java/setup/maven.html
