### ISSUE TITLE
关于分库多数据源问题

### ISSUE THREAD

**Issue by kaorouhaochi** [jeecgboot/JimuReport#2215]
##### 问题描述：
项目需要分两个数据库进行操作，根据jimu文档进行分库走单独的report数据库之后，DataSourceConfig注册的数据库导致所有项目查询都走report数据库了，项目报错xxx不存在。想问如何能够在项目里面使用多个数据源

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/152259231/9c6640fe-16c6-4029-9bfd-8c5210ed9d6b)
![image](https://github.com/jeecgboot/JimuReport/assets/152259231/dd1b5a97-6157-4564-a457-70ceb43506e5)
下图是原先的数据源不生效了
![image](https://github.com/jeecgboot/JimuReport/assets/152259231/f88fb70c-2dd7-45b1-a24f-b4b0e85c7729)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
设置个性化的数据源，通过yml
![image](https://github.com/jeecgboot/JimuReport/assets/3162115/dc984d29-4f06-4096-9341-e44de74e98fe)
