### ISSUE TITLE
新建报表报错误页面

### ISSUE THREAD

**Issue by 3043871668** [jeecgboot/JimuReport#2219]
##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/73048063/d29c07e4-d1a7-49fe-9926-2192b718b996)

##### 重现步骤：
刚进去报不支持定位的更新和删除，点击新建报表报错误页面

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
遇到问题请先升级到最新版，老版无法支持

**Comment by 3043871668** [comment]
项目里有线程可以集成积木报表吗

**Comment by 3043871668** [comment]
项目里有线程可以集成积木报表吗






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月29日(星期三) 上午9:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 新建报表报错误页面 (Issue #2219)





 
Closed #2219 as completed.
