### ISSUE TITLE
无法对超出AX列进行编辑

### ISSUE THREAD

**Issue by yang990802** [jeecgboot/JimuReport#222]
##### 版本号：
1.3.1-beta4

##### 问题描述：
进去仅有AX列，插入更多的列之后保存重新打开。只能显示AX列，无法对后续的列进行编辑和删除，再插入新的列，之前的列还会存在。

##### 截图&代码：

<img width="1280" alt="4BB026B5-B82E-4FE1-BEB4-C5D6E86C4B82" src="https://user-images.githubusercontent.com/83158443/115985768-f7e1ea00-a5df-11eb-8de2-c0172fbadf01.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
待分析-ty

**Comment by tygithub1** [comment]
升级到这个版本看看

<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.3-beta</version>
</dependency>
有升级脚本，具体见http://jimureport.com/doc/log
