### ISSUE TITLE
全局拦截

### ISSUE THREAD

**Issue by SleepyWiKi** [jeecgboot/JimuReport#2220]
##### 问题描述：
将版本从1.5.6升级到1.6.4后，进入我们业务系统的登录页面也会被JimuReportTokenInterceptor这个类进行全局拦截去校验token，但是这时候我们业务系统是没有登录的，没有token，也并没有去访问jimureport部分内容。

##### 错误日志&截图：
<img width="1062" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/96610516/9d6da85d-c927-4137-bdb5-5071c0d1b71c">

##### 重现步骤：
<img width="384" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/96610516/7dd49017-b9e8-4027-8488-bf4bb4db2372">
<img width="489" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/96610516/ab5e4da7-b048-4c99-8dbc-65200684ca69">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by hua350264633** [comment]
我在想会不会和“[Token权限控制](https://help.jeecg.com/jimureport/config/token.html)”有关

**Comment by zhangdaiscott** [comment]
我们的扫码加了请求前缀，除非你请求了我们的前缀

![image](https://github.com/jeecgboot/JimuReport/assets/3162115/e082353e-545e-48e2-9387-1cb6846b2e8d)
