### ISSUE TITLE
新建不了报表

### ISSUE THREAD

**Issue by 3043871668** [jeecgboot/JimuReport#2227]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/73048063/78e2145d-fd09-46f2-ada4-6a015f9855f1)
![image](https://github.com/jeecgboot/JimuReport/assets/73048063/d48effa3-0179-418f-b77a-adb94e215a5d)
![image](https://github.com/jeecgboot/JimuReport/assets/73048063/18f1ad44-3ceb-4a71-9e14-faabc56543fc)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你这个错，不是我们的程序提示的，你得自己研究下
