### ISSUE TITLE
报表参数 日期类型

### ISSUE THREAD

**Issue by huadanzhilei** [jeecgboot/JimuReport#2229]
##### 错误日志&截图：

<img width="661" alt="c0f089c70f444a36afba66156f1372d3" src="https://github.com/jeecgboot/JimuReport/assets/42882769/1eabd229-6912-47ca-add6-16feaa5eb2e0">
<img width="1856" alt="ca64862e53f1e185c0b4d505d27ddbc2" src="https://github.com/jeecgboot/JimuReport/assets/42882769/4caf2bcc-b4d8-4e6e-9bff-14f3d10d050a">

**Comment by 1298191366** [comment]
你的表达式 少等于号  `=dateStr('yyyy-MM-dd')`
