### ISSUE TITLE
ruoyi-cloud集成jimureport1.6.5使用API数据源时出险token为null的问题

### ISSUE THREAD

**Issue by xiaosile44** [jeecgboot/JimuReport#2230]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/41051526/ba73b557-dce0-422a-9438-5489a5f5b1ea)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你token是怎么集成的

看看这个文档
https://help.jeecg.com/jimureport/config/token.html
