### ISSUE TITLE
报表查询时数据显示正常，导出excel或者pdf时数据丢失

### ISSUE THREAD

**Issue by cauchemar02** [jeecgboot/JimuReport#2232]
##### 错误日志&截图：
![1701326500700](https://github.com/jeecgboot/JimuReport/assets/122009614/bbbc4c62-e040-48a8-ab6a-3146990c44bd)
![1701326526669](https://github.com/jeecgboot/JimuReport/assets/122009614/ef1b2ad1-f08f-4c37-af56-b8af9bf8c730)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by cauchemar02** [comment]
![1701326500700](https://github.com/jeecgboot/JimuReport/assets/122009614/6dec71e5-b638-4653-8f66-a196b57eeb6a)
![1701326526669](https://github.com/jeecgboot/JimuReport/assets/122009614/5daa0775-069e-4623-b6ad-cb8e0bfa6647)

**Comment by zhangdaiscott** [comment]
遇到问题请先升级到最新版
