### ISSUE TITLE
查询栏有参数 后台日志查询空

### ISSUE THREAD

**Issue by huadanzhilei** [jeecgboot/JimuReport#2233]
##### 问题描述：查询栏有参数 后台日志查询空

想要默认查询当月的 理想状态是 每月一号 0点  到最后一天 月末的 23.59.59 这个怎么设置

##### 错误日志&截图：
<img width="507" alt="8c943c934e339eb31fd045dc82cd39a3" src="https://github.com/jeecgboot/JimuReport/assets/42882769/2e0aa510-aaa5-401a-8090-35cf56ddd55c">

<img width="766" alt="6e5e1c809da05e11458d31ce0083cb02" src="https://github.com/jeecgboot/JimuReport/assets/42882769/ecc4f8b3-ceab-477e-b500-d412abad8fab">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by huadanzhilei** [comment]
<img width="1598" alt="1701393064856" src="https://github.com/jeecgboot/JimuReport/assets/42882769/d881ce60-e31a-470c-b926-b9ce66cf46d2">

**Comment by huadanzhilei** [comment]
不太明白   获取当月第一天 最后一天   这个是新功能？  那我查询栏有数据  后台日志还是空 是为什么

**Comment by zhangdaiscott** [comment]
查询栏有数据 是什么意思

**Comment by zhangdaiscott** [comment]
图文并茂或者录视频

**Comment by huadanzhilei** [comment]
<img width="403" alt="1701422153669" src="https://github.com/jeecgboot/JimuReport/assets/42882769/801246c6-6b44-42b5-8bab-01fd75d95e61">
<img width="403" alt="1701422153669" src="https://github.com/jeecgboot/JimuReport/assets/42882769/298c361e-e48c-48df-8c5c-be0e543e59a3">
<img width="1172" alt="1701422282697" src="https://github.com/jeecgboot/JimuReport/assets/42882769/8b67eef1-63de-48f7-a3c8-48be4b6619ad">
![1701422412982](https://github.com/jeecgboot/JimuReport/assets/42882769/461bb8c2-64b3-41ce-97c1-7d0a2d2a6edb)

预览打开  开始日期结束日期都有数据  后台查询sql时间条件 为空   
点击查询  sql日志 时间还是为空

**Comment by zhangdaiscott** [comment]
你截图sql给我们没有任何帮助

**Comment by huadanzhilei** [comment]
我写的你是一点没看啊  

预览打开 开始日期结束日期都有数据 后台查询sql时间条件 为空
点击查询 sql日志 时间还是为空

**Comment by huadanzhilei** [comment]
<img width="1873" alt="1701477843628" src="https://github.com/jeecgboot/JimuReport/assets/42882769/68cc8da8-e6f8-45e5-bde8-dd34687c68e5">
设置了报表参数   但是看起来 后台 日志条件都没传过来
