### ISSUE TITLE
导出图片的时候图片长宽像素很大，有数据的表格只占一小部分

### ISSUE THREAD

**Issue by w7ss** [jeecgboot/JimuReport#2237]
##### 版本号：
v1.6.3

##### 问题描述：
导出图片的时候图片长宽像素很大，有数据的表格只占一小部分

##### 错误日志&截图：
![屏幕截图 2023-12-03 164154](https://github.com/jeecgboot/JimuReport/assets/26373730/6baf5fae-1f71-4123-8e13-4eb9c44d2ba1)
导出的图片：
![test](https://github.com/jeecgboot/JimuReport/assets/26373730/ace325b6-296f-44ce-b20f-dea0b972aaa3)

**Comment by lvdandan16** [comment]
请在积木官网做个示例，我们复现一下

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
