### ISSUE TITLE
导出PDF时，富文本的html标签都还在

### ISSUE THREAD

**Issue by a815128782** [jeecgboot/JimuReport#2238]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/57400285/3cb27b14-6124-49b1-8da6-91b51bb5e352)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by a815128782** [comment]
ws?什么意思？

**Comment by 1298191366** [comment]
已修复，待新版本发布
