### ISSUE TITLE
无法打开服务器代理

### ISSUE THREAD

**Issue by zhangjun70** [jeecgboot/JimuReport#2241]
##### 版本号：
http://www.jimureport.com/myWork

##### 问题描述：
无法打开服务器代理，导致出现跨域和https问题

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/152935718/616f968a-2dd3-4f9d-b73c-932f60703556)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你的接口改成https开头的即可
