### ISSUE TITLE
sql里面有注释就提示sql注入的问题，请问有办法解决吗？

### ISSUE THREAD

**Issue by zenithwu** [jeecgboot/JimuReport#2242]
版本为最新的：v1.6.5

sql里面有注释就提示sql注入的问题，请问有办法解决吗？

**Comment by zhangdaiscott** [comment]
升级到临时版本

```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.6.6-beta2</version>
</dependency>
```

**Comment by zenithwu** [comment]
你好，我试了还是不行。我看了代码还是有注释限制。

![WechatIMG1767](https://github.com/jeecgboot/JimuReport/assets/22339221/47099ae3-6a6d-451e-8aaa-43b9625df762)
![WechatIMG1766](https://github.com/jeecgboot/JimuReport/assets/22339221/72dd72a1-2e03-4644-8296-8894f81cd9c7)
![WechatIMG1765](https://github.com/jeecgboot/JimuReport/assets/22339221/46f0908f-728e-4a9b-8b64-d0b5c0a92207)

**Comment by zhangdaiscott** [comment]
把你的sql贴出来

**Comment by zenithwu** [comment]
我这边在客户环境不好复制，有截图
![image](https://github.com/jeecgboot/JimuReport/assets/22339221/aa97fdfb-559e-41db-9aca-62dfc088ed24)

**Comment by zhangdaiscott** [comment]
你自己sql问题，为什么要加注释

**Comment by zenithwu** [comment]
主要是加注释为了以后给其他人看懂sql的注视含义。方面后面人来改

**Comment by zhangdaiscott** [comment]
这样有被攻击风险
