### ISSUE TITLE
配置了“多租户模式”=“tenant”，并且“数据源安全”=“false”后：访问报表提示“安全模式下，不允许使用平台数据源（请配置数据源）！”

### ISSUE THREAD

**Issue by hua350264633** [jeecgboot/JimuReport#2244]
##### 版本号：

1.6.5
##### 问题描述：
配置文件中，配置了“多租户模式”=“tenant”，并且“数据源安全”=“false”后，积木报表数据集必须选择数据源后才能访问，否则会提示“安全模式下，不允许使用平台数据源（请配置数据源）！”，是不是判断逻辑写错了？

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/32692650/8cc617d4-be72-4aaf-8e34-72ef9f32a89d)
![image](https://github.com/jeecgboot/JimuReport/assets/32692650/18f0c92f-6d31-4eb1-906c-f4029b15d44e)
![image](https://github.com/jeecgboot/JimuReport/assets/32692650/68dab376-97e2-4b84-bcb5-93814e53e83d)

##### 重现步骤：
看截图说明

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
就是这么做的，你都开启多租户了，还能选平台的数据源不安全

**Comment by zhangdaiscott** [comment]
目前我们是这么做的，saas大于数据源安全

**Comment by hua350264633** [comment]
> 目前我们是这么做的，saas大于数据源安全

好吧，但是我觉得这个地方有点不合理，因为如果我只需要区分“租户”的报表配置数据，但是不想区分“数据源”时就很麻烦
为了启用“租户”功能，必须每个租户都配置一遍“数据源”会很麻烦

**Comment by zhangdaiscott** [comment]
我们考虑下

**Comment by hua350264633** [comment]
> 我们考虑下

好的，非常感谢！

**Comment by 1298191366** [comment]
已修复，待新版本发布
