### ISSUE TITLE
根据日志打印sql 查询数据库 有数据但是页面不显示

### ISSUE THREAD

**Issue by huadanzhilei** [jeecgboot/JimuReport#2246]
##### 版本号：
1.6.5

##### 问题描述：
数据不显示
但是根据边框看是有数据的

##### 错误日志&截图：
<img width="1723" alt="微信图片_20231207085530" src="https://github.com/jeecgboot/JimuReport/assets/42882769/1c213eb7-f291-4a7a-a0a5-e0986c51b901">

<img width="601" alt="微信图片_20231207085608" src="https://github.com/jeecgboot/JimuReport/assets/42882769/544b89f7-a427-48f4-9bea-df8c339049ef">
<img width="1848" alt="1701910646184" src="https://github.com/jeecgboot/JimuReport/assets/42882769/0a4fb7b5-3efb-4b0b-b159-c4fddbe2ecf8">
<img width="833" alt="1701910713292" src="https://github.com/jeecgboot/JimuReport/assets/42882769/b14e3166-0d94-4c91-962f-6757862f9dd6">

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/3162115/e70dadd8-f0a1-4b18-a09f-6b93be18ac89)
