### ISSUE TITLE
有分组的情况下，导出excel跟页面显示不一致

### ISSUE THREAD

**Issue by huang879819875** [jeecgboot/JimuReport#2248]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/153151448/35e64ef8-0ffe-4b6e-b83f-1b559b147436)
![image](https://github.com/jeecgboot/JimuReport/assets/153151448/1e4d470e-1141-47f7-945a-b717f0177c5a)

https://github.com/jeecgboot/JimuReport/assets/153151448/bdea610f-41e8-4e32-a625-980dc24e9887

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by huang879819875** [comment]
从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年12月8日 16:35
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [jeecgboot/JimuReport] 有分组的情况下，导出excel跟页面显示不一致 (Issue #2248)


请导出报表配置和数据或者在我们积木官网做个示例，我们复现一下

―

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
