### ISSUE TITLE
下载链接中没有1.6.5版本的免安装文件，还是1.6.3版本的

### ISSUE THREAD

**Issue by zgiw** [jeecgboot/JimuReport#2249]
##### 版本号：
1.6.5

##### 问题描述：
下载链接中没有1.6.5版本的免安装文件，还是1.6.3版本的

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/71875297/1cb34f40-6be7-4779-9462-0e63f262b117)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 z
