### ISSUE TITLE
SQL语句明文传给后端被堡垒机拦截

### ISSUE THREAD

**Issue by suimz** [jeecgboot/JimuReport#2252]
##### 版本号：

1.6.5

##### 问题描述：

SQL数据集中，SQL语句明文传给后端，直接被堡垒机拦截

是否考虑对SQL进行加密等手段传输给后端

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/14940814/b078f887-2394-41b8-9189-3313a2bfbffa)

![image](https://github.com/jeecgboot/JimuReport/assets/14940814/9053db18-e379-4cb4-9a92-aba213f3e0fd)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Sanpoh** [comment]
@suimz @lvdandan16 @learningpro @zhangdaiscott @jeecgos 
你好，请问这个问题现在解决了吗
