### ISSUE TITLE
柱状图

### ISSUE THREAD

**Issue by huadanzhilei** [jeecgboot/JimuReport#2253]
##### 版本号：
1.6.5

##### 问题描述：
怎么设置图表柱状图 模版里没有啊

<img width="538" alt="1701940294223" src="https://github.com/jeecgboot/JimuReport/assets/42882769/4caa41f8-e2ad-4822-babf-8eb90273f6a8">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by huadanzhilei** [comment]
顶

**Comment by lvdandan16** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/54099258/cb841084-6b88-42dd-93a6-96364c271334)
直接添加所需要的图表
