### ISSUE TITLE
集成到若依中，已连接redis添加字典时报错

### ISSUE THREAD

**Issue by XiaoXiongPotter** [jeecgboot/JimuReport#2254]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by XiaoXiongPotter** [comment]
![Uploading 6FD3109B-2EC8-4676-B115-8F1668865971.png…]()

**Comment by hoperunChen** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/13013558/cf28131b-6c28-44cd-b8d1-5e7f7e75ec06)
未复现问题
