### ISSUE TITLE
最新版本的搜索框搜索失效

### ISSUE THREAD

**Issue by xiaobaiyis** [jeecgboot/JimuReport#2255]
##### 版本号：
1.6.5

##### 问题描述：
单选搜索框中的搜索失效

##### 重现步骤：
![image](https://github.com/jeecgboot/JimuReport/assets/114853731/a80703eb-a535-477f-b618-84f81d3b8989)
![image](https://github.com/jeecgboot/JimuReport/assets/114853731/a2e3783d-4355-4663-918c-b90ff0e870df)
![image](https://github.com/jeecgboot/JimuReport/assets/114853731/bdfea2ef-d047-4adf-81df-1ef8b1de54d1)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
1.6.6试试

**Comment by xiaobaiyis** [comment]
我看官网版本只有1.6.5

**Comment by xiaobaiyis** [comment]
我是进页面之后直接搜索的 依然搜索不到

**Comment by 1298191366** [comment]
已修复，待新版本发布
