### ISSUE TITLE
若依框架集成积木报表后登录报错

### ISSUE THREAD

**Issue by cloudwinter** [jeecgboot/JimuReport#2256]
##### 版本号：
jimureport:1.6.5
springboot:2.3.3.RELEASE
框架若依

##### 问题描述：
集成之后，登录后台，提示

##### 错误日志&截图：
nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: select distinct m.perms
        from sys_menu m
                 left join sys_role_menu_rel rm on m.pk_id = rm.menu_id
                 left join sys_user_org_role_rel ur on rm.role_id = ur.role_id
                 left join sys_role r on r.pk_id = ur.role_id
        where m.forbid_flag = 0
          and r.forbid_flag = 0
          and ur.user_id = ?
          and ur.org_no = ?
### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: select distinct m.perms
        from sys_menu m
                 left join sys_role_menu_rel rm on m.pk_id = rm.menu_id
                 left join sys_user_org_role_rel ur on rm.role_id = ur.role_id
                 left join sys_role r on r.pk_id = ur.role_id
        where m.forbid_flag = 0
          and r.forbid_flag = 0
          and ur.user_id = ?
          and ur.org_no = ?
com.yhjx.mes.common.exception.MesException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
可参考集成文档：https://help.jeecg.com/jimureport/projectJoin/ruoyivue.html
这个看不出来什么问题，具体集成问题需要自行解决
