### ISSUE TITLE
查询报表中日期范围和数据集求和同时存在时，查询报错，sql缺失and条件

### ISSUE THREAD

**Issue by jiakuanhu** [jeecgboot/JimuReport#2258]
##### 版本号：
1.6.4

##### 问题描述：
查询报表制作，当查询报表中日期范围和数据集求和同时存在时，执行查询会报错，原因是拼接的求和sql中，缺少了and条件

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/64471855/7549d77b-e2f6-4a40-8f9d-861f4c6503b1)

![image](https://github.com/jeecgboot/JimuReport/assets/64471855/6e024f3b-d178-4340-9247-6d25fd4d1bbf)
![image](https://github.com/jeecgboot/JimuReport/assets/64471855/d1392e66-145a-4de2-810a-f6d094012b58)

##### 重现步骤：
 怀疑任何一个求和+任何一个查询皆可复现 ，按照上传图片设置配置必复现。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by CrackerClay** [comment]
统计函数DBSUM + 任何一个带条件查询的SQL 也有同样的问题

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布

**Comment by hechademaonini** [comment]
在1.6.6版本中依旧存在这个问题
