### ISSUE TITLE
报表单元格中如何设置文字方向为竖向输出

### ISSUE THREAD

**Issue by alawnyang** [jeecgboot/JimuReport#2259]
##### 问题描述：
想实现档案盒脊背的批量打印输出，如2cm、3CM、4CM、5CM...，在一张A4纸上分栏输出多列同样宽度的脊背，脊背中案卷题名单元格文字方向为竖向，这个应怎么设置？

##### 错误日志&截图：
![档案脊背](https://github.com/jeecgboot/JimuReport/assets/58247639/232c2203-6dae-499d-97db-a92cd2ba29a5)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
