### ISSUE TITLE
windows免安装版不能使用多租户

### ISSUE THREAD

**Issue by zgiw** [jeecgboot/JimuReport#2260]
##### 版本号：
1.6.6

##### 问题描述：
在windows免安装版的application.yml设置了多租户，但点击start.bat直接闪退，取消多租户就没问题

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/71875297/51d3bbf7-ffb0-43c9-8113-00787f58ae56)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/3162115/462b6ddc-5d55-4c2d-8cc8-26a63c9deacc)
