### ISSUE TITLE
API 数据返回非集合数据，处理时使用了JSONArray处理

### ISSUE THREAD

**Issue by liudeiang** [jeecgboot/JimuReport#2261]
##### 版本号：
1.6.5

##### 问题描述：
API 数据返回非集合数据，新增接口时没勾选集合。处理时使用了JSONArray处理

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/136183945/9fbea740-d249-4288-ad93-b62014eb4c49)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
提供测试数据

**Comment by hoperunChen** [comment]
已修复，待新版本发布
