### ISSUE TITLE
横向纵向组合动态列分组 函数处理无法动态扩展

### ISSUE THREAD

**Issue by MangYuan** [jeecgboot/JimuReport#2262]
##### 错误日志&截图：
![1](https://github.com/jeecgboot/JimuReport/assets/21568040/c9e05842-5d7f-4c77-8330-619de5f752bb)
![2](https://github.com/jeecgboot/JimuReport/assets/21568040/05300a80-42d7-42a8-a46a-15002e57a039)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
其他暂不支持
