### ISSUE TITLE
跑马灯动态数据设置接口返回数据后，预览没有数据

### ISSUE THREAD

**Issue by cai1449074828** [jeecgboot/JimuReport#2263]
##### 问题描述：

跑马灯动态数据设置接口返回数据后，预览没有数据
##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/15009292/25bc8962-1224-4230-9ba7-137f3f60ef68)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
已修改
