### ISSUE TITLE
多张图片显示

### ISSUE THREAD

**Issue by yhan219** [jeecgboot/JimuReport#2264]
##### 版本号：
1.6.5

##### 问题描述：
现在图片组件只能展示一张图片，我想展示多张图片要怎么处理。后端返回的是图片数组或逗号分隔的图片地址

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by yhan219** [comment]
或者有没有替代方案，比如循环块或者横向分组的，我试了下没弄出来

**Comment by zhangdaiscott** [comment]
不支持
