### ISSUE TITLE
报表条件表达式case无短路特性

### ISSUE THREAD

**Issue by NapChen** [jeecgboot/JimuReport#2265]
##### 版本号：
1.6.5

##### 问题描述：
使用case时，即使前面的条件成立，也会计算后面的情况，那么就不能用于排除除零的这种情况

##### 错误日志&截图：
无

##### 重现步骤：
任意单元格使用如下条件表达式=case(24==24,1,1/(24-24))，依旧会报除零错误

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by hoperunChen** [comment]
已修复，待新版本发布
