### ISSUE TITLE
导出 excel 文件，数据的千分位丢失问题

### ISSUE THREAD

**Issue by tonyyls** [jeecgboot/JimuReport#2267]
##### 问题描述：

1、数据123456.78，格式调整为数字且设置成2位小数，预览时见到的是123,456.78(正确的效果)，双击以及EXCEL下载后显示的都是123456.78（千分位丢失）
2、通过DBSUM函数获得一个数字987654.32，格式调整为数字且设置成2位小数，预览时见到的是987,654.32(正确的效果)，双击以及EXCEL下载后显示的是987654.32（千分位丢失）

##### 错误日志&截图：
预览效果：
![image](https://github.com/jeecgboot/JimuReport/assets/1624736/ec8ffb20-2c94-4521-b11c-cb0abec043f8)

导出后的效果：
![image](https://github.com/jeecgboot/JimuReport/assets/1624736/24018c3e-11d8-4544-88d6-76d62fd7480f)

双击设计页面单元格的效果：
![image](https://github.com/jeecgboot/JimuReport/assets/1624736/b5535345-f382-4437-bad9-c50bb1b75d15)

![image](https://github.com/jeecgboot/JimuReport/assets/1624736/54341608-1fcd-4d11-8027-19337bc57841)

##### 重现步骤：
如上图

**Comment by lvdandan16** [comment]
归集到 #138
