### ISSUE TITLE
存在风险漏洞被攻击

### ISSUE THREAD

**Issue by xiaopan50313** [jeecgboot/JimuReport#2268]
##### 版本号：
1.5.8

##### 问题描述：
存在漏洞，被挖矿软件攻击

##### 错误日志&截图：
![b17ab2c2ad7277b4d56701e40eeb995](https://github.com/jeecgboot/JimuReport/assets/50644232/4d137e32-cca4-4dad-b20f-7baf571ce810)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
看日志，升级版本
