### ISSUE TITLE
升级到1.6.5版本后，sql脚本中带--注释的，会提示有sql注入风险

### ISSUE THREAD

**Issue by yejunxiang** [jeecgboot/JimuReport#2270]
##### 版本号：
1.6.5

##### 问题描述：
带有注释, 格式: -- 注释内容
就会提示sql注入风险

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/37584177/6502d033-d910-49a8-a995-fd3deac12d3c)

##### 重现步骤：
新建查询报表，增加注释: -- 测试注释
然后预览，即可重现

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by yejunxiang** [comment]
麻烦能尽快修复并解决，很急，项目很多，逐个替换注释，比较麻烦

**Comment by zhangdaiscott** [comment]
为了安全，这个不允许出现注释
