### ISSUE TITLE
本地debug模式运行后，Init JimuReport Config就卡主了

### ISSUE THREAD

**Issue by cloudwinter** [jeecgboot/JimuReport#2272]
##### 版本号：
1.6.5

##### 问题描述：
ruoyi集成jmreport之后，本地debug模式运行后，就卡主了

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/8609643/5ded88f8-6e41-436b-9d99-2484a4f60ba0)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
minidao的扫码路径配置下
