### ISSUE TITLE
散点图动态设置颜色

### ISSUE THREAD

**Issue by ccubec** [jeecgboot/JimuReport#2273]
##### 版本号：
散点图能动态设置颜色吗

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by ccubec** [comment]
能自定义 散点图颜色吗？

**Comment by lvdandan16** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/54099258/a8388a94-3c90-4f7d-87cf-c080a19e685c)
使用自定义配色

**Comment by ccubec** [comment]
这个定义的范围变化了，自定义颜色就失效了，能修改默认颜色吗？

**Comment by ccubec** [comment]
> ![image](https://private-user-images.githubusercontent.com/54099258/290749389-a8388a94-3c90-4f7d-87cf-c080a19e685c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NjAzODYsIm5iZiI6MTcwMjg2MDA4NiwicGF0aCI6Ii81NDA5OTI1OC8yOTA3NDkzODktYTgzODhhOTQtM2M5MC00ZjdkLTg3Y2YtYzA4MGExOWU2ODVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDAwNDEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZDJlNWVlYzc0OGUwMjkzY2ViYmNkMDZhN2FmZmFmNTQ2OTJiNWNkYjZlY2E5N2NhZjY0M2ZhMTRhYWM3ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2-92s37bLwoC9J9KQugzdQiWGApOXzUEVhcg8tFyLz0) 使用自定义配色

这个范围变化了，颜色就恢复默认值了，颜色的默认值能修改吗
