### ISSUE TITLE
积木报表不分页时 10000条导出， page-size-number参数不起作用

### ISSUE THREAD

**Issue by gdgzczh** [jeecgboot/JimuReport#2276]
##### 版本号：
积木报表  1.6.4

##### 问题描述：
用api接口取数据时

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 1298191366** [comment]
目前导出excel是根据数据集勾选分页时导出的。你是有什么需求需要不勾选分页时分页导出吗

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
