### ISSUE TITLE
积木报表横向扩展动态部分缺少显示不知原因，但查询姓名却可以显示

### ISSUE THREAD

**Issue by afearboy** [jeecgboot/JimuReport#2277]
##### 版本号：
3.6.1

##### 问题描述：
在积木报表中，使用来的横向动态扩展，但发现部分数据的横向表头不显示，不知原因。数据都是一样的。

##### 截图&代码：
报表错误如图
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/82691864/93c77556-6058-4168-968e-5ff9b28fce3f)

数据如下：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/82691864/d0266a8b-d4d1-4e61-ae59-4f935c3bc6ab)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by lvdandan16** [comment]
横向扩展第一行数据需要时完整的，参考文档：特殊规则
https://help.jeecg.com/jimureport/group/directionDynamic.html

**Comment by afearboy** [comment]
我确信每条都有记录，专门看了你们说的第一条记录必须有值。就是把行记录转为了列显示而已，但头没有。
----- 原始邮件 -----
发件人：lvdandan16 ***@***.***>
收件人：jeecgboot/JimuReport ***@***.***>
抄送人：afearboy ***@***.***>,  Author ***@***.***>
主题：Re:_[jeecgboot/JimuReport]_积木报表横向扩展动态部分缺少显示不知原因，但查询姓名却可以显示_(Issue_#2277)
日期：2023年12月15日 15点01分


Reopened #2277.

**Comment by lvdandan16** [comment]
那就把你的报表配置及数据导出来，或者在我们积木官网做个示例，我们复现一下

**Comment by afearboy** [comment]
多谢回复，我知道原因了。这个可能是缓存问题，但很奇怪的就是，我另外做一份同样的就可以出来，那个不出来的怎么刷新都不行。


----- 原始邮件 -----
发件人：lvdandan16 ***@***.***>
收件人：jeecgboot/JimuReport ***@***.***>
抄送人：afearboy ***@***.***>,  Author ***@***.***>
主题：Re:_[jeecgboot/JimuReport]_积木报表横向扩展动态部分缺少显示不知原因，但查询姓名却可以显示_(Issue_#2277)
日期：2023年12月22日 16点47分


那就把你的报表配置及数据导出来，或者在我们积木官网做个示例，我们复现一下
