### ISSUE TITLE
api解析json格式以及主子表主表数据多条的情况下无法分开显示

### ISSUE THREAD

**Issue by xtsora** [jeecgboot/JimuReport#228]
##### 版本号：
1.3.2
##### 问题描述：
1：目前版本data中参数不支持数组集合，过于简单了，建议增加，这样的同时创建报表的时候可以使用#{apitest.xxx.xxx}这种方式
2：主子表（无法查询全部）主表数据多条会导致数据都显示在一张报表上，以及子表数据无法对应上是哪一条主表，从而无法区分
强烈建议官方更新

##### 截图&代码：

![image](https://user-images.githubusercontent.com/70882167/116049110-80c45880-a6a8-11eb-8b06-9ae51c4cea67.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xtsora** [comment]
请官方回复

**Comment by zhangdaiscott** [comment]
先归集到https://github.com/jeecgboot/JimuReport/issues/138

**Comment by xinxingzhao** [comment]
这个提议好

**Comment by tb2888** [comment]
这问题解决了么？Api数据集
![image](https://user-images.githubusercontent.com/55084864/222079880-17210cd5-9c54-4f0b-8420-d6767d8d53b8.png)
