### ISSUE TITLE
提示“”

### ISSUE THREAD

**Issue by guxiaoni** [jeecgboot/JimuReport#2280]
##### 版本号：
1.6.6

##### 问题描述：
添加源数据库，点击测试，提示“权限不足，请添加角色角色权限”

##### 错误日志&截图：

![@K9HOIYS$RAVIX_HVMML(VX](https://github.com/jeecgboot/JimuReport/assets/53426954/945e2b3f-62be-4691-97d4-61c83a79da66)

##### 重现步骤
点击添加数据源，点击测试按钮：

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/jimureport/prodSafe.html
