### ISSUE TITLE
使用积木报表设置颜色和分组求和会有“表达式渲染错误的单元格：R5,E5,R7,E7,R9,E9,R14,E14”报错的问题

### ISSUE THREAD

**Issue by zengxiaokang1** [jeecgboot/JimuReport#2281]
##### 版本号：
1.5.8

##### 问题描述：
积木报表设置颜色和分组求和会有“表达式渲染错误的单元格：R5,E5,R7,E7,R9,E9,R14,E14”

##### 错误日志&截图：
<img width="1266" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/50865941/963edf88-43b7-49ce-bd90-d48a60d59dbe">

##### 重现步骤：
首先进行分组合并在一个列上面进行修改底纹颜色如下代码：
=(let sex= #{peReport.priceWeight};
 if(sex > #{peReport.qbrActualAllocation}){
     color(#{peReport.priceWeight},'red','yellow')
}elsif(sex== 0){
   0
}else{
     #{peReport.priceWeight}
})

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Howike** [comment]
1.6.6也有这个问题，通过两列进行数学运算也会提示，如=#{peReport.priceWeight/#{peReport.qbrActualAllocation}*100

**Comment by Howike** [comment]
1.6.6也有这个问题，通过两列进行数学运算也会提示，如=#{peReport.priceWeight/#{peReport.qbrActualAllocation}*100

**Comment by Howike** [comment]
1.6.6也有这个问题，通过两列进行数学运算也会提示，如=#{peReport.priceWeight/#{peReport.qbrActualAllocation}*100

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
