### ISSUE TITLE
报表动态列和固定列求和问题

### ISSUE THREAD

**Issue by 12wmy** [jeecgboot/JimuReport#2283]
版本号：1.6.6

 问题描述：报表有动态列和固定列，只能对动态列求和，不能对固定列求和

 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/149373744/39bd9fae-cae7-4c99-a925-c2c967b675ba)

 重现步骤：

 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
怎么设计的？

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by lvdandan16** [comment]
已修复，待新版本发布
