### ISSUE TITLE
升级版本后，设计报表显示无权限

### ISSUE THREAD

**Issue by liyuhui98** [jeecgboot/JimuReport#2284]
##### 版本号：
1.6.6

##### 问题描述：
升级版本后，设计报表显示无权限

##### 错误日志&截图：
![图片](https://github.com/jeecgboot/JimuReport/assets/81678276/1a02deef-003f-4544-a95c-bab74cfed48c)

已实现getToken方法，getRole方法（但进入设计页面上实际并未进入该方法，怀疑是否该步骤错误）
![图片](https://github.com/jeecgboot/JimuReport/assets/81678276/1199d44a-bc3f-4b31-8281-0c99c7eb61d2)
![图片](https://github.com/jeecgboot/JimuReport/assets/81678276/3c810409-34e7-4803-89b9-f1a196784cb8)

模式为开发模式，lowCodeMode: dev
在升级至1.6.2之后的版本，用于对应角色的用户拥有设计角色，具体如何分配角色呢，未找到相关文档，是否是getRole方法实现错误？
##### 重现步骤：
在升级至1.6.2之后的版本，

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你这样发帖，我们无从下手
