### ISSUE TITLE
Sql预览时空指针异常

### ISSUE THREAD

**Issue by wangchaolong9331** [jeecgboot/JimuReport#2285]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/43001806/a9fa7cf0-9d05-49f4-a4d7-2800621d10e2)
![image](https://github.com/jeecgboot/JimuReport/assets/43001806/1df103cf-c62c-4540-a232-586c09974e8d)
![image](https://github.com/jeecgboot/JimuReport/assets/43001806/192171aa-e4fa-4f79-acad-50b35781599a)
![image](https://github.com/jeecgboot/JimuReport/assets/43001806/7f845df0-f314-4d09-b3e2-dbd9a38755ec)

##### 重现步骤：新建报表-->SQL数据集-->填写SQL->SQL解析
![image](https://github.com/jeecgboot/JimuReport/assets/43001806/447bd5e5-97c5-4bb4-8797-8661bb929fd0)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
先升级到最新版

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
