### ISSUE TITLE
jdk17+启动报错

### ISSUE THREAD

**Issue by 203579397** [jeecgboot/JimuReport#2286]
##### 版本号：
1.5.9

##### 问题描述：
jdk17+启动报错

##### 错误日志&截图：
15:48:08.079 [main] INFO  o.a.c.c.StandardService - [log,173] - Stopping service [Tomcat]
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
15:48:08.192 [main] WARN  o.a.c.l.WebappClassLoaderBase - [log,173] - The web application [ROOT] appears to have started a thread named [Thread-2] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@17.0.9/sun.net.dns.ResolverConfigurationImpl.notifyAddrChange0(Native Method)
 java.base@17.0.9/sun.net.dns.ResolverConfigurationImpl$AddressChangeListener.run(ResolverConfigurationImpl.java:176)
15:48:14.488 [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter - [report,40] - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field dataSourceDao in org.jeecg.modules.jmreport.desreport.service.a.j required a bean of type 'org.jeecg.modules.jmreport.desreport.dao.JimuReportDataSourceDao' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'org.jeecg.modules.jmreport.desreport.dao.JimuReportDataSourceDao' in your configuration.

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 203579397** [comment]
15:48:08.079 [main] INFO  o.a.c.c.StandardService - [log,173] - Stopping service [Tomcat]
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
15:48:08.192 [main] WARN  o.a.c.l.WebappClassLoaderBase - [log,173] - The web application [ROOT] appears to have started a thread named [Thread-2] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@17.0.9/sun.net.dns.ResolverConfigurationImpl.notifyAddrChange0(Native Method)
 java.base@17.0.9/sun.net.dns.ResolverConfigurationImpl$AddressChangeListener.run(ResolverConfigurationImpl.java:176)
15:48:14.488 [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter - [report,40] - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field dataSourceDao in org.jeecg.modules.jmreport.desreport.service.a.j required a bean of type 'org.jeecg.modules.jmreport.desreport.dao.JimuReportDataSourceDao' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'org.jeecg.modules.jmreport.desreport.dao.JimuReportDataSourceDao' in your configuration.

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/jimureport/quick.html


SpringBoot3系列支持
SpringBoot3+JDK17 版本（需要配置[JEECG私服](https://help.jeecg.com/java/setup/maven.html)）

```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot3-starter</artifactId>
  <version>1.6.6-beta2</version>
</dependency>
```

**Comment by 203579397** [comment]
我的运行jvm是17+，但source是1.8。这样也不行吗

**Comment by zhangdaiscott** [comment]
不清楚，为什么不一致

**Comment by 203579397** [comment]
@zhangdaiscott 
我们为了向后兼容高版本jdk，一直都是这么做的。
不过也没关系，我已经知会项目组成员了。
感谢
