### ISSUE TITLE
1、数据无法显示（部分）2、分版下面的数据无法放置

### ISSUE THREAD

**Issue by Stars-XK** [jeecgboot/JimuReport#2287]
##### 问题描述：
1、通过sql查询是返回了数据，但是拖动到表格中显示为空。直接填写文本可以显示，但同一个位置拖入数据就无法显示。详细看截图

2、将多个sql查询回来的数据《列表，每列固定24行》放入同一行展示，设置分版后，下面第25行无法再次放入值，否则就会报错无法打开预览。，详细看截图

##### 错误日志&截图：
1、
![image](https://github.com/jeecgboot/JimuReport/assets/39972726/7830a08c-bede-446c-9801-29d855a5ae16)

![image](https://github.com/jeecgboot/JimuReport/assets/39972726/0f812e68-1af5-4348-bb15-306a709e78f0)

![image](https://github.com/jeecgboot/JimuReport/assets/39972726/5c38236d-197b-443e-b2f3-4df23060de08)

2、
可以打开的情况
![image](https://github.com/jeecgboot/JimuReport/assets/39972726/b641f168-aeb7-408d-b532-30d2284ef0fd)

无法打开的情况
报错： Cannot invoke "com.alibaba.fastjson.JSONObject.keySet()" because "" is null

**Comment by lvdandan16** [comment]
请在积木官网做个示例，我们复现一下

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
