### ISSUE TITLE
多租户模式下，报表钻取url参数没有tenantId

### ISSUE THREAD

**Issue by caocz** [jeecgboot/JimuReport#2288]
##### 版本号：

1.6.6
##### 问题描述：
多租户模式下，报表钻取url参数没有tenantId, 导致下钻报表打不开。

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/29848862/9f63829c-678b-455d-a4b9-1c7921aecfbb)
![image](https://github.com/jeecgboot/JimuReport/assets/29848862/ee69cb7e-cc9a-4cc8-8f56-47d97a29732d)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
