### ISSUE TITLE
动态列被覆盖问题

### ISSUE THREAD

**Issue by superman4808** [jeecgboot/JimuReport#2290]
##### 版本号：
v1.6.3

##### 问题描述：
固定列字段在动态列字段之后，动态列部分字段会被固定列覆盖，如何使动态列字段不被覆盖？

##### 错误日志&截图：
![动态列](https://github.com/jeecgboot/JimuReport/assets/121927607/b4630fe8-db73-4eba-ab77-970cdc7d197c)
![动态列被覆盖](https://github.com/jeecgboot/JimuReport/assets/121927607/26f96ae8-8a04-4047-a50c-6af68167d70e)

##### 重现步骤：
[报表配置.zip](https://github.com/jeecgboot/JimuReport/files/13733871/default.zip)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
目前不支持动态列后加数据
