### ISSUE TITLE
sql 解析提示 签名校验失败

### ISSUE THREAD

**Issue by huadanzhilei** [jeecgboot/JimuReport#2296]
##### 版本号：
1.6.5

##### 问题描述：

sql 解析提示 签名校验失败
##### 截图&代码：

<img width="1055" alt="1702946707685" src="https://github.com/jeecgboot/jeecg-boot/assets/42882769/b64df8ce-01ee-4d43-bce0-7cf7dae7e795">

**Comment by 1298191366** [comment]
经测试未复现，我怀疑是你中文乱码问题，你试试英文还有没有问题
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/57f1eef2-b5aa-41fe-823e-5b58c1be7dea)
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/99680784-374d-4f07-9df8-da0d1b260b34)
正常情况下
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/fc95d3ce-702a-4d96-b1df-dc7767ed7638)
