### ISSUE TITLE
积木报表打印报表的时候数据源只要配置成SQL数据集 就不能打印和导出

### ISSUE THREAD

**Issue by xiaoshuai220** [jeecgboot/JimuReport#2298]
##### 错误日志&截图：
![bug1](https://github.com/jeecgboot/JimuReport/assets/53173115/08dcd11e-645f-45bd-9e43-73420eab93dd)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
未复现过此问题，看看有没有报错信息

**Comment by xiaoshuai220** [comment]
感谢，之前的报错是配置SQL数据集的时候没有加引号。如下图
![bugok](https://github.com/jeecgboot/JimuReport/assets/53173115/d0f82e55-eb38-4163-a3cd-9935e94796ec)
现在还有一个问题，就是打印的时候SQL数据集配置的数据打印预览的时候数据不出来。如下图
![bug2](https://github.com/jeecgboot/JimuReport/assets/53173115/218fbb18-f30f-4737-a827-e53d92f521d5)
zhge这个是后台日志
![bug3](https://github.com/jeecgboot/JimuReport/assets/53173115/a9a7c593-a255-46d6-93b2-672a2cf88ecd)
现在是打印的时候浏览器后没有报错，后台数据解析为空。如下图
![Uploading bug3.jpg…]()

**Comment by lvdandan16** [comment]
在积木报表官网做个示例，我们复现一下

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
