### ISSUE TITLE
导出Excel时图片未导出

### ISSUE THREAD

**Issue by superman4808** [jeecgboot/JimuReport#2300]
##### 版本号：
V1.6.3

##### 问题描述：
导出Excel时图片未导出

##### 错误日志&截图：
![导出Excel](https://github.com/jeecgboot/JimuReport/assets/121927607/5bae6ef9-736f-4fd6-a01d-922fee065caa)

![图片未导出](https://github.com/jeecgboot/JimuReport/assets/121927607/b452f4de-7099-4fb2-a8e9-309b0d8012f3)

##### 重现步骤：

[脚本.zip](https://github.com/jeecgboot/JimuReport/files/13748119/default.zip)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
未复现，你的图片是什么格式的，因为图片是你本地的，所以我上传了我本地的。分组是因为没有数据。你可以把你的分组删掉，导出在试一下，如果是分组问题，请提供一下表结构和测试数据
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/ed38b965-328c-4e83-a705-ab4327b97efe)

**Comment by superman4808** [comment]
您好！我这边上传的图片是png格式的。图片刚刚上传时预览和导出是没有问题的，但是多次重复预览导出或者过了几天后再次打开预览导出会有图片缺失的概率，刷新后图片可能出来也可能缺失




归来仍是少年
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月25日(星期一) 下午4:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 导出Excel时图片未导出 (Issue #2300)





 
未复现，你的图片是什么格式的，因为图片是你本地的，所以我上传了我本地的。分组是因为没有数据。你可以把你的分组删掉，导出在试一下，如果是分组问题，请提供一下表结构和测试数据
 image.png (view on web)

**Comment by 1298191366** [comment]
好的，我追踪一下，看看能不能复现

**Comment by 1298191366** [comment]
问题复现不出来，你看看你前后端有没有报错信息，或者升级到最新版本尝试一下
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.6.6</version>
</dependency>
```

**Comment by superman4808** [comment]
谢谢！没事了，是服务器的原因




归来仍是少年
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月27日(星期三) 下午4:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 导出Excel时图片未导出 (Issue #2300)





 
问题复现不出来，你看看你前后端有没有报错信息，或者升级到最新版本尝试一下
 <dependency&gt;   <groupId&gt;org.jeecgframework.jimureport</groupId&gt;   <artifactId&gt;jimureport-spring-boot-starter</artifactId&gt;   <version&gt;1.6.6</version&gt; </dependency&gt;
