### ISSUE TITLE
单元格能否对已查询的数据结果集 进行二次 条件筛选填充

### ISSUE THREAD

**Issue by walkdy2019** [jeecgboot/JimuReport#2301]
##### 错误日志&截图：
如下图：
![image](https://github.com/jeecgboot/JimuReport/assets/113163036/bd87b59c-d05c-40a3-838b-cfd64578955f)
可以在单元格上，对数据集结果进行条件筛选后再填充。
比如：对一组数据集结果，在某个单元格上 设置过滤条件，对于记录中 id = 2001 且 date = '2023-12-01'的数据，填充符合该条件的记录中的 creator列值。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
查询条件配置 参考文档：https://help.jeecg.com/jimureport/query/reportQuery.html
单元格上单独设置不支持

**Comment by walkdy2019** [comment]
这个最基础的功能，至今没有解决嘛。我也遇到了，上面给的方法不能解决这个问题，弃用了。
