### ISSUE TITLE
打印下拉的html打印数据与界面不一致

### ISSUE THREAD

**Issue by Fangyi01** [jeecgboot/JimuReport#2303]
##### 问题描述：
同一条数据html打印和canvas打印不一致
#####################html打印
![image](https://github.com/jeecgboot/JimuReport/assets/87565562/c0f40714-a17e-462b-84b5-2dce0eff7aa9)
#####################canvas打印
![image](https://github.com/jeecgboot/JimuReport/assets/87565562/6d8e1702-38cc-40dc-a3f4-710eda4c3bec)

接口参数及返回数据均一致
![image](https://github.com/jeecgboot/JimuReport/assets/87565562/c5902ab8-1f59-480d-a69b-06db617657e9)

##### 错误日志&截图：
同一条数据html打印和canvas打印不一致

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级最新版本，不区分html打印和canvas打印

**Comment by Fangyi01** [comment]
该条数据为
![Uploading image.png…]()
