### ISSUE TITLE
交叉报表，横向合并列后在右侧接着绑定2个普通列，其中最后一列格式错乱

### ISSUE THREAD

**Issue by maming123** [jeecgboot/JimuReport#2304]
##### 问题描述：
我用json数据源创建了一个交叉报表，横向合并列后，如果右侧只绑定一个普通列，那么结果是正常的，但是如果在横向合并列右侧接着绑定2个普通列，那么其中最后一列就和第一列分开很多，好像跑到下一页了。

##### 重现步骤：
json数据源：
`{
    "data": [
        {
            "diqu": "1100工作面",
            "class": "上出口向外20m(下帮)",
            "year": "孔深及煤粉量（kg/m）",
            "mouth": "1-2m",
            "sales": "840.15",
            "dongli":"无",
            "panding":"无冲击 危险性",
            "panding2":"无冲击 危险性"
        },{
            "diqu": "1100工作面",
            "class": "上出口向外20m(下帮)",
            "year": "孔深及煤粉量（kg/m）",
            "mouth": "2-3m",
            "sales": "840.15",
            "dongli":"无",
            "panding":"无冲击 危险性",
            "panding2":"无冲击 危险性"
        },{
            "diqu": "1100工作面",
            "class": "上出口向外20m(下帮)",
            "year": "孔深及煤粉量（kg/m）",
            "mouth": "3-4m",
            "sales": "840.15",
            "dongli":"无",
            "panding":"无冲击 危险性",
            "panding2":"无冲击 危险性"
        },{
            "diqu": "1100工作面",
            "class": "上出口向外50m(下帮)",
            "year": "孔深及煤粉量（kg/m）",
            "mouth": "1-2m",
            "sales": "840.15",
            "dongli":"无",
            "panding":"无冲击 危险性",
            "panding2":"无冲击 危险性"
        },{
            "diqu": "1100工作面",
            "class": "上出口向外110m(下帮)",
            "year": "孔深及煤粉量（kg/m）",
            "mouth": "2-3m",
            "sales": "840.15",
            "dongli":"无",
            "panding":"无冲击 危险性",
            "panding2":"无冲击 危险性"
        },{
            "diqu": "1100工作面",
            "class": "上出口向外30m(下帮)",
            "year": "孔深及煤粉量（kg/m）",
            "mouth": "3-4m",
            "sales": "840.15",
            "dongli":"顶钻",
            "panding":"无冲击 危险性",
            "panding2":"无冲击 危险性"
        }
    ]
}`

报表设计：
<img width="723" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/7600470/1e1b0f5c-b483-4280-a8f4-9d91fbced396">

预览的结果：
<img width="1445" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/7600470/872eac70-ec49-43fc-bb8c-85c9e933acc5">

导出excel的结果：
<img width="1143" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/7600470/ce7a7d0f-81ae-4495-b5c1-e119ef03c38b">

但我预览和下载想得到的结果应该是：
<img width="827" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/7600470/ab31fdfa-62aa-4136-a1e0-935c27e7cfc3">

不清楚是积木的BUG还是不支持 横向分组后再紧接着绑定2个普通列，盼回复

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
目前还不支持横向分组后加列  后续会支持

**Comment by maming123** [comment]
你好，这个后续会支持 有时间计划么？或者购买商业版本会支持的快些么
