### ISSUE TITLE
浏览器页面显示积木报表，免费的可视化报表，是否可以修改配置

### ISSUE THREAD

**Issue by yishuifeixue** [jeecgboot/JimuReport#2305]
##### 版本号：
1.6.0

##### 问题描述：
浏览器页面显示积木报表，免费的可视化报表，是否可以修改配置

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/35915681/2bd20907-3dd7-497b-a968-8c3b586d191f)

##### 重现步骤：
打开配置的报表

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持
