### ISSUE TITLE
嵌入用online在线表单生成的列表

### ISSUE THREAD

**Issue by Fengzhidong** [jeecgboot/JimuReport#2307]
##### 版本号：

3.4.3-beta2
##### 问题描述：
请教一下各位大佬，我想在项目中嵌入用online在线表单生成的列表，如何去嵌入呢？不用菜单引入的话

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档：http://doc.jeecg.com/2373083
