### ISSUE TITLE
数值类型的数据在导出的Excel中并非数值类型

### ISSUE THREAD

**Issue by superman4808** [jeecgboot/JimuReport#2308]
##### 版本号：
V1.6.3

##### 问题描述：
数值类型的数据在导出的Excel中并非数值类型

##### 错误日志&截图：
![数值格式](https://github.com/jeecgboot/JimuReport/assets/121927607/9cd31098-d649-4a2b-a834-60c6413a43a1)
![导出非数值格式](https://github.com/jeecgboot/JimuReport/assets/121927607/e042a221-5db5-44b8-babe-4ef56fb304cc)

##### 重现步骤：
[报表配置.zip](https://github.com/jeecgboot/JimuReport/files/13770479/default.zip)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请升级新版本试一下
