### ISSUE TITLE
快速集成项目demo,新建报表，然后出错

### ISSUE THREAD

**Issue by sssfdfsdf** [jeecgboot/JimuReport#2309]
##### 版本号：
JimuReport v1.6.6版本发布(绿色免安装版)

##### 问题描述：
按照系统示例的说明，在浏览器中输入http://localhost:8085/jmreport/list，然后，点击新建报表，然后出现页面错误

##### 错误日志&截图：
![微信图片_20231227132347](https://github.com/jeecgboot/JimuReport/assets/154954124/43014c75-e1bb-4036-b560-e286ac9f77d0)

![微信图片_20231227132400](https://github.com/jeecgboot/JimuReport/assets/154954124/e2ca30e6-a370-4469-9771-36c6d9036db6)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
报什么错，错误信息贴一下

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
