### ISSUE TITLE
扩展表格+固定打印页尾时会多生成一个空白的页尾

### ISSUE THREAD

**Issue by yqf0410** [jeecgboot/JimuReport#2311]
##### 版本号：
1.6.6

##### 问题描述：
扩展表格+固定打印页尾时会多生成一个空白的页尾

##### 错误日志&截图：
![微信截图_20231228170745](https://github.com/jeecgboot/JimuReport/assets/28585316/2c945f9d-a852-4779-8702-2f2b8972f593)
![image](https://github.com/jeecgboot/JimuReport/assets/28585316/a388abf3-2ece-42d8-b894-78a01339f751)

##### 重现步骤：
1、创建扩展表格
2、在表格底部设置固定打印页尾
3、预览、打印

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请在积木官网做个示例，我们复现一下

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
