### ISSUE TITLE
是否有方案可完成对预览数据进行二次修改，保存后可再次展示的功能

### ISSUE THREAD

**Issue by maming123** [jeecgboot/JimuReport#2313]
##### 问题描述：
您好，我有这样一个问题，想咨询下是否可以实现。

目前据我所知 通过积木报表设计出来的报表，可被预览、打印、导出。

需求如下： 
通过设计模板生成的预览数据中，是否有办法或者变通的途径 可以让用户手动修改生成的预览数据，修改后回存到数据库，然后可再次展示出修改后的结果。

主要目的是用户想针对通过模板生成的excel进行二次修改保存，归档。

这个需求按理解应该是填报功能。

如果目前没有此功能，但购买商业版的源代码，在提供技术支持的情况下可以实现 ，我们也可以考虑。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持数据填报
