### ISSUE TITLE
积木报表调用API报错：请升级？

### ISSUE THREAD

**Issue by susuyas** [jeecgboot/JimuReport#2314]
##### 错误日志&截图：
<img width="1530" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/89789265/c1031b7d-139b-416f-9e25-641ec6582213">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
？什么情况下导致

**Comment by zhangdaiscott** [comment]
这个错误应该是你调用的接口返回的吧

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
