### ISSUE TITLE
sql语句优化

### ISSUE THREAD

**Issue by wqb553001** [jeecgboot/JimuReport#2315]
##### 问题描述：
      目前的SQL语句中的 INSERT，都是采用一条记录一条插入语句，执行耗时过长：
      `Summary: 2525 of 2525 statements executed in 3 m 32 s 983 ms (6973117 symbols in file)`

      建议调整为批量 INSERT ，能大大提升效率：
      `Summary: 99 of 99 statements executed in 28 s 705 ms (6882338 symbols in file)`
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
这是什么功能？不是积木报表吧  积木报表现在不支持insert
