### ISSUE TITLE
为什么我后端接口请求可以请求到积木报表list接口 前端页面展示不出来

### ISSUE THREAD

**Issue by weijunzhigu** [jeecgboot/JimuReport#2317]
##### 版本号：
1.5.2

##### 问题描述：
后端接口请求可以请求到积木报表list接口 前端页面展示不出来 前端就一直处于加载中 如果不关闭在线设计这个页面 项目里其他的页面的接口都会超时了

##### 错误日志&截图：
![DHMSO1CZ8SBH)2}V_3U%BDX_tmb](https://github.com/jeecgboot/JimuReport/assets/105276313/32626c90-4bc0-48aa-8532-46ebd79f178b)
![S9VZ3S1}@PGO4CY9FA8HB4E](https://github.com/jeecgboot/JimuReport/assets/105276313/ada7c013-fd17-426d-98fc-c2853a632cd8)
![X`X~( RKHKXH57~ZO0X9%31_tmb](https://github.com/jeecgboot/JimuReport/assets/105276313/6f30d093-fead-41a3-abf5-d4db563b265d)
##### 重现步骤：
积木报表的表已经在jeecgboot数据库中
1.引入依赖  
        <jimureport-spring-boot-starter.version>1.5.2</jimureport-spring-boot-starter.version>

 <dependency>
            <groupId>org.jeecgframework.jimureport</groupId>
            <artifactId>jimureport-spring-boot-starter</artifactId>
            <version>${jimureport-spring-boot-starter.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>autopoi-web</artifactId>
                    <groupId>org.jeecgframework</groupId>
                </exclusion>
            </exclusions>
        </dependency>
2.菜单jeecgboot自带的报表设计菜单里的积木报表
![image](https://github.com/jeecgboot/JimuReport/assets/105276313/09ddb580-16e9-48a4-b51d-3913c180d7c9)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by weijunzhigu** [comment]
这是我的积木报表的菜单项 
![image](https://github.com/jeecgboot/JimuReport/assets/105276313/fe9c0744-7879-462c-9bde-554933544863)

**Comment by weijunzhigu** [comment]
jeecgboot前端是vue2的版本 		后端是<jeecgboot.version>3.4.0-SNAPSHOT</jeecgboot.version>

**Comment by weijunzhigu** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/105276313/5ddc8985-117d-490e-887b-2e5ec9da4831) 
进一步发现是请求这个js的时候一直没有返回 这是为什么
![image](https://github.com/jeecgboot/JimuReport/assets/105276313/cb1a88ff-36d4-4dae-84d1-b9a479bad313)
![image](https://github.com/jeecgboot/JimuReport/assets/105276313/5e77b6c6-0fac-4101-975e-c37b6b1c8ff2) jia'z加载不出这个js

**Comment by weijunzhigu** [comment]
这个js为什么会卡死呢？

**Comment by lvdandan16** [comment]
看报什么错

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
