### ISSUE TITLE
mysql where语句中子查询中in语句带参数工作不正常

### ISSUE THREAD

**Issue by wuyb66** [jeecgboot/JimuReport#2318]
##### 版本号：1.6.6
    <properties>
        <jimureport.version>1.6.6</jimureport.version>
        <java.version>1.8</java.version>
        <minio.version>8.0.3</minio.version>
        
        <mysql-connector-java.version>8.0.27</mysql-connector-java.version>
    </properties>
##### 问题描述：
mysql where语句中子查询中in语句带参数工作不正常
下面查询语句不能正常工作：
```sql
select count(*) as total_devices  from sys_robot_task_device 
where robot_task_id in (SELECT
	DISTINCT robot_task_id
FROM sys_robot_task
WHERE start_time >= '${start_time}' AND end_time <= '${end_time}'
  AND (${task_ids} IS NULL OR task_id IN (${task_ids}))
  AND (${robot_ids} IS NULL OR robot_id IN (${robot_ids}))
 )
```
去掉带参数in语句正常：
```sql
select count(*) as total_devices  from sys_robot_task_device 
where robot_task_id in (SELECT
	DISTINCT robot_task_id
FROM sys_robot_task
WHERE start_time >= '${start_time}' AND end_time <= '${end_time}'
 )
```
不使用参数也正常：
```sql
 select count(*) as total_devices  from sys_robot_task_device 
where robot_task_id in (SELECT
	DISTINCT robot_task_id
FROM sys_robot_task
WHERE start_time >= '2023-12-01 00:00:00' AND end_time <= '2023-12-31 00:00:00'
  AND ('6b16952f060046709f601d1d9f67cd40' IS NULL OR task_id IN ('6b16952f060046709f601d1d9f67cd40'))
  AND ('b2bed7dd605848aa828060340a9f6a33' IS NULL OR robot_id IN ('b2bed7dd605848aa828060340a9f6a33'))
 )
```

##### 错误日志&截图：
 where语句中子查询中in语句带参数log：
2023-12-31 16:10:16.761 [http-nio-8085-exec-6] INFO  org.jeecg.modules.jmreport.desreport.service.a.e:291 - ------报表【inspect_result_total_stat】，查询的sql: select count(*) as total_devices  from sys_robot_task_device 
where robot_task_id in (SELECT
	robot_task_id
FROM sys_robot_task
WHERE start_time >= :start_time AND end_time <= :end_time
  AND (:task_ids IS NULL OR task_id IN (:task_ids))
  AND (:robot_ids IS NULL OR robot_id IN (:robot_ids))
group by robot_task_id
 )
2023-12-31 16:10:16.761 [http-nio-8085-exec-6] INFO  org.jeecg.modules.jmreport.desreport.service.a.e:292 - ------报表查询参数: {start_time=2023-12-01 00:00:00, robot_ids='b2bed7dd605848aa828060340a9f6a33', end_time=2023-12-31 23:59:59, task_ids='6b16952f060046709f601d1d9f67cd40'}
2023-12-31 16:10:16.762 [http-nio-8085-exec-6] INFO  org.jeecg.modules.jmreport.desreport.util.g:1490 - order by 之前的sql select count(*) as total_devices  from sys_robot_task_device 
where robot_task_id in (SELECT
	robot_task_id
FROM sys_robot_task
WHERE start_time >= :start_time AND end_time <= :end_time
  AND (:task_ids IS NULL OR task_id IN (:task_ids))
  AND (:robot_ids IS NULL OR robot_id IN (:robot_ids))
group by robot_task_id
 )

##### 重现步骤：
建立主表、子表，查询子表，其中子表的主表id要在主表条件查询结果之中。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 1298191366** [comment]
1.6.2版本之后in需要使用函数
参考文档：https://help.jeecg.com/jimureport/query/function.html
