### ISSUE TITLE
导出将近20万条数据到Excel时报内存溢出

### ISSUE THREAD

**Issue by besthui0323** [jeecgboot/JimuReport#2319]
##### 版本号：
1.5.6

##### 问题描述：
我在执行方法：
```java
private IJmReportExportExcel exportExcel;
...
Map localMap = this.exportExcel.exportExcel(str, localJSONObject, localJSONArray);
```
将20万条数据导出到Excel时（我希望这20万条数据导出个一个sheet中，所以我yml中设置了page-size-number: 1000000），报了内存溢出的报错，我本地调试的电脑使用的内存是32G，下面是报错截图。我该如何在不增大内存的情况下解决我的问题呢？请求大佬能给出一个解决方案，感谢感谢！！！

##### 错误日志&截图：
<img width="923" alt="内存溢出报错" src="https://github.com/jeecgboot/JimuReport/assets/126238833/8181ee68-08da-44f3-8dd0-5c4752e024d1">

##### 重现步骤：
<img width="774" alt="企业微信截图_17040148515620" src="https://github.com/jeecgboot/JimuReport/assets/126238833/fc4fc802-2337-4b47-9721-0a9a8012773c">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
归集：#138
