### ISSUE TITLE
sql中使用year_month作为查询条件会报错，使用的是mysql

### ISSUE THREAD

**Issue by lishijiajava** [jeecgboot/JimuReport#2322]
##### 版本号：
1.6.1

##### 问题描述：
我的sql语句中有一个year_month年月字段，配置查询条件时，选择年月查询会报错。解析出来的sql有问题
select * from (SELECT t.`year_month`,t.institution_num,t.institution_name,t.account_no,t.custom_name,t.contract_no,t.contract_amt,t.loan_bal,t.deposit_bal,t.deposit_curr_month_avg_bal,t.deposit_curr_year_avg_bal FROM `system_loan_deposit_report` t where t.deleted = 0) jeecg_rp_temp where year_month= '2024-01' 
需要改成`year_month`= '2024-01'   才能在工具中执行
![image](https://github.com/jeecgboot/JimuReport/assets/139893640/1e0a6f7c-c41c-44f8-923a-63351c3c0eaa)

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/139893640/203be7ee-631e-49bf-b64d-3dbd9cab4f25)

##### 重现步骤：
![image](https://github.com/jeecgboot/JimuReport/assets/139893640/4eb673ac-93de-4c9f-a09e-5c943bf49339)
![image](https://github.com/jeecgboot/JimuReport/assets/139893640/71af386c-f8db-475a-b45d-c996ca367935)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
你可以使用as作为字段名称，查询就不会报错了
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/d1aea373-efda-4d7f-a33a-c5acbfb852f5)
