### ISSUE TITLE
POST请求大JSON入参传递问题

### ISSUE THREAD

**Issue by 18207556302** [jeecgboot/JimuReport#2324]
##### 错误日志&截图：
页面截图：
![image](https://github.com/jeecgboot/JimuReport/assets/44963951/91cc34b3-7f3e-40c3-aa10-b863cd2a09e9)
后端错误日志：
![image](https://github.com/jeecgboot/JimuReport/assets/44963951/4c7e0efe-bb44-406e-8bd1-44d28b0c3078)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你这个不符合规范

**Comment by 18207556302** [comment]
那我要发送POST的API请求，如何操作

**Comment by 18207556302** [comment]
大佬。POST带JSON入参的，咋操作啊。给个建议啊

**Comment by lvdandan16** [comment]
post请求参考文档：https://help.jeecg.com/jimureport/queryCriteria/apiInterface.html
