### ISSUE TITLE
导出报表失败 The maximum number of Cell Styles was exceeded. You can define up to 64000 style in a .xlsx

### ISSUE THREAD

**Issue by csego** [jeecgboot/JimuReport#2325]
##### 版本号：
1.6.6

##### 问题描述：
 当数据量较大时，我的报表 2 万多行，15 个列 导出报表失败

##### 错误日志&截图：
jimureport  | 2024-01-03 17:28:09.136 [http-nio-8085-exec-9] INFO  org.jeecg.modules.jmreport.desreport.service.a.e:329 - ------数据源 dbSourceKey:【881887860297478144】
jimureport  | 2024-01-03 17:28:19.203 [http-nio-8085-exec-12] ERROR o.a.c.c.C.[.[localhost].[/].[dispatcherServlet]:175 - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: The maximum number of Cell Styles was exceeded. You can define up to 64000 style in a .xlsx Workbook] with root cause
jimureport  | java.lang.IllegalStateException: The maximum number of Cell Styles was exceeded. You can define up to 64000 style in a .xlsx Workbook
jimureport  | 	at org.apache.poi.xssf.model.StylesTable.createCellStyle(StylesTable.java:831)
jimureport  | 	at org.apache.poi.xssf.usermodel.XSSFWorkbook.createCellStyle(XSSFWorkbook.java:754)
jimureport  | 	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createCellStyle(SXSSFWorkbook.java:884)
jimureport  | 	at org.jeecg.modules.jmreport.desreport.service.a.l.a(JmReportExportExcelImpl.java:2628)
jimureport  | 	at org.jeecg.modules.jmreport.desreport.service.a.l.a(JmReportExportExcelImpl.java:1198)
jimureport  | 	at org.jeecg.modules.jmreport.desreport.service.a.l.a(JmReportExportExcelImpl.java:889)
jimureport  | 	at org.jeecg.modules.jmreport.desreport.service.a.l.a(JmReportExportExcelImpl.java:645)
jimureport  | 	at org.jeecg.modules.jmreport.desreport.service.a.l.a(JmReportExportExcelImpl.java:278)
jimureport  | 	at org.jeecg.modules.jmreport.desreport.service.a.l.exportExcel(JmReportExportExcelImpl.java:140)
jimureport  | 	at org.jeecg.modules.jmreport.desreport.a.a.b(DesignReportController.java:1258)
jimureport  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jimureport  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jimureport  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jimureport  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
jimureport  | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
jimureport  | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
jimureport  | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
jimureport  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
jimureport  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
jimureport  | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
jimureport  | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
jimureport  | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
jimureport  | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
jimureport  | 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
jimureport  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:528)
jimureport  | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
jimureport  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:596)
jimureport  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
jimureport  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
jimureport  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
jimureport  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
jimureport  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
jimureport  | 	at org.jeecg.modules.jmreport.common.a.a.doFilter(JimuReportFilter.java:26)
jimureport  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
jimureport  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
jimureport  | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
jimureport  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
jimureport  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
jimureport  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
jimureport  | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
jimureport  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
jimureport  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
jimureport  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
jimureport  | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
jimureport  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
jimureport  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
jimureport  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
jimureport  | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
jimureport  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
jimureport  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
jimureport  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
jimureport  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
jimureport  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
jimureport  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
jimureport  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
jimureport  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
jimureport  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
jimureport  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
jimureport  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)
jimureport  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
jimureport  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
jimureport  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
jimureport  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
jimureport  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
jimureport  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
jimureport  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
jimureport  | 	at java.base/java.lang.Thread.run(Thread.java:829)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不是有个大数据导出按钮吗
