### ISSUE TITLE
部分数据显示缺少标记点

### ISSUE THREAD

**Issue by Bingo333** [jeecgboot/JimuReport#2326]
##### 版本号：
1.6.5

##### 问题描述：
普通折线图--折线设置--标记点，显示缺少部分标记点

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/23184213/4a5021be-b2dc-4b1f-b6a9-9c70facabe4a)

##### 重现步骤：
查询10天等少量数据，显示正常；
查询时间范围比如2个月时，显示缺少部分标记点

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/54099258/253e4f05-0b8e-48fe-916c-5be5df346614)
数据多，显示不全时，下方有日期的才会显示，可以向右拖拽图表显示更多数据
