### ISSUE TITLE
查询模式下拉没有办法根据查询条件进行筛选

### ISSUE THREAD

**Issue by QAWEST** [jeecgboot/JimuReport#2327]
##### 版本号：
1.6.6

##### 问题描述：
数据集勾选查询，查询模式是多选，下拉没有办法根据查询条件进行筛选

##### 错误日志&截图：
![D8B7C9B9-8832-4a6b-AA9A-A754FB2A3008](https://github.com/jeecgboot/JimuReport/assets/87600486/6552f48d-00b7-49f2-8cbb-365a784096a3)
![3244ED29-D821-4b87-9948-63AE27023592](https://github.com/jeecgboot/JimuReport/assets/87600486/e0b3ae05-c8e7-4013-beb8-d2aa3bf38443)
![image](https://github.com/jeecgboot/JimuReport/assets/87600486/e630aa30-5d2f-4fb8-9479-3b6440cdb925)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级这个版本试一下
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.6.6-beta2</version>
</dependency>
```
