### ISSUE TITLE
增加行列锁定

### ISSUE THREAD

**Issue by jingmoo** [jeecgboot/JimuReport#2328]
##### 版本号：
v1.6.6

##### 问题描述：
能否跟Excel一样锁定表头，可锁定行和列，报表太长时拖动滚动条可看到最左边的锁定列或行

##### 错误日志&截图：
无

##### 重现步骤：
无

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
目前不支持
