### ISSUE TITLE
打印页码定制

### ISSUE THREAD

**Issue by Yxw521** [jeecgboot/JimuReport#2329]
##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/76502207/a7e2c462-5c85-47e8-8322-5c82f0245975)

**Comment by lvdandan16** [comment]
现在就支持 参考文档：https://help.jeecg.com/jimureport/7.pagenumset.html

**Comment by Yxw521** [comment]
> 现在就支持 参考文档：https://help.jeecg.com/jimureport/7.pagenumset.html
不想要1/3,想要：当前第1页，总共3页。这样的效果

**Comment by lvdandan16** [comment]
这个目前没有，具体报价的话，可以找我们商务
