### ISSUE TITLE
图表PDF导出内容异常

### ISSUE THREAD

**Issue by hu-yan-xiao** [jeecgboot/JimuReport#2332]
##### 错误日志&截图：
![J~H)X@(_(MH}Z}@)1Z@4J$Y](https://github.com/jeecgboot/JimuReport/assets/58208126/c3b335a2-57f5-4194-b10c-ba7c21598419)  

![X`6I)6RO@G@W7 C}XWHTP)E](https://github.com/jeecgboot/JimuReport/assets/58208126/993a2672-fb53-46b2-b935-366528090006)

##### 重现步骤：
1.设计时为整个图表设置单元格填充色  2、预览页面导出PDF 内容异常

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，目前是导出后有图表，图标后的背景颜色消失

**Comment by hu-yan-xiao** [comment]
需要等新版本，发布吗？

**Comment by 1298191366** [comment]
是的

**Comment by hu-yan-xiao** [comment]
感谢感谢。咱们下一个版本大概什么时间发布呀？
