### ISSUE TITLE
导入报表配置报错

### ISSUE THREAD

**Issue by 13813586515** [jeecgboot/JimuReport#2333]
##### 版本号：
1.6.5

##### 问题描述：
导入报表配置失败

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/21357134/3bade8a6-7764-4c5a-98aa-7d9ed5bf1987)

##### 重现步骤：
测试导出报表配置，然后导入正式环境
以下是从测试环境导出的json
[test.json](https://github.com/jeecgboot/JimuReport/files/13847964/test.json)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
错误太少

**Comment by 13813586515** [comment]
你这回复的，我也知道错误太少啊，可是积木的控制台打印就这些，我能咋办

**Comment by zhangdaiscott** [comment]
提供导入json

**Comment by lvdandan16** [comment]
收录 ws

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
