### ISSUE TITLE
请提供对外接口JimuReportTokenInterceptor.backError，用户可根据需要，处理token校验失败结果。而不是给前端直接返回json字串

### ISSUE THREAD

**Issue by shiyingyan** [jeecgboot/JimuReport#2335]
##### 问题描述：
token校验不通过，浏览器页面直接文字提示“token校验失败，无权限访问！”无法满足实际要求。
应该提供对外接口，可根据需要自定义。比如：显示自定义的页面，或者跳转到登录页面
同理，其它拦截器错误处理，应该也对外提供接口

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/8131314/c67a7293-3e59-47d1-b322-fdccfd770386)

![image](https://github.com/jeecgboot/JimuReport/assets/8131314/e0baebd5-3f2b-492f-9ed5-4b43d5980d20)

##### 重现步骤：
token校验失败即可

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持  归集至：#138
