### ISSUE TITLE
循环块内字段多值显示问题

### ISSUE THREAD

**Issue by superman4808** [jeecgboot/JimuReport#2336]
##### 版本号：
V1.6.3

##### 问题描述：
循环块内某行字段返回的数据为多个时，如何才能使这些字段在同一个循环块内显示

##### 错误日志&截图：
![1](https://github.com/jeecgboot/JimuReport/assets/121927607/c1afd115-605a-441b-bc17-ebdad722ba43)
![2](https://github.com/jeecgboot/JimuReport/assets/121927607/ac51dedc-026a-4a28-9fc8-efc1c4325802)

##### 重现步骤：
[报表配置.zip](https://github.com/jeecgboot/JimuReport/files/13855482/default.zip)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by sanye8899** [comment]
同问

**Comment by lvdandan16** [comment]
字段有多个值，是指子表吗？

**Comment by sanye8899** [comment]
是的  子表

**Comment by lvdandan16** [comment]
收录 cr

**Comment by zhangdaiscott** [comment]
新版发布支持
