### ISSUE TITLE
在制作报表的时候，需要拖拉数据源字段到报表设计区，能否一次性拖拉到设计区域？

### ISSUE THREAD

**Issue by chenxudong2** [jeecgboot/JimuReport#2337]
##### 版本号：
1.6.6

##### 问题描述：

在制作报表的时候，需要拖拉数据源字段到报表设计区，能否一次性拖拉到设计区域？
把数据库字段描述做为设计表单头，宽度为数据库的指定的宽度哦。这样就可以加速报表设计速度。

##### 错误日志&截图：
![1](https://github.com/jeecgboot/JimuReport/assets/35134790/74f97036-9123-4cb1-9021-635ee34dff0d)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不能

**Comment by chenxudong2** [comment]
这个功能后续有计划新增么？感觉对报表制作者来说，效率是很大的提升
