### ISSUE TITLE
积木集成到springboot中部署后报错

### ISSUE THREAD

**Issue by qwertdafgdfg** [jeecgboot/JimuReport#2339]
##### 版本号：
jimureport-spring-boot-starter-1.5.8.jar
##### 问题描述：
积木集成到springboot中部署后报错，点击  SQL解析后  后端接口报错如下。
![image](https://github.com/jeecgboot/JimuReport/assets/32232106/3bf09f5e-25dd-4872-ab3f-1b55f0521c97)
![2024-01-08 16_02_39-积木报表—免费可视化Web报表工具](https://github.com/jeecgboot/JimuReport/assets/32232106/d3b5f490-69c1-4f61-9c22-013f7633cb9b)

##### 错误日志&截图：
Handler dispatch failed; nested exception is java.lang.VerifyError: StackMapTable error: bad offset\nException Details:\n  Location:\n    org/jeecg/modules/jmreport/desreport/util/e.a(Lcom/alibaba/fastjson/JSONObject;)Lcom/alibaba/fastjson/JSONObject; @0: new\n  Reason:\n    Invalid stackmap specification.\n  Current Frame:\n    bci: @85\n    flags: { }\n    locals: { 'com/alibaba/fastjson/JSONObject', 'java/util/ArrayList', 'java/util/Iterator' }\n    stack: { }\n  Bytecode:\n    0x0000000: bb00 b859 b701 4b4c 2ab6 00ef b901 9c01\n    0x0000010: 004d 2cb9 018f 0100 9900 4a2c b901 9001\n    0x0000020: 00c0 00a5 4e2d b801 5e99 0036 1240 2db6\n    0x0000030: 011d 9a00 2d13 0418 2db6 011d 9a00 2312\n    0x0000040: 672d b601 1d9a 001a 125a 2db6 011d 9a00\n    0x0000050: 112b 2db8 010e b801 10b9 0191 0200 57a7\n    0x0000060: ffb3 2bb8 014c bb00 8c59 b700 e64e bb00\n    0x0000070: 8d59 04b7 00eb 3a04 2bb9 0193 0100 3a05\n    0x0000080: 1905 b901 8f01 0099 0034 1905 b901 9001\n    0x0000090: 00c0 009f 3a06 2a19 06b8 012e b600 ee3a\n    0x00000a0: 072d 1907 b600 e757 1904 1906 b801 2e19\n    0x00000b0: 07b6 00f0 5701 3a07 a7ff c819 04b0     \n  Stackmap Table:\n    append_frame(@18,Object[#184],Object[#189])\n    same_frame_extended(@85)\n    chop_frame(@88,1)\n    full_frame(@118,{Object[#141],Top,Top,Object[#140],Object[#141],Object[#189]},{})\n    full_frame(@177,{Top,Top,Top,Top,Object[#141]},{})\n"

##### 重现步骤：
部署后jar包启动报错

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
依赖冲突了吧

**Comment by qwertdafgdfg** [comment]
没有依赖冲突，我这里fastjson用的都是fastjson-1.2.83版本的，这个报错只有打成jar包部署环境下才报错，开发环境下不报错的。

**Comment by zhangdaiscott** [comment]
那就确认下达成jar是不是冲突了
