### ISSUE TITLE
部署tomcat8失败

### ISSUE THREAD

**Issue by shiyingyan** [jeecgboot/JimuReport#2340]
##### 问题描述：
生成war文件，部署到tomcat8.*版本，无法启动。 
原因：内置的filter没有实现Filter的init和destroy方法， 因为tomcat8.*版本中，Filter的init/destory方法，子类必须重载。 
请尽快解决bug，谢谢

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/8131314/836e1ee2-5370-4421-be1f-44d11956ae89)

##### 重现步骤：
tomcat8.*版本，部署war包

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
建议使用tomcat9
