### ISSUE TITLE
合计功能合计行号

### ISSUE THREAD

**Issue by hdthhh** [jeecgboot/JimuReport#2342]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/100888871/0c329ba9-0514-401a-9aa5-ac078bfdcb35)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by hdthhh** [comment]
![微信截图_20240108161849](https://github.com/jeecgboot/JimuReport/assets/100888871/78a0a313-950f-4210-8b13-2e8238bfd714)

**Comment by lvdandan16** [comment]
不支持
