### ISSUE TITLE
积木报表合并单元格，数据只能显示40个字

### ISSUE THREAD

**Issue by chenyudd** [jeecgboot/JimuReport#2344]
##### 版本号：
1.5.8

##### 问题描述：
积木报表合并单元格，数据只能显示40个字

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/111737453/25ebd72e-a4f6-49bd-9e8e-f5f63fbf15c0)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
