### ISSUE TITLE
删除线，下划线使用之后再点取消，导出的excel仍有两线

### ISSUE THREAD

**Issue by zhao950429** [jeecgboot/JimuReport#2345]
##### 版本号：
166

##### 问题描述：
删除线，下划线使用之后再点取消，导出的excel仍有两线

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/33420852/753072ff-7c5c-41b9-b73b-44f78b54506d)

![image](https://github.com/jeecgboot/JimuReport/assets/33420852/d48c0979-2ca8-4ecc-8096-d9249652ccb8)

##### 重现步骤：
创建excel报表，绘制16*16表格，设置单元格样式，全选表格设置下划线删除线，保存，预览，删除下划线删除线，保存预览导出

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
