### ISSUE TITLE
内网穿透发布到公网，访问加载js特别慢

### ISSUE THREAD

**Issue by lishijiajava** [jeecgboot/JimuReport#2346]
##### 版本号：
1.6.1

##### 问题描述：

使用内网穿透发布到公网，访问加载js特别慢。
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/139893640/43ec1978-b5ab-4933-afed-85e52b711251)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
内网穿透发布到公网，是指？

**Comment by lishijiajava** [comment]
> 内网穿透发布到公网，是指？

没事了，就是带宽太小了
