### ISSUE TITLE
如何在增强js中获取参数设置好的默认值？

### ISSUE THREAD

**Issue by happyuanhao** [jeecgboot/JimuReport#2350]
##### 版本号：
1.6.5

##### 问题描述：
根据#2247的回复，因为这张表中我设置的是sql查询参数，查询的是时间范围的总和，在参数设置中没有时间范围的选项，因此 我想问一下在我给某个时间控件设置上默认值后，我如何在增强js中获取此默认值，根据默认值判断另一个时间标签的值？

##### 错误日志&截图：
<img width="1025" alt="微信图片_20240110164841" src="https://github.com/jeecgboot/JimuReport/assets/25651702/ff0675cc-582a-4eb2-bb8f-8c3d91835bb6">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
