### ISSUE TITLE
url路径后面的参数怎么直接显示到单元格

### ISSUE THREAD

**Issue by Ding-ding-wang** [jeecgboot/JimuReport#2351]
##### 版本号：
v1.6.6

##### 问题描述：
预览页面url路径后面的参数怎么直接显示到单元格

##### 错误日志&截图：
![微信图片_20240110165937](https://github.com/jeecgboot/JimuReport/assets/41403466/f1785f50-1e90-4ae1-b948-0231d236b617)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档：https://help.jeecg.com/jimureport/summary/paramReport.html
