### ISSUE TITLE
官网在线体验，图表设置单元格背景色后打印和导出PDF显示异常

### ISSUE THREAD

**Issue by hu-yan-xiao** [jeecgboot/JimuReport#2354]
##### 版本号：
1.6.6

##### 问题描述：
报表设计，添加柱状图，设置单元格背景色，打印预览和导出PDF异常。

##### 重现步骤：
分享的连接地址：https://bootapi.jeecg.com/jmreport/shareView/905253836221140992?shareToken=b6e7895d6345a67c171e1aed3c6b0c9a
点击打印，预览页面无图表内容
![image](https://github.com/jeecgboot/JimuReport/assets/58208126/b071976f-7664-4494-8413-7a9883b0bd82)
点击导出PDF  显示未能正确加载PDF
![image](https://github.com/jeecgboot/JimuReport/assets/58208126/83411ae9-a2e6-41ad-a356-d33aadc9ee55)

**Comment by lvdandan16** [comment]
收录 zy

**Comment by 1298191366** [comment]
已修复，待新版本发布，目前导出pdf图表下的背景颜色会被去掉。后期会修改

**Comment by hu-yan-xiao** [comment]
背景色去掉了，但是图标内容依旧没有显示，打开PDF是一个空白文件。如图：
![image](https://github.com/jeecgboot/JimuReport/assets/58208126/26853354-cb5e-4d92-ac63-c6e021ba40f0)

**Comment by 1298191366** [comment]
你重新拖拽试一下

**Comment by hu-yan-xiao** [comment]
OK,新托进来得没有问题，谢谢。开源幸苦
