### ISSUE TITLE
自定义横向分组 日期排序错误,不能排序

### ISSUE THREAD

**Issue by llmoe** [jeecgboot/JimuReport#2355]
##### 版本号：
1.6.6

##### 问题描述：
使用 自定义横向分组 日期排序错误，排序错乱，使用分组里面的排序、自定义文本排序 均无效

##### 错误日志&截图：
突然发现截错图了(已更新了)，因为做了几个报表有些报表可以按照SQL里面的排序，有些又不能，然后分组的排序也无效的，问题应该是一样的没办法根据 分组设置排序

没办法自定义排序 ，就算SQL里面排序好了。。但是实际上也不是按照读取排序的例如👇
![image](https://github.com/jeecgboot/JimuReport/assets/17946937/7f310e7e-3680-41aa-a8bc-98e44d425838)

<img width="1364" alt="截屏2024-01-12 18 23 16" src="https://github.com/jeecgboot/JimuReport/assets/17946937/b2c2ac91-d142-4a15-8ae9-49d21d0b1527">

数据格式
<img width="1355" alt="截屏2024-01-12 18 25 28" src="https://github.com/jeecgboot/JimuReport/assets/17946937/0a5edc13-6dc6-4f3a-8b13-d37fac681618">

##### 重现步骤：
按照上图数据做个表即可

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
你想升序排？

**Comment by lvdandan16** [comment]
收录 cr

**Comment by 1298191366** [comment]
已修复，待新版本发布
