### ISSUE TITLE
图形报表设计中上传背景图，一段时间后该图片消失

### ISSUE THREAD

**Issue by SleepyWiKi** [jeecgboot/JimuReport#2356]
##### 版本号：
1.6.4

##### 问题描述：
在报表设计里面的图形报表中，右键单击单元格后上传背景，一开始（可能前两天图片都还可以显示）几天（大概两天后图片消失不见）；

##### 错误日志&截图：
无错误日志
截图如下：
![image](https://github.com/jeecgboot/JimuReport/assets/96610516/fca3b079-6b96-432f-88a9-8aa2b91bab94)

##### 重现步骤：
点击报表设计进入报表设计页面，选择图形报表-->随便右键单击一个空格处在下拉菜单中选择背景图片-->右侧抽屉中选择图片上传，一开始图片都还在，过段时间图片就没了。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
有报错信息吗

**Comment by hu-yan-xiao** [comment]
容器部署吗？服务重启资源路径改变了吧

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
