### ISSUE TITLE
新环境使用积木报表，脚本迁移后，为什么必须需要在报表页面点击数据库连接配置，然后点击确认，报表才能正常展示？

### ISSUE THREAD

**Issue by wuke001** [jeecgboot/JimuReport#2357]
##### 版本号：
1.6.4

##### 问题描述：
1、在A服务上创建好的报表，迁移到另外B服务器时。
2、把A服务器对应的积木报表的SQL脚本，都迁移到B服务器上。
3、在B服务器上预览报表时，报表不展示，后台会报错null。
4、必须在报表设计页面点击数据连接编辑，连接信息不需要改，直接点确定。
5、B服务器上的所有报表都能正常展示了
问：为什么还要重新点这一下？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
？

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
