### ISSUE TITLE
SQL解析失败：请注意，值可能存在SQL注入风险!

### ISSUE THREAD

**Issue by MearyGao** [jeecgboot/JimuReport#2358]
##### 问题描述：

SQL解析失败：请注意，值可能存在SQL注入风险!
##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/18022533/6cc85cb1-a6db-4512-92fc-fdc7a8a46cb0)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by MearyGao** [comment]
这种情况是要更换表名称吗

**Comment by zhangdaiscott** [comment]
升级到最新版试试，应该处理了
