### ISSUE TITLE
docker-compose 部署报错

### ISSUE THREAD

**Issue by darling331** [jeecgboot/JimuReport#2359]
##### 版本号：
1.6

##### 问题描述：
docker-compose 部署失败，找不到jar包

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/49277316/0b122274-841b-4a34-b616-a5f3a693ad84)

##### 重现步骤：
Building jimureport
[+] Building 6.2s (9/9) FINISHED                                                                                                                             docker:default
 => [internal] load build definition from Dockerfile                                                                                                                   0.0s
 => => transferring dockerfile: 487B                                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/anapsix/alpine-java:8_server-jre_unlimited                                                                                  6.2s
 => CANCELED [1/5] FROM docker.io/anapsix/alpine-java:8_server-jre_unlimited@sha256:d97f12170501e5faea7f86f9a9205d05f5cadcf7fb34fb53c3a7cef893e9cdd9                   0.0s
 => => resolve docker.io/anapsix/alpine-java:8_server-jre_unlimited@sha256:d97f12170501e5faea7f86f9a9205d05f5cadcf7fb34fb53c3a7cef893e9cdd9                            0.0s
 => => sha256:d97f12170501e5faea7f86f9a9205d05f5cadcf7fb34fb53c3a7cef893e9cdd9 741B / 741B                                                                             0.0s
 => => sha256:49d744fbb5264c490edc4eb05a6a17ef32041843c57d17ba79c922a1960a5a5a 11.03kB / 11.03kB                                                                       0.0s
 => [internal] load build context                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                        0.0s
 => CACHED [2/5] RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime                                                                                           0.0s
 => CACHED [3/5] RUN mkdir -p /jimureport                                                                                                                              0.0s
 => CACHED [4/5] WORKDIR /jimureport                                                                                                                                   0.0s
 => ERROR [5/5] ADD ./target/jimureport-example-1.6.jar ./                                                                                                             0.0s
------
 > [5/5] ADD ./target/jimureport-example-1.6.jar ./:
------
Dockerfile:13
--------------------
  11 |     EXPOSE 8085
  12 |     
  13 | >>> ADD ./target/jimureport-example-1.6.jar ./
  14 |     
  15 |     CMD java -DMYSQL-HOST=jimureport-mysql -Dfile.encoding=utf-8 -Djava.security.egd=file:/dev/./urandom -jar jimureport-example-1.6.jar
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 6eadf9e7-d987-4315-89c3-e14f1d2e26fc::osk36mhhyrfp4w0asnpleele4: failed to walk /var/lib/docker/tmp/buildkit-mount208180718/target: lstat /var/lib/docker/tmp/buildkit-mount208180718/target: no such file or directory
ERROR: Service 'jimureport' failed to build : Build failed

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档：https://help.jeecg.com/jimureport/projectJoin/dockercompose.html

**Comment by darling331** [comment]
好的，谢谢，我找到docker部署的文章了，原来是我找错了
