### ISSUE TITLE
打印相关问题

### ISSUE THREAD

**Issue by maxwellQAQ** [jeecgboot/JimuReport#2360]
##### 版本号：
1.6.2

##### 问题描述：
在doc文件中已描述

##### 错误日志&截图：
1边框线不能够占满纸张大小问题：
![图片](https://github.com/jeecgboot/JimuReport/assets/150879657/b9017187-35e9-49f9-bac5-88f08747f96b)
2表头跨页和多出一个二维码问题
![图片](https://github.com/jeecgboot/JimuReport/assets/150879657/91264fd9-6a8f-407e-a1fb-9fbb9df255fc)
3.固定每页行数
api数据集返回集合所有数据，勾选分页，能设置每页多少数据

##### 相关模板 SQL：
[打印模板.txt](https://github.com/jeecgboot/JimuReport/files/13915527/default.txt)

**Comment by lvdandan16** [comment]
问题1：你设计的时候占满了吗？
问题2：收录 zy
问题3：不支持

**Comment by maxwellQAQ** [comment]
补充说明：
问题1：我们用的不是A4纸，但是纸张的大小专门配置了和打印机一样的，具体可查看我发的sql语句
问题3：希望能支持，因为表格打印的时候经常出现多一页或者下一页多一个表头出来，如果能让我们开发自己控制每页显示多少条数据，就能避免这种类似的问题

**Comment by maxwellQAQ** [comment]
> 问题1：你设计的时候占满了吗？ 问题2：收录 zy 问题3：不支持

补充说明：
问题1：我们用的不是A4纸，但是纸张的大小专门配置了和打印机一样的，具体可查看我发的sql语句
问题3：希望能支持，因为表格打印的时候经常出现多一页或者下一页多一个表头出来，如果能让我们开发自己控制每页显示多少条数据，就能避免这种类似的问题

**Comment by lvdandan16** [comment]
报表需要导出json格式
