### ISSUE TITLE
单元格格式自动换行时超长截断或字体大小自适应

### ISSUE THREAD

**Issue by hmy502** [jeecgboot/JimuReport#2361]
##### 问题描述：
超长自动换行功能很实用，但是能否增加个字体自适应或超长阶段的功能，也就是如果内容过长不改变行高，把字体变小或截断

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持，归集：#138
