### ISSUE TITLE
求解，实现交叉表哪里出问题了

### ISSUE THREAD

**Issue by li-Riley** [jeecgboot/JimuReport#2362]
##### 版本号：
官网演示版 

##### 问题描述：
实现交叉表时不知道什么原因显示不出来

##### 错误日志&截图：
数据集：
![1705049246208](https://github.com/jeecgboot/JimuReport/assets/68844177/fc10c59a-e2ad-46a0-8aab-3d663e8a700c)
横向配置：
![1705049332715](https://github.com/jeecgboot/JimuReport/assets/68844177/d4158741-eef8-43ef-84be-eb2dec741f8e)
竖向配置：
![1705049359725](https://github.com/jeecgboot/JimuReport/assets/68844177/25281e92-a9a4-48fc-b130-bd1bb3fd23f4)
数据配置：
![image](https://github.com/jeecgboot/JimuReport/assets/68844177/dc68e59d-a614-43dd-b682-cd8674415cc0)
结果：
![1705049484345](https://github.com/jeecgboot/JimuReport/assets/68844177/500d9271-169d-4d8d-8010-6b01e0602106)

##### 重现步骤：
官网积木报表打印设置，-》纵向分组小计示例2

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档：https://help.jeecg.com/jimureport/group/directionDynamic.html
