### ISSUE TITLE
打印时分页异常，期待回复

### ISSUE THREAD

**Issue by 15934475922** [jeecgboot/JimuReport#2364]
##### 版本号：
1.6.2

##### 问题描述：
情景：报表 分页 打印
         

>  ** 预览时分页正常没有问题**
![image](https://github.com/jeecgboot/JimuReport/assets/48462269/eb0e5c49-24f9-4602-b210-748621467957)

>   **打印时分页有误**
![image](https://github.com/jeecgboot/JimuReport/assets/48462269/8c2502ef-bae3-4d32-b125-ecc8b583147a)

##### 错误日志&截图：
数据源
![image](https://github.com/jeecgboot/JimuReport/assets/48462269/361328e9-b4d3-4bad-b766-82c31010b2c4)

![image](https://github.com/jeecgboot/JimuReport/assets/48462269/d378b92a-7ae4-4ae5-82d9-86108c6c65f1)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 cr

**Comment by hoperunChen** [comment]
预览正常是因为每页只显示一行数据，但是打印时系统是不分页的，所以会出现多条数据重复的情况，这是正常的。
新版本中「主子表循环」功能可以满足您的需求，请follow积木报表新版本的发布。
