### ISSUE TITLE
打印时背景图片与数据表格错位

### ISSUE THREAD

**Issue by losepure** [jeecgboot/JimuReport#2365]
##### 版本号：
1.6.5

##### 问题描述：
打印时背景图片与数据表格错位

##### 错误日志&截图：
![11](https://github.com/jeecgboot/JimuReport/assets/16299547/5f4188bc-79c4-4d6d-bc84-489c38cb021f)

##### 重现步骤：
使用数据表格对背景图片中的表格进行定位，编辑和预览模式都是正常的，但是打印时候显示错位，原因时图片尺寸发生了拉伸和压缩，但不明白是什么原因造成这种情况的。

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
