### ISSUE TITLE
api数据源分页问题

### ISSUE THREAD

**Issue by lishijiajava** [jeecgboot/JimuReport#2366]
##### 版本号：

1.6.1
##### 问题描述：

按照官网配置的api分页接口。返回的总数是15条，但是页码栏这块显示不对
![image](https://github.com/jeecgboot/JimuReport/assets/139893640/4b6c39f8-8790-4f87-99b9-cc611f0249d8)

##### 重现步骤：
这是api接口
![image](https://github.com/jeecgboot/JimuReport/assets/139893640/7d4d8f2e-e58d-4365-93e8-a491fd330d53)
![image](https://github.com/jeecgboot/JimuReport/assets/139893640/b0c9bedb-2db4-4ab6-8c04-7f1ac4cd9971)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
预览工具条重新设置条数了吗？参考文档：https://help.jeecg.com/jimureport/base/tools.html

**Comment by lishijiajava** [comment]
> 预览工具条重新设置条数了吗？参考文档：https://help.jeecg.com/jimureport/base/tools.html

预览工具条没动过，现在就直接在api接口改返回就正常了？ total改为总页数，count改为总条数
![image](https://github.com/jeecgboot/JimuReport/assets/139893640/89558ae7-6a2c-40f1-b097-a9ef9af1c6d8)
