### ISSUE TITLE
DBSUM 加查询条件统计时报 SQL 语法错误，条件字段前缺少 and

### ISSUE THREAD

**Issue by GaoChunjiang** [jeecgboot/JimuReport#2367]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/15353083/20118172-16cd-493f-bf8c-c8b2a9cee34d)
![image](https://github.com/jeecgboot/JimuReport/assets/15353083/17d40ffc-a621-41e0-8a73-c5f13e6e6056)
![image](https://github.com/jeecgboot/JimuReport/assets/15353083/f8c6dcc2-ed0f-425e-9c98-fd7b2ef0a267)
![image](https://github.com/jeecgboot/JimuReport/assets/15353083/3b138a4b-1e3f-4cac-addd-df2b8ddbb46e)

##### 重现步骤：
1、添加数据集；
2、添加查询条件；
3、添加 DBSUM 函数；
4、预览，并输入查询条件；

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by GaoChunjiang** [comment]
查询条件配置
![image](https://github.com/jeecgboot/JimuReport/assets/15353083/edc887e4-5969-490d-904d-351170c5c28a)

**Comment by lvdandan16** [comment]
收录 ws
