### ISSUE TITLE
积木报表，保存报表的时候能不能设置纸张大小，比如纸张设置成A5，然后后面我都用这个报表调用接口生成pdf文件

### ISSUE THREAD

**Issue by Writebugeveryday** [jeecgboot/JimuReport#2368]
##### 版本号：
1.6.6

##### 问题描述：
积木报表，保存报表的时候能不能设置纸张大小，比如纸张设置成A5，然后后面我都用这个报表调用接口生成pdf文件

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/111101415/d606a823-1720-4231-b8c2-f4a03deca130)

##### 重现步骤：
保存时没有设置纸张大小的按钮

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
打印设置纸张
