### ISSUE TITLE
使用横向扩展列之后，分页的总条数和导出有问题

### ISSUE THREAD

**Issue by phsy** [jeecgboot/JimuReport#2369]
##### 版本号：
1.6.2

##### 问题描述：
原始数据有接近30万条，报表中设置了分组和横向扩展列，渲染的总行数应该在1万条以内，但是分页栏上显示的总条数依然是原始数据条数
在导出的时候，也是按照30万条数据分了30个sheet，而不是一个sheet

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
默认超过1万条就分sheet

**Comment by phsy** [comment]
使用了分组和行转列之后，渲染出的数据实际不到1万行
分页查询的时候没法预先知道渲染后的数据条数
但是导出的时候数据应该按照实际渲染来分sheet，除非导出的时候也是也走的分页逻辑来分sheet

**Comment by lvdandan16** [comment]
导出是导出全部数据
