### ISSUE TITLE
1.6.6

### ISSUE THREAD

**Issue by duoduo5553** [jeecgboot/JimuReport#2371]
版本号：1.6.6

问题描述：给多个sql数据集统计分页

错误日志&截图：

重现步骤：

友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by duoduo5553** [comment]
版本号：1.6.6

问题描述：给多个sql数据集统一分页

错误日志&截图：

重现步骤：

友情提示（为了提高issue处理效率）：

积木报表是一款免费报表产品，功能免费源码不开放;
未按格式要求发帖，会被直接删掉;
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请图文并茂详细描述问题
