### ISSUE TITLE
积木报表时间修改，柱状图颜色从自定义变成默认

### ISSUE THREAD

**Issue by LITIE-ai** [jeecgboot/JimuReport#2372]
##### 版本号：
1.5.4

##### 问题描述：
积木报表时间修改，柱状图颜色从自定义变成默认

##### 错误日志&截图：
![QQ图片20240116131911](https://github.com/jeecgboot/JimuReport/assets/79312962/4ab318e8-351a-4ff0-a9d7-120030d31c05)
![QQ图片20240116131858](https://github.com/jeecgboot/JimuReport/assets/79312962/5ec69f04-4e20-4020-ba5c-a83886320fda)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws
