### ISSUE TITLE
角色授权在哪里访问

### ISSUE THREAD

**Issue by XIAOAOAARON** [jeecgboot/JimuReport#2373]
##### 版本号：
部署的docker 最新的仓库

##### 问题描述：
角色授权在哪里访问? 感觉文档不清晰 , 还是说相关的文档在其他的地方 ?

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/34054781/7da6bbc2-a2d0-447a-84f0-2d04c0afb2d9)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你要做什么

**Comment by XIAOAOAARON** [comment]
> 你要做什么

我要知道它在哪里啊.

**Comment by XIAOAOAARON** [comment]
> 你要做什么

就像看到文档后跟着操作 , 结果找不到入口 ?

**Comment by lvdandan16** [comment]
这是集成jeecgboot的，如果你没有集成jeecgboot就没有这个入口
