### ISSUE TITLE
字体大小能否支持自定义

### ISSUE THREAD

**Issue by niupengchao** [jeecgboot/JimuReport#2375]
##### [错误日志&截图：]
![2)14 EVY8IZLJ O8}F 5N7Q](https://github.com/jeecgboot/JimuReport/assets/63273068/ee88127f-0c2d-423c-878d-4e140f27aa88)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Stars-XK** [comment]
同。如果不行，设置的字号再小一些也行呀，现在的满足不了使用

**Comment by lvdandan16** [comment]
不支持自定义
收录 zy

**Comment by zhangdaiscott** [comment]
看后面的规划

先收录到“需求汇总”中
https://github.com/jeecgboot/JimuReport/issues/138

**Comment by liaozhiyang** [comment]
已新增自定义字体大小功能，下一版本发布。

![image](https://github.com/user-attachments/assets/8df1ea83-ebbd-49d6-b88c-1da046368c07)
