### ISSUE TITLE
带背景导出图片时报错

### ISSUE THREAD

**Issue by niupengchao** [jeecgboot/JimuReport#2377]
##### 错误日志&截图：
![1705501025748](https://github.com/jeecgboot/JimuReport/assets/63273068/e2654dd9-9440-43ee-ab0c-b3273eb7ff96)
![1705501084130](https://github.com/jeecgboot/JimuReport/assets/63273068/ea56abfe-c109-4752-bb7b-2599e7cb1a34)
![1705501199222](https://github.com/jeecgboot/JimuReport/assets/63273068/6f765151-bd7d-4e94-81b4-9cbfb61d9d83)
![1705502293992](https://github.com/jeecgboot/JimuReport/assets/63273068/62d2a7a3-d224-4d79-8b22-bb43bb8fcb0e)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
