### ISSUE TITLE
带背景导出图片错乱

### ISSUE THREAD

**Issue by niupengchao** [jeecgboot/JimuReport#2379]
##### 错误日志&截图：
预览截图：
![1705560995413](https://github.com/jeecgboot/JimuReport/assets/63273068/b1a3b1fc-daa1-4aae-916c-3a15f886b4e5)
导出图片：
![实习证明副本1543 (5)](https://github.com/jeecgboot/JimuReport/assets/63273068/c171c512-c7ce-44fa-a696-5d3b1ce35a1e)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
