### ISSUE TITLE
concat函数使用问题

### ISSUE THREAD

**Issue by tangshilan** [jeecgboot/JimuReport#2380]
##### 问题描述：列表中使用， =concat('#{jm.dept}','#{jm.name}')函数，不显示数据，正常使用 #{jm.name}是有数据的。
使用，=concat('${jm.dept}','${jm.name}')格式是有数据的，但是所有的数据值都一样，正常数据是不一样的。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 cr

**Comment by hoperunChen** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/13013558/732122d3-ef63-4ae7-a8e6-2a35b1665ef9)
![image](https://github.com/jeecgboot/JimuReport/assets/13013558/2efa93dd-0954-4188-bf98-5c024e7c309f)
未复现，烦请提供设计模版和模拟数据。
