### ISSUE TITLE
打印多余文字去除

### ISSUE THREAD

**Issue by duoduo5553** [jeecgboot/JimuReport#2384]
版本号：1.6.6

问题描述：图片中红框圈起来的文字(左上日期 上面中间为菜单名称 左下为接口地址), 如何去除?每次打印预览都会自动出现这三个信息

错误日志&截图：
![打印问题](https://github.com/jeecgboot/JimuReport/assets/49507431/d4f6ccd5-f93b-4863-aacf-0fce5b7161f1)

重现步骤：

友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档  常见问题10：https://help.jeecg.com/jimureport/qa.html
