### ISSUE TITLE
cnmoney有bug

### ISSUE THREAD

**Issue by zgiw** [jeecgboot/JimuReport#2385]
##### 版本号：
1.6.6

##### 问题描述：
根据文档动态cell表达式方法，在使用cnmoney函数时，使用的动态单元格输出中文大写金额，但转换的大写金额不是正确的

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/71875297/b6cafaa4-cbba-4abe-83dd-24d7115fcaf4)
![image](https://github.com/jeecgboot/JimuReport/assets/71875297/adf2a722-592e-48f8-8e98-e40b1dfc6493)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持此种用法
