### ISSUE TITLE
新建报表报错

### ISSUE THREAD

**Issue by LiZhenHaibrr** [jeecgboot/JimuReport#2386]
##### 版本号：
1.6.5

##### 问题描述：
新建报表的时候报错 
freemarker.core.InvalidReferenceException: The following has evaluated to null or missing: ==> reportConfig [in template "jmreport/desreport/index.ftl" at line 13, column 33]
##### 错误日志&截图：
FreeMarker template error:
The following has evaluated to null or missing:
==> reportConfig  [in template "jmreport/desreport/index.ftl" at line 13, column 33]

----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${reportConfig}  [in template "jmreport/desreport/index.ftl" at line 13, column 31]

##### 重现步骤：

集成完以后可以访问 新建报表的时候报错

**Comment by LiZhenHaibrr** [comment]
fastjson版本为 1.2.83

**Comment by lvdandan16** [comment]
fastjson使用1.2.78
