### ISSUE TITLE
在线大屏设计器websocket重连以后，数据关联不上了

### ISSUE THREAD

**Issue by yu1335436268** [jeecgboot/JimuReport#2388]
##### 问题描述：
使用在线大屏设计器，数据方式选择websocket，当websocket断开重连以后，虽然可以正常收到websocket的消息，但页面不会发生改变了。

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/22932259/7bf74989-363e-49cf-b8c6-da6805d3a96d)

##### 重现步骤：
1.大屏组件选择websocket方式
2.预览时，等待websocket断开，尝试重连，连接成功
3.此时再次发送websocket消息，大屏组件内的数据不会被改变

**Comment by lvdandan16** [comment]
收录 sq
