### ISSUE TITLE
分组排序乱序问题

### ISSUE THREAD

**Issue by wenhongjun** [jeecgboot/JimuReport#2390]
##### 版本号：
1.6.6

##### 问题描述：
优化建议：
=row() 这种排序函数 无法设置分组 只能自己维护 使用#{t_index+1} 进行分组也无法满足要求
问题：
index非中文 为数字 使用你们的正序倒序没用 
自己维护
接口中已经对index字段排序好了，在分组设置中也设置了默认排序  也没用

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/40422721/a973df2f-4968-4313-af20-e7e9b556c817)
![image](https://github.com/jeecgboot/JimuReport/assets/40422721/7aada3d1-8e63-478c-8642-72959836d597)
![image](https://github.com/jeecgboot/JimuReport/assets/40422721/d19149ec-7560-4bc2-8a4d-fcf343eccf58)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by rengm3707** [comment]
我也遇到了同样的问题，解决了吗？
![image](https://github.com/jeecgboot/JimuReport/assets/57214336/3ede4a7b-ea0f-46f7-abc0-2e8fe4fdf8a4)

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
