### ISSUE TITLE
找不到背景图设置的按钮

### ISSUE THREAD

**Issue by paliumh** [jeecgboot/JimuReport#2392]
##### 版本号：
1.6.6

##### 问题描述：
找不到背景图设置的按钮

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/31791638/981f15e5-39fa-4a3c-8bf3-2f86bf3bba69)

**Comment by lvdandan16** [comment]
![Uploading image.png…]()
鼠标往下滚动
