### ISSUE TITLE
序号分组排序乱序问题

### ISSUE THREAD

**Issue by rengm3707** [jeecgboot/JimuReport#2394]
##### 版本号：
1.6.6

##### 问题描述：
序号分组排序乱序问题，大概猜到应该是源码没有按照int类型排序，而是把序号按照string类型排序的

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/57214336/e616a205-8ba2-428c-908d-a0ad5b3dbf6e)
![image](https://github.com/jeecgboot/JimuReport/assets/57214336/e2bfeabe-c981-49bd-bc6f-590c4cd2ccf6)

![image](https://github.com/jeecgboot/JimuReport/assets/57214336/daee56f3-ee4c-463c-bdc4-47e48a1c1d7b)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
