### ISSUE TITLE
积木报表预览与导出pdf不一致

### ISSUE THREAD

**Issue by xiaolexi** [jeecgboot/JimuReport#2396]
##### 版本号：
<version>1.6.4</version>

##### 问题描述：
积木报表预览与导出pdf不一致,请帮忙处理一下,多谢

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/48915405/b8cfd825-b341-4db2-b41c-1be0201fb4e4)
![image](https://github.com/jeecgboot/JimuReport/assets/48915405/35ca7e09-9a1d-4be1-b019-72828703bffc)

![image](https://github.com/jeecgboot/JimuReport/assets/48915405/a9885e97-bda6-4cb0-a5c1-8fdf170c5936)

##### 重现步骤：
循环背景图,然后对好字段,预览的时候是没问题的.但是导出pdf的时候字体会错位.

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by xiaolexi** [comment]
好的,我下周一提供一下

**Comment by xiaolexi** [comment]
[合格证测试套打.json](https://github.com/jeecgboot/JimuReport/files/14070611/default.json)
帮忙看看,感谢

**Comment by lvdandan16** [comment]
你这个是设置的循环打印？

**Comment by xiaolexi** [comment]
导出pdf 然后循环打印

**Comment by 1298191366** [comment]
未复现。请在官网做个示例并提供报表id，你的图片是本地的，我这里没有你的套打图片，就按照官网示例做了一下
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/62b15c99-5853-46b0-bf67-e3a5ebc6787e)

你这个循环快已经超出A4纸了，请尝试少选一个单元格。或者升级你的版本进行尝试，当前最新版本是`1.7.4`
![A4](https://github.com/jeecgboot/JimuReport/assets/30997828/13e6930a-494c-4922-8c3b-73b99de27c7c)
