### ISSUE TITLE
报表单元格设置数值类型，导出后并不是数值

### ISSUE THREAD

**Issue by jiezais88** [jeecgboot/JimuReport#2397]
##### 版本号：
1.6.1

##### 问题描述：
报表单元格设置数值类型，导出后并不是数值

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/30690950/be2be1f2-7775-45cb-aa1f-af5139973ed6)
![image](https://github.com/jeecgboot/JimuReport/assets/30690950/66701014-b528-4b27-93d8-8b8cfa976e56)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级最新版本试一下

**Comment by jiezais88** [comment]
> 升级最新版本试一下

没法升级，已经生产在使用了，升级之后提示sql注入不能写注释

**Comment by jiezais88** [comment]
> 升级最新版本试一下

没法升级已经在生产使用了，升级会提示sql注入没法写注释
