### ISSUE TITLE
API数据源-返回复杂 JSON 结构

### ISSUE THREAD

**Issue by jaysonjh** [jeecgboot/JimuReport#2399]
##### 问题描述：
添加API数据源，API 返回的是一个混合结构，如代码，请问如何能将feeServiceTypeList，feeSourceList用于循环。
`
{
  "code": 0,
  "data": {
    "hospitalId": 3,
    "hospitalName": "xx微创医院",
    "createDate": "2024-01-27",
    "dataMonth": "2024-01",
    "feeServiceTypeList": [
      {
        "type": 100,
        "typeName": "专陪",
        "fee": 21100
      },
      {
        "type": 101,
        "typeName": "温馨普陪",
        "fee": 42
      }
    ],
    "feeSourceList": [
      {
        "type": "1",
        "typeName": "对公收入",
        "fee": 21142,
        "remark": null
      }
    ]
  },
  "msg": ""
}
`

##### 错误日志&截图：
运行时，提示JSON 格式化异常。
`
com.alibaba.fastjson.JSONException: field null expect '[', but {, pos 1, line 1, column 2{"dataMonth":"2024-01","hospitalId":3,"hospitalName":"xx微创医院","feeSourceList":[{"fee":21142,"typeName":"对公收入","type":"1"}],"feeServiceTypeList":[{"fee":21100,"typeName":"专陪","type":100},{"fee":42,"typeName":"温馨普陪","type":101}],"createDate":"2024-01-27"}

`
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档：https://help.jeecg.com/jimureport/rumen/apiJson.html
