### ISSUE TITLE
展示时没有空白页,但是打印预览的时候有空白页.

### ISSUE THREAD

**Issue by xiaolexi** [jeecgboot/JimuReport#2400]
##### 版本号：
<version>1.6.4</version>

##### 问题描述：
展示时没有空白页,但是打印预览的时候有空白页.帮忙处理一下

##### 错误日志&截图：
![图片](https://github.com/jeecgboot/JimuReport/assets/48915405/6a3309b7-fef3-477b-8b63-25a0e1d50aec)
![图片](https://github.com/jeecgboot/JimuReport/assets/48915405/cada51a3-7baf-4c0f-9734-e66e1ce4df86)
![图片](https://github.com/jeecgboot/JimuReport/assets/48915405/43341824-b153-4327-8fdb-719b217f1c13)

##### 重现步骤：
[21148标签纸.json](https://github.com/jeecgboot/JimuReport/files/14072250/21148.json)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
在中间空白页还是在最后几页是空白页？

**Comment by xiaolexi** [comment]
这个找到解决方法了

**Comment by L5501** [comment]
> 这个找到解决方法了

请问怎么解决的
