### ISSUE TITLE
积木报表,打印预览 与页面展示不一致

### ISSUE THREAD

**Issue by xiaolexi** [jeecgboot/JimuReport#2402]
##### 版本号：
1.6.4

##### 问题描述：
积木报表,打印预览 与页面展示不一致

##### 错误日志&截图：
[货位105148标签纸 (1).json](https://github.com/jeecgboot/JimuReport/files/14074682/105148.1.json)

https://github.com/jeecgboot/JimuReport/assets/48915405/e02a7f84-9f1e-4746-951d-adc8566360d5
![image](https://github.com/jeecgboot/JimuReport/assets/48915405/2fbe4e6c-6173-4b96-8e3c-c597e9dcaed2)

![image](https://github.com/jeecgboot/JimuReport/assets/48915405/0ffc7d6d-89da-43b2-a7fd-1f8bc0f5b85b)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by xiaolexi** [comment]
[货位105148标签纸 (1).json](https://github.com/jeecgboot/JimuReport/files/14074682/105148.1.json)
这个json不是吗

**Comment by lvdandan16** [comment]
收录 zy

**Comment by liaozhiyang** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/8199499/e2a8aebe-a502-4d49-8b33-475773f99ef2)
根据你提供的json，没发现此问题。可在官网上做个例子试试，看是否有此问题
