### ISSUE TITLE
导出PDF接口线程不安全，在并发情况下，每次获得的pdf与入参不符

### ISSUE THREAD

**Issue by HisLastBow** [jeecgboot/JimuReport#2403]
##### 错误日志&截图：
报表数据涉及个人隐私 无法提供 提供一小段日志
截图是aop到org.jeecg.modules.jmreport.desreport.service.a.e.show(String,String,List)方法  两次不同入参，但是在此方法得到了同样的返回值，数据源查询错误可能性已排除
1
![1](https://github.com/jeecgboot/JimuReport/assets/58935274/b2715d13-b06a-4370-a572-51f150855365)

2
![1706577694350](https://github.com/jeecgboot/JimuReport/assets/58935274/901bd456-8e77-493d-989a-9371498b6030)

##### 重现步骤：
1.并发调用导出pdf接口，并传入不同入参 获取到的pdf有时是其他请求的数据
2.如果配置多个数据源  还会产生部分数据源是本次请求 部分数据是其他请求的情况

**Comment by lvdandan16** [comment]
原来版本已不在支持导出pdf接口，最新版本做了升级，需商业版才支持
