### ISSUE TITLE
分组列很多的情况下导出非常慢

### ISSUE THREAD

**Issue by phsy** [jeecgboot/JimuReport#2405]
##### 版本号：
1.6.3

##### 问题描述：
有一个生产报表，有20个字段，前17个字段都是分组字段，只有最后3列不分组
现象就是分页查询很快，全量导出非常非常慢，3万多条数据直到超时都没导出来
把分组减少或者去掉就可以导出成功了

有没有什么方法能加快这种多分组报表的导出速度？

**Comment by zhangdaiscott** [comment]
那肯定慢，你分组太多

**Comment by phsy** [comment]
有没有什么办法能让报表导出？
哪怕慢也行，现在是完全不能导出

**Comment by zhangdaiscott** [comment]
多少数据量，提供测试例子
