### ISSUE TITLE
报表在数据量1万条左右 , 导出或打印出现报错

### ISSUE THREAD

**Issue by relinson** [jeecgboot/JimuReport#2407]
##### 版本号：
1.6.6

##### 问题描述：
当数据量稍微大一点的时候 , 点击打印以及导出PDF等功能 , 界面无响应 . 查看Console发现有报错 , 具体为Math.max.apply参数超过上限 .

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/1357222/f8bd97d5-5624-4e9b-8293-e1882be1b565)
![image](https://github.com/jeecgboot/JimuReport/assets/1357222/417ed31e-f7c0-4e79-a045-a7e27ffd5280)

##### 重现步骤：
1. 制作一张报表 , 数据量1万条左右 , 输出15个字段左右 . 
2. 预览报表 , 点击打印或者导出图片pdf . 

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by relinson** [comment]
这个问题是否考虑解决？

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by relinson** [comment]
1. 随表制作一张报表 . 输出15个字段左右 . 
2. 数据量1万条左右 .
3. 预览报表 , 点击打印或者导出图片pdf .

**Comment by zhangdaiscott** [comment]
用的大数据导出按钮？

**Comment by zhangdaiscott** [comment]
升级到最新版看看，这块印象中改过

**Comment by liaozhiyang** [comment]
报错已修复，下一版本发布。
数据有点多，打印和到导出图片会比较慢。
导出PDF图象目前不支持这么大数据量的
