### ISSUE TITLE
报表套打问题

### ISSUE THREAD

**Issue by chenshan07073311** [jeecgboot/JimuReport#241]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/27768927/117414919-4aa99300-af4a-11eb-9077-e1e9c4ee8278.png)

![image](https://user-images.githubusercontent.com/27768927/117414952-539a6480-af4a-11eb-8a38-6bd531df5a82.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
待分析-ws

**Comment by chenshan07073311** [comment]
预计几时可以完善

**Comment by chenshan07073311** [comment]
> 待分析-ws

这个问题你们那边已经排期了？ 背景图位置如果固定住就可以解决

**Comment by zhangdaiscott** [comment]
现在最新版支持了，你试试
http://jimureport.com/doc/log
