### ISSUE TITLE
预览时二维码变得很小

### ISSUE THREAD

**Issue by xiaolexi** [jeecgboot/JimuReport#2410]
##### 版本号：
1.6.6

##### 问题描述：
预览时二维码变得很小

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/48915405/96cdd373-ef2b-4685-a0e0-302dd23e34ad)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by xiaolexi** [comment]
[白底10555循环2.json](https://github.com/jeecgboot/JimuReport/files/14094443/10555.2.json)

**Comment by xiaolexi** [comment]
[白底10555循环2.json](https://github.com/jeecgboot/JimuReport/files/14094489/10555.2.json)

**Comment by lvdandan16** [comment]
收录 zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
你本地可在左侧序号2这拖动行高为其他高度，再调整为原来的高度，可解决目前的问题。（原因应该是：通过右侧调整行高，合并单元格的高度没有随之变化。左侧拖动无此问题）
![image](https://github.com/jeecgboot/JimuReport/assets/8199499/907ee2f2-5f2c-4470-9979-80cb08e85550)
