### ISSUE TITLE
能不能支持 app 打印?

### ISSUE THREAD

**Issue by xiaolexi** [jeecgboot/JimuReport#2411]
##### 版本号：
1.6.6

##### 问题描述：
能不能支持 app 打印?
app发url,后台处理然后app选定打印机,进行打印
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
no

**Comment by zhangdaiscott** [comment]
商业版会出

**Comment by xiaolexi** [comment]
T_T

**Comment by xiaolexi** [comment]
2024/11/6 请问现在最新的商业版1.9.0能支持APP打印吗
