### ISSUE TITLE
api数据集调用第三方api需要传递token

### ISSUE THREAD

**Issue by ruoqing999** [jeecgboot/JimuReport#2413]
##### 版本号：

<name>jimureport-example</name>
    <groupId>org.jeecg</groupId>
    <artifactId>jimureport-example</artifactId>
    <version>1.6</version>
##### 问题描述：
我部署了jimureport-example这个服务，然后api数据集如果调用第三方api，需要请求头传递token认证的话，是不是不支持？
api数据集token机制详解，我看了这个好几遍，是在把积木框架集成到自己的项目里然后再去重写使用嘛？
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 1298191366** [comment]
你直接实现getToken，api获取的时候有传header，你用request.getHeader('token')获取就行

**Comment by ruoqing999** [comment]
> 你直接实现getToken，api获取的时候有传header，你用request.getHeader('token')获取就行

![image](https://github.com/jeecgboot/JimuReport/assets/139634169/8b64038a-7c93-425c-85a7-8c6048850b84)
不好意思哈，没有特别明白，我是想在api解析这里取调用某个需要传递token的接口，然后这个接口会从请求头的Authorization去获取token，我看那个api数据集token解析，是
![image](https://github.com/jeecgboot/JimuReport/assets/139634169/736c0f3f-330e-44b0-ad7f-f588cb223040)
这样子？但是我觉得这样应该不行叭？

**Comment by 1298191366** [comment]
我没理解你的需求，这里不是有个getToken吗，当你api解析的时候会自动将token给你传过去，是这个需求吗？
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/da4c7445-a7c3-482e-9f9f-83bcd8cea8da)
