### ISSUE TITLE
点击打印预览时会多出两个空白页

### ISSUE THREAD

**Issue by xiaolexi** [jeecgboot/JimuReport#2415]
##### 版本号：
1.6.6

##### 问题描述：
点击打印预览时会多出两个空白页

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/48915405/d482abbc-552c-419f-bf3a-8cf128f9c2ed)
![image](https://github.com/jeecgboot/JimuReport/assets/48915405/327cb423-9e71-404d-bf2b-3d3515a0c1b0)
![image](https://github.com/jeecgboot/JimuReport/assets/48915405/a75e0a28-bd02-4215-a6c1-2d6745ec70ba)
![image](https://github.com/jeecgboot/JimuReport/assets/48915405/5965388d-4be8-42ec-afd0-20c4bf6d3df2)

##### 重现步骤：
[A4QS国标四张版CE.json](https://github.com/jeecgboot/JimuReport/files/14121403/A4QS.CE.json)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
删除设计界面的空白行试一下

**Comment by xiaolexi** [comment]
这个没问题了
