### ISSUE TITLE
预览的时候图片消失及错乱

### ISSUE THREAD

**Issue by xiaolexi** [jeecgboot/JimuReport#2417]
##### 版本号：
1.6.6

##### 问题描述：
预览的时候图片消失及错乱
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/48915405/a1641758-99f5-488f-be16-59dd0e5228d6)

##### 重现步骤：
[A4常规国标三张版CE1768.json](https://github.com/jeecgboot/JimuReport/files/14125887/A4.CE1768.json)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 zy

**Comment by liaozhiyang** [comment]
效果图：
![image](https://github.com/jeecgboot/JimuReport/assets/8199499/a2f93b8c-c194-41c4-a23d-c7856a352476)
![image](https://github.com/jeecgboot/JimuReport/assets/8199499/4325aa9b-47fe-40a2-8c20-63b42e49225a)

循环块里面的图片别使用插入图片，要使用右侧这种方式，或者从库里取。
