### ISSUE TITLE
表格使用折行的情况下，导出pdf行高度计算不准确 , 生成的pdf文件中存在很多半截页面

### ISSUE THREAD

**Issue by relinson** [jeecgboot/JimuReport#2421]
##### 版本号：
1.5.9 ~ 1.6.6

##### 问题描述：
表格使用折行的情况下，导出pdf行高度计算不准确 , pdf文件中存在很多半截页面 。

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/1357222/61bd3556-37e7-4774-b96b-63b0cda3960a)

##### 重现步骤：
1. 设置某个列为折行 ， 该列数据长度实际显示2行以上 ；
2. 导出pdf ， 出现很多半截页面。

> 建议不要手工增加新页面 ， 让table自动扩展和分页。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
试试最新版 1.7.0
