### ISSUE TITLE
循环块设置后变成空白的，不显示数据了

### ISSUE THREAD

**Issue by zgiw** [jeecgboot/JimuReport#2425]
##### 版本号：
jimureport v1.6.6

##### 问题描述：
循环块设置后变成空白的，不显示数据了,也没有提示错误，在设置循环块之前，数据是能显示出来的，只是不是我想要的结果，因为我这个报表是标签，是要循环打印的

##### 错误日志&截图：
这是没设置循环块的打印预览结果：
![image](https://github.com/jeecgboot/JimuReport/assets/71875297/58fd92e9-c1fc-443a-b766-7949a5ec12dd)
这是设置循环块后的打印预览结果：
![image](https://github.com/jeecgboot/JimuReport/assets/71875297/9c2635c4-57f0-4052-8e29-3e7ecf442fe4)
这是设置页面：
![image](https://github.com/jeecgboot/JimuReport/assets/71875297/c3851378-7d2b-46e2-8fa1-bf8f77f63ef6)
这是数据集：
![image](https://github.com/jeecgboot/JimuReport/assets/71875297/9273acc6-2e89-46b5-866f-b32f4539f762)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请在积木官网做个示例，我们复现一下
