### ISSUE TITLE
导出pdf 底部边框消失,&出现空白页

### ISSUE THREAD

**Issue by xiaolexi** [jeecgboot/JimuReport#2427]
##### 版本号：
1.6.6

##### 问题描述：
导出pdf 底部边框消失,&出现空白页

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/48915405/267f930a-6ddc-4d46-9f60-44642fb5eebb)

##### 重现步骤：
[货位6520.json](https://github.com/jeecgboot/JimuReport/files/14318101/6520.json)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
试试最新版 1.7.0
