### ISSUE TITLE
导出PDF图像是发生错乱

### ISSUE THREAD

**Issue by xiaolexi** [jeecgboot/JimuReport#2430]
##### 版本号：
1.6.6

##### 问题描述：
导出PDF图像是发生错乱

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/48915405/1b62f597-790d-408a-81f0-bcbb8ad9fa02)

##### 重现步骤：
[社内现品票 (1).json](https://github.com/jeecgboot/JimuReport/files/14321043/1.json)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
试试最新版 1.7.0

**Comment by xiaolexi** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/48915405/699cba4d-8225-4651-8399-28789758433f)
升级1.7之后导出pdf图像还是存在同样的问题 T_T

**Comment by xiaolexi** [comment]
[2社内现品票.json](https://github.com/jeecgboot/JimuReport/files/14399243/2.json)
更新至1.7还是存在该问题

**Comment by xiaolexi** [comment]
官网的url能提供下不?

**Comment by xiaolexi** [comment]
我找不到官网做报表的入口,
官网的url能提供下不?

**Comment by zhangdaiscott** [comment]
http://jimureport.com/

**Comment by xiaolexi** [comment]
https://bootapi.jeecg.com/jmreport/shareView/925597627045990400?shareToken=07b9f749b04f4d4b876600bac742111d

我怎么在你们官网测试打印呢?没有数据吧

**Comment by xiaolexi** [comment]
https://bootapi.jeecg.com/jmreport/shareView/925597627045990400?sh
但是数据我不知道怎么弄进去.预览不了

**Comment by xiaolexi** [comment]
1.7.1版本试了下可以了
