### ISSUE TITLE
导出pdf 行距错乱,变得不可控

### ISSUE THREAD

**Issue by xiaolexi** [jeecgboot/JimuReport#2431]
##### 版本号：
1.6.6

##### 问题描述：
导出pdf 行距错乱,变得不可控

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/48915405/e00e846d-3dc0-42bc-a187-3ddb025325eb)

##### 重现步骤：
[社内现品票 (1).json](https://github.com/jeecgboot/JimuReport/files/14321052/1.json)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
试试最新版 1.7.0

**Comment by xiaolexi** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/48915405/a4bea263-28b6-45eb-8015-e65ebbcd956c)
升级1.7之后还是存在同样的问题.导出pdf行间距不可控

**Comment by lvdandan16** [comment]
收录 zy

**Comment by 1298191366** [comment]
已修复，待新版本发布
