### ISSUE TITLE
下载的报表文件名可以使用参数动态显示吗

### ISSUE THREAD

**Issue by superman4808** [jeecgboot/JimuReport#2432]
##### 版本号：
V1.6.3

##### 问题描述：
下载的报表文件名可以使用参数动态显示吗

##### 错误日志&截图：
![报表文件名修改](https://github.com/jeecgboot/JimuReport/assets/121927607/de5ec8f5-4a0d-4f90-b1e3-a5706f1908e3)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持
