### ISSUE TITLE
开启租户模式点击报表显示您没有权限访问该页面

### ISSUE THREAD

**Issue by wzlnt123456** [jeecgboot/JimuReport#2433]
##### 错误日志&截图：
![微信图片_20240220085417](https://github.com/jeecgboot/JimuReport/assets/143306650/ba88b5d5-12d8-455a-a731-887537873bb4)
![微信图片_20240220085441](https://github.com/jeecgboot/JimuReport/assets/143306650/c016da36-d2c4-497f-8b99-71df7c0e6260)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
说明没有拥有这个报表的租户吧

**Comment by wzlnt123456** [comment]
有租户的

**Comment by wzlnt123456** [comment]
谁能给个接口下载pdf的
教程吗

**Comment by wzlnt123456** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/143306650/3cb22873-8d06-4db9-8251-2968abe662fc)
现在最新版本这个怎么用？搞不懂了？

**Comment by zhangdaiscott** [comment]
免费版用不了

**Comment by zhangdaiscott** [comment]
cr 测试jeecgboot集成

**Comment by hoperunChen** [comment]
请修改`org.jeecg.config.jimureport.JimuReportTokenService.getTenantId()`方法修改为：
```
/**
 * 获取多租户id
 * @return tenantId
 */
public String getTenantId() {
    HttpServletRequest request = SpringContextUtils.getHttpServletRequest();
    String tenantId = request.getParameter("tenantId");
    if(StringUtils.isEmpty(tenantId)) {
        tenantId = request.getHeader("tenantId");
        if (StringUtils.isNotEmpty(tenantId)) {
            return tenantId;
        }
    }
    return tenantId;
}
```
