### ISSUE TITLE
1.7 版本主子表循环打印，主子表参数查询显示问题

### ISSUE THREAD

**Issue by fengqshanl** [jeecgboot/JimuReport#2435]
##### 版本号：

1.7.0

##### 问题描述：

主子表循环打印，主子表参数查询显示问题，应该每一个主表根据 id 去子表中查询，结果显示的是错误的查询结果。

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/101240271/85befc1f-842c-47f6-8586-e9422f871279)

##### 重现步骤：

设置主子表循环打印，配置循环打印参数，设置循环块，配置主循环

详细配置如下：

[主子表循环打印.json](https://github.com/jeecgboot/JimuReport/files/14340973/default.json)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
已修复，请等待新版本发布。
