### ISSUE TITLE
js增强的三级联动可以实现多选联动吗

### ISSUE THREAD

**Issue by whatwhatw** [jeecgboot/JimuReport#2437]
##### 版本号：
1.6.6

##### 问题描述：
1、三级联动可以实现多选联动吗？

##### 错误日志&截图：
帮助文档中的三级联动，
![image](https://github.com/jeecgboot/JimuReport/assets/154484667/824381ad-f385-4b6c-a48d-07edabc780ed)
可以实现查询条件多选，即选择多个省，第二级参数出现这多个省的市的下拉数据吗
![image](https://github.com/jeecgboot/JimuReport/assets/154484667/a919e573-82a7-40c1-8fd4-0e029889e597)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持

**Comment by whatwhatw** [comment]
好的，谢谢
