### ISSUE TITLE
下拉单选框或多选框如何改变其高度？

### ISSUE THREAD

**Issue by breezeGit** [jeecgboot/JimuReport#2438]
##### 问题描述：下拉单选框或多选框的宽度好像是用的行内样式style设置的，通过增强CSS是不是无法修改？
  .jm-query-form .ivu-scroll-container{
    height:400px;
   }
通过类似这种设置无效

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/22423315/1b14c0d2-5555-4e88-b0e3-ecde638a1868)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持
