### ISSUE TITLE
跨站脚本（cross-site scripting，XSS）漏洞

### ISSUE THREAD

**Issue by lhhgh** [jeecgboot/JimuReport#2439]
##### 版本号：
1.6.1

##### 问题描述：
出现跨站脚本（cross-site scripting，XSS）漏洞

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/113173621/f2867d63-c53e-44a2-bc16-96509044d726)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
处理过，升级到最新版

**Comment by lhhgh** [comment]
目前升级到1.7.0后，还被扫码到了跨脚本漏洞，请问还需要添加哪些配置？

**Comment by zhangdaiscott** [comment]
那个接口？

**Comment by zhangdaiscott** [comment]
我们确认下

**Comment by lhhgh** [comment]
请问，跨站脚本漏洞修复了吗？目前1.7.0版本，还需要添加什么配置吗？

**Comment by zhangdaiscott** [comment]
ws

**Comment by lhhgh** [comment]
啥意思？

**Comment by 1298191366** [comment]
未复现，请描述一下你是怎样操作触发的XSS攻击。直接预览页面传参还是接口调用？

**Comment by lhhgh** [comment]
我没有方式复现，公司使用明鉴漏洞扫描系统扫描出来的。上面的图片是漏扫文档的截图
