### ISSUE TITLE
增加加载效果

### ISSUE THREAD

**Issue by 199hl** [jeecgboot/JimuReport#2440]
##### 问题描述：
在打开积木报表的时候 页面展示出来了 但是数据部分尚未展示会出现空白情况建议增加一个加载效果 直到接口（/jmreport/show）请求结束

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/67632039/8cfad2f7-f64e-4e71-bfae-c8907943f082)

##### 重现步骤：
大数据量下会出现

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
多大的数据量

**Comment by 199hl** [comment]
> 多大的数据量

500-1000条数据左右

**Comment by 199hl** [comment]
200条数据 导出pdf后 pdf出现一条数据占据一整页的情况 隔一张出现一次
![image](https://github.com/jeecgboot/JimuReport/assets/67632039/3af13feb-9cd5-42cf-9faf-20cba8aa13e3)

**Comment by zhangdaiscott** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
