### ISSUE TITLE
查询条件联动下拉数据问题

### ISSUE THREAD

**Issue by whatwhatw** [jeecgboot/JimuReport#2445]
版本：1.6.6

如图：第一级机构有两个选项，选择全部的时候可以查询到5个返回值，也在控制台打印了，但是药房的下拉没数据，
![13719c333ea7c445e81752541f136c72](https://github.com/jeecgboot/JimuReport/assets/154484667/2e0e4fa4-d9c8-4888-b9a1-924ac89b1e74)

选择演示机构的时候，后台返回长度为4的数据信息，但药房的下拉显示上次全部查询的数据。
![DDBB47A0-94A5-463b-AD43-B1BC9854E67A](https://github.com/jeecgboot/JimuReport/assets/154484667/117e3078-b144-4e1f-94e5-039558452664)

js 配置：
`function init(){
// 加载第1个下拉框数据
$http.metaGet('/jmreport/getOrgList').then(res=>{
  let options =  res.data;
console.log(options);
  this.updateSelectOptions('drug_acceptance', 'orgId', options)
})
// 监听第1个下拉框改变事件 加载第2个下拉框数据
this.onSearchFormChange('drug_acceptance', 'orgId', (value)=>{
    let params = {params: {pid: value}}
    $http.metaGet('/jmreport/getPharmacyByOrg', params ).then(res=>{
        let options =  res.data;
console.log(options);
        this.updateSelectOptions('drug_acceptance', 'deptId', options)
    })
})
}`

_Originally posted by @whatwhatw in https://github.com/jeecgboot/JimuReport/issues/2066#issuecomment-1963275156_

**Comment by whatwhatw** [comment]
我发现updateSelectOptions方法有些数组数据无法双向绑定（这不是您的原因，这还是vue2的特性），建议您将updateSelectOptions方法修改
  updateSelectOptions(dbCode, fieldName, options){
        for(let i=0;i<this.configQueryList.length;i++){
            let item = this.configQueryList[i]
            if(item.dbCode == dbCode && item.name == fieldName && item.mode == 7){
                this.$set(this.configQueryList[i],'dictList',options)
                break;
            }
        }
    },

**Comment by zhangdaiscott** [comment]
ws

**Comment by zhangdaiscott** [comment]
图片裂了重新上传

**Comment by whatwhatw** [comment]
已经解决了，谢谢
