### ISSUE TITLE
报表配置的统计值（最大值，最小值，平均值等只有第一行生效）

### ISSUE THREAD

**Issue by LITIE-ai** [jeecgboot/JimuReport#2447]
##### 版本号：
<dependency>
	<groupId>org.jeecgframework.jimureport</groupId>
	<artifactId>jimureport-spring-boot-starter</artifactId>
	<version>1.5.6</version>
</dependency>
##### 问题描述：
报表配置的统计值（最大值，最小值，平均值等只有第一行生效

##### 错误日志&截图：
![2C N83P{U3W} `UK@(UCWM](https://github.com/jeecgboot/JimuReport/assets/79312962/d0a089dc-e5f1-42cb-b2c2-0dfe9c397f0e)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
遇到问题先升级到最新版看看是否存在
