### ISSUE TITLE
删除行和列之后报错

### ISSUE THREAD

**Issue by aizimo** [jeecgboot/JimuReport#2448]
##### 版本号：
1.5

##### 问题描述：
在删除了好多列和行之后，出现上述报错信息，在删除之前都正常使用，

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/129708440/bdd21568-57cc-436b-8679-8627701603ee)

##### 重现步骤：
删除了好多列和行之后

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
无法支持
