### ISSUE TITLE
积木报表连接sqlserver数据库，打开报表设计报错

### ISSUE THREAD

**Issue by Carson-Mr** [jeecgboot/JimuReport#2452]
集成积木报表，选择sqlserver数据库报错
![image](https://github.com/jeecgboot/JimuReport/assets/15940077/7cb8a4f4-e1ba-404d-bf1f-b934a2fff492)
![image](https://github.com/jeecgboot/JimuReport/assets/15940077/1d1db2cb-f55a-4e45-ac0f-5359f7ff3085)

**Comment by zhangdaiscott** [comment]
按照格式发帖
