### ISSUE TITLE
内网环境使用

### ISSUE THREAD

**Issue by basepoint-99** [jeecgboot/JimuReport#2454]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by basepoint-99** [comment]
版本号：无
问题描述：内网环境无法下载依赖，能否通过github上的程序打成jar包拿进去本地引入，有无教程
错误日志&截图：无
重现步骤：无

**Comment by zhangdaiscott** [comment]
按格式要求发帖，会被直接删掉;

**Comment by zhangdaiscott** [comment]
http://jimureport.com/download
