### ISSUE TITLE
 jmReport(1.7版本) JSON parse error: not close json text, token : ,

### ISSUE THREAD

**Issue by wangdaxia163** [jeecgboot/JimuReport#2456]
##### 版本号：
jimureport-spring-boot-starter 1.7版本

##### 问题描述：
报JSON错误
请求地址：http://localhost:8400/jmreport/excelQueryName
第一次保存成功，第二次修改保存就报错。
报错：JSON parse error: not close json text, token : ,

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/13695400/ddca1750-18a6-44fa-9e35-724430f5570f)

##### 重现步骤：
{"apiCode":"","apiMethod":"","apiUrl":"","code":"20240303093946","createBy":"","createTime":"2024-03-03 09:39:47","cssStr":"","dataList":"","delFlag":0,"dictInfo":"","id":"924082127030919168","isRefresh":"","jsStr":"","jsonStr":"{\"loopBlockList\":[],\"area\":{\"sci\":0,\"width\":100,\"eci\":0,\"sri\":5,\"eri\":5,\"height\":25},\"excel_config_id\":\"924082127030919168\",\"printConfig\":{\"layout\":\"portrait\",\"printCallBackUrl\":\"\",\"paper\":\"A4\",\"isBackend\":false,\"width\":210,\"definition\":1,\"marginX\":10,\"height\":297,\"marginY\":10},\"hiddenCells\":[],\"zonedEditionList\":[],\"rows\":{\"0\":{\"cells\":{\"2\":{\"text\":\"fdsg \"}}},\"2\":{\"cells\":{\"1\":{\"text\":\"sdfg\"},\"2\":{\"text\":\"sfdg\"},\"3\":{\"text\":\"sfdg\"}}},\"3\":{\"cells\":{\"1\":{\"text\":\"sfdg\"},\"2\":{\"text\":\"sgf\"},\"3\":{\"text\":\"sfdg\"}}},\"4\":{\"cells\":{\"1\":{\"text\":\"sdfg\"},\"2\":{\"text\":\"sdfg\"},\"3\":{\"text\":\"sdfg\"}}},\"len\":100,\"5\":{\"cells\":{\"0\":{},\"1\":{\"text\":\"fdgjd\"},\"2\":{\"text\":\"fj\"},\"3\":{\"text\":\"fjfgj\"}}},\"6\":{\"cells\":{\"1\":{\"text\":\"fgj\"},\"2\":{\"text\":\"fgj\"},\"3\":{\"text\":\"fgj\"}}}},\"dbexps\":[],\"dicts\":[],\"rpbar\":{\"show\":true,\"pageSize\":\"\",\"btnList\":[]},\"fixedPrintHeadRows\":[],\"fixedPrintTailRows\":[],\"freeze\":\"A1\",\"dataRectWidth\":400,\"displayConfig\":{},\"background\":false,\"name\":\"sheet1\",\"autofilter\":{},\"styles\":[],\"validations\":[],\"cols\":{\"len\":50},\"merges\":[]}","name":"GDSHGS","note":"","pyStr":"","status":"","template":0,"tenantId":"","thumb":"","type":"printinfo","updateBy":"","updateTime":"2024-03-03 09:39:47","viewCount":0}

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请提供重现步骤

**Comment by zhangdaiscott** [comment]
无回复，关闭
