### ISSUE TITLE
报表页面字段数据能进行超链接点击跳转到服务端指定单号的详情页面吗？

### ISSUE THREAD

**Issue by superman4808** [jeecgboot/JimuReport#2457]
##### 版本号：
V1.6.3

##### 问题描述：
字段数据能进行超链接点击跳转到指定单号的详情页面吗？

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/121927607/0d45ad53-273b-48d0-bb83-0bee874b8020)
![screenshot-20240304-093100](https://github.com/jeecgboot/JimuReport/assets/121927607/3ed25ce3-cf67-48c2-8bf5-e30855bda5de)

##### 重现步骤：
[yundan.zip](https://github.com/jeecgboot/JimuReport/files/14475577/yundan.zip)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
可以，传递参数，接受rul你自己设计规则

**Comment by superman4808** [comment]
有案例吗？能发一下吗？谢谢！
