### ISSUE TITLE
1.6.6版本，下拉多选查询不生效

### ISSUE THREAD

**Issue by dx0809** [jeecgboot/JimuReport#2458]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/35514496/5a0226c1-931a-489d-9fd0-fb249ee84385)
![%}I6(EP3%YD 3Z6_ 63 IO6](https://github.com/jeecgboot/JimuReport/assets/35514496/57640a19-2b75-499d-8fba-e0556c3c2cb3)
![_2U4$O)T%Y7~N1}~UBZ$5J7](https://github.com/jeecgboot/JimuReport/assets/35514496/44a610e7-99e7-4a98-b0aa-391ab08dab62)

##### 重现步骤：
1、配置的SQL数据集，接收多选的参数
2、配置下拉多选
3、点击查询，日志有打印SQL语句，但是没生效，1个值和多个值都不生效

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
in查询参考文档：https://help.jeecg.com/jimureport/query/function.html
