### ISSUE TITLE
动态合计无效

### ISSUE THREAD

**Issue by Missmei** [jeecgboot/JimuReport#2461]
##### 版本号
1.6.1

##### 问题描述：
横向动态列之后无法统计

##### 错误日志&截图：

![8c07ad99a14e8a8dd00abb83b33281f9](https://github.com/jeecgboot/JimuReport/assets/61619104/2b78c89b-1859-4ef6-90b4-073d7b113b5d)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
=DBSUM(db.xx)
https://help.jeecg.com/jimureport/function/tongji.html

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by hoperunChen** [comment]
已修复，待新版本发布。
