### ISSUE TITLE
docker部署的积木报表，一年多了运行正常。今天突然访问不了，发现是jimureport的数据库不见了，请问如何恢复

### ISSUE THREAD

**Issue by 972293570** [jeecgboot/JimuReport#2462]
##### 版本号：
v1.5.2 | 2022-07-12

##### 问题描述：
docker部署的积木报表，一年多了运行正常。今天突然访问不了，发现是jimureport的数据库不见了，请问如何恢复

##### 重现步骤：
无法重现，请问如何恢复

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 972293570** [comment]
![Uploading jim.png…]()

**Comment by 972293570** [comment]
![jim](https://github.com/jeecgboot/JimuReport/assets/16028038/116bb5fd-dd04-437d-8f04-2b2f6c65ccfa)

**Comment by 972293570** [comment]
不好意思，之前上传的截图没成功，在这里补充下：

**Comment by 972293570** [comment]
不好意思之前的截图没上传成功，在这里补充下：
![image](https://github.com/jeecgboot/JimuReport/assets/16028038/6d5fd9b1-4677-467b-bcfb-b882e7f633f7)
![image](https://github.com/jeecgboot/JimuReport/assets/16028038/1c3d9689-901e-48dc-8a88-440352e15706)
![image](https://github.com/jeecgboot/JimuReport/assets/16028038/a14727f6-3803-4532-a342-d40e32622f9f)

**Comment by hzlskj** [comment]
在线大屏SQL数据链接失败哦，咋搞哦

**Comment by zhangdaiscott** [comment]
这个得你自己搞啊，服务器的事情，跟程序无关
