### ISSUE TITLE
升级到1.7.0之后，菜单配置“打开方式”为“外部”，能正常访问报表；“打开方式”为“内部”，提示“HTTP Status 400 – Bad Request”

### ISSUE THREAD

**Issue by angelina0311** [jeecgboot/JimuReport#2463]
##### 版本号：
1.7.0

##### 问题描述：
积木报表升级到1.7.0之后，菜单配置“打开方式”为“外部”，能正常访问报表；“打开方式”为“内部”，提示“HTTP Status 400 – Bad Request”

##### 错误日志&截图：
1、
![image](https://github.com/jeecgboot/JimuReport/assets/101538902/ae26945e-f3e8-415c-9bab-d8ee7e3d6c49)

![image](https://github.com/jeecgboot/JimuReport/assets/101538902/4f704d9b-45ab-40a1-afa1-839faeebe566)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
跟积木报表没关系吧
