### ISSUE TITLE
列太多超出屏幕后没有出现滚动条, 应该怎么配置

### ISSUE THREAD

**Issue by qiaojing1** [jeecgboot/JimuReport#2465]
##### 版本号：
1.6.6

##### 问题描述：
列太多超出屏幕后没有出现滚动条, 应该怎么配置

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/66162802/364e676b-beff-44a2-a271-6f52bd9ad26e)

##### 重现步骤：
配置一个列比较多的表格, 预览时列显示不全也没有横向滚动条

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
未复现，[请导出报表配置](https://help.jeecg.com/jimureport/issues.html)或升级到最新版试一下

放到缩小浏览器到一定比例会自动显示和隐藏滚动条
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/1a20fe94-ec67-4c83-ae50-cca15c2bed86)
