### ISSUE TITLE
在线大屏SQL数据链接失败

### ISSUE THREAD

**Issue by hzlskj** [jeecgboot/JimuReport#2466]
##### 问题描述：
前天开始大屏显示SQL数据链接失败

##### 错误日志&截图：

![D9089417CF39A59FE430548EEA01B94E](https://github.com/jeecgboot/JimuReport/assets/162468776/3b28ca17-3a79-4732-b371-0330d02d913c)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你自己连可以吗

**Comment by zhangdaiscott** [comment]
我们调整了下服务器的配置，你看看好了吗

**Comment by hzlskj** [comment]
还不对

**Comment by hzlskj** [comment]
非常感谢，正常了
