### ISSUE TITLE
英文单引号保存时发生错乱

### ISSUE THREAD

**Issue by xiaolexi** [jeecgboot/JimuReport#2468]
##### 版本号：
1.7.1

##### 问题描述：
英文单引号保存时发生错乱  '''''''''''''''''''''''''''''''

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/48915405/87bdc82e-2879-4a56-a066-dfb0a4e4d102)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
经测试，未复现。请在官网制作报表示例并提供ID

预览页面我也看了，应该没啥问题
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/e9c3cfaa-e568-4f9c-8c28-2cbb6c71c2ee)
