### ISSUE TITLE
报表如何实现动态列

### ISSUE THREAD

**Issue by 15900971514** [jeecgboot/JimuReport#2470]
##### 问题描述：
表格如何实现动态列，也就是动态表头，表格的部分列是固定的，**部分列是动态可配置**的，可以增加或者减少的。不要删帖，谢谢！

##### 错误日志&截图：
![动态表头](https://github.com/jeecgboot/JimuReport/assets/41932071/643ab006-f29a-4233-a7c7-5358e2f38dec)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 15900971514** [comment]
急求如何解决这个问题，万分感谢！

**Comment by zhangdaiscott** [comment]
ws

**Comment by zhangdaiscott** [comment]
看看 横向动态列分组
https://help.jeecg.com/jimureport/group/transverseDynamic.html

**Comment by zhangdaiscott** [comment]
暂时不支持
