### ISSUE TITLE
关于jimureport的问题咨询

### ISSUE THREAD

**Issue by jiandandianhao** [jeecgboot/JimuReport#2471]
##### 版本号：
v1.7.2

##### 问题描述：
你好，能咨询下下拉树目前测试只能支持api接口数据，是否可以支持sql数据集，如果可以是要如何实现?

##### 错误日志&截图：
none

##### 重现步骤：
none

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
只支持接口

**Comment by BO-DI** [comment]
> 只支持接口

那下拉树的动态传参怎么处理的呢？
![image](https://github.com/user-attachments/assets/60403ea8-63ab-4da4-a432-bd264ebe30f2)
