### ISSUE TITLE
使用函数DBSUM，where 条件问题

### ISSUE THREAD

**Issue by gaojd** [jeecgboot/JimuReport#2472]
##### 版本号：
V1.6.5

##### 问题描述：
使用函数DBSUM，选择查询条件时，SQL报错，第一个条件前没有加上and

##### 错误日志&截图：
![QQ截图20240311102918](https://github.com/jeecgboot/JimuReport/assets/11324700/7a3261ed-244f-43d2-a12b-0934d332fdda)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
已修复可升级至1.7.0
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.7.0</version>
</dependency>
```
