### ISSUE TITLE
查询条件不支持新增一个自定义按钮

### ISSUE THREAD

**Issue by qingqiuerpan** [jeecgboot/JimuReport#2473]
##### 版本号：
1.7.2-beta

##### 问题描述：
在查询条件中追加一个按钮，并给按钮绑定点击事件，点击之后直接报500，Token校验失败

##### 错误日志&截图：
如上

##### 重现步骤：

如上
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持
