### ISSUE TITLE
多单元格合并后设置二维码扫描不出来

### ISSUE THREAD

**Issue by YuHong931219** [jeecgboot/JimuReport#2476]
##### 版本号：
1.6.5

##### 问题描述：
当多个单元格合并后，再设置二维码，这个时候预览扫描，二维码不能识别

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/29400623/45220ceb-0f93-457a-bd69-8c65ab19169b)

##### 重现步骤：
1、添加sql数据集，查询出二维码的内容（可能有拼接字符串）
2、合并单元格，横向纵向都可以，合并三个以上效果会比较明显
3、保存报表，配置参数预览，二维码识别不出来

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by YuHong931219** [comment]
上述图片是图层二维码，补充一张单元格二维码
![image](https://github.com/jeecgboot/JimuReport/assets/29400623/23f90243-2908-4141-8c4f-d1e20da95f73)

**Comment by lvdandan16** [comment]
收录 zy

**Comment by liaozhiyang** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/8199499/c3637d92-1135-49f1-9d22-c231b93ebeed)
有详细的步骤或者录屏吗？不好复现出来
