### ISSUE TITLE
一个单元里面放多个数据源的字段，只会显示第一个，后面的数据源数据字段值不会显示

### ISSUE THREAD

**Issue by zszxz** [jeecgboot/JimuReport#2477]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/49815243/9806c723-7f2e-4500-8ece-583935b0f0a0)

**Comment by zhangdaiscott** [comment]
此功能已经修复，下个版本会支持

**Comment by ayjdcg** [comment]
1.7.4版本仍有这个问题
