### ISSUE TITLE
分组以后序号问题

### ISSUE THREAD

**Issue by sunRUI78** [jeecgboot/JimuReport#2479]
版本号：1.5.6
前端版本：还是 vue2版？
问题描述： 行号给的连个函数=row() 和 #{t_index+1} 无法实现需求
想要的效果是 序号列和未合并列对应

![微信图片_20240313114307](https://github.com/jeecgboot/JimuReport/assets/163228727/e6e18646-32ff-49b9-93a4-723264e665c6)

截图&代码：
这是我做的效果图

![微信图片_20240313114328](https://github.com/jeecgboot/JimuReport/assets/163228727/496a7f40-1da5-4227-be55-fc349e8255c6)

![微信图片_20240313114334](https://github.com/jeecgboot/JimuReport/assets/163228727/c2aa87fc-00b8-4e9a-9e5a-9997a193c84a)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by sunRUI78** [comment]
想知道这种问题  我该如何解决

**Comment by sunRUI78** [comment]
也就是说我想要实现这种效果  现在还不支持是吗？
![微信图片_20240313114307](https://github.com/jeecgboot/JimuReport/assets/163228727/853fe549-c69c-428e-af5b-84a4d581724a)

**Comment by zhangdaiscott** [comment]
都不支持，后面版本

**Comment by sunRUI78** [comment]
但是我看文档有这个功能图例  就是不知道实现 
![1958f43e202809b1658c1e8faf40ab7](https://github.com/jeecgboot/JimuReport/assets/163228727/e8980220-af44-4425-b183-2f07f7fd4a45)
![50f88260918de637dfe07cf19798639](https://github.com/jeecgboot/JimuReport/assets/163228727/ee176ecd-d894-4561-9f7c-e6586f1b3e3b)

**Comment by sunRUI78** [comment]
我看到了样例  这个样例怎么实现的

**Comment by hoperunChen** [comment]
设计：
![image](https://github.com/jeecgboot/JimuReport/assets/13013558/d759076f-3da5-49b2-a952-66702fd6f446)
预览：
![image](https://github.com/jeecgboot/JimuReport/assets/13013558/623291bf-f573-498a-819e-85ef749b02c7)
@sunRUI78  你要的是这个效果吗？

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题

**Comment by BO-DI** [comment]
row()或者${数据集_index+1}只能实现当页行号，无法实现数据全集的行号，这个问题三年了竟然还没修复？
