### ISSUE TITLE
分版后底部合计丢失

### ISSUE THREAD

**Issue by LH040707** [jeecgboot/JimuReport#2481]
##### 版本号：
1.6.6

##### 问题描述：
分版底部合计丢失

##### 错误日志&截图：
![09c9b105cd6e9eadbbc6fc3869b4040](https://github.com/jeecgboot/JimuReport/assets/24651895/be364408-425f-4199-b19f-ed1238a8cf55)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
@LH040707 没看出来哪里有问题，烦请详细描述下您的问题。

**Comment by LH040707** [comment]
> @LH040707没看出来哪里有问题，烦请详细描述下您的问题。

如题所属左边合计少了第18行，改行是第二个版的合计

**Comment by hoperunChen** [comment]
> > @LH040707没看出来哪里有问题，烦请详细描述下您的问题。
> 
> 如题所属左边合计少了第18行，改行是第二个版的合计

您这个报表是左右两边数据集数量不一样对吗？左边数据集有29条数据，右边18条数据，所以左右两边合计不在同一行。
要不您把设计页截下图看看。

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
