### ISSUE TITLE
oracle数据库查不到数据

### ISSUE THREAD

**Issue by SunYoung06** [jeecgboot/JimuReport#2482]
##### 问题描述：
初始集成，这里主要是不清楚sql中，oracle语句为何查不到数据

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/28640749/f8d4546a-5311-443f-9dfd-1923a59382a5)

![image](https://github.com/jeecgboot/JimuReport/assets/28640749/c09e7e3f-35b9-4270-a7e4-212cb1652033)

![image](https://github.com/jeecgboot/JimuReport/assets/28640749/3a6eb020-c900-482b-bd59-a0dbc9305f2b)

##### 重现步骤：
1. 将jar集成在我司pom，2.将oracle的脚本，create到我司数据库，3.程序启动，4.浏览器输入ip:port/jmreport/list，显示的页面如下图，日志如下，
数据库中能查到从脚本中导入库表中的数据，

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
看日志有没有报错，日志图片不显示

**Comment by SunYoung06** [comment]
看不到这个是吗？

**Comment by 1298191366** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/1d58493d-ec6d-41d2-aab3-ec0694361378)
这个应该是有数据，你查询的数据库和查询列表的数据库不一致，查询列表的数据库是`JIMU_REPORT`,我觉的是你的sql没数据
