### ISSUE TITLE
SQL语句中包含GROUP BY 则下拉多选无法正常使用

### ISSUE THREAD

**Issue by zhifayong** [jeecgboot/JimuReport#2486]
##### 错误日志&截图：
![709465eb8e44641e842228e32354396e](https://github.com/jeecgboot/JimuReport/assets/163961282/edb2df4a-3ec0-4ae4-a965-7483734297e1)
![461cbf134859a9838bffd217a73fe019](https://github.com/jeecgboot/JimuReport/assets/163961282/b4948c0d-e60e-4295-80c1-f1e2085a2518)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
老版本无法处理，请先升级到最新版
