### ISSUE TITLE
若依plus配置

### ISSUE THREAD

**Issue by baflys** [jeecgboot/JimuReport#2487]
##### 错误日志&截图：
![Snipaste_2024-03-20_09-08-37](https://github.com/jeecgboot/JimuReport/assets/60059460/51eb1337-6399-46b4-876f-3452e699dd46)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
怎么访问的，积木报表是后台集成，需要通过后台端口地址访问
