### ISSUE TITLE
并发线程安全问题

### ISSUE THREAD

**Issue by LIUSHUAI2018** [jeecgboot/JimuReport#2488]
##### 版本号：
1.6.6

##### 问题描述：

在使用导出excel时有一定的几率会导出别人正在导出的数据，我在反编译源码看原因到时候找到这个地方，希望官方能看一下
##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/37928107/d65b49d1-fafb-49f2-889f-9182771ebc41)
![image](https://github.com/jeecgboot/JimuReport/assets/37928107/c5326e06-f15c-4d2d-b7fb-b630baff2c03)
希望官方能解答一下这个问题

**Comment by LIUSHUAI2018** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/37928107/75fcb652-4520-44da-a338-83948817f833)

这个对象是单例的吧

**Comment by zhangdaiscott** [comment]
cr

**Comment by LIUSHUAI2018** [comment]
cr啥意思

**Comment by LIUSHUAI2018** [comment]
cr看的怎么样了，商业版本有修复吗

**Comment by hoperunChen** [comment]
已修复，下个版本更新。
