### ISSUE TITLE
BASE64图片类型单元格，导出PDF时图片不显示

### ISSUE THREAD

**Issue by duliming** [jeecgboot/JimuReport#2489]
##### 版本号：
1.7.2-beta

##### 问题描述：
Base64类型的单元格，导出PDF时不显示图片。预览时正常。

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/11660461/eb22775a-148b-4299-a6ce-1509e4ca172e)
导出PDF之后是这样的：
![image](https://github.com/jeecgboot/JimuReport/assets/11660461/b967f2cb-e7e9-41c1-ad6f-19e4b6de0502)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws
