### ISSUE TITLE
导出报错

### ISSUE THREAD

**Issue by gendao** [jeecgboot/JimuReport#2490]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/18734206/ffd5d0eb-f979-4684-b197-f8d5275d0681)
![image](https://github.com/jeecgboot/JimuReport/assets/18734206/80901c55-70db-471a-adb3-5b54f7bb3fcb)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/13013558/1b45015f-4f16-466d-8c1e-cb9d698b8e94)
未复现，请提供复现步骤或示例。
