### ISSUE TITLE
从1.4.0更新至1.6.6版本，下拉多选，下拉输入数据，无法正常查询匹配；且double（）函数将String类型转化为数值型失败

### ISSUE THREAD

**Issue by zhifayong** [jeecgboot/JimuReport#2491]
##### 错误日志&截图：
<img width="82" alt="企业微信截图_1711006167916" src="https://github.com/jeecgboot/JimuReport/assets/163961282/906cb0dd-5944-4caa-8aea-8cfca7200dce">
<img width="83" alt="企业微信截图_17110061869401" src="https://github.com/jeecgboot/JimuReport/assets/163961282/9779b28f-98ce-4a7b-952b-aba5907d4cad">
<img width="447" alt="企业微信截图_17110061146862" src="https://github.com/jeecgboot/JimuReport/assets/163961282/f84b383b-a92b-420c-9974-4ef5e79fd0ac">
<img width="171" alt="企业微信截图_17110063023335" src="https://github.com/jeecgboot/JimuReport/assets/163961282/68ad2bca-5e7d-4911-9531-906a85454d91">
<img width="674" alt="企业微信截图_17110062532013" src="https://github.com/jeecgboot/JimuReport/assets/163961282/ea0c490c-b17b-4aa1-b2bf-a2e25f00289c">

##### 重现步骤：
在pom文件从1.4.0修改为1.6.6版本后更新依赖，于是出现了以上问题

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
下拉输入数据是什么意思？

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by zhangdaiscott** [comment]
无回复，暂时关闭
