### ISSUE TITLE
火狐浏览器打印兼容

### ISSUE THREAD

**Issue by Yxw521** [jeecgboot/JimuReport#2492]
##### 错误日志&截图：
火狐的效果
![image](https://github.com/jeecgboot/JimuReport/assets/76502207/4f6ebee1-988d-4fa9-a95d-7f93dab74eb9)
![image](https://github.com/jeecgboot/JimuReport/assets/76502207/d9f1cf7e-ff3f-47d9-bdc8-ba8ad96afd62)
谷歌的效果

![image](https://github.com/jeecgboot/JimuReport/assets/76502207/27f582c1-46cd-44f2-809a-a1fd7bddce5d)

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
这是火狐浏览器升级之后才有的问题，用116版本测试是正常，124版本测试异常，只是看着异常，但是打印其实是正常的。
暂时先不改动。
![image](https://github.com/jeecgboot/JimuReport/assets/8199499/e0275113-74ef-40d3-b4fd-261d7c48b624)
