### ISSUE TITLE
SUM、MAX、MIN统计函数混合使用问题

### ISSUE THREAD

**Issue by maxid** [jeecgboot/JimuReport#2493]
##### 版本号：
1.6.6～1.7.2-beta

##### 问题描述：
SUM、MAX、MIN统计函数混合使用问题

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/927429/191b8dfc-6592-41e5-81a7-ff0e653da510)

##### 重现步骤：
公式设置：
![image](https://github.com/jeecgboot/JimuReport/assets/927429/850b4138-c173-495b-a460-952deae88a35)
结果：
![image](https://github.com/jeecgboot/JimuReport/assets/927429/191b8dfc-6592-41e5-81a7-ff0e653da510)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
下个版本，会有  是否参与计算，设置忽略
