### ISSUE TITLE
导出PDF失败打不开

### ISSUE THREAD

**Issue by slajdfk** [jeecgboot/JimuReport#2495]
##### 版本号：
1.6.6

##### 问题描述：

导出pdf失败
##### 错误日志&截图：
操作失败，Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: com.lowagie.text.pdf.PdfPCell.setRowspan(I)V

##### 重现步骤：

<img width="601" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/157799272/7e0ea4e4-23af-43e8-b315-d0949e3dbb50">
这个包下面没有此方法。
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
感觉你这个是依赖冲突导致，自己排查下
