### ISSUE TITLE
折线图不显示分页数据？

### ISSUE THREAD

**Issue by 312353457** [jeecgboot/JimuReport#2497]
##### 版本号：
1.7.2-beta

##### 问题描述：
我使用SQL数据集创建数据报表，上部分显示数据表单，下半部分显示折线图，10条数据一页；
问题：
翻页的时候表单数据变化，折线图的数据不会跟随变化，请问怎么解决？

##### 错误日志&截图：
 
![Uploading QQ截图20240326110524.png…]()

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
图片列了

**Comment by jeecgos** [comment]
cr

**Comment by hoperunChen** [comment]
在预览时图表是展示所有数据的，已修复图表在首次加载时展示分页数据的问题。
