### ISSUE TITLE
如何设置固定位置不变，不随着上面的动态数据向下或向上移动

### ISSUE THREAD

**Issue by fantsyforever** [jeecgboot/JimuReport#2498]
##### 问题描述：
打印页面分两部分，中间部分是动态数据，条数不确定。下部是固定位置的数据。如何设置或者操作可以让下部固定不变，不随着中间部分的数据条数而向上或向下移动。

##### 错误日志&截图：
![QQ截图20240326110618](https://github.com/jeecgboot/JimuReport/assets/7495584/d368530c-79dc-4426-8f90-55d1ea69c3f8)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持
