### ISSUE TITLE
报表参数不能选择查询

### ISSUE THREAD

**Issue by JackMa1046** [jeecgboot/JimuReport#2500]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/63281884/4df2fee1-c6bb-4b70-a167-20ba8f85e72d)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by JackMa1046** [comment]
ws是什么意思？

**Comment by hoperunChen** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/13013558/b41d4b6c-0b1c-4cba-bbd2-ebee6eaec91d)
![image](https://github.com/jeecgboot/JimuReport/assets/13013558/0e17b17b-e6fc-46d0-8cc1-2e68fdf0b90d)
未复现该问题，请提供详细的重现步骤。

**Comment by zhangdaiscott** [comment]
确认下项目是不是没有集成redis
