### ISSUE TITLE
使用SQL集合报表，部分国家不展示

### ISSUE THREAD

**Issue by yi-jun** [jeecgboot/JimuReport#2503]
##### 版本号：
1.6.6

##### 问题描述：
使用SQL数据集合，在SQL中查询出来国家，如：英国、美国、日本、比利时。在SQL预览中能看到国家，而在预览报表时看不见，点击后才能看到，猜测是隐藏了？或者是字体颜色有误？

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/12711303/c350a88e-3aec-420b-8b08-d125263b6c5d)
![image](https://github.com/jeecgboot/JimuReport/assets/12711303/fd7b760b-cae8-43e3-b057-da8f9e0d9433)
![image](https://github.com/jeecgboot/JimuReport/assets/12711303/9b55a6c3-7d38-4c3f-a5bd-8e1dc1821355)

##### 重现步骤：
数据库存储是一个订单表，里面国家是代码，还有一个字典表，SQL是订单表关联字典表，在SQL层面查询出来就已经是中文

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by hoperunChen** [comment]
未复现，烦请提供复现示例或详细步骤。
![image](https://github.com/jeecgboot/JimuReport/assets/13013558/2d9a8fa6-a381-41a7-9a55-4ce954169420)
![image](https://github.com/jeecgboot/JimuReport/assets/13013558/fd076377-11ad-49a0-80c8-3c5be593f442)

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
