### ISSUE TITLE
API接口返回的数据源，返回数据结构是固定的吗？

### ISSUE THREAD

**Issue by superman4808** [jeecgboot/JimuReport#2504]
##### 版本号：
V1.6.3

##### 问题描述：
返回的数据结构不同，接口是有数据返回，但是积木解析不出数据

##### 错误日志&截图：
以下为能解析出数据：
![have1](https://github.com/jeecgboot/JimuReport/assets/121927607/02a2a147-37ee-4a12-af63-4e5803c858ed)
![have](https://github.com/jeecgboot/JimuReport/assets/121927607/ba6c1867-e139-400b-a7d7-bf1fee0c6da2)

下面是解析不出数据：
![null1](https://github.com/jeecgboot/JimuReport/assets/121927607/51a25cf4-fc45-4520-9675-b12adb6c9d8d)
![null](https://github.com/jeecgboot/JimuReport/assets/121927607/c13311ca-0ca5-471a-a07e-8335760fa5f3)

##### 重现步骤：
[报表配置.zip](https://github.com/jeecgboot/JimuReport/files/14766197/default.zip)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
接口返回格式，请看积木要求，必须按照积木要求格式
