### ISSUE TITLE
是否支持统计报告配置导出

### ISSUE THREAD

**Issue by zhangkaichuang** [jeecgboot/JimuReport#2505]
需求：1、统计报告里可以配置一段统计文字，例如“本月PM2.5平均浓度66μg/m³，同比上升8.2%”，其中数据“66”、“8.2%”可通过连接数据库的方式配置获取；
2、统计报告里可配置报告封面、章节标题、统计文字、统计表、统计图，统计图表的样式可以自行设置
3、最终输出pdf报告

**Comment by zhangkaichuang** [comment]
![QQ图片20240327093518](https://github.com/jeecgboot/JimuReport/assets/77256324/57f6efd6-800d-4046-8d61-1ec61c74d75b)

**Comment by zhangdaiscott** [comment]
你配置成对应的格式，支持pdf导出

**Comment by zhangkaichuang** [comment]
我上面的图片是在word中编辑的，咱们的报表工具有类似与这样的编辑方式吗，您说的配置成对应的格式怎么配置呢，是在excel格式的编辑器中把文本整成我需要格式吗
