### ISSUE TITLE
自定义请求头不生效，返回401，认证失败，无法访问系统资

### ISSUE THREAD

**Issue by MrHuangdada** [jeecgboot/JimuReport#2506]
##### 版本号：
1.7.2-beta

##### 问题描述：
集成springboot项目，系统token的请求头是“Authorization”，但是报表的请求头是“token”，不匹配
重写customApiHeader方法，请求头还是“token”，致使报表的请求都是401

希望有适配的办法，或者解决的方案
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/165116574/640de3d0-87b5-40ba-a56b-d9eff76b5ffc)
![image](https://github.com/jeecgboot/JimuReport/assets/165116574/f2b7b4ab-609b-4a51-9164-93f2866ec1f5)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
原来的token规则得保留，可以额外加新的

**Comment by MrHuangdada** [comment]
> 原来的token规则得保留，可以额外加新的

大佬，怎么能加新的请求头？文档上没找到相关的说明
