### ISSUE TITLE
打印出现多张纸

### ISSUE THREAD

**Issue by wxynf4** [jeecgboot/JimuReport#2508]
##### 错误日志&截图：
![) QJS{DEH~T(79C@83`IUB9](https://github.com/jeecgboot/JimuReport/assets/45929130/0af0a3ad-35fb-4138-b3f7-dd54e32722fc)
![W3GUG @@$@0S)F4ZECJEV{V](https://github.com/jeecgboot/JimuReport/assets/45929130/0618015f-5243-499e-a167-568324a93cd6)
![image](https://github.com/jeecgboot/JimuReport/assets/45929130/c9fe2716-cd91-44e8-8775-f59c040dea0a)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by wxynf4** [comment]
> 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

官网ID：933623518602809344

**Comment by liaozhiyang** [comment]
已解决，下一版本发布。
在新版本未发布之前，你可在设计器把单元格有多行内容的行高稍微调高10像素。打印即可和设计器一致

![image](https://github.com/jeecgboot/JimuReport/assets/8199499/810a7ead-176f-406d-a0cb-6e12f0702f0d)
