### ISSUE TITLE
横向动态分组合计如何配置

### ISSUE THREAD

**Issue by WooZhangYan** [jeecgboot/JimuReport#2509]
##### 版本号：
1.6.6

##### 问题描述：
官方文档里面没有说明配置，类似于截图中的横向动态扩展列后进行总合计，即横向扩展日期，下一行能支持在最后一列求总和

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/104556081/2f72f6bf-8bd5-4f92-8509-1b37d966af99)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by hoperunChen** [comment]
横向小计文档：https://help.jeecg.com/jimureport/group/horizontalSubtotal.html

**Comment by WooZhangYan** [comment]
横向小计是分组内的求和，如截图我需要将一整行进行求和，目前只看到sum能支持，但是sum只支持静态的多列求和，如果横向扩展多列就没办法做到了

**Comment by hoperunChen** [comment]
动态分组总合计是支持的，直接用=sum(单元格坐标）就可以了，样例：
![image](https://github.com/jeecgboot/JimuReport/assets/13013558/602ebf93-f2fb-4bdb-a8dd-448c8e3c083b)
![image](https://github.com/jeecgboot/JimuReport/assets/13013558/e33c851f-dcb3-4c64-a03b-f2827bf2c202)

**Comment by WooZhangYan** [comment]
我配置出来计算结果不对呢，需要配置什么吗
![image](https://github.com/jeecgboot/JimuReport/assets/104556081/f001e73c-89c8-41ea-bd46-450d560e88a9)
![image](https://github.com/jeecgboot/JimuReport/assets/104556081/85ec2eeb-2916-4639-84bd-c06906d07c12)

**Comment by hoperunChen** [comment]
cr

**Comment by hoperunChen** [comment]
已修复，下个版本更新
