### ISSUE TITLE
怎么切换英文显示

### ISSUE THREAD

**Issue by JackMa1046** [jeecgboot/JimuReport#2511]
##### 问题描述：
怎么把这些展示成英文

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/63281884/dd2ac67f-8ef7-4c67-b4ee-58e386f639c8)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
暂不支持界面国际化。
归集：#138
