### ISSUE TITLE
浮点类型0.00000000000怎么才能导出为0

### ISSUE THREAD

**Issue by JackMa1046** [jeecgboot/JimuReport#2513]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/63281884/7e9378e4-4a53-4578-ab1d-888e8efe81fc)
![image](https://github.com/jeecgboot/JimuReport/assets/63281884/ba58d6e2-b0fe-4903-8c60-22ab5c201e31)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
设置小数位数

**Comment by JackMa1046** [comment]
不能解决问题，因为这一列不止0.0000000000，还存在有值的情况，比如34224.14838451200这种，如何才能展示成0和34224.148384512

**Comment by zhangdaiscott** [comment]
目前不支持，你可以通过数据层面处理
