### ISSUE TITLE
段落文本格式编辑

### ISSUE THREAD

**Issue by zhangkaichuang** [jeecgboot/JimuReport#2514]
在我提交的这个issue中([https://github.com/jeecgboot/JimuReport/issues/2505](#2505))回复的可以配置成对应的格式
问题：我上面的图片是在word中编辑的，咱们的报表工具有类似与这样的编辑方式吗，您说的配置成对应的格式怎么配置呢，是在excel格式的编辑器中把文本整成我需要格式吗

**Comment by zhangdaiscott** [comment]
你在说什么？

**Comment by zhangkaichuang** [comment]
我之前发布了一个issue，你们进行了解答之后就把这个给关掉了，我还有一些疑问无法继续在原来的issue中提问，就附上了我那个issue的连接，您点进去看一下就知道了

**Comment by zhangdaiscott** [comment]
不支持word
