### ISSUE TITLE
关于积木报表给出的数据库报表不能超过500个的提示

### ISSUE THREAD

**Issue by sdqdsongjq** [jeecgboot/JimuReport#2515]
##### 版本号：
1.7

##### 问题描述：

创建报表时提示：创建失败，免费版最多支持500个数据库链接
##### 错误日志&截图：
但是其实刚开始连上库，数据库表里面可能也没超过500个表，不知道怎么计算的，
另外收费版怎么个收费法

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
http://jimureport.com/vip

**Comment by a123456wlzhyy** [comment]
遇到同样问题，还没开始用呢，不可能有500个，点新增就提示。这个回答是什么意思？到底500个以下能不能免费用？
