### ISSUE TITLE
如何设置单元格格式而非数据格式

### ISSUE THREAD

**Issue by JackMa1046** [jeecgboot/JimuReport#2516]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
ws

**Comment by JackMa1046** [comment]
ws是啥意思？

**Comment by 1298191366** [comment]
经测试百分比导出无问题，除非你设置了小数位数，目前除了处置类型的导出是数值类型，其余全是文本，不支持数值类型
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/095d3de5-41de-4a9a-b2d1-32f604423a87)

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
