### ISSUE TITLE
预览的数据和导出的数据不一样

### ISSUE THREAD

**Issue by JackMa1046** [jeecgboot/JimuReport#2517]
##### 问题描述：
预览的数据为123,456,789.12   导出下载到本地就变成了123456789.12   没有逗号了

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by JackMa1046** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/63281884/c57458a6-ec73-4caa-b4fe-f041546b9973)
![image](https://github.com/jeecgboot/JimuReport/assets/63281884/53b4f7f4-43af-43de-aefe-fb4a2cc55bf3)
![image](https://github.com/jeecgboot/JimuReport/assets/63281884/da6b2d34-fdcb-4779-9bcb-b29f2a28413b)

**Comment by jeecgos** [comment]
暂不支持，重复问题 #2267
