### ISSUE TITLE
可不可以直接支持数据嵌套 ,对象里面套list

### ISSUE THREAD

**Issue by li-yongheng** [jeecgboot/JimuReport#2518]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by li-yongheng** [comment]
如  这种样式
![Snipaste_2024-04-01_13-52-34](https://github.com/jeecgboot/JimuReport/assets/76946463/337bf0b2-c040-4d86-b0c0-28c2574e65ac)
  可不可以一个接口实现

**Comment by jeecgos** [comment]
暂不支持，归集：#138
