### ISSUE TITLE
导出的百分比不能进行汇总计算

### ISSUE THREAD

**Issue by JackMa1046** [jeecgboot/JimuReport#2524]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/63281884/ca883c32-f5f1-4795-9db8-2d418479f513)
![image](https://github.com/jeecgboot/JimuReport/assets/63281884/f154a8b3-566e-499b-a716-ec7b2a36524b)
![image](https://github.com/jeecgboot/JimuReport/assets/63281884/fc8f7036-c70e-4c82-9f2c-98ab46a9dd0c)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
重复问题：#2516
