### ISSUE TITLE
积木报表问题反馈

### ISSUE THREAD

**Issue by 122kj** [jeecgboot/JimuReport#2526]
#####   #[#错误日志&截图：
![屏幕截图 2024-04-02 144546](https://github.com/jeecgboot/JimuReport/assets/136661559/7721120d-6ec8-419b-8e67-51d6a3e1d3f7)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 122kj** [comment]
请问这个问题有办法解决吗

**Comment by jeecgos** [comment]
暂不支持，归集：#138
