### ISSUE TITLE
jeecg-boot 3.4.4 升级jimu 1.7.4 版本 在登录时登录时报错（Handler dispatch failed； nested exception is java.lang.NoSuchMethodErro）

### ISSUE THREAD

**Issue by chifeixiaoye** [jeecgboot/JimuReport#2530]
##### 版本号：
1.7.4

##### 问题描述：

jeecg-boot 3.4.4 升级jimu 1.7.4 版本 在登录时登录时报错（Handler dispatch failed； nested exception is java.lang.NoSuchMethodErro）
1.7.4 以下版本 无此问题
##### 错误日志&截图：
![1712349605641](https://github.com/jeecgboot/JimuReport/assets/102878811/ed10cb07-dde7-41d7-8b10-9817c6378cba)
![1712349699186](https://github.com/jeecgboot/JimuReport/assets/102878811/7f8e8433-de8f-489d-a4f6-563633a3275b)
![1712349805557](https://github.com/jeecgboot/JimuReport/assets/102878811/59f078d8-230f-43de-bcca-cb5230d972c5)

##### 重现步骤：
1.jeecg-boot 3.4.4 根目录下 pom.xml 更改 积木报表版本号
![1712349980563](https://github.com/jeecgboot/JimuReport/assets/102878811/78093483-79ed-4401-bc86-94e103a5fbca)
2.打开网页登录管理员账号，一直转圈登录不上，查看控制台发现报错

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
排除积木报表依赖中jsqlparse高版本
