### ISSUE TITLE
能否实现点击图表然后弹出明细报表的功能

### ISSUE THREAD

**Issue by n13151125** [jeecgboot/JimuReport#2532]
##### 问题描述：
能否实现点击图表然后弹出明细报表的功能，如某报表是用柱形图展示，通过点击柱形图弹出明细数据

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
参考下：https://help.jeecg.com/jimureport/summary/linkageConfig.html

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
