### ISSUE TITLE
JimuReport1.7.4支持spring boot1.5.6吗

### ISSUE THREAD

**Issue by StarskyBoy** [jeecgboot/JimuReport#2533]
##### 问题描述：
JimuReport1.7.4支持spring boot1.5.6吗

##### 错误日志&截图：
ERROR:Application startup failed
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
不支持，至少需要springboot 2.X
