### ISSUE TITLE
如何配置查询条件必填

### ISSUE THREAD

**Issue by WooZhangYan** [jeecgboot/JimuReport#2535]
##### 版本号：
1.6.6

##### 问题描述：
请问该如何配置查询条件必填？这边有需求查询条件需必填才能查询出数据，希望能在查询条件为空时提示用户必填

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/104556081/e0627120-b357-4415-b025-b066879acaeb)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
查询必填没有，但是可以配置点击查询再出数据，也可以设置查询条件默认值
https://help.jeecg.com/jimureport/query/jsEnhance.html#41-%E6%BC%94%E7%A4%BA%E6%95%88%E6%9E%9C

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
