### ISSUE TITLE
日期范围框 默认值 天少个0

### ISSUE THREAD

**Issue by wYoona** [jeecgboot/JimuReport#2536]
##### 版本号：
1.6.6
##### 问题描述：
日期范围框 默认值 
=concat(dateStr('yyyy-MM',-1),'-',dateStr('dd'))|=dateStr('yyyy-MM-dd')
天 少个0

##### 错误日志&截图：
![5146260b7243cf6b23849738e129267e](https://github.com/jeecgboot/JimuReport/assets/52777352/b07e1fbd-00b2-4bbe-af78-f59fb49c4968)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
陈锐

**Comment by jeecgos** [comment]
cr

**Comment by jeecgos** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/162332873/b25991dc-e2e7-4ddd-a680-94b04f293748)
未复现，请提供详细复现步骤或在官网创建示例。

**Comment by wYoona** [comment]
将本机时间设置为每月的1号至9号，直接点击查询。

**Comment by hoperunChen** [comment]
已修复，请等待新版本发布。
原来的=dateStr('dd')会去零，新版本中使用=dateStr2('dd')来获取日期值，该函数不去零。
