### ISSUE TITLE
关于老版本bug，新版本功能阉割问题

### ISSUE THREAD

**Issue by 13813586515** [jeecgboot/JimuReport#2540]
##### 版本号：
1.6.6

##### 问题描述：
1.6.6往后的版本就是1.7+，变革版本，有些内容就需要收费了，如果不升级新版本，1.6.6中存在的bug就无法修复，免费版本的官网说还会继续维护，请问如何fix那些开源版本下的bug？我看新版本已经fix这个bug了，https://github.com/jeecgboot/JimuReport/issues/2255

##### 错误日志&截图：
![7e9d9e36e2c9e7ab18911bc2a35b2f4](https://github.com/jeecgboot/JimuReport/assets/21357134/656306dc-1d1f-4117-b7e4-ee4916602b49)

##### 重现步骤：
设计报表时 查询选择下拉多选

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
老版本只修复严重安全漏洞问题
