### ISSUE TITLE
配置的报表偶尔会出现报错情况, 具体见描述

### ISSUE THREAD

**Issue by qiaojing1** [jeecgboot/JimuReport#2541]
##### 版本号：
1.7.2

##### 问题描述：
配置下图这样一个报表, 偶尔会出现数组报错, 非常偶然, 刷新几十次会出现一次, 大部分情况刷新都是不报错的
![image](https://github.com/jeecgboot/JimuReport/assets/66162802/85bd9dc7-9da4-4725-9622-410f20f5728f)

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/66162802/32970f29-34a2-4061-8989-60b9e427e3e5)

##### 重现步骤：
可能要刷新很多次才会复现, 不是很确定是不是配置的不对导致的

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
目前未能复现问题，暂时关闭issue；如果发现必现的方法，麻烦再提issue吧。
