### ISSUE TITLE
怎样下载文件，好引入到vue项目里

### ISSUE THREAD

**Issue by tongnian1** [jeecgboot/JimuReport#2544]
##### 问题描述：

怎样下载文件，好引入到vue项目里
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
java项目集成

**Comment by tongnian1** [comment]
> java项目集成

有链接参考吗

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/jimureport/quick.html

**Comment by tongnian1** [comment]
> https://help.jeecg.com/jimureport/quick.html

想用积木报表是不是得有接口才能用呀
