### ISSUE TITLE
一个报表里面有多个子报表时，导出的子表排序与页面展示的不一致

### ISSUE THREAD

**Issue by superman4808** [jeecgboot/JimuReport#2546]
##### 版本号：
V1.6.6

##### 问题描述：
一个报表里面有多个子报表时，导出的子表排序与页面展示的不一致

##### 错误日志&截图：
![页面排序](https://github.com/jeecgboot/JimuReport/assets/121927607/99a2466d-b8fc-49ba-b87b-f5fb6f883366)
![导出子表排序](https://github.com/jeecgboot/JimuReport/assets/121927607/0e8074f6-e62c-4683-ad1a-dbe6ee9034a2)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你这全水印了，让我们看个寂寞吗

**Comment by superman4808** [comment]
数据库存的排序：
![页面排序](https://github.com/jeecgboot/JimuReport/assets/121927607/37e59be3-71bb-4c6b-bb07-b504d8ab6885)
![导出](https://github.com/jeecgboot/JimuReport/assets/121927607/397c6940-407e-4f77-b426-86a4f1b732b3)
导出之后的排序：
![导出子表排序](https://github.com/jeecgboot/JimuReport/assets/121927607/b6ca178c-5065-4c40-be90-d40facea29a5)
