### ISSUE TITLE
积木报表集成到自己项目，点击创建报表，前后端报解析出错

### ISSUE THREAD

**Issue by suebu** [jeecgboot/JimuReport#2547]
##### 版本号：
1.7.4

##### 问题描述：
积木报表集成到自己项目，点击创建报表，前后端报解析出错
com.alibaba.fastjson.JSONException: write javaBean error, fastjson version 1.2.40, class org.springframework.beans.factory.support.DefaultListableBeanFactory, fieldName : $$beanFactory, write javaBean error, fastjson version 1.2.40, class com.alibaba.druid.pool.DruidDataSource, fieldName : dataSource

##### 错误日志&截图：
![90b5ef6b44958743c93de87fdb98508](https://github.com/jeecgboot/JimuReport/assets/49521021/ca83e50d-cb9a-4dbe-adb1-14c85f5feebf)
![8714f0b4b65c1ee6511169c653bb896](https://github.com/jeecgboot/JimuReport/assets/49521021/98b8cffa-c4b8-4581-9040-e4b886003043)

##### 重现步骤：
1.按SQL导入数据表结构，使用的MySQL5.7.43版本，按照文档导入maven管理，配置文件也是文档上的照搬
2.启动项目，正常，进入页面也正常，点击创建报表，提示解析序列化问题，提示如图片
2.点击查看报表模板详情，提示解析序列化问题，提示如图片

**Comment by zhangdaiscott** [comment]
看看是不是依赖冲突

**Comment by jeecgos** [comment]
请将 fastjson 升级到1.2.83

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
