### ISSUE TITLE
关于报表小计的问题

### ISSUE THREAD

**Issue by bluesky2007** [jeecgboot/JimuReport#2551]
##### 版本号：

1.5.6
##### 问题描述：

如何通过分组小计，按不同列的小计计算出百分比，如下图所示
##### 错误日志&截图：
![jimuquestion](https://github.com/jeecgboot/JimuReport/assets/46044625/d4eba5e9-4e09-4b09-923d-7396a0d77399)
[](url)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/162332873/e79958fb-770b-450b-93e8-269b7a7c3938)
![image](https://github.com/jeecgboot/JimuReport/assets/162332873/c2f34ffc-ef50-4e77-a856-edbd32943855)

**Comment by jeecgos** [comment]
cr

**Comment by hoperunChen** [comment]
已修复，待新版发布。 
可以使用如下方式：
![image](https://github.com/jeecgboot/JimuReport/assets/13013558/beb8487b-b262-4d78-abe5-88b9b757284a)
![image](https://github.com/jeecgboot/JimuReport/assets/13013558/eea60603-124d-438c-bef5-f20ae84f30e7)

参考文档：https://help.jeecg.com/jimureport/function/dynamiCell.html

**Comment by bluesky2007** [comment]
你好，是不是要升级版本？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月24日(星期三) 晚上8:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/JimuReport] 关于报表小计的问题 (Issue #2551)














 
已修复，待新版发布。
 可以使用如下方式：
 image.png (view on web)
 image.png (view on web)
 
参考文档：https://help.jeecg.com/jimureport/function/dynamiCell.html

**Comment by hoperunChen** [comment]
> 你好，是不是要升级版本？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年4月24日(星期三) 晚上8:23 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [jeecgboot/JimuReport] 关于报表小计的问题 (Issue #2551) 已修复，待新版发布。 可以使用如下方式： image.png (view on web) image.png (view on web) 参考文档：https://help.jeecg.com/jimureport/function/dynamiCell.html — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

要升级版本，可以关注下官网的升级日志。http://www.jimureport.com/doc/log
