### ISSUE TITLE
给分组小计设置背景色之后导致下面的合计值计算重复了

### ISSUE THREAD

**Issue by zmSlow** [jeecgboot/JimuReport#2552]
##### 问题描述：
给分组小计设置背景色之后导致下面的合计值计算重复了

##### 错误日志&截图：
![QQ截图20240415160639](https://github.com/jeecgboot/JimuReport/assets/30498623/8d5e375f-5967-44a0-99a6-937e6c70ef44)

##### 重现步骤：
1.设置完分组合计后，给分组依据字段后面的字段设置=(let name='#{HK.dept_name}';if(name==''){rowcolor('合计','','yellow')} else{'#{HK.dept_name}'})

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 1298191366** [comment]
升级到最新版本测试无问题，你可以升级测试一下看看还有没有问题，如有问题请再次回复
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/96d0c41b-400a-4c23-b036-635010ade088)

```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.7.4</version>
</dependency>
```

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
