### ISSUE TITLE
动态行动态列  用max min  第一行好用 第二行就不好用了

### ISSUE THREAD

**Issue by sjqit** [jeecgboot/JimuReport#2553]
##### 错误日志&截图：
![1713177796158](https://github.com/jeecgboot/JimuReport/assets/167081020/d76381bc-c630-46b5-b0e9-6c35ededba8e)
![image](https://github.com/jeecgboot/JimuReport/assets/167081020/a01d96bc-4dc5-4408-83c4-56b92cdc44f6)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
cr

**Comment by sjqit** [comment]
> cr

有结果了吗？
