### ISSUE TITLE
ROUND函数不支持表达式

### ISSUE THREAD

**Issue by ahhyong** [jeecgboot/JimuReport#2554]
##### 版本号：
 v1.7.4

##### 问题描述：
计算百分比时，比如单元格C1，设置值为=O18/N10，想通过ROUND函数进行四舍五入（=ROUND(O18/N10,4)），就会报错：

<img width="485" alt="1" src="https://github.com/jeecgboot/JimuReport/assets/9338685/97dc323b-4f32-440c-9fa0-45ec94c6527f">

但是，如果是C2=O18/N10，C1=ROUND(C2, 4)就是正常的。  

是使用有错误？还是ROUND函数不支持嵌套嘛？  如果是不支持，后续版本会增加这个功能嘛（这个功能在报表中是很常见的）？

**Comment by jeecgos** [comment]
ROUND函数是支持表达式嵌套的，但是表达式参数并不支持单元格计算语法。
