### ISSUE TITLE
【总计】位置放在各城市的下面，而不是占了aqi字段的位置

### ISSUE THREAD

**Issue by tongnian1** [jeecgboot/JimuReport#2555]
##### 问题描述：
【总计】位置放在各城市的下面，而不是占了aqi字段的位置
![da8a3fcfd04035e386694b3e83f554f](https://github.com/jeecgboot/JimuReport/assets/37102096/1b40e001-d887-4230-9467-9d4c8e89190b)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
补充版本号

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
