### ISSUE TITLE
省市区查询框三级联动加载数据失败问题

### ISSUE THREAD

**Issue by yixuexing** [jeecgboot/JimuReport#2556]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
ws

**Comment by 1298191366** [comment]
`/jeecg-boot/ces/ai/customSelect`这个是我们本地测试的接口，你肯定获取不到。需要你自己写，按照文档返回指定格式即可

![image](https://github.com/jeecgboot/JimuReport/assets/30997828/a80751f1-67c3-45fc-a86f-99c08d837d39)

文档地址：https://help.jeecg.com/jimureport/query/jsEnhance.html#1%E5%AE%9E%E7%8E%B0%E4%B8%89%E7%BA%A7%E8%81%94%E5%8A%A8

参考代码：
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/39293dfc-db06-405d-9847-084a28ebdfe9)
