### ISSUE TITLE
本地可以启动正常访问，放服务器上新建报表报错。java.lang.NoClassDefFoundError: Could not initialize class org.jeecgframework.minidao.util.SnowflakeIdWorker

### ISSUE THREAD

**Issue by yiyuzhou** [jeecgboot/JimuReport#2558]
##### 错误日志&截图：
![Q9TBKCMU8TO N VTAITWLLG](https://github.com/jeecgboot/JimuReport/assets/33140584/d325bfef-6a9b-40a2-b4a1-ad89a8002210)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
是不是minidao依赖冲突

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
