### ISSUE TITLE
升级到1.7.x后页面打开报错，看打印sql多了一个order by

### ISSUE THREAD

**Issue by suyang1023** [jeecgboot/JimuReport#2561]
##### 版本号：
1.7.4

##### 问题描述：
数据源sql中带order by时，从1.6.6升级到1.7.x版本后会报错，在原先的sql基础上好像又加了一个order by

##### 错误日志&截图：
我的数据源是这么配置的
![image](https://github.com/jeecgboot/JimuReport/assets/11532782/8fc82f89-f502-4ddb-956d-054a7e7e7959)
系统打印的sql可以看到多了一个order by
<img width="1192" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/11532782/905031cf-89cf-4ef1-97a0-48bb7c314ec4">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by suyang1023** [comment]
我的数据源是order by 两个字段，感觉系统又对查到的第一个字段进行order by

**Comment by zhangdaiscott** [comment]
看看报表配置是不是做了排序配置

**Comment by jeecgos** [comment]
cr

**Comment by hoperunChen** [comment]
已修复，待新版本发布。
