### ISSUE TITLE
在线版本没有列表横向扩展

### ISSUE THREAD

**Issue by LLLLJJJJMMMM** [jeecgboot/JimuReport#2563]
版本号：
在线版本

 问题描述：
在线版本没有列表横向扩展
集成的版本有横向扩展，在线版本是否可以有列表横向扩展

 错误日志&截图：
在线版本
<img width="1044" alt="b2372d19cbd98d749d4fa467dc044c6" src="https://github.com/jeecgboot/JimuReport/assets/101620126/7a58b445-f987-4104-bd0b-4d6fb20b4ce0">
集成版本
<img width="1044" alt="decc316e90f69672f59ae7c99a00a08" src="https://github.com/jeecgboot/JimuReport/assets/101620126/bb5d2dee-dc90-40b1-9fa9-79540404071f">

重现步骤：

友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
最新版的分组设置中，只有「数据设置」选择了分组时才会展示「横向扩展」字段。
