### ISSUE TITLE
横向内容过多时，导出pdf和打印不全

### ISSUE THREAD

**Issue by WooZhangYan** [jeecgboot/JimuReport#2564]
##### 版本号：
1.6.6

##### 问题描述：
横向内容过多时，导出pdf和打印不全，只能导出/打印页面固定范围

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/104556081/8b3aa1de-d903-401f-9316-b69fe1fbf780)
![image](https://github.com/jeecgboot/JimuReport/assets/104556081/dbe5b36b-106e-4db4-87f4-4bbf6b99a40a)
![image](https://github.com/jeecgboot/JimuReport/assets/104556081/b759c88d-9dcf-4031-aa92-8d01617c7411)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
横向内容过多时，pdf的导出和打印确实会截断内容，请尝试导出pdf图像和缩放打印。

**Comment by WooZhangYan** [comment]
能否通过配置将导出pdf选项隐藏
![Uploading image.png…]()

**Comment by jeecgos** [comment]
「能否通过配置将导出pdf选项隐藏」
暂不支持隐藏导出pdf选项。

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
