### ISSUE TITLE
分页发票打印 页面预览数据与打印数据不一致

### ISSUE THREAD

**Issue by casper199807** [jeecgboot/JimuReport#2565]
##### 版本号：
1.6.0

##### 问题描述：
在进行发票分页打印时无法根据预览数据进行连打

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/58022349/4ce4b546-42f4-4a4a-9966-cee00936b39d)
![image](https://github.com/jeecgboot/JimuReport/assets/58022349/ab8698c9-4d24-4b1c-a98a-c0d5e3e51578)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
