### ISSUE TITLE
如何配置表头固定

### ISSUE THREAD

**Issue by WooZhangYan** [jeecgboot/JimuReport#2566]
##### 版本号：
V1.6.6

##### 问题描述：
页面数据过多时，向下拖动滚动条，表头不固定对查看数据不友好，如何配置表头固定

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/104556081/ca4480d6-1560-4c41-bb17-674ac25dfda5)
![image](https://github.com/jeecgboot/JimuReport/assets/104556081/28b80295-f9d5-4876-9e50-29d3dd966000)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
最新商业版支持，冻结
