### ISSUE TITLE
超链接报表钻取参数传递不是期望值

### ISSUE THREAD

**Issue by littlefourfour** [jeecgboot/JimuReport#2568]
##### 问题描述：
使用报表钻取功能时，如果列展示使用了横向分组即动态列，向子报表传递列名参数时，列表最后一行数据传递参数异常

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/44185223/b04253a1-9510-47bf-a79b-cb5a25885b49)
![image](https://github.com/jeecgboot/JimuReport/assets/44185223/a3c0436b-eac5-4205-8692-4e3e1f28fccc)

##### 重现步骤：
列展示使用横向分组：
![image](https://github.com/jeecgboot/JimuReport/assets/44185223/02a3535d-cd2e-4e66-a7af-951632e1ff79)
列表纵向分组配置：
![image](https://github.com/jeecgboot/JimuReport/assets/44185223/969fe856-c46d-429d-b8d8-fd0c7b4c3026)
报表钻取参数传递配置：
![image](https://github.com/jeecgboot/JimuReport/assets/44185223/b1f72963-da1d-4026-9410-dc17e1f75c12)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by littlefourfour** [comment]
紧急问题反馈

**Comment by littlefourfour** [comment]
不止是最后一行，存在横向分组的情况下，点击超链接，数据传递的不是期望值

**Comment by artFollower** [comment]
遇到类型问题，解决了吗

**Comment by zhangdaiscott** [comment]
ws

**Comment by littlefourfour** [comment]
> 遇到类型问题，解决了吗

没有解决 我尝试升级了版本，但是问题还是存在。只要是使用了横向分组，传递值就会有问题

**Comment by artFollower** [comment]
> ws
大佬大佬，啥时候帮忙看看这个问题啊

**Comment by 1298191366** [comment]
已修复，带新版本发布

**Comment by RamonZhao** [comment]
有大佬解决这个问题了吗？1.9.1 还是存在这个情况
