### ISSUE TITLE
同时设置了报表参数查询和报表字段中的查询，报表字段的下拉多选未生效

### ISSUE THREAD

**Issue by zmSlow** [jeecgboot/JimuReport#2569]
##### 版本号：
1.6.6

##### 问题描述：
同时设置了报表参数查询和报表字段中的查询，报表字段的下拉多选未生效

##### 错误日志&截图：
![QQ截图20240422115337](https://github.com/jeecgboot/JimuReport/assets/30498623/43430840-b524-4a06-9a56-716f8d34e4f5)
![QQ截图111](https://github.com/jeecgboot/JimuReport/assets/30498623/e9cbcb97-5093-42f3-9a19-075afe8713b5)

##### 重现步骤：
SELECT
		dp.pro_no,
		dp.sname,
		faa.sum_allotment_money,
		dp.apply_format,
		dp.project_type,
		dp.bus_manager,
		dd1.sname as exe_dept,
		dd2.sname as dept_name,
		dp.exe_manager,
		dp.self_unit,
		DATE_FORMAT( dp.allocate_time, '%Y-%m-%d' ) AS allocate_time,
		kh.sname AS kh_sname,
		cn.sname AS cn_sname,
		mk.sname AS mk_sname 
	FROM  
	(select project_id,exe_dept_id,bus_dept_id,sum(allotment_money) as sum_allotment_money ,create_date from fact_accountentry_allocation   
		where is_flag='1'  and allocation_type='10162014' 
		<#if isNotEmpty(select_startTime)> 
	   AND DATE_FORMAT( create_date, '%Y-%m-%d' ) >= '${select_startTime}' 
	  </#if>
		<#if isNotEmpty(select_endTime)> 
	   AND DATE_FORMAT( create_date, '%Y-%m-%d' ) <= '${select_endTime}' 
	  </#if>
	   GROUP BY  project_id,exe_dept_id,bus_dept_id ) faa
		
	LEFT JOIN  dimzip_project dp on   faa.project_id=dp.aid and dp.is_current='1'
	LEFT JOIN dimzip_dept dd1 on dd1.aid=faa.exe_dept_id and dd1.start_time <= faa.create_date and dd1.end_time>= faa.create_date
	LEFT JOIN dimzip_dept dd2 on dd2.aid=faa.bus_dept_id and dd2.start_time <= faa.create_date and dd2.end_time>= faa.create_date
	LEFT JOIN dimzip_tenant kh ON kh.aid = dp.client_id  AND kh.start_time <= dp.allocate_time AND kh.end_time >= dp.allocate_time
	LEFT JOIN dimzip_channel cn ON cn.aid = dp.channel_id  AND cn.start_time <= dp.allocate_time AND cn.end_time >= dp.allocate_time
	LEFT JOIN dimzip_market mk ON mk.aid = dp.market_id  AND mk.start_time <= dp.allocate_time AND mk.end_time >= dp.allocate_time 
ORDER BY dp.allocate_time desc 

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
cr

**Comment by jeecgos** [comment]
已修复，请等待新版本发布。

**Comment by hoperunChen** [comment]
已修复，请等待新版本发布。
