### ISSUE TITLE
数据库字段中带有英文句号时报表预览不显示

### ISSUE THREAD

**Issue by easyfck** [jeecgboot/JimuReport#2570]
##### 版本号：
1.7

##### 问题描述：
数据库字段中带有英文句号 .  数据预览的时候没有问题，拖到表格内，预览提示无数据

##### 错误日志&截图：
![微信截图_20240422222541](https://github.com/jeecgboot/JimuReport/assets/38744966/086dc360-ff06-412b-b91d-e05fda3c7d68)
![微信截图_20240422222557](https://github.com/jeecgboot/JimuReport/assets/38744966/6ebff9ef-6009-49d9-a2c0-bb86bd479909)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
可以使用as
