### ISSUE TITLE
下拉树支持和其他下拉列表联动么？

### ISSUE THREAD

**Issue by sjqit** [jeecgboot/JimuReport#2571]
##### 问题描述：
一.     1.6.6下拉树支持和其他下拉列表联动么？  1.7.4最新版本支持么？
二.      支持下拉树列表设置默认值么 getSelectOptions()方法获取不到下拉树的数据;

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/167081020/187985b2-f935-43ce-8461-6ccf7ffc4884)
部门和测点联动 查询部门下的测点

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
暂不支持，归集：#138
