### ISSUE TITLE
出现多余的格子

### ISSUE THREAD

**Issue by sjqit** [jeecgboot/JimuReport#2572]
##### 问题描述：
出现多余的格子

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/167081020/379e1548-dcae-4858-b85e-1f7b0ecb9de6)
![image](https://github.com/jeecgboot/JimuReport/assets/167081020/cd30e6ec-5138-4020-b103-710f68ca2336)

##### 重现步骤：
数据：
{
	"data": [
		{
			"date": "2023-04-10",
			"dapate": "",
			"name": "水管一",
			"value": "20"
		},
		{
			"date": "2023-04-11",
			"dapate": "",
			"name": "水管一",
			"value": "18"
		},
		{
			"date": "2023-04-12",
			"dapate": "",
			"name": "水管一",
			"value": "24"
		},
		{
			"date": "最大值",
			"dapate": "",
			"name": "水管一",
			"value": "24"
		},
		{
			"date": "最大值时间",
			"dapate": "",
			"name": "水管一",
			"value": "2023-04-12"
		},
		{
			"date": "最小值",
			"dapate": "",
			"name": "水管一",
			"value": "18"
		},
		{
			"date": "最小值时间",
			"dapate": "",
			"name": "水管一",
			"value": "2023-04-11"
		},
		{
			"date": "2023-04-10",
			"dapate": "",
			"name": "水管二",
			"value": "35"
		},
		{
			"date": "2023-04-11",
			"dapate": "",
			"name": "水管二",
			"value": "37"
		},
		{
			"date": "2023-04-12",
			"dapate": "",
			"name": "水管二",
			"value": "31"
		},
		{
			"date": "最大值",
			"dapate": "",
			"name": "水管二",
			"value": "37"
		},
		{
			"date": "最大值时间",
			"dapate": "",
			"name": "水管二",
			"value": "2023-04-11"
		},
		{
			"date": "最小值",
			"dapate": "",
			"name": "水管二",
			"value": "31"
		},
		{
			"date": "最小值时间",
			"dapate": "",
			"name": "水管二",
			"value": "2023-04-12"
		},
		{
			"date": "2023-04-10",
			"dapate": "",
			"name": "水管三",
			"value": "35"
		},
		{
			"date": "2023-04-11",
			"dapate": "",
			"name": "水管三",
			"value": "37"
		},
		{
			"date": "2023-04-12",
			"dapate": "",
			"name": "水管三",
			"value": "31"
		},
		{
			"date": "最大值",
			"dapate": "",
			"name": "水管三",
			"value": "37"
		},
		{
			"date": "最大值时间",
			"dapate": "",
			"name": "水管三",
			"value": "2023-04-11"
		},
		{
			"date": "最小值",
			"dapate": "",
			"name": "水管三",
			"value": "31"
		},
		{
			"date": "最小值时间",
			"dapate": "",
			"name": "水管三",
			"value": "2023-04-12"
		},
		{
			"date": "2023-04-10",
			"dapate": "",
			"name": "库水位",
			"value": "2"
		},
		{
			"date": "2023-04-11",
			"dapate": "",
			"name": "库水位",
			"value": "3"
		},
		{
			"date": "2023-04-12",
			"dapate": "",
			"name": "库水位",
			"value": "5"
		},
		{
			"date": "最大值",
			"dapate": "",
			"name": "库水位",
			"value": "5"
		},
		{
			"date": "最大值时间",
			"dapate": "",
			"name": "库水位",
			"value": "2023-04-12"
		},
		{
			"date": "最小值",
			"dapate": "",
			"name": "库水位",
			"value": "2"
		},
		{
			"date": "最小值时间",
			"dapate": "",
			"name": "库水位",
			"value": "2023-04-10"
		},
		{
			"date": "2023-04-10",
			"dapate": "",
			"name": "降雨量",
			"value": "2"
		},
		{
			"date": "2023-04-11",
			"dapate": "",
			"name": "降雨量",
			"value": "3"
		},
		{
			"date": "2023-04-12",
			"dapate": "",
			"name": "降雨量",
			"value": "5"
		},
		{
			"date": "最大值",
			"dapate": "",
			"name": "降雨量",
			"value": "5"
		},
		{
			"date": "最大值时间",
			"dapate": "",
			"name": "降雨量",
			"value": "2023-04-12"
		},
		{
			"date": "最小值",
			"dapate": "",
			"name": "降雨量",
			"value": "2"
		},
		{
			"date": "最小值时间",
			"dapate": "",
			"name": "降雨量",
			"value": "2023-04-10"
		}
	]
}

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
右键-「导出报表配置」，把导出的json发一下。

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
