### ISSUE TITLE
报表模版未设置自动换行，导出文件却自动换行

### ISSUE THREAD

**Issue by superman4808** [jeecgboot/JimuReport#2573]
##### 版本号：
V1.6.6

##### 问题描述：
报表模版未设置自动换行，导出文件却自动换行

##### 错误日志&截图：
![未自动换行](https://github.com/jeecgboot/JimuReport/assets/121927607/723f339d-2e46-4cbd-8e14-3611cd21cd63)
![预览效果](https://github.com/jeecgboot/JimuReport/assets/121927607/91ad0fd9-ab05-40c6-878a-620215865a9a)
![导出换行](https://github.com/jeecgboot/JimuReport/assets/121927607/177efec4-1a74-4b0a-b4a7-e1530599f42e)
导出录频：
![导出换行录频](https://github.com/jeecgboot/JimuReport/assets/121927607/56fed627-f150-4e63-af38-f2e3c37190ae)

##### 重现步骤：
[配置.zip](https://github.com/jeecgboot/JimuReport/files/15070946/default.zip)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 1298191366** [comment]
已修复，待新版本发布
