### ISSUE TITLE
freemarker语法里，如何使用系统上下文变量进行判断

### ISSUE THREAD

**Issue by drtk712** [jeecgboot/JimuReport#2574]
##### 版本号：
1.7.4

##### 问题描述：

sql的freemarker语法里，如何使用系统上下文变量进行判断

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
详细说明

**Comment by drtk712** [comment]
> 详细说明

SELECT * FROM my_table
WHERE 1=1 
and column = #{sysUserCode} **--- 条件生效，可以查出指定数据**


SELECT * FROM my_table
WHERE 1=1
<#if isNotEmpty(sysUserCode)> 
    and column = #{sysUserCode} **--- 条件不生效**
</#if>

**Comment by zhangdaiscott** [comment]
不支持条件
