### ISSUE TITLE
如何控制查询栏查询条件之间空白行

### ISSUE THREAD

**Issue by yiyuzhou** [jeecgboot/JimuReport#2575]
##### 版本号：
jmreport  v1.6.6

##### 问题描述：
查询栏查询条件之前空白太多，如何控制两行缩短？

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/33140584/946a7b43-0866-446b-b5dd-e5c2a32ee412)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by yiyuzhou** [comment]
> ws 优化效果

啥意思？没听明白 。我在文档搜优化效果没结果啊

**Comment by 1298191366** [comment]
已修复，待新版本发布
