### ISSUE TITLE
自定义纸张报表打印

### ISSUE THREAD

**Issue by qqyueding** [jeecgboot/JimuReport#2576]
##### 问题描述：

打印纸张设置用的是自定义纸张241*140
![b7aff36920a8cc62f121b7f939eedf88](https://github.com/jeecgboot/JimuReport/assets/10055570/5b285011-8ba3-41eb-ac86-4e44d7772ade)
，打印出来的效果和预览的效果不一样。![2](https://github.com/jeecgboot/JimuReport/assets/10055570/c5db31ea-618f-48cd-b184-9fafb431d0a8)打印出来的边距一直都这么宽，怎么调都不生效.

##### 错误日志&截图：

![b7aff36920a8cc62f121b7f939eedf88](https://github.com/jeecgboot/JimuReport/assets/10055570/5b285011-8ba3-41eb-ac86-4e44d7772ade)
![d0d3598a0f76272b5664d151f1a4be69](https://github.com/jeecgboot/JimuReport/assets/10055570/4133612c-5717-4b26-9e92-51e28a05e334)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
有A4尺寸的吗？你试试A4看正常吗？我这打印机没有完全一样的尺寸，试了其他别的尺寸没复现问题。

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
