### ISSUE TITLE
报表钻取加载失败

### ISSUE THREAD

**Issue by xi-xi-jun** [jeecgboot/JimuReport#2577]
##### 版本号：
docker部署 1.7.4 

##### 问题描述：
根据官网报表钻取示例操作，发现钻取子表数据加载失败，猜测可能是字典没有正确解析引起。

##### 错误日志&截图：
如下图所示，这一块性别给后台的数据为字典名称，而不是值。如果手动修改男为1，则正常加载数据。
![image](https://github.com/jeecgboot/JimuReport/assets/113566654/3c6676a5-d08f-4846-b2c2-92ebd9a73c49)

##### 重现步骤：
步骤根据官网文档的7.2报表钻取步骤操作
1. 创建钻取报表
（1）钻取报表的数据集
![image](https://github.com/jeecgboot/JimuReport/assets/113566654/edc3e4c7-ca85-4f07-9c17-d27768bf3b9e)
（2）钻取报表
![image](https://github.com/jeecgboot/JimuReport/assets/113566654/40474b81-f5b4-4eeb-9feb-d4294d793948)

2. 创建跳转的报表
（1）跳转报表数据集
![image](https://github.com/jeecgboot/JimuReport/assets/113566654/dcb21096-5056-4f11-987d-46948fe2c6ee)
（2）跳转报表
![image](https://github.com/jeecgboot/JimuReport/assets/113566654/3bc0b7ae-8192-40ee-b027-3d10f791a7df)
3. 为创建的钻取报表添加链接
![image](https://github.com/jeecgboot/JimuReport/assets/113566654/d55036b6-1340-4234-a8e0-5ec9c840627b)

（1）添加图表钻取
![image](https://github.com/jeecgboot/JimuReport/assets/113566654/f1abe195-decf-4a68-8e86-18426c4bdc8c)
4. 钻取演示
（1）第一级页面
![image](https://github.com/jeecgboot/JimuReport/assets/113566654/f46cac14-ca2c-4331-b482-de7a1d189096)
（2）钻取界面
例如：点击 男 ，进入新界面
![image](https://github.com/jeecgboot/JimuReport/assets/113566654/700e7d4c-07d1-4f43-86b2-9dfc4238f490)
如果将url中的男改为其字典中对应的1，则正常显示
![image](https://github.com/jeecgboot/JimuReport/assets/113566654/681871a7-92af-4bee-b25e-169dbe2cf487)

其他：
我是4月23使用官网docker命令部署的，字典中性别也是使用默认的,如下图所示：
![image](https://github.com/jeecgboot/JimuReport/assets/113566654/25a2412b-0ecb-428a-8158-077ef6a8d89c)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by xi-xi-jun** [comment]
@zhangdaiscott 我感觉要么在跳转前的报表中将参数处理好，要么在跳转后的目标报表中将参数处理好。在跳转后的目标报表中数据集设置中，有参数设置一列，目前这个参数也可以指定字典，但是在钻取过程中这个字典设置不起作用。
![image](https://github.com/jeecgboot/JimuReport/assets/113566654/7ce83ad1-17dc-4851-8fe8-8f899a233fe1)

**Comment by 1298191366** [comment]
已修复，待新版本发布
