### ISSUE TITLE
配置的报表预览时文字边缘模糊

### ISSUE THREAD

**Issue by qiaojing1** [jeecgboot/JimuReport#2578]
##### 版本号：
1.7.2

##### 问题描述：
配置的报表在预览时会感觉文字边缘比较模糊,不够清晰. 我把浏览器放大反而会觉得文字变清晰了,是否是配置的不对

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/66162802/c7d3d3fa-86e6-45b1-8eb5-3aa662d5b461)

##### 重现步骤：
配置一个表格类的报表,点击预览

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题

**Comment by renci-zz** [comment]
我也是这样的，不知道有没有解决办法

**Comment by jeecgos** [comment]
> 我也是这样的，不知道有没有解决办法

可否图文说明下，具体怎么模糊？另外针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by renci-zz** [comment]
这个是默认情况展示的
![image](https://github.com/user-attachments/assets/8ca23b69-f936-49f7-a6aa-16d05eb324d0)

**Comment by renci-zz** [comment]
@jeecgos 问题重现了没？
另外官网的注册功能好像没有办法发送短信

**Comment by jeecgos** [comment]
> @jeecgos 问题重现了没？ 另外官网的注册功能好像没有办法发送短信

复现了，正在看，有结果会告诉你。

官网的短信应该没问题，能正常收到啊。

**Comment by jeecgDeveloper** [comment]
页面100%时预览文字默认，无法重现。
请提供更加详细的信息，如：电脑分辨率，浏览器版本等
