### ISSUE TITLE
伪造 (SSRF) 漏洞

### ISSUE THREAD

**Issue by liuchang8877** [jeecgboot/JimuReport#2579]
##### 版本号：
V 1.7.4

##### 问题描述：
安全漏洞

##### 错误日志&截图：
1.Jeecg-boot/积木报表存在服务器端请求伪造 (SSRF) 漏洞:Jeecg-Boot是JeecgBoot社区的一款基于代码生成器的低代码平台, 2.Jeecg-Boot/积木报表存在服务器端请求伪造 (SSRF) 漏洞,由于传入的参数可控且未进行过滤,造成了SSRF漏洞的产生,攻击者可利用该漏洞探测内网、攻击内网应用(如SQL注入、Struts2、K8S、AWS等)。
影响产品:
Jeecg-boot<=v3.6.3、Jimureport <=v1.7.4

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请发具体那个请求，如何攻击
