### ISSUE TITLE
大屏的“全国地图”中能否支持画线。

### ISSUE THREAD

**Issue by xiongchenxu** [jeecgboot/JimuReport#258]
##### 版本号：
1.3.3-beta

##### 问题描述：
在大屏中的“全国地图”功能中，能否支持画线，就是在展示的地图中，画出一块区域(注意：不是飞线那种)，在线文档中没有看到？

##### 截图&代码：
在线文档的地址：
http://report.jeecg.com/2240482

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
请上传图片效果
