### ISSUE TITLE
还没开始用呢，不可能有500个，点新增就提示免费版最多支持500个报表。 

### ISSUE THREAD

**Issue by a123456wlzhyy** [jeecgboot/JimuReport#2580]
##### 版本号：
1.7.4

##### 问题描述：
还没开始用呢，不可能有500个，点新增就提示免费版最多支持500个报表。 

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by hoperunChen** [comment]
500个限制应该是数据库表，不是报表，确认下您数据库里数据库表有没有超过500.

**Comment by lucifrgzf** [comment]
问一下我1.7.4保存完后，界面上只要新增报表没有我保存的是什么情况

**Comment by a123456wlzhyy** [comment]
数据库里表也没有500个

**Comment by zhangdaiscott** [comment]
数据库表有多少个?
