### ISSUE TITLE
报表导出excel,动态图片不见了

### ISSUE THREAD

**Issue by linjk03** [jeecgboot/JimuReport#2582]
##### 版本号：
1.6.6

##### 问题描述：
![image](https://github.com/jeecgboot/JimuReport/assets/167974290/c9a7f428-af93-4f8f-855b-da91f921d517)
如上图描述，图片不是指定前端静态的URL，而以动态生成的签名图片，效果如下图
![image](https://github.com/jeecgboot/JimuReport/assets/167974290/dcc53dbe-950f-4e50-8213-9f53642c0b61)

##### 错误日志&截图：
无错误日志。
![image](https://github.com/jeecgboot/JimuReport/assets/167974290/6698398e-69a9-408f-afd5-cbd2c47c102c)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
