### ISSUE TITLE
点击确定后报错

### ISSUE THREAD

**Issue by lucifrgzf** [jeecgboot/JimuReport#2583]
##### 版本号：
1.74版本Windows64免安装版本

##### 问题描述：

为什么会报错这个呀，有大佬懂么1.74版本的点击右下角确定的时候报错了
##### 错误日志&截图：
![NWRPF(CVH7ZJHX AMRLBLIJ](https://github.com/jeecgboot/JimuReport/assets/129467754/c7d34342-8b0b-4390-b409-0841839f137f)
![image](https://github.com/jeecgboot/JimuReport/assets/129467754/f0effbf4-037d-44c5-bdff-eea691d2b890)

##### 重现步骤：
左边的mysql表已经都进去了就点击了个确定就报错

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
检查下你的数据库里jimu_report_db_field表有没有字段：jimu_report_db_id
如果有检查下数据库是不是开了区分大小写的配置
