### ISSUE TITLE
我保存后在欢迎进入积木报表工作台看不到保存的报表

### ISSUE THREAD

**Issue by lucifrgzf** [jeecgboot/JimuReport#2584]
##### 版本号：

1.7.4
##### 问题描述：
我保存后在欢迎进入积木报表工作台看不到保存的报表

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/129467754/02c01f38-0edc-4873-a5b3-2c78bfb59964)

##### 重现步骤：
我每次保存了报表但是在首页却都看不到

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lucifrgzf** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/129467754/2ea3373a-c470-4e20-b774-f5fd3d3f0b5f)
看了网页上我Failed to load resource: the server responded with a status of 500 ()

**Comment by jeecgos** [comment]
后台报错日志贴一下。

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/3162115/9263ebc0-ff5f-4673-adc6-a3d22cb9e6e5)
这不提示重名了吗

**Comment by lucifrgzf** [comment]
我找到问题了就是导数据库时候MAP那个表有问题导致后面的表都没导进去，才会前端不显示保存的报表的
