### ISSUE TITLE
多租户方式下钻报表不能自动拼接租户参数

### ISSUE THREAD

**Issue by 1322408199** [jeecgboot/JimuReport#2586]
##### 版本号：
 1.7.4

##### 问题描述：
添加超链下钻报表，下钻报表打不开，下钻报表url缺失租户参数，在地址栏手动增加租户可以正常打开页面。 
2张报表属于同一个租户下定义的。

##### 错误日志&截图：

提示错误如下：
{"success":false,"message":"开启了Saas模式：用户只能看自己租户下的数据！","code":500,"result":null,"timestamp":1714029616028}

##### 重现步骤：
1.设置下钻报表
1.设置汇总报表，超链接配置->报表下钻（链接报表选下钻报表）

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
ws

**Comment by 1298191366** [comment]
经测试无问题，请确认在列表页或者是否存在租户id，没有需要你手动拼接上，钻取之前是否存在租户id
列表
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/5131dedb-9472-4839-ade7-29fe7a787f4b)
钻取
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/2e605bf0-842d-493c-8d70-cb680f83ddf7)
钻取之后
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/334a4a14-c66a-432e-b552-f5eafc472d3d)

**Comment by 1322408199** [comment]
手动加上租户id可以正常下钻。
