### ISSUE TITLE
jimuReport集成到项目中，操作员传递不到报表中

### ISSUE THREAD

**Issue by 1322408199** [jeecgboot/JimuReport#2587]
##### 版本号：
v1.7.4

##### 问题描述：
jimuReport模块集成到项目中，登录系统，设计积木报表表格及数据集参数都能正确预览，
但是，报表页脚增加操作员，系统参数配置 #{sysuserCode} , 报表无法输出系统操作员。

##### 错误日志&截图：
报表页脚区域增加   操作员： #{sysuserCode}

##### 重现步骤：
1.设计报表
2 页脚增加 操作员:#{sysuserCode}

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
系统变量 不支持在报表设计器使用。只支持作为数据集的参数来用。
