### ISSUE TITLE
报表钻取，设计点击数字跳转对应报表，但是参数不符

### ISSUE THREAD

**Issue by artFollower** [jeecgboot/JimuReport#2588]
##### 问题描述：
配置了一个年度报表，点击数量，可以查询对应年，对应合同的报表，使用了钻取报表，但是配置了参数，点击后参数值不对

##### 错误日志&截图：
<img width="1358" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/26338398/dad1334b-e102-46a5-aeaf-956145c4fb71">
<img width="851" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/26338398/821025f2-5002-4a04-ba84-6c0b1219e5d3">

##### 重现步骤：

<img width="396" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/26338398/6a7dda3c-43a3-44e5-b3e5-ef15f1a1f9b8">
<img width="1213" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/26338398/ce89de56-f6f7-422e-aa84-308ad579f12d">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by xi-xi-jun** [comment]
哈哈，你的参数位置在D，看你配置的是C

**Comment by artFollower** [comment]
> 哈哈，你的参数位置在D，看你配置的是C

一看你就是没看文档，我要获取C这个位置的参数，肯定得配置C啊

**Comment by 1298191366** [comment]
已修复，带新版本发布
