### ISSUE TITLE
打印预览多两页空白页

### ISSUE THREAD

**Issue by ckingggg** [jeecgboot/JimuReport#2591]
##### 问题描述：
打印预览多两页空白页

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/39080481/92849ad2-6184-4422-aded-8fd406eca892)

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
