### ISSUE TITLE
下拉树 查询接口怎么动态传参

### ISSUE THREAD

**Issue by sjqit** [jeecgboot/JimuReport#2592]
##### 问题描述：
把报表用iframe嵌套到自己的画面，查询条件中的下拉树配置的查询接口参数怎么用自己画面的值当作参数传递给后端

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/167081020/4946e7d2-9ba7-4222-828f-3af4b08b9693)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
这个肯定实现不了

**Comment by BO-DI** [comment]
> 这个肯定实现不了

但是很多时候需要用到，比如，我把外链地址的url参数换成动态参数，填到配置。
这是我业务系统的外链：
![image](https://github.com/user-attachments/assets/aec7fea7-5fa4-4800-9b7f-507eb2a197fb)
下面这个是jeecgboot官网示例的外链：
![image](https://github.com/user-attachments/assets/c24e7ae8-5dc4-40b1-aa4a-34a18205bf00)

**Comment by BO-DI** [comment]
@sjqit  请问博主，针对这种情况，在后来的版本中您有找到突破口吗？

**Comment by sjqit** [comment]
> @sjqit 请问博主，针对这种情况，在后来的版本中您有找到突破口吗？
还是这个版本 拦截请求，在请求后面拼上自己的参数

**Comment by BO-DI** [comment]
> > @sjqit 请问博主，针对这种情况，在后来的版本中您有找到突破口吗？
> > 还是这个版本 拦截请求，在请求后面拼上自己的参数

请问，您指的是在报表项目中的拦截请求，还是把报表集成到业务系统中的拦截请求呢？

**Comment by BO-DI** [comment]
> > @sjqit 请问博主，针对这种情况，在后来的版本中您有找到突破口吗？
> > 还是这个版本 拦截请求，在请求后面拼上自己的参数

我在报表项目中去拦截业务系统的api请求，咋拦截不到，只能拦截报表项目中的请求，跨域配置也做了？
业务系统接口截图：
![image](https://github.com/user-attachments/assets/1573726c-a1ba-4d1c-acf6-f0941b6c0934)
报表项目接口截图：
![image](https://github.com/user-attachments/assets/3ae4a8cc-9fdf-4415-a0ad-339862353b8d)

**Comment by sjqit** [comment]
> > > @sjqit 请问博主，针对这种情况，在后来的版本中您有找到突破口吗？
> > > 还是这个版本 拦截请求，在请求后面拼上自己的参数
> 
> 我在报表项目中去拦截业务系统的api请求，咋拦截不到，只能拦截报表项目中的请求，跨域配置也做了？ 业务系统接口截图： ![image](https://private-user-images.githubusercontent.com/53505854/394996688-1573726c-a1ba-4d1c-acf6-f0941b6c0934.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NzUzNTksIm5iZiI6MTczMzk3NTA1OSwicGF0aCI6Ii81MzUwNTg1NC8zOTQ5OTY2ODgtMTU3MzcyNmMtYTFiYS00ZDFjLWFjZjYtZjA5NDFiNmMwOTM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDAzNDQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NDk5ZjgwOGM2YTcyYmQ0ODdjMzY1YTkxYzlkYWFiMTA1ZWE2ZmNkODE4MWM0ZmY2MzNhOTliMmQ3Y2ZlYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I5ay5VWdg8gwd-pJxTEfC6nEhQYYsf4gSe-IYhaosjE) 报表项目接口截图： ![image](https://private-user-images.githubusercontent.com/53505854/394996826-3ae4a8cc-9fdf-4415-a0ad-339862353b8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NzUzNTksIm5iZiI6MTczMzk3NTA1OSwicGF0aCI6Ii81MzUwNTg1NC8zOTQ5OTY4MjYtM2FlNGE4Y2MtOWZkZi00NDE1LWEwYWQtMzM5ODYyMzUzYjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDAzNDQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0NDhhZDRjN2EwNTI4MGM2YjYyZjE3MDUyNWIwODVhZjk4N2QyMzg4Zjg5NmNhNmUxOTQ5YmQzY2M5MmViMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.etkeovh0ntnUtcK2q67aqmidF-bUIi6-eJRRJGSRY4I) ![image](https://private-user-images.githubusercontent.com/53505854/394997904-1f76a480-85d1-4a72-ae67-9c3782aac921.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NzUzNTksIm5iZiI6MTczMzk3NTA1OSwicGF0aCI6Ii81MzUwNTg1NC8zOTQ5OTc5MDQtMWY3NmE0ODAtODVkMS00YTcyLWFlNjctOWMzNzgyYWFjOTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDAzNDQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNzZiZDk4Nzg2OGFkMjU5MzliNDVlNmMwNTJhMDQ2ZTM3OGMyNjAxODk4YmY5NzkyNWJjODk5MWI3NDk4OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-3AXd3uB0Si7LvkmGwc0-c15lYdIp0y0VPAF1RoxXig)

你加我q说吧  315482510
