### ISSUE TITLE
打印错误

### ISSUE THREAD

**Issue by cofx2ex2** [jeecgboot/JimuReport#2593]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/86476574/9a199ea5-de95-4239-add3-7fbd2d910629)

##### 重现步骤：
请求打印就有出现

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
怎么重现？

**Comment by zhangdaiscott** [comment]
cr

**Comment by cofx2ex2** [comment]
CIIFB
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月26日(星期五) 中午12:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 打印错误 (Issue #2593)





 
怎么重现？

**Comment by zhangdaiscott** [comment]
提供重现环境和代码

**Comment by 1298191366** [comment]
请参考下图所示修改 试试还有没有问题
![29d8b8b0a4189e70dcb13bb4f9f01367](https://github.com/jeecgboot/JimuReport/assets/30997828/cb759e91-d656-4031-b3ef-5f57ea7812b6)
