### ISSUE TITLE
本地启动没问题，打成jar包丢到服务器上提示没找到文件

### ISSUE THREAD

**Issue by homhm** [jeecgboot/JimuReport#2594]
##### 版本号：
![image](https://github.com/jeecgboot/JimuReport/assets/55725287/41e9d813-1d12-402e-b52c-95b42e7fae84)

##### 问题描述：
本地启动没有问题，丢到服务器上启动不了

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/55725287/f8ab01b4-a9a5-41a0-a6b4-0b7ccce6c0e1)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
请补充项目名称和版本。

**Comment by jeecgos** [comment]
cr
