### ISSUE TITLE
API数据集请求头携带参数问题

### ISSUE THREAD

**Issue by 121820** [jeecgboot/JimuReport#2596]
##### 版本号：

1.7.4
##### 问题描述：

API数据集请求接口时，怎么增加请求的头信息参数呢
##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/21014747/3f76717e-d67e-4e75-abc0-06db3a770f03)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
自定义实现类header
