### ISSUE TITLE
报表计算报空指针

### ISSUE THREAD

**Issue by lostYoungWuYun** [jeecgboot/JimuReport#2597]
##### 版本号：

1.4.32
##### 问题描述：

报表计算报空指针

##### 错误日志&截图：

![111](https://github.com/jeecgboot/JimuReport/assets/35129771/e6be461c-fe1c-44cf-a6bd-80bbb0d4b98f)
![222](https://github.com/jeecgboot/JimuReport/assets/35129771/f90a224a-b403-4bc3-94c2-add16ed106ea)
![333](https://github.com/jeecgboot/JimuReport/assets/35129771/2c4df62e-a193-4a0a-bd54-f8a207c669ee)
![555](https://github.com/jeecgboot/JimuReport/assets/35129771/650487f2-2281-4c67-a22c-8d4a63984459)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请先升级到最新版再提对应问题
