### ISSUE TITLE
更换不了请求方式

### ISSUE THREAD

**Issue by liyunlong94** [jeecgboot/JimuReport#2598]
##### 版本号：
1.7.2-beta
##### 问题描述：

由于安全问题，积木报表url后面会拼接token，请问商业版的积木报表可以用post的请求方式把token放body来实现解决这个安全问题吗
##### 错误日志&截图：
![4A2A$E@0{E~LHMV3AME`A68](https://github.com/jeecgboot/JimuReport/assets/33396417/1fff14f6-3024-4f4b-8f64-a66ff71a3958)

##### 重现步骤：
打开每个配置完的报表都会带token在地址中

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

![2](https://github.com/jeecgboot/JimuReport/assets/33396417/d2a13607-6d5b-4ec4-ac5d-8ea4afe598cf)

**Comment by zhangdaiscott** [comment]
有分享报表功能，那个不带token
