### ISSUE TITLE
横纵动态分组存在问题

### ISSUE THREAD

**Issue by wqy727176064** [jeecgboot/JimuReport#2599]
##### 版本号：
1.7.4

##### 问题描述：
1.数据交叉分组存在问题，分组合并后列宽存在问题，数据会显示到第一列
![image](https://github.com/jeecgboot/JimuReport/assets/66465606/118d0529-02c1-4dfc-912f-c269a9949dc9)
![image](https://github.com/jeecgboot/JimuReport/assets/66465606/10f9a63c-e060-40ba-84d0-b1fd9bad3d29)
2.动态分列显示查无数据
![image](https://github.com/jeecgboot/JimuReport/assets/66465606/9ef9a349-8a4a-4458-bbb6-48da0dcdf6cb)
![image](https://github.com/jeecgboot/JimuReport/assets/66465606/d4fe35b1-68ae-465e-ae2c-facafcab9229)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by wqy727176064** [comment]
预计需求
![image](https://github.com/jeecgboot/JimuReport/assets/66465606/1f52bcaf-6593-4206-9645-7953d38622ad)

**Comment by wqy727176064** [comment]
预期样式
![image](https://github.com/jeecgboot/JimuReport/assets/66465606/82ade35a-a361-4c1b-8e73-d336df7bcf75)

**Comment by jeecgos** [comment]
交叉表需要使用横向分组，不是自定义分组。
参考文档：https://ojrjjvdr7z.k.topthink.com/jimureport/group/transverseDynamic.html

**Comment by wqy727176064** [comment]
> 交叉表需要使用横向分组，不是自定义分组。 参考文档：https://ojrjjvdr7z.k.topthink.com/jimureport/group/transverseDynamic.html

单独使用横向分组，数据都打印不出来
![image](https://github.com/jeecgboot/JimuReport/assets/66465606/1cc6487d-9aca-43f5-8399-8a8f405e6dec)
![image](https://github.com/jeecgboot/JimuReport/assets/66465606/b07a6c25-a226-4141-8fb5-0b8379b244d5)
