### ISSUE TITLE
能否增加一个横向的柱形图组件

### ISSUE THREAD

**Issue by davidlhfxa** [jeecgboot/JimuReport#2600]
##### 版本号：
Jimureport 1.5 免费版本，安装到本地的

##### 问题描述：
没有横向的柱形图组件，类似下面截图效果的

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/28556880/2ab2ddf8-e16c-403e-ba3f-e49d01f87b63)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
已添加，请等待新版本发布。
