### ISSUE TITLE
一个页面含2个数据集，条件通过参数传递查询，预览时参数条件不生效

### ISSUE THREAD

**Issue by 1322408199** [jeecgboot/JimuReport#2601]
##### 版本号：
1.7.4
##### 问题描述：
报表包含2个数据集，
2个数据集仅设置参数，报表字段明细tab页“查询”均不勾选，参数个数相同，字段名称一致，类型一致，一个日期范围条件，一个输入文本，设计过程参数都有默认值而且一致。
预览页面时，再更改查询条件，结果不发生变化。

##### 错误日志&截图：
预览：更改时间页面没有刷新

##### 重现步骤：
一个页面设置2个数据集，2个数据集操作同一张表，一个明细数据，一个是明细的求和数据。
之所以用2个数据集，是因为明细数据有一列在报表中会重复出现（操作时间不同，记录可以重复出现），而合计或总计行只想算其中一次的值，用sum()或dbsum() 均不能准确计算出真实求和值。 

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
截图详细说明或者线上做个例子

**Comment by 1322408199** [comment]
场景举例：
2张表，一张客户单据表，一张单据收费明细表。
--------------------------------------------------------------------------------------------------------------------------
tab_a (id int not null, name varchar(30) not null,  pcs numeric, weight numeric);
--id: 单据编号
--name:单据名称
--pcs: 单据件数
--weight: 单据重量
--------------------------------------------------------------------------------------------------------------------------
tab_b(id int not null, opetime default '"sysdate"()' not null, curpcs numeric, curweight numeric, curfee numeric)
--id: 单据编号
--opetime: 操作时间
--curpcs: 本次计费件数
--curweight:本次计费重量
--curfee: 本次计费金额
-->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
tab_a.id 和 tab_b.id 来数据关联

tab_a: 数据
----------------------------------------------------------------------
   id                     name                pcs                  weight(Kg) 
-----------------------------------------------------------------------
00001               食品                   10                       100
00002               衣服                   50                        10

tab_b: 数据
-----------------------------------------------------------------------------------------
   id                             opetime               curpcs              curweight(Kg)            curfee(RMB)
-----------------------------------------------------------------------------------------
00001                2024-05-07 12:05:00        5                       50                      100
00002                2024-05-07 13:10:00        50                     10                      150
00001                2024-05-08 10:15:00        5                       50                      320

--<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

tab_a 和 tab_b 关联期望数据结果(tab_a.id=tab_b.id)：
-----------------------------------------------------------------------------------------------------------------------------------------
 单据名(name)   单据号(id)      单据件数(pcs)     单据重量(weight)    操作时间(opetime)      curpcs    curweight     curfee
 食品                  00001               10                         100                    2024-05-07 12:05:00        5                  50             100
 食品                  00001               10                         100                    2024-05-08 10:15:00        5                  50             150
 衣服                  00002               50                         10                      2024-05-07 13:10:00       50                 10             320
------------------------------------------------------------------------------------------------------------------------------------------
合计                                    **这里是60                这里是110**                                             这里是60       这里是110   这里是570


数据集条件：操作时间和单据号
<#if isNotEmpty(id)>
 and a.id>= '${id}'
</#if>
<#if isNotEmpty(opetime)>
 and b.opetime>= '${opetime_begin}'
 and b.opetime<= '${opetime_end}'
</#if>


问题：
通过tab_a和tab_b关联，单据件数和单据重量在合计行上不是期望的值。

**Comment by jeecgos** [comment]
cr
