### ISSUE TITLE
直接将预览链接插入iframe使用，部署后公网地址无法访问服务器数据库有办法解决吗？

### ISSUE THREAD

**Issue by N1ck549** [jeecgboot/JimuReport#2602]
##### 版本号：
1.6.6

##### 问题描述：
直接将图形报表的预览链接插入iframe使用，本地Localhost可以正常访问，部署后公网地址无法访问服务器数据库有好的办法解决吗？

##### 错误日志&截图：
”提示数据源配置错误，请检查链接“

**Comment by zhangdaiscott** [comment]
这是你自己项目的问题
