### ISSUE TITLE
表格边框渲染错误

### ISSUE THREAD

**Issue by wqy727176064** [jeecgboot/JimuReport#2603]
##### 版本号：
1.7.4

##### 问题描述：
已设置边框，但部分数据（空数据）边框无显示。

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/66465606/b1f740b9-033e-4f74-8176-2b3fa47893f7)
![image](https://github.com/jeecgboot/JimuReport/assets/66465606/2d11defe-5c98-48f1-97a9-340144da0bb6)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by wqy727176064** [comment]
使用的动态合并

**Comment by zhangdaiscott** [comment]
cr

**Comment by zhangdaiscott** [comment]
请针对问题提供[报表设计配置或SQL脚本]或在官网制作报表示例并提供ID;

**Comment by hoperunChen** [comment]
@wqy727176064 w「动态合并格」功能是为了合并固定内容列采用的功能，他的本身并不是给动态单元格用的。
![image](https://github.com/user-attachments/assets/ba8a6c35-e680-40d9-9537-211d181e1201)

**您的这个需求可以使用分组功能来实现，分组功能会对数据排序，来保证动态数据的相邻合并。**[纵向分组文档](https://help.jeecg.com/jimureport/group/direction.html)
