### ISSUE TITLE
=row() 生成行号 如果有空白格添加边框线后 会出现空白行有行号

### ISSUE THREAD

**Issue by wenhongjun** [jeecgboot/JimuReport#2604]
##### 版本号：
1.7.4

##### 问题描述：
=row() 生成行号 如果有空白格添加边框线后 会出现空白行有行号

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/40422721/bef48d2c-2a37-422b-bf49-09b0bd67070e)

![1714879573059](https://github.com/jeecgboot/JimuReport/assets/40422721/1207ac29-7a08-4fc0-b274-0d9dfd76ed79)
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
啥意思

**Comment by jeecgos** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
