### ISSUE TITLE
导出pdf只会导出当前页的数据

### ISSUE THREAD

**Issue by wenhongjun** [jeecgboot/JimuReport#2605]
##### 版本号：
1.7.4
##### 问题描述：
1.导出pdf只会导出当前页的数据
2. 空白单元格（复制其他单元格后删除里面的内容）导出没有边框线，如果重新选择边框线，没有数据时就会有空的一行且有行号
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/40422721/6a3b7f9f-9d69-445c-946b-8b94d7cf5c5b)
![image](https://github.com/jeecgboot/JimuReport/assets/40422721/15611914-efcb-4fdd-82f2-eaa8e0da35e8)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by wenhongjun** [comment]
行号使用的是=row()

**Comment by zhangdaiscott** [comment]
ws

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by 1298191366** [comment]
问题1：niru你如果是api的情况下，接口回传一个`printAll`当为true的时候需要你接口返回所有数据
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/49f4880c-deed-497c-95ec-233708685ac6)
问题2：未复现，请提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)，及测试数据
