### ISSUE TITLE
api数据集中显示token为null

### ISSUE THREAD

**Issue by yupenglideyupeng** [jeecgboot/JimuReport#2608]
##### 版本号：
1.6.4

##### 问题描述：
实现了JmReportTokenServiceI，也重写了getToken方法，日志里也是有对应获取到token，到页面上使用api就提示没有token

##### 错误日志&截图：
 
![QQ截图20240506145246](https://github.com/jeecgboot/JimuReport/assets/111445730/7a37d0ba-57c5-4894-8873-c270f493eb76)
![QQ截图20240506145235](https://github.com/jeecgboot/JimuReport/assets/111445730/fad17dbc-2c4b-4b30-bfcb-71acd0a62ff0)
![QQ截图20240506145228](https://github.com/jeecgboot/JimuReport/assets/111445730/d144ab37-09fc-40c0-864e-af2b44138d45)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
header中没有传递token？

**Comment by 1298191366** [comment]
未复现。你说的在页面上使用api是什么意思，下面是测试结果，如有问题请再次回复
测试结果：
api解析
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/6c46fafb-5897-4a92-8546-51eb514e47fd)
预览：
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/5eb86085-f743-4d97-b58a-e3bc90ca510d)
