### ISSUE TITLE
单元格表达式渲染错误

### ISSUE THREAD

**Issue by WooZhangYan** [jeecgboot/JimuReport#2609]
##### 版本号：
V1.6.6

##### 问题描述：
同样的报表，查询条件不同但是列数据基本相同，有的正常，有的却会报错单元格渲染失败

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/104556081/56644341-06c9-4333-9b87-f3689428fec8)
![image](https://github.com/jeecgboot/JimuReport/assets/104556081/fb819019-a352-42be-aa5a-347432a5125a)
![image](https://github.com/jeecgboot/JimuReport/assets/104556081/f11d28aa-0036-4ce8-a264-67c3a77862f4)
![image](https://github.com/jeecgboot/JimuReport/assets/104556081/57c41e4e-9a1b-4526-9db7-8be291cfb666)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
cr

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by 1298191366** [comment]
未复现，请提供[[SQL脚本]](https://help.jeecg.com/jimureport/issues.html)，或升级到最新版本试一下
> if函数
![image](https://github.com/user-attachments/assets/2b2f24d7-a605-4da0-9dbc-1b2877e7db06)
> 设计页面
![image](https://github.com/user-attachments/assets/638f84ea-3909-4840-a454-3b532e6a82bd)
> 预览页面
![image](https://github.com/user-attachments/assets/11b7b21b-d78a-4141-a28e-79203f2ab803)
> 最新版本
(1.7.9)[http://www.jimureport.com/doc/log]
