### ISSUE TITLE
新建报表保存之后页面关闭后，找不到已保存的报表信息，列表里刷新也不显示。

### ISSUE THREAD

**Issue by lranlran** [jeecgboot/JimuReport#2611]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
报什么错

**Comment by zhangdaiscott** [comment]
ws

**Comment by zhangdaiscott** [comment]
你是不是没有配置数据库？初始化数据库了吗
