### ISSUE TITLE
表格数值类型展示错误0E-9

### ISSUE THREAD

**Issue by 318313260** [jeecgboot/JimuReport#2613]
##### 版本号：
v1.7.2

##### 问题描述：
存储过程报表展示:当数据为空或者0时,页面展示为0E-9
使用的数据库为SqlServer
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/59547202/d9adca49-48d8-41a7-bb50-c84e5df210cf)
![image](https://github.com/jeecgboot/JimuReport/assets/59547202/72117380-4f3b-4dd0-9ca9-e056c9997991)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
在1.7.8+版本中已经修复了该问题，升级到最新版试试
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.7.9</version>
</dependency>
```
