### ISSUE TITLE
主子表数据批量打印按主表分页显示问题

### ISSUE THREAD

**Issue by jun2751** [jeecgboot/JimuReport#2615]
##### 错误日志&截图：

![1715162581558](https://github.com/jeecgboot/JimuReport/assets/135805650/ace8dc20-34f9-45c7-9bc5-27aec311adc6)

##### 重现步骤：
官网报表模版ID:948114618600214528

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by liaozhiyang** [comment]
分版区域选择有问题
![image](https://github.com/jeecgboot/JimuReport/assets/8199499/b478ec07-2905-4e11-8dc5-b032193be697)

按这样改试试
![image](https://github.com/jeecgboot/JimuReport/assets/8199499/0a4b0f20-18a1-4d04-87a0-ebc28b4edc6d)

**Comment by liaozhiyang** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/8199499/3c66e589-4ac9-4455-b147-35f6731f388e)
