### ISSUE TITLE
大屏设计器可以集成到springboot项目中吗

### ISSUE THREAD

**Issue by zhangkaichuang** [jeecgboot/JimuReport#2616]
我把积木报表集成到springboot项目中之后，在报表管理的首页没有找到大屏设计器，大屏设计器是可以集成到springboot项目中的吗，还是说大屏设计器模块未开源需要购买之后才能使用
![微信图片_20230811175008](https://github.com/jeecgboot/JimuReport/assets/77256324/368049d4-1b7d-40a0-892e-92bbd22a73d9)

**Comment by zhangdaiscott** [comment]
大屏不开源
