### ISSUE TITLE
查询条件为空时弹窗提示

### ISSUE THREAD

**Issue by YangJuQuan** [jeecgboot/JimuReport#2618]
##### 问题描述：
![image](https://github.com/jeecgboot/JimuReport/assets/44860527/4367ffed-85ff-419d-a9f2-4ce4bc9c9d1d)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by YangJuQuan** [comment]
有解决方法吗

**Comment by zhangdaiscott** [comment]
看后面的规划

先收录到“需求汇总”中
https://github.com/jeecgboot/JimuReport/issues/138

**Comment by 1298191366** [comment]
已优化，下个版本支持参数配置`{"required":true}` 是否必填
