### ISSUE TITLE
返回上一页无法返回原报表问题

### ISSUE THREAD

**Issue by wenhongjun** [jeecgboot/JimuReport#2621]
##### 版本号：
1.7.4

##### 问题描述：
报表钻取后切换上方tab页，再返回当前报表点击返回上一页无法回到原报表了

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/40422721/2e60e09d-7535-4e58-b394-ab458b8236a9)

##### 重现步骤：
报表钻取后切换上方tab页，再返回当前报表点击返回上一页无法回到原报表了

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
