### ISSUE TITLE
表格动态横向分组如何计算合计

### ISSUE THREAD

**Issue by chinahongyuan** [jeecgboot/JimuReport#2623]
##### 版本号：
1.5

##### 问题描述：
如何进行动态横向分组合计？

##### 错误日志&截图：
![微信图片_20240511171510](https://github.com/jeecgboot/JimuReport/assets/42561646/ae7958d6-9555-4202-92a7-60c7d4a431d3)

##### 重现步骤：
比如我要计算examcount的合计，如何处理？

**Comment by jeecgos** [comment]
升级到1.7.0+版本
