### ISSUE TITLE
怎么设置报表查询参数的默认值为当前日期或者当前月份

### ISSUE THREAD

**Issue by wqy727176064** [jeecgboot/JimuReport#2624]
##### 版本号：
1.7.4

##### 问题描述：
怎么设置报表查询参数的默认值为当前日期或者当前月份

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/66465606/848bbed1-fd85-463a-86f2-07932d2b46d1)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/162332873/d82d12f0-faef-473e-9097-0a6b36341a2f)
参考：https://help.jeecg.com/jimureport/query/timeControlDefaultValue.html
