### ISSUE TITLE
分组和表达式不支持一起使用，无法达成分组数据动态展示数据背景颜色的效果

### ISSUE THREAD

**Issue by flightwang** [jeecgboot/JimuReport#2625]
##### 版本号：

1.7.4
##### 问题描述：
分组和表达式不支持一起使用，无法达成分组数据动态展示数据背景颜色的效果

##### 重现步骤：
分组 #{xs.dynamic(sales)}

表达式 =(let sex= 10; if(sex< 0){ return  color(sex,'#ffffff','#EE5739');}elsif(sex== 0){return color(sex,'#ffffff','#1ABF3F');}else{return color(sex,'#ffffff','#0F95FC');})

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
暂不支持，归集：#138
