### ISSUE TITLE
导出报表穿越

### ISSUE THREAD

**Issue by remuzimalin** [jeecgboot/JimuReport#2627]
##### 版本号：
1.6.1

##### 问题描述：
同时查看A和B两张报表，在A报表页面内导出EXCEL时，会出现导出的却是B报表的数据。

##### 错误日志&截图：

![导出串表](https://github.com/jeecgboot/JimuReport/assets/169422839/e84f3ab3-2679-4a04-b0e5-f36a5d98237f)

##### 重现步骤：
导出报表名称是A，但数据是B表的数据。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
cr

**Comment by jeecgos** [comment]
@remuzimalin 
升级到1.7.52+版本试下。

**Comment by hoperunChen** [comment]
@remuzimalin 升级到1.7.52以上版本试下，在1.7.52版本已经修复该问题。
#2488
