### ISSUE TITLE
使用存储过程查询结果不能分页

### ISSUE THREAD

**Issue by remuzimalin** [jeecgboot/JimuReport#2628]
##### 版本号：
1.6.1

##### 问题描述：
调用存储过程查出来的结果，即使设置了分页及行数，也不起作用，查出来的结果会在一个页面里显示，不会分页；

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
存储过程暂时不支持分页，归集：#138
