### ISSUE TITLE
静态值如何自动合并单元格

### ISSUE THREAD

**Issue by sjqit** [jeecgboot/JimuReport#2629]
##### 问题描述：
“统计报表”四个字的表格怎么随着横向分组的字段的列数自动合并单元格

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/167081020/7a13061f-387b-47b2-bb3b-108115a70aff)
![image](https://github.com/jeecgboot/JimuReport/assets/167081020/1df37701-e9ed-4088-b4d2-5139b8ba30ab)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
1.7.0+ 版本已支持表格标题随横向分组扩展，请升级至最新版本。
![image](https://github.com/user-attachments/assets/2dc282c5-1eaf-4ccc-8ea0-8709b6d6d15c)
![image](https://github.com/user-attachments/assets/54042adc-2e32-4ab5-a440-6092e0f8094b)
