### ISSUE TITLE
请问一下这个给按钮添加权限如何实现？

### ISSUE THREAD

**Issue by ss2121qwwq11** [jeecgboot/JimuReport#2630]
##### 版本号：
1.7.4

##### 问题描述：
![企业微信截图_17157603935488](https://github.com/jeecgboot/JimuReport/assets/134994272/1d2dd42b-a76c-4ff4-a632-c869aab3ebc7)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
暂不支持，归集：#138
