### ISSUE TITLE
报表导入后样式丢失，并且参数名、字段名错乱

### ISSUE THREAD

**Issue by Dmo24** [jeecgboot/JimuReport#2631]
##### 版本号：
1.7.4

##### 问题描述：
报表导入后样式丢失，并且参数名、字段名错乱

##### 错误日志&截图：
<img width="1102" alt="4ad031e2f9f0a28dd4aadbc9b60f02bc" src="https://github.com/jeecgboot/JimuReport/assets/38171886/b187be0d-5e43-4457-82c6-a4e3d55fa9b4">

##### 重现步骤：
导出报表，然后导入

**Comment by zhangdaiscott** [comment]
ws

**Comment by jeecgos** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
