### ISSUE TITLE
导出报错

### ISSUE THREAD

**Issue by 13834607883** [jeecgboot/JimuReport#2632]
##### 问题描述：
报表导出：
报表中合并单元格以后导出报错，转换异常

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/162332873/79a1921f-acd6-43e2-bda6-7074b1ed804f)
未复现，请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by zhangdaiscott** [comment]
未按格式要求发帖，会被直接删掉;
