### ISSUE TITLE
API输出

### ISSUE THREAD

**Issue by 13813586515** [jeecgboot/JimuReport#2633]
##### 问题描述：
制作好一张报表之后，如何能把这张报表的内容通过api输出，比如可以给移动端使用，可以给第三方使用

##### 错误日志&截图：
暂无

##### 重现步骤：
暂无

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
目前不支持移动端，今年会上仪表盘支持移动端
