### ISSUE TITLE
报表查询条件

### ISSUE THREAD

**Issue by AlexWangQP** [jeecgboot/JimuReport#2634]
##### 版本号：
1.7.4

##### 问题描述：
在查询选择下拉单选的时候，当列表首次加载有数据会先试下拉框，重新查询后列表无数据，下拉框的数据依然存在，首次加载如果没有数据，查询哪里就不会呈现出为下拉框，而是简单的数据输入框，不是应该呈现是下拉框显示暂无数据吗？使用条件再次搜索列表展示数据了，但是查询哪里还是输入框，不能一下拉的形式去呈现

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
目前只是初始化的时候才会加载查询条件，后期报表查询条件不再支持自动解析数据中查询字段作为字典
![image](https://github.com/user-attachments/assets/9ce75f3f-d041-46b5-89a1-668cf339e41d)
