### ISSUE TITLE
图片显示问题

### ISSUE THREAD

**Issue by gongyuxiaoyou** [jeecgboot/JimuReport#2635]
##### 版本号：
1.7.4

##### 问题描述：
图片一直是裂图，不管什么格式。然后图片没有值的，也显示裂图。如图是显示了base64的字符串，以及图片显示的样子

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/67811461/09807cc5-2236-4edc-8cea-baea0641f128)

![image](https://github.com/jeecgboot/JimuReport/assets/67811461/ee210d68-e70d-462b-999b-38da88511dfc)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你的普通内容是什么格式

**Comment by gongyuxiaoyou** [comment]
> 你的普通内容是什么格式

除了那个裂图是Base64图片格式（以及图片格式也试过了），其他内容格式都是“正常”，我看其他人也提了这个裂图问题

**Comment by gongyuxiaoyou** [comment]
还测出一个新的问题了，导出pdf的时候，如果base64的值为null或者为""，那会导致报错

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by zhangdaiscott** [comment]
ws
