### ISSUE TITLE
对于集合数据值为0或者为空是否在图例上不需要表现出来

### ISSUE THREAD

**Issue by afearboy** [jeecgboot/JimuReport#2637]
##### 版本号：
1.6.4

##### 问题描述：
对于集合数据值为0或者为空是否在图例上不需要表现出来
数据集合为：
![image](https://github.com/jeecgboot/JimuReport/assets/82691864/4a5e7239-98cc-4bf1-a30e-7967b6f1b519)

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/82691864/5f642346-f831-45cd-8c28-18b765713f79)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你是不是应该控制数据，不查为零的
