### ISSUE TITLE
在dataease中集成积木报表报nested exception is java.lang.NoSuchMethodError: 'net.sf.jsqlparser.statement.select.SelectBody  错误

### ISSUE THREAD

**Issue by ss2121qwwq11** [jeecgboot/JimuReport#2639]
##### 版本号：
1.7.4
##### 问题描述：
在dataease 中分支为(**pr@dev@refactor_richText**)集成jimureport 报错，
dataease项目地址：https://github.com/dataease/dataease
dataease 依赖的jsqlparser版本为4.8

```
  <dependency>
            <groupId>com.github.jsqlparser</groupId>
            <artifactId>jsqlparser</artifactId>
            <version>4.8</version>
   </dependency>
```

##### 错误日志&截图：
"nested exception is java.lang.NoSuchMethodError: 'net.sf.jsqlparser.statement.select.SelectBody net.sf.jsqlparser.statement.select.Select.getSelectBody()'"

##### 重现步骤：
在项目 core\backend\pom.xml 中引入jimureport依赖
第一步：
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
   <version>1.7.4</version>
</dependency>
```
第二步：
```
io.dataease.auth.filter.JWTFilter.preHandle返回值修改为：true
```
#### 友情提示（为了提高issue处理效率）：
- 积木报表是一款免费报表产品，功能免费源码不开放;
- 未按格式要求发帖，会被直接删掉;
- 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
- 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
jsqlparser版本号冲突
