### ISSUE TITLE
负数与0.000000进行计算时，小数位数限制失效

### ISSUE THREAD

**Issue by hh207** [jeecgboot/JimuReport#2642]
##### 版本号：
1.7.3

##### 问题描述：
负数与0.000000进行计算时，小数位数限制失效

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/63766613/57727e41-cf25-41b0-b097-0f0a5ecfbce0)
![image](https://github.com/jeecgboot/JimuReport/assets/63766613/212a3b90-1901-49c7-abeb-0b4da191435f)

##### 重现步骤：
1. 设置一列为负数的列
2. 设置一列为0.000000的列
3. 将两列值进行相乘，显示为科学计数法展示形式

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
已修复，待新版本发布
