### ISSUE TITLE
自定义排序不生效

### ISSUE THREAD

**Issue by wqy727176064** [jeecgboot/JimuReport#2643]
##### 版本号：
1.7.4

##### 问题描述：
第二列设置了自定义排序，未生效

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/66465606/89f9b82f-0eda-4919-be4f-3b9c4cf51406)
实际生成样式：
![image](https://github.com/jeecgboot/JimuReport/assets/66465606/472abfe6-1962-4339-a328-be8828afd969)
目标样式：
![image](https://github.com/jeecgboot/JimuReport/assets/66465606/7101ccb8-7765-4930-bf74-f9fd6fcb7da8)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
cr

**Comment by zhangdaiscott** [comment]
请针对问题提供[报表设计配置或SQL脚本]或在官网制作报表示例并提供ID;
