### ISSUE TITLE
积木报表打印在预览时正常，但点击打印按钮时报错（不弹出打印页面）

### ISSUE THREAD

**Issue by KKConney** [jeecgboot/JimuReport#2645]
##### 问题描述：
前端应用 在 打印预览时 正常显示数据，但在点击打印按钮时 接口报错，400，问题是 ，数据条数过多时会出现报错，可能条数少可以弹出打印页面

##### 错误日志&截图：

![WX20240517-174701@2x](https://github.com/jeecgboot/JimuReport/assets/8678483/87a49a82-d377-4185-91b5-ef1d5cec2505)

##### 重现步骤：
1、新建设计页面；
2、配置api数据后，数据是 集合；
3、参数传递以 加密的 base64 形式

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
未按格式要求发帖，会被直接删掉;
