### ISSUE TITLE
希望增加选项可以默认展开查询栏

### ISSUE THREAD

**Issue by zzdxzhangzhi** [jeecgboot/JimuReport#2646]
##### 版本号：
1.7.4

##### 问题描述：
报表的查询栏默认是收缩的，查询条件看不到。希望能通过修改选项，默认看到这样的页面：
![1715944854724](https://github.com/jeecgboot/JimuReport/assets/23204727/6e5011b4-65d1-4ea9-9075-24fe452cff67)

##### 错误日志&截图：
![1715944842869](https://github.com/jeecgboot/JimuReport/assets/23204727/368ececb-bed4-42f0-ab90-8dc51439331f)

##### 重现步骤：
每个报表都是如此。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
看后面的规划

先收录到“需求汇总”中
https://github.com/jeecgboot/JimuReport/issues/138

**Comment by 1298191366** [comment]
目前可以通过 js增强来实现，升级到最新版`1.7.8`即可
![image](https://github.com/user-attachments/assets/8121aa0b-7136-46c1-be9f-7af6d979b41a)

![image](https://github.com/user-attachments/assets/32fd8dcb-e1a0-4bb6-8c27-22ed6a976aa8)

(参考文档)[https://help.jeecg.com/jimureport/qa.html#38%E9%A2%84%E8%A7%88%E7%95%8C%E9%9D%A2%E6%9F%A5%E8%AF%A2%E6%A0%8F%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE%E9%BB%98%E8%AE%A4%E5%B1%95%E5%BC%80]
