### ISSUE TITLE
图表坐标轴标题超出隐藏

### ISSUE THREAD

**Issue by xi-xi-jun** [jeecgboot/JimuReport#2647]
##### 版本号：
docker部署 1.7.4

##### 问题描述：
图表坐标轴标题超出隐藏，是否可以修改显示标题字数？如果在右边距中进行调整，滑块拉到最大，也就只能显示6个字符。

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/113566654/3e433149-d708-4beb-bf3e-d15ac24bd52d)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布，后续版本最多支持15个字
