### ISSUE TITLE
部分报表SQL查询时间太长了 超过一分钟  客户不知道是不是能加载出来 等待没有耐心 能否增加一个加载中页面  进行引导

### ISSUE THREAD

**Issue by Anchor957** [jeecgboot/JimuReport#2650]
##### 版本号：
任何版本

##### 问题描述：
加载时间过长没有加载中引导

##### 重现步骤：
慢SQL的时候很明显

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
预览加载吗

**Comment by 1298191366** [comment]
预览加载目前是存在的，如果是滴版本请升级到最新版本尝试一下
![预览加载](https://github.com/user-attachments/assets/ff458112-d788-482f-88c7-ad7fd73f66fb)
