### ISSUE TITLE
积木报表总是报这个错误

### ISSUE THREAD

**Issue by qwe1076293486** [jeecgboot/JimuReport#2652]
##### 版本号：
V1.7.4

##### 问题描述：
积木报表经常页面无法加载  报Incompatible magic value 33554431 in class file 

##### 错误日志&截图：
{"code":1,"msg":"Handler dispatch failed; nested exception is java.lang.ClassFormatError: Incompatible magic value 33554431 in class file org/jeecg/modules/jmreport/common/util/ViewFreemarker","data":null,"ok":false}
<img width="1079" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/28478407/53f85764-03c5-4a14-a381-07342099b202">

##### 重现步骤：
一般是频繁预览和下载后会产生

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
如何重现

**Comment by qwe1076293486** [comment]
大量用户同时去操作预览和下载的情况下  产生的

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
未复现，请提供可以复现的测操作步骤。
尝试复现的步骤如下：
使用接口工具对预览页面进行压测
![QQ_1721648609680](https://github.com/user-attachments/assets/c6570ca0-f55e-44b8-bb56-e06565817462)
压测的错误接口是因为超时：
![QQ_1721649124641](https://github.com/user-attachments/assets/50e7835e-86ba-4364-b52c-91d086d95562)
压测的同时使用浏览器访问，会发现加载时间明细变长了，但是最终都能加载出来。
![QQ_1721649013220](https://github.com/user-attachments/assets/ea6b5fa3-dd95-4bcc-973a-652fb3fe7dd9)
![QQ_1721648317794](https://github.com/user-attachments/assets/a8e8db09-fc5d-492b-acb7-da3593d64163)

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
