### ISSUE TITLE
按表头分组，有时候会出现表头只显示部分列名，大部分列名不显示的情况

### ISSUE THREAD

**Issue by AXXZSTHL** [jeecgboot/JimuReport#2655]
##### 版本号：
1.7.2

##### 问题描述：
按表头分组，有时候会出现表头只显示部分列名，大部分列名不显示的情况

##### 错误日志&截图：

![WX20240527-101607@2x](https://github.com/jeecgboot/JimuReport/assets/37093283/05014860-39e2-415a-a239-d776cf9b28cd)

![WX20240527-101654@2x](https://github.com/jeecgboot/JimuReport/assets/37093283/4a87fec8-504b-4272-b052-87c82c4c1842)

##### 重现步骤：

select 院区, 门诊类别,挂号量 from  dual
查询出来的结果：
院区1  普通门诊  213
院区1   专家门诊  12 
院区2  普通门诊  54
院区2  专家门诊  121

我初步感觉是因为 数据如果有缺少对应院区的门诊类别数据时，就会导致显示bug，重新吧报表制作一遍又好了，但是过段时间不定期又出现这种问题，无法修复 ，感谢

**Comment by zhangdaiscott** [comment]
提供重现数据

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
