### ISSUE TITLE
分组后怎么设置行号

### ISSUE THREAD

**Issue by apple0407** [jeecgboot/JimuReport#2658]
##### 版本号：
1.7

##### 问题描述：
分组后怎么设置行号。

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/jimureport/function/lineNumber.html

**Comment by apple0407** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件我已收到，我会尽快给您回复。

**Comment by apple0407** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件我已收到，我会尽快给您回复。
