### ISSUE TITLE
Api 数据源能不能统一管理，后续新增报表直接选就行了

### ISSUE THREAD

**Issue by a520213** [jeecgboot/JimuReport#2660]
##### 版本号：
Api 数据源能不能统一管理，后续新增报表直接选就行了

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
看后面的规划

先收录到“需求汇总”中
https://github.com/jeecgboot/JimuReport/issues/138

**Comment by jeecgos** [comment]
v1.9.0版本已支持共享数据集。文档参考：https://help.jeecg.com/jimureport/dataSet/shareSource.html
