### ISSUE TITLE
图表柱状图中，X轴的文字 倾斜40度怎么设置

### ISSUE THREAD

**Issue by tank-w** [jeecgboot/JimuReport#2661]
##### 版本号：
1.5.4

##### 问题描述：
![QQ图片20240528094745](https://github.com/jeecgboot/JimuReport/assets/30696089/f1cce9e0-d706-4c65-bbb1-7048dd3fe256)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
你是想要这个吗？你可以在x轴设置，文字角度拖拽滑动条
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/610e6ed4-0ae9-45bc-bcc8-e0e6bdfafda7)
