### ISSUE TITLE
默认进入报表页面不进行查询这个怎么设置的，我没找到，方便提供一下吗

### ISSUE THREAD

**Issue by AXXZSTHL** [jeecgboot/JimuReport#2662]
##### 版本号：
1.7.4

##### 问题描述：
默认进入报表页面不进行查询这个怎么设置的，我没找到，方便提供一下吗

##### 重现步骤：
默认进入报表页面不进行查询这个怎么设置的，我没找到，方便提供一下吗

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/jimureport/query/jsEnhance.html#4%E8%AE%BE%E7%BD%AE%E9%A2%84%E8%A7%88%E4%B8%8D%E8%87%AA%E5%8A%A8%E5%8A%A0%E8%BD%BD%E6%95%B0%E6%8D%AE

**Comment by AXXZSTHL** [comment]
好的好的，十分感谢发自我的 iPhone在 2024年5月31日，13:30，JEECG ***@***.***> 写道：﻿
https://help.jeecg.com/jimureport/query/jsEnhance.html#4%E8%AE%BE%E7%BD%AE%E9%A2%84%E8%A7%88%E4%B8%8D%E8%87%AA%E5%8A%A8%E5%8A%A0%E8%BD%BD%E6%95%B0%E6%8D%AE
