### ISSUE TITLE
使用配置字典后预览报错：Null key returned for cache operation

### ISSUE THREAD

**Issue by xueshiji** [jeecgboot/JimuReport#2664]
##### 版本号：
jimureport-spring-boot3-starter-fastjson2 1.7.3
springboot 3.2.5

##### 问题描述：
报错Null key returned for cache operation，经调试发现是下图中var3找不到导致的，就很玄学

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/32958628/8ead8370-335c-494c-b237-ed33424492ea)
![image](https://github.com/jeecgboot/JimuReport/assets/32958628/cde71f7e-091a-47cd-adaf-7be8066a6563)

##### 重现步骤：
配置字典后预览即可重现

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
cr

**Comment by 1298191366** [comment]
未复现，你本地应该有啥特殊的配置吧
![image](https://github.com/user-attachments/assets/c7e5b304-f7db-44d7-9455-f1108ad8a311)

![image](https://github.com/user-attachments/assets/54c2e7e7-8c58-478f-9dea-6f57dd997167)

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
