### ISSUE TITLE
积木报表单元格无定时刷新功能

### ISSUE THREAD

**Issue by YaoWei1ong** [jeecgboot/JimuReport#2665]
##### 版本号：
1.7.4

##### 问题描述：
积木报表单元格无定时刷新数据功能，是否可通过其他方式实现？

##### 错误日志&截图：
![企业微信截图_17169637288419](https://github.com/jeecgboot/JimuReport/assets/53426902/cd3b3308-1f43-401b-9ba5-d3bf592ce5bc)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Cmr111** [comment]
有解决办法了吗？

**Comment by YaoWei1ong** [comment]
显然没有

**Comment by zhangdaiscott** [comment]
看后面的规划

先收录到“需求汇总”中
https://github.com/jeecgboot/JimuReport/issues/138
