### ISSUE TITLE
js增强可以动态控制导出按钮是否显示吗

### ISSUE THREAD

**Issue by zzbsss** [jeecgboot/JimuReport#2669]
##### 版本号：
v:1.6.7

##### 问题描述：

js增强动态控制导出按钮是否显示吗

**Comment by zhangdaiscott** [comment]
不能

**Comment by zhangdaiscott** [comment]
看后面的规划

先收录到“需求汇总”中
https://github.com/jeecgboot/JimuReport/issues/138
