### ISSUE TITLE
积木报表下拉搜索模糊匹配无效

### ISSUE THREAD

**Issue by LLLLJJJJMMMM** [jeecgboot/JimuReport#2672]
##### 版本号：
1.7.4

##### 问题描述：
输入数字时模糊匹配无效

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/101620126/22d03f3a-4b1f-4a11-a986-d4d3762840f6)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
