### ISSUE TITLE
使用积木报表1.7.4版本，无法进入报表详情，网页控制台报错：SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by JackMartin1** [jeecgboot/JimuReport#2673]
##### 版本号：
1.7.4

##### 问题描述：
使用springboot集成jimureport，进入jmreport/list页面后，无法再进入某个报表的详情，打开控制台后发现 getReportConfigJson函数异常

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/32858595/e513ffd4-81b8-499f-ad5b-3247971762d8)
![image](https://github.com/jeecgboot/JimuReport/assets/32858595/867078f7-770c-433a-9fb1-58496367ea97)

##### 重现步骤：
1.集成jmreport依赖
2.运行项目，访问jmreport/list
3.点击进入其中任意一个报表

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
所有报表都这样？还是个别的
