### ISSUE TITLE
报表字段文本显示字段注释

### ISSUE THREAD

**Issue by muzi2580** [jeecgboot/JimuReport#2674]
##### 版本号：
1.5.6

##### 问题描述：
查询出来的表结构字段文本应该为字段注释，可是显示还是字段名。

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/118150617/2590819a-ac59-4177-9496-02792d7ae054)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
我们并未真正去查询表结构，算法不一样

**Comment by zhangdaiscott** [comment]
看后面的规划

先收录到“需求汇总”中
https://github.com/jeecgboot/JimuReport/issues/138
