### ISSUE TITLE
下拉查询只有10条选项，我想全部显示，在参数里配置了{'selectSearchPageSize':20}，确定后还是只有10条

### ISSUE THREAD

**Issue by 1732690250** [jeecgboot/JimuReport#2675]
##### 版本号：
1.4.0

##### 问题描述：
下拉查询只有10条选项，我想全部显示，在参数里配置了{'selectSearchPageSize':20}，确定后还是只有10条

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/145249915/98ac4c9d-20a8-42de-9e96-dd99ec97465c)
![image](https://github.com/jeecgboot/JimuReport/assets/145249915/06d25e1a-75f7-4800-8199-17dc0ac780c1)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws
