### ISSUE TITLE
SpringBoot2.7.18集成jimureport1.7.4 jar启动报错

### ISSUE THREAD

**Issue by HoHo1** [jeecgboot/JimuReport#2677]
##### 版本号：
SpringBoot 2.7.18
jimureport 1.7.4 
mybatisplus 3.5.6
##### 问题描述：
idea本地运行正常,打包jar启动异常

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/4090983/571d43d3-3130-4fbc-a648-f39826639ec7)

##### 重现步骤：
![image](https://github.com/jeecgboot/JimuReport/assets/4090983/70a16846-b651-418c-a1ec-61521c245b5e)
jsqlparser与mybatisplus版本冲突
![image](https://github.com/jeecgboot/JimuReport/assets/4090983/9139bafb-95ac-48da-9600-de9b1a517142)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by HoHo1** [comment]
最新的1.7.52也是一样的问题

**Comment by zhangdaiscott** [comment]
手工排除冲突依赖

**Comment by HoHo1** [comment]
> 手工排除冲突依赖
冲突的jsqlparser已经排除了 ,是还有其他依赖冲突?
 现在是在idea总可以启动 打包jar之后无法启动
