### ISSUE TITLE
图片设置，打印预览时没问题，调用打印机会错位

### ISSUE THREAD

**Issue by Capela-Cui** [jeecgboot/JimuReport#2678]
##### 版本号：
报表id 958236561257091072
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/60765807/2edcd34e-75c0-4f52-bf21-4fc29cad71da)

![image](https://github.com/jeecgboot/JimuReport/assets/60765807/025191fe-f4e8-462b-8291-0460bce41b8d)

##### 重现步骤：
![image](https://github.com/jeecgboot/JimuReport/assets/60765807/4d1425d7-7606-4b4c-b3f6-fe19bec56ac5)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
未按格式要求发帖，会被直接删掉;
