### ISSUE TITLE
折柱图报错

### ISSUE THREAD

**Issue by LLLLJJJJMMMM** [jeecgboot/JimuReport#2680]
##### 版本号：
1.6.6
##### 问题描述：
折柱图报错，但是api反显的json转为静态数据没有问题，调用APi动态数据会出现该问题

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/101620126/adbd6b17-481d-402e-b526-77d2c25b62a8)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
升级到最新版看看 1.7.5
