### ISSUE TITLE
字段名称有“-”短横线字符，解析报错

### ISSUE THREAD

**Issue by sjqit** [jeecgboot/JimuReport#2682]
##### 版本号：
1.6.6

##### 问题描述：
字段名称有“-”短横线字符，解析报错（整编-库水位日整编-一天-A20107100000TEST01）

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/167081020/4cd79c93-2f4b-4555-917d-22b0f19b529f)
![image](https://github.com/jeecgboot/JimuReport/assets/167081020/d9181ab3-1c6e-4fda-9030-0e2455f46f2e)
![image](https://github.com/jeecgboot/JimuReport/assets/167081020/57dcc70d-27c6-4d0f-a8ee-c4f59948acb6)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by ccc247215** [comment]
不止，我归类了：空格，/，（，），(，），.,=,>,<   都不行

**Comment by 1298191366** [comment]
字段不支持特殊字符，下个版本特殊字符sql解析之后保存在特殊字符将不允许保存
