### ISSUE TITLE
循环主子表 分页混乱

### ISSUE THREAD

**Issue by cdbmfrcjj** [jeecgboot/JimuReport#2683]
##### 版本号：
1.74

##### 问题描述：
循环主子表 时 按官方文档进行 按页循环,框选到绿色分页线,循环出的结果 打印和导出 时候 分页混乱 

##### 错误日志&截图：
<img width="522" alt="联想截图_20240607133727" src="https://github.com/jeecgboot/JimuReport/assets/71683167/bbf10588-a8e9-4823-b6f4-84abb9b6c0cf">
<img width="870" alt="联想截图_20240607133754" src="https://github.com/jeecgboot/JimuReport/assets/71683167/19377aa3-a963-451e-8507-a07715b67101">
<img width="870" alt="联想截图_20240607133803" src="https://github.com/jeecgboot/JimuReport/assets/71683167/d8a41c02-4df1-483c-9e0e-aac12c0d37a4">
<img width="870" alt="联想截图_20240607133812" src="https://github.com/jeecgboot/JimuReport/assets/71683167/90bae38d-0cb4-4c56-9de9-8302be4332cc">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
cr

**Comment by jeecgos** [comment]
已修复，请等待新版本发布。

**Comment by hoperunChen** [comment]
已修复，请等待新版本发布。
