### ISSUE TITLE
双折线图问题

### ISSUE THREAD

**Issue by LLLLJJJJMMMM** [jeecgboot/JimuReport#2684]
##### 版本号：
1.7.5

##### 问题描述：
点击时会出现额外的一条线
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/101620126/3b73e1dc-dbcb-4bd0-8b5b-3b8e3fdd35b0)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by 1298191366** [comment]
未复现，以下是我测试结果。请提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)及测试数据

https://github.com/jeecgboot/JimuReport/assets/30997828/e4031d21-185a-40a6-bc2a-5c38d935cf2c
