### ISSUE TITLE
字典传参渲染到报表上异常

### ISSUE THREAD

**Issue by weishuaix** [jeecgboot/JimuReport#2688]
##### 版本号：
1.7.52

##### 问题描述：
通过api配置字典编码，页面选择后报表上渲染到的是所有字典的最后一个字典数据，不是对应的参数字典
![image](https://github.com/jeecgboot/JimuReport/assets/38178416/fccd1ebd-7311-4343-a552-ebc6cf793d4a)
![image](https://github.com/jeecgboot/JimuReport/assets/38178416/018c0eb2-7023-47ef-b616-3ae2bce17b21)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by weishuaix** [comment]
报表自带的字典测试也会出现问题

**Comment by zhangdaiscott** [comment]
没明白什么意思

**Comment by weishuaix** [comment]
> 没明白什么意思

就是使用字典参数渲染到报表上面，报表聚合出来的值不是对应字典参数，而是其他字典的值， 假设有 A,B,C三个字典，字典值都有1、2，选的是A字典的1，渲染出来的是是C字典的1的值

**Comment by weishuaix** [comment]
有复现出来吗，下个版本会不会更新啊

**Comment by zhangdaiscott** [comment]
ws

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by weishuaix** [comment]
[收费明细右玉.json](https://github.com/user-attachments/files/16122902/default.json)

**Comment by 1298191366** [comment]
经测试，没有发现你说的问题，我不太清楚你后台怎么写的
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/1145fdf7-a6dc-458a-93aa-9d8aafb220ed)
我后台的写法，目前是写死的，你可以debug你写的代码，看看key值不一样 传过来的字典是不是和你想要的字典是一样的
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/f5e1a8e5-7e15-452b-aef8-6d48d3e58fcf)

**Comment by weishuaix** [comment]
传递CUSTOMER_CUST_TYPE到页面上，然后查询普通客户，应该会渲染出线上缴费这个出来

**Comment by weishuaix** [comment]
@1298191366

**Comment by 1298191366** [comment]
我试试

**Comment by 1298191366** [comment]
你方便的话截个图，我看看，我目前是这样操作的
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/e64ba0a0-07b9-4fad-ae2c-c537855a1b8f)

**Comment by weishuaix** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/38178416/c06c241e-f3e8-4bc9-8a13-a1732b807250)
![image](https://github.com/jeecgboot/JimuReport/assets/38178416/31b8a66d-31c6-4523-ba1a-7ab930d7a70e)

**Comment by weishuaix** [comment]
表格里面内容字典聚合没问题，是字典参数传参有问题
![image](https://github.com/jeecgboot/JimuReport/assets/38178416/fa38125d-bfae-43ab-9a90-d73f1fce65b4)

**Comment by 1298191366** [comment]
奥奥，看见了，我还以为是列表翻译，是有bug

**Comment by weishuaix** [comment]
嗯嗯，比较严重的bug了，望尽快修复

**Comment by 1298191366** [comment]
已修复，待新版本发布
