### ISSUE TITLE
用户预览无法批量复制

### ISSUE THREAD

**Issue by Big-Zeng** [jeecgboot/JimuReport#2690]
##### 版本号：
1.7

##### 问题描述：
用户预览无法批量复制，现在只能双击单元格复制，无法批量复制多个单元格。帆软是可以的。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请图文并茂

**Comment by Big-Zeng** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/37169998/833a3a66-8f57-4948-85e4-92a9c98b24d1)
无法用鼠标一下子框选多个单元格复制。
帆软报表的功能如下，可以鼠标框选复制，然后可以粘贴到其他地方
![image](https://github.com/jeecgboot/JimuReport/assets/37169998/27e82762-343e-4ede-b715-eea67d893593)

**Comment by zhangdaiscott** [comment]
暂时不支持

**Comment by zhangdaiscott** [comment]
先收录到“新需求汇总”中
https://github.com/jeecgboot/JimuReport/issues/138
