### ISSUE TITLE
js增强，目前只发现$http.metaGet的方法，有post的请求方式吗？

### ISSUE THREAD

**Issue by SunYoung06** [jeecgboot/JimuReport#2691]
##### 版本号：
1.7.5

##### 问题描述：
js增强，目前只发现$http.metaGet的方法，有post的请求方式吗？

function init(){
// 加载第1个下拉框数据
$http.**metaPost**('127.0.0.1:8080/a/a').then(res=>{
  let options =  [{value: '001',text: '北京市'},{value: '002',text: '天津市'}];
  this.updateSelectOptions('test', 'branch_name', options)
})
}

不会将options中的内容，加载到branch_name下，

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/3162115/3c07fb95-252e-4484-a2d8-86dcb20c6b78)

 你可以试一下
