### ISSUE TITLE
报表和图表共用 一个查询栏查询api数据集 如何实现

### ISSUE THREAD

**Issue by HJY-666** [jeecgboot/JimuReport#2694]
##### 问题描述：
报表和图表共用 一个查询栏查询api数据集如何实现

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by HJY-666** [comment]
![Uploading c4df751de7cf909073eb23e0edd5f1d9.png…]()

**Comment by HJY-666** [comment]
- 
<img width="983" alt="c4df751de7cf909073eb23e0edd5f1d9" src="https://github.com/jeecgboot/JimuReport/assets/58809237/d797a8f5-ea12-4954-bd9b-44fd46362247">

**Comment by zhangdaiscott** [comment]
参数一样就行
