### ISSUE TITLE
关于dbsum的bug

### ISSUE THREAD

**Issue by 13813586515** [jeecgboot/JimuReport#2695]
##### 版本号：
1.7.52

##### 问题描述：

多列使用dbsum，底部总计出现重复
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/21357134/03901280-14cd-4a64-8a64-a9d45bf232f1)
![image](https://github.com/jeecgboot/JimuReport/assets/21357134/eda67095-008d-4f1c-bd08-bdf78c9948c0)
![image](https://github.com/jeecgboot/JimuReport/assets/21357134/bca5d9ab-f5b2-4514-8c17-43ac71c6b640)

##### 重现步骤：
在多个列中都使用dbsum会出现重复总计行

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 13813586515** [comment]
且重复的行数与当前页数据行数一致

**Comment by 13813586515** [comment]
![Uploading image.png…]()
后台报错提示上

**Comment by 13813586515** [comment]
执行表达式错误:: expression=DBSUM(1), env={ignore=[], DB1=0, JM_EXP_ARG_SIZE=1}, error=Function not found: DBSUM

**Comment by 1298191366** [comment]
请提供报表json，并提供数据 我这复现不出来
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/eb6e987a-70be-40bd-b3df-7b92392f6193)

![image](https://github.com/jeecgboot/JimuReport/assets/30997828/47b52750-c649-4b61-91f5-d878fef0faeb)

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
@13813586515 未复现，请针对问题在官网制作报表示例并提供ID;
![image](https://github.com/user-attachments/assets/df360835-9ed3-46d8-a95b-1f6da88d7fd1)

![image](https://github.com/user-attachments/assets/07400147-4ca8-4582-b7f9-429e6b8ab5ef)

**Comment by zhangdaiscott** [comment]
已修复，下个版本发布
