### ISSUE TITLE
缩放打印图片显示问题

### ISSUE THREAD

**Issue by cdbmfrcjj** [jeecgboot/JimuReport#2697]
##### 版本号：
官网在线版本
##### 问题描述：
缩放打印图片 显示的是图片原始尺寸的一部分，并不缩放，默认打印的话显示正常

##### 错误日志&截图：
缩放打印截图
![482cd0c1a6f7258a14add22207bf945](https://github.com/jeecgboot/JimuReport/assets/71683167/ba5466dc-0d4e-49ff-a7a7-e21cd640e56b)
默认打印截图
![d61f4f77cfc24a197194c7449c46b01](https://github.com/jeecgboot/JimuReport/assets/71683167/7b7f4c03-6a3e-4997-b4ec-ad8d6173f1db)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by liaozhiyang** [comment]
没复现出来，能在[积木报表官网](http://jimureport.com/)做个例子吗？
