### ISSUE TITLE
积木报表打印，预览的时候可以看到完整的图片，打印预览的时候图片则变为破图

### ISSUE THREAD

**Issue by xiaoshuai220** [jeecgboot/JimuReport#2700]
##### 问题描述：
预览的时候可以看到完整的图片，打印预览的时候图片则变为破图

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/53173115/57948ff5-8b33-40f9-a61a-03f33e17f9ae)

##### 重现步骤：
![1718334245740](https://github.com/jeecgboot/JimuReport/assets/53173115/e60079f3-89eb-4021-95bc-264196fbc4d7)
![Uploading 1718334406954.jpg…]()

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请先升级到最新版

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
