### ISSUE TITLE
积木报表不能通过nginx反向代理访问，智能直接访问报表服务器地址

### ISSUE THREAD

**Issue by lr998** [jeecgboot/JimuReport#2701]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/9923953/ad871332-a629-4f40-97c2-13bad6e691a9)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
直接通过后台地址访问
