### ISSUE TITLE
报表下钻的时候，传递过去的参数并未生效，使用的是参数默认值

### ISSUE THREAD

**Issue by Kitsune-Schariac** [jeecgboot/JimuReport#2702]
##### 版本号：
1.5.8

##### 问题描述：
报表下钻时，如果目标报表的参数设置了默认值并勾选查询，则不会使用上游传递过来的值，而是使用默认值，如果取消勾选查询，则会正常使用传递的值

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/57817094/9ce04fcf-d5fc-4473-a34b-98e818449deb)
![image](https://github.com/jeecgboot/JimuReport/assets/57817094/b30c022c-c656-49f8-8015-17f6e7b6068e)

##### 重现步骤：
勾选查询时会使用默认值，取消勾选则会使用传递过来的值

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by zhangdaiscott** [comment]
请先升级到最新版确认是否还存在问题

**Comment by yupeishan** [comment]
> 已修复，待新版本发布

你好  请问这个问题的修复版本发布了嘛，刚刚测试1.7.6有这个问题
