### ISSUE TITLE
Springboot3.3.0+jdk17启动项目后页面访问不到

### ISSUE THREAD

**Issue by liuzb2022** [jeecgboot/JimuReport#2703]
##### 错误日志&截图：
![8d90f2ee3b9daa48acb1ae18c26052e](https://github.com/jeecgboot/JimuReport/assets/101079910/b808d3e7-1ccd-4975-8074-eadbe6ef713a)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
？

**Comment by yang1707** [comment]
这个问题解决了吗?

**Comment by zhangdaiscott** [comment]
好了

**Comment by yang1707** [comment]
需要加什么配置吗?出现同样的问题,版本:
        <dependency>
            <groupId>org.jeecgframework.jimureport</groupId>
            <artifactId>jimureport-spring-boot3-starter-fastjson2</artifactId>
            <version>1.7.8</version>
        </dependency>

**Comment by liuzb2022** [comment]
***@***.***(scanBasePackages = {"org.jeecg.modules.jmreport"})




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月20日(星期二) 中午11:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/JimuReport] Springboot3.3.0+jdk17启动项目后页面访问不到 (Issue #2703)














 
需要加什么配置吗?出现同样的问题,版本:
 
 org.jeecgframework.jimureport
 jimureport-spring-boot3-starter-fastjson2
 1.7.8

**Comment by yang1707** [comment]
@liuzb2022 已解决,感谢
