### ISSUE TITLE
关于1.7.52 分组 数值类型异常问题

### ISSUE THREAD

**Issue by kevin6234** [jeecgboot/JimuReport#2704]
##### 问题描述：
表格进行纵向和横向分组时, 部分数值字段显示异常

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/173050380/829cd1a1-f11c-440c-abed-c4f0b74bce08)

![image](https://github.com/jeecgboot/JimuReport/assets/173050380/b301875e-2c8c-4bd0-a5a1-f49cf31de825)
![image](https://github.com/jeecgboot/JimuReport/assets/173050380/4f5f1b79-3bec-4fc3-acc2-4004d409626b)

##### 重现步骤：
设置表格固定行为纵向分组列,动态行为横向分组列,  设置字段为数值并保留两位小数,  表格值为0的数据展示为0.000000 和 0E-10
有值的字段展示正常

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by hoperunChen** [comment]
@kevin6234 请问，在老版本中是否存在这个问题？

**Comment by hoperunChen** [comment]
已修复，待新版发布

**Comment by kevin6234** [comment]
升级前是1.6.4 不存在该问题


似水流年
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月19日(星期三) 中午11:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 关于1.7.52 分组 数值类型异常问题 (Issue #2704)





 
@kevin6234 请问，在老版本中是否存在这个问题？
