### ISSUE TITLE
v1.7.52合并单元格不生效

### ISSUE THREAD

**Issue by xzk-2023** [jeecgboot/JimuReport#2707]
##### 版本号：
v1.7.52

##### 问题描述：
合并单元格不生效

##### 错误日志&截图：
没有日志报错

##### 重现步骤：
点击合并单元格，单元格没有合并

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
已经发现，会尽快发布新版

**Comment by zhangdaiscott** [comment]
```
<dependency>
   <groupId>org.jeecgframework.jimureport</groupId>
   <artifactId>jimureport-spring-boot-starter</artifactId>
   <version>1.7.6</version>
   <exclusions>
      <exclusion>
         <artifactId>jsqlparser</artifactId>
         <groupId>com.github.jsqlparser</groupId>
      </exclusion>
   </exclusions>
</dependency>
```
