### ISSUE TITLE
关于函数简便操作的优化

### ISSUE THREAD

**Issue by alancess** [jeecgboot/JimuReport#2709]
##### 版本号：
1.7.6

##### 问题描述：

望优化：在使用DBSUM或SUM函数时可直接点选数据集中标签，而非先拖拽至格子中才能点选
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by alancess** [comment]
![0619](https://github.com/jeecgboot/JimuReport/assets/68429490/ad758940-1ce1-4605-aa2d-2acf4ebf867c)

**Comment by zhangdaiscott** [comment]
ws  优化

**Comment by 1298191366** [comment]
已修复，待新版本发布
