### ISSUE TITLE
文件上传大小被限制在哪修改

### ISSUE THREAD

**Issue by 211806349** [jeecgboot/JimuReport#2711]
##### 错误日志&截图：
![8VJQ`IEWH0_Y_$C$MK6690B](https://github.com/jeecgboot/JimuReport/assets/45117200/9a1f04dc-62dc-465e-8e37-8abc76d1ffb1)

![WOBB1XAU~ `T9 W5`TBQ41A](https://github.com/jeecgboot/JimuReport/assets/45117200/383d8270-39af-4e2c-a003-9e205fa6bf78)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
nginx？
