### ISSUE TITLE
报错 权限不足，此功能需要分配角色！

### ISSUE THREAD

**Issue by 250114036** [jeecgboot/JimuReport#2712]
##### 问题描述：
报表设计器中新增数据源测试时，报错“权限不足，此功能需要分配角色！”

##### 错误日志&截图：
![0J36 NWD1G8PLQX5PVIP59A](https://github.com/jeecgboot/JimuReport/assets/41503505/3ff55ac9-6d67-49e0-b018-8654718a9d54)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
看console日志，缺什么角色，分配什么角色，应该是admin
