### ISSUE TITLE
jimureport报表管理界面 眉头上面的 列表和视图切换是否可以默认选择成 列表，或者这一块可以开放出来自行设计

### ISSUE THREAD

**Issue by shixing02** [jeecgboot/JimuReport#2713]
##### 版本号：
V1.7.5

##### 问题描述：
jimureport报表管理界面 眉头上面的 列表和视图切换是否可以默认选择成 列表，或者这一块可以开放出来自行设计

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/148853083/944b118d-d011-412a-a47a-e3cc893c0e6b)

##### 重现步骤：

![jimureport眉头格式设置](https://github.com/jeecgboot/JimuReport/assets/148853083/4941d3f8-1b92-4fc3-b79d-71df8e4a783e)
![jimureport眉头格式设置](https://github.com/jeecgboot/JimuReport/assets/148853083/fd99d19a-9e62-4e99-b5f8-27aec1ea9b50)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws  加缓存配置

**Comment by 1298191366** [comment]
已修复，待新版本发布。
