### ISSUE TITLE
增加增强型js的样例说明

### ISSUE THREAD

**Issue by SunYoung06** [jeecgboot/JimuReport#2714]
##### 版本号：
1.7.4

##### 问题描述：

有几个需求，需要协助是否支持：
1. 需要控制触发查询按钮时，能够对参数进行如必填、正确性的逻辑校验，
目前js的样例，只有对默认值的操作

2. 需要能配置时间控件，如配置时间范围的跨度：
类似选择时间范围跨度不能超过3个月，
选择了开始时间为2024-06-01，结束时间只能选2024-09-01以前的时间
或者选择了结束时间为2024-06-01，开始时间只能选2024-03-01以后的时间

3. 能够选中一个参数，对其样式设置为不可编辑。

上述需求，不管现在有没有实现，
如果已经能实现，希望给一个样例，
如现在还不能实现，希望给一个答复，减少我们的研究时间，

当我尝试在 在线版本把已经研究的js写入时，发现报错了，

只能在这里写入我的js内容，
`function init(){
// 假设时间控件ID为 create_time_start ，发现并不能选中开始时间的控件，是否有其他选择？
setTimeout(() => {
document.getElementsByClassName('ivu-btn-primary')[0].addEventListener('click', function(event) {
if (document.getElementsByClassName('ivu-input ivu-input-default ivu-input-with-suffix')[0]._value == ''){
alert('时间参数必选');
// 这个方法能获取时间为空，并弹出提示窗，但是并不能阻止查询继续，
event.preventDefault();
}
});
}, 1000)
}
`
##### 错误日志&截图：

 操作失败，PreparedStatementCallback; bad SQL grammar [UPDATE jimu_report SET ID = ?, CODE = ?, NAME = ?, TYPE = ?, JSON_STR = ?, CREATE_BY = ?, CREATE_TIME = ?, UPDATE_BY = ?, UPDATE_TIME = ?, DEL_FLAG = ?, TEMPLATE = ?, VIEW_COUNT = ?, PY_STR = ? WHERE id = ?]; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'PY_STR' in 'field list'

##### 重现步骤：
预览地址:  https://bootapi.jeecg.com/jmreport/shareView/958518938592169984?shareToken=36ab8bd6f9afbd2938ad20dca7ee9880 
复制预览地址在浏览器打开

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
目前没有校验逻辑
https://help.jeecg.com/jimureport/query/jsEnhance.html

**Comment by zhangdaiscott** [comment]
看后面的规划

先收录到“需求汇总”中
https://github.com/jeecgboot/JimuReport/issues/138
