### ISSUE TITLE
动态横向动态列数据合计超过35列后的数据合计时都以2倍计算，其它列正常，减少列数就正常。

### ISSUE THREAD

**Issue by scrollsyou** [jeecgboot/JimuReport#2716]
##### 版本号：
1.7.6

##### 问题描述：

动态横向动态列数据合计超过35列后的数据合计时都以2倍计算，其它列正常，减少列数就正常。
##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/7288404/e883b016-7a96-45f8-b088-d814ef3a6675)
![image](https://github.com/jeecgboot/JimuReport/assets/7288404/c4c4cbf3-4706-4408-a810-c64850b219a7)

##### 重现步骤：

目前测试数数据列数不够多是正常的。
当生产数据列数多时，后面的列开始计算合计异常。
![image](https://github.com/jeecgboot/JimuReport/assets/7288404/309bcda0-1290-448b-9f50-1b637adc5bb3)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by scrollsyou** [comment]
[总报表.json](https://github.com/user-attachments/files/15922041/default.json)
这是导出的设计配置

**Comment by jeecgos** [comment]
陈锐

**Comment by jeecgos** [comment]
cr

**Comment by hoperunChen** [comment]
已修复，待新版本发布。
