### ISSUE TITLE
单元格属性设置中，无高级配置下拉框

### ISSUE THREAD

**Issue by ClearSkyChan** [jeecgboot/JimuReport#2718]
##### 版本号：
  <jimureport.version>1.7.6</jimureport.version>
  <java.version>1.8</java.version>
        <minio.version>8.0.3</minio.version>
##### 问题描述：
试用横向纵向组合动态列分组功能时，发现无法将单元格设置为动态属性，选择分组，纵向，没出现高级配置的字段。

##### 错误日志&截图：

<img width="248" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/6889909/c78cf2b4-dbe4-43a6-92a9-8a7883cbda31">

##### 重现步骤：
1、点击单元格
2、右侧分组设置
3、选择纵向
4、**没出现高级配置**

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
cr

**Comment by jeecgos** [comment]
@ClearSkyChan 
* 1.7.52版本后，「高级配置」已经改为：横向分组字段；原高级配置选项分为普通属性和动态属性，现在横向分组字段勾选就代表选中了动态属性
* 只有「数据设置」选中为「列表」时，才可以设置当前单元格为「横向分组字段」
![image](https://github.com/user-attachments/assets/3bb0f4e8-cd1e-4e93-80a7-d8d83d6c4e2b)

**Comment by hoperunChen** [comment]
@ClearSkyChan 
* 1.7.52版本后，「高级配置」已经改为：横向分组字段；原高级配置选项分为普通属性和动态属性，现在横向分组字段勾选就代表选中了动态属性
* 只有「数据设置」选中为「列表」时，才可以设置当前单元格为「横向分组字段」
![image](https://github.com/user-attachments/assets/3bb0f4e8-cd1e-4e93-80a7-d8d83d6c4e2b)
