### ISSUE TITLE
单元格加减乘除计算错误。

### ISSUE THREAD

**Issue by JackieXiangxy** [jeecgboot/JimuReport#2719]
##### 版本号：
1.7.6

##### 问题描述：
单元格加减乘除预算错误。
在设置好单元格加减运算规则后，所有的运算结果都使用第一行的运算信息展示

##### 错误日志&截图：
运算规则设置：
![image](https://github.com/jeecgboot/JimuReport/assets/32051597/d3ce85de-d113-40db-b4f9-4336e6eb6bb0)

运算结果：
![image](https://github.com/jeecgboot/JimuReport/assets/32051597/4c6d2f9c-11ce-440d-ad94-3b01d521bba7)

##### 重现步骤：

配置单元格加减乘除运算，然后直接回填数据展示即可复现该bug

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by JackieXiangxy** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/32051597/21aab52c-b341-4b04-9430-dae051e9e0a3)

**Comment by 2187522075** [comment]
我也同样的问题，你解决了吗

**Comment by JackieXiangxy** [comment]
> 我也同样的问题，你解决了吗

没有解决，系统自带的bug

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
@JackieXiangxy 您好，普通的坐标运算表达式（eg. =E1*E2) 不会随着动态行自适应扩展。您可以使用compute函数来实现动态行运算的需求，具体配置方式如下：
![QQ_1721714514636](https://github.com/user-attachments/assets/dcee407c-6f0b-4a19-956a-9514a9f142ac)
![QQ_1721715027814](https://github.com/user-attachments/assets/105d996b-7962-4ea1-885b-eccbb17771f9)
`#{a.compute(sales-gift)}`：
* `a` : 数据集code。
* `compute`：计算函数名称。
* `sales-gift`：具体的运算，支持加减乘除运算；`sales`和`gift`都是数据集a下的字段。
