### ISSUE TITLE
积木报表的图表在预览中可以支持 大小拉扯 或者 自适应 吗

### ISSUE THREAD

**Issue by HJY-666** [jeecgboot/JimuReport#2720]
##### 版本号：
v1.0

##### 问题描述：
 积木报表的图表在预览中可以支持 大小拉扯 或者 自适应 吗

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/58809237/f82070a1-9735-45d5-85c8-c33cfaeed463)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持，可以使用jeecgboot的仪表盘
