### ISSUE TITLE
报表设计预览拼接租户id但是始终提示没有租户权限

### ISSUE THREAD

**Issue by 17356212005** [jeecgboot/JimuReport#2722]
版本号：v1.7.6

问题描述：报表设计预览拼接租户id但是始终提示没有租户权限
配置了jeecg :
  jmreport:
    #多租户模式，默认值为空(created:按照创建人隔离、tenant:按照租户隔离) (v1.6.2+ 新增)
    saasMode: tenant

 错误日志&截图：
![微信图片_20240621201458](https://github.com/jeecgboot/JimuReport/assets/54160081/8faeb41b-c27b-4050-86e0-54434a93d4ee)

![微信图片_20240621201458](https://github.com/jeecgboot/JimuReport/assets/54160081/820840ae-1e87-4450-84d5-20bba9df5b0a)

重现步骤：

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
未复现，看看你的数据库有没有存租户id,并且header中传的值是否与数据库中的值匹配

请查看 getTenantId是否返回的与数据库中的值是否一样
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/444175bc-3b81-47cb-8138-ae84412ad440)
