### ISSUE TITLE
积木报表如何固定标题行

### ISSUE THREAD

**Issue by chinaanze** [jeecgboot/JimuReport#2724]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by chinaanze** [comment]
版本 1.6   如何实现标题行固定

**Comment by zhangdaiscott** [comment]
最新商业版有冻结功能
![image](https://github.com/jeecgboot/JimuReport/assets/3162115/41ccbdea-86dd-41f7-be7c-c524cbd08fa9)

**Comment by chinaanze** [comment]
@zhangdaiscott    免费版，是无法实现这一功能的吗？
