### ISSUE TITLE
更新1.7.6版本后导出PDF依旧报错

### ISSUE THREAD

**Issue by liqinghe9** [jeecgboot/JimuReport#2729]
##### 错误日志&截图：java.nio.file.InvalidPathException: Trailing char < > at index 12: \opt\upload\ 
![image](https://github.com/jeecgboot/JimuReport/assets/173428450/200de73f-0917-4314-a6eb-7ef242f15c62)

##### 报表配置：
[用能分析报告02 (2).json](https://github.com/user-attachments/files/15952416/02.2.json)

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
