### ISSUE TITLE
使用最新多租户若依框架集成积木报表报错

### ISSUE THREAD

**Issue by sybclannad** [jeecgboot/JimuReport#2731]
##### 错误日志&截图：
Description:

Field dataSourceDao in org.jeecg.modules.jmreport.desreport.service.a.k required a bean of type 'org.jeecg.modules.jmreport.desreport.dao.JimuReportDataSourceDao' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'org.jeecg.modules.jmreport.desreport.dao.JimuReportDataSourceDao' in your configuration.

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
什么架构？

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
你是springboot3集成的吗，你试一下这个版本看看还有没有问题，springboot3分离版和不分离版本应该都没有问题了
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot3-starter-fastjson2</artifactId>
  <version>1.7.8</version>
</dependency>
```
