### ISSUE TITLE
函数拆分数组后怎样设置循环

### ISSUE THREAD

**Issue by 495563129** [jeecgboot/JimuReport#2733]
##### 版本号：
1.7.6

##### 问题描述：
string.split(target,regex,[limit])
该函数，将字符串分割为数组后，怎样将数组类似集合一样一行一行循环啊。

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/48550372/fbac0adf-5a46-43be-8526-a137ba6b21ca)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
暂不支持，归集：#138
