### ISSUE TITLE
单元格设置自动换行后，如何设置行高？

### ISSUE THREAD

**Issue by 495563129** [jeecgboot/JimuReport#2734]
##### 版本号：
1.7.6

##### 问题描述：
单元格设置自动换行后，相设置行高，但不知道应该怎样操作，也尝试过“增强配置”-CSS设置，但是不知道该怎样使用，单元格的Class应该怎样获取啊。

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/48550372/4500252a-acff-4486-9aea-58d72ca4e6d9)

![image](https://github.com/jeecgboot/JimuReport/assets/48550372/9db76f83-d6fc-47f7-a13d-6cd445b616c4)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
暂不支持，归集：#138
