### ISSUE TITLE
积木报表加减乘除怎么实现

### ISSUE THREAD

**Issue by 2187522075** [jeecgboot/JimuReport#2735]
##### 问题描述：问题1：我在积木报表中输入=sum(H4,I4)*2，最终出来的是计算H4*2的值。
问题2：能否实现类似这种的计算：9-K4/MAX($K$4:$K$208)*9+MIN($K$4:$K$208)/MAX($K$4:$K$208)*9+1

##### 错误日志&截图：

![01](https://github.com/jeecgboot/JimuReport/assets/173860926/682261c8-3cbc-4bcf-aa25-c3c94f640b3f)
![02](https://github.com/jeecgboot/JimuReport/assets/173860926/db2d4fcc-b6a5-4e79-8d58-3fc4b0ad9423)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 2187522075** [comment]
星号在刚才的问题中不识别，实际是我输入了*星号

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
@2187522075  您好，`=sum(H4,I4)*2` 这种简单的表达式和运算混合的情况再新版本将支持，请等待新版本发布。
![QQ_1721821037633](https://github.com/user-attachments/assets/8c33f044-5e62-47f9-acc6-7b2473878221)

如 `9-K4/MAX($K$4:$K$208)*9+MIN($K$4:$K$208)/MAX($K$4:$K$208)*9+1` 这样的多函数混合运算表达式暂时还不支持。归集：#138
