### ISSUE TITLE
API接口解析传参类型是否可以是集合类型

### ISSUE THREAD

**Issue by superman4808** [jeecgboot/JimuReport#2736]
##### 版本号：
V1.6.3

##### 问题描述：
API接口解析传参类型是否可以是集合类型

##### 错误日志&截图：
![1](https://github.com/jeecgboot/JimuReport/assets/121927607/d0a6d724-c440-401b-aa02-7cb30b0f4888)
![2](https://github.com/jeecgboot/JimuReport/assets/121927607/4052a3b6-ba1b-4a20-b944-bdf20742afa1)

##### 重现步骤：
[报表配置.zip](https://github.com/user-attachments/files/15981994/default.zip)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
默认规则
