### ISSUE TITLE
浏览器窗口标题

### ISSUE THREAD

**Issue by hdthhh** [jeecgboot/JimuReport#2737]
##### 问题描述：
这个浏览器窗口标题能改吗，在哪改

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/100888871/768c3ea9-a522-469b-ac2e-30f15eb93bf2)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by hdthhh** [comment]
能问一下为什么关闭了吗

**Comment by dapengchen12** [comment]
我也想问这个问题，这个title不能改吗？？
