### ISSUE TITLE
大屏设计器 表格组件问题

### ISSUE THREAD

**Issue by MewMew945** [jeecgboot/JimuReport#2738]
##### 问题描述：
  大屏设计器里面的表格组件，当文本太长时会导致整一行的内容出框

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/108110960/354327e7-24b1-4c4a-8a02-167b4b9ff806)

##### 重现步骤：
使用表格组件，然后固定表格宽度，在表格的输入较长的字段

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
已修改，下版本发布

**Comment by wpqiu** [comment]
> 已修改，下版本发布

请问现在修复了吗
