### ISSUE TITLE
排序异常

### ISSUE THREAD

**Issue by 12341234-yangboran** [jeecgboot/JimuReport#2739]
##### 版本号：
1.7.6

##### 问题描述：
sql server数据库配置sql数据集，在sql中设置了order by。在报表预览中进行查询时会出现两个排序字段

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/74187378/1eaa29c9-8682-4e42-bfd8-385f638a2848)

##### 重现步骤：
SELECT
	m.fbillno,
	s.cinvname,
	c.ccusname,
	m.fbilldate,
	s.fqty
FROM
	[dbo].[KF_MaterialOutStoreM_D] as m
	LEFT JOIN [dbo].[KF_MaterialOutStoreS_D] as s ON m.fbillno = s.fbillno
	LEFT JOIN [dbo].[t_ClientInfo_B] as c ON m.clientcode = c.ccuscode 
WHERE
	m.FBillType = 'Out002' order by ccusname desc

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
未复现，请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
使用和您一样的查询sql：
![image](https://github.com/jeecgboot/JimuReport/assets/13013558/769e1d72-3d71-41fe-b08e-37abfad05b8d)
在预览时使用ccusname字段查询
![image](https://github.com/jeecgboot/JimuReport/assets/13013558/5a2e63c6-e94d-4e32-8657-46dc96066c0d)
![image](https://github.com/jeecgboot/JimuReport/assets/13013558/bfd9b550-33ff-4ed8-a665-aeea8790a63b)

**Comment by hoperunChen** [comment]
已修复，请等待新版本发布。
