### ISSUE TITLE
报表中内嵌入 hm.js 导致 局域网访问卡顿。严重影像业务体验。

### ISSUE THREAD

**Issue by mfdking** [jeecgboot/JimuReport#2742]
##### 版本号：
1.7.6

##### 问题描述：

在局域网内访问时，总会去访问 hm.js （经过查询，是百度统计）。这个在广域网上没有问题，在局域网使用时，
严重影响 用户体验。等待几十秒，这个链接统计失败，才继续出数据。
##### 错误日志&截图：
只是由于有这个，导致访问慢。我看了开源的，和商业的都是这样。

##### 重现步骤：
那个报表都有这个问题。
建议：广域网可以生效，局域网别统计了，统计不上数据，还影像业务体验。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
未复现，百度那个已经做成异步的了，即使在局域网应该也不会影响页面的渲染
