### ISSUE TITLE
1.7.4免安装版没有跟随分组扩列

### ISSUE THREAD

**Issue by Dalay71** [jeecgboot/JimuReport#2743]
##### 版本号：

1.7.4免安装版

##### 错误日志&截图：
![BA5C7CAD28E134BF076A48525F1453B7](https://github.com/jeecgboot/JimuReport/assets/94943662/34606cd4-93c6-4645-a117-9762200ba14b)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
免安装版本已经更新到最新版
