### ISSUE TITLE
导出的数据格式化不生效

### ISSUE THREAD

**Issue by 13813586515** [jeecgboot/JimuReport#2744]
##### 版本号：
1.7.6

##### 问题描述：
1.数值类型，保留两位小数，界面是显示了2为，但是导出的数据没有保留2为
2.双击2位小数的单元格，会使格式化失效
##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/21357134/d1081005-57c3-4dec-b168-1f4c4d82b4d9)
![image](https://github.com/jeecgboot/JimuReport/assets/21357134/3fc9b8c3-85b7-4c22-9d55-be00890415fc)

##### 重现步骤：
1.格式化数据保留2位
2.点击导出

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
zy

请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by 13813586515** [comment]
[返店会员贡献度.json](https://github.com/user-attachments/files/16023128/default.json)
DROP TABLE IF EXISTS `report_member_return_store_sum`;
CREATE TABLE `report_member_return_store_sum`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `sucess_date` date NOT NULL COMMENT '日期',
  `dept_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '门店编号',
  `level_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '等级编号',
  `dept_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '门店名称',
  `guide_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '导购编号',
  `guide_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '导购名称',
  `comuse_cnt` int(11) NULL DEFAULT NULL COMMENT '消费人数',
  `consume_r_cnt` int(11) NULL DEFAULT NULL COMMENT '返店消费人数',
  `pay_price` decimal(10, 2) NULL DEFAULT NULL COMMENT '消费金额',
  `return_pay_price` decimal(10, 2) NULL DEFAULT NULL COMMENT '返店消费金额',
  `last_regist_cnt` decimal(11, 0) NULL DEFAULT NULL COMMENT '去年注册并且返店消费人数',
  `last_regist_return_price` decimal(10, 2) NULL DEFAULT NULL COMMENT '去年注册并且返店消费金额',
  `new_cust_cnt` int(11) NULL DEFAULT NULL COMMENT '新客消费人数',
  `new_cust_pay_price` decimal(10, 2) NULL DEFAULT NULL COMMENT '新客消费金额',
  `sleep_cust_cnt` int(11) NULL DEFAULT NULL COMMENT '沉睡会员消费人数',
  `sleep_cust_price` decimal(10, 2) NULL DEFAULT NULL COMMENT '沉睡会员消费金额',
  `loss_cust_cnt` int(11) NULL DEFAULT NULL COMMENT '流失会员消费人数',
  `loss_cust_price` decimal(10, 2) NULL DEFAULT NULL COMMENT '流失会员消费金额',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint(20) NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`, `tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 90209 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '返店会员消费' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of report_member_return_store_sum
-- ----------------------------
INSERT INTO `report_member_return_store_sum` VALUES (71358, '2023-01-13', 'L00010', 'VIP1', '常州百货大楼', '101615', '栾燕婷', 1, 0, 4900.00, 0.00, 0, 0.00, 0, 0.00, 1, 4900.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71359, '2023-01-13', 'L00011', 'VIP3', '常州购物中心', '101121', '陈妹', 1, 0, 875.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71360, '2023-01-13', 'L00011', 'VIP4', '常州购物中心', '102261', '吴苏贤', 2, 0, 8792.00, 0.00, 0, 0.00, 0, 0.00, 1, 6166.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71361, '2023-01-13', 'L00012', 'VIP1', '常州购物中心ONE店', '100184', '靳岭', 1, 0, 1935.00, 0.00, 0, 0.00, 0, 0.00, 1, 1935.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71362, '2023-01-13', 'L00012', 'VIP2', '常州购物中心ONE店', '100184', '靳岭', 1, 0, 11910.00, 0.00, 0, 0.00, 1, 11910.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71363, '2023-01-13', 'L00012', 'VIP2', '常州购物中心ONE店', '100215', '毛芳', 1, 0, 8926.00, 0.00, 0, 0.00, 1, 8926.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71364, '2023-01-13', 'L00012', 'VIP4', '常州购物中心ONE店', '100215', '毛芳', 1, 0, 9390.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71365, '2023-01-13', 'L00013', 'VIP1', '常州新世纪', '100189', '张春秀', 1, 0, 4925.00, 0.00, 0, 0.00, 1, 4925.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71366, '2023-01-13', 'L00013', 'VIP1', '常州新世纪', '100192', '严雪', 1, 0, 2875.00, 0.00, 0, 0.00, 1, 2875.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71367, '2023-01-13', 'L00013', 'VIP2', '常州新世纪', '100192', '严雪', 2, 0, 3638.00, 0.00, 0, 0.00, 1, 675.00, 1, 2963.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71368, '2023-01-13', 'L00017', 'VIP4', '成都群光百货', '100408', '陈慧', 1, 0, 8583.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71369, '2023-01-13', 'L00018', 'VIP2', '成都王府井', '101367', '邓丽均', 1, 0, 6000.00, 0.00, 0, 0.00, 1, 6000.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71370, '2023-01-13', 'L00018', 'VIP1', '成都王府井', '101770', '唐玫佳', 1, 0, 1750.00, 0.00, 0, 0.00, 1, 1750.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71371, '2023-01-13', 'L00018', 'VIP3', '成都王府井', '101770', '唐玫佳', 1, 0, 4175.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71372, '2023-01-13', 'L00023', 'VIP4', '福州东百', '100302', '陈润香', 1, 0, 4388.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71373, '2023-01-13', 'L00023', 'VIP3', '福州东百', '101243', '吴锦晶', 1, 0, 3325.00, 0.00, 0, 0.00, 0, 0.00, 1, 3325.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71374, '2023-01-13', 'L00028', 'VIP1', '贵阳荔星名店', '101978', '葛玉梅', 1, 0, 1050.00, 0.00, 0, 0.00, 0, 0.00, 1, 1050.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71375, '2023-01-13', 'L00030', 'VIP1', '杭州大厦', '101957', '刘煜', 1, 0, 2115.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71376, '2023-01-13', 'L00032', 'VIP1', '湖州浙北', '101376', '董美丽', 1, 0, 5588.00, 0.00, 0, 0.00, 0, 0.00, 1, 5588.00, 1, 5588.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71377, '2023-01-13', 'L00032', 'VIP2', '湖州浙北', '101376', '董美丽', 2, 0, 11988.00, 0.00, 0, 0.00, 0, 0.00, 2, 11988.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71378, '2023-01-13', 'L00032', 'VIP3', '湖州浙北', '102906', '刘佳佳', 1, 0, 2975.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71379, '2023-01-13', 'L00032', 'VIP4', '湖州浙北', '102906', '刘佳佳', 1, 0, 8333.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71380, '2023-01-13', 'L00034', 'VIP4', '济南恒隆', '100114', '王培培', 1, 0, 11388.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71381, '2023-01-13', 'L00034', 'VIP1', '济南恒隆', '100121', '郝素琴', 1, 0, 3705.00, 0.00, 0, 0.00, 0, 0.00, 1, 3705.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71382, '2023-01-13', 'L00034', 'VIP1', '济南恒隆', '101620', '李宁', 1, 0, 70.00, 0.00, 0, 0.00, 0, 0.00, 1, 70.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71383, '2023-01-13', 'L00034', 'VIP1', '济南恒隆', '102786', '李倩', 4, 0, 5852.00, 0.00, 0, 0.00, 3, 5740.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71384, '2023-01-13', 'L00042', 'VIP4', '洛阳丹尼斯', '101424', '刘静', 1, 0, 4320.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71385, '2023-01-13', 'L00042', 'VIP1', '洛阳丹尼斯', '102919', '闫小霞', 2, 0, 1888.00, 0.00, 0, 0.00, 0, 0.00, 1, 875.00, 1, 875.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71386, '2023-01-13', 'L00049', 'VIP1', '青岛佳世客', '100128', '董美丽', 2, 0, 2609.00, 0.00, 0, 0.00, 2, 2609.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71387, '2023-01-13', 'L00049', 'VIP2', '青岛佳世客', '100947', '郝冬梅', 1, 0, 2970.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71388, '2023-01-13', 'L00050', 'VIP1', '青岛台东利群', '102377', '黄宝霞', 1, 0, 2438.00, 0.00, 0, 0.00, 1, 2438.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71389, '2023-01-13', 'L00052', 'VIP3', '日照银座', '102429', '林灵', 1, 0, 687.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71390, '2023-01-13', 'L00054', 'VIP3', '厦门盛名来雅', '100299', '黄丽卿', 1, 0, 7326.00, 0.00, 0, 0.00, 0, 0.00, 1, 7326.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71391, '2023-01-13', 'L00054', 'VIP2', '厦门盛名来雅', '102035', '简凤英', 1, 0, 3563.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71392, '2023-01-13', 'L00054', 'VIP4', '厦门盛名来雅', '102035', '简凤英', 1, 0, -775.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71393, '2023-01-13', 'L00054', 'VIP4', '厦门盛名来雅', '102381', '林锦烘', 2, 0, 1100.00, 0.00, 0, 0.00, 0, 0.00, 1, 813.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71394, '2023-01-13', 'L00055', 'VIP1', '上海八佰伴', '100227', '徐欢欢', 1, 0, 3250.00, 0.00, 0, 0.00, 0, 0.00, 1, 3250.00, 1, 3250.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71395, '2023-01-13', 'L00055', 'VIP2', '上海八佰伴', '100227', '徐欢欢', 1, 0, 4750.00, 0.00, 0, 0.00, 1, 4750.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71396, '2023-01-13', 'L00055', 'VIP3', '上海八佰伴', '100227', '徐欢欢', 1, 0, 3500.00, 0.00, 0, 0.00, 0, 0.00, 1, 3500.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71397, '2023-01-13', 'L00055', 'VIP2', '上海八佰伴', '102850', '詹婷婷', 1, 0, 14700.00, 0.00, 0, 0.00, 1, 14700.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71398, '2023-01-13', 'L00055', 'VIP3', '上海八佰伴', '102850', '詹婷婷', 1, 0, 3750.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71399, '2023-01-13', 'L00055', 'VIP4', '上海八佰伴', '102850', '詹婷婷', 1, 0, 150.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71400, '2023-01-13', 'L00061', 'VIP4', '上海龙之梦', '100167', '杨新川', 1, 0, 2306.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71401, '2023-01-13', 'L00064', 'VIP4', '上海南京路新世界', '100165', '陈玉美', 1, 0, 4525.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71402, '2023-01-13', 'L00067', 'VIP1', '上海又一城购物中心', '100170', '尤会玲', 1, 0, 9000.00, 0.00, 0, 0.00, 0, 0.00, 1, 9000.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71403, '2023-01-13', 'L00067', 'VIP3', '上海又一城购物中心', '100170', '尤会玲', 1, 0, 11000.00, 0.00, 0, 0.00, 0, 0.00, 1, 11000.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71404, '2023-01-13', 'L00067', 'VIP4', '上海又一城购物中心', '100170', '尤会玲', 1, 0, 9000.00, 0.00, 0, 0.00, 0, 0.00, 1, 9000.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71405, '2023-01-13', 'L00067', 'VIP2', '上海又一城购物中心', '101419', '万丽', 1, 0, 11000.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71406, '2023-01-13', 'L00067', 'VIP4', '上海又一城购物中心', '101419', '万丽', 2, 0, 20000.00, 0.00, 0, 0.00, 0, 0.00, 2, 20000.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71407, '2023-01-13', 'L00070', 'VIP1', '深圳茂业东门店', '101159', '林丽银', 1, 0, 5750.00, 0.00, 0, 0.00, 1, 5750.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71408, '2023-01-13', 'L00070', 'VIP2', '深圳茂业东门店', '102680', '陈建华', 1, 0, 2150.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71409, '2023-01-13', 'L00071', 'VIP1', '深圳茂业华强店', '100329', '陈爱娟', 1, 0, 1750.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71410, '2023-01-13', 'L00071', 'VIP2', '深圳茂业华强店', '100329', '陈爱娟', 1, 0, 875.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71411, '2023-01-13', 'L00071', 'VIP4', '深圳茂业华强店', '100329', '陈爱娟', 2, 0, 6088.00, 0.00, 0, 0.00, 0, 0.00, 1, 5013.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71412, '2023-01-13', 'L00071', 'VIP1', '深圳茂业华强店', '102266', '黄汉玲', 1, 0, 1125.00, 0.00, 0, 0.00, 0, 0.00, 1, 1125.00, 1, 1125.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71413, '2023-01-13', 'L00071', 'VIP3', '深圳茂业华强店', '102266', '黄汉玲', 2, 0, 4013.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71414, '2023-01-13', 'L00075', 'VIP2', '石家庄先天下广场', '102790', '王卫卫', 1, 0, 1025.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71415, '2023-01-13', 'L00075', 'VIP3', '石家庄先天下广场', '102790', '王卫卫', 1, 0, 7815.00, 0.00, 0, 0.00, 0, 0.00, 1, 7815.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71416, '2023-01-13', 'L00077', 'VIP3', '苏州美罗', '100181', '钱芳', 1, 0, 4950.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71417, '2023-01-13', 'L00077', 'VIP1', '苏州美罗', '100195', '冯明华', 1, 0, -4250.00, 0.00, 0, 0.00, 1, -4250.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71418, '2023-01-13', 'L00078', 'VIP2', '苏州美罗新区店', '100185', '张艳艳', 2, 0, 13050.00, 0.00, 0, 0.00, 1, 6350.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71419, '2023-01-13', 'L00078', 'VIP3', '苏州美罗新区店', '101791', '郭秀', 1, 0, 1100.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71420, '2023-01-13', 'L00079', 'VIP1', '苏州石路', '102992', '崔丽娜', 1, 0, 1750.00, 0.00, 0, 0.00, 0, 0.00, 1, 1750.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71421, '2023-01-13', 'L00086', 'VIP4', '无锡商业大厦', '102551', '史玉琼', 2, 0, 51600.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71422, '2023-01-13', 'L00089', 'VIP1', '武汉国际广场', '102271', '姜明', 1, 0, 1650.00, 0.00, 0, 0.00, 1, 1650.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71423, '2023-01-13', 'L00091', 'VIP1', '武汉群光', '101929', '胡菲菲', 1, 0, 4125.00, 0.00, 0, 0.00, 0, 0.00, 1, 4125.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71424, '2023-01-13', 'L00092', 'VIP1', '西安钟楼专卖店', '101108', '芦蓓蓓', 1, 0, 390.00, 0.00, 0, 0.00, 1, 390.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71425, '2023-01-13', 'L00092', 'VIP4', '西安钟楼专卖店', '101108', '芦蓓蓓', 1, 0, 3848.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71426, '2023-01-13', 'L00100', 'VIP4', '郑州丹尼斯', '100349', '王小婉', 1, 0, 1050.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71427, '2023-01-13', 'L00106', 'VIP3', '重庆世纪新都', '102004', '陶星亚', 2, 0, 6251.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71428, '2023-01-13', 'L00106', 'VIP3', '重庆世纪新都', '102692', '张青丽', 1, 0, 2125.00, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71429, '2023-01-13', 'L00106', 'VIP4', '重庆世纪新都', '102692', '张青丽', 1, 0, 1875.00, 0.00, 0, 0.00, 0, 0.00, 1, 1875.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);
INSERT INTO `report_member_return_store_sum` VALUES (71430, '2023-01-13', 'L00111', 'VIP1', '成都奥特莱斯特卖', '102119', '向燕', 1, 0, 1410.00, 0.00, 0, 0.00, 1, 1410.00, 0, 0.00, 0, 0.00, 'etl', '2024-06-14 10:48:08', 'etl', '2024-06-14 10:48:08', b'0', 607);

**Comment by hoperunChen** [comment]
「1.数值类型，保留两位小数，界面是显示了2位，但是导出的数据没有保留2位」： 已修复，待新版本发布。
「2.双击2位小数的单元格，会使格式化失效」：双击展示原始数据，点击其他单元格恢复正常，这个没有问题；目前就是这样设计的。
