### ISSUE TITLE
分组功能异常

### ISSUE THREAD

**Issue by 12341234-yangboran** [jeecgboot/JimuReport#2746]
##### 问题描述：
sql server数据库，多表连接配置数据报表。
积木报表运行的sql比配置的sql多字段，多出的字段没有带表别名，产生异常。

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/74187378/22ad08db-fc0d-4151-a94a-118d35da1e85)

##### 重现步骤：
配置sql
SELECT
	s.FSupplyName,
	s.FMaterial,
	s.FQty,
	m.FBillDate 
FROM
	HAJX_KF_MaterialInStoreM_D as m
	LEFT JOIN HAJX_KF_MaterialInStoreS_D as s ON m.FBillNo = s.FBillNo

积木报表执行sql
SELECT TOP
	10 FSupplyName,
	FMaterial,
	FQty,
	FBillDate 
FROM
	(
	SELECT
		ROW_NUMBER ( ) OVER ( ORDER BY ROW_ALIAS_1 ) PAGE_ROW_NUMBER,
		FSupplyName,
		FMaterial,
		FQty,
		FBillDate 
	FROM
		(
		SELECT
			s.FSupplyName,
			s.FMaterial,
			s.FQty,
			m.FBillDate,
			fsupplyname AS ROW_ALIAS_1 
		FROM
			HAJX_KF_MaterialInStoreM_D AS m
			LEFT JOIN HAJX_KF_MaterialInStoreS_D AS s ON m.FBillNo = s.FBillNo 
		) AS PAGE_TABLE_ALIAS 
	) AS PAGE_TABLE_ALIAS 
WHERE
	PAGE_ROW_NUMBER > 0 
ORDER BY
	PAGE_ROW_NUMBER

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 12341234-yangboran** [comment]
能解决吗

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
未复现，我这里没有多出来的字段`fsupplyname`，你看看是不是其他数据集里面的,没有加上别名
数据集：
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/82aebfef-a9bc-49cc-858c-ac835ec7bca4)
报表sql拼接的：
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/183f9af0-e395-4fb7-a153-40a8beed539c)
sqlserver 版本号
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/90e353de-674f-40a3-9452-de373a734f3d)

**Comment by hoperunChen** [comment]
已修复，请等待新版本发布。
