### ISSUE TITLE
1.7.6 下拉框动态日期回显报表上报错

### ISSUE THREAD

**Issue by Dalay71** [jeecgboot/JimuReport#2747]
##### 版本号：
1.7.6
##### 问题描述：
='会计期间:'+'${param.acc_period_begin}'+'至'+'${param.acc_period_end}'
##### 错误日志&截图：
![微信截图_20240628160848](https://github.com/jeecgboot/JimuReport/assets/94943662/02373719-2a52-4894-b7a5-406944721bd3)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
描述太简单
