### ISSUE TITLE
多表关联sql查询条件中少了and关键字

### ISSUE THREAD

**Issue by 250114036** [jeecgboot/JimuReport#2748]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/41503505/7b0ed391-7b5b-4d12-854a-255edd5ec85b)

PreparedStatementCallback; bad SQL grammar [SELECT sum(actual_payable) askey from ( select ggp.name as area, gp.name as district, p.name as building, n.name as unit, h.household_number, r.name as resident_name, hc.cost_name, h.house_type, h.heat_area, hc.unit_price, hc.actual_payable, t.actual_amount, t.channel_code, t.pay_method, t.pay_date, su.nickname, t.remark from t_charge t left join t_charge_cost tcc on t.id = tcc.charge_id left join household_cost hc on tcc.cost_id = hc.id left join household_resident r on t.house_id = r.house_id left join household_house h on h.`id` = t.`house_id` left join t_region n on n.`id` = h.`district_id` left join t_region p on n.`parent_id` = p.`id` left join t_region gp on p.`parent_id` = gp.`id` left join t_region ggp on gp.`parent_id` = ggp.`id` left join system_users su on su.id = t.updater where t.`tenant_id` = ? order by t.pay_date desc )jeecg_rp_temp where 1=1 district like ?]; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'district like '%a%'' at line 1

where 1=1 district like ? 中少了 and
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 250114036** [comment]
后发现是合计函数有问题，去掉就不报错了   =DBSUM(daySelect.actual_amount)

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by zhangdaiscott** [comment]
cr

**Comment by 1298191366** [comment]
未复现，请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

>sql解析页面：

![image](https://github.com/user-attachments/assets/7b4622ce-3473-4d1d-a76a-b3d4379e8c15)
>设计页面：

![image](https://github.com/user-attachments/assets/d3e91b7d-a706-4dbe-b669-58f43819916d)

> 预览页面

![image](https://github.com/user-attachments/assets/463e4250-6e69-458f-aa02-e8ddc4835fe4)
