### ISSUE TITLE
多表关联sql分组，数据库表中有重复字段作为分组条件时，生成的查询不会按表区分，报错

### ISSUE THREAD

**Issue by 12341234-yangboran** [jeecgboot/JimuReport#2751]
##### 版本号：
1.7.6

##### 问题描述：
多表关联sql分组，数据库表中有重复字段作为分组条件时，生成的查询不会按表区分，报错

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/74187378/30cec49d-e838-4ca2-ae0e-09c862a164f3)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
cr

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by hoperunChen** [comment]
已修复，请等待新版本发布。
