### ISSUE TITLE
自定义函数不能动态获取单元格内容

### ISSUE THREAD

**Issue by sjqit** [jeecgboot/JimuReport#2752]
##### 版本号：
1.6.6

##### 问题描述：
自定义函数只能获取B4一个单元格的值，不能获取一整列的值，应该为B4到动态列的最后一行啊。。。

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/167081020/2d2a54de-b3c6-460b-9928-1e2d3514e1f5)
![image](https://github.com/jeecgboot/JimuReport/assets/167081020/bfc52ecf-59b3-4fc7-9304-331c9fa7b7d3)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by weishuaix** [comment]
可能得试一下::B4

**Comment by sjqit** [comment]
也不好用啊

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
自定义报表函数已支持动态行的聚合计算，下一个版本更新。

**Comment by PHP-Snake** [comment]
> 自定义报表函数已支持动态行的聚合计算，下一个版本更新。 文档：https://ojrjjvdr7z.k.topthink.com/jimureport/function/custom.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8A%A5%E8%A1%A8%E5%87%BD%E6%95%B0%E6%94%AF%E6%8C%81%E5%8A%A8%E6%80%81%E8%A1%8C%E7%9A%84%E8%81%9A%E5%90%88%E8%AE%A1%E7%AE%97

预计什么时候释放此版本
