### ISSUE TITLE
sql解析异常

### ISSUE THREAD

**Issue by JackieXiangxy** [jeecgboot/JimuReport#2753]
##### 版本号：
1.7.6

##### 问题描述：
sql解析异常。输入的sql可以正确执行，但是输入后解析出来的slq有异常，导致执行失败

##### 错误日志&截图：
正确的输入
![image](https://github.com/jeecgboot/JimuReport/assets/32051597/ceda911f-ae20-4e98-ab7b-80178bca1f0c)

![image](https://github.com/jeecgboot/JimuReport/assets/32051597/96d594cd-7d93-43b4-b149-b70c9d74843d)

解析结果
![image](https://github.com/jeecgboot/JimuReport/assets/32051597/f734df1a-9d01-49e9-8329-996624f46067)

##### 重现步骤：

让测试按照上面截图中的写法写一个slq来测试。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by JackieXiangxy** [comment]
把顺序反过来写又能解析出来。真的是被你们这些bug打败了

![image](https://github.com/jeecgboot/JimuReport/assets/32051597/d4d452f7-8d7d-4b53-9cdb-94a9c3795a01)


![image](https://github.com/jeecgboot/JimuReport/assets/32051597/2e671c8c-6bcd-46d1-8f0a-b58f5c88babf)

**Comment by JackieXiangxy** [comment]
上面给出的截图中还有另外一个解析的bug。让你研发同学自己去看一下在哪里。找不到就在下面留言

**Comment by zhangdaiscott** [comment]
提供原始SQL

**Comment by 1298191366** [comment]
已修复，带新版本发布
