### ISSUE TITLE
单纯想开个issue吐槽一下你们系统的bug。能不能让测试好好测试一下每个迭代。有些基本的功能都有问题啊，而且有些问题不同版本还不兼容

### ISSUE THREAD

**Issue by JackieXiangxy** [jeecgboot/JimuReport#2754]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
有问题欢迎提issue
