### ISSUE TITLE
是否能对mybatis-plus进行升级？

### ISSUE THREAD

**Issue by run65536** [jeecgboot/JimuReport#2755]

**Comment by zhangdaiscott** [comment]
排除jsqlparser

```

<dependency>
   <groupId>org.jeecgframework.jimureport</groupId>
   <artifactId>jimureport-spring-boot-starter</artifactId>
   <version>1.7.6</version>
   <exclusions>
      <exclusion>
         <artifactId>jsqlparser</artifactId>
         <groupId>com.github.jsqlparser</groupId>
      </exclusion>
   </exclusions>
</dependency>

```

**Comment by run65536** [comment]
1、我使用的mybatis-plus版本为3.5.7
2、pom.xml中已经排除了jsqlparser和druid
pom.xml配置信息：
<groupId>org.jeecgframework.jimureport</groupId>
   <artifactId>jimureport-spring-boot-starter</artifactId>
   <version>1.7.52</version>
   <exclusions>
      <exclusion>
         <artifactId>druid</artifactId>
         <groupId>com.alibaba</groupId>
      </exclusion>
      <exclusion>
         <artifactId>jsqlparser</artifactId>
         <groupId>com.github.jsqlparser</groupId>
      </exclusion>
   </exclusions>
项目一直启动不起来，但将mybatis-plus降版本为3.5.2，项目启动正常。
以下是项目报错信息部分内容：
ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'testRpSpringBean': Unsatisfied dependency expressed through field 'dictService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jimuDictServiceImpl': Unsatisfied dependency expressed through field 'reportDictDao'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.jeecg.modules.jmreport.desreport.dao.JimuReportDictDao' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: ***@***.***(required=true)}
Related cause: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jimuReportDao' defined in URL
----- 原始邮件 -----
发件人：JEECG ***@***.***>
收件人：jeecgboot/JimuReport ***@***.***>
抄送人：复东 ***@***.***>,  Author ***@***.***>
主题：Re:_[jeecgboot/JimuReport]_是否能对mybatis-plus进行升级？_(Issue_#2755)
日期：2024年07月02日 13点49分


排除jsqlparser

<dependency>
   <groupId>org.jeecgframework.jimureport</groupId>
   <artifactId>jimureport-spring-boot-starter</artifactId>
   <version>1.7.6</version>
   <exclusions>
      <exclusion>
         <artifactId>jsqlparser</artifactId>
         <groupId>com.github.jsqlparser</groupId>
      </exclusion>
   </exclusions>
</dependency>

**Comment by zhangdaiscott** [comment]
我们不能随便升级，兼容老版本也是很重要的
等吧，看我们后面的升级计划。。。
