### ISSUE TITLE
固定打印表头，表头上包含了图片，导出的pdf第二页表头就没有图片了

### ISSUE THREAD

**Issue by hungxiaocai123456** [jeecgboot/JimuReport#2756]
##### 问题描述：
固定打印表头，表头上包含了图片，导出的pdf第二页表头就没有图片了

##### 错误日志&截图：
<img width="591" alt="74603af94ecc948f4c17fcb9268623e" src="https://github.com/jeecgboot/JimuReport/assets/61574119/001acba2-7e0e-4a02-9107-5e88709f229a">

<img width="604" alt="a4a2a6a70e32556bec1f66fb08fb602" src="https://github.com/jeecgboot/JimuReport/assets/61574119/5cb00f22-9876-441d-989a-2f060f06a68e">

##### 重现步骤：
<img width="523" alt="0050ee845020247e6150f91c99d66ac" src="https://github.com/jeecgboot/JimuReport/assets/61574119/90714133-f0f8-420a-8e50-1aa9cac6a04a">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
