### ISSUE TITLE
导出的pdf文件目前缺少-当前页码/总页数

### ISSUE THREAD

**Issue by hungxiaocai123456** [jeecgboot/JimuReport#2757]
##### 问题描述：
导出的pdf文件目前缺少-当前页码/总页数

##### 错误日志&截图：
<img width="511" alt="1719906458579" src="https://github.com/jeecgboot/JimuReport/assets/61574119/9c6b75d9-e5c2-4f3c-87c9-5b7c1a735dc0">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
下个版本发布此功能
