### ISSUE TITLE
1.7.6三级联动方法文档不全

### ISSUE THREAD

**Issue by Dalay71** [jeecgboot/JimuReport#2758]
##### 版本号：

1.7.6
##### 问题描述：
三级联动方法文档不全以及有其他方法实现？

##### 错误日志&截图：

![微信截图_20240702160852](https://github.com/jeecgboot/JimuReport/assets/94943662/69fe6bf3-90da-45c5-a977-a65464ea3bed)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by Dalay71** [comment]
中国人说中国话

**Comment by 1298191366** [comment]
文档已更新，[api参考示例](https://help.jeecg.com/jimureport/query/jsEnhance.html#12-%E8%AE%BE%E8%AE%A1%E6%AD%A5%E9%AA%A4)
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/af76770c-f9f6-4603-aa20-f0647746aad0)
