### ISSUE TITLE
更新邮箱的依赖以更好的适配spring3

### ISSUE THREAD

**Issue by gitskybo** [jeecgboot/JimuReport#2760]
##### 版本号：
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot3-starter-fastjson2</artifactId>
    <version>1.7.32</version>
##### 问题描述：
 spring3 里面使用的邮件依赖还是javax。请更新邮箱的依赖以更好的适配spring3

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/57713058/6c9ba5d7-f11f-4f5b-a149-14117592f64d)

##### 重现步骤：
请更新邮箱的依赖以更好的适配spring3

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
更换成什么？

**Comment by zhangdaiscott** [comment]
springboot3版本
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot3-starter-fastjson2</artifactId>
  <version>1.7.8</version>
</dependency>
```
