### ISSUE TITLE
若依框架的springboot3+jdk21,启动报错

### ISSUE THREAD

**Issue by jacky8466** [jeecgboot/JimuReport#2761]
##### 版本号：
jimureport-spring-boot3-starter-fastjson2
1.7.32

##### 问题描述：
启动报错：
`Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'saasModeSecurityUtil': Unsatisfied dependency expressed through field 'jimuReportService': Error creating bean with name 'jimuReportServiceImpl': Unsatisfied dependency expressed through field 'jmReportDbSourceService': Error creating bean with name 'jmReportDbSourceServiceImpl': Unsatisfied dependency expressed through field 'dataSourceDao': No qualifying bean of type 'org.jeecg.modules.jmreport.desreport.dao.JimuReportDataSourceDao' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}`
Related cause: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jimuReportShareDao' defined in URL [jar:file:/E:/repo/org/jeecgframework/jimureport/jimureport-spring-boot3-starter-fastjson2/1.7.32/jimureport-spring-b

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/11418894/06ac4096-4301-4eae-803f-244f04b38a51)
![image](https://github.com/jeecgboot/JimuReport/assets/11418894/c60bb454-ed78-40a3-8070-00e854b13510)

##### 重现步骤：
若依框架里的springboot3版本

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
扫码路径配置了吗

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/jimureport/projectJoin/ruoyi.html

**Comment by jacky8466** [comment]
> 扫码路径配置了吗

肯定配了哦，之前的版本是springboot2 现在是升级到springboot3了，不过用的是mybatis-plus,在springboot2中是能正常访问的

**Comment by jacky8466** [comment]
我的依赖包版本信息
`<properties>
        <tyzn.version>4.3.0</tyzn.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>21</java.version>
        <maven-jar-plugin.version>3.3.0</maven-jar-plugin.version>
        <shiro.version>2.0.1</shiro.version>
        <mybatis-spring-boot.version>3.0.3</mybatis-spring-boot.version>
        <thymeleaf.extras.shiro.version>2.1.0</thymeleaf.extras.shiro.version>
        <druid.version>1.2.23</druid.version>
        <bitwalker.version>1.21</bitwalker.version>
        <kaptcha.version>2.3.3</kaptcha.version>
        <pagehelper.boot.version>2.1.0</pagehelper.boot.version>
        <fastjson.version>2.0.51</fastjson.version>
        <oshi.version>6.6.1</oshi.version>
        
        <commons.io.version>2.11.0</commons.io.version>
        <poi-ooxml.version>4.1.2</poi-ooxml.version>
        <poi.version>4.1.2</poi.version>
        
        
        <velocity.version>2.3</velocity.version>
        <myexcel.version>3.12.1</myexcel.version>
        <lombok.version>1.18.32</lombok.version>
        <mybatisplus.version>3.5.7</mybatisplus.version>
        <hutool.version>5.8.29</hutool.version>
        <jwt.version>0.12.5</jwt.version>
        <guava.version>33.2.1-jre</guava.version>
        <pinyin4j.version>2.5.1</pinyin4j.version>
        <jimureport.version>1.7.32</jimureport.version>
        <spring-boot.version>3.3.1</spring-boot.version>
    </properties>`

**Comment by zhangdaiscott** [comment]
你把minidao排除了，minidao版本换成 下面的版本试试
```
<dependency>
  <groupId>org.jeecgframework.boot3</groupId>
  <artifactId>minidao-pe</artifactId>
  <version>1.10.1</version>
</dependency>
```

**Comment by jacky8466** [comment]
> 你把minidao排除了，minidao版本换成 下面的版本试试
> 
> ```
> <dependency>
>   <groupId>org.jeecgframework.boot3</groupId>
>   <artifactId>minidao-pe</artifactId>
>   <version>1.10.1</version>
> </dependency>
> ```

> 你把minidao排除了，minidao版本换成 下面的版本试试
> 
> ```
> <dependency>
>   <groupId>org.jeecgframework.boot3</groupId>
>   <artifactId>minidao-pe</artifactId>
>   <version>1.10.1</version>
> </dependency>
> ```

加上这个启动不报错了，前台页面显示正常，单后台有异常日志，虽然不是可以忽略，单看着难受：
`请求地址'/jmreport/desreport_/cdn/axios/axios.min.map',发生系统异常.
org.springframework.web.servlet.resource.NoResourceFoundException: No static resource cdn/axios/axios.min.map.

**Comment by zhangdaiscott** [comment]
截图

**Comment by zhangdaiscott** [comment]
集成依赖
springboot2版本
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.7.8</version>
</dependency>
```
springboot3版本
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot3-starter-fastjson2</artifactId>
  <version>1.7.8</version>
</dependency>
```

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
经测试，集成1.7.8应该就没有问题了，[文档](https://k1vz8d3vxr.x.topthink.com/preview/projectJoin/ruoyi.html#3pom%E4%B8%AD%E5%BC%95%E5%85%A5%E7%A7%AF%E6%9C%A8%E6%8A%A5%E8%A1%A8%E6%9C%80%E6%96%B0%E4%BE%9D%E8%B5%96)
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot3-starter-fastjson2</artifactId>
  <version>1.7.8</version>
</dependency>
```
