### ISSUE TITLE
期望报表在对某个字段进行分组后，可以在某个分组后加一行或N行固定行

### ISSUE THREAD

**Issue by caijiya** [jeecgboot/JimuReport#2762]
##### 版本号：
<jimureport-spring-boot-starter.version>1.6.6</jimureport-spring-boot-starter.version>

##### 问题描述：
期望报表在对某个字段进行分组后，可以在某个分组后加一行或N行固定行

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/33491141/84743b19-0511-4983-a313-6d4dbf58c904)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by caijiya** [comment]
感觉这是个基础功能，但是没找到类似的配置方式

**Comment by jeecgos** [comment]
暂不支持，归集：#138
