### ISSUE TITLE
系统变量传递参数识别没有‘’

### ISSUE THREAD

**Issue by weishuaix** [jeecgboot/JimuReport#2763]
##### 版本号：
1.7.6

##### 问题描述：
mysql系统变量后面条件需要用‘’引起来,不然会执行失败

##### 错误日志&截图：

![image](https://github.com/jeecgboot/JimuReport/assets/38178416/fb3a3e0f-7a38-4671-9ded-8205bcd7c032)
![Uploading image.png…]()

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
sql怎么配置的

**Comment by weishuaix** [comment]
sql上面有
![image](https://github.com/jeecgboot/JimuReport/assets/38178416/6a31a7df-0be9-45cd-8e73-56273c8b4f7f)

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by weishuaix** [comment]
[维修任务明细.json](https://github.com/user-attachments/files/16097453/default.json)

**Comment by 1298191366** [comment]
经测试，未发现该问题，如有其他疑问请再次回复
测试步骤：
后台自定义系统变量，当前步骤设置字符串或者数值类型均可
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/c8f075e0-ed78-4af5-ac0b-566eefbe9f2b)
sql解析页面用的是你的模板
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/401edfad-bd12-4dcf-aae0-f34874143b7f)
后台解析成功示意图
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/c2784b4c-03e6-4fea-a0d1-b04cb4cfa355)
经排查 你这个里面没有加单引号
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/ae3ea93e-ff5f-485e-bd97-e48863a38abc)
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/ff6a6a58-5c70-408e-a5da-b81fbf9af6fc)
