### ISSUE TITLE
sql解析异常

### ISSUE THREAD

**Issue by JackieXiangxy** [jeecgboot/JimuReport#2764]
##### 版本号：
1.7.6

##### 问题描述：
当在where条件手动拼接1=1时，后台在解析sql时，会把动态条件也替换成1=1，导致sql执行报错。
![image](https://github.com/jeecgboot/JimuReport/assets/32051597/77ae538e-3c39-4f83-8ae1-497eed9900e1)

where后面的动态查询条件不要简单粗暴换成1=1。在进行替换的时候做一下判断是否已经有条件了

##### 错误日志&截图：
原始sql
![image](https://github.com/jeecgboot/JimuReport/assets/32051597/cb086499-8c47-49ec-882f-0f51ece9bd61)
![image](https://github.com/jeecgboot/JimuReport/assets/32051597/69438ae2-9ccb-4037-bc3f-8e163b415c45)

解析后的结果

![image](https://github.com/jeecgboot/JimuReport/assets/32051597/b5f92ad6-9948-4775-94d4-7db4e5d9c9b8)

一点小建议：很多情况下报表都是执行比较复杂的slq，希望能将sql执行引擎优化一下，目前存在的问题确实有点多

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你用的是那种模式？

**Comment by JackieXiangxy** [comment]
> 你用的是那种模式？

配置好sql后点击解析按钮

![image](https://github.com/jeecgboot/JimuReport/assets/32051597/aa27b4a8-0ff5-47c6-b259-3b30f4164606)

**Comment by 1298191366** [comment]
已修复，待新版本发布。后续需要你自行填写1=1
