### ISSUE TITLE
带查询条件报错

### ISSUE THREAD

**Issue by a1141188324** [jeecgboot/JimuReport#2766]
##### 版本号：
1.7.6

##### 问题描述：
分享报表地址不带查询条件可以正常查询，带上了接口就报错，并没有日志

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/54978087/245be92e-b9f7-4573-996f-86bdd69bf561)

##### 重现步骤：
分享后一开始可以正常访问，后面就不行了，是不是shareToken问题

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
分享有效期多久？

**Comment by zhangdaiscott** [comment]
ws

**Comment by a1141188324** [comment]
已经解决了 是token的问题  线上会自动带上若依pro的token 但是是过期的 重新登录就报错   本地就不会有这样的问题
