### ISSUE TITLE
关于compute计算的问题

### ISSUE THREAD

**Issue by cycmars** [jeecgboot/JimuReport#2767]
##### 版本号：
1.7.6

##### 问题描述：
1、动态数据源用compute进行除法计算，设置保留4位小数，显示正常，但是导出的excel小数位数没有保留4位；
2、动态数据源用compute进行除法计算，设置保留4位小数，显示格式设置成百分比，小数数位不生效；

##### 错误日志&截图：
![H4YA`TNTE}BIXIA%X(CD131](https://github.com/jeecgboot/JimuReport/assets/3795499/5ad1da6e-9fcc-4f2b-8c48-a1e402f1468e)

excel导出：
![EV}G }@JOSV2ARVJ@P9V$F](https://github.com/jeecgboot/JimuReport/assets/3795499/93351d8b-eee1-4357-a74c-e7c4a52906ef)

百分比格式问题：
![5L6KW6R0{J06@B5X7GTWFXH](https://github.com/jeecgboot/JimuReport/assets/3795499/5095eec2-0eb0-4009-b40e-5158c83b4b59)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
未复现
「动态数据源用compute进行除法计算，设置保留4位小数，显示正常，但是导出的excel小数位数没有保留4位」
![image](https://github.com/user-attachments/assets/a20e656c-af1f-4aca-a05e-8421ef9d912c)
「动态数据源用compute进行除法计算，设置保留4位小数，显示格式设置成百分比」
![image](https://github.com/user-attachments/assets/f28684b8-f654-46d0-a2f6-c5986b70b325)

您可以先**升级到最新版本**试一下还有没有问题,如果还是不行，烦请**在官网制作报表示例并提供ID**;
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.7.9</version>
</dependency>
```

#2693

**Comment by cycmars** [comment]
> 未复现 「动态数据源用compute进行除法计算，设置保留4位小数，显示正常，但是导出的excel小数位数没有保留4位」 ![image](https://private-user-images.githubusercontent.com/162332873/348204967-a20e656c-af1f-4aca-a05e-8421ef9d912c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExODY0NTEsIm5iZiI6MTcyMTE4NjE1MSwicGF0aCI6Ii8xNjIzMzI4NzMvMzQ4MjA0OTY3LWEyMGU2NTZjLWFmMWYtNGFjYS1hMDVlLTg0MjFlZjlkOTEyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QwMzE1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hM2I3MWFkNjJmMmNkMWRkODM5ZmJmODJlOTUyZDQ2NDQ3ODY5NDkzY2UzNDJhOGRhMjM3NGIzZGM4ZTE0MmUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lQiBKTXpYio83ZK8VZ_MM85c1YYhLZszJlDo6OZzK4A) 「动态数据源用compute进行除法计算，设置保留4位小数，显示格式设置成百分比」 ![image](https://private-user-images.githubusercontent.com/162332873/348205258-f28684b8-f654-46d0-a2f6-c5986b70b325.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExODY0NTEsIm5iZiI6MTcyMTE4NjE1MSwicGF0aCI6Ii8xNjIzMzI4NzMvMzQ4MjA1MjU4LWYyODY4NGI4LWY2NTQtNDZkMC1hMmY2LWM1OTg2YjcwYjMyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QwMzE1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTU2MDJlMjdlNjk0YjNjMmQxOTRmY2FhYTFiZjA0YmVhMDllZWRiMGFlOGFiNTUyOTNhMGY2OGRiNzliMGNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t-9S2kj34yXHl3F_pCD8qb2uKDhgrXQptZc3gHXf8YU)
> 
> 您可以先**升级到最新版本**试一下还有没有问题,如果还是不行，烦请**在官网制作报表示例并提供ID**;
> 
> ```
> <dependency>
>   <groupId>org.jeecgframework.jimureport</groupId>
>   <artifactId>jimureport-spring-boot-starter</artifactId>
>   <version>1.7.9</version>
> </dependency>
> ```
> 
> #2693

升级到1.7.9问题依然存在，你导出excel看一下字段数据
**预览界面：**
**导出excel：**

**Comment by hoperunChen** [comment]
已修复，下一个版本发布。
