### ISSUE TITLE
api数据，生成的pdf出来数据会跳页

### ISSUE THREAD

**Issue by xuniyis** [jeecgboot/JimuReport#2769]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/121145973/5e1f3cc4-128d-430d-8c8d-3d095655985f)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by xuniyis** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/121145973/ba8a481a-b40d-4a7a-af1c-766c0f6e3123)
找到了，自动换行的问题   没办法兼容吗
