### ISSUE TITLE
单元格计算错误

### ISSUE THREAD

**Issue by liuhuiwenllfy** [jeecgboot/JimuReport#2773]
##### 版本号：
1.7.6

##### 问题描述：
两个计算出的单元格再次进行计算问题
计算错误，正常应该是D51/B51的结果，但是现在计算出的结果和上一行结果一样

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/38151121/3e9fabb6-75db-4c9f-a049-75f3027bb259)
![image](https://github.com/jeecgboot/JimuReport/assets/38151121/e38e2977-3f40-442f-a202-c22c3bf35363)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by hoperunChen** [comment]
看下动态cell表达式是否能满足你的需求： https://help.jeecg.com/jimureport/function/dynamiCell.html
