### ISSUE TITLE
柱状图数据过多时x轴非常密集

### ISSUE THREAD

**Issue by bc152** [jeecgboot/JimuReport#2774]
##### 问题描述：
柱状图数据过多是x轴非常密集

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/81397216/beeaac9a-fab9-415b-81ae-a6f74a2aba0e)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已优化，待新版本发布，后续您可以设置显示x轴前几条，再配合查询条件进行筛选

![image](https://github.com/user-attachments/assets/a98e70c3-9e7d-47b7-9152-9ababe905c4c)
