### ISSUE TITLE
大屏设计器-地图类组件-->离线地图-->气泡标注地图

### ISSUE THREAD

**Issue by git1121410979** [jeecgboot/JimuReport#2775]
##### 问题描述：使用积木报表中的大屏设计器，使用地图类组件-->离线地图-->气泡标注地图
开启了地图钻取功能，官方文档上面没有钻取地图的示例数据，官方文档的示例数据只有省份数据，省份下以及市区下的数据格式需要怎样的
比如点进去河南省，郑州市的数据、漯河市的数据如何展示，这个数据格式官方文档没有说明

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/52737643/1cfbf335-1383-423d-ac27-421d71dadf29)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
已修改
