### ISSUE TITLE
循环块设置是否支持采购订单主子表

### ISSUE THREAD

**Issue by qdcheche** [jeecgboot/JimuReport#2776]
##### 问题描述：

官方的循环块设置是员工档案卡，一页只打印一条，比如我查询出1号的5个采购订单，是否支持按照采购订单主表循环，
一个单子打印到一张，每个订单的明细条数不一定几条。
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
未按格式要求发帖，会被直接删掉;
