### ISSUE TITLE
关于SQL数据源count(1)语句导致的性能优化建议

### ISSUE THREAD

**Issue by Aaden-Bluce** [jeecgboot/JimuReport#2779]
##### 版本号：
1.6.6

##### 问题描述：
关于SQL数据源count(1)语句导致的性能问题，导致报表打开时间翻倍

##### 错误日志&截图：
打印的日志如下：
```
[org.springframework.jdbc.core.JdbcTemplate ]: Executing SQL query [SELECT COUNT(1) total FROM ( SELECT XXX FROM table ) temp_count]
[org.springframework.jdbc.core.JdbcTemplate ]: Executing SQL query [SELECT XXX FROM table ]
```

##### 重现步骤：
![image](https://github.com/jeecgboot/JimuReport/assets/173425803/03348469-71f9-4149-ad8b-9ec6db322629)
在SQL数据集中，是否集合，是否分页，这两个选项无论怎么选，jimureport都会自动增加count(1)语句，这会导致额外的性能开销。
如果确实需要分页，确实用的上，就我个人来说报表绝大多数都是统计类并不需要分页，建议优化这个逻辑。
比如：勾选分页才查询count，或者自定义选择是否查询count，自定义count()语句，默认的嵌套查询确实太慢了。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
先收录到“新需求汇总”中
https://github.com/jeecgboot/JimuReport/issues/138
