### ISSUE TITLE
1.7.6+ 纵向分组小计显示位置问题

### ISSUE THREAD

**Issue by yupeishan** [jeecgboot/JimuReport#2780]
##### 版本号：
**1.7.6**
升级**1.7.8**后也有此问题

##### 问题描述：
[关于这个文档里的分组小计问题](https://help.jeecg.com/jimureport/combination/subtotalSubtotal.html)
我完全按照文档中进行的配置，但是最后出来的分组小计显示位置却和文档中不一致
##### 错误日志&截图：
如图 文档中将 **省份** 设置为分组依据 捐赠及销量设置为动态计算列  最终显示的分组小计应在城市下方进行汇总
![1](https://github.com/jeecgboot/JimuReport/assets/104750701/d7309d1b-16d3-4f3d-bd60-24f79266ac8d)

但是我根据文档操作后  将 **省份** 设置为分组依据  地区城市为分组字段，销量，赠送为动态列  月份为横向分组
![3](https://github.com/jeecgboot/JimuReport/assets/104750701/05fb16ad-05cd-4592-ba9f-e8604266cbda)
最终显示的小计如下图，
![2](https://github.com/jeecgboot/JimuReport/assets/104750701/37bcf354-017b-4a24-afc6-01307a4caf35)

最终显示的效果与文档中示例5类似，示例5中将 **省份** 的分组依据设置为否 **地区** 的分组依据设置为是 ，
### ***也就是说文档中合计显示在分组依据的后一个字段下，但是本地测试实际操作后发现会显示在分组依据以及后一个字段下，包括了分组依据他本身***

而如果将城市设置为分组依据 则会得到以下结果
![4](https://github.com/jeecgboot/JimuReport/assets/104750701/0444fde3-46f5-4f31-8938-87e3b1d231ca)

##### 重现步骤：
[根据此文档步骤操作即可](https://help.jeecg.com/jimureport/combination/subtotalSubtotal.html)

**Comment by huagelong** [comment]
同问

**Comment by zhangdaiscott** [comment]
cr

**Comment by jeecgos** [comment]
@yupeishan @huagelong

**Comment by hoperunChen** [comment]
@yupeishan @huagelong 
在`1.7.0`之前的版本中，分组小计将在「分组依据」的后一列展示；这会导致：
1. 最后一个分组字段的分组小计将没有地方展示
2. 并不符合用户的使用习惯和直觉；


所以，在1.7.0版本后，纵向分组小计的小计字段会与「分组依据」列保持在一列，如下：

![image](https://github.com/user-attachments/assets/1b882571-1dab-4335-903e-8314d927bc0b)
