### ISSUE TITLE
一个表，最后一行多列用DBSUM 合计时，速度很慢，能否优化一下

### ISSUE THREAD

**Issue by cosolar** [jeecgboot/JimuReport#2781]
##### 版本号：
1.7.8

##### 问题描述：
一个表，最后一行多列用DBSUM 合计时，速度很慢，能不优化一下
=DBSUM(db.xx)
语法： =DBSUM(数据集编码.数据集字段)
返回值：指定数据集指定字段，对该字段所有数据求和
对比SUM函数区别：DBSUM统计数据集所有数据，SUM只支持当前页数据

**Comment by zhangdaiscott** [comment]
DBSUM走的是数据库的合计，而且是全量数据，如果你数据量大，数据库查询慢，这个不是我们程序能解决的
