### ISSUE TITLE
积木报表升级1.7.6版本后sql报错

### ISSUE THREAD

**Issue by lizhao13070** [jeecgboot/JimuReport#2783]
##### 问题描述：
之前用的是1.5.6版本,在1.5.6版本中设置单元格三位小数不会补零,所以升级到1.7.6,升级之后报表sql解析报错

##### 错误日志&截图：
报表sql:
with temp_rq as(
select to_date('${NF}'||'-'||'${YF}'||'-1','yyyy-mm-dd')+rownum-2 as rq from dual
connect by rownum<= extract(day from last_day(to_date('${NF}'||'-'||'${YF}'||'-1','yyyy-mm-dd')))),
temp_data as(
select trunc(start_time) rq, start_time,nvl(qrl,0) as qrl,nvl(xzqds,bcqds) as bcqds
from jl_data_lxgs
where start_time>=to_date('${NF}'||'-'||'${YF}'||'-1'||' 06:00:00','yyyy-mm-dd hh24:mi:ss')-1 
and start_time<add_months(to_date('${NF}'||'-'||'${YF}'||'-1'||' 06:00:00','yyyy-mm-dd hh24:mi:ss'),1)-1
and mydw='${MYDW}'
and materiel='${WLID}'
and bwh='${BID}')

select to_char(t1.rq,'yyyy-mm-dd') as xh,qrl,bcqds
 from temp_rq t1 left join temp_data t2 on t1.rq=t2.rq 
UNION ALL
SELECT '合计',sum(qrl) AS qrl,NULL FROM temp_data
错误日志截图:
![51d7a30f6c9229a000eaf770856776f](https://github.com/jeecgboot/JimuReport/assets/63038008/c8198605-12b4-4594-99ed-6cf104b69678)
![微信图片_20240710101902](https://github.com/jeecgboot/JimuReport/assets/63038008/a15e8e14-cd4f-49c4-8a32-94b7855c664b)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by 1298191366** [comment]
未复现，请提供原sql,或者填写一下默认值试一试
![image](https://github.com/user-attachments/assets/4001ec29-2d04-4714-bb27-ae73b6d03832)
