### ISSUE TITLE
jimureport-spring-boot-starter开源了吗? 我想改前端logo之类的内容

### ISSUE THREAD

**Issue by Jason8080** [jeecgboot/JimuReport#2784]
##### 版本号：
最新版

##### 问题描述：
我想改前端logo之类的内容

##### 错误日志&截图：
无

##### 重现步骤：
无

**Comment by zhangdaiscott** [comment]
开源协议：`功能永久免费、可以商用、代码不开放（大屏不提供离线版,在线免费使用）`
