### ISSUE TITLE
1.7.6+ 线上发布模式下使用图表时报【当前积木平台模式为，发布模式不允许使用在线配置！！】

### ISSUE THREAD

**Issue by yupeishan** [jeecgboot/JimuReport#2785]
##### 版本号：
**1.7.6  1.7.8**

##### 问题描述：
线上配置如下， 当lowCodeMode = prod 时进行线上部署，使用普通账号(非admin，非lowdeveloper)进行查看预览，会出现提示信息
**当前积木平台模式为，发布模式不允许使用在线配置！！**，经过多次测试后发现只有当有图表配置时才会出现此提示信息，其他普通表格报表则不会
![3](https://github.com/jeecgboot/JimuReport/assets/104750701/8e063843-b219-4d2c-b4cb-fd41868919dd)

##### 错误日志&截图：
![1](https://github.com/jeecgboot/JimuReport/assets/104750701/3cc147b6-c16d-45fe-8e8f-76414b319c4b)
![2](https://github.com/jeecgboot/JimuReport/assets/104750701/9c0475b5-32b9-48cc-ac41-6d24cf616823)

报错接口为 /jmreport/qurestSql  去掉图表后则不再出现
![4](https://github.com/jeecgboot/JimuReport/assets/104750701/289bf8fc-4521-4f63-89e3-274f7aa8f69c)

##### 重现步骤：
1.新建任意报表  
2.插入图表，折线图，饼图均可，配置SQL数据集
3.使用普通角色账号进行查看

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/3162115/6e83d53f-3c34-46c3-aa81-20c496bdd454)
改这个参数

**Comment by yupeishan** [comment]
> ![image](https://private-user-images.githubusercontent.com/3162115/347295983-6e83d53f-3c34-46c3-aa81-20c496bdd454.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1OTU5MDQsIm5iZiI6MTcyMDU5NTYwNCwicGF0aCI6Ii8zMTYyMTE1LzM0NzI5NTk4My02ZTgzZDUzZi0zYzM0LTQ2YzMtYWE4MS0yMGM0OTZiZGQ0NTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTBUMDcxMzI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjczNzRlYWEyN2YzYTI5Y2YwNzZlMGUzMDgzN2QxMzNmNTI1Mzk3NGE2YmM1ZGFhODc4N2JkNjlmZTQ3ODM4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mUXhxVu-0pkLpIVgcZNDjq_EhPYKM3uV68YaD35nAfE) 改这个参数

改成dev吗？  确实能解决   但是这样的话线上prod安全模式不就没意义了吗

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/3162115/3016155e-88c7-4073-a951-70f4ad166d68)

**Comment by yupeishan** [comment]
> ![image](https://private-user-images.githubusercontent.com/3162115/347303624-3016155e-88c7-4073-a951-70f4ad166d68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDU2MzcsIm5iZiI6MTcyMDYwNTMzNywicGF0aCI6Ii8zMTYyMTE1LzM0NzMwMzYyNC0zMDE2MTU1ZS04OGM3LTQwNzMtYTk1MS03MGY0YWQxNjZkNjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTBUMDk1NTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWI5ODQ1MGU4ZGQyMjIwM2E2MGU5ZjkyODU5OWExZGQyZWZhYzQzNGYyNjFhZWM1ZTNjMWJmYjYyNzAzMDNlNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0mmvcjIlp33_R2VrQ5UrQa_-U46X8iSm1Tuj7_NM6fA)

我还是有点不太理解，现在不是设计的问题，admin账号查看和实际都是完全没问题的，现在的问题是开启了prod模式，线上admin设计完报表后，其他普通用户去查看时会报这个问题，

**Comment by zhangdaiscott** [comment]
图裂
