### ISSUE TITLE
我用docker部署，用api数据源，怎么在报表设计里设计文字上面盖章的效果，盖章的图片url从api传

### ISSUE THREAD

**Issue by eiweorerw** [jeecgboot/JimuReport#2786]
##### 问题描述：
怎么在报表设计里设计文字上面盖章的效果，盖章的图片url从api传，章要盖在文字上面，作为背景，图片不能修改，放在单元格里图片以后，文字又没办法展示，求解决方案

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
水印效果？

**Comment by eiweorerw** [comment]
类似，就是我要打印的报表下面在文字上面有个盖章，可以实现吗

**Comment by zhangdaiscott** [comment]
目前没

**Comment by zhangdaiscott** [comment]
套打算类似的功能，可以看看

**Comment by zhangdaiscott** [comment]
看后面的规划

先收录到“需求汇总”中
https://github.com/jeecgboot/JimuReport/issues/138
