### ISSUE TITLE
积木报表1.7.32版本分享后不能打开连接

### ISSUE THREAD

**Issue by 15900346784** [jeecgboot/JimuReport#2787]
##### 版本号：
1.7.32

##### 问题描述：
分享后不能打开连接

##### 错误日志&截图：
![360截图20240711183215669](https://github.com/jeecgboot/JimuReport/assets/175300183/398485a6-ce33-4d70-ae0c-70bf8b2d0847)

##### 重现步骤：
分享报表 永久分享 无密码 打不开链接

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
?

**Comment by zhangdaiscott** [comment]
升级到最新版看看

**Comment by zhangdaiscott** [comment]
ws
