### ISSUE TITLE
主子循环块，抛出【Size must be greater than 0】报错

### ISSUE THREAD

**Issue by gouchanghong** [jeecgboot/JimuReport#2788]
##### 版本号：
1.7.8

##### 问题描述：
按照官方文档设置主子循环块后，会产生一个【Size must be greater than 0】的报错，导致报表无法展示。
而只要取消这个循环块，报表就能正常打开。再次设置又会出现同样的错误。再次取消又能正常打开。
并且，测试过接口数据，主数据以及每一个子数据，都是有值的

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/5113132/f34cbf05-6f45-4a5b-87f6-2c1021f124fb)
![image](https://github.com/jeecgboot/JimuReport/assets/5113132/3399c1c3-6b5a-4e01-a186-578be7511653)
![image](https://github.com/jeecgboot/JimuReport/assets/5113132/41855efe-f514-43ee-be4c-33ddfe72e96a)
![image](https://github.com/jeecgboot/JimuReport/assets/5113132/2eb83a5f-8ca9-479f-993f-cb24ab4e16a9)
![image](https://github.com/jeecgboot/JimuReport/assets/5113132/e30a9e38-22e8-4b0c-aaaf-c424f4d791ff)
![image](https://github.com/jeecgboot/JimuReport/assets/5113132/99894192-4984-42f2-9dd2-5d809b29dc9f)

取消后：
![image](https://github.com/jeecgboot/JimuReport/assets/5113132/82cb045c-7957-457d-a616-a7289657b284)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by jeecgos** [comment]
cr

**Comment by hoperunChen** [comment]
已修复，请等待新版本发布。
另外，主子循环块的子表扩展空间是从循环块的最底部开始向上找空行来补上去的。最多不会超过循环块的范围。您的设计需要调整一下：
![image](https://github.com/user-attachments/assets/4f6b28be-d010-46ab-b2f3-dac515288d74)

**Comment by gouchanghong** [comment]
> 已修复，请等待新版本发布。 另外，主子循环块的子表扩展空间是从循环块的最底部开始向上找空行来补上去的。最多不会超过循环块的范围。您的设计需要调整一下： ![image](https://private-user-images.githubusercontent.com/13013558/349492040-4f6b28be-d010-46ab-b2f3-dac515288d74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNjU1MjEsIm5iZiI6MTcyMTI2NTIyMSwicGF0aCI6Ii8xMzAxMzU1OC8zNDk0OTIwNDAtNGY2YjI4YmUtZDAxMC00NmFiLWIyZjMtZGFjNTE1Mjg4ZDc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDAxMTM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwOGU3MTI5YzZkNTY1ZWI5ZDZiNjcwYTYyZTM0ZjVmMGMwMDVhZDA2NDE4ZTI0NjZiZDc5MjhhN2QyNDExZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T8jTkLz-ZP35YPM9MMAEyXIfLzZiraHvFAMxO_n4eUk)

非常感谢
