### ISSUE TITLE
报表单元格组合后 右侧数据列展现不正常

### ISSUE THREAD

**Issue by ssss0205** [jeecgboot/JimuReport#2789]
##### 版本号：
1.7.8
##### 问题描述：
固定名称组合单元格，右侧两个列表信息 。展现表格时数据出现覆盖及空白行。
##### 错误日志&截图：
![8M8$~AJ~H%E7U0 E9EKJA7T](https://github.com/user-attachments/assets/dca01c31-0bb0-4338-b545-0409b4e169a6)
![6Q1ILKYWY`JUM1%RJ)4{@HM](https://github.com/user-attachments/assets/86013f91-b65f-49e1-aaa9-2185f2c41c0d)

##### 重现步骤：
固定名称组合单元格，右侧两个列表信息 。展现表格时数据出现覆盖及空白行。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID

**Comment by ssss0205** [comment]
https://bootapi.jeecg.com/jmreport/index/975286151495897088
975286151495897088

**Comment by ssss0205** [comment]
![微信截图_20240722171636](https://github.com/user-attachments/assets/11586a47-c4b9-4151-87ce-9d02ae3ed8f2)
![微信截图_20240722171728](https://github.com/user-attachments/assets/de5c4aa1-979d-4d31-a4ad-756cac4ba23f)
@zhangdaiscott

**Comment by jeecgos** [comment]
cr

**Comment by jeecgos** [comment]
暂不支持多列表的合并单元格，归集：#138
