### ISSUE TITLE
我用docker部署，用api数据源，要用下拉单选可搜索组件进行查询，但是下拉列表的数据我要从api获取

### ISSUE THREAD

**Issue by eiweorerw** [jeecgboot/JimuReport#2790]
##### 问题描述：
我用docker部署，用api数据源，要用下拉多选可搜索组件进行查询，但是下拉列表的数据我要从api获取，并且下拉列表需要可搜索，我在数据源里直接配置字典编号为我的数据api，结果生成的搜索框是普通输入框，也没有请求我的接口，然后用自定义下拉框，又不能搜索，我看到说可以用数据字典，但是新建了字典以后，点击字典配置没有反应，console里有js报错，
![微信截图_20240715154456](https://github.com/user-attachments/assets/8f28bd47-ca72-4576-b264-190d70476d54)
我应该怎么做才能实现这个功能

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by eiweorerw** [comment]
![1212](https://github.com/user-attachments/assets/2f048caf-9075-427c-8cb4-3354522cb5ef)
![324](https://github.com/user-attachments/assets/66298bc8-a0ce-4997-8d11-1593b327b653)

**Comment by eiweorerw** [comment]
![image](https://github.com/user-attachments/assets/0c998797-2a18-4a11-8c30-27668943156f)
我用这个配置实现了要的功能，但是这个api接口里需要传一个请求的参数值，这个值在api数据集的api地址里可以用，
![image](https://github.com/user-attachments/assets/bf85ca61-49a6-4a78-9ca2-3746924c894b)
但是在字段的字典编码的url里不能用，我如果在字典编码里要传我的参数怎么办，文档里只有系统变量，我用docker安装的能不能把传过来的参数设置为系统变量，或者有其他实现方式

**Comment by 1298191366** [comment]
目前字典api不支持传参数，你可以自己配置系统变量，通过实现`getUserInfo`方法
参考文档：[系统标量](https://help.jeecg.com/jimureport/config/sysVariable.html#%E5%A6%82%E4%BD%95%E8%87%AA%E5%AE%9A%E4%B9%89%E7%B3%BB%E7%BB%9F%E5%8F%98%E9%87%8F)
![image](https://github.com/user-attachments/assets/299bdf51-abd1-41d9-9d94-993bb608111a)

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
