### ISSUE TITLE
积木报表怎么使用sheet进行导出？

### ISSUE THREAD

**Issue by kaibolun** [jeecgboot/JimuReport#2792]
##### 版本号：

1.6.6
##### 问题描述：
您好开发者，这边在使用积木工具进行一些数据导出时遇到一些需求无法再这上面解决，想向您这边获得一些帮助，就是一张是主表，一张是明细表，想要将这两张表分两个sheet进行导出，需要怎么操作呢？再此先感谢您开发的软件工具便利了大众

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
目前不支持
