### ISSUE TITLE
1.4.0升级1.7.8找不到oConvertUtils类

### ISSUE THREAD

**Issue by LUOi33** [jeecgboot/JimuReport#2794]
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/dc691b94-4b6c-4282-a9b1-4d3f6b4a8b3c)
![image](https://github.com/user-attachments/assets/6d73ecef-592e-429c-879a-f902273b2328)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
换成 OkConvertUtils
