### ISSUE TITLE
数据源是否可以共用

### ISSUE THREAD

**Issue by 441004767** [jeecgboot/JimuReport#2796]
##### 版本号：

1.7.8
##### 问题描述：
所有的报表用的数据源是相同的，只是传入的参数不一样，是否可以共用。
现在配置很麻烦，没新增一个报表都要自己配置手动配置数据源
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你说的是数据集吧

**Comment by 441004767** [comment]
是的，是数据集

**Comment by zhangdaiscott** [comment]
看后面的规划

**Comment by jeecgos** [comment]
v1.9.0版本已支持共享数据集。文档参考：https://help.jeecg.com/jimureport/dataSet/shareSource.html
