### ISSUE TITLE
我docker配置的报表突然全部没有了，docker服务一直都没停过

### ISSUE THREAD

**Issue by eiweorerw** [jeecgboot/JimuReport#2797]
##### 版本号：
1.7.9

##### 问题描述：
我docker配置的报表突然全部没有了，docker服务一直都没停过，之前打开的报表设计页面直接报错
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jul 17 16:31:30 CST 2024
There was an unexpected error (type=Internal Server Error, status=500).
##### 错误日志&截图：
![微信截图_20240717163502](https://github.com/user-attachments/assets/d53be61a-b6b6-4a19-97d7-5789b1df5ff3)
![111](https://github.com/user-attachments/assets/438cff33-726d-4fc3-953c-5f2144d4b82e)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by eiweorerw** [comment]
除了/jmreport/list空页面，所有请求都报500，error: "Internal Server Error"
path: "/jmreport/excelQuery"
status: 500
timestamp: "2024-07-17T09:06:07.949+00:00"

**Comment by zhangdaiscott** [comment]
你得自己排查，这个跟环境有关

**Comment by eiweorerw** [comment]
这个应该怎么排查，我按照你们的部署教程操作部署的docker,然后建了四个表，突然好像数据库就空了，查看docker状态容器也正常运行，但是请求接口就是500，我没有做任何docker操作
