### ISSUE TITLE
图表打印问题

### ISSUE THREAD

**Issue by whsnr** [jeecgboot/JimuReport#2799]
##### 问题描述：图表（比如折线图），预览可以显示，打印不能显示（显示空白）
1、API动态数据，服务端直接返回数据比如（for循环直接生成的数据），正常
2、API动态数据，服务端从数据库查询数据并返回，出现下面图片上的情况（跟踪确定服务端执行了并返回数据了）

另外反映个其他其他问题：多数据对比折线图，预览不显示，且自定义属性不生效

##### 错误日志&截图：
预览：
![I9U}}0KAF_SIDZ2 RK)(%LH](https://github.com/user-attachments/assets/4c79c743-9728-4a7e-a46b-1abc89d75097)
打印：
![QK{CYHV`YNJ43 I2(4E( DL](https://github.com/user-attachments/assets/ec94c7ac-24d6-46dd-93c8-2e707491171e)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by jeecgos** [comment]
ws

**Comment by 1298191366** [comment]
未复现，请在官网制作报表示例并提供ID

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
