### ISSUE TITLE
聚合报表列表循环问题

### ISSUE THREAD

**Issue by wushunqing** [jeecgboot/JimuReport#280]
##### 版本号：

1.3.3-beta
##### 问题描述：
使用复杂报表时，一个报表需要包含几个小块的表格。使用发现，循环行会影响其他数据。具体见下图提示

##### 截图&代码：
![image](https://user-images.githubusercontent.com/20431475/119436260-6c7a8680-bd4e-11eb-9662-52fe8b5c9008.png)

![image](https://user-images.githubusercontent.com/20431475/119436529-ead72880-bd4e-11eb-904a-45516cf3427b.png)

##### 参考：
此功能请参考帆软聚合报表，这种在企业内很常见。
https://jingyan.baidu.com/article/90808022e0b5f5fd91c80f35.html

![image](https://user-images.githubusercontent.com/20431475/119476552-bbd9aa80-bd80-11eb-8d96-98f871efedfa.png)

**Comment by wushunqing** [comment]
此功能请参考帆软聚合报表，这种在企业内很常见。
https://jingyan.baidu.com/article/90808022e0b5f5fd91c80f35.html

**Comment by wushunqing** [comment]
![image](https://user-images.githubusercontent.com/20431475/119476552-bbd9aa80-bd80-11eb-8d96-98f871efedfa.png)

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by zhangdaiscott** [comment]
先归集到https://github.com/jeecgboot/JimuReport/issues/138，待安排处理

**Comment by accpman** [comment]
已实现，等下个版本发布
