### ISSUE TITLE
新建报表没有权限

### ISSUE THREAD

**Issue by whwhwhwh222** [jeecgboot/JimuReport#2801]
##### 版本号：
 <dependency>
            <groupId>org.jeecgframework.jimureport</groupId>
            <artifactId>jimureport-spring-boot3-starter-fastjson2</artifactId>
            <version>1.7.8</version>
        </dependency>

##### 问题描述：
我自定义token权限，新建报表提示一些静态资源没权限

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/45763ce9-0974-4cc4-9253-eddb12fb4481)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你自己的项目做了静态资源配置？冲突了？

**Comment by whwhwhwh222** [comment]
我是微服务项目，检查了下没有发现有冲突，没有找到具体原因，请大佬分析下

**Comment by zhangdaiscott** [comment]
gateway路由转发配置，没有加入积木的资源路径

**Comment by whwhwhwh222** [comment]
感谢大佬，解决了
