### ISSUE TITLE
大数据量导出失败，报错渲染失败

### ISSUE THREAD

**Issue by MaYongYong** [jeecgboot/JimuReport#2802]
##### 版本号：
1.7.5

##### 问题描述：
大数据量导出失败，报错渲染失败

##### 错误日志&截图：
![渲染失败](https://github.com/user-attachments/assets/1c93e0fc-912c-4e21-abf5-a65032c09f55)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
升级到最新版，这个问题处理过
