### ISSUE TITLE
打印内容时出现空白页

### ISSUE THREAD

**Issue by diligentkong** [jeecgboot/JimuReport#2804]
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/781f5999-9437-42c6-a8b6-4a7f57ca9226)

![image](https://github.com/user-attachments/assets/89cb4951-0649-4a89-a331-54d17dbc7de5)

![image](https://github.com/user-attachments/assets/f6260d89-5e31-433e-b33f-bfdc45730d00)

![image](https://github.com/user-attachments/assets/4a114d0f-98c1-4bc5-8134-372d214e3774)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by diligentkong** [comment]
官网制作的报表id ： 974217089596608512

974083384265756672 这个报表id 设置了换行以及垂直向上 但是打印或者导出pdf始终在下一页展示

**Comment by jeecgos** [comment]
ws

**Comment by diligentkong** [comment]
[入院记录.json](https://github.com/user-attachments/files/16407053/default.json)
[首日病程.json](https://github.com/user-attachments/files/16407057/default.json)

这是报表配置 打印 、导出pdf的时候都有空白页

**Comment by 1298191366** [comment]
导出已修改，待新版本发布
