### ISSUE TITLE
用户手动录入的数值数据无法和数据库中查出的数值常量取比例结果，使用round会报错。

### ISSUE THREAD

**Issue by alonekokonew** [jeecgboot/JimuReport#2805]
##### 版本号：
1.6.2

##### 问题描述：
用户手动录入的数值数据无法和数据库中查出的数值常量取比例结果，使用round会报错。

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/de3b85d6-e1a2-4d4c-95ad-344385151d28)

##### 重现步骤：
=round(1/3,2) 可以
以下不可以
=round(${param.outSugeryRoomCount}/#{ZT3.麻醉总数},2) 
=round(${param.outSugeryRoomCount}/${ZT3.麻醉总数},2)
=round('${param.outSugeryRoomCount}'/'${ZT3.麻醉总数}',2)
提示： 表达式渲染错误的单元格：C24

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
遇到先升级到最新版

**Comment by jeecgos** [comment]
cr

**Comment by hoperunChen** [comment]
已修复，待新版本发布。
