### ISSUE TITLE
版本升级到1.7.4之后，显示Token校验失败，无权限访问！

### ISSUE THREAD

**Issue by zoufh** [jeecgboot/JimuReport#2806]
![image](https://github.com/user-attachments/assets/cdd0efe1-1d26-4f69-8b3e-54c7789a100f)
![image](https://github.com/user-attachments/assets/ffbde0aa-2ff2-43f6-b134-46e1557bc586)

**Comment by zoufh** [comment]
之前版本是1.5.8

**Comment by zhangdaiscott** [comment]
按照文档实现接口类JmReportTokenServiceI

**Comment by zoufh** [comment]
> 按照文档实现接口类JmReportTokenServiceI

package com.jeecg.modules.jmreport.config;

import com.hedu.sweet.starter.auth.token.SweetTokenFactory;
import org.jeecg.modules.jmreport.api.JmReportTokenServiceI;
import org.springframework.http.HttpHeaders;
import org.springframework.stereotype.Component;
import org.springframework.util.StringUtils;

import javax.servlet.http.HttpServletRequest;
import java.util.Map;

/**
 * 自定义积木报表鉴权(如果不进行自定义，则所有请求不做权限控制)
 * 1.自定义获取登录token
 * 2.自定义获取登录用户
 */
@Component
public class JimuReportTokenService implements JmReportTokenServiceI {

    /**
     * 通过请求获取Token
     * @param request
     * @return
     */
    @Override
    public String getToken(HttpServletRequest request) {
        String token = request.getParameter("token");
        if(!StringUtils.hasText(token)){
            token = request.getHeader("__TOKEN__");
        }
        if(!StringUtils.hasText(token)){
            token = request.getHeader("token");
        }
        if(!StringUtils.hasText(token)){
            token = request.getHeader("X-Access-Token");
        }
        return token;
    }

    /**
     * 通过Token获取登录人用户名
     * @param token
     * @return
     */
    @Override
    public String getUsername(String token) {
        Map<String, String> payload = SweetTokenFactory.getPayload(token);
        String xm = payload.get("xm");
        return xm;
    }

    @Override
    public String[] getRoles(String s) {
        return new String[0];
    }

    /**
     * Token校验
     * @param token
     * @return
     */
    @Override
    public Boolean verifyToken(String token) {
        System.out.println("---------verify-----Token---------------");
        boolean verify = SweetTokenFactory.verify(token);
        System.out.println(verify);
        return verify;
    }

    /**
     *  自定义请求头
     * @return
     */
    @Override
    public HttpHeaders customApiHeader() {
        HttpHeaders header = new HttpHeaders();
        header.add("__TOKEN__", "Please set a custom value 1");
        header.add("token", "token value 2");
        return header;
    }
}

**Comment by zhangdaiscott** [comment]
不行？

**Comment by zoufh** [comment]
> 是的

**Comment by zhangdaiscott** [comment]
只能你自己确认，集成有问题

**Comment by zoufh** [comment]
> 只能你自己确认，集成有问题

好的  多谢
