### ISSUE TITLE
返回大数据量，求和报错，无法求和

### ISSUE THREAD

**Issue by MaYongYong** [jeecgboot/JimuReport#2807]
##### 版本号：
v1.7.8
##### 问题描述：
返回大数据量，求和报错，无法求和

##### 错误日志&截图：
报表设置如下图：
![1721304698556](https://github.com/user-attachments/assets/e69f5af2-ed89-4811-98bc-5d46dcf64924)
最后求和列：
![1721304698543](https://github.com/user-attachments/assets/0fa5320f-4e38-490c-91d1-d5d8a7f8ad27)
报表求和是报错
![1721304698528](https://github.com/user-attachments/assets/71c96da5-0887-4478-844a-1a6726fabc68)

对应报错日志：
2024-07-18 20:05:44.512 [http-nio-8085-exec-6] [1;31mERROR[0;39m [36morg.jeecg.modules.jmreport.desreport.express.a:375[0;39m - 表达式处理出错，单元格：F34063
2024-07-18 20:05:44.634 [http-nio-8085-exec-6] [1;31mERROR[0;39m [36morg.jeecg.modules.jmreport.desreport.express.a:375[0;39m - 表达式处理出错，单元格：H34063

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你确定你是最新版？

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by MaYongYong** [comment]
确认最新版本1.7.8。导出数据3W+，渲染报错。
报错日志：
![报错日志](https://github.com/user-attachments/assets/69d53c38-dbc8-47ab-9456-1d215a2ff85c)
程序报错信息：
![微信截图_20240724154112](https://github.com/user-attachments/assets/f7e2ac99-0c7a-4237-8748-85bbaf29c4a7)
报表配置信息：
[服务项目例数统计新.json](https://github.com/user-attachments/files/16358883/default.json)

**Comment by hoperunChen** [comment]
已修复，待新版本发布。
