### ISSUE TITLE
ruoyi 框架 集成，ip 加端口 可以访问，发到服务器上，域名通过nginx 配的 prod-api  映射 无法访问

### ISSUE THREAD

**Issue by jzeran** [jeecgboot/JimuReport#2808]
##### 版本号：
1.7.8

##### 问题描述：

ruoyi 框架 集成，ip 加端口 可以访问，发到服务器上，域名通过nginx 配的 prod-api  映射 无法访问
##### 错误日志&截图：
![ZTE@RB_%GS5N9$RZ62W29AK](https://github.com/user-attachments/assets/a65b1c95-92c2-477a-ba01-14673fb9b6df)

##### 重现步骤：
ruoyi vue 版本 集成，加个域名，映射端口 访问  nginx 配一下 后台转发
/prod-api/jmreport/list
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
你的nginx配置发一下

**Comment by 1298191366** [comment]
经测试 未复现，如有其他问题 请尽快回复
![image](https://github.com/user-attachments/assets/86ba7ab1-c0f9-4846-8a0b-ce01282bc481)
![image](https://github.com/user-attachments/assets/3878dc04-25fc-4dcf-833e-3dd8753e4143)
nginx前端配置：
![image](https://github.com/user-attachments/assets/aee27aea-f711-4e9f-a672-41a0592aa46f)

正常模式下 是不需要加`/prod-api`请求前缀
![image](https://github.com/user-attachments/assets/6c1aee6a-3206-4182-80c5-14640f0b2174)
你是不是访问后端项目需要用到`/prod-api前缀，而积木报表没有加，如果是没有加请使用
![image](https://github.com/user-attachments/assets/45106d2e-6b72-49c0-8c6c-238b59f38463)
