### ISSUE TITLE
新建报表页面显示异常

### ISSUE THREAD

**Issue by xiaolongyi** [jeecgboot/JimuReport#2809]
##### 错误日志&截图：
![微信截图_20240719102735](https://github.com/user-attachments/assets/2a004202-eadc-4efe-bb97-4fe090e1019a)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by xiaolongyi** [comment]
![Uploading 微信截图_20240719102654.png…]()

**Comment by zhangdaiscott** [comment]
什么浏览器，图裂了

**Comment by xiaolongyi** [comment]
> 什么浏览器，图裂了

谷歌和edge都是一样的

**Comment by xiaolongyi** [comment]
![微信截图_20240719102654](https://github.com/user-attachments/assets/205f8f8c-12a1-4d4c-b26a-32acb8e37b41)

**Comment by zhangdaiscott** [comment]
下载免安装版或者docker版本试试，如果没问题，就是你集成有问题
http://jimureport.com/download

**Comment by mackjieson** [comment]
同样的问题
