### ISSUE TITLE
预览xls时，每页的固定表头失效

### ISSUE THREAD

**Issue by liph7268** [jeecgboot/JimuReport#2810]
##### 版本号：
1.6.6

##### 问题描述：
①在模板中设置固定表头列
②导出xls
③预览xls时，每页的固定表头就失效了，请问这个问题怎么解决

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/5c147ae1-ee20-4cf5-b9d9-fc1ad89f8b1d)

##### 重现步骤：
![image](https://github.com/user-attachments/assets/359ae380-89a3-4d73-867e-fc834f36100b)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
导出excel不支持

**Comment by liph7268** [comment]
后期会支持吗

**Comment by 1298191366** [comment]
你是需要的是冻结行吗

**Comment by liph7268** [comment]
不是冻结行  是在模板中设置了固定表头后，导出xls，在xls中打印预览时，每一页都需要带表头

**Comment by 1298191366** [comment]
我的意思是你需要的是冻结行功能码。固定表头导出就只是一个表头 而不是 excel中的冻结行

**Comment by liph7268** [comment]
![image](https://github.com/user-attachments/assets/3686e573-bd8f-4ffa-844c-710e99d23d4b)

**Comment by liph7268** [comment]
![image](https://github.com/user-attachments/assets/976180c3-9aba-44e0-a62d-6aa57f257a69)

**Comment by liph7268** [comment]
https://bootapi.jeecg.com/jmreport/view/973395872291573760?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MjM0ODc3MzAsInVzZXJuYW1lIjoib2hiYUs2Y25TWENPQ1FZQnpFSHJfNmo3SFJMSSJ9.PXFCWozaXXncUlukML3p22WJcHOoZUwgpIdZd9_IcAY

**Comment by 1298191366** [comment]
这个没做，就是先确认一下，马上处理

**Comment by liph7268** [comment]
好的，谢谢

**Comment by 1298191366** [comment]
冻结行已支持，待新版本发布
