### ISSUE TITLE
怎么设置上线安全，docker部署，按教程操作无效

### ISSUE THREAD

**Issue by eiweorerw** [jeecgboot/JimuReport#2811]
##### 版本号：
1.7.9

##### 问题描述：
我用docker部署的，现在要上线了，但是之前有部署过一个，突然数据库数据用不了了，我现在想把现在部署的服务的报表设计功能关掉，但是按照教程设置resources/application-dev.yml里的dataSourceSafe: yes
      lowCodeMode: prod， 然后重启docker容器以后，还是可以打开报表设计功能，我要怎么操作才能关闭报表设计功能

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
是不是配置的地方不对

**Comment by eiweorerw** [comment]
> 是不是配置的地方不对

我配置的是resources/application-dev.yml文件，我看了application-prod.yml里本来就是lowCodeMode:prod,还有个application.yml，里面没有lowCodeMode配置项，我应该在哪里配置，我配置好以后也重新执行了docker-compose up -d，我应该怎么配置才能生效

**Comment by jeecgos** [comment]
cr

**Comment by eiweorerw** [comment]
> cr

cr什么意思？我不是做java开发的，只是用docker部署的

**Comment by 1298191366** [comment]
经测试 无问题
如果你使用的是`prod`请确保当前用户不是admin或者预留角色。如果是admin或者预留角色也不允许设计，那么请使用`prodsf`
参考文档：[安全模式](https://ojrjjvdr7z.k.topthink.com/jimureport/prodSafe.html)
请注意：无法设计不是指无法进入设计页面，而是 在保存的时候 会有提示
![image](https://github.com/user-attachments/assets/6e455581-0b25-4711-9976-e93c9ab9d7f5)
