### ISSUE TITLE
换行时单词被切割怎么处理

### ISSUE THREAD

**Issue by 475857633** [jeecgboot/JimuReport#2814]
版本号：
1.7.9（官网在线使用）

问题描述：
一段英文长文本设置了自动换行之后，出现换行时一个英文单次被从中间切断了

错误日志&截图：
![image](https://github.com/user-attachments/assets/7fda6b36-f749-4af2-aae6-92871b63de01)
![image](https://github.com/user-attachments/assets/9aa9c5ba-0e4e-479b-a9ac-6fff5d2ed379)

重现步骤：
官网制作的报表id ： 975210043635224576

**Comment by jeecgos** [comment]
重复 #2849

**Comment by 475857633** [comment]
都是我提的，感谢回复&nbsp;


?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月9日(星期五) 下午4:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/JimuReport] 换行时单词被切割怎么处理 (Issue #2814)














 
重复 #2849
