### ISSUE TITLE
图表打印与显示可能不一致问题

### ISSUE THREAD

**Issue by CA1907** [jeecgboot/JimuReport#2816]
##### 问题描述：
图表打印时，如果查询条件与设计时不一致 ，图表显示内容与打印不一致，显示正常，打印的始终是设计时的内容。
测试了柱状图和拆线图、多数据对比拆线图

##### 错误日志&截图：
![7296257BEF4D2A92F5FF921FC31B6DD9](https://github.com/user-attachments/assets/ddd166f6-7e59-484a-af77-8c07d110d112)
![3C526C7BCE2C6EA3D44A73CD1C8A2BE3](https://github.com/user-attachments/assets/2304a2e1-5f5d-4a9f-8c18-26c3019a9a2d)
##### 重现步骤：
1、官网：http://jimureport.com/templates
2、报表模板
3、图表联动报表
4、选择“王伟”
5、点击打印
打印结果中：每月定单和回款率与显示不一致。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
zy

**Comment by liaozhiyang** [comment]
已解决，下一版本发布
