### ISSUE TITLE
关于集合转字符串

### ISSUE THREAD

**Issue by yanwencheng** [jeecgboot/JimuReport#2817]
##### 版本号：
1.6.6

##### 问题描述：
有个需求，是数据集转字符串，输出到单元格，有什么函数么，或者自定义函数怎么处理

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
参考下，自定义报表函数文档：https://help.jeecg.com/jimureport/function/custom.html 。

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
