### ISSUE TITLE
自定义函数仿造MAX函数的问题

### ISSUE THREAD

**Issue by yanwencheng** [jeecgboot/JimuReport#2819]
##### 版本号：
1.6.6

##### 问题描述：
MAX函数在variadicCall中能获取动态单元格的所有数据，自定义函数却获取的动态单元格最后一条数据。
这个该怎么处理？

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/7130b2bd-f5c9-44b2-a932-65e728571e8f)

![image](https://github.com/user-attachments/assets/6ef086cb-c70b-4e62-91cc-39cc635ed0a2)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
陈锐

**Comment by jeecgos** [comment]
cr

**Comment by hoperunChen** [comment]
#2752
自定义报表函数已支持动态行的聚合计算，下一个版本更新。
文档：https://ojrjjvdr7z.k.topthink.com/jimureport/function/custom.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8A%A5%E8%A1%A8%E5%87%BD%E6%95%B0%E6%94%AF%E6%8C%81%E5%8A%A8%E6%80%81%E8%A1%8C%E7%9A%84%E8%81%9A%E5%90%88%E8%AE%A1%E7%AE%97

**Comment by PHP-Snake** [comment]
> #2752 自定义报表函数已支持动态行的聚合计算，下一个版本更新。 文档：https://ojrjjvdr7z.k.topthink.com/jimureport/function/custom.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8A%A5%E8%A1%A8%E5%87%BD%E6%95%B0%E6%94%AF%E6%8C%81%E5%8A%A8%E6%80%81%E8%A1%8C%E7%9A%84%E8%81%9A%E5%90%88%E8%AE%A1%E7%AE%97

需要更新积木报表版本么
