### ISSUE TITLE
实现换页功能

### ISSUE THREAD

**Issue by maxiaole-z** [jeecgboot/JimuReport#2820]
##### 问题描述：
想实现打印按部门，例如：，第一个部门有10条明细，当前页没打印完，第二个部门换下一页打印。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
主子表循环块了解一下？文档：https://help.jeecg.com/jimureport/datareport/loopBlock.html
示例如下：
![image](https://github.com/user-attachments/assets/42d7bc1e-1b40-4671-9af0-723873f4f948)

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
