### ISSUE TITLE
如何实现去除报表空白区域

### ISSUE THREAD

**Issue by chinaanze** [jeecgboot/JimuReport#2821]
##### 错误日志&截图：

![Snipaste_2024-07-25_12-11-53](https://github.com/user-attachments/assets/c570d539-72c0-4678-bf29-f54f4814e15d)

![微信图片_20240725120748](https://github.com/user-attachments/assets/e7f6e2ae-ffdc-43f3-a478-cb4c846aa6b9)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by chinaanze** [comment]
![Uploading Snipaste_2024-07-25_12-11-53.png…]()

**Comment by jeecgos** [comment]
在设计页面，选中表格右边的空白列，右键-【删除内容】然后再【删除列】。
![QQ_1721958369679](https://github.com/user-attachments/assets/b4ddcea3-c0e4-49a1-b4a4-f8ea4ab101fa)
如果不行的话，请升级到最新的版本，再试下。

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
