### ISSUE TITLE
仪表盘中的查询条件为空

### ISSUE THREAD

**Issue by 2937vchengxin** [jeecgboot/JimuReport#2823]
##### 版本号：
1.7.9

##### 问题描述：
仪表盘中的查询条件为空

##### 错误日志&截图：
![DF9659D0-1B04-66B2-BFAB-9B52870B4EC6](https://github.com/user-attachments/assets/6d5a273f-6aa3-4028-bd24-e27f5a24aba2)

##### 重现步骤：
点击仪表盘常用中的查询条件，点击设置，可以看见配置项为空

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
sq

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
