### ISSUE TITLE
单元格设置 Base64图片,值未读取出来

### ISSUE THREAD

**Issue by xglxj2007** [jeecgboot/JimuReport#2824]
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/680318b4-c5a3-4f03-96ef-f00f7871daac)
![image](https://github.com/user-attachments/assets/1741d6d3-4fc1-4c65-81a5-b85709272238)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
已修复，请等待新版本发布。
