### ISSUE TITLE
jimu报表用api数据源不返回数据

### ISSUE THREAD

**Issue by unbelievableTang** [jeecgboot/JimuReport#2826]
##### 版本号：1.5.6
![image](https://github.com/user-attachments/assets/c8f8a9ae-97f9-4d63-953f-201e743eef0d)

##### 问题描述：
jimu报表用api数据源不返回数据
返回对象 用过String，List，JsonObject 都不行

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/1605c107-af44-4644-9e85-d77e5647437a)
![image](https://github.com/user-attachments/assets/3cf026fb-584d-4872-93c3-30c2e57c416b)
![image](https://github.com/user-attachments/assets/f9e131e1-49b3-4f9f-a4a2-bdbc123a2fa0)

##### 重现步骤：
图一是前台配置，图二是接口截图 返回对象 用过String，List，JsonObject 都不行，图三是maven依赖版本号

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
遇到问题，先升级到最新版
