### ISSUE TITLE
积木报表钻取设置条件时，条件判断问题

### ISSUE THREAD

**Issue by 15900346784** [jeecgboot/JimuReport#2827]
##### 版本号：
1.7.32

##### 问题描述：
对报表钻取设置条件，预览时发现同一页内出现不同条件时，都只按照第一条显示的条件，钻取显示第二个报表页面

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/50d253c4-477e-446d-9572-c7d87765bdc4)
![image](https://github.com/user-attachments/assets/31e022a5-9ad3-4ace-b79c-79cd92add1e7)
![image](https://github.com/user-attachments/assets/430710b8-c844-4756-aba5-44aaa0f94ad7)
![image](https://github.com/user-attachments/assets/910a3292-b856-49e2-a90b-fbe0d0fa85c1)
![image](https://github.com/user-attachments/assets/963313be-4e54-4c52-b44e-502d32dd4723)
![image](https://github.com/user-attachments/assets/4601a69e-0cfa-4a9a-8b14-18f4814dda95)
![image](https://github.com/user-attachments/assets/a5468a22-4449-4ce9-b1f3-7bd04fbd8722)

##### 重现步骤：
这种情况有解决办法吗

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 15900346784** [comment]
有人出现过这种情况吗

**Comment by Yuzuski** [comment]
@15900346784 怎么解决呢？是 BUG？大概什么时候可以解决呢

**Comment by 15900346784** [comment]
目前还没解决 想问问是系统BUG吗

**Comment by 1298191366** [comment]
已修复，待新版本发布
