### ISSUE TITLE
复杂SQL如何制作SQL数据集

### ISSUE THREAD

**Issue by unbelievableTang** [jeecgboot/JimuReport#2828]
##### 版本号：
jimureport1.5.6
jeecg 2.4.5

##### 问题描述：
原来我有一段sql，见附件sql语句。其中的 '${start}'和 '${end}'是我后期需要输入的参数。
[sql语句.txt](https://github.com/user-attachments/files/16407755/sql.txt)

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/68747d92-fab3-406f-8354-122a86754363)
点击解析，报错。

我也尝试了通过编写后端接口方式调用api让jimu获取数据但是貌似还是不行，接口有数据，页面报错空数据。
![9f4eaa9043a11ad4ed7c0ad917eb5c5](https://github.com/user-attachments/assets/52dd58d7-b0ef-4c4c-b8ce-6306bd6282ec)
![0451ee12d023d1878b02d57a5e80153](https://github.com/user-attachments/assets/7ffadb3c-77f4-4601-85fa-49c399850627)

前两天github issues组某大佬让我跟新至新版本貌似也还是不行，我首先试了一下在pom中直接更改版本号，发现一大堆报错。
![a322bbb2071ec0f9fbbc5e7192e785d](https://github.com/user-attachments/assets/7e378e44-37a7-4e1a-abc2-2f3798a4137a)
后来我想到可能是我们项目是再加密空间打开的，不能下载依赖，我又到本地的demon项目中加了这个新版本的依赖并且把下载好的包。直接挪到放到了我加密空间的实际项目里。
![image](https://github.com/user-attachments/assets/81847d94-e5ea-4a36-adf9-2dd760bdc15d)

然后发现还是不行，而且出现两个版本共存了。
![4612590d42eda3acba7d92fc228ff2d](https://github.com/user-attachments/assets/e97eb451-fc4b-4136-91d4-937ffdd2ba2b)
![276b24f7cf2790b8620eff0dd6f5c4b](https://github.com/user-attachments/assets/7b65a093-0d93-404d-850a-7c0610c912ba)

我们系统可能偏老了基于jeectboot2.4.5,可能升级jimureport挺难弄的。
有没有直接让这个sql数据集解析成功的方法，如果一定要升级版本能不能协助一下，谢谢。
这是parent模块(root)的pom
![image](https://github.com/user-attachments/assets/7f3e8817-c3c3-4bb9-a1c7-cb728fc1f97b)

这是bp模块的pom，也是我书写调用jimureport接口的模块
![image](https://github.com/user-attachments/assets/110af240-b68d-4e0a-a222-8593d2db0e22)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
版本太老，无法支持，请先升级到最新版
