### ISSUE TITLE
jimureport  docker-compose context: path  绝对路径not found报错

### ISSUE THREAD

**Issue by leqii-com** [jeecgboot/JimuReport#2829]
##### 版本号：
最新

##### 问题描述：
我使用Portainer可视化docker管理平台，使用你们docker-compose代码发布时候，我将conext: ./db修改为绝对路径，报错
failed to deploy a stack: jimureport Pulling jimureport-mysql Pulling jimureport Error jimureport-mysql Error unable to prepare context: path "/data/bashi/JimuReport/jimureport-example/db" not found
不可以用绝对路径吗？

##### 错误日志&截图：
![20240729141448](https://github.com/user-attachments/assets/1c7127b5-5be4-43c0-bbe8-c74ba521d46a)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by hoperunChen** [comment]
请确保你的运行环境确实存在该目录`/data/bashi/JimuReport/jimureport-example/db`，并且该目录下有`Dockerfile`.

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
