### ISSUE TITLE
独立运行demo，报错找不到$refs

### ISSUE THREAD

**Issue by ChengGC** [jeecgboot/JimuReport#283]
##### 版本号：
1.3.0 1.3.3

##### 问题描述：
非集成，独立运行demo 在新建数据报表页面，点击数据集管理下面的三个按钮报错，找不到$refs

##### 截图&代码：
TypeError: this.$refs.dataSource.onMenuSelect is not a function. (In 'this.$refs.dataSource.onMenuSelect(name)', 'this.$refs.dataSource.onMenuSelect' is undefined) — 
<img width="217" alt="截屏2021-05-26 下午6 01 58" src="https://user-images.githubusercontent.com/3363265/119642906-c9a93180-be4d-11eb-9a6d-3d819e102a8d.png">
<img width="856" alt="截屏2021-05-26 下午6 07 48" src="https://user-images.githubusercontent.com/3363265/119642915-cc0b8b80-be4d-11eb-8650-47398a5be8fb.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by ChengGC** [comment]
线上版本也是这个错

**Comment by ChengGC** [comment]
safari 报错 chrome没问题

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by zhangdaiscott** [comment]
你的safari 是什么版本？我们测没问题，你可以升级到最新
