### ISSUE TITLE
下拉单选查询选择器有滚动条后，进行滚动条下拉后，会重新加载一遍数据，变为多次重复的数据

### ISSUE THREAD

**Issue by yupenglideyupeng** [jeecgboot/JimuReport#2830]
##### 问题描述：
下拉单选查询选择器有滚动条后，进行滚动条下拉后，会重新加载一遍数据，变为多次重复的数据

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/3ab57daa-279c-408b-8ed2-99d92b667cae)
![image](https://github.com/user-attachments/assets/e7462b60-5f77-4438-af95-76f04110daec)
![image](https://github.com/user-attachments/assets/6b47f2df-af7a-45e6-9974-e07666dd356e)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by yupenglideyupeng** [comment]
1.7.8版本也有相同问题，接口的数据和字典的数据都会出现

**Comment by 1298191366** [comment]
已修复，待新版本发布
