### ISSUE TITLE
单元格内容超过当前页设置为自动换行时导出pdf时第一页为空

### ISSUE THREAD

**Issue by diligentkong** [jeecgboot/JimuReport#2831]
##### 错误日志&截图：
![1722240619436](https://github.com/user-attachments/assets/5392f0f3-c844-4973-8447-793cd85312e3)
官网配置的报表id 977803375985119232  护理记录

https://bootapi.jeecg.com/jmreport/view/977803375985119232?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MjI1NDAwNjIsInVzZXJuYW1lIjoib2hiYUs2VlA4YzJFUEc0ZGVKeGk4dVBhVGZLMCJ9.nUn2ireCobuY7vjk0NIgH0DMqeg65w9H7zGx90jvjuo

配置的报表格式

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by diligentkong** [comment]
配置的报表格式
[护理记录 (1).json](https://github.com/user-attachments/files/16409585/1.json)

**Comment by 1298191366** [comment]
已修复，待新版本发布
