### ISSUE TITLE
积木报表查询下拉框有重复值

### ISSUE THREAD

**Issue by capluer** [jeecgboot/JimuReport#2832]
##### 版本号：
1.5.0

##### 问题描述：
将某个字段设置为查询条件，在查询栏发现下拉列表的值是重复的，我希望的是每个值显示一次

##### 重现步骤：

在SQL数据集界面，将某个列的“查询”勾选上，“查询模式”选择下拉列表，在报表预览界面，查询栏显示的值是重复的
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
下拉查询需要配合数据字典来使用。
> 自version 1.7.9版本开始,下拉查询不配置数据字典将无法保存报表。

如果一定要使用不依赖数据字典的下拉查询，并且不希望有重复的下拉选项，请更确保`1.7.0<版本<1.7.9`。
