### ISSUE TITLE
参数列为下拉控件，控件值从下拉列表中选择，控件值不允许清空，但可以更换

### ISSUE THREAD

**Issue by 1322408199** [jeecgboot/JimuReport#2834]
##### 版本号：

1.6.6-beta2

##### 问题描述：
 参数列为下拉列表控件且必选内容（不允许空值），参数设置默认值，
 但是当预览报表，选择列表其中任意值后，鼠标移动到文本框下拉箭头会变成X，此时点X
 控件值就被清空了，达不到必选的要求（控件非空值）。

##### 错误日志&截图：
[Uploading list.docx…]()

##### 重现步骤：
任意一个下拉控件都可以浮现

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
该功能即将在1.7.10版本支持，待新版本发布。
#2618
