### ISSUE TITLE
项目集成积木报表token自动续期问题

### ISSUE THREAD

**Issue by java-my-life** [jeecgboot/JimuReport#2835]
##### 问题描述：
目前使用积木报表集成项目中的token时，报表token并没用自动续期机制，如果项目中token过期时间为30分钟，那么从菜单中弹出新tab页跳转报表地址“/jmreport/list?token={token}”传递的token就只有30分钟有效期，一旦超过30分钟，token就会失效，请问要如何解决？
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by hoperunChen** [comment]
积木报表本身是不提供任何token续期功能的，如果你有续期的需求，可以在你的`JmReportTokenServiceI`实现类的`verifyToken`方法中自行实现续期逻辑。
