### ISSUE TITLE
API数据源解析提示 :执行成功，但是数据为空，无法解析报表字段！！  

### ISSUE THREAD

**Issue by robeterlk** [jeecgboot/JimuReport#2836]
##### 版本号：
在线演示功能测试

##### 问题描述：
本地直接通过APIfox访问 http://localhost/dev-api/system/charts/test/ 返回数据格式为
![image](https://github.com/user-attachments/assets/676be6af-3699-47d2-ad12-ca84db950537)
后端代码返回格式为jsonobject
![image](https://github.com/user-attachments/assets/d1259084-223d-49b0-9190-d44996b7b267)

##### 错误日志&截图：
是否集合勾选不勾选都是解析失败
![image](https://github.com/user-attachments/assets/a8cdb3ed-ef12-4c65-945f-f911783e06ac)
![image](https://github.com/user-attachments/assets/c5c1228c-7fe2-4f5d-a329-9514617c9509)

##### 重现步骤：
![image](https://github.com/user-attachments/assets/3047f103-e99c-4f6f-aebb-da8a3c4d1278)
![image](https://github.com/user-attachments/assets/58bfbf3f-3b8b-4b96-b79b-6d4420dbd39c)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
你在线上接口访问你本地的localhost接口，当然不会获取到数据了，积木官网和你本地的网络是不通的。你要把你本地的接口发布到互联网才能在积木报表官网访问。
