### ISSUE TITLE
下拉树请求接口需要后端放开跨域请求，且没有带token头部

### ISSUE THREAD

**Issue by yupenglideyupeng** [jeecgboot/JimuReport#2837]
##### 问题描述：
1.使用下拉树请求自定义接口时，需要在后端添加@CrossOrigin("*") ，否则在前端请求控制台会提示跨CROS跨域错误，（根据request排查请求地址是127.0.0.1）
2.下拉树的请求到后端时没有token数据，下拉选择器的数据是带有token的
    获取token目前使用：HttpServletRequest httpServletRequest对象，使用httpServletRequest.getParameter("token");和httpServletRequest.getHeader("token");获取token
3.下拉树目前只能使用复选框，是否可以支持单选或多选两种情况，并且是否可以支持一次将数据都进行传递，避免已经到了最后一级还需要发起一次请求（类似下拉列表的功能）

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/8ea0333f-98f6-47b5-bb7a-19239c3c67fd)
![image](https://github.com/user-attachments/assets/4f2a60e2-7b37-4553-bba2-ce9ec5bb1fa3)
![image](https://github.com/user-attachments/assets/08632829-970c-462e-be2f-e2d10289d2d9)
![image](https://github.com/user-attachments/assets/59f6d17c-5680-43bb-80fe-d3b5054b90b1)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 1298191366** [comment]
1、目前需要自行配置跨域
2、已修复，待新版本发布
3、不支持
