### ISSUE TITLE
分组报表动态列如何做行合计？

### ISSUE THREAD

**Issue by zhaoliang83121** [jeecgboot/JimuReport#2838]
##### 版本号：
1.6

##### 问题描述：
分组报表动态列如何做行合计？

##### 错误日志&截图：
![46bdf4495ae78db59688ecddcd32a985](https://github.com/user-attachments/assets/12dde48a-ba6d-438d-b694-569b5e14ae8d)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by hoperunChen** [comment]
可以直接使用表达式来计算横向分组的合计，如下：
![QQ_1722570227793](https://github.com/user-attachments/assets/5eb6fada-0eec-401a-8684-734c6b7c0ff9)

参考文档：https://ojrjjvdr7z.k.topthink.com/jimureport/group/groupTotal.html
