### ISSUE TITLE
请问相关源码有开源吗

### ISSUE THREAD

**Issue by thaiyang2009** [jeecgboot/JimuReport#2841]
##### 问题描述：
<img width="625" alt="image" src="https://github.com/user-attachments/assets/56474e10-e2b7-48cc-b43a-8622b8d5b2b8">

**请问相关源码有开源吗**

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
功能免费，源码不提供
