### ISSUE TITLE
PDF数据导出不连续

### ISSUE THREAD

**Issue by liph7268** [jeecgboot/JimuReport#2844]
##### 版本号：
1.6.6

##### 问题描述：
PDF数据导出不连续

##### 错误截图：
![61UK858VJEEJ)Q}VF _H@RS](https://github.com/user-attachments/assets/dde11124-20ad-4323-9adb-d4019f0c1ccf)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by jeecgos** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by jeecgos** [comment]
ws

**Comment by 1298191366** [comment]
未复现。请在官网制作报表示例并提供ID或升级到最新版再次尝试
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.7.8</version>
</dependency>
```

**Comment by liph7268** [comment]
这个问题是由于在模板中对字段设置了自动回行导致的，只要给字段设置了自动回行，导出pdf就会出现导出不连续的情况

**Comment by 1298191366** [comment]
改过了，升级版本，你的版本太低了，升级到最新版本如还有问题 请提供报表json和测试数据，否则无法重现
