### ISSUE TITLE
积木报表横向分组小计问题

### ISSUE THREAD

**Issue by tangyangjun88** [jeecgboot/JimuReport#2845]
##### 版本号：
1.7.8

##### 问题描述：

积木报表横向分组最后的小计当只有一列是小计显示错误的数
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/0f0519bc-a7ac-4d1a-a18e-7e300a62275b)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
cr

**Comment by jeecgos** [comment]
已修复，待新版本发布。

**Comment by hoperunChen** [comment]
已修复，待新版本发布。
