### ISSUE TITLE
导出的PDF有大量空白间断

### ISSUE THREAD

**Issue by superman4808** [jeecgboot/JimuReport#2847]
##### 版本号：
V1.6.3

##### 问题描述：
导出的PDF有大量空白间断

##### 错误日志&截图：
![间断](https://github.com/user-attachments/assets/f304b2ec-0eda-4d59-bc30-66b766be2c7d)

##### 重现步骤：
[报表配置.zip](https://github.com/user-attachments/files/16455822/default.zip)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
