### ISSUE TITLE
英文长文本自动换行时，一个单词没有完整换行，被从中间截断，要怎么设置

### ISSUE THREAD

**Issue by 475857633** [jeecgboot/JimuReport#2849]
版本号：
1.7.9（官网在线使用）

问题描述：
一段英文长文本设置了自动换行之后，出现换行时一个英文单次被从中间切断了

错误日志&截图：
![image](https://github.com/user-attachments/assets/b17be3ca-a37d-4ce6-bf98-59382521399c)
![image](https://github.com/user-attachments/assets/2e52f8ca-e7a3-40ee-9b3a-f0099928fc84)

重现步骤：
官网制作的报表id ： 975210043635224576

**Comment by jeecgos** [comment]
暂不支持，归集：#138
