### ISSUE TITLE
导入的excel，预览格式混乱 

### ISSUE THREAD

**Issue by ProfGuo** [jeecgboot/JimuReport#285]
##### 问题描述：
导入的excel，点预览，数据混乱

##### 截图&代码：
![image](https://user-images.githubusercontent.com/82938590/119808284-8e266a00-bf16-11eb-95da-038ad4fdbf78.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
原excel是什么样的？

**Comment by ProfGuo** [comment]
原excel 长这样
![image](https://user-images.githubusercontent.com/82938590/120189320-c6e17e80-c249-11eb-9a1c-76b2e39a8d87.png)

**Comment by 1298191366** [comment]
可否上传excel设置的原文件，我们这边有问题修复一下

**Comment by ProfGuo** [comment]
问题又出现了，本来格式是好的，在本地改了一下之后 再保存，预览的行顺序就 就乱七八糟了
![Uploading image.png…]()

**Comment by ProfGuo** [comment]
[财经报表-new副本770120210621205926.xlsx](https://github.com/jeecgboot/JimuReport/files/6730438/-new.770120210621205926.xlsx)

**Comment by ProfGuo** [comment]
大佬 救命！

**Comment by tygithub1** [comment]
经测试，上传后和原excel样式基本保持一致。数据乱，请查看自己的数据源！
