### ISSUE TITLE
旧版积木报表没有仪表盘大屏功能，如果想要使用仪表盘功能，是需要怎么处理呢，安装仪表盘依赖，升级到最新版本？

### ISSUE THREAD

**Issue by 526589640** [jeecgboot/JimuReport#2852]
##### 问题描述：
我们公司使用的是旧版积木报表没有仪表盘大屏功能，如果想要使用仪表盘功能，是需要怎么处理呢，安装仪表盘依赖，升级到最新版本？

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/5b56d35b-85b8-46dc-bc13-a43269c8fad3)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
https://www.toutiao.com/article/7394329185667318299/
