### ISSUE TITLE
提示保存成功，但是刷新报表，发现刚配置的东西没了，这块是不是并发问题

### ISSUE THREAD

**Issue by 441004767** [jeecgboot/JimuReport#2853]
##### 版本号：
1.7.8

##### 问题描述：
打开设计，修改了下，然后保存，提示保存成功，当时刷新了下，发下刚才新增的东西没了

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/8426403c-642b-40be-bc47-652d6e55748f)
![image](https://github.com/user-attachments/assets/39ee967f-4e28-4af9-a77f-d06883e843c6)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
好像没加乐观锁，有别人操作？

**Comment by 441004767** [comment]
就我自己一个人操作，本地启动的项目

**Comment by 441004767** [comment]
放着不动，我观察了下数据库，发现会自动保存jimu_report.update_time 会变，然后刷新页面发现数据被还原了

**Comment by zhangdaiscott** [comment]
有别人操作？

**Comment by 441004767** [comment]
没有别人操作，我只是打开了页面，放在那里，然后看了下数据库，发现每一分钟就会自动保存一次

**Comment by 1298191366** [comment]
已优化，后期版本 当多个人进行保存时，其中一个人保存后，其他人就保存不了了。
