### ISSUE TITLE
这哪是统计报表呀

### ISSUE THREAD

**Issue by thappyworld** [jeecgboot/JimuReport#2856]
作为统计报表，只需显示统计结果就行了，为什么一定要显示具体的数据呀，本来是个好工具，却没法用，可惜了！

例如图片中，不需要显示红色线条划去的具体数据

![image](https://github.com/user-attachments/assets/138a7196-c10c-4dcb-85f3-4181ee96ed95)

![image](https://github.com/user-attachments/assets/516eb6c7-f8c3-45b6-ab88-6f5bc82b7de0)

**Comment by zhangdaiscott** [comment]
你自己写sql汇总就好了，为什么非得这么用
