### ISSUE TITLE
打印时显示不全

### ISSUE THREAD

**Issue by zhaoshuai332** [jeecgboot/JimuReport#2859]
##### 问题描述：
报表ID:980260657457090560
打印设置A3纸,打印时显示不全,是否是纸张横向未生效

##### 错误日志&截图：
![171a7adc53d315ed1ff02d09ea4421d](https://github.com/user-attachments/assets/12b63257-413e-4d4e-9e51-e4260f071e99)
![341ef1b3f6d310a89c475ba45d6e5ab](https://github.com/user-attachments/assets/b94ea729-9799-4255-ba87-b5263cb968f7)
![78664795e116cb8489c127ceebef485](https://github.com/user-attachments/assets/109ca7bd-09f3-4745-8184-6daca9bd6c29)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhaoshuai332** [comment]
设置为动态合并的单元格有多列时,跨页显示异常

**Comment by jeecgos** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复下一版本发布。

效果如下：
![image](https://github.com/user-attachments/assets/9baeba05-5022-4d14-8493-ef67a4c5a7d0)
