### ISSUE TITLE
希望优化查询sql的日志

### ISSUE THREAD

**Issue by KingStarPlus** [jeecgboot/JimuReport#2861]
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/6ba6a51e-e8b4-4097-8e25-9e00a6479af4)

![image](https://github.com/user-attachments/assets/9674aa4a-9af7-4985-b4ed-4f092cbf9144)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by hoperunChen** [comment]
新版本中为了系统安全，我们调整了sql查询，参数不会直接在sql中显示。
sql的参数单独在日志中打印了。
![image](https://github.com/user-attachments/assets/79ffc6e0-4679-406d-965a-2cca15475593)
