### ISSUE TITLE
关于jimureport的页面和相关接口是否开源的问题

### ISSUE THREAD

**Issue by furenqiang** [jeecgboot/JimuReport#2863]
##### 版本号：
v1.7.9 | 2024-07-09

##### 问题描述：
报表的接口和前端页面都打到了start依赖<dependency>
            <groupId>org.jeecgframework.jimureport</groupId>
            <artifactId>jimureport-spring-boot-starter</artifactId>
            <version>${jimureport.version}</version>
        </dependency>里面，我想问下这个报表页面的代码是开源的吗？还有/jmreport/**相关的接口是开源的吗？

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/c4edf6f3-7dc3-4435-80e3-55cdbd9345be)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
代码不开源，功能免费使用
