### ISSUE TITLE
数据集管理bug

### ISSUE THREAD

**Issue by douyuhangQQ** [jeecgboot/JimuReport#2866]
##### 错误日志&截图：

![image](https://github.com/user-attachments/assets/6ceec649-02ef-491e-8569-7c6d6dc3002a)
<img width="683" alt="39ebade1a545d36d1f372fe87221e02" src="https://github.com/user-attachments/assets/206361de-5172-4b7c-a3c3-228b9e61c273">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by hoperunChen** [comment]
请检查一下你的数据集市列表数据还是单条数据？

如果是列表数据，使用#{}取值，每行默认只能展示一个数据集（[多源报表](https://help.jeecg.com/jimureport/multi-data-table.md.html)需要额外配置）;
如果是对象，则需要取消勾选数据集设置中的是否集合复选框并且使用${}取值，对象数据集每行可以有多个数据集数据。
或者尝试使用[分版](https://help.jeecg.com/jimureport/datareport/partitioning.html)功能
