### ISSUE TITLE
根据条件实现字体加粗的效果，用2个单元格来处理，一个显示粗体，一个是普通字体

### ISSUE THREAD

**Issue by 441004767** [jeecgboot/JimuReport#2868]
##### 版本号：

1.7.9
##### 问题描述：
我想根据条件，实现字体加粗的效果
效果图
![image](https://github.com/user-attachments/assets/b4f98cbd-8850-43b2-b238-547b2a912651)
操作步骤，用2个单元格来处理，一个显示粗体I9，一个是普通字体J9，然后使用case做处理，但是结果是空值，对应单元格无法显示
![image](https://github.com/user-attachments/assets/b1a752ba-e0af-4113-9601-aa160fde48e9)
最终效果，
![image](https://github.com/user-attachments/assets/b1009949-3f65-459a-b435-1e45987901ab)

##### 重现步骤：
=CASE('#{gwdata.isBold}' == 1,I9,J9)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
CASE表达式的结果参数暂不支持单元格坐标。
暂不支持，归集：#138
