### ISSUE TITLE
曲线打印显示的是默认数据不是根据时间参数展示的实时数据

### ISSUE THREAD

**Issue by 675592567** [jeecgboot/JimuReport#2869]
##### 错误日志&截图：
![Uploading 1723117807920.jpg…]()
![image](https://github.com/user-attachments/assets/914dc37d-b97b-4761-a153-6105683347b0)
![image](https://github.com/user-attachments/assets/c7ebec7c-0a23-4c6b-b421-7d2bef41dd7d)
![image](https://github.com/user-attachments/assets/2a014b07-5749-43e9-bb41-a6026c16c460)

##### 重现步骤：1 先设计图表,曲线图先根据sql去查询,条件是两个时间,然后曲线图可以根据默认时间去展示.
                             2 实际操作预览图表中,预览的数据是根据我们选择的时间生成的曲线
                            3一点击打印就曲线就变成了默认的曲线,无法根据我们之前设定的时间去展示

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
已修复，下个版本更新。
#2816
