### ISSUE TITLE
打war包在tomcat中运行，tomcat启动后访问不到页面

### ISSUE THREAD

**Issue by xiaolangzhong** [jeecgboot/JimuReport#2871]
##### 版本号：
1.7
##### 问题描述：
打war包在tomcat中运行，应该怎样配置才能访问到页面

##### 错误日志&截图：
![1](https://github.com/user-attachments/assets/9cddf1f8-12b6-4e0d-b474-b369fd195462)
![2](https://github.com/user-attachments/assets/e5006c7f-696c-4702-b08d-33ebbea19ff5)
![3](https://github.com/user-attachments/assets/58a734aa-1ff1-406a-ab38-974f2b548768)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不能这么简单改

**Comment by xiaolangzhong** [comment]
噢噢，那麻烦问下如果我想打war包通过tomcat启动，应该怎么配置下啊

**Comment by xiaolangzhong** [comment]
> 不能这么简单改

是需要改yml文件吗

**Comment by zhangdaiscott** [comment]
参考
https://help.jeecg.com/java/publish/war.html

**Comment by xiaolangzhong** [comment]
> 参考 https://help.jeecg.com/java/publish/war.html

按照这个调整了，生成的war包放到tomcat中启动后，还是访问不到啊

**Comment by xiaolangzhong** [comment]
> 参考 https://help.jeecg.com/java/publish/war.html

![1](https://github.com/user-attachments/assets/cdb6a05d-b348-4a86-bf1f-0c9808995ded)
![2](https://github.com/user-attachments/assets/8ff78e94-03c5-4297-adf1-7971579b4c86)
控制台没看到打印出来访问地址

**Comment by xiaolangzhong** [comment]
![3](https://github.com/user-attachments/assets/dbb5b738-8b9f-4898-b14d-c6eef795bc21)
可以了，启动类继承SpringBootServletInitializer、重写config方法、用tomcat9
