### ISSUE TITLE
导出excel中能否包含非图片其他类型的文件链接

### ISSUE THREAD

**Issue by hunqian100** [jeecgboot/JimuReport#2872]
##### 版本号：
1.6.6

##### 问题描述：
导出excel时，添加一个文件路径链接，用于读取服务器的URL文件

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by hoperunChen** [comment]
没看懂你的需求。你是要增加一个插入文件的功能？

**Comment by hunqian100** [comment]
是的，但是因为我最后要导出excel文件，我在本地用excel测试的时候，发现不能在excel文件里面插入pdf，但是可以插入一个超链接，所以就想问问这个设计器有没有这种功能

**Comment by hunqian100** [comment]
> 没看懂你的需求。你是要增加一个插入文件的功能？

是的，但是因为我最后要导出excel文件，我在本地用excel测试的时候，发现不能在excel文件里面插入pdf，但是可以插入一个超链接，所以就想问问这个设计器有没有这种功能

**Comment by zhangdaiscott** [comment]
没有
