### ISSUE TITLE
业务清单套打格式若干问题

### ISSUE THREAD

**Issue by renbooc** [jeecgboot/JimuReport#2875]
##### 版本号：
积木报表1.6.6

##### 问题描述：
问题1： 按照操作文档上传图片设置为套打图片，请问此图片的大小如何确定，是否需要同【打印设置】中的像素宽高大小一致？
问题2： 打印多个明细内容时，会将底部汇总金额往下挤，导致错位，请问如何处理类似问题
问题3： 积木报表如何获取到当前页数值和总页数值

##### 错误日志&截图：
问题1图示
![image](https://github.com/user-attachments/assets/d86ee288-c6bd-4309-b6fc-fcd755f1dd96)

问题2图示
![image](https://github.com/user-attachments/assets/e5375958-30bf-4eec-b4ad-0bb23d51f3bb)
![image](https://github.com/user-attachments/assets/0f53554d-8a31-401e-b9db-791cda918c8c)

问题3图示
![image](https://github.com/user-attachments/assets/e5a18ab9-ede7-42b6-b0c5-a94432c6d487)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
问题1：图片不会受纸张大小的影响；你需要自己保证图片和打印纸张的大小一致。
问题2：暂不支持 归集 #138
问题3：暂不支持 重复 #2839
