### ISSUE TITLE
写SQL的框框希望能拖动，默认大一些，另外放大后就没法还原原大小了

### ISSUE THREAD

**Issue by eyuan** [jeecgboot/JimuReport#2876]
![image](https://github.com/user-attachments/assets/aba4ca62-2a15-462e-b657-1b7fe1e9c7f4)

**Comment by zhangdaiscott** [comment]
鼠标放上去有个放大按钮
![image](https://github.com/user-attachments/assets/b126e46d-f60d-44db-bbab-575282bda5db)
