### ISSUE TITLE
集成后导致项目中所有事务失效

### ISSUE THREAD

**Issue by Jason8080** [jeecgboot/JimuReport#2877]
##### 版本号：
1.7.8

##### 问题描述：
首先我采用的是独立数据源的集成方式, 
然后发现根据文档的方式无法路由到独立的数据源
经过努力添加如下配置后可以各自(项目和积木)独立数据源了
但是发现项目中的所有方法的@Transactional(rollbackFor = Exception.class)都失效了
失效鉴定的方法是: TransactionSynchronizationManager.getCurrentTransactionName() (为null是非事务环境, 有值则在事务中, 但全项目都为null, 而去除积木的依赖(jimureport-spring-boot-starter)后恢复正常...)

```java
@Slf4j
@EnableConfigurationProperties(JmDataSourceProperties.class)
public class JmDataSourceAutoConfiguration {

    @Bean("minidaoDataSource")
    public DataSource dataSource() {
        DruidDataSource dataSource = new DruidDataSource();
        dataSource.setDriverClassName("oracle.jdbc.OracleDriver");
        dataSource.setUrl("jdbc:oracle:thin:@host:port:server");
        dataSource.setUsername("username");
        dataSource.setPassword("password");
        return dataSource;
    }

    @Bean("miniDaoHandler")
    public MiniDaoHandler miniDaoHandler(@Qualifier("minidaoDataSource") DataSource dataSource, EmptyInterceptor emptyInterceptor, ApplicationContext applicationContext) {
        MiniDaoHandler miniDaoHandler = new MiniDaoHandler();
        miniDaoHandler.dataSource = dataSource;
        miniDaoHandler.setApplicationContext(applicationContext);
        miniDaoHandler.setEmptyInterceptor(emptyInterceptor);
        return miniDaoHandler;
    }

    @Bean
    public LdwMiniDaoBeanScannerConfigurer ldwMiniDaoBeanScannerConfigurer(Environment env) {
        return new LdwMiniDaoBeanScannerConfigurer(env);
    }
}
```

##### 错误日志&截图：
积木本身没有异常, 只是影响了业务系统的事务, 导致失效

##### 重现步骤：
必现, 任何一个项目内的应有的事务, 都没了

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
cr

**Comment by 1298191366** [comment]
你可以尝试一下自定义事务管理器，配置完成之后经测试无问题
![image](https://github.com/user-attachments/assets/30f142fb-afe8-46e6-a76d-336752ee97ba)
参考：
![image](https://github.com/user-attachments/assets/b41809ed-94f5-4db5-8648-9b1c87e25615)
