### ISSUE TITLE
接口导出pdf是不是暂时调不了，新文档上面也没有，调旧文档上面的可以吗

### ISSUE THREAD

**Issue by taohu** [jeecgboot/JimuReport#2879]
##### 错误日志&截图：
<img width="1280" alt="jimu" src="https://github.com/user-attachments/assets/6168ab5f-d9fa-4e02-822a-9f6ed5fea2c0">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
后期提供
