### ISSUE TITLE
在sqlserver数据库下查询如果有order by 结尾，在页面查询count时会报错：除非另外还指定了 TOP 或 FOR XML，否则，ORDER BY 子句在视图、内联函数、派生表、子查询

### ISSUE THREAD

**Issue by AXXZSTHL** [jeecgboot/JimuReport#2880]
##### 错误日志&截图：
![IMG_9553](https://github.com/user-attachments/assets/d4ad5d96-0451-4f3c-bc50-cf2812b3c331)

##### 重现步骤：
在sqlserver数据库下查询如果有order by 结尾

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
下个版本修复
