### ISSUE TITLE
若依pro升级到1.7.8后，点设计报表提示不存在租户编号错误

### ISSUE THREAD

**Issue by renbooc** [jeecgboot/JimuReport#2881]
##### 版本号：
1.6.6版本升级至1.7.8

##### 问题描述：
![image](https://github.com/user-attachments/assets/68dd714b-10da-4a9f-86af-d61eab6ba5b2)

ruoyi-vue-pro集成积木报表，从1.6.6升级至1.7.8，1.6.6版本能正常打开报表设计器并能设计报表，升级后无法进行设计报表操作，后端提示: Error updating database.  Cause: java.lang.NullPointerException: TenantContextHolder 不存在租户编号

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/dc5a3500-b983-423c-a125-7156c386ecac)
![image](https://github.com/user-attachments/assets/82c612e1-106a-4a0e-9a36-0fe10b3de702)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
这是你自己的代码报错

**Comment by renbooc** [comment]
若依知识星球里已有解决方案，已解决！
