### ISSUE TITLE
求和sum加了其他不需要的内容

### ISSUE THREAD

**Issue by hdthhh** [jeecgboot/JimuReport#2882]
##### 问题描述：
使用sum函数求和时，使用的时（E6）类写法确定求知的所有数值，但当E6下方还有其他数值，而求和的结果在数值下方时，该写法会把这些其他的数值也算进去，
例如，这个额度原本只想要加这些200，却错误地加上了下方地编号，导致结果比原本多加了18个编号的值，变成3618
当编号在额度上方时也会出现这个问题

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/862a2a6c-9cc6-4e5d-ba74-c8e2e84eb30e)
![image](https://github.com/user-attachments/assets/c7df0232-cfa9-41da-b574-6e8500717f1a)
![image](https://github.com/user-attachments/assets/2bd7ad6e-e487-4ea7-b115-822d18e94262)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
请先升级到最新版本，参考[单元格计算规则](https://help.jeecg.com/jimureport/function/cellCalculation.html)
