### ISSUE TITLE
图片循环怎么在模板里面配置样式呀

### ISSUE THREAD

**Issue by taohu** [jeecgboot/JimuReport#2883]
##### 错误日志&截图：
<img width="671" alt="jm1" src="https://github.com/user-attachments/assets/ab038b9b-e3cf-4965-beab-12537b05959b">
<img width="846" alt="jm2" src="https://github.com/user-attachments/assets/21c62ce4-a893-481a-9367-08c593025212">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持
