### ISSUE TITLE
行操作

### ISSUE THREAD

**Issue by zxl20000616** [jeecgboot/JimuReport#2884]
##### 问题描述：
我的Reason 如何跟着每行数据呢 一行数据跟着一个reason 而不是整个一起出来

##### 重现步骤：
![image](https://github.com/user-attachments/assets/d5d238f1-43f7-4e01-8ef6-391904860bcb)
![image](https://github.com/user-attachments/assets/2e741622-8dd9-4685-9d44-5915e178474e)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
设置循环块
