### ISSUE TITLE
图形报表的点地图，怎么设置只显示数值和区域名

### ISSUE THREAD

**Issue by amwylig** [jeecgboot/JimuReport#2885]
##### 错误日志&截图：
![1723543046009](https://github.com/user-attachments/assets/4b50e94e-339e-4511-a11e-6cb0366e1d56)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
ws

**Comment by amwylig** [comment]
> ws

ws是啥意思呐？？
