### ISSUE TITLE
自定义函数：处理数组会提示行渲染错误

### ISSUE THREAD

**Issue by XXXXXXasd** [jeecgboot/JimuReport#2886]
##### 版本号：
1.7.9

##### 问题描述：
自定义函数：例如从mysql中获取的了10条数据，每一条数据上都一个payload字段改字段是一个数组，当我使用自定义函数的传入#{item.payload},会提示行渲染错误

##### 重现步骤：
从数据库中获取到数组格式的数组，例如[{"a":1,"b":2},{},{},{}], 自定义一个函数继承AbstractVariadicFunction（函数名随意arr_test），当我在单元格里使用该自定义函数=arr_test(#{item.payload}) 这个时候就会报错,会提示行渲染错误

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
暂不支持自定义函数接收数组数据，归集：#138
