### ISSUE TITLE
开启纵向分组后，原排序失效

### ISSUE THREAD

**Issue by 01Fan-Xing** [jeecgboot/JimuReport#2887]
##### 错误日志&截图：
开启前：
![image](https://github.com/user-attachments/assets/3585604f-80f3-4786-aae1-5ed51b3b3ebc)
开启后：
![image](https://github.com/user-attachments/assets/d2c0ff5e-989d-4d94-b762-b1bd60d891ae)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
开启纵向分组后，默认会对数据进行排序。您可以使用[自定义文本排序](https://help.jeecg.com/jimureport/group/dataSort.html#32-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%96%87%E6%9C%AC%E6%8E%92%E5%BA%8F)功能来实现自定义的排序。
