### ISSUE TITLE
1.7.8,prod模式 用户查看报表 报错发布模式不允许使用在线配置！！

### ISSUE THREAD

**Issue by RuiZhang-cn** [jeecgboot/JimuReport#2888]
##### 版本号：
            <version>1.7.8</version>

##### 问题描述：
用户查看报表 提示当前积木平台模式为，发布模式不允许使用在线配置！！
配置为:lowCodeMode: prod
想实现生产环境下 彻底关闭在线报表设计,但是不影响用户查看,现在配置为prod之后用户查看图表就报错.
##### 错误日志&截图：
 低代码模式，拦截请求路径：/jmreport/qurestSql
{
  "code": 500,
  "success": false,
  "message": "当前积木平台模式为，发布模式不允许使用在线配置！！",
  "timestamp": 1723548023422
}
##### 重现步骤：
配置为:lowCodeMode: prod 然后
使用普通用户角色查看任意报表,

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
预览报表不会报错啊，不让设计

**Comment by RuiZhang-cn** [comment]
> 预览报表不会报错啊，不让设计
      lowCodeMode: prod 然后普通用户访问
![image](https://github.com/user-attachments/assets/c9607f32-dd36-4132-9f66-78f5ba2d7114)

**Comment by zhangdaiscott** [comment]
我们看下

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
