### ISSUE TITLE
docker数据持久化、迁移数据问题

### ISSUE THREAD

**Issue by JinCheng666** [jeecgboot/JimuReport#2889]
##### 版本号：
1.7.8

##### 问题描述：
用docker启动的积木报表，如何将docker中的**数据持久化**？只持久化mysql的数据就可以了吗？还是积木报表的数据也得持久化出来？
另外升级、迁移docker时，如何能保证数据的连贯性？（数据不被覆盖）

##### docker启动方式：
参考这个方式启动的，源码克隆的是github上的源码，checkout到了v1.7.8
https://help.jeecg.com/jimureport/docker.html

第一步：下载项目
    git clone https://gitee.com/jeecg/JimuReport.git
   git checkout v1.7.8
第二步：进入项目 jimureport-demo 根目录
    cd JimuReport/jimureport-example
第三步：maven执行package
    mvn clean package
第四步：执行命令，生成镜像
    docker-compose up -d

**Comment by zhangdaiscott** [comment]
如果考虑稳定，就把数据库mysql单独出去，报表配置数据都存在数据库里面

**Comment by JinCheng666** [comment]
> 如果考虑稳定，就把数据库mysql单独出去，报表配置数据都存在数据库里面

@zhangdaiscott 您好，那就是说数据和配置都在mysql中存储。这个docker内没有存储数据和配置：jimureport
不知道我的理解对不对

**Comment by pupss89345** [comment]
@JinCheng666  
如果要更新替換 Docker 內的初始數據庫 
請在Dockerfile 裡面替換 
`CMD java -DMYSQL-HOST=jimureport-mysql -Dfile.encoding=utf-8 -Djava.security.egd=file:/dev/./urandom -jar jimureport-example-1.9.jar`
將 jimureport-mysql 替換成你數據庫的IP
且將 application-dev.yml 裡面的 datasource 改成你要遷移的數據庫 IP 與帳密
