### ISSUE TITLE
三联纸（240mm*140mm）打印问题，预览时正常，打印出的内容显示不全

### ISSUE THREAD

**Issue by liph7268** [jeecgboot/JimuReport#2890]
##### 版本号：
1.6.6

##### 问题描述：
三联纸（240mm*140mm）打印问题，预览时正常，打印出的内容显示不全

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/e8c130f0-9aae-4d2a-b09f-e7e3ba0981be)

##### 重现步骤：
设置
![image](https://github.com/user-attachments/assets/97e05854-bc76-4cc8-b1de-72a848d2df92)
打印预览
![image](https://github.com/user-attachments/assets/f705937b-5800-4427-b864-43a980a53b51)
打印后
![image](https://github.com/user-attachments/assets/86e50b2f-9177-44bc-a231-fd369c6f7188)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
遇到问题先升级版本，老版本无法处理
