### ISSUE TITLE
Api数据源设置了分页，如何计算API数据集所有数据的和? 

### ISSUE THREAD

**Issue by JHCkenan** [jeecgboot/JimuReport#2891]
##### 问题描述：
1. sum只能计算当页和，DBSUM不能在Api数据集使用。那么如何计算API数据集所有数据的和?
2. 通过sum计算某列的和，如何通过条件判断只取其中某些行，而不是该列的全部行？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
暂不支持，归集：#138
