### ISSUE TITLE
套版导出成EXCEL格式用OFFICE打开会乱掉，但是WPS可以正常打开，请问怎样才能用OFFICE正常打开导出的EXCEL格式的套版

### ISSUE THREAD

**Issue by wangxianxian1** [jeecgboot/JimuReport#2892]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
套打时给打印用的，导出excel暂时还不能保证样式完全一致。
