### ISSUE TITLE
积木报表：自定义api数据源属性字段  

### ISSUE THREAD

**Issue by WHO57** [jeecgboot/JimuReport#2895]
##### 错误日志&截图：
![Snipaste_2024-08-15_11-23-13](https://github.com/user-attachments/assets/118b4a6a-a364-4f9f-8aa0-63d875e53f2a)
![Snipaste_2024-08-15_11-23-40](https://github.com/user-attachments/assets/b312a237-11cc-4a4e-b68a-46ceed654fd2)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by WHO57** [comment]
追加问题：
对于报表中自定义（ x轴 y轴 值 ） 属性的方式，暂时将返回的数据 key值改为 name type value 后预览数据图表显示正常。
![Snipaste_2024-08-15_14-28-03](https://github.com/user-attachments/assets/c171d248-8af7-4b17-9d43-2b8e477897b0)
![Snipaste_2024-08-15_14-27-37](https://github.com/user-attachments/assets/bc536f49-3cd3-4211-93cb-6d1d9f2b31ae)

但是，因为我的数据集是采取了分页，预览中    点击下一页按钮   图表的数据不改变    勾选其他条件后 点击查询按钮  图表只更新第一次返回的数据    

也尝试使用  图表的  定时刷新功能  但是传递到后端的值 pageNo和pageSize始终没有改变

**Comment by WHO57** [comment]
追加问题：横向纵向组合动态列分组中  横向表头列宽度异常

![Snipaste_2024-08-16_16-08-11](https://github.com/user-attachments/assets/db205d12-4435-44ff-8304-f5cfa556c23d)

是否可以在横向纵向组合动态列分组实现这样的表头关系

![Snipaste_2024-08-16_16-22-31](https://github.com/user-attachments/assets/60711295-cb50-4444-947a-153b00f5d9ab)

**Comment by hoperunChen** [comment]
问题二：图表不支持分页查询。
问题三：请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by WHO57** [comment]
问题3：
报表设计页面：
![Snipaste_2024-08-19_08-21-12](https://github.com/user-attachments/assets/bfd054b1-9e4a-4875-868f-7bf39cf5848a)
预览界面：
![Snipaste_2024-08-19_08-21-19](https://github.com/user-attachments/assets/8da51dbb-a37a-4897-baaa-347bc211d4e7)
api解析返回的数据集：
{
    "total": 129600,
    "data": [
        {
            "unit": "A",
            "bayName": "间隔1",
            "description": "遥测信号104SZJ1",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:00",
            "tagName": "yc1",
            "type": "AB线电压",
            "value": "12.824"
        },
        {
            "unit": "A",
            "bayName": "间隔1",
            "description": "遥测信号104SZJ1",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:02",
            "tagName": "yc1",
            "type": "AB线电压",
            "value": "31.711"
        },
        {
            "unit": "A",
            "bayName": "间隔1",
            "description": "遥测信号104SZJ1",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:04",
            "tagName": "yc1",
            "type": "AB线电压",
            "value": "14.748"
        },
        {
            "unit": "A",
            "bayName": "间隔1",
            "description": "遥测信号104SZJ1",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:06",
            "tagName": "yc1",
            "type": "AB线电压",
            "value": "24.000"
        },
        {
            "unit": "A",
            "bayName": "间隔1",
            "description": "遥测信号104SZJ1",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:08",
            "tagName": "yc1",
            "type": "AB线电压",
            "value": "2.375"
        },
        {
            "unit": "A",
            "bayName": "间隔1",
            "description": "遥测信号104SZJ1",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:10",
            "tagName": "yc1",
            "type": "AB线电压",
            "value": "36.264"
        },
        {
            "unit": "A",
            "bayName": "间隔1",
            "description": "遥测信号104SZJ1",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:12",
            "tagName": "yc1",
            "type": "AB线电压",
            "value": "30.649"
        },
        {
            "unit": "A",
            "bayName": "间隔1",
            "description": "遥测信号104SZJ1",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:14",
            "tagName": "yc1",
            "type": "AB线电压",
            "value": "19.058"
        },
        {
            "unit": "A",
            "bayName": "间隔1",
            "description": "遥测信号104SZJ1",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:16",
            "tagName": "yc1",
            "type": "AB线电压",
            "value": "10.226"
        },
        {
            "unit": "A",
            "bayName": "间隔1",
            "description": "遥测信号104SZJ1",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:18",
            "tagName": "yc1",
            "type": "AB线电压",
            "value": "39.994"
        },
        {
            "unit": "W",
            "bayName": "间隔1",
            "description": "遥测信号104QCJK2",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:00",
            "tagName": "yc2",
            "type": "AB线电压",
            "value": "20.651"
        },
        {
            "unit": "W",
            "bayName": "间隔1",
            "description": "遥测信号104QCJK2",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:02",
            "tagName": "yc2",
            "type": "AB线电压",
            "value": "37.956"
        },
        {
            "unit": "W",
            "bayName": "间隔1",
            "description": "遥测信号104QCJK2",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:04",
            "tagName": "yc2",
            "type": "AB线电压",
            "value": "14.164"
        },
        {
            "unit": "W",
            "bayName": "间隔1",
            "description": "遥测信号104QCJK2",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:06",
            "tagName": "yc2",
            "type": "AB线电压",
            "value": "38.444"
        },
        {
            "unit": "W",
            "bayName": "间隔1",
            "description": "遥测信号104QCJK2",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:08",
            "tagName": "yc2",
            "type": "AB线电压",
            "value": "24.271"
        },
        {
            "unit": "W",
            "bayName": "间隔1",
            "description": "遥测信号104QCJK2",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:10",
            "tagName": "yc2",
            "type": "AB线电压",
            "value": "9.224"
        },
        {
            "unit": "W",
            "bayName": "间隔1",
            "description": "遥测信号104QCJK2",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:12",
            "tagName": "yc2",
            "type": "AB线电压",
            "value": "46.502"
        },
        {
            "unit": "W",
            "bayName": "间隔1",
            "description": "遥测信号104QCJK2",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:14",
            "tagName": "yc2",
            "type": "AB线电压",
            "value": "22.005"
        },
        {
            "unit": "W",
            "bayName": "间隔1",
            "description": "遥测信号104QCJK2",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:16",
            "tagName": "yc2",
            "type": "AB线电压",
            "value": "32.052"
        },
        {
            "unit": "W",
            "bayName": "间隔1",
            "description": "遥测信号104QCJK2",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:18",
            "tagName": "yc2",
            "type": "AB线电压",
            "value": "8.471"
        },
        {
            "unit": "A",
            "bayName": "间隔2",
            "description": "遥测信号104QCJK974",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:00",
            "tagName": "yc974",
            "type": "A相电流",
            "value": "44.592"
        },
        {
            "unit": "A",
            "bayName": "间隔2",
            "description": "遥测信号104QCJK974",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:02",
            "tagName": "yc974",
            "type": "A相电流",
            "value": "31.718"
        },
        {
            "unit": "A",
            "bayName": "间隔2",
            "description": "遥测信号104QCJK974",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:04",
            "tagName": "yc974",
            "type": "A相电流",
            "value": "20.292"
        },
        {
            "unit": "A",
            "bayName": "间隔2",
            "description": "遥测信号104QCJK974",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:06",
            "tagName": "yc974",
            "type": "A相电流",
            "value": "63.537"
        },
        {
            "unit": "A",
            "bayName": "间隔2",
            "description": "遥测信号104QCJK974",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:08",
            "tagName": "yc974",
            "type": "A相电流",
            "value": "39.263"
        },
        {
            "unit": "A",
            "bayName": "间隔2",
            "description": "遥测信号104QCJK974",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:10",
            "tagName": "yc974",
            "type": "A相电流",
            "value": "77.352"
        },
        {
            "unit": "A",
            "bayName": "间隔2",
            "description": "遥测信号104QCJK974",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:12",
            "tagName": "yc974",
            "type": "A相电流",
            "value": "31.076"
        },
        {
            "unit": "A",
            "bayName": "间隔2",
            "description": "遥测信号104QCJK974",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:14",
            "tagName": "yc974",
            "type": "A相电流",
            "value": "21.824"
        },
        {
            "unit": "A",
            "bayName": "间隔2",
            "description": "遥测信号104QCJK974",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:16",
            "tagName": "yc974",
            "type": "A相电流",
            "value": "56.375"
        },
        {
            "unit": "A",
            "bayName": "间隔2",
            "description": "遥测信号104QCJK974",
            "stationName": "厂站1",
            "time": "2024-07-01 00:00:18",
            "tagName": "yc974",
            "type": "A相电流",
            "value": "47.345"
        }
    ],
    "count": 1296000
}

**Comment by WHO57** [comment]
> 问题二：图表不支持分页查询。 问题三：请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

问题3所需数据已提交

**Comment by 1298191366** [comment]
已经修复过了，更新到最新版本`1.8.0`即可解决
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.8.0</version>
</dependency>
```
