### ISSUE TITLE
是否能够支持将excel里的公式导出到excel文件中

### ISSUE THREAD

**Issue by yupenglideyupeng** [jeecgboot/JimuReport#2896]
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/464ab128-1b82-4841-81d2-017ecba42b52)
![image](https://github.com/user-attachments/assets/d5023100-d7ba-4e4a-85e6-6ad8f17ab31b)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
不支持
