### ISSUE TITLE
打印预览空白行问题

### ISSUE THREAD

**Issue by renbooc** [jeecgboot/JimuReport#2897]
##### 版本号：
v1.7.8

##### 问题描述：
打印预览，第一页正常显示空白行，第2页无法显示

##### 错误日志&截图：
![f417337c4ae98b59580962db8b5757c](https://github.com/user-attachments/assets/ddde91f5-9678-4620-aa45-f40a858e7995)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
