### ISSUE TITLE
导出错误

### ISSUE THREAD

**Issue by jimjin** [jeecgboot/JimuReport#2898]
##### 版本号：
1.7.9

##### 问题描述：
生成报表 excel导出错误

##### 错误日志&截图：
dy":"{\"excelConfigId\":\"984042157941993472\",\"queryParam\":{\"token\":\"ad0b31c76dc048f5b805714104e8201c\",\"pageNo\":\"1\",\"prod_stock_records__year\":\"2024\",\"prod_stock_records__month\":\"8\",\"pageSize\":10,\"currentPageNo\":\"1\",\"currentPageSize\":10}}"}(String), 192.168.0.1(String), Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36(String), 2024-08-15T21:07:23.177(LocalDateTime), java.lang.NullPointerException(String), NullPointerException: null(String), NullPointerException: null(String), java.lang.NullPointerException
server-dev  | 	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
server-dev  | 	at java.util.regex.Matcher.reset(Matcher.java:309)
server-dev  | 	at java.util.regex.Matcher.<init>(Matcher.java:229)
server-dev  | 	at java.util.regex.Pattern.matcher(Pattern.java:1093)
server-dev  | 	at org.jeecg.modules.jmreport.desreport.service.a.l.b(JmReportExportExcelImpl.java:768)
server-dev  | 	at org.jeecg.modules.jmreport.desreport.service.a.l.a(JmReportExportExcelImpl.java:636)
server-dev  | 	at org.jeecg.modules.jmreport.desreport.service.a.l.a(JmReportExportExcelImpl.java:285)
server-dev  | 	at org.jeecg.modules.jmreport.desreport.service.a.l.exportExcel(JmReportExportExcelImpl.java:147)
server-dev  | 	at org.jeecg.modules.jmreport.desreport.a.a.b(DesignReportController.java:1323)
server-dev  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
server-dev  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
server-dev  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
server-dev  | 	at java.lang.reflect.Method.invoke(Method.java:498)
server-dev  | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
server-dev  | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
server-dev  | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
server-dev  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
server-dev  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
server-dev  | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
server-dev  | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
server-dev  | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
server-dev  | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
server-dev  | 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
server-dev  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
server-dev  | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
server-dev  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
server-dev  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
server-dev  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
server-dev  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
server-dev  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
server-dev  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
server-dev  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:111)
server-dev  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
server-dev  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
server-dev  | 	at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:67)
server-dev  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
server-dev  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)

##### 重现步骤：
预览 -> 选择导出-> Excel

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by 1298191366** [comment]
已修复，待新版本发布
