### ISSUE TITLE
分页打印中如何获取当前页金额

### ISSUE THREAD

**Issue by renbooc** [jeecgboot/JimuReport#2899]
##### 版本号：
1.7.8

##### 问题描述：
1、业务单据分页后，如何获取到当前页的合计金额且将合计金额进行汉字大写展现？在预览页面合计金额显示正确，但最后打印预览时候所以金额就出现的错误，显示为总金额
2、表达式函数是否支持嵌套使用，比如 =cnmoney(sum())的形式

##### 错误日志&截图：
![1](https://github.com/user-attachments/assets/4519b99c-c585-4b43-ba2e-3c550ec98b5d)

![image](https://github.com/user-attachments/assets/45adf81f-b482-460b-b452-c3d5fb5eda43)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 1298191366** [comment]
1、不支持，目前打印就是打印全部 无法每页获取
2、已优化，待新版本发布
