### ISSUE TITLE
不使用自动换行时，若文字过多会出现无法查看到文字的情况，需要双击点开才能查看

### ISSUE THREAD

**Issue by yupenglideyupeng** [jeecgboot/JimuReport#2900]
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/57eaee89-68b8-4c92-8865-d611b83345eb)
![image](https://github.com/user-attachments/assets/6ebaeef8-0f00-43ec-99db-7cdfaad401d4)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by hoperunChen** [comment]
不设置自动换行，文字内容超出单元格再预览时会被截取，只有双击时才可以查看全部内容，在积木报表中，这是正常的。
如果不想内容被截取请使用自动换行。
你可以描述下为什么你的具体使用场景，我们可能会在后续的版本中加入对你的使用场景的支持。

**Comment by yupenglideyupeng** [comment]
> 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

配置都是正常配置，只是没打开自动换行

**Comment by jeecgos** [comment]
如果不设置自动换行，内容过多时内容确实会被截取，这个是正常的。

**Comment by jeecgos** [comment]
但是我这里内容过多时至少会展示第一行数据。所以想确认下，您那一点数据都不展示是怎么复现的？
![QQ_1724586155176](https://github.com/user-attachments/assets/46a307a4-53de-4a6d-86e4-6ca7c4f8713e)
