### ISSUE TITLE
通过判断查询出来的数据集中的一个变量，决定使用的组件类型

### ISSUE THREAD

**Issue by gouchanghong** [jeecgboot/JimuReport#2901]
##### 版本号：
1.7.8

##### 问题描述：
目前积木报表，是否能通过判断查询出来的数据集中的一个变量，决定使用的组件类型？
例如：查询出来图片链接字段是否有值，针对同一个单元格，有值的话，使用图片组件，展示图片，没有值的话，使用文本组件，展示一个文本变量。
找了一下官方文档，没有找到类似的方案。
是否能通过js增强，或者其他方式实现？能否给点指导性代码看下。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
暂不支持，归集：#138
