### ISSUE TITLE
多源报表BUG

### ISSUE THREAD

**Issue by YMccc98** [jeecgboot/JimuReport#2902]
##### 问题描述：
多源报表BUG:使用调用存储过程的数据集在页面查看无法关联，导出却无异常

##### 错误日志&截图：
![1723874494789](https://github.com/user-attachments/assets/961fe234-0268-4d65-988b-825dc78ea30e)
![1723874494795](https://github.com/user-attachments/assets/421c6dd1-907b-45b7-84d6-f14058272dbf)
![1723874494803](https://github.com/user-attachments/assets/d760ec68-0d9c-4530-9484-6bf919a0ab55)
![1723874495852](https://github.com/user-attachments/assets/fbe11431-a505-4c25-bf5f-639a8214faf3)
![1723874579488](https://github.com/user-attachments/assets/2f231913-e6ed-4c1b-be36-6d05cfcd3bcc)

注：我看到后端传回来的show接口(展示报表数据的),存储过程的isList返回null值,我查了数据库isList为1的，其它查表或json的数据集都是有值的,不知道会不会是这个原因导致的？
![image](https://github.com/user-attachments/assets/a9996192-4e42-46d3-9afc-98550996abce)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
cr

**Comment by jeecgos** [comment]
已修复，待新版本发布。
