### ISSUE TITLE
统计和展示有几个问题请问一下

### ISSUE THREAD

**Issue by MonkeyKiller2330** [jeecgboot/JimuReport#2903]
##### 版本号：
免费版

##### 问题描述：
1.统计的底层是使用SQL或api获取数据后，会保存至积木报表自己的列式存储数据库吗然后定时同步？然后再从自己的列式存储数据库进行数据分析与展示吗？还是说就是单纯的讲SQL或api返回的数据统计后就进行展示，不做任何的保存操作，每次界面统计刷新时都会重新通过SQL和api重新获取数据统计。
2.单次查询有数据量的限制吗？比如单次查询最大限制10w条数据。
3.如果数据分析与展示是直接对SQL或api返回的数据进行统计后就展示，会不会将统计的结果进行缓存，后续缓存失效后，再重新获取数据统计后再缓存吗？
望回复

**Comment by zhangdaiscott** [comment]
版本号

图文并茂

**Comment by MonkeyKiller2330** [comment]
![image](https://github.com/user-attachments/assets/0ef1a468-0031-46b7-afde-bb38c1c35c21)
1.比如我创建了一张这样的复杂报表，里面的数据每次刷新时，都是从我配置的数据源重新查询一次吗？还是说会定时将我配置的数据源的数据同步到你的数据库中，每次刷新从你的数据库中获取数据进行统计？
2.查询有数据量限制吗？

**Comment by zhangdaiscott** [comment]
积木报表不负责数据同步，只负责报表渲染，至于查询什么数据，查询多少是你自己配置的事情
