### ISSUE TITLE
jimureport has a privilege escalation vulnerability

### ISSUE THREAD

**Issue by Niiiiko** [jeecgboot/JimuReport#2904]
##### version：
latest

##### Code Analysis：

Analysis org.jeecg.modules.jmreport.config.firewall.interceptor.JimuReportTokenInterceptor
try to analysis preHandle method
![image](https://github.com/user-attachments/assets/5fa698b7-3f3e-447b-958a-d90c16bdafe0)
The core code to bypass the permission check is in the red box in the figure below. After obtaining the previousPage parameter, it enters the j.d function for judgment. Then, after judging by the this.jimuReportShareService.isSharingEffective function, the preHandle of JimuReportTokenInterceptor returns true.
![image](https://github.com/user-attachments/assets/874eebe5-0d6c-45ed-8f01-247e83b5da6a)
step into org.jeecg.modules.jmreport.desreport.service.a.f#isShareingToken
Extract JmReport-Share-Token from request headers, get parameter shareToken after judging through j.c
shareToken is judged through j.c again and passed into this.jimuReportShareDao.getShareByShareToken function
![image](https://github.com/user-attachments/assets/b639f4ef-ad0c-4ab9-badb-2574b98af24a)
This method is used to query whether shareToken exists in the database.
![image](https://github.com/user-attachments/assets/156a60b0-d3ea-4b37-8287-3e415766ccca)
When the query result is empty, preHandle returns true
![image](https://github.com/user-attachments/assets/a1db9f90-f091-4aa8-831f-0393d8d365e0)

##### 重现步骤：
Request blocked
![image](https://github.com/user-attachments/assets/8148ec69-00d3-41b5-8726-d3ab948d14ea)
Permission bypass
GET /jeecg-boot/jmreport/dict/list?previousPage=1&shareToken= HTTP/1.1
Host: localhost:8087
JmReport-Share-Token:123
Content-Length: 2

![image](https://github.com/user-attachments/assets/8dfe6851-c248-40f0-8f17-d3c9d4a73bc4)

**Comment by jeecgos** [comment]
已修复，下版本更新 #2865
