### ISSUE TITLE
怎么设置能让第二列的编码与第一列的编码一致并只显示相同的部分

### ISSUE THREAD

**Issue by amwylig** [jeecgboot/JimuReport#2906]
##### 错误日志&截图：
![1724123436453](https://github.com/user-attachments/assets/27b875a6-6d1c-473f-8aaa-dbf77bd70d24)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
是两个不同的数据集？ 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID; 或者贴下 数据集和报表设计页。

**Comment by amwylig** [comment]
> 是两个不同的数据集？ 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID; 或者贴下 数据集和报表设计页。

是的，两个不同的数据集

**Comment by hoperunChen** [comment]
请参考[多源报表](https://help.jeecg.com/jimureport/multi-data-table.md.html)功能，该功能支持列表展示主子表数据。
建议升级到最新版本，最低支持版本`1.7.2-beta+`。
