### ISSUE TITLE
如报DBsum-错误如何解决

### ISSUE THREAD

**Issue by chinaanze** [jeecgboot/JimuReport#2907]
##### 错误日志&截图：
![报表报错](https://github.com/user-attachments/assets/9eb44915-b7a7-42ee-9bbd-b4c33df7374a)
![报表控制台](https://github.com/user-attachments/assets/ae09e3bd-c22e-49bd-8318-737a6886bcb8)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
啥版本？

**Comment by jeecgos** [comment]
由于长时间未回复，暂时关闭
