### ISSUE TITLE
如何扩展iotdb，tsdb 时序数据库

### ISSUE THREAD

**Issue by super-ax** [jeecgboot/JimuReport#2908]
##### 版本号：
v1.7.9 | 2024-07-09

##### 问题描述：
我想扩展iotdb，tsdb 时序数据库, 在pox.xml 扩展驱动就可以使用吗？
![image](https://github.com/user-attachments/assets/bed00801-dd64-4b53-9d01-450f7fc3a34e)

**Comment by jeecgos** [comment]
暂不兼容iotdb和tsdb 数据库。归集 #138
