### ISSUE TITLE
报表查询配置中的查询空间下拉树

### ISSUE THREAD

**Issue by Pepsicookie** [jeecgboot/JimuReport#2910]
##### 版本号：

1.5.6
##### 问题描述：

后台书写对应接口，测试时可以自己调通，但是从前端请求时，不走这个接口，dictList:null,后台的接口为什么不请求？

##### 错误日志&截图：

有加密，没法截图
##### 重现步骤：
（1）前端配置数据源、参数配置，设置的是两个loadTree、loadTreeByValue
（2）后台接口
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
您积木报表前端的域名和提供接口的服务的域名是否一致？是不是跨域了？

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题

**Comment by BO-DI** [comment]
> 您积木报表前端的域名和提供接口的服务的域名是否一致？是不是跨域了？

请问查询下拉树的查询传参只能是固定值吗，动态传参可以吗？

**Comment by jeecgos** [comment]
> > 您积木报表前端的域名和提供接口的服务的域名是否一致？是不是跨域了？
> 
> 请问查询下拉树的查询传参只能是固定值吗，动态传参可以吗？

传参是固定值，不支持动态传参；

*另：有问题请新开issue提问，尽量不要在别人已经关闭的issue下回复，谢谢*
