### ISSUE TITLE
1.7.9版本springboot2集成后前端获取后台配置的报表配置的方法报错

### ISSUE THREAD

**Issue by jx66802196** [jeecgboot/JimuReport#2911]
##### 版本号：
1.7.9

##### 问题描述：
通过springboot2的方式集成到项目中之后前端报错
VM1569:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getReportConfigJson (985772255280058368?menuType=datainfo:12833:21)
    at load (985772255280058368?menuType=datainfo:12849:28)
    at onload (985772255280058368?menuType=datainfo:11947:43)

查看页面上的代码是因为
    /**
     * 获取后台配置的报表配置
     */
    function getReportConfigJson() {
        let str = '';
        return JSON.parse(str)
    }
这个方法里赋里空值

##### 错误日志&截图：
![test1](https://github.com/user-attachments/assets/67490d4d-f06c-45f2-81ed-825a8a46e45d)
![test2](https://github.com/user-attachments/assets/ddb22ec8-6ce3-4320-854a-554a47df75be)

##### 重现步骤：
通过springboot2的方式集成到项目中之后访问/jmreport/list，然后点新建报表

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jx66802196** [comment]
最后发现是项目中的 fastjson版本问题，项目用的是fastjson2:2.0.5,但是经过测试发现只有用 fastjson 1.2.83才能正常使用积木报表的功能，但是降低fastjson版本会影响项目本身功能，有没有方法能将积木报表的 fastjson版本升级到2.X的版本？

**Comment by jeecgos** [comment]
springboot2版本的积木报表暂时不会升级fastjson到2.X。您可以考虑更换为springboot3版本的积木报表，springboot3版本中使用的是fastjson2.x
