### ISSUE TITLE
COUNTNZ无法和字符串拼接使用

### ISSUE THREAD

**Issue by zhenfeihao** [jeecgboot/JimuReport#2912]
##### 版本号：
1.7.9

##### 问题描述：
='派出机构小计('+COUNTNZ(A6)+'个)'

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/8d52bc43-65db-4acd-929f-264a8081c35a)

![image](https://github.com/user-attachments/assets/9b49f87e-369d-429c-b4a9-d7748d7a0467)
应该是6个，却显示为1个

##### 重现步骤：
单元格值为='派出机构小计('+COUNTNZ(A6)+'个)'

**Comment by jeecgos** [comment]
陈锐

**Comment by hoperunChen** [comment]
表达式和字符串组合使用的用法应该是：`派出机构小计（=COUNTNZ(C1)）个`；文档：[文字与表达式组合](https://help.jeecg.com/jimureport/function/cell.html#%E6%96%87%E5%AD%97%E4%B8%8E%E8%A1%A8%E8%BE%BE%E5%BC%8F%E7%BB%84%E5%90%88)
按照上述拼接方法，拼接后字符串是没问题的：
设计：
![QQ_1724982412400](https://github.com/user-attachments/assets/947cad6c-6cce-4151-8b5d-07779d9610fb)
预览：
![QQ_1724982466107](https://github.com/user-attachments/assets/27435f4e-50e4-48fd-a91f-7269bd8c5293)

烦请尝试下`派出机构小计（=COUNTNZ(C1)）个`这种拼接方式是否可以用，如果还是不行，请在官网制作报表示例并提供ID;
