### ISSUE TITLE
整合到ruoyi菜单中后，静态资源

### ISSUE THREAD

**Issue by YuYangHP** [jeecgboot/JimuReport#2916]
##### 问题描述：
无论customPrePath和apiBasePath配置什么都不生效

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/bfce8b45-2937-4c51-81e4-4edab1f0b2f3)
![image](https://github.com/user-attachments/assets/c33196a9-b7b4-44a7-95ce-6774d570f149)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by YuYangHP** [comment]
应该访问http://localhost:9080/dev-api/jmreport/desreport_/cdn/vue/vue.min.js   或者http://localhost:8080/moonCimp/jmreport/desreport_/cdn/vue/vue.min.js    但是怎么配置都不好使

**Comment by jeecgos** [comment]
请描述下你那 部署环境，有没有用nginx做负载？积木是独立部署还是集成到业务系统里？

**Comment by YuYangHP** [comment]
集成到业务系统中，没有用nginx做负载，本地启动

**Comment by zhangdaiscott** [comment]
信息不完整，补充版本号
