### ISSUE TITLE
图表上传背景图片，上传成功，但是不能显示

### ISSUE THREAD

**Issue by liqy00** [jeecgboot/JimuReport#2918]
版本号：
版本1.7.8和版本1.8.0
问题描述：
文件上传到本地的应该怎么处理？或者怎么配置？

![image](https://github.com/user-attachments/assets/eccad945-efb4-4b73-81e1-63dab22ded34)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
你是怎么部署和运行的？请提供一下重现步骤。

**Comment by liqy00** [comment]
1、通过地址：https://github.com/jeecgboot/JimuReport  拉取最新代码；（1.7.8 和 1.8.0；其它版本没有测试）
2、下载sql脚本，并导入本地MySQL数据（版本5.7.33）；
3、通过IDEA的debug模式启动；
4、访问并设计报表，如下图：
![image](https://github.com/user-attachments/assets/822b243d-86a7-492c-87d6-d757b630c426)

**Comment by jeecgos** [comment]
陈锐

**Comment by hoperunChen** [comment]
已修复，待新版本发布。
