### ISSUE TITLE
目前这个版本必须登录后才能看报表，如何设置不登录也能查看报表

### ISSUE THREAD

**Issue by AXXZSTHL** [jeecgboot/JimuReport#2919]
##### 重现步骤：在Chrome浏览器打开积木报表并且登录，复制报表地址到edge浏览器就直接白屏了，我目前设置了/jmreport/view/为免登录，但是好像还是不行
http.csrf().disable()
                .authorizeRequests()
                .antMatchers("/login/**").permitAll()
                .antMatchers("/jmreport/view/**").permitAll()
                .anyRequest().authenticated()
                .and()
                .formLogin()
                .loginPage("/login/login.html")
                .loginProcessingUrl("/login")
                .successHandler(new CustomLoginSuccessHandler())
                .permitAll().and()
                .logout()
                .invalidateHttpSession(true)
                .clearAuthentication(true).permitAll();

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
好的，尽快修复

**Comment by AXXZSTHL** [comment]
感谢

**Comment by hoperunChen** [comment]
已修复，在1.8.1版本中可以使用以下配置，来允许预览页面不登录访问。
```
spring:
  security:
    # view 页面允许不登录访问（默认false）
    open-view-page: true
```

**Comment by AXXZSTHL** [comment]
我现在用的授权版本1.7.9，是否能更新修复一下这个问题，我这边等急用这个

**Comment by zhangdaiscott** [comment]
分享链接可以访问

**Comment by AXXZSTHL** [comment]
我现在用的就是1.7.9jmbi-datax版本，现在打开分享页面报错
![IMG_9611](https://github.com/user-attachments/assets/10bfe4bf-305d-44e3-b119-63b6ad69e70c)
![IMG_9610](https://github.com/user-attachments/assets/3be6a61d-465d-4f2e-9184-e51609b28451)

**Comment by hoperunChen** [comment]
@AXXZSTHL  图裂了

**Comment by AXXZSTHL** [comment]
![1331724637165_ pic_hd](https://github.com/user-attachments/assets/1d02a75e-9b01-4561-9e55-2ef35c097700)
![1321724637164_ pic_thumb](https://github.com/user-attachments/assets/e5922c9d-aa2d-4883-bcb9-e0e52d06a0ae)

**Comment by AXXZSTHL** [comment]
问题能复现吗，还需要我提供什么线索吗

**Comment by hoperunChen** [comment]
@AXXZSTHL 您好，我这边用`1.7.9jmbi-datax`版本测试了一下，在未登录的情况下是可以正常访问分享的报表的。
如果您是使用example启动的积木报表，您可以和github仓库比对下您本地的这两个文件是不是最新的
![QQ_1724756991817](https://github.com/user-attachments/assets/0bfe769e-640d-48e8-9f45-12a5c5831f9b)

**Comment by AXXZSTHL** [comment]
但是我这边提示找不到org.jeecg.modules.jmreport.common.util.OkConvertUtils
<img width="1402" alt="image" src="https://github.com/user-attachments/assets/e618cfc9-378b-410a-a4dc-a9d854ae4e21">
<img width="1334" alt="iShot_2024-08-28_08 14 52" src="https://github.com/user-attachments/assets/4ee66ab2-3a04-437e-b99e-4859a6fe8e0f">

**Comment by AXXZSTHL** [comment]
目前可以直接打开了，但是在iframe中打开报表页面提示  in a frame because it set 'X-FRame-Options' to 'Deny' 说是开启了xss验证，我在代码中写关闭校验，但是项目就启动不起来了
<img width="980" alt="image" src="https://github.com/user-attachments/assets/70c47d25-a4a4-4fe7-bf53-23d0103eae57">

**Comment by AXXZSTHL** [comment]
项目有缓存，我clean了一下又好了，谢谢

**Comment by gaoxiaoniu** [comment]
现在是可以不登录打开，但是导出Excel还是要求登陆

**Comment by jacobchan** [comment]
我也碰到了同样的问题，因为不开放源代码所以很多问题还不好处理。
  必须要实现Token吗？ 一般情况各自业务系统都有自己的网关和鉴权中心。

**Comment by hoperunChen** [comment]
> 我也碰到了同样的问题，因为不开放源代码所以很多问题还不好处理。 必须要实现Token吗？ 一般情况各自业务系统都有自己的网关和鉴权中心。

可以不实现token，此时积木报表将不进行权限校验，任何人都可以访问；你需要在上游控制好权限。

**Comment by hoperunChen** [comment]
> 导出excel需要登录，这个问题有办法解决吗？

在`com.jeecg.modules.jmreport.config.SpringSecurityConfig`增加这两个地址的排除:
```
"/jmreport/exportPdfStream",
"/jmreport/exportAllExcelStream"
```

**Comment by Feiyizhan** [comment]
2.1 版本同样存在这个问题，因为有一个接口漏掉了没有加入到白名单。
