### ISSUE TITLE
分享链接登录问题

### ISSUE THREAD

**Issue by lm798880844** [jeecgboot/JimuReport#2920]
##### 版本号：
1.8.0
##### 问题描述：
分享链接也需要登录查看，能不能改为设计页面需要登录，分享链接不用登录

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
收到，尽快处理

**Comment by hoperunChen** [comment]
已修复，在1.8.1版本中分享链接无需登录
