### ISSUE TITLE
过度封装，多执行SQL

### ISSUE THREAD

**Issue by hkall** [jeecgboot/JimuReport#2921]
##### 问题描述：

执行一个简单非分页查询sql，sdk会总是会多执行count()
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
cr

**Comment by hoperunChen** [comment]
未复现，请提供版本号以及复现步骤。

确保数据集配置中，已经取消分页的选中。
![QQ_1724913969811](https://github.com/user-attachments/assets/260cea06-8bc6-4e51-913c-0a651779eaad)
![QQ_1724914168460](https://github.com/user-attachments/assets/6b163d5b-0df9-4170-b396-03f4fba9b8c9)
