### ISSUE TITLE
图形报表，产线会报“发布模式不允许使用在线配置”

### ISSUE THREAD

**Issue by aliancexuan** [jeecgboot/JimuReport#2922]
##### 问题描述：
产线将lowCodeMode配置为prod模式，如果报表中有图形，则会报如下错误：
{
"code": 500,
"success": false,
"message": "当前积木平台模式为，发布模式不允许使用在线配置！！",
"timestamp": 1723548023422
}

另外：如果lowCodeMode配置为prod模式，按道理，jmreport/list请求也应该报错。现在在产线是能够进入这个url的，而且还能看到所有的报表信息，并没有实现“布模式不允许使用在线配置”的功能。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
是不是和 [1.7.8,prod模式 用户查看报表 报错发布模式不允许使用在线配置！！](https://github.com/jeecgboot/JimuReport/issues/2888) 一个问题？

**Comment by zhangdaiscott** [comment]
截图

**Comment by aliancexuan** [comment]
看样子应该是一个问题造成的。[https://github.com/jeecgboot/JimuReport/issues/2922#issuecomment-2306943995](url)

**Comment by jeecgos** [comment]
> 看样子应该是一个问题造成的。[https://github.com/jeecgboot/JimuReport/issues/2922#issuecomment-2306943995](url)

如果和这个issue一样，已经修复了，下个版本更新。
