### ISSUE TITLE
查询参数使用请求接口作为查询参数，滚动到最后又重新查询了一次

### ISSUE THREAD

**Issue by yupenglideyupeng** [jeecgboot/JimuReport#2923]
##### 问题描述：
查询参数使用请求接口作为查询参数，滚动到最后又重新查询了一次
之前是字典也会出现此问题，1.8.0已修复此问题，但对于请求接口作为查询参数没有修复此问题

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/a5e395f7-e833-4c6f-97b0-f0197765130a)

![image](https://github.com/user-attachments/assets/3c5aa0e7-bef6-463e-aa2e-35f8aa24fc44)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 1298191366** [comment]
参考文档，目前1.8.0做了调整，api需要分页查询，为空的时候需要返回空数据，下载就不会再加载了
https://help.jeecg.com/jimureport/queryCriteria/dictionary.html
