### ISSUE TITLE
根据打印条件记录打印次数

### ISSUE THREAD

**Issue by yuruoguang** [jeecgboot/JimuReport#2924]
##### 版本号：
1.6.6

##### 问题描述：
1、打印无法记录打印次数
2、是否可以在回调接口内拿到打印数据传入的参数，

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
麻烦详细描述下你的业务需求，从你的描述我们没看懂你想要什么功能。

**Comment by hoperunChen** [comment]
打印回调的接口参数中是包含报表预览传入的参数的，您可以尝试下，如果没有请更新到最新版本。
![QQ_1726820295558](https://github.com/user-attachments/assets/16c61e1c-9355-42ba-ba7d-633ee0958eca)
![QQ_1726820270240](https://github.com/user-attachments/assets/64b41002-459d-41c5-8d0a-a9abc9846125)

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
