### ISSUE TITLE
但当前版本使用的是 poi 的4.1.2的版本，下一个版本可以使用poi的5.0.0及以上的版本么？

### ISSUE THREAD

**Issue by liqy00** [jeecgboot/JimuReport#2925]
版本号：
1.7.8 、1.7.9 、1.8.0  当前在这三个版本上进行了验证

##### 问题描述：
但当前版本使用的是 poi 的4.1.2的版本，下一个版本可以使用poi的5.0.0及以上的版本么？

使用poi的5.0.0版本后报错：

![image](https://github.com/user-attachments/assets/354db93e-d5e5-49cb-8c72-8976cc50e09b)

![image](https://github.com/user-attachments/assets/27be11ed-9361-4333-9411-57e8c8ab3be3)

![image](https://github.com/user-attachments/assets/b4385556-30a5-45bd-8afe-579ab3a78528)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
ws
