### ISSUE TITLE
紧急bug，目前所有的查询栏都不显示了

### ISSUE THREAD

**Issue by AXXZSTHL** [jeecgboot/JimuReport#2926]
##### 问题描述：
紧急bug，目前所有的查询栏都不显示了

##### 错误日志&截图：
<img width="1733" alt="image" src="https://github.com/user-attachments/assets/63d6e281-3e53-4dd9-84dc-e28c252d67f4">

<img width="1751" alt="image" src="https://github.com/user-attachments/assets/dc572092-59c3-4bb5-beab-f6e508512164">

##### 重现步骤：
[查询1.json](https://github.com/user-attachments/files/16724230/1.json)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by AXXZSTHL** [comment]
<dependency>
            <groupId>org.jeecg.pe</groupId>
            <artifactId>jmbi-datax</artifactId>
            <version>1.7.9</version>
        </dependency>
这个版本也不行

**Comment by zhangdaiscott** [comment]
![image](https://github.com/user-attachments/assets/85ece8d2-877c-4b27-9ec3-d0cec688c862)

**Comment by AXXZSTHL** [comment]
都试过，还是不出来查询栏
<img width="766" alt="image" src="https://github.com/user-attachments/assets/54160679-6029-4b44-9154-bea84ddef17f">
<img width="992" alt="image" src="https://github.com/user-attachments/assets/a9492c5e-e060-4ae5-b71e-430413a2db8e">

**Comment by 1298191366** [comment]
你1.8.0用的是这个版本吗
![image](https://github.com/user-attachments/assets/157ecfcf-e4a6-46c1-8c16-d17b461392dd)
![image](https://github.com/user-attachments/assets/2da879de-2a31-44fe-a93e-d164e3fd888c)

**Comment by AXXZSTHL** [comment]
<properties>
        <jimureport.version>1.8.0</jimureport.version>
        <java.version>1.8</java.version>
        <minio.version>8.0.3</minio.version>
        
        <mysql-connector-java.version>8.0.27</mysql-connector-java.version>
        
        <jsqlparser.version>4.6</jsqlparser.version>
    </properties>


    <dependencies>
        
        <dependency>
            <groupId>org.jeecgframework.jimureport</groupId>
            <artifactId>jimureport-spring-boot-starter</artifactId>
            <version>${jimureport.version}</version>
        </dependency>

**Comment by AXXZSTHL** [comment]
<properties>
        <jimureport.version>1.8.0</jimureport.version>
        <java.version>1.8</java.version>
        <minio.version>8.0.3</minio.version>
        
        <mysql-connector-java.version>8.0.27</mysql-connector-java.version>
        
        <jsqlparser.version>4.6</jsqlparser.version>
    </properties>


    <dependencies>
        
        <dependency>
            <groupId>org.jeecgframework.jimureport</groupId>
            <artifactId>jimureport-spring-boot-starter</artifactId>
            <version>${jimureport.version}</version>
        </dependency>

**Comment by 1298191366** [comment]
你前端 f12看看有报错吗

**Comment by AXXZSTHL** [comment]
<img width="616" alt="image" src="https://github.com/user-attachments/assets/c583ee4a-7da6-4c5e-bb4b-5e1f1cbd5e10">
有catch

**Comment by 1298191366** [comment]
目前判断了不为空。但是这里应该和查询栏没关系。你可以看看后端报没报错。目前下载的是官网最新版的demo，数据库用的是mysql。你可以试试官网，如有问题请在次回复
