### ISSUE TITLE
分栏设置新版本失效

### ISSUE THREAD

**Issue by luoyuwei3919** [jeecgboot/JimuReport#2927]
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/48b9c15f-5647-4eff-8209-087220e123d8)

##### 重现步骤：
之前的版本1.4.2设计的可以正常显示，之后升级到1.8.0就不行。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
重新设计个全新报表呢？

**Comment by luoyuwei3919** [comment]
切换1.7.8也是可以的。 @zhangdaiscott

**Comment by 1298191366** [comment]
（1）你说的分版是这个样子的吗 
![image](https://github.com/user-attachments/assets/c66f6212-17ba-4bac-9619-9516e077d6dc)
![image](https://github.com/user-attachments/assets/adcd8fd5-f4fe-4dd1-b07a-0de302f4afc3)

（2）未测出，请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html) 和测试数据或在官网制作报表示例并提供ID;

**Comment by 1298191366** [comment]
分栏已修复，待新版本发布
