### ISSUE TITLE
大数据量导出报表时容易导不出来，也不报错，能否加个错误提示？

### ISSUE THREAD

**Issue by remuzimalin** [jeecgboot/JimuReport#2928]
##### 版本号：
1.7.6

##### 问题描述：
数据量较大时（20多万行，30多列），导出报表（包括大数据导出）时可能导不出来，也没有任何提示，能否在导出报表且导不出来时增加一个报错的提示？
有些用户计算机配置不太高，导出大数据量报表的时候一直在等待，也不知道是否报错了。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
好的 cr

**Comment by liqy00** [comment]
> ##### 版本号：
> 1.7.6
> 
> ##### 问题描述：
> 数据量较大时（20多万行，30多列），导出报表（包括大数据导出）时可能导不出来，也没有任何提示，能否在导出报表且导不出来时增加一个报错的提示？ 有些用户计算机配置不太高，导出大数据量报表的时候一直在等待，也不知道是否报错了。
> 
> ##### 错误日志&截图：
> ##### 重现步骤：
> #### 友情提示（为了提高issue处理效率）：
> * 积木报表是一款免费报表产品，功能免费源码不开放;
> * 未按格式要求发帖，会被直接删掉;
> * 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
> * 针对不好重现的问题，请录制操作视频或详细的重现步骤；

我是用的1.7.8和1.8.0，在报表预览页面：大数据excel  按钮是灰色的， 是什么原因？

**Comment by jeecgos** [comment]
「大数据量导出报表时容易导不出来」： 已修复，待新版本发布。
