### ISSUE TITLE
报表参数不支持设置当前月的第一天和最后一天

### ISSUE THREAD

**Issue by alonekokonew** [jeecgboot/JimuReport#2931]
##### 版本号：
1.6.0

##### 问题描述：
报表参数不支持：this.updateSearchFormValue('dbCode', 'fieldName', start+'|'+end)

##### 错误日志&截图：
<img width="1219" alt="1724664586645_B9F751E6-0162-4c32-8F5A-B72173DAB5BD" src="https://github.com/user-attachments/assets/b1f20bd6-39b2-4cba-8c4a-09749ff221fc">

##### 重现步骤：
按照截图，没有达到想要的效果。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 1298191366** [comment]
1、报表参数不支持设置js增强，只支持报表字段
2、如果是报表字段不支持，请升级到[最新版本](http://www.jimureport.com/doc/log)尝试一下
测试结果：
![image](https://github.com/user-attachments/assets/80bb9aa4-1d7f-4fad-aa66-0953e5339314)
