### ISSUE TITLE
报表导出excel功能报错

### ISSUE THREAD

**Issue by Tannysiu** [jeecgboot/JimuReport#2932]
##### 版本号：
当前最新版本： 3.7.0_all（发布日期：2024-06-23）

##### 问题描述：
报表导出excel时，excel中提示异常
{"success":false,"message":"操作失败，The maximum number of Cell Styles was exceeded. You can define up to 64000 style in a .xlsx Workbook","code":500,"result":null,"timestamp":1724726713381}

但实际导出的数据只有6129条

##### 错误日志&截图：
![Uploading 1111.jpg…]()
![Uploading QQ截图20240827134740.jpg…]()

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
图片裂了

**Comment by jeecgos** [comment]
你的单元格数量是不是超过64000了？ 数据列有多少个？
可以试试大数据excel导出。

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
