### ISSUE TITLE
仪表盘移动端布局手机端预览无法滑动

### ISSUE THREAD

**Issue by Tanner-Zhang** [jeecgboot/JimuReport#2934]
##### 版本号：
3.7.0

##### 问题描述：
我在演示环境制作的移动布局页面，使用手机端浏览器访问该预览地址时，手机上无法滑动预览，导致被隐藏部分无法查看

##### 错误日志&截图：
[设计器地址](https://api3.boot.jeecg.com/drag/index?pageId=750931735173201920&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MjQ2OTk4ODgsInVzZXJuYW1lIjoiamVlY2cifQ.ZYvs388YyIGTnHWVATczIcZpxvlNu1jnAy9YNT7x3s8&tenantId=3)
效果图：
![image](https://github.com/user-attachments/assets/ac406530-e1d5-4147-a16f-bdbbcf197a90)

[预览地址](https://api3.boot.jeecg.com/drag/view?pageId=750931735173201920&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MjQ2OTk4ODgsInVzZXJuYW1lIjoiamVlY2cifQ.ZYvs388YyIGTnHWVATczIcZpxvlNu1jnAy9YNT7x3s8&tenantId=3)
效果图：
![image](https://github.com/user-attachments/assets/7bbe634d-b200-43e7-8ff8-ed3ad3b1cf13)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
无法滑动是指？上下滑动还是啥

**Comment by Tanner-Zhang** [comment]
就是上下滑动预览不行

**Comment by zhangdaiscott** [comment]
提供地址

**Comment by Tanner-Zhang** [comment]
https://api3.boot.jeecg.com/drag/view?pageId=750931735173201920&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MjQ2OTk4ODgsInVzZXJuYW1lIjoiamVlY2cifQ.ZYvs388YyIGTnHWVATczIcZpxvlNu1jnAy9YNT7x3s8&tenantId=3

**Comment by Tanner-Zhang** [comment]
设计器地址前面提供了的

**Comment by Tanner-Zhang** [comment]
这个要如何解决呢，大概需要多久呢

**Comment by lsqGitHub716** [comment]
已修改
