### ISSUE TITLE
升级新版本后打开老交叉报表报错，com.alibaba.fastjson.JONObject cannot be cast to java.lang.Comparable

### ISSUE THREAD

**Issue by AXXZSTHL** [jeecgboot/JimuReport#2935]
##### 问题描述：
升级1.7.9版本后，打开老版本数据的交叉报表报错，因为是从1.6.6升级上来，目前没有可替代使用版本，请尽快解决com.alibaba.fastjson.JONObject cannot be cast to java.lang.Comparable

##### 错误日志&截图：
![交叉报表报错](https://github.com/user-attachments/assets/3c098aa8-2742-4638-a7d0-6ce55535803c)
[老数据交叉报表打开报错.json](https://github.com/user-attachments/files/16777010/default.json)
[数据.xlsx](https://github.com/user-attachments/files/16777011/default.xlsx)
[导出配置.json](https://github.com/user-attachments/files/16777046/default.json)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
已修复，待新版本发布。

**Comment by hoperunChen** [comment]
已修复，待新版本发布
