### ISSUE TITLE
超过50行 就预览不出来 没办法打印

### ISSUE THREAD

**Issue by czg108** [jeecgboot/JimuReport#2936]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by czg108** [comment]
> 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
API地址:https://cartons-api.junwuculture.cn/report/printInfo?id=${id}

**Comment by czg108** [comment]
> 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

我使用下载了开源的代码在自己的服务器搭建了一个积木环境，用的是https://cartons-api.junwuculture.cn/report/printInfo?id=${id} api接口来访问报表，超过50条后就空白了，麻烦帮忙看看哪里的问题，非常感谢

**Comment by hoperunChen** [comment]
麻烦您参考[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)在官网制作一个可以复现您反馈的这个问题的示例，并且官网的这个示例报表的id。我们好针对实例来解决问题，您指给我一个数据接口的api我没办法复现和解决问题呢。
下图是我这边测试的例子，没有复现。
![QQ_1725246770508](https://github.com/user-attachments/assets/66fd64f9-9f9e-44ca-a331-385817170cd4)

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
