### ISSUE TITLE
1.8版本配置https后，在仪表盘中有几个接口请求的路径还是http,导致请求混用

### ISSUE THREAD

**Issue by gitchenming** [jeecgboot/JimuReport#2939]
##### 版本号：
1.8

##### 问题描述：
1.8版本配置https后，在仪表盘中有几个接口请求的路径还是http,导致请求混用

##### 错误日志&截图：
![1724896461099](https://github.com/user-attachments/assets/ab12fa99-f8ec-4854-ae1f-44779
![1724896345767](https://github.com/user-attachments/assets/abe1a54b-859f-431e-ad7b-7596f3236763)
c2b940c)
![4bb521802b7568d47dbc851910b2c8a](https://github.com/user-attachments/assets/75670760-c864-4a25-a53d-d28626df4587)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by gitchenming** [comment]
南方小火人

**Comment by gitchenming** [comment]
着急帮忙看下

**Comment by lsqGitHub716** [comment]
https://blog.csdn.net/weixin_34376986/article/details/89767950参考修改nginx配置

**Comment by gitchenming** [comment]
改了下nginx的配置还是不行，nginx配置如下：
<img width="345" alt="微信图片_20240905133156" src="https://github.com/user-attachments/assets/74ed4016-40b3-4273-8d94-7ae21e9a4451">


仪表盘设计里面的组件还是出不来，如下图：
![1725514279063](https://github.com/user-attachments/assets/cd2363bf-2f51-4be3-be0c-68e0329ef3d3)
![Uploading 1725514279063.jpg…]()

报表url是：https://xxxxx/drag/index?pageId=990784598098268160
仪表盘设计的时候左边的组件出不来，访问的地址是http的：
http://xxxxx/drag/page/queryById?id=990784598098268160
http://xxxxx/drag/comp/treeList?excludeComp=
http://xxxxx/drag/onlDragDatasetHead/getLoginUser
http://xxxxx/drag/page/getCount

**Comment by lsqGitHub716** [comment]
你也没有配置  proxy_set_header X-Forwarded-Proto $scheme;呀

**Comment by gitchenming** [comment]
大佬，配置了也还是不行，帮忙看看，nginx配置如下：
location /jmreport/ {
        proxy_set_header Host $host;
        proxy_set_header X-real-ip $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://up_jmreport/jmreport/;
      }

      location /drag/ {
        proxy_set_header Host $host;
        proxy_set_header X-real-ip $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://up_jmreport/drag/;
      }

      location / {
         proxy_set_header Host $host;
         proxy_redirect  off;
         proxy_set_header X-real-ip $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
         proxy_set_header X-Scheme $scheme;
         proxy_pass http://up_jmreport;
      }

**Comment by zhangdaiscott** [comment]
是不是你前端是https的
后端是http的
导致

**Comment by gitchenming** [comment]
不是的，我是用源码部署的积木报表，然后给他配置了https，去访问仪表盘设计器，设计的时候左边的组件列表出不来，看获取组件的接口是http的，不是https，是不是项目里面组件获取那块拿路径有点问题

**Comment by zhangdaiscott** [comment]
？

**Comment by gitchenming** [comment]
就是用hppts访问积木报表的仪表盘的设计器，设计报表的时候左边的组件出不来：
仪表盘在线设计器报表url是：https://xxxxx/drag/index?pageId=990784598098268160
仪表盘在线设计器设计报表的时候左边的组件出不来，访问的地址是http的：
http://xxxxx/drag/page/queryById?id=990784598098268160
http://xxxxx/drag/comp/treeList?excludeComp=
http://xxxxx/drag/onlDragDatasetHead/getLoginUser
http://xxxxx/drag/page/getCount

![364636404-cd2363bf-2f51-4be3-be0c-68e0329ef3d3](https://github.com/user-attachments/assets/bbd93b22-a83d-4f0d-9423-91e6dd779643)



F12看了下有4个接口访问的路径不是https，这4个接口应该也要是https的路径才对吧

**Comment by zhangdaiscott** [comment]
http://boot3.jeecg.com/dashboard/analysis
演示环境没问题

**Comment by gitchenming** [comment]
用http的是没有问题，用https的才会有问题

**Comment by zhangdaiscott** [comment]
仪表盘访问地址就是https
![image](https://github.com/user-attachments/assets/335030a4-f73d-4008-9862-e3ce4d066f93)

**Comment by YongYangLi** [comment]
你的配置  proxy_pass http://up_jmreport;  getScheme()会取到http

![image](https://github.com/user-attachments/assets/e9a6b82e-2441-4cd3-9ef3-831f2d6084c6)
nginx 配置X_GATEWAY_BASE_PATH 
或者 X-Forwarded-Scheme 配置为https .              
如下 : proxy_set_header X-Forwarded-Scheme https;

**Comment by zhangdaiscott** [comment]
参考这个
![image](https://github.com/user-attachments/assets/9181ac43-8605-4c46-acf2-7e72fb7089c4)

**Comment by gaokaoli** [comment]
同样出现了这个问题，还是没有解决！！！！！
