### ISSUE TITLE
当报表中有相对路径的图片资源时，导出pdf格式的报表会报错

### ISSUE THREAD

**Issue by lmxuan** [jeecgboot/JimuReport#2940]
##### 版本号：
1.6.4
##### 问题描述：
报表中有相对路径的图片，导出pdf时，会报错，文件未找到
![image](https://github.com/user-attachments/assets/b6dfae00-e8e6-4a91-bf3c-a9526b75c13a)

##### 错误日志&截图：
![录制_2024_08_29_15_15_39_5](https://github.com/user-attachments/assets/dcf60d9c-f717-44c7-9f1b-607344967185)

##### 重现步骤：
1、设置单元格为图片，并将图片设置为相对路径(相对报表预览地址的路径)
2、点击导出pdf，报错
3、后台看错误日志，发现 java.nio.file.NoSuchFileException: D:\images/../../contractorAdmin/ms-contractor/work_flow_query/resource_download/ae75a00c315049eaba986477ec4263e9，其中 D:\images 我在源码里面找到了配置
![image](https://github.com/user-attachments/assets/5e55275b-2c2a-436e-b819-8fff0aa772a7)
nacos中该项目的配置
![image](https://github.com/user-attachments/assets/8a0d52ab-c1ee-452b-9d92-e108afadecaf)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
图片在预览和导出的逻辑是不一样的，导出的时候系统会去 `path.upload+图片地址`这个目录找文件，你可以尝试下修改配置文件中`path.upload`确保系统能通过路径找到文件。或者图片地址用网络地址（http或https开头）。
