### ISSUE TITLE
jimu_report_db_param表中索引是否重复？

### ISSUE THREAD

**Issue by 1362227089** [jeecgboot/JimuReport#2941]
##### 版本号：
1.8

##### 问题描述：
**jimu_report_db_param**表中**jimu_report_head_id**字段创建了两个索引，是否合理？

##### 错误日志&截图：

![Uploading image.png…]()

**Comment by 1362227089** [comment]
![image](https://github.com/user-attachments/assets/8d6fb40a-bffa-4b3d-b5c2-c111dd12284c)
![Uploading jimu.png…]()

**Comment by zhangdaiscott** [comment]
如果是重复索引，的确不对，可以删掉一个
