### ISSUE TITLE
点击预览 报NoSuchMethodError

### ISSUE THREAD

**Issue by ykjava** [jeecgboot/JimuReport#2942]
##### 版本号：
1.8.0

##### 问题描述：
点击表报的预览 报NoSuchMethodError  按照问题解决也升级了poi的版本4.1.2还是报这个错

##### 错误日志&截图：

![image](https://github.com/user-attachments/assets/f51a650b-f4e0-476a-818f-bf016512c1b6)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
还是依赖冲突，看错误是fastjon，此类问题需要自己排查处理
