### ISSUE TITLE
主子表导出excel，报空指针异常，导出数据为空。

### ISSUE THREAD

**Issue by blanset** [jeecgboot/JimuReport#2945]
##### 问题描述：主子表查询后，导出的excel中报错{"msg":null,"code":500}。后台日志报错 请求地址'/report/jmreport/exportAllExcelStream',发生未知异常.
java.lang.NullPointerException: null
	at org.jeecg.modules.jmreport.desreport.render.a.d.a(TableMultiDsRenderStrategy.java:143)
	at org.jeecg.modules.jmreport.desreport.render.a.e.a(TableRenderStrategy.java:98)
	at org.jeecg.modules.jmreport.desreport.render.a.a.b.a(BaseBaseRenderStrategy.java:385)
	at org.jeecg.modules.jmreport.desreport.render.a.a.b.b(BaseBaseRenderStrategy.java:264)

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/41dcc1c3-abde-4e45-b24a-1a6dd81279bb)

##### 重现步骤：
主表sql：
```sql
SELECT
	oir.dispatchTaskId
FROM
	`order` oir
	LEFT JOIN order_task ot ON ot.order_id = oir.id 
GROUP BY
	oir.dispatchTaskId
```
子表sql：
```sql
SELECT
	CASE WHEN charge IS NULL THEN 0
	ELSE charge
	END as charge
FROM
(
	SELECT
                       dt.orderStates
	FROM
			e_dispatch_task dt
			LEFT JOIN e_emr e ON e.dispatchTaskId = dt.dispatchTaskId
			LEFT JOIN e_emr_order eo ON eo.emrId = e.emrId
	WHERE
			dt.dispatchTaskId = '${dispatchTaskId}'
) t
```
主子表参数连结：
主表的dispatchTaskId和子表dispatchTaskId连结。

两张表分别来自两个源的数据库。

导出excel文件没有内容，后台报空指针异常。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by blanset** [comment]
子表sql写错重新写下，发的时候写错了变量。
> 子表sql：
> 
> ```sql
> SELECT
> 	CASE WHEN charge IS NULL THEN 0
> 	ELSE charge
> 	END as charge
> FROM
> (
> 	SELECT
>                        dt.charge
> 	FROM
> 			e_dispatch_task dt
> 			LEFT JOIN e_emr e ON e.dispatchTaskId = dt.dispatchTaskId
> 			LEFT JOIN e_emr_order eo ON eo.emrId = e.emrId
> 	WHERE
> 			dt.dispatchTaskId = '${dispatchTaskId}'
> ) t
> ```

**Comment by blanset** [comment]
主表字段与子表字段：

![image](https://github.com/user-attachments/assets/d08f62b1-92f0-4f4e-9a09-47db4d3cfee4)

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by hoperunChen** [comment]
已修复，待新版本发布。
