### ISSUE TITLE
表头设置能不能开发一个悬浮状态

### ISSUE THREAD

**Issue by Lr19980321** [jeecgboot/JimuReport#2946]
##### 错误日志&截图
![1725413496524](https://github.com/user-attachments/assets/051d8bdb-4dfc-4047-aaa4-58b725ecf8c5)
![1725413562598](https://github.com/user-attachments/assets/e92a84f0-3cdc-4c74-a39d-17ac467da5bc)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
有冻结功能
