### ISSUE TITLE
报表导出PDF后没显示边框

### ISSUE THREAD

**Issue by 277341707** [jeecgboot/JimuReport#2947]
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/b55df6cc-9d41-4ad9-912e-9253309dc65e)
![微信截图_20240904140228](https://github.com/user-attachments/assets/05ecc8ec-7445-42bc-97a7-3c77735b82cf)

##### 重现步骤：导出pdf后，打开导出的pdf文件，pdf文件表格边框消失
![微信截图_20240904140228](https://github.com/user-attachments/assets/64cecc31-990d-468c-950e-e3912aeb0abf)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by jeecgos** [comment]
您可以先升级到最新版本试一下还有没有问题，如果还有问题请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
