### ISSUE TITLE
同一个报表支持给多个租户使用吗

### ISSUE THREAD

**Issue by jys2013** [jeecgboot/JimuReport#2948]
##### 版本号：
1.7.8

##### 问题描述：

我想问一下，同一个报表支持给多个租户使用吗。比如说做一个员工查询的报表，员工表里面有员工姓名 工号 租户ID这几个字段
租户A可以查到员工表 租户Id=A的数据
租户A可以查到员工表 租户Id=B的数据

**Comment by zhangdaiscott** [comment]
如果你开启的多租户，肯定是按照租户隔离
