### ISSUE TITLE
1.4.0-beta  启动默认开启连接mongodb

### ISSUE THREAD

**Issue by 277341707** [jeecgboot/JimuReport#2949]
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/446e56aa-bf70-4bf7-9fbf-f4e47814eb31)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
升级版本就好了
