### ISSUE TITLE
分享链接在未登录的情况下导出excle有问题

### ISSUE THREAD

**Issue by lm798880844** [jeecgboot/JimuReport#2951]
##### 版本号：
1.8.0

##### 问题描述：
通过分享链接打开的报表，在导出excle后无法打开；实测原因应该是分享链接没有登录，导致导出excle有问题，正常登录后在导出未出现此问题。

##### 错误日志&截图：
![1725584891916](https://github.com/user-attachments/assets/cc715af1-3e2a-4595-8fe3-c76a41c70fcc)

![1725585001093](https://github.com/user-attachments/assets/6e844bfa-5be7-4ff6-85cb-38a3df46ef6e)

##### 重现步骤：
1、在未登录的情况下用分享链接打开报表
2、导出excle
3、打开excle会提示有问题

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布

**Comment by lm798880844** [comment]
感谢
