### ISSUE TITLE
数据库大小写敏感时，查询sql报错找不到字段

### ISSUE THREAD

**Issue by 13058502039** [jeecgboot/JimuReport#2953]
##### 问题描述：
当数据库是小写敏感的时候，比如sqlserver用的Chinese_PRC_CS_AS字符集，后台的所有查询都会提示找不到字段

##### 错误日志&截图：

![图片](https://github.com/user-attachments/assets/2b3b0b3c-f714-4b7f-aa1b-a26ca89a1f1c)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
暂不支持，目前统一大写，需要你修改一下数据库使其大小写兼容
