### ISSUE TITLE
数据报表最多显示到AX列，超出的列无法修改，不能显示，缩放到最小也不行

### ISSUE THREAD

**Issue by Teddy0510** [jeecgboot/JimuReport#2956]
##### 版本号：
1.7.4

##### 问题描述：
数据报表最多显示到AX列，超出的列无法修改，不能显示，缩放到最小也不行

##### 错误日志&截图：
<img width="1232" alt="baddd1b079b9a94a1c1c5b13b13f0720" src="https://github.com/user-attachments/assets/812bd77b-3d89-4f7a-8cba-0097a513151b">

##### 重现步骤：
新建数据报表，数据超过AX列，超出的列无法显示

**Comment by hoperunChen** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by jeecgos** [comment]
请检查下配置文件中col配置的对不对？
![QQ_1726305258150](https://github.com/user-attachments/assets/91dccaee-5bde-48ea-ba95-5266153534f0)

**Comment by Teddy0510** [comment]
已解决，感谢
