### ISSUE TITLE
设置动态合并格未合并正确

### ISSUE THREAD

**Issue by yupenglideyupeng** [jeecgboot/JimuReport#2958]
##### 版本号：
1.6.4

##### 问题描述：
使用动态合并格，最后面的格数据都相同，没有进行正确合并，使用sql直查数据库，sql语句在附件中
目前希望最后两列按全部合并的方式

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/6e4e8b4f-39a3-42ba-acf3-9886b1d1b231)
[sql文件.txt](https://github.com/user-attachments/files/16928319/sql.txt)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
cr

**Comment by hoperunChen** [comment]
已修复，待新版本发布
