### ISSUE TITLE
报表钻取参数错误

### ISSUE THREAD

**Issue by yupenglideyupeng** [jeecgboot/JimuReport#2959]
##### 问题描述：
报表钻取的参数，获取的都是第一个的值，时间范围是月份下的字段

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/fdcdd449-c745-40a5-97d8-bd6a2115b8ef)
![image](https://github.com/user-attachments/assets/700a7263-703b-4da4-a3ba-9aa2eaae7c89)
点击后浏览器地址中的name列的正常的，yearMonth年月列是第一行的
![image](https://github.com/user-attachments/assets/2e9f249e-51e6-413d-a268-c19a9cd2a3c8)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
更新下版本，在1.7.52版本中已经修复该问题了。
#2568
