### ISSUE TITLE
循环块多行打印排版问题

### ISSUE THREAD

**Issue by laifu901** [jeecgboot/JimuReport#296]
##### 截图&代码：

![QQ图片20210531103442](https://user-images.githubusercontent.com/39521412/120252801-21192880-c2b8-11eb-8135-febd0a5f2769.png)
![QQ图片20210531103347](https://user-images.githubusercontent.com/39521412/120252811-28d8cd00-c2b8-11eb-848d-31146ab72231.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by laifu901** [comment]
如果不能重现，请在第一页和第二页连接处进行循环测试

**Comment by zhangdaiscott** [comment]
收录 yf

**Comment by zhangdaiscott** [comment]
先归集到https://github.com/jeecgboot/JimuReport/issues/138，待安排处理
