### ISSUE TITLE
循环设置打印页码，会导致打印的页面越来越多空白，导致后面打印分页错乱

### ISSUE THREAD

**Issue by tjs123** [jeecgboot/JimuReport#2960]
##### 版本号：
1.

##### 问题描述：
循环设置打印页码，会导致打印的页面越来越多空白，导致后面打印分页错乱

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/938015e4-912b-4026-8ca9-6d986b89c1a4)

这个标红的地方有页码就越来越宽

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
版本号是啥？报表是怎么设计的？
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
