### ISSUE TITLE
大数据excel 导出问题

### ISSUE THREAD

**Issue by Tannysiu** [jeecgboot/JimuReport#2961]
##### 版本号：
v1.7.9

##### 问题描述：
数据量57万，列数45列，导出时无响应

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/3bfc339f-397e-418f-82e0-c8436a96e5fc)

![Uploading de10c2d1663e15f7252fcba0c4f65fc.png…]()

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
后台报错还是？

**Comment by xiaohuo12138** [comment]
你这肯定内存溢出了，积木导出的做法是把数据全部加载到内存中，然后进行渲染的，至于大数据和非大数据导出只是excel的样式不同而已，不得不说积木的代码是真挺烂的，怪不得不开源，还把代码混淆了，可能怕别人笑话。你这块自己写一个类自己用流式导出，把容器里面他注入的那个类替换调，用自己的逻辑导出就好了，没记错的话是这个接口IJmReportExportExcel，自己实现一个导出方法吧

**Comment by jeecgos** [comment]
后台有报内存溢出的异常吗？1.8.1版本导出功能，如果内存不够系统会给提示，您可以试试。

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
