### ISSUE TITLE
单元格预览时太宽

### ISSUE THREAD

**Issue by CaptainTomSparta** [jeecgboot/JimuReport#2963]
##### 版本号：
V1.8.0

##### 问题描述：
单元格宽度如何能自动根据内容来调整宽度，避免内容被遮挡，或者产生较多空格

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/aaceebe2-ea88-4fb4-a9fc-7e7a8bf246bd)

![image](https://github.com/user-attachments/assets/49e19420-c03e-4ba4-b65d-5af7b95fbbde)

##### 重现步骤：
打开任意模板，拉宽单元格，保存，预览报表

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
不支持自适应宽高。可以使用自动换行来避免内容过多被遮挡问题。
