### ISSUE TITLE
导出问题

### ISSUE THREAD

**Issue by AreaSrv** [jeecgboot/JimuReport#2964]
##### 版本号：
v1.6.6

##### 问题描述：
导出的Excel表，有一列日期格式的，但是现在用WPS选中这一列设置单元格格式为年月类型或者格式化为年类型，会不生效。这是什么情况呢

##### 错误日志&截图：
![屏幕截图 2024-09-11 111824](https://github.com/user-attachments/assets/65de4013-cb5b-482c-97fb-4218cc58361b)
![微信图片_20240911111416](https://github.com/user-attachments/assets/ab77ccb2-d3f8-4a70-97b6-3f3d62d3d65d)

##### 重现步骤：
1、导出具有日期内容的excel
2、将日期列进行单元格格式化
3、格式化后数据没有按照格式化后的形式显示

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 1298191366** [comment]
已修复，待新版本发布。新版本非大数据模式下可用
