### ISSUE TITLE
spring3 的最新版的鉴权怎么处理

### ISSUE THREAD

**Issue by gitskybo** [jeecgboot/JimuReport#2965]
##### 版本号：
1.8.1

##### 问题描述：
JmReportTokenServiceI 接口缺失，新的鉴权应该如何处理

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/efce6eea-5e04-4d9c-bfc1-c2e0b8ed1ca5)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
spring3 ？

**Comment by gitskybo** [comment]
> spring3 ？

<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot3-starter-fastjson2</artifactId>
  <version>1.8.1</version>
</dependency>
这个依赖 ， spring-boot3 版本下无这个鉴权接口拉

**Comment by zhangdaiscott** [comment]
![image](https://github.com/user-attachments/assets/7f57b6bf-771f-4299-acba-91f0c5786bd4)

我们测试集成没有问题啊

**Comment by gitskybo** [comment]
> ![image](https://private-user-images.githubusercontent.com/3162115/366367154-7f57b6bf-771f-4299-acba-91f0c5786bd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMTA2ODIsIm5iZiI6MTcyNjExMDM4MiwicGF0aCI6Ii8zMTYyMTE1LzM2NjM2NzE1NC03ZjU3YjZiZi03NzFmLTQyOTktYWNiYS05MWYwYzU3ODZiZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMDMwNjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODBkZWI3ZjBhNjc0YTk2ZmE2NTQ2ZTNjNjljYmIzNWRiYjc2ZWM2MDUxY2YwZmI0OTVmMTFkZTQ4MDQzZDU1ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D9XAVjXHr_FvXhqG9VkaX-YYIgOErkH4ftDXEgqMBT8)
> 
> 我们测试集成没有问题啊

说出来可能不信，昨天刷新了几次没有出这个依赖，今天来重新再拉过就有了。
![image](https://github.com/user-attachments/assets/31ceaf4c-4bd6-44f4-a537-365393654f16)
