### ISSUE TITLE
设计已创建数据报表 页面报错 --》 保存失败，可能是版本已过时，请刷新重试!

### ISSUE THREAD

**Issue by zepinZheng** [jeecgboot/JimuReport#2966]
##### 版本号：
<dependency>
   <groupId>org.jeecgframework.jimureport</groupId>
   <artifactId>jimureport-spring-boot-starter</artifactId>
   <version>1.8.1</version>
</dependency>

##### 问题描述：
新创建数据报表 首次创建保存后  再次打开报错   保存失败，可能是版本已过时，请刷新重试!
点击保存按钮 同自动保存都会报此错误

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/0295b1fa-4bd5-4084-a9d7-63952ea93249)
![image](https://github.com/user-attachments/assets/3004a4bb-8d33-4f84-9fb4-7d990e9d4f54)

##### 重现步骤：
设计已创建数据报表 页面报错 保存失败，可能是版本已过时，请刷新重试!

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
同一个报表是不是在多个标签页中打开了？

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
