### ISSUE TITLE
单元格中使用concat函数做字符串连接时错误

### ISSUE THREAD

**Issue by Phoenix1996** [jeecgboot/JimuReport#2969]
##### 版本号：
1.8.1

##### 问题描述：
concat函数做字符串连接时，如果其中有英文字符冒号 : 
会出现错误java.lang.NumberFormatException: For input string: ""

##### 错误日志&截图：
![655324e751d857ebd804f7c2647ab1e](https://github.com/user-attachments/assets/e654638b-08c8-4a44-a0c2-ae8e21667652)
![3ed516580835cccdbffd9007924350b](https://github.com/user-attachments/assets/14bb4091-f16d-4cf7-ac3c-322cf551036f)

##### 重现步骤：

连接字符串中使用英文冒号会出现错误，中文冒号不影响

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Phoenix1996** [comment]
1.7.9版本升级到1.8.1后出现的问题

**Comment by zhangdaiscott** [comment]
收到  cr

**Comment by hoperunChen** [comment]
已修复，待新版本发布。
