### ISSUE TITLE
在报表设计器中如何使用超大字号

### ISSUE THREAD

**Issue by greatneal29** [jeecgboot/JimuReport#2970]
##### 版本号：
1.7.9

##### 问题描述：
在报表设计器中，想使用超大字号，但是设计器只能下拉选择42号，也不能手动输入字号。
我们想打印一个牌号（截图里有样例），字号估计要150以上了，是超大字号。

##### 错误日志&截图：
![微信图片_20240913094339](https://github.com/user-attachments/assets/f1a5e3f1-1041-4cd1-8623-651ca65502e4)
![微信图片_20240913094348](https://github.com/user-attachments/assets/85da5248-3f09-47ee-8415-f5b4baca6ea0)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
好，我们规划下

**Comment by liaozhiyang** [comment]
已新增自定义字体大小功能，下一版本发布。
![image](https://github.com/user-attachments/assets/7d166b71-4323-4060-b5d1-43f2eb2d4413)
