### ISSUE TITLE
可以像EXCEL那样填报码？可以拆入行吗？

### ISSUE THREAD

**Issue by phoenixlucky** [jeecgboot/JimuReport#2971]
##### 问题描述：
试了，好像是不支持插入新行的，只能按照固定样式填报

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/f75a0b9d-f0d0-41d5-986c-acd10496b11c)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
下个版本支持子表
