### ISSUE TITLE
jmreport可上传任意文件

### ISSUE THREAD

**Issue by redu77** [jeecgboot/JimuReport#2972]
##### 版本号：1.8.1
org.jeecgframework.jimureport  1.8.1

##### 问题描述：
Jmreport的上传功能没有正确地限制上传文件的类型或进行安全校验，可上传任意类型文件

##### 错误日志&截图：
{
	"success": true,
	"message": "jimureport/Redis1726280730435.bat",
	"code": 0,
	"result": null,
	"timestamp": 1726280730415
}

##### 重现步骤：
该接口可上传任意文件：http://boot3.jeecg.com/jeecgboot/jmreport/upload

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
