### ISSUE TITLE
字典字段渲染时，报错

### ISSUE THREAD

**Issue by crazy9527** [jeecgboot/JimuReport#2974]
##### 版本号：
1.7.8

##### 问题描述：
jdk17，sringboot3，集成积木报表，渲染字典字段时，抛异常。无字典字段时，显示正常

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/1e9a1e55-55a0-4e57-9dcd-2dfcf5826504)
![image](https://github.com/user-attachments/assets/807d5fe2-a74a-463c-8cc2-466beed9f45b)
![image](https://github.com/user-attachments/assets/21ed2a61-8793-4e8f-a6dd-8e6138defa58)

##### 重现步骤：
对表中的字典字段就行 渲染时，会报错。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
@crazy9527 图片看不清，重传一个清晰的图片？

**Comment by jeecgos** [comment]
ws

**Comment by crazy9527** [comment]
<img width="1231" alt="1" src="https://github.com/user-attachments/assets/0db7d09a-03b0-4c88-baee-fea1cff12550">
<img width="1240" alt="2" src="https://github.com/user-attachments/assets/9aec8074-941a-41e7-9f74-52bae922d1b7">
<img width="545" alt="3" src="https://github.com/user-attachments/assets/3b612fde-4032-461a-803e-e17967145823">

**Comment by crazy9527** [comment]
@jeecgos 已上传清晰图片

**Comment by 1298191366** [comment]
已修复，待新版本发布

**Comment by zxwl666** [comment]
我也遇到了这个问题，集成在芋道里的
