### ISSUE TITLE
预览白屏

### ISSUE THREAD

**Issue by hh-cat** [jeecgboot/JimuReport#2975]
##### 版本号：1.8.1
maven依赖：
```xml
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.8.1</version>
</dependency>
```

##### 问题描述：
报表制作完成之后，点击预览显示白屏。看issue#2919提到说要登录后才能正常访问。我这边已经是实现了JmReportTokenServiceI接口实现了token的鉴权，带上token之后/jmreport/list可以正常显示，其他功能也正常，就是预览白屏。
我也在配置文件中配置了预览不需要登录，但是无效，配置如下：
```yaml
spring:
  security:
    # view 页面允许不登录访问（默认false）
    open-view-page: true
```

##### 错误日志&截图：
点击预览之后白屏：
![Clip_2024-09-16_15-16-48](https://github.com/user-attachments/assets/f9b6775d-095b-4a47-9aa0-703d2370eb30)
控制台报错：
![Clip_2024-09-16_15-15-12](https://github.com/user-attachments/assets/70586a2c-7c1e-4df8-ac8a-1d52740efff0)
![Clip_2024-09-16_15-16-23](https://github.com/user-attachments/assets/4eac8521-1c50-4740-a6e5-b60b0bd8aa8c)
数据已经正确返回到前端：
![Clip_2024-09-16_15-15-58](https://github.com/user-attachments/assets/d592c5bc-6316-4b7e-958d-39fbe6378718)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by hh-cat** [comment]
导出pdf正常，可以看到数据。

**Comment by hh-cat** [comment]
分享链接也是白屏。

**Comment by zhangdaiscott** [comment]
新设计个报表看看

**Comment by hh-cat** [comment]
> 新设计个报表看看

我新建了一个报表，没有添加数据集，尽在页面上随意写了几个单元格，也是无法预览。

**Comment by zhangdaiscott** [comment]
没见别人反馈类似问题，你是使用的那个版本

**Comment by hh-cat** [comment]
> 没见别人反馈类似问题，你是使用的那个版本

从maven依赖的版本来看是1.8.1

**Comment by zhangdaiscott** [comment]
清空下浏览器缓存试试

**Comment by zhangdaiscott** [comment]
使用的是集成版还是，把依赖加入到自己的项目

**Comment by hh-cat** [comment]
> 使用的是绿色免安装版本还是，把依赖加入到自己的项目
> 
> 截图中的那个
> 
> ![image](https://private-user-images.githubusercontent.com/3162115/367972569-f9350cec-bc34-4049-b65c-b55e81c952c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MzczNzYsIm5iZiI6MTcyNjUzNzA3NiwicGF0aCI6Ii8zMTYyMTE1LzM2Nzk3MjU2OS1mOTM1MGNlYy1iYzM0LTQwNDktYjY1Yy1iNTVlODFjOTUyYzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTdUMDEzNzU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2QwMmVlNzRiZjA1NjlkN2Y4ZTExMjMyY2U0NjE2ZTEzNmJjMWQ0NWFiYWU0ZDJkOGVjMWQ5MzA3NGM0ZGEzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.H6GZd2O-v6imu2kVqpQbQk3aIwWsk2tO6T8s0I7lJh4) ![image](https://private-user-images.githubusercontent.com/3162115/367972588-ea2176eb-4964-4a5d-9d7e-e3abfe0634e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MzczNzYsIm5iZiI6MTcyNjUzNzA3NiwicGF0aCI6Ii8zMTYyMTE1LzM2Nzk3MjU4OC1lYTIxNzZlYi00OTY0LTRhNWQtOWQ3ZS1lM2FiZmUwNjM0ZTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTdUMDEzNzU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjg4ZmFiOTBlZDk2YWZlZTFhNzczM2I0ZjhhYmE3NWQ5ZWRkNTAxZDM2MjI0MWIwZDkyNTFlMTE5NzU0NzExNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.10fyp-H8Kk385kbx1kUl4k6Fcy5q1hnlRccS0e_dPSQ)

我是集成到我自己的项目里面:
1. 添加maven依赖：
```xml
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.8.1</version>
</dependency>
```

2. 执行数据库初始化脚本
https://github.com/zhangdaiscott/JimuReport/blob/master/db

3. 实现了JmReportTokenServiceI
```java
@Slf4j
@Component
public class JimuReportSecurityConfigService implements JmReportTokenServiceI {


    @Override
    public String getUsername(String token) {
        if (StrUtil.isBlank(token)) {
            return null;
        }
        SaSession tokenSessionByToken = StpUtil.getTokenSessionByToken(token);
        if (tokenSessionByToken == null) {
            return null;
        }
        Object loginUserObj = tokenSessionByToken.get("loginUser");
        if (loginUserObj instanceof LoginUser) {
            SysUser user = ((LoginUser) loginUserObj).getUser();
            if (user == null) {
                return null;
            }
            return user.getUserName();
        }
        return null;
    }

    @Override
    public String[] getRoles(String token) {
        return new String[]{"admin"};
    }

    @Override
    public Boolean verifyToken(String token) {
        Object loginId = StpUtil.getLoginIdByToken(token);
        return StpUtil.isLogin(loginId);
    }
}
```

**Comment by hh-cat** [comment]
清空了浏览器缓存，换了浏览器，也还是白屏。
导出功能正常，可以导出PDF，PDF中数据也正常。

**Comment by hh-cat** [comment]
我发现了一点端倪！我新建了一个spring boot项目，然后按照上面的步骤集成报表，可以正常预览报表。我的对比了两个项目，发现 **/jmreport/show** 接口的响应不一样，请帮看看能不能定位到是哪里的问题。详情如下：

![Clip_2024-09-17_10-23-07](https://github.com/user-attachments/assets/63126d8c-6e70-41e4-a775-16ebee5175c3)

**Comment by zhangdaiscott** [comment]
不知道了，看看身边同事的情况

**Comment by zhangdaiscott** [comment]
要么你浏览器版本过低？

**Comment by hh-cat** [comment]
> 我发现了一点端倪！我新建了一个spring boot项目，和白屏应用连接同一个数据库，然后按照上面的步骤集成报表，可以正常预览报表。我的对比了两个项目，发现 **/jmreport/show** 接口的响应不一样，请帮看看能不能定位到是哪里的问题。详情如下：
> 
> ![Clip_2024-09-17_10-23-07](https://private-user-images.githubusercontent.com/19165905/367985962-63126d8c-6e70-41e4-a775-16ebee5175c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MDE0MDEsIm5iZiI6MTcyNjkwMTEwMSwicGF0aCI6Ii8xOTE2NTkwNS8zNjc5ODU5NjItNjMxMjZkOGMtNmU3MC00MWU0LWE3NzUtMTZlYmVlNTE3NWMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDA2NDUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZGRiMjhjY2QzODU1ZjI4YjVmNzA3NGVlNTc3NzgwNjk2ZTRmNDZiZDNiZmMwNDNlYjllY2Y5MGFlZDlhNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PKHMYK9Wz2xS6_gMwk-sVxJOJWiPRrUKtYVuP7Z7_as)

就是这个问题导致的！哈哈
org.jeecg.modules.jmreport.desreport.entity.JimuReport类中的jsonStr字段值和getJsonStr方法返回值不一样，getJsonStr方法没有直接返回jsonStr字段的值，而是返回了jsonStrJson字段的值。正常的spring boot项目使用Jackson框架序列化接口响应值，默认会调用getter方法获取字段值，但是我的项目中配置了fastjson2来序列化接口响应值，并且设置了FieldBased策略，这种策略不会调用getter方法，而是通过反射直接获取对象的属性，jsonStr属性是没有值的，所以接口就没有返回jsonStr数据，导致报错白屏。
看看这个问题要不要解决一下，我现在是单独为JimuReport类中的jsonStr字段写了序列化的逻辑，功能正常啦。
@zhangdaiscott

**Comment by zhangdaiscott** [comment]
cr

**Comment by jeecgos** [comment]
已修复，待新版本发布。
