### ISSUE TITLE
绿色免安装版无法配置数据集

### ISSUE THREAD

**Issue by wjnhdd** [jeecgboot/JimuReport#2976]
##### 错误日志&截图：
![ZJL2}K07)QM{W52S%TNC}8H](https://github.com/user-attachments/assets/8cc3709a-babd-4308-b18a-e88ba8a2e37a)

![GZM1@8%OOVN)D7_G5S ~AUH](https://github.com/user-attachments/assets/41d878ab-9af9-427b-b06a-30c8e4b16dcb)

##### 重现步骤：
详见附件log日志文件

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
执行下这里面的仪表盘的升级sql
http://jimureport.com/doc/log
