### ISSUE TITLE
在线免费版数据源

### ISSUE THREAD

**Issue by wjnhdd** [jeecgboot/JimuReport#2977]
##### 版本号：
当前在线免费版

##### 问题描述：
1、在线免费版支持云原生数据仓库 AnalyticDB PostgreSQL 作为数据源吗？
2、支持链接用户本地数据库吗？用户本地指的是个人电脑装的本地数据库（尝试了下没成功连接）

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/85ae6df2-ad89-4475-b8a3-0537c2c88957)

##### 重现步骤：
在线版本尝试连接本地数据库：大屏数据源-新建-配置MYSQL连接-测试连接提示截图所示异常

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/user-attachments/assets/51777db8-2e46-464a-816c-d19014cd5705)

需要改成你服务器的正式IP，并开放数据库端口

**Comment by wjnhdd** [comment]
在线免费版支持云原生数据仓库 AnalyticDB PostgreSQL 作为数据源吗？

**Comment by zhangdaiscott** [comment]
应该没什么区别
