### ISSUE TITLE
表头横向动态合并问题

### ISSUE THREAD

**Issue by 273063020** [jeecgboot/JimuReport#2978]
##### 错误日志&截图：
![QQ_1726796262030](https://github.com/user-attachments/assets/b12e0e34-3ca8-475f-91b5-d7d02357254e)
![QQ_1726796393794](https://github.com/user-attachments/assets/091a9c59-53bf-4c7d-884b-6090cc4bb1c8)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
文档：[横向分组(相邻合并)](https://help.jeecg.com/jimureport/group/transverseDynamic.html)
