### ISSUE TITLE
自定义聚合函数报错

### ISSUE THREAD

**Issue by yanwencheng** [jeecgboot/JimuReport#2979]
##### 版本号：
1.8.0

##### 问题描述：
按照例子（https://ojrjjvdr7z.k.topthink.com/jimureport/function/custom.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8A%A5%E8%A1%A8%E5%87%BD%E6%95%B0%E6%94%AF%E6%8C%81%E5%8A%A8%E6%80%81%E8%A1%8C%E7%9A%84%E8%81%9A%E5%90%88%E8%AE%A1%E7%AE%97）做聚合计算提示方法不存在
![image](https://github.com/user-attachments/assets/77ff4ff4-f82a-4dc8-b418-ab1e888564f2)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
自定义函数写完 注册了吧？请提供您本地自定义函数相关的完整代码 。
![QQ_1726834386790](https://github.com/user-attachments/assets/60eb7e42-1dd9-404f-a534-64df2e867380)

**Comment by yanwencheng** [comment]
> 自定义函数写完 注册了吧？请提供您本地自定义函数相关的完整代码 。 ![QQ_1726834386790](https://private-user-images.githubusercontent.com/162332873/369399001-60eb7e42-1dd9-404f-a534-64df2e867380.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNTUyMDAsIm5iZiI6MTcyNzA1NDkwMCwicGF0aCI6Ii8xNjIzMzI4NzMvMzY5Mzk5MDAxLTYwZWI3ZTQyLTFkZDktNDA0Zi1hNTM0LTY0ZGYyZTg2NzM4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwMTI4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDJkOTY3ZWEyYjBlNmUwMmY3MjQ3ZmViYTg5ZjcwN2QyMDBjY2I3ZDFiN2JkZDI2YTM4MTE1ODk4ZjRjNjEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._cZnjcuCKUoDyjnvttkDO_CIu7rlTf3p7I5jy8vLIwk)
用的聚合函数，报的图中圈起地方的错误
![image](https://github.com/user-attachments/assets/604e356e-15f6-436e-a5f9-9ab45e005504)

**Comment by yanwencheng** [comment]
> 自定义函数写完 注册了吧？请提供您本地自定义函数相关的完整代码 。 ![QQ_1726834386790](https://private-user-images.githubusercontent.com/162332873/369399001-60eb7e42-1dd9-404f-a534-64df2e867380.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNTUyMDAsIm5iZiI6MTcyNzA1NDkwMCwicGF0aCI6Ii8xNjIzMzI4NzMvMzY5Mzk5MDAxLTYwZWI3ZTQyLTFkZDktNDA0Zi1hNTM0LTY0ZGYyZTg2NzM4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwMTI4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDJkOTY3ZWEyYjBlNmUwMmY3MjQ3ZmViYTg5ZjcwN2QyMDBjY2I3ZDFiN2JkZDI2YTM4MTE1ODk4ZjRjNjEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._cZnjcuCKUoDyjnvttkDO_CIu7rlTf3p7I5jy8vLIwk)
用的聚合函数，报的是图中圈起的地方方法不存在
![image](https://github.com/user-attachments/assets/633eb023-e932-412f-821d-1c11cc1633e8)

**Comment by hoperunChen** [comment]
`ExpressUtil.getIgnoreCells(env)`可以改为：`List<String> ignoreCells = (List<String>) env.get("ignore");`
文档已经做了调整。

**Comment by yanwencheng** [comment]
> `ExpressUtil.getIgnoreCells(env)`可以改为：`List<String> ignoreCells = (List<String>) env.get("ignore");` 文档已经做了调整。

好的
