### ISSUE TITLE
合并两行表格，打印数据显示有问题

### ISSUE THREAD

**Issue by baohaolong6666** [jeecgboot/JimuReport#298]
##### 版本号：
1.3.21-beta

##### 问题描述：
合并两行表格，打印数据显示有问题。合并两行，但是数据回显只有一行，而且只带边框。

##### 截图&代码：
报表设计图：
![image](https://user-images.githubusercontent.com/47874532/120412304-eaf7a980-c388-11eb-8fd6-1005504e99d2.png)
报表预览图：
![image](https://user-images.githubusercontent.com/47874532/120412338-f945c580-c388-11eb-961f-235151c5587b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
确认有问题

**Comment by zhangdaiscott** [comment]
收录  ty

**Comment by accpman** [comment]
数据化不支持合并行，通过调整单元格高度来适应

**Comment by zhangdaiscott** [comment]
已经修复，升级到版本1.3.63-beta , 要[配置私服](http://report.jeecg.com/2195924)


```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.63-beta</version>
</dependency>
```
