### ISSUE TITLE
外部的系统里导入积木报表的链接后打开会报错提示

### ISSUE THREAD

**Issue by amwylig** [jeecgboot/JimuReport#2981]
##### 版本号：
1.8.1

##### 问题描述：
在外部的系统里导入积木报表的链接后打开会报错提示，拒绝我们的链接请求，但是1.6.6的版本就可以正常访问

##### 错误截图：
![image](https://github.com/user-attachments/assets/e6140ff3-b34b-4061-820d-a250032bb077)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by jeecgos** [comment]
cr

**Comment by hoperunChen** [comment]
已修复，待新版本发布。
