### ISSUE TITLE
通过API配置数据字典问题

### ISSUE THREAD

**Issue by lm798880844** [jeecgboot/JimuReport#2982]
##### 版本号：
v1.8.1

##### 问题描述：
通过API配置数据字典不成功

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/ea573f97-3525-427a-9b94-801137a80ce8)
![image](https://github.com/user-attachments/assets/643e6a4c-65dd-42d4-85b2-68c41f0834fb)
![image](https://github.com/user-attachments/assets/d17aabf9-32bd-4039-bfa6-e1ad60957cb6)
![image](https://github.com/user-attachments/assets/fff00f04-e1bd-428d-90ab-5fdaff29e64b)

##### 重现步骤：
通过这个 https://help.jeecg.com/jimureport/queryCriteria/dictionary.html 的配置方式，没能成功实现API配置数据字典，麻烦看看是什么原因吧！

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
