### ISSUE TITLE
导出pdf报错

### ISSUE THREAD

**Issue by gouchanghong** [jeecgboot/JimuReport#2983]
##### 问题描述：导出pdf报错
1.7.8版本中，日志里就存在一个空指针报错，但是不影响导出，到了1.8.11版本，直接影响导出。

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/5534bc34-e50d-4685-bb3b-d55255231c0d)

已在官网制作报表：
https://bootapi.jeecg.com/jmreport/view/997054565948149760?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MjY0MTExODUsInVzZXJuYW1lIjoiMTc3ODQxNzk5NTQifQ.tzMkhY30Jh68cGwAZMpBBngxBJWkcSr8Yo9k7PHWH1M&tenantSid=1807647282561093634&applySid=1836589030659637250

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws
