### ISSUE TITLE
ruoyi单体版本集成后，在仪表盘设计器中创建数据源后显示无操作权限。

### ISSUE THREAD

**Issue by defaultw** [jeecgboot/JimuReport#2985]
##### 版本号：
1.8.1-beta

##### 问题描述：
ruoyi单体版本集成后，在仪表盘设计器中创建数据源后显示无操作权限。

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/b8a1407d-a865-46eb-8e55-9b47f4920cf6)

##### 重现步骤：
1. 在单体应用中创建新的模块，并导入JimuReport相关依赖；
2. 启动服务，页面显示正常；
3. 进入仪表盘设计器，新建仪表盘，点击【数据源】按钮新建mysql类型数据源。

**Comment by zhangdaiscott** [comment]
需要拥有admin角色

**Comment by shiwuye888** [comment]
> 需要拥有admin角色

这个要在哪创建？

**Comment by shiwuye888** [comment]
> ##### 版本号：
> 1.8.1-beta
> 
> ##### 问题描述：
> ruoyi单体版本集成后，在仪表盘设计器中创建数据源后显示无操作权限。
> 
> ##### 错误日志&截图：
> ![image](https://private-user-images.githubusercontent.com/46698747/369669090-b8a1407d-a865-46eb-8e55-9b47f4920cf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNjE1MTMsIm5iZiI6MTcyNzA2MTIxMywicGF0aCI6Ii80NjY5ODc0Ny8zNjk2NjkwOTAtYjhhMTQwN2QtYTg2NS00NmViLThlNTUtOWI0N2Y0OTIwY2Y2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDAzMTMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZDU1NDZlMjk0NGJhOTA4ZGY3NWEwNDk0ZTNkNjI0ZDkwNmI0MTk0ZDQxMWY4OTBkYjBlZTJkOTUyMTczYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lP-V_JgRrTdGd_pnsaCOqhSznyL1z9uB5jkRFRoQI98)
> 
> ##### 重现步骤：
> 1. 在单体应用中创建新的模块，并导入JimuReport相关依赖；
> 2. 启动服务，页面显示正常；
> 3. 进入仪表盘设计器，新建仪表盘，点击【数据源】按钮新建mysql类型数据源。

你解决了吗？

**Comment by shiwuye888** [comment]
你解决了吗？

**Comment by defaultw** [comment]
> 需要拥有admin角色

![image](https://github.com/user-attachments/assets/76fc680a-47c7-414d-b374-2804ce6ae5dc)
已经是管理员登录了

**Comment by shiwuye888** [comment]
> > 需要拥有admin角色
> 
> ![image](https://private-user-images.githubusercontent.com/46698747/369760160-76fc680a-47c7-414d-b374-2804ce6ae5dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNzc3ODEsIm5iZiI6MTcyNzA3NzQ4MSwicGF0aCI6Ii80NjY5ODc0Ny8zNjk3NjAxNjAtNzZmYzY4MGEtNDdjNy00MTRkLWIzNzQtMjgwNGNlNmFlNWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA3NDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YTBkNjQyYzkwODkyMzcxZjY4NTU4OTkyM2MxNDc3YTE2YWRiZmI4Y2MxMGNlZDExMTk1MTNkNDE1ODlkYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LhK7JMruScHca-FzrqlTQ8gldzAeCzaHEi1jxPpYAFg) 已经是管理员登录了，ruiyi版本为4.7.9

/**
 * @author Yx.Gui
 * @date 2024/9/23
 */
@Component
@Slf4j
public class JimuReportTokenService implements JmReportTokenServiceI {

    @Resource
    TokenService tokenService;

    @Override
    public String getToken(HttpServletRequest request) {
        log.info("JimuReportTokenService getToken:{}", JmReportTokenServiceI.super.getToken(request));
        return JmReportTokenServiceI.super.getToken(request);
    }

    @Override
    public String getUsername(String s) {
        log.info("JimuReportTokenService getUsername:{}", s);
//        LoginUser loginUser = tokenService.geUser(s);
        return "admin";
    }

    @Override
    public String[] getRoles(String s) {
        return new String[0];
    }

    @Override
    public Boolean verifyToken(String s) {
        log.info("JimuReportTokenService verifyToken:{}", s);
        return true;
    }
}

**Comment by defaultw** [comment]
> > > 需要拥有admin角色
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/46698747/369760160-76fc680a-47c7-414d-b374-2804ce6ae5dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNzc3ODEsIm5iZiI6MTcyNzA3NzQ4MSwicGF0aCI6Ii80NjY5ODc0Ny8zNjk3NjAxNjAtNzZmYzY4MGEtNDdjNy00MTRkLWIzNzQtMjgwNGNlNmFlNWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA3NDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YTBkNjQyYzkwODkyMzcxZjY4NTU4OTkyM2MxNDc3YTE2YWRiZmI4Y2MxMGNlZDExMTk1MTNkNDE1ODlkYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LhK7JMruScHca-FzrqlTQ8gldzAeCzaHEi1jxPpYAFg) 已经是管理员登录了，ruiyi版本为4.7.9
> 
> /**
> 
> * @author Yx.Gui
> * @Date 2024/9/23
>   */
>   @component
>   @slf4j
>   public class JimuReportTokenService implements JmReportTokenServiceI {
>   @resource
>   TokenService tokenService;
>   @OverRide
>   public String getToken(HttpServletRequest request) {
>   log.info("JimuReportTokenService getToken:{}", JmReportTokenServiceI.super.getToken(request));
>   return JmReportTokenServiceI.super.getToken(request);
>   }
>   @OverRide
>   public String getUsername(String s) {
>   log.info("JimuReportTokenService getUsername:{}", s);
>   //        LoginUser loginUser = tokenService.geUser(s);
>   return "admin";
>   }
>   @OverRide
>   public String[] getRoles(String s) {
>   return new String[0];
>   }
>   @OverRide
>   public Boolean verifyToken(String s) {
>   log.info("JimuReportTokenService verifyToken:{}", s);
>   return true;
>   }
>   }
> 
> getUserName返回一定是admin然后去新增数据源和数据集就有修改和删除了

可以啦，谢谢了😀

**Comment by defaultw** [comment]
> > > > > 需要拥有admin角色
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/46698747/369760160-76fc680a-47c7-414d-b374-2804ce6ae5dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNzc3ODEsIm5iZiI6MTcyNzA3NzQ4MSwicGF0aCI6Ii80NjY5ODc0Ny8zNjk3NjAxNjAtNzZmYzY4MGEtNDdjNy00MTRkLWIzNzQtMjgwNGNlNmFlNWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA3NDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YTBkNjQyYzkwODkyMzcxZjY4NTU4OTkyM2MxNDc3YTE2YWRiZmI4Y2MxMGNlZDExMTk1MTNkNDE1ODlkYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LhK7JMruScHca-FzrqlTQ8gldzAeCzaHEi1jxPpYAFg) 已经是管理员登录了，ruiyi版本为4.7.9
> > > 
> > > 
> > > /**
> > > 
> > > * @author Yx.Gui
> > > * @Date 2024/9/23
> > >   */
> > >   @component
> > >   @slf4j
> > >   public class JimuReportTokenService implements JmReportTokenServiceI {
> > >   @resource
> > >   TokenService tokenService;
> > >   @OverRide
> > >   public String getToken(HttpServletRequest request) {
> > >   log.info("JimuReportTokenService getToken:{}", JmReportTokenServiceI.super.getToken(request));
> > >   return JmReportTokenServiceI.super.getToken(request);
> > >   }
> > >   @OverRide
> > >   public String getUsername(String s) {
> > >   log.info("JimuReportTokenService getUsername:{}", s);
> > >   //        LoginUser loginUser = tokenService.geUser(s);
> > >   return "admin";
> > >   }
> > >   @OverRide
> > >   public String[] getRoles(String s) {
> > >   return new String[0];
> > >   }
> > >   @OverRide
> > >   public Boolean verifyToken(String s) {
> > >   log.info("JimuReportTokenService verifyToken:{}", s);
> > >   return true;
> > >   }
> > >   }
> > > 
> > > getUserName返回一定是admin然后去新增数据源和数据集就有修改和删除了
> > 
> > 
> > 可以啦，谢谢了😀
> 
> 没想到吧，这个是我提出的，我自己解决了。

哈哈哈哈 刚注意到🤣
