### ISSUE TITLE
积木报表主子报表关联问题

### ISSUE THREAD

**Issue by 2655722451** [jeecgboot/JimuReport#2986]
##### 版本号：
jdk：11
sqlserver数据库：sqlServer 2016
积木报表版本：1.7.8
jeecg-boot版本：3.6.2

##### 问题描述：

我已经成功地配置了一个包含主表和从表的报表，并在设计中添加了循环块以处理数据集合。然而，在运行报表时，我发现尽管主表的数据结果集能够正确遍历，但从表的结果集却没有实现同样的遍历效果。我想请问这是由何种原因造成的？是否是在配置环节存在某些需要调整的地方？
##### 错误日志&截图：

我还注意到在主子报表参数设置中，我已尝试进行相应的关联配置，但在实际测试中，这些设置似乎并未生效。
为了便于您的理解，以下是主子表的数据格式示例：
![1](https://github.com/user-attachments/assets/84b813af-bb52-4b37-82e3-04a54b080c06)

关联是通过主子报表参数设置这里设置的，但测试发现实际并没有关联上：
![2](https://github.com/user-attachments/assets/fe197ff9-2265-49dc-b7bb-de209172543d)

主子表的数据格式如下：
![3](https://github.com/user-attachments/assets/ef7bf272-a994-4b54-8a5b-8a2f774a099d)

##### 重现步骤：
为方便理解下面文件是上面描述的测试demo：
[1BookingOrder (8) (1).json](https://github.com/user-attachments/files/17092244/1BookingOrder.8.1.json)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
cr

**Comment by hoperunChen** [comment]
你的子表数据集的查询参数需要传给你的api接口（比如：http://localhost/xxxx?id=${bookingOrderId}），然后在你的api接口里面根据参数对数据进行过滤。
![QQ_1728462580676](https://github.com/user-attachments/assets/470cf1b8-c232-43e1-83b0-b40d87875f4e)

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
