### ISSUE TITLE
ruoyi-admin-plus-4.6.0集成积木报表后，静态资源无法访问

### ISSUE THREAD

**Issue by CHFisMine** [jeecgboot/JimuReport#2987]
##### 问题描述：ruoyi-vue-plus4.6.0 集成 积木报表后 静态资源无法访问,
配置列出来了，我应该怎么修改才能访问到静态资源

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/56917f64-41b7-447d-85a0-6c92142c9e14)
![image](https://github.com/user-attachments/assets/f3720f43-c1e1-4518-95e2-22334317f264)

##### 重现步骤：
![image](https://github.com/user-attachments/assets/0a653852-cdfa-4c00-b844-fd674a7dbf2e)
![image](https://github.com/user-attachments/assets/a20f7b22-fb77-4d5c-81de-ce1759d8c600)
![image](https://github.com/user-attachments/assets/06c15c53-f5f9-438a-87a4-75a338f224be)
![image](https://github.com/user-attachments/assets/e9a3edf6-5322-48f7-ac5d-0ba688d7de53)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
看文档
https://help.jeecg.com/jimureport/projectJoin/ruoyivue.html

**Comment by CHFisMine** [comment]
jeecg开发人员你好：
&nbsp; &nbsp; 我在使用ruoyi-vue-plus 集成 积木报表的时候，根据文档可以在本地环境下测试使用。但是上线以后，我发现 积木报表的请求路径存在问题:
路径拼接以后，不符合项目的nginx代理配置，nginx配置的是/prod-api 转到 ip:端口/ruoyi-admin。我配置完 重定向以后 就是跳转到正确的路径，静态资源可以访问到，但是无法新建报表，因为请求方式被改变。请教下咱们的 路径拼接是不是可以优化一下？









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月23日(星期一) 中午11:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] ruoyi-admin-plus-4.6.0集成积木报表后，静态资源无法访问 (Issue #2987)





 
看文档
 https://help.jeecg.com/jimureport/projectJoin/ruoyivue.html
