### ISSUE TITLE
集成进ruoyi后，添加数据源以及数据集无法删除以及修改

### ISSUE THREAD

**Issue by shiwuye888** [jeecgboot/JimuReport#2988]
##### 版本号：
1.8.1-beta仪表盘

##### 问题描述：
集成进ruoyi后，我自己添加数据源以及数据集无法删除以及修改

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by shiwuye888** [comment]
我看案例上的数据源以及数据集是可以修改删除的。我集成进去无法修改和删除。

**Comment by defaultw** [comment]
https://github.com/jeecgboot/JimuReport/issues/2985#issuecomment-2367453188

**Comment by zhangdaiscott** [comment]
目前设计的是需要有admin角色才能修改

**Comment by 2508207487** [comment]
> 目前设计的是 1、自己可以维护自己创建的数据集和数据源； 2、admin角色有超级权限，可以任意修改数据和数据源
> 
> 升级扩展方案 1、导入施工角色：admin、dbadeveloper、lowdeveloper都可以编辑任何数据集和数据源 2、dataSourceSafe=true的话，限制自己维护自己的或者导入施工角色 dataSourceSafe=false的话，不再限制，所有者都可以修改

我加上token鉴权后，角色部分没有动，还是admin，若依登录用户也是admin，怎么也没法修改数据和数据源

**Comment by 2508207487** [comment]
> 目前设计的是 1、自己可以维护自己创建的数据集和数据源； 2、admin角色有超级权限，可以修改任意数据和数据源
> 
> 后期扩展方案 1、内置预留角色：admin、dbadeveloper、lowdeveloper 都可以编辑任意数据集和数据源 2、dataSourceSafe=true的话，限制自己维护自己的或者内置预留角色 dataSourceSafe=false的话，不再限制，所有人都可以修改

这是token的实现类，原版的登录去掉了，若依以外链的方式携带token访问，若依登录用户是admin
/**
 * 自定义积木报表鉴权(如果不进行自定义，则所有请求不做权限控制)
 * 1.自定义获取登录token
 * 2.自定义获取登录用户
 */
@Component
public class JimuReportTokenServiceImpl implements JmReportTokenServiceI {

    @Autowired
    private TokenService tokenService;

    /**
     * 通过请求获取Token
     * @param request
     * @return
     */
    @Override
    public String getToken(HttpServletRequest request) {
        String token = tokenService.getToken(request);
        return token;
    }

    /**
     * 自定义获取租户
     *
     * @return
     */
    @Override
    public String getTenantId() {
        return "1";
    }

    
    /**
     * 通过Token获取登录人用户名
     * @param token
     * @return
     */
    @Override
    public String getUsername(String token) {
        String usernameFromToken = tokenService.getUsernameFromToken(token);
        return usernameFromToken;
    }

    /**
     * 自定义用户拥有的角色
     * 
     * @param token
     * @return
     */
    @Override
    public String[] getRoles(String token) {
        return new String[]{"admin"};
    }

    /**
     * Token校验
     * @param token
     * @return
     */
    @Override
    public Boolean verifyToken(String token) {
        LoginUser loginUser = tokenService.getLoginUser(token);
        return tokenService.verifyToken(loginUser);
    }

    /**
     *  自定义请求头
     * @return
     */
    @Override
    public HttpHeaders customApiHeader() {
        HttpHeaders header = new HttpHeaders();
        return header;
    }
}

**Comment by jeecgos** [comment]
ws

**Comment by jeecgDeveloper** [comment]
测试未复现你的问题。查看一下进到设计页面时，接口返回的角色和用户信息是否有操作权限。
