### ISSUE TITLE
自定义函数怎么接收查询参数 

### ISSUE THREAD

**Issue by yanwencheng** [jeecgboot/JimuReport#2989]
##### 版本号：
1.8.0

##### 问题描述：
1、有个查询参数 start_date，自定义了个函数，想将这个查询参数格式化获取月初日期，月末日期，怎么将查询参数start_date传入自定义函数呢？ 
##### 错误日志&截图： 
1、如果传单元格值，自定义函数获取不到
![image](https://github.com/user-attachments/assets/4b6be6ce-85eb-405c-abd4-b3a52ecf0d51)
2、如果直接传${start_date},后台获取的是1992（实际应该是2024-09-23）
![image](https://github.com/user-attachments/assets/97feebc2-808b-4813-93b3-ae55627d3583)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
ws

**Comment by hoperunChen** [comment]
已修复，待新版本发布。
在新版本中，您需要用单引号将日期类型的表达式参数包裹起来，如下：
![QQ_1728619277549](https://github.com/user-attachments/assets/9151e5f0-4631-4cb8-9eb0-24b4b0a371ba)
