### ISSUE TITLE
日期查询条件格式化错误

### ISSUE THREAD

**Issue by yanwencheng** [jeecgboot/JimuReport#2990]
##### 版本号：
1.8.0

##### 问题描述：
1、日期查询条件
![image](https://github.com/user-attachments/assets/3d775d39-5504-4800-8f71-033f37f2aec5)
2、格式化设置
=DATE_STR(${param.search_date},'yyyy年MM月')

##### 错误日志&截图：
结果显示了错误日期
![image](https://github.com/user-attachments/assets/d42ca813-902d-4c8e-a75f-81cf795a1074)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
函数中使用日期参数需要用英文单引号（'${param.search_date}'）将日期参数包裹起来。如下：
=DATE_STR('${param.search_date}','yyyy年MM月')

**Comment by hoperunChen** [comment]
函数中使用日期参数需要用英文单引号（`'`）将日期参数包裹起来。如下：
`=DATE_STR('${param.search_date}','yyyy年MM月')`
