### ISSUE TITLE
token 验证通过后 jmreport/index/1506889334194700288 谷歌浏览器显示空白

### ISSUE THREAD

**Issue by 2014shijina2014** [jeecgboot/JimuReport#2991]
##### 版本号：
1.8.1

##### 问题描述：

token 验证通过后 jmreport/index/1506889334194700288 谷歌浏览器显示空白

![微信截图_20240923170256](https://github.com/user-attachments/assets/da6132a4-5fcc-41e5-8a14-83c6f999d44c)
![微信截图_20240923174644](https://github.com/user-attachments/assets/c732b89f-8319-4a99-95bf-31d247110d75)

![微信截图_20240923174708](https://github.com/user-attachments/assets/7b7ea3bf-c8d3-461b-abe8-2d1943bb77df)
![微信截图_20240923174729](https://github.com/user-attachments/assets/23c1e7f7-94fd-4095-ba42-ca9d67c7ef5a)

spring-boot3

**Comment by 2014shijina2014** [comment]
spring-boot3

**Comment by jeecgos** [comment]
您是直接启动的demo项目还是集成到业务系统里？有没有具体的复现流程？

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
