### ISSUE TITLE
积木报表可以自定义类似FineReport的父子格吗？

### ISSUE THREAD

**Issue by team6Huang** [jeecgboot/JimuReport#2992]
##### 版本号：
1.8.1

##### 问题描述：
积木报表可以自定义类似FineReport的父子格吗？ 类似于纵向分组显示在上方

##### 错误日志&截图：
![1567997245184979](https://github.com/user-attachments/assets/c7421144-1383-4b91-a4cf-f7a8e8ba73c4)
类似这种效果

##### 重现步骤：
积木报表分组报表
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
支持

**Comment by team6Huang** [comment]
有文档说明吗，我看到的只有纵向合并单元格的，不能单独拿出来放到分组的上方
