### ISSUE TITLE
仪表盘日期筛选怎么配置？

### ISSUE THREAD

**Issue by shiwuye888** [jeecgboot/JimuReport#2993]
##### 版本号：
1.8.1-beta

##### 问题描述：
设置了查询参数，查询组件也选择了，但是为啥日期是两个。我定义了两个一个是startTime，一个是endTime，在交互里面的筛选选择日期如何配置？
如果我想通过近一周/近一月筛选怎么配置？

##### 错误日志&截图：
![0923-1](https://github.com/user-attachments/assets/d3a40213-21b3-424d-84cc-d2d2f04f8fea)
![0923-2](https://github.com/user-attachments/assets/702bf45c-3f27-4c3b-9e59-ed22093efe70)
![0923-3](https://github.com/user-attachments/assets/24e4e57d-7340-4e1f-be79-62452bae980a)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lsqGitHub716** [comment]
sq

**Comment by lsqGitHub716** [comment]
日期查询传递的是范围参数，会将设置的参数例如createTime，加上begin和end的后缀；

例如你可以通过配置sql，将开始和结束时间的变量同步加上begin和end的后缀：
![image](https://github.com/user-attachments/assets/61dc3d03-ee57-4d08-9102-96b7b00f08e6)

设置查询字段：
![image](https://github.com/user-attachments/assets/d977dc98-6a89-4b6d-84c6-99f8d3a4ff15)

查看效果：
![image](https://github.com/user-attachments/assets/013ce3cc-3335-4d8b-80da-a95c56564bf5)
