### ISSUE TITLE
JS增强-三级联动  自动补全

### ISSUE THREAD

**Issue by vincent-shi** [jeecgboot/JimuReport#2995]
##### 问题描述：
您好。想在官方文档 JS增强示例 - 实现三级联动  的基础上实现自动补全，请问有现成的方案么，或者有什么实现思路

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
自动补全指的是什么？
如果您说的自动补全指的是下拉框的输入检索，目前的积木报表暂时不支持下拉搜索控件。

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
