### ISSUE TITLE
javabean数据集无法设置图表

### ISSUE THREAD

**Issue by yanwencheng** [jeecgboot/JimuReport#2998]
##### 版本号：
1.8.0

##### 问题描述：
javabean数据集无法设置图表,绑定数据集选择javabean后无分类属性、值属性选择框

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
截图说明

**Comment by yanwencheng** [comment]
> 截图说明

![image](https://github.com/user-attachments/assets/8383b267-c391-4fe5-b084-86bc081e992b)

**Comment by yanwencheng** [comment]
> 截图说明

javaBean是否能使用图表？

**Comment by jeecgos** [comment]
javabean暂时不支持自定义属性，归集：#138
