### ISSUE TITLE
报表配置在菜单中后部分浏览器请求不能携带header请求头

### ISSUE THREAD

**Issue by hay313955795** [jeecgboot/JimuReport#2999]
##### 版本号：
1.5.6

##### 问题描述：
部分报表在 windows 环境下如果使用到系统参数 #{sysUserCode} 会报错不能获取报表信息

##### 错误日志&截图：
<img width="1531" alt="image" src="https://github.com/user-attachments/assets/f8dfd8cc-14f9-4f03-99c7-14465659c8ef">

##### 重现步骤：
<img width="663" alt="image" src="https://github.com/user-attachments/assets/a3e94d5a-4bfc-4413-a7ef-f52b3beb1437">
正常使用 能显示 
但是更换了用户或浏览器之后 请求头中不再携带 token 参数 导致需要权限校验的时候报错
<img width="971" alt="image" src="https://github.com/user-attachments/assets/56d0f1cd-2b2b-49ab-be81-a22342cb3fb2">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
提供重现步骤

**Comment by hay313955795** [comment]
配置也是按官网上的教程来操作的，事情发生的就很突然。我以为是个例。没想到我更换了浏览器也会出现这样的问题。不知道是什么情况导致的。麻烦大佬帮我看一下

**Comment by hao1175310925** [comment]
仪表盘能拿到token不，我是仪表盘可以，报表拿不到

**Comment by hoperunChen** [comment]
配置菜单时需要加上token参数：`?token=${token}`
![image](https://github.com/user-attachments/assets/0ca3171b-1bf0-4f01-b509-56aa76011909)
