### ISSUE TITLE
版本号：1.3.4-beta  循环表头分组 标题头只显示field字段

### ISSUE THREAD

**Issue by hexq** [jeecgboot/JimuReport#300]
版本号：1.3.4-beta
参考官方文档：http://report.jeecg.com/2119057
**问题描述：**
把省份(province)属性设置为横向分组之后，预览报表，没有成功渲染设置的field，都显示为province。截图见下面，急！！！
达不到官方文档显示的效果

**截图&代码：**
1，配置截图
![image](https://user-images.githubusercontent.com/1995173/120631854-ea4f3800-c49a-11eb-9518-3165df433de0.png)

2，预览效果：
![image](https://user-images.githubusercontent.com/1995173/120631906-f9ce8100-c49a-11eb-881e-2b3cc1f7df2d.png)

**JSON数据源：**
{"data":[
    {
        "month":"2021-05",
        "province":"河北",
        "count_type":1,
        "count_1":500,
        "device_type":"T10"
    },
    {
        "month":"2021-04",
        "province":"河北",
        "count_type":1,
        "count_1":0,
        "device_type":"T10"
    },
    {
        "month":"2021-01",
        "province":"河北",
        "count_type":1,
        "count_1":0,
        "device_type":"T10"
    },
    {
        "month":"2021-05",
        "province":"河北",
        "count_type":1,
        "count_1":200,
        "device_type":"T11"
    },
     {
        "month":"2021-04",
        "province":"河北",
        "count_type":1,
        "count_1":0,
        "device_type":"T11"
    },
     {
        "month":"2021-01",
        "province":"河北",
        "count_type":1,
        "count_1":400,
        "device_type":"T11"
    },
    {
        "month":"2021-05",
        "province":"山东",
        "count_type":1,
        "count_1":0,
        "device_type":"T10"
    },
    {
        "month":"2021-04",
        "province":"山东",
        "count_type":1,
        "count_1":500,
        "device_type":"T10"
    },
   {
        "month":"2021-01",
        "province":"山东",
        "count_type":1,
        "count_1":0,
        "device_type":"T10"
    },
    {
        "month":"2021-05",
        "province":"山东",
        "count_type":1,
        "count_1":420,
        "device_type":"T11"
    },
    {
        "month":"2021-04",
        "province":"山东",
        "count_type":1,
        "count_1":400,
        "device_type":"T11"
    },
    {
        "month":"2021-01",
        "province":"山东",
        "count_type":1,
        "count_1":0,
        "device_type":"T11"
    },
    {
        "month":"2021-05",
        "province":"湖南",
        "count_type":1,
        "count_1":0,
        "device_type":"T10"
    },
    {
        "month":"2021-04",
        "province":"湖南",
        "count_type":1,
        "count_1":200,
        "device_type":"T10"
    },
    {
        "month":"2021-01",
        "province":"湖南",
        "count_type":1,
        "count_1":1500,
        "device_type":"T10"
    },
    {
        "month":"2021-05",
        "province":"湖南",
        "count_type":1,
        "count_1":0,
        "device_type":"T11"
    },
    {
        "month":"2021-04",
        "province":"湖南",
        "count_type":1,
        "count_1":0,
        "device_type":"T11"
    },
    {
        "month":"2021-01",
        "province":"湖南",
        "count_type":1,
        "count_1":1500,
        "device_type":"T11"
    }
]}

_Originally posted by @hexq in https://github.com/zhangdaiscott/JimuReport/issues/279#issuecomment-853772318_

**Comment by zhangdaiscott** [comment]
降版本呢？还是所有版本都有问题

**Comment by hexq** [comment]
1.3.3-beta也测试过，相同的问题。不知道是否还要降

**Comment by hexq** [comment]
版本号：1.3.4-beta
参考官方文档：http://report.jeecg.com/2119057
问题描述：疑似 循环表头分组 的设计存在缺陷

截图&代码：
![image](https://user-images.githubusercontent.com/1995173/120783930-1c759e00-c55e-11eb-825c-8fa5279586ab.png)

**分析：**
1，接昨天的问题，今天找前端同学帮忙分析了下。针对上面链接的官方示例，发现在保存模板的时候，已经不存在groupRight函数，而是根据数据源的数据进行了固化（见上图的多个“销售额”关键字，已经搜不到groupRight关键字，但是可以搜到group关键字）
2，但实际情况是数据源的数据可能是动态变化的，这也是循环表头存在的意义。按1的处理，导致数据源的动态数据变化时，预览的数据是不完整的，可能也是无法渲染的。
3，个人感觉正确的处理方式应该是：模板存储GroupRight函数，当需要预览时，才根据这个函数，结合数据源去进行实际的渲染。也就是模板存储时，模板和数据要分离。
以上分析只是从现象上看如此，不一定正确，盼复。

**Comment by zhangdaiscott** [comment]
暂不支持功能归集 #138

**Comment by zhangdaiscott** [comment]
升级到版本1.3.63-beta , 要[配置私服](http://report.jeecg.com/2195924) ，看是否解决，无回复三天内关闭

文档：http://report.jeecg.com/2032023
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.63-beta</version>
</dependency>
```
