### ISSUE TITLE
docker部署拉镜像失败

### ISSUE THREAD

**Issue by lizhichao999** [jeecgboot/JimuReport#3000]
##### 版本号：
zuix最新版

##### 问题描述：

2024/09/25 09:06:11 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
2024/09/25 09:06:11 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
[+] Building 0.0s (0/0)  docker:default
2024/09/25 09:06:11 http2: server: error reading preface from client //./pipe/docker_engine: file has already been close[+] Building 0.0s (0/0)  docker:default
2024/09/25 09:06:11 http2: server: error reading preface from client //./pipe/docker_engine: file has already been close[+] Building 10.8s (4/4) FINISHED                                                                        docker:default
 => [jimureport internal] load build definition from Dockerfile                                                    0.0s
 => => transferring dockerfile: 427B                                                                               0.0s
 => ERROR [jimureport internal] load metadata for docker.io/anapsix/alpine-java:8_server-jre_unlimited            10.7s
 => [jimureport-mysql internal] load build definition from Dockerfile                                              0.0s
 => => transferring dockerfile: 260B                                                                               0.0s
 => ERROR [jimureport-mysql internal] load metadata for docker.io/library/mysql:8.0.19                            10.7s
------
 > [jimureport internal] load metadata for docker.io/anapsix/alpine-java:8_server-jre_unlimited:
------
------
 > [jimureport-mysql internal] load metadata for docker.io/library/mysql:8.0.19:
------
failed to solve: mysql:8.0.19: failed commit on ref "unknown-sha256:d0db132d50832bdfea5486d08a8fb0d3fb527be04ca2b16d10ec02e850930637": "unknown-sha256:d0db132d50832bdfea5486d08a8fb0d3fb527be04ca2b16d10ec02e850930637" failed size validation: 8165 != 7842: failed precondition
##### 重现步骤：
docker 部署

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
更新代码了
