### ISSUE TITLE
图片打印问题

### ISSUE THREAD

**Issue by xueyuenet** [jeecgboot/JimuReport#3002]
##### 版本号：
1.8.1

##### 问题描述：
数据报 预览的时候图片可以是正常缩放,打印的时候图片就不正常了
导出excel的时候图片能否缩小一点 不要充满整个单元格,现在充满单元格会遮挡单元格的边框了

##### 错误日志&截图：
![0001](https://github.com/user-attachments/assets/0855f205-0e4e-4a45-b6d7-bf27969823fd)
![0002](https://github.com/user-attachments/assets/1a76b6ba-8dbe-4299-b2be-d56aef40fbbc)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by jeecgos** [comment]
zy

**Comment by liaozhiyang** [comment]
![image](https://github.com/user-attachments/assets/e114cb20-de8a-47aa-8d31-d63ac8df0a74)

没复现出来，能在官网提供一个例子吗？

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
