### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by The-miss-you** [jeecgboot/JimuReport#3004]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by gaoxiaoniu** [comment]
在线文档有

**Comment by The-miss-you** [comment]
> 在线文档有

你倒是说在哪文档的哪个目录啊？

**Comment by jeecgos** [comment]
联动的配置可参考文档：
https://help.jeecg.com/jimureport/query/jsEnhance.html#1%E5%AE%9E%E7%8E%B0%E4%B8%89%E7%BA%A7%E8%81%94%E5%8A%A8

多选下拉框暂时不支持联动，归集：#138
