### ISSUE TITLE
url中传入时间明文开始时间和结束时间，在积木报表中的查询条件怎么获取呢？

### ISSUE THREAD

**Issue by liumingxiao1998** [jeecgboot/JimuReport#3007]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by liumingxiao1998** [comment]
> ##### 版本号：1.6.6
> ##### 问题描述：url中传入不放在token中的开始时间和结束时间，在积木报表中的查询条件怎么获取呢？
> ##### 错误日志&截图：
> ##### 重现步骤：

**Comment by liumingxiao1998** [comment]
> > ##### 版本号：1.6.6
> > ##### 问题描述：url中传入不放在token中的开始时间和结束时间，在积木报表中的查询条件怎么获取呢？
> > ##### 错误日志&截图：
> > ##### 重现步骤：

**Comment by jeecgos** [comment]
不能直接用报表参数配置嘛？https://help.jeecg.com/jimureport/query/reportParams.html

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
