### ISSUE TITLE
页面没有样式，作者又没有好的解决方案

### ISSUE THREAD

**Issue by Ldd1234567890** [jeecgboot/JimuReport#3008]
##### 版本号：

1.7.8
##### 问题描述：
使用iframe标签属性src内嵌积木报表，后台获取租户编号是在headers中获取的，由于src不能设置headers，我改用axios请求回来的data直接用vue指令v-html

##### 错误日志&截图：

![1727407665593](https://github.com/user-attachments/assets/51d80563-8b48-4b1a-8efe-57d6020aebd4)
![1727407739750](https://github.com/user-attachments/assets/dfd3c84d-de69-48c7-b920-07b1000d716b)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
自己集成问题
