### ISSUE TITLE
报表实现问题 横纵动态切换多个模板

### ISSUE THREAD

**Issue by Caloer** [jeecgboot/JimuReport#3011]
##### 版本号：
v1.8.1

##### 问题描述：
报表好像不能实现一个设计里面包含两个模板

##### 错误日志&截图：

![image](https://github.com/user-attachments/assets/bc9791dc-71b6-4d5d-8902-bd31e7acf41b)

##### 重现步骤：

![企业微信截图_17275737497472](https://github.com/user-attachments/assets/ae19107c-4df5-41b0-8106-7073eb90c6c9)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Caloer** [comment]
这种能否实现

**Comment by zhangdaiscott** [comment]
no
