### ISSUE TITLE
如何将 JimuReport 集成到 JeecgBoot

### ISSUE THREAD

**Issue by robinfeng** [jeecgboot/JimuReport#3012]
##### 版本号：
jeecgboot-vue3@3.7.1 dev
jimureport 20240929 下载 zip

##### 问题描述：
在 Jeecgboog 菜单, 点击 “低代码开发 > 积木报表设计” 菜单, 弹出窗口一直显示“正在加载...”

##### 错误日志&截图：
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/fbaac77a-5233-4d0d-ba51-eb20e7dc5d77">
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/6bf43cf7-72c4-49d0-9fb8-27fb62cc0121">

##### 重现步骤：
参考此文档集成积木报表(https://help.jeecg.com/jimureport/quick.html)
1. 编辑 C:\Code\JeecgBoot-master\jeecg-boot\jeecg-module-system\pom.xml, 添加以下段落
```
<dependency>
   <groupId>org.jeecgframework.jimureport</groupId>
   <artifactId>jimureport-spring-boot-starter</artifactId>
   <version>3.7.1</version>
</dependency>
```
2. 在 jeecg-boot 数据库中, 执行初始化 sql 脚本 C:\Code\JimuReport-master\db\jimureport.mysql5.7.create.sql1
3. 排除权限拦截, 不知道怎么做 N/A
4. 实现扩展接口, 不知道怎么做 N/A
5. 访问积木报表出现以下错误
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/fbaac77a-5233-4d0d-ba51-eb20e7dc5d77">
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/6bf43cf7-72c4-49d0-9fb8-27fb62cc0121">

**Comment by zhangdaiscott** [comment]
默认已经集成了积木报表

**Comment by robinfeng** [comment]
那么, 为何我点击“低代码开发 > 积木报表设计”, 弹出的界面一直显示"正在加载..."?

**Comment by zhangdaiscott** [comment]
F12看看浏览器报错没有

**Comment by robinfeng** [comment]
好像没有报错
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/a4abb556-2344-4c6c-ae3e-647b7074077c">

**Comment by zhangdaiscott** [comment]
浏览器版本？
内网还是外网

**Comment by robinfeng** [comment]
Chrome 浏览器, 内网.
<img width="704" alt="image" src="https://github.com/user-attachments/assets/2e402431-d8aa-40e3-82c0-7ada7195dddf">

**Comment by zhangdaiscott** [comment]
联网试试

**Comment by robinfeng** [comment]
可以正常访问外网, www.baidu.com, www.bing.com 都可以访问.

**Comment by zhangdaiscott** [comment]
那就不知道了

**Comment by zhangdaiscott** [comment]
你可以加 418799587 给你远程看看

**Comment by robinfeng** [comment]
谢谢, 已经解决. 在内网就可以访问.
