### ISSUE TITLE
打印留白问题：如果当某段文字内容的高度大于第一页剩余空间的高度， 这段文字本身的内容不足一页 就会 第一张留白 ，但是文字本身内容大于一页就会正常显示

### ISSUE THREAD

**Issue by diligentkong** [jeecgboot/JimuReport#3013]
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/50c27052-a259-4112-ad87-dd3596a1dcfd)

![image](https://github.com/user-attachments/assets/ebdf4e5f-7112-49ef-8e0d-b3096c0844a0)

##### 重现步骤： 如果当某段文字内容的高度大于第一页剩余空间的高度， 这段文字本身的内容不足一页 就会 第一张留白。对应的官网ID：1000563822085623808

如果当某段文字内容的高度大于第一页剩余空间的高度， 这段文字本身的内容又大于一页，正常显示，官网id ：974083384265756672

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by liaozhiyang** [comment]
![image](https://github.com/user-attachments/assets/28925e3f-132c-43f1-b912-a59a44d317a5)
这个问题，你可以通过在设计器页面增加换行来解决。

![image](https://github.com/user-attachments/assets/eb403a72-5e65-48ec-b2db-b9bfacf02765)
这个问题，已解决，下一版本发布。
