### ISSUE TITLE
仪表盘里domianURL参数写死，无法正常获取数据。（报表里没有这个问题）

### ISSUE THREAD

**Issue by hao1175310925** [jeecgboot/JimuReport#3014]
##### 错误日志&截图：
![QQ_1728353462733](https://github.com/user-attachments/assets/0c4ac64a-e162-4f1a-91da-6b295f6cfde4)
![QQ_1728353560271](https://github.com/user-attachments/assets/389d23cc-197a-47ce-ae42-e025a7f56636)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你是如何配置的？https？

**Comment by hao1175310925** [comment]
> 你是如何配置的？https？

是https，是yaml里的apiBasePath配置吗？

**Comment by zhangdaiscott** [comment]
https://jeecg.com/doc/qa
40
