### ISSUE TITLE
仪表盘报表界面显示差异 问题

### ISSUE THREAD

**Issue by gaokaoli** [jeecgboot/JimuReport#3015]
##### 版本号：
最新版本

##### 问题描述：

测试库是正常的
![image](https://github.com/user-attachments/assets/5edf47f8-76ec-41e1-a3f5-f78d566a7cb1)

正式库 https 带了域名
就变成这样了

![image](https://github.com/user-attachments/assets/2740d6ee-d08d-4591-900c-940b3ef607e1)

后续使用其他浏览器，发现显示不全
![image](https://github.com/user-attachments/assets/9476201c-a60c-4081-a09c-82c6bc311eb1)

不懂是什么问题所在

而且新增的时候 是有数据的，而且可以添加成功

![image](https://github.com/user-attachments/assets/5a8ae5a7-b007-4002-8063-6fac5d613748)

就是左边一侧丢失，导致无法找到添加的那一栏数据

##### 重现步骤：

数据库也是正常的

![image](https://github.com/user-attachments/assets/3fcfccb0-29de-4996-b287-07ae146d9f77)

测试库和正式库用的都是一样的

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by gaokaoli** [comment]
已解决！

**Comment by gaokaoli** [comment]
很神奇，等了好一会 自动好了！实在不知啥情况 自动恢复了！
up主有空看看是不是bug问题 还是缓存问题

**Comment by zhangdaiscott** [comment]
你可以观察下，知道具体原因再发新issue
