### ISSUE TITLE
maven执行package报错

### ISSUE THREAD

**Issue by JasonZhangNICE** [jeecgboot/JimuReport#3017]
##### 问题描述：
按照文档https://help.jeecg.com/jimureport/docker.html 执行docker部署时报错

##### 错误日志&截图：
[mvn error.txt](https://github.com/user-attachments/files/17293918/mvn.error.txt)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
可以忽略test

**Comment by zhangdaiscott** [comment]
应该是你环境问题，我这边package没报错，不是单元测试不通过的事
