### ISSUE TITLE
统计函数没有返回值

### ISSUE THREAD

**Issue by dxwmls** [jeecgboot/JimuReport#3018]
##### 版本号：
1.81

##### 问题描述：
统计函数没有结果。数据集字段都正常显示有数据，但用DBAVERAGE()这函数的时候没有返回值 

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
图文截图说明

**Comment by jeecgos** [comment]
未复现，请提供复现步骤或在官网制作示例
![QQ_1728715758770](https://github.com/user-attachments/assets/54a11dc2-e159-4f2a-81e9-89812c19effd)
![QQ_1728715771907](https://github.com/user-attachments/assets/5aa39c1e-b039-4e6f-bea3-4560a5c86d8b)

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
