### ISSUE TITLE
如何用标签包裹数据集内容，使html代码在页面渲染

### ISSUE THREAD

**Issue by Voldemoooooo** [jeecgboot/JimuReport#3019]
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/41d05223-7448-4e11-ac01-d3bf683a511b)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Voldemoooooo** [comment]
数据库保存为图片在线地址，需求是用img包裹在页面 能预览图片

**Comment by zhangdaiscott** [comment]
没明白

**Comment by Voldemoooooo** [comment]
![image](https://github.com/user-attachments/assets/0e379cf6-b393-4919-a81d-2898532cb614)
想在报表预览页面将这个图片在线地址显示为图片

**Comment by jeecgos** [comment]
![QQ_1728716003677](https://github.com/user-attachments/assets/12f87a4b-8df0-4551-ae4a-8eeb1a15aa7d)
将单元格格式设置成图片。
