### ISSUE TITLE
API数据集解析报错

### ISSUE THREAD

**Issue by hzc1099339637** [jeecgboot/JimuReport#3020]
##### 版本号：
1.7.4和1.7.8都试了

##### 问题描述：
spring-boot版本2.7.8，集成积木报表，启动成功。
在配置API数据集，点击Api解析时，页面没有反应，后台报错，错误截图如下。

##### 错误日志&截图：
![ee95d70b-547e-4609-b398-7af8c9bababa](https://github.com/user-attachments/assets/06111530-53d3-4582-af5b-9aea5b3fa3c5)

##### 重现步骤：
![8efbd60d-6d29-47e9-aa60-2b823ffcd9cf](https://github.com/user-attachments/assets/80b93da1-ecba-475f-b5b6-3ceba9eccbae)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/user-attachments/assets/4f495226-3daf-49b8-b1bb-d21fd6578be9)

用免anz安装版本试试

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
