### ISSUE TITLE
查询报500

### ISSUE THREAD

**Issue by mayiB** [jeecgboot/JimuReport#3021]
##### 版本号：
1.5.6

##### 问题描述：
根据日期查询数据报错500，sql测试是没有问题的，切换短一点的日期也没有问题。但是根据报错的查询条件数据量也才290条。

##### 错误日志&截图：
![微信截图_20241010102159](https://github.com/user-attachments/assets/85d06d7c-0141-423c-8b4f-26d5f599b367)

##### 重现步骤：
选择日期，点击查询

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
1. 升级到最新版本，看看还有没有问题。
2. 如果最新版也有这个问题，麻烦贴一下错误日志，或者针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
