### ISSUE TITLE
缩放打印报错

### ISSUE THREAD

**Issue by xueyuenet** [jeecgboot/JimuReport#3022]
##### 问题描述：
1在官网测试的缩放打印报错（）
2列太多无法往右滚动

1003471094864498688

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by xueyuenet** [comment]
![quark_KGVqHYLEes](https://github.com/user-attachments/assets/af8966fa-833b-47c3-897d-9dc0e72177e5)

**Comment by jeecgos** [comment]
zy

**Comment by liaozhiyang** [comment]
你可把清晰度调整为1，就没报错了。数据太多时，调高清晰度会导致内存不足，你调整到10，相当于把canvas放大了10倍去打印。

![image](https://github.com/user-attachments/assets/f078282c-91d3-417e-b983-2c9c0d1fa4d8)

设置为1后的效果：

![image](https://github.com/user-attachments/assets/5b37c94b-fefc-49bb-b0dd-be8f0e89487d)


最终效果：
（
   1.左侧有空隙，需删除设计遗留的痕迹【可删错说明到最后的列】，固定打印头在这个场景没用可删除
   2.6-18行也有设计遗留的痕迹可删除
  ）

![image](https://github.com/user-attachments/assets/32c693fe-412b-4498-8615-e5bbf140b1fa)

**Comment by liaozhiyang** [comment]
列太多移动可通过横向滚动条滚动

![image](https://github.com/user-attachments/assets/bf9c95b7-ce1e-4d6c-b6f4-d3169d8e4473)
