### ISSUE TITLE
文本框数据和数据库查询出的数据无法保持一致

### ISSUE THREAD

**Issue by 15891749436** [jeecgboot/JimuReport#3024]
##### 错误日志&截图：
![微信图片_20241010180839](https://github.com/user-attachments/assets/f4c98c76-7ac2-49e2-8227-611a1987082e)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 15891749436** [comment]
文本框数据和数据库查询出的数据无法保持一致

**Comment by jeecgos** [comment]
cr

**Comment by jeecgos** [comment]
集合的查询并编辑功能将在下个版本发布。
设置方式参考：https://help.jeecg.com/jimureport/submit/queryEdit.html#%E9%9B%86%E5%90%88%E6%95%B0%E6%8D%AE%E6%9F%A5%E8%AF%A2%E5%B9%B6%E7%BC%96%E8%BE%91
