### ISSUE TITLE
积木报表界面混乱

### ISSUE THREAD

**Issue by gaokaoli** [jeecgboot/JimuReport#3025]
##### 版本号：

最新版本号1.8.1

##### 问题描述：

引入积木报表之后界面出错混乱
![image](https://github.com/user-attachments/assets/682ab8c5-9520-4ce7-ae4e-75c7d175dc37)

##### 错误日志&截图：

前端浏览器报错如下：
![image](https://github.com/user-attachments/assets/c2a24d7c-802d-4658-a47c-7d29fc86c7e9)

后端报错：

com.alibaba.fastjson.JSONException: write javaBean error, fastjson version 1.2.73, class org.springframework.beans.factory.support.DefaultListableBeanFactory, fieldName : $$beanFactory, MBeanServerInterceptors are disabled.
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:539)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:149)

Caused by: java.lang.UnsupportedOperationException: MBeanServerInterceptors are disabled.
	at com.sun.jmx.mbeanserver.JmxMBeanServer.getMBeanInstantiator(JmxMBeanServer.java:278)

![image](https://github.com/user-attachments/assets/01cf0353-2327-4043-9465-71135b539ba1)

##### 重现步骤：

springboot + Avue项目
引入1.8.1积木报表 以及实现 JimuReportTokenServiceImpl，之后前端引入相关路径，打开就是乱码

以及引入http的鉴权
![image](https://github.com/user-attachments/assets/670784a2-e5ac-4635-a3d8-bfd924e600c3)

最后出错

![image](https://github.com/user-attachments/assets/64931439-c7e2-4563-a597-1c2f4b6fbc56)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by hoperunChen** [comment]
fastjson升级到1.2.83试试

**Comment by gaokaoli** [comment]
引入之后

后端不报错了，但是前端浏览器还是会出现这个问题

![image](https://github.com/user-attachments/assets/82794937-4304-4522-a801-f0fb0ee8d779)

![image](https://github.com/user-attachments/assets/2c0a6e4a-dde3-4169-9f13-d5aa17ff5634)
