### ISSUE TITLE
若依分离整合积木仪表盘报错

### ISSUE THREAD

**Issue by gpuer** [jeecgboot/JimuReport#3026]
##### 版本号：
Spring Boot Version: 2.5.15
mybatis plus: 3.5.1

##### 问题描述：
JimuDragCategoryDao找不到

##### 错误日志&截图：

***************************
APPLICATION FAILED TO START
***************************

Description:

Field jimuDragCategoryDao in org.jeecg.modules.drag.service.a.a required a bean of type 'org.jeecg.modules.drag.dao.JimuDragCategoryDao' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'org.jeecg.modules.drag.dao.JimuDragCategoryDao' in your configuration.

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
配置minidao扫描路径

https://help.jeecg.com/jimureport/projectJoin/ruoyiDrag.html
8

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
