### ISSUE TITLE
仪表盘报表的静态资源加载错误

### ISSUE THREAD

**Issue by gaokaoli** [jeecgboot/JimuReport#3029]
##### 版本号：

最新版本

##### 问题描述：

目前积木报表是可以正常查看，配置了静态资源的扫码！

# 积木报表配置
jeecg:
  jmreport:
    customPrePath: /api/blade-equipment
    saas-mode: tenant

但是积木仪表盘还是显示有问题

![image](https://github.com/user-attachments/assets/f22994d3-e6d8-480d-ab89-7ab895399368)

发现积木报表能成功是因为戴上了  /api/blade-equipment，而维度仪表盘没成功，是因为请求的时候就没带上这个
但是我的前端链接都带了，后端没带，怀疑是 静态资源配置没扫上，请问这个仪表盘需要带上什么呢

![image](https://github.com/user-attachments/assets/75349208-a41d-4ac9-9fbc-b1ea86e16784)

如果访问：
http://127.0.0.1:1888/drag/list/core/api/api.js?v=1726050881.10，就出错

![image](https://github.com/user-attachments/assets/fc869f72-9eca-4cda-b6d6-a5d2b3bdb77d)

手动访问 http://127.0.0.1:1888/api/blade-equipment/drag/list/core/api/api.js?v=1726050881.10
就出现如下情况：
![image](https://github.com/user-attachments/assets/1d1d83ba-e739-4187-bfcd-0b994b1c0b90)

请问这是什么原因呢

感觉是也要配置一套静态资源的扫码

但是这样好像不是很对

![image](https://github.com/user-attachments/assets/078743bf-6770-4c04-b5d3-d4b9e7dabd13)

目前发现静态资源的请求都没有补充前缀，后端的请求倒是有的
![image](https://github.com/user-attachments/assets/f860724e-9160-456d-9c1a-1bd8f6e781ba)

##### 重现步骤：

该issues的后续：https://github.com/jeecgboot/JimuReport/issues/3023

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by bikot1205** [comment]
是不是没适配【customPrePath】这个功能啊。报表设计器是好用的，现在发现仪表盘设计器有问题。。

**Comment by zhangdaiscott** [comment]
更新版本
https://blog.csdn.net/zhangdaiscott/article/details/143369569
