### ISSUE TITLE
数据源链接测试报错

### ISSUE THREAD

**Issue by feilx2224** [jeecgboot/JimuReport#3030]
##### 问题描述：
链接测试数据源提示：数据源安全模式下，禁止数据源链接测试

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/9bc11907-185b-40d5-a628-43f21f49bafd)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zxwl666** [comment]
https://help.jeecg.com/java/publish/firewall.html

这文档？

**Comment by jeecgos** [comment]
> https://help.jeecg.com/java/publish/firewall.html
> 
> 这文档？

@feilx2224 参考文档：https://help.jeecg.com/java/publish/firewall.html
