### ISSUE TITLE
积木报表打印会多出一页空白页

### ISSUE THREAD

**Issue by wangshimincode** [jeecgboot/JimuReport#3031]
##### 版本号：
积木报表：1.8.1

##### 问题描述：
打印时会多出一页空白页

##### 错误日志&截图：
![63722d128350b9a40c303d656305b79d](https://github.com/user-attachments/assets/7eca86a9-bb16-46dc-896b-cd9bb7e8338b)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
什么浏览器？
