### ISSUE TITLE
自定义函数例子没有作用

### ISSUE THREAD

**Issue by rwyydxy** [jeecgboot/JimuReport#3032]
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/56604851-9fa5-4606-97e6-d469c5e141bf)
![image](https://github.com/user-attachments/assets/8a60825f-aa74-427c-b61b-d97d0a0c57d5)
![image](https://github.com/user-attachments/assets/57c8fd59-aee8-40af-b34d-0eaeb15f83ac)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
需要加上这两句话，文档已修改
```
  instance.addFunction(fun.getName().toUpperCase(),fun);
  instance.addFunction(fun.getName().toLowerCase(),fun);
```

**Comment by rwyydxy** [comment]
可以了，起作用了，感谢
