### ISSUE TITLE
积木报表页面数据源维护接口明文显示数据库密码问题

### ISSUE THREAD

**Issue by bawuab** [jeecgboot/JimuReport#3033]
##### 问题描述：积木报表页面数据源维护接口明文显示数据库密码问题
这个能否隐藏掉明文密码，上线安全配置文档达不到我们的需求，如果有人把配置文件模式为dev就可以看见明文传输的密码了

##### 错误日志&截图：
![1728977446304](https://github.com/user-attachments/assets/cc8975f5-47e5-4a6b-b9ef-75b6f02c4ced)

##### 重现步骤：
如问题描述

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by bawuab** [comment]
这个问题什么时候能解决啊

**Comment by zhangdaiscott** [comment]
升级最新版看看

**Comment by bawuab** [comment]
> 升级最新版看看
这个地方还是这样
![image](https://github.com/user-attachments/assets/8d7af21f-e1c5-4033-8d12-a8f181f02bb9)
