### ISSUE TITLE
docker本机模式，怎么连接其他服务器上面的数据库配置数据源

### ISSUE THREAD

**Issue by feilx2224** [jeecgboot/JimuReport#3034]
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/4d08519f-f959-4864-a9c0-5a49314bfaae)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
链接其他服务器需要配置其他服务器的外网IP

**Comment by feilx2224** [comment]
> 链接其他服务器需要配置其他服务器的外网IP

在配置文件里面吗
