### ISSUE TITLE
加上token鉴权后admin角色下积木仪表盘数据源和数据集无法修改删除

### ISSUE THREAD

**Issue by 2508207487** [jeecgboot/JimuReport#3035]
##### 问题描述：
项目单独部署，自带登录功能已去除，加上token鉴权后积木仪表盘的数据源和数据集无法修改删除，登录用户是admin，角色部分没有动默认也是admin，积木报表功能正常

##### 错误日志&截图：
![图片](https://github.com/user-attachments/assets/2a4c8dc7-d896-470d-9cd6-be1ab4403502)
![图片](https://github.com/user-attachments/assets/c1284190-a803-4f9c-a547-6afb245ff1e9)
![图片](https://github.com/user-attachments/assets/dc5c57ba-8df9-4fcf-a07f-7016eaa1070f)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 2508207487** [comment]
redis由于无法指定连接重新配置过，maven没有动，redisConfig重新配置的ruoyi-vue的序列化方式
@Configuration
public class RedisConfig {

    @Value("${spring.redis.host}")
    private String host;

    @Value("${spring.redis.port}")
    private int port;

    @Value("${spring.redis.password}")
    private String password;

    @Value("${spring.redis.database}")
    private int database;

    @Bean
    JedisConnectionFactory jedisConnectionFactory() {
        RedisStandaloneConfiguration config = new RedisStandaloneConfiguration();
        config.setHostName(host);
        config.setPort(port);
        config.setPassword(password);
        config.setDatabase(database);
        return new JedisConnectionFactory(config);
    }

    @Bean
    public RedisTemplate<String, Object> redisTemplate() {
        RedisTemplate<String, Object> template = new RedisTemplate<>();
        template.setConnectionFactory(jedisConnectionFactory());

        FastJson2JsonRedisSerializer serializer = new FastJson2JsonRedisSerializer(Object.class);

        // 使用StringRedisSerializer来序列化和反序列化redis的key值
        template.setKeySerializer(new StringRedisSerializer());
        template.setValueSerializer(serializer);

        // Hash的key也采用StringRedisSerializer的序列化方式
        template.setHashKeySerializer(new StringRedisSerializer());
        template.setHashValueSerializer(serializer);

        template.afterPropertiesSet();
        return template;
    }
}

**Comment by jeecgDeveloper** [comment]
仪表盘加载时打断点看一下，有没有进入到配置的这个getRoles方法

**Comment by 2508207487** [comment]
> 仪表盘加载时打断点看一下，有没有进入到配置的这个getRoles方法

![图片](https://github.com/user-attachments/assets/a3c7e800-088f-459d-8fd3-a9d6ca55c6ea)
进来了

**Comment by jeecgDeveloper** [comment]
测试没问题。那你看看进入设计页面时，查询的接口，有返回用户角色和用户信息吗？然后看看新增的数据源的用户信息是否匹配

**Comment by 2508207487** [comment]
> 测试没问题。那你看看进入设计页面时，查询的接口，有返回用户角色和用户信息吗？然后看看新增的数据源的用户信息是否匹配

应该是添加数据时没有加上创建人导致的，响应回来的数据中测试那个是我创建的，没有创建人，下面的是之前系统的有创建人
![图片](https://github.com/user-attachments/assets/7510670c-6aa5-4c90-b62d-5d4ed9eb3813)

数据库中加上创建人后就有修改删除了
![图片](https://github.com/user-attachments/assets/8c88eeae-9b8b-4652-b360-7ee415dec1f4)
![图片](https://github.com/user-attachments/assets/caa2d636-f7dc-4768-b502-b83e5d3fa4a9)

**Comment by 2508207487** [comment]
数据集也是一样的问题
![图片](https://github.com/user-attachments/assets/f191e5f1-e39a-4fc7-8a7e-b2b046153885)
![图片](https://github.com/user-attachments/assets/3bd19855-9751-4494-ac93-1d3ad1829861)

**Comment by jeecgDeveloper** [comment]
升级到最新版试试
 <dependency>
   <groupId>org.jeecgframework.jimureport</groupId>
   <artifactId>jimureport-dashboard-spring-boot-starter</artifactId>
   <version>1.9.0</version>
 </dependency>

**Comment by jeecgDeveloper** [comment]
升级到新版试试
```
<dependency>
   <groupId>org.jeecgframework.jimureport</groupId>
   <artifactId>jimureport-dashboard-spring-boot-starter</artifactId>
   <version>1.9.0</version>
 </dependency>
```

**Comment by 2508207487** [comment]
> 升级到新版试试
> 
> ```
> <dependency>
>    <groupId>org.jeecgframework.jimureport</groupId>
>    <artifactId>jimureport-dashboard-spring-boot-starter</artifactId>
>    <version>1.9.0</version>
>  </dependency>
> ```

![图片](https://github.com/user-attachments/assets/e785feed-bc9b-4140-8fbe-e48f4043983e)

**Comment by zhangdaiscott** [comment]
去执行升级sql

**Comment by 2508207487** [comment]
![图片](https://github.com/user-attachments/assets/7d10a7dd-7670-44c2-922b-975dd2f72257)
这个角色校验没有用吗，我这传了个字符串“超级管理员”也没有提示权限不足啥的

**Comment by zhangdaiscott** [comment]
传递英文code，按照我们的规则，不是你自己想什么事什么

**Comment by 2508207487** [comment]
> 传递英文code，按照我们的规则，不是你自己想什么事什么

我的意思是，角色校验这不是校验的admin吗，我传的“超级管理员”的字符串，但是他没有提示权限不足

**Comment by zhangdaiscott** [comment]
目前仪表盘的功能还没有加角色控制

**Comment by jeecgos** [comment]
> 配置文件切换到发布模式prod后获取不到token

您截图里这个`tokenService`是你自己的token实现类吗？您先检查下为啥他会返回null？
![QQ_1730460815749](https://github.com/user-attachments/assets/029e144e-ce63-4298-88d4-a2fe46341be3)

**Comment by 2508207487** [comment]
> > 配置文件切换到发布模式prod后获取不到token
> 
> 您截图里这个`tokenService`是你自己的token实现类吗？您先检查下为啥他会返回null？ ![QQ_1730460815749](https://private-user-images.githubusercontent.com/162332873/382268413-029e144e-ce63-4298-88d4-a2fe46341be3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MDkzNjgsIm5iZiI6MTczMDUwOTA2OCwicGF0aCI6Ii8xNjIzMzI4NzMvMzgyMjY4NDEzLTAyOWUxNDRlLWNlNjMtNDI5OC04OGQ0LWEyZmU0NjM0MWJlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQwMDU3NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDFkMmYxYWRkNmY3NjM5MTE3NWJkYjNiMmFhYjNiYWMwMzBjYzAyMTcwNWE4MGE4NmQ0MDAzNTJhMmY4MWVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0pgsHP8tPq8U9NIBSUDzc7deZOrUWtvLhzP_HLCYGR4)

进积木仪表盘时第一次能获取到，后面就获取不到了，应该是程序的bug，另外配置文件选dev开发模式的话功能正常

**Comment by jeecgDeveloper** [comment]
> > > 配置文件切换到发布模式prod后获取不到token
> > 
> > 
> > 您截图里这个`tokenService`是你自己的token实现类吗？您先检查下为啥他会返回null？ ![QQ_1730460815749](https://private-user-images.githubusercontent.com/162332873/382268413-029e144e-ce63-4298-88d4-a2fe46341be3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MDkzNjgsIm5iZiI6MTczMDUwOTA2OCwicGF0aCI6Ii8xNjIzMzI4NzMvMzgyMjY4NDEzLTAyOWUxNDRlLWNlNjMtNDI5OC04OGQ0LWEyZmU0NjM0MWJlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQwMDU3NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDFkMmYxYWRkNmY3NjM5MTE3NWJkYjNiMmFhYjNiYWMwMzBjYzAyMTcwNWE4MGE4NmQ0MDAzNTJhMmY4MWVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0pgsHP8tPq8U9NIBSUDzc7deZOrUWtvLhzP_HLCYGR4)
> 
> 进积木仪表盘时第一次能获取到，后面就获取不到了，应该是程序的bug，另外配置文件选dev开发模式的话功能正常

两种模式有什么区别呢？token实现类不一样吗？

**Comment by jeecgDeveloper** [comment]
长时间未回复，如扔有问题，请提交新issue
