### ISSUE TITLE
栈溢出问题

### ISSUE THREAD

**Issue by 1154315454** [jeecgboot/JimuReport#3036]
##### 版本号：
jimureport-spring-boot-starter：1.8.0
##### 问题描述：
页面中直接报错栈溢出

##### 错误日志&截图：
 
![9497bd1680e513c9aa30bbeab5a2c42b](https://github.com/user-attachments/assets/a2015f75-4402-43f6-afaf-04918a037623)

 
<img width="655" alt="6e71d79740199cf9b37010b202a31d6" src="https://github.com/user-attachments/assets/b4e10c36-fa5a-4238-871a-bd0af633e45c">

##### 重现步骤：
现在无法重现，页面配置了好多个页面

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
看报错可能是某个报表的表达式参数设置的不对导致的，你是什么情况报错？请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
