### ISSUE TITLE
 dbType mysql, , druid-version 1.2.22, syntax error

### ISSUE THREAD

**Issue by gaokaoli** [jeecgboot/JimuReport#3038]
##### 版本号：

最新版本

##### 问题描述：

添加了依赖包之后，不知道是不是不兼容 自身网站代码，大片功能出现问题
（后续发现是仪表盘的报表）

比如如下提示：

![image](https://github.com/user-attachments/assets/69701aa8-5974-4126-ae27-e47dc15a7030)

根据错误提示，我的mapper文件也没有所说的那个错误！

![image](https://github.com/user-attachments/assets/ccfdb7fe-74c3-48f4-a003-3b3345df818a)

##### 错误日志&截图：

大部分功能出现错误，不确定是否你这边的版本太高，导致不兼容。类似如下Bug
![image](https://github.com/user-attachments/assets/177f43be-2421-48df-8f35-c5aa235a1caf)

实际是这样的
![image](https://github.com/user-attachments/assets/103e6aab-4ff0-4129-9864-3cf4c3679c8e)

把相关的pom文件以及代码去除之后，正常是可以查询的。为啥不兼容呢~
![image](https://github.com/user-attachments/assets/48e0aa4c-0710-44ec-b3f1-832eb15a9687)

##### 重现步骤：

本身我的代码是排除掉的

![image](https://github.com/user-attachments/assets/e84c04c4-e88a-45a6-b4a1-128b5869b449)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
可以提供一个可以复现问题的示例工程吗，我们本地没有办法复现这个问题。
@gaokaoli

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
