### ISSUE TITLE
疑似 循环表头分组 的设计和实现存在缺陷

### ISSUE THREAD

**Issue by hexq** [jeecgboot/JimuReport#304]
版本号：1.3.4-beta
参考官方文档：http://report.jeecg.com/2119057
问题描述：疑似 循环表头分组 的设计和实现存在缺陷

截图&代码：
![image](https://user-images.githubusercontent.com/1995173/120783930-1c759e00-c55e-11eb-825c-8fa5279586ab.png)

**分析：**
1，接昨天的问题，今天找前端同学帮忙分析了下。针对上面链接的官方示例，发现在保存模板的时候，已经不存在groupRight函数，而是根据数据源的数据进行了固化（见上图的多个“销售额”关键字，已经搜不到groupRight关键字，但是可以搜到group关键字）
2，但实际情况是数据源的数据可能是动态变化的，这也是循环表头存在的意义。按1的处理，导致数据源的动态数据变化时，预览的数据是不完整的，可能也是无法渲染的。
3，个人感觉正确的处理方式应该是：模板存储GroupRight函数，当需要预览时，才根据这个函数，结合数据源去进行实际的渲染。也就是模板存储时，模板和数据要分离。
以上分析只是从现象上看如此，不一定正确，盼复。

_Originally posted by @hexq in https://github.com/zhangdaiscott/JimuReport/issues/300#issuecomment-854562621_

**Comment by zhangdaiscott** [comment]
暂不支持功能归集 #138

**Comment by zhangdaiscott** [comment]
升级到版本1.3.63-beta , 要[配置私服](http://report.jeecg.com/2195924) ，看是否解决，无回复三天内关闭

```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.63-beta</version>
</dependency>
```
