### ISSUE TITLE
导出未登录报错

### ISSUE THREAD

**Issue by hughkon** [jeecgboot/JimuReport#3040]
##### 版本号：
                            1.81

##### 问题描述：
                              未登录时通过view或shareview访问，都会报错。

##### 错误日志&截图：

Excel无法打开文件“分版错误报表_1729129323332.x1sx”，因为文件格式或文件扩展名无效。请确定文件未损坏，并且文件扩展名与文件的格式匹配。
                             
![Snipaste_2024-10-17_09-42-55](https://github.com/user-attachments/assets/d2c3d531-917e-4ccb-9d7a-90cb367690dd)

**Comment by zhangdaiscott** [comment]
是分享的报表还是？

**Comment by hughkon** [comment]
分享的报表和预览的都不行，不登录的话都不行

**Comment by zhangdaiscott** [comment]
ws

**Comment by jeecgos** [comment]
已经修复了，待新版本发布
你可以手动改一下，将pdf和excel排除掉，`SpringSecurityConfig`
![image](https://github.com/user-attachments/assets/568275e9-bf2b-480e-91e2-9ff263596944)
```
// Security排除导出excel和pdf
 .antMatchers("/jmreport/exportPdfStream", "/jmreport/exportAllExcelStream")
```
