### ISSUE TITLE
oracle中文乱码

### ISSUE THREAD

**Issue by lianyucao** [jeecgboot/JimuReport#3041]
##### 版本号：
jimureport-v1.7.9 免安装板

##### 问题描述：
数据集使用的是oracle,查询数据后发现中文乱码,检查数据库发现数据库内容正常显示,同时查看文档未发现报表有设置字符编码的地方,经多次尝试无法将中文乱码更改为正常显示,并且无法确认问题所在

##### 错误日志&截图：
<img width="553" alt="微信图片_20241017102800" src="https://github.com/user-attachments/assets/780ef464-59a9-493d-b8c9-ba450d68054e">
<img width="474" alt="微信图片_202410171028001" src="https://github.com/user-attachments/assets/44eafa91-87fc-4ce9-806a-df9d748f639a">
<img width="525" alt="微信图片_202410171028002" src="https://github.com/user-attachments/assets/e3505151-3c4a-4171-899b-b5c3dbe9bba8">
<img width="606" alt="微信图片_202410171028003" src="https://github.com/user-attachments/assets/5c4650f7-89ca-417c-8a5d-43c8584afedb">
<img width="775" alt="微信图片_202410171028004" src="https://github.com/user-attachments/assets/34217a70-0caa-455c-81fe-fa3ab187bf4b">
<img width="712" alt="微信图片_202410171028005" src="https://github.com/user-attachments/assets/bfae83d2-476b-4855-94d2-4f5460646d7f">
<img width="1280" alt="微信图片_202410171028006" src="https://github.com/user-attachments/assets/60494d45-8576-47d7-8c73-7c274c18ba46">
<img width="449" alt="微信图片_202410171028007" src="https://github.com/user-attachments/assets/e697445b-93e3-40b6-bd03-90dad3f7f967">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
可能跟你的数据库和项目编码有关
