### ISSUE TITLE
（Bug）数据字典无法进行更新修改

### ISSUE THREAD

**Issue by gaokaoli** [jeecgboot/JimuReport#3042]
##### 版本号：

最新版本号

##### 问题描述：

**数据字典无法进行更新修改，会报错**

##### 错误日志&截图：

![image](https://github.com/user-attachments/assets/8fc3ee83-8db1-4fb3-9a2d-e70217e44a98)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
麻烦发一下完整的错误提示，以及后端的报错。

**Comment by gaokaoli** [comment]
"PreparedStatementCallback; SQL [UPDATE jimu_dict SET ID = ?, DICT_NAME = ?, DICT_CODE = ?, DESCRIPTION = ?, DEL_FLAG = ?, CREATE_BY = ?, CREATE_TIME = ?, UPDATE_BY = ?, UPDATE_TIME = ?, TYPE = ?, TENANT_ID = ? WHERE id = ?]; Data truncation: Out of range value for column 'type' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'type' at row 1"

截图如下：

![image](https://github.com/user-attachments/assets/d324f1ac-a3c0-4bcf-9e87-24a97ba17cd5)

后端截图如下：

![image](https://github.com/user-attachments/assets/8c3c1a7c-ecb0-4cf2-84bb-44aeb6139633)

**Comment by jeecgos** [comment]
ws

**Comment by jeecgos** [comment]
已优化，待新版本发布
