### ISSUE TITLE
分享报表导出excel或者pdf，打开后提示用户名或密码错误

### ISSUE THREAD

**Issue by yaocanke** [jeecgboot/JimuReport#3043]
##### 版本号：
v1.8

##### 问题描述：
分享报表导出excel或者pdf，打开后提示用户名或密码错误

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/b5eef120-4083-4697-b8a6-43584a5daf73)

**Comment by jeecgDeveloper** [comment]
111

**Comment by jeecgos** [comment]
ws

**Comment by jeecgos** [comment]
已经修复了，待新版本发布
你可以手动改一下，将pdf和excel排除掉，页面：`SpringSecurityConfig`
![image](https://github.com/user-attachments/assets/568275e9-bf2b-480e-91e2-9ff263596944)
```
// Security排除导出excel和pdf
 .antMatchers("/jmreport/exportPdfStream", "/jmreport/exportAllExcelStream")
```

**Comment by yaocanke** [comment]
> 已经修复了，待新版本发布 你可以手动改一下，将pdf和excel排除掉，页面：`SpringSecurityConfig` ![image](https://private-user-images.githubusercontent.com/162332873/378321875-568275e9-bf2b-480e-91e2-9ff263596944.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDI2MzEsIm5iZiI6MTcyOTUwMjMzMSwicGF0aCI6Ii8xNjIzMzI4NzMvMzc4MzIxODc1LTU2ODI3NWU5LWJmMmItNDgwZS05MWUyLTlmZjI2MzU5Njk0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwOTE4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzhiMjg1Mzc5MzE2MThjZjAxZjI0NWM2YzMyNmEyNjRmMmIyN2M1ZDFjZDQzYzZmZmExMTA0N2Y4OTllMzYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2yWkC2MRsL9gwBcWfv0l87ouO-QmixyPAn5eEFOGp_4)
> 
> ```
> // Security排除导出excel和pdf
>  .antMatchers("/jmreport/exportPdfStream", "/jmreport/exportAllExcelStream")
> ```

按照上述方法 已解决
