### ISSUE TITLE
TestController被占用问题

### ISSUE THREAD

**Issue by pinzhong** [jeecgboot/JimuReport#3045]
##### 版本号：
1.7.8及以上

##### 问题描述：
如果程序中已经写过TestController的RestController接口，启动失败，提示注入bean失败

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
那你换个名字

**Comment by jeecgos** [comment]
已修复，待新版本发布
