### ISSUE TITLE
为积木仪表盘添加数据集时的错误

### ISSUE THREAD

**Issue by robinfeng** [jeecgboot/JimuReport#3047]
##### 版本号：
Jeecg 3.7.1

##### 问题描述：
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/0d68dabc-31ef-4054-b2d5-586b272e82be)

##### 重现步骤：
1. 登录 JeecgBoot Pro
2. 访问 低代码开发 > 仪表盘设计器
3. 点击“新建仪表盘”, 输入名称, 点击确定
4. 在该仪表盘上, 点击设计
5. 点击“数据集”
6. 点击“新增数据集”
7. 输入自定义 API 源, 点击”API解析“
* 出现错误: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0. 详见截屏

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
sq

**Comment by robinfeng** [comment]
请问, "sq" 啥意思?

**Comment by jeecgDeveloper** [comment]
已修改，下版本发布

**Comment by liuling1314** [comment]
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0, 试用了 1.9.1 的版本，还是报错，最新版本还是没修复吗，api字段多的时候，列表字段要一个一个添加，还挺麻烦的，希望尽快 上线 @zhangdaiscott

**Comment by zhangdaiscott** [comment]
你是解析报错吗

**Comment by zhangdaiscott** [comment]
还是添加的时候报错

**Comment by zhangdaiscott** [comment]
得下个版本了，未合并

**Comment by a123456wlzhyy** [comment]
jeecgboot最新版本添加数据集api解析报IndexOutOfBoundsException: Index 0 out of bounds for length 0，jimureport-example项目就没问题，同样是1.9.1版本，jeecgboot要怎么修改才能好用？
