### ISSUE TITLE
积木新仪表盘数据源设置为API获取时，返回数据解析报错。IndexOutOfBoundsExceptions

### ISSUE THREAD

**Issue by shiwuye888** [jeecgboot/JimuReport#3048]
##### 版本号：
1.8.1-beta

##### 问题描述：
![image](https://github.com/user-attachments/assets/dddb4792-0e77-41c6-a39c-c04f9fae4927)
该方法查询的结果如下：
![image](https://github.com/user-attachments/assets/82018f2e-c404-42be-87bb-40bea670d0c8)

数据源配置为API时解析报错。如何解决？
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/2e600762-f8a8-4594-b859-17969809f3d2)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by shiwuye888** [comment]
很急很急，哪位大佬知道？

**Comment by jeecgos** [comment]
sq

**Comment by shiwuye888** [comment]
> sq
什么意思？

**Comment by zhangdaiscott** [comment]
试试这个版本，应该修复了
```
 <dependency>
   <groupId>org.jeecgframework.jimureport</groupId>
   <artifactId>jimureport-dashboard-spring-boot-starter</artifactId>
   <version>1.9.0</version>
 </dependency>

```

**Comment by shiwuye888** [comment]
> 试试这个版本，应该修复了
> 
> ```
>  <dependency>
>    <groupId>org.jeecgframework.jimureport</groupId>
>    <artifactId>jimureport-dashboard-spring-boot-starter</artifactId>
>    <version>1.9.0</version>
>  </dependency>
> ```
我下午试试

**Comment by sunjulei** [comment]
![image](https://github.com/user-attachments/assets/95cb16fd-2dd6-466a-a8cb-dfaf957596f5)
![image](https://github.com/user-attachments/assets/e8c6e651-edd4-49d6-a964-6ad4c199eceb)

<jimureport-spring-boot-starter.version>1.9.1</jimureport-spring-boot-starter.version>
我也碰到这个问题了，是master分支的
