### ISSUE TITLE
导出EXCE后图片被拉长

### ISSUE THREAD

**Issue by xueyuenet** [jeecgboot/JimuReport#3049]
##### 版本号：
1.8.1

##### 问题描述：
打印预览图片正常，导出EXCE后图片被拉长，导出excel的图片能否不要拉伸

##### 错误日志&截图：
![123](https://github.com/user-attachments/assets/df7183dc-ecd5-4565-a25e-00a2840d7f6e)
![456](https://github.com/user-attachments/assets/9e4c6dd9-badf-4c80-87f9-27f86c845242)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
ws
