### ISSUE TITLE
积木报表的数据显示与不显示

### ISSUE THREAD

**Issue by gaokaoli** [jeecgboot/JimuReport#3050]
##### 版本号：
最新版本

##### 问题描述：

积木报表的 如果是数字0，怎么让其不显示呢

![image](https://github.com/user-attachments/assets/78a0b4a9-b57c-4bf9-84fc-49d54fe12be4)

后续升级的时候可否增加一些过滤的，0就不显示的按钮框 

##### 重现步骤：

后续发现 直接在sql 中加入NULLIF 语句进行判定去解决了

但是有些是通过公式 将列相加的，相加的公式就无法进行规避，不显示0
![image](https://github.com/user-attachments/assets/4b4f4527-acdb-45d1-a723-2d3a0015b77e)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
暂不支持，归集：#138
