### ISSUE TITLE
多数据对比柱形图，在sql数据源中添加时间范围条件，进行sql解析报错

### ISSUE THREAD

**Issue by zimuxiuan** [jeecgboot/JimuReport#3051]
##### 版本号：
jimureport-spring-boot3-starter-fastjson2
1.8.1

##### 问题描述：

多数据对比柱形图，在sql数据源中添加时间范围条件，进行sql解析报错，并且图表无法展示数据。

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/a79cce30-d618-4060-974c-e79009e101fe)
![image](https://github.com/user-attachments/assets/06eca5f4-5e48-4638-ab7a-30a0e78a1526)
![image](https://github.com/user-attachments/assets/a70943a1-07a3-4935-9cb8-7359904d1ff7)
![image](https://github.com/user-attachments/assets/75d4df12-d492-42d1-af71-df243532dc85)

##### 重现步骤：
1.新建 “多数据对比柱形图”
2.添加SQL数据集
3.填写sql语句
4.点击sql解析

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zimuxiuan** [comment]
数据sql改为如下，也是同样的解析异常：
SELECT
	org.`NAME` org_name,
	pay.pay_type,
	SUM(pay.pay_amount) pay_amt
FROM
	pay_order_record pay
	INNER JOIN sys_org org on org.id=pay.org_id
WHERE
	pay.pay_status='1'
  AND pay.settle_time BETWEEN '${dateBegin}' AND '${dateEnd}'
  AND (org.ID = '#{sysOrgCode}' or org.PARENT_ID = '#{sysOrgCode}')
GROUP BY
	org.`NAME`, pay.pay_type

**Comment by jeecgos** [comment]
cr

**Comment by jeecgos** [comment]
按照您提供的步骤，未复现该问题。
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID；
如果不方便可以先分享下完整的报错堆栈日志，以及您jsqlParser的版本号。
![QQ_1730086954979](https://github.com/user-attachments/assets/6a3484c6-33ea-4b81-97be-d68b8cbc072c)
