### ISSUE TITLE
设置空值不计算后,分组小计的平均值仍然将空值算到计数中

### ISSUE THREAD

**Issue by codetylor** [jeecgboot/JimuReport#3052]
##### 问题描述：
红框内前两行为数据,第三行为分组小计的平均值,分组小计中聚合方式为平均值并且设置空值不计算, 但在分组小计计算出来的平均值仍然将空值算到计数范围内. 平均值应为59.5/1=59.5而不是目前表格里算的59.5/2=29.75

##### 错误日志&截图：
![屏幕截图 2024-10-22 175717](https://github.com/user-attachments/assets/c8c24b8a-a7d4-4e93-bc27-5965c21c00a9)

**Comment by jeecgos** [comment]
请补充版本号 @codetylor

**Comment by jeecgos** [comment]
ws

**Comment by codetylor** [comment]
版本号1.8.1

**Comment by jeecgos** [comment]
已修复，待新版本发布
