### ISSUE TITLE
支持cirrodata行云数据库

### ISSUE THREAD

**Issue by lixufang-git** [jeecgboot/JimuReport#3053]
##### 版本号：
1.8

##### 问题描述：
支持cirrodata行云数据库

##### 错误日志&截图：

支持cirrodata行云数据库
##### 重现步骤：
支持cirrodata行云数据库

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
暂时不支持，归集：#138。
后续支持后会告诉您。
