### ISSUE TITLE
大屏报表无显示

### ISSUE THREAD

**Issue by hzlskj** [jeecgboot/JimuReport#3054]
##### 版本号：
![934b3d596e8fe49debdefe02e0a00d4](https://github.com/user-attachments/assets/67f87bee-c32a-491a-9e3f-fd96c5779430)

##### 问题描述：
![image](https://github.com/user-attachments/assets/69f366d7-8fbf-4ab2-9c5a-b07a086dc357)

#### 友情提示（为了提高issue处理效率）：有网络断开后就此提示

**Comment by jeecgos** [comment]
请补充版本号和复现步骤。

**Comment by jeecgos** [comment]
出现这个错误可以确认下你的数据源的连接信息对不对。
