### ISSUE TITLE
多选用in时，选多个项目的时候，查不出数据

### ISSUE THREAD

**Issue by zwjsoft** [jeecgboot/JimuReport#3055]
##### 版本号：
1.8.1

##### 问题描述：
多选用in时，选多个项目的时候，查不出数据，查询数据库执行的sql，发现在多选的字符串上面人为的增加了''。

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/9968036e-6ebd-4db2-8194-37bdbf2c4087)

![image](https://github.com/user-attachments/assets/17490cb2-048d-4ca2-947a-a2e771a83f26)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
参考：https://help.jeecg.com/jimureport/query/function.html
