### ISSUE TITLE
 导出文件失败：Error: timeout of 600000ms exceeded但是配置的超时时间远超600000ms 我使用的是商业授权版麻烦看一下问题

### ISSUE THREAD

**Issue by AXXZSTHL** [jeecgboot/JimuReport#3056]
##### 版本号：
1.8.0

##### 问题描述：
导出文件失败：Error: timeout of 600000ms exceeded但是配置的超时时间远超600000ms

##### 错误日志&截图：
<img width="1396" alt="image" src="https://github.com/user-attachments/assets/1dccf639-7822-475b-9fc9-18c0b42a344e">

![1811729669736_ pic_hd](https://github.com/user-attachments/assets/588aade8-b6bc-4292-86d6-13224d9bb33f)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
cr

**Comment by jeecgos** [comment]
已修复，待新版本发布。

**Comment by AXXZSTHL** [comment]
好的，感谢，麻烦问一下，一般jmbi-datax的包会什么时候更新，我每次只能通过改版本号刷新的方式测有没有发布新版本，有没有一个和开源版一样获取更新信息消息的地方
