### ISSUE TITLE
,单元格边框加粗，导出DPF，没有加粗效果

### ISSUE THREAD

**Issue by wkinged** [jeecgboot/JimuReport#3057]
##### 版本号：
1.6.6，1.8.1

##### 问题描述：
,单元格边框加粗，导出DPF，没有加粗效果

##### 重现步骤：
1.设置单元格边框，加粗
![image](https://github.com/user-attachments/assets/9c010c87-7b01-4230-9212-02826ccbc7b3)

2.导出PDF
![image](https://github.com/user-attachments/assets/3012da80-05a3-44e2-b7bc-c90a1e3e3069)
![image](https://github.com/user-attachments/assets/0c506c07-9260-4bb4-b48f-9dd81d0db74e)

3.导出PDF图像
![image](https://github.com/user-attachments/assets/15a65ee2-3218-4b3b-bbc7-513064a6b750)
![image](https://github.com/user-attachments/assets/29e739f7-b187-45ec-8905-504626c12192)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
暂不支持，归集：#138
