### ISSUE TITLE
积木报表存在严重漏洞

### ISSUE THREAD

**Issue by cai1449074828** [jeecgboot/JimuReport#3059]
https://stack.chaitin.com/vuldb/index?page=1&search=%25E7%25A7%25AF%25E6%259C%25A8%25E6%258A%25A5%25E8%25A1%25A8
我想问下这里的漏洞是否都已经修复好了，特别是严重的漏洞：[积木报表 /jeecg-boot/jmreport/save 远程代码执行漏洞](https://stack.chaitin.com/vuldb/detail/aeede9be-f91b-4ef4-899e-9d7d5263c624)

![image](https://github.com/user-attachments/assets/7f93f94f-6b67-45bb-bda8-033b0c053fe2)

**Comment by zhangdaiscott** [comment]
你发的都是那年的了，升级到最新版即可
