### ISSUE TITLE
仪表盘设计器集成时【customPrePath】不好用

### ISSUE THREAD

**Issue by bikot1205** [jeecgboot/JimuReport#3060]
##### 版本号：
1.8.1-beta

##### 问题描述：
用ruoyi-vue集成仪表盘设计器的时候，出现customPrePath配置不好用的问题。导致js无法找到。

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/949e9d6f-2b3e-4bc1-9975-da19abd7988c)

![image](https://github.com/user-attachments/assets/5bec3095-3d0e-42d1-8e83-7f336b761db6)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
sq

**Comment by jeecgDeveloper** [comment]
已修改，下版本发布
