### ISSUE TITLE
sql数据集使用In语法传参问题

### ISSUE THREAD

**Issue by m-qing-m** [jeecgboot/JimuReport#3062]
##### 版本号：
1.5.8 

##### 问题描述：
  首先我想实现的业务场景就是用户自己选择相应的数据来展示数据
  然后我写一个sql语句中有一句id in (${ids}) 对应用户选中的数据id，后续我在界面传值例如 ?ids=1,2 但是结果是没有查询到数据 ，现象 
  就是如果我写的是?ids=1可以查出?ids=1,2 不行。
##### 错误日志&截图：
![72e64cb23ecf7e674caf4227b99a2dd4](https://github.com/user-attachments/assets/44139aa3-2819-479e-9444-29e806a65283)
日志
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
参考：https://help.jeecg.com/jimureport/query/function.html

**Comment by jeecgos** [comment]
请升级版本！
