### ISSUE TITLE
全国地图的联动和下钻，点击省份的时候，能在文本框组件显示点击的省份名称。

### ISSUE THREAD

**Issue by chentianyi1989** [jeecgboot/JimuReport#3063]
##### 版本号：
2024官网demo

##### 问题描述：
需求：全国地图的联动和下钻，点击省份的时候，能在文本框组件显示点击的省份名称。
![image](https://github.com/user-attachments/assets/8398e4b4-8dba-498b-83c9-a4c01ebaf988)
第一个是离线地图，离线地图好像不支持联动。
第二个是在线地图，联动配置如图
![image](https://github.com/user-attachments/assets/21ab0c72-9de1-4f5d-8128-939dc051949a)
问题：点击对应省份后，没有响应。
![image](https://github.com/user-attachments/assets/e5a57b36-ec42-4cf2-ad59-5d071f8534ab)
使用饼图可以触发请求事件
![image](https://github.com/user-attachments/assets/70650807-4eed-4896-a61d-f32b52c06b9b)

##### 错误日志&截图：
官网案例地址：https://bootapi.jeecg.com/bigscreen/#/build/1849008557039607810?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3Mjk4ODI4MDcsInVzZXJuYW1lIjoiMTM2NTE3ODE5NDkifQ.IsF3a5Qo6iCLk_iO4g9mN90wWCYkaYDKl0Q_sSVxbek

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
sq

**Comment by chentianyi1989** [comment]
您好，邮件我已经收到，会尽快给您回复。

**Comment by chentianyi1989** [comment]
sq是什么意思呢？

**Comment by jeecgDeveloper** [comment]
旧版大屏后期不做更新，建议您使用新版BI大屏配置试试；
![image](https://github.com/user-attachments/assets/072c47f6-1fb4-4548-a25e-9ea1e54d93b5)
![demo33](https://github.com/user-attachments/assets/1da2bc82-198a-46c0-9176-7f233e05d9f1)

**Comment by chentianyi1989** [comment]
您好，邮件我已经收到，会尽快给您回复。
