### ISSUE TITLE
添加地图-点地图报表 添加完报表参数查询条件后无法运行

### ISSUE THREAD

**Issue by huangchaoc** [jeecgboot/JimuReport#3064]
##### 版本号：
1.8.1
##### 问题描述：
添加地图-点地图报表 添加完报表参数查询条件后无法运行

##### 错误日志&截图：
![捕获](https://github.com/user-attachments/assets/28e07307-4906-4678-bf25-e84aae69cb10)
![捕获1](https://github.com/user-attachments/assets/0f7e79d2-b59f-4c00-bd05-22b1167b1537)

##### 重现步骤：
添加地图-点地图报表 添加完报表参数查询条件后无法运行，在添加报表参数前一切正常。注：预览时可以查询

**Comment by jeecgos** [comment]
ws

**Comment by jeecgos** [comment]
已修复，待新版本发布
