### ISSUE TITLE
设置固定表尾，用A4纸打印，但表尾并没有在A4纸下方

### ISSUE THREAD

**Issue by gouchanghong** [jeecgboot/JimuReport#3065]
##### 问题描述：
设置固定表尾，用A4纸打印，但表尾并没有在A4纸的最下方，而是在A4纸中间偏下位置。
因为中间的数据是一个循环，数据可能多可能少，理想状态是，无论中间的数据多与少，表头都在最上方，表尾都在最下方，并且数据超过一页纸时，第二页纸也是同样的效果。

并且，如果数据量多的时候，导出pdf，表尾会出现重复的现象

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/2246d642-390b-473d-a0a4-03e03555e402)

![image](https://github.com/user-attachments/assets/cdd46f5f-139a-405f-8402-66c2fb47e174)

##### 重现步骤：
已在官网制作了报表，以下链接可访问：
https://bootapi.jeecg.com/jmreport/view/1009360483930951680?tenantSid=1830504961629360129&applySid=1848907107183104002&userSid=1830508253952479233&userName=%E6%9C%BA%E6%9E%84%E7%AE%A1%E7%90%86%E5%91%98

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
已修复
