### ISSUE TITLE
报表的查询条件是否可以在报表内容里面引用

### ISSUE THREAD

**Issue by afearboy** [jeecgboot/JimuReport#3066]
##### 版本号：
v3.7.1

##### 问题描述：
报表的查询条件是否可以在报表内容里面引用,比如条件里面选择的年份2024，在报表内容里面同时可以显示年份2024，内容与条件同步。

##### 错误日志&截图：
报表的查询条件是否可以在报表内容里面引用

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
可以通过${param.参数名}来引用
