### ISSUE TITLE
自动分组问题

### ISSUE THREAD

**Issue by lonelybeanz** [jeecgboot/JimuReport#3068]
##### 版本号：
1.8.1

##### 问题描述：
查询列表会自动分组，明明没有分组

##### 错误日志&截图：
<img width="1175" alt="image" src="https://github.com/user-attachments/assets/7e526175-bde9-4751-8965-a2638024c31e">

<img width="1074" alt="image" src="https://github.com/user-attachments/assets/5e526599-d2e8-48c6-8543-c4631ba17d7a">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by jeecgos** [comment]
cr

**Comment by lonelybeanz** [comment]
目前可以通过增加一个唯一键放到列表前方（白色隐藏）的方式防止自动分组

**Comment by jeecgos** [comment]
@lonelybeanz  已修复，待新版本发布。
