### ISSUE TITLE
积木报表新仪表盘，采用API的方式获取数据，数据解析报错。

### ISSUE THREAD

**Issue by shiwuye888** [jeecgboot/JimuReport#3069]
##### 版本号：
1.8.1-beat
##### 问题描述：
1、数据集配置如图所示：
![image](https://github.com/user-attachments/assets/b5a04698-00e0-4f24-8a3e-94618eac1d6e)
2、准备的数据，如图所示，参考官方文档上的格式返回的：
![image](https://github.com/user-attachments/assets/664e1c63-10da-4bb4-bd6e-3f0791d5e5fb)
![image](https://github.com/user-attachments/assets/62b895ec-6dfd-4298-9a8c-c4f0c423aac2)

##### 错误日志&截图：
API解析时报错：
![image](https://github.com/user-attachments/assets/cd337ef2-b10c-4b96-b207-4074862b7e78)
![image](https://github.com/user-attachments/assets/b9771d3f-8d0a-458a-a9d0-90f892c20796)
![image](https://github.com/user-attachments/assets/b1cd74d5-d778-4177-a29e-2f89d0d88e96)
报错：
请求地址'/drag/onlDragDatasetHead/queryFieldByApi',发生未知异常.
java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

##### 重现步骤：
1、设置数据集格式为API获取
2、准备一个GET请求，将官方文档上的数据格式返回
3、点击解析API报错

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
请参考这个：https://help.jeecg.com/jimureport/dataSet/api.html

**Comment by jeecgos** [comment]
![QQ_1729851975539](https://github.com/user-attachments/assets/a1890bbe-6644-42e6-952e-882e4b15fa7f)

**Comment by jeecgos** [comment]
sq

**Comment by shiwuye888** [comment]
> sq

啥意思？

**Comment by shiwuye888** [comment]
> 试试这个版本，应该修复了
> 
> ```
>  <dependency>
>    <groupId>org.jeecgframework.jimureport</groupId>
>    <artifactId>jimureport-dashboard-spring-boot-starter</artifactId>
>    <version>1.9.0</version>
>  </dependency>
> ```

这个依赖在哪下载？aliyun没有

**Comment by zhangdaiscott** [comment]
私服

**Comment by shiwuye888** [comment]
> 私服

那我该如何下载呢？

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/java/setup/maven.html
