### ISSUE TITLE
报表升级后使用DENSE_RANK()报错

### ISSUE THREAD

**Issue by dm1408** [jeecgboot/JimuReport#3070]
##### 问题描述：
报表升级后使用DENSE_RANK()报错

##### 错误日志&截图：

![image](https://github.com/user-attachments/assets/5df51f8f-ee25-415d-bf5d-2a3c0172328a)
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
cr

**Comment by jeecgos** [comment]
![QQ_1730097007179](https://github.com/user-attachments/assets/12573419-c4c3-4658-86f8-1d8d7ee09a5e)
![QQ_1730097015040](https://github.com/user-attachments/assets/89de5a7d-48f7-4729-a707-4c9475d209f3)

**Comment by dm1408** [comment]
版本号：1.8.1

**Comment by dm1408** [comment]
> 未复现，请提供版本号和重现步骤，或者针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID; ![QQ_1730097007179](https://private-user-images.githubusercontent.com/162332873/380601763-12573419-c4c3-4658-86f8-1d8d7ee09a5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTk4NjcsIm5iZiI6MTczMDA5OTU2NywicGF0aCI6Ii8xNjIzMzI4NzMvMzgwNjAxNzYzLTEyNTczNDE5LWM0YzMtNDY1OC04NmY4LTFkOGQ3ZWUwOWE1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQwNzEyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTYwZTU5MzIzOTc1YjJlOTk4Y2IwNzY5ZWIwYzY0YWM4YTNkNTA2MTc4NGNmOTI2N2Q3MzBlYTdiZGU3MjVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MKu2ydou0olwwGVctt67yLg-qU24KOUdN5g-EJpPits) ![QQ_1730097023690](https://private-user-images.githubusercontent.com/162332873/380601840-e566ad73-b4a6-4010-9503-5e9508be62f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTk4NjcsIm5iZiI6MTczMDA5OTU2NywicGF0aCI6Ii8xNjIzMzI4NzMvMzgwNjAxODQwLWU1NjZhZDczLWI0YTYtNDAxMC05NTAzLTVlOTUwOGJlNjJmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQwNzEyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMmVkOGQ3NzU4ZGVjOTliYTQwNjU4ZmQ3OThmMDk1MjIxNzU0NDBjOGQ4OWEwZDliZWRmMzYyZDM5OThkYmU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8FBQ6um6okrZj6A3Yf-E59LHyPlYIymZ3VzURVPvGvQ) ![QQ_1730097015040](https://private-user-images.githubusercontent.com/162332873/380601789-89de5a7d-48f7-4729-a707-4c9475d209f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTk4NjcsIm5iZiI6MTczMDA5OTU2NywicGF0aCI6Ii8xNjIzMzI4NzMvMzgwNjAxNzg5LTg5ZGU1YTdkLTQ4ZjctNDcyOS1hNzA3LTRjOTQ3NWQyMDlmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQwNzEyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjVmZjE3NDNiMTdhZTJiNWM0M2RlYWNkZDVkZTUyZTM1ZDQ0ZDU5NjZhNThkNTNmOGNlMzA2NmY3MTNmY2QwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-rIBa-v3Frh-7n9OsTi9ufa9yqfq2MTaqqtYD8V71Z8)

1.8.1

**Comment by jeecgos** [comment]
> 版本号：1.8.1

还有重现步骤；或者针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
