### ISSUE TITLE
主子报表，子报表空指针问题

### ISSUE THREAD

**Issue by lonelybeanz** [jeecgboot/JimuReport#3071]
##### 版本号：
1.8.1

##### 问题描述：
当主报表无数据时，子报表没必要去请求的。目前出现空指针问题

##### 错误日志&截图：
<img width="871" alt="image" src="https://github.com/user-attachments/assets/7a982432-b2a3-4cf9-b95c-b0343b0a8e64">

<img width="1150" alt="image" src="https://github.com/user-attachments/assets/9658f6f8-e722-472b-b94b-55a9ea456653">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
cr

**Comment by jeecgos** [comment]
已修复，待下个版本发布。
