### ISSUE TITLE
1.7.0版本支持多少条数据集，1.8.1-beta支持免费创建多少条数据集？

### ISSUE THREAD

**Issue by longjingcha** [jeecgboot/JimuReport#3072]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
免费版都是200条数据集，您如果有需求可以考虑购买商业版本

**Comment by longjingcha** [comment]
1.7.0版本数据库查看的的50多条数据集，为什么都提示已经超过200条呢？保存不了了？

**Comment by hoperunChen** [comment]
> 1.7.0版本数据库查看的的50多条数据集，为什么都提示已经超过200条呢？保存不了了？

你的报表有多少条？我确认了一下，200条是积木报表的数量限制，您确定你那提示的是数据集限制200吗？

**Comment by jeecgos** [comment]
> 1.7.0版本数据库查看的的50多条数据集，为什么都提示已经超过200条呢？保存不了了？

你的报表有多少条？我确认了一下，200条是积木报表的数量限制，您确定你那提示的是数据集限制200吗？
