### ISSUE TITLE
1.7.52免费版的数据集支持多少条？

### ISSUE THREAD

**Issue by longjingcha** [jeecgboot/JimuReport#3075]
##### 问题描述：
你好，请问一下咱们1.7.52免费版的数据集支持多少条？

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/e3708154-86ae-4c5f-af8b-0df8f3f64847)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
最新版应该放开到1000

**Comment by longjingcha** [comment]
> 最新版应该放开到1000

从哪个版本开始放开到1000?能否告知一下呢？1.7.52版本呢？
