### ISSUE TITLE
请问积木报表支持ARM架构的CPU吗，如果不支持的话是否有退出ARM版本的计划？

### ISSUE THREAD

**Issue by cao49049** [jeecgboot/JimuReport#3076]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持？

**Comment by cao49049** [comment]
![cdbb48af65b7cb15fe41671948c40d7](https://github.com/user-attachments/assets/1fe63646-4486-4bb9-b81f-523df5a9adf1)
我用的arm架构的cpu，docker安装的时候提示这个错误，请问是怎么回事呢，X86的服务器就没报错，安装成功。

**Comment by zhangdaiscott** [comment]
那你自己制作docker，或者自己制作JAR包启动
应该是docker里面用的jdk不兼容
