### ISSUE TITLE
仪表盘多租户的问题

### ISSUE THREAD

**Issue by 13813586515** [jeecgboot/JimuReport#3078]
##### 版本号：
1.8.1-beta

##### 问题描述：
仪表盘多租户，查询和新增时无法带租户 ，但是点复制居然可以带租户，通过断点发现，查询和新增不走扩展类JmReportTokenServiceImpl但是复制会走

##### 重现步骤：
1.按照文档集成token
2.打开模式为saasMode: tenant
3.点击 报表设计器 发现"/jmreport/list"会进入JmReportTokenServiceImpl获取自定义租户的tenantid
4.点击 仪表盘设计器 发现""/drag/list"**不会**进入JmReportTokenServiceImpl
5.点击 仪表盘设计器 复制功能 会进入JmReportTokenServiceImpl

**Comment by zhangdaiscott** [comment]
sq

**Comment by zhangdaiscott** [comment]
最新版已经修复
https://blog.csdn.net/zhangdaiscott/article/details/143369569
