### ISSUE TITLE
1.3.4-beta

### ISSUE THREAD

**Issue by qqlindy** [jeecgboot/JimuReport#308]
##### 版本号：
1.3.4-beta

##### 问题描述：
项目能正常启动，但是有空指针异常。每五秒输出下列空指针异常。 
[DirectJDKLog.java             ]--[175]: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
	at org.jeecg.modules.jmreport.desreport.a.a.b(DesignReportController.java:1169)

##### 截图&代码：
![image](https://user-images.githubusercontent.com/31119027/121126992-ade55880-c85b-11eb-92f2-90599153cab5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by larson-zss** [comment]
我这也有这个错误，发现就是导入excel后，在表格中无法增加方框，增加就报这个错

**Comment by zhangdaiscott** [comment]
收录 ws

**Comment by tygithub1** [comment]
点进去看看是啥代码，贴出来

**Comment by 1298191366** [comment]
导入excel加边框也没有报错，是否可以提供一下数据或者怎样配置的
