### ISSUE TITLE
文件上传minio的问题

### ISSUE THREAD

**Issue by shixiangyu1996** [jeecgboot/JimuReport#3081]
##### 错误日志&截图：
![Uploading image.png…]()

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
导出跟minio有什么关系？

**Comment by fecym** [comment]
我现在就是想把文件上传minio 但是我对着文档在yaml文件里面配置了minio的相关地址 但是我去minio里面找文件发现没有上传上去

**Comment by shixiangyu1996** [comment]
就是导出paf不是会生成文件吗 我就想吧这个文件上传的minoio里面  但是按照文档上面配置了之后我去minio里面找文件发现没有上传上来

**Comment by zhangdaiscott** [comment]
导出pdf生成文件到磁盘中，不会上传mino

**Comment by shixiangyu1996** [comment]
那上传minio的配置配好了之后 是什么会上传上去呢?
