### ISSUE TITLE
单元格内设置自动换行后，如何调整行间距？

### ISSUE THREAD

**Issue by jiapengshuai** [jeecgboot/JimuReport#3083]
##### 版本号：
1.7.9

##### 问题描述：
单元格内设置自动换行后，如何调整行间距？换行后多行内容都是挤在一块的，效果很差
如果免费版不支持此功能，商业付费版是否支持持功能，如果支持，如何设置？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
暂不支持，归集：#138
