### ISSUE TITLE
SQL数据集配置的时候，如果是where条件配置模糊匹配的时候该如何传参呢？${'name'},怎么加百分号呢？

### ISSUE THREAD

**Issue by longjingcha** [jeecgboot/JimuReport#3084]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by longjingcha** [comment]
有解答的没？还是说是官方不支持呢？

**Comment by jeecgos** [comment]
要实现模糊查询有多种方式可以使用，以下提供两种，您可以参考：
方法一：sql中使用`like concat`
![QQ_1730428234980](https://github.com/user-attachments/assets/4ff12029-f7c2-4c49-92a5-f268f6b2bea3)
![QQ_1730428312349](https://github.com/user-attachments/assets/662dea54-2257-4344-a0d1-c0ea08686bcd)
方法二：地址栏中使用%的转义
![QQ_1730428369798](https://github.com/user-attachments/assets/43e3e632-f09a-4693-a052-cc2b66f6c6a2)
![QQ_1730428398647](https://github.com/user-attachments/assets/33f3c206-06e6-486c-aca8-b2b555fc0430)
