### ISSUE TITLE
ruoyi- vue 集成 积木报表，本机调试运行正常。发布到服务器样式丢失。customPrePath  改成 prod-api  问题依旧

### ISSUE THREAD

**Issue by usandchina** [jeecgboot/JimuReport#3085]
##### 版本号：
        jimureport-spring-boot-starter  1.8.1

##### 错误日志&截图：
![1B6DA2A1B96C5AF772C2C22259371C4F](https://github.com/user-attachments/assets/e44e39bf-6a5d-4933-a015-6a421206b304)

**Comment by guotong1001** [comment]
怎么解决的
