### ISSUE TITLE
最新版本的jimureport无法兼容springboot3.3.4

### ISSUE THREAD

**Issue by zhanglan1184** [jeecgboot/JimuReport#3086]
##### 版本号：
    <dependency>
            <groupId>org.jeecgframework.jimureport</groupId>
            <artifactId>jimureport-spring-boot3-starter-fastjson2</artifactId>
            <version>1.8.1</version>
        </dependency>

##### 问题描述：
最新版本的jimureport无法兼容springboot3.3.4，出现页面无法渲染的情况

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/c91f5478-2af4-4791-abbe-8e2c9f149738)

##### 重现步骤：
将项目springboot版本升级到3.3.4，重启后端刷新页面，一片空白。降低springboot版本到3.3.3，恢复正常

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
错误日志截图

**Comment by zhanglan1184** [comment]
没有报错的日志，是前端直接无法渲染/jimu/jmreport/list返回的结果
![image](https://github.com/user-attachments/assets/91322ffb-6c76-492d-999e-798f9b76522d)

**Comment by zhangdaiscott** [comment]
集成问题，静态资源未加载，看文档

**Comment by zhanglan1184** [comment]
![微信截图_20241031145556](https://github.com/user-attachments/assets/69e91e9f-2ff2-4593-afe8-e0af9df92f0a)


静态资源可访问到，但是springboot是3.3.4版本就无法渲染
