### ISSUE TITLE
大屏连接数据库

### ISSUE THREAD

**Issue by zdwwwwwwwwwwwww** [jeecgboot/JimuReport#3087]
##### 问题描述：
大屏连接数据库出现问题，为什么说没有权限 我已经增加了

##### 错误日志&截图：
数据库连接失败：Could not connect to address=(host=127.0.0.1)(port=3306)(type=master) : (conn=6835570) Access denied for user 'root'@'172.17.0.1' (using password: YES) Current charset is UTF-8. If password has been set using other charset, consider using option 'passwordCharacterEncoding' 
![ffcc79f4-9570-4c19-b3db-b4a63b6d6278](https://github.com/user-attachments/assets/d10778bb-0a86-405c-8d27-eb3e579a14f7)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 2508207487** [comment]
这是官方部署的项目，服务器在官方那，不能用本地ip，可以用花生壳做个内网穿透

**Comment by zhangdaiscott** [comment]
可以把127.0.0.1 换成你的外网IP

**Comment by zdwwwwwwwwwwwww** [comment]
> 这是官方部署的项目，服务器在官方那，不能用本地ip，可以用花生壳做个内网穿透

方便留个联系方式吗，小白，有点弄不明白

**Comment by zdwwwwwwwwwwwww** [comment]
> 可以把127.0.0.1 换成你的外网IP

是需要搞一个内网穿透吗
