### ISSUE TITLE
报表预览报错：Could not initialize class org.jeecg.modules.desreport.express.ExpressUtil

### ISSUE THREAD

**Issue by yangweigithub** [jeecgboot/JimuReport#3090]
##### 版本号：
1.8.1

##### 问题描述：
报表设计好以后，跳转到预览页面出现报错信息：Could not initialize class org.jeecg.modules.desreport.express.ExpressUtil

##### 错误日志&截图：

![1730346033081](https://github.com/user-attachments/assets/125f3280-a6da-4ca0-94f6-f4b9cdb08b82)

##### 重现步骤：
![1730345955744](https://github.com/user-attachments/assets/b870b47e-4b0a-4b79-9c0e-3fc0ce543217)
![1730346033081](https://github.com/user-attachments/assets/e3ac7552-11c0-4851-a269-ca91f1fa499b)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by yangweigithub** [comment]
springboot 版本 2.3.5.RELEASE
----- 原始邮件 -----
发件人：JEECG ***@***.***>
收件人：jeecgboot/JimuReport ***@***.***>
抄送人：小卫笔记 ***@***.***>,  Author ***@***.***>
主题：Re:_[jeecgboot/JimuReport]_报表预览报错：Could_not_initialize_class_org.jeecg.modules.desreport.express.ExpressUtil_(Issue_#3090)
日期：2024年10月31日 11点45分


你的环境和项目架构说明

**Comment by zhangdaiscott** [comment]
试试最新版
https://blog.csdn.net/zhangdaiscott/article/details/143369569
