### ISSUE TITLE
报表制作分组聚合功能无效

### ISSUE THREAD

**Issue by FanPeng2024** [jeecgboot/JimuReport#3095]
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/9511f7e2-0e09-40b7-ba03-ca1464a48176)

##### 重现步骤：
![微信图片_20241031175558](https://github.com/user-attachments/assets/242251fb-772e-4035-bc04-df828ef98307)
我连接本地数据源，报表制作选择数据源，横列纵列都设置为分组，userid参数设置为动态，聚合为计数，但是结果显示了userid参数明细，我想知道这个是我操作错误还是版本根本不支持聚合？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；
![微信图片_20241031175528](https://github.com/user-attachments/assets/df61396d-77bf-4176-9da8-f9f956482589)

**Comment by jeecgos** [comment]
给横向分组字段设置的这个聚合方式是**分组小计**功能[参考文档](https://help.jeecg.com/jimureport/combination/subtotalSubtotal.html)，这个功能会针对纵向分组进行聚合计算;即对纵向的每一组数据进行聚合计算。您现在配置出来的就是**纵向分组小计效果**，只是因为你每一组纵向数据只有一条所以计数都等于1。

如果您需要对整个交叉报表进行聚合，可以使用[分组内合计功能](https://help.jeecg.com/jimureport/group/groupTotal.html)

**Comment by FanPeng2024** [comment]
非常感谢您的解答，我按照您给出的文档试验了但不是我想要的效果。我想要的是不显示计数的内容也不以计数对象单个为计数条件。根据文档的例子都是显示地区销售额后再进行小组合计，而实际大表中的数据不需要显示销售额，而直接统计数据条数和金额，这个功能如何实现呢？
![微信图片_20241101133133](https://github.com/user-attachments/assets/f74b0e73-bdae-4833-bf23-ea4b62ede395)

**Comment by FanPeng2024** [comment]
举例说就是：辽宁省下十万用户信息表，如何进行地市分组计数，而不是要显示每一个用户ID然后再最后单独一行分组求和，这不符合大数据分析。我试了很多个方法但都显示了用户ID再分组求和，包括文档中的示例也是将所有地区明细显示出来后再分组求和。

**Comment by jeecgos** [comment]
> 举例说就是：辽宁省下十万用户信息表，如何进行地市分组计数，而不是要显示每一个用户ID然后再最后单独一行分组求和，这不符合大数据分析。我试了很多个方法但都显示了用户ID再分组求和，包括文档中的示例也是将所有地区明细显示出来后再分组求和。

这个暂时不支持哦，先归集到：#138；
