### ISSUE TITLE
苹果ARM芯片docker部署修改文件问题

### ISSUE THREAD

**Issue by cao49049** [jeecgboot/JimuReport#3096]
##### 问题描述：
docker部署的第四步中“如果使用的是Mac M系列芯片，需要修改docker-compose.ym|文件的第一行为: FR0M arm64v8/mysq1:8”这一条是不是应该的是Dockerfile这个文件啊？

##### 错误日志&截图：
![}0JJI51X{W)2FDQ 4 }0UWB](https://github.com/user-attachments/assets/fb0518bd-1be2-4fe1-9e9e-4a3053e18a27)

Dockerfile
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by corrosive4354** [comment]
老哥，看见你们在用docker，
感觉可以尝试下servbay这个工具，在mac上更专业些

**Comment by jeecgos** [comment]
@cao49049 确实是写错了，应该是：
> 如果使用的是Mac M系列芯片，需要修改`db/Dockerfile`文件的第一行为：`FROM arm64v8/mysql:8`
