### ISSUE TITLE
苹果M芯片Docker部署成功，但运行不起来

### ISSUE THREAD

**Issue by cao49049** [jeecgboot/JimuReport#3097]
##### 版本号：
jimureport-example  1.9
jdk-18.0.2.1
##### 问题描述：
按docker部署的教程（我是苹果M芯片，修改了Dockerfile文件第一行为FROM arm64v8/mysq1:8），全程无报错，可是容器无法启动，查看日志显示如下，请问是怎么回事呢？

##### 错误日志&截图：
![dd63f991dc30162816dcf202e075c6a](https://github.com/user-attachments/assets/27a8adef-515d-4e14-9d31-cbe5f19422fd)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
@cao49049 您好，应该是您`arm64v8/mysql:8`改错文件了。
`Mac Apple M`系列芯片需要修改的是：
* `jimureport-example/db/Dockerfile`文件的第一行为：`FROM arm64v8/mysql:8`

另外jimureport的基础镜像也需要针对arm制作一个，并且修改第一行为：`FROM 自己制作的镜像名称`，jdk镜像制作可以可参考：https://juejin.cn/post/7203239282209718329

**Comment by hoperunChen** [comment]
> 请问官方能否出个针对arm的基础镜像，小白不太会做镜像。

以下镜像（仅供学习参考）
> 链接：https://pan.baidu.com/s/1m-Krn_oFuis636xZAOVm-w?pwd=ra73
