### ISSUE TITLE
新手配置。SQL无法解析

### ISSUE THREAD

**Issue by liusj51** [jeecgboot/JimuReport#3098]
##### 版本号：
v1.9.0 

##### 问题描述：
数据源连接后，SQL解析没有内容。数据源连接测试是OK. SQL解析字段没有出现。 SQL SERVER2012

##### 错误日志&截图：

![20241101134339](https://github.com/user-attachments/assets/5e86e424-70f8-4231-873b-85887d68558e)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
点击sql解析以后，页面上有提示解析成功吗？
![QQ_1730445949551](https://github.com/user-attachments/assets/42258966-2a54-4c3a-86fe-84b262074982)

如果没有提示成功，看下后台有没有报错信息？

**Comment by liusj51** [comment]
用后台服务器浏览器可以SQL解析，有字段。但是其他电脑浏览器SQL解析后就只是闪烁一下，字段没有出来。不知道什么原因

**Comment by jeecgos** [comment]
> 用后台服务器浏览器可以SQL解析，有字段。但是其他电脑浏览器SQL解析后就只是闪烁一下，字段没有出来。不知道什么原因

有问题的是什么浏览器？用浏览器的开发者工具看下控制台里有没有报错。

**Comment by liusj51** [comment]
@个人电脑使用chrome浏览器，点SQL解析没闪烁一下。开发者工具报错如图。
![微信图片_20241101164051](https://github.com/user-attachments/assets/bff2a298-e57c-48e9-9bbf-8c220cb3ac9f)

**Comment by jeecgos** [comment]
![QQ_1730459441022](https://github.com/user-attachments/assets/b96dbe98-73fd-477c-ac12-4023577bf19c)
你本地调用解析接口没有成功。检查下你本地到http://192.168.35.228:8085/inreport/queryFieldBySql 网络是不是通的？

**Comment by liusj51** [comment]
用telnet 测试192.168.35.228 8085 是通的. 但是这个还是报错, 不知道什么原因? 是不是哪个服务没有打开?
![image](https://github.com/user-attachments/assets/881aea9b-6d80-4260-a43a-ae71b6d08e55)

**Comment by hoperunChen** [comment]
> 用telnet 测试192.168.35.228 8085 是通的. 但是这个还是报错, 不知道什么原因? 是不是哪个服务没有打开? 

http://192.168.35.228:8085/jmreport/queryFieldBySql 是不是通的，之前的地址打错了。
如果网络是通的，看下后端有没有报错？

**Comment by liusj51** [comment]
![image](https://github.com/user-attachments/assets/dc5a4ba2-e0b6-4146-9c03-37be04b2cda8)
http://192.168.35.228:8085/jmreport/queryFieldBySql     网络是通的.

**Comment by jeecgos** [comment]
你的积木报表是怎么部署的？

**Comment by liusj51** [comment]
我们是按帮助文档一键部署的:  https://help.jeecg.com/jimureport/docker.html

**Comment by jeecgos** [comment]
我们这边使用docker-compose 一键部署并没有复现该问题，目前就上文推断，问题应该不是出在积木报表系统上。您可以在尝试下使用一个纯净的服务器部署，并且确保你的客户端和服务端是直连 中间没有任何转发的情况下看看还有没有问题。

> 以下是尝试复现的记录：
> CentOs7.9。docker-compose部署；
> ![QQ_1731290299907](https://github.com/user-attachments/assets/ba3b9be2-4082-46b4-a6ab-964554ab41a5)
> 客户端访问积木报表，并解析sql语句，未出现异常。
> ![QQ_1731290547905](https://github.com/user-attachments/assets/3daeaab3-ca38-4ba3-9e8a-03ced3490b46)

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题

**Comment by AshlynYang-dev** [comment]
> 因长时间未回复，暂时关闭此问题

我也出现了类似的情况，我加了一层网关做转发，也是这个接口请求不到
