### ISSUE TITLE
Field onlDragShareDao in org.jeecg.modules.drag.service.a.i required a bean of type 'org.jeecg.modules.drag.dao.OnlDragShareDao' that could not be found.

### ISSUE THREAD

**Issue by 1095321607** [jeecgboot/JimuReport#3099]
##### 版本号：
1.9.0

##### 问题描述：
提示该dao找不到

##### 错误日志&截图：

![image](https://github.com/user-attachments/assets/3b2afb50-b9f6-4df8-b3c2-f7e812effedb)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 1095321607** [comment]
Field onlDragShareDao in org.jeecg.modules.drag.service.a.i required a bean of type 'org.jeecg.modules.drag.dao.OnlDragShareDao' that could not be found

**Comment by zhangdaiscott** [comment]
```
#持久层框架
minidao:
  base-package: org.jeecg.modules.jmreport.*,org.jeecg.modules.drag.*
```
