### ISSUE TITLE
集合数据源，未按预想格式输出

### ISSUE THREAD

**Issue by luxin0810** [jeecgboot/JimuReport#3100]
##### 问题描述：一个集合数据源，分两行显示，如果是两条数据就是四行，上面两行是数据1，下面两行是数据2，
但现在显示的是数据1.1数据2.1数据1.2数据2.2

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/53fdfd5a-9370-46b4-82eb-9abc363aab6e)

![image](https://github.com/user-attachments/assets/53553152-d6e3-419b-bf62-99ce77bde992)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
您看下[循环块](https://help.jeecg.com/jimureport/datareport/loopBlock.html)能不能满足你的需求？
https://help.jeecg.com/jimureport/datareport/loopBlock.html

**Comment by luxin0810** [comment]
已解决 @jeecgos
