### ISSUE TITLE
小票打印高度能否自动获取

### ISSUE THREAD

**Issue by luxin0810** [jeecgboot/JimuReport#3101]
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/9bf3610c-acf2-49c1-802d-0c4d71ec4566)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
您好，抱歉，该功能目前还不支持。
#1128 也不支持 ， 先都归集到 #138

**Comment by luxin0810** [comment]
我小票打印机实测，是不会打印空白页面的 @jeecgos
