### ISSUE TITLE
自定义文本排序不生效

### ISSUE THREAD

**Issue by qiao-ydl** [jeecgboot/JimuReport#3107]
##### 版本号：
1.8.0

##### 问题描述：
横向/纵向分组后自定义文本排序不生效
先使用sql排序，查询数据是有序的，报表展示数据变成无序了
后使用自定义文本排序后发现不生效

##### 错误日志&截图：
![0e45a14b6c16c5adc695bc53a162449](https://github.com/user-attachments/assets/f8ccaf91-823c-4083-8e9d-d28dcd44aefe)
![5dde7e97e2ed603ba8c19bec662acac](https://github.com/user-attachments/assets/cc1e5d5c-8c47-4619-8169-74c443c067ae)
![0fe8c2bb0ad40b8961d523c62b67b40](https://github.com/user-attachments/assets/c996ce19-89cd-45c9-8f2f-ea52cf279c97)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
先升级到最新版，再看是否有问题

**Comment by jeecgos** [comment]
cr
