### ISSUE TITLE
报表sql里面字符串包含有:报表无法加载，解析sql也失败

### ISSUE THREAD

**Issue by 1487634539** [jeecgboot/JimuReport#3108]
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/262280b4-664d-44c9-93a8-ad0b2d7f5612)
![image](https://github.com/user-attachments/assets/44022882-d915-4f55-99fd-b6f429ea8d13)
![image](https://github.com/user-attachments/assets/24c241ad-c07d-4202-9077-5bda6fa5eb28)

##### 重现步骤：
我是用的是这段sql：

WITH date_range AS ( SELECT generate_series ( '2024-11-03' :: TIMESTAMP, CONCAT ( '2024-11-03', ' 23:59:59' ) :: TIMESTAMP, '10 minute' :: INTERVAL ) AS datetime ) SELECT
to_char( dr.datetime, 'YYYY-MM-DD HH24:MI' ) AS datetime,
MAX ( ivd.node_value ) FILTER ( WHERE ivd.node_code = 'UNIT1:10PGB13CQ102XQ01' ) AS data1
FROM
	date_range dr
	LEFT JOIN dcs_node_data ivd ON dr.datetime = date_trunc( 'minute', ivd.data_time ) 
GROUP BY
	dr.datetime 
ORDER BY
	dr.datetime;

在我把其中的 UNIT1:10PGB13CQ102XQ01 的:改为下划线_之后就不会有这个问题，但是我这个编码是固定的，没法改变的，是由别的地方提供，只负责用它采集数据，所以没法修改，我只是修改确定了问题在它的身上

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；
[1机月水汽系统参数.json](https://github.com/user-attachments/files/17629807/1.json)

**Comment by 1487634539** [comment]
最新版1.9.0也同样有这个问题，我追评使用的就是最新版测试的啊

**Comment by jeecgos** [comment]
cr

**Comment by jeecgos** [comment]
已修复，待下个版本更新
