### ISSUE TITLE
颜色表达式无法和分组共用

### ISSUE THREAD

**Issue by lyu-zzed** [jeecgboot/JimuReport#3109]
##### 版本号：

1.8.1
##### 问题描述：

对年龄大于24的人的性别数据进行更换填充颜色时无法进行分组
=(
if('#{tt.age}'  > '24') {
    return color('#{tt.group(sex)}', '#000100', '#f7ccac');
}
return '#{tt.group(sex)}';
)

##### 错误日志&截图：

![image](https://github.com/user-attachments/assets/3da36b1c-188e-4912-82b6-bce23a7e1e4c)

##### 重现步骤：

在性别栏下面填写
=(
if('#{tt.age}'  > '24') {
    return color('#{tt.group(sex)}', '#000100', '#f7ccac');
}
return '#{tt.group(sex)}';
)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；
  
  下面是报表配置文件
[简单分组报表副本6566.json](https://github.com/user-attachments/files/17640495/6566.json)

**Comment by jeecgos** [comment]
暂不支持，归集：#138
