### ISSUE TITLE
报表钻取，选择主表汉子字段为连接时候原始值不能下拉，为英文字段可以

### ISSUE THREAD

**Issue by xiaochunping** [jeecgboot/JimuReport#3110]
##### 版本号：
v1.8.1

##### 问题描述：
报表钻取，选择主表汉子字段为连接时候原始值不能下拉，为英文字段可以

##### 错误日志&截图：
![f6109a53b9c344fe5d7cb1a981068839](https://github.com/user-attachments/assets/5f1e2f56-3527-461e-af66-305c8ddd2ad0)
![6ddf5475349347062f2af3e76fd6a737](https://github.com/user-attachments/assets/27134e76-dc04-4a54-a67d-b7f396b7d7ed)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
cr

**Comment by jeecgos** [comment]
已修复，待下个版本更新。
