### ISSUE TITLE
积木仪表盘点击预览后，页面中调用的接口，是我该服务的IP端口，不是nginx的端口

### ISSUE THREAD

**Issue by wangyl123123** [jeecgboot/JimuReport#3111]
##### 问题描述：积木仪表盘点击预览后，页面中调用的接口，是我该服务的IP端口，不是nginx的端口
我从nginx访问系统，统一转发到网关，网关在统一转发到积木报表服务。
##### 错误日志&截图：
预览页面：http://localhost/drag/share/view/1011890741255962624
预览页面下的请求：http://192.168.101.21:11007/drag/page/queryById?id=1011890741255962624

![1730865735788](https://github.com/user-attachments/assets/094749c2-49ff-42be-ad81-561ab1d99bbc)
![1730865755310](https://github.com/user-attachments/assets/d52af933-7be5-49ce-8859-952fb6575018)

##### 重现步骤：
我从nginx访问系统，统一转发到网关，网关在统一转发到积木报表服务。
当访问到drag/share/view/1011890741255962624?tenantId=1页面时，页面内的请求直接访问的是本服务IP端口，可以配置成访问nginx的IP端口吗？
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
没明白，直接访问后台不就好了

**Comment by wangyl123123** [comment]
我们这里只开放了nginx的端口，所有请求都是通过nginx转到网关，再到报表服务。
http://localhost/drag/share/view/1011890741255962624。这里可以访问到这个预览页面，但是预览页面内部调的接口apiBase是
http://192.168.101.21:11007/drag/page/queryById。11007是报表服务的端口。80是nginx的端口。
![1730880370773](https://github.com/user-attachments/assets/29c2c48b-6d1c-435b-ba8f-5f99678a9d3d)
我看到后台返回了domainURL，这个domainURL 可以自己配置吗

**Comment by wangyl123123** [comment]
![image](https://github.com/user-attachments/assets/353c997b-7e40-48f0-8830-0d75d5f0138d)
我配置了这个参数，也不管用

**Comment by zhangdaiscott** [comment]
不支持

**Comment by guoyangjie** [comment]
> 不支持

1.9.1这个问题还有，是不支持这样跳转？
