### ISSUE TITLE
springboot3集成积木报表1.8.1出现404问题

### ISSUE THREAD

**Issue by simaozi** [jeecgboot/JimuReport#3112]
##### 版本号：
        <dependency>
            <groupId>org.jeecgframework.jimureport</groupId>
            <artifactId>jimureport-spring-boot3-starter-fastjson2</artifactId>
            <version>1.8.1</version>
        </dependency>
jdk17
springboot3

##### 问题描述：
空白项目只集成积木报表boot3依赖 启动无法访问首页

##### 错误日志&截图：
![Snipaste_2024-11-06_12-54-30](https://github.com/user-attachments/assets/0277896a-e1a3-4e05-9d87-dd7b6b844f40)

##### 重现步骤：
1.新建项目-添加pom
![1](https://github.com/user-attachments/assets/417b93dc-1dba-4cd4-85ca-0e9c838bcaed)
![2](https://github.com/user-attachments/assets/068d7a62-4664-41c3-b484-108f3423473a)
![3](https://github.com/user-attachments/assets/e87c14b6-e2dc-4171-8c4f-7fa3aa3a92d9)

2.修改配置
![4](https://github.com/user-attachments/assets/2dede64e-c818-4611-9cb2-5672ba10754c)

3.然后导入了1.8.1版本的sql到数据库
4.启动项目，访问localhost:9000/jmreport/list](http://localhost:8085/jmreport/list
结果就是404
请问以上可能是什么问题

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；
![3](https://github.com/user-attachments/assets/dfcdfd1c-efcf-4201-8215-a55476db8166)

**Comment by simaozi** [comment]
是接口都访问不到，同样的配置下，如果把jdk，springboot，积木报表都换成boot2那一套，就没有问题，是需要加什么特殊的配置吗？

**Comment by simaozi** [comment]
![5](https://github.com/user-attachments/assets/592fe678-5771-45eb-938a-90f57a54e6a1)

**Comment by simaozi** [comment]
看起来是这个请求从浏览器发出去，被认为是静态资源而不是接口，导致404，请问如何解决呢？

**Comment by zhangdaiscott** [comment]
![image](https://github.com/user-attachments/assets/c1f023ac-ae32-410e-8094-8348e3e9f5ea)
权限用的是什么？
按照文档每一步都操作了吗
https://help.jeecg.com/jimureport/quick.html

**Comment by simaozi** [comment]
是空项目，就是想单纯测试一下集成的，所以压根就没有权限，所以既没有排除也没有重写

**Comment by simaozi** [comment]
> ![图像](https://private-user-images.githubusercontent.com/3162115/383426412-c1f023ac-ae32-410e-8094-8348e3e9f5ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NzMzNDQsIm5iZiI6MTczMDg3MzA0NCwicGF0aCI6Ii8zMTYyMTE1LzM4MzQyNjQxMi1jMWYwMjNhYy1hZTMyLTQxMGUtODA5NC04MzQ4ZTNlOWY1ZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDZUMDYwNDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWU3MTI4NTM4ZDE4NDFkOWI5ODdhOTVjYTEwOTY0MmVjYTUwZTZmOGUxZmQxOWU3YmZiNTIyOGMyMTNiYzMzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Tdwu66us_ekucpC96f3-C8PpyGUuk3XBFX5UIWYjWBw)权限用的是什么？ 按照文档每一步都操作了吗 https://help.jeecg.com/jimureport/quick.html

![11](https://github.com/user-attachments/assets/f1a2bbbf-20aa-451f-bf08-29277883c705)
如此空白的项目，如图，配置就在上面，贴了完整的。
看起来像是这个controller没有放到容器里呢？您是否有官方的boot3的集成demo呢？为何我切换到2就一切正常了。。（当然springboot也需要同时切换到2.7.1x）

**Comment by simaozi** [comment]
![32](https://github.com/user-attachments/assets/68e7f0bb-af6b-49fa-90c5-b82bff006752)
麻烦官方看一下，我觉得问题可能是在红圈这里，这个请求头明显是有问题的，但是可能是因为框架没有注入控制器导致的请求头问题

**Comment by zhangdaiscott** [comment]
启动类，扫码路径怎么配置的

**Comment by simaozi** [comment]
![55](https://github.com/user-attachments/assets/71b5cb8d-6117-4a54-bbdd-4faef15da985)
啥也没写，走的默认的，我一开始也想过需不需要额外扫描积木报表的路径，但是我看boot2的可以自动识别，所以就没试验，难道积木boot3的需要自己额外扫包吗？自动配置没生效还是没写这块。。。

**Comment by simaozi** [comment]
![777](https://github.com/user-attachments/assets/ae3082ea-c2da-4beb-a0d8-49d8171cd1d7)
我刚才这样试了一下，就可以了。。。果然是默认自动配置可能官网忘了写了，这个bug有点严重啊亲，可以优先更新吗

**Comment by KimlerJin** [comment]
![f25c4d0f7e7abb41a74029f5fc454b70](https://github.com/user-attachments/assets/a12eb91c-2301-4a26-bc68-5866beb3f10c)
我建了个issue被删了，如上图大家用的时候注意一下
