### ISSUE TITLE
自定义日期查询格式报错

### ISSUE THREAD

**Issue by yaocanke** [jeecgboot/JimuReport#3113]
##### 版本号：
软件版本：1.9.0
数据库：oracle11G

##### 问题描述：
在查询条件中定义查询日期格式为yyyy，在预览查询的时候报错，原因是 后台SQL语句的 to_date无法将'yyyy'格式转换成'yyyy-MM-dd HH24:mi:ss'，在mysql中正常，但oracle会报错。
where f_year= to_date( ?,'yyyy-MM-dd HH24:mi:ss')

##### 错误日志&截图：
![9a55e96117f8c2c1be90292041eb893](https://github.com/user-attachments/assets/e941e1d4-cc4c-4c3a-8354-64c6c5b084d8)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by KimlerJin** [comment]
![f25c4d0f7e7abb41a74029f5fc454b70](https://github.com/user-attachments/assets/36c839e2-7316-422e-a7f0-1e3ecdb01878)
坑！注意

**Comment by zhangdaiscott** [comment]
cr

**Comment by jeecgos** [comment]
@yaocanke 你的这个`f_year`在数据库里是什么类型？
>如果是字符串类型，是不能用`日期类型`的查询条件的，因为在查询时我们会将查询条件转换成date类型去比较，这样你肯定查不到想要的数据。建议你使用字典下拉或者输入框来实现查询。

**Comment by yaocanke** [comment]
> @yaocanke 你的这个`f_year`在数据库里是什么类型？
> 
> > 如果是字符串类型，是不能用`日期类型`的查询条件的，因为在查询时我们会将查询条件转换成date类型去比较，这样你肯定查不到想要的数据。建议你使用字典下拉或者输入框来实现查询。

SQL语句是：select col_a,col_b,to_char(col_b,'yyyy') as f_year from table_A
其中col_b字段在oracle数据库里字段类型为datetime，
f_year字段为参考官方手册将col_b字段转成年，
参考官网的内容如下：
![image](https://github.com/user-attachments/assets/e776dcb0-5bbc-4cef-90b7-66c3571e15dd)

**Comment by jeecgos** [comment]
你这种情况字段类型需要使用字符类型，不能用日期，查询条件使用输入框或者下拉选择。
![QQ_1731054894139](https://github.com/user-attachments/assets/56a25613-7369-49ab-b06c-970c85bcc3af)

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
