### ISSUE TITLE
仪表盘报表静态资源出错

### ISSUE THREAD

**Issue by gaokaoli** [jeecgboot/JimuReport#3115]
##### 版本号：

最新版本，还有这个问题：https://github.com/jeecgboot/JimuReport/issues/3029

##### 问题描述：
仪表盘界面错乱，静态资源请求出错

![image](https://github.com/user-attachments/assets/6451edb1-4049-4451-90f4-7354d7929a06)

![image](https://github.com/user-attachments/assets/a96e7ee7-23e8-4032-9c5b-b3fad79de59f)

![image](https://github.com/user-attachments/assets/9dbec5f9-5681-4194-adba-40dff657f2d7)

---------------------------------------------------
积木报表是正常可以的
![image](https://github.com/user-attachments/assets/1537aefe-1a26-4f75-91f0-a6df9158c2b4)

维度仪表盘不行！

##### 重现步骤：

原先积木报表是可以的，增加了仪表盘报表就不行了
![image](https://github.com/user-attachments/assets/113e7664-c78d-47f3-ae03-2da10d8743ba)

`@Slf4j
@Service("onlDragExternalServiceImpl")
public class jimuDragExternalServiceImpl implements IOnlDragExternalService{

	/**
	 *  根据多个字典code查询多个字典项
	 * @param codeList
	 * @return key = dictCode ； value=对应的字典项
	 */
	@Override
	public Map<String, List<DragDictModel>> getManyDictItems(List<String> codeList, List<JSONObject> tableDictList) {
		Map<String, List<DragDictModel>> manyDragDictItems  = new HashMap<>();

		return manyDragDictItems;
	}

	/**
	 *
	 * @param dictCode
	 * @return
	 */
	@Override
	public List<DragDictModel> getDictItems(String dictCode) {
		List<DragDictModel> dictItems  = new ArrayList<>();

		return dictItems;
	}

	/**
	 * 添加日志
	 * @param dragLogDTO
	 */
	@Override
	public void addLog(DragLogDTO dragLogDTO) {

	}

	/**
	 * 保存日志
	 * @param logMsg
	 * @param logType
	 * @param operateType
	 */
	@Override
	public void addLog(String logMsg, int logType, int operateType) {

	}
}`

`        <dependency>
            <groupId>org.jeecgframework.jimureport</groupId>
            <artifactId>jimureport-dashboard-spring-boot-starter</artifactId>
            <version>1.9.0</version>
            <exclusions>
                <exclusion>
                    <artifactId>knife4j-openapi2-spring-boot-starter</artifactId>
                    <groupId>com.github.xiaoymin</groupId>
                </exclusion>
            </exclusions>
        </dependency>`
        
        
        

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
sq

**Comment by zhangdaiscott** [comment]
详细说明你的架构和配置方式，用法

**Comment by gaokaoli** [comment]
badex的架构：[https://[bladex.cn/#/](https://bladex.cn/#/)](url)

按照上述方式进行嵌入，发现不大行，找不到静态资源
具体配置
![image](https://github.com/user-attachments/assets/c8fce826-48a9-4317-8300-51531e4af4ce)

**Comment by gaokaoli** [comment]
不是很明白解决方法，求up主修复

**Comment by zhangdaiscott** [comment]
下个版本支持，未做这个功能
