### ISSUE TITLE
动态合并单元格不生效

### ISSUE THREAD

**Issue by lyu-zzed** [jeecgboot/JimuReport#3116]
##### 版本号：
1.9.0

##### 问题描述：
动态合并单元格和if表达一起使用时动态合并单元格不生效

=(
if('#{shouru.name}' == '张一一') {
    return color('#{shouru.ncnum}', '#000100', '#f7ccac');
}
return '#{shouru.ncnum}';
)
只用颜色表达式的时候就可以使用
=color('#{shouru.ncnum}', '#000100', '#f7ccac')；

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/c3e219ea-feb7-470b-9c6f-8f1dd4a7aba6)

![image](https://github.com/user-attachments/assets/9a762651-ac77-4e65-8064-f53d95e17bc3)

##### 重现步骤：
在D5列填入
=(
if('#{shouru.name}' == '张一一') {
    return color('#{shouru.ncnum}', '#000100', '#f7ccac');
}
return '#{shouru.ncnum}';
)
然后设置为动态合并单元格

报表配置：
[学校收入一览表副本2172.json](https://github.com/user-attachments/files/17656504/2172.json)

**Comment by jeecgos** [comment]
暂不支持，归集：#138
