### ISSUE TITLE
分组10个的限制能否更多一些

### ISSUE THREAD

**Issue by zwjsoft** [jeecgboot/JimuReport#3118]
##### 版本号：
1.9

##### 问题描述：
目前分组最多支持10个字段，能否更多一点，因为分组的合并单元格合计可以解决很多问题，10个字段还是有点少，一个文本组合和几个数字组合就不够了。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
你说的最多10个字段，是横向动态列分组还是纵向分组？现在的版本里纵向分组应该是不限制分组字段数量了，你可以试一下。如果有问题麻烦提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by zwjsoft** [comment]
> 你说的最多10个字段，是横向动态列分组还是纵向分组？现在的版本里纵向分组应该是不限制分组字段数量了，你可以试一下。如果有问题麻烦提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

经过再测试，是好的，之前可能某一个字段不同没合并，其他字段都看错了
