### ISSUE TITLE
分组后列表字段设置最大值不生效！

### ISSUE THREAD

**Issue by zwjsoft** [jeecgboot/JimuReport#3119]
##### 版本号：
1.9

##### 问题描述：
报表的一些字段设置的分组，一些字段设置了取大值，分组生效了，最大值列未生效。

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/6f7684d5-e65a-433b-a50c-b1fa4e152aae)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
@zwjsoft 分组不能和最大值函数一起用，可以看下[分组内合计（分组聚合）](https://help.jeecg.com/jimureport/group/groupTotal.html)能不能满足你的需求？

**Comment by zwjsoft** [comment]
> @zwjsoft 分组不能和最大值函数一起用，可以看下[分组内合计（分组聚合）](https://help.jeecg.com/jimureport/group/groupTotal.html)能不能满足你的需求？

应该不能，那个增加合计行用的，我这个其实本质是分组，分组的时候相同的合并单元格，现在我希望不同的值也合并单元格，取最大或者最小值，都是为了解决一个场景，一些数据被拆成多行后，希望按照一定的规则后合并单元格显示

**Comment by jeecgos** [comment]
> > @zwjsoft 分组不能和最大值函数一起用，可以看下[分组内合计（分组聚合）](https://help.jeecg.com/jimureport/group/groupTotal.html)能不能满足你的需求？
> 
> 应该不能，那个增加合计行用的，我这个其实本质是分组，分组的时候相同的合并单元格，现在我希望不同的值也合并单元格，取最大或者最小值，都是为了解决一个场景，一些数据被拆成多行后，希望按照一定的规则后合并单元格显示

目前还不支持，归集：#138
