### ISSUE TITLE
关于积木报表文件上传minio的问题

### ISSUE THREAD

**Issue by shixiangyu1996** [jeecgboot/JimuReport#3121]
##### 问题描述：大佬们好:
有几个问题想请教一下 :
1: 我想请问一下 我想在预览完毕之后把文件id上传到minio 这样的话我应该怎么做呢? 
2: 我按照官网文件上传minio的配置说明 操作之后 也找到了积木上传的接口 我应该怎么操作才可以上传呢?
3: 大佬们能不能出一个导出pdf之后的回调接口哇 我想能拿到查询主数据的具体业务id 和形成的pdf的文件
 
感谢大佬们  谢谢!
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
文件id，你是指那个文件如果是指报表导出PDF的话，没这个功能

**Comment by zhangdaiscott** [comment]
没这功能
