### ISSUE TITLE
1.9.0 token无法覆盖传递

### ISSUE THREAD

**Issue by 15206125206** [jeecgboot/JimuReport#3122]
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/a0dd6867-2ffc-417a-8a20-fc5f4f959832)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
已经处理，下个版本发布
