### ISSUE TITLE
仪表盘的静态资源无法访问

### ISSUE THREAD

**Issue by grnv1** [jeecgboot/JimuReport#3124]
##### 版本号：
1.9.0

##### 问题描述：
使用了sringboot的微服务架构，配置了customPrePath，但是只对报表以及仪表盘的首页生效，在仪表盘内部仍然通过没有添加中间路径的连接访问静态资源。

##### 错误日志&截图：
主页访问的是有中间路径的连接：
![Uploading 微信图片_20241111165859.jpg…]()
编辑仪表盘时访问的是没有中间路径的连接：
![Uploading 微信图片_20241111165850.jpg…]()

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by hao1175310925** [comment]
楼主，这个问题你后面有解决了吗

**Comment by jeecgDeveloper** [comment]
截图看不到，重新发一下

**Comment by hao1175310925** [comment]
版本号：1.9.0

问题描述：yaml里配置了apiBasePath参数，报表目前正常，仪表盘里还是局域网ip

错误日志&amp;截图：








目前这些接口，还有一些静态资源会报错






??
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月15日(星期五) 中午12:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 仪表盘的静态资源无法访问 (Issue #3124)





 
截图看不到，重新发一下

**Comment by grnv1** [comment]
![屏幕截图 2024-11-11 165550](https://github.com/user-attachments/assets/29c5a226-e739-4a53-b8d1-5bd85cf12263)
![屏幕截图 2024-11-11 165626](https://github.com/user-attachments/assets/40b81114-6da9-4aff-bf27-0854c193c6a6)

**Comment by jeecgos** [comment]
#3115

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/JimuReport/issues/3128
