### ISSUE TITLE
关于静态资源的问题

### ISSUE THREAD

**Issue by shixiangyu1996** [jeecgboot/JimuReport#3127]
##### 版本号：

1.7.0
##### 问题描述：
配置了
jeecg:  
  jmreport:
    customPrePath: /demo
之后还是访问不到 路径拼不上去  接口返回的是200

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
描述过于简单
