### ISSUE TITLE
集成后访问无页面样式

### ISSUE THREAD

**Issue by guotong1001** [jeecgboot/JimuReport#3128]
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/f0d8af0f-f8ba-4536-bc84-8c868015cc50)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
有排除静态资源吗？
```
filterChainDefinitionMap.put("/jmreport/**", "anon");
filterChainDefinitionMap.put("/**/*.js.map", "anon");
filterChainDefinitionMap.put("/**/*.css.map", "anon");
```
