### ISSUE TITLE
Api数据源报表传参，post请求，后端接收不到参数

### ISSUE THREAD

**Issue by dujx2018** [jeecgboot/JimuReport#313]
##### 版本号：
1.3.4-beta

##### 问题描述：
Api数据源报表传参，post请求，后端接收不到参数是怎么回事

##### 截图&代码：

不知道什么原因图片上传总是失败。
api地址如下
http://ip:port/analysis/purchaseDetails2?beginDate=${beginDate}&endDate=${endDate}
报表参数：

<meta name="Generator" content="Microsoft Excel">

<style>

</style>

参数 | 参数文本 | 默认值
-- | -- | --
beginDate | beginDate | 2021-05-01
endDate | endDate | 2021-05-19

**Comment by tygithub1** [comment]
参考文档： https://www.kancloud.cn/zhangdaiscott/jimureport/2196699

**Comment by dujx2018** [comment]
收到，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月11日(星期五) 下午5:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhangdaiscott/JimuReport] Api数据源报表传参，post请求，后端接收不到参数 (#313)





 
参考文档： https://www.kancloud.cn/zhangdaiscott/jimureport/2196699
