### ISSUE TITLE
springboot3 1.8.1 多数据源报错

### ISSUE THREAD

**Issue by zwjsoft** [jeecgboot/JimuReport#3130]
##### 版本号：
springboot3 1.8.1

##### 问题描述：
启动多数据源报错，我的环境里面确实有2个数据源和2个JdbcTemplate，其中一个数据源也加了@Primary标记，需要怎么处理？

##### 错误日志&截图：
Field jdbcTemplate in org.jeecg.modules.jmreport.test.TestController required a single bean, but 2 were found:
	- mngappJdbcTemplate: defined by method 'primaryJdbcTemplate' in class path resource [com/mngapp/commtools/config/DataSourceConfig.class]
	- quartzJdbcTemplate: defined by method 'secondaryJdbcTemplate' in class path resource [com/mngapp/commtools/config/DataSourceConfig.class]

This may be due to missing parameter name information

org.jeecg.modules.jmreport.test.TestController，这里面的@Autowired 应该有问题

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
已修复，请等待新版本发布。
