### ISSUE TITLE
报表中用到了条件表达式if，查询时每页显示100条及以下都行，300条就报错

### ISSUE THREAD

**Issue by wang727179528** [jeecgboot/JimuReport#3131]
##### 重现步骤：
条件表达式如下：
=(let istelsupplier= '#{dpStock.istelsupplier}'; 
if(istelsupplier== '是'){
   return  color('是','red','');
}else{
   return '否';
})

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
![QQ_1731897113093](https://github.com/user-attachments/assets/d552f0a3-441d-4f52-acee-7b9d879aab62)
![QQ_1731897137590](https://github.com/user-attachments/assets/322f0c84-e6ae-4120-98f6-ebef88ed2f5f)
未复现，请先升级版本试一下。

**Comment by wang727179528** [comment]
升级版本可能会对业务造成影响，麻烦您这边使用我这个版本测一下可以吗
