### ISSUE TITLE
报表sql数据源查询为空，新增有效

### ISSUE THREAD

**Issue by guotong1001** [jeecgboot/JimuReport#3133]
##### 问题描述：
新增报表，选择sql数据源，查询为空，新增数据源后依然查询为空，数据库有新增的记录

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/cbe85a8f-504a-49c2-b4d6-9079bbbb4294)
![image](https://github.com/user-attachments/assets/83890413-cb1f-4674-b30d-a229da2801c7)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
无回复关闭
