### ISSUE TITLE
1.9.0版SQLserver数据源报错

### ISSUE THREAD

**Issue by ziyouduxing** [jeecgboot/JimuReport#3135]
##### 版本号：1.9.0
springboot 2.3.5.RELEASE

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by ziyouduxing** [comment]
![Uploading 9333f854896ff05d17dcc355ca52227.png…]()

**Comment by ziyouduxing** [comment]
![9333f854896ff05d17dcc355ca52227](https://github.com/user-attachments/assets/b2d7d835-b0a6-4835-ae9c-5ed48afb8a86)

**Comment by zhangdaiscott** [comment]
jsqlparse版本冲突吧

**Comment by ziyouduxing** [comment]
<dependency>
			<groupId>org.jeecgframework.jimureport</groupId>
			<artifactId>jimureport-spring-boot-starter</artifactId>
			<version>1.9.0</version>
			<exclusions>
				<exclusion>
					<groupId>com.github.jsqlparser</groupId>
					<artifactId>jsqlparser</artifactId>
				</exclusion>
			</exclusions>
</dependency>
排除掉了也不行，只有SQLserv数据库报错，MySQL、Oracle数据库都没问题

**Comment by ziyouduxing** [comment]
![343ae499daac15d343bae693096ee20](https://github.com/user-attachments/assets/72e2fb03-3c10-4d71-a17d-312cdaf1dd9e)
排除了也不行，只有SQLservice数据库报错，MySQL、Oracle数据库都没问题
