### ISSUE TITLE
get请求的大屏参数，拼接到了数据源后面

### ISSUE THREAD

**Issue by Gyv12345** [jeecgboot/JimuReport#3138]
##### 版本号：
1.9.0

##### 问题描述：
大屏设计中的一个柱状图使用的是数据源形式，自己写的sql，在预览 和 分享 的页面，如果get请求上有参数的话，会被数据源查询的时候，拼接到最后。

##### 错误日志&截图：
<img width="1001" alt="image" src="https://github.com/user-attachments/assets/97d25b86-7d85-42de-a594-8e57d5fbd037">
<img width="699" alt="image" src="https://github.com/user-attachments/assets/173353f6-bb24-4533-80f1-c34c1c06f188">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
大屏配置截图

**Comment by Gyv12345** [comment]
<img width="1209" alt="image" src="https://github.com/user-attachments/assets/8e2e8b3f-7acb-4402-a981-ffd355708b00">
这个嘛

**Comment by Gyv12345** [comment]
<img width="366" alt="image" src="https://github.com/user-attachments/assets/978c41d4-8921-4abe-aec6-0eb8e98a3ff9">
