### ISSUE TITLE
新建数据大屏，保存时报错

### ISSUE THREAD

**Issue by brantzzu** [jeecgboot/JimuReport#3139]
##### 版本号：
1.9.0

##### 问题描述：
新建数据大屏，点击保存按钮提示操作失败。

##### 错误日志&截图：

![54ca70d61b36ef932d4bd01d92f3226b_720](https://github.com/user-attachments/assets/eb8c7208-181c-44ca-9911-7cfa9c16f629)

`package org.jeecg.modules.drag.b;

import java.text.MessageFormat;
import java.util.Base64;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.SynchronousQueue;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;
import javax.servlet.http.HttpServletRequest;
import org.apache.commons.lang3.StringUtils;
import org.jeecg.modules.drag.config.common.Result;
import org.jeecg.modules.drag.config.page.DragPage;
import org.jeecg.modules.drag.e.a;
import org.jeecg.modules.drag.e.i;
import org.jeecg.modules.drag.e.m;
import org.jeecg.modules.drag.entity.OnlDragPage;
import org.jeecg.modules.drag.service.IOnlDragDataSourceService;
import org.jeecg.modules.drag.service.IOnlDragPageService;
import org.jeecg.modules.jmreport.config.JmReportBaseConfig;
import org.jeecg.modules.jmreport.config.client.JmReportTokenClient;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController("onlDragPageController")
@RequestMapping({"/drag/page"})`
`PostMapping({"/add"})
    public Result<OnlDragPage> a(@RequestBody OnlDragPage var1, HttpServletRequest var2) {
        Result var3 = new Result();

        try {
            var3 = this.a(var2, var3);
            if (!var3.isSuccess()) {
                return var3;
            }

            String var4 = m.c(var2);
            String var5 = m.b(var2);
            if (StringUtils.isNotBlank(var4)) {
                var1.setLowAppId(var4);
            }

            if (StringUtils.isNotBlank(var5)) {
                var1.setTenantId(Integer.parseInt(var5));
            }`
经查是变量var5返回值为undefined 导致StringUtils.isNotBlank(var5) 这行代码报错
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
贴错误

**Comment by jeecgos** [comment]
sq

**Comment by zhangdaiscott** [comment]
无回复，关闭

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
