### ISSUE TITLE
积木报表预览希望可以支持居中显示，目前靠左展示

### ISSUE THREAD

**Issue by MrArlong** [jeecgboot/JimuReport#3140]
##### 版本号：
1.9.0

##### 问题描述：
希望预览页面可以居中显示报表

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/44d6712a-3735-4884-935d-6ec343ffb94c)

##### 重现步骤：
路由：jmreport/view/

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
暂不支持，归集：#138
