### ISSUE TITLE
报表在线设计，修改后无法保存，控制台报错

### ISSUE THREAD

**Issue by HHYYNN** [jeecgboot/JimuReport#3141]
##### 版本号：
JimuReport v1.9.0

##### 问题描述：
在线报表设计完成之后，点击【保存无反应】，控制台报错。

##### 错误日志&截图：
![222](https://github.com/user-attachments/assets/968355af-5cc2-47d9-9e47-a5671b0f9f3e)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
json冲突了吧

**Comment by zhangdaiscott** [comment]
那就是两边的版本不一致
