### ISSUE TITLE
1.9积木报表，设计报表后，编辑保存时报错

### ISSUE THREAD

**Issue by hujia1758** [jeecgboot/JimuReport#3142]
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/78cda4fb-db34-4670-b2eb-b9c7d423ab12)
![image](https://github.com/user-attachments/assets/93223d8f-d92d-434f-9c9a-da3666c8803e)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by hujia1758** [comment]
[合同报表2.json](https://github.com/user-attachments/files/17809553/2.json)

**Comment by jeecgos** [comment]
未复现，请在官网制作一个示例看下有没有问题？如果有问题提供一下id，我再帮您看下。
![QQ_1731995234322](https://github.com/user-attachments/assets/5b85a5ba-d272-4fbd-8993-0c3cd7bb833f)

> 我看到你的错误堆栈中有一个`CustomFastJsonHttpMessageConverter`，这个并不是积木报表的类，你可以检查下是不是这个类导致的报错？

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
