### ISSUE TITLE
积木报表是否支持 ES的数据源 

### ISSUE THREAD

**Issue by liuhao920708** [jeecgboot/JimuReport#3143]
##### 版本号：
jimureport-font 1.1.0

##### 问题描述：
积木报表 数据源维护中是否可以新增ES的数据源
##### 错误日志&截图：

![image](https://github.com/user-attachments/assets/a2cd3714-5b01-4f09-96b1-e101238e6fd0)

##### 重现步骤：
 新增数据源

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
目前不支持

**Comment by jeecgos** [comment]
已支持，需升级新版本
