### ISSUE TITLE
打印时，文本中的空格会被莫名替换掉

### ISSUE THREAD

**Issue by gouchanghong** [jeecgboot/JimuReport#3144]
##### 版本号：
1.9.0

##### 问题描述：
积木自己的预览页面，文本中还正常有空格，但是点击打印后，chrome的打印预览，以及真实打印出来的纸质文件，空格就没了。
并且，接口查询出来的数据中，是确定有空格的

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/b58655de-442b-4db6-a4aa-058605ca77ff)
![image](https://github.com/user-attachments/assets/90c9a18a-03b1-4132-8d00-116488ff21d0)
![image](https://github.com/user-attachments/assets/41037b03-ca59-44c7-8f8b-a31b5cc7a107)

##### 重现步骤：
已在官网制作了报表，以下链接可访问：
https://bootapi.jeecg.com/jmreport/view/1018380324939583488?tenantSid=1830504961629360129&applySid=1858322485873332226&userSid=1830508253952479233&userName=%E6%9C%BA%E6%9E%84%E7%AE%A1%E7%90%86%E5%91%98

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
收到

**Comment by jeecgDeveloper** [comment]
已修复，下一版本发布。
