### ISSUE TITLE
联查传递将主表参数传递到联查后明细表的参数

### ISSUE THREAD

**Issue by zwjsoft** [jeecgboot/JimuReport#3145]
##### 版本号：
1.9

##### 问题描述：
1、总表和明细表都有相关的参数，例如plan_date，能不能将总表查询参数plan_date传递到明细表上，目前测试联查传参的时候要么选字段或者自定义，字段里面没有对应字段，自定义可以写C行，B行等，都没有将总表参数传递到明细表上的方法，请问是否支持？，当然我将参数放到某一个单元格后，通过这个单元格是可以传递
2、通过单元格传递参数后，由于被联查的表上也有相关的参数，而且有默认值，发现不能将默认值覆盖掉;
3、联查后的报表必须点查询后才出数据，不能自动出数据

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/635e2f3f-fcf3-43f6-a9f9-f73a7dadac75)
![image](https://github.com/user-attachments/assets/0ce5db82-cdc9-47aa-8640-b1082bd454aa)
![image](https://github.com/user-attachments/assets/0e25d9ae-00e7-4616-b6b7-cd7c4510a519)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
1. 暂时不支持。
3 没有复现，你看下是不是钻取的报表没有勾选默认查询
![QQ_1732271155950](https://github.com/user-attachments/assets/d99e8362-4e95-44ca-8be3-14b826f08da1)

**Comment by jeecgos** [comment]
第二条，地址栏参数并不会覆盖查询控件的值。所以你看到的地址参数是15 但是查询条件时17 这个是没有问题的。
报表钻取针对你的场景有做特殊处理
- 被钻取的报表第一次查询时，查询的值会优先用地址参数，
- 第二次及以后会使用查询控件的值。

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
