### ISSUE TITLE
积木报表保存失败

### ISSUE THREAD

**Issue by QIANJIN0259** [jeecgboot/JimuReport#3146]
##### 版本号：

1.8.1
##### 问题描述：
积木报表保存失败，在创建时第一次保存可以保存成功，再编辑就不可以保存了。
sqlserver2014数据库，这个是怎么回事呢？

##### 错误日志&截图：
![微信图片_20241118172504](https://github.com/user-attachments/assets/3d378449-ce0e-4c0b-a769-1706f4985b9e)

![微信图片_20241118172511](https://github.com/user-attachments/assets/4d9f7e03-5b78-4aaf-8315-f3f16e8dac27)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
升级到最新版即可解决
