### ISSUE TITLE
ruoyiVue集成积木报表，在线填报报表token校验失败

### ISSUE THREAD

**Issue by elenJudy** [jeecgboot/JimuReport#3147]
##### 问题描述：
ruoyiVue集成积木报表，在线填报报表，填报完成后点击跳转详情或继续填报，地址添加token参数将空格（20%）改成了+（2B%）,导致token校验失败。

##### 错误日志&截图：
![2ehs1e0zw37gwmz6125ow3rzz_0](https://github.com/user-attachments/assets/8599ecf3-f766-4546-ab31-ea520a6962b0)
![1nzwfle597016wexwe4cdu463_0](https://github.com/user-attachments/assets/bbbdf829-9526-4041-9f48-e5e23faba913)

##### 重现步骤：
1.在线填报数据报表，提交；
2.选择跳转详情或继续填报。
（ruoyiVue集成积木报表）

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
cr

**Comment by jeecgDeveloper** [comment]
已修复，下一版本发布。
