### ISSUE TITLE
新仪表盘数据局表格分页-查询重置后，分页未重置

### ISSUE THREAD

**Issue by shiwuye888** [jeecgboot/JimuReport#3148]
##### 版本号：
        <dependency>
            <groupId>org.jeecgframework.jimureport</groupId>
            <artifactId>jimureport-dashboard-spring-boot-starter</artifactId>
            <version>1.9.0</version>
        </dependency>

##### 问题描述：
数据表格和查询条件组合后，给定查询条件，查询出来129条，重置查询条件查询没有结果但是分页总数和页码不正确，没有重置。

##### 错误日志&截图：

![image](https://github.com/user-attachments/assets/fd7ecd13-9a95-48ef-bdf9-2e62d60b8570)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
sq
