### ISSUE TITLE
积木报表中 查询控件下拉树的问题

### ISSUE THREAD

**Issue by liuhao920708** [jeecgboot/JimuReport#3149]
##### 版本号：

jimureport-font-1.1.0.jar
##### 问题描述：
https://ojrjjvdr7z.k.topthink.com/jimureport/query/dropdownTree.html#1%E6%95%B0%E6%8D%AE%E6%BA%90%E9%85%8D%E7%BD%AE-1
查询控件下拉树 
![image](https://github.com/user-attachments/assets/03ad12ac-5306-4a65-80d1-731d33ebbdf1)
这个格式输出 并不能正确的展开 这块有最新的结构吗

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/01d215d5-e3ba-4f26-b982-7a78efaf7723)
![Uploading image.png…]()

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
cr

**Comment by BO-DI** [comment]
您这个解决了吗，我的下拉树也是这种情况，详情看[BUG#3167](https://github.com/jeecgboot/JimuReport/issues/3167)

**Comment by jeecgos** [comment]
@liuhao920708 经验证，下拉树是没问题的。
![QQ_1732502111443](https://github.com/user-attachments/assets/d727dee8-52a8-4450-8787-c18da0927ba5)

从你的截图来看，应该是你的`loadTree `接口没有根据pid进行数据过滤。

> 参考代码：
> ![QQ_1732502274874](https://github.com/user-attachments/assets/b468b44f-ac24-417c-94a1-211383d68c7f)
> 返回值是一个一维数组，每次查询返回一层的数据
> [{
    "title": "一级菜单",
    "value": "A01",
    "pid": "0",
    "id": "1537703191145512962"
}]

**Comment by BO-DI** [comment]
该下拉树必须按照上述格式进行吗，我得格式是这样得。
![image](https://github.com/user-attachments/assets/d7c9af19-6de4-4f58-b9c9-3bf561480bab)

**Comment by jeecgos** [comment]
> 该下拉树必须按照上述格式进行吗，我得格式是这样得。 ![image](https://private-user-images.githubusercontent.com/53505854/393125711-d7c9af19-6de4-4f58-b9c9-3bf561480bab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0Njg0NjQsIm5iZiI6MTczMzQ2ODE2NCwicGF0aCI6Ii81MzUwNTg1NC8zOTMxMjU3MTEtZDdjOWFmMTktNmRlNC00ZjU4LWI5YzktM2JmNTYxNDgwYmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA2NTYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMjIwZjMxMzYyMTRlMWM0YTExMTcwOWQ1NTUwN2JhNGNmNTdjNGE1YjQ5N2Q2YTY1YjAyZmEyNjJiYjhiZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NcUQVRcJzQ0-UvC9RW9CR0UlaDUfmjVFFou0Y6EglsM)

同 #3167

**Comment by BO-DI** [comment]
后续针对下拉树会放开结构格式吗，这样的话限制的太多了。因为有可能是公共方法，为了共用所以比较复杂。&nbsp;


左手年华
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月6日(星期五) 下午2:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/JimuReport] 积木报表中 查询控件下拉树的问题 (Issue #3149)














  
该下拉树必须按照上述格式进行吗，我得格式是这样得。 
  
同 #3167

**Comment by jeecgos** [comment]
需求：【自定义下拉树属性字段】，归集：#138。

**Comment by BO-DI** [comment]
请问，这种下拉树，明明是最后一级为啥还有下一级层级图标，有办法解决吗？
![下拉树查询问题](https://github.com/user-attachments/assets/11d51c6c-2c0b-457e-876a-a07e631ef1c6)

**Comment by jeecgos** [comment]
> 请问，这种下拉树，明明是最后一级为啥还有下一级层级图标，有办法解决吗？ ![下拉树查询问题](https://private-user-images.githubusercontent.com/53505854/393170006-11d51c6c-2c0b-457e-876a-a07e631ef1c6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzY1MjksIm5iZiI6MTczMzQ3NjIyOSwicGF0aCI6Ii81MzUwNTg1NC8zOTMxNzAwMDYtMTFkNTFjNmMtMmMwYi00NTdlLTg3NmEtYTA3ZTYzMWVmMWM2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA5MTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMDMwZWFkODE4YjdlOTVhYjExNGEyZGI1NTU4MmJlNzExOWU0MDBkYTQ5ZWFjNWVhYjExYWNiOTk1NThhZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f7H-h6UM_522Ff1WjjNK5F028BrQOSumOx3b1nFW9Y0) [ ![下拉树查询问题](https://private-user-images.githubusercontent.com/53505854/393170006-11d51c6c-2c0b-457e-876a-a07e631ef1c6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzY1MjksIm5iZiI6MTczMzQ3NjIyOSwicGF0aCI6Ii81MzUwNTg1NC8zOTMxNzAwMDYtMTFkNTFjNmMtMmMwYi00NTdlLTg3NmEtYTA3ZTYzMWVmMWM2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA5MTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMDMwZWFkODE4YjdlOTVhYjExNGEyZGI1NTU4MmJlNzExOWU0MDBkYTQ5ZWFjNWVhYjExYWNiOTk1NThhZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f7H-h6UM_522Ff1WjjNK5F028BrQOSumOx3b1nFW9Y0) ](https://private-user-images.githubusercontent.com/53505854/393170006-11d51c6c-2c0b-457e-876a-a07e631ef1c6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzY1MjksIm5iZiI6MTczMzQ3NjIyOSwicGF0aCI6Ii81MzUwNTg1NC8zOTMxNzAwMDYtMTFkNTFjNmMtMmMwYi00NTdlLTg3NmEtYTA3ZTYzMWVmMWM2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA5MTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMDMwZWFkODE4YjdlOTVhYjExNGEyZGI1NTU4MmJlNzExOWU0MDBkYTQ5ZWFjNWVhYjExYWNiOTk1NThhZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f7H-h6UM_522Ff1WjjNK5F028BrQOSumOx3b1nFW9Y0) [ ](https://private-user-images.githubusercontent.com/53505854/393170006-11d51c6c-2c0b-457e-876a-a07e631ef1c6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzY1MjksIm5iZiI6MTczMzQ3NjIyOSwicGF0aCI6Ii81MzUwNTg1NC8zOTMxNzAwMDYtMTFkNTFjNmMtMmMwYi00NTdlLTg3NmEtYTA3ZTYzMWVmMWM2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA5MTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMDMwZWFkODE4YjdlOTVhYjExNGEyZGI1NTU4MmJlNzExOWU0MDBkYTQ5ZWFjNWVhYjExYWNiOTk1NThhZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f7H-h6UM_522Ff1WjjNK5F028BrQOSumOx3b1nFW9Y0)

目前不行

**Comment by BO-DI** [comment]
> > 请问，这种下拉树，明明是最后一级为啥还有下一级层级图标，有办法解决吗？ ![下拉树查询问题](https://private-user-images.githubusercontent.com/53505854/393170006-11d51c6c-2c0b-457e-876a-a07e631ef1c6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzY1MjksIm5iZiI6MTczMzQ3NjIyOSwicGF0aCI6Ii81MzUwNTg1NC8zOTMxNzAwMDYtMTFkNTFjNmMtMmMwYi00NTdlLTg3NmEtYTA3ZTYzMWVmMWM2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA5MTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMDMwZWFkODE4YjdlOTVhYjExNGEyZGI1NTU4MmJlNzExOWU0MDBkYTQ5ZWFjNWVhYjExYWNiOTk1NThhZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f7H-h6UM_522Ff1WjjNK5F028BrQOSumOx3b1nFW9Y0)
> >       
> >         [
> >           
> >             ![下拉树查询问题](https://private-user-images.githubusercontent.com/53505854/393170006-11d51c6c-2c0b-457e-876a-a07e631ef1c6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzY1MjksIm5iZiI6MTczMzQ3NjIyOSwicGF0aCI6Ii81MzUwNTg1NC8zOTMxNzAwMDYtMTFkNTFjNmMtMmMwYi00NTdlLTg3NmEtYTA3ZTYzMWVmMWM2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA5MTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMDMwZWFkODE4YjdlOTVhYjExNGEyZGI1NTU4MmJlNzExOWU0MDBkYTQ5ZWFjNWVhYjExYWNiOTk1NThhZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f7H-h6UM_522Ff1WjjNK5F028BrQOSumOx3b1nFW9Y0)
> >           
> >         ](https://private-user-images.githubusercontent.com/53505854/393170006-11d51c6c-2c0b-457e-876a-a07e631ef1c6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzY1MjksIm5iZiI6MTczMzQ3NjIyOSwicGF0aCI6Ii81MzUwNTg1NC8zOTMxNzAwMDYtMTFkNTFjNmMtMmMwYi00NTdlLTg3NmEtYTA3ZTYzMWVmMWM2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA5MTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMDMwZWFkODE4YjdlOTVhYjExNGEyZGI1NTU4MmJlNzExOWU0MDBkYTQ5ZWFjNWVhYjExYWNiOTk1NThhZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f7H-h6UM_522Ff1WjjNK5F028BrQOSumOx3b1nFW9Y0)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/53505854/393170006-11d51c6c-2c0b-457e-876a-a07e631ef1c6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzY1MjksIm5iZiI6MTczMzQ3NjIyOSwicGF0aCI6Ii81MzUwNTg1NC8zOTMxNzAwMDYtMTFkNTFjNmMtMmMwYi00NTdlLTg3NmEtYTA3ZTYzMWVmMWM2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA5MTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMDMwZWFkODE4YjdlOTVhYjExNGEyZGI1NTU4MmJlNzExOWU0MDBkYTQ5ZWFjNWVhYjExYWNiOTk1NThhZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f7H-h6UM_522Ff1WjjNK5F028BrQOSumOx3b1nFW9Y0)
> >         
> >        [ ![下拉树查询问题](https://private-user-images.githubusercontent.com/53505854/393170006-11d51c6c-2c0b-457e-876a-a07e631ef1c6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzY1MjksIm5iZiI6MTczMzQ3NjIyOSwicGF0aCI6Ii81MzUwNTg1NC8zOTMxNzAwMDYtMTFkNTFjNmMtMmMwYi00NTdlLTg3NmEtYTA3ZTYzMWVmMWM2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA5MTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMDMwZWFkODE4YjdlOTVhYjExNGEyZGI1NTU4MmJlNzExOWU0MDBkYTQ5ZWFjNWVhYjExYWNiOTk1NThhZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f7H-h6UM_522Ff1WjjNK5F028BrQOSumOx3b1nFW9Y0) ](https://private-user-images.githubusercontent.com/53505854/393170006-11d51c6c-2c0b-457e-876a-a07e631ef1c6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzY1MjksIm5iZiI6MTczMzQ3NjIyOSwicGF0aCI6Ii81MzUwNTg1NC8zOTMxNzAwMDYtMTFkNTFjNmMtMmMwYi00NTdlLTg3NmEtYTA3ZTYzMWVmMWM2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA5MTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMDMwZWFkODE4YjdlOTVhYjExNGEyZGI1NTU4MmJlNzExOWU0MDBkYTQ5ZWFjNWVhYjExYWNiOTk1NThhZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f7H-h6UM_522Ff1WjjNK5F028BrQOSumOx3b1nFW9Y0)
> >       
> >         [
> >           
> >             ![下拉树查询问题](https://private-user-images.githubusercontent.com/53505854/393170006-11d51c6c-2c0b-457e-876a-a07e631ef1c6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzY1MjksIm5iZiI6MTczMzQ3NjIyOSwicGF0aCI6Ii81MzUwNTg1NC8zOTMxNzAwMDYtMTFkNTFjNmMtMmMwYi00NTdlLTg3NmEtYTA3ZTYzMWVmMWM2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA5MTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMDMwZWFkODE4YjdlOTVhYjExNGEyZGI1NTU4MmJlNzExOWU0MDBkYTQ5ZWFjNWVhYjExYWNiOTk1NThhZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f7H-h6UM_522Ff1WjjNK5F028BrQOSumOx3b1nFW9Y0)
> >           
> >         ](https://private-user-images.githubusercontent.com/53505854/393170006-11d51c6c-2c0b-457e-876a-a07e631ef1c6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzY1MjksIm5iZiI6MTczMzQ3NjIyOSwicGF0aCI6Ii81MzUwNTg1NC8zOTMxNzAwMDYtMTFkNTFjNmMtMmMwYi00NTdlLTg3NmEtYTA3ZTYzMWVmMWM2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA5MTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMDMwZWFkODE4YjdlOTVhYjExNGEyZGI1NTU4MmJlNzExOWU0MDBkYTQ5ZWFjNWVhYjExYWNiOTk1NThhZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f7H-h6UM_522Ff1WjjNK5F028BrQOSumOx3b1nFW9Y0)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/53505854/393170006-11d51c6c-2c0b-457e-876a-a07e631ef1c6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzY1MjksIm5iZiI6MTczMzQ3NjIyOSwicGF0aCI6Ii81MzUwNTg1NC8zOTMxNzAwMDYtMTFkNTFjNmMtMmMwYi00NTdlLTg3NmEtYTA3ZTYzMWVmMWM2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA5MTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMDMwZWFkODE4YjdlOTVhYjExNGEyZGI1NTU4MmJlNzExOWU0MDBkYTQ5ZWFjNWVhYjExYWNiOTk1NThhZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f7H-h6UM_522Ff1WjjNK5F028BrQOSumOx3b1nFW9Y0)
> >         
> >        [ ](https://private-user-images.githubusercontent.com/53505854/393170006-11d51c6c-2c0b-457e-876a-a07e631ef1c6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzY1MjksIm5iZiI6MTczMzQ3NjIyOSwicGF0aCI6Ii81MzUwNTg1NC8zOTMxNzAwMDYtMTFkNTFjNmMtMmMwYi00NTdlLTg3NmEtYTA3ZTYzMWVmMWM2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA5MTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMDMwZWFkODE4YjdlOTVhYjExNGEyZGI1NTU4MmJlNzExOWU0MDBkYTQ5ZWFjNWVhYjExYWNiOTk1NThhZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f7H-h6UM_522Ff1WjjNK5F028BrQOSumOx3b1nFW9Y0)
> 
> 目前不行

单选有戏吗，我看咋还有复选框。
