### ISSUE TITLE
积木设计器中，点击一些功能提示需要升级企业版本，如何做到？

### ISSUE THREAD

**Issue by 13851656591** [jeecgboot/JimuReport#3151]
##### 版本号：
version 2

##### 问题描述：
积木设计器中，点击一些功能提示需要升级企业版本，如何做到？
例如冻结按钮，我看免费版本中说明了有冻结功能，但是现在无法使用
![screenshot_2024-11-20_14-12-19](https://github.com/user-attachments/assets/b328b85c-19a4-4d34-83de-59ea10f28053)

**Comment by zhangdaiscott** [comment]
http://jimureport.com/vip
