### ISSUE TITLE
请问一下，图片展示支持本地绝对路径吗

### ISSUE THREAD

**Issue by 1095321607** [jeecgboot/JimuReport#3156]
##### 版本号：
1.8.1

##### 问题描述：
请问一下，图片展示支持本地绝对路径吗，我使用本地路径的时候解析不出来，使用https的网络图片是可以解析的

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持
