### ISSUE TITLE
多选下拉，去掉一个选项后，结果整个条件都没有了

### ISSUE THREAD

**Issue by zwjsoft** [jeecgboot/JimuReport#3157]
##### 版本号：
1.9

##### 问题描述：
有一个多选下拉，选择了几个项目后查询，数据正确，然后去掉其中一个选项后再查询，发现结果反而变多了，研究发现，这个条件已经不生效了。但是如果把整个下拉都清出掉，然后重新选一遍，是不会有问题的。

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/5a38c23b-8fac-46a7-9cb0-0fb2de9c26bb)
![image](https://github.com/user-attachments/assets/b6f28182-0c82-4285-8c98-9a3e2499deed)

![image](https://github.com/user-attachments/assets/e32d5560-c06b-430b-9941-0df392a0446c)

所以造成查询结果变多了，因为这个过滤条件整个没了!如果用上面的×把整个条件都清掉，重选没问题。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
ws

**Comment by jeecgos** [comment]
已修复，待新版本发布
