### ISSUE TITLE
部署到linux后，启动正常，访问页面/jmreport/list报错，提示java.lang.NoClassDefFoundError: freemarker/template/Configuration

### ISSUE THREAD

**Issue by dongping8887** [jeecgboot/JimuReport#3158]
##### 版本号：
1.9.0

##### 问题描述：
部署到linux后，启动正常，访问页面/jmreport/list报错，提示java.lang.NoClassDefFoundError: freemarker/template/Configuration

##### 错误日志&截图：
<img width="1070" alt="image" src="https://github.com/user-attachments/assets/9148439b-dd0a-4edb-a595-be291c020385">

##### 重现步骤：
部署到linux后，访问页面/jmreport/list。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
你打包一个DEMO项目部署上去看看有没有这个问题？

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
