### ISSUE TITLE
集成仪表盘后，啥都没干，就报超出限制

### ISSUE THREAD

**Issue by xyaix** [jeecgboot/JimuReport#3160]
##### 版本号：
1.9.0

##### 问题描述：
使用ruoyi-vue框架集成仪表盘，访问后，想新增一个，或者访问默认的模板，都提示超出限制

##### 错误日志&截图：
![微信截图_20241121151135](https://github.com/user-attachments/assets/dec2bec0-387b-41ba-b1a6-745e275ac5c3)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by xyaix** [comment]
![微信截图_20241121151202](https://github.com/user-attachments/assets/2e6f173e-f5af-46ae-a165-ce538df9aa7a)
集成后啥都没做，就成这样了

**Comment by zhangdaiscott** [comment]
数据库表数量多少

**Comment by xyaix** [comment]
> 数据库表数量多少

确实是数据库表超了，感谢！
