### ISSUE TITLE
我想在系统中通过接口下载报表模板附件，Excel或者PDF格式都可以，请问提供的有没有这样的接口

### ISSUE THREAD

**Issue by modidady** [jeecgboot/JimuReport#3161]
##### 版本号：
哪个版本都可以

在系统中通过接口下载报表模板附件，Excel或者PDF格式都可以

##### 错误日志&截图：
无

##### 重现步骤：
无

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
没有

**Comment by jeecgos** [comment]
参考文档：https://help.jeecg.com/jimureport/exportapi.html
