### ISSUE TITLE
字典code中直接输入sql语句时不能通过${} 获取url传参

### ISSUE THREAD

**Issue by Williams0818** [jeecgboot/JimuReport#3162]
##### 版本号：
v1.65

##### 问题描述：
字典code中直接输入sql语句时不能通过${} 获取url传参

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/8d7af8a9-d613-4e9f-9023-7d94fb7c57c0)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
暂不支持，归集：#138
