### ISSUE TITLE
sql自动解析会出现重复数据

### ISSUE THREAD

**Issue by Williams0818** [jeecgboot/JimuReport#3163]
##### 版本号：
v1.6.5

##### 问题描述：
![image](https://github.com/user-attachments/assets/c23e3869-e5d8-4354-b29c-c7992f4f54df)
![ed0d026915a5524f6c4087706632aad2](https://github.com/user-attachments/assets/7640e2b6-8176-4ead-91ed-8f2ea85e9d35)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
升级到最新版 ，好像解决过

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
