### ISSUE TITLE
仪表盘设计中的图表显示中为什么表格显示是空的，图表中有数据

### ISSUE THREAD

**Issue by feilx2224** [jeecgboot/JimuReport#3166]
##### 版本号：

1.8.1
##### 问题描述：
仪表盘设计中的图表显示中为什么表格显示是空的，图表中有数据

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/576b71f4-63c1-4085-9618-59dd3609c817)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
sq

**Comment by feilx2224** [comment]
> sq

什么意思

**Comment by jeecgDeveloper** [comment]
请描述一下你的图表数据配置方式和使用方式，复现步骤

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
