### ISSUE TITLE
API数据源里得查询下拉树参数配置问题

### ISSUE THREAD

**Issue by BO-DI** [jeecgboot/JimuReport#3167]
##### 版本号：
1.9.0

##### 问题描述：
本地按照官方给定格式配置了，但是没有返回相应json数据。

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/a040be69-b70f-4a1c-81fd-d92d903ba096)
![image](https://github.com/user-attachments/assets/6e7037e7-8225-4838-b8a3-cf4b45ead3dc)
![查询下拉树参数配置截图](https://github.com/user-attachments/assets/8c886110-ffdf-4c6c-b956-8283ef040cfa)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
ws

**Comment by BO-DI** [comment]
是因为返回格式不严谨，还是什么呢？

**Comment by jeecgos** [comment]
目前请求方式只支持get请求，文档已更新

**Comment by jeecgos** [comment]
目前请求方式只支持get请求，文档已更新
![image](https://github.com/user-attachments/assets/ab2ff01c-1716-48c7-9da4-ef58542ff525)

**Comment by BO-DI** [comment]
什么时候支持post请求及相关格式的输出呢，目前的话，查询项参数配置的输出范围太窄了。

**Comment by BO-DI** [comment]
![image](https://github.com/user-attachments/assets/a3848a0a-b58c-4414-8093-d1d8897b1f2c)
![image](https://github.com/user-attachments/assets/91eaaac4-ea31-4839-9215-7e9656b82da8)
下拉树我也支持get请求了，但是还没出来。

**Comment by jeecgos** [comment]
请严格参照文档要求提供接口，不要自己造结构，你的返回结构和系统要求不一样当然显示不出来。
![QQ_1733468021946](https://github.com/user-attachments/assets/c3cb5166-725f-4b28-8628-cf374df73dbf)

参考文档：https://help.jeecg.com/jimureport/query/dropdownTree.html
