### ISSUE TITLE
API数据源中的查询下拉树的参数配置问题

### ISSUE THREAD

**Issue by BO-DI** [jeecgboot/JimuReport#3169]
##### 版本号：
1.9.0

##### 问题描述：
本地按照官方给定格式配置了，但是没有返回相应json数据。

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/a040be69-b70f-4a1c-81fd-d92d903ba096)
![image](https://github.com/user-attachments/assets/6e7037e7-8225-4838-b8a3-cf4b45ead3dc)
![查询下拉树参数配置截图](https://github.com/user-attachments/assets/8c886110-ffdf-4c6c-b956-8283ef040cfa)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
重复 #3167
