### ISSUE TITLE
预览排版异常问题，会多出空行

### ISSUE THREAD

**Issue by laifu901** [jeecgboot/JimuReport#317]
##### 截图&代码：
![QQ图片20210610103613](https://user-images.githubusercontent.com/39521412/121456363-88318e00-c9d8-11eb-9521-65a50c7d7285.png)
![QQ图片20210610103441](https://user-images.githubusercontent.com/39521412/121456370-8cf64200-c9d8-11eb-8c5d-650b80645199.png)
![QQ图片20210610103336](https://user-images.githubusercontent.com/39521412/121456382-9089c900-c9d8-11eb-99f9-c34fbaec2baa.png)
![QQ图片20210610104438](https://user-images.githubusercontent.com/39521412/121456580-e1012680-c9d8-11eb-8048-7e09edf6627b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 yf

**Comment by tygithub1** [comment]
设计规则是： 如果只有一条数据请在配置数据集的时候 取消勾选 `是否列表` 那么在表格中可以使用$表达式 ，使用word排版。如果有多条数据，只能在一行处理，其余排版不支持。

**Comment by laifu901** [comment]
> 设计规则是： 如果只有一条数据请在配置数据集的时候 取消勾选 `是否列表` 那么在表格中可以使用$表达式 ，使用word排版。如果有多条数据，只能在一行处理，其余排版不支持。

我理解你的意思，我这个是这种情况，是多条数据但是由于打印宽度的限制无法在一行展示完所有字段，只能弄成多行进行循环多行打印。如果只支持一行到打印线那能自动换行也行。实时是支持循环多行，单有时候排版会堆叠到一起或者打印有空行。

**Comment by tygithub1** [comment]
循环块支持 但是要全部圈起来  不能只循环部分 ，看我这个：
![image](https://user-images.githubusercontent.com/27989856/121667477-e6479980-cadc-11eb-857c-0f08224233e0.png)
![image](https://user-images.githubusercontent.com/27989856/121667555-ff504a80-cadc-11eb-9318-6a05e9c681ea.png)

**Comment by laifu901** [comment]
> 循环块支持 但是要全部圈起来 不能只循环部分 ，看我这个：
> ![image](https://user-images.githubusercontent.com/27989856/121667477-e6479980-cadc-11eb-857c-0f08224233e0.png)
> ![image](https://user-images.githubusercontent.com/27989856/121667555-ff504a80-cadc-11eb-9318-6a05e9c681ea.png)



> 循环块支持 但是要全部圈起来 不能只循环部分 ，看我这个：
> ![image](https://user-images.githubusercontent.com/27989856/121667477-e6479980-cadc-11eb-857c-0f08224233e0.png)
> ![image](https://user-images.githubusercontent.com/27989856/121667555-ff504a80-cadc-11eb-9318-6a05e9c681ea.png)

嗯，你这个数据内容可能没那么多，如果循环多列或者把行间距拉大就会出现我那种情况，好像第一页没问题，我做了14个表单，每个表单都有三页数据，第二页那块排版基本每个都有问题，要么出现空行或者循环多行会堆叠在一起，在设计的时候没有，在预览打印或者导出的时候就会出现。

**Comment by ProfGuo** [comment]
![image](https://user-images.githubusercontent.com/82938590/123744060-ca1b6900-d8e0-11eb-99af-bdd7d3d47a7d.png)

**Comment by ProfGuo** [comment]
报表预览 也会有乱序
