### ISSUE TITLE
【紧急】升级1.8.1版本后，小计及数据合计部分的展示方式和统计数据发生变化

### ISSUE THREAD

**Issue by xiaoyatousuju** [jeecgboot/JimuReport#3170]
##### 错误日志&截图：
1.6.4版本的数据小计及合计业务
![image](https://github.com/user-attachments/assets/05aaf0f8-6822-4bd7-9a9a-b0d4d2eeed88)

1.8.1版本的数据消息及合计业务

![image](https://github.com/user-attachments/assets/3107aa73-0723-430c-8f68-6ba89afe5d0a)

这个严重影响了数据的准确性，真实性啊，怎么会出现这么严重的bug呢？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
遇到问题先升级到最新版，中间版本无法提供支持

**Comment by xiaoyatousuju** [comment]
> 遇到问题先升级到最新版，中间版本无法提供支持

新版本也是一样的问题

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by xiaoyatousuju** [comment]
> 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

{"loopBlockList":[],"printConfig":{"layout":"portrait","paginationShow":false,"printCallBackUrl":"","paper":"A4","isBackend":false,"width":210,"paginationLocation":"middle","definition":1,"marginX":7,"height":297,"marginY":7},"hidden":{"rows":[],"cols":[]},"dbexps":[],"dicts":[],"freeze":"A1","dataRectWidth":833,"autofilter":{},"validations":[],"cols":{"0":{"width":12},"1":{"width":113},"2":{"width":85},"3":{"width":100},"4":{"width":66},"5":{"width":81},"6":{"width":76},"7":{"width":59},"8":{"width":69},"9":{"width":72},"len":50},"area":{"sri":5,"sci":10,"eri":5,"eci":10,"width":100,"height":25},"pyGroupEngine":false,"excel_config_id":"937604239145676800","hiddenCells":[],"zonedEditionList":[],"rows":{"0":{"cells":{"1":{"style":13,"text":" "},"2":{"merge":[1,5],"style":17,"text":"操作员每日汇总统计报表","height":50},"8":{"style":13,"text":" "},"9":{"style":13,"text":" "}}},"1":{"cells":{"1":{"style":13,"text":" "},"8":{"style":13,"text":" "},"9":{"style":13,"text":" "}}},"2":{"cells":{"1":{"style":13,"text":" "},"2":{"merge":[0,5],"style":48,"text":"#{hnkjdxccdd.查询时间}","height":25},"3":{},"4":{},"5":{},"6":{},"7":{},"8":{"style":13,"text":" "},"9":{"style":13,"text":" "}}},"3":{"cells":{"1":{"style":50,"text":" "},"2":{"style":50,"text":" "},"3":{"style":50,"text":" "},"4":{"style":50,"text":" "},"5":{"style":50,"text":" "},"6":{"style":50,"text":" "},"7":{"style":50,"text":" "},"8":{"merge":[0,1],"style":14,"text":"货币单位：元","height":25}}},"4":{"cells":{"1":{"style":42,"text":"操作员"},"2":{"style":42,"text":"交易时间"},"3":{"style":42,"text":"交易事件"},"4":{"style":42,"text":"交易次数"},"5":{"style":42,"text":"交易金额"},"6":{"style":42,"text":"成本费"},"7":{"style":42,"text":"押金"},"8":{"style":42,"text":"现金"},"9":{"style":42,"text":"非现金"}}},"5":{"cells":{"1":{"funcname":"-1","subtotal":"groupField","style":43,"text":"#{hnkjdxccd.group(操作员)}","aggregate":"group"},"2":{"funcname":"-1","subtotal":"groupField","style":43,"text":"#{hnkjdxccd.group(交易时间)}","aggregate":"group"},"3":{"style":43,"text":"#{hnkjdxccd.交易事件}"},"4":{"funcname":"SUM","subtotal":"-1","style":43,"text":"#{hnkjdxccd.交易次数}"},"5":{"funcname":"SUM","decimalPlaces":"2","subtotal":"-1","style":49,"text":"#{hnkjdxccd.交易金额}"},"6":{"funcname":"SUM","decimalPlaces":"2","subtotal":"-1","style":49,"text":"#{hnkjdxccd.成本费}"},"7":{"funcname":"SUM","decimalPlaces":"2","subtotal":"-1","style":49,"text":"#{hnkjdxccd.押金}"},"8":{"funcname":"SUM","decimalPlaces":"2","subtotal":"-1","style":49,"text":"#{hnkjdxccd.现金}"},"9":{"funcname":"SUM","decimalPlaces":"2","subtotal":"-1","style":49,"text":"#{hnkjdxccd.非现金}"},"10":{"text":""}}},"6":{"cells":{"1":{"style":13,"text":" "},"2":{"style":13,"text":" "},"3":{"style":13,"text":" "},"4":{"style":13,"text":" "},"5":{"style":13,"text":" "},"6":{"style":13,"text":" "},"7":{"style":13,"text":" "},"8":{"style":13,"text":" "},"9":{"style":13,"text":" "}},"height":10},"7":{"cells":{"1":{"merge":[0,3],"style":13,"text":"使用单位：#{hnkjdxccdd.机构}","height":25},"5":{"style":13,"text":" "},"6":{"merge":[0,3],"style":13,"text":"打印时间：#{hnkjdxccdd.打印时间}","height":25}}},"8":{"cells":{"1":{"merge":[0,3],"style":13,"text":"操作员：#{hnkjdxccdd.操作人}","height":25},"5":{"style":13,"text":" "},"6":{"merge":[0,3],"style":13,"text":"#{hnkjdxccdd.负责人}","height":25}}},"9":{"cells":{"1":{"merge":[0,3],"style":13,"text":"#{hnkjdxccdd.审核人}","height":25},"5":{"style":13,"text":" "},"6":{"merge":[0,3],"style":13,"text":"#{hnkjdxccdd.制表人}","height":25}}},"10":{"cells":{"1":{"style":11,"text":" "},"2":{"style":11,"text":" "},"3":{"style":11,"text":" "},"4":{"style":11,"text":" "},"5":{"style":11,"text":" "},"6":{"style":11,"text":" "},"7":{"style":11,"text":" "},"8":{"style":11,"text":" "},"9":{"style":11,"text":" "}}},"11":{"cells":{"1":{"style":11,"text":" "},"2":{"style":11,"text":" "},"3":{"style":11,"text":" "},"4":{"style":11,"text":" "},"5":{"style":11,"text":" "},"6":{"style":11,"text":" "},"7":{"style":11,"text":" "},"8":{"style":11,"text":" "},"9":{"style":11,"text":" "}}},"12":{"cells":{"1":{"style":11,"text":" "},"2":{"style":11,"text":" "},"3":{"style":11,"text":" "},"4":{"style":11,"text":" "},"5":{"style":11,"text":" "},"6":{"style":11,"text":" "},"7":{"style":11,"text":" "},"8":{"style":11,"text":" "},"9":{"style":11,"text":" "}}},"13":{"cells":{"1":{"style":11,"text":" "},"2":{"style":11,"text":" "},"3":{"style":11,"text":" "},"4":{"style":11,"text":" "},"5":{"style":11,"text":" "},"6":{"style":11,"text":" "},"7":{"style":11,"text":" "},"8":{"style":11,"text":" "},"9":{"style":11,"text":" "}}},"len":98},"rpbar":{"show":true,"pageSize":"","btnList":[]},"groupField":"hnkjdxccd.操作员","fixedPrintHeadRows":[],"fixedPrintTailRows":[],"displayConfig":{},"background":false,"name":"sheet1","styles":[{"align":"center"},{"color":"#3"},{"color":"#3","align":"center"},{"color":"#33"},{"color":"#33","align":"center"},{"color":"#333"},{"color":"#333","align":"center"},{"color":"#3333"},{"color":"#3333","align":"center"},{"color":"#33339"},{"color":"#33339","align":"center"},{"color":"#333399"},{"color":"#333399","align":"center"},{"color":"#333399","font":{"name":"宋体"}},{"color":"#333399","align":"center","font":{"name":"宋体"}},{"color":"#333399","align":"center","font":{"size":16,"name":"宋体"}},{"color":"#333399","font":{"size":16,"name":"宋体"}},{"color":"#333399","align":"center","font":{"size":16,"name":"宋体","bold":true}},{"color":"#333399","font":{"size":16,"name":"宋体","bold":true}},{"border":{"top":["thin","#"],"left":["thin","#"],"bottom":["thin","#"],"right":["thin","#"]},"color":"#333399","align":"center","font":{"size":16,"name":"宋体","bold":true}},{"border":{"top":["thin","#3"],"left":["thin","#3"],"bottom":["thin","#3"],"right":["thin","#3"]},"color":"#333399","align":"center","font":{"size":16,"name":"宋体","bold":true}},{"border":{"top":["thin","#33"],"left":["thin","#33"],"bottom":["thin","#33"],"right":["thin","#33"]},"color":"#333399","align":"center","font":{"size":16,"name":"宋体","bold":true}},{"border":{"top":["thin","#333"],"left":["thin","#333"],"bottom":["thin","#333"],"right":["thin","#333"]},"color":"#333399","align":"center","font":{"size":16,"name":"宋体","bold":true}},{"border":{"top":["thin","#3333"],"left":["thin","#3333"],"bottom":["thin","#3333"],"right":["thin","#3333"]},"color":"#333399","align":"center","font":{"size":16,"name":"宋体","bold":true}},{"border":{"top":["thin","#33339"],"left":["thin","#33339"],"bottom":["thin","#33339"],"right":["thin","#33339"]},"color":"#333399","align":"center","font":{"size":16,"name":"宋体","bold":true}},{"border":{"top":["thin","#333399"],"left":["thin","#333399"],"bottom":["thin","#333399"],"right":["thin","#333399"]},"color":"#333399","align":"center","font":{"size":16,"name":"宋体","bold":true}},{"border":{"bottom":["thin","#333399"]},"color":"#333399","font":{"size":16,"name":"宋体","bold":true}},{"color":"#333399","align":"center","font":{"name":"宋体","bold":true}},{"border":{"top":["thin","#000"],"left":["thin","#000"],"bottom":["thin","#000"],"right":["thin","#000"]},"color":"#333399","align":"center","font":{"name":"宋体","bold":true}},{"border":{"top":["thin","#000"],"left":["thin","#000"],"bottom":["thin","#000"],"right":["thin","#000"]},"color":"#333399","font":{"name":"宋体"}},{"border":{"top":["thin","#"],"left":["thin","#"],"bottom":["thin","#"],"right":["thin","#"]},"color":"#333399","align":"center","font":{"name":"宋体","bold":true}},{"border":{"top":["thin","#"],"left":["thin","#"],"bottom":["thin","#"],"right":["thin","#"]},"color":"#333399","font":{"name":"宋体"}},{"border":{"top":["thin","#3"],"left":["thin","#3"],"bottom":["thin","#3"],"right":["thin","#3"]},"color":"#333399","align":"center","font":{"name":"宋体","bold":true}},{"border":{"top":["thin","#3"],"left":["thin","#3"],"bottom":["thin","#3"],"right":["thin","#3"]},"color":"#333399","font":{"name":"宋体"}},{"border":{"top":["thin","#33"],"left":["thin","#33"],"bottom":["thin","#33"],"right":["thin","#33"]},"color":"#333399","align":"center","font":{"name":"宋体","bold":true}},{"border":{"top":["thin","#33"],"left":["thin","#33"],"bottom":["thin","#33"],"right":["thin","#33"]},"color":"#333399","font":{"name":"宋体"}},{"border":{"top":["thin","#333"],"left":["thin","#333"],"bottom":["thin","#333"],"right":["thin","#333"]},"color":"#333399","align":"center","font":{"name":"宋体","bold":true}},{"border":{"top":["thin","#333"],"left":["thin","#333"],"bottom":["thin","#333"],"right":["thin","#333"]},"color":"#333399","font":{"name":"宋体"}},{"border":{"top":["thin","#3333"],"left":["thin","#3333"],"bottom":["thin","#3333"],"right":["thin","#3333"]},"color":"#333399","align":"center","font":{"name":"宋体","bold":true}},{"border":{"top":["thin","#3333"],"left":["thin","#3333"],"bottom":["thin","#3333"],"right":["thin","#3333"]},"color":"#333399","font":{"name":"宋体"}},{"border":{"top":["thin","#33339"],"left":["thin","#33339"],"bottom":["thin","#33339"],"right":["thin","#33339"]},"color":"#333399","align":"center","font":{"name":"宋体","bold":true}},{"border":{"top":["thin","#33339"],"left":["thin","#33339"],"bottom":["thin","#33339"],"right":["thin","#33339"]},"color":"#333399","font":{"name":"宋体"}},{"border":{"top":["thin","#333399"],"left":["thin","#333399"],"bottom":["thin","#333399"],"right":["thin","#333399"]},"color":"#333399","align":"center","font":{"name":"宋体","bold":true}},{"border":{"top":["thin","#333399"],"left":["thin","#333399"],"bottom":["thin","#333399"],"right":["thin","#333399"]},"color":"#333399","font":{"name":"宋体"}},{"border":{"top":["thin","#333399"],"left":["thin","#333399"],"bottom":["thin","#333399"],"right":["thin","#333399"]},"color":"#333399","align":"center","font":{"name":"宋体"}},{"font":{"bold":true}},{"border":{"top":["thick","#333399"],"left":["thick","#333399"],"bottom":["thick","#333399"],"right":["thick","#333399"]},"color":"#333399","align":"center","font":{"size":16,"name":"宋体","bold":true}},{"border":{"bottom":["thick","#333399"]},"color":"#333399","font":{"size":16,"name":"宋体","bold":true}},{"border":{"top":["thick","#333399"]},"color":"#333399","align":"center","font":{"name":"宋体"}},{"border":{"top":["thin","#333399"],"left":["thin","#333399"],"bottom":["thin","#333399"],"right":["thin","#333399"]},"color":"#333399","format":"number","font":{"name":"宋体"}},{"font":{"name":"宋体"}}],"isGroup":true,"freezeLineColor":"rgb(185, 185, 185)","merges":["C1:H2","C3:H3","I4:J4","B8:E8","G8:J8","B9:E9","G9:J9","B10:E10","G10:J10"]}

**Comment by xiaoyatousuju** [comment]
> 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

https://bootapi.jeecg.com/jmreport/shareView/1020980574833430528

**Comment by xiaoyatousuju** [comment]
> 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

![image](https://github.com/user-attachments/assets/47950b8e-662e-4feb-b733-f2858685a477)

**Comment by xiaoyatousuju** [comment]
> 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

你好，方便给一个回应吗？

**Comment by xiaoyatousuju** [comment]
> 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

你好，请问这个可以给确认下吗？

**Comment by jeecgos** [comment]
ws

**Comment by xiaoyatousuju** [comment]
> ws

这个回复是个什么意思？

**Comment by jeecgos** [comment]
已修复，待新版本发布
