### ISSUE TITLE
仪表盘数据表格能配置显示条数吗

### ISSUE THREAD

**Issue by 2752557729** [jeecgboot/JimuReport#3172]
##### 版本号：
1.9.0

##### 问题描述：
仪表盘数据表格，这个只显示5条数据，能配置吗？

##### 错误日志&截图：
![39e3ed546e55b11d2a8778877162ed8e](https://github.com/user-attachments/assets/6de64f62-9c20-4721-a0c2-e09f00521664)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你想自定义展示的数据条数？

**Comment by 2752557729** [comment]
> 你想自定义展示的数据条数？

是的

**Comment by 2752557729** [comment]
@jeecgos

**Comment by jeecgDeveloper** [comment]
已修改，下版本发布
