### ISSUE TITLE
可以实现签章盖着公司名称的效果吗

### ISSUE THREAD

**Issue by moguangyang** [jeecgboot/JimuReport#3173]
##### 版本号：
1.9.0

##### 问题描述：
是否可以实现签章盖着公司名称的效果

##### 错误日志&截图：
![aa](https://github.com/user-attachments/assets/fe6af891-6d28-41bb-b837-02cf3378d32a)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/user-attachments/assets/bdf5eb3c-f524-434d-91d1-0cd117793d1e)

**Comment by moguangyang** [comment]
插入图片会把文字遮住了，做不到透明的效果

**Comment by moguangyang** [comment]
如果是动态的数据是否也能实现
