### ISSUE TITLE
仪表盘可以动态传参吗

### ISSUE THREAD

**Issue by feilx2224** [jeecgboot/JimuReport#3174]
##### 版本号：
1.8.1

##### 问题描述：
仪表盘怎么做动态传参，让根据不同的参数来变化

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgDeveloper** [comment]
目前仪表盘可以通过配置组件联动的方式来传参刷新图表数据；你说的动态传参的具体使用场景和需求是什么？

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
