### ISSUE TITLE
分享链接后对方需要输入用户名和密码，怎么能让不输入直接看

### ISSUE THREAD

**Issue by feilx2224** [jeecgboot/JimuReport#3175]
##### 版本号：
1.8.1

##### 问题描述：

分享的仪表盘，对方打开链接需要输入用户名和密码，怎么做可以直接显示数据
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
已修复，请等待新版本发布。
