### ISSUE TITLE
多数据对比折线图使用API数据源问题

### ISSUE THREAD

**Issue by LuckClown** [jeecgboot/JimuReport#3178]
##### 版本号：
1.9.0

##### 问题描述：
多数据对比折线图，使用API数据源。如果API数据源因为有参数没有数据的时候，折线图的配置项会减少，退回到之前的版本了。导致预览时浏览器报错，加载不出来。

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/bf1db30e-15b0-46e3-9412-89fc8832ea83)

##### 重现步骤：
1、新增多数据对比折线图
2、使用api数据源 - 接口无数据，因为有查询参数
3、点击运行
4、切换回 样式 选项卡，发现样式缺失。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
按照步骤未复现该问题，请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
![QQ_1732870405860](https://github.com/user-attachments/assets/55786e55-a9fb-442b-bb75-b134f09d58d1)

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
