### ISSUE TITLE
hikari连接池的connectionTestQuery参数设置不上

### ISSUE THREAD

**Issue by qinghechaoge** [jeecgboot/JimuReport#3179]
##### 版本号：

1.6.6
##### 问题描述：
connectionTestQuery参数设置不上

##### 错误日志&截图：
![0cd4b63ba0cbf01797a98fd65b4ce361](https://github.com/user-attachments/assets/696f56d8-7e68-42e7-a52d-a0b998011d26)

**Comment by jeecgos** [comment]
cr

**Comment by jeecgos** [comment]
已修复，请等待新版本发布。
