### ISSUE TITLE
怎么设置才能不用点击查询栏进行查询，而是直接在项目的链接中输入参数的数值后，访问链接，即可完成查询的目的。

### ISSUE THREAD

**Issue by amwylig** [jeecgboot/JimuReport#3180]
##### 版本号：
1.9.0

##### 问题描述：
怎么设置才能不用点击查询栏进行查询，而是直接在项目的链接中输入参数的数值后，访问链接，即可完成查询的目的。
我用的是SQL查询
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/8ee22cc8-d95c-41c0-bc44-8f797c9e1f50)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
![QQ_1732872232850](https://github.com/user-attachments/assets/e3ec55d8-0da7-4ba9-99c0-7e072f859c1d)
![QQ_1732872268046](https://github.com/user-attachments/assets/b22611d9-84fd-4c0c-ba85-8abdb758fdb4)

**Comment by hoperunChen** [comment]
@amwylig  把查询默认值去掉，查询控件有默认值时会优先用控件默认值的值作为查询条件（非钻取报表）

**Comment by amwylig** [comment]
> @amwylig 把查询默认值去掉，查询控件有默认值时会优先用控件默认值的值作为查询条件（非钻取报表）

好滴，我试试看，谢谢

**Comment by BO-DI** [comment]
http链接中能传入这样得参数吗？我查询项中有一个公司id值，但是目前这个值写死得，我想把从前端VUE项目动态获取，怎么赋值给它呢？是在header里吗？

**Comment by jeecgos** [comment]
> http链接中能传入这样得参数吗？我查询项中有一个公司id值，但是目前这个值写死得，我想把从前端VUE项目动态获取，怎么赋值给它呢？是在header里吗？

是你的报表中有一个报表参数：{公司id}，这个值希望从业务系统中动态获取吗？

**Comment by jeecgos** [comment]
> http链接中能传入这样得参数吗？我查询项中有一个公司id值，但是目前这个值写死得，我想把从前端VUE项目动态获取，怎么赋值给它呢？是在header里吗？

如果你的报表中有一个报表参数（如 {公司id}），并希望从业务系统中动态获取值，可以通过动态修改地址中的参数实现。因为积木报表的查询参数是从URL中读取的，需确保在业务系统打开积木报表页面时，已动态更新URL参数。

例如，在前端VUE项目中，可以通过代码在跳转之前修改URL参数，确保 {公司id} 的值是最新的。

**Comment by BO-DI** [comment]
感谢大佬，我也在找对应得前端赋值处。例如：



然后我在业务系统配置处，增加&amp;companyId=${sessionStorage.currentCompany.id}&amp;farmId=${sessionStorage.currentFarm.id},应该即更新了吧。


左手年华
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月6日(星期五) 中午11:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 怎么设置才能不用点击查询栏进行查询，而是直接在项目的链接中输入参数的数值后，访问链接，即可完成查询的目的。 (Issue #3180)





  
http链接中能传入这样得参数吗？我查询项中有一个公司id值，但是目前这个值写死得，我想把从前端VUE项目动态获取，怎么赋值给它呢？是在header里吗？
  
如果你的报表中有一个报表参数（如 {公司id}），并希望从业务系统中动态获取值，可以通过动态修改地址中的参数实现。因为积木报表的查询参数是从URL中读取的，需确保在业务系统打开积木报表页面时，已动态更新URL参数。
 
例如，在前端VUE项目中，可以通过代码在跳转之前修改URL参数，确保 {公司id} 的值是最新的。

**Comment by BO-DI** [comment]
> > http链接中能传入这样得参数吗？我查询项中有一个公司id值，但是目前这个值写死得，我想把从前端VUE项目动态获取，怎么赋值给它呢？是在header里吗？
> 
> 如果你的报表中有一个报表参数（如 {公司id}），并希望从业务系统中动态获取值，可以通过动态修改地址中的参数实现。因为积木报表的查询参数是从URL中读取的，需确保在业务系统打开积木报表页面时，已动态更新URL参数。
> 
> 例如，在前端VUE项目中，可以通过代码在跳转之前修改URL参数，确保 {公司id} 的值是最新的。

也就是说必须要经过前端得项目解析参数是吧，我动态去拼不对，解析出来得是个变量字符串。
![image](https://github.com/user-attachments/assets/1570cb69-b43d-475e-8492-b29add2499cf)

**Comment by jeecgos** [comment]
> > > http链接中能传入这样得参数吗？我查询项中有一个公司id值，但是目前这个值写死得，我想把从前端VUE项目动态获取，怎么赋值给它呢？是在header里吗？
> > 
> > 
> > 如果你的报表中有一个报表参数（如 {公司id}），并希望从业务系统中动态获取值，可以通过动态修改地址中的参数实现。因为积木报表的查询参数是从URL中读取的，需确保在业务系统打开积木报表页面时，已动态更新URL参数。
> > 例如，在前端VUE项目中，可以通过代码在跳转之前修改URL参数，确保 {公司id} 的值是最新的。
> 
> 也就是说必须要经过前端得项目解析参数是吧，我动态去拼不对，解析出来得是个变量字符串。 ![image](https://private-user-images.githubusercontent.com/53505854/393107646-1570cb69-b43d-475e-8492-b29add2499cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0Njg1MzcsIm5iZiI6MTczMzQ2ODIzNywicGF0aCI6Ii81MzUwNTg1NC8zOTMxMDc2NDYtMTU3MGNiNjktYjQzZC00NzVlLTg0OTItYjI5YWRkMjQ5OWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA2NTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlYWNjMjQ5MmI2YjYzMGYzOWVjODgwNjhhY2Y4NmY1ZDJjZmRjNDkyNzUzZWUyOTBkYWYwNTE1MTBlOWNjY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EFwR07d-VEdhg1jN3_jRcegbRJRiz4H_kmR90wOU_IU)

这是你自己业务系统代码的问题，你要自己解决哈。

**Comment by BO-DI** [comment]
好的。&nbsp;


左手年华
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月6日(星期五) 下午2:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/JimuReport] 怎么设置才能不用点击查询栏进行查询，而是直接在项目的链接中输入参数的数值后，访问链接，即可完成查询的目的。 (Issue #3180)














    
http链接中能传入这样得参数吗？我查询项中有一个公司id值，但是目前这个值写死得，我想把从前端VUE项目动态获取，怎么赋值给它呢？是在header里吗？
  
如果你的报表中有一个报表参数（如 {公司id}），并希望从业务系统中动态获取值，可以通过动态修改地址中的参数实现。因为积木报表的查询参数是从URL中读取的，需确保在业务系统打开积木报表页面时，已动态更新URL参数。
 例如，在前端VUE项目中，可以通过代码在跳转之前修改URL参数，确保 {公司id} 的值是最新的。
  
也就是说必须要经过前端得项目解析参数是吧，我动态去拼不对，解析出来得是个变量字符串。 
  
这是你自己业务系统代码的问题，你要自己解决哈。
