### ISSUE TITLE
仪表盘数据集配置-SQL解析并且成功后没有出现字段

### ISSUE THREAD

**Issue by amwylig** [jeecgboot/JimuReport#3181]
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/06ae3978-c110-4b66-868b-4bd0278b21ec)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by amwylig** [comment]
> 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

SELECT
wljc.`日期`,
wljc.`物料编码`,
wljc.`物料简称`,
qc.`期初`,
qc.`入库`,
qc.`出库`,
qc.`期末`
FROM
(SELECT
	日期,
	物料编码,
	IF(LENGTH(COALESCE(zidian.M_NAME,物料简称)) = '1',`物料名称`,COALESCE(zidian.M_NAME,物料简称)) 物料简称,
	物料分组
FROM
	jd_zrjxc 
	LEFT JOIN zidian ON zidian.Y_code = jd_zrjxc.物料编码
	AND zidian.GROUPID_CODE = 'WLJC' 
WHERE 1=1
	and 物料简称 is not null
	and 1=1 and date_format( `日期`, '%Y-%m-%d' ) ='${riqi}'
	and 物料分组 not in ('低值易耗品','红酒')
	GROUP BY 物料编码,COALESCE(zidian.M_NAME,物料简称),物料分组,计量单位
	order by FIELD(物料简称, '佳配1段375g', '佳配1段800g', '佳配1段900g') desc , zidian.ID_GROUP is null ,zidian.ID_GROUP) wljc
	LEFT JOIN
	(SELECT 	日期,
	物料编码,
	物料简称,
	sum(期初) 期初,
	SUM(入库) 入库,
	SUM(出库) 出库,
	SUM(期末) 期末
	 FROM `jd_zrjxc`
	 WHERE 1=1
	 AND  物料简称 is not null
	 AND  物料简称 not IN(' ')
	and 1=1 and date_format( `日期`, '%Y-%m-%d' ) ='${riqi}'
	 GROUP BY 日期,物料编码,物料简称) qc
	ON qc.`物料编码` = wljc.`物料编码` AND qc.`日期` = wljc.`日期`
	WHERE 1=1
	AND qc.`期初` is not NULL

**Comment by zhangdaiscott** [comment]
后台提示什么，这个sql能查到数据吗

**Comment by amwylig** [comment]
> 后台提示什么，这个sql能查到数据吗

 就出现了解析成功，但是没有字段显示出来，这个sql是可以查的到的

**Comment by jeecgDeveloper** [comment]
已修改，下版本发布
