### ISSUE TITLE
sql数据集解析报错

### ISSUE THREAD

**Issue by 2752557729** [jeecgboot/JimuReport#3182]
##### 版本号：
1.9.0

##### 问题描述：
SQL注入风险

##### 错误日志&截图：
![f7a97eda3344f82d6c48ef76d8e04d20](https://github.com/user-attachments/assets/61e90ee5-fc5d-4cb1-a95c-96d07bff2ff5)
![d9e8b226de0f2cafb6dcd7391a8e2342](https://github.com/user-attachments/assets/1013ee05-10bc-4671-bb45-0b5da007f6aa)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by hoperunChen** [comment]
麻烦发一下**脱敏**后的sql语句。

**Comment by jeecgos** [comment]
麻烦发一下**脱敏后**的sql语句

**Comment by 2752557729** [comment]
查到了，是mid()函数。
