### ISSUE TITLE
【紧急】升级1.8.1版本后，小计及数据合计部分的展示方式和统计数据发生变化 

### ISSUE THREAD

**Issue by xiaoyatousuju** [jeecgboot/JimuReport#3183]
##### 错误日志&截图：

1.6.4版本的数据小计及合计业务
![image](https://github.com/user-attachments/assets/488c55b6-f49f-403e-8a36-81f52d546adb)

1.8.1版本的数据消息及合计业务
![image](https://github.com/user-attachments/assets/40a098a6-023f-4af5-8f18-c14440c90fdc)

这个严重影响了数据的准确性，真实性啊，怎么会出现这么严重的bug呢？
##### 重现步骤：

以下是演示环境配置的对应的设计模板
https://bootapi.jeecg.com/jmreport/shareView/1020980574833430528

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
重复 #3170
