### ISSUE TITLE
数据集无法编辑和删除

### ISSUE THREAD

**Issue by 2752557729** [jeecgboot/JimuReport#3184]
##### 版本号：
1.9.0

##### 问题描述：
数据集无法编辑和删除

##### 错误日志&截图：
![4ab2815cd3da1871dc233169d4a55dfa](https://github.com/user-attachments/assets/e33073c4-fdc0-4bf3-8858-aafcb9fd3e5a)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgDeveloper** [comment]
目前设计的是:
1、自己可以维护自己创建的数据集和数据源；
2、admin、dbadeveloper、lowdeveloper 角色有超级权限，可以修改任意数据和数据源

查看一下你的角色设置，或者数据的创建人是否当前登录人，是否都符合要求
