### ISSUE TITLE
在报表中插入图片后删除其他单元格内容图片会一起删除

### ISSUE THREAD

**Issue by wkahau** [jeecgboot/JimuReport#3186]
##### 版本号：
Starting JimuReportApplication v1.9 using Java 18.0.2 on Kai-Notebook

##### 问题描述：
在报表中插入图片后删除其他单元格内容图片会一起删除
尝试设置图片固定，删除其他单元格内容，图片也会一同删除。
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/42d67938-9a3c-4e0e-ac69-98d5bdb5ce3b)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
已经修复了，下个版本发布
你可以试下官方
jimureport.com

**Comment by wkahau** [comment]
> 已经修复了，下个版本发布 你可以试下官方 jimureport.com

真棒！！！非常感谢，感觉非常好用，支持！！
