### ISSUE TITLE
关于打印第二页空白问题

### ISSUE THREAD

**Issue by wkahau** [jeecgboot/JimuReport#3188]
##### 版本号：
Starting JimuReportApplication v1.9 using Java 18.0.2 on Kai-Notebook

##### 问题描述：
问题发生：在设计打印表单时候，纸张为A5，打印边距设计为1，结果打印时超出打印范围，显示不完整。后调整打印边距为5，出现2页。
问题处理：我从1-4设置打印边距，发现1-3，打印分页正常，显示只有1页，但是从4开始，第二页为空白。

##### 错误日志&截图：
1、打印边距为1-3：
![image](https://github.com/user-attachments/assets/92c3d6c6-b268-4bc8-bab7-f922cb692c53)
![image](https://github.com/user-attachments/assets/bf5abd67-cba8-427c-864e-7357fba5b2da)
2、打印边距设置为4：
![image](https://github.com/user-attachments/assets/889be3ee-6966-4368-97bb-37116289cefc)
![image](https://github.com/user-attachments/assets/0e12733b-842d-4ae4-82fc-d83d5b804bda)

##### 重现步骤：
如需提供报表设计以及SQL数据集信息，烦请告知。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
@wkahau 
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
