### ISSUE TITLE
其他页面直接调用预览打印

### ISSUE THREAD

**Issue by ShaoFeng-Guo** [jeecgboot/JimuReport#3189]
##### 版本号：
1.8.1

##### 问题描述：
如果是通过引入jar包的方式，有没有办法在其他页面可以实现这种点击就预览打印的功能，多数情况下，用户想直接弹出打印框，不用再去报表页面打开再点打印

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/277fc6cb-e97a-4ae0-b223-970f30b6e803)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
可以看下https://ojrjjvdr7z.k.topthink.com/jimureport/directPrintApi.html 和https://ojrjjvdr7z.k.topthink.com/jimureport/exportapi.html 能不能满足你的需求？
