### ISSUE TITLE
动态分组后的列错乱和不显示

### ISSUE THREAD

**Issue by 15206125206** [jeecgboot/JimuReport#3190]
##### 版本号：
1.8.1-beta

##### 问题描述：
动态分组后的列错乱和不显示

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/e8487ed5-093e-45f5-8bec-a14abc78be4d)
![image](https://github.com/user-attachments/assets/247610e9-976c-4e70-8df3-ab85651dc2f6)

##### 重现步骤：
[测试数据.xls](https://github.com/user-attachments/files/17944141/default.xls)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 15206125206** [comment]
横向分组列放到最后就没问题

**Comment by jeecgos** [comment]
cr

**Comment by jeecgos** [comment]
已修复，请等待新版本发布。
