### ISSUE TITLE
填报无法分页。

### ISSUE THREAD

**Issue by renyuxian940302** [jeecgboot/JimuReport#3192]
##### 错误日志&截图：
![8fe57d9c26b8f596ab84527a8c07d50b](https://github.com/user-attachments/assets/484feeff-704b-4693-98af-b8927b6ebab4)
![cd22ea6d4507f9d771ab64838a50902b](https://github.com/user-attachments/assets/7431baea-7dbf-41ff-8afe-c9499a7aa7c2)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
zy

**Comment by zhangdaiscott** [comment]
下个版本发布
