### ISSUE TITLE
填报校验问题

### ISSUE THREAD

**Issue by renyuxian940302** [jeecgboot/JimuReport#3193]
##### 错误日志&截图：
![68e65910fcd0b5eedc46b0ee64b8ec84](https://github.com/user-attachments/assets/8e5b7c00-8a7b-40fb-a3c1-e64ce18fd391)

![cd710c39f3bc1d4ecc3b2e009121c112](https://github.com/user-attachments/assets/26be7299-77f4-4db3-83b6-1d5bd0168c44)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by renyuxian940302** [comment]
2.如何设置某一列必填(某个字段必填)  该问题已经解决

**Comment by jeecgDeveloper** [comment]
已修复，下一版本发布。
