### ISSUE TITLE
参数设置了默认值，预览报表时，查询框里没有计算并显示出来。

### ISSUE THREAD

**Issue by amwylig** [jeecgboot/JimuReport#3195]
##### 错误日志&截图：
![8db6687aa6252295d8dc084b6795446e](https://github.com/user-attachments/assets/bf80ad00-4be0-4b3a-bd41-20ac09120092)
![image](https://github.com/user-attachments/assets/88f642ca-aa6e-4a4c-b0c4-33017ce91dea)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
ws

**Comment by jeecgos** [comment]
把下拉单选去掉就好了，下拉单选和多选是用于字符串的
![image](https://github.com/user-attachments/assets/338a4ccf-5ef3-4b74-80fc-d34092b888bb)
