### ISSUE TITLE
积木报表能不能自主排序

### ISSUE THREAD

**Issue by zhoulel** [jeecgboot/JimuReport#3196]
##### 版本号：

1.5.4
##### 问题描述：
表头能不能和online报表一样点击自主排序的
##### 错误日志&截图：

![1733098446741](https://github.com/user-attachments/assets/76439a43-864e-4a56-9cde-7cc490773b07)

##### 重现步骤：
![image](https://github.com/user-attachments/assets/c82e7816-a6f5-4b41-9716-c44eadaf06c7)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
新增功能：自定义排序，请等待新版本发布。
![QQ_1733833179111](https://github.com/user-attachments/assets/afa5a08c-6b54-4ba6-8348-f84872963e87)
