### ISSUE TITLE
积木报表可以设置默认分页吗？

### ISSUE THREAD

**Issue by javaswimmer** [jeecgboot/JimuReport#3197]
##### 版本号：
1.9.0

##### 问题描述：
积木报表可以设置默认分页吗？

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/ca07857d-7f4b-4309-bd4c-45521ba2303d)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
参考文档：https://help.jeecg.com/jimureport/base/tools.html
![QQ_1733477673547](https://github.com/user-attachments/assets/fad6a630-900b-4cd9-8c07-7ce54ccf229e)
