### ISSUE TITLE
当列的数值为0时隐藏这一列，不为0时，则显示。然后查询出来的结果怎么设置为隔1行填充颜色

### ISSUE THREAD

**Issue by amwylig** [jeecgboot/JimuReport#3198]
##### 错误日志&截图：
![b3d59dbdf2030ff4be62898039c0ce9a](https://github.com/user-attachments/assets/56fbc077-1686-4009-90ff-142e662e8e8b)
![image](https://github.com/user-attachments/assets/5f91b460-643d-4ab5-8785-8f3ac27d6af2)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
1. 不支持
2. 参考：https://help.jeecg.com/jimureport/function/condition.html#%E6%96%91%E9%A9%AC%E7%BA%BF%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B

**Comment by amwylig** [comment]
> 1. 不支持
> 2. 参考：https://help.jeecg.com/jimureport/function/condition.html#%E6%96%91%E9%A9%AC%E7%BA%BF%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B

第一个不能做一下更新么，用if来做到之类的┭┮﹏┭┮
