### ISSUE TITLE
报表导出空白

### ISSUE THREAD

**Issue by liyuan881024** [jeecgboot/JimuReport#3199]
##### 错误日志&截图：
查询条件为黄色时，能导出数据
![1733197781739_3BD4C335-9003-4297-A555-843E3E3DF4E9](https://github.com/user-attachments/assets/b06f8551-4a23-4c22-b225-d4c2fccbabaf)
当查询条件选择橙色时，导出数据空白
![1733197145552_D59DB909-6379-47f1-8D12-67A3250405C9](https://github.com/user-attachments/assets/cc2fbc71-16c4-4d79-8c2c-b184088ada88)

##### 重现步骤：
无

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by liyuan881024** [comment]
已经解决了，是查询时数据量太多，参数超过限制。谢谢
