### ISSUE TITLE
大屏在内网环境无法获取svg、icon

### ISSUE THREAD

**Issue by zhao-yifei** [jeecgboot/JimuReport#3200]
##### 版本号：
1.9.0

##### 问题描述：
内网环境内部署积木报表 ，设计器+预览 图标丢失

##### 错误日志&截图：
内网部署积木报表
1、打开设计器，图标样式丢失
![270f3e2c7a8c707e1c1eba1e83a6e81](https://github.com/user-attachments/assets/d8d5e8a8-1347-4cd9-8f9a-d7828331f2f0)

2、打开预览，图标样式丢失
![4e5cdb6a17ba66594c24a13d911cd52](https://github.com/user-attachments/assets/fc01abfc-69d8-4e3c-8b57-0a00c1c878b2)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgDeveloper** [comment]
已修改，更到最新版试试
 <dependency>
   <groupId>org.jeecgframework.jimureport</groupId>
   <artifactId>jimubi-spring-boot-starter</artifactId>
   <version>1.9.1</version>
 </dependency>

**Comment by jeecgDeveloper** [comment]
已修改，更到最新版试试
```
 <dependency>
   <groupId>org.jeecgframework.jimureport</groupId>
   <artifactId>jimubi-spring-boot-starter</artifactId>
   <version>1.9.1</version>
 </dependency>
```
