### ISSUE TITLE
积木报表导出的pdf打印颜色非常淡且线框粗细无效

### ISSUE THREAD

**Issue by gtiszjj** [jeecgboot/JimuReport#3202]
##### 版本号：
1.6.1  1.7.8

##### 问题描述：
报表设置边框线，很粗，导出的pdf，预览没问题，但是，实际打印机打印线条非常细，且颜色非常淡

##### 错误日志&截图：
官网的导出pdf，直接打印也是如此

**Comment by gtiszjj** [comment]
经过排查，发现导出的xls网格线被jmreport默认设置为thin格式，pdf类似问题

**Comment by jeecgos** [comment]
导出excel已支持待新版本发布，导出pdf暂不支持
