### ISSUE TITLE
之前正常的表格，打开Python增强，预览报错

### ISSUE THREAD

**Issue by YskRuoSE** [jeecgboot/JimuReport#3203]
##### 问题描述：
想使用多级动态表头的功能，目前3级不够用。看到使用Python引擎可以多级渲染。但是打开之后预览表格，原本正常的表格报错，尝试注册了线上账号，原本正常的表格，打开python引擎之后也报错
FreeMarker template error:
The following has evaluated to null or missing:
==> ss.groupRight  [in template "template" at line 1, column 210]

##### 错误日志&截图：
2024-12-04 14:43:46.252 [http-nio-8085-exec-8] ERROR freemarker.runtime:60 - Error executing FreeMarker template
freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> ss.groupRight  [in template "template" at line 1, column 210]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

##### 重现步骤：
怀疑可能是免费版本不支持，尝试线上版本，注册了账号，找了一个模板，不开python引擎可以正常预览，打开之后也报错。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
开源版现在还不支持Python引擎

**Comment by YskRuoSE** [comment]
线上注册的在线使用，也报错怎么回事呢？也是不打开Python引擎可以正常显示。打开之后就报错。

**Comment by zhangdaiscott** [comment]
没放开这个功能

**Comment by jeecgos** [comment]
已修复，请等待新版本发布。
