### ISSUE TITLE
大屏每天报连接错误

### ISSUE THREAD

**Issue by hzlskj** [jeecgboot/JimuReport#3205]
##### 问题描述：
数据库服务器晚上上传数据到百度网盘，可能影响服务器网络了，第二天就报此错误，提示连接超过5次，每次方法都是数据源重连接，

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/30031d54-1d68-40e8-8ec5-cc519e11f878)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你的大屏组件是设置了定时刷新吧，会定时去调用数据库，你上传资源肯定把你们服务器的资源给占用了导致数据库连不上，我们程序做了试错机制，错误次数太多就不再去链接了，防止恶意攻击行为。

你可以采用以下方案
1、扩大服务器资源
2、每天手工重置数据库链接
