### ISSUE TITLE
数据源不见了

### ISSUE THREAD

**Issue by hzlskj** [jeecgboot/JimuReport#3206]
##### 问题描述：
数据源只有新增，没有老的了

##### 错误日志&截图：
![d4df1464efa92420c213732a04edc32c](https://github.com/user-attachments/assets/2f49a8b6-e802-49fd-8c5c-d7b74304c239)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
好了
