### ISSUE TITLE
报表导出数据不全

### ISSUE THREAD

**Issue by zhoulel** [jeecgboot/JimuReport#3207]
##### 版本号：
1.5.4

##### 问题描述：
报表导出数据不全 前面几列有数据后面几列就没有了  合计也是空的

##### 错误日志&截图：
![~T_F_)7{3YO2C`{BAD53VIA](https://github.com/user-attachments/assets/d4192042-d021-4b6c-bcab-7e7179abea1b)

![image](https://github.com/user-attachments/assets/7c0762db-36ac-4228-9a92-01832a256b4a)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请先升级到最新版
