### ISSUE TITLE
积木仪表盘设计页面静态地址项目名丢失及接口地址是ip的问题

### ISSUE THREAD

**Issue by chendong2025** [jeecgboot/JimuReport#3208]
##### 版本号：
1.9.1

##### 问题描述：
积木仪表盘功能，点击设计，接口地址会出现使用部署项目的ip地址及端口、以及项目名丢失的情况，导致外部请求接口失败。

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/1c8fed9a-6c4d-4498-8f1b-aebc91ec2804)

##### 重现步骤：
积木仪表盘--设计 页面。 部署框架采用的是 ruoyi cloud

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by hao1175310925** [comment]
我也有这个问题

**Comment by jeecgDeveloper** [comment]
已修改，下版本发布
