### ISSUE TITLE
基本运算符不生效+表头如何跟查询条件联动显示

### ISSUE THREAD

**Issue by wangrEthanoo** [jeecgboot/JimuReport#3209]
##### 问题描述：
问题一：表头怎样与查询条件进行联动，比如查询条件里面有省份和年度，在表头也显示“XXXX省XXXX年XXXXX”
问题二：除法的基本运算符中怎样避免除数为0的情况，如何写判断，在哪写，初始化不查询数据，由于除数为0会报错“/by zero”；查询数据后，由于部分查出来有除数为0，会报错“ERROR[0;39m [36mo.j.m.j.desreport.render.method.FreemarkerMethod:107[0;39m - Division undefined
java.lang.ArithmeticException: Division undefined
	at java.math.BigDecimal.divide(BigDecimal.java:1744)”
问题三：请问积木报表每个sql的执行时间大概是多久？是否可以在配置文件里面设置执行时间，如果可以，最长可以多久？因为有些sql数据量上百万，优化后的
执行时间超过50s左右会自动在数据库取消当前操作，页面预览显示白板
##### 错误日志&截图：
问题一：
<img width="959" alt="428459c44a8172175cfccef90d541b0" src="https://github.com/user-attachments/assets/1f1d76f8-eef2-4112-a68c-09c3c703f84f">
<img width="929" alt="50c65989b70f8e4e3020797f7c39134" src="https://github.com/user-attachments/assets/f0ad5e3e-568b-4ecf-b35e-721724d43e36">
<img width="776" alt="a38d467425c32b71d12aebd5e8482d2" src="https://github.com/user-attachments/assets/54a2a62c-7f43-412a-86fd-991c22583b8b">
问题二：
<img width="822" alt="40d57b389ee9551038797f1458ca025" src="https://github.com/user-attachments/assets/a1cc55b8-617f-4d39-80bb-7c47f6d8decc">
![image](https://github.com/user-attachments/assets/b9d90784-83e5-4922-9eee-a3f2d1de4525)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by wangrEthanoo** [comment]
问题二：除法运算符：除数为0判断不生效，要怎样实现避免除数为0的情况

**Comment by jeecgos** [comment]
问题一：升到最新版本后 用 ${param.xxxx} 试一下。
问题二：升到最新版本试下，应该改过了。
问题三：在配置文件中设置下数据源的超时
![QQ_1733479226914](https://github.com/user-attachments/assets/9e78a63c-963c-4fd5-b188-af61cc50cffd)

**Comment by wangrEthanoo** [comment]
> 问题一：升到最新版本后 用 ${param.xxxx} 试一下。 问题二：升到最新版本试下，应该改过了。 问题三：在配置文件中设置下数据源的超时 ![QQ_1733479226914](https://private-user-images.githubusercontent.com/162332873/393198587-9e78a63c-963c-4fd5-b188-af61cc50cffd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MjQzNTgsIm5iZiI6MTczMzcyNDA1OCwicGF0aCI6Ii8xNjIzMzI4NzMvMzkzMTk4NTg3LTllNzhhNjNjLTk2M2MtNGZkNS1iMTg4LWFmNjFjYzUwY2ZmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQwNjAwNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTFmOTA0OWFmOTFlMWIwNTI1MzRkNzdhYzQ3MzVjYjY5ZjAwOWQ1MmNlNmRiNTczNzA5OWZmMjM2YzdlZTE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cKJ9h8u8P-W_r_Cz_4E04Ylc5u-8DdMxnzbuvbJb2V4)

您好，我们现在用的版本是直接部署在服务器上，在线进行设计的，这个问题必须要升级到最新版本吗？如果升级对以前已经设计好的报表是否会有影响

**Comment by jeecgos** [comment]
> 您好，我们现在用的版本是直接部署在服务器上，在线进行设计的，这个问题必须要升级到最新版本吗？

你可以先试一下用${param.xxx}在你的版本上有没有效果，如果没有效果就只能升级了。
![QQ_1733731884381](https://github.com/user-attachments/assets/62c0ecad-fd4a-445a-8608-41bfc91f7562)
![QQ_1733731950465](https://github.com/user-attachments/assets/1b0ee713-63e8-418c-9417-6b8baeab0d8d)

> 如果升级对以前已经设计好的报表是否会有影响

建议在升级前做好备份工作。或者在开发环境升级好确认没问题再升级生产环境。

**Comment by wangrEthanoo** [comment]
> ${param.xxx}

![image](https://github.com/user-attachments/assets/eb62a92e-9148-44c1-8a81-b92429179153)
![image](https://github.com/user-attachments/assets/73698103-39d9-4f18-b706-a94469ce84dd)
我只有DS一个数据集，查询条件的这些字段，比如aab301并没有在DS这个数据集里面查出来，那我这个${param.xxx}要怎样写？${DS.aab301}？

**Comment by jeecgos** [comment]
写法：${param.aab301}  
param是固定值

**Comment by wangrEthanoo** [comment]
> param

可以可以，这个生效了，那除法报错的那个在1.6的版本上可以解决吗？

**Comment by jeecgos** [comment]
问题二：除数为零报错问题：已修复，请等待新版本发布。
