### ISSUE TITLE
功能缺失-目前对word模板设计支持不好

### ISSUE THREAD

**Issue by wangwangfish** [jeecgboot/JimuReport#3213]
##### 版本号：
v1.9.1

##### 问题描述：
目前对word模板设计支持不好，类似word风格，设计word模板，动态绑定数据集，最后动态填充数据生成word和pdf

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
pdf支持

**Comment by zhangdaiscott** [comment]
咱不考虑
