### ISSUE TITLE
1.9.1版本集成到ruoyi-vue后项目启动失败

### ISSUE THREAD

**Issue by scxinya** [jeecgboot/JimuReport#3214]
##### 版本号：
1.9.1

##### 问题描述：
将最新版本依赖集成至ruoyi-vue后项目启动失败，debug如下图所示

##### 错误日志&截图：
![d6ffdb54a79539d4cee6b7169eb0be9c](https://github.com/user-attachments/assets/887a177b-9914-4728-a994-3ac0acd6de09)

##### 重现步骤：
先集成了1.9.0版本依赖，通过升级方式更新了1.9.1版本依赖，ruoyi-vue后端项目启动

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by LEEHOR** [comment]
我也是遇到这个问题。求解决方法

**Comment by zhangdaiscott** [comment]
看错误提示

**Comment by LEEHOR** [comment]
在framework模块下的config/ThreadPoolConfig类中添加下面的方法
 /**
     * 积木报表启动报错
     */
    @Bean(name = "taskScheduler")
    protected TaskScheduler taskScheduler()
    {
        ThreadPoolTaskScheduler scheduler = new ThreadPoolTaskScheduler();
        scheduler.setPoolSize(8);
        scheduler.setThreadNamePrefix("scheduled-thread-");
        return scheduler;
    }

**Comment by jeecgos** [comment]
cr
