### ISSUE TITLE
启动

### ISSUE THREAD

**Issue by lvsongxiaobai** [jeecgboot/JimuReport#3215]
##### 问题描述：
启动报错

##### 错误日志&截图：

![1733448610879](https://github.com/user-attachments/assets/b063f157-1cc2-4372-a883-97b7a768b881)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
只支持springboot2
