### ISSUE TITLE
积木仪表盘—查询条件中，添加字典编码后，查询条件组件消失了

### ISSUE THREAD

**Issue by TSM1206** [jeecgboot/JimuReport#3216]
##### 版本号：
V1.9.1

##### 问题描述：
积木仪表盘—查询条件中，添加字典编码后，查询条件组件消失了

##### 错误日志&截图：

![a06c2d63889b62a9e8e48a3b6db25575](https://github.com/user-attachments/assets/7f48b0aa-93cf-4c1b-9e3c-164ef8862fff)
![7dd6f5524754a8c8f2b901d2e0075b6b](https://github.com/user-attachments/assets/4215f2be-f4a3-43d6-ba39-4a61a1a22261)

https://github.com/user-attachments/assets/64e8e383-1dfc-474c-9275-a6d2cf09c67e

##### 重现步骤：
添加查询条件——增加查询项——添加字典编码——保存预览——组件消失——删除字典编码——保存预览——组件出现

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
sq

**Comment by jeecgDeveloper** [comment]
测试1.9.1版本，未复现你说的问题，请确认一下
1.这个问题是否拖出来表单组件，配置下拉组件和字典，就必会复现？
2.当组件不显示时，查看工作台，是否有报错信息？
3.非当前窗口，正式预览页面是否也不显示？
