### ISSUE TITLE
在线填报#{}渲染异常

### ISSUE THREAD

**Issue by LAW-t** [jeecgboot/JimuReport#3217]
##### 版本号：
1.9.1

##### 问题描述：
在“在线填报”中，使用#{}查询数据，该单元格渲染异常

##### 错误日志&截图：
设计：
![image](https://github.com/user-attachments/assets/ffed4200-f548-491e-915b-7a600da209ad)
预览：
![image](https://github.com/user-attachments/assets/1f85029f-1310-498c-a033-ecd797ada135)

##### 重现步骤：
任意创建在线填报，链接数据集，使用#{}的单元格都渲染异常，${}渲染正常

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
填报数据源不支持 数据列表的查询报表。请使用数据报表。
