### ISSUE TITLE
仪表盘查询组件日期怎么设置默认值为当天或者昨天

### ISSUE THREAD

**Issue by 15206125206** [jeecgboot/JimuReport#3218]
##### 版本号：
1.9.1

##### 问题描述：
![Uploading image.png…]()

##### 错误日志&截图：
日期函数都没作用

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 15206125206** [comment]
![image](https://github.com/user-attachments/assets/30673902-1874-489b-939a-32689f21ecb8)

**Comment by zhangdaiscott** [comment]
查询条件？

**Comment by 15206125206** [comment]
![image](https://github.com/user-attachments/assets/0537bb68-0af5-4fb3-bdd6-4ec86ac9bac7)
就是这个默认显示当天要怎么弄

**Comment by zhangdaiscott** [comment]
sq

**Comment by jeecgDeveloper** [comment]
已修改，下版本发布
