### ISSUE TITLE
从积本BI切换回积木报表时tocken会漏掉

### ISSUE THREAD

**Issue by tyhg001** [jeecgboot/JimuReport#3219]
##### 错误日志&截图：从积木报表切换到积本BI时会带tocken
![image](https://github.com/user-attachments/assets/7aaf27f1-0e86-4cc6-a254-447f2a876ca7)
但从积本bi再点回积木报表时tocken就没有了
![image](https://github.com/user-attachments/assets/a8f7b894-ce73-4f03-9d2c-70a82b19c907)
![image](https://github.com/user-attachments/assets/210ecd54-6f45-4313-bc52-e2d34f9b1edc)

**Comment by zhangdaiscott** [comment]
sq

**Comment by zhangdaiscott** [comment]
你集成到jeecg中为什么不是两个菜单，还用这种跳转模式

**Comment by tyhg001** [comment]
我没多加菜单，那多加个菜单也行吧

**Comment by jeecgDeveloper** [comment]
已修改，下版本发布
