### ISSUE TITLE
api数据集get请求后台取不到参数

### ISSUE THREAD

**Issue by tyhg001** [jeecgboot/JimuReport#322]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/19584941/121629497-dc5a7200-caad-11eb-9e80-b7b1ae3693f3.png)
![image](https://user-images.githubusercontent.com/19584941/121629503-e4b2ad00-caad-11eb-8b94-3d8e97c90810.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布

**Comment by zhangdaiscott** [comment]
升级
http://jimureport.com/doc/log
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.51-beta</version>
</dependency>
```
