### ISSUE TITLE
ruoyi  集成积木  仪表盘和大屏启动报错 

### ISSUE THREAD

**Issue by lvsongxiaobai** [jeecgboot/JimuReport#3220]
##### 版本号：
1.9.1 

##### 问题描述：
ruoyi  集成积木  仪表盘和大屏启动报错 

##### 错误日志&截图：

![aaaa](https://github.com/user-attachments/assets/3004e7ab-94ec-4977-a5a9-61a9c37efaa0)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
错误信息太少，看不出来

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/JimuReport/issues/3250
