### ISSUE TITLE
Cache SPEL 表达式解析不到参数

### ISSUE THREAD

**Issue by chenqinru** [jeecgboot/JimuReport#3222]
##### 版本号：

- JDK 21
- Springboot 3.2.2
- jimureport-dashboard-spring-boot3-starter 1.8.1-beta

##### 问题描述：

jimureport-dashboard中使用的缓存组件，在使用SPEL表达式解析参数的时候，无法获取到参数（确认maven已经开启了 -parameters 参数名解析），项目中其他地方使用缓存组件没问题。

##### 错误日志&截图：

![image](https://github.com/user-attachments/assets/cdd94240-f02a-4934-aef3-0274d6de4a35)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
升级到最新版试试
https://blog.csdn.net/zhangdaiscott/article/details/144251351

**Comment by zhangdaiscott** [comment]
等新版本springBoot3发布就好了
