### ISSUE TITLE
升级到1.91后多选下拉新问题

### ISSUE THREAD

**Issue by zwjsoft** [jeecgboot/JimuReport#3223]
##### 版本号：
1.91

##### 问题描述：
升级到1.91后，多选下拉在默认值情况下显示出现了问题，但是查询的结果似乎正确。
![image](https://github.com/user-attachments/assets/d609665e-5906-4a5e-a996-23a0b7ed44cc)
![image](https://github.com/user-attachments/assets/ee62bbb2-8bf4-4bfd-a9b5-870fcd30489a)

其中职务这个下拉显示不正常，但同样产线这个下拉又是正常的，区别产线的id全部为数字

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by BO-DI** [comment]
请问，下拉多选得查询项动态传参是怎么处理的呢？

**Comment by zwjsoft** [comment]
大小写问题，下拉这个地方需要分大小写，数据库里面不分太小写

**Comment by zhangdaiscott** [comment]
WS

**Comment by BO-DI** [comment]
> WS

这是啥意思呢，不懂，辛苦说清楚点，谢谢！！！

**Comment by jeecgos** [comment]
1、已修复，待新版本发布
2、你可以使用系统变量  https://help.jeecg.com/jimureport/config/sysVariable.html#%E5%A6%82%E4%BD%95%E8%87%AA%E5%AE%9A%E4%B9%89%E7%B3%BB%E7%BB%9F%E5%8F%98%E9%87%8F
