### ISSUE TITLE
下拉树动态传参问题

### ISSUE THREAD

**Issue by BO-DI** [jeecgboot/JimuReport#3224]
##### 版本号：
1.9.1

##### 问题描述：
在积木报表的查询项中，需要实现下拉树，但是传参只支持固定值，动态传参不支持，这块目前有解决方案吗，还是说可以js增强处理呢？
[但是我看已关闭的issue里说是bug问题，说是下个版本会修复，这能确定吗？](https://github.com/jeecgboot/JimuReport/issues/1210)

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/c7e0dc71-a8d0-4a18-b7e8-f75cc5fc13ed)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by BO-DI** [comment]
我验证的js增强是不是只能是下拉框而不能是下拉树呢？

**Comment by jeecgos** [comment]
ws

**Comment by BO-DI** [comment]
> ws

这是啥意思呢，是后续版本会支持吗？

**Comment by jeecgos** [comment]
@BO-DI 请求地址里的这个参数 （本例：#{farmId}) 是系统变量，不是数据集的参数。你需要实现自定义系统变量来返回这个值。
https://help.jeecg.com/jimureport/config/sysVariable.html#%E5%A6%82%E4%BD%95%E8%87%AA%E5%AE%9A%E4%B9%89%E7%B3%BB%E7%BB%9F%E5%8F%98%E9%87%8F

**Comment by BO-DI** [comment]
目前这个我是通过拦截器实现动态切换得，因为这个说是不支持动态参数，我就问后续支不支持。目前这个不是只支持固定值和无参吗？

**Comment by jeecgos** [comment]
> 目前这个我是通过拦截器实现动态切换得，因为这个说是不支持动态参数，我就问后续支不支持。目前这个不是只支持固定值和无参吗？

先归集：#138，后续支持后会告知。

**Comment by BO-DI** [comment]
好的。
