### ISSUE TITLE
在测试环境中仪表盘部分接口访问不到

### ISSUE THREAD

**Issue by grnv1** [jeecgboot/JimuReport#3225]
##### 版本号：
1.9.1

##### 问题描述：
使用springboot框架对积木报表以及仪表盘进行集成，需要经过网关，因此配置了customPrePath以及apiBasePath，配置如下图：
![屏幕截图 2024-12-09 163254](https://github.com/user-attachments/assets/94cf8b92-9964-4dfd-a925-5f94ad27c332)
在实际使用时，通过网关路径http://10.134.22.220:30381/jimu-platform/drag/list 访问报表主页正常，但在点进报表设计页面后一直加载。检查后发现调用的接口地址是网关地址直接拼接上接口地址，而不是网关地址拼接路由再拼接上接口地址，因此无法访问。
![屏幕截图 2024-12-09 163735](https://github.com/user-attachments/assets/b9d49ab6-ef46-4a2d-bc09-7a079093ae8b)

##### 错误日志&截图：
如上

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by grnv1** [comment]
请问这个问题时参数配置有问题还是因为什么别的原因，需要怎么改

**Comment by jeecgos** [comment]
sq

**Comment by jeecgos** [comment]
#3208

**Comment by jeecgDeveloper** [comment]
已修改，下版本发布
