### ISSUE TITLE
仪表盘鉴权问题

### ISSUE THREAD

**Issue by grnv1** [jeecgboot/JimuReport#3226]
##### 版本号：
1.9.1

##### 问题描述：
我们希望将积木仪表盘集成到我们已有的系统中，因此鉴权时希望使用我们系统自己的鉴权方法，请问在生成仪表盘分享链接时如果勾选了开启校验，这时链接中的token是如何生成的？如果我们希望使用我们自己的token来访问这个分享链接，要如何修改代码？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
参考
https://gitee.com/jeecg/JeecgBoot/blob/master/jeecg-boot/jeecg-module-system/jeecg-system-biz/src/main/java/org/jeecg/config/jimureport/JimuReportTokenService.java
