### ISSUE TITLE
保存数据源报错

### ISSUE THREAD

**Issue by tyl1997** [jeecgboot/JimuReport#3229]
##### 问题描述：
保存数据源报错

##### 错误日志&截图：
<img width="1274" alt="a6835008a44adac127ad71adb91fffc" src="https://github.com/user-attachments/assets/62e6e437-d26a-4fe5-abeb-b8712f433e9d">

##### 重现步骤：
新建报表，增加数据源

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
版本号

**Comment by tyl1997** [comment]
1.6.7

**Comment by tyl1997** [comment]
1.6.6,搞错了
