### ISSUE TITLE
保存数据源报错

### ISSUE THREAD

**Issue by tyl1997** [jeecgboot/JimuReport#3230]
##### 版本号：
1.6.6

##### 问题描述：
保存数据源的时候提示某字段不能为空

##### 错误日志&截图：
![@V~0487TUP6NH5QMLV@4TB8](https://github.com/user-attachments/assets/c2030814-cec4-4f60-9fea-ab039ffc0423)

##### 重现步骤：
新增报表，新增数据源

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
请确认下是不是升级了积木报表版本，但是没有执行sql语句？

> iz_shared_source字段是1.9.0版本共享数据集功能新增的字段。
