### ISSUE TITLE
横向动态分组合计需求

### ISSUE THREAD

**Issue by 15206125206** [jeecgboot/JimuReport#3231]
##### 版本号：
1.9.1

##### 问题描述：
怎么合计后和其他单元格进行计算

##### 错误日志&截图：
![f4ac5e1aeca390eb6f57243c024e484](https://github.com/user-attachments/assets/65e0cc2f-3067-47ec-9143-77dd31ee4852)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 15206125206** [comment]
按照文档试了很多方式都达不到预期效果

**Comment by jeecgos** [comment]
![QQ_1734081030457](https://github.com/user-attachments/assets/8217633c-3949-4d5a-b750-828262e59ab6)
![QQ_1734081103427](https://github.com/user-attachments/assets/0214b558-d9ea-4b9b-9052-1dbea16bf11e)

**Comment by 15206125206** [comment]
感谢回复，但是和我的诉求可能不太一样，我横向分组的是商品数量，sum之后需要乘零售价，这个貌似好像不支持

**Comment by 15206125206** [comment]
感谢回复，但是和我的诉求可能不太一样，我横向分组的是商品数量，sum之后需要乘零售价，这个貌似好像不支持

**Comment by jeecgos** [comment]
cr

**Comment by jeecgos** [comment]
已修复，请等待新版本发布。
