### ISSUE TITLE
积木报表升级1.9.1后，分组无效

### ISSUE THREAD

**Issue by jiangbr1614** [jeecgboot/JimuReport#3235]
##### 问题描述：
积木报表升级1.9.1后，字段进行纵向分组时，报错，显示一个miniDaoUtil里面缺少了addOrderBy方法。

##### 错误日志&截图：
Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.jeecgframework.minidao.util.MiniDaoUtil.addOrderBy(Ljava/lang/String;Ljava/lang/String;Z)Ljava/lang/String;

![图1](https://github.com/user-attachments/assets/8790ea58-5d73-430f-9b16-537a366c3fd3)
![图2](https://github.com/user-attachments/assets/91e04a44-9d32-4b32-b37e-ca8379010ed6)
![图4](https://github.com/user-attachments/assets/ce40f9f5-ef5b-4631-b24e-3b2271a65e3c)

##### 重现步骤：
升级报表版本至1.9.1，然后找到报表字段分组，选择纵向分组既会报错。

**Comment by jeecgos** [comment]
MiniDao版本太低了，升级到1.10.5

**Comment by jiangbr1614** [comment]
> MiniDao版本太低了，升级到1.10.5
大佬我的jeecg项目找了半天POM.xml都没找到这个依赖，然后我手动的加了一个dependency,左侧的包还是老版本怎么办
![反面](https://github.com/user-attachments/assets/1f8edb70-d6b9-4101-897a-b56c8883f753)

**Comment by jeecgos** [comment]
装个mavenHelper插件
