### ISSUE TITLE
添加 api接口数据集报错

### ISSUE THREAD

**Issue by liuling1314** [jeecgboot/JimuReport#3237]
##### 版本号：
1.9.1

##### 问题描述：

添加api数据集报错
##### 错误日志&截图：
![Screenshot](https://github.com/user-attachments/assets/85a47ccb-d96c-410e-a2f2-0f89e0194455)

##### 重现步骤：

添加api数据集即可重现
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by liuling1314** [comment]
@zhangdaiscott 抽个时间给看下，是不是 1.9.1 忘记合并了，我看这个issue 10月份是close掉了

**Comment by zhangdaiscott** [comment]
下个版本发布

**Comment by BO-DI** [comment]
> @zhangdaiscott 抽个时间给看下，是不是 1.9.1 忘记合并了，我看这个issue 10月份是close掉了

你这个是企业版本的吧

**Comment by sweetcard** [comment]
这个问题出在如果不定义 jeecg.jmreport.apiBasePath 就会出现
