### ISSUE TITLE
【建议】顶部菜单支持配置隐藏显示

### ISSUE THREAD

**Issue by JaneYork** [jeecgboot/JimuReport#3238]
##### 问题描述：
顶部菜单，支持隐藏显示，比如只用到了大屏，其他两个可以不展示入口

##### 错误日志&截图：
<img width="1278" alt="image" src="https://github.com/user-attachments/assets/881ca96a-7e1c-458d-8091-d779b468327c">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不采纳
