### ISSUE TITLE
横向分组下，excel导出报错

### ISSUE THREAD

**Issue by HyoKaWeng** [jeecgboot/JimuReport#324]
##### 版本号：
v1.3.4-beta

##### 问题描述：
数据报表使用了横向分组时候（这里我用到分组的单元格为C2），点击excel导出，将弹出tip提示:"操作失败，Merged region C2 must contain 2 or more cells"

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/54339660/121809027-c0adc200-cc8d-11eb-91e6-13af186168c6.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
试下这个版本，注意[配置jeecg私服](http://report.jeecg.com/2195924)
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.61-beta</version>
</dependency>
```

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/JimuReport/issues/353

**Comment by HyoKaWeng** [comment]
经测试，横向分组下excel导出已修复，感谢您的答复



在 2021-07-03 19:29:24，"张代浩@JEECG" ***@***.***> 写道：

试下这个版本，注意配置jeecg私服

<dependency>

  <groupId>org.jeecgframework.jimureport</groupId>

  <artifactId>jimureport-spring-boot-starter</artifactId>

  <version>1.3.61-beta</version>

</dependency>
