### ISSUE TITLE
sql方法的下拉参数，不能支持租户

### ISSUE THREAD

**Issue by zwjsoft** [jeecgboot/JimuReport#3240]
##### 版本号：
1.9.1

##### 问题描述：

![image](https://github.com/user-attachments/assets/120f7f7b-a8b3-4622-86d4-d2ae04a75d90)
我用${tenantId} ${tenant_id} #{tenantId} #{tenant_id} 等都没生效

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持
