### ISSUE TITLE
base64图片无法使用

### ISSUE THREAD

**Issue by 1770082850** [jeecgboot/JimuReport#3241]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 1770082850** [comment]
![6](https://github.com/user-attachments/assets/9d405a8a-98ed-427b-a274-ad42222c769d)
![7](https://github.com/user-attachments/assets/f49146d0-20ea-4d3f-bbca-4bd3c6673a8c)
![8](https://github.com/user-attachments/assets/c5535e83-d7a8-4ac1-a89c-62617ac41653)

**Comment by zhangdaiscott** [comment]
升级到最新版试试

**Comment by zhangdaiscott** [comment]
无回复关闭，升级后还有问题请发新issue
