### ISSUE TITLE
在sql里想加个开始时间结束时间的查询，点保存都是正常的  预览的时候就后台报错了

### ISSUE THREAD

**Issue by LuBigChong** [jeecgboot/JimuReport#3242]
##### 版本号：
1.9.1

##### 问题描述：
在sql里想加个开始时间结束时间的查询，点保存都是正常的  预览的时候就后台报错了，好像很缓存有关

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/a10c180d-ff5d-4a3a-8150-3804604855e0)

![image](https://github.com/user-attachments/assets/3e4d8783-d29f-4705-97f6-e1cf2d9c1767)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
给个默认值试试

**Comment by LuBigChong** [comment]
Duplicate of #

> 给个默认值试试

![image](https://github.com/user-attachments/assets/bc484b4c-dcc7-443d-9083-1821e90936e2)
更离谱 ，预览的时候直接页面报错了

**Comment by jeecgos** [comment]
没有复现该问题，你是怎么集成的积木报表？能提供一个最简版的复现项目吗？
![QQ_1733989739345](https://github.com/user-attachments/assets/58ba8bdf-6620-4b0a-9283-729dc913e2a9)
![QQ_1733989765904](https://github.com/user-attachments/assets/1b38846c-30a3-4bf1-b6a8-19386e2dcb64)
