### ISSUE TITLE
新建的数据报表，点击设计按钮修改后再保存，后台就报错json格式有问题

### ISSUE THREAD

**Issue by LuBigChong** [jeecgboot/JimuReport#3243]
##### 版本号：
1.91

##### 问题描述：
新建的数据报表，随便完善好数据之后点保存，回到list页面点击设计按钮，再次点击保存后台就会报错，好像和token有关

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/92598465-d128-4af3-afd2-a540ab84a433)
![image](https://github.com/user-attachments/assets/99db8144-98a3-44c4-9bfc-519a624ba32d)
![image](https://github.com/user-attachments/assets/025a2ef4-f31a-4d95-a86b-e5f9c767753a)

##### 重现步骤：
点击设计按钮进入页面  就算什么都不点，直接点保存按钮后台也会报错

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by limingjie138** [comment]
相同问题 不知道老版本有这个问题不 等待作者解决

**Comment by zhangdaiscott** [comment]
使用的是jeecgboot?

**Comment by LuBigChong** [comment]
> 使用的是jeecgboot?
是的

**Comment by zhangdaiscott** [comment]
录个视频或者详细说明重现步骤

**Comment by zhangdaiscott** [comment]
我这边测试无问题
