### ISSUE TITLE
反斜杠使用富文本无法显示问题

### ISSUE THREAD

**Issue by yongyaoli** [jeecgboot/JimuReport#3245]
##### 问题描述：
数据库：SqlServer
数据中有“\” (业务要求，不能更改显示)，SQL解析正常，预览也正常显示\ .
但是查询报表时反斜杠消失。单元格类型 选择 富文本 也无效
使用 REPLACE 函数 替换为四个 也无效
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
ws

**Comment by jeecgos** [comment]
已修复，待新版本发布

**Comment by yongyaoli** [comment]
使用1.9.1 版本？ @jeecgos

**Comment by jeecgos** [comment]
> 使用1.9.1 版本？ @jeecgos

1.9.2以上版本，还没发，请关注官网。
