### ISSUE TITLE
若依集成积木1.9.1 启动报错怎么解决

### ISSUE THREAD

**Issue by lvsongxiaobai** [jeecgboot/JimuReport#3246]
##### 版本号：
1.9.1

##### 问题描述：
启动报错

##### 错误日志&截图：

![1733974056867](https://github.com/user-attachments/assets/2b02555b-d955-474f-8a8a-4ae819a059e3)

![1733973972048](https://github.com/user-attachments/assets/2289d96e-800f-4998-992d-09576961cc64)

![1733974020661](https://github.com/user-attachments/assets/9dd5160b-db9d-4ab0-bcfc-2c70e2775846)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
fastjon版本冲突？

**Comment by lvsongxiaobai** [comment]
尝试替换版本还是不行

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/JimuReport/issues/3250
