### ISSUE TITLE
关于错误提示返回涉及安全看流动问题

### ISSUE THREAD

**Issue by huangcong92** [jeecgboot/JimuReport#3247]
##### 版本号：
1.8.0

##### 问题描述：
在调用/jmreport/queryFieldBySql 该接口的时候,错误提示返回才产生安全问题,
也没办法在全局捕捉直接返回,因为积木本身就捕捉封装返回了.

##### 错误日志&截图：
错误页面由服务器产生403、404、500等错误时，返回详细错误信息。报错信息中可能会包含服务器代码信息、数据库连接信息、SQL语句或者敏感文件的路径，为攻击者收集信息提供了方便。
![image](https://github.com/user-attachments/assets/0d548a95-63ab-49f9-a420-66e40bb9ad72)
![image](https://github.com/user-attachments/assets/f7cde8ff-3650-4f38-a973-c3065ece3138)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
升级到最新版，我们有改过

**Comment by huangcong92** [comment]
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
