### ISSUE TITLE
1.6.6升级到1.9.1预览无法查看

### ISSUE THREAD

**Issue by Henryyanl** [jeecgboot/JimuReport#3248]
##### 问题描述：
预览无法加载出来，js报错isShowSearchBtnByNoLoad is not defined

##### 错误日志&截图：

![image](https://github.com/user-attachments/assets/babccc56-fd17-43da-8ec7-b422d4928471)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你设计下报表，重新保存下试试

**Comment by zhangdaiscott** [comment]
cr

**Comment by Henryyanl** [comment]
> 你设计下报表，重新保存下试试

我新建的报表也不行

**Comment by jeecgos** [comment]
> > 你设计下报表，重新保存下试试
> 
> 我新建的报表也不行

清一下浏览器缓存试一下

**Comment by Henryyanl** [comment]
> > > 你设计下报表，重新保存下试试
> > 
> > 
> > 我新建的报表也不行
> 
> 清一下浏览器缓存试一下

试过也不可以

**Comment by zhangdaiscott** [comment]
那不应该，那应该还是你升级的问题

**Comment by jeecgos** [comment]
`isShowSearchBtnByNoLoad is not defined` 这个错误应该是你本地的页面和js不匹配导致的。你可以检查一下你那加载的js里有没有`isShowSearchBtnByNoLoad `这个变量。

**Comment by Henryyanl** [comment]
> `isShowSearchBtnByNoLoad is not defined` 这个错误应该是你本地的页面和js不匹配导致的。你可以检查一下你那加载的js里有没有`isShowSearchBtnByNoLoad `这个变量。

如果没有，应该怎么办，我就是改的版本号打了升级脚本，还有什么操作要做吗？

**Comment by jeecgos** [comment]
> > `isShowSearchBtnByNoLoad is not defined` 这个错误应该是你本地的页面和js不匹配导致的。你可以检查一下你那加载的js里有没有`isShowSearchBtnByNoLoad `这个变量。
> 
> 如果没有，应该怎么办，我就是改的版本号打了升级脚本，还有什么操作要做吗？

如果没有这个字段，大概率是你的某个请求链路缓存了js文件，你需要检查下你的项目和环境排查下可能是哪里的问题。

**Comment by jeecgos** [comment]
> > > > `isShowSearchBtnByNoLoad is not defined` 这个错误应该是你本地的页面和js不匹配导致的。你可以检查一下你那加载的js里有没有`isShowSearchBtnByNoLoad `这个变量。
> > > 
> > > 
> > > 如果没有，应该怎么办，我就是改的版本号打了升级脚本，还有什么操作要做吗？
> > 
> > 
> > 如果没有这个字段，大概率是你的某个请求链路缓存了js文件，你需要检查下你的项目和环境排查下可能是哪里的问题。
> 
> 我对比了官网的/jmreport/desreport_/js/biz/view.js，这个里面是有isShowSearchBtnByNoLoad，我这个项目里面没有，浏览器和jar包都清理过了就是不行

你本地jimureport-spring-boot-starter.jar包里view.js 这个文件 有 isShowSearchBtnByNoLoad吗？

**Comment by jeecgos** [comment]
> > > > > > `isShowSearchBtnByNoLoad is not defined` 这个错误应该是你本地的页面和js不匹配导致的。你可以检查一下你那加载的js里有没有`isShowSearchBtnByNoLoad `这个变量。
> > > > > 
> > > > > 
> > > > > 如果没有，应该怎么办，我就是改的版本号打了升级脚本，还有什么操作要做吗？
> > > > 
> > > > 
> > > > 如果没有这个字段，大概率是你的某个请求链路缓存了js文件，你需要检查下你的项目和环境排查下可能是哪里的问题。
> > > 
> > > 
> > > 我对比了官网的/jmreport/desreport_/js/biz/view.js，这个里面是有isShowSearchBtnByNoLoad，我这个项目里面没有，浏览器和jar包都清理过了就是不行
> > 
> > 
> > 你本地jimureport-spring-boot-starter.jar包里view.js 这个文件 有 isShowSearchBtnByNoLoad吗？
> 
> 本地jar包里面有这个，运行起来就是找不到，不知道哪里的问题了。。

那就是你的集成环境的问题了，排查下中间的链路吧。

**Comment by Henryyanl** [comment]
> > > > > > > `isShowSearchBtnByNoLoad is not defined` 这个错误应该是你本地的页面和js不匹配导致的。你可以检查一下你那加载的js里有没有`isShowSearchBtnByNoLoad `这个变量。
> > > > > > 
> > > > > > 
> > > > > > 如果没有，应该怎么办，我就是改的版本号打了升级脚本，还有什么操作要做吗？
> > > > > 
> > > > > 
> > > > > 如果没有这个字段，大概率是你的某个请求链路缓存了js文件，你需要检查下你的项目和环境排查下可能是哪里的问题。
> > > > 
> > > > 
> > > > 我对比了官网的/jmreport/desreport_/js/biz/view.js，这个里面是有isShowSearchBtnByNoLoad，我这个项目里面没有，浏览器和jar包都清理过了就是不行
> > > 
> > > 
> > > 你本地jimureport-spring-boot-starter.jar包里view.js 这个文件 有 isShowSearchBtnByNoLoad吗？
> > 
> > 
> > 本地jar包里面有这个，运行起来就是找不到，不知道哪里的问题了。。
> 
> 那就是你的集成环境的问题了，排查下中间的链路吧。

用的是jeecgboot3.3.0
