### ISSUE TITLE
报表钻取后，查询的值能否与参数的值一致

### ISSUE THREAD

**Issue by amwylig** [jeecgboot/JimuReport#3249]
##### 问题描述：
1.在我使用报表钻取后，得到的报表链接，当我对链接里面的参数做修改后，虽然出来的结果是根据我修改的参数得到的结果，但是查询栏里面的参数依旧是报表参数的默认值，这样很容易会产生误导。

就是我想对链接的参数进行修改的时候，查询栏里面也应该要与链接中的参数所对应的一致。

例如图中的链接参数：riqi=2024-12-08    那么在我回车出来后，查询栏里的日期也应该为：2024-12-08，而不是默认值：=dateStr('yyyy-MM-dd',-1)所计算出来的结果

2.报表钻取后，底部的下划线该如何去掉？？

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/f4fb28cb-f897-4027-9d5a-7a2e2ae25b8a)

![image](https://github.com/user-attachments/assets/dd7bbb53-28ca-455d-b110-6931d214fbec)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
> 2.报表钻取后，底部的下划线该如何去掉？？ 

这个问题是啥意思？

**Comment by amwylig** [comment]
> > 2.报表钻取后，底部的下划线该如何去掉？？
> 
> 这个问题是啥意思？

![image](https://github.com/user-attachments/assets/224d0727-6b53-43df-b8f8-e5165a144603)
就是报表钻取后会强制有下划线出来，怎么也取消不掉

**Comment by zhangdaiscott** [comment]
钻取肯定有链接，没链接用户也不知道是钻取

**Comment by amwylig** [comment]
> 钻取肯定有链接，没链接用户也不知道是钻取

我们领导就觉得这个下划线很碍事，就想把这个下划线给去掉，看看能不能再新版本的时候能通过工作台里面的下划线操作来去掉

![image](https://github.com/user-attachments/assets/b732f57a-099a-4748-9393-92b885fc1718)

**Comment by zhangdaiscott** [comment]
咱不采纳

**Comment by amwylig** [comment]
> 咱不采纳

那我第一个问题能在新版本解决吗

**Comment by jeecgos** [comment]
> > 咱不采纳
> 
> 那我第一个问题能在新版本解决吗

第一个问题会在新版本优化，具体优化方案，我们改好后会再下面告知。

**Comment by jeecgos** [comment]
已优化，待新版本发布
