### ISSUE TITLE
若依老版本3.2.0 集成积木新版本启动报错

### ISSUE THREAD

**Issue by lvsongxiaobai** [jeecgboot/JimuReport#3250]
##### 版本号：

1.9.1
##### 错误日志&截图：

![1733974056867](https://github.com/user-attachments/assets/857eb83a-97df-4ef9-a78b-00273a60814b)

##### 重
![1733973972048](https://github.com/user-attachments/assets/fea4b94e-812c-47a9-8392-3c7891f2cb09)
现步骤：

![1733974020661](https://github.com/user-attachments/assets/fa8f6fee-eaff-49fe-b57a-c24e7d8c318f)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
那个版本，具体架构说明

**Comment by lvsongxiaobai** [comment]
若依前后端分离版 若依3.2.0  springboot2.2.6.RELEASE

**Comment by zhangdaiscott** [comment]
提供源码链接地址

**Comment by lvsongxiaobai** [comment]
好的稍等

**Comment by lvsongxiaobai** [comment]
https://gitee.com/lu-ting-song/zz_data.git

**Comment by lvsongxiaobai** [comment]
可以联系我qq1223576128 感谢感谢

**Comment by jeecgos** [comment]
解决方案：
1. 将`ruoyi-admin/src/main/resources/META-INF/spring-devtools.properties`文件中`restart.include.json=/com.alibaba.fastjson.*.jar`注释掉。
2. `pom`中去掉`spring-boot-devtools`的依赖（建议使用此方案，热加载使用jRebel来替代）。

原因：使用 `spring-boot-devtools` 的时候 项目中的类会使用 `devtools`的 `RestartClassloader` 去加载，而第三方jar中的类会使用默认的`Launcher$AppClassLoader `去加载，如果两个`classloader`加载的类互相有引用就肯呢个会出现这个问题。本例中若依将`fastjson` 的`jar`包`include`到`devtools`中加载了，但是积木报表没有用`devtools`，却用了`fastjson`，此时就出现了上述的同一个`class`被两个不同的类加载器加载的问题。

**Comment by lvsongxiaobai** [comment]
谢谢
