### ISSUE TITLE
新建报表后，要保存报表信息，信息已填写，无法保存，提示信息未填写

### ISSUE THREAD

**Issue by BBBOOO** [jeecgboot/JimuReport#3251]
##### 版本号：

1.8.1
##### 问题描述：
1.从图1从选择文件夹底下的图形报表，进行新建报表，选择数据报表
2.编辑好之后，保存报表信息弹窗中，已经填写好了名称和所属文件夹，但是提示“请填写报表名称”和“请选择报表类型”，无法保存

##### 错误截图：

![图1](https://github.com/user-attachments/assets/54f9acdd-564e-4213-ad40-0c6e9b3d5424)
![图2](https://github.com/user-attachments/assets/4eb2cdbe-71dd-41ba-96c8-95ff44eb53e5)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by BBBOOO** [comment]
> jeecgboot 是那个版本

你好，大神，我们要怎么处理呢

**Comment by zhangdaiscott** [comment]
自己研究，集成问题
