### ISSUE TITLE
报表自动导出插件在哪下载

### ISSUE THREAD

**Issue by usedbdi** [jeecgboot/JimuReport#3252]
##### 版本号：
1.9.1

##### 问题描述：
自动导出插件在哪下载

##### 错误日志&截图：
无

##### 重现步骤：
无

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
暂时不麻烦提供

**Comment by usedbdi** [comment]
![image](https://github.com/user-attachments/assets/f145a8cb-dbdb-47d7-8849-14331b432c9d)
那你这让准备导出插件才能用定时导出，不给插件怎么用啊
