### ISSUE TITLE
关于本地部署如何使用会员组件的问题

### ISSUE THREAD

**Issue by wangqianping** [jeecgboot/JimuReport#3253]
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/809974c5-bd8e-4a08-aded-52a3d1e3786d)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
联系官网商务购买企业版
http://jimureport.com/vip
