### ISSUE TITLE
升级1.9.1版本，进不了BI大屏设计界面

### ISSUE THREAD

**Issue by jiangbr1614** [jeecgboot/JimuReport#3255]
##### 版本号：
1.9.1

##### 问题描述：
升级了1.9.1版本，进不了BI大屏设计界面，进去只能看到仪表盘设计。

**Comment by jiangbr1614** [comment]
![1](https://github.com/user-attachments/assets/830625e9-4126-42e3-b3f8-b45190947fa6)
![2](https://github.com/user-attachments/assets/80e7f75e-810e-4c8f-bf64-a20866ed2a7b)
![3](https://github.com/user-attachments/assets/77615b38-974c-4073-b4fe-cb5cb4edd692)

**Comment by zhangdaiscott** [comment]
![image](https://github.com/user-attachments/assets/797f8272-39cc-43bc-82a9-962dabb8a62c)
这个删了

**Comment by jiangbr1614** [comment]
![1](https://github.com/user-attachments/assets/77d67af0-0bd8-4442-b909-bccb2143c0b9)


![2](https://github.com/user-attachments/assets/c1ddc5ef-71b7-4ab6-ab38-bed8339e48bc)
已经删了，没有用啊，大佬

**Comment by zhangdaiscott** [comment]
说明你maven没升级生效
