### ISSUE TITLE
minidao 报错 必须提供MemberAccess实现

### ISSUE THREAD

**Issue by yangleyang9696** [jeecgboot/JimuReport#3256]
##### 版本号：
1.9.1

##### 问题描述：
刚引入到pom开始集成, 启动报错

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/d0ebaaa3-115a-4084-b6bb-0f4907a07b8b)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
说明依赖冲突了可能是minidao
自己排除旧版本
