### ISSUE TITLE
ruoyi-vue集成BI模块无法进入仪表板设计页面

### ISSUE THREAD

**Issue by git-wangzd** [jeecgboot/JimuReport#3257]
##### 问题描述：用ruoyi-vue集成BI模块，点击仪表板的设计按钮，跳转不到设计页面，token验证已经重写，报表模块是正常的。
并且请求都没有dev-api的前缀了

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/604952b0-4760-48f7-945f-df7c60ae2adb)
![image](https://github.com/user-attachments/assets/919a8592-7658-47ce-aae0-47ba57ab590c)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
百度下错误，不太清楚，还是跟你集成环境有关
