### ISSUE TITLE
积木报表BI大屏被拦截

### ISSUE THREAD

**Issue by jiangbr1614** [jeecgboot/JimuReport#3258]
##### 版本号：
3.7.2

##### 问题描述：
升级完3.7.2后，使用BI大屏设计器，在数据源连接测试的时候，报错null，查看后台报错日志，说的是低代码模式，拦截请求路径：/drag/onlDragDataSource/testConnection， 那这个时候我是应该吧applicaton.dev.yml 的jeecg.lowCodeMode 从prod变为dev吗。
还是说在ShiroConfig.java 当中加点什么。
还有这里的分配角色admin、lowdeveloper可以放开限制，是jeecg角色定义一个叫admin的角色吗
##### 错误日志&截图：

![1](https://github.com/user-attachments/assets/4f538dfb-fa2a-4063-ae9d-d9f195626195)
![2](https://github.com/user-attachments/assets/e9dc4fcb-7419-4f9d-ad70-9688f4e30ac4)
![3](https://github.com/user-attachments/assets/b6129237-f87a-438d-9953-9f66433eb102)

**Comment by zhangdaiscott** [comment]
角色code 是admin 或者 lowdeveloper

**Comment by zhangdaiscott** [comment]
你用的是啥啊，不是jeecgboot吧，为啥写3.7.2，这边测jeecgboot最新版没问题
