### ISSUE TITLE
自动换行后默认打印时单元格中内容超出

### ISSUE THREAD

**Issue by Scarecrow12138** [jeecgboot/JimuReport#3259]
##### 版本号：
1.9.1

##### 问题描述：
1. 打印设计界面,部分格子设置自动换行,但是在打印界面中是正确的没有发生超出(见图一)
2. 在积木报表的打印预览页面也正常也没有发生超出(见图二)
3. (重点!重点!) 点击默认打印,系统的打印预览页面,所有设置自动换行的格子都发生了超出(见图三)

##### 错误日志&截图：
图一 ↓
![image](https://github.com/user-attachments/assets/38c3ce05-3095-46da-9cb9-b5108bec944d)

图二
![image](https://github.com/user-attachments/assets/d1c90585-41f6-4713-9bd2-c4f9f5ef7c81)

图三
![image](https://github.com/user-attachments/assets/63b89d2c-9acd-4f8e-ba82-68c2b6a56b0f)

##### 重现步骤：
目前报表都是静态的文字  可直接导入报表配置文件尝试复现问题
[SalesContract.json](https://github.com/user-attachments/files/18139428/SalesContract.json)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
zy

**Comment by jeecgDeveloper** [comment]
已修复，下一版本发布。

**Comment by jeecgDeveloper** [comment]
已修复，下一版本发布

**Comment by Scarecrow12138** [comment]
6的

**Comment by Scarecrow12138** [comment]
作者大大 给你发了一封求助邮件  能否帮下忙!!
