### ISSUE TITLE
传参报表 下拉框可选项 多于实际内容

### ISSUE THREAD

**Issue by EvilMir** [jeecgboot/JimuReport#326]
##### 版本号：
1.3.4-beta

##### 问题描述：
传参报表 下拉框可选项 多余实际内容
直接sql查询结果只有2条，但是下拉框貌似把所有信息都拉出来了
这个下拉列表的获取好像并不关心这个参数条件？还是哪里需要设置？
##### 截图&代码：

![报价书](https://user-images.githubusercontent.com/13412832/122326408-d7d70300-cf5e-11eb-88a4-5614785ba77d.png)
![报价书1](https://user-images.githubusercontent.com/13412832/122326422-dc032080-cf5e-11eb-980b-f51ffdcc4707.png)
![报价书2](https://user-images.githubusercontent.com/13412832/122326429-ddcce400-cf5e-11eb-8838-a79ea02030c3.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布，当前是跟据浏览器中的拼参数来下拉框复值的
