### ISSUE TITLE
升级到1.9.1，仪表盘设计器添加不了组件

### ISSUE THREAD

**Issue by a123456wlzhyy** [jeecgboot/JimuReport#3260]
##### 错误日志&截图：
<img width="1112" alt="image" src="https://github.com/user-attachments/assets/68c58aaa-a29a-4a08-a189-a333d773e48c" />
<img width="729" alt="image" src="https://github.com/user-attachments/assets/3d68a294-242c-4dfe-9bfc-c13caa054008" />
<img width="732" alt="image" src="https://github.com/user-attachments/assets/c7755078-9232-4f20-8bc8-64db77638553" />

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你是什么项目

**Comment by zhangdaiscott** [comment]
我测了下
https://github.com/jeecgboot/JimuReport/tree/master/jimureport-example

没问题

**Comment by zhangdaiscott** [comment]
测试jeecgboot最新版也无问题

**Comment by a123456wlzhyy** [comment]
ok 可能是组件冲突，我再看看吧

**Comment by a123456wlzhyy** [comment]
我用jeecgboot最新版仍然有此问题，跟我用的是postgresql数据库有关吗

**Comment by zhangdaiscott** [comment]
仪表盘不是拖，是点击
