### ISSUE TITLE
大屏分享以后还是不能打开，必须登入才行

### ISSUE THREAD

**Issue by wangqianping** [jeecgboot/JimuReport#3262]
##### 问题描述：
大屏分享勾选了无需校验，且SpringSecurity放开了/drag/share/view/**的权限，依旧无法直接打开分享的大屏页面，浏览器F12报错如下

##### 错误日志&截图：

![image](https://github.com/user-attachments/assets/cd72acf4-f754-46cf-8a49-ec3a6e8002c9)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
@wangqianping  SpringSecurity 不能只放开`/drag/share/view/**`。可以参考下example项目中的security配置。https://github.com/jeecgboot/JimuReport/blob/master/jimureport-example/src/main/java/com/jeecg/modules/jmreport/config/SpringSecurityConfig.java
