### ISSUE TITLE
微服务项目集成报表, 使用自己项目的token

### ISSUE THREAD

**Issue by yangleyang9696** [jeecgboot/JimuReport#3263]
##### 版本号：
1.9.2

##### 问题描述：
1.微服务项目集成报表
2.如何使用自己项目的网关和token?
3.实现 JmReportTokenServicel 中的 customApiHeader 不生效
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/e5017c5c-664b-42c4-9932-6000979d67f1)

![image](https://github.com/user-attachments/assets/eb0f26db-fa0d-4e10-8528-7fef23d74ab7)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
应该还是集成的不对，可以自己打点日志

**Comment by jeecgos** [comment]
你需要实现的是`verifyToken(String token)` 以及 `getToken(HttpServletRequest request)`这两个方法。

**Comment by jeecgos** [comment]
暂不支持，归集：#138
