### ISSUE TITLE
空白单元格，加入边框线后，导出边框线的单元格会加空格

### ISSUE THREAD

**Issue by lj980911** [jeecgboot/JimuReport#3265]
##### 问题描述：
新建一个报表后，空白的单元格加入边框线后，预览导出后，会在空白的单元格自动加入空格

##### 错误日志&截图：
这个是创建后
![1734328919678](https://github.com/user-attachments/assets/9353db20-12a2-4983-a856-afec9bc33077)
所有空白带有表格线的都会里面带一个空格
![1734329079650](https://github.com/user-attachments/assets/356fc38e-7f46-458e-aed1-a5545bb361a1)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
ws

**Comment by jeecgos** [comment]
已修复，待新版本发布
