### ISSUE TITLE
js增强动态传参或者系统变量

### ISSUE THREAD

**Issue by lhw6509650** [jeecgboot/JimuReport#3267]
##### 版本号：
1.9.0
##### 问题描述：

js增强动态传参或者系统变量
##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/c6ac31a5-7da2-4b3a-b214-59fb798bd530)
比如像上面那样

**Comment by jeecgos** [comment]
ws

**Comment by jeecgos** [comment]
已修复，待新版本发布，后续版本支持系统变量
