### ISSUE TITLE
SpringBoot3 集成后页面为空白

### ISSUE THREAD

**Issue by Q3B0** [jeecgboot/JimuReport#3268]
##### 问题描述：
SpringBoot3 版本集成后打开页面为空白，不报错

##### 错误日志&截图：

![image](https://github.com/user-attachments/assets/72b7e058-8bd2-44c9-8ee0-68007b10c2c0)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/jimureport/SpringBoot3zhichi.html
集成对应的版本

**Comment by Q3B0** [comment]
![image](https://github.com/user-attachments/assets/fb9670ae-8b47-4972-8391-553310539b8d)
集成的是SpringBoot3的版本
多数据源有影响么？

**Comment by zhangdaiscott** [comment]
不知道，自己排查原因，其他用户使用正常
