### ISSUE TITLE
数据填报对于移动端适配

### ISSUE THREAD

**Issue by 13813586515** [jeecgboot/JimuReport#3270]
##### 问题描述：
数据填报页想内切到移动端，样式无法自适应

##### 错误日志&截图：
由于内容铭感，暂时不能截图

##### 重现步骤：
1.新增数据填报
2.内嵌到小程序内，样式无法自适应
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持移动端
