### ISSUE TITLE
【严重bug】大屏实时时间组件：星期几不会随着日期改变。

### ISSUE THREAD

**Issue by yangyang56452** [jeecgboot/JimuReport#3272]
##### 版本号：
码云下载的项目：https://gitee.com/jeecg/JimuReport#jimureport%E7%A7%AF%E6%9C%A8%E6%8A%A5%E8%A1%A8%E5%85%8D%E8%B4%B9%E6%8A%A5%E8%A1%A8%E5%B7%A5%E5%85%B7
v1.9.1 | 2024-12-05

##### 问题描述：
大屏的实时时间组件，星期几不会随着时间变化，昨天打开是周一，今天时间过了一天，依旧是周一。这是一个f非常严重的Bug。希望官网尽快解决，谢谢

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/59c0f621-3416-4767-8a92-12ba77ee9596)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
好

**Comment by jeecgDeveloper** [comment]
已修改，下版本发布
