### ISSUE TITLE
【咨询】想在api数据查询时带上用户信息

### ISSUE THREAD

**Issue by grnv1** [jeecgboot/JimuReport#3275]
##### 版本号：
1.9.1

##### 问题描述：
在使用数据报表功能是，我们希望建立一个月度数据统计报表，我们有两个需求，一个是通过月份选择可以让表头显示不同月数据统计，并且在调用api数据库的查询接口时带上所选的时间。另一个是让不同的人查看报表时依照那个人的数据权限只看到他能看到的部分数据，也就是在调用api数据库的带上用户token。请问这两个需求要怎么实现？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
如果你采用的是api数据集，默认调用apiheader里面就带着token，数据隔离自己做就行

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
