### ISSUE TITLE
是否支持分组汇总功能

### ISSUE THREAD

**Issue by jerrysbest** [jeecgboot/JimuReport#3276]
##### 版本号：
1.9.1
##### 问题描述：

不支持分组汇总功能
##### 错误日志&截图：
<img width="662" alt="1734417862923" src="https://github.com/user-attachments/assets/cfae2d89-a3f8-4612-92d2-7e348307df51" />

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
参考
https://help.jeecg.com/jimureport/group/verticalSubtotal.html
