### ISSUE TITLE
点击设计之后之前的复杂柱形图的配置数据会丢失

### ISSUE THREAD

**Issue by 1095321607** [jeecgboot/JimuReport#3278]
##### 版本号：
1.9.1

##### 问题描述：
点击设计之后之前的复杂柱形图的配置数据会丢失

##### 错误日志&截图：

![image](https://github.com/user-attachments/assets/08cba6a6-f0bb-4710-b27f-863770b66015)
![image](https://github.com/user-attachments/assets/18807e83-3dab-429a-9a1c-c88e51599759)

##### 重现步骤：
新建复杂图表，保存退出，点击设计

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 1095321607** [comment]
刚刚我用JimuReport项目试了一下也是一样的，点击设计进去之后他会默认展示之前的样子，如下图
![image](https://github.com/user-attachments/assets/ab63a276-e59d-4c80-a619-2f251f1cae52)
然后等到再次渲染（有快有慢）如下
![image](https://github.com/user-attachments/assets/cf41bb50-636a-4fe4-99aa-3d648f1b7243)
然后点击图表那里就没数据了
![image](https://github.com/user-attachments/assets/468336df-a58f-4267-9131-eddad2800d21)

**Comment by 1095321607** [comment]
如果在图表重新渲染之前点击图表数据就能保留

**Comment by zhangdaiscott** [comment]
录个视频

**Comment by jeecgos** [comment]
cr

**Comment by jeecgos** [comment]
未复现，请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

> 原本不需要参数的接口改成需要参数：
![image](https://github.com/user-attachments/assets/db51dd69-4396-4967-9319-1343542b2854)
![image](https://github.com/user-attachments/assets/4b47b88b-2fb6-4600-9f7c-b6b635978cb5)
重新进入设计页面，报表的数据绑定未丢失：
![image](https://github.com/user-attachments/assets/bf53c2e3-18b6-4a94-8607-c130847137c2)

**Comment by 1095321607** [comment]
我在线大致操作出来了一个 你们看看为什么没渲染 1031011458018004992
![image](https://github.com/user-attachments/assets/2acf4425-202a-4ad1-9446-910ac34e4e9d)
用的你们的测试样例，这么配置应该是有数据的吧,而且这个图表已经无法编辑了，点击保存虽然提示保存成功，但是退出去再进来参数是空的，可能问题就是配置保存失败了的问题

**Comment by jeecgos** [comment]
已修复，请等待新版本发布。

**Comment by 1095321607** [comment]
好的，感谢回复

**Comment by 1095321607** [comment]
还是没有修复核心问题啊，就比如在线的这个例子，虽然图表的配置保存下来了  但是图表还是无法渲染

**Comment by 1095321607** [comment]
![image](https://github.com/user-attachments/assets/7c36105b-5a24-4069-9bc6-255df1679b00)

**Comment by jeecgos** [comment]
#3392
