### ISSUE TITLE
无法打印日志

### ISSUE THREAD

**Issue by 13813586515** [jeecgboot/JimuReport#3283]
##### 版本号：
1.9.1

##### 问题描述：
1.8.1升级到1.9.1后，日志不打印，回退1.8.1版本日志可以打印

##### 错误日志&截图：
![image](https://github.com/user-attachments/assets/0af3e5c8-3332-47a2-b691-2120b75d47e5)
已开启了日志打印

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
什么日志

**Comment by 13813586515** [comment]
> 什么日志

https://help.jeecg.com/jimureport/projectJoin/springboot.html
![image](https://github.com/user-attachments/assets/180cbd1f-1ae5-46b1-ae6c-a9d91c0bbf7d)

**Comment by zhangdaiscott** [comment]
你想打印什么日志，新版把日志都注释了

**Comment by 13813586515** [comment]
> 你想打印什么日志，新版把日志都注释了

还能打印什么日志。。。。，肯定是参数和脚本啊，把日志注释掉了，参数传的对不对都不知道了。。。

**Comment by zhangdaiscott** [comment]
下个版本考虑保留部分
