### ISSUE TITLE
多源报表可否实现复杂表头

### ISSUE THREAD

**Issue by yangleyang9696** [jeecgboot/JimuReport#3284]
##### 版本号：
1.9.1

##### 问题描述：
1. 使用主子报表
2. 主数据用于实现 主键, 账号, 姓名 列, 纵向展示
3. 子数据用于实现后面的统计横向数据
4. 由于真实业务场景统计过于复杂, 该报表无法通过一个 SQL 实现
##### 错误日志&截图：

![image](https://github.com/user-attachments/assets/f24270f1-0d87-47f1-8b7a-0791d620a2c7)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
cr

**Comment by jeecgos** [comment]
暂不支持多源报表横向动态扩展，归集：#138
