### ISSUE TITLE
数据源安全模式下，禁止使用数据源连接测试！  

### ISSUE THREAD

**Issue by killuato27** [jeecgboot/JimuReport#3285]
##### 问题描述：
数据源安全模式下，禁止使用数据源连接测试！  

##### 错误日志&截图：
配置oracle连接串的时候，提示这个

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/jimureport/prodSafe.html

**Comment by killuato27** [comment]
> https://help.jeecg.com/jimureport/prodSafe.html

设置 lowCodeMode：prod ，可以彻底关闭在线报表设计，屏蔽所有风险；

这个在哪设置来着
