### ISSUE TITLE
大屏报表，在手机端查看时，为何在每个格子中的图表会滑动，影响整个手机页面上下滑动

### ISSUE THREAD

**Issue by JerryLiu69** [jeecgboot/JimuReport#3287]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
@JerryLiu69  请按照格式发帖，注明 版本号，图文问题描述以及复现步骤。
