### ISSUE TITLE
1.9.0 预览空白  Cannot read property 'isRpFirstLoad' of undefined

### ISSUE THREAD

**Issue by yongyaoli** [jeecgboot/JimuReport#3288]
##### 问题描述：
添加数据源后 ，预览报表时 控制台报错 预览空白
TypeError: Cannot read property 'isRpFirstLoad' of undefined
    at handleChartData (view.js?v=1730276111.10:110)
    at view.js?v=1730276111.10:10
    at Object.success (manager.js?v=1730276111.10:4)
    at request.js?v=1730276111.10:10

##### 错误日志&截图：

![000](https://github.com/user-attachments/assets/bd0e2766-2a4c-4c7b-b7f4-a8a721d36fca)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
数据库的升级sql都执行了吗
http://jimureport.com/doc/log

**Comment by yongyaoli** [comment]
仪表盘部分没有使用，所以仪表盘部分的SQL没有执行。其他的都执行过了

**Comment by zhangdaiscott** [comment]
清下浏览器缓存试试

**Comment by yongyaoli** [comment]
使用谷歌浏览器，清除全部缓存后问题依旧。F12看到是下面这里报的错
![11111](https://github.com/user-attachments/assets/4f393f58-1d4b-45f0-b38b-9d7a7d98067e)

**Comment by yongyaoli** [comment]
![11111](https://github.com/user-attachments/assets/e425ba2f-57af-46c3-8789-f7631f163c55)

**Comment by jeecgos** [comment]
@yongyaoli 删掉本地maven仓库里的 jimureport-spring-boot-starter:1.9.0  重新下一个试试

**Comment by yongyaoli** [comment]
@jeecgos  本地maven仓库 全部删掉 重新下载，重新打包，依然是这样的情况。

**Comment by jeecgos** [comment]
> @jeecgos 本地maven仓库 全部删掉 重新下载，重新打包，依然是这样的情况。

你看下你的页面上请求的 js的版本号是什么，1.9.0版本,最新的版本号应该是1730459714.10 。如果不是那代表你的jar还是旧的，清理maven缓存、清理ide缓存，重新打包再看看。

**Comment by yongyaoli** [comment]
现在是版本是：1730276111.10
我清除了ide缓存
![1734707222568](https://github.com/user-attachments/assets/513d8a88-8d7a-444c-999d-68447f507b15)
也彻底删除了repository文件夹，进行重新下载，但是包出来依然还是1730276111.10
![1734707334915](https://github.com/user-attachments/assets/c00ad347-f42e-4ec4-960f-bdb0cfeb6972)
我用的另外一个包，不能本地启动，有什么办法可以本地看这个版本号吗？

**Comment by zhangdaiscott** [comment]
直接升级到最新版，或者让别人试试
