### ISSUE TITLE
仪表盘中的统计插件，是否可以支持小数点数据展示

### ISSUE THREAD

**Issue by su20241001** [jeecgboot/JimuReport#3292]
##### 版本号：
最新版本

##### 问题描述：
![image](https://github.com/user-attachments/assets/c87caa84-680e-41e7-8a8e-dff4e6f057b4)
请问：
上面的数据是否支持小数点展示，在某些情况下，数据要到小数点后6位。现在直接给我四舍五入了。
不知道是否可以支持。
例如：
2000 展示 2000
2000.1456 展示 2000.1456

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
重复问题不要提多次
