### ISSUE TITLE
报表管理填报栏自定义组件

### ISSUE THREAD

**Issue by liangdd77** [jeecgboot/JimuReport#3293]
##### 版本号：

1.9.1
##### 问题描述：
报表管理填报栏怎么添加自定义前端组件

##### 错误日志&截图：
![1734688834755](https://github.com/user-attachments/assets/04159c8d-a036-488b-9940-6a02bc568a8e)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持自定义
