### ISSUE TITLE
下拉框 Api接口 自定义URI无效

### ISSUE THREAD

**Issue by dhlmango** [jeecgboot/JimuReport#3296]
##### 问题描述：
填报报表-下拉框-自定义环境变量URI无效

##### 错误日志&截图：
<img width="1444" alt="image" src="https://github.com/user-attachments/assets/df38832f-0390-4fe2-a905-13f8a59b5518" />
由于默认的环境变量满足不了需求，自定义#{http}环境变量， 在编辑报表界面 配置地址之后 触发到了此接口。 但是后续预览使用的时候没有触发调用该接口，也没有报错日志。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持这么用法
