### ISSUE TITLE
设计无法保存

### ISSUE THREAD

**Issue by KissSleep510** [jeecgboot/JimuReport#3297]
##### 版本号：
v1.9.1

##### 问题描述：
数据报表视图导出excel之后无法设计

##### 错误日志&截图：
[localhost-1734849038541.log](https://github.com/user-attachments/files/18220962/localhost-1734849038541.log)
![无法保存](https://github.com/user-attachments/assets/1403d7cf-9f5a-46b6-ade4-27dc59efa1ba)

##### 重现步骤：
设计报表保存完成之后 查看视图 导出excel
重新设计报表 无法进行保存

[测试.json](https://github.com/user-attachments/files/18220937/default.json)
[测试_1734847887295.xlsx](https://github.com/user-attachments/files/18220938/_1734847887295.xlsx)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
随便找个报表吗，还是什么特殊场景下

**Comment by KissSleep510** [comment]
目前尝试了其他自带的报表 同样出现了无法进行保存
![image](https://github.com/user-attachments/assets/3c26f043-9de5-4a43-903b-fa1b2e8e2364)

**Comment by KissSleep510** [comment]
导出报表配置之后是否还可以进行报表设计保存
重新测试 在导出配置之后无法进行设计保存
![image](https://github.com/user-attachments/assets/ec05b363-f0a5-460d-964f-9c1516663fc4)

**Comment by zhangdaiscott** [comment]
cr

**Comment by zhangdaiscott** [comment]
经过测试无问题，看看报什么错，截图出来
我们的升级sql都执行了吗，确认
http://jimureport.com/doc/log

**Comment by KissSleep510** [comment]
使用的是windows免安装版本v1.9.1
是否是这个错误报告
![Snipaste_2024-12-22_16-45-11](https://github.com/user-attachments/assets/16b64292-4bac-4a7d-aa06-d1c9d176d3b3)
[报错文档.txt](https://github.com/user-attachments/files/18221271/default.txt)


这是我的sql文件和报表设计配置
[测试.json](https://github.com/user-attachments/files/18221248/default.json)
![sql1](https://github.com/user-attachments/assets/35135816-cdd0-4ae6-9770-7b09932714f7)
![sql2](https://github.com/user-attachments/assets/564079ad-3a26-462e-83ec-2188a178893a)

目前的情况就是导入报表设计配置之后无法进行设计 无法具体确定是什么原因导致

**Comment by zhangdaiscott** [comment]
数据库是新的还是旧的

**Comment by KissSleep510** [comment]
需要更新吗
![image](https://github.com/user-attachments/assets/3884da88-ee06-4351-a8f9-ab106b2b31d5)

**Comment by zhangdaiscott** [comment]
绿色版测试也无问题
![image](https://github.com/user-attachments/assets/9af68ecf-5bc7-4c64-b7d6-fa3c613fdb2a)

**Comment by KissSleep510** [comment]
导入此报表设计配置之后无法进行设计
[测试.json](https://github.com/user-attachments/files/18221495/default.json)

**Comment by zhangdaiscott** [comment]
无法重现

**Comment by jeecgos** [comment]
@KissSleep510 重新下载一个新的免安装版，注意下start的创建时间不小于12.19
![image](https://github.com/user-attachments/assets/0c5ce987-7eec-40f2-a1bc-7c591735e26c)

**Comment by KissSleep510** [comment]
问题已解决
________________________________
发件人: 积木Developer ***@***.***>
发送时间: 2024年12月23日 15:35
收件人: jeecgboot/JimuReport ***@***.***>
抄送: KissSleep ***@***.***>; Mention ***@***.***>
主题: Re: [jeecgboot/JimuReport] 设计无法保存 (Issue #3297)


@KissSleep510<https://github.com/KissSleep510> 重新下载一个新的免安装版，注意下start的创建时间不小于12.19
image.png (view on web)<https://github.com/user-attachments/assets/0c5ce987-7eec-40f2-a1bc-7c591735e26c>

―
