### ISSUE TITLE
如何修改jimubi的logo图标

### ISSUE THREAD

**Issue by adujunyi** [jeecgboot/JimuReport#3298]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
免费版不支持，可以联系官网企业版http://jimureport.com/vip

**Comment by adujunyi** [comment]
怎么收费的呀？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月23日(周一) 下午4:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/JimuReport] 如何修改jimubi的logo图标 (Issue #3298)




 
免费版不支持，可以联系官网企业版http://jimureport.com/vip
