### ISSUE TITLE
实现JmReportTokenServiceI  自定义token接口 访问积木报表报错403

### ISSUE THREAD

**Issue by lvsongxiaobai** [jeecgboot/JimuReport#3299]
##### 版本号：
1.9.1

##### 错误日志&截图：

![1734942179439](https://github.com/user-attachments/assets/a3e4b15d-9062-41ca-9442-6075e1554d4d)

![1734942209214](https://github.com/user-attachments/assets/b98a83fe-8080-4360-8653-b1581181177d)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
跟token没关系吧  403是资源请求不到

**Comment by zhangdaiscott** [comment]
无回复关闭
