### ISSUE TITLE
测试环境用jara包，调用接口为啥token和cookies是用Base64加密了，导致和我系统的格式不一样，401了

### ISSUE THREAD

**Issue by grnv1** [jeecgboot/JimuReport#3301]
##### 问题描述：
测试环境用jara包，调用接口为啥token和cookies是用Base64加密了，导致和我系统的格式不一样，401了

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
请补充版本号并图文描述问题和复现步骤。

**Comment by jeecgos** [comment]
因长时间未回复，暂时关闭此问题
