### ISSUE TITLE
多数据对比柱形图 提示语 是否可进行百分比显示

### ISSUE THREAD

**Issue by yongyaoli** [jeecgboot/JimuReport#3303]
##### 问题描述：
多数据对比柱形图 提示的数值是否能按百分比进行显示？

##### 错误日志&截图：
![图片](https://github.com/user-attachments/assets/38e4b919-2aed-402c-b4ea-9451061281f2)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
暂不支持，归集：#138
