### ISSUE TITLE
男女性别象形图静态数据对应错误

### ISSUE THREAD

**Issue by wangqianping** [jeecgboot/JimuReport#3305]
##### 问题描述：
数据和图例反了

##### 错误日志&截图：

![image](https://github.com/user-attachments/assets/522b3fd9-869b-45f9-b4be-7ee5df9f771e)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
sq

**Comment by jeecgDeveloper** [comment]
已修改，下版本更新
