### ISSUE TITLE
积木报表缓存

### ISSUE THREAD

**Issue by usedbdi** [jeecgboot/JimuReport#3306]
##### 版本号：
1.9.1

##### 问题描述：
报表图标缓存问题

##### 错误日志&截图：
无

##### 重现步骤：
我从别的项目复制过来的程序，有一个sql 数据源，sql语句在数据库能正常执行且正常出现数据，但是放到报表里预览就是不行，没有数据，且饼状图还是原来旧项目的数据。我想问项目的是不是有缓存啊，在那清除

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
报表预览没有缓存，能提供复现的示例项目吗？

**Comment by zhangdaiscott** [comment]
无回复关闭
