### ISSUE TITLE
积木仪表盘表格组件配置按钮传递数据到服务端报错

### ISSUE THREAD

**Issue by lhw6509650** [jeecgboot/JimuReport#3309]
##### 版本号：
1.9.1
##### 问题描述：
积木仪表盘表格组件配置按钮传递数据到服务端报错

##### 错误日志&截图：
![6bc74f2899c52c81fff47ce43536ee9e](https://github.com/user-attachments/assets/0b51c387-521b-440a-8f7f-1082eac0e005)
![944c9e5c3f0516db3ccb12f51b32cd51](https://github.com/user-attachments/assets/2fd3d35a-1874-43cf-92fc-4114b2cbe0a6)
到readValue就报错了，下面的读chartId，数据里没有这个字段
![ea648376285ff49848f016942c6cfb42](https://github.com/user-attachments/assets/9faada05-d5b9-45c5-9ad3-1c0e8ca427be)

**Comment by jeecgos** [comment]
sq

**Comment by jeecgos** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by jeecgDeveloper** [comment]
已修改，下版本更新

**Comment by lhw6509650** [comment]
![image](https://github.com/user-attachments/assets/a976cc83-78d7-4f1b-8799-2069441febd5)
1.9.3还未修复啊，这个交互是不是就用不了啊

**Comment by jeecgDeveloper** [comment]
> ![image](https://github.com/user-attachments/assets/a976cc83-78d7-4f1b-8799-2069441febd5) 1.9.3还未修复啊，这个交互是不是就用不了啊 [@zhangdaiscott](https://github.com/zhangdaiscott) [@jeecgDeveloper](https://github.com/jeecgDeveloper)

描述一下你是怎么配置使用的，截图详细说明一下操作步骤

**Comment by jeecgDeveloper** [comment]
> ![image](https://github.com/user-attachments/assets/a976cc83-78d7-4f1b-8799-2069441febd5) 1.9.3还未修复啊，这个交互是不是就用不了啊 [@zhangdaiscott](https://github.com/zhangdaiscott) [@jeecgDeveloper](https://github.com/jeecgDeveloper)

参考 文档 https://help.jeecg.com/jimureport/drag/baseopera/chart/interactive/tablebtn.html
