### ISSUE TITLE
使用若依前后端分离版本ruoyiVue(3.8.8版本)，集成积木报表1.9.1版本，启动报错

### ISSUE THREAD

**Issue by wshagcl** [jeecgboot/JimuReport#3311]
##### 版本号：
1.9.1

##### 问题描述：
使用若依前后端分离版本ruoyiVue(3.8.8版本)，集成积木报表1.9.1版本，启动报错

##### 错误日志&截图：
![微信截图_20241226143954](https://github.com/user-attachments/assets/e19588b0-88c9-473d-9e72-4e97b841f313)
***************************
APPLICATION FAILED TO START
***************************

Description:

Field taskScheduler in org.jeecg.modules.jmreport.automate.service.a.a required a bean of type 'org.springframework.scheduling.TaskScheduler' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'org.springframework.scheduling.TaskScheduler' in your configuration.

##### 重现步骤：
已经按照文档中配置了（https://help.jeecg.com/jimureport/projectJoin/ruoyivue.html）

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by turnip3579** [comment]
已通过查看之前关闭的问题解决，是ruoyi热部署pom引入导致的

**Comment by wshagcl** [comment]
> 已通过查看之前关闭的问题解决，是ruoyi热部署pom引入导致的

找到的类似问题，错误不都相同。请指明具体问题编号

**Comment by turnip3579** [comment]
> > 已通过查看之前关闭的问题解决，是ruoyi热部署pom引入导致的
> 
> 找到的类似问题，错误不都相同。请指明具体问题编号

是这个问题，老师 https://github.com/jeecgboot/JimuReport/issues/3250

**Comment by wshagcl** [comment]
> > > 已通过查看之前关闭的问题解决，是ruoyi热部署pom引入导致的
> > 
> > 
> > 找到的类似问题，错误不都相同。请指明具体问题编号
> 
> 是这个问题，老师 #3250

按照这个操作没有解决问题。而且错误原因跟这个#3250也不一样啊。

**Comment by jeecgos** [comment]
已修复，下个版本发布。
**临时解决**方案：
在若依中添加
```
package com.ruoyi.framework.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.scheduling.TaskScheduler;
import org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler;

@Configuration
public class SchedulerConfig {
    @Bean
    public TaskScheduler taskScheduler() {
        return new ThreadPoolTaskScheduler();
    }
}
```
