### ISSUE TITLE
图表是否可以筛选现有数据源？

### ISSUE THREAD

**Issue by yongyaoli** [jeecgboot/JimuReport#3312]
##### 问题描述：
我有一个数据源A1， 全量数据，是否可以 仪表盘使用指定的某条数据，饼状图取这个数据源的全部数据？
现在只能写两个数据源 分别对两个图表指定数据源吗？

##### 错误日志&截图：
![1735203488828](https://github.com/user-attachments/assets/cdb58d05-89ec-4a84-8ba8-52b896a69377)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
不支持
