### ISSUE TITLE
iframe嵌入报表调用提交api找不到

### ISSUE THREAD

**Issue by itsldy** [jeecgboot/JimuReport#3315]
##### 版本号：
1.9.1

##### 问题描述：
启动免安装版jar包，设计填报报表通过iframe嵌入报表分享链接，提交api请求失败；浏览器直接打开分享链接提交数据api请求成功。

##### 错误日志&截图：
接口重定型302
![19bdf3e6239c3ddc7eec6034eb27516](https://github.com/user-attachments/assets/acf43959-abbe-4c41-ae03-34ad10f86645)

##### 重现步骤：
1.启动桌面版本
![image](https://github.com/user-attachments/assets/36fcad0c-8f96-4add-bbda-31bd81a7cb9c)
2.设置填报数据源
![image](https://github.com/user-attachments/assets/babcfe80-965b-4c47-899a-82011d85ea3d)
3.嵌入iframe
![image](https://github.com/user-attachments/assets/5ebf200c-551f-4bbd-96b9-df6ee8a8494c)
4.提交数据
![image](https://github.com/user-attachments/assets/c92ed73f-3f20-43c9-9cca-5c2e80717a3e)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
集成问题，你需要自己处理。
应该是触发了浏览器的安全限制。可以检查下积木报表的域名和嵌入系统的域名一致吗？

**Comment by itsldy** [comment]
我这里使用的是node后台，并不能使用官网的集成方式，使用window版进行报表嵌入会遇到上述问题。是否可以提供解决方案？

**Comment by jeecgos** [comment]
> 我这里使用的是node后台，并不能使用官网的集成方式，使用window版进行报表嵌入会遇到上述问题。是否可以提供解决方案？

我这里积木报表通过iframe嵌入网页是没有问题的。
![image](https://github.com/user-attachments/assets/9b9a7a73-d4f4-4764-a8b8-858618abc6b0)


你那里应该是触发了浏览器的安全限制，你可以检查下这个 警告，针对自己的架构查下解决方案。
![image](https://github.com/user-attachments/assets/ad0488c1-1bd7-4afd-b9fb-8da635d3b6d0)

**Comment by zhangdaiscott** [comment]
![image](https://github.com/user-attachments/assets/f251fbe3-12cc-428f-b613-670fd213a2ff)
https://ojrjjvdr7z.k.topthink.com/jimureport/config/yaml.html
