### ISSUE TITLE
请官方回复下啊主子表问题优化方案

### ISSUE THREAD

**Issue by xtsora** [jeecgboot/JimuReport#332]
##### 版本号：
1.3.5-beta

##### 问题描述：
主子表问题
1：更新之后的主子表，按照官方配置之后（但未设置查询条件），将参数拼接到url后面却无法显示对应参数的值

2：主子报表无法批量查询

3：无法展示当前结构

请官方给个解决方案，或者说如果是因为我自己未找到方法的原因，请指出如何设置。
以下为截图，有具体设想结构，请阅。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/70882167/122872382-f3794980-d362-11eb-9b31-e0506fe3913b.png)

![image](https://user-images.githubusercontent.com/70882167/122872392-f8d69400-d362-11eb-8276-2bcc18face7a.png)

![image](https://user-images.githubusercontent.com/70882167/122872421-03912900-d363-11eb-8ae0-8c0c37ba7ce3.png)
![image](https://user-images.githubusercontent.com/70882167/122872445-0a1fa080-d363-11eb-9ddd-8df756e9e362.png)
![image](https://user-images.githubusercontent.com/70882167/122872456-0e4bbe00-d363-11eb-8838-7e585a6e1e15.png)
![image](https://user-images.githubusercontent.com/70882167/122872468-1277db80-d363-11eb-9af0-78c3341dbc60.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by arkerwu** [comment]
这个需求是刚需啊，十分常见

**Comment by xtsora** [comment]
> 这个需求是刚需啊，十分常见；盼解决

兄弟，你也遇到这个问题了吗？也是同样的功能吗？

**Comment by arkerwu** [comment]
> > 这个需求是刚需啊，十分常见；盼解决
> 
> 兄弟，你也遇到这个问题了吗？也是同样的功能吗？

在研究这玩意，还没开始用

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/JimuReport/issues/331

**Comment by lvdandan16** [comment]
归集
