### ISSUE TITLE
iframe集成BI报表

### ISSUE THREAD

**Issue by guoyangjie** [jeecgboot/JimuReport#3320]
##### 错误日志&截图：

<img width="1256" alt="d9a86fd1e738eb2a78412091dcba458" src="https://github.com/user-attachments/assets/e99d5f3f-75cd-4e68-a02b-50d869469f87" />
<img width="1154" alt="8981a75fdacd8815ca6210c10e8f48b" src="https://github.com/user-attachments/assets/01656dce-497d-4b6b-a0be-5ba97b26e817" />

##### 重现步骤：

项目iframe中集成复现，直接跳转打开新的页面没不会有这个问题
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
集成问题，自己查issue，看看别人怎么处理的

**Comment by guoyangjie** [comment]
> 集成问题，自己查issue，看看别人怎么处理的

![image](https://github.com/user-attachments/assets/82014f7f-bae2-45ed-912d-bdd4942102c0)
不是集成问题，通过nginx代理之后都有这个问题

**Comment by zhangdaiscott** [comment]
![image](https://github.com/user-attachments/assets/f251fbe3-12cc-428f-b613-670fd213a2ff)
https://ojrjjvdr7z.k.topthink.com/jimureport/config/yaml.html
