### ISSUE TITLE
【bug】带有下钻链接的报表翻页后的下钻链接的参数丢失

### ISSUE THREAD

**Issue by jsonzoup** [jeecgboot/JimuReport#336]
##### 版本号：
v1.3.4-beta

##### 问题描述：
【bug】带有下钻链接的报表翻页后的下钻链接的参数丢失

##### 截图&代码：
无

**Comment by zhangdaiscott** [comment]
收录 ws

**Comment by 1298191366** [comment]
请把你的怎么设计的截图

**Comment by jsonzoup** [comment]
![image](https://user-images.githubusercontent.com/24908749/123420267-ef149100-d5ed-11eb-991b-a0e71a8bc47c.png)
![image](https://user-images.githubusercontent.com/24908749/123420521-36028680-d5ee-11eb-8e0d-593d4bb20f38.png)
![image](https://user-images.githubusercontent.com/24908749/123420604-54688200-d5ee-11eb-8ddd-030f8eac6cf0.png)

**Comment by 1298191366** [comment]
你看看是不是这样操作的，如果有不同点请说明，id可以取到不同的值，参数对应的是子表的参数（是否相同），原始参数是主表的字段
![钻取](https://user-images.githubusercontent.com/30997828/123945738-09c17e00-d9d1-11eb-90c2-99040262209f.gif)
