### ISSUE TITLE
【bug】下钻报表传参值相同的问题

### ISSUE THREAD

**Issue by jsonzoup** [jeecgboot/JimuReport#337]
##### 版本号：
v1.3.4-beta

##### 问题描述：
【bug】下钻报表链接，链接指定的参数是id, 链接的文字名称相同，此时参数id传的参数值都是相同的了（都是取得第一行的id的值），id应该取得值不同才对。

##### 截图&代码：
无

**Comment by zhangdaiscott** [comment]
收录 ws

**Comment by 1298191366** [comment]
请把你预览页面或者设计页面截一下图，是不是在分组下钻取的

**Comment by jsonzoup** [comment]
截图参考issue https://github.com/jeecgboot/JimuReport/issues/336

**Comment by 1298191366** [comment]
问题未测出，详情请看issue [#336](https://github.com/jeecgboot/JimuReport/issues/336) 动态图，如有其他问题请回复
