### ISSUE TITLE
报表设计单元格设置

### ISSUE THREAD

**Issue by kiver2016** [jeecgboot/JimuReport#338]
##### 版本号：
1.3.4-beta

##### 问题描述：
1.报表设计时行高列宽无法定量化设置。
2.日期格式无法自定。。

##### 截图&代码：
截图暂时没有

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
日期格式无法自定是什么意思？

**Comment by tygithub1** [comment]
暂不支持
