### ISSUE TITLE
【bug】交叉报表导出报错问题

### ISSUE THREAD

**Issue by jsonzoup** [jeecgboot/JimuReport#339]
##### 版本号：
v1.3.4-beta

##### 问题描述：
交叉报表页面显示都么有问题，但导出excel时报错!

##### 截图&代码：
![image](https://user-images.githubusercontent.com/24908749/123195097-298d0980-d4da-11eb-9f04-4eef6e6681af.png)
![image](https://user-images.githubusercontent.com/24908749/123195109-2db92700-d4da-11eb-94aa-f830da85f75d.png)

**Comment by lvdandan16** [comment]
下个版本发布

**Comment by jsonzoup** [comment]
非常感谢！
