### ISSUE TITLE
预览页面，无法显示Z列之后的内容

### ISSUE THREAD

**Issue by 13071652014** [jeecgboot/JimuReport#341]
##### 版本号：
1.3.5-beta、1.3.51-beta、等多个版本都有问题

##### 问题描述：
预览页面，无法显示Z列之后的内容，修改yml配置文件 的 col 也无效，这个问题很多人都遇到，都不能正常使用了，麻烦官方尽早修复

##### 截图&代码：
![Snipaste_2021-06-24_14-27-38](https://user-images.githubusercontent.com/56342460/123233742-e304d280-d50c-11eb-9f03-6d2e6411a875.jpg)

![Snipaste_2021-06-24_14-42-04](https://user-images.githubusercontent.com/56342460/123233761-e8fab380-d50c-11eb-908c-1f8a272b5076.jpg)

![Snipaste_2021-06-24_14-43-19](https://user-images.githubusercontent.com/56342460/123233791-ef892b00-d50c-11eb-9980-efb9a7081ecd.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
没重现，能否线上造个例子，把预览地址发出来

**Comment by 13071652014** [comment]
预览地址:  https://bootapi.jeecg.com/jmreport/shareView/569299697374941184 
预览密码:  692z

**Comment by 13071652014** [comment]
![image](https://user-images.githubusercontent.com/56342460/123567027-d1187d80-d7f3-11eb-8eb9-60a68130826b.png)

**Comment by 13071652014** [comment]
@tygithub1

**Comment by tygithub1** [comment]
该问题已经修复，下个版本发布，当内容的宽度小于浏览器屏幕的宽度就会出现该问题，所以你可以暂时在超出屏幕的后面某一列里输入个空格就能展示全了

**Comment by 13071652014** [comment]
@tygithub1 
官网上设计器的这个bug是修复了，但是我本地1.3.6-beta 版本的依旧存在这个问题

**Comment by zhangdaiscott** [comment]
1.3.61-beta

**Comment by 13071652014** [comment]
![image](https://user-images.githubusercontent.com/56342460/124532372-fa17be80-de42-11eb-89e4-8d82bef3e28e.png)
1.3.61-beta 版本还是不行，换了浏览器测试也一样   @zhangdaiscott

**Comment by zhangdaiscott** [comment]
1.3.61-beta 跟在线的一样的，确认你依赖变过来了没有

**Comment by 13071652014** [comment]
确定是变了的，上图的第三个截图的左侧依赖 也是1.3.61-beta的

**Comment by 13071652014** [comment]
idea 缓存清理，项目重新加载 也一样是这个问题，也没报错

**Comment by zhangdaiscott** [comment]
哪等再打新版吧，应该你要的功能未更新

**Comment by zhangdaiscott** [comment]
已经修复，升级到版本1.3.62-beta , 要[配置私服](http://report.jeecg.com/2195924)

```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.62-beta</version>
</dependency>
```

**Comment by 13071652014** [comment]
已修复，谢谢大佬 @zhangdaiscott
