### ISSUE TITLE
循环表头的横向分组报表时（以时间维度分组），如果有一组数据缺少某项，会导致报表显示异常

### ISSUE THREAD

**Issue by k8king** [jeecgboot/JimuReport#342]
##### 版本号：
1.3.51-beta

##### 问题描述：
制作循环表头的横向分组报表时（以时间维度分组），有一组数据缺少了某个月份。
导致展现异常。

##### 截图&代码：
- 数据成组出现时显示正常
![image](https://user-images.githubusercontent.com/1725280/123315478-5d117780-d55e-11eb-86e4-9ca11801f001.png)

![image](https://user-images.githubusercontent.com/1725280/123315564-70244780-d55e-11eb-9059-cf94fc77c889.png)

- 数据不成组出现（缺少一个月）时显示正常

![image](https://user-images.githubusercontent.com/1725280/123315694-934ef700-d55e-11eb-960e-499f4db98c05.png)

![image](https://user-images.githubusercontent.com/1725280/123315863-c72a1c80-d55e-11eb-9b92-ef5078ee6cc0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
是这样的  暂时需要用户自己补全数据，后期考虑报表自动补全

**Comment by zhangdaiscott** [comment]
已经修复，升级到版本1.3.63-beta , 要[配置私服](http://report.jeecg.com/2195924)

文档：http://report.jeecg.com/2032023
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.63-beta</version>
</dependency>
```
