### ISSUE TITLE
当一个大的报表中的多个小表格都使用了循环表头分组时，显示异常。

### ISSUE THREAD

**Issue by k8king** [jeecgboot/JimuReport#343]
##### 版本号：
1.3.51-beta

##### 问题描述：
有这样一个需求，需要在一张大的报表中集成多个小的表格，表头都需要动态展示。
多个小表格都使用了循环表头分组，发现显示异常。

##### 截图&代码：
- 一个循环表头时显示正常
![image](https://user-images.githubusercontent.com/1725280/123313236-e6737a80-d55b-11eb-9e8a-b41de2cb84c1.png)

![image](https://user-images.githubusercontent.com/1725280/123313305-fab77780-d55b-11eb-9ab2-329e5a150b29.png)

- 多个循环表头时显示异常

![image](https://user-images.githubusercontent.com/1725280/123313667-4f5af280-d55c-11eb-8fb3-7ec4513475c6.png)

![image](https://user-images.githubusercontent.com/1725280/123313846-787b8300-d55c-11eb-9400-f58f65b4cf5e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
暂不支持
