### ISSUE TITLE
项目集成报错

### ISSUE THREAD

**Issue by nnleo** [jeecgboot/JimuReport#344]
##### 版本号：
1.3.6-beta

##### 问题描述：

项目集成中,按照文档配置minidao,切换数据库不生效,运行时根据打印日志显示运行的是默认配置,项目qido启动成功后,也是因为配置不生效,报sql语法错误
##### 截图&代码：
![image](https://user-images.githubusercontent.com/70355119/124052821-bcd1bc00-da51-11eb-8695-9d68bde4afd8.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你看你配置的对吗？
咨询看文档
