### ISSUE TITLE
SQL语句动态绑定参数优化

### ISSUE THREAD

**Issue by wczengxc** [jeecgboot/JimuReport#345]
##### 截图&代码：
例如：
![image](https://user-images.githubusercontent.com/51688412/124209059-6f218600-db1b-11eb-8ef3-d7e6ada6254c.png)
想达到mybatis中xml配置效果如下图：
![image](https://user-images.githubusercontent.com/51688412/124209167-9d06ca80-db1b-11eb-829c-e501f460e1ec.png)

**Comment by zhangdaiscott** [comment]
最新版不存在这个问题了吧？

**Comment by wczengxc** [comment]
> 最新版不存在这个问题了吧？

应该是不支持的，比如我SQL里绑定了5个参数，实际只给3个参数传了值，另外2个没传值的话，这样拼接出来的SQL会查不到任何数据；而实际业务上需要达到的效果是，根据传了值得3个条件能查出数据。

**Comment by wczengxc** [comment]
您好，应该是不支持的，比如我SQL里绑定了5个参数，实际只给3个参数传了值，另外2个没传值的话，这样拼接出来的SQL会查不到任何数据；而实际业务上需要达到的效果是，根据传了值得3个条件能查出数据。


PS：另外2个参数如果没传值，拼接出来的SQL语句那2个参数是等于空&nbsp; 比如&nbsp; AND region = ''，这样会导致查不出数据，而实际是希望region没传值的话，拼接的SQL不要拼接AND region = ''&nbsp;
如果方便的话，可以电话：15850586169




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月2日(星期五) 下午2:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] SQL语句动态绑定参数优化 (#345)





 
最新版不存在这个问题了吧？

**Comment by lvdandan16** [comment]
建议使用api数据

**Comment by GrayZhang2014** [comment]
1.3.1-beta4  我用的这个版本没这个问题呀

**Comment by wczengxc** [comment]
> 1.3.1-beta4 我用的这个版本没这个问题呀

你可能没明白我的意思，不是有问题，是满足不了业务需求。

**Comment by wczengxc** [comment]
> 建议使用api数据

用api数据是可以解决，但api要写代码，增加了工作量。

**Comment by xinxingzhao** [comment]
> > 建议使用api数据
> 
> 用api数据是可以解决，但api要写代码，增加了工作量。

写个查询接口还好吧？用jeecg boot写查询接口基本没工作量

**Comment by wczengxc** [comment]
> > > 建议使用api数据
> > 
> > 
> > 用api数据是可以解决，但api要写代码，增加了工作量。
> 
> 写个查询接口还好吧？用jeecg boot写查询接口基本没工作量

咨询下，jeecg boot写API接口  有文档说明嘛

**Comment by nnleo** [comment]
讲真的  还是api最实用 ，这个sql查询问题很多

**Comment by xinxingzhao** [comment]
> > > > 建议使用api数据
> > > 
> > > 
> > > 用api数据是可以解决，但api要写代码，增加了工作量。
> > 
> > 
> > 写个查询接口还好吧？用jeecg boot写查询接口基本没工作量
> 
> 咨询下，jeecg boot写API接口 有文档说明嘛

需要返回指定格式的json就可以了

**Comment by zhangdaiscott** [comment]
归集到 https://github.com/jeecgboot/JimuReport/issues/138
