### ISSUE TITLE
报表设计中的SQL数据集是怎么使用多源数据管理中的数据集?

### ISSUE THREAD

**Issue by guccee** [jeecgboot/JimuReport#348]
##### 版本号：
2.4.5

##### 问题描述：
报表设计中的SQL数据集是怎么使用多源数据管理中的数据集?

##### 截图&代码：
![image](https://user-images.githubusercontent.com/58318101/124226353-8bcdb600-db3b-11eb-8295-fe0f376f2534.png)
![image](https://user-images.githubusercontent.com/58318101/124227208-de5ba200-db3c-11eb-9136-8eceeebbd87a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
?左侧是不可以创建数据源吗
