### ISSUE TITLE
翻页的能否加上过渡动画

### ISSUE THREAD

**Issue by zy528** [jeecgboot/JimuReport#349]
##### 版本号：
1.3.6-beta

##### 问题描述：
点击下一页，如数据量过大，翻页查询慢，没有加载动画，无法感知翻页完成。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
收录

**Comment by zhangdaiscott** [comment]
不紧急
