### ISSUE TITLE
报表全量导出问题

### ISSUE THREAD

**Issue by c270348095** [jeecgboot/JimuReport#351]
##### 版本号：
1.3.2-beta

##### 问题描述：
报表通过excel导出，默认带导出当前页数据。可否全量导出，既不分页？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by c270348095** [comment]
如下操作，需要全量，既不分页导出
![image](https://user-images.githubusercontent.com/12913916/124279986-b55a0200-db7a-11eb-9d78-b508d8991605.png)

**Comment by zhangdaiscott** [comment]
升级到最新版本
