### ISSUE TITLE
表头在横向分组的情况下，excel导出失败

### ISSUE THREAD

**Issue by HyoKaWeng** [jeecgboot/JimuReport#353]
##### 问题描述：
表头在横向分组的情况下，excel导出失败，报“Merge region XX must contain 2 or more cells”(这里的XX即横向分组的单元格)

##### 截图&代码：

![2](https://user-images.githubusercontent.com/54339660/124350988-5d7ad400-dc2a-11eb-9847-ed351cdcc913.jpg)
![3](https://user-images.githubusercontent.com/54339660/124351008-7a170c00-dc2a-11eb-87c5-07bc4642061b.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
试下这个版本,[配置jeecg私服](http://report.jeecg.com/2195924)
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.61-beta</version>
</dependency>

**Comment by HyoKaWeng** [comment]
经测试，横向分组下excel导出已修复，感谢您的答复



在 2021-07-03 19:27:53，"张代浩@JEECG" ***@***.***> 写道：

试下这个版本,配置jeecg私服

org.jeecgframework.jimureport
jimureport-spring-boot-starter
1.3.61-beta
