### ISSUE TITLE
希望报表内容能支持选择复制

### ISSUE THREAD

**Issue by jsonzoup** [jeecgboot/JimuReport#355]
##### 版本号：
v1.4.3-beta

##### 问题描述：
使用过程中很多时候需要从报表中复制内容，现在报表不可选择文字，也不可以复制。

##### 截图&代码：
无

**Comment by ulyn** [comment]
同样遇到这个问题，简单看了下它是canvas画的。
瞬间准备放弃这工具。

PS：进了群提问了一句，瞬间被禁言，也是服了，这工具的档次瞬间没了。

**Comment by zhangdaiscott** [comment]
重复问题
