### ISSUE TITLE
是否会提供序号功能（对于列表数据）

### ISSUE THREAD

**Issue by GrayZhang2014** [jeecgboot/JimuReport#357]
##### 版本号：
1.3.1-beta4

##### 问题描述：
1、是否会提供序号功能？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/37683436/124540561-3acb0400-de52-11eb-8b26-90edce16115b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已规划

**Comment by zhangdaiscott** [comment]
已经修复，升级到版本1.3.63-beta , 要[配置私服](http://report.jeecg.com/2195924)

文档：http://report.jeecg.com/2332220
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.63-beta</version>
</dependency>
```
