### ISSUE TITLE
是否会开放直接传递sql片段到报表中运行？

### ISSUE THREAD

**Issue by GrayZhang2014** [jeecgboot/JimuReport#358]
##### 版本号：
1.3.1-beta4

##### 问题描述：
1、是否会开放直接传递sql片段到报表中运行？
   贵团队开发的报表设计器中，支持sql数据源带参制作，其中支持定义参数，通过前端http请求将参数传递进去，
   在使用过程中：我直接将sql片段直接传递，首次可运行成功，分页则失败（原因：请求参数（sql片段）编码过，
   传递到sql中执行失败）

##### 截图&代码：
![image](https://user-images.githubusercontent.com/37683436/124541404-e9bc0f80-de53-11eb-886a-39dd0df5a0e0.png)
![image](https://user-images.githubusercontent.com/37683436/124541473-107a4600-de54-11eb-8bf8-2c9ca15d0a31.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不会，容易产生sql漏洞
