### ISSUE TITLE
积木报表 列超出设定纸张宽度后，调整会格式出问题

### ISSUE THREAD

**Issue by mybirday19870901** [jeecgboot/JimuReport#359]
##### 截图&代码：
![QQ图片20210706143459](https://user-images.githubusercontent.com/30786442/124553469-5c82b600-de67-11eb-8b94-16c7bfcc7a6e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
遇到问题，先升级到最新版本号
http://jimureport.com/doc/log

**Comment by mybirday19870901** [comment]
你好，我已升级到最新离线版本，还是会出现这个问题，你们的在线版预览是没问题的

**Comment by mybirday19870901** [comment]
现在的情况是超出一定列后，预览会格式缺失

**Comment by zhangdaiscott** [comment]
已经修复，升级到版本1.3.62-beta , 要[配置私服](http://report.jeecg.com/2195924)

```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.62-beta</version>
</dependency>
```
