### ISSUE TITLE
预览的时候，表头宽度可以被调动

### ISSUE THREAD

**Issue by HyoKaWeng** [jeecgboot/JimuReport#360]
##### 问题描述：
预览的时候，表头宽度可以被调动

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/54339660/124559529-678d1480-de6e-11eb-8558-ef833ab835e4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你是想达到这个效果吧？

**Comment by HyoKaWeng** [comment]
是的，感谢答复
