### ISSUE TITLE
单类别的图表修改颜色后无法保存

### ISSUE THREAD

**Issue by liujunMy** [jeecgboot/JimuReport#361]
##### 版本号：
1.3.51-beta

##### 问题描述：
单类别的图表修改图表的颜色，保存退出图表后再打开又恢复原来默认的颜色了

##### 截图&代码：
![GO`GIPRNU)WP~PIUG2N0}@H](https://user-images.githubusercontent.com/69063220/124571735-a6c16280-de7a-11eb-9a95-d06318c5b15f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
