### ISSUE TITLE
查询条件自动解析的下拉列表，限制获取条数

### ISSUE THREAD

**Issue by zy528** [jeecgboot/JimuReport#364]
##### 版本号：
1.3.6-beta
##### 问题描述：
查询条件自动解析的下拉列表 能加上条数限制吗，数据量过大 解析速度慢，系统容易oom

##### 截图&代码：

![image](https://user-images.githubusercontent.com/30794610/125044653-c2bd4200-e0ce-11eb-838b-0177b3e99b40.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xinxingzhao** [comment]
这里居然没做limit限制？我一直以为是有限制的

**Comment by zhangdaiscott** [comment]
收录 ty
（做成下拉搜索）

**Comment by zhangdaiscott** [comment]
归集到 https://github.com/jeecgboot/JimuReport/issues/138
