### ISSUE TITLE
集成到系统后，本地运行没有问题，但是部署到测试服务器后，点击新建报表后，跳转新页签为空白

### ISSUE THREAD

**Issue by cy3329520** [jeecgboot/JimuReport#365]
##### 版本号：

1.3.6-beta
##### 问题描述：
集成到系统后，本地运行没有问题，但是部署到测试服务器后，点击新建报表后，跳转新页签为空白
在线设计页面是没问题的，但是点击新件报表后，跳转的新页面是空白
打开f12后，发现有两个js请求不了
jmreport/desreport_/corelib/jmsheet.js?v=1.0.33
jmreport/desreport_/js/config/map_type_list.js?v=1.0.33

##### 截图&代码：
![image](https://user-images.githubusercontent.com/27672864/125067404-d1afee80-e0e6-11eb-807b-26dc76014ef1.png)

jmreport/index/573429975450800128?token=null&menuType=datainfo
![image](https://user-images.githubusercontent.com/27672864/125067422-d70d3900-e0e6-11eb-9c46-23ea59b64c5c.png)

**Comment by cy3329520** [comment]
![image](https://user-images.githubusercontent.com/27672864/125067890-6a466e80-e0e7-11eb-8754-fc5118d7136f.png)

**Comment by cy3329520** [comment]
控制台
![image](https://user-images.githubusercontent.com/27672864/125069033-c8c01c80-e0e8-11eb-86d7-a670bb7e6fbe.png)

**Comment by zhangdaiscott** [comment]
这个应该是你部署的文档，跟程序没关系
