### ISSUE TITLE
主子表关系下，excel导出的列表数据显示为空

### ISSUE THREAD

**Issue by HyoKaWeng** [jeecgboot/JimuReport#366]
##### 版本号：
v1.3.6-beta

##### 问题描述：
我配置了三个数据集：“查询”（维护查询的字段），“列表”（分页的列表数据集），“图”（返回 折线图 所需数据的数据集），并且配置了两个主子表关系：使“查询”和“列表”分别作为第一个主子表，使“查询”和“图”作为第二个主子表
想实现一个“列表”和“图”的数据跟随“查询”数据集的字段同时变化，并且我也实现了，但是在测试excel导出的时候，发现列表的数据在导出成excel时候，显示为空，当我将两个主子表关系都移除之后，导出的excel中，列表的数据就正常显示了。

后来我尝试将“查询”和“列表”数据集合并成为一个数据集，并配置“图”数据集作为其子表来依赖这个列表的数据集，但是在测试excel导出的时候，导出的excel中的列表依然没有显示数据。

后台没有报错信息输出

##### 截图&代码：

![快照312](https://user-images.githubusercontent.com/54339660/125163941-25dbd100-e1c2-11eb-8e69-ad9f12191990.png)
![快照1](https://user-images.githubusercontent.com/54339660/125163950-2d9b7580-e1c2-11eb-99a4-1dc08758c04b.png)
![快照2](https://user-images.githubusercontent.com/54339660/125163954-31c79300-e1c2-11eb-8818-965bcd44ed14.png)
![快照2 (2)](https://user-images.githubusercontent.com/54339660/125163963-3d1abe80-e1c2-11eb-8afb-10b4d08ba523.png)
![快照233](https://user-images.githubusercontent.com/54339660/125163978-515ebb80-e1c2-11eb-9331-f94b148c23f0.png)
![快照1 (2)](https://user-images.githubusercontent.com/54339660/125163989-5d4a7d80-e1c2-11eb-8854-7858ede1695f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
先升级到最新版，确认是否还存在问题
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.64-beta</version>
</dependency>
```

**Comment by HyoKaWeng** [comment]
经测试，已解决，感谢答复。。。



在 2021-07-13 15:30:55，"张代浩@JEECG" ***@***.***> 写道：

先升级到最新版，确认是否还存在问题

<dependency>

  <groupId>org.jeecgframework.jimureport</groupId>

  <artifactId>jimureport-spring-boot-starter</artifactId>

  <version>1.3.64-beta</version>

</dependency>
