### ISSUE TITLE
报表设计权限管理(只能看到自己创建的报表)

### ISSUE THREAD

**Issue by boolean-dev** [jeecgboot/JimuReport#368]
##### 版本号：
1.3.4-beta

##### 问题描述：
在多人协作的情况下，A创建的报表，B无法看到，导致系统需要多个人员共用一个帐号，才能够实现多人编辑同一个报表设计。
建议方案：
1. 报表新增一个是否共享字段，如果设置为共享，则登录的所有人员都可见
2. 在配置文件中新增一个参数，由参数来控制报表是否共享（缺点：开放或关闭只能进行全局控制）
3. 设计一套完整的权限系统（较为复杂）

##### 截图&代码：
![image](https://user-images.githubusercontent.com/20177406/125405796-b137ab00-e3ea-11eb-9713-3fb688bb8a0b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
有个saas属性配置，开启saas做隔离，不开启不隔离

收录 ws

**Comment by boolean-dev** [comment]
我这边已经配置成了 sass=false
但是还是不生效，这个我看你们文档上说的是 `数据字典是否进行saas数据隔离(限制只能看自己的字典)`
![image](https://user-images.githubusercontent.com/20177406/125725052-eacbf9ee-3aa6-4324-8b53-6bb5be44bb5c.png)

下面是我这边的相关配置信息
配置文件
![image](https://user-images.githubusercontent.com/20177406/125725076-7f71d8ec-9064-4f39-9a85-8f0af9fe1518.png)

admin 帐号展示的报表页面
![image](https://user-images.githubusercontent.com/20177406/125725166-b093a7e9-2b9e-42b2-b551-37bbb848566b.png)

个人帐号展示的报表页面
![image](https://user-images.githubusercontent.com/20177406/125725276-86d4451d-326a-41d2-8e02-5e2d0d0d23bd.png)

**Comment by 1298191366** [comment]
已修复，待新版本发布
