### ISSUE TITLE
交叉表-当横向分组的值有表情符号时报错

### ISSUE THREAD

**Issue by jsonzoup** [jeecgboot/JimuReport#369]
##### 版本号：
v1.3.64-beta

##### 问题描述：
当横向分组的值有表情符号时报错

##### 截图&代码：
![image](https://user-images.githubusercontent.com/24908749/125416557-9d85594f-e517-45e8-8a3e-b634c16a56bb.png)

**Comment by zhangdaiscott** [comment]
能描述的更详细点吗

**Comment by jsonzoup** [comment]
感觉是带表情符号的字段，您没有获取到TableRenderStrategy, 造成了空指针异常。

**Comment by zhangdaiscott** [comment]
收录 yf

**Comment by accpman** [comment]
贴出你的设计模版，还有使用的标签符号
