### ISSUE TITLE
柱形报表使用API动态数据时，预览无法渲染数据

### ISSUE THREAD

**Issue by clxryxy** [jeecgboot/JimuReport#371]
##### 版本号：
1.3.6-beta、1.3.64-beta

##### 问题描述：

通过API动态数据获取接口数据后，早编辑页面能正常渲染柱形图，但是保存预览后，柱形图无法渲染，导出pdf等文件也是无法渲染出现。
##### 截图&代码：
![image](https://user-images.githubusercontent.com/22394982/125580984-032314a0-a8d8-4987-a8cc-d32d4f3968ac.png)

![image](https://user-images.githubusercontent.com/22394982/125581032-1f22e1fe-2eff-4631-9b03-f0308cf4ea50.png)

![image](https://user-images.githubusercontent.com/22394982/125581935-b0e6169c-cb1b-42a2-b7f9-1675d7086a85.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
接口提供，接口的数据也提供

**Comment by 1298191366** [comment]
问题未测出
设计页面：
![image](https://user-images.githubusercontent.com/30997828/126773403-c12d5aff-eeef-4418-b2e4-0518d38be5fc.png)
预览页面
![image](https://user-images.githubusercontent.com/30997828/126773434-fdbcbd66-b19c-46f4-b739-b7228749f702.png)
如有问题，请提供数据

**Comment by Justin-Binber** [comment]
我也有相同的问题，怎么解决的？
