### ISSUE TITLE
api动态查询条件支持下拉,多选,以及时间范围查询

### ISSUE THREAD

**Issue by nnleo** [jeecgboot/JimuReport#372]
##### 版本号：
1.3.64-beta

##### 问题描述：
希望报表参数查询能像查询明细一样有个查询模式,从而使查询条件支持下拉,多选,时间范围的

##### 截图&代码：

![image](https://user-images.githubusercontent.com/70355119/125589913-ff3e1aa8-0cb2-4b74-8f20-fb657cdf0ff2.png)
![image](https://user-images.githubusercontent.com/70355119/125590293-ee7a2e63-885c-4a37-9751-06a61c860b3b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录  ty

**Comment by zhangdaiscott** [comment]
归集到 https://github.com/jeecgboot/JimuReport/issues/138

**Comment by tygithub1** [comment]
已支持 下个版本发
