### ISSUE TITLE
横向分组数据格式为“2021-01”格式时，渲染失败

### ISSUE THREAD

**Issue by boolean-dev** [jeecgboot/JimuReport#373]
##### 版本号：
1.3.64-beta

##### 问题描述：
我想根据月份进行横向分组，我把日期格式化了如下格式 'YYYY-MM'，但是在执行的时候，导致了报错。
但是如果把日期格式化成'YYYY_MM'，就正常了

##### 截图&代码：
错误的相关示例：
原始数据库数据
![image](https://user-images.githubusercontent.com/20177406/125592317-591223ac-b2e2-4fc0-993b-0d0ae7fc359c.png)
报表设计截图：
![image](https://user-images.githubusercontent.com/20177406/125592432-dc240670-0115-4a2c-8194-1d583257afdf.png)
报错日志：
```log
FreeMarker template error:
The following has evaluated to null or missing:
==> account.num_2021  [in template "template" at line 1, column 164]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${account.num_2021 - 6}  [in template "template" at line 1, column 162]
----

Java stack trace (for programmers):
----
```
详细日志
[error.log](https://github.com/jeecgboot/JimuReport/files/6814763/error.log)

==================================
正确示例：
![image](https://user-images.githubusercontent.com/20177406/125592931-ebe8843e-ffb7-4372-98cb-6f2a684936bd.png)

![image](https://user-images.githubusercontent.com/20177406/125592962-a2675f1b-79bd-4b22-8eec-bc5f9da7242b.png)

![image](https://user-images.githubusercontent.com/20177406/125593026-d4c69a2d-6d71-42aa-9b62-838f6bd678dc.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 yf

**Comment by accpman** [comment]
已处理，等下个版本修复
