### ISSUE TITLE
查询时回车,会刷新页面,而不是返回查询结果

### ISSUE THREAD

**Issue by qianxunman** [jeecgboot/JimuReport#374]
##### 版本号：
v1.3.4-beta

##### 问题描述：
查询时回车,会刷新页面,而不是返回查询结果

##### 截图&代码：
![image](https://user-images.githubusercontent.com/31980521/125899733-b5ac0cc5-abef-4d53-9b9b-e187bfa47a31.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
