### ISSUE TITLE
jmreport后端的bigdecimal数据返回值无法实现保留二位小数位

### ISSUE THREAD

**Issue by bluecodezlx** [jeecgboot/JimuReport#375]
##### 版本号：
jimureport 1.3.64-beta

##### 问题描述：
jmreport后端的bigdecimal数据返回值无法实现保留二位小数位；
当BigDecimal类型的属性上有@JsonFiled注解，且该注解中的format有值时，使用自定义的方法进行￥#0.00格式序列化；

##### 截图&代码：
![image](https://user-images.githubusercontent.com/2093382/126027616-bdb17c75-da4a-4443-94fb-a1cf0db0c9c6.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
这个是数据源查询的数据就是这个格式  还是说页面渲染的问题？
