### ISSUE TITLE
循环表格标题设置

### ISSUE THREAD

**Issue by MRStruggle** [jeecgboot/JimuReport#377]
##### 版本号：
1.3.1-beta4

##### 问题描述：
项目实现循环表格前面一列标题固定

##### 截图&代码：
![image](https://user-images.githubusercontent.com/29857641/126110431-b95b391f-93df-4e28-9513-b04d74a3a348.png)
想实现如上提效果，

实际上
如果表格有3行，那么显示3此一样的文件标题，

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
收录 yf
