### ISSUE TITLE
预览时表头中文乱码显示？？

### ISSUE THREAD

**Issue by shatang123** [jeecgboot/JimuReport#378]
##### 版本号：
1.3.6-beta

##### 问题描述：
本地使用springboot2.5.2集成积木报表，不参杂任何业务，创建一个报表后进行预览，发现表头中文显示乱码，数据中文显示正常，打开f12查看，发现回传数据中，中文就是乱码

##### 截图&代码：

![image](https://user-images.githubusercontent.com/79393593/126128486-e561cc8e-97e3-401c-88e2-57e9b26c28c4.png)
![image](https://user-images.githubusercontent.com/79393593/126128748-0d6d169a-4f88-469b-8fea-c93ff9b8db44.png)
![image](https://user-images.githubusercontent.com/79393593/126128855-26c6b8ad-f792-4fc6-8575-6b7d79e83240.png)
![image](https://user-images.githubusercontent.com/79393593/126128942-efe15e2d-f25a-47be-b87e-a50a42b47443.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
查看数据库是否乱码
