### ISSUE TITLE
图表布局可以覆盖行号的位置

### ISSUE THREAD

**Issue by xinxingzhao** [jeecgboot/JimuReport#379]
##### 版本号：
V1.3.64-bata

##### 问题描述：
图表设计的时候，图表的布局可以覆盖到行号的位置，列号的位置也同理，也可以覆盖到，建议不要让图表覆盖到这个位置，虽然并没有影响到报表的显示。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/13712791/126172278-b327660b-9915-4a37-b3e5-19c85dc8e409.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
收录

**Comment by lvdandan16** [comment]
[功能归集到#138](https://github.com/jeecgboot/JimuReport/issues/138)
