### ISSUE TITLE
使用Api数据库关于解析Api以及Token设置的问题

### ISSUE THREAD

**Issue by Curtain-Wang** [jeecgboot/JimuReport#380]
##### 版本号：

1.3.64-beta

##### 问题描述：

使用API数据集，按照文档里面api数据集token机制详解介绍的去实现JmReportTokenServiceI接口，重写getToken()方法或者customApiHeader()方法都不行。看了后端日志，仿佛这个配置就没生效。还有个小问题，如果是解析post请求，参数是json类型的，怎么传参？谢谢~

##### 截图&代码：
代码截图
![1](https://user-images.githubusercontent.com/49394182/126257552-dd6c6a4c-501b-47ef-9f83-de3b1357a257.png)
控制台截图
![2](https://user-images.githubusercontent.com/49394182/126257565-cab85597-44cf-46ff-87d0-55e54a85f3e0.png)

日志截图（没有打印调用WebClient.getToken()的日志）

![3](https://user-images.githubusercontent.com/49394182/126257591-c5f8f152-d974-4919-b189-7289a08d6c76.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xinxingzhao** [comment]
这个问题我也遇到过，貌似官方文档写得并不是很清楚，我的解决办法是把所有积木的接口和数据接口全部不做token校验了

**Comment by Curtain-Wang** [comment]
@xinxingzhao 这样子不适用导出第三方需要token的接口数据情况。对了，你知道Post请求如何传json参数吗~~

**Comment by zhangdaiscott** [comment]
不行是什么意思？

**Comment by Curtain-Wang** [comment]
@zhangdaiscott 不行就是按照文档说的重写getToken()方法或者customApiHeader()方法都不能在解析api的时候传入token。但是就在刚刚，发现问题啦，是我没有将实现JmReportTokenServiceI接口的配置类成功注册到Spring中。因为该类不在包扫描的路径中~

**Comment by Curtain-Wang** [comment]
@zhangdaiscott 还有个小问题就是 要解析的Api它如果是post请求的，然后参数是json格式的，这种情况我们怎么传参？求大神告知~

**Comment by zhangdaiscott** [comment]
统一规划，先归集到 https://github.com/jeecgboot/JimuReport/issues/138
