### ISSUE TITLE
SpringCloud通过服务中心访问jimuReport服务.css,.js文件加载不了

### ISSUE THREAD

**Issue by qxy19861204** [jeecgboot/JimuReport#381]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/51010994/126269120-1bc3a870-a17d-4518-80e8-67b1c82d6273.png)
![image](https://user-images.githubusercontent.com/51010994/126269177-c0c7edfa-db14-47af-bc73-a6fe0c6d9a81.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
#自定义项目前缀
    customPrePath:

http://report.jeecg.com/2302149
