### ISSUE TITLE
如何配置才能使得分享报表的时候不需要密码呢？

### ISSUE THREAD

**Issue by sifenglib** [jeecgboot/JimuReport#382]
##### 版本号：
1.3.64-beta

##### 问题描述：
如何配置才能使得分享报表的时候不需要密码呢？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/61527672/126284117-2081a220-6fb4-4cd7-8cc8-041b85b04dc1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/126437991-95225b5d-29c9-4f1b-8fff-61e1859cec71.png)
