### ISSUE TITLE
设计报表与预览结果不一

### ISSUE THREAD

**Issue by MintNiu** [jeecgboot/JimuReport#383]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/48917227/126322488-24be4f13-ff43-4678-a94b-f02251264e4c.png)
![image](https://user-images.githubusercontent.com/48917227/126322794-5182bfbd-5dec-4256-b2ac-5d1c2263c2ac.png)
设计成果和展示结果不一

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
？

**Comment by zqlgfrzy** [comment]
我也遇到过这种问题，在设计的时候
![设计](https://user-images.githubusercontent.com/38415342/127440206-aa5b5b77-fb52-4923-ab98-d255b9c4738f.png)
然后预览的时候：
![预览](https://user-images.githubusercontent.com/38415342/127440231-4b7080ce-2adc-47e9-bcb6-61314fe0f876.png)
莫名其妙会多出来很多空白

**Comment by zhangdaiscott** [comment]
非集合数据集用 ${}
#{}表达式，同个数据集只能在一行上面
