### ISSUE TITLE
报表打印需求

### ISSUE THREAD

**Issue by YBenX** [jeecgboot/JimuReport#384]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/3353434/126423651-11455ca4-5346-4792-8d9e-86770c9ee9c5.png)
![image](https://user-images.githubusercontent.com/3353434/126423675-7f77007a-34b9-4497-ac70-242657743672.png)
![image](https://user-images.githubusercontent.com/3353434/126423730-c8a916f5-0656-41c6-b700-eadacf8276e1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
归集到https://github.com/jeecgboot/JimuReport/issues/138
