### ISSUE TITLE
ruoyi-vue按照官方文档集成JimuReport,访问出现404页面

### ISSUE THREAD

**Issue by AleanHX** [jeecgboot/JimuReport#385]
##### 版本号：
JimuReport版本是1.3.5-beta

##### 问题描述：
ruoyi-vue按照官方文档集成JimuReport,访问http://localhost/jmreport/list出现404页面

##### 截图&代码：

![image](https://user-images.githubusercontent.com/45304002/126461187-68b0854f-9227-4554-bf7b-d654269b4e24.png)

在模块ruoyi-admin的pom文件中添加如下依赖
```
<dependency>
            <groupId>org.jeecgframework.jimureport</groupId>
            <artifactId>jimureport-spring-boot-starter</artifactId>
            <version>1.3.5-beta</version>
</dependency>
```

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lijong** [comment]
遇到同样的问题 您解决了吗

**Comment by AleanHX** [comment]
> 遇到同样的问题

没有。。。。。

**Comment by AleanHX** [comment]
没有




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月26日(星期一) 下午5:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/JimuReport] ruoyi-vue按照官方文档集成JimuReport,访问出现404页面 (#385)





 
遇到同样的问题 您解决了吗

**Comment by zhangdaiscott** [comment]
这是后端jar项目，不能用前端路由访问，得用后端的请求访问

**Comment by AleanHX** [comment]
谢谢，我再看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "张代浩@***@***.***&gt;; 
发送时间: 2021年7月26日(星期一) 晚上6:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/JimuReport] ruoyi-vue按照官方文档集成JimuReport,访问出现404页面 (#385)





 
这是后端jar项目，不能用前端路由访问，得用后端的请求访问

**Comment by AleanHX** [comment]
> 遇到同样的问题

其实菜单链接就是**`“http://网址:端口号/jmreport/list"`**。很重要！！！
我之前用的是前端路由，所以不行。
