### ISSUE TITLE
JimuReport 是否有对IE11的支持

### ISSUE THREAD

**Issue by BetaVolare** [jeecgboot/JimuReport#386]
##### 版本号：
v1.1.05

##### 问题描述：
IE上无法展示通过JimuReport配置的excel 模板,显示的是一个空白页面
##### 截图&代码：

![image](https://user-images.githubusercontent.com/26106337/126579268-8ed8ff60-47e5-47cb-96ec-1d2842c592ab.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
[功能归集到#138](https://github.com/jeecgboot/JimuReport/issues/138)
