### ISSUE TITLE
如何在一个表格里面显示2个数据集中的数据

### ISSUE THREAD

**Issue by 348339749** [jeecgboot/JimuReport#388]
##### 截图&代码：
![图片](https://user-images.githubusercontent.com/58327529/126617563-7f817881-0fe2-417d-acc1-0ed2258572d3.png)
![图片](https://user-images.githubusercontent.com/58327529/126617608-9b554b7a-2a90-4afd-bff0-d2f4afc904b4.png)
![图片](https://user-images.githubusercontent.com/58327529/126617737-9781469e-6006-430e-bbda-e093a7418850.png)

![图片](https://user-images.githubusercontent.com/58327529/126617452-f2732d2f-d297-4518-b6f9-f99ded1badd6.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
[功能归集到#138](https://github.com/jeecgboot/JimuReport/issues/138)
