### ISSUE TITLE
1.3.64beta新建报表报错

### ISSUE THREAD

**Issue by xChaosCN** [jeecgboot/JimuReport#389]
##### 版本号：
1.3.64beta
RuoYi 3.2.0

##### 问题描述：
集成至RuoYi（Vue前端分离版）后新建报表(/jmreport/save)时报错

##### 截图&代码：
![Untitled](https://user-images.githubusercontent.com/7285000/126618025-eec01d50-e7c0-4948-98a5-d374204951b4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
一块就是依赖冲突，学会百度
![image](https://user-images.githubusercontent.com/3162115/126633626-57ce7c23-9df3-43de-b168-61a2483ba3c3.png)

**Comment by xChaosCN** [comment]
全局只引用了一个FastJson 1.2.75

**Comment by xChaosCN** [comment]
> 一块就是依赖冲突，学会百度
> ![image](https://user-images.githubusercontent.com/3162115/126633626-57ce7c23-9df3-43de-b168-61a2483ba3c3.png)

全局只引用了一个FastJson 1.2.75 没有冲突
