### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by gelinagg** [jeecgboot/JimuReport#390]
##### 问题描述：
取消显示问题

##### 截图&代码：红框的内容可以选择不显示吗

![image](https://user-images.githubusercontent.com/17491916/126625562-d727e5ab-3d19-48f1-b8a5-72b74b14bf92.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by gelinagg** [comment]
之前有人提过，貌似还没有给出方案

**Comment by gelinagg** [comment]
https://github.com/jeecgboot/JimuReport/issues/191

**Comment by gelinagg** [comment]
我是整个都不需要，我只是几个图表，而且是内嵌在jeecgboot中的。有这个大大影响美观。无法使用。

**Comment by zhangdaiscott** [comment]
已经规划，下个版本
