### ISSUE TITLE
小数位带千分符

### ISSUE THREAD

**Issue by sunshanjin** [jeecgboot/JimuReport#391]
##### 版本号：
1.3.64-beta

##### 问题描述：
单元格设置数字，小数位保留4位，预览后，小数位也带千分符

##### 截图&代码：
![image](https://user-images.githubusercontent.com/7366954/126754775-746cc393-9d11-4b7e-a48c-cc459f0b7b61.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
收录ty

**Comment by tygithub1** [comment]
已经修改,下个版本发
