### ISSUE TITLE
设置小数位数后，导出的

### ISSUE THREAD

**Issue by sunshanjin** [jeecgboot/JimuReport#392]
##### 版本号：
1.3.64-beta

##### 问题描述：
设置字段位数字，小数位保留4位，预览无问题，导出后，excel中小数位消失

##### 截图&代码：
![image](https://user-images.githubusercontent.com/7366954/126755012-8adf38ba-21a8-4ea3-89f7-2aced1a0ef6f.png)
![image](https://user-images.githubusercontent.com/7366954/126755091-5ce423ad-3e2d-411b-a2be-da8e5c5c9068.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
