### ISSUE TITLE
日期无法进行格式化显示

### ISSUE THREAD

**Issue by shatang123** [jeecgboot/JimuReport#394]
##### 版本号：
1.3.64

##### 问题描述：
日期无法格式化，使用的是mysql数据库，数据库的日期格式为datetime，报表选择日期格式化为长日期格式，但还是显示原始内容
![image](https://user-images.githubusercontent.com/79393593/126946446-05e8da2d-db41-4c59-8ffa-f77f546b5aaa.png)

![image](https://user-images.githubusercontent.com/79393593/126946418-e9a26147-9c33-4c3b-b19d-ff8acc9b2138.png)

![image](https://user-images.githubusercontent.com/79393593/126946503-d3ef1ba3-19b7-4d87-abb5-f785217bd401.png)

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
版本号升级到 1.3.65-beta  试试

**Comment by shatang123** [comment]
> 版本号升级到 1.3.65-beta 试试

出了这个版本嘛，
![image](https://user-images.githubusercontent.com/79393593/126950077-d70d6355-f6eb-4102-827c-5aad34b6c268.png)

**Comment by zhangdaiscott** [comment]
升级到这个版本，配置 [jeecg私服](http://report.jeecg.com/2195924)
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.65-beta</version>
</dependency>
```

**Comment by shatang123** [comment]
> 升级到这个版本，配置 [jeecg私服](http://report.jeecg.com/2195924)
> 
> ```
> <dependency>
>   <groupId>org.jeecgframework.jimureport</groupId>
>   <artifactId>jimureport-spring-boot-starter</artifactId>
>   <version>1.3.65-beta</version>
> </dependency>
> ```

还是没有格式化，已经配置了私服，升级了最新版，日期还是以前na'y那样子显示
![image](https://user-images.githubusercontent.com/79393593/127088628-d03fd2b3-d38a-4d5b-b8e6-1a8842031fb6.png)

**Comment by shatang123** [comment]
> > 升级到这个版本，配置 [jeecg私服](http://report.jeecg.com/2195924)
> > ```
> > <dependency>
> >   <groupId>org.jeecgframework.jimureport</groupId>
> >   <artifactId>jimureport-spring-boot-starter</artifactId>
> >   <version>1.3.65-beta</version>
> > </dependency>
> > ```
> 
> 还是没有格式化，已经配置了私服，升级了最新版，日期还是以前na'y那样子显示
> ![image](https://user-images.githubusercontent.com/79393593/127088628-d03fd2b3-d38a-4d5b-b8e6-1a8842031fb6.png)

![image](https://user-images.githubusercontent.com/79393593/127088717-d35a11e5-6265-445e-afa4-8c050ccee470.png)

![image](https://user-images.githubusercontent.com/79393593/127088742-8576276a-3433-4445-8f8d-5648d6fa6cea.png)
