### ISSUE TITLE
能否预览的时候，表格可以居中显示，假如屏幕较宽，右边空间太多了，不是很美观。

### ISSUE THREAD

**Issue by sj-dev** [jeecgboot/JimuReport#395]
##### 版本号：

org.jeecgframework.jimureport:jimureport-spring-boot-starter:1.3.6-beta

##### 问题描述：
能否预览的时候，表格可以居中显示，假如屏幕较宽，右边空间太多了，不是很美观。

##### 截图&代码：

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/10184494/126966144-043fc49a-608a-4e53-9a22-350db6177925.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不支持

**Comment by showyoulove1990** [comment]
是否考虑增加这个设置属性？
