### ISSUE TITLE
分组报表、设置表格边框、200多条记录时导出excel报错(项目上线急解决)

### ISSUE THREAD

**Issue by mumuxix** [jeecgboot/JimuReport#397]
##### 版本号：
最新版本1.3、1.3.64-beta都有此问题

##### 问题描述：
采用sql查询出的数据配置报表：表格设置分组、设置加边框，在超过200条记录时导出excel报错：Attempting to write a row[11] in the range [0,102] that is already written to disk

##### 截图&代码：
![image](https://user-images.githubusercontent.com/62630362/127079864-029957bd-5773-4c7b-89ae-31ff0cbacfa2.png)
![image](https://user-images.githubusercontent.com/62630362/127079870-2de90b76-74d4-466c-a4d9-ad8be33b8815.png)
![image](https://user-images.githubusercontent.com/62630362/127079879-c761cfbc-fd1d-4c8f-ae60-9c849f44b88a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
升级到这个版本，配置 [jeecg私服](http://report.jeecg.com/2195924)
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.65-beta</version>
</dependency>
```
