### ISSUE TITLE
当记录超过大概1000条时，导出的excel缺失表格边框样式

### ISSUE THREAD

**Issue by mumuxix** [jeecgboot/JimuReport#398]
##### 版本号：
1.3.64-beta

##### 问题描述：
当记录超过大概1000条时，导出的excel缺失表格边框样式，在excel中显示没有默认的边框，是空白的

##### 截图&代码：
![image](https://user-images.githubusercontent.com/62630362/127080113-c2722954-e89f-4ee0-a0a7-c4e119103e6e.png)
![image](https://user-images.githubusercontent.com/62630362/127080119-9ddad786-0b51-4987-b42c-84c042d28874.png)
![image](https://user-images.githubusercontent.com/62630362/127080127-5af75deb-2d0c-4890-a603-e4c553f59cd5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
就是这么做的，数据量大的时候带着样式导出会报错
