### ISSUE TITLE
API数据源列表和不列表同时使用的时候，表格会裂开

### ISSUE THREAD

**Issue by lhbwhite** [jeecgboot/JimuReport#401]
##### 问题描述：API数据源列表和不列表同时使用的时候，前面是连续两行列表#{ele.test1}  #{ele.test2}，后面是${ele.test3}，表格会裂开

#####截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lhbwhite** [comment]
>
![Snipaste_2021-07-28_11-56-37](https://user-images.githubusercontent.com/72908720/127261848-8ff0c81a-c970-4ba0-90d5-8c88823365fb.png)
![Snipaste_2021-07-28_11-56-53](https://user-images.githubusercontent.com/72908720/127261857-f0a1211e-884b-485d-a46e-c73c5b4c982f.png)

**Comment by zhangdaiscott** [comment]
不支持这么用
