### ISSUE TITLE
启动报错，不动

### ISSUE THREAD

**Issue by GGeMonster** [jeecgboot/JimuReport#403]
##### 截图&代码：
![图片](https://user-images.githubusercontent.com/49889353/127284166-69ade364-1b71-42e2-8811-dfaf24bea03a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
改过什么

**Comment by GGeMonster** [comment]
数据库地址

**Comment by zhangdaiscott** [comment]
截图

**Comment by GGeMonster** [comment]
![图片](https://user-images.githubusercontent.com/49889353/127290264-2351e829-67d7-40da-963e-0231d8bff21b.png)

**Comment by GGeMonster** [comment]
之前还可以用，今天打开怎么也运行不起来

**Comment by zhangdaiscott** [comment]
不清楚
