### ISSUE TITLE
项目部署到服务器上新建的报表后无法删除，部署的服务器是不能连接外网的

### ISSUE THREAD

**Issue by sunjianvs** [jeecgboot/JimuReport#404]
##### 版本号：

1.3.64-
##### 问题描述：

部署到服务器上无法删除报表，本地能删除，然后部署到可以连接外网的服务器上也能删除，部署到公司不能连接外网的服务器上无法删除，请问这个报表删除是不是涉及了需要连接外网的操作？
##### 截图&代码：

![QQ截图20210729092554](https://user-images.githubusercontent.com/56440321/127427938-b1fc6a29-5939-4704-aa05-910d51bced0a.png)

![QQ截图20210729114120](https://user-images.githubusercontent.com/56440321/127428010-63728d6c-e8d2-44ad-abea-637a698624be.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
本地没问题就是你部署的有问题
