### ISSUE TITLE
http://localhost:8085/jmreport/view/553050941272494080这个登录之后，没有token也能访问，可不可以动态配置，没token不能访问

### ISSUE THREAD

**Issue by chendong2018** [jeecgboot/JimuReport#405]
##### 问题描述：http://localhost:8085/jmreport/list?token=这个已经加了权限
也已经生效了。但http://localhost:8085/jmreport/view/553050941272494080这个登录之后访问不需要token都可以访问，这样随便发给谁都能看到数据了。能不能在yml配置或再哪里配置，类似黑名单这样的，需要toekn才能访问jmreport/view

##### 截图&代码：
![image](https://user-images.githubusercontent.com/39365951/127462636-244a8f72-0688-45c3-b381-f97070b4b5ee.png)

![image](https://user-images.githubusercontent.com/39365951/127462688-3a5b31ec-add5-4341-b2cb-0d37e518ffb4.png)
![image](https://user-images.githubusercontent.com/39365951/127585416-c4a83f7a-2ee7-468a-bc90-bd2d4912813e.png)

![image](https://user-images.githubusercontent.com/39365951/127463424-85dd3a48-1b1f-44cf-b5d5-87d992821125.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://report.jeecg.com/2208864

**Comment by zhangxinyuan1** [comment]
@zhangdaiscott 自行设置token 仅仅在API数据源才有效
