### ISSUE TITLE
交叉报表配置的有交叉斜线单元格时，导出的excel表头中交叉斜线单元格中文显示乱码

### ISSUE THREAD

**Issue by zhang6685979** [jeecgboot/JimuReport#406]
##### 版本号：
1.3.65-beta

##### 问题描述：
在单元格中设置单元格斜线，输入对应的中文（地区|省份|月份），设计好对应表格后预览正常，但导出的excel该单元格显示乱码，英文能够正常显示，期望解决中文乱码问题

##### 截图&代码：
![image](https://user-images.githubusercontent.com/4394937/127463290-973fc815-eb33-44c9-860c-e977a50e52ca.png)

![image](https://user-images.githubusercontent.com/4394937/127463223-348c9324-4308-43db-95ea-40056c123009.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
所有报表都这样？确认下是不是数据库编码问题

**Comment by zhang6685979** [comment]
> 所有报表都这样？确认下是不是数据库编码问题

我们自己排查了一下，数据库编码配置的是utf-8,在本地开发环境导出是正常的,但是部署到linux服务器上有问题，这个是不是需要什么设置？

**Comment by zhangdaiscott** [comment]
jar启动的编码设置为utf-8 试试

**Comment by zhangdaiscott** [comment]
收录 ws 生成图片加逻辑设置utf8编码

**Comment by zhang6685979** [comment]
> 收录 ws 生成图片加逻辑设置utf8编码

好的，谢谢

**Comment by weileai** [comment]
我也遇到了这个问题.
经过尝试,jar包启动时设置编码还是不行.
收录ws生成图片,具体如何操作呢?我看了它是使用的是poi导出时生成的图片,
大神能说一下如何解决呢?

**Comment by 1298191366** [comment]
已修复，待新版本发布
