### ISSUE TITLE
表格不渲染

### ISSUE THREAD

**Issue by sunshanjin** [jeecgboot/JimuReport#407]
##### 版本号：
1.3.64-beta

##### 问题描述：
使用elementui iframe显示报表时，出现报表不渲染情况

##### 截图&代码：

![image](https://user-images.githubusercontent.com/7366954/127583386-c22355e3-0d42-4c13-8609-8cd10ea5107d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
描述过于简单，无法分析
