### ISSUE TITLE
Api参数始终传的是默认值

### ISSUE THREAD

**Issue by tyhg001** [jeecgboot/JimuReport#409]
##### 截图&代码：
具体api参数配置：
![image](https://user-images.githubusercontent.com/19584941/127621710-1b7f4bd8-1ea5-4945-9481-f06e104740d4.png)

url中传的参数：
![image](https://user-images.githubusercontent.com/19584941/127621775-ec24bde5-9292-4044-ab2d-f0774f08eb76.png)

后台实际接收到的参数：
![image](https://user-images.githubusercontent.com/19584941/127620983-24e21b24-5266-484d-9cbf-8b831ee4a200.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 ws

**Comment by 1298191366** [comment]
测试无问题，浏览器地址拼接错误，凭借的是$里面的参数，不是前面的。
![image](https://user-images.githubusercontent.com/30997828/127802172-e4ec4866-20a9-4adf-a038-bbde28c61ea5.png)

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/127803072-8f1022ed-3395-40c4-b5d5-da7b0849ef23.png)

url的参数名应该是全小写，不是驼峰
