### ISSUE TITLE
设置4位小数后，报表显示错误

### ISSUE THREAD

**Issue by sunshanjin** [jeecgboot/JimuReport#411]
##### 版本号：
1.3.7

##### 问题描述：
报表字段设置位4位小数后，预览显示错误

##### 截图&代码：
设置4位小数显示如下：

![image](https://user-images.githubusercontent.com/7366954/127729988-59130579-485a-4922-ba25-16c1ba986864.png)
设置两位小数显示如下：
![image](https://user-images.githubusercontent.com/7366954/127729997-0652d5ea-f17a-44ff-a595-f6f95d5d991a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
请把你的设置操作截图

**Comment by tygithub1** [comment]
现在的情况是：我测试是没有问题的
![image](https://user-images.githubusercontent.com/27989856/127846869-ae3b010e-da6c-49d7-88bf-acbd34b11f0b.png)
建议到线上造个例子：http://www.jimureport.com/
