### ISSUE TITLE
设置小数位，导出后，不带小数

### ISSUE THREAD

**Issue by sunshanjin** [jeecgboot/JimuReport#412]
##### 版本号：
1.3.7

##### 问题描述：
报表设置2位小数，预览正常，但是导出后，小数位消失

##### 截图&代码：
设置2位小数显示如下
![image](https://user-images.githubusercontent.com/7366954/127730038-3b2745a8-8003-4f83-9ee9-fe74f5b8d7ff.png)
导出excel后显示如下：
![image](https://user-images.githubusercontent.com/7366954/127730057-5dbe3e41-17b0-44d8-adf7-658310a7c350.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
请把你的设置操作截图

**Comment by sunshanjin** [comment]
> 请把你的设置操作截图

![image](https://user-images.githubusercontent.com/7366954/127801075-6295a20e-fa2e-4d3b-b63a-9dde5a65d384.png)

**Comment by 1298191366** [comment]
已修复，待新版本发布
