### ISSUE TITLE
小数点变成了千分符

### ISSUE THREAD

**Issue by sunshanjin** [jeecgboot/JimuReport#413]
##### 版本号：
1.3.7

##### 问题描述：
设置字段保留两位小数，预览时，小数点变成了千分符

##### 截图&代码：
![image](https://user-images.githubusercontent.com/7366954/127730153-acc563d1-91ea-436d-a66d-868d3607ef8e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
请把你的设置操作截图

**Comment by sunshanjin** [comment]
> 请把你的设置操作截图

![image](https://user-images.githubusercontent.com/7366954/127800935-6ea0eb3c-a5e6-48ee-b332-4462d3cd4d36.png)

**Comment by sunshanjin** [comment]
> 请把你的设置操作截图
![image](https://user-images.githubusercontent.com/7366954/127800983-8c71e78c-e802-497d-8f94-be7795ad62bb.png)

**Comment by tygithub1** [comment]
确认问题，已修复，下个版本发布
