### ISSUE TITLE
在一个单元格里行间距无法调整

### ISSUE THREAD

**Issue by lulusoft** [jeecgboot/JimuReport#415]
##### 版本号：

2.4.5
##### 问题描述：
在一个单元格里有多行文字，需要调整行间距，目前无法加载样式进行调整

##### 截图&代码：
比如：在一个单元格里对如下文字
JeecgBoot 是一款基于代码生成器的低代码开发平台，零代码开发！采用前后端分离架构：SpringBoot2.x，Ant Design&Vue，Mybatis-plus，Shiro，JWT。强大的代码生成器让前后端代码一键生成，无需写任何代码! JeecgBoot引领新的开发模式(Online Coding模式-> 代码生成器模式-> 手工MERGE智能开发)， 帮助解决Java项目70%的重复工作，让开发更多关注业务逻辑。既能快速提高开发效率 
想调整为
JeecgBoot 是一款基于代码生成器的低代码开发平台，零代码开发！采用前后端分离架构：SpringBoot2.x，Ant Design&Vue，

Mybatis-plus，Shiro，JWT。强大的代码生成器让前后端代码一键生成，无需写任何代码! JeecgBoot引领新的开发模式(Online 

Coding模式-> 代码生成器模式-> 手工MERGE智能开发)， 帮助解决Java项目70%的重复工作，让开发更多关注业务逻辑。既能快

速提高开发效率 

目前无法实现。
建议：对每个单元格可以加样式

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
请图文并茂

**Comment by lulusoft** [comment]
由于需要对文字自动扩展和换行，采用在一列里显示，但需要行间距增大，而无法实现
![image](https://user-images.githubusercontent.com/3874472/127764289-f8d987b1-4622-4d5d-9cdb-3138979c8682.png)
目前只能
![image](https://user-images.githubusercontent.com/3874472/127764579-7cbd3b5a-7e13-43d0-af01-f08d6ff500fd.png)
而无法达到如下效果

![image](https://user-images.githubusercontent.com/3874472/127764409-33590468-688c-4cdc-88b7-7f768d4b7d66.png)

**Comment by zhangdaiscott** [comment]
不支持样式

**Comment by lulusoft** [comment]
这就是解决方案？
