### ISSUE TITLE
横向分组下，表头的默认排序失效

### ISSUE THREAD

**Issue by HyoKaWeng** [jeecgboot/JimuReport#417]
##### 版本号：
v1.3.7

##### 问题描述：
我想要在横向分组下实现一个中文月份的表头，我将横向分组的单元格设置成默认排序方式，发现实际预览的效果却没有按照数据集从后端所返回的排序方式，有点像是正序的排序方式。此后，我尝试将版本回退至v1.3.64-beta发现该版本下的横向分组的表头是支持默认排序，烦请校验，望答复。

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/54339660/127797404-e056416c-5f70-4fe7-946b-702a76546ab2.png)
![图片](https://user-images.githubusercontent.com/54339660/127797411-64d4f9ff-dcc3-4bfd-be17-bc6e9a563a5d.png)
![图片](https://user-images.githubusercontent.com/54339660/127797512-b84ffa8e-d829-4b03-99d4-9beaecb95109.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
能否提供模板数据，升级sql或者在线上设计

**Comment by accpman** [comment]
已修复，等下个版本
