### ISSUE TITLE
横向分组下，表头不支持括号等符号

### ISSUE THREAD

**Issue by HyoKaWeng** [jeecgboot/JimuReport#418]
##### 版本号：
v1.3.7

##### 问题描述：
我想要实现在表头中展示形如"里程(公里)"或是"里程/km"的效果，但是实际预览的时候，会抛出异常，并且报表不会显示任何内容(全白),经测试，一些符号无论是中文下还是英文下都是无法显示的

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/54339660/127797916-0acb0feb-3764-416e-96a8-fa5bd9fbccb6.png)
![图片](https://user-images.githubusercontent.com/54339660/127797924-f76a78ae-3415-4bfa-8a5b-4c1a6fd836ca.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 yf

**Comment by accpman** [comment]
已修复
