### ISSUE TITLE
导出pdf不支持自动行高

### ISSUE THREAD

**Issue by baojian9420** [jeecgboot/JimuReport#419]
##### 版本号：
1.3.7

##### 问题描述：
预览、导出excel支持自动行高，**导出pdf不支持自动行高**，望适配

##### 截图&代码：
![image](https://user-images.githubusercontent.com/54088765/127820219-5d0ad489-3b40-4e2e-81ac-862e64a612d3.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
暂时不支持

**Comment by SunflowerGY** [comment]
这么重要的功能都不支持吗，这导出效果与用户预期效果都不一致！

**Comment by lvdandan16** [comment]
收录 ws

**Comment by lvdandan16** [comment]
重复问题，后续修改，已归集到 #138 关闭此问题

**Comment by fqfcuc** [comment]
我们也遇到这个问题了
