### ISSUE TITLE
默认参数不能渲染到pdf上

### ISSUE THREAD

**Issue by baojian9420** [jeecgboot/JimuReport#420]
##### 版本号：
1.3.7

##### 问题描述：
自定义api数据集，参数设置默认值不能渲染到导出的pdf中

##### 截图&代码：
![image](https://user-images.githubusercontent.com/54088765/127821498-d3ba7c19-a982-409d-8919-72ef0eb5c31f.png)
![image](https://user-images.githubusercontent.com/54088765/127821556-42f611ec-1c22-4ae4-858c-eadbf59885e6.png)
![image](https://user-images.githubusercontent.com/54088765/127821644-f3cf6043-46ff-4198-8f0d-d65092e9a9ac.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
统一规划，先归集到 https://github.com/jeecgboot/JimuReport/issues/138
