### ISSUE TITLE
请支持单元格内嵌html代码

### ISSUE THREAD

**Issue by lulusoft** [jeecgboot/JimuReport#421]
##### 版本号：
v1.3.7

##### 问题描述：
由于目前单元格不支持样式定义，遇到多行自动换行时行间距无法调整，其他控件如ldop采用的是html内嵌设计，建议支持该需求

##### 截图&代码：
即实现ldop如下功能：

![image](https://user-images.githubusercontent.com/3874472/127837922-1064ca94-fbf6-4ef2-9fbf-83a3f7d54c7f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
暂时不支持，归集到 https://github.com/jeecgboot/JimuReport/issues/138
