### ISSUE TITLE
通过springcloud gateway访问的时候静态资源报错404

### ISSUE THREAD

**Issue by zhuhaitingfeng** [jeecgboot/JimuReport#423]
##### 版本号：
1.3.65-beta

##### 问题描述：
通过springcloud gateway访问的时候静态资源报错404

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/38696855/127945935-b0feef48-d70a-46db-8801-640c453e6af4.png)
![image](https://user-images.githubusercontent.com/38696855/127945934-09712c0f-30b4-4505-8b26-91578b6a2d88.png)

##### 重现步骤：
在springcspringcloud的gateway里面的yml访问的时候加上 predicates:
        - Path=/report/**, /static/**, /public/**依然访问不了静态资源（例如js，css文件）

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
http://report.jeecg.com/2302149
#自定义项目前缀
    customPrePath:
