### ISSUE TITLE
为什么会有一次全量查询的sql（不带分页的）

### ISSUE THREAD

**Issue by zhuhaitingfeng** [jeecgboot/JimuReport#424]
##### 版本号：
1.3.65-beta

##### 问题描述：
有一次全量查询的sql（不带分页的）

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/38696855/127947772-b7fb364d-35da-4b15-a91b-d281f115d6dd.png)

##### 重现步骤：
我这边直接将mysql开放日志打印功能，得到的结果和服务器日志页面一样的效果，就是查询一次报表的时候首次会执行不带分页的sql，这样的话数据量达到几万条的时候就会直接导致oom

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
是什么报表，什么场景，详细描述

**Comment by zhuhaitingfeng** [comment]
> 是什么报表，什么场景，详细描述

数据报表，我设置了分页的场景下也走了一次全量查询
![image](https://user-images.githubusercontent.com/38696855/127952511-c138f278-54e8-425f-8224-04c9236ae44a.png)

**Comment by zhangdaiscott** [comment]
是设置了字段查询导致的？

**Comment by zhuhaitingfeng** [comment]
我有尝试没有任何字段查询的报表，也一样查询了全部的

**Comment by zhuhaitingfeng** [comment]
> 是设置了字段查询导致的？

我有尝试没有任何字段查询的报表，也一样查询了全部的

**Comment by zhangdaiscott** [comment]
未重现，本地升级最新版本，先本地测下

**Comment by zhuhaitingfeng** [comment]
> 未重现，本地升级最新版本，先本地测下

https://github.com/jeecgboot/JimuReport/issues/425 可以看下这个issue不，如果支持的话设置了字段查询就不用全量查询了

**Comment by zhuhaitingfeng** [comment]
> 未重现，本地升级最新版本，先本地测下

![image](https://user-images.githubusercontent.com/38696855/128113436-1bb42210-5c06-4861-84d1-790adb2a1182.png)
新版本是正常的，只有两条sql（不用字段分页的情况下）

**Comment by zhuhaitingfeng** [comment]
> 未重现，本地升级最新版本，先本地测下

![image](https://user-images.githubusercontent.com/38696855/128115814-95dec619-e504-42ca-8a45-fc25a4712e7a.png)
![image](https://user-images.githubusercontent.com/38696855/128115827-1cb065ed-7d23-4161-9075-dfa5b69dd98c.png)
如图所示至少应该只需要一次全量查询，但是我勾选了四个字段，这边竟然来了四次全量查询了，其实这里可以优化下，一个全量查询，然后前端去distinct，不错真实我用了帆软和rdp报表工具这里最佳的处理方法就是我这个issue所提出来的，用sql集去处理搜索条件https://github.com/jeecgboot/JimuReport/issues/425

**Comment by zhangdaiscott** [comment]
配置了查询字段才会导致此问题，你不是说不配置查询也会出问题吗

**Comment by zhuhaitingfeng** [comment]
> 配置了查询字段才会导致此问题，你不是说不配置查询也会出问题吗

不配置查询目前发现没问题
