### ISSUE TITLE
搜索条件不支持来自于数据源

### ISSUE THREAD

**Issue by zhuhaitingfeng** [jeecgboot/JimuReport#425]
##### 版本号：
1.3.65-beta

##### 问题描述：
有一次全量查询的sql（不带分页的）

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/38696855/127948383-056995d7-406e-4e0a-8edb-f654efa8684a.png)
![image](https://user-images.githubusercontent.com/38696855/127950705-cf1ffaf5-036c-456c-8a93-2f4026bc5879.png)

##### 重现步骤：
这种实现方式应该是去掉分页条件之后查出所有数据，然后再distinct得到去重后的数据，应该要单独给个数据源去获取搜索条件的数据，这种实现方式会导致oom，虽然提供api模式的，但是要组装数据很麻烦，希望能提供sql数据集形式的（类似图二这种，专门提供一个sqlshuj数据集去实现搜索条件的数据源，这样就避免了全量查询带来的oom问题了，并且最关键的是简单方便）

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
统一规划，先归集到 https://github.com/jeecgboot/JimuReport/issues/138
