### ISSUE TITLE
分组内小计不生效

### ISSUE THREAD

**Issue by zhuhaitingfeng** [jeecgboot/JimuReport#427]
##### 版本号：
1.3.7

##### 问题描述：
分组内小计不生效

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/38696855/127993454-08a38a11-8fbf-4e10-a9a6-934ffa2ff3e9.png)
![image](https://user-images.githubusercontent.com/38696855/127993470-1fb0fce8-4372-468c-a100-e4215de2e8cd.png)
![image](https://user-images.githubusercontent.com/38696855/127993481-f4b0459e-48db-4265-aacc-309e4f213727.png)
![image](https://user-images.githubusercontent.com/38696855/127993716-63d3ca57-aa4f-4c88-9d90-9b6dc8d55aed.png)

##### 重现步骤：
分别按照三张图顺序设置了小计分组字段，下方显示小计文本，求和列，但是最终数据查询出来没有小计这行，不清楚问题在哪里，都是按照http://report.jeecg.com/2333594  （1.7 分组内小计）操作的

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你这截图太不专业，完全看不出怎么设置的

**Comment by zhuhaitingfeng** [comment]
> 你这截图太不专业，完全看不出怎么设置的

你这边可以单独点击图片，查看右边的分组设计和小计设置，单机点击图片就很清晰了

**Comment by zhuhaitingfeng** [comment]
> 你这截图太不专业，完全看不出怎么设置的

或者说你这边还需要我提供哪方面的截图，我可以再截取下

**Comment by zhangdaiscott** [comment]
去线上做个例子

**Comment by zhuhaitingfeng** [comment]
> 去线上做个例子

https://bootapi.jeecg.com/jmreport/index/582780685736300544?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjgwNTg3NTcsInVzZXJuYW1lIjoib2hiYUs2VEliVktZcUpXRzdEbGtNNDZHV2NjYyJ9.gYP2yF85D1DZ7_fBukAZQdzVgQDBcJiurz7CJOUg0NM


已经建好

**Comment by zhuhaitingfeng** [comment]
> 去线上做个例子

你好，请问下是哪里有问题呢

**Comment by lvdandan16** [comment]
收录 yf
