### ISSUE TITLE
不能导出PDF

### ISSUE THREAD

**Issue by caoshuiming** [jeecgboot/JimuReport#428]

**Comment by caoshuiming** [comment]
前端报错：Uncaught(in promise) TypeError: Cannot read property 'cells' of undefined
at e.value(jmsheet.js?v=1.0.25:197)

**Comment by zhangdaiscott** [comment]
先升级到最新，http://jimureport.com/doc/log ，再清理浏览器缓存

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；
