### ISSUE TITLE
希望能优化下报表分组功能

### ISSUE THREAD

**Issue by JCH9527** [jeecgboot/JimuReport#429]
##### 版本号：
1.3.7
##### 问题描述：
报表分组功能给第一、第二和第三个字段设置聚合方式分组，如果其中一个字段没有相同内容则不会合并，但会导致下一个有相同内容的字段不会合并。
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/87842203/128109895-c8183612-ee7f-42ed-9a9e-c517b0ea2441.png)
![image](https://user-images.githubusercontent.com/87842203/128109939-efdafad9-ec79-4e8a-85ce-ea0d541f8946.png)
##### 重现步骤：
给报表分组设置，聚合方式选择分组，保存，预览。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持
