### ISSUE TITLE
报表打印时如何固定表头表展

### ISSUE THREAD

**Issue by kmxiaohao** [jeecgboot/JimuReport#430]
##### 问题描述：
报表设计时：如何像execl 里，设置打印标题，表尾。

##### 错误日志&截图：
![图片](https://user-images.githubusercontent.com/88417222/128120225-e5fc58e5-59bc-485a-8f12-037aba64fb7a.png)
如图，每一页都有相应的表头表尾显示
销售单据明细，每页都有对应的表头，每页有表尾，是否支持，如果支持，如何设置

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持

**Comment by love88758** [comment]
> 不支持

这个功能有计划支持吗，固定页眉页脚经常会用到
