### ISSUE TITLE
1.3 动态列分组(横向)不生效

### ISSUE THREAD

**Issue by zhuhaitingfeng** [jeecgboot/JimuReport#432]
##### 版本号：
1.3.7

##### 问题描述：
 动态列分组(横向)不生效

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/38696855/128138641-accc5f02-2474-41e0-a967-d74153bdfd12.png)
![image](https://user-images.githubusercontent.com/38696855/128138697-a2bcee02-7c81-4d4c-a0b9-8aaa672e7e45.png)
![image](https://user-images.githubusercontent.com/38696855/128138798-8f33dd00-f98b-4767-8279-3b128557e06f.png)

##### 重现步骤：
按照1.3 动态列分组(横向)如上图配置，结果不生效，显示如最下方图的效果

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhuhaitingfeng** [comment]
![image](https://user-images.githubusercontent.com/38696855/128140941-218b866e-ddc0-4c04-b122-f94c21987175.png)
![image](https://user-images.githubusercontent.com/38696855/128140980-baa0d168-95c1-4c47-a044-654284ec2097.png)
按照   1.4 组合动态列分组 增加了动态属性之后，第二张图片报错空指针异常

**Comment by zhuhaitingfeng** [comment]
![image](https://user-images.githubusercontent.com/38696855/128144532-7197bc10-2cad-4d95-97d1-5ea4796036d0.png)
我看了你们这个例子的也挂了，报错500

**Comment by lvdandan16** [comment]
提供线上例子，我们来测试

**Comment by lvdandan16** [comment]
收录 yf

**Comment by zhuhaitingfeng** [comment]
> 提供线上例子，我们来测试

https://bootapi.jeecg.com/jmreport/view/584537267553783808?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2Mjg0Nzc5MDAsInVzZXJuYW1lIjoib2hiYUs2VEliVktZcUpXRzdEbGtNNDZHV2NjYyJ9.DyjeKFYA3gyuK9RT0An0KTgFlMj7DxOJ0c_ec103rc0

例子已经提供，不过线上的出了另外一个问题，按理来说这里有两个交易号，应该展示两条数据，现在核心问题是本地一模一样配置还直接报错空指针了

**Comment by accpman** [comment]
![Uploading image.png…]()
ownername也不允许为空，分组列的数据不能为空

**Comment by zhuhaitingfeng** [comment]
> ownername也不允许为空，分组列的数据不能为空

![image](https://user-images.githubusercontent.com/38696855/128690676-f8e6aaca-3d23-405f-9ab0-c3d64f6d6277.png)

线上的例子没问题了，但是为什么本地还是报错空指针呢

https://bootapi.jeecg.com/jmreport/view/584537267553783808?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2Mjg1MDQzOTUsInVzZXJuYW1lIjoib2hiYUs2VEliVktZcUpXRzdEbGtNNDZHV2NjYyJ9.YQyP8EjMJUU6L36z3-UZoervygZByK2SxToDjTtPrBo

这是线上例子，本地一模一样，依赖是1.3.75
