### ISSUE TITLE
集成积木后。数据源维护报错

### ISSUE THREAD

**Issue by Zhaozziyan** [jeecgboot/JimuReport#433]
##### 版本号：
1.3.7

##### 问题描述：
数据源维护。点击测试报错。无法连接数据源

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/88430383/128157537-78fced21-540a-487f-bf12-b01631f18a12.png)
![image](https://user-images.githubusercontent.com/88430383/128157589-26772d6b-53bf-42f1-8ee0-fbf186e3cb7a.png)
![image](https://user-images.githubusercontent.com/88430383/128157734-640accc5-7e1a-4e80-8255-8212dbc276fb.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
什么版本

**Comment by Zhaozziyan** [comment]
> 什么版本

1.3.7。并且执行了最新的sql

**Comment by zhangdaiscott** [comment]
数据库什么版本

**Comment by Zhaozziyan** [comment]
> 数据库什么版本

数据库是5.7.11

**Comment by zhangdaiscott** [comment]
https://blog.csdn.net/weixin_43668662/article/details/104193421?utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-1.control&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-1.control

自己百度
