### ISSUE TITLE
打印方面建议

### ISSUE THREAD

**Issue by Mr-Pro** [jeecgboot/JimuReport#434]
##### 版本号：
next

##### 问题描述：
建议可推出打印报表方面客户端支持，可以Web直接调起打印，设计器内可以设置打印偏好，通过客户端直接调起打印操作，具体可参见锐浪报表。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不预览直接的打印？

**Comment by Mr-Pro** [comment]
> 不预览直接的打印？

是的，比如一些营业大厅或者是一些打票场景，他们只需要预先调好打印偏移，校准发票内容格式，后续的只是一直打票，并不需要一直预览。
