### ISSUE TITLE
1.4 组合动态列分组 报错空指针

### ISSUE THREAD

**Issue by zhuhaitingfeng** [jeecgboot/JimuReport#436]
##### 版本号：
1.3.7

##### 问题描述：
按照官网提供的 各地区商品销售额一栏表 例子操作报错空指针异常

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/38696855/128282896-615aa2a2-11e2-4a5d-8db6-7b7988e6659f.png)
![image](https://user-images.githubusercontent.com/38696855/128282947-f7d1f000-9a44-44fb-be84-7cbc17b08172.png)

##### 重现步骤：
步骤一模一样，但是报错空指针异常

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 yf

**Comment by accpman** [comment]
当你报表向右横向扩展时，其实就是行转列，当行转列的时候业主姓名，收款日期，支付方式收费员等纵向字段肯定会出现重复的值，此时需要对纵向的字段全部进行分组

**Comment by zhuhaitingfeng** [comment]
> 当你报表向右横向扩展时，其实就是行转列，当行转列的时候业主姓名，收款日期，支付方式收费员等纵向字段肯定会出现重复的值，此时需要对纵向的字段全部进行分组

https://bootapi.jeecg.com/jmreport/view/584537267553783808?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2Mjg0Nzc5MDAsInVzZXJuYW1lIjoib2hiYUs2VEliVktZcUpXRzdEbGtNNDZHV2NjYyJ9.DyjeKFYA3gyuK9RT0An0KTgFlMj7DxOJ0c_ec103rc0

我有按你说的这么配置了，结果发现出问题都不显示了

**Comment by zhuhaitingfeng** [comment]
> 当你报表向右横向扩展时，其实就是行转列，当行转列的时候业主姓名，收款日期，支付方式收费员等纵向字段肯定会出现重复的值，此时需要对纵向的字段全部进行分组

https://bootapi.jeecg.com/jmreport/index/584537267553783808?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2Mjg0Nzc5MDAsInVzZXJuYW1lIjoib2hiYUs2VEliVktZcUpXRzdEbGtNNDZHV2NjYyJ9.DyjeKFYA3gyuK9RT0An0KTgFlMj7DxOJ0c_ec103rc0

要不你这边尝试给这个配置下看如何实现（按理应该是两条数据）

**Comment by accpman** [comment]
业主姓名列值不能空

**Comment by accpman** [comment]
![image](https://user-images.githubusercontent.com/4446237/128694097-ec7e379a-28cd-443f-af88-ca14e6cf44e1.png)

**Comment by zhuhaitingfeng** [comment]
> 业主姓名列值不能空

![image](https://user-images.githubusercontent.com/38696855/128694092-c635165f-c18a-4cd6-8092-af7e653d5839.png)
线上li例子没问题了，本地还是空指针

**Comment by accpman** [comment]
加我QQ574501933
