### ISSUE TITLE
使用postman测试带权限后返回403

### ISSUE THREAD

**Issue by sunshanjin** [jeecgboot/JimuReport#437]
##### 版本号：
1.3.7

##### 问题描述：
使用postman测试带权限后返回403

##### 错误日志&截图：
使用postman测试导出接口/jmreport/exportAllExcel时，如果不带权限，则可以正常返回json，否则返回403
不带权限：
![image](https://user-images.githubusercontent.com/7366954/128308049-b6892ad2-517f-4251-ac6b-ada7abed6d61.png)
带权限：
![image](https://user-images.githubusercontent.com/7366954/128308281-68e1a31e-d47b-41f8-acf7-80322b905461.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
怎么个带权限？

**Comment by sunshanjin** [comment]
> 怎么个带权限？
![image](https://user-images.githubusercontent.com/7366954/128313868-e19cdf28-deed-467e-b7b1-565cb06574f4.png)

**Comment by lvdandan16** [comment]
是不是用法有问题？
