### ISSUE TITLE
 不通过url中带参数的方式,  sql数据集中的参数 是否可以支持动态参数注入

### ISSUE THREAD

**Issue by tengpeter** [jeecgboot/JimuReport#438]
##### 版本号：
     1.3.7
##### 问题描述：
     数据集中的参数 支不支持动态参数注入的形式

##### 重现步骤：
    不通过url中带参数的方式,  sql数据集中的参数 是否可以支持动态参数注入

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不通过url中带参数的方式，你想通过什么方式

**Comment by tygithub1** [comment]
等新版发布，可参考文档：https://www.kancloud.cn/zhangdaiscott/jimureport/2373410
