### ISSUE TITLE
数据集配置点击确认会报如下错误

### ISSUE THREAD

**Issue by Linxin1126** [jeecgboot/JimuReport#439]
##### 版本号：

1.3.7
##### 问题描述：
数据集配置点击确认会报如下错误

##### 错误日志&截图：
org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [INSERT INTO jimu_report_db ( ID ,JIMU_REPORT_ID ,CREATE_BY ,UPDATE_BY ,CREATE_TIME ,UPDATE_TIME ,DB_CODE ,DB_CH_NAME ,DB_TYPE ,DB_TABLE_NAME ,DB_DYN_SQL ,DB_KEY ,TB_DB_KEY ,TB_DB_TABLE_NAME ,JAVA_TYPE ,JAVA_VALUE ,API_URL ,API_METHOD ,IS_PAGE ,DB_SOURCE ,DB_SOURCE_TYPE ,IS_LIST ,JSON_DATA ,API_CONVERT ) values ( ? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? )]; SQL state [null]; error code [0]; Error; nested exception is java.sql.SQLException: Error

##### 重现步骤：
<img width="1443" alt="iShot2021-08-06 11 20 18" src="https://user-images.githubusercontent.com/65431980/128451213-e1d4735a-d483-402f-8b47-54c7e3e40d21.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
数据库字段完整了？ 执行了升级脚本了吗
http://jimureport.com/doc/log

**Comment by Linxin1126** [comment]
> 数据库字段完整了？ 执行了升级脚本了吗
> http://jimureport.com/doc/log

全都升级成最新的了

**Comment by zhangdaiscott** [comment]
你对比下，看看是不是缺字段

**Comment by Linxin1126** [comment]
> 你对比下，看看是不是缺字段
重复对比过了 不存在缺字段的情况

**Comment by zhangdaiscott** [comment]
这个错误重现不了，无法排查

**Comment by lvdandan16** [comment]
收录 ty

**Comment by Linxin1126** [comment]
问题已解决，使用mysql驱动5.1.47会出现如上错误，换成其他版本，如：5.1.46
