### ISSUE TITLE
动态列报错空指针

### ISSUE THREAD

**Issue by zhuhaitingfeng** [jeecgboot/JimuReport#440]
##### 版本号：
1.3.7

##### 问题描述：
动态列报错空指针

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/38696855/128471980-63ebb602-9c41-452c-bc9b-aaf5ecb59039.png)
![image](https://user-images.githubusercontent.com/38696855/128471987-053e80a4-f3f2-404b-8263-7629e79906e7.png)
![image](https://user-images.githubusercontent.com/38696855/128472056-bf7b7f4a-5055-4b58-86d1-892a3b6edf0c.png)

##### 重现步骤：
用的是最下面的图来处理，数据源等都是一模一样，但是就是报错空指针

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhuhaitingfeng** [comment]
![image](https://user-images.githubusercontent.com/38696855/128477931-1654233a-4049-4153-9bbb-fb1707b55493.png)
https://bootapi.jeecg.com/jmreport/index/583532675571470336?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjgyMzg0MTgsInVzZXJuYW1lIjoib2hiYUs2VEliVktZcUpXRzdEbGtNNDZHV2NjYyJ9.9y1lbPZyr81aNOr1Aq3sTyCbrwqi5ZqiRNYenBqmU0k

我在官网上弄了一个一模一样的，官网执行成功，但是1.3.7版本执行失败了

**Comment by zhangdaiscott** [comment]
升级到 1.3.72

**Comment by zhuhaitingfeng** [comment]
> 升级到 1.3.72

![image](https://user-images.githubusercontent.com/38696855/128480318-059ac99f-f47b-42f3-a99a-b3c5c54da913.png)
![image](https://user-images.githubusercontent.com/38696855/128480375-c3ac6ffd-a4ae-4ccf-9675-1d9f0f74cf9f.png)

刚刚升级了依然报这个错，你们能不能帮忙测试下这个场景呢

**Comment by zhangdaiscott** [comment]
确定依赖变成功了?

**Comment by zhangdaiscott** [comment]
刚发了一个  1.3.73，改完依赖，记得刷新
![image](https://user-images.githubusercontent.com/3162115/128487976-e0124930-cfce-40df-a93f-4cda4a9e08d8.png)

**Comment by zhuhaitingfeng** [comment]
> 刚发了一个 1.3.73，改完依赖，记得刷新
> ![image](https://user-images.githubusercontent.com/3162115/128487976-e0124930-cfce-40df-a93f-4cda4a9e08d8.png)

![image](https://user-images.githubusercontent.com/38696855/128490675-df09d889-b628-431a-b975-8be7383e7a94.png)
能否加下qq远程调试下，我升级了依然还是报错空指针，我的qq是1729985580

**Comment by lvdandan16** [comment]
收录 yf

**Comment by zhuhaitingfeng** [comment]
> 收录 yf

yf是啥意思呢

**Comment by zhuhaitingfeng** [comment]
> 确定依赖变成功了?

![image](https://user-images.githubusercontent.com/38696855/128664287-4156616d-a4d3-43e6-bb9d-df9068c3beb6.png)
依赖是没问题的

**Comment by accpman** [comment]
当你报表向右横向扩展时，其实就是行转列，当行转列的时候业主姓名，收款日期，支付方式收费员等纵向字段肯定会出现重复的值，此时需要对纵向的字段全部进行分组
