### ISSUE TITLE
当新报表过大时,后台报错

### ISSUE THREAD

**Issue by csw443702124** [jeecgboot/JimuReport#441]
##### 

> 版本号：1.3.64-beta

##### 问题描述：
新建个excel 报表,保存时出错

##### 错误日志&截图：
![微信图片_20210806161954](https://user-images.githubusercontent.com/60021842/128480178-5873c3f7-740c-4ed1-8a2d-e3443c482475.png)

##### 重现步骤：
新建报表,上传Excel 表格,保存 出错   需要excel表格模板可以加我QQ 443702124

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
字段类型改成
![image](https://user-images.githubusercontent.com/3162115/128485977-082c6383-ae7a-4fa6-a39a-2ae78ea90309.png)
```
ALTER TABLE `jeecgboot`.`jimu_report` 
MODIFY COLUMN `json_str` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT 'json字符串' AFTER `type`;
```
