### ISSUE TITLE
1.3.7 报表设计器报错：不支持该SQL转换为分页查询

### ISSUE THREAD

**Issue by iGuozy** [jeecgboot/JimuReport#442]
##### 版本号：
1.3.7

##### 问题描述：
报表设计器报错：不支持该SQL转换为分页查询

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/48822119/128621599-d0a29577-3d70-49c3-b153-30a0f79afd22.png)
![image](https://user-images.githubusercontent.com/48822119/128621614-ca973e72-38ca-4cd4-ac72-36eb9be535d7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
什么数据库？可以升级到1.3.72

**Comment by iGuozy** [comment]
SQL Server

**Comment by zhangdaiscott** [comment]
升级就好了
