### ISSUE TITLE
PDF导出失败

### ISSUE THREAD

**Issue by caoshuiming** [jeecgboot/JimuReport#446]
##### 错误日志&截图：
![微信图片_20210809172610](https://user-images.githubusercontent.com/77309395/128686452-d09f40bd-db8f-4718-9058-c6a9f7c74c6e.jpg)
![微信图片_20210809173503](https://user-images.githubusercontent.com/77309395/128686572-7ce660c0-cef4-4cfe-9642-55325816231a.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
能在线上做个例子？

**Comment by caoshuiming** [comment]
有点难，但是我复现了另外一个bug，在官网做的
预览地址:&nbsp; https://bootapi.jeecg.com/jmreport/shareView/581005665607438336&nbsp;
预览密码:&nbsp; wyow
复制预览地址在浏览器打开

空指针异常


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月9日(星期一) 下午5:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] PDF导出失败 (#446)





 
能在线上做个例子？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangdaiscott** [comment]
收录 ws

**Comment by 1298191366** [comment]
第一个错Invalid font type 是初始化字体失败请查看是否引入中文字体宋体，第二个错线上应该是没有问题了，应该已经修改过了
