### ISSUE TITLE
积木大屏普通表格滚动bug

### ISSUE THREAD

**Issue by suchan66** [jeecgboot/JimuReport#447]
#### 版本号：
1.3.75
#### 问题描述：
线上大屏设计器使用普通表格时，开启滚动后，只滚动一小部分。无法显示所有数据。
#### 错误日志&截图：
我不会上传视频T^T
#### 重现步骤：
创建一个普通表格，数据类型使用静态数据，数据最好稍微多点，并开启滚动。
#### 备注：
用户名：18897828665
相关大屏名称：质量部大屏3-20210808

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
测试未重现你说的问题，请详细描述一下你的操作步骤和数据信息，最好加上截图

**Comment by suchan66** [comment]
#### 测试用例
1. 数据：10行；
[
    {
        "number": "111",
        "supplier": "A"
    },
    {
        "number": "222",
        "supplier": "B"
    },
    {
        "number": "333",
        "supplier": "C"
    },
    {
        "number": "444",
        "supplier": "D"
    },
    {
        "number": "555",
        "supplier": "E"
    },
    {
        "number": "666",
        "supplier": "F"
    },
    {
        "number": "777",
        "supplier": "G"
    },
    {
        "number": "888",
        "supplier": "H"
    },
    {
        "number": "999",
        "supplier": "I"
    },
    {
        "number": "101010",
        "supplier": "J"
    }
]

2. 显示：5行；
3. 滚动行数：3行。

#### 结果
最终只能显示到第8行。
![image](https://user-images.githubusercontent.com/30565066/129658900-d029132f-b9d7-4889-90d1-e0159ff018fa.png)

**Comment by lvdandan16** [comment]
滚动时间太短，数据未展示全，时间已结束
