### ISSUE TITLE
报表下钻参数不支持数据集字段

### ISSUE THREAD

**Issue by zxinghl** [jeecgboot/JimuReport#449]
##### 问题描述：
报表钻取 参数设置 提示支持下拉框选择数据集字段
但下拉列表中只能选择输入表达式、并没有数据集字段

##### 错误日志&截图：
<img width="531" alt="图片" src="https://user-images.githubusercontent.com/29223822/128798646-2767b9b6-d39a-4381-8ba6-fb9c074d1981.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
1.请说明版本号
2.说明数据集
3.是单元格还是图表添加的钻取配置

**Comment by lvdandan16** [comment]
因长时间未回复，关闭此任务
