### ISSUE TITLE
勾选一个列作为查询条件就多一次全量查询

### ISSUE THREAD

**Issue by zhuhaitingfeng** [jeecgboot/JimuReport#450]
##### 版本号：
1.3.7

##### 问题描述：
勾选一个列作为查询条件就多一次全量查询（不带分页的查询）

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/38696855/128824965-2db36508-bc4e-47db-bbea-e275c0d89d26.png)
![image](https://user-images.githubusercontent.com/38696855/128824989-a0216f11-1fea-41cd-906a-b593bd270ed8.png)

##### 重现步骤：
勾选一个列作为查询条件就多一次全量查询（不带分页的查询），如上图所示，勾选了四列作为查询条件，就多了四个全量查询，至少可以优化为一次全量查询就行

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
升级到1.3.75 已经改成分页加载

**Comment by zhuhaitingfeng** [comment]
> 升级到1.3.75 已经改成分页加载

不能这么解决吧，你这样会导致的结果就是找不到后面的数据（查询的时候），相当于是只对当前页的数据做下过滤

**Comment by zhangdaiscott** [comment]
你用了吗
