### ISSUE TITLE
导出与预览效果不一致

### ISSUE THREAD

**Issue by sunshanjin** [jeecgboot/JimuReport#451]
##### 版本号：
1.3.76

##### 问题描述：
页面预览时参数渲染正常，但是导出的参数渲染出现错误

##### 错误日志&截图：
预览界面：
![image](https://user-images.githubusercontent.com/7366954/128975760-59e65f18-191d-4690-844d-237bdcaa577d.png)
打印或导出界面：
![image](https://user-images.githubusercontent.com/7366954/128975850-f50b44a4-b65d-48df-bbed-342885fac997.png)

##### 重现步骤：
脚本：oracle11g数据库
select to_char(sysdate, 'yyyy')||'年'||to_char(sysdate, 'mm')||'月'||to_char(sysdate, 'dd')||'日' tab,
case when '${startYearMonth}' = '${endYearMonth}' then 
substr('${startYearMonth}', 1, 4) || '年' || substr('${startYearMonth}', 6, 2) || '月'
else
substr('${startYearMonth}', 1, 4) || '年' || substr('${startYearMonth}', 6, 2) || '月' || '~' || substr('${endYearMonth}', 1, 4) || '年' || substr('${endYearMonth}', 6, 2) || '月'
end
yearMonth from dual

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
设计页面截图

**Comment by sunshanjin** [comment]
> 请将设计页面截图

![image](https://user-images.githubusercontent.com/7366954/129496765-3ec41cc9-838b-40a6-9fb4-196751e51058.png)

**Comment by lvdandan16** [comment]
导出的数据值不正确？可否线上做个例子

**Comment by sunshanjin** [comment]
> 导出的数据值不正确？可否线上做个例子

![image](https://user-images.githubusercontent.com/7366954/129644381-6c34a575-3a6c-4b13-9423-3dc6b9f0d48a.png)
预览的时候是正常的，但是导出的excel就变成这样了

**Comment by sunshanjin** [comment]
> 导出的数据值不正确？可否线上做个例子

官网我没有数据库连接

**Comment by sunshanjin** [comment]
> 导出的数据值不正确？可否线上做个例子

预览地址:  https://bootapi.jeecg.com/jmreport/shareView/587916468289884160 
预览密码:  blm1
复制预览地址在浏览器打开

**Comment by 1298191366** [comment]
根据你网上的例子测试没有问题，或者升级到最新版1.3.792再次尝试，如果本地有问题请根据**[文档](http://report.jeecg.com/2376604)**将sql上传一下
最新版本(需要配置私服)
```<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.792</version>
</dependency>
```
![image](https://user-images.githubusercontent.com/30997828/130566778-93b892a8-a4d7-4f36-a0a3-feb1715b31d4.png)

**Comment by 1298191366** [comment]
已修复，待新版本发布
