### ISSUE TITLE
报表预览问题

### ISSUE THREAD

**Issue by daiyaoxin** [jeecgboot/JimuReport#452]
##### 版本号：
1.3.7

##### 问题描述：
可以进行SQL解析和数据预览，但是报表预览报错显示超时

##### 错误日志&截图：
 StatementCallback; SQL [SELECT COUNT(1) total FROM ( SELECT DISTINCT a.type '所属专业', a.`code` '工程编码', a.req_nickname '需求名称', '待设计' `工程状态`, a.area '区域', a.branch '分支局', a.create_time '创建时间', b.NAME '提单人员', b.phone '提单人电话', IF ( a.design_unit = 9, "四川院", "江苏院" ) "设计院", DATEDIFF( a.design_date, a.create_time ) `距离创建到设计结束时长`, a.design_date `设计结束时间`, d.`name` '设计人员', DATEDIFF( a.org_supervision_date, design_date ) `距离设计结束管理员处理时长`, a.org_supervision_date `工程管理员处理时间`, a.org_work_date `项目经理处理时间`, DATEDIFF( a.org_work_date, a.org_supervision_date ) `工程管理员到项目经理处理时长`, c.`name` '工程管理员', DATEDIFF((SELECT b.clock_time FROM gw_project_int_clock b WHERE b.filemanage_id = a.id LIMIT 1),a.org_work_date) `项目经理到开始施工时长`, (SELECT b.clock_time FROM gw_project_int_clock b WHERE b.filemanage_id = a.id LIMIT 1) `施工开始时间`, a.work_finish_date `施工结束时间`, DATEDIFF(a.work_finish_date,(SELECT b.clock_time FROM gw_project_int_clock b WHERE b.filemanage_id = a.id LIMIT 1)) `施工时长`, (SELECT COUNT(bb.id) FROM gw_project_int_clock bb WHERE bb.filemanage_id = a.id) `打卡数量`, e.`name` '施工队长' , IF(ISNULL(a.old_pole_num + a.new_pole_num),0,(a.old_pole_num + a.new_pole_num)) /( ( SELECT COUNT( gcn.id ) AS sign_num FROM gw_project_int_clock gcn WHERE gcn.filemanage_id = a.id AND gcn.clock_nodeid = 20 ) + ( SELECT COUNT( gcn.id ) AS sign_num FROM gw_project_int_clock gcn WHERE gcn.filemanage_id = a.id AND gcn.clock_nodeid = 5 ) )`杆路准确度`, IF(ISNULL(a.old_pole_num + a.new_pole_num),0,(a.old_pole_num + a.new_pole_num)) /( ( SELECT COUNT( gcn.id ) AS sign_num FROM gw_project_int_clock gcn WHERE gcn.filemanage_id = a.id AND gcn.clock_nodeid = 21 ) + ( SELECT COUNT( gcn.id ) AS sign_num FROM gw_project_int_clock gcn WHERE gcn.filemanage_id = a.id AND gcn.clock_nodeid = 6 ) )`管道准确度`, a.tie_line_date `杆路完成时间`, DATEDIFF(a.tie_line_date,a.work_finish_date) `施工完成到杆路完成时长`, (SELECT b.clock_time FROM gw_project_int_clock b WHERE b.filemanage_id = a.id AND b.type = 2 LIMIT 1) `监理巡检打卡时间`, (SELECT COUNT(cc.id) FROM gw_project_int_clock cc WHERE cc.filemanage_id = a.id and cc.type=2) `巡检打卡数`, (SELECT COUNT(dd.id) FROM gw_project_int_clock dd WHERE dd.filemanage_id = a.id AND dd.type = 2 AND dd.clock_nodeid = 30) `经济签证`, (SELECT COUNT(ee.id) FROM gw_project_int_clock ee WHERE ee.filemanage_id = a.id AND ee.type = 2 AND ee.clock_nodeid = 31) `隐蔽签证`, (SELECT COUNT(ff.id) FROM gw_project_int_clock ff WHERE ff.filemanage_id = a.id AND ff.type = 2 AND ff.clock_nodeid = 32 ) `技术签证` FROM gw_project_int a LEFT JOIN gw_user c ON ( c.id = a.project_manager ) LEFT JOIN gw_user d ON ( d.phone = a.design_receiving) LEFT JOIN gw_user e ON ( e.id = a.work_user), gw_user b WHERE a.create_user = b.phone AND a.delflag != 1 ) temp_count]; Statement cancelled due to timeout or client request; nested exception is com.mysql.cj.jdbc.exceptions.MySQLTimeoutException: Statement cancelled due to timeout or client reques

##### 重现步骤：

https://user-images.githubusercontent.com/84888786/129004065-a6378fd3-c8cb-4f26-933a-2df9424032b1.MP4

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级最新版本  1.3.78
