### ISSUE TITLE
报表查询下拉框 文字不显示问题

### ISSUE THREAD

**Issue by yueyunp** [jeecgboot/JimuReport#453]
##### 版本号：
1.3.7
##### 问题描述：
查询栏下拉框  文字查询选中多次后  选择框内无文字

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/88695123/129123098-4b052b39-35d9-4247-8693-c86c2cd58c01.png)

![image](https://user-images.githubusercontent.com/88695123/129123192-2fcc8c6f-9abb-4044-80f4-0d0f620e4ae9.png)

##### 重现步骤：
输入文字查询然后选中    多操作几次就会出现

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
升级到1.3.78 版本

**Comment by lvdandan16** [comment]
收录 ws
