### ISSUE TITLE
查询栏中的日期范围查询条件怎样默认查询当月1号到当前日期的数据

### ISSUE THREAD

**Issue by lilei82102911** [jeecgboot/JimuReport#454]
![image](https://user-images.githubusercontent.com/10509211/129125846-70bd30fc-ce2c-479f-ad8d-012dfd8bb79a.png)

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
最新版的也没有直接的表达式 可以参考下述操作：
![image](https://user-images.githubusercontent.com/27989856/129894892-88cdbeda-6876-4005-b6b2-e8ac8c02fccd.png)
```
// 默认值配置为
=concat(string.substring(dateStr('yyyy-MM-dd'),0, 8), '01')#=dateStr('yyyy-MM-dd')
```
效果：
![image](https://user-images.githubusercontent.com/27989856/129895022-1524ba4f-0ce5-4917-aabb-3c72f3471af6.png)
