### ISSUE TITLE
积木报表管理向左滑动列表，右边展示大片空白，向下滑动列表，下边有太多空白 

### ISSUE THREAD

**Issue by lixuejie64** [jeecgboot/JimuReport#456]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/47851046/129146579-3c0dc712-f192-47df-9dbd-ee4aca2c598f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
设计是什么样的  是不是本身页面有空格内容  新建一个，如果只在第一行第一列写一个文本 也会有这种问题吗？

**Comment by lvdandan16** [comment]
问题已修复，升级到最新版本
