### ISSUE TITLE
报表参数如果设置为查询条件，再通过URL传参就无效了

### ISSUE THREAD

**Issue by zxinghl** [jeecgboot/JimuReport#458]
##### 问题描述：
报表参数如果设置为查询条件，再通过URL传参就无效了

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
?

**Comment by lvdandan16** [comment]
1.说明版本号
2.截图设计页面

**Comment by lvdandan16** [comment]
因长时间未回复，关闭此任务
