### ISSUE TITLE
分页错乱

### ISSUE THREAD

**Issue by zhuhaitingfeng** [jeecgboot/JimuReport#459]
##### 版本号：
1.3.77

##### 问题描述：
分页错乱

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/38696855/129159888-5503b2d1-3939-469c-814f-720be314e90c.png)

##### 重现步骤：
刚进入首页的时候分页pageNo是0，刷选一个条件之后分页条件pageNo变成了1了

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by zhuhaitingfeng** [comment]
> 收录 ty

多谢老兄，望尽快解决

**Comment by tygithub1** [comment]
数据集配置界面截个图看看

**Comment by tygithub1** [comment]
经测试，无此问题，分页参数不需要自己拼到链接上，只需勾选分页配置，系统会自动传参
![image](https://user-images.githubusercontent.com/27989856/130552903-4b8caefa-9e56-4314-b219-3db216578d90.png)
