### ISSUE TITLE
时间组件增加年份类型

### ISSUE THREAD

**Issue by youyafeng** [jeecgboot/JimuReport#463]
##### 问题描述：
时间查询现在支持 时间和日期 能否增加一种年份类型  因为有些报表搜索条件是按照年搜索

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
下个版本支持
