### ISSUE TITLE
查询条件下拉框取值：在SQL语句中添加报表参数（时间范围）后，查询条件下拉框取值消失

### ISSUE THREAD

**Issue by stevenczy81** [jeecgboot/JimuReport#464]
##### 版本号：
1.3.78
##### 问题描述：
在SQL语句增加报表参数（时间范围）后，原先正常的下拉框取值就不能正常显示了
如果去掉SQL语句中where条件中的参数，即可正常显示。
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/73892470/129378124-0d8b55fa-6c5c-4c99-ae82-2e1ce0c547cb.png)

![image](https://user-images.githubusercontent.com/73892470/129378250-5c076b43-9405-4f77-8d92-4d672a5a111d.png)

![image](https://user-images.githubusercontent.com/73892470/129378890-abfca8e8-f8fd-4660-851e-190837f88ab5.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
参数有默认值吗

**Comment by stevenczy81** [comment]
> 参数有默认值吗
参数有默认值的，而且在预览里面也能看到数据的

**Comment by zhangdaiscott** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布

**Comment by stevenczy81** [comment]
请问 1.3.792 这个版本修复了这个问题了吗？

**Comment by zhangdaiscott** [comment]
修复了
