### ISSUE TITLE
升级到1.3.78  下拉单选查询问题

### ISSUE THREAD

**Issue by yueyunp** [jeecgboot/JimuReport#466]
##### 版本号：
1.3.78

##### 问题描述：
下拉单选框  输入关键字搜索 选中结果之后  下拉框里值丢失 

##### 重现步骤：
框里原有的数据
![image](https://user-images.githubusercontent.com/88695123/129498684-3cde5311-2707-41a7-ab6a-4655a7a1d24b.png)
1.输入关键字搜索一下
![image](https://user-images.githubusercontent.com/88695123/129498695-baf063c6-fb8a-4d5c-bc16-643d887b11d4.png)
2.选择搜索结果 之后清楚文本框内容 重新选择
![image](https://user-images.githubusercontent.com/88695123/129498725-69db911c-6608-4a1b-aa8a-fb2b7c822cb8.png)
3.结果下拉框的值只有我刚才搜索后选中的了
![image](https://user-images.githubusercontent.com/88695123/129498751-b5dc54d0-9ac1-499c-bdeb-02ab391da2cf.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
试试这个版本，配置jeecg私服

```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.79</version>
</dependency>
```
