### ISSUE TITLE
报表内图表联动报错

### ISSUE THREAD

**Issue by christxlx** [jeecgboot/JimuReport#467]
##### 版本号：
1.78

##### 问题描述：
按照文档设置了图表联动,试了几个版本,都是点击切换字段值的时候报错

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/78583127/129498860-1e17949b-eb6a-466f-b8b3-ae3c6ed23495.png)
![image](https://user-images.githubusercontent.com/78583127/129498891-0c9fbeea-a617-4849-93d0-b72e8a7a6603.png)

##### 重现步骤：
按照文档方式配置图表联动,报错,启动,报错400

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
线上做个例子

**Comment by christxlx** [comment]
什么意思?怎么做

**Comment by lvdandan16** [comment]
http://jimureport.com/
官网上登录，做个例子，把报表链接贴过来

**Comment by christxlx** [comment]
我这边是本地的数据库,没办法官网连接啊
