### ISSUE TITLE
整合后和mongodb注入出现冲突

### ISSUE THREAD

**Issue by christxlx** [jeecgboot/JimuReport#469]
##### 版本号：
1.3.78

##### 问题描述：
整合到springboot项目中,和mongodb项目出现冲突,我在启动类加了mongodb的扫描,但是还是扫不到类

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/78583127/129532077-d8a1b48b-824c-4874-bf31-f928b5c61811.png)
![image](https://user-images.githubusercontent.com/78583127/129532119-92577d03-a7da-432f-9fb5-46b5d1860605.png)

##### 重现步骤：
整合项目,启动,报错扫不到MongoDBtemplete,加入指定扫包路径还是扫不到

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
排除下这个类 org.jeecg.modules.jmreport.config.DisabledMongoStartConfig
