### ISSUE TITLE
积木离线部署到互联网不可达的服务器上启动慢，定位应该是这个百度统计影响了第一次访问删除掉 ，百度统计 tj.ftl；启动报错

### ISSUE THREAD

**Issue by ramber1** [jeecgboot/JimuReport#470]
##### 版本号：
1.3.78

##### 问题描述：
积木离线部署到互联网不可达的服务器上启动成功，第一次访问系统链接访问慢，定位应该是这个百度统计影响了第一次访问；删除掉 百度统计 tj.ftl；启动报错

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/37301245/129537220-72a9ab60-235e-4268-8f6f-e32994c58e93.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你是访问那个请求慢？我们测的断网也不慢

**Comment by ramber1** [comment]
我是新建大屏的时候比较慢，控制台显示访问百度统计需要10-20秒，这个代码能去掉吗？怎么去掉

**Comment by ramber1** [comment]
![image](https://user-images.githubusercontent.com/37301245/130379503-7b35f216-c881-4b7b-8107-ddae9c20c1fe.png)

**Comment by zhangdaiscott** [comment]
大屏没有离线版

**Comment by ramber1** [comment]
能去掉这个访问链接吗，怎么去掉？我现在先使用报表


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月23日(星期一) 上午10:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 积木离线部署到互联网不可达的服务器上启动慢，定位应该是这个百度统计影响了第一次访问删除掉 ，百度统计 tj.ftl；启动报错 (#470)





 
大屏没有离线版
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangdaiscott** [comment]
到底什么慢？

**Comment by ramber1** [comment]
> 什么慢？
我现在部署了一个离线版的，访问不了互联网，现在每次做报表的时候，他都会访问百度统计；能不能不访问百度统计

**Comment by ramber1** [comment]
> 什么慢？

我现在在centos服务器上部署了一个离线版的积木jar包，服务器访问不了互联网；现在每次用积木做报表的时候，他要访问百度统计；这个耗时间非常多，能不能把这个访问百度统计的去掉，怎么去掉？
![image](https://user-images.githubusercontent.com/37301245/130595028-7aa8f10a-5440-4c82-ba0d-4bf1359e3b5c.png)

**Comment by zhangdaiscott** [comment]
影响访问速度？我们测试的没问题
