### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by EdgarLi-Xun** [jeecgboot/JimuReport#471]
##### 版本号：
2.3.0

##### 问题描述：
登录失败问题，本身用的是shiro，集成积木后会导致登录失败

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/31910303/130169985-11963a4f-7d5f-4625-ab9e-6fea5a8bd0b7.png)

##### 重现步骤：
本身用的是shiro，集成积木后会导致登录失败

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
扫码路径加上你自己的类路径
