### ISSUE TITLE
controller冲突

### ISSUE THREAD

**Issue by KnightGeorge** [jeecgboot/JimuReport#472]
##### 版本号：
jeecg-boot:2.4.2
jimureport-spring-boot-starter:1.3.78

##### 问题描述：
maven引入包后项目无法正常运行

##### 错误日志&截图：
Failed to parse configuration class [com.xxxx.xxxx.XxxxApplication]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'jimuReportTestController' for bean class [org.jeecg.modules.jmreport.desreport.a.g] conflicts with existing, non-compatible bean definition of same name and class [org.jeecg.modules.jmreport.desreport.a.e]

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
1.3.791 这个版本试试
http://jimureport.com/doc/log

**Comment by KnightGeorge** [comment]
791这个版本还是报相同问题，请问有jeecg-boot项目嵌入积木报表的具体方法吗？

**Comment by zhangdaiscott** [comment]
你是不是老包没删?其他人为什么没问题

**Comment by KnightGeorge** [comment]
maven项目呀，我pom.xml改了，maven仓库看过jar包也是791；启动前maven clean过；项目重新编译过

**Comment by zhangdaiscott** [comment]
我意思你的项目是不是两个 jimureport  jar依赖

**Comment by KnightGeorge** [comment]
只有一个依赖，我去本地的maven仓库将之前的相关的包全都删了，然后重新拉了一遍

**Comment by zhangdaiscott** [comment]
你项目里有这个jimuReportTestController？

**Comment by KnightGeorge** [comment]
项目里没有，但是用的jeecgboot的jar包里有没有不知道

**Comment by KnightGeorge** [comment]
Annotation-specified bean name 'jimuReportTestController' for bean class [org.jeecg.modules.jmreport.desreport.a.g] conflicts with existing, non-compatible bean definition of same name and class [org.jeecg.modules.jmreport.desreport.a.e]现在这个错，我通过反编译进去jar包看过，没看出来有啥冲突
