### ISSUE TITLE
脚本中字段与结果不一致

### ISSUE THREAD

**Issue by sunshanjin** [jeecgboot/JimuReport#473]
##### 版本号：
1.3.792

##### 问题描述：
脚本中的字段与最后结果中的字段不一致

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/7366954/130379423-57fbf472-aba2-4753-b1e7-314d86c89cda.png)

##### 重现步骤：
select to_char(sysdate, 'yyyy')||'年'||to_char(sysdate, 'mm')||'月'||to_char(sysdate, 'dd')||'日' tab,
case when '${startYearMonth}' = '${endYearMonth}' then 
substr('${startYearMonth}', 1, 4) || '年' || substr('${startYearMonth}', 6, 2) || '月'
else
substr('${startYearMonth}', 1, 4) || '年' || substr('${startYearMonth}', 6, 2) || '月' || '~' || substr('${endYearMonth}', 1, 4) || '年' || substr('${endYearMonth}', 6, 2) || '月'
end
month from dual

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
参数怎么设置？
![image](https://user-images.githubusercontent.com/3162115/130385871-26a13c2d-554c-4b2c-a13a-b4affb177eca.png)

**Comment by sunshanjin** [comment]
> 参数怎么设置？
> ![image](https://user-images.githubusercontent.com/3162115/130385871-26a13c2d-554c-4b2c-a13a-b4affb177eca.png)

![image](https://user-images.githubusercontent.com/7366954/130532710-843ae434-c5b9-49c9-9559-7e92f6bc9857.png)

**Comment by zhangdaiscott** [comment]
你为什么不用表达式来组装时间，整这么复杂的sql就为了获取时间，不值当

**Comment by sunshanjin** [comment]
> 你为什么不用表达式来组装时间，整这么复杂的sql就为了获取时间，不值当

因为要按照查询条件组装这个时间

**Comment by 1298191366** [comment]
集成1.3.792测试没有问题，你看看你sql解析出来的字段是这样子的吗
![image](https://user-images.githubusercontent.com/30997828/131460194-755b4288-d04b-462e-9176-4342a79673c3.png)
数据预览：
![image](https://user-images.githubusercontent.com/30997828/131460247-af58bb9a-4b22-4428-aae8-de9ed8125609.png)

**Comment by zhangdaiscott** [comment]
升级到最新看看

**Comment by lvdandan16** [comment]
因长时间未回复，关闭此任务
