### ISSUE TITLE
引入积木和和项目mongodb出现冲突

### ISSUE THREAD

**Issue by christxlx** [jeecgboot/JimuReport#474]
##### 版本号：
1.3.78

##### 问题描述：
引入积木和和项目mongodb出现冲突,jar包冲突,导致本身无法使用了

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/78583127/130396469-61b5c99f-4178-498f-9ea6-a008fca6b84a.png)
![image](https://user-images.githubusercontent.com/78583127/130396478-144c976e-1007-432c-a87b-9435db9b1c75.png)
![image](https://user-images.githubusercontent.com/78583127/130396584-0f6828a6-702b-4423-90e3-78b8477a1fae.png)
![image](https://user-images.githubusercontent.com/78583127/130396553-5b217320-156d-45d0-b136-33b07983f899.png)

##### 重现步骤：
导入之后,一开始启动就冲突,然后排除了mongo配置类解决了,但是今天测试自定义表单出现了插入失败的问题

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.792</version>
</dependency>
```

http://jimureport.com/doc/log

**Comment by christxlx** [comment]
问题没有得到解决,还是同样的问题,我回退到不支持mongodb的积木测试了一下,是没问题的

**Comment by zhangdaiscott** [comment]
###  20. 引入积木报表和项目mongodb出现冲突
  https://github.com/jeecgboot/JimuReport/issues/469

**Comment by christxlx** [comment]
找到了解决办法,需要排除掉这三个jar包
![image](https://user-images.githubusercontent.com/78583127/130538797-579506bd-d67e-4c1b-aa32-e7a474cb3d97.png)
