### ISSUE TITLE
特殊字符，fastjson报错

### ISSUE THREAD

**Issue by fy7105** [jeecgboot/JimuReport#475]
##### 版本号：
1.3.78

##### 问题描述：
数据库值为 /\ 等时，fastjson报错

##### 错误日志&截图：
com.alibaba.fastjson.JSONException: syntax error, position at 23687, name text

##### 重现步骤：
数据库字段值为 \/ 等

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
什么值？

**Comment by fy7105** [comment]
遇到这两个/和\

**Comment by tygithub1** [comment]
经测试/没有问题，那就是\的问题，通常情况下\用于转义，如果文本里只有一个反斜杠，那其实没有意义，想要显示反斜杠就\\
