### ISSUE TITLE
报表参数：日期增加默认值后，预览报错，并且查询条件，下拉框不能选择

### ISSUE THREAD

**Issue by stevenczy81** [jeecgboot/JimuReport#476]
##### 版本号：
1.3.792

##### 问题描述：
报表参数中，查询条件：给开始日期、结束日期默认值：
开始日期：=concat(string.substring(dateStr('yyyy-MM-dd'),0, 8), '01')
结束日期：=dateStr('yyyy-MM-dd')

数据预览时会报错，报表查询是可以正常的，但是查询条件（下拉单选）不能选择；

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/73892470/130484786-dddafcaf-51bb-4cd0-8e72-d0168481b78a.png)

![image](https://user-images.githubusercontent.com/73892470/130485034-289f5541-122b-4b0c-88a2-3f7a112a7427.png)

![image](https://user-images.githubusercontent.com/73892470/130485188-d71c5957-292b-4df0-a051-e6933142479f.png)

**Comment by zhangdaiscott** [comment]
截图你的下拉配置

**Comment by stevenczy81** [comment]
请看下下拉配置：

![image](https://user-images.githubusercontent.com/73892470/130549841-474681ee-5c64-4588-a224-e29c7d1cac99.png)

**Comment by 1298191366** [comment]
我集成1.792测试没有问题，你看看你解析出来的字段是这个吗
![image](https://user-images.githubusercontent.com/30997828/131458959-83789b51-e3e3-4b65-9475-1bdfa975434d.png)
数据预览：
![image](https://user-images.githubusercontent.com/30997828/131459504-28a9ce9b-1b5b-4958-b41a-3d7c29d69b7f.png)

**Comment by 1298191366** [comment]
问题一：已修复，待新版本发布。问题2：参数不是字段，无法进行配置后就可以下拉单选
