### ISSUE TITLE
报表性能问题

### ISSUE THREAD

**Issue by jsonzoup** [jeecgboot/JimuReport#479]
##### 版本号：
1.3.78

##### 问题描述：
带有查询条件的报表会每个查询条件都执行一下整个SQL ,查询dict，
事实上，我并不需要从数据中抽取dict, 有的是模糊查询，有的是字典查询（配置了字典）
这导致这个报表初始化非常慢。特别是条件多的情况下。

##### 错误日志&截图：
![I4_FP2RNW5O(PW(84V%BNO0](https://user-images.githubusercontent.com/24908749/130573621-fa7702fb-33ec-4abf-9f5b-7f821de2f3ee.png)
![}6SK)J243V_ O ~U5PB$)Q9](https://user-images.githubusercontent.com/24908749/130573639-06a7fab2-760a-47f5-b985-b37e3aeadbe7.png)

我这个例子来说，会执行7,8次这个sql的查询。本来10秒就能出来，这就干到了70秒。
并不需要每个查询条件从数据集中提取一遍啊。非常耗性能。

##### 重现步骤：
无

**Comment by zhangdaiscott** [comment]
你这里面肯定存在，未配置字典的下拉

**Comment by jsonzoup** [comment]
我截图的那个sql ，redeem_name这个字段是模糊查询的字符，它不是下拉框为什么还会查询这个sql呢。

**Comment by zhangdaiscott** [comment]
经测试不存在

**Comment by jsonzoup** [comment]
是在我这个版本测试的么？

**Comment by zhangdaiscott** [comment]
http://jimureport.com/doc/log

**Comment by jsonzoup** [comment]
好的，感谢。

**Comment by jsonzoup** [comment]
![image](https://user-images.githubusercontent.com/24908749/130577569-5b2f0c40-4a52-4dc0-b54b-be96ee43fbe5.png)
scott, 是不是还没有推上去呢。

**Comment by jsonzoup** [comment]
![image](https://user-images.githubusercontent.com/24908749/130577664-667dd378-cb71-4e2d-a86a-e977b9231bcc.png)
Scott，是不是haimei还没有推上去呢。

**Comment by jsonzoup** [comment]
![image](https://user-images.githubusercontent.com/24908749/130577726-cdc36254-d321-48ca-bd5c-5dd1f44a9184.png)
是不是还没推上去呢。
