### ISSUE TITLE
API数据集接口访问异常

### ISSUE THREAD

**Issue by KnightGeorge** [jeecgboot/JimuReport#480]
##### 版本号：
jimureport-demo-1.3.jar

##### 问题描述：
API数据集解析接口404，但是访问的项目的后台接口的打印都走到了

##### 错误日志&截图：
![Dingtalk_20210824160145](https://user-images.githubusercontent.com/34829624/130580468-f606acea-94a3-4c2d-93ba-f6ea73811fd0.jpg)
![Dingtalk_20210824160544](https://user-images.githubusercontent.com/34829624/130580484-25b06ef9-1205-4065-94f5-74dca574ccb4.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
什么意思？

**Comment by KnightGeorge** [comment]
![Dingtalk_20210824161026](https://user-images.githubusercontent.com/34829624/130581166-5837a2b5-1bd2-4377-8583-807f2fbd6083.jpg)
这里点解析，但是积木的后台报404，我自己项目的后台都已经访问到了，也有日志打印，返回的数据格式如第二张图所示

**Comment by zhangdaiscott** [comment]
自己排查，肯定是接口协议不匹配 ，F12看接口提示信息

**Comment by KnightGeorge** [comment]
但为啥response里返回200
![Dingtalk_20210824170143](https://user-images.githubusercontent.com/34829624/130588871-8cbafc73-c646-4461-b87c-c7d31cc585b5.jpg)

**Comment by zhangdaiscott** [comment]
这是我们的接口返回好吗
