### ISSUE TITLE
【feat】是否支持动态显示隐藏列、排序功能

### ISSUE THREAD

**Issue by jsonzoup** [jeecgboot/JimuReport#481]
##### 版本号：
1.3.792

##### 问题描述：
是否支持动态显示隐藏列、排序功能

##### 错误日志&截图：
无

##### 重现步骤：
无

**Comment by zhangdaiscott** [comment]
不支持

**Comment by jsonzoup** [comment]
什么时候支持

**Comment by wr8515** [comment]
> v1.9.3 版本已支持。

是动态的吗，好像只支持了手动设置？

**Comment by jeecgos** [comment]
> > v1.9.3 版本已支持。
> 
> 是动态的吗，好像只支持了手动设置？

确实只支持手动，看错标题了。

**Comment by wr8515** [comment]
> > > v1.9.3 版本已支持。
> > 
> > 
> > 是动态的吗，好像只支持了手动设置？
> 
> 确实只支持手动，看错标题了。

后面有计划支持动态吗

**Comment by jeecgos** [comment]
你可以receiving下issue，后续支持了我们会告知。
