### ISSUE TITLE
【bug】

### ISSUE THREAD

**Issue by jsonzoup** [jeecgboot/JimuReport#487]
##### 版本号：
1.3.792

##### 问题描述：
导出报表报错

##### 错误日志&截图：
![TP@{8U8)KCM7YC@MC59%P3F](https://user-images.githubusercontent.com/24908749/130721196-aedde478-18ff-42e3-94f3-7b4a12be01cb.jpg)

**Comment by tygithub1** [comment]
哎，错误提示的非常明显了吧 numberformat异常，说明你把一个不是数字的东西设置成数字了，具体看你怎么设计的

**Comment by tygithub1** [comment]
未回复可关闭
