### ISSUE TITLE
单个图表是否支持查询条件

### ISSUE THREAD

**Issue by felixkxq** [jeecgboot/JimuReport#490]
##### 问题描述：
单个图表组件是否支持查询条件？具体如下图

##### 错误日志&截图：
<img width="346" alt="1629959570(1)" src="https://user-images.githubusercontent.com/20662358/130912772-845fcfb0-c728-4bdc-b3cd-48f2aefda1f0.png">
<img width="235" alt="1629959641(1)" src="https://user-images.githubusercontent.com/20662358/130912907-f153e045-5909-4375-a0a7-8d96076899ff.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
查询条件是统一显示在上方的，设计的时候每个图表的查询条件名称不同，就是支持每个图表组件的查询
详细可查看文档
http://report.jeecg.com/2373403

**Comment by felixkxq** [comment]
补充问题：
1、查询条件统一在上方，每个单独的图表不好区分用哪个查询条件。
2、这种交互方式目前大屏设计器是否支持？

**Comment by lvdandan16** [comment]
不支持
