### ISSUE TITLE
在线积木大屏普通表格滚动问题

### ISSUE THREAD

**Issue by suchan66** [jeecgboot/JimuReport#492]
##### 版本号：
1.3.8-beta
##### 问题描述：
在线积木大屏普通表格，是否可以支持小于10行数据的滚动呢？比如有5行数据，滚动显示1行，目前无法实现。
##### 测试用例：
1. 测试数据：
[
  {
    "type1": "张三",
    "type2": "1"
  },
  {
    "type1": "刘东",
    "type2": "2"
  },
  {
    "type1": "张三",
    "type2": "3"
  },
  {
    "type1": "刘东",
    "type2": "4"
  },
  {
    "type1": "张三",
    "type2": "5"
  }
]
2. 开启滚动，设置滚动行数为1行。
![image](https://user-images.githubusercontent.com/30565066/131059862-7ce9c62c-bb0e-4e1b-b88c-8619bbc878a3.png)
3. 结果：未出现滚动。

#### [之前提的issues也请关注下哦！](https://github.com/jeecgboot/JimuReport/issues/447)
https://github.com/jeecgboot/JimuReport/issues/447

**Comment by lvdandan16** [comment]
暂不支持
归集到 #138
