### ISSUE TITLE
在线大屏旋转饼图bug

### ISSUE THREAD

**Issue by suchan66** [jeecgboot/JimuReport#493]
##### 版本号：
1.3.8-beta

##### 问题描述：
旋转饼图数据来源选择静态数据时，会强制显示样例数据。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/30565066/131209795-313521f0-f31d-46b8-9993-c08c6100cb7a.png)

##### 重现步骤：
1. 创建旋转饼图；
2. 选择静态数据，并且只填一个数据。
如：
[
    {
        "name": "达成总件数：121",
        "value": 121
    }
]
3. 保存后预览，可看到显示的数据中，不止有自己填写的数据，还有样例数据。
4. 刷新设计页面，可看到设计页面也如预览页面一般，随后点击查看静态数据内容，发现被强制拼接了样例数据。
![image](https://user-images.githubusercontent.com/30565066/131209895-7c1c84fe-3937-487c-8114-2b93cefff8b4.png)
![image](https://user-images.githubusercontent.com/30565066/131209908-062f96cc-69a3-444b-8e65-fe351d3d2d98.png)

**Comment by lsqGitHub716** [comment]
已处理，下版本发布
