### ISSUE TITLE
数值类型，太长科学计数法

### ISSUE THREAD

**Issue by tsh0794** [jeecgboot/JimuReport#494]
##### 版本号：
1.3.7
##### 问题描述：
1、数值类型，超过8位数，报表界面显示正常，但是双击查看就是科学计数法。并且不会参与SUM求和

##### 错误日志&截图：
![LBNN5RXATK{}ERFI}F2EL0J](https://user-images.githubusercontent.com/89760691/131281132-c78e2351-fea1-4a93-a2ad-9258003fff83.jpg)
![R4FM{0O 63D6T$ U(~K28M8](https://user-images.githubusercontent.com/89760691/131281135-4c87c649-7960-4256-867b-f3ab82ab894f.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
已修复，更新最新版本
http://jimureport.com/doc/log

**Comment by tsh0794** [comment]
好的，非常感谢发自我的华为手机-------- 原始邮件 --------发件人： lvdandan16 ***@***.***>日期： 2021年9月6日周一 下午2:18收件人： jeecgboot/JimuReport ***@***.***>抄送： tsh0794 ***@***.***>, Author ***@***.***>主    题： Re: [jeecgboot/JimuReport] 数值类型，太长科学计数法 (#494)

已修复，更新最新版本

http://jimureport.com/doc/log
