### ISSUE TITLE
[BUG]1.3.793分组不显示

### ISSUE THREAD

**Issue by guanyugege** [jeecgboot/JimuReport#496]
##### 问题描述：
设置了分组，显示效果只显示了一个字段名称

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/39876211/131306368-356948ee-ae27-4927-806f-92b51ea0bbfd.png)
![image](https://user-images.githubusercontent.com/39876211/131306462-31b7ba3b-1028-4e50-9749-47fcae9bd7dd.png)
![image](https://user-images.githubusercontent.com/39876211/131306506-d757432c-0e71-40b7-8602-2bc57dd84c07.png)

##### 重现步骤：
随便设置一个分组就可以重现

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
可参照横向动态分组文档进行设计，横向动态分组需设置动态列
http://report.jeecg.com/2119055
