### ISSUE TITLE
数值类型太长，科学计数法，SUM时不统计问题

### ISSUE THREAD

**Issue by tsh0794** [jeecgboot/JimuReport#497]
##### 版本号：
1.3.78

##### 问题描述：
在做分组统计报表时，选择类型为“数值”类型，界面显示正常，但是双击查看时就是科学计数法，并且SUM时，此条数据不进行加算
##### 错误日志&截图：

![LBNN5RXATK{}ERFI}F2EL0J](https://user-images.githubusercontent.com/89760691/131319504-1d3fa270-909c-42c4-83fd-4a1df7813da7.jpg)
![R4FM{0O 63D6T$ U(~K28M8](https://user-images.githubusercontent.com/89760691/131319524-115fe23e-2d42-44d9-9496-3529a6534663.jpg)

##### 重现步骤：
1、界面显示
![image](https://user-images.githubusercontent.com/89760691/131319654-f0f420d1-de70-4eb2-a154-5a877cde8276.png)
2、双击查看
![image](https://user-images.githubusercontent.com/89760691/131319761-d9217258-496a-4384-ad2d-3ce2ff4ab98d.png)
3、SUM 统计
![image](https://user-images.githubusercontent.com/89760691/131319976-0afd72d1-1699-4c6d-adc9-d3387c7fdad9.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级最新版本

**Comment by tsh0794** [comment]
已经更新到1.379还是报错发自我的华为手机-------- 原始邮件 --------发件人： lvdandan16 ***@***.***>日期： 2021年9月3日周五 傍晚6:32收件人： jeecgboot/JimuReport ***@***.***>抄送： tsh0794 ***@***.***>, Author ***@***.***>主    题： Re: [jeecgboot/JimuReport] 数值类型太长，科学计数法，SUM时不统计问题 (#497)

升级最新版本

**Comment by lvdandan16** [comment]
今天刚发了一个版本 或者下周再更新最新的

**Comment by tsh0794** [comment]
好的，非常感谢发自我的华为手机-------- 原始邮件 --------发件人： lvdandan16 ***@***.***>日期： 2021年9月3日周五 傍晚6:59收件人： jeecgboot/JimuReport ***@***.***>抄送： tsh0794 ***@***.***>, Author ***@***.***>主    题： Re: [jeecgboot/JimuReport] 数值类型太长，科学计数法，SUM时不统计问题 (#497)

今天刚发了一个版本 或者下周再更新最新的

**Comment by tsh0794** [comment]
升级到1.3794还是一样的发自我的华为手机-------- 原始邮件 --------发件人： lvdandan16 ***@***.***>日期： 2021年9月3日周五 傍晚6:59收件人： jeecgboot/JimuReport ***@***.***>抄送： tsh0794 ***@***.***>, Author ***@***.***>主    题： Re: [jeecgboot/JimuReport] 数值类型太长，科学计数法，SUM时不统计问题 (#497)

今天刚发了一个版本 或者下周再更新最新的

**Comment by lvdandan16** [comment]
那你在线上做例子，把id贴过来

**Comment by zhangdaiscott** [comment]
升级到1.3795
