### ISSUE TITLE
不同数据源在同一行的数据不显示

### ISSUE THREAD

**Issue by aibing0803** [jeecgboot/JimuReport#498]
##### 错误日志&截图：
![不同数据源在同一行的引用](https://user-images.githubusercontent.com/37793007/131590691-22d08e6d-e396-4eb6-8a3d-0266416856bc.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
是这样，不支持

**Comment by zhangdaiscott** [comment]
非循环的，应该设置为非集合数据集

**Comment by aibing0803** [comment]
是的，按照此方法问题解决了
