### ISSUE TITLE
有扩展单元格情况下，单元格值的获取

### ISSUE THREAD

**Issue by aibing0803** [jeecgboot/JimuReport#499]
##### 问题描述：
报表有多部分组成，但上方报表有扩展单元格，下方使用某个单元格时，获取的数据是扩展后数据的单元格。
比如A1单元格是扩展单元格，有4条数据；
A4单元格是某个值，为“152”；
A7单元格公司等于A4，希望得到的是“152”，但实际数据为A1单元格的第4个元素；

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/37793007/131608805-c0d6e83a-2e0f-4de0-b8da-c0e4c158f46d.png)
预览结果：
![image](https://user-images.githubusercontent.com/37793007/131608879-1f53e6fd-2003-46f1-835d-026be324c95e.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
当第一列是多数据集合，预览展示时单元格位置坐标已改变，再使用A1就找不到了，定位不准确
