### ISSUE TITLE
单元格与字符串拼接错误

### ISSUE THREAD

**Issue by aibing0803** [jeecgboot/JimuReport#500]
##### 问题描述：
希望得到A4单元格与’年‘（字符串）拼接结果，使用公式concat(A4,'年')，出现错误

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/37793007/131610142-786e39ca-e470-417a-9900-41db2ce89599.png)

错误日志：
 Syntax error: insert ')' to complete statement at 7, lineNumber: 1, token : [type='variable',lexeme='A4',index=7], while parsing expression: ` CONCAT(A4:^^^ 
![image](https://user-images.githubusercontent.com/37793007/131610106-29423d93-d175-44ce-af95-28c8f037dfd4.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 yf

**Comment by lvdandan16** [comment]
暂不支持
归集到 #138
