### ISSUE TITLE
扩展单元格的拼接

### ISSUE THREAD

**Issue by aibing0803** [jeecgboot/JimuReport#501]
##### 问题描述：
希望实现扩展单元格的拼接，但找不到实现思路，请问能否实现
![image](https://user-images.githubusercontent.com/37793007/131611370-fc566d06-a30d-4f45-86e0-bad2d9393d55.png)
![image](https://user-images.githubusercontent.com/37793007/131611439-21f34648-566c-4f18-9032-ee88f50927e8.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
http://report.jeecg.com/2332213
