### ISSUE TITLE
1.3.793 查询栏下拉框最多只能显示10条数据

### ISSUE THREAD

**Issue by 13071652014** [jeecgboot/JimuReport#502]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/56342460/131634072-7b8ce668-5a4d-4675-8221-19f6b9e182d7.png)
![image](https://user-images.githubusercontent.com/56342460/131634308-fb961a0d-2086-438f-ad55-7e34ce039ce1.png)
![image](https://user-images.githubusercontent.com/56342460/131634437-c5a12be7-7f38-42e5-8f34-3a4183cc44ab.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 13071652014** [comment]
![image](https://user-images.githubusercontent.com/56342460/131635313-f6a5fea8-1243-440e-b66d-f90737b88635.png)
![image](https://user-images.githubusercontent.com/56342460/131635538-57a44f76-040e-4c82-8ff9-58b116d5415a.png)
![image](https://user-images.githubusercontent.com/56342460/131635835-cd86963e-23a0-4e7c-8d29-187b9621a9e9.png)

搜索到的内容也是这10条数据里的，接口返回只返回了10条数据，实际上我的SQL查询到的数据不止10条

**Comment by 1298191366** [comment]
集成1.3.793配置后搜索没有问题，你后台输出sql语句了吗，你看看sql语句是啥。如果想要配置下拉框显示条数，请参考[官方文档](http://report.jeecg.com/2302149) 配置select-show-total
原始查询数据
![image](https://user-images.githubusercontent.com/30997828/131644260-da7304eb-e30e-46fe-8df7-874758123f80.png)
输入第1后的查询数据
![image](https://user-images.githubusercontent.com/30997828/131644373-7ad84937-b3a6-4f40-a5e5-311021cad252.png)

**Comment by 13071652014** [comment]
![image](https://user-images.githubusercontent.com/56342460/131669214-c05358dd-581e-438e-9e38-7e82b7a82331.png)

![image](https://user-images.githubusercontent.com/56342460/131674241-2000f1de-ce49-4adf-bdfc-32175ca61e07.png)

![image](https://user-images.githubusercontent.com/56342460/131674370-be89e432-3d76-4988-9e72-6589c5ea8f70.png)

**Comment by lvdandan16** [comment]
未复现此问题
