### ISSUE TITLE
两个数据集，查询条件名称相同，后台报错

### ISSUE THREAD

**Issue by tsh0794** [jeecgboot/JimuReport#507]
##### 版本号：
1.3.793

##### 问题描述：
两个数据集，查询条件名称相同，后台报错。两个查询条件都year,描述年

##### 错误日志&截图：
![L4XAM(UK(N0}3 HIQIGZ6`3](https://user-images.githubusercontent.com/89760691/131792160-5d4ba0cc-a4d3-422f-8933-e54fe42beb80.jpg)

##### 重现步骤：
1、第一个数据集信息
![image](https://user-images.githubusercontent.com/89760691/131792255-0824ca7d-c9c3-4355-bb06-b567df6735f2.png)
2、第二个数据信息
![image](https://user-images.githubusercontent.com/89760691/131792400-9eebb581-6825-438e-be58-c88e8c44f66c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
请导出报表配置 及用到的数据集相关表结构和数据

**Comment by lvdandan16** [comment]
因长时间未回复，关闭此任务
