### ISSUE TITLE
驱动类不存在

### ISSUE THREAD

**Issue by christxlx** [jeecgboot/JimuReport#508]
##### 版本号：
1.3.8-beta

##### 问题描述：
配置sqlserver时候出新驱动类不存在,mysql可以

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/78583127/131802497-fb4ae5c2-18c0-484b-840d-24b56dd04b12.png)

##### 重现步骤：
配置sqlserver时候出新驱动类不存在

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Jethro-Cheng** [comment]
怎么解决的诶
