### ISSUE TITLE
背景图上传不成功

### ISSUE THREAD

**Issue by meepo8023** [jeecgboot/JimuReport#509]
##### 错误日志&截图：
对比一下存在库里的报表数据，上传图片和上传背景图都已经传成功了，使用的地址也一样，但是图片可以显示，背景图不行。是不是BUG啊

![1](https://user-images.githubusercontent.com/88531867/131818013-d6058176-9248-44e9-80b2-62b346605a45.png)
![2](https://user-images.githubusercontent.com/88531867/131818036-3010f6e9-b4f2-40d3-ad26-3d424d74bb1b.png)
![3](https://user-images.githubusercontent.com/88531867/131818047-fcad195b-e705-41ab-be4b-a0b408d7fda4.png)
![4](https://user-images.githubusercontent.com/88531867/131818487-c0c7be3f-5c38-419b-9028-b16cd8f0b716.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
这个问题我们没有复现，可能本地的问题？

**Comment by lvdandan16** [comment]
因长时间未回复，关闭此任务
