### ISSUE TITLE
下拉框和多选框不出数据

### ISSUE THREAD

**Issue by zhuhaitingfeng** [jeecgboot/JimuReport#510]
##### 版本号：
1.3.79

##### 问题描述：
下拉框和多选框不出数据，只能手动填入数据

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/38696855/131829376-644b9957-8332-47df-ae4a-62d7f6747c67.png)
![image](https://user-images.githubusercontent.com/38696855/131829383-cec0ed5d-e25d-4867-9ac1-9359c182d94c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhuhaitingfeng** [comment]
> ##### 版本号：
> 1.3.79
> 
> ##### 问题描述：
> 下拉框和多选框不出数据，只能手动填入数据
> 
> ##### 错误日志&截图：
> ![image](https://user-images.githubusercontent.com/38696855/131829376-644b9957-8332-47df-ae4a-62d7f6747c67.png)
> ![image](https://user-images.githubusercontent.com/38696855/131829383-cec0ed5d-e25d-4867-9ac1-9359c182d94c.png)
> 
> ##### 重现步骤：
> #### 友情提示（为了提高issue处理效率）：
> * 未按格式要求发帖，会被直接删掉;
> * 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
> * 针对不好重现的问题，请录制操作视频或详细的重现步骤；

![image](https://user-images.githubusercontent.com/38696855/131831395-76e97aec-b2bc-4661-a147-a9a6b87eceed.png)
bu不知道是不是这个404导致的

**Comment by lvdandan16** [comment]
导出报表配置 贴过来

**Comment by lvdandan16** [comment]
因长时间未回复，关闭此任务
