### ISSUE TITLE
积木报表怎么集成到vue的页面

### ISSUE THREAD

**Issue by chenyuxingkong** [jeecgboot/JimuReport#511]
##### 问题描述：
element-plus 的 dislog 中需要使用的积木报表的可视化图形设计，使用的是 iframe 来嵌套，还有没有更好的办法

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/46917670/131935934-c73c81df-8857-4001-89d6-5845127480ca.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
没有
