### ISSUE TITLE
预览超时

### ISSUE THREAD

**Issue by 497590008** [jeecgboot/JimuReport#512]
##### 问题描述：
点击预览时提示“api连接超时，请重试“。已经将超时时间设置成10分钟connect-timeout: 600000，且预览时未超过1分钟就报次错了

##### 错误日志&截图：

![Uploading image.png…]()
##### 重现步骤：
设计保存后，点击预览

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
因为你版本号未填写，我用的是1.3.795最新版

**Comment by 1298191366** [comment]
因为你版本号未填写，我用的是1.3.795最新版
测试1：
connect-timeout: 120000  //2分钟
测试结果：没有超过120000
![image](https://user-images.githubusercontent.com/30997828/132500082-3e6911d5-fb01-4717-a477-810ea81d712e.png)
测试2：
connect-timeout: 60000 //1分钟
测试结果：超过了1分钟
![image](https://user-images.githubusercontent.com/30997828/132500444-41dfc639-1028-40fa-86b8-a4bd406195c0.png)

可能存在问题，没有配置好
```
jeecg :
  jmreport:
    connect-timeout: 60000
```
可能问题2：
版本太老，旧版本不支持
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.3.795</version>
</dependency>
```
