### ISSUE TITLE
JimuReport使用自定义数据源

### ISSUE THREAD

**Issue by huang619915854** [jeecgboot/JimuReport#513]
##### 版本号：
        <dependency>
			<groupId>org.jeecgframework.jimureport</groupId>
			<artifactId>jimureport-spring-boot-starter</artifactId>
			<version>1.3.78</version>
		</dependency>

##### 问题描述：
在jeecg项目里面不能够动态切换数据源，始终使用的是第一条数据源

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/20438282/131991585-c8c41749-7584-48ea-bfa4-3fe8e1267796.png)

**Comment by zhangdaiscott** [comment]
详细说明用法

**Comment by lvdandan16** [comment]
因长时间未回复，关闭此任务
