### ISSUE TITLE
; nested exception is java.lang.NoClassDefFoundError: org/jeecgframework/minidao/aspect/EmptyInterceptor

### ISSUE THREAD

**Issue by y735832496** [jeecgboot/JimuReport#514]
##### 问题描述：
从1.3.78升级到了1.3.794居然连项目都跑不起来，giegie们能看看嘛，是不是我的问题

##### 错误日志&截图：

nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [org.jeecg.modules.jmreport.common.interceptor.MinidaoInterceptor] for bean with name 'minidaoInterceptor' defined in URL [jar:file:/C:/Users/aaa/.m2/repository/org/jeecgframework/jimureport/jimureport-spring-boot-starter/1.3.794/jimureport-spring-boot-starter-1.3.794.jar!/org/jeecg/modules/jmreport/common/interceptor/MinidaoInterceptor.class]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: org/jeecgframework/minidao/aspect/EmptyInterceptor

##### 重现步骤：
项目启动报错

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by y735832496** [comment]
1.3.78可以正常运行，但是1.3.794原地报错，不知道各位情况如何，jar包我从你们的私服下载到了

**Comment by zhangdaiscott** [comment]
重启idea

**Comment by y735832496** [comment]
不，是因为1.3.794里的POM文件没有关联依赖......

**Comment by y735832496** [comment]
1.3.78下载下来的POM ，minidao,druid......这些依赖都有 ，1.3.794里的pom什么都没。。。我后来手动加了

**Comment by lvdandan16** [comment]
下载最新版本
