### ISSUE TITLE
JIMUREPORT 是否可以集成在JEECG4.0版本里？

### ISSUE THREAD

**Issue by Alexxugm** [jeecgboot/JimuReport#515]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
目前不支持，你可以单独运行

**Comment by Alexxugm** [comment]
谢谢！希望能很快实现支持。谢



Best Regards,


Alex Xu







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月6日(星期一) 上午9:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] JIMUREPORT 是否可以集成在JEECG4.0版本里？ (#515)





 
目前不支持，你可以单独运行
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
