### ISSUE TITLE
api数据源预览时后台报错

### ISSUE THREAD

**Issue by yy-haung** [jeecgboot/JimuReport#517]
##### 版本号：
1.3.795

##### 问题描述：
api数据源解析通过 但在预览时后台报JSON错误

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/77088046/132173322-472059a4-07bb-4ffc-a819-f1c629fa8439.png)
![image](https://user-images.githubusercontent.com/77088046/132173344-7a9db027-838b-4933-92ad-6b1da5e4fac0.png)
![image](https://user-images.githubusercontent.com/77088046/132173421-9dfd7bd7-e53a-406c-99bd-ef35329d68e3.png)
![image](https://user-images.githubusercontent.com/77088046/132173539-392484b0-87fd-4fa1-a4c2-e006b9e70ba4.png)

##### 重现步骤：
1使用api解析数据源
2预览报表

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
经过测试你提供的接口数据预览没有问题，样式是有问题，待新版本发布就好了
![image](https://user-images.githubusercontent.com/30997828/133020947-a8f830cc-1548-4a68-800b-5b929fafe100.png)

**Comment by 1298191366** [comment]
预览页面出现[可能和返回数据有关，你看看是不是和这个issue返回的内容一致#532

**Comment by yy-haung** [comment]
{
    "data": [
        {
            "date": "2021-09-03",
            "dailySales": 8049.02,
            "dailyDowns": 0,
            "dailyRegistrations": 4,
            "appDailyReg": 5,
            "h5DailyReg": 4,
            "registeredConversionRate": 0,
            "dailyPurchase": 13,
            "purchaseConversionRate": "100.00%",
            "dailyActive": 5,
            "totalDowns": 0,
            "totalRegistrations": 376,
            "totalPurchase": 222,
            "totalSales": 32512.07
        }
    ]
}

这个是我返回的数据格式 你看一下有问题吗 是按照文档所写的一样返回的

**Comment by 1298191366** [comment]
看着是没有问题的，你有没有其他做什么操作，你这是部分数据还是全部数据。

**Comment by 1298191366** [comment]
看着是没有问题的，你有没有其他做什么操作，你这是部分数据还是全部数据。因为我用你的JSON数据是没有问题的

**Comment by 1298191366** [comment]
你导一下SQl脚本 http://report.jeecg.com/2376604，把用到的表数据也发一份，我这里复现不了这个bug

**Comment by yy-haung** [comment]
{
    "data": [
        {
            "sex": "男",
            "name": "haung",
            "age": 18
        }
    ]
}


![image](https://user-images.githubusercontent.com/77088046/133219330-7118a260-9fc3-4a72-b83e-f360cf9941da.png)
![image](https://user-images.githubusercontent.com/77088046/133219754-db9c8548-65bc-422d-bded-0f7c2b123d43.png)
![image](https://user-images.githubusercontent.com/77088046/133219755-45d90e90-6e40-4f81-9cb1-f82cc10907c3.png)

沒有连接数据库 就用手写的一个json格式 也是一样报错了

**Comment by yy-haung** [comment]
![Uploading image.png…]()

**Comment by 1298191366** [comment]
不行的话你还是把数据导出一份吧，我这测不出来，[文档]( http://report.jeecg.com/2376604)
![image](https://user-images.githubusercontent.com/30997828/133223094-cc272983-22b4-4e6c-9bba-af0fc8139175.png)
接口
![image](https://user-images.githubusercontent.com/30997828/133223461-a51ca575-4663-409a-8ce1-c4f35ad7e93e.png)

设计页面
![image](https://user-images.githubusercontent.com/30997828/133223347-dbde6456-750e-437d-8de8-78e9be7c9c05.png)
预览页面

**Comment by yy-haung** [comment]
[report-export-mysql.zip](https://github.com/jeecgboot/JimuReport/files/7160428/report-export-mysql.zip)\
导出的报表配置

**Comment by lvdandan16** [comment]
你的版本是1.3.8-bate
换成1.3.796试试   配置JEECG私服
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.796</version>
</dependency>

**Comment by yy-haung** [comment]
私服配置了 也换成了1.3.796 依然还是存在
![image](https://user-images.githubusercontent.com/77088046/133360746-c4687055-c96a-4cd0-9589-d03450bd7a0f.png)
![image](https://user-images.githubusercontent.com/77088046/133360752-a90a1e4f-a666-45ad-a2dd-62f4890d54fd.png)

我通过debug定位到错误是在这个地方报出的 希望能有些帮助

**Comment by lvdandan16** [comment]
那你直接再官网上做个例子，把链接复制过来，我们直接看例子

**Comment by yy-haung** [comment]
在官网上做的案例没有问题

**Comment by yy-haung** [comment]
https://bootapi.jeecg.com/jmreport/index/597947571314708480?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MzE2NzUyMDYsInVzZXJuYW1lIjoiMTUxNzk0MTYyMzYifQ.rtn72l0695TJ8xKpFnvKu8Pj98I305IeV85ceiptUg0

**Comment by 1298191366** [comment]
你看看是不是实现了这个类转换器ApiDataConvertAdapter,导致数据没有对应上

**Comment by yy-haung** [comment]
![image](https://user-images.githubusercontent.com/77088046/133363004-c849de24-a63b-461f-9e6e-44c2c2501bce.png)
并没有实现这个转换器

**Comment by tygithub1** [comment]
导出的配置中有两个数据集，请先确认两个数据集都返回了正常的数据格式。
经测试，无问题，可关闭
