### ISSUE TITLE
大屏执行SQL语句报错；在报表中执行OK；SqlServer2008

### ISSUE THREAD

**Issue by Q094w5bvUAM9IW6547RpyGq** [jeecgboot/JimuReport#520]
##### 错误日志&截图：
![QQ图片20210906173539](https://user-images.githubusercontent.com/41258994/132195561-01da3043-c666-44db-8b88-d4fa1a49158a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
提供一下大屏id

**Comment by lvdandan16** [comment]
因长时间未回复，关闭此任务
