### ISSUE TITLE
挂到linux服务器下，报表打开速度特别慢，打开后执行速度正常。

### ISSUE THREAD

**Issue by meepo8023** [jeecgboot/JimuReport#523]
##### 版本号：
1.3.78

##### 问题描述：
挂到linux服务器下，报表打开速度特别慢，打开后执行速度正常。

##### 重现步骤：
数据库查询速度也测试了正常，直接打开新建报表也要加载好久。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
访问的是那个地址? 是不是外网不通

**Comment by zhangdaiscott** [comment]
访问的是那个地址? 是不是外网不通

**Comment by meepo8023** [comment]
官网下载的jar报，本地linux服务器部署的报表服务器，打开报表慢，包括新建报表速度也很慢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月7日(星期二) 晚上8:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 挂到linux服务器下，报表打开速度特别慢，打开后执行速度正常。 (#523)





 
访问的是那个地址? 是不是外网不通
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by meepo8023** [comment]
的确是不通外网，报表工具还要访问外网么？有什么好办法能拒绝访问外网么？

**Comment by lvdandan16** [comment]
收录 z

**Comment by meepo8023** [comment]
访问的hm.baidu.com，这个问题都一周了怎么还没解决啊

**Comment by zhangdaiscott** [comment]
重新不了，测试无问题
