### ISSUE TITLE
HTML 打印表格显示不全

### ISSUE THREAD

**Issue by 110526** [jeecgboot/JimuReport#526]
##### 版本号：
1.3.795及以前版本

##### 问题描述：
使用API数据集,非集合数据集.预览正常, 如果数据集的某个字段为空, 则**HTML**打印页面表格展示不全, Canvas没问题.

##### 错误日志&截图：
设计页面:
![image](https://user-images.githubusercontent.com/22165590/132434021-05217838-6c51-494f-9a2e-e33f68c21156.png)
API数据源:
![image](https://user-images.githubusercontent.com/22165590/132433718-743225aa-dc7f-48fb-b113-d9748116f1ef.png)
API数据格式:
![image](https://user-images.githubusercontent.com/22165590/132433880-a93b4257-c71c-4f08-b0c6-e6b3acac857c.png)
预览页面:
![image](https://user-images.githubusercontent.com/22165590/132433798-97e5ca56-3056-428d-b975-a040f9a695e0.png)
**HTML**打印页面:
![image](https://user-images.githubusercontent.com/22165590/132433996-06b9c883-6d08-4f4b-a408-edfd2004865c.png)

##### 重现步骤：
前提是API数据源的属性为空,将空属性放到表格中.

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 110526** [comment]
需要json_str字段里面的内容进行排查吗?

**Comment by lvdandan16** [comment]
导出报表配置上传一下

**Comment by lvdandan16** [comment]
收录 ty

**Comment by 110526** [comment]
> 导出报表配置上传一下
在哪里导出报表配置? 最近刚接触, 不太了解.(我这个是打印, 好像不是报表)

**Comment by lvdandan16** [comment]
导出报表配置参考文档  http://report.jeecg.com/2376604

**Comment by 110526** [comment]
> 导出报表配置参考文档 http://report.jeecg.com/2376604
当前版本为1.3.8-beta, 后面试过1.3.795版本,也没有导出配置的右键菜单.
![image](https://user-images.githubusercontent.com/22165590/133017578-bf59747e-5fd8-478b-b4d2-6d2cb8a28a4a.png)
![image](https://user-images.githubusercontent.com/22165590/133017669-88b603f0-8685-45c3-83c6-0158eb522e87.png)
清空缓存后, 页面右键没有导出报表配置的菜单
![image](https://user-images.githubusercontent.com/22165590/133017722-df545251-35c4-4dda-936e-2f6afe2eda87.png)

**Comment by 110526** [comment]
> 导出报表配置参考文档  http://report.jeecg.com/2376604
报表配置:
[report-export-mysql.sql.txt](https://github.com/jeecgboot/JimuReport/files/7151166/report-export-mysql.sql.txt)
api代码:
[api.txt](https://github.com/jeecgboot/JimuReport/files/7151170/api.txt)

**Comment by tygithub1** [comment]
已修复，等最新版发布

**Comment by 110526** [comment]
> 已修复，等最新版发布

收到，  感谢！
