### ISSUE TITLE
1.3.795 导出excel,部分电脑无法打开

### ISSUE THREAD

**Issue by songyinhai2006** [jeecgboot/JimuReport#527]
##### 版本号：
1.3.795

##### 问题描述：
导出excel,部分电脑无法打开。提示“因为文件格式或文件扩展无效...”，之前的版本是可以的，

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/52561802/132438792-1b9fc589-b2bc-40d0-bf00-f3678b45103d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
提供一下数据，导出配置及表数据

**Comment by lvdandan16** [comment]
收录 ws

**Comment by songyinhai2006** [comment]
https://user-images.githubusercontent.com/52561802/132845906-676328cd-c6bb-489b-9ad7-b282039be572.mp4

我用的是默认的模板，采用的默认的导出配置，没有改相关配置。导出的文件
[多选条件查询报表 (1).xlsx](https://github.com/jeecgboot/JimuReport/files/7143423/1.xlsx)

**Comment by zhangdaiscott** [comment]
http://report.jeecg.com/2376604

**Comment by songyinhai2006** [comment]
[report-export-mysql.txt](https://github.com/jeecgboot/JimuReport/files/7147059/report-export-mysql.txt)

**Comment by 1298191366** [comment]
因为导出的excel的文件时xlsx，请查看你的软件能不能打开xlsx的，我看你是office，Excel2003是打不开xlsx格式的，我下载了你上传的excel可以打开

**Comment by 1298191366** [comment]
因为导出的excel的文件是xlsx结尾的，请查看你的软件能不能打开xlsx的结尾的文件，我看你是office，Excel2003及之前版本是打不开xlsx格式的，我下载了你上传的excel可以打开的
