### ISSUE TITLE
根据查询条件保存打印次数

### ISSUE THREAD

**Issue by libo5209** [jeecgboot/JimuReport#531]
##### 问题描述：打印模板打印之后，没有保存打印次数
1.根据打印模板的查询条件保存打印次数

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
