### ISSUE TITLE
【1.3795版本】分组小计使用【条件表达式（=(if)）】报错

### ISSUE THREAD

**Issue by qq514232492** [jeecgboot/JimuReport#534]
##### 版本号：
1.3795
##### 问题描述：
分组小计使用【条件表达式（=(if)）】报错

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/40046582/132649519-c5e852a3-6a79-4e6e-b9eb-7122c3649b23.png)
![image](https://user-images.githubusercontent.com/40046582/132649564-804c1e8a-947a-4993-b6b9-ddb12206198c.png)
[report-export-mysql.txt](https://github.com/jeecgboot/JimuReport/files/7134741/report-export-mysql.txt)

##### 重现步骤：
分组小计使用【条件表达式（=(if)）】报错

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
分组小计暂不支持表达式
归集到 #138
