### ISSUE TITLE
日期查询条件获取前10天，月份无法动态变化

### ISSUE THREAD

**Issue by xiebor** [jeecgboot/JimuReport#537]
##### 重现步骤：
![image](https://user-images.githubusercontent.com/37875140/132661625-4e9ac31a-5cc4-4e51-b6f8-4c8bf186e9a2.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
默认值使用 =concat(dateStr('yyyy-MM-dd',-14),' 00:00:00')|=dateStr('yyyy-MM-dd HH:mm:ss')
如果还不行，就升级到最新版本
