### ISSUE TITLE
整数数字转成大写金额为空白

### ISSUE THREAD

**Issue by libo5209** [jeecgboot/JimuReport#538]
##### 问题描述：
整数数字转大写金额为空白

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/40787669/132671752-3fc63f13-dce8-4e97-ab88-d977d5e0d985.png)
![image](https://user-images.githubusercontent.com/40787669/132671772-87ee6cad-8d79-4429-8d7e-5e6805aace89.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
