### ISSUE TITLE
本地直接运行的Demo似乎无法修改数据库以及新建报表

### ISSUE THREAD

**Issue by archerzhaopan** [jeecgboot/JimuReport#540]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/33536314/132834693-99356d99-ac5e-4e0e-9fff-d4dae479c746.png)
![image](https://user-images.githubusercontent.com/33536314/132834918-adb91512-a26e-4170-9ea5-566e641b5fb8.png)

**Comment by zhangdaiscott** [comment]
无法修改是什么意思

**Comment by EsuRt** [comment]
同样，打开报表设计器一起转圈圈。

**Comment by lvdandan16** [comment]
更新最新版本
