### ISSUE TITLE
多循环块不起作用

### ISSUE THREAD

**Issue by aibing0803** [jeecgboot/JimuReport#541]
##### 错误日志&截图：
报表设置：
![image](https://user-images.githubusercontent.com/37793007/132939135-1e1e8599-fdcd-448b-8024-b44474609120.png)
报表效果：
![image](https://user-images.githubusercontent.com/37793007/132939151-1a8bc726-bc85-4510-baf8-4941c18ae310.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
目前不支持多个使用

**Comment by lvdandan16** [comment]
已支持
可升级最新版本
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.5.0</version>
</dependency>
```
