### ISSUE TITLE
内存中org.jeecg.modules.jmreport.desreport.render.a.a.b一些信息解析过程消耗过大，导致应用假死

### ISSUE THREAD

**Issue by sifenglib** [jeecgboot/JimuReport#542]
##### 版本号：
api("org.jeecgframework.jimureport:jimureport-spring-boot-starter:1.3.64-beta")

##### 问题描述：
内存中org.jeecg.modules.jmreport.desreport.render.a.a.b一些信息解析过程消耗过大，导致应用假死

##### 错误日志&截图：

当时访问应用时发现访问不到，但未找到具体原因，后来dump下来后，内存中org.jeecg.modules.jmreport.desreport.render.a.a.b一些信息解析过程消耗过大，导致应用假死，还请帮忙分析一下问题，谢谢。

![f7f810528311b9564b4cfc5da590467](https://user-images.githubusercontent.com/61527672/132941242-f1358ccb-46f0-40f6-a16a-404c00ef135e.png)

![78d420ee29c7fed6a6fdfcf17b331d1](https://user-images.githubusercontent.com/61527672/132941248-ce7acac4-dcbf-4c43-9c26-fce69e4bc400.png)

![30c6181a0dfc93720300c260453bacf](https://user-images.githubusercontent.com/61527672/132941255-67028ec0-2823-4a80-91eb-c87465c28ea6.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
是操作的什么功能

**Comment by sifenglib** [comment]
没有操作任何功能，我们是我们原来的项目集成在了一起了，过了一天之后发现访问的时候卡住了，后来重启之后就好了，然后dump出来后发现是这个地方占了很大的内存

**Comment by lvdandan16** [comment]
现在还有这个问题吗

**Comment by sifenglib** [comment]
目前暂时还没出现过了，还需要继续观察

**Comment by lvdandan16** [comment]
好的，如果再出现再联系我们
