### ISSUE TITLE
报表参数填写默认值无效

### ISSUE THREAD

**Issue by shenbushou** [jeecgboot/JimuReport#543]
版本号：1.3.8-beta+
问题描述：报表参数填写默认值无效。将报表参数中的止期默认值设定为：=dateStr()
预览中报表并未按照以上的日期填入默认值。尝试了很多次，不管填什么都不会填入默认值或进行默认查询。
错误日志&截图：
![1631504605(1)](https://user-images.githubusercontent.com/64524981/133021025-068f64f9-955b-4a85-88fb-aac3945627a8.jpg)
重现步骤：
![1631504625](https://user-images.githubusercontent.com/64524981/133021034-f4f44284-9155-4196-a717-3dbe232a14a9.jpg)

**Comment by lvdandan16** [comment]
升级下版本，配置jeecg私服

<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.796</version>
</dependency>
