### ISSUE TITLE
表格列怎么取消最大限制，目前需要上百列得操作 在线等 急！！！

### ISSUE THREAD

**Issue by lis-ai** [jeecgboot/JimuReport#546]
##### 版本号：
1.3.795

##### 问题描述：
![8PE92ZZW_A7_A63G%K_9E9N](https://user-images.githubusercontent.com/52161263/133059856-15e02d7d-6def-41c7-98dd-0d7244ed7176.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参数配置中修改最大列
http://report.jeecg.com/2302149
