### ISSUE TITLE
图形报表开发，三级联动失效问题

### ISSUE THREAD

**Issue by tsh0794** [jeecgboot/JimuReport#547]
##### 版本号：
1.3.795

##### 问题描述：
1、开发图形报表，第一张图表年度，第二张图表月度，第三张图表仓库明细趋势；
2、联动关系，点击第一张图年度，刷新第二张图表月度数据，点击第二张图表具体月度，刷新第三张图仓库明细趋势；
3、第一次刷新数据正常，但是点击年度数据后，仓库明细趋势就失效。

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/89760691/133060334-2edf48a7-b663-4a56-9564-3284293ff9a1.png)
![image](https://user-images.githubusercontent.com/89760691/133060365-9b2ad6f3-bd16-4427-98e5-2dcc43b9fe89.png)
![image](https://user-images.githubusercontent.com/89760691/133060411-80633668-12dc-4f6b-ac7b-bb7addc4dabe.png)

##### 重现步骤：
1、第一次进入报表界面，按照正常顺序是正常
![image](https://user-images.githubusercontent.com/89760691/133060589-1d2520ae-3b5c-4149-86e0-15864c25c553.png)

2、当点击年度图表，比如说2020年。月度图表正常刷新，但是点击月度图表，切换月度时，第三张报表数据无法刷新

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
已经修复，等下个版本发布
