### ISSUE TITLE
导出pdf接口调用后台代码报错

### ISSUE THREAD

**Issue by Lctiv** [jeecgboot/JimuReport#549]
##### 版本号：
1.3.793

##### 问题描述：
String apiResult = restTemplate.postForObject(url, httpEntity, String.class); 报错：

No HttpMessageConverter for java.util.HashMap
##### 错误日志&截图：
![QQ图片20210915151138](https://user-images.githubusercontent.com/88873311/133387611-e8e3fd59-2ebb-4c61-aff0-11c0d14af7b4.png)
![QQ图片20210915151214](https://user-images.githubusercontent.com/88873311/133387663-178a4f61-7e6c-421c-aea7-41542b39b466.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by Lctiv** [comment]
> 收录 ws

收录ws是啥意思，我修改了调用接口代码，已经导出PDF，但是导出不完整，只有页面一部分内容。

**Comment by 1298191366** [comment]
那你的预览页面和设计页面是怎样设计的，导出的pdf是什么样的

**Comment by 1298191366** [comment]
导出报表配置并提供数据

**Comment by lvdandan16** [comment]
因长时间未回复，关闭此任务
