### ISSUE TITLE
pdf导出报Invalid font type

### ISSUE THREAD

**Issue by cxy1314kb** [jeecgboot/JimuReport#551]
##### 版本号：
1.3.795

##### 问题描述：
当导出不止一页的pdf时报错Invalid font type，在win上部署则不会。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/48480672/133414521-95d07022-8155-45eb-bb04-372770dcdc85.png)
![image](https://user-images.githubusercontent.com/48480672/133414547-95e6d213-4dc7-4a6d-9665-b42464bfbc69.png)

##### 重现步骤：
1.打包到服务器之后会提示需要导入jimureport-font依赖，
2.导入后重新部署
3.选择每页30条导出pdf正常
4.选择每页100条导出pdf报错如上图。
其他说明：在win上运行不会出现

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by trace-night** [comment]
@cxy1314kb 在linux系上安装SimSun字体库即可

**Comment by cxy1314kb** [comment]
感谢，已经解决，我直接把windows下Fonts目录的字体导入到linux：/usr/share/fonts
