### ISSUE TITLE
积木报表数据项纵向分组后，如果查询结果为空，则会报错误信息

### ISSUE THREAD

**Issue by yuan19981112** [jeecgboot/JimuReport#553]
##### 版本号：
 v1.3.795
##### 问题描述：
纵向分组后，如果查询结果为空，则会报错误信息。

##### 错误日志&截图：
![_RG496U9EE6$JXB$ OS~RQS](https://user-images.githubusercontent.com/53033662/133564242-8026dd6a-b774-4c80-8c8b-956c7fc7e5a4.jpg)

![8E3@X12K@LF`GYDDXXB)@ 2](https://user-images.githubusercontent.com/53033662/133564131-e3735716-df31-4d0f-93f2-798953689705.png)

##### 重现步骤：
SQL脚本：
SELECT wtlxmc,dlmc,xlmc,format(SUM(reportnum),0)  sbs,format(SUM(operatenum),0) sls ,
format(SUM(instnum),0) las,format(SUM(dispatchnum),0) pqs,format(SUM(disposenum),0) czs,
format(SUM(checknum),0) hcs,format(SUM(archivenum),0) jas,format(SUM(intimearchivenum),0) aqjas,
format(SUM(toarchivenum),0) wjas,format(SUM(needarchivenum),0) yjas,
case when archivenum=0 then '0.00%' else concat(cast(SUM(archivenum)/SUM(needarchivenum) as decimal(7,2))*100,'%') end as jal,
case when intimearchivenum=0 then '0.00%' else concat(cast(SUM(intimearchivenum)/SUM(needarchivenum) as decimal(7,2))*100,'%') end as aqjal
FROM snqajsj
WHERE wtlxmc= '部件' AND operatetime BETWEEN '${start_date}' AND '${end_date}' 
<#if isNotEmpty('${problem_level}')> 
    and wtjbmc LIKE  CONCAT('%','${problem_level}','%')
</#if>
<#if isNotEmpty('${problem_source}')> 
    and wtlymc LIKE  CONCAT('%','${problem_source}','%')
</#if>
GROUP BY  wtlxmc,dlmc,xlmc 
ORDER  BY   wtlxmc,dlmc,xlmc

对wtlx,dlmc,xlmc字段进行纵向分组后，选择未来的时间段查询，结果本应该是空数据，但是分组后会报错，不分组则不会报错

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级1.3.796，[需配置JEECG私服](http://report.jeecg.com/2195924)
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.796</version>
</dependency>
```
