### ISSUE TITLE
什么时候可以支持数据仓库数据源hive,presto等

### ISSUE THREAD

**Issue by a4561614** [jeecgboot/JimuReport#554]
##### 版本号：
什么时候可以支持数据仓库数据源hive,presto等

##### 问题描述：
什么时候可以支持数据仓库数据源hive,presto等

##### 错误日志&截图：

什么时候可以支持数据仓库数据源hive,presto等
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持
归集到 #138
