### ISSUE TITLE
api数据源请求第三方数据需要配置token， 请问如何配置第三方接口token以通过接口验证获取数据

### ISSUE THREAD

**Issue by lanshan12315** [jeecgboot/JimuReport#555]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
自定义token参考文档：http://report.jeecg.com/2222224

**Comment by linybexc** [comment]
token不应该出现在url中，在调用api接口的时候，直接传给第三方api就可以了。
