### ISSUE TITLE
springboot配置文件数据库支持

### ISSUE THREAD

**Issue by xiaozhiyl** [jeecgboot/JimuReport#556]
##### 版本号：
1.3.795

##### 问题描述：
换成达梦数据库以后不支持
启动以后访问网页会报错SQL语句错误

##### 错误日志&截图：
<img width="877" alt="捕获" src="https://user-images.githubusercontent.com/57853246/134449885-9145a83f-cc4b-4219-9414-48b0743bb9ae.PNG">

##### 重现步骤：
配置文件的驱动：
datasource:
    driver-class-name: dm.jdbc.driver.DmDriver

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
达梦里边积木表都建了吗

**Comment by xiaozhiyl** [comment]
建了 驱动也换成达梦了 就是说无效表什么的

**Comment by 1298191366** [comment]
你这样子建数据库，如果用户名是SYSDBA,那么你就在SYSDBA下新建表，这样就不用模式名.表名了
![image](https://user-images.githubusercontent.com/30997828/134837851-526b9999-b336-4f1a-9044-cf88a9027ec7.png)
