### ISSUE TITLE
报表配置查询时无法使用模糊查询模式

### ISSUE THREAD

**Issue by freewind1977** [jeecgboot/JimuReport#557]
##### 问题描述：报表配置查询时无法使用模糊查询模式
在官网的手册上看到时是可以支持报表查询条件，使用模糊方式的。但用jeecgboot集成的报表，在配l置时发现没有该选项，是该功能不开放，还是其他什么原因？？

![image](https://user-images.githubusercontent.com/26646785/134456683-1e45604e-e9bb-4e6a-922a-151380679628.png)

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/26646785/134456527-d1ab6d1a-701d-4aa8-ac7e-372a0ad028c5.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
更新最新版本
