### ISSUE TITLE
离线版能不能也整个设计管理员帐号，免得被人随便改报表

### ISSUE THREAD

**Issue by cxigit** [jeecgboot/JimuReport#558]
##### 版本号：
1.3.795

##### 问题描述：
没有个管理员帐号，总觉得会被人改报表

##### 错误日志&截图：
无

##### 重现步骤：
无

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持
归集到 #138

**Comment by hoperunChen** [comment]
jimureport-example中已经集成spring secruity，待新版本发布。
