### ISSUE TITLE
报表合并单元格，然后填充背景色之后内容显示不完整

### ISSUE THREAD

**Issue by sifenglib** [jeecgboot/JimuReport#559]
##### 版本号：
compile("org.jeecgframework.jimureport:jimureport-spring-boot-starter:1.3.795")

##### 问题描述：
报表合并单元格，然后填充背景色之后内容显示不完整

##### 错误日志&截图：
刚开始合并单元格的时候是正常的
![image](https://user-images.githubusercontent.com/61527672/134612147-ef6198b5-7046-4aa9-8157-2eadaa9a6d3e.png)
然后选择填充颜色之后就有一部分不显示出来了
![image](https://user-images.githubusercontent.com/61527672/134612199-6f2d1699-ccbe-4f5c-988f-741e6887ffa5.png)
预览报表的时候也是不展示的，导出表格没有问题

##### 重现步骤：
1、合并单元格
2、居中
3、填充颜色

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by sifenglib** [comment]
发现一个可以解决这个问题的方法，就是第一行和第一列空出来，就可以完全展示了

**Comment by lvdandan16** [comment]
导出报表配置 http://report.jeecg.com/2376604

**Comment by lvdandan16** [comment]
已修复，下个版本升级
