### ISSUE TITLE
如何去根据数据源名称去拿到数据源去执行sql语句？

### ISSUE THREAD

**Issue by YBenX** [jeecgboot/JimuReport#560]
##### 版本号：
1.3.79

##### 问题描述：
1.如何去根据数据源名称去拿到数据源去执行sql语句？
2.IJmReportDbSourceService 的getByDbKey获取一个不存在（？不理解这个DbKey是对应数据库哪个字段）的时候拿到一个空的对象也往dynamicDataSourceVoHashMap里面添加数据。
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/3353434/134631871-c2ada954-a698-4567-ab0c-7238456d7737.png)

![image](https://user-images.githubusercontent.com/3353434/134631290-00b1cef2-6e32-448c-adbc-e7ba624a41d9.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
具体是什么问题？

**Comment by YBenX** [comment]
> 具体是什么问题？

1.我需要根据指定的数据源去获取数据字典
2.上面那个是不是bug，为什么找不到dbkey的对象也加进去？
![image](https://user-images.githubusercontent.com/3353434/134754816-956edebf-d1fb-4183-ac78-82fbbdc509fb.png)

**Comment by YBenX** [comment]
![image](https://user-images.githubusercontent.com/3353434/134754918-020074a2-1319-4802-adf9-d638253df18a.png)

**Comment by lvdandan16** [comment]
问题1下个版本修复
问题2不支持

**Comment by lvdandan16** [comment]
问题1已修复，下个版本升级
问题2不支持
