### ISSUE TITLE
打印或导出分页报表时能否只导出某一页的内容

### ISSUE THREAD

**Issue by EsuRt** [jeecgboot/JimuReport#561]
##### 版本号：
1.3.79

##### 问题描述：
打印或导出分页报表时能否只导出某一页的内容（含固定行和数据），默认的打印或导出是针对所有数据。

##### 错误日志&截图：
![1](https://user-images.githubusercontent.com/15177069/134795814-c9d6e6d4-4fa0-458b-af4d-5a684efe8718.jpg)

##### 重现步骤：
点击“打印”或“导出”

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持固定行数打印和导出
归集到 #138
