### ISSUE TITLE
数值类型转百分比类型逻辑上存在问题

### ISSUE THREAD

**Issue by MartellRose** [jeecgboot/JimuReport#565]
##### 问题描述：
数值类型转百分比类型逻辑上存在问题，会对要转的值除以100，如果想要正常显示需要对该值乘以100
但是如果在单元格中进行*100操作会报错

具体问题见下图

##### 错误日志&截图：
![1](https://user-images.githubusercontent.com/38313534/135017266-60fd951f-9e48-4346-a871-cf4281ed92c0.png)
选择数值类型时预览页面显示如下：
![2](https://user-images.githubusercontent.com/38313534/135017268-b1c12c2c-35f3-4414-90f3-3f969d0d0e4a.png)
选择百分比类型时预览页面显示如下：
![3](https://user-images.githubusercontent.com/38313534/135017270-d9f6d601-b048-43b5-967c-beb15885ca75.png)
对单元格数值乘以100
![4](https://user-images.githubusercontent.com/38313534/135018356-16eb4f6d-12cc-483d-bb4a-02c8e000be18.png)
预览页面显示
![5](https://user-images.githubusercontent.com/38313534/135018360-b9091686-cdd7-4355-8d9f-6e67b20a5bfa.png)

**Comment by lvdandan16** [comment]
已修复，下个版本升级
