### ISSUE TITLE
分页查询第一页传递了报表参数但点击下一页时就没有传递了

### ISSUE THREAD

**Issue by hupanfeng** [jeecgboot/JimuReport#566]
##### 版本号：
1.3.795

##### 问题描述：
报表参数在点击下一页时不会传到后台了导致查询出现问题

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/4697988/135029669-da10d709-7643-498f-82d2-8c2c6c96292f.png)
![image](https://user-images.githubusercontent.com/4697988/135029679-424e701a-d54b-4c48-881e-a5149c39b8e8.png)
查看调用方法：
第一次进去传参截图:
![image](https://user-images.githubusercontent.com/4697988/135029683-94b77a4e-91ce-49e9-a629-212d4b7383ed.png)
点击下一页传参截图:
![image](https://user-images.githubusercontent.com/4697988/135029690-2ba10408-9268-450b-9ace-8de5c116477b.png)

**Comment by lvdandan16** [comment]
提供报表配置及数据我们看一下

**Comment by lvdandan16** [comment]
因长时间未回复，关闭此任务
