### ISSUE TITLE
报表数据包含特殊字符“\”时，在页面上显示为“◻”,excel导出时显示为“？”

### ISSUE THREAD

**Issue by hupanfeng** [jeecgboot/JimuReport#568]
##### 版本号：

1.3.795

##### 问题描述：

报表数据包含特殊字符“\”时，在页面上显示为“◻”,excel导出时显示为“？”

**Comment by lvdandan16** [comment]
不支持单独使用"\"，如要要显示可以使用转义字符"\\"
