### ISSUE TITLE
打印预览和打印内容重叠

### ISSUE THREAD

**Issue by Howike** [jeecgboot/JimuReport#574]
##### 版本号：

1.3.7
##### 问题描述：
打印预览和打印内容重叠

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/37234883/136487587-c496f97a-dc74-4387-9299-6bb81b760050.png)

##### 重现步骤：
文字内容格式
![image](https://user-images.githubusercontent.com/37234883/136487690-b8732c8b-af83-4864-b341-6c34975f5a53.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
是用的自动换行吗

**Comment by Howike** [comment]
是的

**Comment by Howike** [comment]
> 是用的自动换行吗

是的

**Comment by tygithub1** [comment]
官网示例测试：
设计页面：
![image](https://user-images.githubusercontent.com/27989856/136651817-7ec3d293-c501-457b-88b5-1d971e1e4a1d.png)

预览页面：
https://bootapi.jeecg.com/jmreport/view/606723388369059840

**Comment by No996ICU** [comment]
我用的1.5.6最新版本，有些还是会出现重叠，文字重复的情况，有时候不出现有时候出现
