### ISSUE TITLE
jeecgboot集成积木报表通过存储过程调用返回数据，但是查询栏无法动态传参

### ISSUE THREAD

**Issue by fchaoyu** [jeecgboot/JimuReport#575]
##### 版本号：
jeecgboot 2.4.6

##### 问题描述：
jeecgboot里面集成的积木报表设计了一个“电子支付统计”报表调用存储过程需要传入2个参数分别是开始日期和结束日期，jeecgboot已配置菜单，第一次打开报表可以调用存储过程获取到数据，使用的是默认值的日期，通过查询栏选择的日期后台就会出错，无法获取数据
jeecgboot菜单管理配置的地址：
{{ window._CONFIG['domianURL'] }}/jmreport/view/603561742384799744?token=${token}

#####  #错误日志&截图：
"积木报表设计"
<img src='http://drs.gd-jxm.com/1.jpg'>

"第一次打开报表"
<img src='http://drs.gd-jxm.com/2.jpg'>

"在报表页的查询栏选择日期"
<img src='http://drs.gd-jxm.com/3.jpg'>

"查询栏选择日期后台出错"
<img src='http://drs.gd-jxm.com/4.jpg'>

##### 重现步骤：
1.通过菜单栏打开“电子支付统计”
2.点击查询栏，选择日期
3.点击查询

**Comment by lvdandan16** [comment]
默认值中日期格式是20210930，查询条件中日期格式是2021-10-01 格式不统一能查出来数据吗
