### ISSUE TITLE
报表查询参数的SQL查询的数据字典能否带url的参数传递？

### ISSUE THREAD

**Issue by YBenX** [jeecgboot/JimuReport#580]
##### 问题描述：
报表查询参数的SQL查询的数据字典能否带url的参数传递？
目前是无法传递的

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/3353434/136788206-ad4a8a14-30f1-4598-84ee-56b6953bc7c3.png)
![}XIN9Q_J{QJHQ7(9H3`8)~Y](https://user-images.githubusercontent.com/3353434/136788214-d0c8b3de-d14c-4ba1-b048-f3707836686a.png)
![image](https://user-images.githubusercontent.com/3353434/136788437-27653d04-ab1b-4848-9107-d4095f881c7a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持
归集到 #138
