### ISSUE TITLE
使用Quickstart版本,图表默认乱码问题

### ISSUE THREAD

**Issue by cagy520** [jeecgboot/JimuReport#584]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/9970419/136913314-c5a4d395-d4b8-4a9e-871a-d63c950245a1.png)

##### 重现步骤：
1.阿里云MYSQL5.7
2.打开navicat链接数据库，记事本打开jimureport.mysql5.7.create.sql，全选复制SQL到navicat执行创建数据库
3.启动start.bat
4.打开网页界面，添加图表
5.看到默认乱码

**Comment by zhangdaiscott** [comment]
看看数据库里面的数据乱码吗

**Comment by cagy520** [comment]
经过测试，在linux下没有这个乱码问题。windows有乱码

**Comment by lvdandan16** [comment]
window环境下可以先修改start.bat文件，加上编码，修改为
java -Dfile.encoding=utf-8 -jar jimureport-example-1.4.jar
加上后前端使用无乱码问题，后台日志会出现中文乱码，我们修复问题后，会重新上传一个版本

**Comment by zhangdaiscott** [comment]
已经处理，下个版本发布
