### ISSUE TITLE
导出excel，数据为空时报错

### ISSUE THREAD

**Issue by wangweimain** [jeecgboot/jimureport#587]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/51606816/137055310-fa17ceb0-8459-4b49-a41d-c8dcad618843.png)
![image](https://user-images.githubusercontent.com/51606816/137055330-d56b3631-6c82-4910-ad88-6593ff3aff03.png)

##### 重现步骤：
查询报表后，点击导出excel时报错

[sql.zip](https://github.com/jeecgboot/JimuReport/files/7334236/sql.zip)
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws
