### ISSUE TITLE
导出excel错误，pageNo为2，pageSize为10000. 所以导出后一直没有数据

### ISSUE THREAD

**Issue by joel1889** [jeecgboot/JimuReport#588]
##### 版本号：
1.4.0-beta

##### 问题描述：
导出excel错误，pageNo为2，pageSize为10000. 所以导出后一直没有数据。
pdf等导出正常。

##### 错误日志&截图：
[jimu_dict.zip](https://github.com/jeecgboot/JimuReport/files/7342297/jimu_dict.zip)
![xxxxxxx](https://user-images.githubusercontent.com/64270082/137236735-44a9fe6f-10e6-4e67-a4c8-780f94c6a3bf.png)
![yyyyy](https://user-images.githubusercontent.com/64270082/137236795-ab233d9c-a4c7-437b-a5a2-6fecd33c9bf9.jpeg)

##### 重现步骤：
报表配置中的榜单流水可作为示例

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
请参考这个把sql导出，你把所有数据都导出了，报表是哪一个都不知道  http://report.jeecg.com/2376604

**Comment by 1298191366** [comment]
你第二个是不是分页，如果时分也的话我已经找到问题了

**Comment by 1298191366** [comment]
下面的表格

**Comment by joel1889** [comment]
是分页，但是导出excel不是导出全部吗，我看url的名字也是叫exportAll

**Comment by joel1889** [comment]
还有，上一个人提的导出excel，如果没有数据的会报empty String错误，我目前也遇到了

**Comment by 1298191366** [comment]
doule类型转换错误吗
