### ISSUE TITLE
分组显示错误

### ISSUE THREAD

**Issue by wangweimain** [jeecgboot/jimureport#591]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/51606816/137257657-1811895d-f142-456a-9301-96f363fb03a7.png)

##### 重现步骤：
[sql.zip](https://github.com/jeecgboot/JimuReport/files/7343307/sql.zip)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by wangweimain** [comment]
[sql.zip](https://github.com/jeecgboot/JimuReport/files/7343304/sql.zip)

**Comment by lvdandan16** [comment]
收录 yf
