### ISSUE TITLE
报表只到100行

### ISSUE THREAD

**Issue by abcdbbcd** [jeecgboot/JimuReport#596]
##### 版本号：
1.31

##### 问题描述：
导入一个260行的excel，实际只导入100行，如何操作可以扩展报表行数

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/30685218/137444425-610dd500-9577-4840-b6f1-12d44bffecd2.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/137666996-c869d390-8d83-4cb2-9c68-9de7baec2a7c.png)
设置列索引，参考文档：http://report.jeecg.com/2302149
