### ISSUE TITLE
预览界面时，点击查询后，滚动条会消失

### ISSUE THREAD

**Issue by snake-2** [jeecgboot/JimuReport#599]
版本号：jimu 1.3.795

问题描述：
当预览界面时，列表和图表在同一个界面，选择查询条件点击查询后，滚动条会消失，看不到下面的图表。

错误日志&截图：
![TA~ZD~IV{GC0X`}UCUIA0LX](https://user-images.githubusercontent.com/52567415/137858558-f2a0f944-1ecb-456e-a02a-828de74fa2eb.jpg)

重现步骤：

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by tygithub1** [comment]
已修改，等新版
在图表下方单元格录入一个空格也能解决这个问题
