### ISSUE TITLE
积木大屏，websocket方式有bug？

### ISSUE THREAD

**Issue by lsylovelmy** [jeecgboot/JimuReport#606]
版本号：2021.10.20 线上版本

问题描述：使用websocket的方式推送数据，但数据没显示，控制台确实是有日志打印出来。

错误日志&截图：

![1](https://user-images.githubusercontent.com/29912029/138191018-e59e8994-4f05-41cb-90ee-b314d27000eb.png)
![2](https://user-images.githubusercontent.com/29912029/138191026-d53434d1-8712-46f4-9239-6699e9d462e9.png)

重现步骤：如上图所示，数据是用websocket方式推送的。数据格式控制台也有了。格式应该没问题的。

**Comment by lvdandan16** [comment]
现在可以了吗

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题。
