### ISSUE TITLE
XA crash recovery finished. 后    jimureport容器仍然报无法链接数据库，jimureport-mysql容器故障不应影响 jimureport容器从外部数据库获取数据

### ISSUE THREAD

**Issue by shenguobin** [jeecgboot/JimuReport#618]
##### 版本号：
v1.3.795

##### 问题描述：
jimureport-mysql  容器经常出现
Starting XA crash recovery...

 XA crash recovery finished. 后    jimureport容器仍然报无法链接数据库
实际我的数据源是外部数据库
jimureport-mysql容器故障不应影响 jimureport容器从外部数据库获取数据

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/26364366/138688801-df914f94-a6d0-4f2a-80ff-efa0b30f0bc7.png)

##### 重现步骤：
可能是我服务器配置比较低，瞬时读写压力大导致jimureport-mysql  容器挂掉
![image](https://user-images.githubusercontent.com/26364366/138689156-08b356b3-313b-445f-9da8-931bef2b8982.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
因长时间未回复，关闭此问题
