### ISSUE TITLE
打印没有按照纸张进行分页打印

### ISSUE THREAD

**Issue by 497590008** [jeecgboot/JimuReport#619]
##### 版本号：
1.3.78

##### 问题描述：
设置了打印区域后，在打印区域内设置数据，并按照操作手册进行循环快设置（数据集是集合但不分页），但是打印出来的数据排版是乱的，没有按页打印

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/89560096/138986121-020c5bb8-16b4-4716-aaec-0a7f1e1bf8ea.png)
![image](https://user-images.githubusercontent.com/89560096/138986197-3ce34dbb-9c68-414c-a0f7-6d056b8c82ca.png)
![image](https://user-images.githubusercontent.com/89560096/138986218-b321d573-d389-408d-bf1a-ed3ae1d240e3.png)
![image](https://user-images.githubusercontent.com/89560096/138986226-8c7fc935-2f38-41aa-8057-5ca59ffed917.png)
![image](https://user-images.githubusercontent.com/89560096/138986266-dd78dc59-74dc-42f9-b574-e0263aca45d6.png)
![image](https://user-images.githubusercontent.com/89560096/138986286-4cbfe2c4-a092-436c-bb75-825494b2c60c.png)

##### 重现步骤：
1、设置纸张大小为70mm*35mm
2、设置数据集，API数据，数据集为集合，但不分页
3、选择打印纸张70mm*35mm，按照图纸在打印区域内设置数据，将打印区域内的所有列都设置成循环块，保存
4、选择三条数据进行打印，打印纸张选择70mm*35mm，打印结果排版混乱

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 497590008** [comment]
print-test报表，如图







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月29日(星期五) 下午4:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 打印没有按照纸张进行分页打印 (Issue #619)





 
在线上做个例子，我们看一下吧
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 497590008** [comment]
按照打印页面设计，我写的内容都在打印页面内，但是打印预览的时候，最后一行直接在另一页上了。打印模板和打印机选的都是A4纸

**Comment by lvdandan16** [comment]
导出模板配置吧

**Comment by lvdandan16** [comment]
因长时间未回复，关闭此问题
