### ISSUE TITLE
JavaBean数据集参数默认值问题

### ISSUE THREAD

**Issue by liuspring315** [jeecgboot/jimureport#620]
##### 版本号：
<version>1.4.0-beta</version>

##### 问题描述：
1、定义了三个JavaBean数据集，编码分别是xiangmuxinxi， chengyuanxinxi，jiaoshixinxi
![image](https://user-images.githubusercontent.com/11194611/139181365-dc8f2a9a-f308-4582-8315-6dbe46200873.png)

2、三个数据集用的bean是同一个，都是queryMongoService
3、三个数据集里的报表参数都有一个名为metadataClassificationId的参数，都设置了默认值，每个数据集里的默认值都不一样
![image](https://user-images.githubusercontent.com/11194611/139181686-cb4296bc-493b-4642-8ff7-3860f2250362.png)
第一个数据集，metadataClassificationId的默认值是9
![image](https://user-images.githubusercontent.com/11194611/139181748-039d101d-f943-41dc-b1d1-4e439f1552f6.png)
第二个数据集，metadataClassificationId的默认值是12
![image](https://user-images.githubusercontent.com/11194611/139181809-5ee820e0-1773-4c9b-8376-5f0ccefb2249.png)
第三个数据集，metadataClassificationId的默认值是11

4、createData方法被调用了三次，
调用的链接是http://localhost:9206/jmreport/view/613524953029607424?token=d3ebfb14-15c4-4ad7-a630-e1bb434e1f4d&competitionId=19&periodId=1&activityId=40&userId=0eeba257-e584-5cfe-8fcb-e76d8326df7d
并没有传metadataClassificationId参数，想使用每个数据集里配置的默认值，问题是接收到的metadataClassificationId的值都是最后一个数据集里设置的默认值11
![image](https://user-images.githubusercontent.com/11194611/139182168-c86c31f4-253f-4611-a6f7-577d662bed1d.png)

##### 错误日志&截图：
见问题描述

##### 重现步骤：
见问题描述

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by sdmq** [comment]
问题：  createData(Map<String, Object> map)  map参数： 包括浏览器地址栏 和 查询条件   
实际上并没有 浏览器地址栏所以获取不到报表ID
