### ISSUE TITLE
在线大屏设计器玉钰图数据显示问题

### ISSUE THREAD

**Issue by suchan66** [jeecgboot/JimuReport#622]
##### 版本号：
1.4.0

##### 问题描述：
在线大屏设计器中，柱状图里的玉钰图，如何显示数值和图例？通用处理可如何配置？

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/30565066/139195462-5f22379f-4525-403a-85c2-434913b1ccf4.png)

无显示数值和图例的操作栏
![image](https://user-images.githubusercontent.com/30565066/139195593-3a915aaf-90bb-4931-8a0c-e99160f4c3ec.png)

通用处理中，如下配置无效：
opt=>{
  opt.series[0].data.label.show = true;
  opt.series[0].data.label.position = 'inner';
  opt.series[0].data.label.textStyle.color = '#FFFFFF';
  opt.series[0].data.label.formatter='{b} : {c} ({d}%)';
  opt.series[0].data.labelLine.normal.show=false;
  return opt
}
![image](https://user-images.githubusercontent.com/30565066/139195632-7f4af33c-5f0c-4053-a694-33fb1f02943c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
玉钰图不支持图例配置
通用处理参考文档：http://report.jeecg.com/2264870
