### ISSUE TITLE
如何拓展报表设计页 fx支持的函数

### ISSUE THREAD

**Issue by Sinvirance** [jeecgboot/JimuReport#625]
##### 版本号：

1.4.0
##### 问题描述：
你好，我在报表设计时从 excel 迁移到积木报表时遇到了一些问题，项目需要用到 excel 的工程函数，积木报表目前的并不支持这样的函数？
1. 请问在接下来的版本开发有计划增加这些函数吗？
2. 或者是否有办法进行拓展吗，如果有我应该修改或者是如何创建拓展类来实现这些函数接口？

**Comment by lvdandan16** [comment]
暂不支持
归集到 #138
