### ISSUE TITLE
1.4版本导出PDF时，表格的边框不显示

### ISSUE THREAD

**Issue by hugosiyawei** [jeecgboot/JimuReport#628]
##### 版本号：
1.4.0
##### 问题描述：
导出PDF时，表格边框不显示，导出excel时，可以显示

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/93515298/139644554-b885b471-ecbe-4c11-a663-d1a78bc1a00c.png)

![image](https://user-images.githubusercontent.com/93515298/139644663-770f9664-55d6-4871-8271-da0fe69de779.png)

**Comment by lvdandan16** [comment]
升级1.4.1
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.4.1</version>
</dependency>
