### ISSUE TITLE
api数据源怎么传post

### ISSUE THREAD

**Issue by SEJJA3** [jeecgboot/JimuReport#630]
##### 问题描述：
![image](https://user-images.githubusercontent.com/62530244/139654723-a76c566a-0c45-4ec4-9510-227b7fdf0f5f.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考文档：http://report.jeecg.com/2332212

**Comment by ywm12345** [comment]
那就是不能在body里面传递参数是不

**Comment by tygithub1** [comment]
post请求参数都在body里
