### ISSUE TITLE
JavaBean数据集参数默认值问题-请认真了解反应的问题，不要敷衍了事

### ISSUE THREAD

**Issue by liuspring315** [jeecgboot/JimuReport#631]
https://github.com/jeecgboot/JimuReport/issues/620

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/140247909-1b6936e3-606c-45a0-b70d-f7e3e04fc613.png)
![image](https://user-images.githubusercontent.com/54099258/140248082-1cfc363c-d404-455a-ba5a-1f4b07fce3c1.png)

默认不选择查询模式，那就是输入框，输入框也是一种控件；
查询总纲和技巧说明中都有说明

**Comment by liuspring315** [comment]
太气人了，我说用到控件了吗，我说用到输入框了吗

“参数生效优先级：查询条件值>浏览器地址栏url拼接值>默认值”

我没用到查询条件值
我没用到浏览器地址栏url拼接值

只用到了默认值

一张报表里，调用三次同一个javabean数据集，参数默认值不一样，接收到的是一样的

**Comment by zhangdaiscott** [comment]
你仔细看我们的回复

**Comment by liuspring315** [comment]
你让我仔细看你们的回复
我让你们仔细看我提的问题

我问的是一张报表里，写了多个数据集，数据集配的同一个javabean，既然是同一个javabean，参数名必然一样

如果是用查询条件值或浏览器地址栏url拼接值，那javabean每次接收到的参数值是一样的，这个可以理解

但
我没用到查询条件值
我没用到浏览器地址栏url拼接值

我是在数据集的参数里配的默认值
每个数据集的参数默认值不一样
但javabean接收到的参数值总是最后一个数据集里配置的默认参数值

这难道不是bug？
难道你们就不肯复现一下？

老跟我强调查询区域，查询字段，控件干啥，我没用到查询区域，查询字段，控件
