### ISSUE TITLE
带Url图片打印时出错

### ISSUE THREAD

**Issue by Derryxiao** [jeecgboot/JimuReport#632]
##### 版本号：
v1.3.795 | 20210906
##### 问题描述：
表格里有图片时进行打印..图片还没显示完成..就被打印定格了(预览中正常)

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/7510741/139811374-21bc0d40-0af6-4d2a-8178-d4a997adfd80.png)
![image](https://user-images.githubusercontent.com/7510741/139811417-38f3fe5a-d48b-4498-bd16-085e6090c21c.png)

##### 重现步骤：
1.使用带图片的循环体
2.点击打印

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
先升级最新版本试一下

**Comment by onepiecewyz** [comment]
请教一下，url图片是怎么导入的~~官网文档没看到
