### ISSUE TITLE
导出pdf功能，长文本不换行

### ISSUE THREAD

**Issue by lch245298** [jeecgboot/JimuReport#633]
##### 版本号：
1.4.0-beta

##### 问题描述：
导出pdf功能，长文本不换行，已经设置了换行。把行拉高也不行。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/62693683/140000485-a7b88418-2868-4851-940e-b19a33b96a90.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持
归集到 #138
