### ISSUE TITLE
在线大屏设计器，所有类型的柱状图、折线图是否可以支持滚动

### ISSUE THREAD

**Issue by suchan66** [jeecgboot/JimuReport#639]
##### 版本号：
1.4.0

##### 问题描述：
在线大屏设计器，所有类型的柱状图、折线图是否可以支持滚动？类似排名表和表格的那种滚动形式。

##### 错误日志&截图：
上面提到的图表在设计器中的位置如下所示：
柱状图：
![image](https://user-images.githubusercontent.com/30565066/140281414-d28c31b7-06fd-4964-94e9-88abf7c5c5d7.png)
折线图：
![image](https://user-images.githubusercontent.com/30565066/140281464-4aafc458-5035-4b65-b06e-b88d98924bc2.png)

排名表：
![image](https://user-images.githubusercontent.com/30565066/140281516-bf123800-1d23-466c-8793-8e36cfab93fb.png)
普通表格：
![image](https://user-images.githubusercontent.com/30565066/140281646-bbc7ecd2-0dea-4820-8b21-376c82f07c9e.png)
![image](https://user-images.githubusercontent.com/30565066/140281709-a78fbabe-48db-4370-a335-96874b62479a.png)

##### 建议：
希望所有类型的柱状图、折线图可以支持滚动。
1. 滚动形式与排名表类似。
2. 可设置一次最多显示的柱体个数，超出这个数量后，就会滚动。
3. 可设置滚动的间隔时间。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
