### ISSUE TITLE
【SQL解析】出来的字段可以按字段名排序吗？

### ISSUE THREAD

**Issue by neo0820** [jeecgboot/JimuReport#640]
##### 版本号：
1.4.0
##### 问题描述：
查询过程出来的字段比较多，有2百多个，但是按照顺序来的。【SQL解析】出来的字段没有按字段名排序来，2百多个要手工一个个调整非常不方便。

##### 错误日志&截图：
![图片](https://user-images.githubusercontent.com/39484553/140299311-4fad8176-dab3-4ff1-96c9-ad76536be9ca.png)

实际通过【SQL解析】后，字段排序就乱了。有办法优化吗？
![图片](https://user-images.githubusercontent.com/39484553/140299373-86927525-e23f-47e1-8cd0-6df4a7313ea7.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
已修改--下个版本发布
