### ISSUE TITLE
数值类型，如果是null会导出出错

### ISSUE THREAD

**Issue by tyhg001** [jeecgboot/JimuReport#641]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/19584941/140447285-8b44dead-a741-45d7-97e3-348f83d21a15.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
你的数据是什么样子的，我测着没有问题，请出报表配置并提供数据：http://report.jeecg.com/2376604
![image](https://user-images.githubusercontent.com/30997828/140675345-b6b91416-3c6a-402c-86bb-e5003169a315.png)
![image](https://user-images.githubusercontent.com/30997828/140675385-e116562c-4f75-48cd-ba8a-a470fde4e898.png)
