### ISSUE TITLE
预览时报表不会根据默认参数进行查询,手动点选日期后就能正常查询了.

### ISSUE THREAD

**Issue by shenbushou** [jeecgboot/JimuReport#642]
版本号：
1.3.8-测试版+

问题描述：
预览时报表不会根据默认参数进行查询,手动点选日期后就能正常查询了.

错误日志&截图：
点开预览时的截图和
![0ZAOPQV~P(UH8_Q2Z3QIGH9](https://user-images.githubusercontent.com/64524981/140474301-f1b8a00a-2f72-4b4c-a0e6-ba773ab3d9c9.png)
             手动点选日期后截图如下
![3TGFP@CPA($ASYNU}W)GU V](https://user-images.githubusercontent.com/64524981/140474337-fc45523c-c234-406d-8fe6-35251a2911a5.png)

重现步骤：
报表参数的配置如图所示
![image](https://user-images.githubusercontent.com/64524981/140474429-20329d82-571e-412c-99df-054c897b801c.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级最新版本试一下

**Comment by shenbushou** [comment]
已經升級至最新，未能解決

**Comment by lvdandan16** [comment]
那你导出报表配置和数据，我们测试一下
http://report.jeecg.com/2376604

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
经测试,默认值配置固定值，没有问题，
你的问题是：dataStr 返回的是带时分秒格式的时间，这能查询到数据吗？请仔细阅读dataStr 使用文档  http://report.jeecg.com/2384072
