### ISSUE TITLE
API数据集查询数据报错

### ISSUE THREAD

**Issue by zhaoshuyun96** [jeecgboot/JimuReport#643]
##### 问题描述：
API数据集，报表参数作为查询条件时，如果不配置默认值，预览页面，后台出空指针异常。

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/93768393/140495865-5e65c450-5600-43d6-a37e-98a3edf70420.png)

**Comment by tygithub1** [comment]
提供详细设计说明

**Comment by zhaoshuyun96** [comment]
> 提供详细设计说明

![image](https://user-images.githubusercontent.com/93768393/140676303-ad086e59-d9e0-4b49-94de-dcd64d984a3c.png)

**Comment by tygithub1** [comment]
测试无误！
