### ISSUE TITLE
纵向分组预览显示不正常

### ISSUE THREAD

**Issue by ls85232589** [jeecgboot/JimuReport#644]
##### 问题描述：
纵向分组预览显示问题（1.3.64-beta版本可以）

##### 错误日志&截图：
![74_4@K5FFNDCK1EAP(QJF I](https://user-images.githubusercontent.com/77136293/140680659-6d401832-3593-4b31-8772-1c4de300aaef.png)
![Q2S %6ZW` FUL%@D$H7~ {5](https://user-images.githubusercontent.com/77136293/140680672-0cba970c-0592-483f-b1d7-6288618de0b5.png)

##### 重现步骤：
[report-export-mysql (2).zip](https://github.com/jeecgboot/JimuReport/files/7494137/report-export-mysql.2.zip)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤

**Comment by lvdandan16** [comment]
api 地址访问不通，看报表设计没有问题，估计是数据的问题，最好能看一下数据

**Comment by ls85232589** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月8日(星期一) 中午11:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 纵向分组预览显示不正常 (Issue #644)





 
api 地址访问不通，看报表设计没有问题，估计是数据的问题，最好能看一下数据
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ls85232589** [comment]
> api 地址访问不通，看报表设计没有问题，估计是数据的问题，最好能看一下数据

是不是数据太多了，但是1.3.64-beta版本显示是没有问题的

**Comment by lvdandan16** [comment]
数据多倒是没关系，1.3.64往上版本，分组这块我们改了很多，看一下数据是不是完整
文档：http://report.jeecg.com/2119057
![image](https://user-images.githubusercontent.com/54099258/140691066-c276f584-6573-42c9-ac39-5f692dfa612b.png)

**Comment by ls85232589** [comment]
您看下我给您发的数据格式是完整的吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月8日(星期一) 中午1:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 纵向分组预览显示不正常 (Issue #644)





 
数据多倒是没关系，1.3.64往上版本，分组这块我们改了很多，看一下数据是不是完整
 文档：http://report.jeecg.com/2119057
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/140693877-818ea6d4-a998-4030-83d2-2bedf9f483d2.png)

您的数据我看不了，api不通，预览超时了

**Comment by ls85232589** [comment]
我发了份附件zip格式，解压后文档里是json格式的数据，您那没办法复现一下吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月8日(星期一) 下午2:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 纵向分组预览显示不正常 (Issue #644)





 

 
您的数据我看不了，api不通，预览超时了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lvdandan16** [comment]
收录 ty

**Comment by lvdandan16** [comment]
升级到1.4.1即可解决   无需后台排序

<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.4.1</version>
</dependency>
