### ISSUE TITLE
导出pdf问题:导出pdf能否与打印预览效果相同？

### ISSUE THREAD

**Issue by leiorixsoft** [jeecgboot/JimuReport#645]
##### 问题描述：
１:预览时有网格线，导出pdf文件后没有网格线；
2：套打设置了背景图，预览时没有背景图，导出pdf时有背景图；导出pdf时能否根据"是否套打"这个参数，显示背景图；
3：打印预览时printAll=true有效果，预览全部数据,导出pdf时printAll=true无效果，显示的是分页数据;
导出pdf图像按钮无以上问题

**Comment by lvdandan16** [comment]
截图说明一下

**Comment by leiorixsoft** [comment]
我在github上提交Issue #645时，无法上传图片，现将图片以邮件的形式发给你们。


图一：这是预览效果，是有网络线的

图二：这是点击：“导出pdf”按钮后下载pdf打印后的效果



图三：这是套打预览效果，背景图不显示（正常）



图四：这是点击：“导出pdf”按钮后下载pdf打印后的效果，背景图又显示了（不正常）




图五：这是预览时数据条数：每页显示30条，有25页之多。




图六：这是点击：“打印html”按钮后的效果，数量正常有27页之多。





图七：这是在图五界面，点击：“导出pdf”按钮后下载pdf打印后的效果，只显示了图五中第一页30条的数据，显示只有2页。也就是说：导出pdf导出的不是所有数据，而是第一页，printAll=true无效。

----- Original Message -----

**Comment by zhangdaiscott** [comment]
图片没出来

**Comment by leiorixsoft** [comment]
我在github上提交Issue #645时，无法上传图片，现将图片以邮件的形式发给你们。


图一：这是预览效果，是有网络线的

图二：这是点击：“导出pdf”按钮后下载pdf打印后的效果
 
 
图三：这是套打预览效果，背景图不显示（正常）



图四：这是点击：“导出pdf”按钮后下载pdf打印后的效果，背景图又显示了（不正常）




图五：这是预览时数据条数：每页显示30条，有25页之多。




图六：这是点击：“打印html”按钮后的效果，数量正常有27页之多。





图七：这是在图五界面，点击：“导出pdf”按钮后下载pdf打印后的效果，只显示了图五中第一页30条的数据，显示只有2页。也就是说：导出pdf导出的不是所有数据，而是第一页，printAll=true无效。







在 2021-11-10 12:08:22，"JEECG" ***@***.***> 写道：

图片没出来

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lvdandan16** [comment]
还是没有图片

**Comment by leiorixsoft** [comment]
我在github上提交Issue #645时，无法上传图片，现将图片以邮件的形式发给你们。如果邮件无法显示图片，请查阅附件．


图一：这是预览效果，是有网络线的

图二：这是点击：“导出pdf”按钮后下载pdf打印后的效果
 
 
图三：这是套打预览效果，背景图不显示（正常）



图四：这是点击：“导出pdf”按钮后下载pdf打印后的效果，背景图又显示了（不正常）




图五：这是预览时数据条数：每页显示30条，有25页之多。




图六：这是点击：“打印html”按钮后的效果，数量正常有27页之多。





图七：这是在图五界面，点击：“导出pdf”按钮后下载pdf打印后的效果，只显示了图五中第一页30条的数据，显示只有2页。也就是说：导出pdf导出的不是所有数据，而是第一页，printAll=true无效。







在 2021-11-10 12:08:22，"JEECG" ***@***.***> 写道：

图片没出来

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
