### ISSUE TITLE
使用报表钻取条件用法对饼图设置钻取功能，条件不起作用

### ISSUE THREAD

**Issue by yangjunzhou861012** [jeecgboot/JimuReport#646]
##### 版本号：
1.4.0-beta

##### 问题描述：
http://report.jeecg.com/2427505 按此文档上，对一个饼图进行钻取，但是只能钻取到第一个链接的图表，第二个链接一直不起作用，不管条件怎么设置，都只能钻取第一个连接的图表

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/18575974/140701561-344d6718-cb2b-4c92-99cc-dad85ce95aa9.png)

##### 重现步骤：
![image](https://user-images.githubusercontent.com/18575974/140700598-80768914-3f99-44f4-a25c-97c83f20936b.png)
然后对此饼图进行配置两个钻取连接（ps:该饼图是使用sql查询方式，tp是分类属性）
![image](https://user-images.githubusercontent.com/18575974/140700807-34e65e0a-93e6-4ee8-bdf9-162ecd3ab73d.png)
这是第一个钻取配置
![image](https://user-images.githubusercontent.com/18575974/140701018-0e450e9b-7716-41c0-ac01-ab765d028ab4.png)
这是第二个钻取配置
配置完成后的如下
![image](https://user-images.githubusercontent.com/18575974/140701097-4326ba61-8bbb-4b7a-8ffa-74f56b4f0082.png)
但是只有第一个教师信息查询能钻取，学生信息查询一直不起作用，无论条件怎么设置，都只会调整到第一个钻取配置上

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级到最新版本1.4.1试试
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.4.0</version>
</dependency>
```

**Comment by 1298191366** [comment]
如果是图表钻取的情况下条件参数中须填写固定值，type(系列属性),name(分类属性),value(值属性)

**Comment by yangjunzhou861012** [comment]
> 的情况下条件参数中须填写固定值

我上面是写了固定值的，是不是格式写的的不对？

> 升级到最新版本1.4.1试试
> 
> ```
> <dependency>
>     <groupId>org.jeecgframework.jimureport</groupId>
>     <artifactId>jimureport-spring-boot-starter</artifactId>
>     <version>1.4.1</version>
> </dependency>
> ```
升级之后问题还在，是我参数格式写的不对吗？


> 如果是图表钻取的情况下条件参数中须填写固定值，type(系列属性),name(分类属性),value(值属性)

**Comment by yangjunzhou861012** [comment]
> 升级到最新版本1.4.1试试
> 
> ```
> <dependency>
>     <groupId>org.jeecgframework.jimureport</groupId>
>     <artifactId>jimureport-spring-boot-starter</artifactId>
>     <version>1.4.1</version>
> </dependency>
> ```

升级之后，问题还是存在，是我参数写的格式不对吗？

**Comment by yangjunzhou861012** [comment]
> 如果是图表钻取的情况下条件参数中须填写固定值，type(系列属性),name(分类属性),value(值属性)

上面是写了固定条件的，但是一直没起作用，都是一个连接，是我参数格式不对？
