### ISSUE TITLE
谷歌浏览器中无法打开预览界面，console报错

### ISSUE THREAD

**Issue by lch245298** [jeecgboot/JimuReport#647]
##### 版本号：
1.4.0

##### 问题描述：
谷歌浏览器中无法打开预览界面，console报错
谷歌浏览器版本问题么？xp比较老的系统了
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/62693683/140854835-a6cf4bb5-1bab-4779-a3fb-a9e838c638aa.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
xp系统？xp系统我们也没试过
您先试一下其他系统可不可以

**Comment by zhangdaiscott** [comment]
谷歌浏览器版本号？

**Comment by lch245298** [comment]
是xp系统，版本49，挺老
----- 原始邮件 -----
发件人：JEECG ***@***.***>
收件人：jeecgboot/JimuReport ***@***.***>
抄送人：lch245298 ***@***.***>,  Author ***@***.***>
主题：Re:_[jeecgboot/JimuReport]_谷歌浏览器中无法打开预览界面，console报错_(Issue_#647)
日期：2021年11月10日 12点03分



谷歌浏览器版本号？



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangdaiscott** [comment]
升级浏览器吧
