### ISSUE TITLE
报表设计器最大列只能支持到AX列

### ISSUE THREAD

**Issue by 513337197** [jeecgboot/JimuReport#648]
##### 版本号：
1.4.1

##### 问题描述：
报表设计器最大列只能支持到AX列

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/19811173/140879151-963ce8ea-875b-4790-a154-ac3363b3f213.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/140906567-840a60ab-420d-4f13-886f-eae0152a2d70.png)

参考文档 直接改列数量：http://report.jeecg.com/2302149
