### ISSUE TITLE
怎么将查询参数动态显示在表格上

### ISSUE THREAD

**Issue by yzmking** [jeecgboot/JimuReport#651]
##### 版本号：

1.4.0
##### 问题描述：
请问，怎么将查询参数动态显示在表格上

##### 错误日志&截图：
![1636508656(1)](https://user-images.githubusercontent.com/44563730/141034391-d49ec74c-0fa3-43e4-88aa-12dfdd02517e.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
文档上有写

**Comment by yzmking** [comment]
请问可以发一下对应文档的具体地址吗，没有找到




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月10日(星期三) 上午9:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 怎么将查询参数动态显示在表格上 (Issue #651)





 
文档上有写
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
