### ISSUE TITLE
添加json数据集，下拉框不显示

### ISSUE THREAD

**Issue by yzmking** [jeecgboot/JimuReport#652]
##### 版本号：

1.4.0
##### 问题描述：
添加json数据集，下拉框不显示

##### 错误日志&截图：
![1636511555(1)](https://user-images.githubusercontent.com/44563730/141039385-53821ba7-82e3-43ca-b337-e325fb0a8928.jpg)
![1636511572(1)](https://user-images.githubusercontent.com/44563730/141039391-900126fb-65a8-4a08-84c7-101cba7ab0be.jpg)

##### 重现

步骤：

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
此数据源的查询逻辑应该没做

**Comment by yzmking** [comment]
主要是想用来做下拉框的选择项

**Comment by zhangdaiscott** [comment]
此功能意义不大，咱不考虑做
