### ISSUE TITLE
Docker方式部署报错

### ISSUE THREAD

**Issue by liukaips** [jeecgboot/JimuReport#653]
##### 版本号：
V1.4.0

##### 问题描述：
Docker方式部署报错

##### 错误日志&截图：
mvn clean package 时报
![image](https://user-images.githubusercontent.com/24819958/141046925-81eec7ac-937e-4fb0-a431-50444cc7612a.png)
docker-compose up -d 报
![image](https://user-images.githubusercontent.com/24819958/141046960-6f47d221-4e59-40bb-9c8e-4ae2c4ddce97.png)

##### 重现步骤：
执行mvn clean package
执行 docker-compose up -d

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
依赖没下载成功？

**Comment by learningpro** [comment]
不知道官方用的maven版本是多少，类似的问题在sf上搜，说是要用3.8以下的版本，但是maven现在官方已经没有3.8以下的版本可用了，希望jeecg官方可以升级到3.9.5版本的maven
