### ISSUE TITLE
1.38升级1.40后,导出excel功能失效

### ISSUE THREAD

**Issue by shenbushou** [jeecgboot/JimuReport#654]
##### 版本号：
1.40

##### 问题描述：
1.38升级1.40后,导出excel功能失效

##### 错误日志&截图：

![184fd74b28363ed87b899e84807f3d6](https://user-images.githubusercontent.com/64524981/141223483-50b4a257-7d0c-4af3-a27b-620a40280b18.png)
![3fb4d116d6a4bf02d64eb3994b625dc](https://user-images.githubusercontent.com/64524981/141223496-f11e40f3-9ed3-471d-bfc6-3b0e552dd42e.png)

![c4e2bfe03b8e3ccb53d9db64a13ca37](https://user-images.githubusercontent.com/64524981/141223505-368b271e-9bc2-4a9d-a43b-951c0ceeddef.png)
##### 重现步骤：
将1.38升级到1.40

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级1.4.1试试，如果还不行，就导出报表配置及数据
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.4.0</version>
</dependency>
```
