### ISSUE TITLE
如果默认查询时间内的数据不足两页,手动点选其他含有多页数据的日期,分页功能无法使用

### ISSUE THREAD

**Issue by shenbushou** [jeecgboot/JimuReport#655]
##### 版本号：
1.40

##### 问题描述：
使用报表参数做了默认查询时间,如果默认查询时间内的数据不足两页,手动点选其他含有多页数据的日期,分页功能无法使用,1.38中遇到这个问题,管理要求我升级.升级为1.4后仍未解决

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/64524981/141224664-276cebbb-f48e-44a8-b361-3b07d634da5b.png)

##### 重现步骤：
默认查询时间内的数据不足两页,手动点选其他含有多页数据的日期后,分页功能无法使用

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
报表配置及数据导出贴上来，我们看一下

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
经测试，该问题已修复，1.4未发布，等下个版本

**Comment by shenbushou** [comment]
ty
