### ISSUE TITLE
横向动态分组计算乘法、减法、除法失效，只有加法能用，使用过compute()方法，V 1.4.0 依然不起作用！！！

### ISSUE THREAD

**Issue by yxxcrtd** [jeecgboot/JimuReport#657]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级到1.4.1
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.4.1</version>
</dependency>
