### ISSUE TITLE
积木报表配置报表钻取单元格传值与表格传值问题

### ISSUE THREAD

**Issue by huangqingbo1005** [jeecgboot/JimuReport#658]
##### 版本号：
1.4.0

##### 问题描述：
  1.报表钻取，不支持传递某一固定单元格的值
  2.从后端取的表格数据，配置了跳转列，无法按期望传其他列的值

##### 错误日志&截图：

> 
![1636699998](https://user-images.githubusercontent.com/94162231/141423884-fa0d3842-1014-4b1f-81dc-a4e9440909d3.png)

> 

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，下个版本发布
