### ISSUE TITLE
积木报表查询的数据和导出excel的数据总条数是一样的，但是数据内容有差距

### ISSUE THREAD

**Issue by Ethan-stack-arch** [jeecgboot/JimuReport#659]
##### 版本号：
1.4.0

##### 问题描述：
积木报表查询的数据和导出excel的数据总条数是一样的，但是数据内容有差距

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/78842627/141602573-274e9a66-2d11-4411-b1ce-1a10f89ec4c3.png)
![image](https://user-images.githubusercontent.com/78842627/141602597-0aa8e468-62ad-412d-93d9-afff304e36d2.png)
![image](https://user-images.githubusercontent.com/78842627/141602624-e5e699d1-2aeb-4780-9e5f-fc249069ea0c.png)

##### 重现步骤：
根据条件筛选然后查询数据之后，选择导出excel，会出现重复数据

**Comment by zhangdaiscott** [comment]
啥意思

**Comment by Ethan-stack-arch** [comment]
就是筛选条件没变，然后两次导出，导出的结果不相同

**Comment by zhangdaiscott** [comment]
重现步骤

**Comment by lvdandan16** [comment]
因长时间未回复，暂关闭此问题
