### ISSUE TITLE
导出数据量大时出错

### ISSUE THREAD

**Issue by tyhg001** [jeecgboot/JimuReport#660]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/19584941/141602743-e36a7b1c-5d19-4c95-9f3c-467ba6181457.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
截图看你的报表，详细描述下你的报表数据量

**Comment by tyhg001** [comment]
`
{
	"loopBlockList": [],
	"area": {
		"sri": 5,
		"sci": 9,
		"eri": 5,
		"eci": 9,
		"width": 66,
		"height": 25
	},
	"excel_config_id": "613957952625770496",
	"printConfig": {
		"paper": "A3",
		"width": 297,
		"height": 420,
		"definition": 2,
		"isBackend": false,
		"marginX": 10,
		"marginY": 10,
		"layout": "landscape"
	},
	"zonedEditionList": [],
	"rows": {
		"0": {
			"cells": {
				"0": {
					"text": "${param.mouth}",
					"style": 17,
					"merge": [
						0,
						7
					],
					"height": 48
				},
				"1": {},
				"2": {},
				"3": {},
				"4": {},
				"5": {},
				"6": {},
				"7": {},
				"8": {
					"merge": [
						0,
						11
					],
					"height": 48,
					"text": "月项目明细",
					"style": 13
				}
			},
			"height": 48
		},
		"1": {
			"cells": {
				"0": {
					"text": "单位：万元",
					"style": 11
				},
				"5": {
					"text": ""
				},
				"17": {
					"text": "统计日期:",
					"style": 18
				},
				"18": {
					"text": "=now()",
					"style": 20,
					"merge": [
						0,
						1
					],
					"height": 25
				}
			}
		},
		"2": {
			"cells": {
				"0": {
					"text": "项目信息",
					"merge": [
						0,
						3
					],
					"height": 38,
					"style": 14
				},
				"4": {
					"text": "分配",
					"merge": [
						0,
						3
					],
					"height": 38,
					"style": 14
				},
				"8": {
					"text": "开票",
					"merge": [
						0,
						2
					],
					"height": 38,
					"style": 14
				},
				"11": {
					"text": "开票收款",
					"style": 14,
					"merge": [
						0,
						2
					],
					"height": 38
				},
				"14": {
					"text": "预收款",
					"merge": [
						0,
						2
					],
					"height": 38,
					"style": 24
				},
				"16": {
					"style": 15,
					"text": " "
				},
				"17": {
					"text": "应收账款",
					"merge": [
						0,
						2
					],
					"height": 38,
					"style": 14
				},
				"20": {},
				"21": {},
				"22": {},
				"23": {},
				"24": {},
				"25": {},
				"26": {},
				"27": {},
				"28": {},
				"29": {},
				"30": {},
				"31": {},
				"32": {},
				"33": {},
				"34": {},
				"35": {},
				"36": {},
				"37": {},
				"38": {},
				"39": {},
				"40": {},
				"41": {},
				"42": {},
				"43": {},
				"44": {}
			},
			"height": 38
		},
		"3": {
			"cells": {
				"0": {
					"text": "项目编码",
					"style": 14,
					"zonedEdition": 0
				},
				"1": {
					"text": "项目名称",
					"style": 14,
					"zonedEdition": 0
				},
				"2": {
					"text": "是否在手",
					"style": 16,
					"zonedEdition": 0
				},
				"3": {
					"text": "项目负责人",
					"style": 14,
					"zonedEdition": 0
				},
				"4": {
					"text": "合同总价",
					"style": 14,
					"zonedEdition": 0
				},
				"5": {
					"text": "本月已分配",
					"style": 16,
					"zonedEdition": 0
				},
				"6": {
					"text": "本年已分配",
					"style": 16,
					"zonedEdition": 0
				},
				"7": {
					"text": "历年累计分配",
					"style": 16,
					"zonedEdition": 0
				},
				"8": {
					"text": "本月开票",
					"style": 14,
					"zonedEdition": 0
				},
				"9": {
					"text": "本年开票",
					"style": 14,
					"zonedEdition": 0
				},
				"10": {
					"text": "历年累计开票",
					"style": 16,
					"zonedEdition": 0
				},
				"11": {
					"text": "本月收款",
					"style": 14,
					"zonedEdition": 0
				},
				"12": {
					"text": "本年收款",
					"style": 14,
					"zonedEdition": 0
				},
				"13": {
					"text": "历年累计收款",
					"style": 16,
					"zonedEdition": 0
				},
				"14": {
					"text": "本月预收",
					"style": 14,
					"zonedEdition": 0
				},
				"15": {
					"text": "本年预收",
					"style": 14
				},
				"16": {
					"text": "历年累计预收",
					"style": 16,
					"zonedEdition": 0
				},
				"17": {
					"text": "开票未收款",
					"style": 16,
					"zonedEdition": 0
				},
				"18": {
					"text": "未开票未收款",
					"style": 16,
					"zonedEdition": 0
				},
				"19": {
					"text": "总应收",
					"style": 14,
					"zonedEdition": 0
				},
				"20": {
					"zonedEdition": 0
				},
				"21": {
					"zonedEdition": 0
				},
				"22": {
					"zonedEdition": 0
				},
				"23": {
					"zonedEdition": 0
				},
				"24": {
					"zonedEdition": 0
				},
				"25": {
					"zonedEdition": 0
				},
				"26": {
					"zonedEdition": 0
				},
				"27": {
					"zonedEdition": 0
				},
				"28": {
					"zonedEdition": 0
				},
				"29": {
					"zonedEdition": 0
				},
				"30": {
					"zonedEdition": 0
				},
				"31": {
					"zonedEdition": 0
				},
				"32": {
					"zonedEdition": 0
				},
				"33": {
					"zonedEdition": 0
				},
				"34": {
					"zonedEdition": 0
				},
				"35": {
					"zonedEdition": 0
				},
				"36": {
					"zonedEdition": 0
				},
				"37": {
					"zonedEdition": 0
				},
				"38": {
					"zonedEdition": 0
				},
				"39": {
					"zonedEdition": 0
				},
				"40": {
					"zonedEdition": 0
				},
				"41": {
					"zonedEdition": 0
				},
				"42": {
					"zonedEdition": 0
				},
				"43": {},
				"44": {}
			},
			"height": 59
		},
		"4": {
			"cells": {
				"0": {
					"text": "#{proj.projid}",
					"style": 4
				},
				"1": {
					"text": "#{proj.projname}",
					"style": 5,
					"linkIds": "614261335387602944",
					"rendered": "",
					"config": "",
					"display": "link"
				},
				"2": {
					"text": "#{proj.izhand}",
					"style": 4
				},
				"3": {
					"text": "#{proj.manager}",
					"style": 4
				},
				"4": {
					"text": "#{proj.premoney}",
					"style": 23,
					"decimalPlaces": "2"
				},
				"5": {
					"text": "#{proj.assignthismouth}",
					"style": 23,
					"decimalPlaces": "2"
				},
				"6": {
					"text": "#{proj.assignthisyear}",
					"style": 23,
					"decimalPlaces": "2"
				},
				"7": {
					"text": "#{proj.assignmoney}",
					"style": 23,
					"decimalPlaces": "2"
				},
				"8": {
					"text": "#{proj.ticketthismouth}",
					"style": 23,
					"decimalPlaces": "2"
				},
				"9": {
					"text": "#{proj.ticketthisyear}",
					"style": 23,
					"decimalPlaces": "2"
				},
				"10": {
					"text": "#{proj.ticketmoney}",
					"style": 23,
					"decimalPlaces": "2"
				},
				"11": {
					"text": "#{proj.receivethismouth}",
					"style": 23,
					"decimalPlaces": "2"
				},
				"12": {
					"text": "#{proj.receivethisyear}",
					"style": 23,
					"decimalPlaces": "2"
				},
				"13": {
					"text": "#{proj.receivemoney}",
					"style": 23,
					"decimalPlaces": "2"
				},
				"14": {
					"text": "#{proj.prereceivethismouth}",
					"style": 23,
					"decimalPlaces": "2"
				},
				"15": {
					"text": "#{proj.prereceivethisyear}",
					"style": 8
				},
				"16": {
					"text": "#{proj.prereceivemoney}",
					"style": 23,
					"decimalPlaces": "2"
				},
				"17": {
					"style": 23,
					"text": "#{proj.ticketnoreceive}",
					"decimalPlaces": "2"
				},
				"18": {
					"style": 23,
					"text": "#{proj.needticket}",
					"decimalPlaces": "2"
				},
				"19": {
					"style": 23,
					"text": "#{proj.needreceive}",
					"decimalPlaces": "2"
				},
				"20": {},
				"21": {},
				"22": {},
				"23": {},
				"24": {},
				"25": {},
				"26": {},
				"27": {},
				"28": {},
				"29": {},
				"30": {},
				"31": {},
				"32": {},
				"33": {},
				"34": {},
				"35": {},
				"36": {},
				"37": {},
				"38": {},
				"39": {},
				"40": {},
				"41": {},
				"42": {},
				"43": {},
				"44": {}
			},
			"height": 47
		},
		"10": {
			"cells": {
				"18": {
					"text": ""
				}
			}
		},
		"len": 101
	},
	"dbexps": [],
	"dicts": [],
	"rpbar": {
		"show": true,
		"pageSize": "20",
		"btnList": [
			1,
			2,
			3,
			4,
			5,
			6,
			7,
			8
		]
	},
	"freeze": "A1",
	"dataRectWidth": 1384,
	"displayConfig": {},
	"background": false,
	"name": "sheet1",
	"autofilter": {},
	"styles": [
		{
			"align": "center"
		},
		{
			"align": "center",
			"valign": "middle"
		},
		{
			"align": "center",
			"valign": "middle",
			"textwrap": true
		},
		{
			"align": "center",
			"textwrap": true
		},
		{
			"align": "center",
			"valign": "middle",
			"border": {
				"bottom": [
					"thin",
					"#000"
				],
				"top": [
					"thin",
					"#000"
				],
				"left": [
					"thin",
					"#000"
				],
				"right": [
					"thin",
					"#000"
				]
			}
		},
		{
			"align": "center",
			"valign": "middle",
			"textwrap": true,
			"border": {
				"bottom": [
					"thin",
					"#000"
				],
				"top": [
					"thin",
					"#000"
				],
				"left": [
					"thin",
					"#000"
				],
				"right": [
					"thin",
					"#000"
				]
			}
		},
		{
			"align": "center",
			"textwrap": true,
			"border": {
				"bottom": [
					"thin",
					"#000"
				],
				"top": [
					"thin",
					"#000"
				],
				"left": [
					"thin",
					"#000"
				],
				"right": [
					"thin",
					"#000"
				]
			}
		},
		{
			"align": "center",
			"border": {
				"bottom": [
					"thin",
					"#000"
				],
				"top": [
					"thin",
					"#000"
				],
				"left": [
					"thin",
					"#000"
				],
				"right": [
					"thin",
					"#000"
				]
			}
		},
		{
			"border": {
				"bottom": [
					"thin",
					"#000"
				],
				"top": [
					"thin",
					"#000"
				],
				"left": [
					"thin",
					"#000"
				],
				"right": [
					"thin",
					"#000"
				]
			}
		},
		{
			"align": "center",
			"font": {
				"size": 16
			}
		},
		{
			"font": {
				"size": 16
			}
		},
		{
			"font": {
				"size": 8
			}
		},
		{
			"align": "center",
			"font": {
				"size": 16,
				"bold": true
			}
		},
		{
			"font": {
				"size": 16,
				"bold": true
			}
		},
		{
			"align": "center",
			"valign": "middle",
			"border": {
				"bottom": [
					"thin",
					"#000"
				],
				"top": [
					"thin",
					"#000"
				],
				"left": [
					"thin",
					"#000"
				],
				"right": [
					"thin",
					"#000"
				]
			},
			"bgcolor": "#a7d08c"
		},
		{
			"bgcolor": "#a7d08c"
		},
		{
			"align": "center",
			"valign": "middle",
			"textwrap": true,
			"border": {
				"bottom": [
					"thin",
					"#000"
				],
				"top": [
					"thin",
					"#000"
				],
				"left": [
					"thin",
					"#000"
				],
				"right": [
					"thin",
					"#000"
				]
			},
			"bgcolor": "#a7d08c"
		},
		{
			"align": "right",
			"font": {
				"size": 16,
				"bold": true
			}
		},
		{
			"align": "right"
		},
		{
			"align": "left"
		},
		{
			"align": "left",
			"format": "date2"
		},
		{
			"format": "date2"
		},
		{
			"bgcolor": "#a7d08c",
			"align": "center"
		},
		{
			"align": "center",
			"valign": "middle",
			"border": {
				"bottom": [
					"thin",
					"#000"
				],
				"top": [
					"thin",
					"#000"
				],
				"left": [
					"thin",
					"#000"
				],
				"right": [
					"thin",
					"#000"
				]
			},
			"format": "number"
		},
		{
			"bgcolor": "#a7d08c",
			"align": "center",
			"border": {
				"bottom": [
					"thin",
					"#000"
				],
				"top": [
					"thin",
					"#000"
				],
				"left": [
					"thin",
					"#000"
				],
				"right": [
					"thin",
					"#000"
				]
			}
		}
	],
	"validations": [],
	"cols": {
		"1": {
			"width": 189
		},
		"2": {
			"width": 38
		},
		"3": {
			"width": 67
		},
		"4": {
			"width": 63
		},
		"5": {
			"width": 61
		},
		"6": {
			"width": 64
		},
		"7": {
			"width": 59
		},
		"8": {
			"width": 64
		},
		"9": {
			"width": 66
		},
		"10": {
			"width": 62
		},
		"11": {
			"width": 61
		},
		"12": {
			"width": 68
		},
		"13": {
			"width": 61
		},
		"14": {
			"width": 64
		},
		"15": {
			"width": 64
		},
		"16": {
			"width": 62
		},
		"17": {
			"width": 60
		},
		"18": {
			"width": 58
		},
		"19": {
			"width": 53
		},
		"len": 51
	},
	"merges": [
		"A1:H1",
		"I1:T1",
		"S2:T2",
		"A3:D3",
		"E3:H3",
		"I3:K3",
		"L3:N3",
		"O3:Q3",
		"R3:T3"
	]
}`

**Comment by tyhg001** [comment]
![image](https://user-images.githubusercontent.com/19584941/141708032-656433d6-9acf-416e-a1e8-29462b241d5c.png)

**Comment by tyhg001** [comment]
数据一共5000条左右

**Comment by tyhg001** [comment]
2000条数据导出是正常的，应该是样式循环的位置出了问题，创建的style过多了

**Comment by zhangdaiscott** [comment]
http://report.jeecg.com/2302149
这些参数看看改过吗
![image](https://user-images.githubusercontent.com/3162115/141715538-cc6a46ff-bc34-4877-b955-e76eef64de33.png)

**Comment by tyhg001** [comment]
改了参数：page-size-number: 64000，好像能导出来了

**Comment by zhangdaiscott** [comment]
改大了，反而能导出了？
