### ISSUE TITLE
导出excel，筛选条件没变，每次导出的数据都不相同

### ISSUE THREAD

**Issue by Ethan-stack-arch** [jeecgboot/JimuReport#661]
##### 版本号：
1.4.0

##### 问题描述：
根据查询条件进行筛选之后，选择导出excel，当数据量大的时候，每次导出的数据都不相同

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请详细说明

**Comment by Ethan-stack-arch** [comment]
![image](https://user-images.githubusercontent.com/78842627/142388015-c7acef29-9da3-4595-adf9-5842c694fed8.png)

![image](https://user-images.githubusercontent.com/78842627/142388080-792aa607-cf19-4868-a827-7c73d9a005fe.png)

![image](https://user-images.githubusercontent.com/78842627/142388232-bd838900-1469-49d1-bfa8-2fcdc7aad64c.png)

第三图为在线查询的数据只有一条，然后去掉id，导出为excel，发现有重复数据，第一二图为 导出的重复数据

**Comment by lvdandan16** [comment]
每个sheet都导出了同一条数据？

**Comment by Ethan-stack-arch** [comment]
不一定是每个sheet都会有同一条，是有随机重复的数据， 有可能A 这条数据在 sheet1 里有， 在sheet2 里也有，然后B 这条数据，在sheet1 没有，在sheet2 有 ，就是这种随机重复，

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
未复现该bug，去掉id是什么意思，将工人id的输入框清空吗，如果请空的话条件就传递不到后台，可能会出现你所说的bug，所以不能去除查询条件

**Comment by Ethan-stack-arch** [comment]
请问你用的版本是 1.4.1的嘛？    还是1.4.0的

**Comment by 1298191366** [comment]
1.4.1的

**Comment by 1298191366** [comment]
因为你看，如果查询条件不变的话，他应该是正确的，如果去除查询条件，就是导出全部了
![image](https://user-images.githubusercontent.com/30997828/142989056-86f8fbf5-be62-4146-a03f-e969e7a30698.png)

**Comment by Ethan-stack-arch** [comment]
是的，我说的去掉id的意思就是导出16号全部的，然后再导出的excel里筛选 工人id，就会可能有多条，我的版本是1.4.0

**Comment by Ethan-stack-arch** [comment]
我猜测，可能是因为数据超过1万条，然后分多个sheet，是多线程进行的，没有一个类似偏移量的值来记录数据是否已经导出，所以当导出的数据超过一万条，为多个sheet的时候，可能会有重复值，个人猜测。

**Comment by 1298191366** [comment]
你配置的是每页多少条，我本地是3万条，每个sheet 10000，分3页也没重现重复的数据，你设计页面是怎样设计的

**Comment by Ethan-stack-arch** [comment]
好的，我更新一下1.4.1试一下，我的是原本的基本配置，没改，每个sheet10000，谢谢你
