### ISSUE TITLE
报表导出excel或PDF时间数据缺失

### ISSUE THREAD

**Issue by Lctiv** [jeecgboot/JimuReport#663]
##### 版本号：
<dependency>
            <groupId>org.jeecgframework.jimureport</groupId>
            <artifactId>jimureport-spring-boot-starter</artifactId>
            <version>1.4.0</version>
        </dependency>

##### 问题描述：
报表设计一个单元格内放入俩个变量，具体内容如： ${reportmap.querystarttime}—${reportmap.queryendtime}
报表预览，及导出图片或者导出PDF图片 都可正确完整显示值比如2021-11-15—2021-11-15
但是导出为excel或PDF时自动经过时间格式转换，只保留了第一个变量的值，后面的字符-以及第二个变量值都不显示，而且时间格式是2021/11/15
##### 错误日志&截图：
报表设计截图：
![QQ图片20211115143721](https://user-images.githubusercontent.com/88873311/141733957-d3d3590c-54f5-4eb8-a4fe-03df1dd61923.png)
报表预览截图为正常展示：
![QQ图片20211115143822](https://user-images.githubusercontent.com/88873311/141734164-fc7dfd32-80b5-4493-9cb0-be8b5302cef9.png)
导出PDF或者excelli里展示数据缺失：
![image](https://user-images.githubusercontent.com/88873311/141734289-384b72a8-b118-463c-ab49-edc44310492e.png)
![image](https://user-images.githubusercontent.com/88873311/141734374-ebe8cc93-bfb1-4f51-ab07-b2e710ee8af1.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待下版本发布
