### ISSUE TITLE
=case()的判断

### ISSUE THREAD

**Issue by yzmking** [jeecgboot/JimuReport#664]
##### 版本号：
1.4.0

##### 问题描述：
当case内有不同的数据集，侧为空

##### 错误日志&截图：

![1636962007](https://user-images.githubusercontent.com/44563730/141741307-b74f8935-80b4-4f7c-ba1f-ac167d3bf786.jpg)
![1636962026(1)](https://user-images.githubusercontent.com/44563730/141741324-07ce0293-d81a-41fb-b7d7-1bd6e3fd8871.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持混数据集用
