### ISSUE TITLE
超链接是否可以支持变量赋值

### ISSUE THREAD

**Issue by liukaips** [jeecgboot/JimuReport#666]
##### 问题描述：
选择超链接不支持变量赋值

##### 错误日志&截图：

![Uploading image.png…]()
其中#{jira_task.task_id} 是否可以支持读取变量
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持

**Comment by 1298191366** [comment]
不支持读取变量，你可以参考http://report.jeecg.com/2427407中的网络报表钻取在下面新增参数进行拼接
