### ISSUE TITLE
excel导出报错

### ISSUE THREAD

**Issue by joel1889** [jeecgboot/JimuReport#667]
##### 问题描述：
导出excel,报null错误，如下图

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/64270082/141877355-993b3a6a-c93c-4f66-944f-dc9683f60e15.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级1.4.1试一下
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.4.1</version>
</dependency>
```
