### ISSUE TITLE
导出pdf不完整，表格也缺失

### ISSUE THREAD

**Issue by joel1889** [jeecgboot/JimuReport#668]
##### 问题描述：
导出前如图1，导出后如图2
问题一：导出的数据不完整
问题二： 导出后 部分表格缺失

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/64270082/141877681-e56f4b5c-5928-40cc-aa48-feb85a37a068.png)
![090909090909](https://user-images.githubusercontent.com/64270082/141878014-c0d6b48a-3c9e-4c08-b325-920db6bdea96.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级1.4.1版本即可
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.4.1</version>
</dependency>
