### ISSUE TITLE
请问 1.4.1 大概什么时候发布？

### ISSUE THREAD

**Issue by yxxcrtd** [jeecgboot/JimuReport#669]
请问 1.4.1 什么时候发布？

**Comment by lvdandan16** [comment]
1.4.1 已经发了，需配置[JEECG私服](http://report.jeecg.com/2195924) 
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.4.1</version>
</dependency>
