### ISSUE TITLE
希望可以在查询条件项中增加必填项设置

### ISSUE THREAD

**Issue by africaadonis** [jeecgboot/JimuReport#671]
##### 问题描述：
希望可以在查询条件项中增加必填项设置，否则查询大表的时候会查询全表，如果有此功能，就可以设置一个对应索引字段的必填查询条件了！
![image](https://user-images.githubusercontent.com/40649464/142143979-7e1a7f8b-6444-4717-94d0-94951c1c1778.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
无价值

**Comment by africaadonis** [comment]
http://www.unieapreport.com/
东软的这个报表中有此功能
