### ISSUE TITLE
数据查询工具条的时候显示总数据条数

### ISSUE THREAD

**Issue by yangjunzhou861012** [jeecgboot/JimuReport#672]
##### 问题描述：
数据查询的时候工具条只显示共多少页，但是没有显示共多少条记录数

##### 错误日志&截图：
可以看到共47页，但是并不知道具体多少条记录
![image](https://user-images.githubusercontent.com/18575974/142158899-d4b3dd4f-0708-4b52-bd1a-33459a09c904.png)

##### 重现步骤：
报表设计器-->新建报表-->填写好sql,设计好报表-->保存-->预览

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
已支持，下个版本发布
