### ISSUE TITLE
分组汇总问题

### ISSUE THREAD

**Issue by tyhg001** [jeecgboot/JimuReport#673]
##### 问题描述：
1. 汇总数据的小数位变多；
2.在单元格上的链接延续到了汇总的格上；

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/19584941/142171790-ada5eaef-c637-4efb-a6d2-ad88c1b5b2b5.png)
![image](https://user-images.githubusercontent.com/19584941/142171951-c4d4b1bb-a9d8-46e3-8be9-0aa61e093753.png)

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
已修复
