### ISSUE TITLE
在单元格中,常量和变量不能混合使用,函数计算和普通计算不能混用

### ISSUE THREAD

**Issue by abcdbbcd** [jeecgboot/JimuReport#674]
##### 版本号：
1.4.0以及1.4.1

##### 问题描述：
在单元格中使用 =C2+C3+10,在预览的时候就会报错:For input string ""
另一种情况,在单元格中使用=SUM(C2:AC2)/10,在预览的时候也会报错sub什么的

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持
归集到 #138
