### ISSUE TITLE
搜索下拉框最多只显示10条数据（应该显示所有，不要分页）

### ISSUE THREAD

**Issue by joel1889** [jeecgboot/JimuReport#675]
##### 问题描述：
如 下图所示，搜索下拉框最多只显示10条数据（应该显示所有，不要分页）

##### 错误日志&截图：
![868686868](https://user-images.githubusercontent.com/64270082/142376379-a851f7da-a14a-429a-94d4-e300e3fb643a.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
字典code用select SQL形式是不会分页的
你现在这个分页了吗？

**Comment by joel1889** [comment]
我的sql语句中没有分页，但是奇怪返回的数据只有10条，所以我怀疑是不是你们处理过给分页了？版本1.4.1

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
下个版本支持配置selectSearchPageSize：显示条数，如果像显示全部，分页条数设置长一条即可
![image](https://user-images.githubusercontent.com/30997828/144347835-539d4af0-3eaa-4a63-a744-ec5d1a0fcae5.png)
