### ISSUE TITLE
间隙变大

### ISSUE THREAD

**Issue by luojiewen123** [jeecgboot/JimuReport#677]
##### 问题描述：
间隙变大了，这是什么原因

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/50332160/142594181-173d66d0-6abd-465b-a962-353305183f0f.png)
![image](https://user-images.githubusercontent.com/50332160/142594249-6d50ff40-d4ea-4aa5-82cc-f74106d2bfad.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考常见问题 22：http://report.jeecg.com/2087464
