### ISSUE TITLE
怎么屏蔽查询下拉框的取消按钮

### ISSUE THREAD

**Issue by yzmking** [jeecgboot/JimuReport#678]
##### 版本号：

1.4.0
##### 问题描述：
怎么屏蔽查询下拉框的取消按钮

##### 错误日志&截图：

![1528](https://user-images.githubusercontent.com/44563730/142795117-a992bfb6-ea15-42a1-857c-df6fc2e181b8.png)
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
不支持
