### ISSUE TITLE
使用非管理员的账号时，报表钻取问题

### ISSUE THREAD

**Issue by yzmking** [jeecgboot/JimuReport#680]
##### 版本号：
1.4.0

##### 问题描述：

使用非管理员的账号时，报表钻取没有了链接报表的下拉选择，而已多条数据传参数id，均为第一条数据的id
##### 错误日志&截图：
![1637567886(1)](https://user-images.githubusercontent.com/44563730/142826560-b0fe2ea1-19e6-459c-a38a-7591c150637b.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
问题1：请确认是否开启saas模式，如果saas为true的情况下，请确保当前用户下存在报表，且不包含当前报表
问题2：配置的钻取的单元格数据是否重复，重复的话默认取第一条数据
