### ISSUE TITLE
报表设计：主表是列表，子表要根据主表的ID作为参数取数据

### ISSUE THREAD

**Issue by zhangjijun** [jeecgboot/JimuReport#682]
##### 版本号：
1.4.0

##### 问题描述：
报表设计：主表是列表，子表要根据主表的ID作为参数取数据，不知如何传参数

##### 错误日志&截图：
![1556af4c0615c4e1a602d7813147807](https://user-images.githubusercontent.com/10395554/142962844-67f279e4-17d1-4b0c-877a-3fa54a828d49.png)

官网ID：622950554817351680

##### 重现步骤：
子表的数据源是SQL，其中要接收一个参数ocean_id，但此参数来源于主表的结果集，主表在页面是列表的方式展示，不知如何配置参数。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
http://report.jeecg.com/2296481
