### ISSUE TITLE
PDF打印支持自适应行高

### ISSUE THREAD

**Issue by fqfcuc** [jeecgboot/JimuReport#684]
##### 版本号：
1.4.0

##### 问题描述：
因为需要在一个list上多选数据批量打印，我们用PDF合并的方式实现的，但是pdf打印有一个问题，就是不能根据内容自适应行高。需要pdf上根据单元格内容自适应行高

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
已支持 下个版本
