### ISSUE TITLE
点击下拉框,并未显示待选项

### ISSUE THREAD

**Issue by shenbushou** [jeecgboot/JimuReport#685]
##### 版本号：
1.38和1.4

##### 问题描述：
我在两个环境,1.38和1.4中都遇到这个问题,已经设置了查询项,和查询模式,但是预览时,点击下拉框,并未显示待选项,这种情况在四个报表中有出现,其他十几个报表未发现

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/64524981/142987418-88019faf-9409-4aec-9c6a-2237bb707321.png)

##### 重现步骤：
点击下拉框,并未显示 待选项
下面给出报表配置
[report-export-mysql (1).txt](https://github.com/jeecgboot/JimuReport/files/7586485/report-export-mysql.1.txt)
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
没显示的是用的报表参数还是报表字段

**Comment by JohnnyKIT** [comment]
> 

我也发现了，在同时设置有报表参数 和报表字段的查询后 报表字段的查询的下拉框就空了

**Comment by JohnnyKIT** [comment]
> 

1.4.0版本

**Comment by lvdandan16** [comment]
报表参数是必须要配置字典code，不会默认下拉框的值
你的报表参数和报表字段是同一个字段吗？

**Comment by JohnnyKIT** [comment]
> 报表参数是必须要配置字典code，不会默认下拉框的值 你的报表参数和报表字段是同一个字段吗？

并不是同一个字段
SQL:
SELECT encounter_doctor_id,encounter_doctor_name,encounter_dept_name,count(encounter_doctor_name) as '门诊完成量'
from outpatient_order_db.biz_outpatient_encounter
where 1=1 and active=1 and  encounter_status = '3' and encounter_type = '1' and encounter_dept_id in ('274','279','283','289','292','293','299','22060','22105','22106') and DATE_FORMAT(encounter_date,'%Y-%m-%d') between '${begintime}' and '${endtime}'
GROUP BY encounter_doctor_id,encounter_dept_id
ORDER BY encounter_dept_id,encounter_doctor_id

----
![image](https://user-images.githubusercontent.com/42707217/144564059-a1c6b4bd-53ea-4d28-ae29-564cbac1a98f.png)
![image](https://user-images.githubusercontent.com/42707217/144564083-007459e6-7e73-4e50-9873-0f7cf3f9e5e6.png)

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
