### ISSUE TITLE
时间范围查询

### ISSUE THREAD

**Issue by 123456db** [jeecgboot/JimuReport#686]
##### 版本号：

1.4.0
##### 问题描述：
数据库有一个字段day_id ,取值格式yyyyMMdd 
在前端作为查询条件 ，默认值为=dataStr('yyyyMMdd',-1)|=dataStr('yyyyMMdd',-1)  format格式yyyyMMdd

##### 错误日志&截图：
数据页面查询 时间控件显示不对

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请帖图

**Comment by 123456db** [comment]
这个已找到解决方法，前端不支持
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月26日(星期五) 下午5:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/JimuReport] 时间范围查询 (Issue #686)





 
请帖图
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
