### ISSUE TITLE
合并单元格后，打印高度问题

### ISSUE THREAD

**Issue by mageexiao** [jeecgboot/JimuReport#688]
##### 版本号：
1.4.0

##### 问题描述：
报表设计器截图：
![Snipaste_2021-11-25_09-03-20](https://user-images.githubusercontent.com/36838446/143334290-bf591427-d4e1-40f1-a14f-8ddbbe270f4b.png)
##### 错误日志&截图：
打印预览：
![Snipaste_2021-11-25_09-04-08](https://user-images.githubusercontent.com/36838446/143334318-60685d5a-ba0b-4d16-91cf-bf750a1e7282.png)
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 dd

**Comment by lvdandan16** [comment]
导出报表配置，我们复现一下

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题。
