### ISSUE TITLE
集成若依框架后出现问题

### ISSUE THREAD

**Issue by c626210053** [jeecgboot/JimuReport#689]
##### 版本号：
1.4.0

##### 问题描述：
集成若依框架 页面出来了  但是后台出现这个错误 为什么？

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/59947333/143382987-a5651cc3-cd1d-4319-b4d3-bf829d96478b.png)

##### 重现步骤：

按你们官网操作若依框架集成 然后做报表 后台控制台出现这个问题
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已修复，下个版本发布，这个是个警告，应该不影响功能使用，发布后请更新再看看是否已修复

**Comment by c626210053** [comment]
1.4.1版本&nbsp;他们有的能用，我maven的时候找不到。麻烦问下，还有就是 1.4.1&nbsp;大概什么时候发布？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月2日(星期四) 上午10:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 集成若依框架后出现问题 (Issue #689)





 
已修复，下个版本发布，这个是个警告，应该不影响功能使用，发布后请更新再看看是否已修复
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1298191366** [comment]
1.4.1 还不支持这个bug，发布新版本会在群里通知
