### ISSUE TITLE
图形报表折线图X轴无法排序

### ISSUE THREAD

**Issue by guolin1126** [jeecgboot/JimuReport#690]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/43664831/143399209-20741a32-a7e5-4c83-bb32-031e2d9d854e.png)

##### 重现步骤：
![image](https://user-images.githubusercontent.com/43664831/143399122-f92d7ddd-49ea-4e43-be0f-fcd9e827e360.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
x轴不支持排序，你用的是sql数据源还是api数据源，如果是sql数据源的话写order by应该会管用吧，如果是api查看每次传过来的数据是否就是错乱的，如果不是的话请提供你的sql语句或者提供报表配置及数据  http://report.jeecg.com/2376604

**Comment by guolin1126** [comment]
用的是sql数据源，一开始就写了order by 的，但是并没有用，你们可以模拟一下，sql很简单的，就是按照时间排序实现不了




sql如下：


select to_char(statistical_time,'yyyymmdd') as statistical_time,
order_count as 每日订单总数量,
sku_shipments as sku每日发货数量,
sku_count as sku总数量,
sku_stock as sku在库库存总数量,	
sku_storage as sku每日入库数量,
sku_the_library as sku每日出库数量,
order_storage as 每日入库单量,	
order_refund as 每日退款订单量,	
order_returns as 每日退货订单量,	
order_supply_again as 每日补发订单量,&nbsp;
mail_receiving as 每日邮件接收数量,	
mail_handling as 每日邮件处理数量	,
tongtool_operation_log as 每日通途操作日志数量,	
tongtool_remarks as 每日通途备注数量
from report_data_quantity
order by to_char(statistical_time,'yyyymmdd')&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月1日(星期三) 上午9:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 图形报表折线图X轴无法排序 (Issue #690)





 
你用的是sql数据源还是api数据源，如果是sql数据源的话写order by应该会管用吧，如果是api查看每次传过来的数据是否就是错乱的，如果不是的话请提供你的sql语句或者提供报表配置及数据  http://report.jeecg.com/2376604
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1298191366** [comment]
我就是用的order by之后没有重现出来问题，我本地用的是mysql，你用的是什么数据库，后者跟新到最新版1.4.2尝试一下

**Comment by zhangdaiscott** [comment]
你的表和数据提供下

**Comment by guolin1126** [comment]
数据库用的PostgreSQ，&nbsp;我在编辑预览出来数据就是排序正常的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月7日(星期二) 中午11:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 图形报表折线图X轴无法排序 (Issue #690)





 
你的表和数据提供下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lvdandan16** [comment]
重新编辑预览后正常了？

**Comment by guolin1126** [comment]
只是在数据集的编辑里面预览是正常的排序，但是在做成折线图之后预览排序是失效的








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月20日(星期一) 晚上7:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 图形报表折线图X轴无法排序 (Issue #690)





 
重新编辑预览后正常了？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lvdandan16** [comment]
你这个表数据和表结构，提供一下，我们测试一下，

**Comment by guolin1126** [comment]
数据库是PostgreSQL；


CREATE TABLE public.test_data_quantity (
	statistical_time date NULL,&nbsp;
	ddsl int4 NULL,&nbsp;
	shipments int4 NULL,&nbsp;
	ffsl int4 NULL,&nbsp;
	stock int4 NULL,
	s_storage int4 NULL,&nbsp;
	s_library int4 NULL,&nbsp;
	refund int4 NULL
);


INSERT INTO public.test_data_quantity
(statistical_time, ddsl, shipments, ffsl, stock, s_storage, s_library, refund)
VALUES('2021-12-20', 2102, 2185, 133191, 146274, 1567, 12334, 23343);
INSERT INTO public.test_data_quantity
(statistical_time, ddsl, shipments, ffsl, stock, s_storage, s_library, refund)
VALUES('2021-12-21', 2193, 2213, 133264, 143607, 1830, 4545, 45465);
INSERT INTO public.test_data_quantity
(statistical_time, ddsl, shipments, ffsl, stock, s_storage, s_library, refund)
VALUES('2021-12-22', 2019, 1908, 133341, 143661, 2145, 7544, 4255);
INSERT INTO public.test_data_quantity
(statistical_time, ddsl, shipments, ffsl, stock, s_storage, s_library, refund)
VALUES('2021-12-23', 1886, 1898, 133466, 143669, 543, 4425, 7775);
INSERT INTO public.test_data_quantity
(statistical_time, ddsl, shipments, ffsl, stock, s_storage, s_library, refund)
VALUES('2021-12-24', 1679, 1720, 133554, 143669, 5224, 3577, 9754);
INSERT INTO public.test_data_quantity
(statistical_time, ddsl, shipments, ffsl, stock, s_storage, s_library, refund)
VALUES('2021-12-25', 1252, 1133, 133556, 143681, 1395, 3454, 6454);
INSERT INTO public.test_data_quantity
(statistical_time, ddsl, shipments, ffsl, stock, s_storage, s_library, refund)
VALUES('2021-12-26', 1396, 88, 133556, 143681, 0, 6412, 1642);
INSERT INTO public.test_data_quantity
(statistical_time, ddsl, shipments, ffsl, stock, s_storage, s_library, refund)
VALUES('2021-12-27', 1843, 3030, 133556, 143669, 22, 15485, 1124);
INSERT INTO public.test_data_quantity
(statistical_time, ddsl, shipments, ffsl, stock, s_storage, s_library, refund)
VALUES('2021-12-28', 2414, 2317, 133557, 143654, 28, 4495, 1254);
INSERT INTO public.test_data_quantity
(statistical_time, ddsl, shipments, ffsl, stock, s_storage, s_library, refund)
VALUES('2021-12-29', 2271, 2334, 133729, 143652, 186, 4674, 4513);
INSERT INTO public.test_data_quantity
(statistical_time, ddsl, shipments, ffsl, stock, s_storage, s_library, refund)
VALUES('2021-12-30', 2212, 2188, 133854, 143675, 134, 1646, 4854);

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月20日(星期一) 晚上7:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 图形报表折线图X轴无法排序 (Issue #690)





 
你这个表数据和表结构，提供一下，我们测试一下，
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
