### ISSUE TITLE
导出excel、PDF加水印功能

### ISSUE THREAD

**Issue by kisspycn** [jeecgboot/JimuReport#691]
##### 版本号：
1.4

##### 问题描述：

是否具备报表数据导出excel、PDF文件加水印功能？
##### 重现步骤：
报表数据导出excel、PDF文件加水印功能。

**Comment by lvdandan16** [comment]
暂不支持
归集 #138

**Comment by kisspycn** [comment]
计划什么时候支持？

**Comment by lvdandan16** [comment]
具体时间还得后期再看

**Comment by jeecgos** [comment]
导出水印功能1.8.0版本已支持，欢迎试用。
