### ISSUE TITLE
插入图表乱码

### ISSUE THREAD

**Issue by xiaowen0710** [jeecgboot/JimuReport#692]
##### 版本号：
1.4.0

##### 问题描述：
插入图表乱码，idea测试正常，发布到tomcat乱码，数据库不乱码，用的同一个数据库。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/53167907/143411720-31b80964-a1e5-4a55-9fe7-36c908ea942d.png)

![image](https://user-images.githubusercontent.com/53167907/143411764-80342558-4b67-479b-881f-2153852ebc66.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
确认一下tomcat字符集

与gitee问题重复，关闭此问题
https://gitee.com/jeecg/JimuReport/issues/I4JKTV
