### ISSUE TITLE
系统参数使用  分页失效

### ISSUE THREAD

**Issue by 123456db** [jeecgboot/JimuReport#693]
##### 版本号：

1.4.0
##### 错误日志&截图：
insert into jimu_report(api_code,create_time,name,template,del_flag,id,view_count,note,status,thumb,update_time,create_by,api_url,type,css_str,update_by,js_str,code,json_str,api_method) values (null,'2021-11-22 10:34:27','门架系统牌识抓拍匹配成功率日报表',0,0,'622587720172048384','193',null,null,null,'2021-11-25 17:00:02','admin',null,'datainfo',null,'admin',null,'20211122103427','{"loopBlockList":[],"area":{"sri":18,"sci":3,"eri":18,"eci":3,"width":157,"height":25},"excel_config_id":"622587720172048384","printConfig":{"paper":"A4","width":210,"height":297,"definition":1,"isBackend":false,"marginX":10,"marginY":10,"layout":"portrait"},"zonedEditionList":[],"rows":{"0":{"cells":{"0":{"merge":[0,5],"height":25,"text":"门架系统牌识抓拍匹配成功率日报表","style":5,"zonedEdition":0},"7":{},"9":{"text":""}},"height":66},"1":{"cells":{"0":{"text":"统计日期","zonedEdition":0,"style":6},"1":{"text":"路段名称","zonedEdition":0,"style":6},"2":{"text":"路段单位","zonedEdition":0,"style":6},"3":{"text":"门架ID","zonedEdition":0,"style":6},"4":{"text":"门架名称","zonedEdition":0,"style":6},"5":{"text":" ","zonedEdition":0,"style":7}}},"2":{"cells":{"0":{"text":"#{report01.day_id}","style":8,"zonedEdition":0},"1":{"text":"#{report01.section_name}","style":8,"zonedEdition":0},"2":{"text":"#{report01.section_owner_name}","style":8},"3":{"text":"#{report01.gantry_id}","style":8},"4":{"text":"#{report01.gantry_name}","style":8},"5":{"text":" ","zonedEdition":0,"style":7},"7":{},"8":{},"9":{},"10":{},"11":{},"12":{}}},"3":{"cells":{"0":{"style":3,"text":" "},"1":{"style":3,"text":" "},"2":{"style":3,"text":" "},"7":{"style":3,"zonedEdition":0,"text":" "},"8":{"style":3,"zonedEdition":0,"text":" "},"9":{"style":3,"zonedEdition":0,"text":" "},"10":{"text":"","zonedEdition":0},"11":{"zonedEdition":0},"12":{"zonedEdition":0}}},"4":{"cells":{"7":{"style":3,"text":" "},"8":{"style":3,"text":" "},"9":{"style":3,"text":" "}}},"5":{"cells":{},"height":25},"6":{"cells":{"0":{"text":"备注：20211125"}}},"len":100},"dbexps":[],"dicts":[],"rpbar":{"show":true,"pageSize":"100","btnList":[1,2,3,4,5,6,7,8,9]},"freeze":"A1","dataRectWidth":1111,"displayConfig":{},"background":false,"name":"sheet1","autofilter":{},"styles":[{"align":"center"},{"align":"center","font":{"size":16}},{"font":{"size":16}},{"font":{"bold":true}},{"font":{"bold":true},"align":"center"},{"align":"center","font":{"size":16},"border":{"bottom":["thin","#000"],"top":["thin","#000"],"left":["thin","#000"],"right":["thin","#000"]}},{"align":"center","border":{"bottom":["thin","#000"],"top":["thin","#000"],"left":["thin","#000"],"right":["thin","#000"]}},{"border":{"bottom":["thin","#000"],"top":["thin","#000"],"left":["thin","#000"],"right":["thin","#000"]}},{"font":{"bold":true},"align":"center","border":{"bottom":["thin","#000"],"top":["thin","#000"],"left":["thin","#000"],"right":["thin","#000"]}}],"validations":[],"cols":{"0":{"width":100},"3":{"width":157},"4":{"width":154},"10":{"width":100},"len":50},"merges":["A1:F1"]}',null);
insert into jimu_report_db(db_code,db_ch_name,is_list,create_time,db_type,db_key,db_source,id,jimu_report_id,db_dyn_sql,is_page,update_time,tb_db_table_name,create_by,api_url,json_data,db_table_name,update_by,tb_db_key,java_type,java_value,api_method,api_convert,db_source_type) values ('report01','牌识抓拍匹配成功率日报表','1','2021-11-25 17:06:47','0',null,'622588170111815680','622588692273303552','622587720172048384','select
 day_ID
 ,SECTION_NAME
 ,SECTION_OWNER_NAME
 ,GANTRY_ID
 ,GANTRY_NAME
 ,DSC
 ,GANTRY_STATUS
 ,GANTRY_HEX
 ,GANTRY_ORDER_NUM
 ,GANTRY_TYPE
 ,VIU_PIC_NAME
 ,LABEL_SUCCESS_NUM
 ,MATCH_SUCCESS_NUM
 ,PIC_NUM
 ,MATCH_SUCCESS_RATE from HSOP_ST_ACT_GANTRY_PIC_MATCH_SUCCESS_RATE_DM   where day_id=''#{authonCode}'' order by day_id desc','1','2021-11-25 17:06:47',null,'admin',null,'',null,'admin',null,null,null,null,'','mysql');
insert into jimu_report_db_field(create_time,widget_type,order_num,search_mode,field_text,dict_code,id,search_flag,update_time,create_by,jimu_report_db_id,widget_width,search_value,update_by,field_name,search_format,ext_json) values ('2021-11-25 17:06:47','String',0,null,'section_name',null,'622588692357189632',0,null,'admin','622588692273303552',null,null,null,'section_name',null,'');
insert into jimu_report_db_field(create_time,widget_type,order_num,search_mode,field_text,dict_code,id,search_flag,update_time,create_by,jimu_report_db_id,widget_width,search_value,update_by,field_name,search_format,ext_json) values ('2021-11-25 17:06:47','String',1,3,'门架','SELECT  gantry_id AS value, gantry_name AS text FROM  HSOP_ST_ACT_GANTRY_PIC_MATCH_SUCCESS_RATE_DM group by value,text','622588692403326976',1,null,'admin','622588692273303552',null,null,null,'gantry_id',null,'');

insert into jimu_report_db_field(create_time,widget_type,order_num,search_mode,field_text,dict_code,id,search_flag,update_time,create_by,jimu_report_db_id,widget_width,search_value,update_by,field_name,search_format,ext_json) values ('2021-11-25 17:06:47','String',2,null,'gantry_type',null,'622588692432687104',null,null,'admin','622588692273303552',null,null,null,'gantry_type',null,'');
insert into jimu_report_db_field(create_time,widget_type,order_num,search_mode,field_text,dict_code,id,search_flag,update_time,create_by,jimu_report_db_id,widget_width,search_value,update_by,field_name,search_format,ext_json) values ('2021-11-25 17:06:47','String',3,null,'gantry_hex',null,'622588692466241536',null,null,'admin','622588692273303552',null,null,null,'gantry_hex',null,'');
insert into jimu_report_db_field(create_time,widget_type,order_num,search_mode,field_text,dict_code,id,search_flag,update_time,create_by,jimu_report_db_id,widget_width,search_value,update_by,field_name,search_format,ext_json) values ('2021-11-25 17:06:47','String',4,null,'gantry_order_num',null,'622588692491407360',null,null,'admin','622588692273303552',null,null,null,'gantry_order_num',null,'');
insert into jimu_report_db_field(create_time,widget_type,order_num,search_mode,field_text,dict_code,id,search_flag,update_time,create_by,jimu_report_db_id,widget_width,search_value,update_by,field_name,search_format,ext_json) values ('2021-11-25 17:06:47','date',5,2,'统计日期',null,'622588692524961792',1,null,'admin','622588692273303552',null,'=dateStr(''yyyyMMdd'',-1)|=dateStr(''yyyyMMdd'',-1)',null,'day_id','yyyyMMdd','');
insert into jimu_report_db_field(create_time,widget_type,order_num,search_mode,field_text,dict_code,id,search_flag,update_time,create_by,jimu_report_db_id,widget_width,search_value,update_by,field_name,search_format,ext_json) values ('2021-11-25 17:06:47','String',6,null,'gantry_name',null,'622588692554321920',null,null,'admin','622588692273303552',null,null,null,'gantry_name',null,'');
insert into jimu_report_db_field(create_time,widget_type,order_num,search_mode,field_text,dict_code,id,search_flag,update_time,create_by,jimu_report_db_id,widget_width,search_value,update_by,field_name,search_format,ext_json) values ('2021-11-25 17:06:47','String',7,null,'label_success_num',null,'622588692583682048',null,null,'admin','622588692273303552',null,null,null,'label_success_num',null,'');
insert into jimu_report_db_field(create_time,widget_type,order_num,search_mode,field_text,dict_code,id,search_flag,update_time,create_by,jimu_report_db_id,widget_width,search_value,update_by,field_name,search_format,ext_json) values ('2021-11-25 17:06:48','String',8,null,'match_success_num',null,'622588692613042176',null,null,'admin','622588692273303552',null,null,null,'match_success_num',null,'');
insert into jimu_report_db_field(create_time,widget_type,order_num,search_mode,field_text,dict_code,id,search_flag,update_time,create_by,jimu_report_db_id,widget_width,search_value,update_by,field_name,search_format,ext_json) values ('2021-11-25 17:06:48','String',9,null,'pic_num',null,'622588692642402304',null,null,'admin','622588692273303552',null,null,null,'pic_num',null,'');
insert into jimu_report_db_field(create_time,widget_type,order_num,search_mode,field_text,dict_code,id,search_flag,update_time,create_by,jimu_report_db_id,widget_width,search_value,update_by,field_name,search_format,ext_json) values ('2021-11-25 17:06:48','String',10,null,'gantry_status',null,'622588692671762432',null,null,'admin','622588692273303552',null,null,null,'gantry_status',null,'');
insert into jimu_report_db_field(create_time,widget_type,order_num,search_mode,field_text,dict_code,id,search_flag,update_time,create_by,jimu_report_db_id,widget_width,search_value,update_by,field_name,search_format,ext_json) values ('2021-11-25 17:06:48','String',11,null,'dsc',null,'622588692701122560',null,null,'admin','622588692273303552',null,null,null,'dsc',null,'');
insert into jimu_report_db_field(create_time,widget_type,order_num,search_mode,field_text,dict_code,id,search_flag,update_time,create_by,jimu_report_db_id,widget_width,search_value,update_by,field_name,search_format,ext_json) values ('2021-11-25 17:06:48','String',12,null,'viu_pic_name',null,'622588692734676992',null,null,'admin','622588692273303552',null,null,null,'viu_pic_name',null,'');
insert into jimu_report_db_field(create_time,widget_type,order_num,search_mode,field_text,dict_code,id,search_flag,update_time,create_by,jimu_report_db_id,widget_width,search_value,update_by,field_name,search_format,ext_json) values ('2021-11-25 17:06:48','String',13,null,'match_success_rate',null,'622588692764037120',null,null,'admin','622588692273303552',null,null,null,'match_success_rate',null,'');
insert into jimu_report_db_field(create_time,widget_type,order_num,search_mode,field_text,dict_code,id,search_flag,update_time,create_by,jimu_report_db_id,widget_width,search_value,update_by,field_name,search_format,ext_json) values ('2021-11-25 17:06:48','String',14,null,'section_owner_name',null,'622588692793397248',null,null,'admin','622588692273303552',null,null,null,'section_owner_name',null,'');

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
图文并茂，详细描述一下问题

**Comment by 123456db** [comment]
系统参数使用

第一页数据

第二页数据

第二页数据没有变化，前端页面没有变化

后台sql查询第一次数据正常的，第二次没有日志打印




不使用系统参数是正常的



第一页数据



第二页数据













------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月26日(星期五) 下午5:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 系统参数使用  分页失效 (Issue #693)





 
Closed #693.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
