### ISSUE TITLE
报表传自定义参数

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/JimuReport#694]
##### 版本号：
3.0

##### 问题描述：
需求：查看报表时，报表能显示操作者，并显示操作时间年月日时分秒,打印的时候用，可以知道是哪位操作员登录打印的，打印时间是什么时候

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
dd

**Comment by lvdandan16** [comment]
暂不支持
归集到 #138
