### ISSUE TITLE
主子表——主表是列表，子表根据主表的字段作为参数取数据问题

### ISSUE THREAD

**Issue by zhangjijun** [jeecgboot/JimuReport#696]
##### 版本号：
1.4.0

##### 问题描述：
主表是列表的情况，子表根据主表的某一字段作为参数，只展示了主表第一条数据对应的子表数据。

##### 错误日志&截图：
![1638171319(1)](https://user-images.githubusercontent.com/10395554/143826835-7fe4d77f-34b9-4678-ae27-ebf265f05a45.png)
![1638171538(1)](https://user-images.githubusercontent.com/10395554/143826887-b12afbd9-01d7-4dd6-acbf-fbb81e80165e.png)

##### 重现步骤：
最终期望达到的效果：
![image](https://user-images.githubusercontent.com/10395554/143827251-b6cc0de1-bb3d-4245-b456-1bad65e3c5a9.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
直接查是实现不了的
您可以试一下，用SQL将主子表联合查询出来，在设计器页面，主表字段使用纵向分组，子表字段正常展示
