### ISSUE TITLE
从1.1-beta 升级到1.4.0之后，预览报错

### ISSUE THREAD

**Issue by Rubyguanzi** [jeecgboot/JimuReport#699]
##### 版本号：

1.4.0
##### 问题描述：
这边是用jeecgboot2.4.2 版本单独升级jimureport 1.4.0 ，预览会提示数据回去： Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: com.alibaba.fastjson.JSONObject.clone()Lcom/alibaba/fastjson/JSONObject;

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/34430119/144157492-d6ab6f83-e694-4b2c-8dc2-c2163b9829a7.png)

##### 重现步骤：
预览就会出现问题

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
http://report.jeecg.com/2087464
31
