### ISSUE TITLE
请问预览的时候积木报表列宽能随鼠标拖动改动列宽吗？

### ISSUE THREAD

**Issue by charlie468** [jeecgboot/JimuReport#700]
##### 版本号：
1.4.0

##### 问题描述：
请问预览的时候积木报表列宽能随鼠标拖动改动列宽吗？

##### 错误日志&截图：
![E{VRYB0VGV{7O{@{`AIWKFG](https://user-images.githubusercontent.com/11472509/144159992-80d02aa6-b98e-4518-b7be-156cc89a7872.png)

**Comment by lvdandan16** [comment]
不支持
