### ISSUE TITLE
超链接参数在翻页后获取不到

### ISSUE THREAD

**Issue by tyhg001** [jeecgboot/JimuReport#701]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/19584941/144170038-ce996827-98de-42ad-941d-596b638af371.png)

第二页
![image](https://user-images.githubusercontent.com/19584941/144170341-8bfb1526-f725-4529-8d99-776432fd1523.png)
点击后网址参数没有了
![image](https://user-images.githubusercontent.com/19584941/144170405-bd2a0a06-ab11-4d0b-aa69-2e7a53a7b728.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
升级到这个版本
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.4.11</version>
</dependency>
```
