### ISSUE TITLE
是否支持三个API

### ISSUE THREAD

**Issue by luojiewen123** [jeecgboot/JimuReport#703]
##### 问题描述：

请问是不支持三个API吗 为什么我加了第三个 表头就没显示打印了  （已经测试了，只要删除第三个，第一个就能显示）
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/50332160/144215432-1ab34299-743b-4d84-a968-4d438ce9c9bf.png)
![image](https://user-images.githubusercontent.com/50332160/144215497-1f6c8a82-f9a0-4b7d-9e6e-693587495645.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
导出报表配置及数据，我们测一下吧

**Comment by luojiewen123** [comment]
已经解决了，原因是api报错，但是奇怪的是删除一个api，报错的接口都能查出来数据，






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 下午5:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 是否支持三个API (Issue #703)





 
导出报表配置及数据，我们测一下吧
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lvdandan16** [comment]
api 不报错，三个api都能出来了？

**Comment by luojiewen123** [comment]
嗯呐




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 下午5:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 是否支持三个API (Issue #703)





 
api 不报错，三个api都能出来了？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
