### ISSUE TITLE
=sum()函数计算double类型结果为Integer类型

### ISSUE THREAD

**Issue by yyicis** [jeecgboot/JimuReport#704]
##### 错误日志&截图：
![1638409753(1)](https://user-images.githubusercontent.com/80677701/144342783-8eada15c-f430-4a81-bedd-a03b3f1144f4.jpg)

![image](https://user-images.githubusercontent.com/80677701/144343133-c895831a-3059-4e56-933b-de20d9cf273f.png)

![image](https://user-images.githubusercontent.com/80677701/144343165-5d233f0f-e020-4313-bcef-0e118490d1f2.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
已经修复了，升级新版本
