### ISSUE TITLE
报表参数保存不成功

### ISSUE THREAD

**Issue by Optimusruan** [jeecgboot/JimuReport#707]
##### 版本号：
1.4.2

##### 问题描述：
已经存在的参数却提示找不到

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/16751699/144737265-dff8c3c6-5504-424e-8927-b1f890d9611c.png)
![20211205150332](https://user-images.githubusercontent.com/16751699/144737272-1b9bc130-5e60-46d0-9df9-b7fd55d8c34d.png)
![20211205150550](https://user-images.githubusercontent.com/16751699/144737277-98357917-8bfa-4063-965f-b934ea807038.png)
![20211205150525](https://user-images.githubusercontent.com/16751699/144737283-d7dab2cb-7a53-4213-b721-d8b6fea575d2.png)

##### 重现步骤：
点击该报表的设计，然后在系统自动保存后，提示找不到字段，尝试多次保存，会提示其他的字段找不到，需要不断重新修改字段再保存，运气好就马上可以，运气不好就要重复修改字段再保存的操作多次

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Optimusruan** [comment]
模板解析结果{"0":{"cells":{"2":{"merge":[1,17],"height":50,"text":"门 诊 工 作 量 统 计","style":5}}},"1":{"cells":{}},"2":{"cells":{"2":{"merge":[1,1],"height":50,"text":"科室|人次|就诊分类","lineStart":"lefttop","style":2},"4":{"text":"总诊疗","style":4,"merge":[1,0],"height":50},"5":{"merge":[0,4],"height":25,"text":"门诊人次","style":3},"10":{"merge":[0,4],"height":25,"text":"急诊人次","style":3},"15":{"merge":[0,4],"height":25,"text":"其他诊疗人次","style":3}}},"3":{"cells":{"5":{"text":"主任医师","style":2},"6":{"text":"副主任医师","style":2},"7":{"text":"主治医师","style":2},"8":{"text":"医师","style":2},"9":{"text":"合计","style":2},"10":{"text":"主任医师","style":2},"11":{"text":"副主任医师","style":2},"12":{"text":"主治医师","style":2},"13":{"text":"医师","style":2},"14":{"text":"合计","style":2},"15":{"text":"主任医师","style":2},"16":{"text":"副主任医师","style":2},"17":{"text":"主治医师","style":2},"18":{"text":"医师","style":2},"19":{"text":"合计","style":2}}},"4":{"cells":{"2":{"text":"全院合计","merge":[0,1],"height":25,"style":4},"3":{},"4":{"text":"=SUM(J5,O5,T5)","style":2},"5":{"text":"","style":2},"6":{"text":"","style":2},"7":{"text":"","style":2},"8":{"text":"","style":2},"9":{"text":"","style":2},"10":{"text":"","style":2},"11":{"style":2,"text":""},"12":{"style":2,"text":""},"13":{"style":2,"text":""},"14":{"style":2,"text":""},"15":{"style":2,"text":""},"16":{"style":2,"text":""},"17":{"style":2,"text":""},"18":{"style":2,"text":""},"19":{"style":2,"text":""}}},"5":{"cells":{"2":{"text":"☯{s1.group(科室分类)}","subtotal":"groupField","funcname":"-1","aggregate":"group","style":4},"3":{"text":"☯{s1.科室名称}","style":2},"4":{"text":"☯{s1.tot}","style":2,"funcname":"SUM","subtotal":"-1","aggregate":""},"5":{"text":"☯{s1.qty_normal2}","funcname":"SUM","subtotal":"-1","style":2},"6":{"text":"☯{s1.qty_normal3}","funcname":"SUM","subtotal":"-1","style":2},"7":{"text":"☯{s1.qty_normal4}","funcname":"SUM","subtotal":"-1","style":2},"8":{"text":"☯{s1.qty_normal5}","funcname":"SUM","subtotal":"-1","style":2},"9":{"style":2,"text":"☯{s1.tot_normal}","subtotal":"-1","funcname":"SUM"},"10":{"text":"☯{s1.qty_emc2}","funcname":"SUM","subtotal":"-1","style":2},"11":{"text":"☯{s1.qty_emc3} ","funcname":"SUM","subtotal":"-1","style":2},"12":{"text":"☯{s1.qty_emc4}","funcname":"SUM","subtotal":"-1","style":2},"13":{"text":"☯{s1.qty_emc5}","funcname":"SUM","subtotal":"-1","style":2},"14":{"style":2,"text":"☯{s1.tot_emc}","funcname":"SUM","subtotal":"-1"},"15":{"text":"☯{s1.qty_other2}","funcname":"SUM","subtotal":"-1","style":2},"16":{"text":"☯{s1.qty_other3}","funcname":"SUM","subtotal":"-1","style":2},"17":{"text":"☯{s1.qty_other4}","funcname":"SUM","subtotal":"-1","style":2},"18":{"text":"☯{s1.qty_other5}","funcname":"SUM","subtotal":"-1","style":2},"19":{"style":2,"text":"☯{s1.tot_other}","funcname":"SUM","subtotal":"-1"}}},"6":{"cells":{}},"7":{"cells":{"8":{"text":""}}},"8":{"cells":{}},"9":{"cells":{}},"10":{},"11":{"cells":{},"height":25},"12":{},"13":{},"14":{"cells":{"7":{"text":""}}},"15":{"cells":{},"height":25}}

**Comment by lvdandan16** [comment]
导出报表配置和数据

**Comment by Optimusruan** [comment]
阮才通已经收到您的邮件

**Comment by Optimusruan** [comment]
[数据.xlsx](https://github.com/jeecgboot/JimuReport/files/7693012/default.xlsx)

**Comment by Optimusruan** [comment]
现在怀疑是dbsum函数有问题，我将使用dbsum的所有格子清空，报表就不报“找不到xx变量”的错误了

**Comment by lvdandan16** [comment]
insert SQL语句贴上来，我们直接执行就可以

**Comment by Optimusruan** [comment]
阮才通已经收到您的邮件
