### ISSUE TITLE
关于增加报表的文件管理的功能

### ISSUE THREAD

**Issue by ouqiubin** [jeecgboot/JimuReport#708]
##### 问题描述：
在jeecgboot中使用积木报表进行报表创建时，如果在生产环境有100多张报表，现在这种列表或者视图格式就显得体系不够清楚，很杂乱。
虽然现在有提供搜索功能，但是，如果可以对报表分件进行分类管理的同时，再加上搜索就非常棒了。

##### 错误日志&截图：

![jimureport](https://user-images.githubusercontent.com/7531867/144802391-11059085-f7de-49c5-a6e4-b038811e19d3.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
右上角不是有视图切换吗

**Comment by ouqiubin** [comment]
> 不是有视图切换吗

企业中的报表通常都是有下钻等交互功能，那么在积木报表中开发一张报表，就需要两个或者三个以上的文件。这是一张报表，完整的BI报表系统，通常是上百张各种分析主题的报表，如果加上交互下钻等衍生出来出来的文件就会很多了。做一下文件的分类管理，比如按报表的标题名称归类到可以命名的文件夹内会清楚很多。

**Comment by lvdandan16** [comment]
归集到 #138

**Comment by jeecgos** [comment]
v1.8.1支持
