### ISSUE TITLE
分页有问题

### ISSUE THREAD

**Issue by joel1889** [jeecgboot/JimuReport#709]
##### 版本号：
1.4.2

##### 问题描述：
分页点击下一页无反应

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/64270082/144817217-c7b8bed8-f2bb-430b-b6fb-703b8c820c25.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
具体描述一下，api还是sql

**Comment by JohnnyKIT** [comment]
> 具体描述一下，api还是sql 可导出报表配置，我们测一下
1.4.2 mysql数据集
我的一个简单查询也遇到同样的问题分页不行。点击下一页只有页码会+1 但是数据并不会变，F12没有发起新的请求 配置如图：
![image](https://user-images.githubusercontent.com/42707217/145815051-2f855096-d52b-4acd-84be-cd434529b882.png)
![image](https://user-images.githubusercontent.com/42707217/145815108-4f0342ea-e283-43ac-ad55-0c84fea04667.png)
![image](https://user-images.githubusercontent.com/42707217/145815222-e62836e2-feda-4c37-9f47-d00db191d530.png)
![image](https://user-images.githubusercontent.com/42707217/145815265-37e37464-2873-4214-900f-acd7db24c5dd.png)
![image](https://user-images.githubusercontent.com/42707217/145815288-6e9d8a1a-c8ba-404e-a8c0-032b7ca78f4c.png)

**Comment by lvdandan16** [comment]
未测出此问题
导出报表配置和数据，我们复现一下吧
http://report.jeecg.com/2376604

**Comment by JohnnyKIT** [comment]
> 未测出此问题 导出报表配置和数据，我们复现一下吧 http://report.jeecg.com/2376604
我刚又测试了一下
Chrome版本79.0.3945.130有分页问题。最新Edge能正常分页，应该不是报表配置问题

**Comment by joel1889** [comment]
分页没有问题了
最近github总是登不上，所以就没回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月21日(星期二) 下午4:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 分页有问题 (Issue #709)





  
未测出此问题 导出报表配置和数据，我们复现一下吧 http://report.jeecg.com/2376604
 我刚又测试了一下
 Chrome版本79.0.3945.130有分页问题。最新Edge能正常分页，应该不是报表配置问题
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JohnnyKIT** [comment]
> 未测出此问题 导出报表配置和数据，我们复现一下吧 http://report.jeecg.com/2376604

好像是浏览器缓存的问题，清缓存后就可以了

**Comment by joel1889** [comment]
分页问题好了。
最近github无法登陆，所以一直没有回复


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月21日(星期二) 晚上7:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 分页有问题 (Issue #709)





  
未测出此问题 导出报表配置和数据，我们复现一下吧 http://report.jeecg.com/2376604
  
好像是浏览器缓存的问题，清缓存后就可以了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
