### ISSUE TITLE
springboot集成1.4.2版本启动即报错

### ISSUE THREAD

**Issue by Lctiv** [jeecgboot/JimuReport#711]
##### 版本号：

1.4.2
##### 问题描述：

springboot项目集成1.4.0版本正常运行，升级1.4.2版本启动即报错 com.mongodb.MongoSocketOpenException: Exception opening socket。 本项目并未搭建且无需使用mogodb，pom文件也未引入相关依赖。springboot版本2.4.12
##### 错误日志&截图：
正常运行1.4.0图片：
![image](https://user-images.githubusercontent.com/88873311/144978148-a9bb50bb-2a41-4aa4-87b6-fe0ef6dfd8ef.png)
升级1.4.2报错
![image](https://user-images.githubusercontent.com/88873311/144978303-6e609d76-7351-4ebc-8df1-93ce3f8b3846.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
启动类加上这段代码
`@EnableAutoConfiguration(exclude={MongoAutoConfiguration.class})`
