### ISSUE TITLE
本地上传模式下 图片名称包含中文无法显示

### ISSUE THREAD

**Issue by llmoe** [jeecgboot/JimuReport#713]
##### 版本号：
1.4.2

##### 问题描述：
本地上传模式下 图片名称包含中文无法显示。。。建议重新编码图片名字

##### 错误日志&截图：
<img width="1919" alt="截屏2021-12-09 11 59 46" src="https://user-images.githubusercontent.com/17946937/145332301-3445696a-8bf0-4290-a0fd-3793c47839b0.png">

##### 重现步骤：
本地上传模式，图片名字中文

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
你这个上传路径提供一下
![image](https://user-images.githubusercontent.com/54099258/145546790-27ac3d49-7a34-425b-894c-3f3c4864216a.png)

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题。
