### ISSUE TITLE
关于积木组件 引用的包问题

### ISSUE THREAD

**Issue by blackcatpolice** [jeecgboot/JimuReport#714]
##### 版本号：
1.4.0

##### 问题描述：
我的项目种用到了 Java Security 以及 org.bouncycastle:bcprov-jdk15on:1.6.8 这个包，但是却和报表种引用的包冲突，经过检查，积木报表其中引用到了 itext 相关的组件，  这些组件中 的 com.lowagie:itext-rtf:2.1.7 引用了 bouncycastle:bcprov-jdk14:138 . 

同时，另外一些组件还存在引用 

##### 重现步骤：
无

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
itext  pdf用的，你以手工排除试试
