### ISSUE TITLE
api参数钻取错误

### ISSUE THREAD

**Issue by tyhg001** [jeecgboot/JimuReport#715]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/19584941/145503775-af4f8509-c60a-4c69-99f4-724b981d3453.png)
点击第二条仍然取的是第一条的项目id
![image](https://user-images.githubusercontent.com/19584941/145503867-e7a0fe45-e0df-4387-83aa-82c13a00e7c2.png)

**Comment by lvdandan16** [comment]
设计页面是配置的=A1 还是=A，如果是=A1 就是取第一条
![image](https://user-images.githubusercontent.com/54099258/145545792-950d016e-476c-4ed1-9b9b-9d4773dcc586.png)
