### ISSUE TITLE
积木报表上传图片无法预览，jimu官网例子可复现

### ISSUE THREAD

**Issue by Sunshinebaby** [jeecgboot/JimuReport#717]
##### 版本号：
1.4.0

##### 问题描述：
积木报表上传图片无法预览，jimu官网例子可复现

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/20432403/145741534-b60ec25e-33f1-4fd0-a2ef-23ce09392a4d.png)
![image](https://user-images.githubusercontent.com/20432403/145741721-8f6fb501-3145-47ef-9d20-fd5b47a89b5c.png)

##### 重现步骤：
打开报表，上传图片，图片无法预览

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/146537763-b39a642e-40ec-4d09-8fef-ae94b0b37c67.png)
没上传成功吧

**Comment by lvdandan16** [comment]
此问题因长时间未回复，暂时关闭
