### ISSUE TITLE
如何使用JeecgBoot的数据字典呢？

### ISSUE THREAD

**Issue by yijian0645** [jeecgboot/JimuReport#719]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
直接用就可以了，配置系统字典编码
![image](https://user-images.githubusercontent.com/54099258/145800286-6c0e69bf-c3ec-4d04-bfc6-955e250546de.png)

**Comment by lvdandan16** [comment]
积木报表字典与jeecgboot数据字典相互独立的，可以把jeecgboot字典数据导入到报表字典中
