### ISSUE TITLE
关于系统变量使用问题

### ISSUE THREAD

**Issue by yijian0645** [jeecgboot/JimuReport#720]
##### 问题描述：

查询创建人是当前登录用户的记录报表时，照着文档里配置了SQL数据源语句为：
select * from demo_student2 where create_by = '#{sysUserCode}'
然后发现预览的时候就报错了。

用的是JeecgBoot整合积木报表来着，业务表demo_student2 中是包含create_by字段的。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/14273752/145764784-b0f6500e-f555-4c12-94fc-459f0e80c9ed.png)

##### 重现步骤：
![image](https://user-images.githubusercontent.com/14273752/145764828-2d7d5f53-a95f-4eec-921a-b5415f6a256f.png)

![image](https://user-images.githubusercontent.com/14273752/145764870-58d0cd52-33f1-4dc3-a91e-4779dab185c5.png)

![image](https://user-images.githubusercontent.com/14273752/145764907-d6443148-e734-413b-835a-9a411c3716ac.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by yijian0645** [comment]
这个什么问题啊，折腾好久都没找到原因。。。

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
未测出，请导出配置和数据。http://report.jeecg.com/2376604

**Comment by 1298191366** [comment]
报错信息已修复，待新版本发布，出现这个错误是因为你没有自定义系统变量，参考文档http://report.jeecg.com/2159712

**Comment by yijian0645** [comment]
> 

文档我看了，就是说默认系统变量sysUserCode也不能直接在SQL中用，也需要先配置一下“三、如何自定义系统变量”里面的自定义系统变量才可以是吧？

**Comment by 1298191366** [comment]
> > 
> 
> 文档我看了，就是说默认系统变量sysUserCode也不能直接在SQL中用，也需要先配置一下“三、如何自定义系统变量”里面的自定义系统变量才可以是吧？

是的，你需要自己做一下，如果是jeecgboot直接复制一份即可
