### ISSUE TITLE
查询只能显示10条件，但是查询失效

### ISSUE THREAD

**Issue by tsh0794** [jeecgboot/JimuReport#721]
##### 版本号：

1.4.2
##### 问题描述：
查询只能显示10条件，但是查询失效。查看后台发现，年份作为参数，后面无法获取到，一直都是空。比如月份，报表数据有1-11月份，但是查询条件只能显示10条，并且搜索11显示无此数据

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/89760691/145943170-d0d6f20b-b496-47f8-87ba-c4dd39cb7f18.png)
![2](https://user-images.githubusercontent.com/89760691/145943204-4470145a-b7bd-4264-a739-bde2058d3fb8.png)

![3](https://user-images.githubusercontent.com/89760691/145943224-0552f878-f6a9-4415-a63e-fc726cd84b1b.png)

![image](https://user-images.githubusercontent.com/89760691/145946558-3e893413-43b5-4e90-a1f7-1c4fa4b0190c.png)
![image](https://user-images.githubusercontent.com/89760691/145946865-6b8be387-de2e-466a-a0d2-11fb2b387634.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
导出报表配置和数据，我们复现一下
http://report.jeecg.com/2376604

**Comment by tsh0794** [comment]
不好意思，一直再忙忘记了，我现在就上传。



***@***.***
 
发件人： lvdandan16
发送时间： 2021-12-17 19:29
收件人： jeecgboot/JimuReport
抄送： tsh0794; Author
主题： Re: [jeecgboot/JimuReport] 查询只能显示10条件，但是查询失效 (Issue #721)
导出报表配置和数据，我们复现一下
http://report.jeecg.com/2376604
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tsh0794** [comment]
[report-export-mysql.txt](https://github.com/jeecgboot/JimuReport/files/7760250/report-export-mysql.txt)
[数据.xlsx](https://github.com/jeecgboot/JimuReport/files/7760251/default.xlsx)

**Comment by tsh0794** [comment]
这问题，什么时候能处理完哦

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
1.4.21已经修复，注意：在1.4.21之后版本没有最数据去重处理，数据如果重复请用sql语句的方式拼写`select`
![image](https://user-images.githubusercontent.com/30997828/154431979-79861f50-43f7-4c12-a219-e86eed5904e7.png)

```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.4.2</version>
</dependency>
```
