### ISSUE TITLE
关于数据字典可以按照多字段检索的建议

### ISSUE THREAD

**Issue by JohnnyKIT** [jeecgboot/JimuReport#722]
##### 版本号：

1.4.2
##### 问题描述：
现在下拉列表的数据字典只能提供value 和 text 。下拉菜单可以检索text。希望可以额外提供类似text的检索字段。例如我想提供拼音码字段，在下拉展示text的情况下，还能通过拼音码模糊检索下拉项目。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
归集到 #138
