### ISSUE TITLE
积木报表魔板案例上传封面报错

### ISSUE THREAD

**Issue by gbf0722** [jeecgboot/JimuReport#723]
##### 版本号：
1.3.78

##### 问题描述：

积木报表魔板案例上传封面报错，后台报参数错误
##### 错误日志&截图：

Name for argument type [java.lang.Long] not available, and parameter name information not found in class file either
##### 重现步骤：
登陆积木报表，数据报表，点击模板案例，随意找个案例，点击上传封面，idea控制台报错。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by gbf0722** [comment]
积木报表魔板案例上传封面报错

**Comment by zhangdaiscott** [comment]
改过了，升级到最新版
