### ISSUE TITLE
bug提交--在线设计无法登录

### ISSUE THREAD

**Issue by Zhenzheng00** [jeecgboot/JimuReport#724]
##### 问题描述：
积木报表在线设计无法登录

##### 错误日志&截图：
![bug](https://user-images.githubusercontent.com/66759925/146168833-3d426415-9ec1-474e-adba-a2fe2024dd27.png)

##### 重现步骤：
主页登录即可重现

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
现在可以了吗
