### ISSUE TITLE
存储过程执行异常

### ISSUE THREAD

**Issue by YBenX** [jeecgboot/JimuReport#726]
##### 错误日志&截图：存储过程执行异常(sql server)
![image](https://user-images.githubusercontent.com/3353434/146354325-cebbaa4f-7acb-462b-9037-ace6e8c7e6d7.png)

mysql的不报异常，但是查询不到数据，实际是有数据的
![image](https://user-images.githubusercontent.com/3353434/146393912-8e633fe0-843b-4438-b12d-6404d3c9365a.png)

![image](https://user-images.githubusercontent.com/3353434/146393819-268a93f1-e34f-4d96-b78d-e5add4243951.png)

![image](https://user-images.githubusercontent.com/3353434/146393766-dab4a2d6-57c2-4dc4-969c-a0dbdfcbf1fc.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
为复现，你的参数里面是否存在默认值，你是不是点击数据预览是报的错误
![image](https://user-images.githubusercontent.com/30997828/146735922-081b3e36-9f40-4dc2-a110-1ceb8e4def2b.png)

**Comment by YBenX** [comment]
经排查存储过程里面有临时表时会报错。
CREATE PROCEDURE [dbo].[SP_Test] 
 @WorkID INT,
 @BDate DATETIME,--开始时间
 @EDate DATETIME--结束时间 
AS
BEGIN  

 CREATE TABLE #TempData
 (
     A INT, 
  B VARCHAR(30), 
  C INT, 
 )   
   INSERT INTO #TempData(A,B,C)
   SELECT 1,'测试',22 
   SELECT * FROM #TempData
  DROP TABLE #TempData
END

**Comment by 1298191366** [comment]
![image](https://user-images.githubusercontent.com/30997828/146746146-a011688a-0a82-4413-bf69-bcd9b3f1f0ee.png)

**Comment by 1298191366** [comment]
可以通过` set nocount on`来解决
![image](https://user-images.githubusercontent.com/30997828/146746170-74e7a0e9-4e2a-4c53-a7fc-3a2eadb36834.png)
