### ISSUE TITLE
个性排名控件动画失效

### ISSUE THREAD

**Issue by ericsuch** [jeecgboot/JimuReport#728]
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by ericsuch** [comment]
![image](https://user-images.githubusercontent.com/49475546/146625974-43c2ee75-894f-4aad-960a-81668e0f87c5.png)

**Comment by lvdandan16** [comment]
你怎么配置的，可以把大屏id贴上来，我们看一下

**Comment by ericsuch** [comment]
您好


你把排名表，个性排名拉出来。就可以看到了。
https://bootapi.jeecg.com/bigscreen/#/view/1468568093004402689















在 2021-12-20 19:00:43，"lvdandan16" ***@***.***> 写道：

你怎么配置的，可以把大屏id贴上来，我们看一下

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/146882072-64300b00-0ce0-4d30-a4b1-ab857c047b07.png)
我这点开没问题 你是什么浏览器

**Comment by ericsuch** [comment]
Mac / Chrome
















在 2021-12-21 14:27:47，"lvdandan16" ***@***.***> 写道：


我这点开没问题 你是什么浏览器

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ericsuch** [comment]
Hello



现在又好了。







在 2021-12-21 14:27:47，"lvdandan16" ***@***.***> 写道：


我这点开没问题 你是什么浏览器

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
