### ISSUE TITLE
SQL是否支持临时表的写法?

### ISSUE THREAD

**Issue by YBenX** [jeecgboot/JimuReport#729]
##### 问题描述：
SQL Server 数据库，是否支持临时表的写法?现在执行会报错: 不支持该SQL转换为分页查询!

##### 错误日志&截图： 
![image](https://user-images.githubusercontent.com/3353434/146633740-5ceb8eef-9950-4dc1-9224-c8f826fa5a3f.png)

![image](https://user-images.githubusercontent.com/3353434/146633718-1a40b56d-5dd3-4b2f-a7ed-95d5465b48fc.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你可以换成视图或者存储过程写法

**Comment by YBenX** [comment]
> 以换成视图或者存储过程写法

现在存储过程执行是会报错的，这个能不能尽快修复，影响使用了比较急。
