### ISSUE TITLE
查询条件栏能否默认展开？

### ISSUE THREAD

**Issue by YBenX** [jeecgboot/JimuReport#731]
##### 问题描述：
查询条件栏能否默认展开？

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/3353434/146731919-54be5293-6281-4773-95ed-730134d206ce.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考常见问题38：http://report.jeecg.com/2087464
