### ISSUE TITLE
大屏设计器配置的接口地址，端口必须映射到公网才能访问到数据吗

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/JimuReport#732]
##### 版本号：
1.4.2

##### 问题描述：
比如我配置的接口地址，该地址端口没有映射到公网，但是能上网，请问这样的网络环境能使用吗

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/90361617/146752303-6e08059c-e8c5-4fa8-a673-3c22e4bc102c.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
需要https
https://my.oschina.net/jeecg/blog/5340254
