### ISSUE TITLE
系统变量直接在报表上显示

### ISSUE THREAD

**Issue by YBenX** [jeecgboot/JimuReport#733]
##### 问题描述：
什么时候支持系统变量直接在报表上显示?
尝试过#{param.sysUserCode}或${param.sysUserCode}都无法显示。能否优先处理一下这个问题，比较急用，感谢。
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/3353434/146777314-f7a4203f-3e4f-4e5b-aeb5-3b7c08447ab0.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
