### ISSUE TITLE
数据源配置错误

### ISSUE THREAD

**Issue by LYHHS** [jeecgboot/JimuReport#734]
![image](https://user-images.githubusercontent.com/17923609/146861563-5fbfbfe8-8b35-4804-9203-12b1da95386b.png)

为什么会出现数据源配置错误的情况，我数据源测试连接是成功的

**Comment by lvdandan16** [comment]
大屏id贴出来，我们看一下

**Comment by lsqGitHub716** [comment]
问题现在还存在吗
