### ISSUE TITLE
jeecgboot2.2.1按文档集成积木报表后，提示token为空。

### ISSUE THREAD

**Issue by deping85** [jeecgboot/JimuReport#735]
##### 版本号：
积木报表1.4.2
jeecgboot2.2.1

##### 问题描述：
按文档集成，打开积木报表时，提示token为空。寻去解决方法。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/88117301/146882977-63c6612e-b9e8-4b45-9c48-9a808da24680.png)
![image](https://user-images.githubusercontent.com/88117301/146883074-3843ec43-c038-460b-91cd-67810517a29f.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by deping85** [comment]
![image](https://user-images.githubusercontent.com/88117301/147013959-5fe48cf5-86f2-47b3-bfc3-f3d0afddffc0.png)
调整shiroconfig文件中的顺序，把这段代码放在过滤器靠前面的位置，不提示token为空了。但是提示“No message available”。
![image](https://user-images.githubusercontent.com/88117301/147014058-d98b5978-dbd9-4087-bf40-9251b18edfb8.png)
安装官方视频教程中演示，多次刷新Maven,build项目，没有效果。后续不知道该如何处理了。请教各位大神！！

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
未测出，通过官方文档集成应该没问题，我是新下载下来的项目，你看看项目是不是改了什么东西
![image](https://user-images.githubusercontent.com/30997828/155446433-4576262a-e552-4803-819e-b17593b7dd82.png)
