### ISSUE TITLE
时间选择框bug

### ISSUE THREAD

**Issue by lizhiit** [jeecgboot/JimuReport#737]
##### 版本号：
            <version>1.4.2</version>
##### 问题描述：
时间选择框与选择结果错位，如截图所示，我在时间选择框里选择的是2021年12月1日  但最终填写的值却是2021-12-03

##### 错误日志&截图：
![VQNPM)W}MD()({J$ CSLM55](https://user-images.githubusercontent.com/40656956/146888683-a02d8191-7639-4aa8-b8aa-9a5eb443f930.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws
