### ISSUE TITLE
下拉选择列表只能支持10个内容

### ISSUE THREAD

**Issue by hu11612457** [jeecgboot/JimuReport#739]
##### 版本号：
jimureport-example-1.4.jar

##### 问题描述：

下拉框里只有10个选项，未包含所有
##### 错误日志&截图：

截图没有找到地方上传，就是查询栏的下拉列表只显示10个内容，没有显示全部的内容

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by ycy8126** [comment]
![image](https://user-images.githubusercontent.com/97648370/149258723-55659898-70db-49a0-be6b-fab2b6db81b1.png)
技术支持文档里有
