### ISSUE TITLE
db 单元格表达式 无法使用

### ISSUE THREAD

**Issue by wyeye** [jeecgboot/JimuReport#742]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/51752290/147449191-470511f2-8eba-42e2-b821-084da7f0ba7b.png)
![image](https://user-images.githubusercontent.com/51752290/147449229-9a510152-d8f1-4aea-942a-c1bed1573ac9.png)
![image](https://user-images.githubusercontent.com/51752290/147449247-270b55e2-c7e9-40f1-a33f-bd3bab12ee37.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
使用的是什么数据集，目前只支持sql数据集

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
