### ISSUE TITLE
导出Excel时报错Method code too large!

### ISSUE THREAD

**Issue by ljy1762701876** [jeecgboot/JimuReport#743]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/96720416/147453943-a2f23d10-d892-4e4b-a054-2bec0feaba56.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by ljy1762701876** [comment]
版本已升级到1.4.2，但这个错误还在

**Comment by lvdandan16** [comment]
提供报表配置及数据，我们看一下

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
