### ISSUE TITLE
【报表联动】联动图表异常

### ISSUE THREAD

**Issue by Action45** [jeecgboot/JimuReport#746]
##### 错误日志&截图：
http://localhost:8661/report/jmreport/getCharData?params=[%7B%22test_user%22:%22310487954101248%22%7D]&charId=jhNNvURoUV5JK8oR&reportId=633879184887439360
![image](https://user-images.githubusercontent.com/87290598/147520951-31573d0c-1fee-4968-821c-808058c69096.png)

后台：
![image](https://user-images.githubusercontent.com/87290598/147520983-7ba55bf6-102b-4a69-adf1-f2c2fb3fd18f.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
提供报表配置及数据

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
