### ISSUE TITLE
Oracle数据源具体该怎么配置

### ISSUE THREAD

**Issue by yuantaoge** [jeecgboot/JimuReport#747]
##### 问题描述：
测试连接时提示：数据源已连接错误3次以上,请检查配置信息

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/59112182/147553462-0a0ae293-5397-4d13-aafe-cfde1563dc9d.png)

##### 重现步骤：
以下是数据源的相关信息

![1640679082182_F26CFEC9-0640-4f0d-87EE-3398A4E59BAC](https://user-images.githubusercontent.com/59112182/147553580-14650b46-47e9-4d9a-9e30-a2a7814e43f3.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
说明你配置错误，填写正确的信息
