### ISSUE TITLE
初次接触，请问Oracle数据源具体该如何连接

### ISSUE THREAD

**Issue by yuantaoge** [jeecgboot/JimuReport#748]
##### 问题描述：
显示数据源成功连接后一段时间又显示数据连接失败

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/59112182/147556562-9178b972-e307-4755-9459-322bc08290e4.png)
显示数据源成功连接
![image](https://user-images.githubusercontent.com/59112182/147556722-92d25450-98ff-45ab-bf43-24f74626023b.png)
但是等一会儿，就显示数据连接失败

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lsqGitHub716** [comment]
请问问题现在还存在吗？
