### ISSUE TITLE
orcle数据源配置

### ISSUE THREAD

**Issue by yuantaoge** [jeecgboot/JimuReport#749]
##### 问题描述：
知道显示是配置信息错了，但是不知如图所示，具体是错在哪里，请不吝赐教，方便的话不知能否圈点出来，不胜感激
下面奉上数据源配置截图以及相关所需配置数据库的信息，小白初次接触，感激感激

##### 错误日志&截图：
![1640742770539_7623D36F-8F0C-4f8f-85EF-CF5C0A8FFD9C](https://user-images.githubusercontent.com/59112182/147620023-2a3e3d05-0933-42e6-8d93-d1438ab259a7.png)
下面是数据库的相关信息
Data Source=(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 10.20.4.162 )(PORT = 1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = MES)));
User Id=MES_TEST;
Password=MES_TEST123;

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
ip 端口外网不通把，请确认外网是否通
