### ISSUE TITLE
数据源连接问题

### ISSUE THREAD

**Issue by yuantaoge** [jeecgboot/JimuReport#750]
##### 问题描述：
测试连接一开始显示连接成功，一会儿又显示失败，期间并没有做任何改动

##### 错误日志&截图：
![1640751057515_BABF60E6-21EA-4fd7-B1A3-7ACA74DDD255](https://user-images.githubusercontent.com/59112182/147626942-380788af-8e40-4954-a8ed-9f0ed29c10f2.png)

![1640751100427_1D860877-BF65-4fa5-A498-138C7CCD46CB](https://user-images.githubusercontent.com/59112182/147626948-7ee7e5cd-84de-4b66-b5e2-6550e8e9200d.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
影响大屏使用吗

**Comment by yuantaoge** [comment]
![image](https://user-images.githubusercontent.com/59112182/147627823-accfd632-3e3a-4ab1-89e7-55fd69948fb9.png)
很影响

**Comment by lsqGitHub716** [comment]
数据加载异常的时候，你用Navicat连那个oracle数据库可以正常连接吗

**Comment by yuantaoge** [comment]
用PLsqlDeveloper连接这个oracle数据库可以正常连接的
![image](https://user-images.githubusercontent.com/59112182/147715460-8b91bef2-f907-43c3-bc40-003c902d218f.png)

**Comment by yuantaoge** [comment]
![image](https://user-images.githubusercontent.com/59112182/147715574-f6b46c3d-f0cf-4ff1-a463-909fe724e5c8.png)
上次连接后我搜索了好久，怀疑格式错了，然后根据百度把最后的位置改为实例名后连接如下图测试连接成功
![lALPJwY7RAPdKqvNAlbNAp4_670_598](https://user-images.githubusercontent.com/59112182/147715641-ff2e69cc-a388-47a4-bcca-16fac60ee1ad.png)
但是在大屏使用时，依旧是如下图数据源有问题
![lALPJxf-vTvOuK7NAnPNAvo_762_627](https://user-images.githubusercontent.com/59112182/147715695-6c2bac88-f028-43b9-b1c1-98348a0afa9c.png)
然后加了QQ群，在群里也有人碰到和我一样的问题（不过他连接的是MySQL数据库），后来我用MySQL数据库也测试了一下，结果如下图
![lALPJwY7RAQHqkTNAlfNAo8_655_599](https://user-images.githubusercontent.com/59112182/147715787-93efe3c9-e485-422d-b8b7-e564dd896d67.png)
![lALPJx8ZuoUnB9vNAk_NAo8_655_591](https://user-images.githubusercontent.com/59112182/147715800-7a5aae06-a285-4063-95f7-296d6c9b5af6.png)
返回数据源就显示下图这样
![lALPJwnIwqiV1QbNAijNApA_656_552](https://user-images.githubusercontent.com/59112182/147715898-5b36a4a9-b824-4572-b43e-b0bc8a04caaf.png)
还是一样的问题

**Comment by lsqGitHub716** [comment]
![image](https://user-images.githubusercontent.com/65587928/147717856-c14e3fb6-37bf-4883-b057-15f1902d3425.png)
mysql在这个地方放好使吗？

**Comment by lsqGitHub716** [comment]
你把创建的oracle数据源删了，再重新建一个，然后看sq执行这里正常吗

**Comment by yuantaoge** [comment]
mysql也是一样的问题
![ce20dc3f06a0636f1cc1057a17ca428799bbede04ffb45644df47f05a4622407QzpcVXNlcnNcQWRtaW5pc3RyYXRvci5QQzgwMTA5MTAwMTBcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDExNDg3MzMzMDlfdjJcSW1hZ2VGaWxlc1wxNjQwODQyMjM4OTg0X0I3NzVGMUE0LUM4OEQtNDQxOS1CQjEwLTJGMjYyMzkzNDE2OC5wbmc=](https://user-images.githubusercontent.com/59112182/147724573-dc625acf-13ad-4de9-ae36-d82212320dc4.png)
![226e280dda5113a7d17a46ddd57582e1d7669e3ba7d6aaa1f4034061663a8e7eQzpcVXNlcnNcQWRtaW5pc3RyYXRvci5QQzgwMTA5MTAwMTBcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDExNDg3MzMzMDlfdjJcSW1hZ2VGaWxlc1wxNjQwODQyNDU3OTc4X0I3ODk0RjMxLThCODMtNDE0NS1CNjFELUMwOTk5RUNFNUZBNy5wbmc=](https://user-images.githubusercontent.com/59112182/147724578-3e800b71-d0a9-414d-a11a-a9e4943b60b6.png)

**Comment by yuantaoge** [comment]
我把创建的oracle数据源删了，再重新建一个，然后看sq执行这里还是无法正常显示
![2e1538ba7c6ea5790e1bc32ad59b2d7b1f331083b1e7c68488c97ff2314ded3fQzpcVXNlcnNcQWRtaW5pc3RyYXRvci5QQzgwMTA5MTAwMTBcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDExNDg3MzMzMDlfdjJcSW1hZ2VGaWxlc1wxNjQwODQyOTY1OTAyXzg0ODM5MzA5LTc4OTAtNDE5Yy1CNkMzLTJGMkM1MjczMEZERC5wbmc=](https://user-images.githubusercontent.com/59112182/147725157-c42fa6bc-2dd0-4075-ba61-6864c05fad65.png)
![66fd5a139fc00f5d4c14492718baf169b854b32ebed84a90e62c9f036a1cf3f5QzpcVXNlcnNcQWRtaW5pc3RyYXRvci5QQzgwMTA5MTAwMTBcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDExNDg3MzMzMDlfdjJcSW1hZ2VGaWxlc1wxNjQwODQzMTMzNTQ1XzM1RkQ4RDZFLTU3Q0QtNDdlMS04MjJBLUM2Mzc2QzJBRTkzMS5wbmc=](https://user-images.githubusercontent.com/59112182/147725163-77aca374-6cd9-44bd-a4f2-70ebe533a708.png)

**Comment by yuantaoge** [comment]
请问我是需要安装什么驱动还是哪里需要进行什么操作步骤？如果方便的话，请具体描述一下

**Comment by LYHHS** [comment]
您好，我也遇到同样的现象了，请问您最后怎么解决这个问题的

**Comment by yuantaoge** [comment]
> 您好，我也遇到同样的现象了，请问您最后怎么解决这个问题的

保证想要连接的数据库可以映射在公网上

**Comment by LYHHS** [comment]
谢谢，我已经解决了



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月5日(星期三) 下午3:07
***@***.***&gt;;
抄送:&nbsp;"Damon ***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 数据源连接问题 (Issue #750)





  
您好，我也遇到同样的现象了，请问您最后怎么解决这个问题的
  
保证想要连接的数据库可以映射在公网上
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
