### ISSUE TITLE
设置大屏websocket数据源不能与后台通讯

### ISSUE THREAD

**Issue by leewatt** [jeecgboot/JimuReport#751]
版本号：
积木官网 http://jimureport.com/bigScreen

问题描述：
1. 按积木手册http://report.jeecg.com/2306131集成后台代码
2. 将表格设置大屏websocket数据源：
ws://example.com/websocket/refreshChart
3. 打开预览，websocket没有触发后台OnOpen()，因此也不能继续测试交换数据
4. 通过下面HTML文件直接打开则可以与后台通讯

测试例子：
<!DOCTYPE html>  
<meta charset="utf-8" />  
<title>WebSocket Test</title>  
<script language="javascript"type="text/javascript">  
    var wsUri ="ws://example.com/websocket/refreshChart/{chartId}"; 

    var output;  
    
    function init() { 
        output = document.getElementById("output"); 
        testWebSocket(); 
    }  
 
    function testWebSocket() { 
        websocket = new WebSocket(wsUri); 
        websocket.onopen = function(evt) { 
            onOpen(evt) 
        }; 
        websocket.onclose = function(evt) { 
            onClose(evt) 
        }; 
        websocket.onmessage = function(evt) { 
            onMessage(evt) 
        }; 
        websocket.onerror = function(evt) { 
            onError(evt) 
        }; 
    }  
 
    function onOpen(evt) { 
        writeToScreen("CONNECTED"); 
        doSend("WebSocket rocks"); 
    }  
 
    function onClose(evt) { 
        writeToScreen("DISCONNECTED"); 
    }  
 
    function onMessage(evt) { 
        writeToScreen('<span style="color: blue;">RESPONSE: '+ evt.data+'</span>'); 
        websocket.close(); 
    }  
 
    function onError(evt) { 
        writeToScreen('<span style="color: red;">ERROR:</span> '+ evt.data); 
    }  
 
    function doSend(message) { 
        writeToScreen("SENT: " + message);  
        websocket.send(message); 
    }  
 
    function writeToScreen(message) { 
        var pre = document.createElement("p"); 
        pre.style.wordWrap = "break-word"; 
        pre.innerHTML = message; 
        output.appendChild(pre); 
    }  
 
    window.addEventListener("load", init, false);  
</script>  
<h2>WebSocket Test</h2>  
<div id="output"></div>  
</html>

**Comment by leewatt** [comment]
HTML粘贴不能正确显示，请https://www.xyhtml5.com/examples/2782.html改写接口地址

**Comment by lvdandan16** [comment]
收录 ldd
