### ISSUE TITLE
积木报表的打印尺寸无法自定义调整。

### ISSUE THREAD

**Issue by wfeng616** [jeecgboot/JimuReport#752]
##### 版本号：
v1.4.2

##### 问题描述：
在积木报表的视频介绍里面是可以拉动表格中的绿线来调整文档大小的，v1.4.2的版本好像不支持这个操作，只能通过”打印设置“来调整。但是”打印设置“只支持几种尺寸，我们想打印80mm*60mm的标签，没有找到这个尺寸。请问这个要如何处理？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/155847940-f6189fdf-904c-4d2a-a0a5-af3e5d490e03.png)

参考文档：http://report.jeecg.com/2141759
