### ISSUE TITLE
导出PDF后的条码没有显示下方的覆盖文字

### ISSUE THREAD

**Issue by AusonSir** [jeecgboot/JimuReport#754]
##### 版本号：
1.4.2

##### 问题描述：
导出的PDF中的条码没有显示下方的覆盖文字，预览中可以看见覆盖文字，确认是否显示文字按钮已打开

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/30992116/147716115-9c4e7461-ac8b-4832-9216-925a4ac1c3ef.png)
![image](https://user-images.githubusercontent.com/30992116/147716093-7b06450e-6390-4d48-90d5-b75fc3d6bf41.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
已修复，见下版本
