### ISSUE TITLE
对单元格混合使用条件函数、颜色函数时，报表切换分页报错

### ISSUE THREAD

**Issue by JackNieLi** [jeecgboot/JimuReport#758]
##### 版本号：
1.4.0、1.4.2

##### 问题描述：
对单元格混合使用条件函数、颜色函数时，报表切换分页条数报错

##### 错误日志&截图：
Syntax error: unexpect token '{', maybe forget to insert ';' to complete last expression at 38, lineNumber: 1, token : [type='Char',lexeme='{',index=38], while parsing expression: ` let name = '燃气配管部';nif(name == '房地产部'){^^^ `
![image](https://user-images.githubusercontent.com/97092021/148146162-99fb5865-2d4c-4209-be93-eb31590488df.png)

##### 重现步骤：
1、对某一单元格设置单元格表达式，如：
=(let name = '#{UTF8.sale_org_name}';
if(name == '房地产部'){color('房地产部','red','yellow')}
else{'#{UTF8.sale_org_name}'})
条件函数和颜色函数混合使用
2、预览报表，单元格颜色设定正常显示，当你切换分页时，会出现报错，比如从每页50条切换到每页100条

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
未测出，提到出报表配置我们测一下
