### ISSUE TITLE
换页时bug，打印预览，最后一页的换页时多了一行数据

### ISSUE THREAD

**Issue by quebecmcj** [jeecgboot/JimuReport#760]
##### 版本号：
jimureport： v1.40

##### 问题描述：
chrome浏览器，打印预览，最后一页的换页时多了一行数据。

##### 错误日志&截图：
![001](https://user-images.githubusercontent.com/55817534/148176363-b6b6cfef-cf85-41de-95ba-c0a8efd0c56e.png)
![002](https://user-images.githubusercontent.com/55817534/148176395-edfaa0fd-8008-44f0-b3fc-60a31213fa7a.png)

##### 重现步骤：
1.在列表下面加上显示项目ABCD,分2行，如图，在实际业务需求中，这2行显示项目应该和列表在一页里显示，不能让这2行显示 
  项目单独显示在一页里，因为这2行显示项目，需要签字盖章。
2.调整合适的列表高度，以便使显示项目ABCD正好处于换页边界
3.打印预览(html)，产生多一行数据的bug
4.已提供报表设计SQL脚本，见附件【[报表设计SQL脚本.zip】
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计SQL脚本.zip](https://github.com/jeecgboot/JimuReport/files/7812922/SQL.zip)](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请重新上传附件，附件无法下载

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
