### ISSUE TITLE
分页预览有效打印无效

### ISSUE THREAD

**Issue by zhangqikooo** [jeecgboot/JimuReport#762]
##### 问题描述：
分页打印为按预览的分页效果打印，而是打印所有的数据。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/54796342/148638858-5bcad737-e594-402b-8916-9e8bcb5d3226.png)
![image](https://user-images.githubusercontent.com/54796342/148638904-f43f705c-c285-44e9-a005-e82572728508.png)

##### 重现步骤：
1.分页API数据集合
2.预览
3.Canvas打印

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持分页打印
暂归集 #138

**Comment by Zoe-Zhu** [comment]
什么时候支持一下分页打印？
