### ISSUE TITLE
报表打印表头问题

### ISSUE THREAD

**Issue by fenggang110** [jeecgboot/JimuReport#767]
##### 错误日志&截图：
![FX}D35KDS$K(BJAK01N)JT6](https://user-images.githubusercontent.com/36908986/149131102-804dcb1f-dc4b-4b0a-b366-312d41ba10cb.png)

##### 重现步骤：
无

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持
归集 #138
