### ISSUE TITLE
springboot集成jimureport后预览时 com.alibaba.fastjson.JSONObject.clone()报java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by swy583** [jeecgboot/JimuReport#772]
##### 错误日志&截图：
![图片](https://user-images.githubusercontent.com/22882919/149511662-b9d10965-91ca-43b5-85c2-9d53c802a41f.png)
![图片](https://user-images.githubusercontent.com/22882919/149512209-ad1c2dc4-17a9-4175-b927-75c6dc3e2a83.png)
![图片](https://user-images.githubusercontent.com/22882919/149512285-9293e7c5-3d97-4d56-814a-f46ad9bd32b7.png)
![图片](https://user-images.githubusercontent.com/22882919/149512460-05e0bbd6-2f17-44e5-852c-42c5d9a9a1b4.png)
![图片](https://user-images.githubusercontent.com/22882919/149512552-350639ee-e078-49b0-bf43-ebdfab61c555.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by NapChen** [comment]
将fastjson升级到最新版本就可以了

**Comment by lvdandan16** [comment]
参考常见问题 31 http://report.jeecg.com/2087464#31140beta_JSON_213
