### ISSUE TITLE
impala数据源支持

### ISSUE THREAD

**Issue by qinjun5230** [jeecgboot/JimuReport#774]
##### 版本号：
v1.4.2

##### 问题描述：
请问有针对 impala的支持计划吗？如果有，大概什么时候可以支持啊？目前，我测试添加了 impala的jdbc驱动，添加数据源连接可以连上，但是没法解析sql，报无法自动获取数据源错误

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/7245473/149962615-f7ad6a56-d0c6-483e-9373-1a5d9b4c4b60.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持
归集到 #138
