### ISSUE TITLE
报表设计界面日期没有相应的格式化

### ISSUE THREAD

**Issue by LancCJ** [jeecgboot/JimuReport#775]
##### 版本号：
1.4.2

##### 问题描述：
报表设计界面日期没有相应的格式化

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/2968042/150081245-28bf96a9-7ee8-4541-8f4a-ebc9cd19c58b.png)

##### 重现步骤：
新建报表，直接选中单元格查看

**Comment by lvdandan16** [comment]
参考文档：使用nowstr http://report.jeecg.com/2332217#nowstr_78
