### ISSUE TITLE
报表数据填充问题

### ISSUE THREAD

**Issue by Sam-Tsui** [jeecgboot/JimuReport#776]
##### 版本号：
1.4.0

##### 问题描述：
报表模板的行数是固定的，前面几列的内容也是写死固定，因此数据填充是从中间的列开始，但是在循环列表数据填充时会出现显示问题。

##### 错误日志&截图：
报表模板图：
![111](https://user-images.githubusercontent.com/9668496/150112488-94ef7bd8-6425-40eb-a1f8-03f093bc4b90.png)
-----
预览截图：
![222](https://user-images.githubusercontent.com/9668496/150112536-fc15430f-e53e-41d1-87ec-7c1241398fd6.png)

![image](https://user-images.githubusercontent.com/9668496/150112912-d40f669b-243d-4fc6-b42f-9529393dd615.png)

##### 重现步骤：
如上。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
循环是整行循环
