### ISSUE TITLE
按key循环

### ISSUE THREAD

**Issue by 13071652014** [jeecgboot/JimuReport#778]
##### 版本号：
1.4.2

##### 问题描述：
希望能增加个 分组后按key循环的功能 , 有很多表格需要用到这个功能 .

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/56342460/150289967-ce24944b-13e6-4661-a1de-d79fd724ba0b.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 13071652014** [comment]
这个功能会出吗? 大概哪个版本后会出?

**Comment by lvdandan16** [comment]
暂不支持
收录 #138
