### ISSUE TITLE
报表查询接口的查询方式可以支持POST请求吗？

### ISSUE THREAD

**Issue by guilter** [jeecgboot/JimuReport#779]
##### 版本号：
1.4.2

##### 问题描述：
报表的查询接口的查询方式可以支持POST请求吗？
有时候参数会很多很长，用GET请求会导致URL过长。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/153812728-00db31d6-60e3-469e-977a-e9ba8e93b3a4.png)
可以x选择post方式
