### ISSUE TITLE
ApiDataConvertAdapter转换后 值为null字段的字段被清除

### ISSUE THREAD

**Issue by catlvsuger** [jeecgboot/JimuReport#783]
##### 问题描述：Api解析时，实现 ApiDataConvertAdapter 自定义转换，getData(JSONObject jsonObject) jsonObject里面字段值为null的字段被清除了，创建报表时获取到的字段缺少
![image](https://user-images.githubusercontent.com/39261781/150640282-59961e8a-8a55-41d4-9bdf-7ab44d8ea809.png)

public class MyDataConvertAdapter implements ApiDataConvertAdapter {
    @Override
    public String getData(JSONObject jsonObject)  {
        log.info(jsonObject.toJSONString());
        if(jsonObject.containsKey("result")){
            try {
                JSONArray pageList = jsonObject.getJSONObject("result").getJSONArray("records");
                return pageList.toJSONString();
            } catch (Exception e){
                log.info("contractParser 异常：{}",e.getMessage());
            }
        }
        return "";
   }
}

##### 错误日志&截图：
解析前：
![image](https://user-images.githubusercontent.com/39261781/150640315-a0ab0e12-de26-4d41-93ef-3b2d3129a505.png)
解析后：
![image](https://user-images.githubusercontent.com/39261781/150640333-48e00ed2-ee50-4c4c-bf12-0b065867ff4b.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
null字段的字段被清除,已修复，待新版本发布
