### ISSUE TITLE
Docker 部署后执行命令，生成镜像报错

### ISSUE THREAD

**Issue by licx506** [jeecgboot/JimuReport#788]
##### 版本号：
v1.4.2
##### 问题描述：
在执行 docker-compose up -d 后 最后一步报错

##### 错误日志&截图：
Building jimureport
Step 1/8 : FROM anapsix/alpine-java:8_server-jre_unlimited
 ---> 49d744fbb526
Step 2/8 : MAINTAINER jeecgos@163.com
 ---> Using cache
 ---> c7e228bc490c
Step 3/8 : RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
 ---> Using cache
 ---> e32fc62002f6
Step 4/8 : RUN mkdir -p /jimureport
 ---> Using cache
 ---> 3ab5f93a0227
Step 5/8 : WORKDIR /jimureport
 ---> Using cache
 ---> d4cf5150f3c7
Step 6/8 : EXPOSE 8085
 ---> Using cache
 ---> 019c953e2840
Step 7/8 : ADD ./target/jimureport-example-1.4.jar ./
ERROR: Service 'jimureport' failed to build: ADD failed: file not found in build context or excluded by .dockerignore: stat target/jimureport-example-1.4.jar: file does not exist

jimureport-example-1.4.jar路径：/home/user/JimuReport/jimureport-example/target/jimureport-example-1.4.2.jar
##### 重现步骤：
Docker全新部署
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
打包后是否生成了jimureport-example-1.4.2.jar

**Comment by licx506** [comment]
已经生成jimureport-example-1.4.2.jar，报错提示的是：/target/jimureport-example-1.4.jar   生成的文件是 jimureport-example-1.4.2.jar，不知道是不是这个原因。
