### ISSUE TITLE
开源方面的问题咨询

### ISSUE THREAD

**Issue by wzqiang1332** [jeecgboot/JimuReport#789]
##### 版本号：
1.4.2

##### 问题描述：

因为在调研报表工具，所以想问一个开源方面的问题，这个项目demo这一块是开源的，报表设计器没有开源。
如果我们想结合公司的情况在现在的基础上加一些功能做一些定制化的修改，比如跟其他系统的用户集成，增加报表访问权限管理，修改一些基础样式。
这些是否允许？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
报表访问权限可以做，参考文档即可。
样式可以通过增强来实现

**Comment by zhangxinyuan1** [comment]
对报表设计器进行权限管控，这块要如何做，看哪个文档？
