### ISSUE TITLE
增加行列时，使用单元格表达式的行列不能自动调整

### ISSUE THREAD

**Issue by wl3446100** [jeecgboot/JimuReport#790]
##### 版本号：
1.4.2

##### 问题描述：
模板设计好之后，后续如果对模板进行增加行列的调整，如果后面有单元格的取数是使用的单元格运算，会需要一个一个手工调整

##### 重现步骤：
![图片](https://user-images.githubusercontent.com/99460473/153534920-b9d26190-9c3f-43ae-a814-3ed49b17251c.png)
D列前插入一列
![图片](https://user-images.githubusercontent.com/99460473/153535015-00b32eeb-66d7-4e16-8bd9-f0a6cd50f9cb.png)
公式还是C10+D10，需要调整为C10+E10

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持
归集到 #138
