### ISSUE TITLE
右键无“插入”选项

### ISSUE THREAD

**Issue by YanYiZhang** [jeecgboot/JimuReport#792]
##### 版本号：

1.4.2免安装版
##### 问题描述：
报表设计器右键单元格、列、行均无“插入”选项显示

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/79391971/154178476-537ba54a-c257-4ed5-be4a-48c712122589.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
滚动条往下滑

**Comment by YanYiZhang** [comment]
<@_@>谢谢
