### ISSUE TITLE
配置多个数据集不起作用

### ISSUE THREAD

**Issue by 13192294603** [jeecgboot/JimuReport#794]
##### 版本号：
1.4.2

##### 问题描述：
多数据集配置问题

##### 错误日志&截图：
配置多个数据集  只显示了最后一个数据集的数据  官网实例看着只是废弃了一个旧的数据集从而用了个最新的数据集而已
如何做到同时使用两个数据集的数据
![image](https://user-images.githubusercontent.com/55734244/154232280-90d119b4-2a42-47de-8c54-454c57a83c07.png)
![image](https://user-images.githubusercontent.com/55734244/154232393-9d0588bc-6ab8-42dd-a45a-726cd14ba138.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 13192294603** [comment]
两个数据集里面的列表字段是一样的  默认只使用新建的那个数据集的数据
![image](https://user-images.githubusercontent.com/55734244/154396852-29fd97da-5a17-4e96-a8fe-6474903a9d8a.png)

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
不支持，属于配置错误示例
![image](https://user-images.githubusercontent.com/27989856/156717913-2b223666-d55e-4aab-a48b-a26a6b8e8225.png)
