### ISSUE TITLE
报表设计，上传Excel失败

### ISSUE THREAD

**Issue by zhouqibing** [jeecgboot/JimuReport#795]
##### 版本号：
1.4.2

##### 问题描述：
在设计页面，上传本地Excel失败，在官网上测试是可以的，调试发现返回JSON解析失败，本地返回数据key是数字类型，官网则是字符串

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/67934663/154650237-ce034c64-bff5-4876-b24a-afcbab3d139e.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
你本地是不是有json转换的东西，比如将返回的json传递过程中把双引号去掉了，你可以使用官网的demo项目测试看看有没有问题，我集成`1.4.2`未发现该问题
