### ISSUE TITLE
参数为多选，字典是sql生成的，最终生成的in字句中多值间没有引号

### ISSUE THREAD

**Issue by yujiangfan** [jeecgboot/JimuReport#797]
##### 版本号：
1.4.2

##### 问题描述：
多选参数，字典用的select语句，最终解析出来的select语句中的in（）里的内容没有引号，成了一个完整的字符串。

##### 错误日志&截图：
报表sql中的条件如下： ...and ie.campus_id in ('${campus}')...
参数设置如下：![image](https://user-images.githubusercontent.com/34936549/154879574-e3c463ca-292f-4cd3-bf5c-270e73c8a056.png)

最终后台生成的sql如下：
.... and ie.campus_id in ('QZ,2')....
应该为....and ie.campus_id in ('QZ',,'2')...才对
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by Wwwwwys** [comment]
使用freemarker的replace替换字符串
<#if isNotEmpty(xxxx)>
  and xxxx in ('${"${xxxx}"?replace(",","','")}')
</#if>

**Comment by Wwwwwys** [comment]
```
<#if isNotEmpty(XXX)>
  and XXX in ('${"${XXX}"?replace(",","','")}')
</#if>
```

**Comment by yujiangfan** [comment]
谢谢，我后台函数里改为符合这种不带引号的字符串了
