### ISSUE TITLE
api数据集报表 驼峰形式的字段查询无效

### ISSUE THREAD

**Issue by catlvsuger** [jeecgboot/JimuReport#799]
##### 问题描述：api数据集，驼峰形式的字段名变为全小写，根据小写字段去查询，对象匹配不到字段，查询request
请求参数均为小写
![image](https://user-images.githubusercontent.com/39261781/154921197-0add04c9-c604-4a91-b277-6fd3586b6d2c.png)
预览报表，查询不生效，如果将字段改为驼峰，报表该字段不显示数据

##### 处理方式：报表设计完成再修改字段为驼峰，这样报表中字段为全小写，查询请求为驼峰，查询生效，报表也有字段显示
![image](https://user-images.githubusercontent.com/39261781/154922369-74bb5e3a-0cb2-4a67-ae20-316207c6e79d.png)
![image](https://user-images.githubusercontent.com/39261781/154922192-e45fe7d6-debe-4fba-874a-2f1c9ce50447.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 1298191366** [comment]
已修复，待新版本发布

**Comment by timogal** [comment]
![image](https://user-images.githubusercontent.com/17402530/175493572-a020a7d2-bde3-4f5c-be2c-e520a265249f.png)
