### ISSUE TITLE
页面展示有数据，导出excel没数据，后台也没有报错

### ISSUE THREAD

**Issue by xiezuowen** [jeecgboot/JimuReport#802]
##### 版本号：

1.4.2
##### 问题描述：

页面展示有数据，导出excel没数据，后台也没有报错
##### 错误日志&截图：
页面展示：
![1](https://user-images.githubusercontent.com/100402582/155666216-25930606-006b-4b30-9b4d-8cd4dc98b53c.png)
导出excel:
![2](https://user-images.githubusercontent.com/100402582/155666266-54defc2c-314c-45d3-9da4-0ce611fb270d.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by xiezuowen** [comment]
问题描述：
经测试数据来源，由三个api输出，页面展示时三个接口都调用到，导出excel只调用了第一个接口，麻烦确认该逻辑是否正常

**Comment by lvdandan16** [comment]
导出报表配置及数据，我们看一下

**Comment by xiezuowen** [comment]
![微信图片_20220228093332](https://user-images.githubusercontent.com/100402582/155910274-6705647c-1f03-49ff-8b7a-cd39aa5fd5d9.png)
如图所示，三个api,导出excel时候只调用了第一个api,其他两个没有调用，你们可以测试多个api数据源导出试试

**Comment by xiezuowen** [comment]
后台没有报错，pdf导出也是正常的，确认下这个报表配置是否可用
[report-export-mysql (1).txt](https://github.com/jeecgboot/JimuReport/files/8174039/report-export-mysql.1.txt)

**Comment by 1298191366** [comment]
如果是分页导出的话，你看看是不是其他的在另外一个sheet中，分页导出会分sheet的

**Comment by xiezuowen** [comment]
我看了下，没有第二个sheet,我对比了三个api配置，就第一个api设置了分页，然后我把这个分页去掉就成功了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月3日(星期四) 上午10:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [jeecgboot/JimuReport] 页面展示有数据，导出excel没数据，后台也没有报错 (Issue #802)





 
如果是分页导出的话，你看看是不是其他的在另外一个sheet中，分页导出会分sheet的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1298191366** [comment]
已修复，待新版本发布，问题已重现
