### ISSUE TITLE
导出文件增加水印

### ISSUE THREAD

**Issue by mwq198810** [jeecgboot/JimuReport#803]
##### 版本号：
1.4.2

##### 问题描述：
业务保密需要
如何在标准的导出功能中做到 导出excel pdf 等文件 增加水印

##### 错误日志&截图：
无

##### 重现步骤：
物

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持 
#138

**Comment by mwq198810** [comment]
可以通过接口实现吗，或者开放接口给开发者扩展

**Comment by 1298191366** [comment]
导出excel和pdf下个版本支持
