### ISSUE TITLE
看了使用手册，自定义请求header只能写定值进去，而不能每个模板进行自定义？

### ISSUE THREAD

**Issue by Zoe-Zhu** [jeecgboot/JimuReport#806]
##### 版本号：
1.4.2

##### 问题描述：
看了使用手册，自定义请求header只能写定值进去，而不能每个模板进行自定义
##### 重现步骤：
![image](https://user-images.githubusercontent.com/22297885/156513632-abe2ba9e-6498-41eb-af9e-1f947c7564dc.png)
HeaderValue可否在模板生成时进行自定义？

**Comment by lvdandan16** [comment]
不支持

**Comment by Zoe-Zhu** [comment]
> 不支持

那请问有没有计划支持一下？
