### ISSUE TITLE
设置横向循环块，预览和导出时前面的表格会不显示，包括里面的内容。

### ISSUE THREAD

**Issue by zhpingzi** [jeecgboot/JimuReport#808]
##### 版本号：
1.4.2

##### 问题描述：
设置横向循环块，预览和导出时前面的表格会不显示，包括里面的内容。

##### 错误日志&截图：
循环块横向循环次数为5，
![1](https://user-images.githubusercontent.com/82299489/156552469-f720c46a-ccf0-4bd3-a5c8-3af531ecd94d.png)

预览时：
![2](https://user-images.githubusercontent.com/82299489/156552604-5dd4855c-293e-4c66-8d2c-670035c4dd51.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by zhpingzi** [comment]
好的，谢谢
