### ISSUE TITLE
关于查询框中下拉多选样式bug

### ISSUE THREAD

**Issue by yulang1124** [jeecgboot/JimuReport#809]
##### 版本号：
1.4.2

##### 问题描述：

底层数据使用oracle
制作了纵向合并的表，加了查询条件，为下拉多选样式，在报表预览就会直接报错。个人测试了打印的sql，去除截图中的 ‘；’符号，就可正常运行。

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/10266521/156710463-774aa478-f383-417a-9897-7f2f811b2e9f.png)
![image](https://user-images.githubusercontent.com/10266521/156710514-1c0594c1-2566-4526-8383-e8b60201d3e6.png)

##### 重现步骤：

使用Oracle自己可以造个单表数据，百分百出现。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
