### ISSUE TITLE
窗口的名称能否自定义

### ISSUE THREAD

**Issue by 13192294603** [jeecgboot/JimuReport#810]
##### 版本号：

1.4.2
##### 问题描述：
窗口的名称能否自定义

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/55734244/156736416-c1ea49d1-c681-4c34-8ad4-37afd167f785.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
