### ISSUE TITLE
设置图片为套打图片后，没法取消套打图片

### ISSUE THREAD

**Issue by lulusoft** [jeecgboot/JimuReport#812]
##### 版本号：
1.4.3

##### 问题描述：
设置图片为套打图片后，没法取消套打图片

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/3874472/156957494-27fb300c-c095-45ea-a155-6644f2f16689.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
线上做个例子，看看

**Comment by lulusoft** [comment]
原来版本点击右键的确有取消套打图片的功能，我使用过，但1.4.0开始好像就没有了，刚才找了视频也没有找到取消套打的

**Comment by zhangdaiscott** [comment]
鼠标往下滚动
