### ISSUE TITLE
导出pdf后，上传的图片都不呈现

### ISSUE THREAD

**Issue by lulusoft** [jeecgboot/JimuReport#813]
##### 版本号：
1.4.3

##### 问题描述：
1、在设置套打后，再上传一些图片，选择导出pdf，上传的图片都不呈现
2、在设置套打后，再上传一些图片和二维码，选择导出pdf图像，上传的图片、二维码都不呈现

##### 错误日志&截图：
问题1截图：
![image](https://user-images.githubusercontent.com/3874472/156959204-512206f1-ea13-42ed-9601-26998fc87548.png)
![image](https://user-images.githubusercontent.com/3874472/156959241-5fc3b960-0b6a-45ac-83ce-1316754d5cd8.png)
问题2截图：
![image](https://user-images.githubusercontent.com/3874472/156959535-b11be484-d549-49e1-8a90-134883a0155e.png)

##### 重现步骤：
1、在设置套打后，再上传一些图片，选择导出pdf，上传的图片都不呈现
2、在设置套打后，再上传一些图片和二维码，选择导出pdf图像，上传的图片、二维码都不呈现

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 1298191366** [comment]
未测出，请导出报表配置

**Comment by lvdandan16** [comment]
收录 ty

**Comment by 1298191366** [comment]
已修复，待新版本发布
