### ISSUE TITLE
升级到了1.4.3报表钻取参数无法传，原来版本是可以的

### ISSUE THREAD

**Issue by tsh0794** [jeecgboot/JimuReport#815]
##### 版本号：
1.43

##### 问题描述：
升级到了1.4.3报表钻取参数无法传，原来版本是可以的

##### 错误日志&截图：
![)ETZ@~50%(V{HG)$BNO@PB3](https://user-images.githubusercontent.com/89760691/156973026-170e0aed-3bc9-49ba-8357-c0458582d766.png)
后台信息：
![image](https://user-images.githubusercontent.com/89760691/156973125-91d47b25-64e0-41a3-962f-5a52e4b00b8e.png)

![image](https://user-images.githubusercontent.com/89760691/156973555-3ee54dcc-b351-47ad-966f-9e944193c009.png)

![)C)B05XCKFEI%)_6UMPRTL6](https://user-images.githubusercontent.com/89760691/156973575-0ee7512d-5a67-456f-b236-ff2435fef24c.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；
[report-export-mysql (1).txt](https://github.com/jeecgboot/JimuReport/files/8195265/report-export-mysql.1.txt)

**Comment by lvdandan16** [comment]
表结构及数据也上传一下

**Comment by 1298191366** [comment]
我用你的示例没有测出来，你钻取配置的是哪一个，我随便钻取了一个，看起来是有值的
![image](https://user-images.githubusercontent.com/30997828/157000832-e23f76e0-2bcd-4535-bd3d-7ff774b53fe9.png)

![image](https://user-images.githubusercontent.com/30997828/157000961-ab548a62-8fb8-45fa-a6e1-468238b5130e.png)
