### ISSUE TITLE
数据源选择oracle ，无法通过存储过程进行查询数据

### ISSUE THREAD

**Issue by keqinghong** [jeecgboot/JimuReport#816]
##### 版本号：
1.4.3 

##### 问题描述：
在建报表的 数据源配置为oracle时，使用《存储过程》功能无法正常拉取到数据，提示 ’sql解析失败，{}null‘，
1.我们分别用了oracle的存储函数和存储过程两种方式进行测试，均无法正常工作；而使用mysql的存储正常，截图如下，请问是我们使用的方式有问题，还是当前版本未支持oracle的存储过程。
2.使用sql 语句也能正常返回结果。

##### 错误日志&截图：
**1.oracle 的存储函数脚本。**
![image](https://user-images.githubusercontent.com/9244680/156976715-cc003f8d-b558-429e-b77d-49b031515148.png)

**2.oracle的存储过程脚本。**
![image](https://user-images.githubusercontent.com/9244680/156976902-ef4ecc5e-9af0-4bbb-bcdc-c07a5ffa9c3d.png)

**3.执行结果**
![image](https://user-images.githubusercontent.com/9244680/156977028-9c0ea1d9-195d-4687-b4ca-411b2f6cb569.png)

##### 重现步骤：

以上为使用oracle的存储过程遇到的问题，麻烦贵公司技术团队排查下是哪方面的问题，谢谢。联系方式 752498932@qq.com

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
文档地址：http://report.jeecg.com/2376611
