### ISSUE TITLE
通过默认sql数据源配置数据字典下拉条件只能显示10条

### ISSUE THREAD

**Issue by JohnnyKIT** [jeecgboot/JimuReport#817]
##### 版本号：
1.4.2

##### 问题描述：
配置在参数的字典code。 语句输出100多行，但是到报表预览界面，下拉菜单只有10个项目

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
默认只显示10条，可自定义配置显示条数，参考文档：http://report.jeecg.com/2373407
