### ISSUE TITLE
报表设计时未超出边界，但是HTML打印预览的时候会多一张纸

### ISSUE THREAD

**Issue by Huzhangs** [jeecgboot/JimuReport#819]
##### 错误日志&截图：
![WSMQ5(Q5 51VBY(~@8GD4`U](https://user-images.githubusercontent.com/41146743/156993757-d05abe2b-22ee-4d71-8e3a-a8df4f167e9c.png)
![{4(V9 EI9CLX}N~HLL% Z}5](https://user-images.githubusercontent.com/41146743/156993876-6f4ab07c-eda1-4328-ae19-2cafccec953f.png)
![image](https://user-images.githubusercontent.com/41146743/156994014-0c52f356-7370-48cc-8092-3742a6449445.png)

##### 重现步骤：
1.新建sql数据集
2.设计报表的过程中，用到清除数据和清除格式
3.HTML打印，预览的时候会多一张空白页

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by Huzhangs** [comment]
你好，请问下，收录ty是什么意思？

**Comment by tygithub1** [comment]
参考： https://gitee.com/jeecg/JimuReport/issues/I4W4WB#note_9063628_link
