### ISSUE TITLE
报表钻取没法选择数据集数据

### ISSUE THREAD

**Issue by nieguoxu** [jeecgboot/JimuReport#820]
##### 错误日志&截图：
<img width="1080" alt="6b0b334db8ab019cd20bc46b0f9793e" src="https://user-images.githubusercontent.com/67364475/157012213-fb25b1d0-10e7-4d7f-9ee7-1fbf3bc81b3f.png">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
先升级版本到最新
