### ISSUE TITLE
报表钻取时传参短的可以获取,长度长的获取不了

### ISSUE THREAD

**Issue by nieguoxu** [jeecgboot/JimuReport#823]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/67364475/157194677-55b055c5-87a9-4d4d-89ac-bc87a0d177ed.png)
![image](https://user-images.githubusercontent.com/67364475/157194580-a27c02e9-cb81-43de-b46e-2ebb57bdb23b.png)
![image](https://user-images.githubusercontent.com/67364475/157194786-efa3bfdf-0082-495d-b613-249cb31adc4c.png)
![image](https://user-images.githubusercontent.com/67364475/157194899-7e846d1c-6316-4111-9ede-30e8974bafc5.png)
![image](https://user-images.githubusercontent.com/67364475/157194982-1ed85685-e985-4199-b250-85383194dace.png)

##### 重现步骤：
弄两个报表进行钻取,传的参数一个长的一个端的    长的用逗号+单引号( ',' )分割

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
收录 ws

**Comment by 1298191366** [comment]
未测出，把你的配置和数据导出来一份，我们测试一下
![image](https://user-images.githubusercontent.com/30997828/158176197-648a028e-8435-4093-ba40-92d06c1db787.png)

**Comment by nieguoxu** [comment]
> 未测出，把你的配置和数据导出来一份，我们测试一下 ![图片](https://user-images.githubusercontent.com/30997828/158176197-648a028e-8435-4093-ba40-92d06c1db787.png)

已经找到原因了    是因为我数据源SQL列名我弄成中文的了    换成英文的就出来了

**Comment by 1298191366** [comment]
钻取字段名称不支持中文，`字段文本`可以填写字段名称

**Comment by nieguoxu** [comment]
好的
