### ISSUE TITLE
新版本没有循环块

### ISSUE THREAD

**Issue by hbldw521** [jeecgboot/JimuReport#824]
##### 版本号：
![screen_shot_1646791377524](https://user-images.githubusercontent.com/16379263/157358017-de27c46a-560f-42b4-a8b0-1ba3abf9988f.png)

##### 问题描述：
没有循环块的设定

##### 错误日志&截图：
![screen_shot_1646791552824](https://user-images.githubusercontent.com/16379263/157358349-723cab57-e5e2-4f96-97f6-30334836caee.png)

##### 重现步骤：
在一个表格的单元格中，要循环一个列表数据，看到明细报表的帮助手册中有写到循环块，但按照手册点击右键后没有循环块的选项

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
滚动鼠标下拉
