### ISSUE TITLE
JavaBean数据集无法分sheet导出

### ISSUE THREAD

**Issue by zhpingzi** [jeecgboot/JimuReport#825]
##### 版本号：
1.4.2

##### 问题描述：
配置文件中设置 page-size-number: 10，SQL数据集导出后可以分sheet，JavaBean数据集不管设置分页还是不分页，导出之后是一个sheet。

##### 错误日志&截图：

**SQL数据集：**
![1](https://user-images.githubusercontent.com/82299489/157382607-955037fd-d77c-485f-bc6c-e89e75caa0ad.png)
![2](https://user-images.githubusercontent.com/82299489/157382621-38551057-c4a7-4b91-b577-85f3eae30c4e.png)

**JavaBean数据集：**
![3](https://user-images.githubusercontent.com/82299489/157383100-68cdaccb-ccb3-4eef-81d4-fef1b5eb3864.png)
![4](https://user-images.githubusercontent.com/82299489/157383109-c691ecc1-835d-4b16-b86b-a569bc67538e.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
