### ISSUE TITLE
打印时字符串中的特殊字符正常显示，但是导出pdf时出现渲染缺失

### ISSUE THREAD

**Issue by Zoe-Zhu** [jeecgboot/JimuReport#830]
##### 版本号：
1.4.0

##### 问题描述：
打印时字符串中的特殊字符正常显示，但是导出pdf时出现渲染缺失

##### 错误日志&截图：
预览打印截图
![image](https://user-images.githubusercontent.com/22297885/157599161-c377fd07-e58d-45c0-b68d-34a4b3287e21.png)
导出pdf结果
![image](https://user-images.githubusercontent.com/22297885/157599222-321ada47-3e4d-4861-bea4-e4f84a6f145a.png)

##### 重现步骤：
特殊字符（泰语等）api数据集打印，pdf导出字符串缺失

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
导出pdf暂时不支持泰语一些特殊语言

**Comment by lvdandan16** [comment]
归集到 #138
