### ISSUE TITLE
低版本chrome浏览器，无法兼容积木报表

### ISSUE THREAD

**Issue by IsLiving** [jeecgboot/JimuReport#831]
##### 版本号：
1.4.2

##### 问题描述：
低版本chrome浏览器，无法打开积木报表（我使用的chrome39，因为项目的某些原因，不能升级浏览器），有没有什么办法可以解决这种兼容性问题？

##### 错误日志&截图：

![QQ图片20220311090705](https://user-images.githubusercontent.com/38464696/157782412-b2987648-40ca-4b8d-81ab-12087eb50e3c.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
无计划支持
