### ISSUE TITLE
若依分离集成积木报表版本报错

### ISSUE THREAD

**Issue by angelina0311** [jeecgboot/JimuReport#832]
##### 问题描述
若依分离版本集成积木报表报错，

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/101538902/158103421-a4d90349-0d50-40e1-9287-90dce194423e.png)
![image](https://user-images.githubusercontent.com/101538902/158103609-7239d724-14c1-4659-b7e1-1e6284780e14.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请参考常见问题21：http://report.jeecg.com/2087464#21_mongodb_171

**Comment by zhangdaiscott** [comment]
做了自动化处理，请升级到1.4.4-beta看是否解决问题（[需要配置jeecg的maven私服](http://report.jeecg.com/2195924)）


```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.4.4-beta</version>
</dependency>
```
