### ISSUE TITLE
组合动态分组功能单元格位置对应不正确

### ISSUE THREAD

**Issue by 1226689046** [jeecgboot/JimuReport#833]
##### 版本号：
1.4.32

##### 问题描述：
组合动态分组功能出现单元格位置对应不正确的问题

##### 错误日志&截图：
1. json数据源，“东北”只有”1月“和”2月“的数据，预览的报表显示正常
![image](https://user-images.githubusercontent.com/26176405/158116767-e396c64f-9539-4451-8df1-53333c49406b.png)
![image](https://user-images.githubusercontent.com/26176405/158116887-8dffbe6e-7219-4c77-9ee7-f6b60c82253e.png)
2.当”东北“只有”2月“和”3月“的数据的时候，会把数据显示到”1月“和”2月“内
![image](https://user-images.githubusercontent.com/26176405/158116982-ed4c4936-d84f-48e7-b85d-f35b8e6e6e93.png)
![image](https://user-images.githubusercontent.com/26176405/158117004-37832578-ec5a-4002-ae5b-ec42caa05c92.png)

##### 重现步骤：
见上方【错误日志和截图】

#### 友情提示（为了提高issue处理效率）：
- 官网报表id: 663234185045299200

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/158302394-f083f9f9-0576-4b4e-a2e0-cc52f1807e64.png)

参考文档说明：http://report.jeecg.com/2119057

**Comment by Zeno118** [comment]
这个办法优化，不需要第一条都有数据吗？ 现在很多报表很难保证第一条都有数据
