### ISSUE TITLE
关于customGroup分组问题

### ISSUE THREAD

**Issue by xiezuowen** [jeecgboot/JimuReport#836]
##### 版本号：
1.4.2

##### 问题描述：
两个api返回的数据展示，通过customGroup分组展示有问题，后台没有报错

##### 错误日志&截图：
1.
![lQLPDhs88j1HHGfNAnzNBROwVHfMeQiIWZMCNIcMToANAA_1299_636](https://user-images.githubusercontent.com/100402582/158311550-f198b08e-8854-4791-907b-82578062d23b.png)
2.
![lQLPDhs88mZnqfTNASjNBPewpa0bUZ9WJPICNIdPccA1AA_1271_296](https://user-images.githubusercontent.com/100402582/158311582-89f89155-b3d0-4030-8fd3-045a700dc7a2.png)
3.
![lQLPDhs88ooq9CnNARnNA_uwcha4o63czeYCNIeKjIA3AA_1019_281](https://user-images.githubusercontent.com/100402582/158311602-7dbb242c-e485-4156-8b09-f7ee6a875cdd.png)
4.
![lQLPDhs88qWV-uDNASDNA9-w_sBb9NutUMoCNIe2_oANAA_991_288](https://user-images.githubusercontent.com/100402582/158311621-9032f5e8-5770-4f05-828b-8ff454c29ab8.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
已修复见下个版本
