### ISSUE TITLE
是否能够支持自定义数据源来源呢？

### ISSUE THREAD

**Issue by mattmok** [jeecgboot/JimuReport#838]
##### 版本号：
1.4.32

##### 问题描述：
因业务需求，我们需要统一管理数据源，而不是仅仅在积木报表中添加数据源，我们同样需要在线代码生成中添加数据源，因此我们想通过重写IJmReportDbSourceService实现来完成该功能，但是因JmreportDynamicDataSourceVo被混肴，导致原来的程序无法通过编译。

是否能够不混肴org.jeecg.modules.jmreport.dyndb.a.a（该类原名JmreportDynamicDataSourceVo）？

第一，它仅是个java bean。
第二，在dyndb包下面有同名的a类存在。
第二，包名与类名一致，导致冲突。

##### 错误日志&截图：
import org.jeecg.modules.jmreport.dyndb.a.a; 编译时会报找不到符号。
![image](https://user-images.githubusercontent.com/28980774/158554912-093fbe77-0aaa-48c4-8f67-adfe8b2a28f2.png)
包和类名一样存在冲突

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持

**Comment by zhangdaiscott** [comment]
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.4.4-beta</version>
</dependency>
```
