### ISSUE TITLE
报表表格列过多的时候在保存之后再次打开找不到后面的列了

### ISSUE THREAD

**Issue by nieguoxu** [jeecgboot/JimuReport#839]
##### 问题描述：
报表表格列过多的时候在保存之后再次打开找不到后面的列了

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/67364475/158560655-c62db9af-7f60-4ca6-9eb4-44df809d8f4a.png)
![image](https://user-images.githubusercontent.com/67364475/158560766-347070d2-0de2-4ee2-a00c-6c5a9f988d6e.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
设计页面列是固定的，参考配置：http://report.jeecg.com/2087464
