### ISSUE TITLE
1.4.32 sum 计算错误

### ISSUE THREAD

**Issue by bj-wangxing** [jeecgboot/JimuReport#840]
##### 问题描述：sum计算错误
请问是一张报表中无法指定这样多个列的分段计算吗？

##### 错误日志&截图：
![1647429320(1)](https://user-images.githubusercontent.com/45442343/158577991-5299e5f0-e495-4976-a4b5-51109d761a97.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by tygithub1** [comment]
确实不支持，下面的数据集如果没有分页的话可以使用 dbsum
![image](https://user-images.githubusercontent.com/27989856/158975303-f0c3abdc-bb61-49ff-b6e4-3235922d1c66.png)

**Comment by lvdandan16** [comment]
归集到 #138
