### ISSUE TITLE
计划在哪个版本移除对druid的依赖呢？

### ISSUE THREAD

**Issue by mattmok** [jeecgboot/JimuReport#841]
##### 版本号：
1.4.32

##### 问题描述：

JmreportDynamicDbUtil 过时的 DruidDataSource 依赖计划在哪个版本中移除呢？

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/28980774/158719804-6df7046e-7e5a-4f31-9b9a-f40bc8eae03c.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂未计划
