### ISSUE TITLE
积木报表项目部署到k8s后无法上传excel了

### ISSUE THREAD

**Issue by dabaohong** [jeecgboot/JimuReport#845]
##### 问题描述：
积木报表项目部署到k8s后无法上传excel了，配置如下
![image](https://user-images.githubusercontent.com/101400093/158753748-7e65f0d6-3165-44ad-8f28-f8d84283a908.png)

##### 错误日志&截图：
点击上传excel后，再打击打开，无任何效果
![image](https://user-images.githubusercontent.com/101400093/158753897-f5333c69-ba6e-4c39-9738-b1f216045c27.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
本地可以吗？

**Comment by zhangdaiscott** [comment]
看看是不是类似问题，静态资源扫描配置问题
https://github.com/jeecgboot/JimuReport/issues/847

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
