### ISSUE TITLE
导入图片设置大小后，导出EXCEL无效

### ISSUE THREAD

**Issue by tennisdd** [jeecgboot/JimuReport#846]
##### 版本号：
1.4.32

##### 问题描述：
导入图片设置大小后，导出EXCEL样式无效，预览可以时大小正常，导出EXCEL后，图片就平铺单元格了

##### 错误日志&截图：
![微信截图_20220317175110](https://user-images.githubusercontent.com/67934663/158785123-d43aaf57-edd3-42fd-822c-1e0eafd625d1.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
ws

**Comment by lvdandan16** [comment]
暂不支持
归集到：#138
