### ISSUE TITLE
若依微服务,本地localhost正常显示,运行在linux上浏览器报错不显示

### ISSUE THREAD

**Issue by Acechengui** [jeecgboot/JimuReport#847]
##### 版本号：
1.4.3

##### 问题描述：
若依微服务集成积木报表,本地localhost正常显示,运行在linux上浏览器报错不显示
已检查过linux配置文件内容与本地配置一模一样，使用的nacos

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/63096199/158918189-3c5b7148-5e37-4e76-b3c9-b36845061f6f.png)

##### 重现步骤：
若依微服务，新建子模块，引入相应依赖，配置访问路径，启动访问积木报表

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Acechengui** [comment]
回退版本至1.4.2 ,linux访问才恢复正常

**Comment by zhangdaiscott** [comment]
清空缓存了吗

**Comment by Acechengui** [comment]
清空过的，甚至重启了服务器

**Comment by lvdandan16** [comment]
收录 ty

**Comment by zhangdaiscott** [comment]
你这个应该是静态资源加载有问题，看看是不是gateway没有加  /jimureport/资源

**Comment by zhangdaiscott** [comment]
或者

升级到1.4.4-beta看是否解决问题（[需要配置jeecg的maven私服](http://report.jeecg.com/2195924)）


```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.4.4-beta</version>
</dependency>
```
