### ISSUE TITLE
最新版本内网无法使用

### ISSUE THREAD

**Issue by caijinhuang** [jeecgboot/JimuReport#849]
##### 版本号：
1.4.2

##### 问题描述：
最新版本内网访问**[https://hm.baidu.com**报错，无法正常使用，如何解决](https://hm.baidu.xn--com%2A%2A%2C%2C-sy1r6qy8wxt5ai0pjxrmwn8pzotgy42c6k9fy47b/)

##### 错误日志&截图：
无法正常访问

##### 重现步骤：
无法正常访问

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
截图看效果

**Comment by programmingdog** [comment]
![微信图片_20220322145412](https://user-images.githubusercontent.com/8090725/159424580-fd29f2db-e302-4a58-81bc-67c807c70beb.png)

版主，我们也遇到这个问题了，如图。

**Comment by zhangdaiscott** [comment]
访问的那个请求，有什么影响，录个视频

**Comment by caiiansheng** [comment]
如果外网网络不好的话，加载好长时间才能出来
