### ISSUE TITLE
docker安装启动时报错

### ISSUE THREAD

**Issue by Myshiner** [jeecgboot/JimuReport#850]
##### 版本号：
最新

##### 问题描述：
docker-compose up -d时报错

##### 错误日志&截图：
 ⠿ jimureport-mysql Error                                                                                                                                             7.4s
 ⠿ jimureport Error                                                                                                                                                   6.3s
Sending build context to Docker daemon  93.69MB
Step 1/8 : FROM anapsix/alpine-java:8_server-jre_unlimited
8_server-jre_unlimited: Pulling from anapsix/alpine-java
169185f82c45: Pull complete 
4346af5b5a4f: Pull complete 
Digest: sha256:d97f12170501e5faea7f86f9a9205d05f5cadcf7fb34fb53c3a7cef893e9cdd9
Status: Downloaded newer image for anapsix/alpine-java:8_server-jre_unlimited
 ---> 49d744fbb526
Step 2/8 : MAINTAINER jeecgos@163.com
 ---> Running in 9a8beed1f579
Removing intermediate container 9a8beed1f579
 ---> 56736c44ec46
Step 3/8 : RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
 ---> Running in 93a4e717a63b
Removing intermediate container 93a4e717a63b
 ---> bff10bb89d09
Step 4/8 : RUN mkdir -p /jimureport
 ---> Running in 252b0276a2e1
Removing intermediate container 252b0276a2e1
 ---> dfcba01b169a
Step 5/8 : WORKDIR /jimureport
 ---> Running in 8df412672904
Removing intermediate container 8df412672904
 ---> d5dd00e0953a
Step 6/8 : EXPOSE 8085
 ---> Running in d2dc301dc024
Removing intermediate container d2dc301dc024
 ---> a728f78a763e
Step 7/8 : ADD ./target/jimureport-example-1.4.jar ./
Sending build context to Docker daemon  664.4kB
Step 1/5 : FROM mysql:8.0.19
**2 errors occurred:
        * Status: ADD failed: file not found in build context or excluded by .dockerignore: stat target/jimureport-example-1.4.jar: file does not exist, Code: 1
        * Status: Get "https://registry-1.docker.io/v2/": net/http: TLS handshake timeout, Code: 1**

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
修复好了
