### ISSUE TITLE
点“预览”图标的时候报错

### ISSUE THREAD

**Issue by Myshiner** [jeecgboot/JimuReport#851]
##### 版本号：
最新GA版

##### 问题描述：
保存后点“预览”图标的时候报错了，如截图
但是数据预览的时候没问题的
![image](https://user-images.githubusercontent.com/48242833/159427927-1043b860-31b4-44ae-9103-0073a316ab57.png)

##### 错误日志&截图：
![O}$S8X{ZWL08$Y{S9X6`##### 版本号：
最新GA版

##### 错误日志&截图：
G](https://user-images.githubusercontent.com/48242833/159427711-7ec861e8-d6ca-4963-b024-bd2fe61fe7f9.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
图片有问题

**Comment by Myshiner** [comment]
报错就是Syntax error: invalid token at 2, lineNumber: 1, token : [type='Char',lexeme='=',index=0], while parsing expression: `=》^^^`，看起来像是返回值中有特殊字符，总共38列，我测试了一下把有一个字段(下面sql的sr.mark字段)去掉就OK了，但是在navicate等客户端没问题
SQL如下：
select
so.order_id,
so.alipay_order,
so.pay_amount,
so.pay_postage,
so.pay_points,
so.pay_total,
so.rebate_points,
so.act_pay_amount,
so.act_pay_points,
so.state,
so.order_create_at,
so.order_pay_at,
so.item_name,
so.item_count,
so.shop_name,
so.seg_info,
so.principle_recharge,
so.profit_recharge,
so.principle_pay,
so.profit_pay,
so.refund,
so.deliv_time,
sr.return_time,
sr.act_return,
sr.needs_return,
sr.return_req_time,
case sr.business when "售中退款" then "售中" when "售后退款" then "售后" else "unknown" end as business,
**sr.mark,**
af.fid,
af.created_at,
af.income,
af.outcome,
af.trade_type,
af.detail,
"收款差异" as "差异类型",
op.diff_a as "收款差异情况",
op.diff_b as "退款差异情况",
op.mark as "差异原因备注"
from order_pool as op force index(idx_dtm)
join shop_order as so on so.order_id = op.order_id
join shop_return as sr on sr.order_id = so.order_id
join alipay_rec as af on af.base_order = sr.order_id
where op.order_create_at >= '2022-01-01' and op.order_create_at < '2022-02-01'
and op.settle_status = 1;

**Comment by lvdandan16** [comment]
sr.mark 数据中有什么特殊字符？

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此任务
