### ISSUE TITLE
在报表里写的条件判断有问题

### ISSUE THREAD

**Issue by shenbushou** [jeecgboot/JimuReport#854]
##### 版本号：
1.38beat

##### 问题描述：
在报表i里填写的判断条件如下，当字段值>85时，显示红色字体：
=(let rate= '#{tJgcp.rate}'; 
let overa = (rate >= '85');
if(overa){
   return  color('#{tJgcp.rate}','red','yellow');
}else{
   return rate;
})
但是值为9时，也显示成红色了。
##### 错误日志&截图：
<img width="315" alt="1648025627421_F8FC3A1B-011B-4c10-BFDA-21FE1C112233" src="https://user-images.githubusercontent.com/64524981/159661455-b5b5c9d9-86c3-4a54-b79b-75241de529bf.png">

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by shenbushou** [comment]
对了，我暂时升级不了，一升级好多问题

**Comment by zhangdaiscott** [comment]
不升级，我们也无法处理
