### ISSUE TITLE
在报表里填写的判断条件的bug

### ISSUE THREAD

**Issue by shenbushou** [jeecgboot/JimuReport#855]
版本号：
1.38beat

问题描述：
在报表i里填写的判断条件如下，当字段值>85时，显示红色字体：
=(let rate= '#{tJgcp.rate}';
let overa = (rate >= '85');
if(overa){
return color('#{tJgcp.rate}','red','yellow');
}else{
return rate;
})
但是值为9时，也显示成红色了。

这应该是个常见的bug，升级是否能解决？或者过去已经被解决？

错误日志&截图：
<img width="315" alt="1648025627421_F8FC3A1B-011B-4c10-BFDA-21FE1C112233" src="https://user-images.githubusercontent.com/64524981/159867270-bf433ff0-00ed-4d5b-bcf8-4f980ba21ac6.png">

**Comment by lvdandan16** [comment]
设计页面怎么配置的?

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此任务
