### ISSUE TITLE
分组预览中文排序混乱

### ISSUE THREAD

**Issue by LayPotato** [jeecgboot/JimuReport#856]
##### 版本号：

1.4.0-beta
##### 问题描述：

分组预览中文排序混乱
##### 错误日志&截图：

<img width="701" alt="image" src="https://user-images.githubusercontent.com/31718093/159890669-f3058b25-0d4e-42f2-8465-ed67c8edd8f1.png">

##### 重现步骤：
字段是中文，分组设置，纵向，正序。此问题在官方提供的文档-快速入门-2.SQL数据源报表制作同样存在

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
不支持
