### ISSUE TITLE
自定义Token传递，接口端获取到的token没有变化，还是url中的token值

### ISSUE THREAD

**Issue by xedcoing** [jeecgboot/JimuReport#857]
##### 版本号：
1.4.3

##### 问题描述：
自定义Token传递，接口端的header参数名仍然是"token"，而不是自定义的key

##### 重现步骤：
`@Slf4j
@Component
public class JimuReportTokenService implements JmReportTokenServiceI {
	@Autowired
	@Lazy
	private RedisUtil redisUtil;

	@Override
	public String getToken(HttpServletRequest request) {
		return SecureUtil.getToken(WebUtil.getRequest());
	}

	@Override
	public String getUsername(String token) {
		return SecureUtil.getUser().getUserName();
	}

	@Override
	public Boolean verifyToken(String token) {
		return true;
	}

	@Override
	public Map<String, Object> getUserInfo(String token) {
		BladeUser bladeUser = SecureUtil.getUser();
		Map<String, Object> map = new HashMap<String, Object>();
		if (bladeUser == null) {
			log.error("获取用户信息为空");
			return map;
		}

		//设置账号名
		map.put(SYS_USER_CODE, bladeUser.getUserId());
		//设置部门编码
		map.put(SYS_ORG_CODE, bladeUser.getDeptId());
		// 将所有信息存放至map 解析sql/api会根据map的键值解析
		return map;
	}

	@Override
	public HttpHeaders customApiHeader() {
		String token = SecureUtil.getToken(WebUtil.getRequest());

		HttpHeaders httpHeaders = new HttpHeaders();
		httpHeaders.add(TokenConstant.HEADER, token);
		return null;
	}
}`

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
你那接收hearder咋写的，我测试可以用，注意：只有api数据源的时候有效。
![image](https://user-images.githubusercontent.com/30997828/160559218-6ce50b03-c3ee-4d1c-b64b-796a0666b797.png)
![image](https://user-images.githubusercontent.com/30997828/160559250-c013f134-e66e-4728-af5f-a0ce55e7ce20.png)
![image](https://user-images.githubusercontent.com/30997828/160559278-83e2c0dc-398f-4bd3-8aa2-892ede980bf4.png)
而且你写的代码自定义hearder为啥`return null`
![image](https://user-images.githubusercontent.com/30997828/160559443-eb4f0a4a-725d-4d40-b63a-4eb3a7d40d81.png)

**Comment by xedcoing** [comment]
不好意思，是我疏忽了返回了null值， sorry， 感谢大佬
