### ISSUE TITLE
导出PDF支持展示页码和总页数？

### ISSUE THREAD

**Issue by Zoe-Zhu** [jeecgboot/JimuReport#858]
##### 版本号：
1.4.4-beta

##### 问题描述：
导出PDF没有页码和总页数

##### 错误日志&截图：
暂无

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持
归集到 #138

**Comment by 1298191366** [comment]
下个版本支持页码和总页数
