### ISSUE TITLE
打印时是否支持删除每页的时间戳以及每页下面的url?仅保留页码就行

### ISSUE THREAD

**Issue by Zoe-Zhu** [jeecgboot/JimuReport#860]
##### 版本号：
1.4.4-beta

##### 问题描述：
打印时是否支持删除每页的时间戳以及每页下面的url?仅保留页码就行

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/22297885/160088876-a58107b1-a427-4c2a-80d9-33bf3b7f1b0f.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持
归集到：#138
