### ISSUE TITLE
积木报表查询条件问题

### ISSUE THREAD

**Issue by savage-c** [jeecgboot/JimuReport#865]
##### 问题截图：
如图，当选择自定义时，显示两个选择时间的输入框
![image](https://user-images.githubusercontent.com/58260909/160315059-a148006b-8886-4b8c-8c7a-69d7783c24f3.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
