### ISSUE TITLE
紧急BUG 1.4.4 单选下拉问题

### ISSUE THREAD

**Issue by c626210053** [jeecgboot/JimuReport#866]
##### 版本号：

1.4.4
##### 问题描述：
下拉单选筛选   取的字典管理的名称 没有取字典管理的数值

##### 错误日志&截图：
![SDM@KDKWNWR)ICN(UHAG7_D](https://user-images.githubusercontent.com/59947333/160318224-3c33e2c7-6b8a-40ee-a03a-6a756b23aebe.png)
![H (6_UK8XQ(HA{9BRB Y_~2](https://user-images.githubusercontent.com/59947333/160318243-2bc3ac10-5b3f-4a72-93f7-099494ae61ab.png)

##### 重现步骤：
新增的字典管理配置   设置下拉选择  取值取得改字段的名称查询 不是数值进行查询

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
