### ISSUE TITLE
快速集成

### ISSUE THREAD

**Issue by 1198735966** [jeecgboot/JimuReport#867]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/77771538/160318988-3167bfe4-206d-4ef9-aa08-104ef04bb6f0.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
什么环境，如何重现

**Comment by zhangdaiscott** [comment]
ws

**Comment by fhfengzhiyong** [comment]
版本号：1.4.4-beta
集成 [ruoyi-vue-pro](https://gitee.com/zhijiantianya/ruoyi-vue-pro) 会出现上述问题

**Comment by fhfengzhiyong** [comment]
fastjson ->1.2.78
<dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>fastjson</artifactId>
                <version>1.2.78</version>
</dependency>

**Comment by 1298191366** [comment]
集成ruoyi-vue-pro和ruoyi-vue分离版新下载的未发现该问题，需要自行排查哪里出现的问题，你可试一下楼上将fastjson版本改成1.2.78试一下
![image](https://user-images.githubusercontent.com/30997828/160602368-52d6de42-8132-4394-97b2-af860c5dc8fd.png)
![image](https://user-images.githubusercontent.com/30997828/160602754-ae095320-74d9-43e4-a1db-ddbc06eb1b0e.png)
