### ISSUE TITLE
积木报表能否在发布后，还可以修改某些单元格的值

### ISSUE THREAD

**Issue by liangwei2012** [jeecgboot/JimuReport#869]
##### 版本号：
1.4.32

##### 问题描述：
有些报表数据不完善，用户需要补充一些数据再进行打印，但是目前报表好像并不支持发布后，再次修改。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
无计划支持
