### ISSUE TITLE
点击保存，提示：保存失败！

### ISSUE THREAD

**Issue by JustSmile-sys** [jeecgboot/JimuReport#871]
##### 错误日志&截图：
![{U ZV 8CIX`CRW$QA07WWJL](https://user-images.githubusercontent.com/81727213/160551427-2b4be9b8-6e58-4a19-9b68-e25ab7fb7706.png)

##### 重现步骤：

https://user-images.githubusercontent.com/81727213/160551451-b777cf45-f754-4f22-8613-c4af651b72c4.mp4

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级最新版本试一下

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此任务
