### ISSUE TITLE
是否支持调用指定的云打印设备进行打印？

### ISSUE THREAD

**Issue by XB-Paul** [jeecgboot/JimuReport#874]
版本号：1.4.3

问题描述：【打印】是否支持调用指定的云打印设备进行打印？
打印报表数据生成之后，是会有临时文件产生吗？ 若存在此临时文件，我是否可以去调用云打印设备？
（云打印设备是可以直接打印文件的）

**Comment by lvdandan16** [comment]
没有临时文件，不支持云打印
