### ISSUE TITLE
本地离线积木报表插入图片或设置背景不显示

### ISSUE THREAD

**Issue by jiaccool** [jeecgboot/JimuReport#875]
##### 版本号：
集成到jeecg的积木报表已升至最新版1.4.4-beta版

##### 问题描述：
集成到jeecg的离线积木报表插入图片或设置背景不显示

##### 错误日志&截图：
![图片](https://user-images.githubusercontent.com/18107764/160794870-685b7ce1-795e-400e-bde9-522327e71b50.png)

##### 重现步骤：
新建报表-插入图片，插入图片后不显示，或者右键空白处，选择背景图设置，上传背景图后，背景图也不显示。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
已修复，下个版本升级
