### ISSUE TITLE
积木报表-我的大屏-大屏设置-编辑-修改保护密码提示“您没有权限”

### ISSUE THREAD

**Issue by HNyyj** [jeecgboot/JimuReport#876]
##### 错误日志&截图：
![1648718066(1)](https://user-images.githubusercontent.com/45708084/161021157-7ccf52e4-7f46-4666-bd9d-0b22bbd93b3e.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
目前测试没有发现您说的提示错误，您现在能重现这个问题吗？

**Comment by lsqGitHub716** [comment]
目前测试没有发现您说的提示错误，您现在能重现这个问题吗？

**Comment by HNyyj** [comment]
估计是密码超过限制位数
![image](https://user-images.githubusercontent.com/45708084/175240166-aaea64ba-10c7-469d-9ca3-3ea1931a27c7.png)

**Comment by lsqGitHub716** [comment]
已修改，下版本发布

**Comment by HNyyj** [comment]
1
