### ISSUE TITLE
 若依 vue 前后端分离版本 设置背景图片 资源访问不到 401

### ISSUE THREAD

**Issue by allenlu1990** [jeecgboot/JimuReport#877]
##### 版本号：
1.4.4-beta

##### 问题描述：

 若依 vue 前后端分离版本 设置背景图片 资源访问不到 401
##### 错误日志&截图：
认证失败无法访问系统资源， code：401

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
已修复，下个版本升级
