### ISSUE TITLE
使用passthru('start D:\phpstudy_pro\WWW\blog\jimureport-quickstart-1.4.3\start.bat');命令打开后报错如图：

### ISSUE THREAD

**Issue by JustSmile-sys** [jeecgboot/JimuReport#879]
##### 版本号：
jimureport-quickstart-1.4.3

##### 问题描述：
使用passthru('start D:\phpstudy_pro\WWW\blog\jimureport-quickstart-1.4.3\start.bat');命令打开后报错如图：

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/81727213/161203149-ed0caab9-b163-4efc-98b9-da241c6d8411.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
怎么操作的，详细描述一下

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此任务
