### ISSUE TITLE
带有条件筛选的报表模板案例预览时报错

### ISSUE THREAD

**Issue by 2781838262** [jeecgboot/JimuReport#880]
##### 版本号：
1.4.4-beta

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/62685744/161205840-77dfeff2-8956-4e57-a7ef-e87c52621528.png)
![image](https://user-images.githubusercontent.com/62685744/161205880-6bdcaa29-0981-40f0-896d-d0ebad0ea9d3.png)
![image](https://user-images.githubusercontent.com/62685744/161205975-2b26f7d8-1d2f-4163-84ba-59deed840ac5.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
执行sql：http://report.jeecg.com/2722501
