### ISSUE TITLE
边框缺失

### ISSUE THREAD

**Issue by XiaoYu6666** [jeecgboot/JimuReport#883]
##### 问题描述：
![image](https://user-images.githubusercontent.com/100992892/161212525-806d52da-baf8-4ae4-b17d-0ff1e28e0b71.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
手动再设置一次边框，看看效果

**Comment by XiaoYu6666** [comment]
那这个预览页面，是在数据库中存着吗？在哪存着的？哪个表？
![image](https://user-images.githubusercontent.com/100992892/161582096-7d8c32ef-e20e-4a55-959e-908052deca54.png)

**Comment by lvdandan16** [comment]
预览页面是根据设计界面直接展示的，没有单独存表
