### ISSUE TITLE
国产化支持程度

### ISSUE THREAD

**Issue by chaochaohao** [jeecgboot/JimuReport#885]
##### 问题描述：
目前我们支持哪些国产化操作系统，支持哪些国产化中间件。

##### 错误日志&截图：
无

##### 重现步骤：
无。

**Comment by lvdandan16** [comment]
不支持

**Comment by lvdandan16** [comment]
收录 ty

**Comment by tygithub1** [comment]
同学，在学java的第一天，老师就告诉我们，java的特性之一：跨平台，所以如果有一天你开发了一个操作系统，根本不用担心这个报表的集成问题。
