### ISSUE TITLE
页眉页脚修改不了

### ISSUE THREAD

**Issue by yufe000** [jeecgboot/JimuReport#886]
##### 问题描述：
如何自定义页眉页脚，想显示打印页数，格式不能自定义，打印报表的时候需要知道是那一页啊，默认的页眉页脚修改不了。

##### 重现步骤：
打印预览的时候  ，勾选页眉页脚 

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持
归集到 #138

**Comment by yufe000** [comment]
这是来自QQ邮箱的自动回复邮件。
       您好，我已收到你的邮件，我将尽快回复您!
                                                   自由的风
