### ISSUE TITLE
地图不能设置区域地图

### ISSUE THREAD

**Issue by txl2008** [jeecgboot/JimuReport#889]
##### 版本号：
1.4.4-beta 

##### 问题描述：
地图不能设置区域地图

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/8275826/161882140-c9dd13a6-1fcb-46b9-9e1a-05c2ade7b7cc.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不是可以设置区吗？
收录 ws

**Comment by 1298191366** [comment]
请参考文档:http://report.jeecg.com/2051319
