### ISSUE TITLE
设置图片套打&背景图时，无法撤销并且无法重新上传

### ISSUE THREAD

**Issue by zhushiyuml** [jeecgboot/JimuReport#892]
##### 版本号：

v1.4
##### 问题描述：

设置图片套打&背景图时，无法撤销并且无法重新上传
##### 错误日志&截图：

![DINGTALK_IM_1516431704 JPG](https://user-images.githubusercontent.com/100819098/161899983-add12e86-0b15-4988-b763-00137b9bad94.JPG)

<img width="1174" alt="B076F328-709F-41A0-B074-33E4965FE9C1" src="https://user-images.githubusercontent.com/100819098/161900026-a7607be7-d5a0-496d-a2a0-f86b16a2e6fd.png">

##### 重现步骤：
1、上传图片
2、设为套打图片（设为背景图片）
3、鼠标右键-无法看到取消套打设置
4、重新上传提示不能重复上传
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
鼠标右键-滚动条往下拉
