### ISSUE TITLE
积木报表的大屏编辑器编辑大屏以后可以部署吗，可以单独搞出来用还是只能在线预览

### ISSUE THREAD

**Issue by jokerhigher** [jeecgboot/JimuReport#896]
##### 问题描述：
请问积木报表的大屏编辑器编辑大屏以后可以部署吗，就是单独搞出来用还是只能在线预览

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/103160900/162111143-9d7bf169-81bd-42c1-a0db-7bdefa8f86a6.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
只能在线使用
