### ISSUE TITLE
180度仪表盘数据自动刷新无效

### ISSUE THREAD

**Issue by luxiaojie** [jeecgboot/JimuReport#897]
##### 版本号：

1.4.4-beta
##### 问题描述：

使用ｓｑｌ数据集作为　180度仪表盘的数据源时，开启了自动刷新，sql数据源数据更新后，不能反应到报表上。按F5刷新网页我也没效果。必须重新进入设计，点击运行才会更新。
同一个页面的柱状图报表没有这个问题，sql数据源更新后就会在到了自动刷新间隔后显示。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 1298191366** [comment]
已修复，待新版本发布
