### ISSUE TITLE
未发现背景图设置菜单项

### ISSUE THREAD

**Issue by zhaoqing0803** [jeecgboot/JimuReport#899]
##### 版本号：

1.4
##### 问题描述：

未发现背景图设置菜单项
##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/86814530/162141575-7aa98272-e3b2-4448-8987-303cc8030f9d.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
鼠标右击，滚动条往下拉
