### ISSUE TITLE
导出的excel颜色显示异常--有阴影

### ISSUE THREAD

**Issue by crazy-gulang** [jeecgboot/JimuReport#900]
##### 版本号：
1.4.4-beta

##### 问题描述：
预览时数据颜色显示正常，导出excel后，部分数据颜色显示有阴影
yml中设置为primary模式后依然显示阴影

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/42635799/162142427-2b57a555-0f80-46fa-bd54-60b4d93f7cc5.png)
![image](https://user-images.githubusercontent.com/42635799/162142440-6c9b1c13-c8c7-4e2b-acb1-a9b3e128fc5a.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
有阴影这部分是怎么设计的

**Comment by crazy-gulang** [comment]
=(let sex= '#{ONE_DEFENCE.答辩得分}'; 
if(sex >= '4'){
   return  color('#{ONE_DEFENCE.答辩得分}','',' #a7d08c');
}elsif(sex < '3.5'){
   return color('#{ONE_DEFENCE.答辩得分}','','#ffff01');
}else{
   return color('#{ONE_DEFENCE.答辩得分}','',' #f4b184');
})

而且只有答辩得分这一列有问题

**Comment by crazy-gulang** [comment]
> =(let sex= '#{ONE_DEFENCE.答辩得分}'; if(sex >= '4'){ return color('#{ONE_DEFENCE.答辩得分}','','#a7d08c'); }elsif( sex < '3.5'){ return color('#{ONE_DEFENCE.答辩得分}','','#ffff01'); }else{ return color('#{ONE_DEFENCE.答辩答}','','# f4b184'); })
> 
> 只有答辩得分这一列有问题

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/162166966-07949b10-b16e-4d83-ae5c-9da177286de6.png)
中间有个空格吧，去掉试试

**Comment by crazy-gulang** [comment]
果然，是这个问题，检查不仔细 笑哭，多谢
