### ISSUE TITLE
背景图设置报错

### ISSUE THREAD

**Issue by zhaoqing0803** [jeecgboot/JimuReport#902]
##### 版本号：
1.4

##### 问题描述：

背景图设置报错
##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/86814530/162361136-0c77a154-0197-4642-ad0a-6520d380e715.png)

##### 重现步骤：

在图形报表里面新建报表，点击右键，点击背景设置，点击上传，导入j1.jpg,页面上会出现感叹号
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
你这个报错信息，配置用的阿里云oss，没有的话，可以直接配置本地
