### ISSUE TITLE
自定义横向分组问题

### ISSUE THREAD

**Issue by yuhui520** [jeecgboot/JimuReport#905]
##### 错误日志&截图：

![1649399577(1)](https://user-images.githubusercontent.com/53930702/162378050-aceb98af-c3f3-4acc-ac99-65014941e00c.jpg)

![1649399604(1)](https://user-images.githubusercontent.com/53930702/162378072-d62ce48d-089d-466e-9712-392e5b376446.jpg)

##### 重现步骤：
在自定义横向分组后没有数据会出现这种问题，有数据正常

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级版本
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.4.4-beta</version>
</dependency>
```
