### ISSUE TITLE
饼图未按分类汇总展示

### ISSUE THREAD

**Issue by Action45** [jeecgboot/JimuReport#906]
##### 错误日志&截图：
数据 
![AX%7$W)AO)C7{3B4@PFUK2](https://user-images.githubusercontent.com/87290598/162402346-5b331f10-1c08-4a8d-8ed1-88450968e953.png)
![9K~U4T% HYSS9X0$6WCTOMK](https://user-images.githubusercontent.com/87290598/162402387-e99f11d7-1a5b-489a-9a8c-12b46d0b98c0.png)
如图，按name列分类，value统计后，name为[四类]的两条数据值22和20在饼图中分开渲染了。  理论上应是一个且值为22+20 = 42

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持，可以在SQL中分组查询
