### ISSUE TITLE
下拉选值未去重问题

### ISSUE THREAD

**Issue by Action45** [jeecgboot/JimuReport#908]
##### 错误日志&截图：
SQL数据集：
![image](https://user-images.githubusercontent.com/87290598/162658929-706bcc6b-2a77-4696-996b-79284f4bc3cb.png)

查看页面：
![image](https://user-images.githubusercontent.com/87290598/162658654-38309fa9-16fe-40ba-99e5-e70d76873d77.png)

![~5 H%`G7YVWA})}DD CLMZM](https://user-images.githubusercontent.com/87290598/162659034-db84df2b-3741-4f21-a682-91c6054ec9e5.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
默认去重会导致排序混乱
字典code可配置sql字典，自行去重
