### ISSUE TITLE
删除数据字典中的一条数据后重新添加该字典编码，提示“字典编码已存在！”，而且报表参数中还能继续使用已被删除的字典编码

### ISSUE THREAD

**Issue by dylens** [jeecgboot/JimuReport#909]
##### 错误日志&截图：
<img width="958" alt="1-添加了一条字典编号为dye_w的字典记录" src="https://user-images.githubusercontent.com/6213241/162674255-33fa2eba-fa51-45f3-9276-65c72fdf24a4.png">

<img width="950" alt="2-删除该字典记录" src="https://user-images.githubusercontent.com/6213241/162674405-a460d49f-d4a7-45ad-a245-dc6fce5ac82a.png">

<img width="950" alt="3-刷新缓存" src="https://user-images.githubusercontent.com/6213241/162674422-fd202e67-3288-4740-9576-74e1390387a7.png">

<img width="953" alt="4-提示字典编码与存在" src="https://user-images.githubusercontent.com/6213241/162674429-c992a04b-f9d1-49b9-b0f1-6e550408b79e.png">

##### 重现步骤：
1、在报表设计页面点击左侧的“数据字典”编辑按钮；
2、点击“添加”，新增一条字典记录（字典编码为：dye_w）；
3、新增成功后删除该字典记录；
4、再次字典编码为dye_w的字典记录时，提示“字典编码已存在！”；
5、新建一个报表，“数据集管理”->“报表参数” ，新增一个参数，且将该参数的字典code设置为已删除的字典编码dye_w，可以正常使用已被删除的字典编码dye_w；

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
删除为逻辑删除，需手动数据库恢复
