### ISSUE TITLE
勾选多条字典记录后点击删除，被删除的记录依然存在于字典列表中

### ISSUE THREAD

**Issue by dylens** [jeecgboot/JimuReport#910]
##### 错误日志&截图：
<img width="958" alt="1-字典列表" src="https://user-images.githubusercontent.com/6213241/162679784-543f7433-79b9-44b4-b852-7bb4c9ccfbf8.png">

<img width="959" alt="2-勾选多条字典记录后点击删除" src="https://user-images.githubusercontent.com/6213241/162679793-ce0f7390-a679-4588-99f7-8611c99651d4.png">

<img width="959" alt="3-提示删除成功-但被删除的字典记录仍然存在于字典列表中" src="https://user-images.githubusercontent.com/6213241/162679799-abf7c2f2-79ec-48b2-8897-041abb923073.png">

##### 重现步骤：
1、勾选多条字典记录后点击删除，提示删除成功；
2、被删除的字典记录依然存在于字典列表中，再次点击查询还是可以查到；

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
