### ISSUE TITLE
多个自定义横向导致样式错乱

### ISSUE THREAD

**Issue by yuhui520** [jeecgboot/JimuReport#911]
##### 问题描述：
定义了4个数据源进行自定义横行加分板之后导致原有表格样式错乱

##### 错误日志&截图：
![1649732576(1)](https://user-images.githubusercontent.com/53930702/162871115-d700ac7b-680c-45c8-8749-90357fb8884f.jpg)
![1649732493(1)](https://user-images.githubusercontent.com/53930702/162871126-ae45e39c-8eac-44e3-9cae-3819815f53de.jpg)

##### 重现步骤：
多组数据源进行自定义横向导致整体样式错乱

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
导出报表配置及数据，我们看一下

**Comment by yuhui520** [comment]
[非住宅作价确认表 (1).xlsx](https://github.com/jeecgboot/JimuReport/files/8502958/1.xlsx)

**Comment by yuhui520** [comment]
[导出数据报表.xlsx](https://github.com/jeecgboot/JimuReport/files/8502963/default.xlsx)

**Comment by yuhui520** [comment]
[导出数据报表.xlsx](https://github.com/jeecgboot/JimuReport/files/8502967/default.xlsx)

**Comment by lvdandan16** [comment]
导出报表配置参考文档：http://report.jeecg.com/2376604

**Comment by yuhui520** [comment]
[report-export-mysql.zip](https://github.com/jeecgboot/JimuReport/files/8502976/report-export-mysql.zip)

**Comment by lvdandan16** [comment]
不支持
