### ISSUE TITLE
html 打印 有较多文本内容时，行间距变小，个别页尾有留白，和canvas 打印的页数不一样。

### ISSUE THREAD

**Issue by yufe000** [jeecgboot/JimuReport#915]
##### 问题描述：

html 打印和canvas 打印 显示的页数不一样，html 打印 行间距变小，
##### 错误日志&截图：
html 打印的样子：
![image](https://user-images.githubusercontent.com/38098002/163084831-4dd9fa79-61b2-4698-9a1a-6d8321586a3b.png)
canvas 打印的样子：
![image](https://user-images.githubusercontent.com/38098002/163085429-aa967cf4-5f05-45fa-9e1a-3c1f39d4bd77.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请导出报表配置 我们看一下

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题

**Comment by yufe000** [comment]
这是来自QQ邮箱的自动回复邮件。
       您好，我已收到你的邮件，我将尽快回复您!
                                                   自由的风
