### ISSUE TITLE
为什么查询的表格有很多天数据，但是对应的图表上只能显示3天

### ISSUE THREAD

**Issue by carrotzizi** [jeecgboot/JimuReport#916]
##### 版本号：
1.4.0

##### 问题描述：
为什么查询的表格有很多天数据，但是对应的图表上只能显示3天

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/3685250/163086347-77a75991-f4b1-47b4-8bd5-58ac65f92373.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请导出报表配置及数据

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
