### ISSUE TITLE
对于API数据集和JSON数据集，日期类型字段的范围查询不生效

### ISSUE THREAD

**Issue by dylens** [jeecgboot/JimuReport#917]
##### 问题描述：
对于API数据集和JSON数据集，设置报表的日期类型字段（查询模式：范围查询，查询日期格式：yyyy-MM-dd HH:mm:ss），预览页面，选择时间范围后点击查询不生效；

##### 错误日志&截图：
<img width="960" alt="1-json数据集报表字段明细" src="https://user-images.githubusercontent.com/6213241/163130863-2553e0f9-84ae-4cd3-9dd2-6c16251c0d70.png">

<img width="741" alt="2-日期范围查询不生效" src="https://user-images.githubusercontent.com/6213241/163130902-23accf3e-a034-4eb0-9987-6365cf45cc93.png">

##### 重现步骤：
1、选择数据集类型为API数据集或JSON数据集，都可以使用如下json数据：
{ "data": [ { "ctotal": "125箱", "cname": "三元", "cprice": "56", "riqi": "2021-10-21 19:00:00", "id": "1", "dtotal": "1000箱", "tp": "7000.88", "ztotal": "589箱", "规格": "每箱24瓶" }, { "ctotal": "228箱", "cname": "光明", "cprice": "69", "riqi": "2022-03-11 11:00:00", "id": "1", "dtotal": "1900箱", "tp": "9600.66", "ztotal": "709箱", "规格": "每箱24瓶" }, { "ctotal": "129箱", "cname": "特仑苏", "cprice": "59", "riqi": "2022-01-20 15:00:00", "id": "1", "dtotal": "1208箱", "tp": "4730.35", "ztotal": "588箱", "规格": "每箱16瓶" } ] }
2、设置报表的日期类型字段（查询模式：范围查询，查询日期格式：yyyy-MM-dd HH:mm:ss）；
3、预览页面；
4、选择时间范围后点击查询。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
json不支持
Api接口里边有参数吗？

**Comment by dylens** [comment]
> 

Api接口里面没有参数，这里只针对自动解析出来的报表字段明细中的日期范围查询

**Comment by lvdandan16** [comment]
Api接口里边需要接收字段
