### ISSUE TITLE
1.4.4版本 导出2W多条数据问题

### ISSUE THREAD

**Issue by c626210053** [jeecgboot/JimuReport#918]
##### 版本号：

1.4.4
##### 问题描述：

使用导出功能导出2万多条数据出现报错  建议导出插件用阿里的EsayExcel插件
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/59947333/163321596-5fa31b72-e706-4107-a5d8-173c278d1e2b.png)

![image](https://user-images.githubusercontent.com/59947333/163321506-dd5cdb20-13a1-407d-ad7d-536babb4eb5a.png)

##### 重现步骤：

导出1万多条数据可以正常导出
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
请导出报表配置

**Comment by shenbushou** [comment]
hello。你这个是在哪里配置的？我也遇到这个问题了。一定要安装插件吗？
