### ISSUE TITLE
1.4.32版本打印设计报表打印时会多出一个空白页的问题

### ISSUE THREAD

**Issue by hanchen-1988** [jeecgboot/JimuReport#920]
##### 版本号：
1.4.32

##### 问题描述：
打印报表内容为一页，但是打印时出现两页，且第二页为空白页，错误截图为打印设计示例报表打印时截图。

##### 错误日志&截图：
![图片1](https://user-images.githubusercontent.com/103640414/163378835-c8b80b57-3e2b-4834-b609-31d80575496a.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by unbelievableTang** [comment]
大佬如何解决的，我也有这个问题
