### ISSUE TITLE
积木报表能否支持多结果集的行关联设置

### ISSUE THREAD

**Issue by wangjianfei2018** [jeecgboot/JimuReport#921]
##### 问题描述：
两个结果集的字段放在一行、通过关联字段关联无法显示；积木能否支持此功能、像帆软的设计器一样、感觉这是最基本的一个结果集关联设计功能
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/45550902/163501512-694a59fc-f5f7-4a04-baeb-c443a01a78d9.png)
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
