### ISSUE TITLE
离线版--右键无法插入行、删除行、设置背景图等

### ISSUE THREAD

**Issue by donganxifeng** [jeecgboot/JimuReport#923]
##### 问题描述：
右键看不到插入行、删除后、设置背景图片等操作，这是啥原因?

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/5390941/163533383-b8438caa-0557-4772-aab5-64d0f5b50bea.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
滚动条下拉
