### ISSUE TITLE
查询数据比较多时无返回

### ISSUE THREAD

**Issue by Optimusruan** [jeecgboot/JimuReport#925]
##### 版本号：
1.4.4-beta

##### 问题描述：
查询返回来的数据集比较大时，界面看不到数据，浏览器F12 提示
RangeError: Maximum call stack size exceeded
    at Cf (jmsheet.js?v=1.0.5:2:1621826)
    at t.Lf (jmsheet.js?v=1.0.5:2:1621995)
    at t.value (jmsheet.js?v=1.0.5:2:1652575)
    at t.value (jmsheet.js?v=1.0.5:2:1664671)
    at view.js?v=1.0.5:284:21
    at Object.success (manager.js?v=1.0.5:71:17)
    at request.js?v=1.0.5:68:42
#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
分页展示数据

**Comment by Optimusruan** [comment]
阮才通已经收到您的邮件

**Comment by Optimusruan** [comment]
已解决

**Comment by hunk666** [comment]
> 已解决

你是怎么解决的，我用最新版也有这个问题

**Comment by Optimusruan** [comment]
阮才通已经收到您的邮件
