### ISSUE TITLE
在图形报表中插入表格打乱布局

### ISSUE THREAD

**Issue by Michael4134** [jeecgboot/JimuReport#927]
##### 版本号：
1.5.0

##### 问题描述：
在图形报表中插入表格，预览发现布局会被插入的表格打乱。

##### 错误日志&截图：
![1650264222754_D03BD370-7B1D-4f1b-861E-47DF50313A03](https://user-images.githubusercontent.com/50390254/163767750-16339c41-3ca8-4618-a38b-f53e6509b3fd.png)
![1650264295665_2D2DFDC3-0DC6-44a5-BD54-05FD4E4E1AFC](https://user-images.githubusercontent.com/50390254/163767770-2aa033d8-ac38-4093-a097-2befa1614c3b.png)
![1650264363518_2940606B-5951-43ca-B984-B296F9A781B4](https://user-images.githubusercontent.com/50390254/163767785-bcd9b804-b8a8-4028-808c-25695852b985.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
表格设置分版试一下
