### ISSUE TITLE
特殊字符json反序列化报错

### ISSUE THREAD

**Issue by mylikethranduil** [jeecgboot/JimuReport#928]
##### 版本号：
1.5.0-beta

##### 问题描述：
业务数据包含字符【 ' 】，json反序列化报错
除了英文单引号，还存在json反序列化报错情况。

##### 错误日志&截图：
com.alibaba.fastjson.JSONException: syntax error, position at 5761749, name text
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:645) ~[fastjson-1.2.78.jar:na]
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:581) ~[fastjson-1.2.78.jar:na]

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by mylikethranduil** [comment]
采取API获取数据集， 并且使用fastjson JSON.parseObject()解析json数据，并没有报错。

**Comment by mylikethranduil** [comment]
导出Excel表格时报的错，这个bug请尽快修复吧，太影响使用了

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
如果时分组有双引号报错，已修复，待新版本发布
