### ISSUE TITLE
大屏移动端适配问题

### ISSUE THREAD

**Issue by guoleopard** [jeecgboot/JimuReport#929]
##### 版本号：
1.5.0

##### 问题描述：
大屏移动端适配问题

##### 重现步骤：
创建 宽600，长1200的大屏，浏览器预览时，切换到移动端，展示结果没有适配

![1650272714(1)](https://user-images.githubusercontent.com/1821650/163785309-69efec69-7461-470c-8f45-60259c9a5722.png)

![1650272696(1)](https://user-images.githubusercontent.com/1821650/163785276-edb2f984-6d82-40bc-b9eb-728b66d6db9a.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持移动端
