### ISSUE TITLE
excel导出报表fastjson报错

### ISSUE THREAD

**Issue by Acechengui** [jeecgboot/JimuReport#931]
##### 版本号：
1.4.4-bate  
1.5.0-beta

##### 问题描述：
excel报表开启了分页预览时,正常预览,进行excel导出的时候,或者是不设置分页预览,均会报错**com.alibaba.fastjson.JSONException: syntax error, position at 3987892, name text**

##### 错误日志&截图：
错误日志:
`2022-04-19 10:11:51.202 [http-nio-6010-exec-1] INFO  org.jeecg.modules.jmreport.desreport.service.a.e - ------报表【CHQS】，查询的sql: SELECT * FROM dbo.V_PACKGOODS_WEEK_REPORT WHERE status=1 AND parts_less>0 ORDER BY sch_date
2022-04-19 10:11:51.210 [http-nio-6010-exec-1] INFO  org.jeecg.modules.jmreport.desreport.service.a.e - ------数据源 dbSourceKey:【26d21fe4f27920d2f56abc8d90a8e527】
2022-04-19 10:11:59.375 [http-nio-6010-exec-1] ERROR c.j.u.common.exception.GlobalExceptionResolver - 运行时异常:
com.alibaba.fastjson.JSONException: syntax error, position at 3987892, name text`
![image](https://user-images.githubusercontent.com/63096199/163907695-d05f06a9-cda0-4d88-90b4-ef9064c8899a.png)

使用的是sqlserver

##### 重现步骤：
1.使用sqlserver数据源
2.执行的是一个视图 V_PACKGOODS_WEEK_REPORT ,提供导出的全部该视图的数据
[无标题.xlsx](https://github.com/jeecgboot/JimuReport/files/8509290/default.xlsx)

3.设置分页或者不分页 
4.导出excel

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Acechengui** [comment]
升级了fastjosn版本也未解决该问题  目前使用的版本为1.2.79

**Comment by Acechengui** [comment]
![image](https://user-images.githubusercontent.com/63096199/163908027-9faa9026-b510-458f-9ad6-ef352bc66f9d.png)
分页预览时是正常的

**Comment by lvdandan16** [comment]
收录 ws

**Comment by lvdandan16** [comment]
请导出报表配置及数据，我们复现一下

**Comment by Acechengui** [comment]
数据已提供 在重新步骤中的 上传了excel文件,报表未作其他配置  直接将sql查询出来的数据字段映射好

**Comment by 1298191366** [comment]
已修复，待新版本发布
