### ISSUE TITLE
一个页面使用多个循环块出现混乱

### ISSUE THREAD

**Issue by zhengdebin** [jeecgboot/JimuReport#933]
##### 问题描述：
当我需要再一个报表中展示多个循环块正常,后面的出现混乱,请问怎么解决

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/7885964/163968713-36c40ed1-58ef-44aa-a989-e0f20db095fa.png)
![image](https://user-images.githubusercontent.com/7885964/163969219-c25d52dc-3932-4b68-b8db-fea2e76a02b2.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
哪个版本

**Comment by zhengdebin** [comment]
不好意思没写版本，我是在1.4.32上出现的这个问题，谢谢

**Comment by lvdandan16** [comment]
更到最新版本试一下
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.5.0-beta</version>
</dependency>
```

**Comment by zhengdebin** [comment]
解决了，谢谢
