### ISSUE TITLE
1.5.0-beta 版本|紧急|数值格式转问题|导出

### ISSUE THREAD

**Issue by c626210053** [jeecgboot/JimuReport#938]
##### 版本号：
1.5.0-beta

##### 问题描述：
设置好字段类型数值，导出后出现文本类型。 设置字段类型无效

##### 错误日志&截图：
![$6DLB`V~L24LOFG$OT(LR(8](https://user-images.githubusercontent.com/59947333/164351250-dc056328-a899-4029-a770-2b670b8bb65b.jpg)

![G4_G7N VVL177PSV@4W4X(5](https://user-images.githubusercontent.com/59947333/164351258-43282d01-da45-4e19-86c7-f30bcb671ff3.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
