### ISSUE TITLE
1.5.0-beta 版本|紧急|报表分享问题|分享

### ISSUE THREAD

**Issue by chichengzi** [jeecgboot/JimuReport#939]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/64116269/164587122-db6d11dd-03d9-4686-8137-ffd8024f35a8.png)

![image](https://user-images.githubusercontent.com/64116269/164587155-ee133f19-bba2-4d23-af8d-1043efe4dab0.png)

##### 重现步骤：
直接在新建的报表列表点击分享。
![image](https://user-images.githubusercontent.com/64116269/164587220-ca0ca123-6ccc-47d6-9dda-d6d2ef99ec45.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by chichengzi** [comment]
目前我手动在表里面加了这个字段，能够正常使用这个功能，但是您也可以排查一下，因为我看这个脚本是6个月前的了，目前我使用的是1.5.0-beta版本，如果可以的话，请同步一下sql脚本。感谢！

**Comment by zhangxinyuan1** [comment]
最新脚本，还是未修复
