### ISSUE TITLE
数据源出错

### ISSUE THREAD

**Issue by jiajunwang666** [jeecgboot/JimuReport#943]
##### 版本号：
 v1.5.0-beta 

##### 问题描述：
官网数据源出错

##### 错误日志&截图：
![2eb1f1aa97e74430a0ce7d2bdb8448d](https://user-images.githubusercontent.com/74111090/164970001-6ee7e465-5b5e-4bbe-a33c-5e672bb1d64a.png)

##### 重现步骤：
![2eb1f1aa97e74430a0ce7d2bdb8448d](https://user-images.githubusercontent.com/74111090/164970012-3cf37cd5-0ad1-49c1-8548-6cbfe3e031e9.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
已修复，您现在测试一下看看
