### ISSUE TITLE
报表模板里插入图片，不定时就会失效

### ISSUE THREAD

**Issue by xiezuowen** [jeecgboot/JimuReport#945]
##### 版本号：
1.4.2
##### 问题描述：
报表模板里插入图片，不定时就会失效

##### 错误日志&截图：
![1](https://user-images.githubusercontent.com/100402582/164970404-cf1e5b0d-96dc-4f08-b033-3b715a9afda4.png)
![2](https://user-images.githubusercontent.com/100402582/164970450-9df0d7e9-9ab2-444f-9da2-e79cfe4cb557.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
先看一下服务器上有这个文件吗？

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
