### ISSUE TITLE
编辑报表时，总长度超过页面默认长度时，右键新增列

### ISSUE THREAD

**Issue by billy109** [jeecgboot/JimuReport#947]
##### 版本号：
1.5

##### 问题描述：
编辑报表时，总长度超过页面默认长度时，右键新增列之后，下次进入就不会显示了
向右拖动滚动条到最右也不会显示

##### 重现步骤：
![企业微信截图_16508767444234](https://user-images.githubusercontent.com/15712422/165055015-cebf6151-9ad4-4563-a695-6798fefc6241.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
参考常见问题34：http://report.jeecg.com/2087464#34__224
