### ISSUE TITLE
谢谢大哥，帮忙解决下！！！！

### ISSUE THREAD

**Issue by L2S11** [jeecgboot/JimuReport#948]
##### 版本号：
1.4.2

##### 问题描述：
清理了浏览器的缓存，就获取不到系统变量然后就请求接口错误

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/89952276/165058486-96754d50-f50c-431f-b73d-089f76d363b5.png)
![image](https://user-images.githubusercontent.com/89952276/165058836-1fee282f-4051-4dc1-b062-462a6f745920.png)

##### 重现步骤：
清理缓存 请求接口

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
你这是系统变量，还是参数

**Comment by L2S11** [comment]
> 

系统变量好哥哥

**Comment by L2S11** [comment]
11111

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
未测出，清空浏览器缓存和获取你后台的系统变量有啥关系，除非是访问不到你的后台接口
