### ISSUE TITLE
DBSUM()公式报莫名的不可用列

### ISSUE THREAD

**Issue by andywzf** [jeecgboot/JimuReport#951]
##### 版本号：
1.4.3

##### 问题描述：
DBSUM()公式报莫名的不可用列.总共有 几十个列,到AI列了,每列都需要加dbsum公式.
一会报这个列不可用,一会又会报另外一个列不好用  都是有 DBSUM

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/47747103/165279692-c72c1749-a3a2-4b87-9307-7c93d174f3f5.png)

![JM%9IV3IBSARM8%QZ2P4(}5](https://user-images.githubusercontent.com/47747103/165279793-6e69304f-2fb1-432f-a483-ce3b2c8a7d7d.jpg)

##### 重现步骤：
设置多个DBSUM公式后,一会报这个列不可用,一会又报另外一个列不可用.实际都是正确的设置. qq:515994518

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
已修复，下个版本升级

**Comment by andywzf** [comment]
谢谢支持! @lvdandan16
