### ISSUE TITLE
mongodb数据源参数化查询无法解析

### ISSUE THREAD

**Issue by loglong** [jeecgboot/JimuReport#952]
##### 版本号：
jimureport-quickstart-1.4.2

##### 问题描述：
mongodb数据源参数化查询无法解析

####
![WechatIMG1526](https://user-images.githubusercontent.com/4179349/165419117-3281b55e-9f96-4856-9266-c659d4554892.png)
![WechatIMG1528](https://user-images.githubusercontent.com/4179349/165419048-d3857668-74f6-4415-ba08-ef7ee5c1bf00.png)
![WechatIMG1527](https://user-images.githubusercontent.com/4179349/165419047-4f1960e5-3664-438d-bee0-de59afa61d7c.png)
# 错误日志&截图：

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
升级最新版本
