### ISSUE TITLE
不支持复杂数据集

### ISSUE THREAD

**Issue by Lsatin** [jeecgboot/JimuReport#957]
##### 版本号：
1.5.0-beta

##### 问题描述：
为什么这么长时间了，还不支持复杂数据集啊。
JSON：{data: [{key: value, key: [{key: value},{key, value}]}]}

##### 错误日志&截图：
![1651288575(1)](https://user-images.githubusercontent.com/34743318/166088438-f0868676-4e28-4c82-8e90-bbaa3dc94c41.png)
![1651288636(1)](https://user-images.githubusercontent.com/34743318/166088463-2d36e590-1eec-4694-8fac-be8763c3f899.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
不支持
参考处理文档：http://report.jeecg.com/2293839
