### ISSUE TITLE
支持啊，设置为“动态合并”

### ISSUE THREAD

**Issue by sz2349** [jeecgboot/JimuReport#962]
支持啊，设置为“动态合并”

_Originally posted by @Lsatin in https://github.com/jeecgboot/JimuReport/issues/956#issuecomment-1113082535_

**Comment by sz2349** [comment]
我说的是类似与excel里面的冻结首行的功能。
![image](https://user-images.githubusercontent.com/42996028/166877256-e92d209f-691f-40ae-99d3-2f449bfc45e3.png)

**Comment by lvdandan16** [comment]
暂不支持
归集到 #138

**Comment by sz2349** [comment]
谢谢您的来件，我将尽快给您回复。
