### ISSUE TITLE
联动传参

### ISSUE THREAD

**Issue by zhaoqing0803** [jeecgboot/JimuReport#963]
##### 版本号：
1.4

##### 问题描述：
创建两个数据集，用字典显示男女，其实数据是1,2，但是传参的时候还是传的是中文字男女，为啥不传数字？

##### 错误日志&截图：

数据为空
##### 重现步骤：
1创建数据集：SELECT sex,COUNT(1) cnt FROM sys_user GROUP BY sex;用字典显示
2创建数据集：SELECT * FROM test_rp_chart WHERE sex='${test_arg}';传参数
在传参的过程中，依然传的是男女，不是数字，不知道什么原因，请问哪里配置错误

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂时不好解决
归集到：#138
