### ISSUE TITLE
报表下钻时返回上一页下拉树参数回显有问题!!!

### ISSUE THREAD

**Issue by nieguoxu** [jeecgboot/JimuReport#965]
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/67364475/167099612-582d2c3d-1d21-4da6-8c96-9f5307a58e63.png)
![image](https://user-images.githubusercontent.com/67364475/167099654-9530f072-470d-4b5f-84a9-16079ab8a2dc.png)
![image](https://user-images.githubusercontent.com/67364475/167099699-d2939298-fddb-4db3-bead-7db3f23c9901.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布，需要在新增一个通过value值获取树集合，详情请参考文档：http://report.jeecg.com/2388194
