### ISSUE TITLE
查询条件下拉单选的占位文本描述显示不正确

### ISSUE THREAD

**Issue by yuebo** [jeecgboot/JimuReport#966]
##### 版本号：
1.5.0-beta

##### 问题描述：
查询条件下拉单选的占位文本描述显示不正确

##### 错误日志&截图：
![1651900449(1)](https://user-images.githubusercontent.com/9998927/167239531-e4855760-f0ce-407a-9a14-2c3a8defe631.png)

##### 重现步骤：
1. 设置查询条件为下拉单选，预览时占位文本描述显示不正确

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by lvdandan16** [comment]
已修复，下个版本支持
