### ISSUE TITLE
Method code too large! 报错

### ISSUE THREAD

**Issue by ych6666** [jeecgboot/JimuReport#967]
##### 版本号：
1.4.0

##### 问题描述：
查询内容多会出现Method code too large!
有什么优化方案吗

##### 错误日志&截图：
![Snipaste_2022-05-07_16-42-05](https://user-images.githubusercontent.com/89495170/167247450-f17bdeb9-081f-44ea-89b7-9787d95b3189.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
可设置分页展示数据
