### ISSUE TITLE
程序更新以后横向分组金额出不来（图一）,我对比以前做过的横向分组，发现更新后的横向分组没有值（图二），但图三明显可以看到是金额字段是有值的

### ISSUE THREAD

**Issue by baiyixiangqin** [jeecgboot/JimuReport#969]
##### 版本号：
1.5.0

##### 问题描述：

程序更新以后横向分组金额出不来（图一）,我对比以前做过的横向分组，发现更新后的横向分组没有值（图二），但图三明显可以看到是金额字段是有值的
##### 错误日志&截图：
图一
![image](https://user-images.githubusercontent.com/102849584/167397438-dae94b1d-6036-492b-aad5-c6804b997847.png)

图二
![image](https://user-images.githubusercontent.com/102849584/167397523-2524568c-57c4-4519-bcea-8811d2ddc69b.png)

图三
![image](https://user-images.githubusercontent.com/102849584/167397617-c2b98bcc-e5d4-4bf4-aaa7-19e78ef4e425.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
导出报表配置及数据，我们复现一下
