### ISSUE TITLE
最新版本无法用dockerfile打包

### ISSUE THREAD

**Issue by YBenX** [jeecgboot/JimuReport#970]
##### 版本号：
升级到1.5.0-beta版，无法打包，1.4.0版本是可以的。
![image](https://user-images.githubusercontent.com/3353434/167415460-b068926b-9f17-4da9-b81a-282612e0252f.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
测试无问题
