### ISSUE TITLE
查询控件调用外部接口api接口跨域怎么解决？

### ISSUE THREAD

**Issue by YBenX** [jeecgboot/JimuReport#971]
##### 版本号：
后端接口是支持跨域的。
![image](https://user-images.githubusercontent.com/3353434/167417236-8ef47764-d4a9-4891-a012-10b5386b15b9.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
与此问题重复，故删除
https://gitee.com/jeecg/JimuReport/issues/I54EL3
