### ISSUE TITLE
下拉选择值重复

### ISSUE THREAD

**Issue by zy528** [jeecgboot/JimuReport#972]
##### 版本号：
1.5.0-beta

##### 问题描述：
报表数据里一列数据多行为相同值时，下拉多选改列的值数据显示重复

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/30794610/167531735-18215f92-0c27-4c71-9283-bb684afe99c2.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
1.5.0-beta默认不去重，可以使用sql字典去重
参考文档5.2：http://report.jeecg.com/2373407#52SQLcodesql_35
