### ISSUE TITLE
单元格预览打印显示空白

### ISSUE THREAD

**Issue by Zoe-Zhu** [jeecgboot/JimuReport#973]
##### 版本号：
1.4.4-beta

##### 问题描述：
某一个单元格不管放什么数据都不会显示，不知道什么原因，偶发问题。

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/22297885/167537184-4e545951-98ed-4fe6-a3d0-3dfb1c042376.png)
如上图，同样的数据放在下面就正常显示

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Zoe-Zhu** [comment]
![image](https://user-images.githubusercontent.com/22297885/167537365-b356e6cb-59ce-4b16-8d9a-a66b0d0c7ffc.png)

**Comment by lvdandan16** [comment]
导出报表配置和数据，我们复现一下

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
