### ISSUE TITLE
预览界面，点击查询栏展开和合并，横向滚动条会消失

### ISSUE THREAD

**Issue by Jackhzf** [jeecgboot/JimuReport#974]
##### 版本号：
1.4.32

##### 问题描述：
预览界面，点击查询栏展开，横向滚动条会消失，查询栏合并滚动条出现

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/90304373/167567958-d586d47b-a554-4e46-bed3-84cc900cdf79.png)
![image](https://user-images.githubusercontent.com/90304373/167568017-8235d13a-45e2-4577-9381-f06240988a73.png)

**Comment by lvdandan16** [comment]
收录 dd

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
