### ISSUE TITLE
springboot 集成积木报表1.5 启动异常

### ISSUE THREAD

**Issue by majiage** [jeecgboot/JimuReport#977]
##### 版本号：
1.5.0-beta

##### 问题描述：
springboot2.0.7 集成，启动报错

##### 错误日志&截图：
![QQ图片20220511085357](https://user-images.githubusercontent.com/105278197/167747707-397f1e1e-ecbe-43e1-a590-7d9202134331.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
使用demo推荐版本试一下
