### ISSUE TITLE
打印时，布局选项不显示

### ISSUE THREAD

**Issue by liangwei2012** [jeecgboot/JimuReport#978]
##### 版本号：
1.4.32

##### 问题描述：
报表点击html打印后，刚开始是有“布局”这个选项的，等报表加载完毕后，布局选项就没了。

##### 错误日志&截图：
![HC5$ 0)B{M{~~J~ 2ER48QE](https://user-images.githubusercontent.com/102564952/167763846-a9a91116-6a21-4c7d-a819-b0b8e1da4976.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty
