### ISSUE TITLE
查询条件，文本框提示信息没有是字段名不是字段文本

### ISSUE THREAD

**Issue by yangjunzhou861012** [jeecgboot/JimuReport#979]
##### 版本号：
1.5.0-beta

##### 问题描述：
配置好报表，并设置查询条件，如果该条件设置了数据字典，则该查询条件的文本框中的提示信息是：请输入字段名，不是：请输入字段文本

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/18575974/167783908-d4874ef3-47c0-47a2-ab58-2bed67554c2d.png)

##### 重现步骤：
在线设计-->新建报表-->数据集管理，选择sql数据集-->输入sql-->点击sql解析-->配置数据字典，勾选查询，保存
![image](https://user-images.githubusercontent.com/18575974/167783820-6be290d9-69ea-4a1b-8308-58a81e46384d.png)
点击预览报表
![image](https://user-images.githubusercontent.com/18575974/167784115-7c41d530-42e3-4498-9221-f8b2a7fc6213.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by lvdandan16** [comment]
已修复，下个版本支持
