### ISSUE TITLE
使用查询控件下拉树，后端返回数据没问题，但系树状循环显示了

### ISSUE THREAD

**Issue by yzmking** [jeecgboot/JimuReport#984]
##### 版本号：
2.4.6

##### 问题描述：
使用查询控件下拉树，后端返回数据没问题，但系树状循环显示了，广东省是第一级的

##### 错误日志&截图：
![1652349392(1)](https://user-images.githubusercontent.com/44563730/168044778-97242f32-31cf-4a17-aadc-98912a91bb94.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by yzmking** [comment]
是1.4.0版本

**Comment by lvdandan16** [comment]
升级最新版本试试
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.5.0-beta</version>
</dependency>
```

**Comment by yzmking** [comment]
更新最新版本后 ，显示jeecg-boot-module-system项目中有个包没有了，是直接注释相关代码就可以了吗？
![image](https://user-images.githubusercontent.com/44563730/168510203-455ea232-9919-4ad3-8a07-2bcecc671533.png)

**Comment by yzmking** [comment]
![image](https://user-images.githubusercontent.com/44563730/168512961-61eb76a9-5ca2-4a85-9628-d831f6d930ff.png)
![image](https://user-images.githubusercontent.com/44563730/168513020-22fc83be-8161-4584-880d-675e66993175.png)
已升至最高版本，当依旧循环
![image](https://user-images.githubusercontent.com/44563730/168513397-0f214750-710b-4b25-992c-52141b0d10df.png)

而且当我点开展开按钮倒三角，都会去请求一次我返回整个树状图的接口

**Comment by lvdandan16** [comment]
参考文档：http://report.jeecg.com/2388194
看一下你自己接口接收pid参数没有，数据加载是异步的，每次点击会根据pid查询子节点

**Comment by yzmking** [comment]
对，我发现了。。。是我自己用错了，没有看清楚文档，以为是整个结构返回


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月16日(星期一) 中午11:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 使用查询控件下拉树，后端返回数据没问题，但系树状循环显示了 (Issue #984)





 
参考文档：http://report.jeecg.com/2388194
 看一下你自己接口接收pid参数没有，数据加载是异步的，每次点击会根据pid查询子节点
