### ISSUE TITLE
我先case判断字符串长度后 满足条件的对字符串切割，报错长度超出

### ISSUE THREAD

**Issue by zhangshuai233** [jeecgboot/JimuReport#985]
##### 版本号：
1.4.2

##### 问题描述：
我先case判断字符串长度 长度满足了在切割长度内的字符串 为什么会报长度超出？ 
=case(string.length("#{jbxx.fucharq}")>10,string.substring("#{jbxx.fucharq}",0,9),“”)

##### 错误日志&截图：
![Uploading image.png…]()

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ws
