### ISSUE TITLE
固定表头

### ISSUE THREAD

**Issue by ych6666** [jeecgboot/JimuReport#986]
##### 版本号：
1.4.0

##### 问题描述：
数据量过多时怎么实现固定表头啊

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/89495170/168188476-0a273a2a-c191-4365-91ae-f3bb33ebc310.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂不支持
归集到#138
