### ISSUE TITLE
关于横向分组合计

### ISSUE THREAD

**Issue by ych6666** [jeecgboot/JimuReport#990]
##### 版本号：

1.4.0
##### 问题描述：
横向分组后想获取一行数据的和，通过=SUM() 获取不了和

##### 错误日志&截图：

![image](https://user-images.githubusercontent.com/89495170/168244819-6e25ea44-9fea-44ea-a7ec-be3b548d6f38.png)
![image](https://user-images.githubusercontent.com/89495170/168244837-02f7bab8-8e50-49db-a667-b064759cc9dc.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
横向动态列后的合计暂不支持
归集到#138
