### ISSUE TITLE
选择类型

### ISSUE THREAD

**Issue by yufuxin01** [jeecgboot/JimuReport#993]
##### 版本号：

1.4.1
##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/77772498/168418868-f355da2c-1967-4302-a48d-29d41bdaeeeb.png)
选择类型有时候不生效，需要重复操作一次才回生效

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
暂时未复现此问题

**Comment by yufuxin01** [comment]
还行，他们可能报表用的少，我直接有经验了，会后端会爆出数字转换异常的错误，我就知道这个格式写错了

**Comment by lvdandan16** [comment]
哪个类型报错？导出报表配置和数据，我们复现一下试试

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
