### ISSUE TITLE
spring boot jpa 集成报错

### ISSUE THREAD

**Issue by bay1ts** [jeecgboot/JimuReport#995]
##### 问题描述：集成报错,SpringBoot,持久层JPA,数据库Postgresql
配置文件:
minidao :
  base-package: com.saltbay.sirius.dao
  db-type: postgresql

启动类
@SpringBootApplication(exclude = {MongoAutoConfiguration.class},scanBasePackages ={"org.jeecg.modules.jmreport"})

##### 错误日志&截图：
ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'designReportController': Unsatisfied dependency expressed through field 'jmReportDesignService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jimuReportServiceImpl': Unsatisfied dependency expressed through field 'reportDbDao'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.jeecg.modules.jmreport.desreport.dao.JimuReportDbDao' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

***************************
APPLICATION FAILED TO START
***************************

Description:

Field reportDbDao in org.jeecg.modules.jmreport.desreport.service.a.e required a bean of type 'org.jeecg.modules.jmreport.desreport.dao.JimuReportDbDao' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)
[https://ww7a7e0920ba45ce27.oss-cn-zhangjiakou.aliyuncs.com/issue.png](url)

##### 重现步骤：
spring boot,jpa 项目集成后启动

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
springboot几？

**Comment by bay1ts** [comment]
2.6.7

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
未测出，我是新建了一个项目
yml配置（minidao配置的是扫描jar里面的文件，可以省略
）
![image](https://user-images.githubusercontent.com/30997828/176816146-66019b37-4a4f-48d0-b45e-dbdae8c3cfe7.png)
pom文件  
![image](https://user-images.githubusercontent.com/30997828/176817195-296c4913-c9f4-433d-92ca-7dca23cbc10f.png)

启动类，和你配置的一致
![image](https://user-images.githubusercontent.com/30997828/176816273-0e125fb4-cc98-4540-b8d3-9f66027113b5.png)

预览页面
![image](https://user-images.githubusercontent.com/30997828/176816478-d47941f9-32e5-42e8-9fed-23289a57a0b3.png)
