### ISSUE TITLE
报表设计边框

### ISSUE THREAD

**Issue by ipanda2020** [jeecgboot/JimuReport#996]
报表设计的时候无法自定义边框，如仅需要上、左边框

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/168718285-7d5c495a-15cf-4d4a-b6e3-4ea23be1c3fb.png)

**Comment by ipanda2020** [comment]
每次只能点击一个呀，无法同时选中两个。
如点击上边框，则无法再同时选中左边框，请问是需要按什么快捷键吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JimuReport"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月17日(星期二) 上午10:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JimuReport] 报表设计边框 (Issue #996)

**Comment by pkaq** [comment]
同样的问题 为啥直接关了
