### ISSUE TITLE
报表边框的bug

### ISSUE THREAD

**Issue by ipanda2020** [jeecgboot/JimuReport#997]
边框无法实现同时点击设置右边框+下边框；
如果分为两次操作，第一次设置右边框，第二次设置下边框，第二次的操作会覆盖第一次的设置

![image](https://user-images.githubusercontent.com/67934219/168721507-dc83959f-ba0b-4433-bc09-34d1ca89aafd.png)

**Comment by lvdandan16** [comment]
收录 ty
