### ISSUE TITLE
API接口数据不能预览

### ISSUE THREAD

**Issue by tianliang0913** [jeecgboot/JimuReport#999]
##### 版本号：
springboot 2.6.4 
jimureport.version 1.8
mysql  8.0.3

##### 问题描述：

API接口预览数据失败；已经重写getData()
![image](https://user-images.githubusercontent.com/45024598/168776175-f573d74c-c9b5-4cc6-9a09-76bc281ca534.png)

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/45024598/168776328-94ecd172-c727-4db2-9313-51e4443dfaf8.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by tianliang0913** [comment]
![image](https://user-images.githubusercontent.com/45024598/168938265-1fe0b19a-09b4-4c66-8562-4cedb5aa7a72.png)

**Comment by lvdandan16** [comment]
参考文档: http://report.jeecg.com/2020177
![image](https://user-images.githubusercontent.com/54099258/169504515-51750e0c-55cd-447e-b2de-04738c7d61e2.png)

**Comment by yiyang74262580** [comment]
@lvdandan16 大佬，怎么解决的啊

**Comment by yiyang74262580** [comment]
我把我们自定义的jimuresult换成JSONObject返回就好了
